CREATE TABLE `DIGITAALBESTAND` (
    `DIGITAALBESTAND_ID` INT PRIMARY KEY,
        `BLOB` VARCHAR(255),
        `MIMETYPE` VARCHAR(20),
        `NAAM` VARCHAR(80),
        `OMSCHRIJVING` TEXT
) ENGINE=InnoDB;

CREATE TABLE `DOCUMENT` (
    `DOCUMENT_ID` INT PRIMARY KEY,
        `COCUMENTBESCHRIJVING` VARCHAR(255),
        `DATUMCREATIEDOCUMENT` DATE,
        `DATUMONTVANGSTDOCUMENT` DATE,
        `DATUMVERZENDINGDOCUMENT` DATE,
        `DOCUMENTAUTEUR` VARCHAR(200),
        `DOCUMENTIDENTIFICATIE` VARCHAR(255),
        `DOCUMENTTITEL` VARCHAR(200),
        `VERTROUWELIJKAANDUIDING` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `PLANK` (
    `PLANK_ID` INT PRIMARY KEY,
        `PLANKNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `KAST` (
    `KAST_ID` INT PRIMARY KEY,
        `HEEFT_PLANK_ID` INT,
        `KASTNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `STELLING` (
    `STELLING_ID` INT PRIMARY KEY,
        `HEEFT_KAST_ID` INT,
        `STELLINGNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `DEPOT` (
    `DEPOT_ID` INT PRIMARY KEY,
        `HEEFT_STELLING_ID` INT,
        `NAAM` VARCHAR(80),
        `OMSCHRIJVING` TEXT
) ENGINE=InnoDB;

CREATE TABLE `UITGEVER` (
    `UITGEVER_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `VINDPLAATS` (
    `VINDPLAATS_ID` INT PRIMARY KEY,
        `IS_TE_VINDEN_IN_DEPOT_ID` INT,
        `IS_TE_VINDEN_IN_KAST_ID` INT,
        `IS_TE_VINDEN_IN_PLANK_ID` INT,
        `IS_TE_VINDEN_IN_STELLING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `ARCHIEFSTUK` (
    `DOCUMENT_ID` INT PRIMARY KEY,
        `BESCHRIJVING` TEXT,
        `HEEFT_DIGITAALBESTAND_ID` INT,
        `HEEFT_UITGEVER_ID` INT,
        `HEEFT_VINDPLAATS_ID` INT,
        `INVENTARISNUMMER` VARCHAR(20),
        `OMVANG` VARCHAR(255),
        `OPENBAARHEIDSBEPERKING` BOOLEAN,
        `TREFWOORDEN` VARCHAR(200),
        `UITERLIJKEVORM` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `ARCHIEFSTUK` ADD CONSTRAINT FK_ARCHIEFSTUK_GEN_DOCUMENT FOREIGN KEY (`DOCUMENT_ID`) REFERENCES `DOCUMENT` (`DOCUMENT_ID`);
-- Generalization to DOCUMENT

ALTER TABLE `ARCHIEFSTUK` ADD CONSTRAINT FK_ARCHIEFSTUK_HEEFT FOREIGN KEY (`HEEFT_VINDPLAATS_ID`) REFERENCES `VINDPLAATS` (`VINDPLAATS_ID`);
-- HEEFT (0..* to 1, Connector_ID: 1174)

ALTER TABLE `ARCHIEFSTUK` ADD CONSTRAINT FK_ARCHIEFSTUK_HEEFT_2 FOREIGN KEY (`HEEFT_UITGEVER_ID`) REFERENCES `UITGEVER` (`UITGEVER_ID`);
-- HEEFT (0..* to 0..1, Connector_ID: 1175)

ALTER TABLE `ARCHIEFSTUK` ADD CONSTRAINT FK_ARCHIEFSTUK_HEEFT_3 FOREIGN KEY (`HEEFT_DIGITAALBESTAND_ID`) REFERENCES `DIGITAALBESTAND` (`DIGITAALBESTAND_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 1176)

ALTER TABLE `DEPOT` ADD CONSTRAINT FK_DEPOT_HEEFT FOREIGN KEY (`HEEFT_STELLING_ID`) REFERENCES `STELLING` (`STELLING_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 1167)

ALTER TABLE `KAST` ADD CONSTRAINT FK_KAST_HEEFT FOREIGN KEY (`HEEFT_PLANK_ID`) REFERENCES `PLANK` (`PLANK_ID`);
-- HEEFT (0..1 to 0..*, Connector_ID: 1163)

ALTER TABLE `STELLING` ADD CONSTRAINT FK_STELLING_HEEFT FOREIGN KEY (`HEEFT_KAST_ID`) REFERENCES `KAST` (`KAST_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 1161)

ALTER TABLE `VINDPLAATS` ADD CONSTRAINT FK_VINDPLAATS_IS_TE_VINDEN_IN FOREIGN KEY (`IS_TE_VINDEN_IN_STELLING_ID`) REFERENCES `STELLING` (`STELLING_ID`);
-- IS_TE_VINDEN_IN (0..* to 0..1, Connector_ID: 1158)

ALTER TABLE `VINDPLAATS` ADD CONSTRAINT FK_VINDPLAATS_IS_TE_VINDEN_IN_2 FOREIGN KEY (`IS_TE_VINDEN_IN_PLANK_ID`) REFERENCES `PLANK` (`PLANK_ID`);
-- IS_TE_VINDEN_IN (0..* to 1, Connector_ID: 1160)

ALTER TABLE `VINDPLAATS` ADD CONSTRAINT FK_VINDPLAATS_IS_TE_VINDEN_IN_3 FOREIGN KEY (`IS_TE_VINDEN_IN_KAST_ID`) REFERENCES `KAST` (`KAST_ID`);
-- IS_TE_VINDEN_IN (0..* to 1, Connector_ID: 1162)

ALTER TABLE `VINDPLAATS` ADD CONSTRAINT FK_VINDPLAATS_IS_TE_VINDEN_IN_4 FOREIGN KEY (`IS_TE_VINDEN_IN_DEPOT_ID`) REFERENCES `DEPOT` (`DEPOT_ID`);
-- IS_TE_VINDEN_IN (0..* to 1, Connector_ID: 1166)

