CREATE TABLE DOCUMENTTYPE (
    DOCUMENTTYPE_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDDOCUMENTTYPE DATE,
        DATUMEINDEGELDIGHEIDDOCUMENTTYPE DATE,
        DOCUMENTCATEGORIE VARCHAR(80),
        DOCUMENTTYPEOMSCHRIJVING VARCHAR(80),
        DOCUMENTTYPEOMSCHRIJVINGGENERIEK VARCHAR(80),
        DOCUMENTTYPETREFWOORD VARCHAR(255)
);

CREATE TABLE IDENTIFICATIEKENMERK (
    IDENTIFICATIEKENMERK_ID VARCHAR(255) PRIMARY KEY,
        KENMERK VARCHAR(20)
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR(200),
        DOCUMENTIDENTIFICATIE VARCHAR(255),
        DOCUMENTTITEL VARCHAR(200),
        HEEFT_KENMERK_IDENTIFICATIEKENMERK_ID VARCHAR(255),
        IS_VAN_DOCUMENTTYPE_ID VARCHAR(255),
        VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR(255),
        ADRESBUITENLAND VARCHAR(255),
        ADRESCORRESPONDENTIE VARCHAR(100),
        EMAILADRES VARCHAR(80),
        FAXNUMMER VARCHAR(20),
        IDENTIFICATIE VARCHAR(255),
        KVKNUMMER VARCHAR(20),
        NAAM VARCHAR(200),
        RECHTSVORM VARCHAR(100),
        REKENINGNUMMER VARCHAR(255),
        TELEFOONNUMMER VARCHAR(20)
);

CREATE TABLE BEZOEKER (
    RECHTSPERSOON_ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE NATUURLIJKPERSOON (
    RECHTSPERSOON_ID VARCHAR(255) PRIMARY KEY,
        AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON VARCHAR(50),
        AANDUIDINGNAAMGEBRUIK VARCHAR(50),
        AANHEFAANSCHRIJVING VARCHAR(50),
        ACADEMISCHETITEL VARCHAR(80),
        ACHTERNAAM VARCHAR(100),
        ADELLIJKETITELOFPREDIKAAT VARCHAR(255),
        ANUMMER VARCHAR(20),
        ATTRIBUTE VARCHAR(255),
        BURGERSERVICENUMMER VARCHAR(255),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        GEBOORTELAND VARCHAR(255),
        GEBOORTEPLAATS VARCHAR(200),
        GESLACHTSAANDUIDING VARCHAR(255),
        GESLACHTSNAAM VARCHAR(200),
        GESLACHTSNAAMAANSCHRIJVING VARCHAR(200),
        HANDLICHTING VARCHAR(50),
        INDICATIEAFSCHERMINGPERSOONSGEGEVENS BOOLEAN,
        INDICATIEOVERLEDEN BOOLEAN,
        LANDOVERLIJDEN VARCHAR(255),
        NATIONALITEIT VARCHAR(100),
        OVERLIJDENSPLAATS VARCHAR(200),
        VOORLETTERSAANSCHRIJVING VARCHAR(20),
        VOORNAMEN VARCHAR(200),
        VOORNAMENAANSCHRIJVING VARCHAR(200),
        VOORVOEGSELGESLACHTSNAAM VARCHAR(80)
);

CREATE TABLE RECHTHEBBENDE (
    RECHTSPERSOON_ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE UITGEVER (
    RECHTSPERSOON_ID VARCHAR(255) PRIMARY KEY
);

ALTER TABLE BEZOEKER ADD CONSTRAINT FK_BEZOEKER_GEN_NATUURLIJKPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE RECHTHEBBENDE ADD CONSTRAINT FK_RECHTHEBBENDE_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE UITGEVER ADD CONSTRAINT FK_UITGEVER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_HEEFT_KENMERK FOREIGN KEY (HEEFT_KENMERK_IDENTIFICATIEKENMERK_ID) REFERENCES IDENTIFICATIEKENMERK (IDENTIFICATIEKENMERK_ID);
-- HEEFT_KENMERK (0..* to 1, Connector_ID: 283)

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_IS_VAN FOREIGN KEY (IS_VAN_DOCUMENTTYPE_ID) REFERENCES DOCUMENTTYPE (DOCUMENTTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 282)

