CREATE TABLE TYPERINGOPENBARERUIMTE_ENUM (
    TYPERINGOPENBARERUIMTE_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (1, 'ADMINISTRATIEF_GEBIED');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (2, 'FUNCTIONEEL_GEBIED');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (3, 'KUNSTWERK');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (4, 'LANDSCHAPPELIJK_GEBIED');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (5, 'LEEG');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (6, 'ONBEKEND');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (7, 'SPOORBAAN');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (8, 'TERREIN');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (9, 'WATER');
INSERT INTO TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (10, 'WEG');

CREATE TABLE VERBLIJFSOBJECT (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    AANTALKAMERS VARCHAR2(255),
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GEBRUIKSDOEL_ENUM_ID NUMBER,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    HOOGSTEBOUWLAAG VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LAAGSTEBOUWLAAG VARCHAR2(255),
    ONTSLUITINGVERDIEPING_ENUM_ID NUMBER,
    OPPERVLAKTE NUMBER,
    SOORTWOONOBJECT_ENUM_ID NUMBER,
    STATUS_ENUM_ID NUMBER,
    TOEGANGBOUWLAAG VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDEGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    HEEFT_ALS_NEVENADRES_ADRESSEERBAAROBJECT_ID NUMBER,
    HUISLETTER VARCHAR2(255),
    HUISNUMMER VARCHAR2(255),
    HUISNUMMERTOEVOEGING VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LIGT_AAN_OPENBARERUIMTE_ID NUMBER,
    LIGT_IN_BUURT_ID NUMBER,
    LIGT_IN_WOONPLAATS_ID NUMBER,
    POSTCODE VARCHAR2(255),
    STATUS_ENUM_ID NUMBER,
    TYPEADRESSEERBAAROBJECT_ENUM_ID NUMBER,
    VERSIE NUMBER
);

CREATE TABLE GEBRUIKSDOEL_ENUM (
    GEBRUIKSDOEL_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (1, 'BIJEENKOMSTFUNCTIE');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (2, 'CELFUNCTIE_');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (3, 'GEZONDHEIDSZORGFUNCTIE');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (4, 'INDUSTRIEFUNCTIE');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (5, 'KANTOORFUNCTIE');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (6, 'LEEG');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (7, 'LOGIESFUNCTIE');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (8, 'ONBEKEND');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (9, 'ONDERWIJSFUNCTIE_');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (10, 'OVERIGE_GEBRUIKSFUNCTIE_');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (11, 'SPORTFUNCTIE_');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (12, 'WINKELFUNCTIE_');
INSERT INTO GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID, VALUE) VALUES (13, 'WOONFUNCTIE_');

CREATE TABLE STATUSOPENBARERUIMTE_ENUM (
    STATUSOPENBARERUIMTE_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO STATUSOPENBARERUIMTE_ENUM (STATUSOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO STATUSOPENBARERUIMTE_ENUM (STATUSOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (2, 'NAAMGEVING_INGETROKKEN');
INSERT INTO STATUSOPENBARERUIMTE_ENUM (STATUSOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (3, 'NAAMGEVING_UITGEGEVEN');
INSERT INTO STATUSOPENBARERUIMTE_ENUM (STATUSOPENBARERUIMTE_ENUM_ID, VALUE) VALUES (4, 'ONBEKEND');

CREATE TABLE STATUSWOONPLAATS_ENUM (
    STATUSWOONPLAATS_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO STATUSWOONPLAATS_ENUM (STATUSWOONPLAATS_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO STATUSWOONPLAATS_ENUM (STATUSWOONPLAATS_ENUM_ID, VALUE) VALUES (2, 'ONBEKEND');
INSERT INTO STATUSWOONPLAATS_ENUM (STATUSWOONPLAATS_ENUM_ID, VALUE) VALUES (3, 'WOONPLAATS_AANGEWEZEN');
INSERT INTO STATUSWOONPLAATS_ENUM (STATUSWOONPLAATS_ENUM_ID, VALUE) VALUES (4, 'WOONPLAATS_INGETROKKEN_');

CREATE TABLE STATUSPAND_ENUM (
    STATUSPAND_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (1, 'BOUWAANVRAAG_ONTVANGEN');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (2, 'BOUWVERGUNNING_VERLEEND');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (3, 'BOUW_GESTART');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (4, 'LEEG');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (5, 'NIET_GEREALISEERD_PAND');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (6, 'ONBEKEND');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (7, 'PAND_BUITEN_GEBRUIK');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (8, 'PAND_GESLOOPT');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (9, 'PAND_IN_GEBRUIK');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (10, 'PAND_IN_GEBRUIK_NIET_INGEMETEN_');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (11, 'PAND_TEN_ONRECHTE_OPGEVOERD');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (12, 'SLOOPVERGUNNING_VERLEEND');
INSERT INTO STATUSPAND_ENUM (STATUSPAND_ENUM_ID, VALUE) VALUES (13, 'VERBOUWING_PAND');

CREATE TABLE STATUSNUMMERAANDUIDING_ENUM (
    STATUSNUMMERAANDUIDING_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO STATUSNUMMERAANDUIDING_ENUM (STATUSNUMMERAANDUIDING_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO STATUSNUMMERAANDUIDING_ENUM (STATUSNUMMERAANDUIDING_ENUM_ID, VALUE) VALUES (2, 'NAAMGEVING_INGETROKKEN');
INSERT INTO STATUSNUMMERAANDUIDING_ENUM (STATUSNUMMERAANDUIDING_ENUM_ID, VALUE) VALUES (3, 'NAAMGEVING_UITGEGEVEN');
INSERT INTO STATUSNUMMERAANDUIDING_ENUM (STATUSNUMMERAANDUIDING_ENUM_ID, VALUE) VALUES (4, 'ONBEKEND');

CREATE TABLE TYPEADRESSEERBAAROBJECT_ENUM (
    TYPEADRESSEERBAAROBJECT_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO TYPEADRESSEERBAAROBJECT_ENUM (TYPEADRESSEERBAAROBJECT_ENUM_ID, VALUE) VALUES (1, 'LIGPLAATS');
INSERT INTO TYPEADRESSEERBAAROBJECT_ENUM (TYPEADRESSEERBAAROBJECT_ENUM_ID, VALUE) VALUES (2, 'STANDPLAATS');
INSERT INTO TYPEADRESSEERBAAROBJECT_ENUM (TYPEADRESSEERBAAROBJECT_ENUM_ID, VALUE) VALUES (3, 'VERBLIJFSOBJECT');

CREATE TABLE STATUSSTANDPLAATS_ENUM (
    STATUSSTANDPLAATS_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO STATUSSTANDPLAATS_ENUM (STATUSSTANDPLAATS_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO STATUSSTANDPLAATS_ENUM (STATUSSTANDPLAATS_ENUM_ID, VALUE) VALUES (2, 'ONBEKEND');
INSERT INTO STATUSSTANDPLAATS_ENUM (STATUSSTANDPLAATS_ENUM_ID, VALUE) VALUES (3, 'PLAATS_AANGEWEZEN');
INSERT INTO STATUSSTANDPLAATS_ENUM (STATUSSTANDPLAATS_ENUM_ID, VALUE) VALUES (4, 'PLAATS_INGETROKKEN');

CREATE TABLE WOONPLAATS (
    WOONPLAATS_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    EINDREGISTRATIE DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    LIGT_IN_GEMEENTE_ID NUMBER,
    STATUS_ENUM_ID NUMBER,
    TIJDSTIPACTIEF TIMESTAMP,
    TIJDSTIPREGISTRATIE TIMESTAMP,
    VERSIE NUMBER,
    VOORKOMEN DATE,
    WOONPLAATSNAAM VARCHAR2(80),
    WOONPLAATSNAAMNEN VARCHAR2(255)
);

CREATE TABLE STATUSVERBLIJFSOBJECT_ENUM (
    STATUSVERBLIJFSOBJECT_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (2, 'NIET_GEREALISEERD_VERBLIJFSOBJECT');
INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (3, 'ONBEKEND');
INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (4, 'VERBLIJFSOBJECT_BUITEN_GEBRUIK');
INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (5, 'VERBLIJFSOBJECT_GEVORMD');
INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (6, 'VERBLIJFSOBJECT_INGETROKKEN');
INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (7, 'VERBLIJFSOBJECT_IN_GEBRUIK');
INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (8, 'VERBLIJFSOBJECT_IN_GEBRUIK_NIET_INGEMETEN_');
INSERT INTO STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID, VALUE) VALUES (9, 'VERBLIJFSOBJECT_VERBOUWING');

CREATE TABLE BUURT (
    BUURT_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    CODE VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    LIGT_IN_OPENBARERUIMTE_ID NUMBER,
    LIGT_IN_WIJK_ID NUMBER,
    NAAM VARCHAR2(255),
    STATUS_ENUM_ID NUMBER,
    VERSIE NUMBER
);

CREATE TABLE BOOLEAN_ENUM (
    BOOLEAN_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (1, 'JA');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (2, 'LEEG');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (3, 'NEE');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (4, 'ONBEKEND');

CREATE TABLE OPENBARERUIMTE (
    OPENBARERUIMTE_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS VARCHAR2(255),
    HUISNUMMERRANGE_EVEN_NUMMERS VARCHAR2(255),
    HUISNUMMERRANGE_ONEVEN_NUMMERS VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LABELNAAM VARCHAR2(80),
    LIGT_IN_WOONPLAATS_ID NUMBER,
    NAAMOPENBARERUIMTE VARCHAR2(80),
    STATUS_ENUM_ID NUMBER,
    STRAATCODE VARCHAR2(80),
    STRAATNAAM VARCHAR2(255),
    TYPEOPENBARERUIMTE_ENUM_ID NUMBER,
    VERSIE NUMBER,
    WEGSEGMENT VARCHAR2(255)
);

CREATE TABLE SOORTWOONOBJECT_ENUM (
    SOORTWOONOBJECT_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO SOORTWOONOBJECT_ENUM (SOORTWOONOBJECT_ENUM_ID, VALUE) VALUES (1, 'BIJZONDER_WOONGEBOUW');
INSERT INTO SOORTWOONOBJECT_ENUM (SOORTWOONOBJECT_ENUM_ID, VALUE) VALUES (2, 'LEEG');
INSERT INTO SOORTWOONOBJECT_ENUM (SOORTWOONOBJECT_ENUM_ID, VALUE) VALUES (3, 'ONBEKEND');
INSERT INTO SOORTWOONOBJECT_ENUM (SOORTWOONOBJECT_ENUM_ID, VALUE) VALUES (4, 'OVERIG_WOONVERBLIJF');
INSERT INTO SOORTWOONOBJECT_ENUM (SOORTWOONOBJECT_ENUM_ID, VALUE) VALUES (5, 'RECREATIEWONING');
INSERT INTO SOORTWOONOBJECT_ENUM (SOORTWOONOBJECT_ENUM_ID, VALUE) VALUES (6, 'WONING');
INSERT INTO SOORTWOONOBJECT_ENUM (SOORTWOONOBJECT_ENUM_ID, VALUE) VALUES (7, 'WOONEENHEID');

CREATE TABLE KP_STNDPLTS_ADRSSRBRBJCT (
    KP_STNDPLTS_ADRSSRBRBJCT_ID NUMBER PRIMARY KEY,
    STANDPLAATS_ID NUMBER,
    ADRESSEERBAAROBJECT_ID NUMBER
);

CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID NUMBER,
    IDENTIFICATIE VARCHAR2(255),
    TYPEADRESSEERBAAROBJECT_ENUM_ID NUMBER,
    VERSIE NUMBER
);

CREATE TABLE STANDPLAATS (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    STATUS_ENUM_ID NUMBER,
    VERSIE NUMBER
);

CREATE TABLE STATUSLIGPLAATS_ENUM (
    STATUSLIGPLAATS_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO STATUSLIGPLAATS_ENUM (STATUSLIGPLAATS_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO STATUSLIGPLAATS_ENUM (STATUSLIGPLAATS_ENUM_ID, VALUE) VALUES (2, 'ONBEKEND');
INSERT INTO STATUSLIGPLAATS_ENUM (STATUSLIGPLAATS_ENUM_ID, VALUE) VALUES (3, 'PLAATS_AANGEWEZEN');
INSERT INTO STATUSLIGPLAATS_ENUM (STATUSLIGPLAATS_ENUM_ID, VALUE) VALUES (4, 'PLAATS_INGETROKKEN');

CREATE TABLE KP_VRBLJFSBJCT_ADRSSRBRBJCT (
    KP_VRBLJFSBJCT_ADRSSRBRBJCT_ID NUMBER PRIMARY KEY,
    VERBLIJFSOBJECT_ID NUMBER,
    ADRESSEERBAAROBJECT_ID NUMBER
);

CREATE TABLE KP_LGPLTS_ADRSSRBRBJCT (
    KP_LGPLTS_ADRSSRBRBJCT_ID NUMBER PRIMARY KEY,
    LIGPLAATS_ID NUMBER,
    ADRESSEERBAAROBJECT_ID NUMBER
);

CREATE TABLE LIGPLAATS (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    STATUS_ENUM_ID NUMBER,
    VERSIE VARCHAR2(255)
);

CREATE TABLE PAND (
    PAND_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    BRUTOINHOUDPAND VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER VARCHAR2(255),
    EINDGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIEBOVENAANZICHT SDO_GEOMETRY,
    GEOMETRIEMAAIVELD SDO_GEOMETRY,
    GEOMETRIEPUNT SDO_GEOMETRY,
    HOOGSTEBOUWLAAG VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LAAGSTEBOUWLAAG VARCHAR2(255),
    OORSPRONKELIJKBOUWJAAR VARCHAR2(255),
    OPPERVLAKTE VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUSVOORTGANGBOUW_ENUM_ID NUMBER,
    STATUS_ENUM_ID NUMBER,
    VERSIE NUMBER,
    ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_ID NUMBER
);

CREATE TABLE GEMEENTE (
    GEMEENTE_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEMEENTECODE VARCHAR2(255),
    GEMEENTENAAM VARCHAR2(80),
    GEMEENTENAAM_NEN VARCHAR2(255),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE WIJK (
    WIJK_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    LIGT_IN_WOONPLAATS_ID NUMBER,
    STATUS_ENUM_ID NUMBER,
    VERSIE NUMBER,
    WIJKCODE VARCHAR2(255),
    WIJKNAAM VARCHAR2(255)
);

CREATE TABLE ONTSLUITINGSWIJZEVERDIEPING_ENUM (
    ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO ONTSLUITINGSWIJZEVERDIEPING_ENUM (ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO ONTSLUITINGSWIJZEVERDIEPING_ENUM (ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID, VALUE) VALUES (2, 'LIFT');
INSERT INTO ONTSLUITINGSWIJZEVERDIEPING_ENUM (ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID, VALUE) VALUES (3, 'ONBEKEND');
INSERT INTO ONTSLUITINGSWIJZEVERDIEPING_ENUM (ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID, VALUE) VALUES (4, 'ROLTRAP');
INSERT INTO ONTSLUITINGSWIJZEVERDIEPING_ENUM (ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID, VALUE) VALUES (5, 'TRAP');

CREATE TABLE KP_VRBLJFSBJCT_PND (
    KP_VRBLJFSBJCT_PND_ID NUMBER PRIMARY KEY,
    VERBLIJFSOBJECT_ID NUMBER,
    PAND_ID NUMBER
);

CREATE TABLE KP_GMNT_IS_OVRGGN_IN (
    KP_GMNT_IS_OVRGGN_IN_ID NUMBER PRIMARY KEY,
    IS_OVERGEGAAN_IN_1_ID NUMBER,
    IS_OVERGEGAAN_IN_2_ID NUMBER
);

CREATE TABLE STATUSVOORTGANGBOUW_ENUM (
    STATUSVOORTGANGBOUW_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (2, 'NIEUWBOUWVERGUNNING_INGETROKKEN');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (3, 'NIEUWBOUWVERGUNNING_VERLEEND');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (4, 'NIEUWBOUW_GEREED');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (5, 'NIEUWBOUW_GESTART');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (6, 'ONBEKEND');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (7, 'SLOOPVERGUNNING_INGETROKKEN');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (8, 'SLOOPVERGUNNING_VERLEEND');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (9, 'SLOOP_GEREED');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (10, 'SLOOP_GESTART');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (11, 'VERBOUWVERGUNNING_INGETROKKEN');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (12, 'VERBOUWVERGUNNING_VERLEEND');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (13, 'VERBOUW_GEREED');
INSERT INTO STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID, VALUE) VALUES (14, 'VERBOUW_GESTART');

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE LIGPLAATS ADD CONSTRAINT FK_LIGPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE STANDPLAATS ADD CONSTRAINT FK_STANDPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE KP_GMNT_IS_OVRGGN_IN ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_1 FOREIGN KEY (IS_OVERGEGAAN_IN_1_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE KP_GMNT_IS_OVRGGN_IN ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_2 FOREIGN KEY (IS_OVERGEGAAN_IN_2_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE KP_STNDPLTS_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_STNDPLTS_ADRSSRBRBJCT_1 FOREIGN KEY (STANDPLAATS_ID) REFERENCES STANDPLAATS (ADRESSEERBAAROBJECT_ID);
-- STANDPLAATS (many-to-many junction, Connector_ID: 2252)

ALTER TABLE KP_STNDPLTS_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_STNDPLTS_ADRSSRBRBJCT_2 FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2252)

ALTER TABLE KP_LGPLTS_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_LGPLTS_ADRSSRBRBJCT_1 FOREIGN KEY (LIGPLAATS_ID) REFERENCES LIGPLAATS (ADRESSEERBAAROBJECT_ID);
-- LIGPLAATS (many-to-many junction, Connector_ID: 2253)

ALTER TABLE KP_LGPLTS_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_LGPLTS_ADRSSRBRBJCT_2 FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2253)

ALTER TABLE KP_VRBLJFSBJCT_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_VRBLJFSBJCT_ADRSSRBRBJCT_1 FOREIGN KEY (VERBLIJFSOBJECT_ID) REFERENCES VERBLIJFSOBJECT (ADRESSEERBAAROBJECT_ID);
-- VERBLIJFSOBJECT (many-to-many junction, Connector_ID: 2262)

ALTER TABLE KP_VRBLJFSBJCT_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_VRBLJFSBJCT_ADRSSRBRBJCT_2 FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2262)

ALTER TABLE KP_VRBLJFSBJCT_PND ADD CONSTRAINT FK_KP_VRBLJFSBJCT_PND_1 FOREIGN KEY (VERBLIJFSOBJECT_ID) REFERENCES VERBLIJFSOBJECT (ADRESSEERBAAROBJECT_ID);
-- VERBLIJFSOBJECT (many-to-many junction, Connector_ID: 2305)

ALTER TABLE KP_VRBLJFSBJCT_PND ADD CONSTRAINT FK_KP_VRBLJFSBJCT_PND_2 FOREIGN KEY (PAND_ID) REFERENCES PAND (PAND_ID);
-- PAND (many-to-many junction, Connector_ID: 2305)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_LIGT_IN FOREIGN KEY (LIGT_IN_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- LIGT_IN (1 to 1..*, Connector_ID: 2264)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_IN FOREIGN KEY (LIGT_IN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- LIGT_IN (1 to 1, Connector_ID: 2272)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY (LIGT_AAN_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- LIGT_AAN (0..* to 1, Connector_ID: 2281)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_IN_2 FOREIGN KEY (LIGT_IN_WOONPLAATS_ID) REFERENCES WOONPLAATS (WOONPLAATS_ID);
-- LIGT_IN (0..* to 0..1, Connector_ID: 2283)

ALTER TABLE OPENBARERUIMTE ADD CONSTRAINT FK_OPENBARERUIMTE_LIGT_IN FOREIGN KEY (LIGT_IN_WOONPLAATS_ID) REFERENCES WOONPLAATS (WOONPLAATS_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 2288)

ALTER TABLE WOONPLAATS ADD CONSTRAINT FK_WOONPLAATS_LIGT_IN FOREIGN KEY (LIGT_IN_GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- LIGT_IN (1..* to 1.., Connector_ID: 2290)

ALTER TABLE WIJK ADD CONSTRAINT FK_WIJK_LIGT_IN FOREIGN KEY (LIGT_IN_WOONPLAATS_ID) REFERENCES WOONPLAATS (WOONPLAATS_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 2294)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_LIGT_IN_2 FOREIGN KEY (LIGT_IN_WIJK_ID) REFERENCES WIJK (WIJK_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 2297)

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_ZONDER_VERBLIJFSOBJECT_LIGT_IN FOREIGN KEY (ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- ZONDER_VERBLIJFSOBJECT_LIGT_IN (0..* to 0..1, Connector_ID: 2300)

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_STATUSVOORTGANGBOUW_ENUM_ID FOREIGN KEY (STATUSVOORTGANGBOUW_ENUM_ID_STATUSVOORTGANGBOUW_ENUM_ID) REFERENCES STATUSVOORTGANGBOUW_ENUM (STATUSVOORTGANGBOUW_ENUM_ID);
-- STATUSVOORTGANGBOUW_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSPAND_ENUM_ID) REFERENCES STATUSPAND_ENUM (STATUSPAND_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE WIJK ADD CONSTRAINT FK_WIJK_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSOPENBARERUIMTE_ENUM_ID) REFERENCES STATUSOPENBARERUIMTE_ENUM (STATUSOPENBARERUIMTE_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE WIJK ADD CONSTRAINT FK_WIJK_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE WOONPLAATS ADD CONSTRAINT FK_WOONPLAATS_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSWOONPLAATS_ENUM_ID) REFERENCES STATUSWOONPLAATS_ENUM (STATUSWOONPLAATS_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE WOONPLAATS ADD CONSTRAINT FK_WOONPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSNUMMERAANDUIDING_ENUM_ID) REFERENCES STATUSNUMMERAANDUIDING_ENUM (STATUSNUMMERAANDUIDING_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_TYPEADRESSEERBAAROBJECT_ENUM_ID FOREIGN KEY (TYPEADRESSEERBAAROBJECT_ENUM_ID_TYPEADRESSEERBAAROBJECT_ENUM_ID) REFERENCES TYPEADRESSEERBAAROBJECT_ENUM (TYPEADRESSEERBAAROBJECT_ENUM_ID);
-- TYPEADRESSEERBAAROBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSOPENBARERUIMTE_ENUM_ID) REFERENCES STATUSOPENBARERUIMTE_ENUM (STATUSOPENBARERUIMTE_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSVERBLIJFSOBJECT_ENUM_ID) REFERENCES STATUSVERBLIJFSOBJECT_ENUM (STATUSVERBLIJFSOBJECT_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEBRUIKSDOEL_ENUM_ID FOREIGN KEY (GEBRUIKSDOEL_ENUM_ID_GEBRUIKSDOEL_ENUM_ID) REFERENCES GEBRUIKSDOEL_ENUM (GEBRUIKSDOEL_ENUM_ID);
-- GEBRUIKSDOEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_SOORTWOONOBJECT_ENUM_ID FOREIGN KEY (SOORTWOONOBJECT_ENUM_ID_SOORTWOONOBJECT_ENUM_ID) REFERENCES SOORTWOONOBJECT_ENUM (SOORTWOONOBJECT_ENUM_ID);
-- SOORTWOONOBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_ONTSLUITINGVERDIEPING_ENUM_ID FOREIGN KEY (ONTSLUITINGVERDIEPING_ENUM_ID_ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID) REFERENCES ONTSLUITINGSWIJZEVERDIEPING_ENUM (ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID);
-- ONTSLUITINGVERDIEPING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE LIGPLAATS ADD CONSTRAINT FK_LIGPLAATS_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSLIGPLAATS_ENUM_ID) REFERENCES STATUSLIGPLAATS_ENUM (STATUSLIGPLAATS_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE LIGPLAATS ADD CONSTRAINT FK_LIGPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE STANDPLAATS ADD CONSTRAINT FK_STANDPLAATS_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSSTANDPLAATS_ENUM_ID) REFERENCES STATUSSTANDPLAATS_ENUM (STATUSSTANDPLAATS_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE STANDPLAATS ADD CONSTRAINT FK_STANDPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_TYPEADRESSEERBAAROBJECT_ENUM_ID FOREIGN KEY (TYPEADRESSEERBAAROBJECT_ENUM_ID_TYPEADRESSEERBAAROBJECT_ENUM_ID) REFERENCES TYPEADRESSEERBAAROBJECT_ENUM (TYPEADRESSEERBAAROBJECT_ENUM_ID);
-- TYPEADRESSEERBAAROBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPENBARERUIMTE ADD CONSTRAINT FK_OPENBARERUIMTE_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID_STATUSOPENBARERUIMTE_ENUM_ID) REFERENCES STATUSOPENBARERUIMTE_ENUM (STATUSOPENBARERUIMTE_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPENBARERUIMTE ADD CONSTRAINT FK_OPENBARERUIMTE_TYPEOPENBARERUIMTE_ENUM_ID FOREIGN KEY (TYPEOPENBARERUIMTE_ENUM_ID_TYPERINGOPENBARERUIMTE_ENUM_ID) REFERENCES TYPERINGOPENBARERUIMTE_ENUM (TYPERINGOPENBARERUIMTE_ENUM_ID);
-- TYPEOPENBARERUIMTE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPENBARERUIMTE ADD CONSTRAINT FK_OPENBARERUIMTE_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE GEMEENTE ADD CONSTRAINT FK_GEMEENTE_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

