CREATE TABLE ARCHEOLOGIEBESLUIT (
    ARCHEOLOGIEBESLUIT_ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE ARTEFACT (
    ARTEFACT_ID VARCHAR(255) PRIMARY KEY,
        ARTEFECTNUMMER VARCHAR(20),
        BESCHRIJVING TEXT,
        CONSERVEREN BOOLEAN,
        DATERING VARCHAR(255),
        DATERINGCOMPLEX VARCHAR(20),
        DETERMINATIENIVEAU VARCHAR(255),
        DIANUMMER VARCHAR(200),
        DOOSNUMMER VARCHAR(255),
        EXPOSABEL BOOLEAN,
        FOTONUMMER VARCHAR(200),
        FUNCTIE VARCHAR(80),
        HERKOMST VARCHAR(80),
        IS_VAN_SOORT_ARTEFACTSOORT_ID VARCHAR(255),
        KEY VARCHAR(255),
        KEYDOOS VARCHAR(255),
        KEYMAGAZIJNPLAATSING VARCHAR(255),
        KEYPUT VARCHAR(255),
        KEYVONDST VARCHAR(255),
        LITERATUUR VARCHAR(200),
        MATEN VARCHAR(80),
        NAAM VARCHAR(255),
        OPMERKINGEN TEXT,
        ORIGINE VARCHAR(80),
        PROJECTCD VARCHAR(20),
        PUTNUMMER VARCHAR(20),
        RESTAURATIEWENSELIJK BOOLEAN,
        TEKENINGNUMMER VARCHAR(200),
        TYPE VARCHAR(80),
        VINDBAAR_OP_MAGAZIJNPLAATSING_ID VARCHAR(255),
        VONDSTNUMMER VARCHAR(20),
        ZIT_IN_DOOS_ID VARCHAR(255)
);

CREATE TABLE ARTEFACTSOORT (
    ARTEFACTSOORT_ID VARCHAR(255) PRIMARY KEY,
        CODE VARCHAR(255),
        NAAM VARCHAR(200),
        OMSCHRIJVING TEXT
);

CREATE TABLE BORING (
    BORING_ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR(200),
        DOCUMENTIDENTIFICATIE VARCHAR(255),
        DOCUMENTTITEL VARCHAR(200),
        VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE DOOS (
    DOOS_ID VARCHAR(255) PRIMARY KEY,
        DOOSNUMMER VARCHAR(255),
        HERKOMST VARCHAR(200),
        INHOUD TEXT,
        KEY VARCHAR(255),
        KEYMAGAZIJNLOCATIE VARCHAR(255),
        PROJECTCD VARCHAR(255),
        STAAT_OP_MAGAZIJNLOCATIE_ID VARCHAR(255)
);

CREATE TABLE KAART (
    KAART_ID VARCHAR(255) PRIMARY KEY,
        KAART VARCHAR(255),
        NAAM VARCHAR(200),
        OMSCHRIJVING TEXT
);

CREATE TABLE KP_PRJCT_LCT (
    KP_PRJCT_LCT_ID VARCHAR(255) PRIMARY KEY,
    PROJECT_ID VARCHAR(255),
    LOCATIE_ID VARCHAR(255)
);

CREATE TABLE KP_PUT_LCT (
    KP_PUT_LCT_ID VARCHAR(255) PRIMARY KEY,
    PUT_ID VARCHAR(255),
    LOCATIE_ID VARCHAR(255)
);

CREATE TABLE LOCATIE (
    LOCATIE_ID VARCHAR(255) PRIMARY KEY,
        LOCATIE VARCHAR(255)
);

CREATE TABLE MAGAZIJNLOCATIE (
    MAGAZIJNLOCATIE_ID VARCHAR(255) PRIMARY KEY,
        KEY VARCHAR(20),
        STELLING VARCHAR(255),
        VAKNUMMER VARCHAR(255),
        VOLGLETTER VARCHAR(255)
);

CREATE TABLE MAGAZIJNPLAATSING (
    MAGAZIJNPLAATSING_ID VARCHAR(255) PRIMARY KEY,
        BESCHRIJVING TEXT,
        DATUMGEPLAATST DATE,
        HERKOMST VARCHAR(255),
        HOORT_BIJ_PROJECT_ID VARCHAR(255),
        KEY VARCHAR(255),
        KEYDOOS VARCHAR(255),
        KEYMAGAZIJNLOCATIE VARCHAR(255),
        PROJECTCD VARCHAR(255),
        STAAT_OP_MAGAZIJNLOCATIE_ID VARCHAR(255),
        UITGELEEND BOOLEAN,
        ZIT_IN_DOOS_ID VARCHAR(255)
);

CREATE TABLE PROJECT (
    PROJECT_ID VARCHAR(255) PRIMARY KEY,
        COORDINATEN GEOMETRY,
        DATUMEINDE DATE,
        DATUMSTART DATE,
        HEEFT_ARCHEOLOGIEBESLUIT_ID VARCHAR(255),
        HEEFT_BORING_ID VARCHAR(255),
        HEEFT_PUT_ID VARCHAR(255),
        JAARTOT VARCHAR(255),
        JAARVAN VARCHAR(255),
        LOCATIE VARCHAR(255),
        NAAM VARCHAR(80),
        NAAMCODE VARCHAR(255),
        PROJECTCD VARCHAR(255),
        TOPONIEM VARCHAR(80),
        TREFWOORDEN VARCHAR(255),
        VASTLEGGING_DOCUMENT_ID VARCHAR(255)
);

CREATE TABLE PUT (
    PUT_ID VARCHAR(255) PRIMARY KEY,
        HEEFT_VLAK_ID VARCHAR(255),
        KEY VARCHAR(255),
        PROJECTCD VARCHAR(255),
        PUTNUMMER VARCHAR(255)
);

CREATE TABLE SPOOR (
    SPOOR_ID VARCHAR(255) PRIMARY KEY,
        AARD VARCHAR(80),
        BESCHRIJVING TEXT,
        DATERING VARCHAR(20),
        DATUM DATE,
        HEEFT_VULLING_ID VARCHAR(255),
        HOOGTEBOVEN VARCHAR(20),
        HOOGTEONDER VARCHAR(20),
        KEY VARCHAR(255),
        KEYVLAK VARCHAR(255),
        PROJECTCD VARCHAR(255),
        PUTNUMMER VARCHAR(255),
        SPOORNUMMER VARCHAR(255),
        VLAKNUMMER VARCHAR(255),
        VORM VARCHAR(20)
);

CREATE TABLE STELLING (
    STELLING_ID VARCHAR(255) PRIMARY KEY,
        HEEFT_MAGAZIJNLOCATIE_ID VARCHAR(255),
        INHOUD TEXT,
        STELLINGCODE VARCHAR(255)
);

CREATE TABLE VINDPLAATS (
    VINDPLAATS_ID VARCHAR(255) PRIMARY KEY,
        AARD VARCHAR(20),
        BEGINDATERING VARCHAR(255),
        BESCHRIJVING TEXT,
        BIBLIOGRAFIE VARCHAR(200),
        DATERING VARCHAR(255),
        DEPOT VARCHAR(255),
        DOCUMENTATIE VARCHAR(200),
        EINDDATERING DATE,
        GEMEENTE VARCHAR(255),
        HOORT_BIJ_PROJECT_ID VARCHAR(255),
        LOCATIE VARCHAR(255),
        MOBILIA VARCHAR(255),
        ONDERZOEK TEXT,
        PROJECTCODE VARCHAR(20),
        VINDPLAATS VARCHAR(255)
);

CREATE TABLE VLAK (
    VLAK_ID VARCHAR(255) PRIMARY KEY,
        DIEPTETOT VARCHAR(255),
        DIEPTEVAN VARCHAR(255),
        HEEFT_SPOOR_ID VARCHAR(255),
        KEY VARCHAR(255),
        KEYPUT VARCHAR(255),
        PROJECTCD VARCHAR(20),
        PUTNUMMER VARCHAR(20),
        VLAKNUMMER VARCHAR(20)
);

CREATE TABLE VONDST (
    VONDST_ID VARCHAR(255) PRIMARY KEY,
        BEVAT_ARTEFACT_ID VARCHAR(255),
        DATUM DATE,
        KEY VARCHAR(255),
        KEYVULLING VARCHAR(255),
        OMSCHRIJVING TEXT,
        OMSTANDIGHEDEN TEXT,
        PROJECTCD VARCHAR(20),
        PUTNUMMER VARCHAR(20),
        SPOORNUMMER VARCHAR(20),
        VLAKNUMMER VARCHAR(20),
        VONDSTNUMMER VARCHAR(20),
        VULLINGNUMMER VARCHAR(20),
        XCOORDINAAT INTEGER,
        YCOORDINAAT INTEGER
);

CREATE TABLE VULLING (
    VULLING_ID VARCHAR(255) PRIMARY KEY,
        GRONDSOORT VARCHAR(80),
        HEEFT_VONDST_ID VARCHAR(255),
        KEY VARCHAR(255),
        KEYSPOOR VARCHAR(255),
        KLEUR VARCHAR(80),
        PROJECTCD VARCHAR(20),
        PUTNUMMER VARCHAR(20),
        SPOORNUMMER VARCHAR(20),
        STRUCTUUR VARCHAR(80),
        VLAKNUMMER VARCHAR(20),
        VULLINGNUMMER VARCHAR(20)
);

ALTER TABLE KP_PRJCT_LCT ADD CONSTRAINT FK_KP_PRJCT_LCT_1 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- PROJECT (many-to-many junction, Connector_ID: 1195)

ALTER TABLE KP_PRJCT_LCT ADD CONSTRAINT FK_KP_PRJCT_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 1195)

ALTER TABLE KP_PUT_LCT ADD CONSTRAINT FK_KP_PUT_LCT_1 FOREIGN KEY (PUT_ID) REFERENCES PUT (PUT_ID);
-- PUT (many-to-many junction, Connector_ID: 1196)

ALTER TABLE KP_PUT_LCT ADD CONSTRAINT FK_KP_PUT_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 1196)

ALTER TABLE ARTEFACT ADD CONSTRAINT FK_ARTEFACT_IS_VAN_SOORT FOREIGN KEY (IS_VAN_SOORT_ARTEFACTSOORT_ID) REFERENCES ARTEFACTSOORT (ARTEFACTSOORT_ID);
-- IS_VAN_SOORT (0..* to 1, Connector_ID: 1201)

ALTER TABLE ARTEFACT ADD CONSTRAINT FK_ARTEFACT_VINDBAAR_OP FOREIGN KEY (VINDBAAR_OP_MAGAZIJNPLAATSING_ID) REFERENCES MAGAZIJNPLAATSING (MAGAZIJNPLAATSING_ID);
-- VINDBAAR_OP (0..* to 0..1, Connector_ID: 1203)

ALTER TABLE ARTEFACT ADD CONSTRAINT FK_ARTEFACT_ZIT_IN FOREIGN KEY (ZIT_IN_DOOS_ID) REFERENCES DOOS (DOOS_ID);
-- ZIT_IN (0..* to 0..1, Connector_ID: 1202)

ALTER TABLE DOOS ADD CONSTRAINT FK_DOOS_STAAT_OP FOREIGN KEY (STAAT_OP_MAGAZIJNLOCATIE_ID) REFERENCES MAGAZIJNLOCATIE (MAGAZIJNLOCATIE_ID);
-- STAAT_OP (0..* to 1, Connector_ID: 1198)

ALTER TABLE MAGAZIJNPLAATSING ADD CONSTRAINT FK_MAGAZIJNPLAATSING_HOORT_BIJ FOREIGN KEY (HOORT_BIJ_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- HOORT_BIJ (0..* to 0..1, Connector_ID: 1192)

ALTER TABLE MAGAZIJNPLAATSING ADD CONSTRAINT FK_MAGAZIJNPLAATSING_STAAT_OP FOREIGN KEY (STAAT_OP_MAGAZIJNLOCATIE_ID) REFERENCES MAGAZIJNLOCATIE (MAGAZIJNLOCATIE_ID);
-- STAAT_OP (0..* to 0..1, Connector_ID: 1194)

ALTER TABLE MAGAZIJNPLAATSING ADD CONSTRAINT FK_MAGAZIJNPLAATSING_ZIT_IN FOREIGN KEY (ZIT_IN_DOOS_ID) REFERENCES DOOS (DOOS_ID);
-- ZIT_IN (0..1 to 0..*, Connector_ID: 1197)

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_HEEFT FOREIGN KEY (HEEFT_PUT_ID) REFERENCES PUT (PUT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1191)

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_HEEFT_2 FOREIGN KEY (HEEFT_BORING_ID) REFERENCES BORING (BORING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1199)

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_HEEFT_3 FOREIGN KEY (HEEFT_ARCHEOLOGIEBESLUIT_ID) REFERENCES ARCHEOLOGIEBESLUIT (ARCHEOLOGIEBESLUIT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1204)

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_VASTLEGGING FOREIGN KEY (VASTLEGGING_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- VASTLEGGING (None to None, Connector_ID: 117)

ALTER TABLE PUT ADD CONSTRAINT FK_PUT_HEEFT FOREIGN KEY (HEEFT_VLAK_ID) REFERENCES VLAK (VLAK_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1189)

ALTER TABLE SPOOR ADD CONSTRAINT FK_SPOOR_HEEFT FOREIGN KEY (HEEFT_VULLING_ID) REFERENCES VULLING (VULLING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1188)

ALTER TABLE STELLING ADD CONSTRAINT FK_STELLING_HEEFT FOREIGN KEY (HEEFT_MAGAZIJNLOCATIE_ID) REFERENCES MAGAZIJNLOCATIE (MAGAZIJNLOCATIE_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1193)

ALTER TABLE VINDPLAATS ADD CONSTRAINT FK_VINDPLAATS_HOORT_BIJ FOREIGN KEY (HOORT_BIJ_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- HOORT_BIJ (0..1 to 1, Connector_ID: 1190)

ALTER TABLE VLAK ADD CONSTRAINT FK_VLAK_HEEFT FOREIGN KEY (HEEFT_SPOOR_ID) REFERENCES SPOOR (SPOOR_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1187)

ALTER TABLE VONDST ADD CONSTRAINT FK_VONDST_BEVAT FOREIGN KEY (BEVAT_ARTEFACT_ID) REFERENCES ARTEFACT (ARTEFACT_ID);
-- BEVAT (0..1 to 0..*, Connector_ID: 1200)

ALTER TABLE VULLING ADD CONSTRAINT FK_VULLING_HEEFT FOREIGN KEY (HEEFT_VONDST_ID) REFERENCES VONDST (VONDST_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1186)

