CREATE TABLE VOERTUIG (
    VOERTUIG_ID NUMBER PRIMARY KEY,
    KENTEKEN VARCHAR2(255),
    KLEUR VARCHAR2(200),
    LAND VARCHAR2(200),
    MERK VARCHAR2(200),
    TYPE VARCHAR2(200)
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    EMAILADRES VARCHAR2(80),
    FAXNUMMER VARCHAR2(20),
    IDENTIFICATIE VARCHAR2(255),
    KVKNUMMER VARCHAR2(20),
    NAAM VARCHAR2(200),
    RECHTSVORM VARCHAR2(100),
    REKENINGNUMMER VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE KP_PRKRVRGNNNG_PRKRZN (
    KP_PRKRVRGNNNG_PRKRZN_ID NUMBER PRIMARY KEY,
    PARKEERVERGUNNING_ID NUMBER,
    PARKEERZONE_ID NUMBER
);

CREATE TABLE BOOLEAN_ENUM (
    BOOLEAN_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    ACHTERNAAM VARCHAR2(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR2(255),
    EXTERN_ENUM_ID NUMBER,
    FUNCTIE VARCHAR2(50),
    GELEVERD_VIA_LEVERANCIER_ID NUMBER,
    GESLACHTSAANDUIDING VARCHAR2(255),
    MEDEWERKERIDENTIFICATIE VARCHAR2(255),
    MEDEWERKERTOELICHTING VARCHAR2(255),
    ROEPNAAM VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    VOORLETTERS VARCHAR2(20),
    VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE PARKEERGARAGE (
    PARKEERZONE_ID NUMBER PRIMARY KEY
);

CREATE TABLE PARKEERRECHT (
    PARKEERRECHT_ID NUMBER PRIMARY KEY,
    AANMAAKTIJD TIMESTAMP,
    BEDRAGAANKOOP NUMBER(10,2),
    BEDRAGBTW NUMBER(10,2),
    BETREFT_VOERTUIG_ID NUMBER,
    DATUMTIJDEINDE TIMESTAMP,
    DATUMTIJDSTART TIMESTAMP,
    LEVERANCIER_BELPROVIDER_ID NUMBER,
    PRODUCTNAAM VARCHAR2(80),
    PRODUCTOMSCHRIJVING CLOB
);

CREATE TABLE ZONESOORT_ENUM (
    ZONESOORT_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ZONESOORT_ENUM (ZONESOORT_ENUM_ID, VALUE) VALUES
    (1, 'GSM_ZONE'),
    (2, 'VERGUNNINGHOUDERZONE');

CREATE TABLE MULDERFEIT (
    MULDERFEIT_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2),
    BETREFT_VOERTUIG_VOERTUIG_ID NUMBER,
    BEZWAARAFGEHANDELD DATE,
    BEZWAARINGETROKKEN DATE,
    BEZWAARTOEGEWEZEN DATE,
    BONNUMMER NUMBER,
    DATUMBETALING DATE,
    DATUMBEZWAAR DATE,
    DATUMGESEPONEERD DATE,
    DATUMINDIENING DATE,
    DIENSTCD VARCHAR2(255),
    ORGANISATIE VARCHAR2(200),
    OVERTREDING VARCHAR2(80),
    PARKEERTARIEF NUMBER(10,2),
    REDENSEPONEREN VARCHAR2(255),
    VORDERINGNUMMER NUMBER
);

CREATE TABLE STRAATSECTIE (
    STRAATSECTIE_ID NUMBER PRIMARY KEY,
    BEVAT_PARKEERVLAK_ID NUMBER,
    CODE VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(255),
    ZONECODE_ENUM_ID NUMBER
);

CREATE TABLE PRODUCTSOORT (
    PRODUCTSOORT_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(255),
    SOORT_PARKEERVERGUNNING_ID NUMBER,
    TARIEF NUMBER(10,2),
    TARIEFPERIODE VARCHAR2(255),
    VALT_BINNEN_PRODUCTGROEP_ID NUMBER
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(200),
    NUMMER VARCHAR2(255)
);

CREATE TABLE PRODUCTGROEP (
    PRODUCTGROEP_ID NUMBER PRIMARY KEY,
    BESLISBOOM VARCHAR2(255),
    CODE VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(255),
    SOORT_PARKEERVERGUNNING_ID NUMBER
);

CREATE TABLE PARKEERVLAK (
    PARKEERVLAK_ID NUMBER PRIMARY KEY,
    AANTAL NUMBER,
    COORDINATEN SDO_GEOMETRY,
    DOELGROEP_ENUM_ID NUMBER,
    FISCAAL_ENUM_ID NUMBER,
    PLAATS VARCHAR2(200),
    VLAKID VARCHAR2(255)
);

CREATE TABLE NAHEFFING (
    NAHEFFING_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2),
    BEZWAARAFGEHANDELD DATE,
    BEZWAARINGETROKKEN DATE,
    BEZWAARTOEGEWEZEN DATE,
    BONNUMMER NUMBER,
    DATUMBETALING DATE,
    DATUMBEZWAAR DATE,
    DATUMGESEPONEERD DATE,
    DATUMINDIENING DATE,
    DIENSTCD VARCHAR2(255),
    FISCAAL_ENUM_ID NUMBER,
    ORGANISATIE VARCHAR2(200),
    OVERTREDING VARCHAR2(80),
    PARKEERTARIEF NUMBER(10,2),
    REDENSEPONEREN VARCHAR2(255),
    VORDERINGNUMMER NUMBER
);

CREATE TABLE DOELGROEPENPLAATSEN_ENUM (
    DOELGROEPENPLAATSEN_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO DOELGROEPENPLAATSEN_ENUM (DOELGROEPENPLAATSEN_ENUM_ID, VALUE) VALUES
    (1, 'DP01'),
    (2, 'DP02'),
    (3, 'DP03'),
    (4, 'DP04'),
    (5, 'DP05'),
    (6, 'LEEG');

CREATE TABLE KP_PRKRRCHT_PRKRZN (
    KP_PRKRRCHT_PRKRZN_ID NUMBER PRIMARY KEY,
    PARKEERRECHT_ID NUMBER,
    PARKEERZONE_ID NUMBER
);

CREATE TABLE BELPROVIDER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(255)
);

CREATE TABLE PARKEERVERGUNNING (
    PARKEERVERGUNNING_ID NUMBER PRIMARY KEY,
    DATUMEINDEGELDIGHEID DATE,
    DATUMRESERVERING DATE,
    DATUMSTART DATE,
    HOUDER_RECHTSPERSOON_ID NUMBER,
    KENTEKEN VARCHAR2(255),
    MINUTENAFGESCHREVEN NUMBER,
    MINUTENGELDIG NUMBER,
    MINUTENRESTEREND NUMBER,
    NUMMER NUMBER,
    RESULTEERT_PARKEERRECHT_ID NUMBER,
    TYPE VARCHAR2(255)
);

CREATE TABLE PARKEERZONE (
    PARKEERZONE_ID NUMBER PRIMARY KEY,
    AANTALPARKEERVLAKKEN NUMBER,
    ALLEENDAGTARIEF_ENUM_ID NUMBER,
    BEVAT_PARKEERVLAK_ID NUMBER,
    BEVAT_STRAATSECTIE_ID NUMBER,
    DAGTARIEF NUMBER(10,2),
    EINDEDAG DATE,
    EINDTIJD TIMESTAMP,
    GEBRUIK VARCHAR2(255),
    GEOMETRIE SDO_GEOMETRY,
    IPMCODE VARCHAR2(255),
    IPMNAAM VARCHAR2(255),
    ISPARKEERGARAGE_ENUM_ID NUMBER,
    NAAM VARCHAR2(255),
    SECTORCODE VARCHAR2(255),
    SOORTCODE VARCHAR2(255),
    STARTDAG DATE,
    STARTTARIEF NUMBER(10,2),
    STARTTIJD TIMESTAMP,
    TYPECODE VARCHAR2(255),
    TYPENAAM VARCHAR2(255),
    UURTARIEF NUMBER(10,2)
);

CREATE TABLE PARKEERSCAN (
    PARKEERSCAN_ID NUMBER PRIMARY KEY,
    BETREFT_PARKEERVLAK_ID NUMBER,
    BETREFT_VOERTUIG_ID NUMBER,
    CODEGEBRUIKER VARCHAR2(255),
    CODESCANVOERTUIG VARCHAR2(255),
    COORDINATEN SDO_GEOMETRY,
    FOTO VARCHAR2(255),
    KENTEKEN VARCHAR2(255),
    KOMT_VOORT_UIT_NAHEFFING_ID NUMBER,
    PARKEERRECHT_ENUM_ID NUMBER,
    TIJDSTIP TIMESTAMP,
    TRANSACTIEID VARCHAR2(255),
    UITGEVOERD_DOOR_MEDEWERKER_ID NUMBER,
    VERIFICATIE_PARKEERRECHT_ID NUMBER
);

ALTER TABLE BELPROVIDER ADD CONSTRAINT FK_BELPROVIDER_GEN_LEVERANCIER FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES LEVERANCIER (RECHTSPERSOON_ID);
-- Generalization to LEVERANCIER

ALTER TABLE PARKEERGARAGE ADD CONSTRAINT FK_PARKEERGARAGE_GEN_PARKEERZONE FOREIGN KEY (PARKEERZONE_ID) REFERENCES PARKEERZONE (PARKEERZONE_ID);
-- Generalization to PARKEERZONE

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_PRKRVRGNNNG_PRKRZN ADD CONSTRAINT FK_KP_PRKRVRGNNNG_PRKRZN_1 FOREIGN KEY (PARKEERVERGUNNING_ID) REFERENCES PARKEERVERGUNNING (PARKEERVERGUNNING_ID);
-- PARKEERVERGUNNING (many-to-many junction, Connector_ID: 1277)

ALTER TABLE KP_PRKRVRGNNNG_PRKRZN ADD CONSTRAINT FK_KP_PRKRVRGNNNG_PRKRZN_2 FOREIGN KEY (PARKEERZONE_ID) REFERENCES PARKEERZONE (PARKEERZONE_ID);
-- PARKEERZONE (many-to-many junction, Connector_ID: 1277)

ALTER TABLE KP_PRKRRCHT_PRKRZN ADD CONSTRAINT FK_KP_PRKRRCHT_PRKRZN_1 FOREIGN KEY (PARKEERRECHT_ID) REFERENCES PARKEERRECHT (PARKEERRECHT_ID);
-- PARKEERRECHT (many-to-many junction, Connector_ID: 1284)

ALTER TABLE KP_PRKRRCHT_PRKRZN ADD CONSTRAINT FK_KP_PRKRRCHT_PRKRZN_2 FOREIGN KEY (PARKEERZONE_ID) REFERENCES PARKEERZONE (PARKEERZONE_ID);
-- PARKEERZONE (many-to-many junction, Connector_ID: 1284)

ALTER TABLE PRODUCTSOORT ADD CONSTRAINT FK_PRODUCTSOORT_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_PRODUCTGROEP_ID) REFERENCES PRODUCTGROEP (PRODUCTGROEP_ID);
-- VALT_BINNEN (0..* to 1, Connector_ID: 1270)

ALTER TABLE PARKEERZONE ADD CONSTRAINT FK_PARKEERZONE_BEVAT FOREIGN KEY (BEVAT_STRAATSECTIE_ID) REFERENCES STRAATSECTIE (STRAATSECTIE_ID);
-- BEVAT (1 to 0..*, Connector_ID: 1271)

ALTER TABLE STRAATSECTIE ADD CONSTRAINT FK_STRAATSECTIE_BEVAT FOREIGN KEY (BEVAT_PARKEERVLAK_ID) REFERENCES PARKEERVLAK (PARKEERVLAK_ID);
-- BEVAT (1 to 0..*, Connector_ID: 1272)

ALTER TABLE PARKEERZONE ADD CONSTRAINT FK_PARKEERZONE_BEVAT_2 FOREIGN KEY (BEVAT_PARKEERVLAK_ID) REFERENCES PARKEERVLAK (PARKEERVLAK_ID);
-- BEVAT (1 to 0..*, Connector_ID: 1273)

ALTER TABLE PRODUCTSOORT ADD CONSTRAINT FK_PRODUCTSOORT_SOORT FOREIGN KEY (SOORT_PARKEERVERGUNNING_ID) REFERENCES PARKEERVERGUNNING (PARKEERVERGUNNING_ID);
-- SOORT (1 to 0..*, Connector_ID: 1274)

ALTER TABLE PRODUCTGROEP ADD CONSTRAINT FK_PRODUCTGROEP_SOORT FOREIGN KEY (SOORT_PARKEERVERGUNNING_ID) REFERENCES PARKEERVERGUNNING (PARKEERVERGUNNING_ID);
-- SOORT (1 to 0..*, Connector_ID: 1275)

ALTER TABLE PARKEERVERGUNNING ADD CONSTRAINT FK_PARKEERVERGUNNING_HOUDER FOREIGN KEY (HOUDER_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- HOUDER (0..* to 1, Connector_ID: 1276)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_BETREFT FOREIGN KEY (BETREFT_PARKEERVLAK_ID) REFERENCES PARKEERVLAK (PARKEERVLAK_ID);
-- BETREFT (0..* to 1, Connector_ID: 1279)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_BETREFT_2 FOREIGN KEY (BETREFT_VOERTUIG_ID) REFERENCES VOERTUIG (VOERTUIG_ID);
-- BETREFT (0..* to 1, Connector_ID: 1280)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_UITGEVOERD_DOOR FOREIGN KEY (UITGEVOERD_DOOR_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- UITGEVOERD_DOOR (0..* to 1, Connector_ID: 1281)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_VERIFICATIE FOREIGN KEY (VERIFICATIE_PARKEERRECHT_ID) REFERENCES PARKEERRECHT (PARKEERRECHT_ID);
-- VERIFICATIE (0..1 to 0..1, Connector_ID: 1282)

ALTER TABLE PARKEERVERGUNNING ADD CONSTRAINT FK_PARKEERVERGUNNING_RESULTEERT FOREIGN KEY (RESULTEERT_PARKEERRECHT_ID) REFERENCES PARKEERRECHT (PARKEERRECHT_ID);
-- RESULTEERT (0..1 to 0..1, Connector_ID: 1283)

ALTER TABLE PARKEERRECHT ADD CONSTRAINT FK_PARKEERRECHT_BETREFT FOREIGN KEY (BETREFT_VOERTUIG_ID) REFERENCES VOERTUIG (VOERTUIG_ID);
-- BETREFT (0..* to 1, Connector_ID: 1285)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_KOMT_VOORT_UIT FOREIGN KEY (KOMT_VOORT_UIT_NAHEFFING_ID) REFERENCES NAHEFFING (NAHEFFING_ID);
-- KOMT_VOORT_UIT (0..1 to 0..1, Connector_ID: 1287)

ALTER TABLE MULDERFEIT ADD CONSTRAINT FK_MULDERFEIT_BETREFT_VOERTUIG FOREIGN KEY (BETREFT_VOERTUIG_VOERTUIG_ID) REFERENCES VOERTUIG (VOERTUIG_ID);
-- BETREFT_VOERTUIG (0..* to 0..1, Connector_ID: 1288)

ALTER TABLE PARKEERRECHT ADD CONSTRAINT FK_PARKEERRECHT_LEVERANCIER FOREIGN KEY (LEVERANCIER_BELPROVIDER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- LEVERANCIER (0..* to 0..1, Connector_ID: 1289)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_GELEVERD_VIA FOREIGN KEY (GELEVERD_VIA_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- GELEVERD_VIA (0..* to 0..1, Connector_ID: 2194)

ALTER TABLE NAHEFFING ADD CONSTRAINT FK_NAHEFFING_FISCAAL_ENUM_ID FOREIGN KEY (FISCAAL_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- FISCAAL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_PARKEERRECHT_ENUM_ID FOREIGN KEY (PARKEERRECHT_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- PARKEERRECHT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERVLAK ADD CONSTRAINT FK_PARKEERVLAK_DOELGROEP_ENUM_ID FOREIGN KEY (DOELGROEP_ENUM_ID) REFERENCES DOELGROEPENPLAATSEN_ENUM (DOELGROEPENPLAATSEN_ENUM_ID);
-- DOELGROEP_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERVLAK ADD CONSTRAINT FK_PARKEERVLAK_FISCAAL_ENUM_ID FOREIGN KEY (FISCAAL_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- FISCAAL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERZONE ADD CONSTRAINT FK_PARKEERZONE_ISPARKEERGARAGE_ENUM_ID FOREIGN KEY (ISPARKEERGARAGE_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- ISPARKEERGARAGE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERZONE ADD CONSTRAINT FK_PARKEERZONE_ALLEENDAGTARIEF_ENUM_ID FOREIGN KEY (ALLEENDAGTARIEF_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- ALLEENDAGTARIEF_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE STRAATSECTIE ADD CONSTRAINT FK_STRAATSECTIE_ZONECODE_ENUM_ID FOREIGN KEY (ZONECODE_ENUM_ID) REFERENCES ZONESOORT_ENUM (ZONESOORT_ENUM_ID);
-- ZONECODE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_EXTERN_ENUM_ID FOREIGN KEY (EXTERN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- EXTERN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

