CREATE TABLE KP_GMNT_IS_OVRGGN_IN (
    KP_GMNT_IS_OVRGGN_IN_ID NUMBER PRIMARY KEY,
    IS_OVERGEGAAN_IN_1_ID NUMBER,
    IS_OVERGEGAAN_IN_2_ID NUMBER
);

CREATE TABLE WOONPLAATS (
    WOONPLAATS_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    EINDREGISTRATIE DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    LIGT_IN_GEMEENTE_ID NUMBER,
    STATUS VARCHAR2(255),
    TIJDSTIPACTIEF TIMESTAMP,
    TIJDSTIPREGISTRATIE TIMESTAMP,
    VERSIE NUMBER,
    VOORKOMEN DATE,
    WOONPLAATSNAAM VARCHAR2(80),
    WOONPLAATSNAAMNEN VARCHAR2(255)
);

CREATE TABLE INGESCHREVENPERSOON (
    INGESCHREVENPERSOON_ID NUMBER PRIMARY KEY,
    ADRESHERKOMST VARCHAR2(255),
    ANUMMER VARCHAR2(20),
    BESCHRIJVINGLOCATIE VARCHAR2(200),
    BUITENLANDSREISDOCUMENT VARCHAR2(80),
    BURGERLIJKESTAAT VARCHAR2(255),
    DATUMBEGINGELDIGHEIDVERBLIJFPLAATS DATE,
    DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS DATE,
    DATUMINSCHRIJVINGGEMEENTE DATE,
    DATUMOPSCHORTINGBIJHOUDING DATE,
    DATUMVERTREKUITNEDERLAND DATE,
    DATUMVESTIGINGNEDERLAND DATE,
    GEMEENTEVANINSCHRIJVING VARCHAR2(80),
    GEZINSRELATIE VARCHAR2(255),
    INDICATIEGEHEIM NUMBER(1),
    INGEZETENE NUMBER(1),
    LANDWAARNAARVERTROKKEN VARCHAR2(255),
    LANDWAARVANDAANINGESCHREVEN VARCHAR2(255),
    OUDER1 VARCHAR2(255),
    OUDER2 VARCHAR2(255),
    OUDER_1_INGESCHREVENPERSOON_ID NUMBER,
    OUDER_2_INGESCHREVENPERSOON_ID NUMBER,
    PARTNERID VARCHAR2(255),
    REDENEINDEBEWONING DATE,
    REDENOPSCHORTINGBIJHOUDING VARCHAR2(200),
    SIGNALERINGREISDOCUMENT NUMBER(1),
    VERBLIJFSTITEL VARCHAR2(255)
);

CREATE TABLE GEMEENTE (
    GEMEENTE_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEMEENTECODE VARCHAR2(255),
    GEMEENTENAAM VARCHAR2(80),
    GEMEENTENAAM_NEN VARCHAR2(255),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE WIJK (
    WIJK_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    LIGT_IN_WOONPLAATS_ID NUMBER,
    STATUS VARCHAR2(255),
    VERSIE NUMBER,
    WIJKCODE VARCHAR2(255),
    WIJKNAAM VARCHAR2(255)
);

CREATE TABLE BUURT (
    BUURT_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR2(255),
    CODE VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    LIGT_IN_WIJK_ID NUMBER,
    NAAM VARCHAR2(255),
    STATUS VARCHAR2(255),
    VERSIE NUMBER
);

ALTER TABLE KP_GMNT_IS_OVRGGN_IN ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_1 FOREIGN KEY (IS_OVERGEGAAN_IN_1_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE KP_GMNT_IS_OVRGGN_IN ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_2 FOREIGN KEY (IS_OVERGEGAAN_IN_2_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (OUDER_1_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- OUDER_1 (1 to 1, Connector_ID: 1871)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (OUDER_2_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- OUDER_2 (1 to 1, Connector_ID: 1873)

ALTER TABLE WOONPLAATS ADD CONSTRAINT FK_WOONPLAATS_LIGT_IN FOREIGN KEY (LIGT_IN_GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- LIGT_IN (1..* to 1.., Connector_ID: 2290)

ALTER TABLE WIJK ADD CONSTRAINT FK_WIJK_LIGT_IN FOREIGN KEY (LIGT_IN_WOONPLAATS_ID) REFERENCES WOONPLAATS (WOONPLAATS_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 2294)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_LIGT_IN FOREIGN KEY (LIGT_IN_WIJK_ID) REFERENCES WIJK (WIJK_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 2297)

