CREATE TABLE [AANTEKENING] (
    [AANTEKENING_ID] INT PRIMARY KEY,
    [AARD] VARCHAR(100),
    [BEGRENZING] VARCHAR(255),
    [BETREFTGEDEELTEVANPERCEEL] BIT,
    [DATUMEINDE] DATE,
    [DATUMEINDERECHT] DATE,
    [IDENTIFICATIE] VARCHAR(100),
    [OMSCHRIJVING] VARCHAR(200)
);

CREATE TABLE [TENAAMSTELLING] (
    [TENAAMSTELLING_ID] INT PRIMARY KEY,
    [AANDEELINRECHT] VARCHAR(255),
    [AANTEKENING_ID] INT,
    [BURGERLIJKESTAATTENTIJDEVANVERKRIJGING] DATETIME2,
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [EXPLOITANTCODE] VARCHAR(255),
    [IDENTIFICATIETENAAMSTELLING] VARCHAR(255),
    [VERKLARINGINZAKEDERDENBESCHERMING] VARCHAR(100),
    [VERKREGENNAMENSSAMENWERKINGSVERBAND] VARCHAR(255)
);

ALTER TABLE [TENAAMSTELLING] ADD CONSTRAINT FK_TENAAMSTELLING_AANTEKENING FOREIGN KEY ([AANTEKENING_ID]) REFERENCES [AANTEKENING] ([AANTEKENING_ID]);
-- unnamed (1 to 0..*, Connector_ID: 1981)

