CREATE TABLE PIP (
    PIP_ID INTEGER PRIMARY KEY,
    DAGTEKENINGINITIELEPIP DATE,
    DAGTEKENINGPIP DATE,
    EMAILCONTACTPERSOON VARCHAR(255),
    INDICATORMAGOPLEIDINGAFMAKEN BOOLEAN,
    NAAMCONTACTPERSOON VARCHAR(255)
);

CREATE TABLE LEERROUTE (
    LEERROUTE_ID INTEGER PRIMARY KEY,
    AFGESPROKEN_IN_PIP_ID INTEGER,
    EXAMENA2 VARCHAR(255),
    GEENLEERBAARHEIDSTOETSZB VARCHAR(255),
    GESCHATTEINTENSITEITB1ROUTE VARCHAR(255),
    INDICATORALFABETISERING VARCHAR(255),
    INDICATORMAGOPLEIDINGAFMAKEN VARCHAR(255),
    INDICATORTOESTEMMINGEXAMENA2 VARCHAR(255),
    LEERROUTETYPE VARCHAR(255),
    NIVEAU VARCHAR(255)
);

CREATE TABLE B1_ROUTE (
    B1_ROUTE_ID INTEGER PRIMARY KEY,
    AANTALGRATISEXAMENPOGINGENTEGOED INTEGER,
    EXAMENDATUM DATE,
    GEVOLGDEURENPARTICIPATIETAALLES INTEGER,
    ONDERDEEL_VAN__LEERROUTE_ID INTEGER,
    REDENGEENRESULTAAT VARCHAR(255),
    RESULTAAT INTEGER
);

ALTER TABLE LEERROUTE ADD CONSTRAINT FK_LEERROUTE_AFGESPROKEN_IN FOREIGN KEY (AFGESPROKEN_IN_PIP_ID) REFERENCES PIP (PIP_ID);
-- AFGESPROKEN_IN (0..1 to 1, Connector_ID: 1620)

ALTER TABLE B1_ROUTE ADD CONSTRAINT FK_B1_ROUTE_ONDERDEEL_VAN_ FOREIGN KEY (ONDERDEEL_VAN__LEERROUTE_ID) REFERENCES LEERROUTE (LEERROUTE_ID);
-- ONDERDEEL_VAN_ (0..1 to 1, Connector_ID: 1630)

