CREATE TABLE `WAARDEPEILING` (
    `WAARDEPEILING_ID` INT PRIMARY KEY,
    `BIJGEVOEGD_BEWIJS` BOOLEAN,
    `BRONTYPE` VARCHAR(255),
    `DATUM_AANSPRAAK_VERMOGENSCOMPONENT` DATE,
    `LINK_NAAR_BEWIJS` VARCHAR(255),
    `PEILMOMENT` DATE,
    `WAARDESOORT_VERMOGENSCOMPONENT` VARCHAR(255),
    `WAARDE_VERMOGENSCOMPONENT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `VERMOGENSCOMPONENT` (
    `VERMOGENSCOMPONENT_ID` INT PRIMARY KEY,
    `CODE_SOORT_VERMOGENSCOMPONENT` VARCHAR(255),
    `DATUM_VASTSTELLING_VERMOGENCOMPONENT` DATE,
    `IDENTIFICATIE` VARCHAR(255),
    `NOG_AAN_TE_SPREKEN_VERMOGEN` VARCHAR(255),
    `VERMOGENSCOMPONENT_IS_GEWAARDEERD_MET_WAARDEPEILING_WAARDEPEILING_ID` INT,
    `VRIJ_TE_LATEN_VERMOGEN` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BANKREKENING` (
    `VERMOGENSCOMPONENT_ID` INT PRIMARY KEY,
    `BANKREKENINGNUMMER` VARCHAR(255),
    `BRONTYPE` VARCHAR(255),
    `DATUM_AANVANG_BANKREKENING` DATE,
    `DATUM_EINDE_BANKREKENING` DATE,
    `IBAN` VARCHAR(255),
    `REKENINGTYPE` VARCHAR(255),
    `TENAAMSTELLING` VARCHAR(255),
    `VOORKEUR_BANKREKENING` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `ONROEREND_GOED` (
    `VERMOGENSCOMPONENT_ID` INT PRIMARY KEY,
    `OVERWAARDE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `MOTORVOERTUIG` (
    `VERMOGENSCOMPONENT_ID` INT PRIMARY KEY,
    `KENTEKEN` VARCHAR(255),
    `SOORT_MOTORVOERTUIG` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `HYPOTHEEK` (
    `VERMOGENSCOMPONENT_ID` INT PRIMARY KEY,
    `HYPOTHEEK_RUST_OP_ONROEREND_GOED_ONROEREND_GOED_ID` INT,
    `OVERWAARDE` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `BANKREKENING` ADD CONSTRAINT FK_BANKREKENING_GEN_VERMOGENSCOMPONENT FOREIGN KEY (`VERMOGENSCOMPONENT_ID`) REFERENCES `VERMOGENSCOMPONENT` (`VERMOGENSCOMPONENT_ID`);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE `HYPOTHEEK` ADD CONSTRAINT FK_HYPOTHEEK_GEN_VERMOGENSCOMPONENT FOREIGN KEY (`VERMOGENSCOMPONENT_ID`) REFERENCES `VERMOGENSCOMPONENT` (`VERMOGENSCOMPONENT_ID`);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE `MOTORVOERTUIG` ADD CONSTRAINT FK_MOTORVOERTUIG_GEN_VERMOGENSCOMPONENT FOREIGN KEY (`VERMOGENSCOMPONENT_ID`) REFERENCES `VERMOGENSCOMPONENT` (`VERMOGENSCOMPONENT_ID`);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE `ONROEREND_GOED` ADD CONSTRAINT FK_ONROEREND_GOED_GEN_VERMOGENSCOMPONENT FOREIGN KEY (`VERMOGENSCOMPONENT_ID`) REFERENCES `VERMOGENSCOMPONENT` (`VERMOGENSCOMPONENT_ID`);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE `VERMOGENSCOMPONENT` ADD CONSTRAINT FK_VERMOGENSCOMPONENT_VERMOGENSCOMPONENT_IS_GEWAARDEERD_MET_WAARDEPEILING FOREIGN KEY (`VERMOGENSCOMPONENT_IS_GEWAARDEERD_MET_WAARDEPEILING_WAARDEPEILING_ID`) REFERENCES `WAARDEPEILING` (`WAARDEPEILING_ID`);
-- VERMOGENSCOMPONENT_IS_GEWAARDEERD_MET_WAARDEPEILING (0..* to 1..1, Connector_ID: 866)

ALTER TABLE `HYPOTHEEK` ADD CONSTRAINT FK_HYPOTHEEK_HYPOTHEEK_RUST_OP_ONROEREND_GOED FOREIGN KEY (`HYPOTHEEK_RUST_OP_ONROEREND_GOED_ONROEREND_GOED_ID`) REFERENCES `VERMOGENSCOMPONENT` (`VERMOGENSCOMPONENT_ID`);
-- HYPOTHEEK_RUST_OP_ONROEREND_GOED (1..1 to 0..*, Connector_ID: 869)

