CREATE TABLE KOSTENCOMPONENT (
    KOSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2)
);

CREATE TABLE DRAAGKRACHTREGIME (
    DRAAGKRACHTREGIME_ID NUMBER PRIMARY KEY,
    INITIELE_DRAAGKRACHT VARCHAR2(255),
    NAAM VARCHAR2(255),
    PEILDATUM DATE,
    RESTERENDE_DRAAGKRACHT VARCHAR2(255)
);

CREATE TABLE VRIJLATING_INKOMSTEN (
    VRIJLATING_INKOMSTEN_ID NUMBER PRIMARY KEY,
    DOELGROEP VARCHAR2(255),
    MEDISCH NUMBER(1),
    PERIODE_EINDDATUM DATE,
    PERIODE_STARTDATUM DATE,
    SOORT_VRIJLATING VARCHAR2(255),
    VRIJGELATEN_BEDRAG NUMBER(10,2)
);

CREATE TABLE INKOMSTENCOMPONENT (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    BIJGEVOEGD_BEWIJS NUMBER(1),
    BOEKINGSDATUM DATE,
    BRUTO_NETTO VARCHAR2(255),
    INKOMSTEN VARCHAR2(255),
    INKOMSTENCOMPONENTTYPE VARCHAR2(255),
    LINK_NAAR_BEWIJS VARCHAR2(255),
    PEILMOMENT DATE,
    PERIODE_EINDDATUM DATE,
    PERIODE_STARTDATUM DATE
);

CREATE TABLE ONDERHOUDSPLICHT (
    ONDERHOUDSPLICHT_ID NUMBER PRIMARY KEY,
    BIJDRAGE VARCHAR2(255),
    BOEKINGSDATUM DATE,
    ONDERHOUDSPLICHTTYPE VARCHAR2(255),
    PEILMOMENT DATE,
    PERIODE_EINDDATUM DATE,
    PERIODE_STARTDATUM DATE
);

CREATE TABLE REISKOSTEN_NAAR_HET_WERK_ (
    KOSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    SOORT VARCHAR2(255)
);

CREATE TABLE EIGEN_BIJDRAGE (
    KOSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    SOORT VARCHAR2(255)
);

CREATE TABLE TE_BETALEN_ALIMENTATIE (
    KOSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    SOORT VARCHAR2(255)
);

CREATE TABLE BESLAG_OP_INKOMEN (
    KOSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    SOORT VARCHAR2(255)
);

CREATE TABLE DRAAGKRACHT (
    DRAAGKRACHT_ID NUMBER PRIMARY KEY,
    DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME_DRAAGKRACHTREGIME_ID NUMBER,
    EINDDATUM DATE,
    STARTDATUM DATE
);

CREATE TABLE INKOMSTENVERHOUDING (
    INKOMSTENVERHOUDING_ID NUMBER PRIMARY KEY,
    CATEGORIE_INKOMSTEN VARCHAR2(255),
    INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT_PRIMAIR_INKOMSTENCOMPONENT_ID NUMBER,
    PERIODE_EINDDATUM DATE,
    PERIODE_STARTDATUM DATE
);

CREATE TABLE EIGEN_BEDRIJF (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    AANTAL_UREN_PER_WEEK_BESTEED_AAN_WERK VARCHAR2(255),
    INGESCHREVEN_BIJ_KVK NUMBER(1),
    RECHT_OP_ZELFSTANDIGENAFTREK NUMBER(1),
    SOORT_BEDRIJF VARCHAR2(255),
    TOESTEMMING_GEMEENTE_PARTTIME_ONDERNEMEN NUMBER(1)
);

CREATE TABLE MAALTIJDVERGOEDING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE STUDIEFINANCIERING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    DAADWERKELIJK_GENOTEN NUMBER(1),
    INKOMSTENSOORT_STUDIEFINANCIERING VARCHAR2(255)
);

CREATE TABLE LOONBESLAG (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE HOBBY (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    AANTAL_UREN_PER_WEEK_BESTEED_AAN_HOBBY VARCHAR2(255),
    BESCHRIJVING_HOBBY VARCHAR2(255)
);

CREATE TABLE VERGOEDING_IN_NATURA (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE ANDER_INKOMEN (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    BESCHRIJVING_ANDER_INKOMEN VARCHAR2(255),
    CATEGORIE VARCHAR2(255)
);

CREATE TABLE VERLAGING_DOOR_MAATREGEL (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE SECUNDAIR_INKOMSTENCOMPONENT (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE ALIMENTATIE (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    BEDRAG_AAN_ANDERE_REKENINGEN NUMBER(10,2),
    BEDRAG_IN_CONVENANT NUMBER(10,2),
    BIJDRAGEEXPARTNERANDEREREKENINGEN NUMBER(1),
    INKOMSTENSOORT_ALIMENTATIE VARCHAR2(255),
    JUISTE_BEDRAG_BETAALD_DOOR_EX_PARTNER NUMBER(10,2),
    LBIO_INGESCHAKELD NUMBER(1)
);

CREATE TABLE HEFFINGSKORTING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    ALGEMENE_HEFFINGSKORTING NUMBER(1),
    INKOMENSAFHANKELIJKE_COMBINATIEKORTING NUMBER(1)
);

CREATE TABLE DERTIENDE_MAAND_EINDEJAARSUITKERING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE VAKANTIEGELD (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE ONKOSTENVERGOEDING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE INKOMSTENVERMINDERING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE PRIMAIR_INKOMSTENCOMPONENT (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE VERGOEDING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE VERLAGING_DOOR_BOETE (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE REISKOSTENVERGOEDING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE ONDERHOUDSVERHOUDING (
    ONDERHOUDSVERHOUDING_ID NUMBER PRIMARY KEY,
    ONDERHOUDSVERHOUDINGTYPE VARCHAR2(255),
    ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT_ONDERHOUDSPLICHT_ID NUMBER,
    PERIODE_EINDDATUM DATE,
    PERIODE_STARTDATUM DATE
);

CREATE TABLE PENSIOEN (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    BESLAG_OP_PENSIOEN NUMBER(1),
    INKOMSTENSOORT_PENSIOEN VARCHAR2(255),
    LOONHEFFINGSKORTING NUMBER(1),
    PENSIOEN_HEEFT_LOONBESLAG_LOONBESLAG_ID NUMBER,
    PENSIOEN_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID NUMBER,
    PERIODICITEIT_UITBETALING_PENSIOEN VARCHAR2(255),
    UITBETALING_VAKANTIEGELD_PENSIOEN VARCHAR2(255)
);

CREATE TABLE UITKERING (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    BESLAG_OP_UITKERING NUMBER(1),
    INKOMSTENSOORT_UITKERING VARCHAR2(255),
    LOONHEFFINGSKORTING NUMBER(1),
    PERIODICITEIT_UITBETALING_UITKERING VARCHAR2(255),
    TOESLAG_OP_UITKERING NUMBER(1),
    UITKERING_HEEFT_LOONBESLAG_LOONBESLAG_ID NUMBER,
    UITKERING_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID NUMBER,
    UITKERING_HEEFT_VERLAGING_DOOR_BOETE_VERLAGING_DOOR_BOETE_ID NUMBER,
    UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL_VERLAGING_DOOR_MAATREGEL_ID NUMBER,
    UITKERING_VERLAAGD_DOOR_BOETE NUMBER(1),
    UITKERING_VERLAAGD_DOOR_MAATREGEL NUMBER(1),
    VAKANTIEGELD_JAARLIJKS_ONTVANGEN NUMBER(1)
);

CREATE TABLE BETAALD_WERK (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    ARBEIDSCONTRACT NUMBER(1),
    BEGINDATUM_CONTRACT DATE,
    BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING_DERTIENDE_MAAND_EINDEJAARSUITKERING_ID NUMBER,
    BETAALD_WERK_HEEFT_HEFFINGSKORTING_HEFFINGSKORTING_ID NUMBER,
    BETAALD_WERK_HEEFT_LOONBESLAG_LOONBESLAG_ID NUMBER,
    BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING_MAALTIJDVERGOEDING_ID NUMBER,
    BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING_ONKOSTENVERGOEDING_ID NUMBER,
    BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING_REISKOSTENVERGOEDING_ID NUMBER,
    BETAALD_WERK_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID NUMBER,
    EINDDATUM_CONTRACT DATE,
    INKOMSTENSOORT_BETAALD_WERK VARCHAR2(255),
    INKOMSTEN_UIT_IKB_REGELING NUMBER(1),
    LOONDIENST NUMBER(1),
    LOONHEFFINGSNUMMER VARCHAR2(255),
    PERIODICITEIT_UITBETALING_LOON VARCHAR2(255),
    SOORT_CONTRACT VARCHAR2(255),
    URENVERMINDERING VARCHAR2(255)
);

CREATE TABLE STAGE (
    INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY,
    MAALTIJDVERGOEDING TIMESTAMP,
    ONKOSTENVERGOEDING NUMBER(10,2),
    PERIODICITEIT_UITBETALING_LOON VARCHAR2(255),
    REISKOSTENVERGOEDING NUMBER(10,2),
    STAGE_HEEFT_MAALTIJDVERGOEDING_MAALTIJDVERGOEDING_ID NUMBER,
    STAGE_HEEFT_ONKOSTENVERGOEDING_ONKOSTENVERGOEDING_ID NUMBER,
    STAGE_HEEFT_REISKOSTENVERGOEDING_REISKOSTENVERGOEDING_ID NUMBER,
    STAGE_HEEFT_VERGOEDING_IN_NATURA_VERGOEDING_IN_NATURA_ID NUMBER,
    VERGOEDING_IN_NATURA NUMBER(1)
);

ALTER TABLE ALIMENTATIE ADD CONSTRAINT FK_ALIMENTATIE_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE ANDER_INKOMEN ADD CONSTRAINT FK_ANDER_INKOMEN_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE BESLAG_OP_INKOMEN ADD CONSTRAINT FK_BESLAG_OP_INKOMEN_GEN_KOSTENCOMPONENT FOREIGN KEY (KOSTENCOMPONENT_ID) REFERENCES KOSTENCOMPONENT (KOSTENCOMPONENT_ID);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE BETAALD_WERK ADD CONSTRAINT FK_BETAALD_WERK_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE DERTIENDE_MAAND_EINDEJAARSUITKERING ADD CONSTRAINT FK_DERTIENDE_MAAND_EINDEJAARSUITKERING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES SECUNDAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE EIGEN_BEDRIJF ADD CONSTRAINT FK_EIGEN_BEDRIJF_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE EIGEN_BIJDRAGE ADD CONSTRAINT FK_EIGEN_BIJDRAGE_GEN_KOSTENCOMPONENT FOREIGN KEY (KOSTENCOMPONENT_ID) REFERENCES KOSTENCOMPONENT (KOSTENCOMPONENT_ID);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE HEFFINGSKORTING ADD CONSTRAINT FK_HEFFINGSKORTING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES SECUNDAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE HOBBY ADD CONSTRAINT FK_HOBBY_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE INKOMSTENVERMINDERING ADD CONSTRAINT FK_INKOMSTENVERMINDERING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES SECUNDAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE LOONBESLAG ADD CONSTRAINT FK_LOONBESLAG_GEN_INKOMSTENVERMINDERING FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES INKOMSTENVERMINDERING (INKOMSTENCOMPONENT_ID);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE MAALTIJDVERGOEDING ADD CONSTRAINT FK_MAALTIJDVERGOEDING_GEN_VERGOEDING FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES VERGOEDING (INKOMSTENCOMPONENT_ID);
-- Generalization to VERGOEDING

ALTER TABLE ONKOSTENVERGOEDING ADD CONSTRAINT FK_ONKOSTENVERGOEDING_GEN_VERGOEDING FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES VERGOEDING (INKOMSTENCOMPONENT_ID);
-- Generalization to VERGOEDING

ALTER TABLE PENSIOEN ADD CONSTRAINT FK_PENSIOEN_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE PRIMAIR_INKOMSTENCOMPONENT ADD CONSTRAINT FK_PRIMAIR_INKOMSTENCOMPONENT_GEN_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to INKOMSTENCOMPONENT

ALTER TABLE REISKOSTEN_NAAR_HET_WERK_ ADD CONSTRAINT FK_REISKOSTEN_NAAR_HET_WERK__GEN_KOSTENCOMPONENT FOREIGN KEY (KOSTENCOMPONENT_ID) REFERENCES KOSTENCOMPONENT (KOSTENCOMPONENT_ID);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE REISKOSTENVERGOEDING ADD CONSTRAINT FK_REISKOSTENVERGOEDING_GEN_VERGOEDING FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES VERGOEDING (INKOMSTENCOMPONENT_ID);
-- Generalization to VERGOEDING

ALTER TABLE SECUNDAIR_INKOMSTENCOMPONENT ADD CONSTRAINT FK_SECUNDAIR_INKOMSTENCOMPONENT_GEN_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to INKOMSTENCOMPONENT

ALTER TABLE STAGE ADD CONSTRAINT FK_STAGE_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE STUDIEFINANCIERING ADD CONSTRAINT FK_STUDIEFINANCIERING_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE TE_BETALEN_ALIMENTATIE ADD CONSTRAINT FK_TE_BETALEN_ALIMENTATIE_GEN_KOSTENCOMPONENT FOREIGN KEY (KOSTENCOMPONENT_ID) REFERENCES KOSTENCOMPONENT (KOSTENCOMPONENT_ID);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE UITKERING ADD CONSTRAINT FK_UITKERING_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE VAKANTIEGELD ADD CONSTRAINT FK_VAKANTIEGELD_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES SECUNDAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE VERGOEDING ADD CONSTRAINT FK_VERGOEDING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES SECUNDAIR_INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE VERGOEDING_IN_NATURA ADD CONSTRAINT FK_VERGOEDING_IN_NATURA_GEN_VERGOEDING FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES VERGOEDING (INKOMSTENCOMPONENT_ID);
-- Generalization to VERGOEDING

ALTER TABLE VERLAGING_DOOR_BOETE ADD CONSTRAINT FK_VERLAGING_DOOR_BOETE_GEN_INKOMSTENVERMINDERING FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES INKOMSTENVERMINDERING (INKOMSTENCOMPONENT_ID);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE VERLAGING_DOOR_MAATREGEL ADD CONSTRAINT FK_VERLAGING_DOOR_MAATREGEL_GEN_INKOMSTENVERMINDERING FOREIGN KEY (INKOMSTENCOMPONENT_ID) REFERENCES INKOMSTENVERMINDERING (INKOMSTENCOMPONENT_ID);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE UITKERING ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VERLAGING_DOOR_BOETE FOREIGN KEY (UITKERING_HEEFT_VERLAGING_DOOR_BOETE_VERLAGING_DOOR_BOETE_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- UITKERING_HEEFT_VERLAGING_DOOR_BOETE (0..* to 1..1, Connector_ID: 877)

ALTER TABLE UITKERING ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VAKANTIEGELD FOREIGN KEY (UITKERING_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- UITKERING_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 878)

ALTER TABLE UITKERING ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL FOREIGN KEY (UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL_VERLAGING_DOOR_MAATREGEL_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL (0..* to 1..1, Connector_ID: 879)

ALTER TABLE STAGE ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_VERGOEDING_IN_NATURA FOREIGN KEY (STAGE_HEEFT_VERGOEDING_IN_NATURA_VERGOEDING_IN_NATURA_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- STAGE_HEEFT_VERGOEDING_IN_NATURA (0..* to 1..1, Connector_ID: 883)

ALTER TABLE STAGE ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_REISKOSTENVERGOEDING FOREIGN KEY (STAGE_HEEFT_REISKOSTENVERGOEDING_REISKOSTENVERGOEDING_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- STAGE_HEEFT_REISKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 886)

ALTER TABLE PENSIOEN ADD CONSTRAINT FK_PENSIOEN_PENSIOEN_HEEFT_VAKANTIEGELD FOREIGN KEY (PENSIOEN_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- PENSIOEN_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 890)

ALTER TABLE STAGE ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_ONKOSTENVERGOEDING FOREIGN KEY (STAGE_HEEFT_ONKOSTENVERGOEDING_ONKOSTENVERGOEDING_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- STAGE_HEEFT_ONKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 892)

ALTER TABLE ONDERHOUDSVERHOUDING ADD CONSTRAINT FK_ONDERHOUDSVERHOUDING_ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT FOREIGN KEY (ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT_ONDERHOUDSPLICHT_ID) REFERENCES ONDERHOUDSPLICHT (ONDERHOUDSPLICHT_ID);
-- ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT (0..* to 1..1, Connector_ID: 894)

ALTER TABLE STAGE ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_MAALTIJDVERGOEDING FOREIGN KEY (STAGE_HEEFT_MAALTIJDVERGOEDING_MAALTIJDVERGOEDING_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- STAGE_HEEFT_MAALTIJDVERGOEDING (0..* to 1..1, Connector_ID: 895)

ALTER TABLE UITKERING ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_LOONBESLAG FOREIGN KEY (UITKERING_HEEFT_LOONBESLAG_LOONBESLAG_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- UITKERING_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 897)

ALTER TABLE PENSIOEN ADD CONSTRAINT FK_PENSIOEN_PENSIOEN_HEEFT_LOONBESLAG FOREIGN KEY (PENSIOEN_HEEFT_LOONBESLAG_LOONBESLAG_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- PENSIOEN_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 898)

ALTER TABLE INKOMSTENVERHOUDING ADD CONSTRAINT FK_INKOMSTENVERHOUDING_INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT_PRIMAIR_INKOMSTENCOMPONENT_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT (1..* to 0..1, Connector_ID: 901)

ALTER TABLE DRAAGKRACHT ADD CONSTRAINT FK_DRAAGKRACHT_DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME FOREIGN KEY (DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME_DRAAGKRACHTREGIME_ID) REFERENCES DRAAGKRACHTREGIME (DRAAGKRACHTREGIME_ID);
-- DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME (1..* to 1..1, Connector_ID: 906)

ALTER TABLE BETAALD_WERK ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING FOREIGN KEY (BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING_MAALTIJDVERGOEDING_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING (0..* to 1..1, Connector_ID: 908)

ALTER TABLE BETAALD_WERK ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING FOREIGN KEY (BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING_DERTIENDE_MAAND_EINDEJAARSUITKERING_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING (0..* to 1..1, Connector_ID: 909)

ALTER TABLE BETAALD_WERK ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING FOREIGN KEY (BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING_REISKOSTENVERGOEDING_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 910)

ALTER TABLE BETAALD_WERK ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING FOREIGN KEY (BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING_ONKOSTENVERGOEDING_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 911)

ALTER TABLE BETAALD_WERK ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_LOONBESLAG FOREIGN KEY (BETAALD_WERK_HEEFT_LOONBESLAG_LOONBESLAG_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- BETAALD_WERK_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 912)

ALTER TABLE BETAALD_WERK ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_HEFFINGSKORTING FOREIGN KEY (BETAALD_WERK_HEEFT_HEFFINGSKORTING_HEFFINGSKORTING_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- BETAALD_WERK_HEEFT_HEFFINGSKORTING (0..* to 1..1, Connector_ID: 913)

ALTER TABLE BETAALD_WERK ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_VAKANTIEGELD FOREIGN KEY (BETAALD_WERK_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID) REFERENCES INKOMSTENCOMPONENT (INKOMSTENCOMPONENT_ID);
-- BETAALD_WERK_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 914)

