CREATE TABLE ENUMCONTACTSOORT_ENUM (
    ENUMCONTACTSOORT_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMCONTACTSOORT_ENUM (ENUMCONTACTSOORT_ENUM_ID, VALUE) VALUES
    (1, 'BRIEF'),
    (2, 'HUISBEZOEK'),
    (3, 'KAARTJE'),
    (4, 'MAIL'),
    (5, 'OVERIGE'),
    (6, 'SMS_WHATSAPP'),
    (7, 'TELEFOON');

CREATE TABLE ENUMDAGDEEL_ENUM (
    ENUMDAGDEEL_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMDAGDEEL_ENUM (ENUMDAGDEEL_ENUM_ID, VALUE) VALUES
    (1, 'AVOND'),
    (2, 'MIDDAG'),
    (3, 'OCHTEND');

CREATE TABLE ENUMEINDRESULTAAT_ENUM (
    ENUMEINDRESULTAAT_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMEINDRESULTAAT_ENUM (ENUMEINDRESULTAAT_ENUM_ID, VALUE) VALUES
    (1, 'GEEN_CONTACT_MEER_KUNNEN_KRIJGEN'),
    (2, 'INWONER_AL_BEKEND_BIJ_SCHULDHULPVERLENING'),
    (3, 'INWONER_HEEFT_AL_EEN_ANDER_LOPEND_TRAJECT'),
    (4, 'INWONER_HEEFT_BETAALD_BETALINGSREGELING_GETROFFEN_VOOR_OPPAKKEN_MELDING'),
    (5, 'INWONER_HEEFT_ZELF_BETAALD_BETALINGSREGELING_GETROFFEN_NA_OPPAKKEN_MELDING'),
    (6, 'INWONER_PROBEERT_HET_ZELF_OP_TE_LOSSEN'),
    (7, 'INWONER_WIL_GEEN_HULP'),
    (8, 'NIET_OPGEPAKT'),
    (9, 'NIET_OPGEPAKT_BRP_UITSLUITING'),
    (10, 'NIET_OPGEPAKT_GEEN_CAPACITEIT'),
    (11, 'NIET_OPGEPAKT_INWONER_WIL_GEEN_CONTACT'),
    (12, 'VERWIJZING_FINANCIEEL'),
    (13, 'VERWIJZING_NIET_FINANCIEEL'),
    (14, 'VOORZIEN_VAN_INFORMATIE'),
    (15, '_BUDGET_ADVIES_EN_OF_QUICK_FIX');

CREATE TABLE ENUMSIGNAALPARTNER_ENUM (
    ENUMSIGNAALPARTNER_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMSIGNAALPARTNER_ENUM (ENUMSIGNAALPARTNER_ENUM_ID, VALUE) VALUES
    (1, 'BELASTINGDIENST'),
    (2, 'CAK_EIGEN_BIJDRAGE'),
    (3, 'CAK_ZORGVERZEKERINGEN'),
    (4, 'DIENST_TOESLAGEN'),
    (5, 'DUO'),
    (6, 'ENERGIE'),
    (7, 'HUUR'),
    (8, 'HYPOTHEEK'),
    (9, 'OVERIGE'),
    (10, 'WATER'),
    (11, 'ZORG');

CREATE TABLE CONTACTPOGING (
    CONTACTPOGING_ID VARCHAR2(255) PRIMARY KEY,
        BEREIKT NUMBER(1),
        DAGDEEL_ENUM_ID VARCHAR2(255),
        DATUM DATE,
        SOORT_ENUM_ID VARCHAR2(255)
);

CREATE TABLE GEMEENTE (
    GEMEENTE_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEMEENTECODE VARCHAR2(255),
        GEMEENTENAAM VARCHAR2(80),
        GEMEENTENAAM_NEN VARCHAR2(255),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(255),
        IS_OVERGEGAAN_IN_GEMEENTE_ID VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDEGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HUISLETTER VARCHAR2(255),
        HUISNUMMER VARCHAR2(255),
        HUISNUMMERTOEVOEGING VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        POSTCODE VARCHAR2(255),
        STATUS VARCHAR2(255),
        TYPEADRESSEERBAAROBJECT VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        ADRESCORRESPONDENTIE VARCHAR2(100),
        EMAILADRES VARCHAR2(80),
        FAXNUMMER VARCHAR2(20),
        IDENTIFICATIE VARCHAR2(255),
        KVKNUMMER VARCHAR2(20),
        NAAM VARCHAR2(200),
        RECHTSVORM VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE CLIENT (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        CODE VARCHAR2(80),
        GEZAGSDRAGERGEKEND NUMBER(1),
        JURIDISCHESTATUS VARCHAR2(80),
        WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE INGESCHREVENPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESHERKOMST VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        BESCHRIJVINGLOCATIE VARCHAR2(200),
        BUITENLANDSREISDOCUMENT VARCHAR2(80),
        BURGERLIJKESTAAT VARCHAR2(255),
        DATUMBEGINGELDIGHEIDVERBLIJFPLAATS DATE,
        DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS DATE,
        DATUMINSCHRIJVINGGEMEENTE DATE,
        DATUMOPSCHORTINGBIJHOUDING DATE,
        DATUMVERTREKUITNEDERLAND DATE,
        DATUMVESTIGINGNEDERLAND DATE,
        GEMEENTEVANINSCHRIJVING VARCHAR2(80),
        GEZINSRELATIE VARCHAR2(255),
        HEEFT_ALS_ADRES_NUMMERAANDUIDING_ID VARCHAR2(255),
        INDICATIEGEHEIM NUMBER(1),
        INGEZETENE NUMBER(1),
        LANDWAARNAARVERTROKKEN VARCHAR2(255),
        LANDWAARVANDAANINGESCHREVEN VARCHAR2(255),
        OUDER1 VARCHAR2(255),
        OUDER2 VARCHAR2(255),
        OUDER_1_INGESCHREVENPERSOON_ID VARCHAR2(255),
        OUDER_2_INGESCHREVENPERSOON_ID VARCHAR2(255),
        PARTNERID VARCHAR2(255),
        REDENEINDEBEWONING DATE,
        REDENOPSCHORTINGBIJHOUDING VARCHAR2(200),
        SIGNALERINGREISDOCUMENT NUMBER(1),
        VERBLIJFSTITEL VARCHAR2(255)
);

CREATE TABLE NATUURLIJKPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON VARCHAR2(50),
        AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
        AANHEFAANSCHRIJVING VARCHAR2(50),
        ACADEMISCHETITEL VARCHAR2(80),
        ACHTERNAAM VARCHAR2(100),
        ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        ATTRIBUTE VARCHAR2(255),
        BURGERSERVICENUMMER VARCHAR2(255),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        GEBOORTELAND VARCHAR2(255),
        GEBOORTEPLAATS VARCHAR2(200),
        GESLACHTSAANDUIDING VARCHAR2(255),
        GESLACHTSNAAM VARCHAR2(200),
        GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
        HANDLICHTING VARCHAR2(50),
        INDICATIEAFSCHERMINGPERSOONSGEGEVENS NUMBER(1),
        INDICATIEOVERLEDEN NUMBER(1),
        LANDOVERLIJDEN VARCHAR2(255),
        NATIONALITEIT VARCHAR2(100),
        OVERLIJDENSPLAATS VARCHAR2(200),
        VOORLETTERSAANSCHRIJVING VARCHAR2(20),
        VOORNAMEN VARCHAR2(200),
        VOORNAMENAANSCHRIJVING VARCHAR2(200),
        VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMUITSCHRIJVING DATE,
        DATUMVOORTZETTING DATE,
        FAXNUMMER VARCHAR2(20),
        INGESCHREVEN NUMBER(1),
        INOPRICHTING NUMBER(1),
        KVKNUMMER VARCHAR2(255),
        NNPID VARCHAR2(255),
        RECHTSVORM VARCHAR2(255),
        RSINNUMMER VARCHAR2(255),
        STATUTAIRENAAM VARCHAR2(255),
        STATUTAIREZETEL VARCHAR2(255),
        WEBSITEURL VARCHAR2(200)
);

CREATE TABLE KP_NTNTRLJKPRSN (
    KP_NTNTRLJKPRSN_ID VARCHAR2(255) PRIMARY KEY,
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255),
    NATUURLIJKPERSOON_ID VARCHAR2(255)
);

CREATE TABLE SIGNAALPARTNER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        TYPE_ENUM_ID VARCHAR2(255)
);

CREATE TABLE ZAAK (
    ZAAK_ID VARCHAR2(255) PRIMARY KEY,
        ARCHIEFNOMINATIE VARCHAR2(255),
        ATTRIBUTE VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMEINDEGEPLAND DATE,
        DATUMEINDEUITERLIJKEAFDOENING DATE,
        DATUMLAATSTEBETALING DATE,
        DATUMPUBLICATIE DATE,
        DATUMREGISTRATIE DATE,
        DATUMSTART DATE,
        DATUMVERNIETIGINGDOSSIER DATE,
        DOCUMENT VARCHAR2(255),
        DUURVERLENGING VARCHAR2(255),
        HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID VARCHAR2(255),
        INDICATIEBETALING VARCHAR2(255),
        INDICATIEDEELZAKEN VARCHAR2(255),
        INDICATIEOPSCHORTING VARCHAR2(255),
        IS_DEELZAAK_VAN_ZAAK_ID VARCHAR2(255),
        LEGES VARCHAR2(100),
        OMSCHRIJVING VARCHAR2(80),
        OMSCHRIJVINGRESULTAAT VARCHAR2(80),
        REDENOPSCHORTING VARCHAR2(200),
        REDENVERLENGING VARCHAR2(200),
        TOELICHTING VARCHAR2(255),
        TOELICHTINGRESULTAAT VARCHAR2(255),
        VERTROUWELIJKHEID VARCHAR2(255),
        ZAAKIDENTIFICATIE VARCHAR2(255),
        ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE VROEGSIGNAALZAAK (
    ZAAK_ID VARCHAR2(255) PRIMARY KEY,
        DATUM_OPGEPAKT DATE,
        EINDDATUM_MATCHINGPERIODE DATE,
        HEEFT_CONTACTPOGING_ID VARCHAR2(255),
        MATCHINGSDATUM DATE,
        OPGEPAKTDOOR_NIETNATUURLIJKPERSOON_ID VARCHAR2(255),
        OPGEPAKTNAMENS_GEMEENTE_ID VARCHAR2(255),
        RESULTAAT_ENUM_ID VARCHAR2(255),
        STARTDATUM_MATCHTINGPERIODE DATE
);

CREATE TABLE VROEGSIGNAAL (
    VROEGSIGNAAL_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG NUMBER(10,2),
        BETREFT_CLIENT_ID VARCHAR2(255),
        CRISISSIGNAAL NUMBER(1),
        ONTSTAANSDATUM DATE,
        OPGEPAKTIN_VROEGSIGNAALZAAK_ID VARCHAR2(255),
        SIGNAALDATUM DATE,
        STATUS VARCHAR2(255),
        VERZONDENDOOR_SIGNAALPARTNER_ID VARCHAR2(255),
        WARMEOVERDRACHT NUMBER(1)
);

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES INGESCHREVENPERSOON (RECHTSPERSOON_ID);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE NIETNATUURLIJKPERSOON ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE VROEGSIGNAALZAAK ADD CONSTRAINT FK_VROEGSIGNAALZAAK_GEN_ZAAK FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- Generalization to ZAAK

ALTER TABLE SIGNAALPARTNER ADD CONSTRAINT FK_SIGNAALPARTNER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_NTNTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_1 FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NIETNATUURLIJKPERSOON (many-to-many junction, Connector_ID: 152)

ALTER TABLE KP_NTNTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_2 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 152)

ALTER TABLE CONTACTPOGING ADD CONSTRAINT FK_CONTACTPOGING_DAGDEEL_ENUM_ID FOREIGN KEY (DAGDEEL_ENUM_ID) REFERENCES ENUMDAGDEEL_ENUM (ENUMDAGDEEL_ENUM_ID);
-- DAGDEEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE CONTACTPOGING ADD CONSTRAINT FK_CONTACTPOGING_SOORT_ENUM_ID FOREIGN KEY (SOORT_ENUM_ID) REFERENCES ENUMCONTACTSOORT_ENUM (ENUMCONTACTSOORT_ENUM_ID);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE GEMEENTE ADD CONSTRAINT FK_GEMEENTE_IS_OVERGEGAAN_IN FOREIGN KEY (IS_OVERGEGAAN_IN_GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- IS_OVERGEGAAN_IN (None to 0..*, Connector_ID: 341)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_HEEFT_ALS_ADRES FOREIGN KEY (HEEFT_ALS_ADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_ADRES (0..* to 0..1, Connector_ID: 349)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (OUDER_1_INGESCHREVENPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- OUDER_1 (None to None, Connector_ID: 170)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (OUDER_2_INGESCHREVENPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- OUDER_2 (None to None, Connector_ID: 171)

ALTER TABLE SIGNAALPARTNER ADD CONSTRAINT FK_SIGNAALPARTNER_TYPE_ENUM_ID FOREIGN KEY (TYPE_ENUM_ID) REFERENCES ENUMSIGNAALPARTNER_ENUM (ENUMSIGNAALPARTNER_ENUM_ID);
-- TYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VROEGSIGNAAL ADD CONSTRAINT FK_VROEGSIGNAAL_BETREFT FOREIGN KEY (BETREFT_CLIENT_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- BETREFT (0..* to 1, Connector_ID: 1504)

ALTER TABLE VROEGSIGNAAL ADD CONSTRAINT FK_VROEGSIGNAAL_OPGEPAKTIN FOREIGN KEY (OPGEPAKTIN_VROEGSIGNAALZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- OPGEPAKTIN (1..* to 0..1, Connector_ID: 1505)

ALTER TABLE VROEGSIGNAAL ADD CONSTRAINT FK_VROEGSIGNAAL_VERZONDENDOOR FOREIGN KEY (VERZONDENDOOR_SIGNAALPARTNER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- VERZONDENDOOR (0..* to 1, Connector_ID: 1507)

ALTER TABLE VROEGSIGNAALZAAK ADD CONSTRAINT FK_VROEGSIGNAALZAAK_HEEFT FOREIGN KEY (HEEFT_CONTACTPOGING_ID) REFERENCES CONTACTPOGING (CONTACTPOGING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1506)

ALTER TABLE VROEGSIGNAALZAAK ADD CONSTRAINT FK_VROEGSIGNAALZAAK_OPGEPAKTDOOR FOREIGN KEY (OPGEPAKTDOOR_NIETNATUURLIJKPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- OPGEPAKTDOOR (0..* to 1, Connector_ID: 1532)

ALTER TABLE VROEGSIGNAALZAAK ADD CONSTRAINT FK_VROEGSIGNAALZAAK_OPGEPAKTNAMENS FOREIGN KEY (OPGEPAKTNAMENS_GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- OPGEPAKTNAMENS (0..* to 1, Connector_ID: 1509)

ALTER TABLE VROEGSIGNAALZAAK ADD CONSTRAINT FK_VROEGSIGNAALZAAK_RESULTAAT_ENUM_ID FOREIGN KEY (RESULTAAT_ENUM_ID) REFERENCES ENUMEINDRESULTAAT_ENUM (ENUMEINDRESULTAAT_ENUM_ID);
-- RESULTAAT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (None to 0..*, Connector_ID: 243)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (None to 0..1, Connector_ID: 245)

