CREATE TABLE DAKLOOSHEID (
    DAKLOOSHEID_ID VARCHAR(255) PRIMARY KEY,
        DATUMEIND DATE,
        DATUMSTART DATE,
        GEMEENTEOORSPRONG VARCHAR(200),
        TOESTEMMINGGEMEENTELIJKBRIEFADRES BOOLEAN,
        TOESTEMMINGNACHTOPVANG BOOLEAN
);

CREATE TABLE CLIENT (
    CLIENT_ID VARCHAR(255) PRIMARY KEY,
        CODE VARCHAR(80),
        GEZAGSDRAGERGEKEND BOOLEAN,
        HEEFT_DAKLOOSHEID_ID VARCHAR(255),
        JURIDISCHESTATUS VARCHAR(80),
        WETTELIJKEVERTEGENWOORDIGING VARCHAR(80)
);

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT FOREIGN KEY (HEEFT_DAKLOOSHEID_ID) REFERENCES DAKLOOSHEID (DAKLOOSHEID_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1382)

