CREATE TABLE REDEN_AANVRAAG (
    REDEN_AANVRAAG_ID NUMBER PRIMARY KEY,
    DIENSTTYPE VARCHAR2(255),
    GEWENSTE_INGANGSDATUM DATE
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID NUMBER PRIMARY KEY,
    BTWCODE VARCHAR2(255),
    BTWOMSCHRIJVING VARCHAR2(80),
    KOSTENPLAATSSOORTCODE NUMBER(10,2),
    KOSTENPLAATSSOORTOMSCHRIJVING NUMBER(10,2),
    KOSTENPLAATSTYPECODE NUMBER(10,2),
    KOSTENPLAATSTYPEOMSCHRIJVING NUMBER(10,2),
    NAAM VARCHAR2(80),
    OMSCHRIJVING VARCHAR2(200)
);

CREATE TABLE DIENST (
    DIENST_ID NUMBER PRIMARY KEY,
    AANTAL_KOSTENDELERS NUMBER(10,2),
    BEGINDATUM DATE,
    EINDDATUM DATE,
    PERIODICITEIT_STATUSFORMULIER VARCHAR2(255),
    STARTDATUM_STATUSFORMULIER DATE
);

CREATE TABLE NORMAFWIJKING (
    NORMAFWIJKING_ID NUMBER PRIMARY KEY,
    DATUM_VASTSTELLING_NORMAFWIJKING DATE,
    DATUM_VASTSTELLING_VERWIJTBAARHEID DATE,
    IDENTIFICATIE DATE,
    MOTIVATIE_VERWIJTBAARHEID DATE,
    RECIDIVE VARCHAR2(255),
    TYPE_NORMAFWIJKING VARCHAR2(255),
    VERWIJTBAARHEID VARCHAR2(255)
);

CREATE TABLE AANVRAAG (
    AANVRAAG_ID NUMBER PRIMARY KEY,
    AANVRAAGDATUM DATE,
    CODE_ONTVANGENDE_GEMEENTE DATE
);

CREATE TABLE LEVERINGSCOMPONENT (
    LEVERINGSCOMPONENT_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2),
    EINDDATUM DATE,
    GEVALSRUBRIEK VARCHAR2(255),
    HEEFT_KOSTENPLAATS_ID NUMBER,
    OMSCHRIJVING_AFWIJKING VARCHAR2(255),
    PERCENTAGE VARCHAR2(255),
    PERIODE_STARTDATUM DATE,
    SOORT VARCHAR2(255)
);

CREATE TABLE PROFIEL (
    PROFIEL_ID NUMBER PRIMARY KEY,
    BEVAT_REDEN_AANVRAAG_ID NUMBER,
    DATUMAANVANGPROFIEL DATE,
    DATUMEINDEPROFIEL DATE,
    PROFIELTYPE VARCHAR2(200)
);

CREATE TABLE LEVERINGSSPECIFICATIE (
    LEVERINGSSPECIFICATIE_ID NUMBER PRIMARY KEY,
    BESTAAT_UIT_LEVERINGSCOMPONENT_ID NUMBER,
    PERIODE_EINDDATUM DATE,
    PERIODE_STARTDATUM DATE,
    PERIODICITEIT VARCHAR2(255)
);

CREATE TABLE CLIENT (
    CLIENT_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(80),
    DOET_AANVRAAG_AANVRAAG_ID NUMBER,
    GEZAGSDRAGERGEKEND NUMBER(1),
    HEEFT_PROFIEL_ID NUMBER,
    JURIDISCHESTATUS VARCHAR2(80),
    NEEMT_DIENST_AF_DIENST_ID NUMBER,
    VEROORZAAKT_NORMAFWIJKING_ID NUMBER,
    WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE LEVERINGSOPDRACHT (
    LEVERINGSOPDRACHT_ID NUMBER PRIMARY KEY,
    BESTAAT_UIT_LEVERINGSSPECIFICATIE_ID NUMBER,
    IN_KADER_VAN_DIENST_ID NUMBER,
    LEVERINGSKANAAL VARCHAR2(200)
);

CREATE TABLE DEBITEUR (
    DEBITEUR_ID NUMBER PRIMARY KEY,
    EIGEN_KENMERK VARCHAR2(255),
    OPVOERDATUM DATE,
    SOORT_DEBITEUR VARCHAR2(255),
    VERWIJST_CLIENT_ID NUMBER
);

CREATE TABLE TERUGVORDERINGSVERZOEK (
    TERUGVORDERINGSVERZOEK_ID NUMBER PRIMARY KEY,
    AANMAAKDATUM DATE,
    BEHANDELSTATUS_VERZOEK VARCHAR2(255),
    BETREFT_CLIENT_ID NUMBER,
    CATEGORIE VARCHAR2(255),
    FISCAAL VARCHAR2(255),
    PERIODE_EINDDATUM DATE,
    PERIODE_STARTDATUM DATE,
    PRIOTYPE DATE,
    REGELING VARCHAR2(255),
    SUBCATEGORIE VARCHAR2(255),
    TERUGVORDERINGSVERZOEK_BETREFT_DIENST_DIENST_ID NUMBER
);

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT FOREIGN KEY (HEEFT_PROFIEL_ID) REFERENCES PROFIEL (PROFIEL_ID);
-- HEEFT (1 to 1..*, Connector_ID: 947)

ALTER TABLE TERUGVORDERINGSVERZOEK ADD CONSTRAINT FK_TERUGVORDERINGSVERZOEK_BETREFT FOREIGN KEY (BETREFT_CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- BETREFT (0..* to 1..2, Connector_ID: 1636)

ALTER TABLE DEBITEUR ADD CONSTRAINT FK_DEBITEUR_VERWIJST FOREIGN KEY (VERWIJST_CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- VERWIJST (0..1 to 1, Connector_ID: 1655)

ALTER TABLE PROFIEL ADD CONSTRAINT FK_PROFIEL_BEVAT FOREIGN KEY (BEVAT_REDEN_AANVRAAG_ID) REFERENCES REDEN_AANVRAAG (REDEN_AANVRAAG_ID);
-- BEVAT (1 to 0..1, Connector_ID: 1678)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_VEROORZAAKT FOREIGN KEY (VEROORZAAKT_NORMAFWIJKING_ID) REFERENCES NORMAFWIJKING (NORMAFWIJKING_ID);
-- VEROORZAAKT (1 to 0..*, Connector_ID: 1695)

ALTER TABLE LEVERINGSOPDRACHT ADD CONSTRAINT FK_LEVERINGSOPDRACHT_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_LEVERINGSSPECIFICATIE_ID) REFERENCES LEVERINGSSPECIFICATIE (LEVERINGSSPECIFICATIE_ID);
-- BESTAAT_UIT (1..* to 1..1, Connector_ID: 1722)

ALTER TABLE LEVERINGSSPECIFICATIE ADD CONSTRAINT FK_LEVERINGSSPECIFICATIE_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_LEVERINGSCOMPONENT_ID) REFERENCES LEVERINGSCOMPONENT (LEVERINGSCOMPONENT_ID);
-- BESTAAT_UIT (1..* to 1..1, Connector_ID: 1724)

ALTER TABLE LEVERINGSCOMPONENT ADD CONSTRAINT FK_LEVERINGSCOMPONENT_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..* to 0..1, Connector_ID: 1726)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_NEEMT_DIENST_AF FOREIGN KEY (NEEMT_DIENST_AF_DIENST_ID) REFERENCES DIENST (DIENST_ID);
-- NEEMT_DIENST_AF (1..2 to 0..*, Connector_ID: 1733)

ALTER TABLE LEVERINGSOPDRACHT ADD CONSTRAINT FK_LEVERINGSOPDRACHT_IN_KADER_VAN FOREIGN KEY (IN_KADER_VAN_DIENST_ID) REFERENCES DIENST (DIENST_ID);
-- IN_KADER_VAN (1..1 to 1..*, Connector_ID: 1735)

ALTER TABLE TERUGVORDERINGSVERZOEK ADD CONSTRAINT FK_TERUGVORDERINGSVERZOEK_TERUGVORDERINGSVERZOEK_BETREFT_DIENST FOREIGN KEY (TERUGVORDERINGSVERZOEK_BETREFT_DIENST_DIENST_ID) REFERENCES DIENST (DIENST_ID);
-- TERUGVORDERINGSVERZOEK_BETREFT_DIENST (1..1 to 0..*, Connector_ID: 1736)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_DOET_AANVRAAG FOREIGN KEY (DOET_AANVRAAG_AANVRAAG_ID) REFERENCES AANVRAAG (AANVRAAG_ID);
-- DOET_AANVRAAG (1 to 0..*, Connector_ID: 1745)

