CREATE TABLE BOUWACTIVITEIT (
    BOUWACTIVITEIT_ID INTEGER PRIMARY KEY,
    BOUWJAARKLASSE VARCHAR(80),
    BOUWJAARTOT INTEGER,
    BOUWJAARVAN INTEGER,
    INDICATIE VARCHAR(255),
    OMSCHRIJVING VARCHAR(255)
);

CREATE TABLE FOTO (
    FOTO_ID INTEGER PRIMARY KEY,
    BESTANDSGROOTTE INTEGER,
    BESTANDSNAAM VARCHAR(200),
    BESTANDSTYPE VARCHAR(80),
    DATUMTIJD TIMESTAMP,
    LOCATIE VARCHAR(255),
    PIXELSX INTEGER,
    PIXELSY INTEGER
);

CREATE TABLE OORSPRONKELIJKEFUNCTIE (
    OORSPRONKELIJKEFUNCTIE_ID INTEGER PRIMARY KEY,
    FUNCTIE VARCHAR(200),
    FUNCTIESOORT VARCHAR(200),
    HOOFDCATEGORIE VARCHAR(200),
    HOOFDFUNCTIE BOOLEAN,
    SUBCATEGORIE VARCHAR(200),
    TOELICHTING TEXT,
    VERBIJZONDERING VARCHAR(200)
);

CREATE TABLE BOUWSTIJL (
    BOUWSTIJL_ID INTEGER PRIMARY KEY,
    HOOFDSTIJL VARCHAR(200),
    SUBSTIJL VARCHAR(200),
    TOELICHTING TEXT,
    ZUIVERHEID VARCHAR(200)
);

CREATE TABLE AMBACHT (
    AMBACHT_ID INTEGER PRIMARY KEY,
    AMBACHTSOORT VARCHAR(255),
    JAARAMBACHTTOT INTEGER,
    JAARAMBACHTVANAF INTEGER
);

CREATE TABLE TYPEMONUMENT_ENUM (
    TYPEMONUMENT_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO TYPEMONUMENT_ENUM (TYPEMONUMENT_ENUM_ID, VALUE) VALUES
    (1, 'GEMEENTELIJKMONUMENT'),
    (2, 'RIJKSMONUMENT');

CREATE TABLE BOUWTYPE (
    BOUWTYPE_ID INTEGER PRIMARY KEY,
    HOOFDCATEGORIE VARCHAR(200),
    SUBCATEGORIE VARCHAR(200),
    TOELICHTING TEXT
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR(200),
    DOCUMENTIDENTIFICATIE VARCHAR(255),
    DOCUMENTTITEL VARCHAR(200),
    VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE BESCHERMDE_STATUS (
    BESCHERMDE_STATUS_ID INTEGER PRIMARY KEY,
    BRONNEN VARCHAR(255),
    COMPLEX VARCHAR(200),
    DATUMINSCHRIJVINGREGISTER DATE,
    DOCUMENTATIE_DOCUMENT_ID INTEGER,
    GEMEENTELIJKMONUMENTCODE VARCHAR(80),
    GEZICHTSCODE VARCHAR(20),
    MONUMENT_FOTOS_FOTO_ID INTEGER,
    NAAM VARCHAR(200),
    OMSCHRIJVING TEXT,
    OPMERKINGEN TEXT,
    RIJKSMONUMENTCODE VARCHAR(80),
    TYPE_ENUM_ID INTEGER
);

CREATE TABLE KP_BSCHRMD_STTS_BWTYP (
    KP_BSCHRMD_STTS_BWTYP_ID INTEGER PRIMARY KEY,
    BESCHERMDE_STATUS_ID INTEGER,
    BOUWTYPE_ID INTEGER
);

CREATE TABLE KP_BSCHRMD_STTS_ORSPRNKLJKFNCT (
    KP_BSCHRMD_STTS_ORSPRNKLJKFNCT_ID INTEGER PRIMARY KEY,
    BESCHERMDE_STATUS_ID INTEGER,
    OORSPRONKELIJKEFUNCTIE_ID INTEGER
);

CREATE TABLE KP_BSCHRMD_STTS_AMBCHT (
    KP_BSCHRMD_STTS_AMBCHT_ID INTEGER PRIMARY KEY,
    BESCHERMDE_STATUS_ID INTEGER,
    AMBACHT_ID INTEGER
);

CREATE TABLE KP_BSCHRMD_STTS_BWCTVTT (
    KP_BSCHRMD_STTS_BWCTVTT_ID INTEGER PRIMARY KEY,
    BESCHERMDE_STATUS_ID INTEGER,
    BOUWACTIVITEIT_ID INTEGER
);

CREATE TABLE KP_BSCHRMD_STTS_BWSTJL (
    KP_BSCHRMD_STTS_BWSTJL_ID INTEGER PRIMARY KEY,
    BESCHERMDE_STATUS_ID INTEGER,
    BOUWSTIJL_ID INTEGER
);

ALTER TABLE KP_BSCHRMD_STTS_ORSPRNKLJKFNCT ADD CONSTRAINT FK_KP_BSCHRMD_STTS_ORSPRNKLJKFNCT_1 FOREIGN KEY (BESCHERMDE_STATUS_ID) REFERENCES BESCHERMDE_STATUS (BESCHERMDE_STATUS_ID);
-- BESCHERMDE_STATUS (many-to-many junction, Connector_ID: 1141)

ALTER TABLE KP_BSCHRMD_STTS_ORSPRNKLJKFNCT ADD CONSTRAINT FK_KP_BSCHRMD_STTS_ORSPRNKLJKFNCT_2 FOREIGN KEY (OORSPRONKELIJKEFUNCTIE_ID) REFERENCES OORSPRONKELIJKEFUNCTIE (OORSPRONKELIJKEFUNCTIE_ID);
-- OORSPRONKELIJKEFUNCTIE (many-to-many junction, Connector_ID: 1141)

ALTER TABLE KP_BSCHRMD_STTS_BWTYP ADD CONSTRAINT FK_KP_BSCHRMD_STTS_BWTYP_1 FOREIGN KEY (BESCHERMDE_STATUS_ID) REFERENCES BESCHERMDE_STATUS (BESCHERMDE_STATUS_ID);
-- BESCHERMDE_STATUS (many-to-many junction, Connector_ID: 1143)

ALTER TABLE KP_BSCHRMD_STTS_BWTYP ADD CONSTRAINT FK_KP_BSCHRMD_STTS_BWTYP_2 FOREIGN KEY (BOUWTYPE_ID) REFERENCES BOUWTYPE (BOUWTYPE_ID);
-- BOUWTYPE (many-to-many junction, Connector_ID: 1143)

ALTER TABLE KP_BSCHRMD_STTS_BWCTVTT ADD CONSTRAINT FK_KP_BSCHRMD_STTS_BWCTVTT_1 FOREIGN KEY (BESCHERMDE_STATUS_ID) REFERENCES BESCHERMDE_STATUS (BESCHERMDE_STATUS_ID);
-- BESCHERMDE_STATUS (many-to-many junction, Connector_ID: 1145)

ALTER TABLE KP_BSCHRMD_STTS_BWCTVTT ADD CONSTRAINT FK_KP_BSCHRMD_STTS_BWCTVTT_2 FOREIGN KEY (BOUWACTIVITEIT_ID) REFERENCES BOUWACTIVITEIT (BOUWACTIVITEIT_ID);
-- BOUWACTIVITEIT (many-to-many junction, Connector_ID: 1145)

ALTER TABLE KP_BSCHRMD_STTS_BWSTJL ADD CONSTRAINT FK_KP_BSCHRMD_STTS_BWSTJL_1 FOREIGN KEY (BESCHERMDE_STATUS_ID) REFERENCES BESCHERMDE_STATUS (BESCHERMDE_STATUS_ID);
-- BESCHERMDE_STATUS (many-to-many junction, Connector_ID: 1149)

ALTER TABLE KP_BSCHRMD_STTS_BWSTJL ADD CONSTRAINT FK_KP_BSCHRMD_STTS_BWSTJL_2 FOREIGN KEY (BOUWSTIJL_ID) REFERENCES BOUWSTIJL (BOUWSTIJL_ID);
-- BOUWSTIJL (many-to-many junction, Connector_ID: 1149)

ALTER TABLE KP_BSCHRMD_STTS_AMBCHT ADD CONSTRAINT FK_KP_BSCHRMD_STTS_AMBCHT_1 FOREIGN KEY (BESCHERMDE_STATUS_ID) REFERENCES BESCHERMDE_STATUS (BESCHERMDE_STATUS_ID);
-- BESCHERMDE_STATUS (many-to-many junction, Connector_ID: 1150)

ALTER TABLE KP_BSCHRMD_STTS_AMBCHT ADD CONSTRAINT FK_KP_BSCHRMD_STTS_AMBCHT_2 FOREIGN KEY (AMBACHT_ID) REFERENCES AMBACHT (AMBACHT_ID);
-- AMBACHT (many-to-many junction, Connector_ID: 1150)

ALTER TABLE BESCHERMDE_STATUS ADD CONSTRAINT FK_BESCHERMDE_STATUS_DOCUMENTATIE FOREIGN KEY (DOCUMENTATIE_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENTATIE (0..1 to 0..*, Connector_ID: 116)

ALTER TABLE BESCHERMDE_STATUS ADD CONSTRAINT FK_BESCHERMDE_STATUS_MONUMENT_FOTOS FOREIGN KEY (MONUMENT_FOTOS_FOTO_ID) REFERENCES FOTO (FOTO_ID);
-- MONUMENT_FOTOS (1 to 0..*, Connector_ID: 1148)

ALTER TABLE BESCHERMDE_STATUS ADD CONSTRAINT FK_BESCHERMDE_STATUS_TYPE_ENUM_ID FOREIGN KEY (TYPE_ENUM_ID) REFERENCES TYPEMONUMENT_ENUM (TYPEMONUMENT_ENUM_ID);
-- TYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

