CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR2(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR2(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR2(200),
        DOCUMENTIDENTIFICATIE VARCHAR2(255),
        DOCUMENTTITEL VARCHAR2(200),
        VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE OVERIGBENOEMDTERREIN (
    OVERIGBENOEMDTERREIN_ID VARCHAR2(255) PRIMARY KEY,
        GEBRUIKSDOELOVERIGBENOEMDTERREIN VARCHAR2(255),
        OVERIGBENOEMDTERREINIDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE SPORTLOCATIE (
    SPORTLOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200)
);

CREATE TABLE VELD (
    VELD_ID VARCHAR2(255) PRIMARY KEY,
        LIGT_OP_OVERIGBENOEMDTERREIN_ID VARCHAR2(255)
);

CREATE TABLE SPORTPARK (
    SPORTLOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        HEEFT_VELD_ID VARCHAR2(255),
        LIGT_OP_OVERIGBENOEMDTERREIN_ID VARCHAR2(255)
);

CREATE TABLE VERBLIJFSOBJECT (
    VERBLIJFSOBJECT_ID VARCHAR2(255) PRIMARY KEY,
        AANTALKAMERS VARCHAR2(255),
        BEGINGELDIGHEID DATE,
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDGELDIGHEID DATE,
        GEBRUIKSDOEL VARCHAR2(255),
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HOOGSTEBOUWLAAG VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        LAAGSTEBOUWLAAG VARCHAR2(255),
        ONTSLUITINGVERDIEPING VARCHAR2(255),
        OPPERVLAKTE NUMBER,
        SOORTWOONOBJECT VARCHAR2(255),
        STATUS VARCHAR2(255),
        TOEGANGBOUWLAAG VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE WIJK (
    WIJK_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(255),
        STATUS VARCHAR2(255),
        VERSIE NUMBER,
        WIJKCODE VARCHAR2(255),
        WIJKNAAM VARCHAR2(255)
);

CREATE TABLE BINNENLOCATIE (
    SPORTLOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        ADRES VARCHAR2(255),
        BEDIENT_WIJK_ID VARCHAR2(255),
        BOUWJAAR VARCHAR2(255),
        GEMEENTELIJK NUMBER(1),
        GESCHATTEKOSTENPERJAAR NUMBER(10,2),
        GYMZAAL NUMBER(1),
        INSPECTIERAPPORT_DOCUMENT_ID VARCHAR2(255),
        IS_GEVESTIGD_IN_VERBLIJFSOBJECT_ID VARCHAR2(255),
        KLOKURENONDERWIJS VARCHAR2(255),
        KLOKURENVERENIGINGEN VARCHAR2(255),
        LOCATIE VARCHAR2(255),
        ONDERHOUDSNIVEAU VARCHAR2(80),
        ONDERHOUDSSTATUS NUMBER,
        SPORTHAL NUMBER(1),
        VLOEROPPERVLAKTE NUMBER
);

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_GEN_SPORTLOCATIE FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- Generalization to SPORTLOCATIE

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_GEN_SPORTLOCATIE FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- Generalization to SPORTLOCATIE

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_BEDIENT FOREIGN KEY (BEDIENT_WIJK_ID) REFERENCES WIJK (WIJK_ID);
-- BEDIENT (0..* to 1, Connector_ID: 1093)

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_INSPECTIERAPPORT FOREIGN KEY (INSPECTIERAPPORT_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- INSPECTIERAPPORT (0..1 to 0..*, Connector_ID: 115)

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_IS_GEVESTIGD_IN FOREIGN KEY (IS_GEVESTIGD_IN_VERBLIJFSOBJECT_ID) REFERENCES VERBLIJFSOBJECT (VERBLIJFSOBJECT_ID);
-- IS_GEVESTIGD_IN (0..* to 0..1, Connector_ID: 1094)

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_HEEFT FOREIGN KEY (HEEFT_VELD_ID) REFERENCES VELD (VELD_ID);
-- HEEFT (0..1 to 0..*, Connector_ID: 1085)

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_LIGT_OP FOREIGN KEY (LIGT_OP_OVERIGBENOEMDTERREIN_ID) REFERENCES OVERIGBENOEMDTERREIN (OVERIGBENOEMDTERREIN_ID);
-- LIGT_OP (0..1 to 1, Connector_ID: 1084)

ALTER TABLE VELD ADD CONSTRAINT FK_VELD_LIGT_OP FOREIGN KEY (LIGT_OP_OVERIGBENOEMDTERREIN_ID) REFERENCES OVERIGBENOEMDTERREIN (OVERIGBENOEMDTERREIN_ID);
-- LIGT_OP (0..1 to 1, Connector_ID: 1082)

