CREATE TABLE REISDOCUMENT (
    REISDOCUMENT_ID VARCHAR2(255) PRIMARY KEY,
        AANDUIDINGINHOUDINGVERMISSING VARCHAR2(255),
        AUTORITEITVANAFGIFTE VARCHAR2(255),
        DATUMEINDEGELDIGHEIDDOCUMENT DATE,
        DATUMINGANGDOCUMENT DATE,
        DATUMINHOUDINGOFVERMISSING DATE,
        DATUMUITGIFTE DATE,
        REISDOCUMENTNUMMER VARCHAR2(255),
        SOORT VARCHAR2(255)
);

CREATE TABLE INGESCHREVENPERSOON (
    INGESCHREVENPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESHERKOMST VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        BESCHRIJVINGLOCATIE VARCHAR2(200),
        BUITENLANDSREISDOCUMENT VARCHAR2(80),
        BURGERLIJKESTAAT VARCHAR2(255),
        DATUMBEGINGELDIGHEIDVERBLIJFPLAATS DATE,
        DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS DATE,
        DATUMINSCHRIJVINGGEMEENTE DATE,
        DATUMOPSCHORTINGBIJHOUDING DATE,
        DATUMVERTREKUITNEDERLAND DATE,
        DATUMVESTIGINGNEDERLAND DATE,
        GEMEENTEVANINSCHRIJVING VARCHAR2(80),
        GEZINSRELATIE VARCHAR2(255),
        INDICATIEGEHEIM NUMBER(1),
        INGEZETENE NUMBER(1),
        IS_VERSTREKT_AAN_REISDOCUMENT_ID VARCHAR2(255),
        LANDWAARNAARVERTROKKEN VARCHAR2(255),
        LANDWAARVANDAANINGESCHREVEN VARCHAR2(255),
        OUDER1 VARCHAR2(255),
        OUDER2 VARCHAR2(255),
        OUDER_1_INGESCHREVENPERSOON_ID VARCHAR2(255),
        OUDER_2_INGESCHREVENPERSOON_ID VARCHAR2(255),
        PARTNERID VARCHAR2(255),
        REDENEINDEBEWONING DATE,
        REDENOPSCHORTINGBIJHOUDING VARCHAR2(200),
        SIGNALERINGREISDOCUMENT NUMBER(1),
        VERBLIJFSTITEL VARCHAR2(255)
);

CREATE TABLE INGEZETENE (
    INGESCHREVENPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        AANDUIDINGEUROPEESKIESRECHT NUMBER(1),
        AANDUIDINGUITGESLOTENKIESRECHT NUMBER(1),
        DATUMVERKRIJGINGVERBLIJFSTITEL DATE,
        DATUMVERLIESVERBLIJFSTITEL DATE,
        INDICATIEBLOKKERING VARCHAR2(255),
        INDICATIECURATELEREGISTER VARCHAR2(255),
        INDICATIEGEZAGMINDERJARIGE VARCHAR2(255)
);

ALTER TABLE INGEZETENE ADD CONSTRAINT FK_INGEZETENE_GEN_INGESCHREVENPERSOON FOREIGN KEY (INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_IS_VERSTREKT_AAN FOREIGN KEY (IS_VERSTREKT_AAN_REISDOCUMENT_ID) REFERENCES REISDOCUMENT (REISDOCUMENT_ID);
-- IS_VERSTREKT_AAN (1 to 0..*, Connector_ID: 169)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (OUDER_1_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- OUDER_1 (None to None, Connector_ID: 170)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (OUDER_2_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- OUDER_2 (None to None, Connector_ID: 171)

