CREATE TABLE [COLLECTIE] (
    [COLLECTIE_ID] INT PRIMARY KEY,
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [STANDPLAATS] (
    [STANDPLAATS_ID] INT PRIMARY KEY,
    [ADRES] VARCHAR(50),
    [BESCHRIJVING] VARCHAR(255),
    [NAAMINSTELLING] VARCHAR(80)
);

CREATE TABLE [TENTOONSTELLING] (
    [TENTOONSTELLING_ID] INT PRIMARY KEY,
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [OMSCHRIJVING] NVARCHAR(MAX),
    [SUBTITEL] VARCHAR(200),
    [TITEL] VARCHAR(80)
);

CREATE TABLE [INCIDENT] (
    [INCIDENT_ID] INT PRIMARY KEY,
    [DATUM] DATE,
    [LOCATIE] VARCHAR(255),
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [RECHTSPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [ADRESBINNENLAND] VARCHAR(255),
    [ADRESBUITENLAND] VARCHAR(255),
    [ADRESCORRESPONDENTIE] VARCHAR(100),
    [EMAILADRES] VARCHAR(80),
    [FAXNUMMER] VARCHAR(20),
    [IDENTIFICATIE] VARCHAR(255),
    [KVKNUMMER] VARCHAR(20),
    [NAAM] VARCHAR(200),
    [RECHTSVORM] VARCHAR(100),
    [REKENINGNUMMER] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20)
);

CREATE TABLE [BRUIKLEEN] (
    [BRUIKLEEN_ID] INT PRIMARY KEY,
    [AANVRAAGDOOR] VARCHAR(80),
    [DATUMAANVRAAG] DATE,
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [TOESTEMMINGDOOR] VARCHAR(80)
);

CREATE TABLE [HISTORISCH_PERSOON_] (
    [HISTORISCH_PERSOON__ID] INT PRIMARY KEY,
    [BEROEP] VARCHAR(200),
    [DATUMGEBOORTE] DATE,
    [DATUMOVERLIJDEN] DATE,
    [NAAM] VARCHAR(200),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [PUBLIEKTOEGANKELIJK] BIT,
    [WOONDEOP] VARCHAR(50)
);

CREATE TABLE [ZAAL] (
    [ZAAL_ID] INT PRIMARY KEY,
    [CAPACITEIT] INT,
    [NAAM] VARCHAR(80),
    [NUMMER] INT,
    [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [BELANGTYPE] (
    [BELANGTYPE_ID] INT PRIMARY KEY,
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [ROL] (
    [ROL_ID] INT PRIMARY KEY,
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [MEDEWERKER] (
    [MEDEWERKER_ID] INT PRIMARY KEY,
    [ACHTERNAAM] VARCHAR(200),
    [DATUMINDIENST] DATE,
    [DATUMUITDIENST] DATE,
    [EMAILADRES] VARCHAR(255),
    [EXTERN] BIT,
    [FUNCTIE] VARCHAR(50),
    [GESLACHTSAANDUIDING] VARCHAR(255),
    [MEDEWERKERIDENTIFICATIE] VARCHAR(255),
    [MEDEWERKERTOELICHTING] VARCHAR(255),
    [ROEPNAAM] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20),
    [VOORLETTERS] VARCHAR(20),
    [VOORVOEGSELACHTERNAAM] VARCHAR(255)
);

CREATE TABLE [BELANGHEBBENDE] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [DATUMSTART] DATE,
    [DATUMTOT] DATE
);

CREATE TABLE [LENER] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [OPMERKINGEN] NVARCHAR(MAX)
);

CREATE TABLE [KP_BRKLN_TNTNSTLLNG] (
    [KP_BRKLN_TNTNSTLLNG_ID] INT PRIMARY KEY,
    [BRUIKLEEN_ID] INT,
    [TENTOONSTELLING_ID] INT
);

CREATE TABLE [MUSEUMOBJECT] (
    [MUSEUMOBJECT_ID] INT PRIMARY KEY,
    [AFMETING] VARCHAR(255),
    [BETREFT_BRUIKLEEN_ID] INT,
    [BEZITTOT] DATE,
    [BEZITVANAF] DATE,
    [LOCATIE_STANDPLAATS_ID] INT,
    [MEDIUM] VARCHAR(255),
    [VERKRIJGING] VARCHAR(255)
);

CREATE TABLE [KP_TNTNSTLLNG_HSTRSCH_PRSN_] (
    [KP_TNTNSTLLNG_HSTRSCH_PRSN__ID] INT PRIMARY KEY,
    [TENTOONSTELLING_ID] INT,
    [HISTORISCH_PERSOON__ID] INT
);

CREATE TABLE [KP_TNTNSTLLNG_ZL] (
    [KP_TNTNSTLLNG_ZL_ID] INT PRIMARY KEY,
    [TENTOONSTELLING_ID] INT,
    [ZAAL_ID] INT
);

CREATE TABLE [SAMENSTELLER] (
    [MEDEWERKER_ID] INT PRIMARY KEY,
    [ROL] VARCHAR(80)
);

CREATE TABLE [KP_LNR_BRKLN] (
    [KP_LNR_BRKLN_ID] INT PRIMARY KEY,
    [LENER_ID] INT,
    [BRUIKLEEN_ID] INT
);

CREATE TABLE [KP_CLLCT_MSMBJCT] (
    [KP_CLLCT_MSMBJCT_ID] INT PRIMARY KEY,
    [COLLECTIE_ID] INT,
    [MUSEUMOBJECT_ID] INT
);

CREATE TABLE [KP_MSMBJCT_BLNGHBBND] (
    [KP_MSMBJCT_BLNGHBBND_ID] INT PRIMARY KEY,
    [MUSEUMOBJECT_ID] INT,
    [BELANGHEBBENDE_ID] INT
);

CREATE TABLE [KP_MSMBJCT_HSTRSCH_PRSN_] (
    [KP_MSMBJCT_HSTRSCH_PRSN__ID] INT PRIMARY KEY,
    [MUSEUMOBJECT_ID] INT,
    [HISTORISCH_PERSOON__ID] INT
);

CREATE TABLE [KP_INCDNT_MSMBJCT] (
    [KP_INCDNT_MSMBJCT_ID] INT PRIMARY KEY,
    [INCIDENT_ID] INT,
    [MUSEUMOBJECT_ID] INT
);

CREATE TABLE [KP_MSMBJCT_TNTNSTLLNG] (
    [KP_MSMBJCT_TNTNSTLLNG_ID] INT PRIMARY KEY,
    [MUSEUMOBJECT_ID] INT,
    [TENTOONSTELLING_ID] INT
);

CREATE TABLE [KP_SMNSTLLR_TNTNSTLLNG] (
    [KP_SMNSTLLR_TNTNSTLLNG_ID] INT PRIMARY KEY,
    [SAMENSTELLER_ID] INT,
    [TENTOONSTELLING_ID] INT
);

ALTER TABLE [BELANGHEBBENDE] ADD CONSTRAINT FK_BELANGHEBBENDE_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [LENER] ADD CONSTRAINT FK_LENER_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [SAMENSTELLER] ADD CONSTRAINT FK_SAMENSTELLER_GEN_MEDEWERKER FOREIGN KEY ([MEDEWERKER_ID]) REFERENCES [MEDEWERKER] ([MEDEWERKER_ID]);
-- Generalization to MEDEWERKER

ALTER TABLE [KP_TNTNSTLLNG_ZL] ADD CONSTRAINT FK_KP_TNTNSTLLNG_ZL_1 FOREIGN KEY ([TENTOONSTELLING_ID]) REFERENCES [TENTOONSTELLING] ([TENTOONSTELLING_ID]);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1099)

ALTER TABLE [KP_TNTNSTLLNG_ZL] ADD CONSTRAINT FK_KP_TNTNSTLLNG_ZL_2 FOREIGN KEY ([ZAAL_ID]) REFERENCES [ZAAL] ([ZAAL_ID]);
-- ZAAL (many-to-many junction, Connector_ID: 1099)

ALTER TABLE [KP_SMNSTLLR_TNTNSTLLNG] ADD CONSTRAINT FK_KP_SMNSTLLR_TNTNSTLLNG_1 FOREIGN KEY ([SAMENSTELLER_ID]) REFERENCES [SAMENSTELLER] ([MEDEWERKER_ID]);
-- SAMENSTELLER (many-to-many junction, Connector_ID: 1100)

ALTER TABLE [KP_SMNSTLLR_TNTNSTLLNG] ADD CONSTRAINT FK_KP_SMNSTLLR_TNTNSTLLNG_2 FOREIGN KEY ([TENTOONSTELLING_ID]) REFERENCES [TENTOONSTELLING] ([TENTOONSTELLING_ID]);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1100)

ALTER TABLE [KP_MSMBJCT_HSTRSCH_PRSN_] ADD CONSTRAINT FK_KP_MSMBJCT_HSTRSCH_PRSN__1 FOREIGN KEY ([MUSEUMOBJECT_ID]) REFERENCES [MUSEUMOBJECT] ([MUSEUMOBJECT_ID]);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1103)

ALTER TABLE [KP_MSMBJCT_HSTRSCH_PRSN_] ADD CONSTRAINT FK_KP_MSMBJCT_HSTRSCH_PRSN__2 FOREIGN KEY ([HISTORISCH_PERSOON__ID]) REFERENCES [HISTORISCH_PERSOON_] ([HISTORISCH_PERSOON__ID]);
-- HISTORISCH_PERSOON_ (many-to-many junction, Connector_ID: 1103)

ALTER TABLE [KP_MSMBJCT_TNTNSTLLNG] ADD CONSTRAINT FK_KP_MSMBJCT_TNTNSTLLNG_1 FOREIGN KEY ([MUSEUMOBJECT_ID]) REFERENCES [MUSEUMOBJECT] ([MUSEUMOBJECT_ID]);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1118)

ALTER TABLE [KP_MSMBJCT_TNTNSTLLNG] ADD CONSTRAINT FK_KP_MSMBJCT_TNTNSTLLNG_2 FOREIGN KEY ([TENTOONSTELLING_ID]) REFERENCES [TENTOONSTELLING] ([TENTOONSTELLING_ID]);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1118)

ALTER TABLE [KP_INCDNT_MSMBJCT] ADD CONSTRAINT FK_KP_INCDNT_MSMBJCT_1 FOREIGN KEY ([INCIDENT_ID]) REFERENCES [INCIDENT] ([INCIDENT_ID]);
-- INCIDENT (many-to-many junction, Connector_ID: 1122)

ALTER TABLE [KP_INCDNT_MSMBJCT] ADD CONSTRAINT FK_KP_INCDNT_MSMBJCT_2 FOREIGN KEY ([MUSEUMOBJECT_ID]) REFERENCES [MUSEUMOBJECT] ([MUSEUMOBJECT_ID]);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1122)

ALTER TABLE [KP_CLLCT_MSMBJCT] ADD CONSTRAINT FK_KP_CLLCT_MSMBJCT_1 FOREIGN KEY ([COLLECTIE_ID]) REFERENCES [COLLECTIE] ([COLLECTIE_ID]);
-- COLLECTIE (many-to-many junction, Connector_ID: 1126)

ALTER TABLE [KP_CLLCT_MSMBJCT] ADD CONSTRAINT FK_KP_CLLCT_MSMBJCT_2 FOREIGN KEY ([MUSEUMOBJECT_ID]) REFERENCES [MUSEUMOBJECT] ([MUSEUMOBJECT_ID]);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1126)

ALTER TABLE [KP_LNR_BRKLN] ADD CONSTRAINT FK_KP_LNR_BRKLN_1 FOREIGN KEY ([LENER_ID]) REFERENCES [LENER] ([RECHTSPERSOON_ID]);
-- LENER (many-to-many junction, Connector_ID: 1128)

ALTER TABLE [KP_LNR_BRKLN] ADD CONSTRAINT FK_KP_LNR_BRKLN_2 FOREIGN KEY ([BRUIKLEEN_ID]) REFERENCES [BRUIKLEEN] ([BRUIKLEEN_ID]);
-- BRUIKLEEN (many-to-many junction, Connector_ID: 1128)

ALTER TABLE [KP_BRKLN_TNTNSTLLNG] ADD CONSTRAINT FK_KP_BRKLN_TNTNSTLLNG_1 FOREIGN KEY ([BRUIKLEEN_ID]) REFERENCES [BRUIKLEEN] ([BRUIKLEEN_ID]);
-- BRUIKLEEN (many-to-many junction, Connector_ID: 1129)

ALTER TABLE [KP_BRKLN_TNTNSTLLNG] ADD CONSTRAINT FK_KP_BRKLN_TNTNSTLLNG_2 FOREIGN KEY ([TENTOONSTELLING_ID]) REFERENCES [TENTOONSTELLING] ([TENTOONSTELLING_ID]);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1129)

ALTER TABLE [KP_MSMBJCT_BLNGHBBND] ADD CONSTRAINT FK_KP_MSMBJCT_BLNGHBBND_1 FOREIGN KEY ([MUSEUMOBJECT_ID]) REFERENCES [MUSEUMOBJECT] ([MUSEUMOBJECT_ID]);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1130)

ALTER TABLE [KP_MSMBJCT_BLNGHBBND] ADD CONSTRAINT FK_KP_MSMBJCT_BLNGHBBND_2 FOREIGN KEY ([BELANGHEBBENDE_ID]) REFERENCES [BELANGHEBBENDE] ([RECHTSPERSOON_ID]);
-- BELANGHEBBENDE (many-to-many junction, Connector_ID: 1130)

ALTER TABLE [KP_TNTNSTLLNG_HSTRSCH_PRSN_] ADD CONSTRAINT FK_KP_TNTNSTLLNG_HSTRSCH_PRSN__1 FOREIGN KEY ([TENTOONSTELLING_ID]) REFERENCES [TENTOONSTELLING] ([TENTOONSTELLING_ID]);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1152)

ALTER TABLE [KP_TNTNSTLLNG_HSTRSCH_PRSN_] ADD CONSTRAINT FK_KP_TNTNSTLLNG_HSTRSCH_PRSN__2 FOREIGN KEY ([HISTORISCH_PERSOON__ID]) REFERENCES [HISTORISCH_PERSOON_] ([HISTORISCH_PERSOON__ID]);
-- HISTORISCH_PERSOON_ (many-to-many junction, Connector_ID: 1152)

ALTER TABLE [MUSEUMOBJECT] ADD CONSTRAINT FK_MUSEUMOBJECT_LOCATIE FOREIGN KEY ([LOCATIE_STANDPLAATS_ID]) REFERENCES [STANDPLAATS] ([STANDPLAATS_ID]);
-- LOCATIE (0..* to 0..1, Connector_ID: 1117)

ALTER TABLE [MUSEUMOBJECT] ADD CONSTRAINT FK_MUSEUMOBJECT_BETREFT FOREIGN KEY ([BETREFT_BRUIKLEEN_ID]) REFERENCES [BRUIKLEEN] ([BRUIKLEEN_ID]);
-- BETREFT (0..* to 0..1, Connector_ID: 1127)

