CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID INTEGER PRIMARY KEY,
    BTWCODE VARCHAR(255),
    BTWOMSCHRIJVING VARCHAR(80),
    KOSTENPLAATSSOORTCODE DECIMAL(10,2),
    KOSTENPLAATSSOORTOMSCHRIJVING DECIMAL(10,2),
    KOSTENPLAATSTYPECODE DECIMAL(10,2),
    KOSTENPLAATSTYPEOMSCHRIJVING DECIMAL(10,2),
    NAAM VARCHAR(80),
    OMSCHRIJVING VARCHAR(200)
);

CREATE TABLE ACTIVITEITSOORT (
    ACTIVITEITSOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE MAILING (
    MAILING_ID INTEGER PRIMARY KEY,
    DATUM DATE,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE TENTOONSTELLING (
    TENTOONSTELLING_ID INTEGER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    OMSCHRIJVING TEXT,
    SUBTITEL VARCHAR(200),
    TITEL VARCHAR(80)
);

CREATE TABLE VOORZIENING (
    VOORZIENING_ID INTEGER PRIMARY KEY,
    AANTALBESCHIKBAAR INTEGER,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE PROGRAMMASOORT (
    PROGRAMMASOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID INTEGER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR(255),
    ADRESBUITENLAND VARCHAR(255),
    ADRESCORRESPONDENTIE VARCHAR(100),
    EMAILADRES VARCHAR(80),
    FAXNUMMER VARCHAR(20),
    IDENTIFICATIE VARCHAR(255),
    KVKNUMMER VARCHAR(20),
    NAAM VARCHAR(200),
    RECHTSVORM VARCHAR(100),
    REKENINGNUMMER VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20)
);

CREATE TABLE ZAAL (
    ZAAL_ID INTEGER PRIMARY KEY,
    CAPACITEIT INTEGER,
    NAAM VARCHAR(80),
    NUMMER INTEGER,
    OMSCHRIJVING TEXT
);

CREATE TABLE DOELGROEP (
    DOELGROEP_ID INTEGER PRIMARY KEY,
    BESTAAT_UIT_DOELGROEP_ID INTEGER,
    BRANCH VARCHAR(80),
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT,
    SEGMENT VARCHAR(80)
);

CREATE TABLE RONDLEIDING (
    RONDLEIDING_ID INTEGER PRIMARY KEY,
    EINDTIJD TIMESTAMP,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT,
    STARTTIJD TIMESTAMP,
    VOOR_TENTOONSTELLING_ID INTEGER
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200),
    NUMMER VARCHAR(255)
);

CREATE TABLE KP_TNTNSTLLNG_ZL (
    KP_TNTNSTLLNG_ZL_ID INTEGER PRIMARY KEY,
    TENTOONSTELLING_ID INTEGER,
    ZAAL_ID INTEGER
);

CREATE TABLE PRODUCTIE_EENHEID (
    PRODUCTIE_EENHEID_ID INTEGER PRIMARY KEY,
    BETREFT_LEVERANCIER_ID INTEGER
);

CREATE TABLE RESERVERING (
    RESERVERING_ID INTEGER PRIMARY KEY,
    AANTAL INTEGER,
    BETREFT_PRODUCTIE_EENHEID_ID INTEGER,
    BETREFT_VOORZIENING_ID INTEGER,
    BETREFT_ZAAL_ID INTEGER,
    BTW VARCHAR(255),
    TIJDTOT TIMESTAMP,
    TIJDVANAF TIMESTAMP,
    TOTAALPRIJS DECIMAL(10,2)
);

CREATE TABLE ACTIVITEIT (
    ACTIVITEIT_ID INTEGER PRIMARY KEY,
    AANTALPERSONEN INTEGER,
    BESTAAT_UIT_ACTIVITEIT_ID INTEGER,
    HEEFT_RESERVERING_ID INTEGER,
    HEEFT_RONDLEIDING_ID INTEGER,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT,
    VAN_SOORT_ACTIVITEITSOORT_ID INTEGER
);

CREATE TABLE PROGRAMMA (
    PROGRAMMA_ID INTEGER PRIMARY KEY,
    BESTAAT_UIT_ACTIVITEIT_ID INTEGER,
    BTW VARCHAR(255),
    EINDTIJD TIMESTAMP,
    HEEFT_KOSTENPLAATS_ID INTEGER,
    LOCATIE VARCHAR(80),
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT,
    PRIJSEXCLUSIEFBTW DECIMAL(10,2),
    PUBLIEKSTAAK VARCHAR(80),
    SCHOOLNIVEAU VARCHAR(80),
    STARTTIJD TIMESTAMP
);

CREATE TABLE MUSEUMRELATIE (
    RECHTSPERSOON_ID INTEGER PRIMARY KEY,
    RELATIESOORT VARCHAR(80),
    VOOR_PROGRAMMA_ID INTEGER
);

CREATE TABLE KP_PRGRMM_PRGRMMSRT (
    KP_PRGRMM_PRGRMMSRT_ID INTEGER PRIMARY KEY,
    PROGRAMMA_ID INTEGER,
    PROGRAMMASOORT_ID INTEGER
);

CREATE TABLE KP_MSMRLT_DLGRP (
    KP_MSMRLT_DLGRP_ID INTEGER PRIMARY KEY,
    MUSEUMRELATIE_ID INTEGER,
    DOELGROEP_ID INTEGER
);

CREATE TABLE KP_MLNG_MSMRLT (
    KP_MLNG_MSMRLT_ID INTEGER PRIMARY KEY,
    MAILING_ID INTEGER,
    MUSEUMRELATIE_ID INTEGER
);

ALTER TABLE MUSEUMRELATIE ADD CONSTRAINT FK_MUSEUMRELATIE_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_TNTNSTLLNG_ZL ADD CONSTRAINT FK_KP_TNTNSTLLNG_ZL_1 FOREIGN KEY (TENTOONSTELLING_ID) REFERENCES TENTOONSTELLING (TENTOONSTELLING_ID);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1099)

ALTER TABLE KP_TNTNSTLLNG_ZL ADD CONSTRAINT FK_KP_TNTNSTLLNG_ZL_2 FOREIGN KEY (ZAAL_ID) REFERENCES ZAAL (ZAAL_ID);
-- ZAAL (many-to-many junction, Connector_ID: 1099)

ALTER TABLE KP_PRGRMM_PRGRMMSRT ADD CONSTRAINT FK_KP_PRGRMM_PRGRMMSRT_1 FOREIGN KEY (PROGRAMMA_ID) REFERENCES PROGRAMMA (PROGRAMMA_ID);
-- PROGRAMMA (many-to-many junction, Connector_ID: 1107)

ALTER TABLE KP_PRGRMM_PRGRMMSRT ADD CONSTRAINT FK_KP_PRGRMM_PRGRMMSRT_2 FOREIGN KEY (PROGRAMMASOORT_ID) REFERENCES PROGRAMMASOORT (PROGRAMMASOORT_ID);
-- PROGRAMMASOORT (many-to-many junction, Connector_ID: 1107)

ALTER TABLE KP_MLNG_MSMRLT ADD CONSTRAINT FK_KP_MLNG_MSMRLT_1 FOREIGN KEY (MAILING_ID) REFERENCES MAILING (MAILING_ID);
-- MAILING (many-to-many junction, Connector_ID: 1120)

ALTER TABLE KP_MLNG_MSMRLT ADD CONSTRAINT FK_KP_MLNG_MSMRLT_2 FOREIGN KEY (MUSEUMRELATIE_ID) REFERENCES MUSEUMRELATIE (RECHTSPERSOON_ID);
-- MUSEUMRELATIE (many-to-many junction, Connector_ID: 1120)

ALTER TABLE KP_MSMRLT_DLGRP ADD CONSTRAINT FK_KP_MSMRLT_DLGRP_1 FOREIGN KEY (MUSEUMRELATIE_ID) REFERENCES MUSEUMRELATIE (RECHTSPERSOON_ID);
-- MUSEUMRELATIE (many-to-many junction, Connector_ID: 1124)

ALTER TABLE KP_MSMRLT_DLGRP ADD CONSTRAINT FK_KP_MSMRLT_DLGRP_2 FOREIGN KEY (DOELGROEP_ID) REFERENCES DOELGROEP (DOELGROEP_ID);
-- DOELGROEP (many-to-many junction, Connector_ID: 1124)

ALTER TABLE RONDLEIDING ADD CONSTRAINT FK_RONDLEIDING_VOOR FOREIGN KEY (VOOR_TENTOONSTELLING_ID) REFERENCES TENTOONSTELLING (TENTOONSTELLING_ID);
-- VOOR (0..* to 0..1, Connector_ID: 1102)

ALTER TABLE RESERVERING ADD CONSTRAINT FK_RESERVERING_BETREFT FOREIGN KEY (BETREFT_ZAAL_ID) REFERENCES ZAAL (ZAAL_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1104)

ALTER TABLE RESERVERING ADD CONSTRAINT FK_RESERVERING_BETREFT_2 FOREIGN KEY (BETREFT_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1105)

ALTER TABLE PROGRAMMA ADD CONSTRAINT FK_PROGRAMMA_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..* to 1, Connector_ID: 1106)

ALTER TABLE RESERVERING ADD CONSTRAINT FK_RESERVERING_BETREFT_3 FOREIGN KEY (BETREFT_PRODUCTIE_EENHEID_ID) REFERENCES PRODUCTIE_EENHEID (PRODUCTIE_EENHEID_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1108)

ALTER TABLE PRODUCTIE_EENHEID ADD CONSTRAINT FK_PRODUCTIE_EENHEID_BETREFT FOREIGN KEY (BETREFT_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1109)

ALTER TABLE MUSEUMRELATIE ADD CONSTRAINT FK_MUSEUMRELATIE_VOOR FOREIGN KEY (VOOR_PROGRAMMA_ID) REFERENCES PROGRAMMA (PROGRAMMA_ID);
-- VOOR (1 to 0..*, Connector_ID: 1115)

ALTER TABLE DOELGROEP ADD CONSTRAINT FK_DOELGROEP_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_DOELGROEP_ID) REFERENCES DOELGROEP (DOELGROEP_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 1125)

ALTER TABLE PROGRAMMA ADD CONSTRAINT FK_PROGRAMMA_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 1135)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_HEEFT FOREIGN KEY (HEEFT_RESERVERING_ID) REFERENCES RESERVERING (RESERVERING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1136)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_VAN_SOORT FOREIGN KEY (VAN_SOORT_ACTIVITEITSOORT_ID) REFERENCES ACTIVITEITSOORT (ACTIVITEITSOORT_ID);
-- VAN_SOORT (0..* to 1, Connector_ID: 1137)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 1138)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_HEEFT_2 FOREIGN KEY (HEEFT_RONDLEIDING_ID) REFERENCES RONDLEIDING (RONDLEIDING_ID);
-- HEEFT (0..* to 0..1, Connector_ID: 1139)

