CREATE TABLE INGEZETENE (
    INGEZETENE_ID NUMBER PRIMARY KEY,
    AANDUIDINGEUROPEESKIESRECHT NUMBER(1),
    AANDUIDINGUITGESLOTENKIESRECHT NUMBER(1),
    DATUMVERKRIJGINGVERBLIJFSTITEL DATE,
    DATUMVERLIESVERBLIJFSTITEL DATE,
    INDICATIEBLOKKERING VARCHAR2(255),
    INDICATIECURATELEREGISTER VARCHAR2(255),
    INDICATIEGEZAGMINDERJARIGE VARCHAR2(255)
);

CREATE TABLE HUISHOUDEN (
    HUISHOUDEN_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDHUISHOUDEN DATE,
    DATUMEINDEGELDIGHEIDHUISHOUDEN DATE,
    HUISHOUDENGROOTTE VARCHAR2(255),
    HUISHOUDENNUMMER VARCHAR2(255),
    HUISHOUDENSOORT VARCHAR2(255)
);

CREATE TABLE OBJECT (
    OBJECT_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(200),
    DOMEIN VARCHAR2(200),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(50),
    INDICATIERISICO NUMBER(1),
    IS_HUISHOUDEN_ID NUMBER,
    IS_INGEZETENE_ID NUMBER,
    KADASTRALEAANDUIDING VARCHAR2(255),
    NAAM VARCHAR2(200),
    OBJECTTYPE VARCHAR2(255),
    TOELICHTING VARCHAR2(255)
);

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_IS FOREIGN KEY (IS_INGEZETENE_ID) REFERENCES INGEZETENE (INGEZETENE_ID);
-- IS (0..1 to 1, Connector_ID: 2080)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_IS_2 FOREIGN KEY (IS_HUISHOUDEN_ID) REFERENCES HUISHOUDEN (HUISHOUDEN_ID);
-- IS (0..1 to 1, Connector_ID: 2086)

