CREATE TABLE STATUSTYPE (
    STATUSTYPE_ID INTEGER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDSTATUSTYPE DATE,
    DATUMEINDEGELDIGHEIDSTATUSTYPE DATE,
    DOORLOOPTIJDSTATUS TIMESTAMP,
    STATUSTYPEOMSCHRIJVING VARCHAR(80),
    STATUSTYPEOMSCHRIJVINGGENERIEK VARCHAR(80),
    STATUSTYPEVOLGNUMMER VARCHAR(255)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID INTEGER PRIMARY KEY,
    ACHTERNAAM VARCHAR(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR(255),
    EXTERN BOOLEAN,
    FUNCTIE VARCHAR(50),
    GESLACHTSAANDUIDING VARCHAR(255),
    IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID INTEGER,
    IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID INTEGER,
    IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID INTEGER,
    MEDEWERKERIDENTIFICATIE VARCHAR(255),
    MEDEWERKERTOELICHTING VARCHAR(255),
    ROEPNAAM VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20),
    VOORLETTERS VARCHAR(20),
    VOORVOEGSELACHTERNAAM VARCHAR(255)
);

CREATE TABLE KP_BTRKKN_ZK (
    KP_BTRKKN_ZK_ID INTEGER PRIMARY KEY,
    BETROKKENE_ID INTEGER,
    ZAAK_ID INTEGER
);

CREATE TABLE ZAAK (
    ZAAK_ID INTEGER PRIMARY KEY,
    ARCHIEFNOMINATIE VARCHAR(255),
    DATUMEINDE DATE,
    DATUMEINDEGEPLAND DATE,
    DATUMEINDEUITERLIJKEAFDOENING DATE,
    DATUMLAATSTEBETALING DATE,
    DATUMPUBLICATIE DATE,
    DATUMREGISTRATIE DATE,
    DATUMSTART DATE,
    DATUMVERNIETIGINGDOSSIER DATE,
    DUURVERLENGING VARCHAR(255),
    HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID INTEGER,
    HEEFT_STATUS_ID INTEGER,
    INDICATIEBETALING VARCHAR(255),
    INDICATIEDEELZAKEN BOOLEAN,
    INDICATIEOPSCHORTING VARCHAR(255),
    IS_DEELZAAK_VAN_ZAAK_ID INTEGER,
    IS_VAN_ZAAKTYPE_ID INTEGER,
    LEGES VARCHAR(100),
    OMSCHRIJVING VARCHAR(80),
    OMSCHRIJVINGRESULTAAT VARCHAR(80),
    REDENOPSCHORTING VARCHAR(200),
    REDENVERLENGING VARCHAR(200),
    TOELICHTING VARCHAR(255),
    TOELICHTINGRESULTAAT VARCHAR(255),
    VERTROUWELIJKHEID VARCHAR(255),
    ZAAKIDENTIFICATIE VARCHAR(255),
    ZAAKNIVEAU VARCHAR(255)
);

CREATE TABLE BESLUITTYPE (
    BESLUITTYPE_ID INTEGER PRIMARY KEY,
    BESLUITCATEGORIE VARCHAR(255),
    BESLUITTYPEOMSCHRIJVING VARCHAR(80),
    BESLUITTYPEOMSCHRIJVINGGENERIEK VARCHAR(80),
    DATUMBEGINGELDIGHEIDBESLUITTYPE DATE,
    DATUMEINDEGELDIGHEIDBESLUITTYPE DATE,
    INDICATIEPUBLICATIE VARCHAR(255),
    PUBLICATIETEKST VARCHAR(255),
    PUBLICATIETERMIJN VARCHAR(255),
    REACTIETERMIJN VARCHAR(255)
);

CREATE TABLE DOCUMENTTYPE (
    DOCUMENTTYPE_ID INTEGER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDDOCUMENTTYPE DATE,
    DATUMEINDEGELDIGHEIDDOCUMENTTYPE DATE,
    DOCUMENTCATEGORIE VARCHAR(80),
    DOCUMENTTYPEOMSCHRIJVING VARCHAR(80),
    DOCUMENTTYPEOMSCHRIJVINGGENERIEK VARCHAR(80),
    DOCUMENTTYPETREFWOORD VARCHAR(255)
);

CREATE TABLE KP_MDWRKR_ORGNSTRSCHNHD (
    KP_MDWRKR_ORGNSTRSCHNHD_ID INTEGER PRIMARY KEY,
    MEDEWERKER_ID INTEGER,
    ORGANISATORISCHEEENHEID_ID INTEGER
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR(200),
    DOCUMENTIDENTIFICATIE VARCHAR(255),
    DOCUMENTTITEL VARCHAR(200),
    IS_VAN_DOCUMENTTYPE_ID INTEGER,
    VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE BETROKKENE (
    BETROKKENE_ID INTEGER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR(255),
    ADRESBUITENLAND VARCHAR(200),
    IDENTIFICATIE VARCHAR(50),
    IS_MEDEWERKER_ID INTEGER,
    IS_ORGANISATORISCHEEENHEID_ID INTEGER,
    NAAM VARCHAR(200)
);

CREATE TABLE KP_ZK_DCMNT (
    KP_ZK_DCMNT_ID INTEGER PRIMARY KEY,
    ZAAK_ID INTEGER,
    DOCUMENT_ID INTEGER
);

CREATE TABLE ENKELVOUDIGDOCUMENT (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    BESTANDSNAAM VARCHAR(255),
    DOCUMENTFORMAAT VARCHAR(255),
    DOCUMENTINHOUD VARCHAR(255),
    DOCUMENTLINK VARCHAR(200),
    DOCUMENTSTATUS VARCHAR(20),
    DOCUMENTTAAL VARCHAR(20),
    DOCUMENTVERSIE VARCHAR(255)
);

CREATE TABLE OBJECT (
    OBJECT_ID INTEGER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR(255),
    ADRESBUITENLAND VARCHAR(200),
    BETREFT_ZAAK_ID INTEGER,
    DOMEIN VARCHAR(200),
    GEOMETRIE GEOMETRY,
    IDENTIFICATIE VARCHAR(50),
    INDICATIERISICO BOOLEAN,
    IS_BESLUIT_ID INTEGER,
    KADASTRALEAANDUIDING VARCHAR(255),
    NAAM VARCHAR(200),
    OBJECTTYPE VARCHAR(255),
    TOELICHTING VARCHAR(255)
);

CREATE TABLE SAMENGESTELDDOCUMENT (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    OMVAT_ENKELVOUDIGDOCUMENT_ID INTEGER
);

CREATE TABLE ZAAKTYPE (
    ZAAKTYPE_ID INTEGER PRIMARY KEY,
    ARCHIEFCODE VARCHAR(20),
    DATUMBEGINGELDIGHEIDZAAKTYPE DATE,
    DATUMEINDEGELDIGHEIDZAAKTYPE DATE,
    DOORLOOPTIJDBEHANDELING TIMESTAMP,
    HEEFT_STATUSTYPE_ID INTEGER,
    INDICATIEPUBLICATIE VARCHAR(255),
    PUBLICATIETEKST VARCHAR(255),
    SERVICENORMBEHANDELING VARCHAR(255),
    TREFWOORD VARCHAR(255),
    VERTROUWELIJKAANDUIDING VARCHAR(20),
    ZAAKCATEGORIE VARCHAR(255),
    ZAAKTYPEOMSCHRIJVING VARCHAR(80),
    ZAAKTYPEOMSCHRIJVINGGENERIEK VARCHAR(80)
);

CREATE TABLE KP_BSLT_DCMNT (
    KP_BSLT_DCMNT_ID INTEGER PRIMARY KEY,
    BESLUIT_ID INTEGER,
    DOCUMENT_ID INTEGER
);

CREATE TABLE ORGANISATORISCHEEENHEID (
    ORGANISATORISCHEEENHEID_ID INTEGER PRIMARY KEY,
    DATUMONTSTAAN DATE,
    DATUMOPHEFFING DATE,
    EMAILADRES VARCHAR(255),
    FAXNUMMER VARCHAR(20),
    FORMATIE VARCHAR(255),
    IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID INTEGER,
    IS_GEHUISVEST_IN_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID INTEGER,
    IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID INTEGER,
    NAAM VARCHAR(50),
    NAAMVERKORT VARCHAR(255),
    OMSCHRIJVING VARCHAR(80),
    ORGANISATIEIDENTIFICATIE VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20),
    TOELICHTING VARCHAR(255)
);

CREATE TABLE BESLUIT (
    BESLUIT_ID INTEGER PRIMARY KEY,
    BESLUITIDENTIFICATIE VARCHAR(50),
    BESLUITTOELICHTING VARCHAR(255),
    DATUMBESLUIT DATE,
    DATUMPUBLICATIE DATE,
    DATUMSTART DATE,
    DATUMUITERLIJKEREACTIE DATE,
    DATUMVERVAL DATE,
    DATUMVERZENDING DATE,
    IS_UITKOMST_VAN_ZAAK_ID INTEGER,
    IS_VAN_BESLUITTYPE_ID INTEGER,
    IS_VASTGELEGD_IN_DOCUMENT_ID INTEGER,
    OMSCHRIJVING VARCHAR(200),
    REDENVERVAL VARCHAR(255)
);

CREATE TABLE KP_ZK_MDWRKR (
    KP_ZK_MDWRKR_ID INTEGER PRIMARY KEY,
    ZAAK_ID INTEGER,
    MEDEWERKER_ID INTEGER
);

CREATE TABLE STATUS (
    STATUS_ID INTEGER PRIMARY KEY,
    DATUMSTATUSGEZET DATE,
    INDICATIEIAATSTGEZETTESTATUS VARCHAR(255),
    IS_VAN_STATUSTYPE_ID INTEGER,
    STATUSTOELICHTING VARCHAR(255)
);

CREATE TABLE VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (
    VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID INTEGER PRIMARY KEY
);

ALTER TABLE SAMENGESTELDDOCUMENT ADD CONSTRAINT FK_SAMENGESTELDDOCUMENT_GEN_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- Generalization to DOCUMENT

ALTER TABLE ENKELVOUDIGDOCUMENT ADD CONSTRAINT FK_ENKELVOUDIGDOCUMENT_GEN_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- Generalization to DOCUMENT

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_BSLT_DCMNT ADD CONSTRAINT FK_KP_BSLT_DCMNT_1 FOREIGN KEY (BESLUIT_ID) REFERENCES BESLUIT (BESLUIT_ID);
-- BESLUIT (many-to-many junction, Connector_ID: 2150)

ALTER TABLE KP_BSLT_DCMNT ADD CONSTRAINT FK_KP_BSLT_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2150)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_1 FOREIGN KEY (BETROKKENE_ID) REFERENCES BETROKKENE (BETROKKENE_ID);
-- BETROKKENE (many-to-many junction, Connector_ID: 2164)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_2 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2164)

ALTER TABLE KP_MDWRKR_ORGNSTRSCHNHD ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_1 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2175)

ALTER TABLE KP_MDWRKR_ORGNSTRSCHNHD ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_2 FOREIGN KEY (ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- ORGANISATORISCHEEENHEID (many-to-many junction, Connector_ID: 2175)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_DEEL_VAN FOREIGN KEY (IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_DEEL_VAN (1 to 0..1, Connector_ID: 2059)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_GEHUISVEST_IN FOREIGN KEY (IS_GEHUISVEST_IN_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID) REFERENCES VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID);
-- IS_GEHUISVEST_IN (1..* to 1, Connector_ID: 2062)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_VAN FOREIGN KEY (IS_VAN_BESLUITTYPE_ID) REFERENCES BESLUITTYPE (BESLUITTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2066)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_IS FOREIGN KEY (IS_BESLUIT_ID) REFERENCES BESLUIT (BESLUIT_ID);
-- IS (0..1 to 1.., Connector_ID: 2071)

ALTER TABLE STATUS ADD CONSTRAINT FK_STATUS_IS_VAN FOREIGN KEY (IS_VAN_STATUSTYPE_ID) REFERENCES STATUSTYPE (STATUSTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2090)

ALTER TABLE ZAAKTYPE ADD CONSTRAINT FK_ZAAKTYPE_HEEFT FOREIGN KEY (HEEFT_STATUSTYPE_ID) REFERENCES STATUSTYPE (STATUSTYPE_ID);
-- HEEFT (1 to 1..*, Connector_ID: 2093)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY (IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2095)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT FOREIGN KEY (HEEFT_STATUS_ID) REFERENCES STATUS (STATUS_ID);
-- HEEFT (1 to 0..*, Connector_ID: 2101)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_UITKOMST_VAN FOREIGN KEY (IS_UITKOMST_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_UITKOMST_VAN (0..* to 1, Connector_ID: 2112)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_BETREFT FOREIGN KEY (BETREFT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- BETREFT (0..1 to 1, Connector_ID: 2117)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY (IS_VAN_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_IS_VAN FOREIGN KEY (IS_VAN_DOCUMENTTYPE_ID) REFERENCES DOCUMENTTYPE (DOCUMENTTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2127)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_VASTGELEGD_IN FOREIGN KEY (IS_VASTGELEGD_IN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- IS_VASTGELEGD_IN (0..1 to 0..1, Connector_ID: 2149)

ALTER TABLE SAMENGESTELDDOCUMENT ADD CONSTRAINT FK_SAMENGESTELDDOCUMENT_OMVAT FOREIGN KEY (OMVAT_ENKELVOUDIGDOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- OMVAT (0..1 to 2..*, Connector_ID: 2155)

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_IS FOREIGN KEY (IS_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS (0..1 to 1, Connector_ID: 2161)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJK_VOOR FOREIGN KEY (IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_VERANTWOORDELIJK_VOOR (0..1 to 0..1, Connector_ID: 2166)

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_IS_2 FOREIGN KEY (IS_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- IS (0..1 to 1, Connector_ID: 2167)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY (IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2170)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_CONTACTPERSOON_VOOR FOREIGN KEY (IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_CONTACTPERSOON_VOOR (0..1 to 0..1, Connector_ID: 2185)

