CREATE TABLE BEPERKINGSGEBIED (
    GEBIEDSAANWIJZING_ID NUMBER PRIMARY KEY,
    GROEP VARCHAR2(200),
    NAAM VARCHAR2(200)
);

CREATE TABLE FUNCTIE (
    GEBIEDSAANWIJZING_ID NUMBER PRIMARY KEY,
    GROEP VARCHAR2(200),
    NAAM VARCHAR2(200)
);

CREATE TABLE KP_JRDSCH_RGL_LCT (
    KP_JRDSCH_RGL_LCT_ID NUMBER PRIMARY KEY,
    JURIDISCHE_REGEL_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE VERZOEK (
    VERZOEK_ID NUMBER PRIMARY KEY,
    AKKOORDVERKLARING NUMBER(1),
    AMBTSHALVE NUMBER(1),
    BEHANDELAAR_UITVOERENDE_INSTANTIE_ID NUMBER,
    BETREFT_EERDER_VERZOEK_VERZOEK_ID NUMBER,
    DATUMINDIENING DATE,
    DOEL_ENUM_ID NUMBER,
    NAAM VARCHAR2(200),
    REFERENTIEAANVRAGER VARCHAR2(200),
    TOELICHTINGLATERAANTELEVERENINFORMATIE CLOB,
    TOELICHTINGNIETAANTELEVERENINFORMATIE CLOB,
    TOELICHTINGVERZOEK CLOB,
    TYPE_ENUM_ID NUMBER,
    VERZOEKNUMMER VARCHAR2(80),
    VOLGNUMMER VARCHAR2(80)
);

CREATE TABLE KP_TPSBR_RGL_LCT (
    KP_TPSBR_RGL_LCT_ID NUMBER PRIMARY KEY,
    TOEPASBARE_REGEL_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE KP_VRZK_LCT (
    KP_VRZK_LCT_ID NUMBER PRIMARY KEY,
    VERZOEK_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE INITIATIEFNEMER (
    INITIATIEFNEMER_ID NUMBER PRIMARY KEY,
    HEEFT_ALS_VERANTWOORDELIJKE_VERZOEK_ID NUMBER
);

CREATE TABLE UITVOERENDE_INSTANTIE (
    UITVOERENDE_INSTANTIE_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(200)
);

CREATE TABLE KP_VRZK_ACTVTT (
    KP_VRZK_ACTVTT_ID NUMBER PRIMARY KEY,
    VERZOEK_ID NUMBER,
    ACTIVITEIT_ID NUMBER
);

CREATE TABLE TYPE_VERZOEK_ENUM (
    TYPE_VERZOEK_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO TYPE_VERZOEK_ENUM (TYPE_VERZOEK_ENUM_ID, VALUE) VALUES
    (1, 'AANVRAAG_MAATWERKVOORSCHRIFT'),
    (2, 'AANVRAAG_TOESTEMMING_GELIJKWAARDIGE_MAATREGEL'),
    (3, 'AANVRAAG_VERGUNNING'),
    (4, 'INFORMATIE'),
    (5, 'INFORMATIE_ONGEWOON_VOORVAL'),
    (6, 'MELDING'),
    (7, 'MELDING_GELIJKWAARDIGE_MAATREGEL');

CREATE TABLE TOEPASBARE_REGEL (
    TOEPASBARE_REGEL_ID NUMBER PRIMARY KEY,
    BETREFT_ACTIVITEIT_ID NUMBER,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    DOMEIN VARCHAR2(255),
    NAAM VARCHAR2(200),
    OMSCHRIJVING CLOB,
    SOORTAANSLUITPUNT VARCHAR2(200),
    TOESTEMMING VARCHAR2(200)
);

CREATE TABLE GEBIEDSAANWIJZING (
    GEBIEDSAANWIJZING_ID NUMBER PRIMARY KEY,
    GROEP VARCHAR2(200),
    NAAM VARCHAR2(200),
    NEN3610ID VARCHAR2(80)
);

CREATE TABLE LOCATIE (
    LOCATIE_ID NUMBER PRIMARY KEY,
    HOOGTE NUMBER,
    NAAM VARCHAR2(200),
    NEN3610ID VARCHAR2(80)
);

CREATE TABLE KP_TPSBR_RGL_JRDSCH_RGL (
    KP_TPSBR_RGL_JRDSCH_RGL_ID NUMBER PRIMARY KEY,
    TOEPASBARE_REGEL_ID NUMBER,
    JURIDISCHE_REGEL_ID NUMBER
);

CREATE TABLE KP_ACTVTT_LCT (
    KP_ACTVTT_LCT_ID NUMBER PRIMARY KEY,
    ACTIVITEIT_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE KP_JRDSCH_RGL_ACTVTT (
    KP_JRDSCH_RGL_ACTVTT_ID NUMBER PRIMARY KEY,
    JURIDISCHE_REGEL_ID NUMBER,
    ACTIVITEIT_ID NUMBER
);

CREATE TABLE DOEL_VERZOEK_ENUM (
    DOEL_VERZOEK_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO DOEL_VERZOEK_ENUM (DOEL_VERZOEK_ENUM_ID, VALUE) VALUES
    (1, 'AANVULLEN'),
    (2, 'INITIEREN'),
    (3, 'INTREKKEN'),
    (4, 'VOOROVERLEG');

CREATE TABLE JURIDISCHE_REGEL (
    JURIDISCHE_REGEL_ID NUMBER PRIMARY KEY,
    DATUMBEKEND DATE,
    DATUMEINDEGELDIGHEID DATE,
    DATUMINWERKING DATE,
    DATUMSTART DATE,
    IS_OPGENOMEN_IN_REGELTEKST_ID NUMBER,
    OMSCHRIJVING CLOB,
    REGELTEKST VARCHAR2(200),
    THEMA VARCHAR2(200)
);

CREATE TABLE REGELTEKST (
    REGELTEKST_ID NUMBER PRIMARY KEY,
    IDENTIFICATIE VARCHAR2(200),
    IS_GERELATEERD_REGELTEKST_ID NUMBER,
    OMSCHRIJVING CLOB,
    TEKST CLOB,
    WERKINGSGEBIED_REGELTEKST_ID NUMBER
);

CREATE TABLE KP_RGLTKST_LCT (
    KP_RGLTKST_LCT_ID NUMBER PRIMARY KEY,
    REGELTEKST_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE ACTIVITEIT (
    ACTIVITEIT_ID NUMBER PRIMARY KEY,
    BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID NUMBER,
    GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID NUMBER,
    GROEP VARCHAR2(200),
    NAAM VARCHAR2(200),
    NEN3610ID VARCHAR2(80)
);

CREATE TABLE KP_GBDSNWJZNG_LCT (
    KP_GBDSNWJZNG_LCT_ID NUMBER PRIMARY KEY,
    GEBIEDSAANWIJZING_ID NUMBER,
    LOCATIE_ID NUMBER
);

ALTER TABLE BEPERKINGSGEBIED ADD CONSTRAINT FK_BEPERKINGSGEBIED_GEN_GEBIEDSAANWIJZING FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- Generalization to GEBIEDSAANWIJZING

ALTER TABLE FUNCTIE ADD CONSTRAINT FK_FUNCTIE_GEN_GEBIEDSAANWIJZING FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- Generalization to GEBIEDSAANWIJZING

ALTER TABLE KP_TPSBR_RGL_LCT ADD CONSTRAINT FK_KP_TPSBR_RGL_LCT_1 FOREIGN KEY (TOEPASBARE_REGEL_ID) REFERENCES TOEPASBARE_REGEL (TOEPASBARE_REGEL_ID);
-- TOEPASBARE_REGEL (many-to-many junction, Connector_ID: 653)

ALTER TABLE KP_TPSBR_RGL_LCT ADD CONSTRAINT FK_KP_TPSBR_RGL_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 653)

ALTER TABLE KP_TPSBR_RGL_JRDSCH_RGL ADD CONSTRAINT FK_KP_TPSBR_RGL_JRDSCH_RGL_1 FOREIGN KEY (TOEPASBARE_REGEL_ID) REFERENCES TOEPASBARE_REGEL (TOEPASBARE_REGEL_ID);
-- TOEPASBARE_REGEL (many-to-many junction, Connector_ID: 667)

ALTER TABLE KP_TPSBR_RGL_JRDSCH_RGL ADD CONSTRAINT FK_KP_TPSBR_RGL_JRDSCH_RGL_2 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 667)

ALTER TABLE KP_JRDSCH_RGL_LCT ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_JRDSCH_RGL_LCT ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_GBDSNWJZNG_LCT ADD CONSTRAINT FK_KP_GBDSNWJZNG_LCT_1 FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- GEBIEDSAANWIJZING (many-to-many junction, Connector_ID: 674)

ALTER TABLE KP_GBDSNWJZNG_LCT ADD CONSTRAINT FK_KP_GBDSNWJZNG_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 674)

ALTER TABLE KP_JRDSCH_RGL_ACTVTT ADD CONSTRAINT FK_KP_JRDSCH_RGL_ACTVTT_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 677)

ALTER TABLE KP_JRDSCH_RGL_ACTVTT ADD CONSTRAINT FK_KP_JRDSCH_RGL_ACTVTT_2 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 677)

ALTER TABLE KP_ACTVTT_LCT ADD CONSTRAINT FK_KP_ACTVTT_LCT_1 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 680)

ALTER TABLE KP_ACTVTT_LCT ADD CONSTRAINT FK_KP_ACTVTT_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 680)

ALTER TABLE KP_RGLTKST_LCT ADD CONSTRAINT FK_KP_RGLTKST_LCT_1 FOREIGN KEY (REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- REGELTEKST (many-to-many junction, Connector_ID: 684)

ALTER TABLE KP_RGLTKST_LCT ADD CONSTRAINT FK_KP_RGLTKST_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 684)

ALTER TABLE KP_VRZK_LCT ADD CONSTRAINT FK_KP_VRZK_LCT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 692)

ALTER TABLE KP_VRZK_LCT ADD CONSTRAINT FK_KP_VRZK_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 692)

ALTER TABLE KP_VRZK_ACTVTT ADD CONSTRAINT FK_KP_VRZK_ACTVTT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 693)

ALTER TABLE KP_VRZK_ACTVTT ADD CONSTRAINT FK_KP_VRZK_ACTVTT_2 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 693)

ALTER TABLE TOEPASBARE_REGEL ADD CONSTRAINT FK_TOEPASBARE_REGEL_BETREFT FOREIGN KEY (BETREFT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BETREFT (0..* to 1, Connector_ID: 679)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_BOVENLIGGENDE_ACTIVITEIT FOREIGN KEY (BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BOVENLIGGENDE_ACTIVITEIT (1 to 0..1, Connector_ID: 681)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_GERELATEERDE_ACTIVITEIT FOREIGN KEY (GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- GERELATEERDE_ACTIVITEIT (1 to 0..1, Connector_ID: 682)

ALTER TABLE JURIDISCHE_REGEL ADD CONSTRAINT FK_JURIDISCHE_REGEL_IS_OPGENOMEN_IN FOREIGN KEY (IS_OPGENOMEN_IN_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- IS_OPGENOMEN_IN (1..* to 1, Connector_ID: 683)

ALTER TABLE REGELTEKST ADD CONSTRAINT FK_REGELTEKST_IS_GERELATEERD FOREIGN KEY (IS_GERELATEERD_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- IS_GERELATEERD (0..1 to 0..*, Connector_ID: 685)

ALTER TABLE REGELTEKST ADD CONSTRAINT FK_REGELTEKST_WERKINGSGEBIED FOREIGN KEY (WERKINGSGEBIED_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- WERKINGSGEBIED (0..1 to 0..*, Connector_ID: 687)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BETREFT_EERDER_VERZOEK FOREIGN KEY (BETREFT_EERDER_VERZOEK_VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- BETREFT_EERDER_VERZOEK (0..1 to 0..*, Connector_ID: 690)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BEHANDELAAR FOREIGN KEY (BEHANDELAAR_UITVOERENDE_INSTANTIE_ID) REFERENCES UITVOERENDE_INSTANTIE (UITVOERENDE_INSTANTIE_ID);
-- BEHANDELAAR (0..* to 0..1, Connector_ID: 695)

ALTER TABLE INITIATIEFNEMER ADD CONSTRAINT FK_INITIATIEFNEMER_HEEFT_ALS_VERANTWOORDELIJKE FOREIGN KEY (HEEFT_ALS_VERANTWOORDELIJKE_VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- HEEFT_ALS_VERANTWOORDELIJKE (1 to 1..*, Connector_ID: 705)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_DOEL_ENUM_ID FOREIGN KEY (DOEL_ENUM_ID) REFERENCES DOEL_VERZOEK_ENUM (DOEL_VERZOEK_ENUM_ID);
-- DOEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_TYPE_ENUM_ID FOREIGN KEY (TYPE_ENUM_ID) REFERENCES DOEL_VERZOEK_ENUM (DOEL_VERZOEK_ENUM_ID);
-- TYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

