CREATE TABLE `UITVOERENDE_INSTANTIE` (
    `UITVOERENDE_INSTANTIE_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `ZAAKTYPE` (
    `ZAAKTYPE_ID` INT PRIMARY KEY,
    `ARCHIEFCODE` VARCHAR(20),
    `DATUMBEGINGELDIGHEIDZAAKTYPE` DATE,
    `DATUMEINDEGELDIGHEIDZAAKTYPE` DATE,
    `DOORLOOPTIJDBEHANDELING` DATETIME,
    `INDICATIEPUBLICATIE` VARCHAR(255),
    `PUBLICATIETEKST` VARCHAR(255),
    `SERVICENORMBEHANDELING` VARCHAR(255),
    `TREFWOORD` VARCHAR(255),
    `VERTROUWELIJKAANDUIDING` VARCHAR(20),
    `ZAAKCATEGORIE` VARCHAR(255),
    `ZAAKTYPEOMSCHRIJVING` VARCHAR(80),
    `ZAAKTYPEOMSCHRIJVINGGENERIEK` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `RECHTSPERSOON` (
    `RECHTSPERSOON_ID` INT PRIMARY KEY,
    `ADRESBINNENLAND` VARCHAR(255),
    `ADRESBUITENLAND` VARCHAR(255),
    `ADRESCORRESPONDENTIE` VARCHAR(100),
    `EMAILADRES` VARCHAR(80),
    `FAXNUMMER` VARCHAR(20),
    `IDENTIFICATIE` VARCHAR(255),
    `KVKNUMMER` VARCHAR(20),
    `NAAM` VARCHAR(200),
    `RECHTSVORM` VARCHAR(100),
    `REKENINGNUMMER` VARCHAR(255),
    `TELEFOONNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `LOCATIE` (
    `LOCATIE_ID` INT PRIMARY KEY,
    `HOOGTE` INT,
    `NAAM` VARCHAR(200),
    `NEN3610ID` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `DOCUMENT` (
    `DOCUMENT_ID` INT PRIMARY KEY,
    `COCUMENTBESCHRIJVING` VARCHAR(255),
    `DATUMCREATIEDOCUMENT` DATE,
    `DATUMONTVANGSTDOCUMENT` DATE,
    `DATUMVERZENDINGDOCUMENT` DATE,
    `DOCUMENTAUTEUR` VARCHAR(200),
    `DOCUMENTIDENTIFICATIE` VARCHAR(255),
    `DOCUMENTTITEL` VARCHAR(200),
    `VERTROUWELIJKAANDUIDING` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `VRAAG_CLASSIFICATIE_ENUM` (
    `VRAAG_CLASSIFICATIE_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `VRAAG_CLASSIFICATIE_ENUM` (`VRAAG_CLASSIFICATIE_ENUM_ID`, VALUE) VALUES
    (1, 'AANVRAGER'),
    (2, 'ACTIVITEIT'),
    (3, 'GEVRAAGDE_BIJLAGE'),
    (4, 'PROJECT'),
    (5, 'VERZOEK');

CREATE TABLE `MEDEWERKER` (
    `MEDEWERKER_ID` INT PRIMARY KEY,
    `ACHTERNAAM` VARCHAR(200),
    `DATUMINDIENST` DATE,
    `DATUMUITDIENST` DATE,
    `EMAILADRES` VARCHAR(255),
    `EXTERN` BOOLEAN,
    `FUNCTIE` VARCHAR(50),
    `GESLACHTSAANDUIDING` VARCHAR(255),
    `IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID` INT,
    `MEDEWERKERIDENTIFICATIE` VARCHAR(255),
    `MEDEWERKERTOELICHTING` VARCHAR(255),
    `ROEPNAAM` VARCHAR(255),
    `TELEFOONNUMMER` VARCHAR(20),
    `VOORLETTERS` VARCHAR(20),
    `VOORVOEGSELACHTERNAAM` VARCHAR(255),
    `WERKT_BIJ_UITVOERENDE_INSTANTIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `BEVOEGD_GEZAG` (
    `RECHTSPERSOON_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `PROJECTLOCATIE` (
    `PROJECTLOCATIE_ID` INT PRIMARY KEY,
    `ADRES` INT,
    `BETREFT_LOCATIE_ID` INT,
    `KADASTRAALPERCEEL` VARCHAR(80),
    `KADASTRALEGEMEENTE` VARCHAR(80),
    `KADASTRALESECTIE` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `SPECIFICATIE` (
    `SPECIFICATIE_ID` INT PRIMARY KEY,
    `ANTWOORD` VARCHAR(200),
    `GROEPERING` VARCHAR(200),
    `PUBLICEERBAAR` BOOLEAN,
    `VRAAGCLASSIFICATIE_ENUM_ID` INT,
    `VRAAGID` VARCHAR(80),
    `VRAAGREFERENTIE` VARCHAR(200),
    `VRAAGTEKST` TEXT
) ENGINE=InnoDB;

CREATE TABLE `PROJECT` (
    `PROJECT_ID` INT PRIMARY KEY,
    `HEEFT_PROJECTLOCATIE_ID` INT,
    `NAAM` VARCHAR(200),
    `OMSCHRIJVING` TEXT
) ENGINE=InnoDB;

CREATE TABLE `ZAAK` (
    `ZAAK_ID` INT PRIMARY KEY,
    `ARCHIEFNOMINATIE` VARCHAR(255),
    `BETREFT_PROJECT_ID` INT,
    `DATUMEINDE` DATE,
    `DATUMEINDEGEPLAND` DATE,
    `DATUMEINDEUITERLIJKEAFDOENING` DATE,
    `DATUMLAATSTEBETALING` DATE,
    `DATUMPUBLICATIE` DATE,
    `DATUMREGISTRATIE` DATE,
    `DATUMSTART` DATE,
    `DATUMVERNIETIGINGDOSSIER` DATE,
    `DUURVERLENGING` VARCHAR(255),
    `HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID` INT,
    `INDICATIEBETALING` VARCHAR(255),
    `INDICATIEDEELZAKEN` BOOLEAN,
    `INDICATIEOPSCHORTING` VARCHAR(255),
    `IS_DEELZAAK_VAN_ZAAK_ID` INT,
    `IS_VAN_ZAAKTYPE_ID` INT,
    `LEGES` VARCHAR(100),
    `OMSCHRIJVING` VARCHAR(80),
    `OMSCHRIJVINGRESULTAAT` VARCHAR(80),
    `REDENOPSCHORTING` VARCHAR(200),
    `REDENVERLENGING` VARCHAR(200),
    `TOELICHTING` VARCHAR(255),
    `TOELICHTINGRESULTAAT` VARCHAR(255),
    `VERTROUWELIJKHEID` VARCHAR(255),
    `ZAAKIDENTIFICATIE` VARCHAR(255),
    `ZAAKNIVEAU` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_ZK_MDWRKR` (
    `KP_ZK_MDWRKR_ID` INT PRIMARY KEY,
    `ZAAK_ID` INT,
    `MEDEWERKER_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VERZOEK` (
    `VERZOEK_ID` INT PRIMARY KEY,
    `AKKOORDVERKLARING` BOOLEAN,
    `AMBTSHALVE` BOOLEAN,
    `BEHANDELAAR_UITVOERENDE_INSTANTIE_ID` INT,
    `BETREFT_EERDER_VERZOEK_VERZOEK_ID` INT,
    `BETREFT_PROJECT_ID` INT,
    `BEVAT_SPECIFICATIE_ID` INT,
    `DATUMINDIENING` DATE,
    `DOEL` VARCHAR(255),
    `HEEFT_BIJLAGEN_DOCUMENT_ID` INT,
    `LEIDT_TOT_ZAAK_ID` INT,
    `NAAM` VARCHAR(200),
    `REFERENTIEAANVRAGER` VARCHAR(200),
    `TOELICHTINGLATERAANTELEVERENINFORMATIE` TEXT,
    `TOELICHTINGNIETAANTELEVERENINFORMATIE` TEXT,
    `TOELICHTINGVERZOEK` TEXT,
    `TYPE` VARCHAR(255),
    `VERANTWOORDELIJKE_BEVOEGD_GEZAG_ID` INT,
    `VERZOEKNUMMER` VARCHAR(80),
    `VOLGNUMMER` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `KP_ZK_DCMNT` (
    `KP_ZK_DCMNT_ID` INT PRIMARY KEY,
    `ZAAK_ID` INT,
    `DOCUMENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `INITIATIEFNEMER` (
    `RECHTSPERSOON_ID` INT PRIMARY KEY,
    `HEEFT_ALS_VERANTWOORDELIJKE_VERZOEK_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRZK_PRJCTLCT` (
    `KP_VRZK_PRJCTLCT_ID` INT PRIMARY KEY,
    `VERZOEK_ID` INT,
    `PROJECTLOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRZK_LCT` (
    `KP_VRZK_LCT_ID` INT PRIMARY KEY,
    `VERZOEK_ID` INT,
    `LOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `GEMACHTIGDE` (
    `RECHTSPERSOON_ID` INT PRIMARY KEY,
    `DIENT_IN__VERZOEK_ID` INT,
    `IS_GEMACHTIGD_DOOR_INITIATIEFNEMER_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `BEVOEGD_GEZAG` ADD CONSTRAINT FK_BEVOEGD_GEZAG_GEN_RECHTSPERSOON FOREIGN KEY (`RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- Generalization to RECHTSPERSOON

ALTER TABLE `GEMACHTIGDE` ADD CONSTRAINT FK_GEMACHTIGDE_GEN_RECHTSPERSOON FOREIGN KEY (`RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- Generalization to RECHTSPERSOON

ALTER TABLE `INITIATIEFNEMER` ADD CONSTRAINT FK_INITIATIEFNEMER_GEN_RECHTSPERSOON FOREIGN KEY (`RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- Generalization to RECHTSPERSOON

ALTER TABLE `KP_VRZK_PRJCTLCT` ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_1 FOREIGN KEY (`VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- VERZOEK (many-to-many junction, Connector_ID: 112)

ALTER TABLE `KP_VRZK_PRJCTLCT` ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_2 FOREIGN KEY (`PROJECTLOCATIE_ID`) REFERENCES `PROJECTLOCATIE` (`PROJECTLOCATIE_ID`);
-- PROJECTLOCATIE (many-to-many junction, Connector_ID: 112)

ALTER TABLE `KP_VRZK_LCT` ADD CONSTRAINT FK_KP_VRZK_LCT_1 FOREIGN KEY (`VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- VERZOEK (many-to-many junction, Connector_ID: 692)

ALTER TABLE `KP_VRZK_LCT` ADD CONSTRAINT FK_KP_VRZK_LCT_2 FOREIGN KEY (`LOCATIE_ID`) REFERENCES `LOCATIE` (`LOCATIE_ID`);
-- LOCATIE (many-to-many junction, Connector_ID: 692)

ALTER TABLE `KP_ZK_DCMNT` ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY (`ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE `KP_ZK_DCMNT` ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY (`DOCUMENT_ID`) REFERENCES `DOCUMENT` (`DOCUMENT_ID`);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE `KP_ZK_MDWRKR` ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY (`ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE `KP_ZK_MDWRKR` ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY (`MEDEWERKER_ID`) REFERENCES `MEDEWERKER` (`MEDEWERKER_ID`);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_HEEFT_BIJLAGEN FOREIGN KEY (`HEEFT_BIJLAGEN_DOCUMENT_ID`) REFERENCES `DOCUMENT` (`DOCUMENT_ID`);
-- HEEFT_BIJLAGEN (None to None, Connector_ID: 113)

ALTER TABLE `GEMACHTIGDE` ADD CONSTRAINT FK_GEMACHTIGDE_IS_GEMACHTIGD_DOOR FOREIGN KEY (`IS_GEMACHTIGD_DOOR_INITIATIEFNEMER_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- IS_GEMACHTIGD_DOOR (0..1 to 1..*, Connector_ID: 114)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_BETREFT_EERDER_VERZOEK FOREIGN KEY (`BETREFT_EERDER_VERZOEK_VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- BETREFT_EERDER_VERZOEK (0..1 to 0..*, Connector_ID: 690)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_LEIDT_TOT FOREIGN KEY (`LEIDT_TOT_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 691)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_BEHANDELAAR FOREIGN KEY (`BEHANDELAAR_UITVOERENDE_INSTANTIE_ID`) REFERENCES `UITVOERENDE_INSTANTIE` (`UITVOERENDE_INSTANTIE_ID`);
-- BEHANDELAAR (0..* to 0..1, Connector_ID: 695)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_BEVAT FOREIGN KEY (`BEVAT_SPECIFICATIE_ID`) REFERENCES `SPECIFICATIE` (`SPECIFICATIE_ID`);
-- BEVAT (1 to 0..*, Connector_ID: 696)

ALTER TABLE `PROJECTLOCATIE` ADD CONSTRAINT FK_PROJECTLOCATIE_BETREFT FOREIGN KEY (`BETREFT_LOCATIE_ID`) REFERENCES `LOCATIE` (`LOCATIE_ID`);
-- BETREFT (0..* to 0..1, Connector_ID: 697)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_BETREFT FOREIGN KEY (`BETREFT_PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`);
-- BETREFT (1..* to 1.., Connector_ID: 701)

ALTER TABLE `PROJECT` ADD CONSTRAINT FK_PROJECT_HEEFT FOREIGN KEY (`HEEFT_PROJECTLOCATIE_ID`) REFERENCES `PROJECTLOCATIE` (`PROJECTLOCATIE_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 704)

ALTER TABLE `INITIATIEFNEMER` ADD CONSTRAINT FK_INITIATIEFNEMER_HEEFT_ALS_VERANTWOORDELIJKE FOREIGN KEY (`HEEFT_ALS_VERANTWOORDELIJKE_VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- HEEFT_ALS_VERANTWOORDELIJKE (1 to 1..*, Connector_ID: 705)

ALTER TABLE `GEMACHTIGDE` ADD CONSTRAINT FK_GEMACHTIGDE_DIENT_IN_ FOREIGN KEY (`DIENT_IN__VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- DIENT_IN_ (0..1 to 1..*, Connector_ID: 707)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_VERANTWOORDELIJKE FOREIGN KEY (`VERANTWOORDELIJKE_BEVOEGD_GEZAG_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- VERANTWOORDELIJKE (0..* to 1, Connector_ID: 709)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_BETREFT FOREIGN KEY (`BETREFT_PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`);
-- BETREFT (0..* to 0..1, Connector_ID: 2106)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (`HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY (`IS_VAN_ZAAKTYPE_ID`) REFERENCES `ZAAKTYPE` (`ZAAKTYPE_ID`);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (`IS_DEELZAAK_VAN_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE `MEDEWERKER` ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY (`IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID`) REFERENCES `ZAAKTYPE` (`ZAAKTYPE_ID`);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2170)

ALTER TABLE `MEDEWERKER` ADD CONSTRAINT FK_MEDEWERKER_WERKT_BIJ FOREIGN KEY (`WERKT_BIJ_UITVOERENDE_INSTANTIE_ID`) REFERENCES `UITVOERENDE_INSTANTIE` (`UITVOERENDE_INSTANTIE_ID`);
-- WERKT_BIJ (0..* to 1, Connector_ID: 2172)

ALTER TABLE `SPECIFICATIE` ADD CONSTRAINT FK_SPECIFICATIE_VRAAGCLASSIFICATIE_ENUM_ID FOREIGN KEY (`VRAAGCLASSIFICATIE_ENUM_ID`) REFERENCES `VRAAG_CLASSIFICATIE_ENUM` (`VRAAG_CLASSIFICATIE_ENUM_ID`);
-- VRAAGCLASSIFICATIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

