CREATE TABLE DOCUMENT (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR(200),
    DOCUMENTIDENTIFICATIE VARCHAR(255),
    DOCUMENTTITEL VARCHAR(200),
    VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE PROJECTLOCATIE (
    PROJECTLOCATIE_ID INTEGER PRIMARY KEY,
    ADRES INTEGER,
    KADASTRAALPERCEEL VARCHAR(80),
    KADASTRALEGEMEENTE VARCHAR(80),
    KADASTRALESECTIE VARCHAR(80)
);

CREATE TABLE PROJECTACTIVITEIT (
    PROJECTACTIVITEIT_ID INTEGER PRIMARY KEY,
    HEEFT_BETREKKING_OP_DOCUMENT_ID INTEGER,
    UITGEVOERD_OP_PROJECTLOCATIE_ID INTEGER
);

CREATE TABLE SPECIFICATIE (
    SPECIFICATIE_ID INTEGER PRIMARY KEY,
    ANTWOORD VARCHAR(200),
    GEDEFINIEERD_DOOR_PROJECTACTIVITEIT_ID INTEGER,
    GROEPERING VARCHAR(200),
    PUBLICEERBAAR BOOLEAN,
    VRAAGCLASSIFICATIE VARCHAR(255),
    VRAAGID VARCHAR(80),
    VRAAGREFERENTIE VARCHAR(200),
    VRAAGTEKST TEXT
);

CREATE TABLE PROJECT (
    PROJECT_ID INTEGER PRIMARY KEY,
    HEEFT_PROJECTACTIVITEIT_ID INTEGER,
    HEEFT_PROJECTLOCATIE_ID INTEGER,
    NAAM VARCHAR(200),
    OMSCHRIJVING TEXT
);

CREATE TABLE VERZOEK (
    VERZOEK_ID INTEGER PRIMARY KEY,
    AKKOORDVERKLARING BOOLEAN,
    AMBTSHALVE BOOLEAN,
    BETREFT_EERDER_VERZOEK_VERZOEK_ID INTEGER,
    BETREFT_PROJECT_ID INTEGER,
    BEVAT_SPECIFICATIE_ID INTEGER,
    DATUMINDIENING DATE,
    DOEL VARCHAR(255),
    HEEFT_BIJLAGEN_DOCUMENT_ID INTEGER,
    NAAM VARCHAR(200),
    REFERENTIEAANVRAGER VARCHAR(200),
    TOELICHTINGLATERAANTELEVERENINFORMATIE TEXT,
    TOELICHTINGNIETAANTELEVERENINFORMATIE TEXT,
    TOELICHTINGVERZOEK TEXT,
    TYPE VARCHAR(255),
    VERZOEKNUMMER VARCHAR(80),
    VOLGNUMMER VARCHAR(80)
);

CREATE TABLE KP_VRZK_PRJCTLCT (
    KP_VRZK_PRJCTLCT_ID INTEGER PRIMARY KEY,
    VERZOEK_ID INTEGER,
    PROJECTLOCATIE_ID INTEGER
);

CREATE TABLE KP_VRZK_PRJCTCTVTT (
    KP_VRZK_PRJCTCTVTT_ID INTEGER PRIMARY KEY,
    VERZOEK_ID INTEGER,
    PROJECTACTIVITEIT_ID INTEGER
);

ALTER TABLE KP_VRZK_PRJCTLCT ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 112)

ALTER TABLE KP_VRZK_PRJCTLCT ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_2 FOREIGN KEY (PROJECTLOCATIE_ID) REFERENCES PROJECTLOCATIE (PROJECTLOCATIE_ID);
-- PROJECTLOCATIE (many-to-many junction, Connector_ID: 112)

ALTER TABLE KP_VRZK_PRJCTCTVTT ADD CONSTRAINT FK_KP_VRZK_PRJCTCTVTT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 698)

ALTER TABLE KP_VRZK_PRJCTCTVTT ADD CONSTRAINT FK_KP_VRZK_PRJCTCTVTT_2 FOREIGN KEY (PROJECTACTIVITEIT_ID) REFERENCES PROJECTACTIVITEIT (PROJECTACTIVITEIT_ID);
-- PROJECTACTIVITEIT (many-to-many junction, Connector_ID: 698)

ALTER TABLE PROJECTACTIVITEIT ADD CONSTRAINT FK_PROJECTACTIVITEIT_HEEFT_BETREKKING_OP FOREIGN KEY (HEEFT_BETREKKING_OP_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- HEEFT_BETREKKING_OP (None to None, Connector_ID: 100)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_HEEFT_BIJLAGEN FOREIGN KEY (HEEFT_BIJLAGEN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- HEEFT_BIJLAGEN (None to None, Connector_ID: 113)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BETREFT_EERDER_VERZOEK FOREIGN KEY (BETREFT_EERDER_VERZOEK_VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- BETREFT_EERDER_VERZOEK (0..1 to 0..*, Connector_ID: 690)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BEVAT FOREIGN KEY (BEVAT_SPECIFICATIE_ID) REFERENCES SPECIFICATIE (SPECIFICATIE_ID);
-- BEVAT (1 to 0..*, Connector_ID: 696)

ALTER TABLE SPECIFICATIE ADD CONSTRAINT FK_SPECIFICATIE_GEDEFINIEERD_DOOR FOREIGN KEY (GEDEFINIEERD_DOOR_PROJECTACTIVITEIT_ID) REFERENCES PROJECTACTIVITEIT (PROJECTACTIVITEIT_ID);
-- GEDEFINIEERD_DOOR (1..* to 0..1, Connector_ID: 699)

ALTER TABLE PROJECTACTIVITEIT ADD CONSTRAINT FK_PROJECTACTIVITEIT_UITGEVOERD_OP FOREIGN KEY (UITGEVOERD_OP_PROJECTLOCATIE_ID) REFERENCES PROJECTLOCATIE (PROJECTLOCATIE_ID);
-- UITGEVOERD_OP (1..* to 1, Connector_ID: 700)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BETREFT FOREIGN KEY (BETREFT_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- BETREFT (1..* to 1.., Connector_ID: 701)

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_HEEFT FOREIGN KEY (HEEFT_PROJECTACTIVITEIT_ID) REFERENCES PROJECTACTIVITEIT (PROJECTACTIVITEIT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 703)

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_HEEFT_2 FOREIGN KEY (HEEFT_PROJECTLOCATIE_ID) REFERENCES PROJECTLOCATIE (PROJECTLOCATIE_ID);
-- HEEFT (1 to 0..*, Connector_ID: 704)

