CREATE TABLE `DOCUMENT` (
    `DOCUMENT_ID` INT PRIMARY KEY,
    `COCUMENTBESCHRIJVING` VARCHAR(255),
    `DATUMCREATIEDOCUMENT` DATE,
    `DATUMONTVANGSTDOCUMENT` DATE,
    `DATUMVERZENDINGDOCUMENT` DATE,
    `DOCUMENTAUTEUR` VARCHAR(200),
    `DOCUMENTIDENTIFICATIE` VARCHAR(255),
    `DOCUMENTTITEL` VARCHAR(200),
    `VERTROUWELIJKAANDUIDING` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `PROJECT` (
    `PROJECT_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(200),
    `OMSCHRIJVING` TEXT
) ENGINE=InnoDB;

CREATE TABLE `VERZOEK` (
    `VERZOEK_ID` INT PRIMARY KEY,
    `AKKOORDVERKLARING` BOOLEAN,
    `AMBTSHALVE` BOOLEAN,
    `BETREFT_EERDER_VERZOEK_VERZOEK_ID` INT,
    `BETREFT_PROJECT_ID` INT,
    `DATUMINDIENING` DATE,
    `DOEL` VARCHAR(255),
    `NAAM` VARCHAR(200),
    `REFERENTIEAANVRAGER` VARCHAR(200),
    `TOELICHTINGLATERAANTELEVERENINFORMATIE` TEXT,
    `TOELICHTINGNIETAANTELEVERENINFORMATIE` TEXT,
    `TOELICHTINGVERZOEK` TEXT,
    `TYPE` VARCHAR(255),
    `VERZOEKNUMMER` VARCHAR(80),
    `VOLGNUMMER` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `PROJECTLOCATIE` (
    `PROJECTLOCATIE_ID` INT PRIMARY KEY,
    `ADRES` INT,
    `HEEFT_PROJECT_ID` INT,
    `KADASTRAALPERCEEL` VARCHAR(80),
    `KADASTRALEGEMEENTE` VARCHAR(80),
    `KADASTRALESECTIE` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `KP_VRZK_DCMNT` (
    `KP_VRZK_DCMNT_ID` INT PRIMARY KEY,
    `VERZOEK_ID` INT,
    `DOCUMENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRZK_PRJCTLCT` (
    `KP_VRZK_PRJCTLCT_ID` INT PRIMARY KEY,
    `VERZOEK_ID` INT,
    `PROJECTLOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `PROJECTACTIVITEIT` (
    `PROJECTACTIVITEIT_ID` INT PRIMARY KEY,
    `HEEFT_PROJECT_ID` INT,
    `UITGEVOERD_OP_PROJECTLOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_PRJCTCTVTT_DCMNT` (
    `KP_PRJCTCTVTT_DCMNT_ID` INT PRIMARY KEY,
    `PROJECTACTIVITEIT_ID` INT,
    `DOCUMENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `SPECIFICATIE` (
    `SPECIFICATIE_ID` INT PRIMARY KEY,
    `ANTWOORD` VARCHAR(200),
    `BEVAT_VERZOEK_ID` INT,
    `GEDEFINIEERD_DOOR_PROJECTACTIVITEIT_ID` INT,
    `GROEPERING` VARCHAR(200),
    `PUBLICEERBAAR` BOOLEAN,
    `VRAAGCLASSIFICATIE` VARCHAR(255),
    `VRAAGID` VARCHAR(80),
    `VRAAGREFERENTIE` VARCHAR(200),
    `VRAAGTEKST` TEXT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRZK_PRJCTCTVTT` (
    `KP_VRZK_PRJCTCTVTT_ID` INT PRIMARY KEY,
    `VERZOEK_ID` INT,
    `PROJECTACTIVITEIT_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `KP_PRJCTCTVTT_DCMNT` ADD CONSTRAINT FK_KP_PRJCTCTVTT_DCMNT_1 FOREIGN KEY (`PROJECTACTIVITEIT_ID`) REFERENCES `PROJECTACTIVITEIT` (`PROJECTACTIVITEIT_ID`);
-- PROJECTACTIVITEIT (many-to-many junction, Connector_ID: 100)

ALTER TABLE `KP_PRJCTCTVTT_DCMNT` ADD CONSTRAINT FK_KP_PRJCTCTVTT_DCMNT_2 FOREIGN KEY (`DOCUMENT_ID`) REFERENCES `DOCUMENT` (`DOCUMENT_ID`);
-- DOCUMENT (many-to-many junction, Connector_ID: 100)

ALTER TABLE `KP_VRZK_PRJCTLCT` ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_1 FOREIGN KEY (`VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- VERZOEK (many-to-many junction, Connector_ID: 112)

ALTER TABLE `KP_VRZK_PRJCTLCT` ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_2 FOREIGN KEY (`PROJECTLOCATIE_ID`) REFERENCES `PROJECTLOCATIE` (`PROJECTLOCATIE_ID`);
-- PROJECTLOCATIE (many-to-many junction, Connector_ID: 112)

ALTER TABLE `KP_VRZK_DCMNT` ADD CONSTRAINT FK_KP_VRZK_DCMNT_1 FOREIGN KEY (`VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- VERZOEK (many-to-many junction, Connector_ID: 113)

ALTER TABLE `KP_VRZK_DCMNT` ADD CONSTRAINT FK_KP_VRZK_DCMNT_2 FOREIGN KEY (`DOCUMENT_ID`) REFERENCES `DOCUMENT` (`DOCUMENT_ID`);
-- DOCUMENT (many-to-many junction, Connector_ID: 113)

ALTER TABLE `KP_VRZK_PRJCTCTVTT` ADD CONSTRAINT FK_KP_VRZK_PRJCTCTVTT_1 FOREIGN KEY (`VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- VERZOEK (many-to-many junction, Connector_ID: 698)

ALTER TABLE `KP_VRZK_PRJCTCTVTT` ADD CONSTRAINT FK_KP_VRZK_PRJCTCTVTT_2 FOREIGN KEY (`PROJECTACTIVITEIT_ID`) REFERENCES `PROJECTACTIVITEIT` (`PROJECTACTIVITEIT_ID`);
-- PROJECTACTIVITEIT (many-to-many junction, Connector_ID: 698)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_BETREFT_EERDER_VERZOEK FOREIGN KEY (`BETREFT_EERDER_VERZOEK_VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- BETREFT_EERDER_VERZOEK (0..1 to 0..*, Connector_ID: 690)

ALTER TABLE `SPECIFICATIE` ADD CONSTRAINT FK_SPECIFICATIE_BEVAT FOREIGN KEY (`BEVAT_VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- BEVAT (1 to 0..*, Connector_ID: 696)

ALTER TABLE `SPECIFICATIE` ADD CONSTRAINT FK_SPECIFICATIE_GEDEFINIEERD_DOOR FOREIGN KEY (`GEDEFINIEERD_DOOR_PROJECTACTIVITEIT_ID`) REFERENCES `PROJECTACTIVITEIT` (`PROJECTACTIVITEIT_ID`);
-- GEDEFINIEERD_DOOR (1..* to 0..1, Connector_ID: 699)

ALTER TABLE `PROJECTACTIVITEIT` ADD CONSTRAINT FK_PROJECTACTIVITEIT_UITGEVOERD_OP FOREIGN KEY (`UITGEVOERD_OP_PROJECTLOCATIE_ID`) REFERENCES `PROJECTLOCATIE` (`PROJECTLOCATIE_ID`);
-- UITGEVOERD_OP (1..* to 1, Connector_ID: 700)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_BETREFT FOREIGN KEY (`BETREFT_PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`);
-- BETREFT (1..* to 1.., Connector_ID: 701)

ALTER TABLE `PROJECTACTIVITEIT` ADD CONSTRAINT FK_PROJECTACTIVITEIT_HEEFT FOREIGN KEY (`HEEFT_PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 703)

ALTER TABLE `PROJECTLOCATIE` ADD CONSTRAINT FK_PROJECTLOCATIE_HEEFT FOREIGN KEY (`HEEFT_PROJECT_ID`) REFERENCES `PROJECT` (`PROJECT_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 704)

