CREATE TABLE UITVOERINGSREGEL (
    UITVOERINGSREGEL_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(200),
    OMSCHRIJVING CLOB,
    REGEL CLOB
);

CREATE TABLE LOCATIE (
    LOCATIE_ID NUMBER PRIMARY KEY,
    HOOGTE NUMBER,
    NAAM VARCHAR2(200),
    NEN3610ID VARCHAR2(80)
);

CREATE TABLE ACTIVITEIT (
    ACTIVITEIT_ID NUMBER PRIMARY KEY,
    BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID NUMBER,
    GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID NUMBER,
    GROEP VARCHAR2(200),
    NAAM VARCHAR2(200),
    NEN3610ID VARCHAR2(80)
);

CREATE TABLE JURIDISCHE_REGEL (
    JURIDISCHE_REGEL_ID NUMBER PRIMARY KEY,
    DATUMBEKEND DATE,
    DATUMEINDEGELDIGHEID DATE,
    DATUMINWERKING DATE,
    DATUMSTART DATE,
    OMSCHRIJVING CLOB,
    REGELTEKST VARCHAR2(200),
    THEMA VARCHAR2(200)
);

CREATE TABLE TOEPASBAREREGELBESTAND (
    TOEPASBAREREGELBESTAND_ID NUMBER PRIMARY KEY,
    BEVAT_UITVOERINGSREGEL_ID NUMBER,
    DATUMEINDEGELDIGHEID DATE,
    DATUMSTART DATE
);

CREATE TABLE KP_ACTVTT_LCT (
    KP_ACTVTT_LCT_ID NUMBER PRIMARY KEY,
    ACTIVITEIT_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE KP_JRDSCH_RGL_ACTVTT (
    KP_JRDSCH_RGL_ACTVTT_ID NUMBER PRIMARY KEY,
    JURIDISCHE_REGEL_ID NUMBER,
    ACTIVITEIT_ID NUMBER
);

CREATE TABLE KP_JRDSCH_RGL_LCT (
    KP_JRDSCH_RGL_LCT_ID NUMBER PRIMARY KEY,
    JURIDISCHE_REGEL_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE TOEPASBARE_REGEL (
    TOEPASBARE_REGEL_ID NUMBER PRIMARY KEY,
    BETREFT_ACTIVITEIT_ID NUMBER,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    DOMEIN VARCHAR2(255),
    HEEFT_TOEPASBAREREGELBESTAND_ID NUMBER,
    HEEFT_UITVOERINGSREGEL_ID NUMBER,
    NAAM VARCHAR2(200),
    OMSCHRIJVING CLOB,
    SOORTAANSLUITPUNT VARCHAR2(200),
    TOESTEMMING VARCHAR2(200)
);

CREATE TABLE INDIENINGSVEREISTEN (
    TOEPASBARE_REGEL_ID NUMBER PRIMARY KEY
);

CREATE TABLE MAATREGELEN (
    TOEPASBARE_REGEL_ID NUMBER PRIMARY KEY
);

CREATE TABLE KP_TPSBR_RGL_LCT (
    KP_TPSBR_RGL_LCT_ID NUMBER PRIMARY KEY,
    TOEPASBARE_REGEL_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE KP_TPSBR_RGL_JRDSCH_RGL (
    KP_TPSBR_RGL_JRDSCH_RGL_ID NUMBER PRIMARY KEY,
    TOEPASBARE_REGEL_ID NUMBER,
    JURIDISCHE_REGEL_ID NUMBER
);

CREATE TABLE CONCLUSIE (
    TOEPASBARE_REGEL_ID NUMBER PRIMARY KEY
);

ALTER TABLE CONCLUSIE ADD CONSTRAINT FK_CONCLUSIE_GEN_TOEPASBARE_REGEL FOREIGN KEY (TOEPASBARE_REGEL_ID) REFERENCES TOEPASBARE_REGEL (TOEPASBARE_REGEL_ID);
-- Generalization to TOEPASBARE_REGEL

ALTER TABLE INDIENINGSVEREISTEN ADD CONSTRAINT FK_INDIENINGSVEREISTEN_GEN_TOEPASBARE_REGEL FOREIGN KEY (TOEPASBARE_REGEL_ID) REFERENCES TOEPASBARE_REGEL (TOEPASBARE_REGEL_ID);
-- Generalization to TOEPASBARE_REGEL

ALTER TABLE MAATREGELEN ADD CONSTRAINT FK_MAATREGELEN_GEN_TOEPASBARE_REGEL FOREIGN KEY (TOEPASBARE_REGEL_ID) REFERENCES TOEPASBARE_REGEL (TOEPASBARE_REGEL_ID);
-- Generalization to TOEPASBARE_REGEL

ALTER TABLE KP_TPSBR_RGL_LCT ADD CONSTRAINT FK_KP_TPSBR_RGL_LCT_1 FOREIGN KEY (TOEPASBARE_REGEL_ID) REFERENCES TOEPASBARE_REGEL (TOEPASBARE_REGEL_ID);
-- TOEPASBARE_REGEL (many-to-many junction, Connector_ID: 653)

ALTER TABLE KP_TPSBR_RGL_LCT ADD CONSTRAINT FK_KP_TPSBR_RGL_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 653)

ALTER TABLE KP_TPSBR_RGL_JRDSCH_RGL ADD CONSTRAINT FK_KP_TPSBR_RGL_JRDSCH_RGL_1 FOREIGN KEY (TOEPASBARE_REGEL_ID) REFERENCES TOEPASBARE_REGEL (TOEPASBARE_REGEL_ID);
-- TOEPASBARE_REGEL (many-to-many junction, Connector_ID: 667)

ALTER TABLE KP_TPSBR_RGL_JRDSCH_RGL ADD CONSTRAINT FK_KP_TPSBR_RGL_JRDSCH_RGL_2 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 667)

ALTER TABLE KP_JRDSCH_RGL_LCT ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_JRDSCH_RGL_LCT ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_JRDSCH_RGL_ACTVTT ADD CONSTRAINT FK_KP_JRDSCH_RGL_ACTVTT_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 677)

ALTER TABLE KP_JRDSCH_RGL_ACTVTT ADD CONSTRAINT FK_KP_JRDSCH_RGL_ACTVTT_2 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 677)

ALTER TABLE KP_ACTVTT_LCT ADD CONSTRAINT FK_KP_ACTVTT_LCT_1 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 680)

ALTER TABLE KP_ACTVTT_LCT ADD CONSTRAINT FK_KP_ACTVTT_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 680)

ALTER TABLE TOEPASBAREREGELBESTAND ADD CONSTRAINT FK_TOEPASBAREREGELBESTAND_BEVAT FOREIGN KEY (BEVAT_UITVOERINGSREGEL_ID) REFERENCES UITVOERINGSREGEL (UITVOERINGSREGEL_ID);
-- BEVAT (1 to 0..*, Connector_ID: 650)

ALTER TABLE TOEPASBARE_REGEL ADD CONSTRAINT FK_TOEPASBARE_REGEL_HEEFT FOREIGN KEY (HEEFT_TOEPASBAREREGELBESTAND_ID) REFERENCES TOEPASBAREREGELBESTAND (TOEPASBAREREGELBESTAND_ID);
-- HEEFT (0..* to 1, Connector_ID: 651)

ALTER TABLE TOEPASBARE_REGEL ADD CONSTRAINT FK_TOEPASBARE_REGEL_HEEFT_2 FOREIGN KEY (HEEFT_UITVOERINGSREGEL_ID) REFERENCES UITVOERINGSREGEL (UITVOERINGSREGEL_ID);
-- HEEFT (1 to 0..*, Connector_ID: 652)

ALTER TABLE TOEPASBARE_REGEL ADD CONSTRAINT FK_TOEPASBARE_REGEL_BETREFT FOREIGN KEY (BETREFT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BETREFT (0..* to 1, Connector_ID: 679)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_BOVENLIGGENDE_ACTIVITEIT FOREIGN KEY (BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BOVENLIGGENDE_ACTIVITEIT (1 to 0..1, Connector_ID: 681)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_GERELATEERDE_ACTIVITEIT FOREIGN KEY (GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- GERELATEERDE_ACTIVITEIT (1 to 0..1, Connector_ID: 682)

