CREATE TABLE `BEPERKINGSGEBIED` (
    `GEBIEDSAANWIJZING_ID` INT PRIMARY KEY,
    `GROEP` VARCHAR(200),
    `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `FUNCTIE` (
    `GEBIEDSAANWIJZING_ID` INT PRIMARY KEY,
    `GROEP` VARCHAR(200),
    `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `KP_JRDSCH_RGL_LCT` (
    `KP_JRDSCH_RGL_LCT_ID` INT PRIMARY KEY,
    `JURIDISCHE_REGEL_ID` INT,
    `LOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VERZOEK` (
    `VERZOEK_ID` INT PRIMARY KEY,
    `AKKOORDVERKLARING` BOOLEAN,
    `AMBTSHALVE` BOOLEAN,
    `BEHANDELAAR_UITVOERENDE_INSTANTIE_ID` INT,
    `BETREFT_EERDER_VERZOEK_VERZOEK_ID` INT,
    `DATUMINDIENING` DATE,
    `DOEL_ENUM_ID` INT,
    `NAAM` VARCHAR(200),
    `REFERENTIEAANVRAGER` VARCHAR(200),
    `TOELICHTINGLATERAANTELEVERENINFORMATIE` TEXT,
    `TOELICHTINGNIETAANTELEVERENINFORMATIE` TEXT,
    `TOELICHTINGVERZOEK` TEXT,
    `TYPE_ENUM_ID` INT,
    `VERZOEKNUMMER` VARCHAR(80),
    `VOLGNUMMER` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `KP_TPSBR_RGL_LCT` (
    `KP_TPSBR_RGL_LCT_ID` INT PRIMARY KEY,
    `TOEPASBARE_REGEL_ID` INT,
    `LOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRZK_LCT` (
    `KP_VRZK_LCT_ID` INT PRIMARY KEY,
    `VERZOEK_ID` INT,
    `LOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `INITIATIEFNEMER` (
    `INITIATIEFNEMER_ID` INT PRIMARY KEY,
    `HEEFT_ALS_VERANTWOORDELIJKE_VERZOEK_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `UITVOERENDE_INSTANTIE` (
    `UITVOERENDE_INSTANTIE_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `KP_VRZK_ACTVTT` (
    `KP_VRZK_ACTVTT_ID` INT PRIMARY KEY,
    `VERZOEK_ID` INT,
    `ACTIVITEIT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `TYPE_VERZOEK_ENUM` (
    `TYPE_VERZOEK_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `TYPE_VERZOEK_ENUM` (`TYPE_VERZOEK_ENUM_ID`, VALUE) VALUES
    (1, 'AANVRAAG_MAATWERKVOORSCHRIFT'),
    (2, 'AANVRAAG_TOESTEMMING_GELIJKWAARDIGE_MAATREGEL'),
    (3, 'AANVRAAG_VERGUNNING'),
    (4, 'INFORMATIE'),
    (5, 'INFORMATIE_ONGEWOON_VOORVAL'),
    (6, 'MELDING'),
    (7, 'MELDING_GELIJKWAARDIGE_MAATREGEL');

CREATE TABLE `TOEPASBARE_REGEL` (
    `TOEPASBARE_REGEL_ID` INT PRIMARY KEY,
    `BETREFT_ACTIVITEIT_ID` INT,
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `DOMEIN` VARCHAR(255),
    `NAAM` VARCHAR(200),
    `OMSCHRIJVING` TEXT,
    `SOORTAANSLUITPUNT` VARCHAR(200),
    `TOESTEMMING` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `GEBIEDSAANWIJZING` (
    `GEBIEDSAANWIJZING_ID` INT PRIMARY KEY,
    `GROEP` VARCHAR(200),
    `NAAM` VARCHAR(200),
    `NEN3610ID` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `LOCATIE` (
    `LOCATIE_ID` INT PRIMARY KEY,
    `HOOGTE` INT,
    `NAAM` VARCHAR(200),
    `NEN3610ID` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `KP_TPSBR_RGL_JRDSCH_RGL` (
    `KP_TPSBR_RGL_JRDSCH_RGL_ID` INT PRIMARY KEY,
    `TOEPASBARE_REGEL_ID` INT,
    `JURIDISCHE_REGEL_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_ACTVTT_LCT` (
    `KP_ACTVTT_LCT_ID` INT PRIMARY KEY,
    `ACTIVITEIT_ID` INT,
    `LOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_JRDSCH_RGL_ACTVTT` (
    `KP_JRDSCH_RGL_ACTVTT_ID` INT PRIMARY KEY,
    `JURIDISCHE_REGEL_ID` INT,
    `ACTIVITEIT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `DOEL_VERZOEK_ENUM` (
    `DOEL_VERZOEK_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `DOEL_VERZOEK_ENUM` (`DOEL_VERZOEK_ENUM_ID`, VALUE) VALUES
    (1, 'AANVULLEN'),
    (2, 'INITIEREN'),
    (3, 'INTREKKEN'),
    (4, 'VOOROVERLEG');

CREATE TABLE `JURIDISCHE_REGEL` (
    `JURIDISCHE_REGEL_ID` INT PRIMARY KEY,
    `DATUMBEKEND` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `DATUMINWERKING` DATE,
    `DATUMSTART` DATE,
    `IS_OPGENOMEN_IN_REGELTEKST_ID` INT,
    `OMSCHRIJVING` TEXT,
    `REGELTEKST` VARCHAR(200),
    `THEMA` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `REGELTEKST` (
    `REGELTEKST_ID` INT PRIMARY KEY,
    `IDENTIFICATIE` VARCHAR(200),
    `IS_GERELATEERD_REGELTEKST_ID` INT,
    `OMSCHRIJVING` TEXT,
    `TEKST` TEXT,
    `WERKINGSGEBIED_REGELTEKST_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_RGLTKST_LCT` (
    `KP_RGLTKST_LCT_ID` INT PRIMARY KEY,
    `REGELTEKST_ID` INT,
    `LOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `ACTIVITEIT` (
    `ACTIVITEIT_ID` INT PRIMARY KEY,
    `BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID` INT,
    `GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID` INT,
    `GROEP` VARCHAR(200),
    `NAAM` VARCHAR(200),
    `NEN3610ID` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `KP_GBDSNWJZNG_LCT` (
    `KP_GBDSNWJZNG_LCT_ID` INT PRIMARY KEY,
    `GEBIEDSAANWIJZING_ID` INT,
    `LOCATIE_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `BEPERKINGSGEBIED` ADD CONSTRAINT FK_BEPERKINGSGEBIED_GEN_GEBIEDSAANWIJZING FOREIGN KEY (`GEBIEDSAANWIJZING_ID`) REFERENCES `GEBIEDSAANWIJZING` (`GEBIEDSAANWIJZING_ID`);
-- Generalization to GEBIEDSAANWIJZING

ALTER TABLE `FUNCTIE` ADD CONSTRAINT FK_FUNCTIE_GEN_GEBIEDSAANWIJZING FOREIGN KEY (`GEBIEDSAANWIJZING_ID`) REFERENCES `GEBIEDSAANWIJZING` (`GEBIEDSAANWIJZING_ID`);
-- Generalization to GEBIEDSAANWIJZING

ALTER TABLE `KP_TPSBR_RGL_LCT` ADD CONSTRAINT FK_KP_TPSBR_RGL_LCT_1 FOREIGN KEY (`TOEPASBARE_REGEL_ID`) REFERENCES `TOEPASBARE_REGEL` (`TOEPASBARE_REGEL_ID`);
-- TOEPASBARE_REGEL (many-to-many junction, Connector_ID: 653)

ALTER TABLE `KP_TPSBR_RGL_LCT` ADD CONSTRAINT FK_KP_TPSBR_RGL_LCT_2 FOREIGN KEY (`LOCATIE_ID`) REFERENCES `LOCATIE` (`LOCATIE_ID`);
-- LOCATIE (many-to-many junction, Connector_ID: 653)

ALTER TABLE `KP_TPSBR_RGL_JRDSCH_RGL` ADD CONSTRAINT FK_KP_TPSBR_RGL_JRDSCH_RGL_1 FOREIGN KEY (`TOEPASBARE_REGEL_ID`) REFERENCES `TOEPASBARE_REGEL` (`TOEPASBARE_REGEL_ID`);
-- TOEPASBARE_REGEL (many-to-many junction, Connector_ID: 667)

ALTER TABLE `KP_TPSBR_RGL_JRDSCH_RGL` ADD CONSTRAINT FK_KP_TPSBR_RGL_JRDSCH_RGL_2 FOREIGN KEY (`JURIDISCHE_REGEL_ID`) REFERENCES `JURIDISCHE_REGEL` (`JURIDISCHE_REGEL_ID`);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 667)

ALTER TABLE `KP_JRDSCH_RGL_LCT` ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_1 FOREIGN KEY (`JURIDISCHE_REGEL_ID`) REFERENCES `JURIDISCHE_REGEL` (`JURIDISCHE_REGEL_ID`);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 668)

ALTER TABLE `KP_JRDSCH_RGL_LCT` ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_2 FOREIGN KEY (`LOCATIE_ID`) REFERENCES `LOCATIE` (`LOCATIE_ID`);
-- LOCATIE (many-to-many junction, Connector_ID: 668)

ALTER TABLE `KP_GBDSNWJZNG_LCT` ADD CONSTRAINT FK_KP_GBDSNWJZNG_LCT_1 FOREIGN KEY (`GEBIEDSAANWIJZING_ID`) REFERENCES `GEBIEDSAANWIJZING` (`GEBIEDSAANWIJZING_ID`);
-- GEBIEDSAANWIJZING (many-to-many junction, Connector_ID: 674)

ALTER TABLE `KP_GBDSNWJZNG_LCT` ADD CONSTRAINT FK_KP_GBDSNWJZNG_LCT_2 FOREIGN KEY (`LOCATIE_ID`) REFERENCES `LOCATIE` (`LOCATIE_ID`);
-- LOCATIE (many-to-many junction, Connector_ID: 674)

ALTER TABLE `KP_JRDSCH_RGL_ACTVTT` ADD CONSTRAINT FK_KP_JRDSCH_RGL_ACTVTT_1 FOREIGN KEY (`JURIDISCHE_REGEL_ID`) REFERENCES `JURIDISCHE_REGEL` (`JURIDISCHE_REGEL_ID`);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 677)

ALTER TABLE `KP_JRDSCH_RGL_ACTVTT` ADD CONSTRAINT FK_KP_JRDSCH_RGL_ACTVTT_2 FOREIGN KEY (`ACTIVITEIT_ID`) REFERENCES `ACTIVITEIT` (`ACTIVITEIT_ID`);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 677)

ALTER TABLE `KP_ACTVTT_LCT` ADD CONSTRAINT FK_KP_ACTVTT_LCT_1 FOREIGN KEY (`ACTIVITEIT_ID`) REFERENCES `ACTIVITEIT` (`ACTIVITEIT_ID`);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 680)

ALTER TABLE `KP_ACTVTT_LCT` ADD CONSTRAINT FK_KP_ACTVTT_LCT_2 FOREIGN KEY (`LOCATIE_ID`) REFERENCES `LOCATIE` (`LOCATIE_ID`);
-- LOCATIE (many-to-many junction, Connector_ID: 680)

ALTER TABLE `KP_RGLTKST_LCT` ADD CONSTRAINT FK_KP_RGLTKST_LCT_1 FOREIGN KEY (`REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- REGELTEKST (many-to-many junction, Connector_ID: 684)

ALTER TABLE `KP_RGLTKST_LCT` ADD CONSTRAINT FK_KP_RGLTKST_LCT_2 FOREIGN KEY (`LOCATIE_ID`) REFERENCES `LOCATIE` (`LOCATIE_ID`);
-- LOCATIE (many-to-many junction, Connector_ID: 684)

ALTER TABLE `KP_VRZK_LCT` ADD CONSTRAINT FK_KP_VRZK_LCT_1 FOREIGN KEY (`VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- VERZOEK (many-to-many junction, Connector_ID: 692)

ALTER TABLE `KP_VRZK_LCT` ADD CONSTRAINT FK_KP_VRZK_LCT_2 FOREIGN KEY (`LOCATIE_ID`) REFERENCES `LOCATIE` (`LOCATIE_ID`);
-- LOCATIE (many-to-many junction, Connector_ID: 692)

ALTER TABLE `KP_VRZK_ACTVTT` ADD CONSTRAINT FK_KP_VRZK_ACTVTT_1 FOREIGN KEY (`VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- VERZOEK (many-to-many junction, Connector_ID: 693)

ALTER TABLE `KP_VRZK_ACTVTT` ADD CONSTRAINT FK_KP_VRZK_ACTVTT_2 FOREIGN KEY (`ACTIVITEIT_ID`) REFERENCES `ACTIVITEIT` (`ACTIVITEIT_ID`);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 693)

ALTER TABLE `TOEPASBARE_REGEL` ADD CONSTRAINT FK_TOEPASBARE_REGEL_BETREFT FOREIGN KEY (`BETREFT_ACTIVITEIT_ID`) REFERENCES `ACTIVITEIT` (`ACTIVITEIT_ID`);
-- BETREFT (0..* to 1, Connector_ID: 679)

ALTER TABLE `ACTIVITEIT` ADD CONSTRAINT FK_ACTIVITEIT_BOVENLIGGENDE_ACTIVITEIT FOREIGN KEY (`BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID`) REFERENCES `ACTIVITEIT` (`ACTIVITEIT_ID`);
-- BOVENLIGGENDE_ACTIVITEIT (1 to 0..1, Connector_ID: 681)

ALTER TABLE `ACTIVITEIT` ADD CONSTRAINT FK_ACTIVITEIT_GERELATEERDE_ACTIVITEIT FOREIGN KEY (`GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID`) REFERENCES `ACTIVITEIT` (`ACTIVITEIT_ID`);
-- GERELATEERDE_ACTIVITEIT (1 to 0..1, Connector_ID: 682)

ALTER TABLE `JURIDISCHE_REGEL` ADD CONSTRAINT FK_JURIDISCHE_REGEL_IS_OPGENOMEN_IN FOREIGN KEY (`IS_OPGENOMEN_IN_REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- IS_OPGENOMEN_IN (1..* to 1, Connector_ID: 683)

ALTER TABLE `REGELTEKST` ADD CONSTRAINT FK_REGELTEKST_IS_GERELATEERD FOREIGN KEY (`IS_GERELATEERD_REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- IS_GERELATEERD (0..1 to 0..*, Connector_ID: 685)

ALTER TABLE `REGELTEKST` ADD CONSTRAINT FK_REGELTEKST_WERKINGSGEBIED FOREIGN KEY (`WERKINGSGEBIED_REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- WERKINGSGEBIED (0..1 to 0..*, Connector_ID: 687)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_BETREFT_EERDER_VERZOEK FOREIGN KEY (`BETREFT_EERDER_VERZOEK_VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- BETREFT_EERDER_VERZOEK (0..1 to 0..*, Connector_ID: 690)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_BEHANDELAAR FOREIGN KEY (`BEHANDELAAR_UITVOERENDE_INSTANTIE_ID`) REFERENCES `UITVOERENDE_INSTANTIE` (`UITVOERENDE_INSTANTIE_ID`);
-- BEHANDELAAR (0..* to 0..1, Connector_ID: 695)

ALTER TABLE `INITIATIEFNEMER` ADD CONSTRAINT FK_INITIATIEFNEMER_HEEFT_ALS_VERANTWOORDELIJKE FOREIGN KEY (`HEEFT_ALS_VERANTWOORDELIJKE_VERZOEK_ID`) REFERENCES `VERZOEK` (`VERZOEK_ID`);
-- HEEFT_ALS_VERANTWOORDELIJKE (1 to 1..*, Connector_ID: 705)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_TYPE_ENUM_ID FOREIGN KEY (`TYPE_ENUM_ID`) REFERENCES `DOEL_VERZOEK_ENUM` (`DOEL_VERZOEK_ENUM_ID`);
-- TYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VERZOEK` ADD CONSTRAINT FK_VERZOEK_DOEL_ENUM_ID FOREIGN KEY (`DOEL_ENUM_ID`) REFERENCES `DOEL_VERZOEK_ENUM` (`DOEL_VERZOEK_ENUM_ID`);
-- DOEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

