CREATE TABLE DOCUMENT (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR(200),
    DOCUMENTIDENTIFICATIE VARCHAR(255),
    DOCUMENTTITEL VARCHAR(200),
    VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE PROJECT (
    PROJECT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200),
    OMSCHRIJVING TEXT
);

CREATE TABLE VERZOEK (
    VERZOEK_ID INTEGER PRIMARY KEY,
    AKKOORDVERKLARING BOOLEAN,
    AMBTSHALVE BOOLEAN,
    BETREFT_EERDER_VERZOEK_VERZOEK_ID INTEGER,
    BETREFT_PROJECT_ID INTEGER,
    DATUMINDIENING DATE,
    DOEL VARCHAR(255),
    NAAM VARCHAR(200),
    REFERENTIEAANVRAGER VARCHAR(200),
    TOELICHTINGLATERAANTELEVERENINFORMATIE TEXT,
    TOELICHTINGNIETAANTELEVERENINFORMATIE TEXT,
    TOELICHTINGVERZOEK TEXT,
    TYPE VARCHAR(255),
    VERZOEKNUMMER VARCHAR(80),
    VOLGNUMMER VARCHAR(80)
);

CREATE TABLE PROJECTLOCATIE (
    PROJECTLOCATIE_ID INTEGER PRIMARY KEY,
    ADRES INTEGER,
    HEEFT_PROJECT_ID INTEGER,
    KADASTRAALPERCEEL VARCHAR(80),
    KADASTRALEGEMEENTE VARCHAR(80),
    KADASTRALESECTIE VARCHAR(80)
);

CREATE TABLE KP_VRZK_DCMNT (
    KP_VRZK_DCMNT_ID INTEGER PRIMARY KEY,
    VERZOEK_ID INTEGER,
    DOCUMENT_ID INTEGER
);

CREATE TABLE KP_VRZK_PRJCTLCT (
    KP_VRZK_PRJCTLCT_ID INTEGER PRIMARY KEY,
    VERZOEK_ID INTEGER,
    PROJECTLOCATIE_ID INTEGER
);

CREATE TABLE PROJECTACTIVITEIT (
    PROJECTACTIVITEIT_ID INTEGER PRIMARY KEY,
    HEEFT_PROJECT_ID INTEGER,
    UITGEVOERD_OP_PROJECTLOCATIE_ID INTEGER
);

CREATE TABLE KP_PRJCTCTVTT_DCMNT (
    KP_PRJCTCTVTT_DCMNT_ID INTEGER PRIMARY KEY,
    PROJECTACTIVITEIT_ID INTEGER,
    DOCUMENT_ID INTEGER
);

CREATE TABLE SPECIFICATIE (
    SPECIFICATIE_ID INTEGER PRIMARY KEY,
    ANTWOORD VARCHAR(200),
    BEVAT_VERZOEK_ID INTEGER,
    GEDEFINIEERD_DOOR_PROJECTACTIVITEIT_ID INTEGER,
    GROEPERING VARCHAR(200),
    PUBLICEERBAAR BOOLEAN,
    VRAAGCLASSIFICATIE VARCHAR(255),
    VRAAGID VARCHAR(80),
    VRAAGREFERENTIE VARCHAR(200),
    VRAAGTEKST TEXT
);

CREATE TABLE KP_VRZK_PRJCTCTVTT (
    KP_VRZK_PRJCTCTVTT_ID INTEGER PRIMARY KEY,
    VERZOEK_ID INTEGER,
    PROJECTACTIVITEIT_ID INTEGER
);

ALTER TABLE KP_PRJCTCTVTT_DCMNT ADD CONSTRAINT FK_KP_PRJCTCTVTT_DCMNT_1 FOREIGN KEY (PROJECTACTIVITEIT_ID) REFERENCES PROJECTACTIVITEIT (PROJECTACTIVITEIT_ID);
-- PROJECTACTIVITEIT (many-to-many junction, Connector_ID: 100)

ALTER TABLE KP_PRJCTCTVTT_DCMNT ADD CONSTRAINT FK_KP_PRJCTCTVTT_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 100)

ALTER TABLE KP_VRZK_PRJCTLCT ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 112)

ALTER TABLE KP_VRZK_PRJCTLCT ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_2 FOREIGN KEY (PROJECTLOCATIE_ID) REFERENCES PROJECTLOCATIE (PROJECTLOCATIE_ID);
-- PROJECTLOCATIE (many-to-many junction, Connector_ID: 112)

ALTER TABLE KP_VRZK_DCMNT ADD CONSTRAINT FK_KP_VRZK_DCMNT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 113)

ALTER TABLE KP_VRZK_DCMNT ADD CONSTRAINT FK_KP_VRZK_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 113)

ALTER TABLE KP_VRZK_PRJCTCTVTT ADD CONSTRAINT FK_KP_VRZK_PRJCTCTVTT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 698)

ALTER TABLE KP_VRZK_PRJCTCTVTT ADD CONSTRAINT FK_KP_VRZK_PRJCTCTVTT_2 FOREIGN KEY (PROJECTACTIVITEIT_ID) REFERENCES PROJECTACTIVITEIT (PROJECTACTIVITEIT_ID);
-- PROJECTACTIVITEIT (many-to-many junction, Connector_ID: 698)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BETREFT_EERDER_VERZOEK FOREIGN KEY (BETREFT_EERDER_VERZOEK_VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- BETREFT_EERDER_VERZOEK (0..1 to 0..*, Connector_ID: 690)

ALTER TABLE SPECIFICATIE ADD CONSTRAINT FK_SPECIFICATIE_BEVAT FOREIGN KEY (BEVAT_VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- BEVAT (1 to 0..*, Connector_ID: 696)

ALTER TABLE SPECIFICATIE ADD CONSTRAINT FK_SPECIFICATIE_GEDEFINIEERD_DOOR FOREIGN KEY (GEDEFINIEERD_DOOR_PROJECTACTIVITEIT_ID) REFERENCES PROJECTACTIVITEIT (PROJECTACTIVITEIT_ID);
-- GEDEFINIEERD_DOOR (1..* to 0..1, Connector_ID: 699)

ALTER TABLE PROJECTACTIVITEIT ADD CONSTRAINT FK_PROJECTACTIVITEIT_UITGEVOERD_OP FOREIGN KEY (UITGEVOERD_OP_PROJECTLOCATIE_ID) REFERENCES PROJECTLOCATIE (PROJECTLOCATIE_ID);
-- UITGEVOERD_OP (1..* to 1, Connector_ID: 700)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BETREFT FOREIGN KEY (BETREFT_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- BETREFT (1..* to 1.., Connector_ID: 701)

ALTER TABLE PROJECTACTIVITEIT ADD CONSTRAINT FK_PROJECTACTIVITEIT_HEEFT FOREIGN KEY (HEEFT_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 703)

ALTER TABLE PROJECTLOCATIE ADD CONSTRAINT FK_PROJECTLOCATIE_HEEFT FOREIGN KEY (HEEFT_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 704)

