CREATE TABLE LOCATIE (
    LOCATIE_ID NUMBER PRIMARY KEY,
    HOOGTE NUMBER,
    NAAM VARCHAR2(200),
    NEN3610ID VARCHAR2(80)
);

CREATE TABLE REGELTEKST (
    REGELTEKST_ID NUMBER PRIMARY KEY,
    IDENTIFICATIE VARCHAR2(200),
    IS_GERELATEERD_REGELTEKST_ID NUMBER,
    OMSCHRIJVING CLOB,
    TEKST CLOB,
    WERKINGSGEBIED_REGELTEKST_ID NUMBER
);

CREATE TABLE THEMA (
    THEMA_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(200),
    OMSCHRIJVING CLOB,
    SUBTHEMA_THEMA_ID NUMBER
);

CREATE TABLE KP_RGLTKST_LCT (
    KP_RGLTKST_LCT_ID NUMBER PRIMARY KEY,
    REGELTEKST_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE OMGEVINGSDOCUMENT (
    OMGEVINGSDOCUMENT_ID NUMBER PRIMARY KEY,
    BEVAT_REGELTEKST_ID NUMBER
);

CREATE TABLE JURIDISCHE_REGEL (
    JURIDISCHE_REGEL_ID NUMBER PRIMARY KEY,
    DATUMBEKEND DATE,
    DATUMEINDEGELDIGHEID DATE,
    DATUMINWERKING DATE,
    DATUMSTART DATE,
    IS_OPGENOMEN_IN_REGELTEKST_ID NUMBER,
    OMSCHRIJVING CLOB,
    REGELTEKST VARCHAR2(200),
    THEMA VARCHAR2(200)
);

CREATE TABLE KP_RGLTKST_THM (
    KP_RGLTKST_THM_ID NUMBER PRIMARY KEY,
    REGELTEKST_ID NUMBER,
    THEMA_ID NUMBER
);

CREATE TABLE KP_JRDSCH_RGL_THM (
    KP_JRDSCH_RGL_THM_ID NUMBER PRIMARY KEY,
    JURIDISCHE_REGEL_ID NUMBER,
    THEMA_ID NUMBER
);

CREATE TABLE KP_JRDSCH_RGL_LCT (
    KP_JRDSCH_RGL_LCT_ID NUMBER PRIMARY KEY,
    JURIDISCHE_REGEL_ID NUMBER,
    LOCATIE_ID NUMBER
);

ALTER TABLE KP_JRDSCH_RGL_LCT ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_JRDSCH_RGL_LCT ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_JRDSCH_RGL_THM ADD CONSTRAINT FK_KP_JRDSCH_RGL_THM_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 669)

ALTER TABLE KP_JRDSCH_RGL_THM ADD CONSTRAINT FK_KP_JRDSCH_RGL_THM_2 FOREIGN KEY (THEMA_ID) REFERENCES THEMA (THEMA_ID);
-- THEMA (many-to-many junction, Connector_ID: 669)

ALTER TABLE KP_RGLTKST_LCT ADD CONSTRAINT FK_KP_RGLTKST_LCT_1 FOREIGN KEY (REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- REGELTEKST (many-to-many junction, Connector_ID: 684)

ALTER TABLE KP_RGLTKST_LCT ADD CONSTRAINT FK_KP_RGLTKST_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 684)

ALTER TABLE KP_RGLTKST_THM ADD CONSTRAINT FK_KP_RGLTKST_THM_1 FOREIGN KEY (REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- REGELTEKST (many-to-many junction, Connector_ID: 688)

ALTER TABLE KP_RGLTKST_THM ADD CONSTRAINT FK_KP_RGLTKST_THM_2 FOREIGN KEY (THEMA_ID) REFERENCES THEMA (THEMA_ID);
-- THEMA (many-to-many junction, Connector_ID: 688)

ALTER TABLE THEMA ADD CONSTRAINT FK_THEMA_SUBTHEMA FOREIGN KEY (SUBTHEMA_THEMA_ID) REFERENCES THEMA (THEMA_ID);
-- SUBTHEMA (0..1 to 0..*, Connector_ID: 657)

ALTER TABLE JURIDISCHE_REGEL ADD CONSTRAINT FK_JURIDISCHE_REGEL_IS_OPGENOMEN_IN FOREIGN KEY (IS_OPGENOMEN_IN_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- IS_OPGENOMEN_IN (1..* to 1, Connector_ID: 683)

ALTER TABLE REGELTEKST ADD CONSTRAINT FK_REGELTEKST_IS_GERELATEERD FOREIGN KEY (IS_GERELATEERD_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- IS_GERELATEERD (0..1 to 0..*, Connector_ID: 685)

ALTER TABLE REGELTEKST ADD CONSTRAINT FK_REGELTEKST_WERKINGSGEBIED FOREIGN KEY (WERKINGSGEBIED_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- WERKINGSGEBIED (0..1 to 0..*, Connector_ID: 687)

ALTER TABLE OMGEVINGSDOCUMENT ADD CONSTRAINT FK_OMGEVINGSDOCUMENT_BEVAT FOREIGN KEY (BEVAT_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- BEVAT (1 to 1..*, Connector_ID: 689)

