CREATE TABLE OPLOSSING (
    OPLOSSING_ID INTEGER PRIMARY KEY,
    EINDDATUM DATE,
    RESULTEERT_IN_NAZORG_ID INTEGER,
    SOORT_ENUM_ID INTEGER,
    STARTDATUM DATE,
    VTLB VARCHAR(255)
);

CREATE TABLE MORATORIUM (
    MORATORIUM_ID INTEGER PRIMARY KEY,
    DATUMAANVRAAG DATE,
    DATUMGOEDKEURING DATE,
    EINDDATUM DATE,
    STARTDATUM DATE
);

CREATE TABLE UITSTROOM (
    UITSTROOM_ID INTEGER PRIMARY KEY,
    DATUM DATE,
    DATUMBEEINDIGINGSBESCHIKKING DATE,
    OMSCHRIJVING TEXT,
    REDEN_ENUM_ID INTEGER
);

CREATE TABLE GEMEENTE (
    GEMEENTE_ID INTEGER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD BOOLEAN,
    GEMEENTECODE VARCHAR(255),
    GEMEENTENAAM VARCHAR(80),
    GEMEENTENAAM_NEN VARCHAR(255),
    GEOMETRIE GEOMETRY,
    IDENTIFICATIE VARCHAR(255),
    VERSIE INTEGER
);

CREATE TABLE KP_GMNT_IS_OVRGGN_IN (
    KP_GMNT_IS_OVRGGN_IN_ID INTEGER PRIMARY KEY,
    IS_OVERGEGAAN_IN_1_ID INTEGER,
    IS_OVERGEGAAN_IN_2_ID INTEGER
);

CREATE TABLE INTAKE (
    INTAKE_ID INTEGER PRIMARY KEY,
    BESCHIKKINGSDATUM DATE,
    BESCHIKKINGSSOORT VARCHAR(255),
    EINDDATUM DATE,
    RESULTEERT_IN_BEGELEIDING_ID INTEGER,
    RESULTEERT_IN_INFORMATIEENADVIES_ID INTEGER,
    RESULTEERT_IN__STABILISATIE_ID INTEGER,
    STARTDATUM DATE
);

CREATE TABLE SCHULDHULPORGANISATIE (
    SCHULDHULPORGANISATIE_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200)
);

CREATE TABLE LEEFSITUATIE (
    LEEFSITUATIE_ID INTEGER PRIMARY KEY,
    DATUMGELDIGTOT DATE,
    DATUMGELDIGVANAF DATE
);

CREATE TABLE CLIENT (
    CLIENT_ID INTEGER PRIMARY KEY,
    CODE VARCHAR(80),
    GEZAGSDRAGERGEKEND BOOLEAN,
    HEEFT_FINANCIELE_SITUATIE_LEEFSITUATIE_ID INTEGER,
    JURIDISCHESTATUS VARCHAR(80),
    WETTELIJKEVERTEGENWOORDIGING VARCHAR(80)
);

CREATE TABLE WSNP_TRAJECT (
    WSNP_TRAJECT_ID INTEGER PRIMARY KEY,
    DATUMGOEDKEURING DATE,
    DATUMVERZOEK DATE,
    EINDDATUM DATE,
    HEEFT_LEEFSITUATIE_ID INTEGER,
    STARTDATUM DATE
);

CREATE TABLE ENUMUITSTROOMREDEN_ENUM (
    ENUMUITSTROOMREDEN_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMUITSTROOMREDEN_ENUM (ENUMUITSTROOMREDEN_ENUM_ID, VALUE) VALUES
    (1, 'AFGEROND'),
    (2, 'INGETROKKEN'),
    (3, 'NIETVERSCHENEN'),
    (4, 'NIET_PASSEND'),
    (5, 'OVERIG'),
    (6, 'OVERLEDEN'),
    (7, 'VERHUISD'),
    (8, 'VOLDOET_NIET'),
    (9, 'ZELF');

CREATE TABLE INFORMATIEENADVIES (
    INFORMATIEENADVIES_ID INTEGER PRIMARY KEY,
    EINDDATUM DATE,
    STARTDATUM DATE
);

CREATE TABLE VOORLOPIGEVOORZIENING_ (
    VOORLOPIGEVOORZIENING__ID INTEGER PRIMARY KEY,
    EINDDATUM DATE,
    STARTDATUM DATE
);

CREATE TABLE KP_SCHLDHLPRGNST_SCHLDHLPTRJCT (
    KP_SCHLDHLPRGNST_SCHLDHLPTRJCT_ID INTEGER PRIMARY KEY,
    SCHULDHULPORGANISATIE_ID INTEGER,
    SCHULDHULPTRAJECT_ID INTEGER
);

CREATE TABLE ENUMBEGELEIDINGSSOORT_ENUM (
    ENUMBEGELEIDINGSSOORT_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMBEGELEIDINGSSOORT_ENUM (ENUMBEGELEIDINGSSOORT_ENUM_ID, VALUE) VALUES
    (1, 'BESCHERMINGSBEWIND'),
    (2, 'BUDGETBEGELEIDING'),
    (3, 'BUDGETBEHEER'),
    (4, 'BUDGETCOACHING'),
    (5, 'LANGE_TERMIJN_BEGELEIDING_DFD_');

CREATE TABLE PLANVANAANPAK (
    PLANVANAANPAK_ID INTEGER PRIMARY KEY,
    DATUMAFRONDING DATE
);

CREATE TABLE SCHULDHULPTRAJECT (
    SCHULDHULPTRAJECT_ID INTEGER PRIMARY KEY,
    BEVAT_AANMELDING_ID INTEGER,
    BEVAT_BEGELEIDING_ID INTEGER,
    BEVAT_INFORMATIEENADVIES_ID INTEGER,
    BEVAT_INTAKE_ID INTEGER,
    BEVAT_NAZORG_ID INTEGER,
    BEVAT_OPLOSSING_ID INTEGER,
    BEVAT_SCHULDREGELING_ID INTEGER,
    BEVAT_STABILISATIE_ID INTEGER,
    EINDDATUM DATE,
    HEEFT_PLANVANAANPAK_ID INTEGER,
    HEEFT_TRAJECT_CLIENT_ID INTEGER,
    HEEFT_VOORLOPIGEVOORZIENING__ID INTEGER,
    KAN_HEBBEN_CRISISINTERVENTIE_ID INTEGER,
    KAN_HEBBEN_MORATORIUM_ID INTEGER,
    OMSCHRIJVING TEXT,
    ONDER_VERANTWOORDELIJKHEID_VAN_GEMEENTE_ID INTEGER,
    STARTDATUM DATE,
    TOEKENNINGSDATUM DATE,
    TOTAALSCHULDBEDRAGBIJAANVANGSCHULD DECIMAL(10,2),
    UITSTROOM_UITSTROOM_ID INTEGER
);

CREATE TABLE SCHULDREGELING (
    SCHULDREGELING_ID INTEGER PRIMARY KEY,
    AFGEWEZEN VARCHAR(255),
    DATUM DATE,
    DATUMVERZOEKDWANGAKKOORD DATE,
    DWANGAKKOORD BOOLEAN,
    INGETROKKEN VARCHAR(255),
    RESULTEERT_IN_BEGELEIDING_ID INTEGER,
    RESULTEERT_IN_OPLOSSING_ID INTEGER,
    TOEGEKEND VARCHAR(255)
);

CREATE TABLE CRISISINTERVENTIE (
    CRISISINTERVENTIE_ID INTEGER PRIMARY KEY,
    EINDDATUM DATE,
    STARTDATUM DATE
);

CREATE TABLE ENUMOPLOSSINGSSOORT_ENUM (
    ENUMOPLOSSINGSSOORT_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMOPLOSSINGSSOORT_ENUM (ENUMOPLOSSINGSSOORT_ENUM_ID, VALUE) VALUES
    (1, '0_AANBOD'),
    (2, 'BETALINGSREGELING'),
    (3, 'HERFINANCIERING'),
    (4, 'SANERINGSKREDIET'),
    (5, 'SCHULDBEMIDDELING');

CREATE TABLE STABILISATIE (
    STABILISATIE_ID INTEGER PRIMARY KEY,
    EINDDATUM DATE,
    RESULTEERT_IN_BEGELEIDING_ID INTEGER,
    RESULTEERT_IN_SCHULDREGELING_ID INTEGER,
    STARTDATUM DATE
);

CREATE TABLE AANMELDING (
    AANMELDING_ID INTEGER PRIMARY KEY,
    CRISISINTERVENTIE BOOLEAN,
    EINDDATUM DATE,
    RESULTEERT_IN_INTAKE_ID INTEGER,
    STARTDATUM DATE
);

CREATE TABLE NAZORG (
    NAZORG_ID INTEGER PRIMARY KEY,
    EINDDATUM DATE,
    STARTDATUM DATE
);

CREATE TABLE BEGELEIDING (
    BEGELEIDING_ID INTEGER PRIMARY KEY,
    EINDDATUM DATE,
    RESULTEERT_IN_NAZORG_ID INTEGER,
    SOORT_ENUM_ID INTEGER,
    STARTDATUM DATE
);

ALTER TABLE KP_SCHLDHLPRGNST_SCHLDHLPTRJCT ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_SCHLDHLPTRJCT_1 FOREIGN KEY (SCHULDHULPORGANISATIE_ID) REFERENCES SCHULDHULPORGANISATIE (SCHULDHULPORGANISATIE_ID);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 967)

ALTER TABLE KP_SCHLDHLPRGNST_SCHLDHLPTRJCT ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_SCHLDHLPTRJCT_2 FOREIGN KEY (SCHULDHULPTRAJECT_ID) REFERENCES SCHULDHULPTRAJECT (SCHULDHULPTRAJECT_ID);
-- SCHULDHULPTRAJECT (many-to-many junction, Connector_ID: 967)

ALTER TABLE KP_GMNT_IS_OVRGGN_IN ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_1 FOREIGN KEY (IS_OVERGEGAAN_IN_1_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE KP_GMNT_IS_OVRGGN_IN ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_2 FOREIGN KEY (IS_OVERGEGAAN_IN_2_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE STABILISATIE ADD CONSTRAINT FK_STABILISATIE_RESULTEERT_IN FOREIGN KEY (RESULTEERT_IN_SCHULDREGELING_ID) REFERENCES SCHULDREGELING (SCHULDREGELING_ID);
-- RESULTEERT_IN (1 to 0..1, Connector_ID: 959)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT FOREIGN KEY (BEVAT_STABILISATIE_ID) REFERENCES STABILISATIE (STABILISATIE_ID);
-- BEVAT (1 to 0..1, Connector_ID: 960)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_UITSTROOM FOREIGN KEY (UITSTROOM_UITSTROOM_ID) REFERENCES UITSTROOM (UITSTROOM_ID);
-- UITSTROOM (1 to 0..1, Connector_ID: 961)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_ONDER_VERANTWOORDELIJKHEID_VAN FOREIGN KEY (ONDER_VERANTWOORDELIJKHEID_VAN_GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- ONDER_VERANTWOORDELIJKHEID_VAN (0..* to 1, Connector_ID: 962)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_HEEFT FOREIGN KEY (HEEFT_VOORLOPIGEVOORZIENING__ID) REFERENCES VOORLOPIGEVOORZIENING_ (VOORLOPIGEVOORZIENING__ID);
-- HEEFT (1 to 0..*, Connector_ID: 963)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_2 FOREIGN KEY (BEVAT_SCHULDREGELING_ID) REFERENCES SCHULDREGELING (SCHULDREGELING_ID);
-- BEVAT (1 to 0..1, Connector_ID: 964)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_HEEFT_TRAJECT FOREIGN KEY (HEEFT_TRAJECT_CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- HEEFT_TRAJECT (0..* to 1..2, Connector_ID: 965)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_HEEFT_2 FOREIGN KEY (HEEFT_PLANVANAANPAK_ID) REFERENCES PLANVANAANPAK (PLANVANAANPAK_ID);
-- HEEFT (1 to 0..1, Connector_ID: 972)

ALTER TABLE SCHULDREGELING ADD CONSTRAINT FK_SCHULDREGELING_RESULTEERT_IN FOREIGN KEY (RESULTEERT_IN_OPLOSSING_ID) REFERENCES OPLOSSING (OPLOSSING_ID);
-- RESULTEERT_IN (1 to 0..1, Connector_ID: 975)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_3 FOREIGN KEY (BEVAT_OPLOSSING_ID) REFERENCES OPLOSSING (OPLOSSING_ID);
-- BEVAT (1 to 0..1, Connector_ID: 976)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_4 FOREIGN KEY (BEVAT_NAZORG_ID) REFERENCES NAZORG (NAZORG_ID);
-- BEVAT (1 to 0..1, Connector_ID: 978)

ALTER TABLE OPLOSSING ADD CONSTRAINT FK_OPLOSSING_RESULTEERT_IN FOREIGN KEY (RESULTEERT_IN_NAZORG_ID) REFERENCES NAZORG (NAZORG_ID);
-- RESULTEERT_IN (0..1 to 0..1, Connector_ID: 979)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_KAN_HEBBEN FOREIGN KEY (KAN_HEBBEN_MORATORIUM_ID) REFERENCES MORATORIUM (MORATORIUM_ID);
-- KAN_HEBBEN (1 to 0..*, Connector_ID: 980)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT_FINANCIELE_SITUATIE FOREIGN KEY (HEEFT_FINANCIELE_SITUATIE_LEEFSITUATIE_ID) REFERENCES LEEFSITUATIE (LEEFSITUATIE_ID);
-- HEEFT_FINANCIELE_SITUATIE (1 to 0..*, Connector_ID: 981)

ALTER TABLE WSNP_TRAJECT ADD CONSTRAINT FK_WSNP_TRAJECT_HEEFT FOREIGN KEY (HEEFT_LEEFSITUATIE_ID) REFERENCES LEEFSITUATIE (LEEFSITUATIE_ID);
-- HEEFT (0..* to 1, Connector_ID: 982)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_5 FOREIGN KEY (BEVAT_INTAKE_ID) REFERENCES INTAKE (INTAKE_ID);
-- BEVAT (1 to 0..1, Connector_ID: 986)

ALTER TABLE INTAKE ADD CONSTRAINT FK_INTAKE_RESULTEERT_IN_ FOREIGN KEY (RESULTEERT_IN__STABILISATIE_ID) REFERENCES STABILISATIE (STABILISATIE_ID);
-- RESULTEERT_IN_ (1 to 0..1, Connector_ID: 987)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_6 FOREIGN KEY (BEVAT_INFORMATIEENADVIES_ID) REFERENCES INFORMATIEENADVIES (INFORMATIEENADVIES_ID);
-- BEVAT (1 to 0..1, Connector_ID: 989)

ALTER TABLE INTAKE ADD CONSTRAINT FK_INTAKE_RESULTEERT_IN FOREIGN KEY (RESULTEERT_IN_INFORMATIEENADVIES_ID) REFERENCES INFORMATIEENADVIES (INFORMATIEENADVIES_ID);
-- RESULTEERT_IN (0..1 to 0..1, Connector_ID: 990)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_KAN_HEBBEN_2 FOREIGN KEY (KAN_HEBBEN_CRISISINTERVENTIE_ID) REFERENCES CRISISINTERVENTIE (CRISISINTERVENTIE_ID);
-- KAN_HEBBEN (1 to 0..*, Connector_ID: 991)

ALTER TABLE SCHULDREGELING ADD CONSTRAINT FK_SCHULDREGELING_RESULTEERT_IN_2 FOREIGN KEY (RESULTEERT_IN_BEGELEIDING_ID) REFERENCES BEGELEIDING (BEGELEIDING_ID);
-- RESULTEERT_IN (0..1 to 0..*, Connector_ID: 994)

ALTER TABLE INTAKE ADD CONSTRAINT FK_INTAKE_RESULTEERT_IN_2 FOREIGN KEY (RESULTEERT_IN_BEGELEIDING_ID) REFERENCES BEGELEIDING (BEGELEIDING_ID);
-- RESULTEERT_IN (0..1 to 0..*, Connector_ID: 995)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_7 FOREIGN KEY (BEVAT_BEGELEIDING_ID) REFERENCES BEGELEIDING (BEGELEIDING_ID);
-- BEVAT (1 to 0..*, Connector_ID: 996)

ALTER TABLE STABILISATIE ADD CONSTRAINT FK_STABILISATIE_RESULTEERT_IN_2 FOREIGN KEY (RESULTEERT_IN_BEGELEIDING_ID) REFERENCES BEGELEIDING (BEGELEIDING_ID);
-- RESULTEERT_IN (0..1 to 0..*, Connector_ID: 997)

ALTER TABLE BEGELEIDING ADD CONSTRAINT FK_BEGELEIDING_RESULTEERT_IN FOREIGN KEY (RESULTEERT_IN_NAZORG_ID) REFERENCES NAZORG (NAZORG_ID);
-- RESULTEERT_IN (0..1 to 0..1, Connector_ID: 998)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_8 FOREIGN KEY (BEVAT_AANMELDING_ID) REFERENCES AANMELDING (AANMELDING_ID);
-- BEVAT (1 to 0..1, Connector_ID: 1000)

ALTER TABLE AANMELDING ADD CONSTRAINT FK_AANMELDING_RESULTEERT_IN FOREIGN KEY (RESULTEERT_IN_INTAKE_ID) REFERENCES INTAKE (INTAKE_ID);
-- RESULTEERT_IN (1 to 0..1, Connector_ID: 1001)

ALTER TABLE BEGELEIDING ADD CONSTRAINT FK_BEGELEIDING_SOORT_ENUM_ID FOREIGN KEY (SOORT_ENUM_ID) REFERENCES ENUMBEGELEIDINGSSOORT_ENUM (ENUMBEGELEIDINGSSOORT_ENUM_ID);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPLOSSING ADD CONSTRAINT FK_OPLOSSING_SOORT_ENUM_ID FOREIGN KEY (SOORT_ENUM_ID) REFERENCES ENUMOPLOSSINGSSOORT_ENUM (ENUMOPLOSSINGSSOORT_ENUM_ID);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE UITSTROOM ADD CONSTRAINT FK_UITSTROOM_REDEN_ENUM_ID FOREIGN KEY (REDEN_ENUM_ID) REFERENCES ENUMUITSTROOMREDEN_ENUM (ENUMUITSTROOMREDEN_ENUM_ID);
-- REDEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

