CREATE TABLE FRACTIE (
    FRACTIE_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE MILIEUSTRAAT (
    MILIEUSTRAAT_ID VARCHAR2(255) PRIMARY KEY,
        ADRESAANDUIDING VARCHAR2(255),
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE KP_MLSTRT (
    KP_MLSTRT_ID VARCHAR2(255) PRIMARY KEY,
    MILIEUSTRAAT_ID VARCHAR2(255),
    FRACTIE_ID VARCHAR2(255)
);

CREATE TABLE PRIJSREGEL (
    PRIJSREGEL_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG NUMBER(10,2),
        BETREFT_FRACTIE_ID VARCHAR2(255),
        CREDIT NUMBER(1)
);

CREATE TABLE STORTING (
    STORTING_ID VARCHAR2(255) PRIMARY KEY,
        BIJ_MILIEUSTRAAT_ID VARCHAR2(255),
        DATUMTIJD TIMESTAMP,
        GEWICHT NUMBER
);

CREATE TABLE KP_STRTNG (
    KP_STRTNG_ID VARCHAR2(255) PRIMARY KEY,
    STORTING_ID VARCHAR2(255),
    FRACTIE_ID VARCHAR2(255)
);

CREATE TABLE PAS (
    PAS_ID VARCHAR2(255) PRIMARY KEY,
        ADRESAANDUIDING VARCHAR2(255),
        PASNUMMER VARCHAR2(255),
        UITGEVOERDE_STORTING_STORTING_ID VARCHAR2(255)
);

CREATE TABLE KP_PAS_MLSTRT (
    KP_PAS_MLSTRT_ID VARCHAR2(255) PRIMARY KEY,
    PAS_ID VARCHAR2(255),
    MILIEUSTRAAT_ID VARCHAR2(255)
);

ALTER TABLE KP_MLSTRT ADD CONSTRAINT FK_KP_MLSTRT_1 FOREIGN KEY (MILIEUSTRAAT_ID) REFERENCES MILIEUSTRAAT (MILIEUSTRAAT_ID);
-- MILIEUSTRAAT (many-to-many junction, Connector_ID: 825)

ALTER TABLE KP_MLSTRT ADD CONSTRAINT FK_KP_MLSTRT_2 FOREIGN KEY (FRACTIE_ID) REFERENCES FRACTIE (FRACTIE_ID);
-- FRACTIE (many-to-many junction, Connector_ID: 825)

ALTER TABLE KP_PAS_MLSTRT ADD CONSTRAINT FK_KP_PAS_MLSTRT_1 FOREIGN KEY (PAS_ID) REFERENCES PAS (PAS_ID);
-- PAS (many-to-many junction, Connector_ID: 817)

ALTER TABLE KP_PAS_MLSTRT ADD CONSTRAINT FK_KP_PAS_MLSTRT_2 FOREIGN KEY (MILIEUSTRAAT_ID) REFERENCES MILIEUSTRAAT (MILIEUSTRAAT_ID);
-- MILIEUSTRAAT (many-to-many junction, Connector_ID: 817)

ALTER TABLE KP_STRTNG ADD CONSTRAINT FK_KP_STRTNG_1 FOREIGN KEY (STORTING_ID) REFERENCES STORTING (STORTING_ID);
-- STORTING (many-to-many junction, Connector_ID: 824)

ALTER TABLE KP_STRTNG ADD CONSTRAINT FK_KP_STRTNG_2 FOREIGN KEY (FRACTIE_ID) REFERENCES FRACTIE (FRACTIE_ID);
-- FRACTIE (many-to-many junction, Connector_ID: 824)

ALTER TABLE PAS ADD CONSTRAINT FK_PAS_UITGEVOERDE_STORTING FOREIGN KEY (UITGEVOERDE_STORTING_STORTING_ID) REFERENCES STORTING (STORTING_ID);
-- UITGEVOERDE_STORTING (1 to 0..*, Connector_ID: 815)

ALTER TABLE PRIJSREGEL ADD CONSTRAINT FK_PRIJSREGEL_BETREFT FOREIGN KEY (BETREFT_FRACTIE_ID) REFERENCES FRACTIE (FRACTIE_ID);
-- BETREFT (1..* to 1, Connector_ID: 826)

ALTER TABLE STORTING ADD CONSTRAINT FK_STORTING_BIJ FOREIGN KEY (BIJ_MILIEUSTRAAT_ID) REFERENCES MILIEUSTRAAT (MILIEUSTRAAT_ID);
-- BIJ (0..* to 1, Connector_ID: 818)

