CREATE TABLE GEO_OBJECT (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEID DATE,
        DATUMEINDEGELDIGHEID DATE,
        GEOMETRIESOORT GEOMETRY,
        IDENTIFICATIE VARCHAR(255)
);

CREATE TABLE BEGROEIDTERREINDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        BEGROEIDTERREINDEELOPTALUD DATE,
        DATUMBEGINGELDIGHEIDBEGROEIDTERREINDEEL DATE,
        DATUMEINDEGELDIGHEIDBEGROEIDTERREINDEEL DATE,
        FYSIEKVOORKOMENBEGROEIDTERREINDEEL DATE,
        GEOMETRIEBEGROEIDTERREINDEEL GEOMETRY,
        IDENTIFICATIEBEGROEIDTERREINDEEL DATE,
        KRUINLIJNGEOMETRIEBEGROEIDTERREINDEEL GEOMETRY,
        LOD0GEOMETRIEBEGROEIDTERREINDEEL GEOMETRY,
        PLUSFYSIEKVOORKOMENBEGROEIDTERREINDEEL DATE,
        RELATIEVEHOOGTELIGGINGBEGROEIDTERREINDEEL DATE,
        STATUSBEGROEIDTERREINDEEL DATE
);

CREATE TABLE FUNCTIONEELGEBIED (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDFUNCTIONEELGEBIED DATE,
        DATUMEINDEGELDIGHEIDFUNCTIONEELGEBIED DATE,
        GEOMETRIEFUNCTIONEELGEBIED GEOMETRY,
        IDENTIFICATIEFUNCTIONEELGEBIED VARCHAR(255),
        NAAMFUNCTIONEELGEBIED VARCHAR(255),
        STATUSFUNCTIONEELGEBIED VARCHAR(255)
);

CREATE TABLE GEBOUWINSTALLATIE (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDGEBOUWINSTALLATIE DATE,
        DATUMEINDEGELDIGHEIDGEBOUWINSTALLATIE DATE,
        GEOMETRIEGEBOUWINSTALLATIE GEOMETRY,
        IDENTIFICATIEGEBOUWINSTALLATIE VARCHAR(255),
        LOD0GEOMETRIEGEBOUWINSTALLATIE GEOMETRY,
        RELATIEVEHOOGTELIGGINGGEBOUWINSTALLATIE VARCHAR(255),
        STATUSGEBOUWINSTALLATIE VARCHAR(255),
        TYPEGEBOUWINSTALLATIE VARCHAR(255)
);

CREATE TABLE INRICHTINGSELEMENT (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDINRICHTINGSELEMENT DATE,
        DATUMEINDEGELDIGHEIDINRICHTINGSELEMENT DATE,
        GEOMETRIEINRICHTINGSELEMENT GEOMETRY,
        IDENTIFICATIEINRICHTINGSELEMENT VARCHAR(255),
        LOD0GEOMETRIEINRICHTINGSELEMENT GEOMETRY,
        PLUSTYPEINRICHTINGSELEMENT VARCHAR(255),
        RELATIEVEHOOGTELIGGINGINRICHTINGSELEMENT VARCHAR(255),
        STATUSINRICHTINGSELEMENT VARCHAR(255),
        TYPEINRICHTINGSELEMENT VARCHAR(255)
);

CREATE TABLE ONBEGROEIDTERREINDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDONBEGROEIDTERREINDEEL DATE,
        DATUMEINDEGELDIGHEIDONBEGROEIDTERREINDEEL DATE,
        FYSIEKVOORKOMENONBEGROEIDTERREINDEEL DATE,
        GEOMETRIEONBEGROEIDTERREINDEEL GEOMETRY,
        IDENTIFICATIEONBEGROEIDTERREINDEEL DATE,
        KRUINLIJNGEOMETRIEONBEGROEIDTERREINDEEL GEOMETRY,
        ONBEGROEIDTERREINDEELOPTALUD DATE,
        PLUSFYSIEKVOORKOMENONBEGROEIDTERREINDEEL DATE,
        RELATIEVEHOOGTELIGGINGONBEGROEIDTERREINDEEL DATE,
        STATUSONBEGROEIDTERREINDEEL DATE
);

CREATE TABLE OVERIGBOUWWERK (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDOVERIGBOUWWERK DATE,
        DATUMEINDEGELDIGHEIDOVERIGBOUWWERK DATE,
        GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        IDENTIFICATIEOVERIGBOUWWERK VARCHAR(255),
        LOD0GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        LOD1GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        LOD2GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        LOD3GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        RELATIEVEHOOGTELIGGINGOVERIGBOUWWERK VARCHAR(255),
        STATUSOVERIGBOUWWERK VARCHAR(255)
);

CREATE TABLE OVERIGESCHEIDING (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDOVERIGESCHEIDING DATE,
        DATUMEINDEGELDIGHEIDOVERIGESCHEIDING DATE,
        GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        IDENTIFICATIEOVERIGESCHEIDING VARCHAR(255),
        LOD0GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        LOD1GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        LOD2GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        LOD3GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        RELATIEVEHOOGTELIGGINGOVERIGESCHEIDING VARCHAR(255),
        STATUSOVERIGESCHEIDING VARCHAR(255),
        TYPEOVERIGESCHEIDING VARCHAR(255)
);

CREATE TABLE SCHEIDING (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDSCHEIDING DATE,
        DATUMEINDEGELDIGHEIDSCHEIDING DATE,
        GEOMETRIESCHEIDING GEOMETRY,
        IDENTIFICATIESCHEIDING VARCHAR(255),
        LOD0GEOMETRIESCHEIDING GEOMETRY,
        LOD1GEOMETRIESCHEIDING GEOMETRY,
        LOD2GEOMETRIESCHEIDING GEOMETRY,
        LOD3GEOMETRIESCHEIDING GEOMETRY,
        RELATIEVEHOOGTELIGGINGSCHEIDING VARCHAR(255),
        STATUSSCHEIDING VARCHAR(255)
);

CREATE TABLE VEGETATIEOBJECT (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDVEGETATIEOBJECT DATE,
        DATUMEINDEGELDIGHEIDVEGETATIEOBJECT DATE,
        GEOMETRIEVEGETATIEOBJECT GEOMETRY,
        IDENTIFICATIEVEGETATIEOBJECT VARCHAR(255),
        LOD0GEOMETRIEVEGETATIEOBJECT GEOMETRY,
        RELATIEVEHOOGTELIGGINGVEGETATIEOBJECT VARCHAR(255),
        STATUSVEGETATIEOBJECT VARCHAR(255),
        TYPEVEGETATIEOBJECT VARCHAR(255)
);

ALTER TABLE BEGROEIDTERREINDEEL ADD CONSTRAINT FK_BEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE FUNCTIONEELGEBIED ADD CONSTRAINT FK_FUNCTIONEELGEBIED_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE GEBOUWINSTALLATIE ADD CONSTRAINT FK_GEBOUWINSTALLATIE_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE INRICHTINGSELEMENT ADD CONSTRAINT FK_INRICHTINGSELEMENT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONBEGROEIDTERREINDEEL ADD CONSTRAINT FK_ONBEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGBOUWWERK ADD CONSTRAINT FK_OVERIGBOUWWERK_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGESCHEIDING ADD CONSTRAINT FK_OVERIGESCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE SCHEIDING ADD CONSTRAINT FK_SCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE VEGETATIEOBJECT ADD CONSTRAINT FK_VEGETATIEOBJECT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

