CREATE TABLE [BEGELEIDING] (
    [BEGELEIDING_ID] INT PRIMARY KEY,
        [EINDDATUM] DATE,
        [SOORT_BEGELEIDINGSSOORT_ID] INT,
        [SOORT_ENUM_ID] INT,
        [STARTDATUM] DATE
);

CREATE TABLE [BEGELEIDINGSSOORT] (
    [BEGELEIDINGSSOORT_ID] INT PRIMARY KEY,
        [SOORT] VARCHAR(255)
);

CREATE TABLE [CONTACTPERSOON] (
    [CONTACTPERSOON_ID] INT PRIMARY KEY,
        [EMAIL] VARCHAR(255),
        [FUNCTIETITEL] VARCHAR(200),
        [NAAM] VARCHAR(200),
        [TELEFOONNUMMER] VARCHAR(200)
);

CREATE TABLE [ENUMBEGELEIDINGSSOORT_ENUM] (
    [ENUMBEGELEIDINGSSOORT_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [ENUMBEGELEIDINGSSOORT_ENUM] ([ENUMBEGELEIDINGSSOORT_ENUM_ID], VALUE) VALUES
    (1, 'BESCHERMINGSBEWIND'),
    (2, 'BUDGETBEGELEIDING'),
    (3, 'BUDGETBEHEER'),
    (4, 'BUDGETCOACHING'),
    (5, 'LANGE_TERMIJN_BEGELEIDING_DFD_');

CREATE TABLE [ENUMOPLOSSINGSSOORT_ENUM] (
    [ENUMOPLOSSINGSSOORT_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [ENUMOPLOSSINGSSOORT_ENUM] ([ENUMOPLOSSINGSSOORT_ENUM_ID], VALUE) VALUES
    (1, '0_AANBOD'),
    (2, 'BETALINGSREGELING'),
    (3, 'HERFINANCIERING'),
    (4, 'SANERINGSKREDIET'),
    (5, 'SCHULDBEMIDDELING');

CREATE TABLE [KP_SCHLDHLPRGNST] (
    [KP_SCHLDHLPRGNST_ID] INT PRIMARY KEY,
    [SCHULDHULPORGANISATIE_ID] INT,
    [BEGELEIDINGSSOORT_ID] INT
);

CREATE TABLE [NIETNATUURLIJKPERSOON] (
    [NIETNATUURLIJKPERSOON_ID] INT PRIMARY KEY,
        [DATUMAANVANG] DATE,
        [DATUMEINDE] DATE,
        [DATUMUITSCHRIJVING] DATE,
        [DATUMVOORTZETTING] DATE,
        [FAXNUMMER] VARCHAR(20),
        [INGESCHREVEN] BIT,
        [INOPRICHTING] BIT,
        [KVKNUMMER] VARCHAR(255),
        [NNPID] VARCHAR(255),
        [RECHTSVORM] VARCHAR(255),
        [RSINNUMMER] VARCHAR(255),
        [STATUTAIRENAAM] VARCHAR(255),
        [STATUTAIREZETEL] VARCHAR(255),
        [WEBSITEURL] VARCHAR(200)
);

CREATE TABLE [OPLOSSING] (
    [OPLOSSING_ID] INT PRIMARY KEY,
        [EINDDATUM] DATE,
        [SOORT_ENUM_ID] INT,
        [SOORT_OPLOSSINGSSOORT_ID] INT,
        [STARTDATUM] DATE,
        [VTLB] VARCHAR(255)
);

CREATE TABLE [OPLOSSINGSSOORT] (
    [OPLOSSINGSSOORT_ID] INT PRIMARY KEY,
        [SOORT] VARCHAR(255)
);

CREATE TABLE [SCHULDHULPORGANISATIE] (
    [NIETNATUURLIJKPERSOON_ID] INT PRIMARY KEY,
        [NAAM] VARCHAR(200)
);

CREATE TABLE [SCHULDHULPTRAJECT] (
    [SCHULDHULPTRAJECT_ID] INT PRIMARY KEY,
        [BEVAT_BEGELEIDING_ID] INT,
        [BEVAT_OPLOSSING_ID] INT,
        [EINDDATUM] DATE,
        [OMSCHRIJVING] NVARCHAR(MAX),
        [STARTDATUM] DATE,
        [TOEKENNINGSDATUM] DATE,
        [TOTAALSCHULDBEDRAGBIJAANVANGSCHULD] DECIMAL(10,2)
);

ALTER TABLE [SCHULDHULPORGANISATIE] ADD CONSTRAINT FK_SCHULDHULPORGANISATIE_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY ([NIETNATUURLIJKPERSOON_ID]) REFERENCES [NIETNATUURLIJKPERSOON] ([NIETNATUURLIJKPERSOON_ID]);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE [KP_SCHLDHLPRGNST] ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_1 FOREIGN KEY ([SCHULDHULPORGANISATIE_ID]) REFERENCES [SCHULDHULPORGANISATIE] ([NIETNATUURLIJKPERSOON_ID]);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 967)

ALTER TABLE [KP_SCHLDHLPRGNST] ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_2 FOREIGN KEY ([SCHULDHULPTRAJECT_ID]) REFERENCES [SCHULDHULPTRAJECT] ([SCHULDHULPTRAJECT_ID]);
-- SCHULDHULPTRAJECT (many-to-many junction, Connector_ID: 967)

ALTER TABLE [KP_SCHLDHLPRGNST] ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_1 FOREIGN KEY ([SCHULDHULPORGANISATIE_ID]) REFERENCES [SCHULDHULPORGANISATIE] ([NIETNATUURLIJKPERSOON_ID]);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 974)

ALTER TABLE [KP_SCHLDHLPRGNST] ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_2 FOREIGN KEY ([OPLOSSINGSSOORT_ID]) REFERENCES [OPLOSSINGSSOORT] ([OPLOSSINGSSOORT_ID]);
-- OPLOSSINGSSOORT (many-to-many junction, Connector_ID: 974)

ALTER TABLE [KP_SCHLDHLPRGNST] ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_1 FOREIGN KEY ([SCHULDHULPORGANISATIE_ID]) REFERENCES [SCHULDHULPORGANISATIE] ([NIETNATUURLIJKPERSOON_ID]);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 992)

ALTER TABLE [KP_SCHLDHLPRGNST] ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_2 FOREIGN KEY ([CONTACTPERSOON_ID]) REFERENCES [CONTACTPERSOON] ([CONTACTPERSOON_ID]);
-- CONTACTPERSOON (many-to-many junction, Connector_ID: 992)

ALTER TABLE [KP_SCHLDHLPRGNST] ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_1 FOREIGN KEY ([SCHULDHULPORGANISATIE_ID]) REFERENCES [SCHULDHULPORGANISATIE] ([NIETNATUURLIJKPERSOON_ID]);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 993)

ALTER TABLE [KP_SCHLDHLPRGNST] ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_2 FOREIGN KEY ([BEGELEIDINGSSOORT_ID]) REFERENCES [BEGELEIDINGSSOORT] ([BEGELEIDINGSSOORT_ID]);
-- BEGELEIDINGSSOORT (many-to-many junction, Connector_ID: 993)

ALTER TABLE [BEGELEIDING] ADD CONSTRAINT FK_BEGELEIDING_SOORT FOREIGN KEY ([SOORT_BEGELEIDINGSSOORT_ID]) REFERENCES [BEGELEIDINGSSOORT] ([BEGELEIDINGSSOORT_ID]);
-- SOORT (0..* to 1, Connector_ID: 999)

ALTER TABLE [BEGELEIDING] ADD CONSTRAINT FK_BEGELEIDING_SOORT_ENUM_ID FOREIGN KEY ([SOORT_ENUM_ID]) REFERENCES [ENUMBEGELEIDINGSSOORT_ENUM] ([ENUMBEGELEIDINGSSOORT_ENUM_ID]);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [OPLOSSING] ADD CONSTRAINT FK_OPLOSSING_SOORT FOREIGN KEY ([SOORT_OPLOSSINGSSOORT_ID]) REFERENCES [OPLOSSINGSSOORT] ([OPLOSSINGSSOORT_ID]);
-- SOORT (0..* to 1, Connector_ID: 977)

ALTER TABLE [OPLOSSING] ADD CONSTRAINT FK_OPLOSSING_SOORT_ENUM_ID FOREIGN KEY ([SOORT_ENUM_ID]) REFERENCES [ENUMOPLOSSINGSSOORT_ENUM] ([ENUMOPLOSSINGSSOORT_ENUM_ID]);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [SCHULDHULPTRAJECT] ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT FOREIGN KEY ([BEVAT_OPLOSSING_ID]) REFERENCES [OPLOSSING] ([OPLOSSING_ID]);
-- BEVAT (1 to 0..1, Connector_ID: 976)

ALTER TABLE [SCHULDHULPTRAJECT] ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_2 FOREIGN KEY ([BEVAT_BEGELEIDING_ID]) REFERENCES [BEGELEIDING] ([BEGELEIDING_ID]);
-- BEVAT (1 to 0..*, Connector_ID: 996)

