CREATE TABLE KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ (
    KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_ID NUMBER PRIMARY KEY,
    IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID NUMBER,
    IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID NUMBER
);

CREATE TABLE BESCHERMDE_STATUS (
    BESCHERMDE_STATUS_ID NUMBER PRIMARY KEY,
    BETREFT_KADASTRALEONROERENDEZAAK_ID NUMBER,
    BETREFT_OPENBARERUIMTE_ID NUMBER,
    BRONNEN VARCHAR2(255),
    COMPLEX VARCHAR2(200),
    DATUMINSCHRIJVINGREGISTER DATE,
    GEMEENTELIJKMONUMENTCODE VARCHAR2(80),
    GEZICHTSCODE VARCHAR2(20),
    NAAM VARCHAR2(200),
    OMSCHRIJVING CLOB,
    OPMERKINGEN CLOB,
    RIJKSMONUMENTCODE VARCHAR2(80),
    TYPE VARCHAR2(255)
);

CREATE TABLE KADASTRALEONROERENDEZAAK (
    KADASTRALEONROERENDEZAAK_ID NUMBER PRIMARY KEY,
    APPARTEMENTSRECHTVOLGNUMMER VARCHAR2(255),
    BEGRENZING VARCHAR2(255),
    CULTUURCODEONBEBOUWD VARCHAR2(255),
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    GERELATEERD_KADASTRALEONROERENDEZAAK_ID NUMBER,
    IDENTIFICATIE VARCHAR2(255),
    KADASTRALEGEMEENTE VARCHAR2(20),
    KADASTRALEGEMEENTECODE VARCHAR2(20),
    KOOPJAAR NUMBER,
    KOOPSOM VARCHAR2(255),
    LANDINRICHTINGRENTEBEDRAG NUMBER(10,2),
    LANDINRICHTINGRENTEEINDEJAAR DATE,
    LIGGING VARCHAR2(255),
    LOCATIEOMSCHRIJVING VARCHAR2(255),
    OPPERVLAKTE NUMBER,
    PERCEELNUMMER VARCHAR2(255),
    SECTIE VARCHAR2(255),
    VALUTACODE VARCHAR2(255)
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDEGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    HUISLETTER VARCHAR2(255),
    HUISNUMMER VARCHAR2(255),
    HUISNUMMERTOEVOEGING VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LIGT_AAN_OPENBARERUIMTE_ID NUMBER,
    POSTCODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    TYPEADRESSEERBAAROBJECT VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID NUMBER,
    HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID NUMBER,
    IDENTIFICATIE VARCHAR2(255),
    TYPEADRESSEERBAAROBJECT VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE OPENBARERUIMTE (
    OPENBARERUIMTE_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS VARCHAR2(255),
    HUISNUMMERRANGE_EVEN_NUMMERS VARCHAR2(255),
    HUISNUMMERRANGE_ONEVEN_NUMMERS VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LABELNAAM VARCHAR2(80),
    NAAMOPENBARERUIMTE VARCHAR2(80),
    STATUS VARCHAR2(255),
    STRAATCODE VARCHAR2(80),
    STRAATNAAM VARCHAR2(255),
    TYPEOPENBARERUIMTE VARCHAR2(255),
    VERSIE NUMBER,
    WEGSEGMENT VARCHAR2(255)
);

ALTER TABLE KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_1 FOREIGN KEY (IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_2 FOREIGN KEY (IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE BESCHERMDE_STATUS ADD CONSTRAINT FK_BESCHERMDE_STATUS_BETREFT FOREIGN KEY (BETREFT_KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- BETREFT (1 to 0..*, Connector_ID: 1144)

ALTER TABLE BESCHERMDE_STATUS ADD CONSTRAINT FK_BESCHERMDE_STATUS_BETREFT_2 FOREIGN KEY (BETREFT_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- BETREFT (0..1 to 0..*, Connector_ID: 1147)

ALTER TABLE KADASTRALEONROERENDEZAAK ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GERELATEERD FOREIGN KEY (GERELATEERD_KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- GERELATEERD (1 to 0..*, Connector_ID: 1938)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY (LIGT_AAN_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- LIGT_AAN (0..* to 1, Connector_ID: 2281)

