CREATE TABLE [BEOORDELINGSOORT_ENUM] (
    [BEOORDELINGSOORT_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [BEOORDELINGSOORT_ENUM] ([BEOORDELINGSOORT_ENUM_ID], VALUE) VALUES
    (1, 'NIET_OKE'),
    (2, 'NIET_RELEVANT'),
    (3, 'OKE');

CREATE TABLE [AANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
        [AFGEHANDELD] BIT,
        [CATEGORIE] VARCHAR(200),
        [CATEGORIECODE] VARCHAR(80),
        [DATUMAANMAAK] DATE,
        [DATUMAFHANDELING] DATE,
        [DATUMBEGINSTATUS] DATE,
        [DATUMEINDESTATUS] DATE,
        [HOOFDCATEGORIE] VARCHAR(80),
        [HOOFDCATEGORIECODE] VARCHAR(80),
        [IDENTIFICATIE] VARCHAR(255),
        [KANAAL] VARCHAR(80),
        [ONDERWERP] VARCHAR(200),
        [ONDERWERPCODE] VARCHAR(80),
        [SOORT] VARCHAR(80),
        [STATUS] VARCHAR(80),
        [STATUSCODE] VARCHAR(80),
        [STATUSVOLGORDE] VARCHAR(80),
        [SUBCATEGORIE] VARCHAR(200),
        [SUBCATEGORIECODE] VARCHAR(80)
);

CREATE TABLE [COMBIBON] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
        [SANCTIE] VARCHAR(255)
);

CREATE TABLE [FIETSREGISTRATIE] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
        [GELABELD] BIT,
        [VERWIJDERD] BIT
);

CREATE TABLE [FOTO] (
    [FOTO_ID] INT PRIMARY KEY,
        [BESTANDSGROOTTE] INT,
        [BESTANDSNAAM] VARCHAR(200),
        [BESTANDSTYPE] VARCHAR(80),
        [DATUMTIJD] DATETIME2,
        [LOCATIE] VARCHAR(255),
        [PIXELSX] INT,
        [PIXELSY] INT
);

CREATE TABLE [OBJECT] (
    [OBJECT_ID] INT PRIMARY KEY,
        [ADRESBINNENLAND] VARCHAR(255),
        [ADRESBUITENLAND] VARCHAR(255),
        [DOMEIN] VARCHAR(200),
        [GEOMETRIE] GEOMETRY,
        [IDENTIFICATIE] VARCHAR(50),
        [INDICATIERISICO] VARCHAR(255),
        [KADASTRALEAANDUIDING] VARCHAR(255),
        [NAAM] VARCHAR(200),
        [OBJECTTYPE] VARCHAR(255),
        [TOELICHTING] VARCHAR(255)
);

CREATE TABLE [VTHMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
        [ACTIVITEIT] VARCHAR(80),
        [BEOORDELING_ENUM_ID] INT,
        [DATUMSEPONERING] DATE,
        [DATUMTIJDTOT] DATETIME2,
        [GESEPONEERD] BIT,
        [HEEFT_FOTO_ID] INT,
        [LOCATIE] VARCHAR(255),
        [ORGANISATIEONDERDEEL] VARCHAR(80),
        [OVERTREDINGSCODE] VARCHAR(20),
        [OVERTREDINGSGROEP] VARCHAR(200),
        [REFERENTIENUMMER] VARCHAR(80),
        [RESULTAAT] VARCHAR(80),
        [SOORTVTHMELDING] VARCHAR(80),
        [STATUS] VARCHAR(255),
        [STRAATNAAM] VARCHAR(255),
        [TAAKTYPE] VARCHAR(80),
        [ZAAKNUMMER] VARCHAR(20)
);

CREATE TABLE [BOA] (
    [BOA_ID] INT PRIMARY KEY,
        [VERBALISANT_VTHMELDING_ID] INT
);

CREATE TABLE [KP_VTHMLDNG_OBJCT] (
    [KP_VTHMLDNG_OBJCT_ID] INT PRIMARY KEY,
    [VTHMELDING_ID] INT,
    [OBJECT_ID] INT
);

CREATE TABLE [WAARNEMING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY
);

ALTER TABLE [COMBIBON] ADD CONSTRAINT FK_COMBIBON_GEN_VTHMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [VTHMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to VTHMELDING

ALTER TABLE [FIETSREGISTRATIE] ADD CONSTRAINT FK_FIETSREGISTRATIE_GEN_VTHMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [VTHMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to VTHMELDING

ALTER TABLE [VTHMELDING] ADD CONSTRAINT FK_VTHMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE [WAARNEMING] ADD CONSTRAINT FK_WAARNEMING_GEN_VTHMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [VTHMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to VTHMELDING

ALTER TABLE [KP_VTHMLDNG_OBJCT] ADD CONSTRAINT FK_KP_VTHMLDNG_OBJCT_1 FOREIGN KEY ([VTHMELDING_ID]) REFERENCES [VTHMELDING] ([AANVRAAGOFMELDING_ID]);
-- VTHMELDING (many-to-many junction, Connector_ID: 1297)

ALTER TABLE [KP_VTHMLDNG_OBJCT] ADD CONSTRAINT FK_KP_VTHMLDNG_OBJCT_2 FOREIGN KEY ([OBJECT_ID]) REFERENCES [OBJECT] ([OBJECT_ID]);
-- OBJECT (many-to-many junction, Connector_ID: 1297)

ALTER TABLE [BOA] ADD CONSTRAINT FK_BOA_VERBALISANT FOREIGN KEY ([VERBALISANT_VTHMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- VERBALISANT (1 to 0..*, Connector_ID: 1326)

ALTER TABLE [VTHMELDING] ADD CONSTRAINT FK_VTHMELDING_BEOORDELING_ENUM_ID FOREIGN KEY ([BEOORDELING_ENUM_ID]) REFERENCES [BEOORDELINGSOORT_ENUM] ([BEOORDELINGSOORT_ENUM_ID]);
-- BEOORDELING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VTHMELDING] ADD CONSTRAINT FK_VTHMELDING_HEEFT FOREIGN KEY ([HEEFT_FOTO_ID]) REFERENCES [FOTO] ([FOTO_ID]);
-- HEEFT (0..1 to 0..*, Connector_ID: 1298)

