CREATE TABLE BEOORDELINGSOORT_ENUM (
    BEOORDELINGSOORT_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO BEOORDELINGSOORT_ENUM (BEOORDELINGSOORT_ENUM_ID, VALUE) VALUES
    (1, 'NIET_OKE'),
    (2, 'NIET_RELEVANT'),
    (3, 'OKE');

CREATE TABLE AANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID VARCHAR(255) PRIMARY KEY,
        AFGEHANDELD BOOLEAN,
        CATEGORIE VARCHAR(200),
        CATEGORIECODE VARCHAR(80),
        DATUMAANMAAK DATE,
        DATUMAFHANDELING DATE,
        DATUMBEGINSTATUS DATE,
        DATUMEINDESTATUS DATE,
        HOOFDCATEGORIE VARCHAR(80),
        HOOFDCATEGORIECODE VARCHAR(80),
        IDENTIFICATIE VARCHAR(255),
        KANAAL VARCHAR(80),
        ONDERWERP VARCHAR(200),
        ONDERWERPCODE VARCHAR(80),
        SOORT VARCHAR(80),
        STATUS VARCHAR(80),
        STATUSCODE VARCHAR(80),
        STATUSVOLGORDE VARCHAR(80),
        SUBCATEGORIE VARCHAR(200),
        SUBCATEGORIECODE VARCHAR(80)
);

CREATE TABLE COMBIBON (
    AANVRAAGOFMELDING_ID VARCHAR(255) PRIMARY KEY,
        SANCTIE VARCHAR(255)
);

CREATE TABLE FIETSREGISTRATIE (
    AANVRAAGOFMELDING_ID VARCHAR(255) PRIMARY KEY,
        GELABELD BOOLEAN,
        VERWIJDERD BOOLEAN
);

CREATE TABLE FOTO (
    FOTO_ID VARCHAR(255) PRIMARY KEY,
        BESTANDSGROOTTE INTEGER,
        BESTANDSNAAM VARCHAR(200),
        BESTANDSTYPE VARCHAR(80),
        DATUMTIJD TIMESTAMP,
        LOCATIE VARCHAR(255),
        PIXELSX INTEGER,
        PIXELSY INTEGER
);

CREATE TABLE OBJECT (
    OBJECT_ID VARCHAR(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR(255),
        ADRESBUITENLAND VARCHAR(255),
        DOMEIN VARCHAR(200),
        GEOMETRIE GEOMETRY,
        IDENTIFICATIE VARCHAR(50),
        INDICATIERISICO VARCHAR(255),
        KADASTRALEAANDUIDING VARCHAR(255),
        NAAM VARCHAR(200),
        OBJECTTYPE VARCHAR(255),
        TOELICHTING VARCHAR(255)
);

CREATE TABLE VTHMELDING (
    AANVRAAGOFMELDING_ID VARCHAR(255) PRIMARY KEY,
        ACTIVITEIT VARCHAR(80),
        BEOORDELING_ENUM_ID VARCHAR(255),
        DATUMSEPONERING DATE,
        DATUMTIJDTOT TIMESTAMP,
        GESEPONEERD BOOLEAN,
        HEEFT_FOTO_ID VARCHAR(255),
        LOCATIE VARCHAR(255),
        ORGANISATIEONDERDEEL VARCHAR(80),
        OVERTREDINGSCODE VARCHAR(20),
        OVERTREDINGSGROEP VARCHAR(200),
        REFERENTIENUMMER VARCHAR(80),
        RESULTAAT VARCHAR(80),
        SOORTVTHMELDING VARCHAR(80),
        STATUS VARCHAR(255),
        STRAATNAAM VARCHAR(255),
        TAAKTYPE VARCHAR(80),
        ZAAKNUMMER VARCHAR(20)
);

CREATE TABLE BOA (
    BOA_ID VARCHAR(255) PRIMARY KEY,
        VERBALISANT_VTHMELDING_ID VARCHAR(255)
);

CREATE TABLE KP_VTHMLDNG_OBJCT (
    KP_VTHMLDNG_OBJCT_ID VARCHAR(255) PRIMARY KEY,
    VTHMELDING_ID VARCHAR(255),
    OBJECT_ID VARCHAR(255)
);

CREATE TABLE WAARNEMING (
    AANVRAAGOFMELDING_ID VARCHAR(255) PRIMARY KEY
);

ALTER TABLE COMBIBON ADD CONSTRAINT FK_COMBIBON_GEN_VTHMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VTHMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VTHMELDING

ALTER TABLE FIETSREGISTRATIE ADD CONSTRAINT FK_FIETSREGISTRATIE_GEN_VTHMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VTHMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VTHMELDING

ALTER TABLE VTHMELDING ADD CONSTRAINT FK_VTHMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE WAARNEMING ADD CONSTRAINT FK_WAARNEMING_GEN_VTHMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VTHMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VTHMELDING

ALTER TABLE KP_VTHMLDNG_OBJCT ADD CONSTRAINT FK_KP_VTHMLDNG_OBJCT_1 FOREIGN KEY (VTHMELDING_ID) REFERENCES VTHMELDING (AANVRAAGOFMELDING_ID);
-- VTHMELDING (many-to-many junction, Connector_ID: 1297)

ALTER TABLE KP_VTHMLDNG_OBJCT ADD CONSTRAINT FK_KP_VTHMLDNG_OBJCT_2 FOREIGN KEY (OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- OBJECT (many-to-many junction, Connector_ID: 1297)

ALTER TABLE BOA ADD CONSTRAINT FK_BOA_VERBALISANT FOREIGN KEY (VERBALISANT_VTHMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- VERBALISANT (1 to 0..*, Connector_ID: 1326)

ALTER TABLE VTHMELDING ADD CONSTRAINT FK_VTHMELDING_BEOORDELING_ENUM_ID FOREIGN KEY (BEOORDELING_ENUM_ID) REFERENCES BEOORDELINGSOORT_ENUM (BEOORDELINGSOORT_ENUM_ID);
-- BEOORDELING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VTHMELDING ADD CONSTRAINT FK_VTHMELDING_HEEFT FOREIGN KEY (HEEFT_FOTO_ID) REFERENCES FOTO (FOTO_ID);
-- HEEFT (0..1 to 0..*, Connector_ID: 1298)

