CREATE TABLE ZAAK (
    ZAAK_ID VARCHAR2(255) PRIMARY KEY,
        ARCHIEFNOMINATIE VARCHAR2(255),
        ATTRIBUTE VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMEINDEGEPLAND DATE,
        DATUMEINDEUITERLIJKEAFDOENING DATE,
        DATUMLAATSTEBETALING DATE,
        DATUMPUBLICATIE DATE,
        DATUMREGISTRATIE DATE,
        DATUMSTART DATE,
        DATUMVERNIETIGINGDOSSIER DATE,
        DOCUMENT VARCHAR2(255),
        DUURVERLENGING VARCHAR2(255),
        HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID VARCHAR2(255),
        INDICATIEBETALING VARCHAR2(255),
        INDICATIEDEELZAKEN VARCHAR2(255),
        INDICATIEOPSCHORTING VARCHAR2(255),
        IS_DEELZAAK_VAN_ZAAK_ID VARCHAR2(255),
        LEGES VARCHAR2(100),
        OMSCHRIJVING VARCHAR2(80),
        OMSCHRIJVINGRESULTAAT VARCHAR2(80),
        REDENOPSCHORTING VARCHAR2(200),
        REDENVERLENGING VARCHAR2(200),
        TOELICHTING VARCHAR2(255),
        TOELICHTINGRESULTAAT VARCHAR2(255),
        VERTROUWELIJKHEID VARCHAR2(255),
        ZAAKIDENTIFICATIE VARCHAR2(255),
        ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE AANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        AFGEHANDELD NUMBER(1),
        CATEGORIE VARCHAR2(200),
        CATEGORIECODE VARCHAR2(80),
        DATUMAANMAAK DATE,
        DATUMAFHANDELING DATE,
        DATUMBEGINSTATUS DATE,
        DATUMEINDESTATUS DATE,
        HOOFDCATEGORIE VARCHAR2(80),
        HOOFDCATEGORIECODE VARCHAR2(80),
        IDENTIFICATIE VARCHAR2(255),
        KANAAL VARCHAR2(80),
        KAN_LEIDEN_TOT_ZAAK_ID VARCHAR2(255),
        ONDERWERP VARCHAR2(200),
        ONDERWERPCODE VARCHAR2(80),
        SOORT VARCHAR2(80),
        STATUS VARCHAR2(80),
        STATUSCODE VARCHAR2(80),
        STATUSVOLGORDE VARCHAR2(80),
        SUBCATEGORIE VARCHAR2(200),
        SUBCATEGORIECODE VARCHAR2(80)
);

CREATE TABLE BESLUIT (
    BESLUIT_ID VARCHAR2(255) PRIMARY KEY,
        BESLUIT VARCHAR2(200),
        BESLUITIDENTIFICATIE VARCHAR2(50),
        BESLUITTOELICHTING VARCHAR2(255),
        DATUMBESLUIT DATE,
        DATUMPUBLICATIE DATE,
        DATUMSTART DATE,
        DATUMUITERLIJKEREACTIE DATE,
        DATUMVERVAL DATE,
        DATUMVERZENDING DATE,
        IS_UITKOMST_VAN_ZAAK_ID VARCHAR2(255),
        REDENVERVAL VARCHAR2(255)
);

CREATE TABLE OBJECT (
    OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        BETREFT_ZAAK_ID VARCHAR2(255),
        DOMEIN VARCHAR2(200),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(50),
        INDICATIERISICO VARCHAR2(255),
        IS_BESLUIT_ID VARCHAR2(255),
        KADASTRALEAANDUIDING VARCHAR2(255),
        NAAM VARCHAR2(200),
        OBJECTTYPE VARCHAR2(255),
        TOELICHTING VARCHAR2(255)
);

CREATE TABLE VOMAANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        ACTIVITEITEN VARCHAR2(255),
        ADRES VARCHAR2(255),
        BAGID VARCHAR2(255),
        DOSSIERNUMMER VARCHAR2(200),
        INTAKETYPE VARCHAR2(80),
        INTERNNUMMER VARCHAR2(80),
        KADASTRALEAANDUIDING VARCHAR2(255),
        KENMERK VARCHAR2(80),
        LOCATIE VARCHAR2(255),
        LOCATIEOMSCHRIJVING VARCHAR2(255),
        TOELICHTING CLOB
);

ALTER TABLE VOMAANVRAAGOFMELDING ADD CONSTRAINT FK_VOMAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_KAN_LEIDEN_TOT FOREIGN KEY (KAN_LEIDEN_TOT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 380)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_UITKOMST_VAN FOREIGN KEY (IS_UITKOMST_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_UITKOMST_VAN (0..* to 1, Connector_ID: 295)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_BETREFT FOREIGN KEY (BETREFT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- BETREFT (0..1 to 1, Connector_ID: 264)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_IS FOREIGN KEY (IS_BESLUIT_ID) REFERENCES BESLUIT (BESLUIT_ID);
-- IS (0..1 to 1.., Connector_ID: 293)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (None to 0..*, Connector_ID: 243)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (None to 0..1, Connector_ID: 245)

