CREATE TABLE [KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN] (
    [KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN_ID] INT PRIMARY KEY,
    [IS_ONTSTAAN_UIT_OVERGEGAAN_IN_1_ID] INT,
    [IS_ONTSTAAN_UIT_OVERGEGAAN_IN_2_ID] INT
);

CREATE TABLE [KP_ACTVTT_OMGVNGSWT_VTHZK] (
    [KP_ACTVTT_OMGVNGSWT_VTHZK_ID] INT PRIMARY KEY,
    [ACTIVITEIT_OMGEVINGSWET_ID] INT,
    [VTHZAAK_ID] INT
);

CREATE TABLE [BEVINDING] (
    [BEVINDING_ID] INT PRIMARY KEY,
    [AANGEMAAKTDOOR] VARCHAR(255),
    [ACTIVITEIT] VARCHAR(50),
    [BEVINDING_SELF_ID] INT,
    [CONTROLEELEMENT] VARCHAR(50),
    [CONTROLENIVEAU] VARCHAR(50),
    [DATUMAANMAAK] DATE,
    [DATUMMUTATIE] DATE,
    [DIEPTE] VARCHAR(20),
    [FASE] VARCHAR(20),
    [GEMUTEERDDOOR] VARCHAR(255),
    [HEEFT_INSPECTIE_ID] INT,
    [RESULTAAT] VARCHAR(50),
    [RISICO] VARCHAR(50)
);

CREATE TABLE [AANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
    [AFGEHANDELD_ENUM_ID] INT,
    [CATEGORIE] VARCHAR(200),
    [CATEGORIECODE] VARCHAR(80),
    [DATUMAANMAAK] DATE,
    [DATUMAFHANDELING] DATE,
    [DATUMBEGINSTATUS] DATE,
    [DATUMEINDESTATUS] DATE,
    [HOOFDCATEGORIE] VARCHAR(80),
    [HOOFDCATEGORIECODE] VARCHAR(80),
    [IDENTIFICATIE] VARCHAR(255),
    [INGEDIEND_DOOR_INDIENER_ID] INT,
    [KANAAL] VARCHAR(80),
    [KAN_LEIDEN_TOT_ZAAK_ID] INT,
    [MELDER_RECHTSPERSOON_ID] INT,
    [ONDERWERP] VARCHAR(200),
    [ONDERWERPCODE] VARCHAR(80),
    [SOORT] VARCHAR(80),
    [STATUS] VARCHAR(80),
    [STATUSCODE] VARCHAR(80),
    [STATUSVOLGORDE] VARCHAR(80),
    [SUBCATEGORIE] VARCHAR(200),
    [SUBCATEGORIECODE] VARCHAR(80)
);

CREATE TABLE [VTHAANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
    [OMSCHRIJVING] VARCHAR(255)
);

CREATE TABLE [STATUSTYPE] (
    [STATUSTYPE_ID] INT PRIMARY KEY,
    [DATUMBEGINGELDIGHEIDSTATUSTYPE] DATE,
    [DATUMEINDEGELDIGHEIDSTATUSTYPE] DATE,
    [DOORLOOPTIJDSTATUS] DATETIME2,
    [STATUSTYPEOMSCHRIJVING] VARCHAR(80),
    [STATUSTYPEOMSCHRIJVINGGENERIEK] VARCHAR(80),
    [STATUSTYPEVOLGNUMMER] VARCHAR(255)
);

CREATE TABLE [HEFFINGSVERORDENING] (
    [HEFFINGSVERORDENING_ID] INT PRIMARY KEY,
    [VERMELD_IN_HEFFINGGRONDSLAG_ID] INT
);

CREATE TABLE [BESLUITTYPE] (
    [BESLUITTYPE_ID] INT PRIMARY KEY,
    [BESLUITCATEGORIE] VARCHAR(255),
    [BESLUITTYPEOMSCHRIJVING] VARCHAR(80),
    [BESLUITTYPEOMSCHRIJVINGGENERIEK] VARCHAR(80),
    [DATUMBEGINGELDIGHEIDBESLUITTYPE] DATE,
    [DATUMEINDEGELDIGHEIDBESLUITTYPE] DATE,
    [INDICATIEPUBLICATIE] VARCHAR(255),
    [PUBLICATIETEKST] VARCHAR(255),
    [PUBLICATIETERMIJN] VARCHAR(255),
    [REACTIETERMIJN] VARCHAR(255)
);

CREATE TABLE [VTHZAAK] (
    [ZAAK_ID] INT PRIMARY KEY,
    [BEHANDELAAR] VARCHAR(20),
    [BEVOEGDGEZAG] VARCHAR(50),
    [PRIORITERING] INT,
    [TEAMBEHANDELAAR] VARCHAR(20),
    [UITVOERENDEINSTANTIE] VARCHAR(50),
    [VERKAMERING_ENUM_ID] INT
);

CREATE TABLE [VORDERING] (
    [VORDERING_ID] INT PRIMARY KEY,
    [AANGEMAAKTDOOR] VARCHAR(50),
    [BEDRAGBTW] DECIMAL(10,2),
    [DATUMAANMAAK] DATE,
    [DATUMMUTATIE] DATE,
    [GEACCORDEERD] VARCHAR(50),
    [GEACCORDEERDDOOR] VARCHAR(50),
    [GEACCORDEERDOP] VARCHAR(255),
    [GEEXPORTEERD] VARCHAR(50),
    [GEMUTEERDDOOR] VARCHAR(50),
    [HEEFT_VORDERINGREGEL_ID] INT,
    [HEEFT_VTHZAAK_ID] INT,
    [OMSCHRIJVING] NVARCHAR(MAX),
    [TOTAALBEDRAG] DECIMAL(10,2),
    [TOTAALBEDRAGINCLUSIEF] DECIMAL(10,2),
    [VORDERINGNUMMER] VARCHAR(50)
);

CREATE TABLE [BENOEMDOBJECT] (
    [OBJECT_ID] INT PRIMARY KEY,
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [GEOMETRIEPUNT] GEOMETRY,
    [GEOMETRIEVLAK] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(100)
);

CREATE TABLE [KADASTRALEONROERENDEZAAK] (
    [OBJECT_ID] INT PRIMARY KEY,
    [APPARTEMENTSRECHTVOLGNUMMER] VARCHAR(255),
    [BEGRENZING] VARCHAR(255),
    [CULTUURCODEONBEBOUWD] VARCHAR(255),
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [GERELATEERD_KADASTRALEONROERENDEZAAK_ID] INT,
    [IDENTIFICATIE] VARCHAR(255),
    [KADASTRALEGEMEENTE] VARCHAR(20),
    [KADASTRALEGEMEENTECODE] VARCHAR(20),
    [KOOPJAAR] INT,
    [KOOPSOM] VARCHAR(255),
    [LANDINRICHTINGRENTEBEDRAG] DECIMAL(10,2),
    [LANDINRICHTINGRENTEEINDEJAAR] DATE,
    [LIGGING] VARCHAR(255),
    [LOCATIEOMSCHRIJVING] VARCHAR(255),
    [OPPERVLAKTE] INT,
    [PERCEELNUMMER] VARCHAR(255),
    [SECTIE] VARCHAR(255),
    [VALUTACODE] VARCHAR(255)
);

CREATE TABLE [VORDERINGREGEL] (
    [VORDERINGREGEL_ID] INT PRIMARY KEY,
    [AANGEMAAKT_DOOR] VARCHAR(50),
    [AANMAAKDATUM] DATE,
    [BEDRAG_EXCL_BTW] DECIMAL(10,2),
    [BEDRAG_INCL_BTW] DECIMAL(10,2),
    [BTWCATEGORIE] VARCHAR(50),
    [GEMUTEERD_DOOR] VARCHAR(50),
    [MUTATIEDATUM] DATE,
    [OMSCHRIJVING] VARCHAR(50),
    [PERIODIEK] VARCHAR(50),
    [TYPE] VARCHAR(50)
);

CREATE TABLE [RECHTSPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [ADRESBINNENLAND] VARCHAR(255),
    [ADRESBUITENLAND] VARCHAR(255),
    [ADRESCORRESPONDENTIE] VARCHAR(100),
    [EMAILADRES] VARCHAR(80),
    [FAXNUMMER] VARCHAR(20),
    [IDENTIFICATIE] VARCHAR(255),
    [KVKNUMMER] VARCHAR(20),
    [NAAM] VARCHAR(200),
    [RECHTSVORM] VARCHAR(100),
    [REKENINGNUMMER] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20)
);

CREATE TABLE [KP_SBPRDCTTYP_VTHZK] (
    [KP_SBPRDCTTYP_VTHZK_ID] INT PRIMARY KEY,
    [SUBPRODUCTTYPE_ID] INT,
    [VTHZAAK_ID] INT
);

CREATE TABLE [KP_BTRKKN_ZK] (
    [KP_BTRKKN_ZK_ID] INT PRIMARY KEY,
    [BETROKKENE_ID] INT,
    [ZAAK_ID] INT
);

CREATE TABLE [WABOAANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
    [BOUWKOSTEN] DECIMAL(10,2),
    [OLONUMMER] VARCHAR(80),
    [OMSCHRIJVING] VARCHAR(255),
    [PROJECTKOSTEN] DECIMAL(10,2),
    [REGISTRATIENUMMER] VARCHAR(100)
);

CREATE TABLE [OBJECT] (
    [OBJECT_ID] INT PRIMARY KEY,
    [ADRESBINNENLAND] VARCHAR(255),
    [ADRESBUITENLAND] VARCHAR(200),
    [BETREFT_ZAAK_ID] INT,
    [DOMEIN] VARCHAR(200),
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(50),
    [INDICATIERISICO_ENUM_ID] INT,
    [IS_BESLUIT_ID] INT,
    [IS_KADASTRALEONROERENDEZAAK_ID] INT,
    [KADASTRALEAANDUIDING] VARCHAR(255),
    [NAAM] VARCHAR(200),
    [OBJECTTYPE] VARCHAR(255),
    [TOELICHTING] VARCHAR(255)
);

CREATE TABLE [NUMMERAANDUIDING] (
    [NUMMERAANDUIDING_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDEGELDIGHEID] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [HUISLETTER] VARCHAR(255),
    [HUISNUMMER] VARCHAR(255),
    [HUISNUMMERTOEVOEGING] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [POSTCODE] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [TYPEADRESSEERBAAROBJECT] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [VOMAANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
    [ACTIVITEITEN] VARCHAR(255),
    [ADRES] VARCHAR(255),
    [BAGID] VARCHAR(255),
    [DOSSIERNUMMER] VARCHAR(200),
    [INTAKETYPE] VARCHAR(80),
    [INTERNNUMMER] VARCHAR(80),
    [KADASTRALEAANDUIDING] VARCHAR(255),
    [KENMERK] VARCHAR(80),
    [LOCATIE] VARCHAR(255),
    [LOCATIEOMSCHRIJVING] VARCHAR(255),
    [TOELICHTING] NVARCHAR(MAX)
);

CREATE TABLE [ADRESSEERBAAROBJECT] (
    [OBJECT_ID] INT PRIMARY KEY,
    [HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID] INT,
    [HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID] INT,
    [IDENTIFICATIE] VARCHAR(255),
    [TYPEADRESSEERBAAROBJECT] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [HEFFING] (
    [HEFFING_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [BETREFT_VORDERINGREGEL_ID] INT,
    [CODE] VARCHAR(80),
    [DATUMINDIENING] DATE,
    [GEFACTUREERD_ENUM_ID] INT,
    [HEEFT_GRONDSLAG_HEFFINGGRONDSLAG_ID] INT,
    [INREKENING] VARCHAR(255),
    [NUMMER] INT,
    [RUNNUMMER] INT,
    [SOORT_HEFFINGSOORT_ENUM_ID] INT
);

CREATE TABLE [BESLUIT] (
    [BESLUIT_ID] INT PRIMARY KEY,
    [BESLUITIDENTIFICATIE] VARCHAR(50),
    [BESLUITTOELICHTING] VARCHAR(255),
    [DATUMBESLUIT] DATE,
    [DATUMPUBLICATIE] DATE,
    [DATUMSTART] DATE,
    [DATUMUITERLIJKEREACTIE] DATE,
    [DATUMVERVAL] DATE,
    [DATUMVERZENDING] DATE,
    [IS_UITKOMST_VAN_ZAAK_ID] INT,
    [IS_VAN_BESLUITTYPE_ID] INT,
    [OMSCHRIJVING] VARCHAR(200),
    [REDENVERVAL] VARCHAR(255)
);

CREATE TABLE [ZAAKTYPE] (
    [ZAAKTYPE_ID] INT PRIMARY KEY,
    [ARCHIEFCODE] VARCHAR(20),
    [DATUMBEGINGELDIGHEIDZAAKTYPE] DATE,
    [DATUMEINDEGELDIGHEIDZAAKTYPE] DATE,
    [DOORLOOPTIJDBEHANDELING] DATETIME2,
    [HEEFT_HEFFINGGRONDSLAG_ID] INT,
    [HEEFT_PRODUCTTYPE_ID] INT,
    [HEEFT_STATUSTYPE_ID] INT,
    [INDICATIEPUBLICATIE] VARCHAR(255),
    [PUBLICATIETEKST] VARCHAR(255),
    [SERVICENORMBEHANDELING] VARCHAR(255),
    [TREFWOORD] VARCHAR(255),
    [VERTROUWELIJKAANDUIDING] VARCHAR(20),
    [ZAAKCATEGORIE] VARCHAR(255),
    [ZAAKTYPEOMSCHRIJVING] VARCHAR(80),
    [ZAAKTYPEOMSCHRIJVINGGENERIEK] VARCHAR(80)
);

CREATE TABLE [BETROKKENE] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [ADRESBINNENLAND] VARCHAR(255),
    [ADRESBUITENLAND] VARCHAR(200),
    [IDENTIFICATIE] VARCHAR(50),
    [NAAM] VARCHAR(200)
);

CREATE TABLE [BOOLEAN_ENUM] (
    [BOOLEAN_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID], VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE [INDIENER] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY
);

CREATE TABLE [WOONOVERLASTAANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
    [LOCATIE] VARCHAR(255),
    [LOCATIEOMSCHRIJVING] VARCHAR(255),
    [MELDINGOMSCHRIJVING] VARCHAR(255),
    [MELDINGTEKST] VARCHAR(255)
);

CREATE TABLE [STATUS] (
    [STATUS_ID] INT PRIMARY KEY,
    [DATUMSTATUSGEZET] DATE,
    [INDICATIEIAATSTGEZETTESTATUS] VARCHAR(255),
    [IS_VAN_STATUSTYPE_ID] INT,
    [STATUSTOELICHTING] VARCHAR(255)
);

CREATE TABLE [ACTIVITEIT_OMGEVINGSWET] (
    [ACTIVITEIT_OMGEVINGSWET_ID] INT PRIMARY KEY,
    [OMSCHRIJVING] VARCHAR(200)
);

CREATE TABLE [SUBPRODUCTTYPE] (
    [SUBPRODUCTTYPE_ID] INT PRIMARY KEY,
    [HEEFT_PRODUCTTYPE_ID] INT,
    [OMSCHRIJVING] VARCHAR(200),
    [PRIORITEIT] VARCHAR(255)
);

CREATE TABLE [HEFFINGGRONDSLAG] (
    [HEFFINGGRONDSLAG_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [DOMEIN] VARCHAR(80),
    [HEEFT_ACTIVITEIT_OMGEVINGSWET_ID] INT,
    [HOOFDSTUK] INT,
    [OMSCHRIJVING] VARCHAR(255),
    [PARAGRAAF] VARCHAR(255)
);

CREATE TABLE [WOONFRAUDEAANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
    [ADRES] VARCHAR(255),
    [CATEGORIE] VARCHAR(80),
    [LOCATIEOMSCHRIJVING] VARCHAR(255),
    [MELDINGOMSCHRIJVING] VARCHAR(255),
    [MELDINGTEKST] VARCHAR(255)
);

CREATE TABLE [HEFFINGSOORT_ENUM] (
    [HEFFINGSOORT_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [HEFFINGSOORT_ENUM] ([HEFFINGSOORT_ENUM_ID], VALUE) VALUES
    (1, 'LEGES'),
    (2, 'PRECARIO');

CREATE TABLE [KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ] (
    [KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_ID] INT PRIMARY KEY,
    [IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID] INT,
    [IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID] INT
);

CREATE TABLE [MORAANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
    [CROW_ENUM_ID] INT,
    [LOCATIE] VARCHAR(255),
    [LOCATIEOMSCHRIJVING] VARCHAR(255),
    [MELDINGOMSCHRIJVING] VARCHAR(255),
    [MELDINGTEKST] VARCHAR(255)
);

CREATE TABLE [ONBESTEMD_ADRES] (
    [OBJECT_ID] INT PRIMARY KEY,
    [HUISLETTER] VARCHAR(255),
    [HUISNUMMER] VARCHAR(255),
    [HUISNUMMERTOEVOEGING] VARCHAR(255),
    [POSTCODE] VARCHAR(255),
    [STRAATNAAM] VARCHAR(200)
);

CREATE TABLE [INSPECTIE] (
    [INSPECTIE_ID] INT PRIMARY KEY,
    [AANGEMAAKTDOOR] VARCHAR(50),
    [DATUMAANMAAK] DATE,
    [DATUMGEPLAND] DATE,
    [DATUMINSPECTIE] DATE,
    [DATUMMUTATIE] DATE,
    [GEMUTEERDDOOR] VARCHAR(50),
    [HEEFT_VTHZAAK_ID] INT,
    [INSPECTIETYPE] VARCHAR(50),
    [KENMERK] VARCHAR(20),
    [OMSCHRIJVING] VARCHAR(80),
    [OPMERKINGEN] VARCHAR(80),
    [STATUS] VARCHAR(20)
);

CREATE TABLE [PRODUCTTYPE] (
    [PRODUCTTYPE_ID] INT PRIMARY KEY,
    [HEEFT_VTHZAAK_ID] INT,
    [OMSCHRIJVING] VARCHAR(200)
);

CREATE TABLE [ZAAK] (
    [ZAAK_ID] INT PRIMARY KEY,
    [ARCHIEFNOMINATIE] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMEINDEGEPLAND] DATE,
    [DATUMEINDEUITERLIJKEAFDOENING] DATE,
    [DATUMLAATSTEBETALING] DATE,
    [DATUMPUBLICATIE] DATE,
    [DATUMREGISTRATIE] DATE,
    [DATUMSTART] DATE,
    [DATUMVERNIETIGINGDOSSIER] DATE,
    [DUURVERLENGING] VARCHAR(255),
    [HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID] INT,
    [HEEFT_HEFFING_ID] INT,
    [HEEFT_PRODUCT_PRODUCTTYPE_ID] INT,
    [HEEFT_STATUS_ID] INT,
    [INDICATIEBETALING] VARCHAR(255),
    [INDICATIEDEELZAKEN_ENUM_ID] INT,
    [INDICATIEOPSCHORTING] VARCHAR(255),
    [IS_DEELZAAK_VAN_ZAAK_ID] INT,
    [IS_VAN_ZAAKTYPE_ID] INT,
    [LEGES] VARCHAR(100),
    [OMSCHRIJVING] VARCHAR(80),
    [OMSCHRIJVINGRESULTAAT] VARCHAR(80),
    [REDENOPSCHORTING] VARCHAR(200),
    [REDENVERLENGING] VARCHAR(200),
    [TOELICHTING] VARCHAR(255),
    [TOELICHTINGRESULTAAT] VARCHAR(255),
    [VERTROUWELIJKHEID] VARCHAR(255),
    [ZAAKIDENTIFICATIE] VARCHAR(255),
    [ZAAKNIVEAU] VARCHAR(255)
);

ALTER TABLE [INDIENER] ADD CONSTRAINT FK_INDIENER_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [MORAANVRAAGOFMELDING] ADD CONSTRAINT FK_MORAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE [VOMAANVRAAGOFMELDING] ADD CONSTRAINT FK_VOMAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE [VTHAANVRAAGOFMELDING] ADD CONSTRAINT FK_VTHAANVRAAGOFMELDING_GEN_VOMAANVRAAGOFMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [VOMAANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to VOMAANVRAAGOFMELDING

ALTER TABLE [VTHZAAK] ADD CONSTRAINT FK_VTHZAAK_GEN_ZAAK FOREIGN KEY ([ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- Generalization to ZAAK

ALTER TABLE [WABOAANVRAAGOFMELDING] ADD CONSTRAINT FK_WABOAANVRAAGOFMELDING_GEN_VOMAANVRAAGOFMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [VOMAANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to VOMAANVRAAGOFMELDING

ALTER TABLE [WOONFRAUDEAANVRAAGOFMELDING] ADD CONSTRAINT FK_WOONFRAUDEAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE [WOONOVERLASTAANVRAAGOFMELDING] ADD CONSTRAINT FK_WOONOVERLASTAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_GEN_OBJECT FOREIGN KEY ([OBJECT_ID]) REFERENCES [OBJECT] ([OBJECT_ID]);
-- Generalization to OBJECT

ALTER TABLE [BETROKKENE] ADD CONSTRAINT FK_BETROKKENE_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [BENOEMDOBJECT] ADD CONSTRAINT FK_BENOEMDOBJECT_GEN_OBJECT FOREIGN KEY ([OBJECT_ID]) REFERENCES [OBJECT] ([OBJECT_ID]);
-- Generalization to OBJECT

ALTER TABLE [ONBESTEMD_ADRES] ADD CONSTRAINT FK_ONBESTEMD_ADRES_GEN_OBJECT FOREIGN KEY ([OBJECT_ID]) REFERENCES [OBJECT] ([OBJECT_ID]);
-- Generalization to OBJECT

ALTER TABLE [KADASTRALEONROERENDEZAAK] ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GEN_OBJECT FOREIGN KEY ([OBJECT_ID]) REFERENCES [OBJECT] ([OBJECT_ID]);
-- Generalization to OBJECT

ALTER TABLE [KP_SBPRDCTTYP_VTHZK] ADD CONSTRAINT FK_KP_SBPRDCTTYP_VTHZK_1 FOREIGN KEY ([SUBPRODUCTTYPE_ID]) REFERENCES [SUBPRODUCTTYPE] ([SUBPRODUCTTYPE_ID]);
-- SUBPRODUCTTYPE (many-to-many junction, Connector_ID: 1305)

ALTER TABLE [KP_SBPRDCTTYP_VTHZK] ADD CONSTRAINT FK_KP_SBPRDCTTYP_VTHZK_2 FOREIGN KEY ([VTHZAAK_ID]) REFERENCES [VTHZAAK] ([ZAAK_ID]);
-- VTHZAAK (many-to-many junction, Connector_ID: 1305)

ALTER TABLE [KP_ACTVTT_OMGVNGSWT_VTHZK] ADD CONSTRAINT FK_KP_ACTVTT_OMGVNGSWT_VTHZK_1 FOREIGN KEY ([ACTIVITEIT_OMGEVINGSWET_ID]) REFERENCES [ACTIVITEIT_OMGEVINGSWET] ([ACTIVITEIT_OMGEVINGSWET_ID]);
-- ACTIVITEIT_OMGEVINGSWET (many-to-many junction, Connector_ID: 1330)

ALTER TABLE [KP_ACTVTT_OMGVNGSWT_VTHZK] ADD CONSTRAINT FK_KP_ACTVTT_OMGVNGSWT_VTHZK_2 FOREIGN KEY ([VTHZAAK_ID]) REFERENCES [VTHZAAK] ([ZAAK_ID]);
-- VTHZAAK (many-to-many junction, Connector_ID: 1330)

ALTER TABLE [KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ] ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_1 FOREIGN KEY ([IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID]) REFERENCES [KADASTRALEONROERENDEZAAK] ([OBJECT_ID]);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE [KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ] ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_2 FOREIGN KEY ([IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID]) REFERENCES [KADASTRALEONROERENDEZAAK] ([OBJECT_ID]);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE [KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN] ADD CONSTRAINT FK_KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN_1 FOREIGN KEY ([IS_ONTSTAAN_UIT_OVERGEGAAN_IN_1_ID]) REFERENCES [BENOEMDOBJECT] ([OBJECT_ID]);
-- BENOEMDOBJECT (many-to-many junction, Connector_ID: 2013)

ALTER TABLE [KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN] ADD CONSTRAINT FK_KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN_2 FOREIGN KEY ([IS_ONTSTAAN_UIT_OVERGEGAAN_IN_2_ID]) REFERENCES [BENOEMDOBJECT] ([OBJECT_ID]);
-- BENOEMDOBJECT (many-to-many junction, Connector_ID: 2013)

ALTER TABLE [KP_BTRKKN_ZK] ADD CONSTRAINT FK_KP_BTRKKN_ZK_1 FOREIGN KEY ([BETROKKENE_ID]) REFERENCES [BETROKKENE] ([RECHTSPERSOON_ID]);
-- BETROKKENE (many-to-many junction, Connector_ID: 2164)

ALTER TABLE [KP_BTRKKN_ZK] ADD CONSTRAINT FK_KP_BTRKKN_ZK_2 FOREIGN KEY ([ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- ZAAK (many-to-many junction, Connector_ID: 2164)

ALTER TABLE [AANVRAAGOFMELDING] ADD CONSTRAINT FK_AANVRAAGOFMELDING_MELDER FOREIGN KEY ([MELDER_RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- MELDER (1..* to 0..1, Connector_ID: 377)

ALTER TABLE [AANVRAAGOFMELDING] ADD CONSTRAINT FK_AANVRAAGOFMELDING_KAN_LEIDEN_TOT FOREIGN KEY ([KAN_LEIDEN_TOT_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 380)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_HEEFT FOREIGN KEY ([HEEFT_VTHZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT (1..* to 1.., Connector_ID: 1301)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_HEEFT_2 FOREIGN KEY ([HEEFT_VORDERINGREGEL_ID]) REFERENCES [VORDERINGREGEL] ([VORDERINGREGEL_ID]);
-- HEEFT (1.. to 1..*, Connector_ID: 1302)

ALTER TABLE [SUBPRODUCTTYPE] ADD CONSTRAINT FK_SUBPRODUCTTYPE_HEEFT FOREIGN KEY ([HEEFT_PRODUCTTYPE_ID]) REFERENCES [PRODUCTTYPE] ([PRODUCTTYPE_ID]);
-- HEEFT (* to 1, Connector_ID: 1306)

ALTER TABLE [PRODUCTTYPE] ADD CONSTRAINT FK_PRODUCTTYPE_HEEFT FOREIGN KEY ([HEEFT_VTHZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT (1 to 1, Connector_ID: 1310)

ALTER TABLE [INSPECTIE] ADD CONSTRAINT FK_INSPECTIE_HEEFT FOREIGN KEY ([HEEFT_VTHZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT (1..* to 1.., Connector_ID: 1315)

ALTER TABLE [AANVRAAGOFMELDING] ADD CONSTRAINT FK_AANVRAAGOFMELDING_INGEDIEND_DOOR FOREIGN KEY ([INGEDIEND_DOOR_INDIENER_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- INGEDIEND_DOOR (0..* to 1, Connector_ID: 1316)

ALTER TABLE [HEFFINGSVERORDENING] ADD CONSTRAINT FK_HEFFINGSVERORDENING_VERMELD_IN FOREIGN KEY ([VERMELD_IN_HEFFINGGRONDSLAG_ID]) REFERENCES [HEFFINGGRONDSLAG] ([HEFFINGGRONDSLAG_ID]);
-- VERMELD_IN (1 to 0..*, Connector_ID: 1321)

ALTER TABLE [BEVINDING] ADD CONSTRAINT FK_BEVINDING_BEVINDING FOREIGN KEY ([BEVINDING_ID]) REFERENCES [BEVINDING] ([BEVINDING_ID]);
-- unnamed (1 to 0..*, Connector_ID: 1327)

ALTER TABLE [BEVINDING] ADD CONSTRAINT FK_BEVINDING_HEEFT FOREIGN KEY ([HEEFT_INSPECTIE_ID]) REFERENCES [INSPECTIE] ([INSPECTIE_ID]);
-- HEEFT (0..* to 1.., Connector_ID: 1328)

ALTER TABLE [HEFFINGGRONDSLAG] ADD CONSTRAINT FK_HEFFINGGRONDSLAG_HEEFT FOREIGN KEY ([HEEFT_ACTIVITEIT_OMGEVINGSWET_ID]) REFERENCES [ACTIVITEIT_OMGEVINGSWET] ([ACTIVITEIT_OMGEVINGSWET_ID]);
-- HEEFT (1..* to 1.., Connector_ID: 1596)

ALTER TABLE [KADASTRALEONROERENDEZAAK] ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GERELATEERD FOREIGN KEY ([GERELATEERD_KADASTRALEONROERENDEZAAK_ID]) REFERENCES [OBJECT] ([OBJECT_ID]);
-- GERELATEERD (1 to 0..*, Connector_ID: 1938)

ALTER TABLE [HEFFING] ADD CONSTRAINT FK_HEFFING_BETREFT FOREIGN KEY ([BETREFT_VORDERINGREGEL_ID]) REFERENCES [VORDERINGREGEL] ([VORDERINGREGEL_ID]);
-- BETREFT (0..1 to 1.., Connector_ID: 2049)

ALTER TABLE [HEFFING] ADD CONSTRAINT FK_HEFFING_HEEFT_GRONDSLAG FOREIGN KEY ([HEEFT_GRONDSLAG_HEFFINGGRONDSLAG_ID]) REFERENCES [HEFFINGGRONDSLAG] ([HEFFINGGRONDSLAG_ID]);
-- HEEFT_GRONDSLAG (0..* to 1, Connector_ID: 2050)

ALTER TABLE [HEFFING] ADD CONSTRAINT FK_HEFFING_SOORT FOREIGN KEY ([SOORT_ENUM_ID]) REFERENCES [HEFFINGSOORT_ENUM] ([HEFFINGSOORT_ENUM_ID]);
-- SOORT (0..* to 1, Connector_ID: 2051)

ALTER TABLE [BESLUIT] ADD CONSTRAINT FK_BESLUIT_IS_VAN FOREIGN KEY ([IS_VAN_BESLUITTYPE_ID]) REFERENCES [BESLUITTYPE] ([BESLUITTYPE_ID]);
-- IS_VAN (0..* to 1, Connector_ID: 2066)

ALTER TABLE [OBJECT] ADD CONSTRAINT FK_OBJECT_IS FOREIGN KEY ([IS_BESLUIT_ID]) REFERENCES [BESLUIT] ([BESLUIT_ID]);
-- IS (0..1 to 1.., Connector_ID: 2071)

ALTER TABLE [OBJECT] ADD CONSTRAINT FK_OBJECT_IS_2 FOREIGN KEY ([IS_KADASTRALEONROERENDEZAAK_ID]) REFERENCES [OBJECT] ([OBJECT_ID]);
-- IS (0..1 to 0..*, Connector_ID: 2077)

ALTER TABLE [STATUS] ADD CONSTRAINT FK_STATUS_IS_VAN FOREIGN KEY ([IS_VAN_STATUSTYPE_ID]) REFERENCES [STATUSTYPE] ([STATUSTYPE_ID]);
-- IS_VAN (0..* to 1, Connector_ID: 2090)

ALTER TABLE [ZAAKTYPE] ADD CONSTRAINT FK_ZAAKTYPE_HEEFT FOREIGN KEY ([HEEFT_STATUSTYPE_ID]) REFERENCES [STATUSTYPE] ([STATUSTYPE_ID]);
-- HEEFT (1 to 1..*, Connector_ID: 2093)

ALTER TABLE [ZAAKTYPE] ADD CONSTRAINT FK_ZAAKTYPE_HEEFT_2 FOREIGN KEY ([HEEFT_PRODUCTTYPE_ID]) REFERENCES [PRODUCTTYPE] ([PRODUCTTYPE_ID]);
-- HEEFT (1 to 1, Connector_ID: 2096)

ALTER TABLE [ZAAKTYPE] ADD CONSTRAINT FK_ZAAKTYPE_HEEFT_3 FOREIGN KEY ([HEEFT_HEFFINGGRONDSLAG_ID]) REFERENCES [HEFFINGGRONDSLAG] ([HEFFINGGRONDSLAG_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 2097)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_HEEFT FOREIGN KEY ([HEEFT_STATUS_ID]) REFERENCES [STATUS] ([STATUS_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 2101)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_HEEFT_2 FOREIGN KEY ([HEEFT_HEFFING_ID]) REFERENCES [HEFFING] ([HEFFING_ID]);
-- HEEFT (1 to 0..1, Connector_ID: 2103)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY ([HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_HEEFT_PRODUCT FOREIGN KEY ([HEEFT_PRODUCT_PRODUCTTYPE_ID]) REFERENCES [PRODUCTTYPE] ([PRODUCTTYPE_ID]);
-- HEEFT_PRODUCT (1 to 1, Connector_ID: 2110)

ALTER TABLE [BESLUIT] ADD CONSTRAINT FK_BESLUIT_IS_UITKOMST_VAN FOREIGN KEY ([IS_UITKOMST_VAN_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- IS_UITKOMST_VAN (0..* to 1, Connector_ID: 2112)

ALTER TABLE [OBJECT] ADD CONSTRAINT FK_OBJECT_BETREFT FOREIGN KEY ([BETREFT_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- BETREFT (0..1 to 1, Connector_ID: 2117)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY ([IS_VAN_ZAAKTYPE_ID]) REFERENCES [ZAAKTYPE] ([ZAAKTYPE_ID]);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY ([IS_DEELZAAK_VAN_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY ([HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY ([HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE [MORAANVRAAGOFMELDING] ADD CONSTRAINT FK_MORAANVRAAGOFMELDING_CROW_ENUM_ID FOREIGN KEY ([CROW_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- CROW_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VTHZAAK] ADD CONSTRAINT FK_VTHZAAK_VERKAMERING_ENUM_ID FOREIGN KEY ([VERKAMERING_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- VERKAMERING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [AANVRAAGOFMELDING] ADD CONSTRAINT FK_AANVRAAGOFMELDING_AFGEHANDELD_ENUM_ID FOREIGN KEY ([AFGEHANDELD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- AFGEHANDELD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NUMMERAANDUIDING] ADD CONSTRAINT FK_NUMMERAANDUIDING_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_INDICATIEDEELZAKEN_ENUM_ID FOREIGN KEY ([INDICATIEDEELZAKEN_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIEDEELZAKEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [OBJECT] ADD CONSTRAINT FK_OBJECT_INDICATIERISICO_ENUM_ID FOREIGN KEY ([INDICATIERISICO_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIERISICO_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [HEFFING] ADD CONSTRAINT FK_HEFFING_GEFACTUREERD_ENUM_ID FOREIGN KEY ([GEFACTUREERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GEFACTUREERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

