CREATE TABLE INSCHRIJVING (
    INSCHRIJVING_ID VARCHAR(255) PRIMARY KEY,
        DATUM DATE,
        HEEFT_SCHOOL_ID VARCHAR(255)
);

CREATE TABLE KP_SCHL (
    KP_SCHL_ID VARCHAR(255) PRIMARY KEY,
    SCHOOL_ID VARCHAR(255),
    ONDERWIJSLOOPBAAN_ID VARCHAR(255)
);

CREATE TABLE LEERJAAR (
    LEERJAAR_ID VARCHAR(255) PRIMARY KEY,
        JAAREINDE DATE,
        JAARSTART DATE
);

CREATE TABLE LEERLING (
    LEERLING_ID VARCHAR(255) PRIMARY KEY,
        HEEFT_INSCHRIJVING_ID VARCHAR(255),
        HEEFT_ONDERWIJSLOOPBAAN_ID VARCHAR(255),
        HEEFT_STARTKWALIFICATIE_ID VARCHAR(255),
        HEEFT_UITSCHRIJVING_ID VARCHAR(255),
        KWETSBAREJONGERE BOOLEAN
);

CREATE TABLE LOCATIE (
    VASTGOEDOBJECT_ID VARCHAR(255) PRIMARY KEY,
        ADRES VARCHAR(255)
);

CREATE TABLE LOOPBAANSTAP (
    LOOPBAANSTAP_ID VARCHAR(255) PRIMARY KEY,
        KLAS INTEGER,
        ONDERWIJSTYPE_ENUM_ID VARCHAR(255),
        SCHOOLJAAR VARCHAR(255)
);

CREATE TABLE ONDERWIJSLOOPBAAN (
    ONDERWIJSLOOPBAAN_ID VARCHAR(255) PRIMARY KEY,
        LOOPBAANSTAP_ID VARCHAR(255)
);

CREATE TABLE ONDERWIJSSOORT (
    ONDERWIJSSOORT_ID VARCHAR(255) PRIMARY KEY,
        OMSCHRIJVING VARCHAR(80),
        ONDERWIJSTYPE_ENUM_ID VARCHAR(255)
);

CREATE TABLE ONDERWIJSTYPE_ENUM (
    ONDERWIJSTYPE_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ONDERWIJSTYPE_ENUM (ONDERWIJSTYPE_ENUM_ID, VALUE) VALUES
    (1, 'HAVO'),
    (2, 'VMBO_B'),
    (3, 'VMBO_K'),
    (4, 'VMBO_T'),
    (5, 'VWO');

CREATE TABLE SANCTIESOORT_ENUM (
    SANCTIESOORT_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

CREATE TABLE SCHOOL (
    SCHOOL_ID VARCHAR(255) PRIMARY KEY,
        HEEFT_UITSCHRIJVING_ID VARCHAR(255),
        NAAM VARCHAR(200),
        SCHOOL_HEEFT_LOCATIE_ID VARCHAR(255)
);

CREATE TABLE STARTKWALIFICATIE (
    STARTKWALIFICATIE_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEHAALD DATE
);

CREATE TABLE UITSCHRIJVING (
    UITSCHRIJVING_ID VARCHAR(255) PRIMARY KEY,
        DATUM DATE,
        DIPLOMABEHAALD BOOLEAN
);

CREATE TABLE VASTGOEDOBJECT (
    VASTGOEDOBJECT_ID VARCHAR(255) PRIMARY KEY,
        AANTALETAGES INTEGER,
        AANTALPARKEERPLAATSEN INTEGER,
        AANTALRIOLERINGEN INTEGER,
        ADRESAANDUIDING VARCHAR(255),
        AFGEKOCHTEERFPACHT VARCHAR(255),
        AFGESPROKENCONDITIESCORE VARCHAR(255),
        AFKOOPWAARDE VARCHAR(255),
        ASBESTRAPPORTAGEAANWEZIG BOOLEAN,
        BEDRAGAANKOOP DECIMAL(10,2),
        BESTEMMINGSPLAN VARCHAR(200),
        BOEKWAARDE VARCHAR(255),
        BOUWJAAR INTEGER,
        BOUWWERK VARCHAR(80),
        BOVENLIGGENDNIVEAU VARCHAR(80),
        BOVENLIGGENDNIVEAUCODE VARCHAR(20),
        BRUTOVLOEROPPERVLAKTE INTEGER,
        CO2UITSTOOT INTEGER,
        CONDITIESCORE VARCHAR(255),
        DATUMAFSTOTEN DATE,
        DATUMBEREKENINGOPPERVLAK DATE,
        DATUMEIGENDOM DATE,
        DATUMVERKOOP DATE,
        DEELPORTEFEUILLE VARCHAR(80),
        ENERGIEKOSTEN DECIMAL(10,2),
        ENERGIELABEL VARCHAR(255),
        ENERGIEVERBRUIK INTEGER,
        FISCALEWAARDE VARCHAR(255),
        FOTO VARCHAR(255),
        GEARCHIVEERD BOOLEAN,
        HERBOUWWAARDE VARCHAR(255),
        HOOFDSTUK VARCHAR(80),
        IDENTIFICATIE VARCHAR(80),
        JAARLAATSTERENOVATIE VARCHAR(255),
        KOSTENPLAATS DECIMAL(10,2),
        LOCATIE VARCHAR(255),
        MARKTWAARDE VARCHAR(255),
        MONUMENT VARCHAR(255),
        NAAM VARCHAR(80),
        OBJECTSTATUS VARCHAR(255),
        OBJECTSTATUSCODE VARCHAR(255),
        OBJECTTYPE VARCHAR(80),
        OBJECTTYPECODE VARCHAR(255),
        OMSCHRIJVING VARCHAR(80),
        ONDERHOUDSCATEGORIE VARCHAR(80),
        OPPERVLAKTEKANTOOR INTEGER,
        PORTEFEUILLE VARCHAR(80),
        PORTEFEUILLECODE VARCHAR(255),
        PROVINCIE VARCHAR(255),
        TOELICHTING TEXT,
        VERHUURBAARVLOEROPPERVLAK INTEGER,
        VERKOOPBAARHEID VARCHAR(80),
        VERKOOPBEDRAG DECIMAL(10,2),
        VERZEKERDEWAARDE VARCHAR(255),
        WAARDEGROND VARCHAR(255),
        WAARDEOPSTAL VARCHAR(255),
        WIJK VARCHAR(255),
        WOZWAARDE VARCHAR(255)
);

CREATE TABLE VERZUIMSOORT_ENUM (
    VERZUIMSOORT_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO VERZUIMSOORT_ENUM (VERZUIMSOORT_ENUM_ID, VALUE) VALUES
    (1, 'ABSOLUUT'),
    (2, 'RELATIEF');

CREATE TABLE VRIJSTELLINGSOORT_ENUM (
    VRIJSTELLINGSOORT_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

ALTER TABLE LOCATIE ADD CONSTRAINT FK_LOCATIE_GEN_VASTGOEDOBJECT FOREIGN KEY (VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- Generalization to VASTGOEDOBJECT

ALTER TABLE KP_SCHL ADD CONSTRAINT FK_KP_SCHL_1 FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL (SCHOOL_ID);
-- SCHOOL (many-to-many junction, Connector_ID: 1210)

ALTER TABLE KP_SCHL ADD CONSTRAINT FK_KP_SCHL_2 FOREIGN KEY (ONDERWIJSSOORT_ID) REFERENCES ONDERWIJSSOORT (ONDERWIJSSOORT_ID);
-- ONDERWIJSSOORT (many-to-many junction, Connector_ID: 1210)

ALTER TABLE KP_SCHL ADD CONSTRAINT FK_KP_SCHL_1 FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL (SCHOOL_ID);
-- SCHOOL (many-to-many junction, Connector_ID: 1211)

ALTER TABLE KP_SCHL ADD CONSTRAINT FK_KP_SCHL_2 FOREIGN KEY (ONDERWIJSLOOPBAAN_ID) REFERENCES ONDERWIJSLOOPBAAN (ONDERWIJSLOOPBAAN_ID);
-- ONDERWIJSLOOPBAAN (many-to-many junction, Connector_ID: 1211)

ALTER TABLE INSCHRIJVING ADD CONSTRAINT FK_INSCHRIJVING_HEEFT FOREIGN KEY (HEEFT_SCHOOL_ID) REFERENCES SCHOOL (SCHOOL_ID);
-- HEEFT (0..* to 1, Connector_ID: 1220)

ALTER TABLE LEERLING ADD CONSTRAINT FK_LEERLING_HEEFT FOREIGN KEY (HEEFT_UITSCHRIJVING_ID) REFERENCES UITSCHRIJVING (UITSCHRIJVING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1215)

ALTER TABLE LEERLING ADD CONSTRAINT FK_LEERLING_HEEFT_2 FOREIGN KEY (HEEFT_ONDERWIJSLOOPBAAN_ID) REFERENCES ONDERWIJSLOOPBAAN (ONDERWIJSLOOPBAAN_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1216)

ALTER TABLE LEERLING ADD CONSTRAINT FK_LEERLING_HEEFT_3 FOREIGN KEY (HEEFT_STARTKWALIFICATIE_ID) REFERENCES STARTKWALIFICATIE (STARTKWALIFICATIE_ID);
-- HEEFT (1 to 0..1, Connector_ID: 1217)

ALTER TABLE LEERLING ADD CONSTRAINT FK_LEERLING_HEEFT_4 FOREIGN KEY (HEEFT_INSCHRIJVING_ID) REFERENCES INSCHRIJVING (INSCHRIJVING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1219)

ALTER TABLE LOOPBAANSTAP ADD CONSTRAINT FK_LOOPBAANSTAP_ONDERWIJSTYPE_ENUM_ID FOREIGN KEY (ONDERWIJSTYPE_ENUM_ID) REFERENCES ONDERWIJSTYPE_ENUM (ONDERWIJSTYPE_ENUM_ID);
-- ONDERWIJSTYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ONDERWIJSLOOPBAAN ADD CONSTRAINT FK_ONDERWIJSLOOPBAAN_LOOPBAANSTAP FOREIGN KEY (LOOPBAANSTAP_ID) REFERENCES LOOPBAANSTAP (LOOPBAANSTAP_ID);
-- unnamed (1 to 0..*, Connector_ID: 1212)

ALTER TABLE ONDERWIJSSOORT ADD CONSTRAINT FK_ONDERWIJSSOORT_ONDERWIJSTYPE_ENUM_ID FOREIGN KEY (ONDERWIJSTYPE_ENUM_ID) REFERENCES ONDERWIJSTYPE_ENUM (ONDERWIJSTYPE_ENUM_ID);
-- ONDERWIJSTYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE SCHOOL ADD CONSTRAINT FK_SCHOOL_HEEFT FOREIGN KEY (HEEFT_UITSCHRIJVING_ID) REFERENCES UITSCHRIJVING (UITSCHRIJVING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1206)

ALTER TABLE SCHOOL ADD CONSTRAINT FK_SCHOOL_SCHOOL_HEEFT FOREIGN KEY (SCHOOL_HEEFT_LOCATIE_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- SCHOOL_HEEFT (0..1 to 1..*, Connector_ID: 1213)

