CREATE TABLE AANTAL (
    AANTAL_ID VARCHAR2(255) PRIMARY KEY,
        AANTAL NUMBER
);

CREATE TABLE BELIJNING (
    BELIJNING_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200)
);

CREATE TABLE BINNENLOCATIE (
    SPORTLOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        ADRES VARCHAR2(255),
        BOUWJAAR VARCHAR2(255),
        GEMEENTELIJK NUMBER(1),
        GESCHATTEKOSTENPERJAAR NUMBER(10,2),
        GYMZAAL NUMBER(1),
        KLOKURENONDERWIJS VARCHAR2(255),
        KLOKURENVERENIGINGEN VARCHAR2(255),
        LOCATIE VARCHAR2(255),
        ONDERHOUDSNIVEAU VARCHAR2(80),
        ONDERHOUDSSTATUS NUMBER,
        SPORTHAL NUMBER(1),
        VLOEROPPERVLAKTE NUMBER
);

CREATE TABLE KP_BNNNLCT (
    KP_BNNNLCT_ID VARCHAR2(255) PRIMARY KEY,
    BINNENLOCATIE_ID VARCHAR2(255),
    BELIJNING_ID VARCHAR2(255)
);

CREATE TABLE KP_SCHL (
    KP_SCHL_ID VARCHAR2(255) PRIMARY KEY,
    SCHOOL_ID VARCHAR2(255),
    SPORTLOCATIE_ID VARCHAR2(255)
);

CREATE TABLE KP_SPRTVRNGNG (
    KP_SPRTVRNGNG_ID VARCHAR2(255) PRIMARY KEY,
    SPORTVERENIGING_ID VARCHAR2(255),
    SPORT_ID VARCHAR2(255)
);

CREATE TABLE KP_VLD (
    KP_VLD_ID VARCHAR2(255) PRIMARY KEY,
    VELD_ID VARCHAR2(255),
    BELIJNING_ID VARCHAR2(255)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMUITSCHRIJVING DATE,
        DATUMVOORTZETTING DATE,
        FAXNUMMER VARCHAR2(20),
        INGESCHREVEN NUMBER(1),
        INOPRICHTING NUMBER(1),
        KVKNUMMER VARCHAR2(255),
        NNPID VARCHAR2(255),
        RECHTSVORM VARCHAR2(255),
        RSINNUMMER VARCHAR2(255),
        STATUTAIRENAAM VARCHAR2(255),
        STATUTAIREZETEL VARCHAR2(255),
        WEBSITEURL VARCHAR2(200)
);

CREATE TABLE SCHOOL (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200)
);

CREATE TABLE SPORT (
    SPORT_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200)
);

CREATE TABLE SPORTLOCATIE (
    SPORTLOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200)
);

CREATE TABLE SPORTMATERIAAL (
    SPORTMATERIAAL_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200)
);

CREATE TABLE SPORTPARK (
    SPORTLOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        HEEFT_VELD_ID VARCHAR2(255)
);

CREATE TABLE SPORTVERENIGING (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        AANTALNORMTEAMS VARCHAR2(255),
        ADRES VARCHAR2(255),
        BINNENSPORT NUMBER(1),
        BUITENSPORT NUMBER(1),
        EMAIL VARCHAR2(80),
        LEDENAANTAL NUMBER,
        NAAM VARCHAR2(200),
        TYPESPORT VARCHAR2(200)
);

CREATE TABLE VELD (
    VELD_ID VARCHAR2(255) PRIMARY KEY
);

ALTER TABLE SCHOOL ADD CONSTRAINT FK_SCHOOL_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_GEN_SPORTLOCATIE FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- Generalization to SPORTLOCATIE

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_GEN_SPORTLOCATIE FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- Generalization to SPORTLOCATIE

ALTER TABLE SPORTVERENIGING ADD CONSTRAINT FK_SPORTVERENIGING_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE KP_BNNNLCT ADD CONSTRAINT FK_KP_BNNNLCT_1 FOREIGN KEY (BINNENLOCATIE_ID) REFERENCES BINNENLOCATIE (SPORTLOCATIE_ID);
-- BINNENLOCATIE (many-to-many junction, Connector_ID: 1092)

ALTER TABLE KP_BNNNLCT ADD CONSTRAINT FK_KP_BNNNLCT_2 FOREIGN KEY (SPORTMATERIAAL_ID) REFERENCES SPORTMATERIAAL (SPORTMATERIAAL_ID);
-- SPORTMATERIAAL (many-to-many junction, Connector_ID: 1092)

ALTER TABLE KP_BNNNLCT ADD CONSTRAINT FK_KP_BNNNLCT_1 FOREIGN KEY (BINNENLOCATIE_ID) REFERENCES BINNENLOCATIE (SPORTLOCATIE_ID);
-- BINNENLOCATIE (many-to-many junction, Connector_ID: 1097)

ALTER TABLE KP_BNNNLCT ADD CONSTRAINT FK_KP_BNNNLCT_2 FOREIGN KEY (BELIJNING_ID) REFERENCES BELIJNING (BELIJNING_ID);
-- BELIJNING (many-to-many junction, Connector_ID: 1097)

ALTER TABLE KP_SCHL ADD CONSTRAINT FK_KP_SCHL_1 FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL (NIETNATUURLIJKPERSOON_ID);
-- SCHOOL (many-to-many junction, Connector_ID: 1205)

ALTER TABLE KP_SCHL ADD CONSTRAINT FK_KP_SCHL_2 FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1205)

ALTER TABLE KP_SPRTVRNGNG ADD CONSTRAINT FK_KP_SPRTVRNGNG_1 FOREIGN KEY (SPORTVERENIGING_ID) REFERENCES SPORTVERENIGING (NIETNATUURLIJKPERSOON_ID);
-- SPORTVERENIGING (many-to-many junction, Connector_ID: 1087)

ALTER TABLE KP_SPRTVRNGNG ADD CONSTRAINT FK_KP_SPRTVRNGNG_2 FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1087)

ALTER TABLE KP_SPRTVRNGNG ADD CONSTRAINT FK_KP_SPRTVRNGNG_1 FOREIGN KEY (SPORTVERENIGING_ID) REFERENCES SPORTVERENIGING (NIETNATUURLIJKPERSOON_ID);
-- SPORTVERENIGING (many-to-many junction, Connector_ID: 1088)

ALTER TABLE KP_SPRTVRNGNG ADD CONSTRAINT FK_KP_SPRTVRNGNG_2 FOREIGN KEY (SPORT_ID) REFERENCES SPORT (SPORT_ID);
-- SPORT (many-to-many junction, Connector_ID: 1088)

ALTER TABLE KP_VLD ADD CONSTRAINT FK_KP_VLD_1 FOREIGN KEY (VELD_ID) REFERENCES VELD (VELD_ID);
-- VELD (many-to-many junction, Connector_ID: 1096)

ALTER TABLE KP_VLD ADD CONSTRAINT FK_KP_VLD_2 FOREIGN KEY (BELIJNING_ID) REFERENCES BELIJNING (BELIJNING_ID);
-- BELIJNING (many-to-many junction, Connector_ID: 1096)

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_HEEFT FOREIGN KEY (HEEFT_VELD_ID) REFERENCES VELD (VELD_ID);
-- HEEFT (0..1 to 0..*, Connector_ID: 1085)

