CREATE TABLE `AANTAL` (
    `AANTAL_ID` INT PRIMARY KEY,
        `AANTAL` INT
) ENGINE=InnoDB;

CREATE TABLE `BELIJNING` (
    `BELIJNING_ID` INT PRIMARY KEY,
        `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `BINNENLOCATIE` (
    `SPORTLOCATIE_ID` INT PRIMARY KEY,
        `ADRES` VARCHAR(255),
        `BOUWJAAR` VARCHAR(255),
        `GEMEENTELIJK` BOOLEAN,
        `GESCHATTEKOSTENPERJAAR` DECIMAL(10,2),
        `GYMZAAL` BOOLEAN,
        `KLOKURENONDERWIJS` VARCHAR(255),
        `KLOKURENVERENIGINGEN` VARCHAR(255),
        `LOCATIE` VARCHAR(255),
        `ONDERHOUDSNIVEAU` VARCHAR(80),
        `ONDERHOUDSSTATUS` INT,
        `SPORTHAL` BOOLEAN,
        `VLOEROPPERVLAKTE` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BNNNLCT` (
    `KP_BNNNLCT_ID` INT PRIMARY KEY,
    `BINNENLOCATIE_ID` INT,
    `BELIJNING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_SCHL` (
    `KP_SCHL_ID` INT PRIMARY KEY,
    `SCHOOL_ID` INT,
    `SPORTLOCATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_SPRTVRNGNG` (
    `KP_SPRTVRNGNG_ID` INT PRIMARY KEY,
    `SPORTVERENIGING_ID` INT,
    `SPORT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VLD` (
    `KP_VLD_ID` INT PRIMARY KEY,
    `VELD_ID` INT,
    `BELIJNING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `NIETNATUURLIJKPERSOON` (
    `NIETNATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `DATUMAANVANG` DATE,
        `DATUMEINDE` DATE,
        `DATUMUITSCHRIJVING` DATE,
        `DATUMVOORTZETTING` DATE,
        `FAXNUMMER` VARCHAR(20),
        `INGESCHREVEN` BOOLEAN,
        `INOPRICHTING` BOOLEAN,
        `KVKNUMMER` VARCHAR(255),
        `NNPID` VARCHAR(255),
        `RECHTSVORM` VARCHAR(255),
        `RSINNUMMER` VARCHAR(255),
        `STATUTAIRENAAM` VARCHAR(255),
        `STATUTAIREZETEL` VARCHAR(255),
        `WEBSITEURL` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `SCHOOL` (
    `NIETNATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `SPORT` (
    `SPORT_ID` INT PRIMARY KEY,
        `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `SPORTLOCATIE` (
    `SPORTLOCATIE_ID` INT PRIMARY KEY,
        `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `SPORTMATERIAAL` (
    `SPORTMATERIAAL_ID` INT PRIMARY KEY,
        `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `SPORTPARK` (
    `SPORTLOCATIE_ID` INT PRIMARY KEY,
        `HEEFT_VELD_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `SPORTVERENIGING` (
    `NIETNATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `AANTALNORMTEAMS` VARCHAR(255),
        `ADRES` VARCHAR(255),
        `BINNENSPORT` BOOLEAN,
        `BUITENSPORT` BOOLEAN,
        `EMAIL` VARCHAR(80),
        `LEDENAANTAL` INT,
        `NAAM` VARCHAR(200),
        `TYPESPORT` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `VELD` (
    `VELD_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

ALTER TABLE `SCHOOL` ADD CONSTRAINT FK_SCHOOL_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY (`NIETNATUURLIJKPERSOON_ID`) REFERENCES `NIETNATUURLIJKPERSOON` (`NIETNATUURLIJKPERSOON_ID`);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE `BINNENLOCATIE` ADD CONSTRAINT FK_BINNENLOCATIE_GEN_SPORTLOCATIE FOREIGN KEY (`SPORTLOCATIE_ID`) REFERENCES `SPORTLOCATIE` (`SPORTLOCATIE_ID`);
-- Generalization to SPORTLOCATIE

ALTER TABLE `SPORTPARK` ADD CONSTRAINT FK_SPORTPARK_GEN_SPORTLOCATIE FOREIGN KEY (`SPORTLOCATIE_ID`) REFERENCES `SPORTLOCATIE` (`SPORTLOCATIE_ID`);
-- Generalization to SPORTLOCATIE

ALTER TABLE `SPORTVERENIGING` ADD CONSTRAINT FK_SPORTVERENIGING_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY (`NIETNATUURLIJKPERSOON_ID`) REFERENCES `NIETNATUURLIJKPERSOON` (`NIETNATUURLIJKPERSOON_ID`);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE `KP_BNNNLCT` ADD CONSTRAINT FK_KP_BNNNLCT_1 FOREIGN KEY (`BINNENLOCATIE_ID`) REFERENCES `BINNENLOCATIE` (`SPORTLOCATIE_ID`);
-- BINNENLOCATIE (many-to-many junction, Connector_ID: 1092)

ALTER TABLE `KP_BNNNLCT` ADD CONSTRAINT FK_KP_BNNNLCT_2 FOREIGN KEY (`SPORTMATERIAAL_ID`) REFERENCES `SPORTMATERIAAL` (`SPORTMATERIAAL_ID`);
-- SPORTMATERIAAL (many-to-many junction, Connector_ID: 1092)

ALTER TABLE `KP_BNNNLCT` ADD CONSTRAINT FK_KP_BNNNLCT_1 FOREIGN KEY (`BINNENLOCATIE_ID`) REFERENCES `BINNENLOCATIE` (`SPORTLOCATIE_ID`);
-- BINNENLOCATIE (many-to-many junction, Connector_ID: 1097)

ALTER TABLE `KP_BNNNLCT` ADD CONSTRAINT FK_KP_BNNNLCT_2 FOREIGN KEY (`BELIJNING_ID`) REFERENCES `BELIJNING` (`BELIJNING_ID`);
-- BELIJNING (many-to-many junction, Connector_ID: 1097)

ALTER TABLE `KP_SCHL` ADD CONSTRAINT FK_KP_SCHL_1 FOREIGN KEY (`SCHOOL_ID`) REFERENCES `SCHOOL` (`NIETNATUURLIJKPERSOON_ID`);
-- SCHOOL (many-to-many junction, Connector_ID: 1205)

ALTER TABLE `KP_SCHL` ADD CONSTRAINT FK_KP_SCHL_2 FOREIGN KEY (`SPORTLOCATIE_ID`) REFERENCES `SPORTLOCATIE` (`SPORTLOCATIE_ID`);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1205)

ALTER TABLE `KP_SPRTVRNGNG` ADD CONSTRAINT FK_KP_SPRTVRNGNG_1 FOREIGN KEY (`SPORTVERENIGING_ID`) REFERENCES `SPORTVERENIGING` (`NIETNATUURLIJKPERSOON_ID`);
-- SPORTVERENIGING (many-to-many junction, Connector_ID: 1087)

ALTER TABLE `KP_SPRTVRNGNG` ADD CONSTRAINT FK_KP_SPRTVRNGNG_2 FOREIGN KEY (`SPORTLOCATIE_ID`) REFERENCES `SPORTLOCATIE` (`SPORTLOCATIE_ID`);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1087)

ALTER TABLE `KP_SPRTVRNGNG` ADD CONSTRAINT FK_KP_SPRTVRNGNG_1 FOREIGN KEY (`SPORTVERENIGING_ID`) REFERENCES `SPORTVERENIGING` (`NIETNATUURLIJKPERSOON_ID`);
-- SPORTVERENIGING (many-to-many junction, Connector_ID: 1088)

ALTER TABLE `KP_SPRTVRNGNG` ADD CONSTRAINT FK_KP_SPRTVRNGNG_2 FOREIGN KEY (`SPORT_ID`) REFERENCES `SPORT` (`SPORT_ID`);
-- SPORT (many-to-many junction, Connector_ID: 1088)

ALTER TABLE `KP_VLD` ADD CONSTRAINT FK_KP_VLD_1 FOREIGN KEY (`VELD_ID`) REFERENCES `VELD` (`VELD_ID`);
-- VELD (many-to-many junction, Connector_ID: 1096)

ALTER TABLE `KP_VLD` ADD CONSTRAINT FK_KP_VLD_2 FOREIGN KEY (`BELIJNING_ID`) REFERENCES `BELIJNING` (`BELIJNING_ID`);
-- BELIJNING (many-to-many junction, Connector_ID: 1096)

ALTER TABLE `SPORTPARK` ADD CONSTRAINT FK_SPORTPARK_HEEFT FOREIGN KEY (`HEEFT_VELD_ID`) REFERENCES `VELD` (`VELD_ID`);
-- HEEFT (0..1 to 0..*, Connector_ID: 1085)

