CREATE TABLE CLIENT (
    CLIENT_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(80),
    GEZAGSDRAGERGEKEND NUMBER(1),
    JURIDISCHESTATUS VARCHAR2(80),
    WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE DOELGROEP (
    DOELGROEP_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(255),
    OMSCHRIJVING CLOB
);

CREATE TABLE CLIENTBEGELEIDER (
    CLIENTBEGELEIDER_ID NUMBER PRIMARY KEY,
    BEGELEIDERSCODE VARCHAR2(20)
);

CREATE TABLE WERKZOEKENDE (
    CLIENT_ID NUMBER PRIMARY KEY,
    DATUMAANVANGWERKZOEKENDE DATE,
    DATUMEINDEWERKZOEKENDE DATE
);

CREATE TABLE KP_CLNT_DLGRP (
    KP_CLNT_DLGRP_ID NUMBER PRIMARY KEY,
    CLIENT_ID NUMBER,
    DOELGROEP_ID NUMBER
);

CREATE TABLE KP_CLNTBGLDR_CLNT (
    KP_CLNTBGLDR_CLNT_ID NUMBER PRIMARY KEY,
    CLIENTBEGELEIDER_ID NUMBER,
    CLIENT_ID NUMBER
);

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_GEN_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- Generalization to CLIENT

ALTER TABLE KP_CLNTBGLDR_CLNT ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_1 FOREIGN KEY (CLIENTBEGELEIDER_ID) REFERENCES CLIENTBEGELEIDER (CLIENTBEGELEIDER_ID);
-- CLIENTBEGELEIDER (many-to-many junction, Connector_ID: 941)

ALTER TABLE KP_CLNTBGLDR_CLNT ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_2 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- CLIENT (many-to-many junction, Connector_ID: 941)

ALTER TABLE KP_CLNT_DLGRP ADD CONSTRAINT FK_KP_CLNT_DLGRP_1 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- CLIENT (many-to-many junction, Connector_ID: 1586)

ALTER TABLE KP_CLNT_DLGRP ADD CONSTRAINT FK_KP_CLNT_DLGRP_2 FOREIGN KEY (DOELGROEP_ID) REFERENCES DOELGROEP (DOELGROEP_ID);
-- DOELGROEP (many-to-many junction, Connector_ID: 1586)

