CREATE TABLE ERFGOED_OBJECT (
    ERFGOED_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATERINGTOT NUMBER,
        DATERINGVANAF NUMBER,
        OMSCHRIJVING CLOB,
        TITEL VARCHAR2(80)
);

CREATE TABLE ARCHIEFSTUK (
    ERFGOED_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        BESCHRIJVING CLOB,
        INVENTARISNUMMER VARCHAR2(20),
        OMVANG VARCHAR2(255),
        OPENBAARHEIDSBEPERKING NUMBER(1),
        TREFWOORDEN VARCHAR2(200),
        UITERLIJKEVORM VARCHAR2(255)
);

CREATE TABLE FOTO (
    FOTO_ID VARCHAR2(255) PRIMARY KEY,
        BESTANDSGROOTTE NUMBER,
        BESTANDSNAAM VARCHAR2(200),
        BESTANDSTYPE VARCHAR2(80),
        DATUMTIJD TIMESTAMP,
        LOCATIE VARCHAR2(255),
        PIXELSX NUMBER,
        PIXELSY NUMBER
);

CREATE TABLE HISTORISCHE_ROL (
    HISTORISCHE_ROL_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE KP_FT_ERFGD_OBJCT (
    KP_FT_ERFGD_OBJCT_ID VARCHAR2(255) PRIMARY KEY,
    FOTO_ID VARCHAR2(255),
    ERFGOED_OBJECT_ID VARCHAR2(255)
);

CREATE TABLE MUSEUMOBJECT (
    ERFGOED_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        AFMETING VARCHAR2(255),
        BEZITTOT DATE,
        BEZITVANAF DATE,
        MEDIUM VARCHAR2(255),
        VERKRIJGING VARCHAR2(255)
);

CREATE TABLE NATUURLIJKPERSOON (
    NATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON VARCHAR2(50),
        AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
        AANHEFAANSCHRIJVING VARCHAR2(50),
        ACADEMISCHETITEL VARCHAR2(80),
        ACHTERNAAM VARCHAR2(100),
        ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        ATTRIBUTE VARCHAR2(255),
        BURGERSERVICENUMMER VARCHAR2(255),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        GEBOORTELAND VARCHAR2(255),
        GEBOORTEPLAATS VARCHAR2(200),
        GESLACHTSAANDUIDING VARCHAR2(255),
        GESLACHTSNAAM VARCHAR2(200),
        GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
        HANDLICHTING VARCHAR2(50),
        INDICATIEAFSCHERMINGPERSOONSGEGEVENS NUMBER(1),
        INDICATIEOVERLEDEN NUMBER(1),
        LANDOVERLIJDEN VARCHAR2(255),
        NATIONALITEIT VARCHAR2(100),
        OVERLIJDENSPLAATS VARCHAR2(200),
        VOORLETTERSAANSCHRIJVING VARCHAR2(20),
        VOORNAMEN VARCHAR2(200),
        VOORNAMENAANSCHRIJVING VARCHAR2(200),
        VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE AUTEUR (
    NATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE
);

CREATE TABLE HISTORISCH_PERSOON_ (
    NATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        BEROEP VARCHAR2(200),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        NAAM VARCHAR2(200),
        OMSCHRIJVING CLOB,
        PUBLIEKTOEGANKELIJK NUMBER(1),
        WOONDEOP VARCHAR2(50)
);

CREATE TABLE KP_HSTRSCH_PRSN__ERFGD_OBJCT (
    KP_HSTRSCH_PRSN__ERFGD_OBJCT_ID VARCHAR2(255) PRIMARY KEY,
    HISTORISCH_PERSOON__ID VARCHAR2(255),
    ERFGOED_OBJECT_ID VARCHAR2(255)
);

CREATE TABLE KP_MSMBJCT_HSTRSCH_PRSN_ (
    KP_MSMBJCT_HSTRSCH_PRSN__ID VARCHAR2(255) PRIMARY KEY,
    MUSEUMOBJECT_ID VARCHAR2(255),
    HISTORISCH_PERSOON__ID VARCHAR2(255)
);

CREATE TABLE OBJECTCLASSIFICATIE (
    OBJECTCLASSIFICATIE_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE KP_ERFGD_OBJCT_OBJCTCLSSFCT (
    KP_ERFGD_OBJCT_OBJCTCLSSFCT_ID VARCHAR2(255) PRIMARY KEY,
    ERFGOED_OBJECT_ID VARCHAR2(255),
    OBJECTCLASSIFICATIE_ID VARCHAR2(255)
);

CREATE TABLE VIDEO_OPNAME (
    VIDEO_OPNAME_ID VARCHAR2(255) PRIMARY KEY,
        BESTANDSGROOTTE NUMBER,
        DATUMTIJD TIMESTAMP,
        LENGTE NUMBER,
        VIDEOFORMAAT VARCHAR2(80)
);

CREATE TABLE KP_VD_OPNM_ERFGD_OBJCT (
    KP_VD_OPNM_ERFGD_OBJCT_ID VARCHAR2(255) PRIMARY KEY,
    VIDEO_OPNAME_ID VARCHAR2(255),
    ERFGOED_OBJECT_ID VARCHAR2(255)
);

ALTER TABLE ARCHIEFSTUK ADD CONSTRAINT FK_ARCHIEFSTUK_GEN_ERFGOED_OBJECT FOREIGN KEY (ERFGOED_OBJECT_ID) REFERENCES ERFGOED_OBJECT (ERFGOED_OBJECT_ID);
-- Generalization to ERFGOED_OBJECT

ALTER TABLE AUTEUR ADD CONSTRAINT FK_AUTEUR_GEN_HISTORISCH_PERSOON_ FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES HISTORISCH_PERSOON_ (NATUURLIJKPERSOON_ID);
-- Generalization to HISTORISCH_PERSOON_

ALTER TABLE HISTORISCH_PERSOON_ ADD CONSTRAINT FK_HISTORISCH_PERSOON__GEN_NATUURLIJKPERSOON FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (NATUURLIJKPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE MUSEUMOBJECT ADD CONSTRAINT FK_MUSEUMOBJECT_GEN_ERFGOED_OBJECT FOREIGN KEY (ERFGOED_OBJECT_ID) REFERENCES ERFGOED_OBJECT (ERFGOED_OBJECT_ID);
-- Generalization to ERFGOED_OBJECT

ALTER TABLE KP_ERFGD_OBJCT_OBJCTCLSSFCT ADD CONSTRAINT FK_KP_ERFGD_OBJCT_OBJCTCLSSFCT_1 FOREIGN KEY (ERFGOED_OBJECT_ID) REFERENCES ERFGOED_OBJECT (ERFGOED_OBJECT_ID);
-- ERFGOED_OBJECT (many-to-many junction, Connector_ID: 1156)

ALTER TABLE KP_ERFGD_OBJCT_OBJCTCLSSFCT ADD CONSTRAINT FK_KP_ERFGD_OBJCT_OBJCTCLSSFCT_2 FOREIGN KEY (OBJECTCLASSIFICATIE_ID) REFERENCES OBJECTCLASSIFICATIE (OBJECTCLASSIFICATIE_ID);
-- OBJECTCLASSIFICATIE (many-to-many junction, Connector_ID: 1156)

ALTER TABLE KP_FT_ERFGD_OBJCT ADD CONSTRAINT FK_KP_FT_ERFGD_OBJCT_1 FOREIGN KEY (FOTO_ID) REFERENCES FOTO (FOTO_ID);
-- FOTO (many-to-many junction, Connector_ID: 1154)

ALTER TABLE KP_FT_ERFGD_OBJCT ADD CONSTRAINT FK_KP_FT_ERFGD_OBJCT_2 FOREIGN KEY (ERFGOED_OBJECT_ID) REFERENCES ERFGOED_OBJECT (ERFGOED_OBJECT_ID);
-- ERFGOED_OBJECT (many-to-many junction, Connector_ID: 1154)

ALTER TABLE KP_HSTRSCH_PRSN__ERFGD_OBJCT ADD CONSTRAINT FK_KP_HSTRSCH_PRSN__ERFGD_OBJCT_1 FOREIGN KEY (HISTORISCH_PERSOON__ID) REFERENCES HISTORISCH_PERSOON_ (NATUURLIJKPERSOON_ID);
-- HISTORISCH_PERSOON_ (many-to-many junction, Connector_ID: 1151)

ALTER TABLE KP_HSTRSCH_PRSN__ERFGD_OBJCT ADD CONSTRAINT FK_KP_HSTRSCH_PRSN__ERFGD_OBJCT_2 FOREIGN KEY (ERFGOED_OBJECT_ID) REFERENCES ERFGOED_OBJECT (ERFGOED_OBJECT_ID);
-- ERFGOED_OBJECT (many-to-many junction, Connector_ID: 1151)

ALTER TABLE KP_MSMBJCT_HSTRSCH_PRSN_ ADD CONSTRAINT FK_KP_MSMBJCT_HSTRSCH_PRSN__1 FOREIGN KEY (MUSEUMOBJECT_ID) REFERENCES MUSEUMOBJECT (ERFGOED_OBJECT_ID);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1103)

ALTER TABLE KP_MSMBJCT_HSTRSCH_PRSN_ ADD CONSTRAINT FK_KP_MSMBJCT_HSTRSCH_PRSN__2 FOREIGN KEY (HISTORISCH_PERSOON__ID) REFERENCES HISTORISCH_PERSOON_ (NATUURLIJKPERSOON_ID);
-- HISTORISCH_PERSOON_ (many-to-many junction, Connector_ID: 1103)

ALTER TABLE KP_VD_OPNM_ERFGD_OBJCT ADD CONSTRAINT FK_KP_VD_OPNM_ERFGD_OBJCT_1 FOREIGN KEY (VIDEO_OPNAME_ID) REFERENCES VIDEO_OPNAME (VIDEO_OPNAME_ID);
-- VIDEO_OPNAME (many-to-many junction, Connector_ID: 1155)

ALTER TABLE KP_VD_OPNM_ERFGD_OBJCT ADD CONSTRAINT FK_KP_VD_OPNM_ERFGD_OBJCT_2 FOREIGN KEY (ERFGOED_OBJECT_ID) REFERENCES ERFGOED_OBJECT (ERFGOED_OBJECT_ID);
-- ERFGOED_OBJECT (many-to-many junction, Connector_ID: 1155)

