CREATE TABLE [BEPERKINGSCATEGORIE] (
    [BEPERKINGSCATEGORIE_ID] INT PRIMARY KEY,
        [CODE] VARCHAR(255),
        [WET] VARCHAR(255)
);

CREATE TABLE [BEPERKINGSCORESOORT] (
    [BEPERKINGSCORESOORT_ID] INT PRIMARY KEY,
        [VRAAG] VARCHAR(200),
        [WET] VARCHAR(255)
);

CREATE TABLE [BEPERKINGSCORE] (
    [BEPERKINGSCORE_ID] INT PRIMARY KEY,
        [COMMENTAAR] VARCHAR(200),
        [IS_EEN_BEPERKINGSCORESOORT_ID] INT,
        [SCORE] INT,
        [WET] VARCHAR(255)
);

CREATE TABLE [BESCHIKKING] (
    [BESCHIKKING_ID] INT PRIMARY KEY,
        [CODE] VARCHAR(20),
        [COMMENTAAR] VARCHAR(200),
        [DATUMAFGIFTE] DATE,
        [GRONDSLAGEN] INT,
        [WET] VARCHAR(255)
);

CREATE TABLE [BEPERKING] (
    [BEPERKING_ID] INT PRIMARY KEY,
        [BEPERKINGSCORE_ID] INT,
        [CATEGORIE] INT,
        [COMMENTAAR] INT,
        [DUUR] INT,
        [IS_EEN_BEPERKINGSCATEGORIE_ID] INT,
        [IS_GEBASEERD_OP_BESCHIKKING_ID] INT,
        [WET] VARCHAR(255)
);

ALTER TABLE [BEPERKING] ADD CONSTRAINT FK_BEPERKING_BEPERKINGSCORE FOREIGN KEY ([BEPERKINGSCORE_ID]) REFERENCES [BEPERKINGSCORE] ([BEPERKINGSCORE_ID]);
-- unnamed (0..1 to 0..*, Connector_ID: 1071)

ALTER TABLE [BEPERKING] ADD CONSTRAINT FK_BEPERKING_IS_EEN FOREIGN KEY ([IS_EEN_BEPERKINGSCATEGORIE_ID]) REFERENCES [BEPERKINGSCATEGORIE] ([BEPERKINGSCATEGORIE_ID]);
-- IS_EEN (0..* to 0..1, Connector_ID: 1073)

ALTER TABLE [BEPERKING] ADD CONSTRAINT FK_BEPERKING_IS_GEBASEERD_OP FOREIGN KEY ([IS_GEBASEERD_OP_BESCHIKKING_ID]) REFERENCES [BESCHIKKING] ([BESCHIKKING_ID]);
-- IS_GEBASEERD_OP (0..* to 0..1, Connector_ID: 1072)

ALTER TABLE [BEPERKINGSCORE] ADD CONSTRAINT FK_BEPERKINGSCORE_IS_EEN FOREIGN KEY ([IS_EEN_BEPERKINGSCORESOORT_ID]) REFERENCES [BEPERKINGSCORESOORT] ([BEPERKINGSCORESOORT_ID]);
-- IS_EEN (0..* to 0..1, Connector_ID: 1070)

