CREATE TABLE INGESCHREVENPERSOON (
    INGESCHREVENPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESHERKOMST VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        BESCHRIJVINGLOCATIE VARCHAR2(200),
        BUITENLANDSREISDOCUMENT VARCHAR2(80),
        BURGERLIJKESTAAT VARCHAR2(255),
        DATUMBEGINGELDIGHEIDVERBLIJFPLAATS DATE,
        DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS DATE,
        DATUMINSCHRIJVINGGEMEENTE DATE,
        DATUMOPSCHORTINGBIJHOUDING DATE,
        DATUMVERTREKUITNEDERLAND DATE,
        DATUMVESTIGINGNEDERLAND DATE,
        GEMEENTEVANINSCHRIJVING VARCHAR2(80),
        GEZINSRELATIE VARCHAR2(255),
        INDICATIEGEHEIM NUMBER(1),
        INGEZETENE NUMBER(1),
        LANDWAARNAARVERTROKKEN VARCHAR2(255),
        LANDWAARVANDAANINGESCHREVEN VARCHAR2(255),
        OUDER1 VARCHAR2(255),
        OUDER2 VARCHAR2(255),
        OUDER_1_INGESCHREVENPERSOON_ID VARCHAR2(255),
        OUDER_2_INGESCHREVENPERSOON_ID VARCHAR2(255),
        PARTNERID VARCHAR2(255),
        REDENEINDEBEWONING DATE,
        REDENOPSCHORTINGBIJHOUDING VARCHAR2(200),
        SIGNALERINGREISDOCUMENT NUMBER(1),
        VERBLIJFSTITEL VARCHAR2(255)
);

CREATE TABLE LEERLING (
    INGESCHREVENPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        KWETSBAREJONGERE NUMBER(1)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID VARCHAR2(255) PRIMARY KEY,
        ACHTERNAAM VARCHAR2(200),
        DATUMINDIENST DATE,
        DATUMUITDIENST DATE,
        EMAILADRES VARCHAR2(255),
        EXTERN VARCHAR2(255),
        FUNCTIE VARCHAR2(50),
        GESLACHTSAANDUIDING VARCHAR2(255),
        MEDEWERKERIDENTIFICATIE VARCHAR2(255),
        MEDEWERKERTOELICHTING VARCHAR2(255),
        ROEPNAAM VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20),
        VOORLETTERS VARCHAR2(20),
        VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE LEERPLICHTAMBTENAAR (
    MEDEWERKER_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMUITSCHRIJVING DATE,
        DATUMVOORTZETTING DATE,
        FAXNUMMER VARCHAR2(20),
        INGESCHREVEN NUMBER(1),
        INOPRICHTING NUMBER(1),
        KVKNUMMER VARCHAR2(255),
        NNPID VARCHAR2(255),
        RECHTSVORM VARCHAR2(255),
        RSINNUMMER VARCHAR2(255),
        STATUTAIRENAAM VARCHAR2(255),
        STATUTAIREZETEL VARCHAR2(255),
        WEBSITEURL VARCHAR2(200)
);

CREATE TABLE OUDER_OF_VERZORGER (
    INGESCHREVENPERSOON_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE SCHOOL (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200)
);

ALTER TABLE LEERPLICHTAMBTENAAR ADD CONSTRAINT FK_LEERPLICHTAMBTENAAR_GEN_MEDEWERKER FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- Generalization to MEDEWERKER

ALTER TABLE LEERLING ADD CONSTRAINT FK_LEERLING_GEN_INGESCHREVENPERSOON FOREIGN KEY (INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE OUDER_OF_VERZORGER ADD CONSTRAINT FK_OUDER_OF_VERZORGER_GEN_INGESCHREVENPERSOON FOREIGN KEY (INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE SCHOOL ADD CONSTRAINT FK_SCHOOL_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (OUDER_1_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- OUDER_1 (None to None, Connector_ID: 170)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (OUDER_2_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- OUDER_2 (None to None, Connector_ID: 171)

