CREATE TABLE [KOSTENCOMPONENT] (
    [KOSTENCOMPONENT_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2)
);

CREATE TABLE [DRAAGKRACHTREGIME] (
    [DRAAGKRACHTREGIME_ID] INT PRIMARY KEY,
    [INITIELE_DRAAGKRACHT] VARCHAR(255),
    [NAAM] VARCHAR(255),
    [PEILDATUM] DATE,
    [RESTERENDE_DRAAGKRACHT] VARCHAR(255)
);

CREATE TABLE [VRIJLATING_INKOMSTEN] (
    [VRIJLATING_INKOMSTEN_ID] INT PRIMARY KEY,
    [DOELGROEP] VARCHAR(255),
    [MEDISCH] BIT,
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE,
    [SOORT_VRIJLATING] VARCHAR(255),
    [VRIJGELATEN_BEDRAG] DECIMAL(10,2)
);

CREATE TABLE [INKOMSTENCOMPONENT] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [BIJGEVOEGD_BEWIJS] BIT,
    [BOEKINGSDATUM] DATE,
    [BRUTO_NETTO] VARCHAR(255),
    [INKOMSTEN] VARCHAR(255),
    [INKOMSTENCOMPONENTTYPE] VARCHAR(255),
    [LINK_NAAR_BEWIJS] VARCHAR(255),
    [PEILMOMENT] DATE,
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE
);

CREATE TABLE [ONDERHOUDSPLICHT] (
    [ONDERHOUDSPLICHT_ID] INT PRIMARY KEY,
    [BIJDRAGE] VARCHAR(255),
    [BOEKINGSDATUM] DATE,
    [ONDERHOUDSPLICHTTYPE] VARCHAR(255),
    [PEILMOMENT] DATE,
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE
);

CREATE TABLE [REISKOSTEN_NAAR_HET_WERK_] (
    [KOSTENCOMPONENT_ID] INT PRIMARY KEY,
    [SOORT] VARCHAR(255)
);

CREATE TABLE [EIGEN_BIJDRAGE] (
    [KOSTENCOMPONENT_ID] INT PRIMARY KEY,
    [SOORT] VARCHAR(255)
);

CREATE TABLE [TE_BETALEN_ALIMENTATIE] (
    [KOSTENCOMPONENT_ID] INT PRIMARY KEY,
    [SOORT] VARCHAR(255)
);

CREATE TABLE [BESLAG_OP_INKOMEN] (
    [KOSTENCOMPONENT_ID] INT PRIMARY KEY,
    [SOORT] VARCHAR(255)
);

CREATE TABLE [DRAAGKRACHT] (
    [DRAAGKRACHT_ID] INT PRIMARY KEY,
    [DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME_DRAAGKRACHTREGIME_ID] INT,
    [EINDDATUM] DATE,
    [STARTDATUM] DATE
);

CREATE TABLE [INKOMSTENVERHOUDING] (
    [INKOMSTENVERHOUDING_ID] INT PRIMARY KEY,
    [CATEGORIE_INKOMSTEN] VARCHAR(255),
    [INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT_PRIMAIR_INKOMSTENCOMPONENT_ID] INT,
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE
);

CREATE TABLE [EIGEN_BEDRIJF] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [AANTAL_UREN_PER_WEEK_BESTEED_AAN_WERK] VARCHAR(255),
    [INGESCHREVEN_BIJ_KVK] BIT,
    [RECHT_OP_ZELFSTANDIGENAFTREK] BIT,
    [SOORT_BEDRIJF] VARCHAR(255),
    [TOESTEMMING_GEMEENTE_PARTTIME_ONDERNEMEN] BIT
);

CREATE TABLE [MAALTIJDVERGOEDING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [STUDIEFINANCIERING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [DAADWERKELIJK_GENOTEN] BIT,
    [INKOMSTENSOORT_STUDIEFINANCIERING] VARCHAR(255)
);

CREATE TABLE [LOONBESLAG] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [HOBBY] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [AANTAL_UREN_PER_WEEK_BESTEED_AAN_HOBBY] VARCHAR(255),
    [BESCHRIJVING_HOBBY] VARCHAR(255)
);

CREATE TABLE [VERGOEDING_IN_NATURA] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [ANDER_INKOMEN] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [BESCHRIJVING_ANDER_INKOMEN] VARCHAR(255),
    [CATEGORIE] VARCHAR(255)
);

CREATE TABLE [VERLAGING_DOOR_MAATREGEL] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [SECUNDAIR_INKOMSTENCOMPONENT] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [ALIMENTATIE] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [BEDRAG_AAN_ANDERE_REKENINGEN] DECIMAL(10,2),
    [BEDRAG_IN_CONVENANT] DECIMAL(10,2),
    [BIJDRAGEEXPARTNERANDEREREKENINGEN] BIT,
    [INKOMSTENSOORT_ALIMENTATIE] VARCHAR(255),
    [JUISTE_BEDRAG_BETAALD_DOOR_EX_PARTNER] DECIMAL(10,2),
    [LBIO_INGESCHAKELD] BIT
);

CREATE TABLE [HEFFINGSKORTING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [ALGEMENE_HEFFINGSKORTING] BIT,
    [INKOMENSAFHANKELIJKE_COMBINATIEKORTING] BIT
);

CREATE TABLE [DERTIENDE_MAAND_EINDEJAARSUITKERING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [VAKANTIEGELD] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [ONKOSTENVERGOEDING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [INKOMSTENVERMINDERING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [PRIMAIR_INKOMSTENCOMPONENT] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [VERGOEDING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [VERLAGING_DOOR_BOETE] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [REISKOSTENVERGOEDING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY
);

CREATE TABLE [ONDERHOUDSVERHOUDING] (
    [ONDERHOUDSVERHOUDING_ID] INT PRIMARY KEY,
    [ONDERHOUDSVERHOUDINGTYPE] VARCHAR(255),
    [ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT_ONDERHOUDSPLICHT_ID] INT,
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE
);

CREATE TABLE [PENSIOEN] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [BESLAG_OP_PENSIOEN] BIT,
    [INKOMSTENSOORT_PENSIOEN] VARCHAR(255),
    [LOONHEFFINGSKORTING] BIT,
    [PENSIOEN_HEEFT_LOONBESLAG_LOONBESLAG_ID] INT,
    [PENSIOEN_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID] INT,
    [PERIODICITEIT_UITBETALING_PENSIOEN] VARCHAR(255),
    [UITBETALING_VAKANTIEGELD_PENSIOEN] VARCHAR(255)
);

CREATE TABLE [UITKERING] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [BESLAG_OP_UITKERING] BIT,
    [INKOMSTENSOORT_UITKERING] VARCHAR(255),
    [LOONHEFFINGSKORTING] BIT,
    [PERIODICITEIT_UITBETALING_UITKERING] VARCHAR(255),
    [TOESLAG_OP_UITKERING] BIT,
    [UITKERING_HEEFT_LOONBESLAG_LOONBESLAG_ID] INT,
    [UITKERING_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID] INT,
    [UITKERING_HEEFT_VERLAGING_DOOR_BOETE_VERLAGING_DOOR_BOETE_ID] INT,
    [UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL_VERLAGING_DOOR_MAATREGEL_ID] INT,
    [UITKERING_VERLAAGD_DOOR_BOETE] BIT,
    [UITKERING_VERLAAGD_DOOR_MAATREGEL] BIT,
    [VAKANTIEGELD_JAARLIJKS_ONTVANGEN] BIT
);

CREATE TABLE [BETAALD_WERK] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [ARBEIDSCONTRACT] BIT,
    [BEGINDATUM_CONTRACT] DATE,
    [BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING_DERTIENDE_MAAND_EINDEJAARSUITKERING_ID] INT,
    [BETAALD_WERK_HEEFT_HEFFINGSKORTING_HEFFINGSKORTING_ID] INT,
    [BETAALD_WERK_HEEFT_LOONBESLAG_LOONBESLAG_ID] INT,
    [BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING_MAALTIJDVERGOEDING_ID] INT,
    [BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING_ONKOSTENVERGOEDING_ID] INT,
    [BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING_REISKOSTENVERGOEDING_ID] INT,
    [BETAALD_WERK_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID] INT,
    [EINDDATUM_CONTRACT] DATE,
    [INKOMSTENSOORT_BETAALD_WERK] VARCHAR(255),
    [INKOMSTEN_UIT_IKB_REGELING] BIT,
    [LOONDIENST] BIT,
    [LOONHEFFINGSNUMMER] VARCHAR(255),
    [PERIODICITEIT_UITBETALING_LOON] VARCHAR(255),
    [SOORT_CONTRACT] VARCHAR(255),
    [URENVERMINDERING] VARCHAR(255)
);

CREATE TABLE [STAGE] (
    [INKOMSTENCOMPONENT_ID] INT PRIMARY KEY,
    [MAALTIJDVERGOEDING] DATETIME2,
    [ONKOSTENVERGOEDING] DECIMAL(10,2),
    [PERIODICITEIT_UITBETALING_LOON] VARCHAR(255),
    [REISKOSTENVERGOEDING] DECIMAL(10,2),
    [STAGE_HEEFT_MAALTIJDVERGOEDING_MAALTIJDVERGOEDING_ID] INT,
    [STAGE_HEEFT_ONKOSTENVERGOEDING_ONKOSTENVERGOEDING_ID] INT,
    [STAGE_HEEFT_REISKOSTENVERGOEDING_REISKOSTENVERGOEDING_ID] INT,
    [STAGE_HEEFT_VERGOEDING_IN_NATURA_VERGOEDING_IN_NATURA_ID] INT,
    [VERGOEDING_IN_NATURA] BIT
);

ALTER TABLE [ALIMENTATIE] ADD CONSTRAINT FK_ALIMENTATIE_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [ANDER_INKOMEN] ADD CONSTRAINT FK_ANDER_INKOMEN_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [BESLAG_OP_INKOMEN] ADD CONSTRAINT FK_BESLAG_OP_INKOMEN_GEN_KOSTENCOMPONENT FOREIGN KEY ([KOSTENCOMPONENT_ID]) REFERENCES [KOSTENCOMPONENT] ([KOSTENCOMPONENT_ID]);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE [BETAALD_WERK] ADD CONSTRAINT FK_BETAALD_WERK_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [DERTIENDE_MAAND_EINDEJAARSUITKERING] ADD CONSTRAINT FK_DERTIENDE_MAAND_EINDEJAARSUITKERING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [SECUNDAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE [EIGEN_BEDRIJF] ADD CONSTRAINT FK_EIGEN_BEDRIJF_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [EIGEN_BIJDRAGE] ADD CONSTRAINT FK_EIGEN_BIJDRAGE_GEN_KOSTENCOMPONENT FOREIGN KEY ([KOSTENCOMPONENT_ID]) REFERENCES [KOSTENCOMPONENT] ([KOSTENCOMPONENT_ID]);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE [HEFFINGSKORTING] ADD CONSTRAINT FK_HEFFINGSKORTING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [SECUNDAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE [HOBBY] ADD CONSTRAINT FK_HOBBY_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [INKOMSTENVERMINDERING] ADD CONSTRAINT FK_INKOMSTENVERMINDERING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [SECUNDAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE [LOONBESLAG] ADD CONSTRAINT FK_LOONBESLAG_GEN_INKOMSTENVERMINDERING FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [INKOMSTENVERMINDERING] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE [MAALTIJDVERGOEDING] ADD CONSTRAINT FK_MAALTIJDVERGOEDING_GEN_VERGOEDING FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [VERGOEDING] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to VERGOEDING

ALTER TABLE [ONKOSTENVERGOEDING] ADD CONSTRAINT FK_ONKOSTENVERGOEDING_GEN_VERGOEDING FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [VERGOEDING] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to VERGOEDING

ALTER TABLE [PENSIOEN] ADD CONSTRAINT FK_PENSIOEN_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [PRIMAIR_INKOMSTENCOMPONENT] ADD CONSTRAINT FK_PRIMAIR_INKOMSTENCOMPONENT_GEN_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to INKOMSTENCOMPONENT

ALTER TABLE [REISKOSTEN_NAAR_HET_WERK_] ADD CONSTRAINT FK_REISKOSTEN_NAAR_HET_WERK__GEN_KOSTENCOMPONENT FOREIGN KEY ([KOSTENCOMPONENT_ID]) REFERENCES [KOSTENCOMPONENT] ([KOSTENCOMPONENT_ID]);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE [REISKOSTENVERGOEDING] ADD CONSTRAINT FK_REISKOSTENVERGOEDING_GEN_VERGOEDING FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [VERGOEDING] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to VERGOEDING

ALTER TABLE [SECUNDAIR_INKOMSTENCOMPONENT] ADD CONSTRAINT FK_SECUNDAIR_INKOMSTENCOMPONENT_GEN_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to INKOMSTENCOMPONENT

ALTER TABLE [STAGE] ADD CONSTRAINT FK_STAGE_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [STUDIEFINANCIERING] ADD CONSTRAINT FK_STUDIEFINANCIERING_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [TE_BETALEN_ALIMENTATIE] ADD CONSTRAINT FK_TE_BETALEN_ALIMENTATIE_GEN_KOSTENCOMPONENT FOREIGN KEY ([KOSTENCOMPONENT_ID]) REFERENCES [KOSTENCOMPONENT] ([KOSTENCOMPONENT_ID]);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE [UITKERING] ADD CONSTRAINT FK_UITKERING_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [PRIMAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE [VAKANTIEGELD] ADD CONSTRAINT FK_VAKANTIEGELD_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [SECUNDAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE [VERGOEDING] ADD CONSTRAINT FK_VERGOEDING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [SECUNDAIR_INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE [VERGOEDING_IN_NATURA] ADD CONSTRAINT FK_VERGOEDING_IN_NATURA_GEN_VERGOEDING FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [VERGOEDING] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to VERGOEDING

ALTER TABLE [VERLAGING_DOOR_BOETE] ADD CONSTRAINT FK_VERLAGING_DOOR_BOETE_GEN_INKOMSTENVERMINDERING FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [INKOMSTENVERMINDERING] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE [VERLAGING_DOOR_MAATREGEL] ADD CONSTRAINT FK_VERLAGING_DOOR_MAATREGEL_GEN_INKOMSTENVERMINDERING FOREIGN KEY ([INKOMSTENCOMPONENT_ID]) REFERENCES [INKOMSTENVERMINDERING] ([INKOMSTENCOMPONENT_ID]);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE [UITKERING] ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VERLAGING_DOOR_BOETE FOREIGN KEY ([UITKERING_HEEFT_VERLAGING_DOOR_BOETE_VERLAGING_DOOR_BOETE_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- UITKERING_HEEFT_VERLAGING_DOOR_BOETE (0..* to 1..1, Connector_ID: 877)

ALTER TABLE [UITKERING] ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VAKANTIEGELD FOREIGN KEY ([UITKERING_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- UITKERING_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 878)

ALTER TABLE [UITKERING] ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL FOREIGN KEY ([UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL_VERLAGING_DOOR_MAATREGEL_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL (0..* to 1..1, Connector_ID: 879)

ALTER TABLE [STAGE] ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_VERGOEDING_IN_NATURA FOREIGN KEY ([STAGE_HEEFT_VERGOEDING_IN_NATURA_VERGOEDING_IN_NATURA_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- STAGE_HEEFT_VERGOEDING_IN_NATURA (0..* to 1..1, Connector_ID: 883)

ALTER TABLE [STAGE] ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_REISKOSTENVERGOEDING FOREIGN KEY ([STAGE_HEEFT_REISKOSTENVERGOEDING_REISKOSTENVERGOEDING_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- STAGE_HEEFT_REISKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 886)

ALTER TABLE [PENSIOEN] ADD CONSTRAINT FK_PENSIOEN_PENSIOEN_HEEFT_VAKANTIEGELD FOREIGN KEY ([PENSIOEN_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- PENSIOEN_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 890)

ALTER TABLE [STAGE] ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_ONKOSTENVERGOEDING FOREIGN KEY ([STAGE_HEEFT_ONKOSTENVERGOEDING_ONKOSTENVERGOEDING_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- STAGE_HEEFT_ONKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 892)

ALTER TABLE [ONDERHOUDSVERHOUDING] ADD CONSTRAINT FK_ONDERHOUDSVERHOUDING_ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT FOREIGN KEY ([ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT_ONDERHOUDSPLICHT_ID]) REFERENCES [ONDERHOUDSPLICHT] ([ONDERHOUDSPLICHT_ID]);
-- ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT (0..* to 1..1, Connector_ID: 894)

ALTER TABLE [STAGE] ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_MAALTIJDVERGOEDING FOREIGN KEY ([STAGE_HEEFT_MAALTIJDVERGOEDING_MAALTIJDVERGOEDING_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- STAGE_HEEFT_MAALTIJDVERGOEDING (0..* to 1..1, Connector_ID: 895)

ALTER TABLE [UITKERING] ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_LOONBESLAG FOREIGN KEY ([UITKERING_HEEFT_LOONBESLAG_LOONBESLAG_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- UITKERING_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 897)

ALTER TABLE [PENSIOEN] ADD CONSTRAINT FK_PENSIOEN_PENSIOEN_HEEFT_LOONBESLAG FOREIGN KEY ([PENSIOEN_HEEFT_LOONBESLAG_LOONBESLAG_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- PENSIOEN_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 898)

ALTER TABLE [INKOMSTENVERHOUDING] ADD CONSTRAINT FK_INKOMSTENVERHOUDING_INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY ([INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT_PRIMAIR_INKOMSTENCOMPONENT_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT (1..* to 0..1, Connector_ID: 901)

ALTER TABLE [DRAAGKRACHT] ADD CONSTRAINT FK_DRAAGKRACHT_DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME FOREIGN KEY ([DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME_DRAAGKRACHTREGIME_ID]) REFERENCES [DRAAGKRACHTREGIME] ([DRAAGKRACHTREGIME_ID]);
-- DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME (1..* to 1..1, Connector_ID: 906)

ALTER TABLE [BETAALD_WERK] ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING FOREIGN KEY ([BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING_MAALTIJDVERGOEDING_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING (0..* to 1..1, Connector_ID: 908)

ALTER TABLE [BETAALD_WERK] ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING FOREIGN KEY ([BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING_DERTIENDE_MAAND_EINDEJAARSUITKERING_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING (0..* to 1..1, Connector_ID: 909)

ALTER TABLE [BETAALD_WERK] ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING FOREIGN KEY ([BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING_REISKOSTENVERGOEDING_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 910)

ALTER TABLE [BETAALD_WERK] ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING FOREIGN KEY ([BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING_ONKOSTENVERGOEDING_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 911)

ALTER TABLE [BETAALD_WERK] ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_LOONBESLAG FOREIGN KEY ([BETAALD_WERK_HEEFT_LOONBESLAG_LOONBESLAG_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- BETAALD_WERK_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 912)

ALTER TABLE [BETAALD_WERK] ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_HEFFINGSKORTING FOREIGN KEY ([BETAALD_WERK_HEEFT_HEFFINGSKORTING_HEFFINGSKORTING_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- BETAALD_WERK_HEEFT_HEFFINGSKORTING (0..* to 1..1, Connector_ID: 913)

ALTER TABLE [BETAALD_WERK] ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_VAKANTIEGELD FOREIGN KEY ([BETAALD_WERK_HEEFT_VAKANTIEGELD_VAKANTIEGELD_ID]) REFERENCES [INKOMSTENCOMPONENT] ([INKOMSTENCOMPONENT_ID]);
-- BETAALD_WERK_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 914)

