CREATE TABLE [CLIENTBEGELEIDER] (
    [CLIENTBEGELEIDER_ID] INT PRIMARY KEY,
        [BEGELEIDERSCODE] VARCHAR(20)
);

CREATE TABLE [DOELGROEP] (
    [DOELGROEP_ID] INT PRIMARY KEY,
        [NAAM] VARCHAR(255),
        [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [CLIENT] (
    [CLIENT_ID] INT PRIMARY KEY,
        [CODE] VARCHAR(80),
        [GEZAGSDRAGERGEKEND] BIT,
        [JURIDISCHESTATUS] VARCHAR(80),
        [VALT_BINNEN_DOELGROEP_ID] INT,
        [WETTELIJKEVERTEGENWOORDIGING] VARCHAR(80)
);

CREATE TABLE [KP_CLNTBGLDR] (
    [KP_CLNTBGLDR_ID] INT PRIMARY KEY,
    [CLIENTBEGELEIDER_ID] INT,
    [CLIENT_ID] INT
);

CREATE TABLE [WERKZOEKENDE] (
    [CLIENT_ID] INT PRIMARY KEY,
        [DATUMAANVANGWERKZOEKENDE] DATE,
        [DATUMEINDEWERKZOEKENDE] DATE
);

ALTER TABLE [WERKZOEKENDE] ADD CONSTRAINT FK_WERKZOEKENDE_GEN_CLIENT FOREIGN KEY ([CLIENT_ID]) REFERENCES [CLIENT] ([CLIENT_ID]);
-- Generalization to CLIENT

ALTER TABLE [KP_CLNTBGLDR] ADD CONSTRAINT FK_KP_CLNTBGLDR_1 FOREIGN KEY ([CLIENTBEGELEIDER_ID]) REFERENCES [CLIENTBEGELEIDER] ([CLIENTBEGELEIDER_ID]);
-- CLIENTBEGELEIDER (many-to-many junction, Connector_ID: 941)

ALTER TABLE [KP_CLNTBGLDR] ADD CONSTRAINT FK_KP_CLNTBGLDR_2 FOREIGN KEY ([CLIENT_ID]) REFERENCES [CLIENT] ([CLIENT_ID]);
-- CLIENT (many-to-many junction, Connector_ID: 941)

ALTER TABLE [CLIENT] ADD CONSTRAINT FK_CLIENT_VALT_BINNEN FOREIGN KEY ([VALT_BINNEN_DOELGROEP_ID]) REFERENCES [DOELGROEP] ([DOELGROEP_ID]);
-- VALT_BINNEN (None to None, Connector_ID: 1586)

