CREATE TABLE [ADRESSEERBAAROBJECT] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
        [ADRESSEERBAAROBJECT_SELF_ID] INT,
        [HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID] INT,
        [HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID] INT,
        [IDENTIFICATIE] VARCHAR(255),
        [TYPEADRESSEERBAAROBJECT] VARCHAR(255),
        [VERSIE] INT
);

CREATE TABLE [NUMMERAANDUIDING] (
    [NUMMERAANDUIDING_ID] INT PRIMARY KEY,
        [BEGINGELDIGHEID] VARCHAR(255),
        [DATUMEINDE] DATE,
        [DATUMINGANG] DATE,
        [DOCUMENTDATUM] DATE,
        [DOCUMENTNUMMER] INT,
        [EINDEGELDIGHEID] DATE,
        [GECONSTATEERD] BIT,
        [GEOMETRIE] GEOMETRY,
        [HUISLETTER] VARCHAR(255),
        [HUISNUMMER] VARCHAR(255),
        [HUISNUMMERTOEVOEGING] VARCHAR(255),
        [IDENTIFICATIE] VARCHAR(255),
        [POSTCODE] VARCHAR(255),
        [STATUS] VARCHAR(255),
        [TYPEADRESSEERBAAROBJECT] VARCHAR(255),
        [VERSIE] INT
);

CREATE TABLE [OVERIGEADRESSEERBAAROBJECTAANDUIDING] (
    [NUMMERAANDUIDING_ID] INT PRIMARY KEY,
        [IDENTIFICATIECODEOVERIGADRESSEERBAAROBJECTAANDUIDING] VARCHAR(255)
);

ALTER TABLE [OVERIGEADRESSEERBAAROBJECTAANDUIDING] ADD CONSTRAINT FK_OVERIGEADRESSEERBAAROBJECTAANDUIDING_GEN_NUMMERAANDUIDING FOREIGN KEY ([NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- Generalization to NUMMERAANDUIDING

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- unnamed (None to None, Connector_ID: 1540)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY ([HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 350)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY ([HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 347)

