CREATE TABLE BEHEEROBJECT (
    BEHEEROBJECT_ID VARCHAR(255) PRIMARY KEY,
        AANGEMAAKTDOOR VARCHAR(200),
        BEGINGARANTIEPERIODE VARCHAR(255),
        BEHEERGEBIED VARCHAR(255),
        BEHEEROBJECTBEHEERVAK VARCHAR(255),
        BEHEEROBJECTGEBRUIKSFUNCTIE VARCHAR(255),
        BEHEEROBJECTMEMO VARCHAR(255),
        BESCHERMDEFLORAENFAUNA BOOLEAN,
        BUURT VARCHAR(80),
        CONVERSIEID VARCHAR(50),
        DATUMMUTATIE DATE,
        DATUMOPLEVERING DATE,
        DATUMPUBLICATIELV DATE,
        DATUMVERWIJDERING DATE,
        EINDEGARANTIEPERIODE DATE,
        GEBIEDSTYPE VARCHAR(255),
        GEMEENTE VARCHAR(80),
        GEOMETRIE GEOMETRY,
        GEWIJZIGDDOOR VARCHAR(200),
        GRONDSOORT VARCHAR(255),
        GRONDSOORTPLUS VARCHAR(255),
        IDENTIFICATIEIMBOR VARCHAR(255),
        IDENTIFICATIEIMGEO VARCHAR(255),
        JAARVANAANLEG VARCHAR(255),
        OBJECTBEGINTIJD TIMESTAMP,
        OBJECTEINDTIJD TIMESTAMP,
        ONDERHOUDSPLICHTIGE VARCHAR(255),
        OPENBARERUIMTE VARCHAR(80),
        POSTCODE VARCHAR(255),
        RELATIEVEHOOGTELIGGING VARCHAR(255),
        STADSDEEL VARCHAR(80),
        STATUS VARCHAR(255),
        THEORETISCHEINDEJAAR DATE,
        TIJDSTIPREGISTRATIE TIMESTAMP,
        TYPEBEHEERDER VARCHAR(255),
        TYPEBEHEERDERPLUS VARCHAR(255),
        TYPEEIGENAAR VARCHAR(255),
        TYPEEIGENAARPLUS VARCHAR(255),
        TYPELIGGING VARCHAR(255),
        WATERSCHAP VARCHAR(80),
        WIJK VARCHAR(80),
        WOONPLAATS VARCHAR(80),
        ZETTINGSGEVOELIGHEID VARCHAR(255),
        ZETTINGSGEVOELIGHEIDPLUS VARCHAR(255)
);

CREATE TABLE GEO_OBJECT (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEID DATE,
        DATUMEINDEGELDIGHEID DATE,
        GEOMETRIESOORT GEOMETRY,
        IDENTIFICATIE VARCHAR(255),
        VERWIJST_NAAR_BEHEEROBJECT_ID VARCHAR(255)
);

CREATE TABLE BEGROEIDTERREINDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        BEGROEIDTERREINDEELOPTALUD DATE,
        DATUMBEGINGELDIGHEIDBEGROEIDTERREINDEEL DATE,
        DATUMEINDEGELDIGHEIDBEGROEIDTERREINDEEL DATE,
        FYSIEKVOORKOMENBEGROEIDTERREINDEEL DATE,
        GEOMETRIEBEGROEIDTERREINDEEL GEOMETRY,
        IDENTIFICATIEBEGROEIDTERREINDEEL DATE,
        KRUINLIJNGEOMETRIEBEGROEIDTERREINDEEL GEOMETRY,
        LOD0GEOMETRIEBEGROEIDTERREINDEEL GEOMETRY,
        PLUSFYSIEKVOORKOMENBEGROEIDTERREINDEEL DATE,
        RELATIEVEHOOGTELIGGINGBEGROEIDTERREINDEEL DATE,
        STATUSBEGROEIDTERREINDEEL DATE
);

CREATE TABLE FUNCTIONEELGEBIED (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDFUNCTIONEELGEBIED DATE,
        DATUMEINDEGELDIGHEIDFUNCTIONEELGEBIED DATE,
        GEOMETRIEFUNCTIONEELGEBIED GEOMETRY,
        IDENTIFICATIEFUNCTIONEELGEBIED VARCHAR(255),
        NAAMFUNCTIONEELGEBIED VARCHAR(255),
        STATUSFUNCTIONEELGEBIED VARCHAR(255)
);

CREATE TABLE GEBOUWINSTALLATIE (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDGEBOUWINSTALLATIE DATE,
        DATUMEINDEGELDIGHEIDGEBOUWINSTALLATIE DATE,
        GEOMETRIEGEBOUWINSTALLATIE GEOMETRY,
        IDENTIFICATIEGEBOUWINSTALLATIE VARCHAR(255),
        LOD0GEOMETRIEGEBOUWINSTALLATIE GEOMETRY,
        RELATIEVEHOOGTELIGGINGGEBOUWINSTALLATIE VARCHAR(255),
        STATUSGEBOUWINSTALLATIE VARCHAR(255),
        TYPEGEBOUWINSTALLATIE VARCHAR(255)
);

CREATE TABLE INRICHTINGSELEMENT (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDINRICHTINGSELEMENT DATE,
        DATUMEINDEGELDIGHEIDINRICHTINGSELEMENT DATE,
        GEOMETRIEINRICHTINGSELEMENT GEOMETRY,
        IDENTIFICATIEINRICHTINGSELEMENT VARCHAR(255),
        LOD0GEOMETRIEINRICHTINGSELEMENT GEOMETRY,
        PLUSTYPEINRICHTINGSELEMENT VARCHAR(255),
        RELATIEVEHOOGTELIGGINGINRICHTINGSELEMENT VARCHAR(255),
        STATUSINRICHTINGSELEMENT VARCHAR(255),
        TYPEINRICHTINGSELEMENT VARCHAR(255)
);

CREATE TABLE KUNSTWERKDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDKUNSTWERKDEEL DATE,
        DATUMEINDEGELDIGHEIDKUNSTWERKDEEL DATE,
        GEOMETRIEKUNSTWERKDEEL GEOMETRY,
        IDENTIFICATIEKUNSTWERKDEEL VARCHAR(255),
        LOD0GEOMETRIEKUNSTWERKDEEL GEOMETRY,
        LOD1GEOMETRIEKUNSTWERKDEEL GEOMETRY,
        LOD2GEOMETRIEKUNSTWERKDEEL GEOMETRY,
        LOD3GEOMETRIEKUNSTWERKDEEL GEOMETRY,
        RELATIEVEHOOGTELIGGINGKUNSTWERKDEEL VARCHAR(255),
        STATUSKUNSTWERKDEEL VARCHAR(255)
);

CREATE TABLE ONBEGROEIDTERREINDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDONBEGROEIDTERREINDEEL DATE,
        DATUMEINDEGELDIGHEIDONBEGROEIDTERREINDEEL DATE,
        FYSIEKVOORKOMENONBEGROEIDTERREINDEEL DATE,
        GEOMETRIEONBEGROEIDTERREINDEEL GEOMETRY,
        IDENTIFICATIEONBEGROEIDTERREINDEEL DATE,
        KRUINLIJNGEOMETRIEONBEGROEIDTERREINDEEL GEOMETRY,
        ONBEGROEIDTERREINDEELOPTALUD DATE,
        PLUSFYSIEKVOORKOMENONBEGROEIDTERREINDEEL DATE,
        RELATIEVEHOOGTELIGGINGONBEGROEIDTERREINDEEL DATE,
        STATUSONBEGROEIDTERREINDEEL DATE
);

CREATE TABLE ONDERSTEUNENDWATERDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDONDERSTEUNENDWATERDEEL DATE,
        DATUMEINDEGELDIGHEIDONDERSTEUNENDWATERDEEL DATE,
        GEOMETRIEONDERSTEUNENDWATERDEEL GEOMETRY,
        IDENTIFICATIEONDERSTEUNENDWATERDEEL VARCHAR(255),
        PLUSTYPEONDERSTEUNENDWATERDEEL VARCHAR(255),
        RELATIEVEHOOGTELIGGINGONDERSTEUNENDWATERDEEL VARCHAR(255),
        STATUSONDERSTEUNENDWATERDEEL VARCHAR(255),
        TYPEONDERSTEUNENDWATERDEEL VARCHAR(255)
);

CREATE TABLE ONDERSTEUNENDWEGDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDONDERSTEUNENDWEGDEEL DATE,
        DATUMEINDEGELDIGHEIDONDERSTEUNENDWEGDEEL DATE,
        FUNCTIEONDERSTEUNENDWEGDEEL VARCHAR(255),
        FYSIEKVOORKOMENONDERSTEUNENDWEGDEEL_ VARCHAR(255),
        GEOMETRIEONDERSTEUNENDWEGDEEL GEOMETRY,
        IDENTIFICATIEONDERSTEUNENDWEGDEEL VARCHAR(255),
        KRUINLIJNGEOMETRIEONDERSTEUNENDWEGDEEL GEOMETRY,
        LOD0GEOMETRIEONDERSTEUNENDWEGDEEL GEOMETRY,
        ONDERSTEUNENDWEGDEELOPTALUD VARCHAR(255),
        PLUSFUNCTIEONDERSTEUNENDWEGDEEL VARCHAR(255),
        PLUSFYSIEKVOORKOMENONDERSTEUNENDWEGDEEL VARCHAR(255),
        RELATIEVEHOOGTELIGGINGONDERSTEUNENDWEGDEEL VARCHAR(255),
        STATUSONDERSTEUNENDWEGDEEL VARCHAR(255)
);

CREATE TABLE OVERBRUGGINGSDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDOVERBRUGGINGSDEEL DATE,
        DATUMEINDEGELDIGHEIDOVERBRUGGINGSDEEL DATE,
        GEOMETRIEOVERBRUGGINGSDEEL GEOMETRY,
        HOORTBIJTYPEOVERBRUGGING VARCHAR(255),
        IDENTIFICATIEOVERBRUGGINGSDEEL VARCHAR(255),
        LOD0GEOMETRIEOVERBRUGGINGSDEEL GEOMETRY,
        OVERBRUGGINGISBEWEEGBAAR VARCHAR(255),
        RELATIEVEHOOGTELIGGINGOVERBRUGGINGSDEEL VARCHAR(255),
        STATUSOVERBRUGGINGSDEEL VARCHAR(255),
        TYPEOVERBRUGGINGSDEEL VARCHAR(255)
);

CREATE TABLE OVERIGBENOEMDTERREIN (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        GEBRUIKSDOELOVERIGBENOEMDTERREIN VARCHAR(255),
        OVERIGBENOEMDTERREINIDENTIFICATIE VARCHAR(255)
);

CREATE TABLE OVERIGBOUWWERK (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDOVERIGBOUWWERK DATE,
        DATUMEINDEGELDIGHEIDOVERIGBOUWWERK DATE,
        GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        IDENTIFICATIEOVERIGBOUWWERK VARCHAR(255),
        LOD0GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        LOD1GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        LOD2GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        LOD3GEOMETRIEOVERIGBOUWWERK GEOMETRY,
        RELATIEVEHOOGTELIGGINGOVERIGBOUWWERK VARCHAR(255),
        STATUSOVERIGBOUWWERK VARCHAR(255)
);

CREATE TABLE OVERIGESCHEIDING (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDOVERIGESCHEIDING DATE,
        DATUMEINDEGELDIGHEIDOVERIGESCHEIDING DATE,
        GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        IDENTIFICATIEOVERIGESCHEIDING VARCHAR(255),
        LOD0GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        LOD1GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        LOD2GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        LOD3GEOMETRIEOVERIGESCHEIDING GEOMETRY,
        RELATIEVEHOOGTELIGGINGOVERIGESCHEIDING VARCHAR(255),
        STATUSOVERIGESCHEIDING VARCHAR(255),
        TYPEOVERIGESCHEIDING VARCHAR(255)
);

CREATE TABLE PAND (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        BRUTOINHOUDPAND VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER VARCHAR(255),
        EINDGELDIGHEID DATE,
        GECONSTATEERD BOOLEAN,
        GEOMETRIEBOVENAANZICHT GEOMETRY,
        GEOMETRIEMAAIVELD GEOMETRY,
        GEOMETRIEPUNT GEOMETRY,
        HOOGSTEBOUWLAAG VARCHAR(255),
        IDENTIFICATIE VARCHAR(255),
        LAAGSTEBOUWLAAG VARCHAR(255),
        OORSPRONKELIJKBOUWJAAR VARCHAR(255),
        OPPERVLAKTE VARCHAR(255),
        RELATIEVEHOOGTELIGGING VARCHAR(255),
        STATUS VARCHAR(255),
        STATUSVOORTGANGBOUW VARCHAR(255),
        VERSIE INTEGER
);

CREATE TABLE SCHEIDING (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDSCHEIDING DATE,
        DATUMEINDEGELDIGHEIDSCHEIDING DATE,
        GEOMETRIESCHEIDING GEOMETRY,
        IDENTIFICATIESCHEIDING VARCHAR(255),
        LOD0GEOMETRIESCHEIDING GEOMETRY,
        LOD1GEOMETRIESCHEIDING GEOMETRY,
        LOD2GEOMETRIESCHEIDING GEOMETRY,
        LOD3GEOMETRIESCHEIDING GEOMETRY,
        RELATIEVEHOOGTELIGGINGSCHEIDING VARCHAR(255),
        STATUSSCHEIDING VARCHAR(255)
);

CREATE TABLE SPOOR (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDSPOOR DATE,
        DATUMEINDEGELDIGHEIDSPOOR DATE,
        GEOMETRIESPOOR GEOMETRY,
        IDENTIFICATIESPOOR VARCHAR(255),
        LOD0GEOMETRIESPOOR GEOMETRY,
        RELATIEVEHOOGTELIGGINGSPOOR VARCHAR(255),
        STATUSSPOOR VARCHAR(255)
);

CREATE TABLE TUNNELDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDTUNNELDEEL DATE,
        DATUMEINDEGELDIGHEIDTUNNELDEEL DATE,
        GEOMETRIETUNNELDEEL GEOMETRY,
        IDENTIFICATIETUNNELDEEL VARCHAR(255),
        LOD0GEOMETRIETUNNELDEEL GEOMETRY,
        RELATIEVEHOOGTELIGGINGTUNNELDEEL VARCHAR(255),
        STATUSTUNNELDEEL VARCHAR(255)
);

CREATE TABLE VEGETATIEOBJECT (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDVEGETATIEOBJECT DATE,
        DATUMEINDEGELDIGHEIDVEGETATIEOBJECT DATE,
        GEOMETRIEVEGETATIEOBJECT GEOMETRY,
        IDENTIFICATIEVEGETATIEOBJECT VARCHAR(255),
        LOD0GEOMETRIEVEGETATIEOBJECT GEOMETRY,
        RELATIEVEHOOGTELIGGINGVEGETATIEOBJECT VARCHAR(255),
        STATUSVEGETATIEOBJECT VARCHAR(255),
        TYPEVEGETATIEOBJECT VARCHAR(255)
);

CREATE TABLE WATERDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDWATERDEEL DATE,
        DATUMEINDEGELDIGHEIDWATERDEEL DATE,
        GEOMETRIEWATERDEEL GEOMETRY,
        IDENTIFICATIEWATERDEEL VARCHAR(255),
        PLUSTYPEWATERDEEL VARCHAR(255),
        RELATIEVEHOOGTELIGGINGWATERDEEL VARCHAR(255),
        STATUSWATERDEEL VARCHAR(255),
        TYPEWATERDEEL VARCHAR(255)
);

CREATE TABLE WEGDEEL (
    GEO_OBJECT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDWEGDEEL DATE,
        DATUMEINDEGELDIGHEIDWEGDEEL DATE,
        FUNCTIEWEGDEEL VARCHAR(255),
        FYSIEKVOORKOMENWEGDEEL VARCHAR(255),
        GEOMETRIEWEGDEEL GEOMETRY,
        IDENTIFICATIEWEGDEEL VARCHAR(255),
        KRUINLIJNGEOMETRIEWEGDEEL GEOMETRY,
        LOD0GEOMETRIEWEGDEEL GEOMETRY,
        PLUSFUNCTIEWEGDEEL VARCHAR(255),
        PLUSFYSIEKVOORKOMENWEGDEEL VARCHAR(255),
        RELATIEVEHOOGTELIGGINGWEGDEEL VARCHAR(255),
        STATUSWEGDEEL VARCHAR(255),
        WEGDEELOPTALUD VARCHAR(255)
);

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE BEGROEIDTERREINDEEL ADD CONSTRAINT FK_BEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE FUNCTIONEELGEBIED ADD CONSTRAINT FK_FUNCTIONEELGEBIED_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE GEBOUWINSTALLATIE ADD CONSTRAINT FK_GEBOUWINSTALLATIE_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE INRICHTINGSELEMENT ADD CONSTRAINT FK_INRICHTINGSELEMENT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE KUNSTWERKDEEL ADD CONSTRAINT FK_KUNSTWERKDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONBEGROEIDTERREINDEEL ADD CONSTRAINT FK_ONBEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONDERSTEUNENDWATERDEEL ADD CONSTRAINT FK_ONDERSTEUNENDWATERDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONDERSTEUNENDWEGDEEL ADD CONSTRAINT FK_ONDERSTEUNENDWEGDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERBRUGGINGSDEEL ADD CONSTRAINT FK_OVERBRUGGINGSDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGBENOEMDTERREIN ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGBOUWWERK ADD CONSTRAINT FK_OVERIGBOUWWERK_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGESCHEIDING ADD CONSTRAINT FK_OVERIGESCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE SCHEIDING ADD CONSTRAINT FK_SCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE SPOOR ADD CONSTRAINT FK_SPOOR_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE TUNNELDEEL ADD CONSTRAINT FK_TUNNELDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE VEGETATIEOBJECT ADD CONSTRAINT FK_VEGETATIEOBJECT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE WATERDEEL ADD CONSTRAINT FK_WATERDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE WEGDEEL ADD CONSTRAINT FK_WEGDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE GEO_OBJECT ADD CONSTRAINT FK_GEO_OBJECT_VERWIJST_NAAR FOREIGN KEY (VERWIJST_NAAR_BEHEEROBJECT_ID) REFERENCES BEHEEROBJECT (BEHEEROBJECT_ID);
-- VERWIJST_NAAR (1 to 0..1, Connector_ID: 805)

