CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR2(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR2(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR2(200),
        DOCUMENTIDENTIFICATIE VARCHAR2(255),
        DOCUMENTTITEL VARCHAR2(200),
        VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE OMGEVINGSVERGUNNING (
    OMGEVINGSVERGUNNING_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE OPBREKING (
    OPBREKING_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE MOOR_MELDING (
    MOOR_MELDING_ID VARCHAR2(255) PRIMARY KEY,
        ADRESAANDUIDING VARCHAR2(255),
        BETREFT_OPBREKING_ID VARCHAR2(255),
        BETREFT_PROCES_VERBAAL_MOOR_MELDING_ID VARCHAR2(255),
        DATUMAANMELDING DATE,
        DATUMGOEDKEURING DATE,
        EINDTIJD TIMESTAMP,
        GOEDGEKEURD NUMBER(1),
        HERSTELWERKZAAMHEDENVEREIST NUMBER(1),
        OMSCHRIJVINGHERSTELWERKZAAMHEDEN CLOB,
        PUBLICEREN NUMBER(1),
        STARTTIJD TIMESTAMP,
        VERPLICHT_TOT_OMGEVINGSVERGUNNING_ID VARCHAR2(255),
        WEGBEHEERDER VARCHAR2(80)
);

CREATE TABLE PROCES_VERBAAL_MOOR_MELDING (
    PROCES_VERBAAL_MOOR_MELDING_ID VARCHAR2(255) PRIMARY KEY,
        DATUM DATE,
        GOEDKEURING NUMBER(1),
        HEEFT_DOCUMENT_ID VARCHAR2(255),
        OPMERKINGEN CLOB
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        ADRESCORRESPONDENTIE VARCHAR2(100),
        EMAILADRES VARCHAR2(80),
        FAXNUMMER VARCHAR2(20),
        IDENTIFICATIE VARCHAR2(255),
        KVKNUMMER VARCHAR2(20),
        NAAM VARCHAR2(200),
        RECHTSVORM VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE GRONDBEHEERDER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200),
        NUMMER VARCHAR2(255)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID VARCHAR2(255) PRIMARY KEY,
        ACHTERNAAM VARCHAR2(200),
        DATUMINDIENST DATE,
        DATUMUITDIENST DATE,
        EMAILADRES VARCHAR2(255),
        EXTERN VARCHAR2(255),
        FUNCTIE VARCHAR2(50),
        GELEVERD_VIA_LEVERANCIER_ID VARCHAR2(255),
        GESLACHTSAANDUIDING VARCHAR2(255),
        MEDEWERKERIDENTIFICATIE VARCHAR2(255),
        MEDEWERKERTOELICHTING VARCHAR2(255),
        ROEPNAAM VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20),
        VERLEENT_PROCES_VERBAAL_MOOR_MELDING_ID VARCHAR2(255),
        VOORLETTERS VARCHAR2(20),
        VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE UITVOERDER_GRAAFWERKZAAMHEDEN (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DOET_MOOR_MELDING_ID VARCHAR2(255),
        MAAKT_OPBREKING_ID VARCHAR2(255)
);

ALTER TABLE GRONDBEHEERDER ADD CONSTRAINT FK_GRONDBEHEERDER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE UITVOERDER_GRAAFWERKZAAMHEDEN ADD CONSTRAINT FK_UITVOERDER_GRAAFWERKZAAMHEDEN_GEN_GRONDBEHEERDER FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES GRONDBEHEERDER (RECHTSPERSOON_ID);
-- Generalization to GRONDBEHEERDER

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_GELEVERD_VIA FOREIGN KEY (GELEVERD_VIA_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- GELEVERD_VIA (0..* to 0..1, Connector_ID: 388)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_VERLEENT FOREIGN KEY (VERLEENT_PROCES_VERBAAL_MOOR_MELDING_ID) REFERENCES PROCES_VERBAAL_MOOR_MELDING (PROCES_VERBAAL_MOOR_MELDING_ID);
-- VERLEENT (1 to 0..*, Connector_ID: 724)

ALTER TABLE MOOR_MELDING ADD CONSTRAINT FK_MOOR_MELDING_BETREFT FOREIGN KEY (BETREFT_OPBREKING_ID) REFERENCES OPBREKING (OPBREKING_ID);
-- BETREFT (0..1 to 1, Connector_ID: 730)

ALTER TABLE MOOR_MELDING ADD CONSTRAINT FK_MOOR_MELDING_BETREFT_2 FOREIGN KEY (BETREFT_PROCES_VERBAAL_MOOR_MELDING_ID) REFERENCES PROCES_VERBAAL_MOOR_MELDING (PROCES_VERBAAL_MOOR_MELDING_ID);
-- BETREFT (1 to 0..*, Connector_ID: 731)

ALTER TABLE MOOR_MELDING ADD CONSTRAINT FK_MOOR_MELDING_VERPLICHT_TOT FOREIGN KEY (VERPLICHT_TOT_OMGEVINGSVERGUNNING_ID) REFERENCES OMGEVINGSVERGUNNING (OMGEVINGSVERGUNNING_ID);
-- VERPLICHT_TOT (0..* to 0..1, Connector_ID: 729)

ALTER TABLE PROCES_VERBAAL_MOOR_MELDING ADD CONSTRAINT FK_PROCES_VERBAAL_MOOR_MELDING_HEEFT FOREIGN KEY (HEEFT_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- HEEFT (0..* to 0..1, Connector_ID: 725)

ALTER TABLE UITVOERDER_GRAAFWERKZAAMHEDEN ADD CONSTRAINT FK_UITVOERDER_GRAAFWERKZAAMHEDEN_DOET FOREIGN KEY (DOET_MOOR_MELDING_ID) REFERENCES MOOR_MELDING (MOOR_MELDING_ID);
-- DOET (1 to 0..*, Connector_ID: 728)

ALTER TABLE UITVOERDER_GRAAFWERKZAAMHEDEN ADD CONSTRAINT FK_UITVOERDER_GRAAFWERKZAAMHEDEN_MAAKT FOREIGN KEY (MAAKT_OPBREKING_ID) REFERENCES OPBREKING (OPBREKING_ID);
-- MAAKT (1.. to 0..*, Connector_ID: 726)

