CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID VARCHAR2(255),
        HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        TYPEADRESSEERBAAROBJECT VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE LIGPLAATS (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID DATE,
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(255),
        STATUS VARCHAR2(255),
        VERSIE VARCHAR2(255)
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDEGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HUISLETTER VARCHAR2(255),
        HUISNUMMER VARCHAR2(255),
        HUISNUMMERTOEVOEGING VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        LIGT_AAN_OPENBARERUIMTE_ID VARCHAR2(255),
        POSTCODE VARCHAR2(255),
        STATUS VARCHAR2(255),
        TYPEADRESSEERBAAROBJECT VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE OPENBARERUIMTE (
    OPENBARERUIMTE_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS VARCHAR2(255),
        HUISNUMMERRANGE_EVEN_NUMMERS VARCHAR2(255),
        HUISNUMMERRANGE_ONEVEN_NUMMERS VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        LABELNAAM VARCHAR2(80),
        NAAMOPENBARERUIMTE VARCHAR2(80),
        STATUS VARCHAR2(255),
        STRAATCODE VARCHAR2(80),
        STRAATNAAM VARCHAR2(255),
        TYPEOPENBARERUIMTE VARCHAR2(255),
        VERSIE NUMBER,
        WEGSEGMENT VARCHAR2(255)
);

CREATE TABLE OVERIGBENOEMDTERREIN (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        GEBRUIKSDOELOVERIGBENOEMDTERREIN VARCHAR2(255),
        HEEFT_ALS_OFFICIEEL_ADRES_OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID VARCHAR2(255),
        OVERIGBENOEMDTERREINIDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE OVERIGEADRESSEERBAAROBJECTAANDUIDING (
    NUMMERAANDUIDING_ID VARCHAR2(255) PRIMARY KEY,
        IDENTIFICATIECODEOVERIGADRESSEERBAAROBJECTAANDUIDING VARCHAR2(255)
);

CREATE TABLE OVERIGGEBOUWDOBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        BOUWJAAR VARCHAR2(255),
        HEEFT_ALS_OFFICIEEL_ADRES_OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID VARCHAR2(255),
        INDICATIEPLANOBJECT VARCHAR2(255),
        OVERIGGEBOUWDOBJECTIDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE STANDPLAATS (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUM_BEGIN_GELDIGHEID DATE,
        DATUM_EINDE DATE,
        DATUM_EINDE_GELDIGHEID DATE,
        DATUM_INGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(255),
        STATUS VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE VERBLIJFSOBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        AANTALKAMERS VARCHAR2(255),
        BEGINGELDIGHEID DATE,
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDGELDIGHEID DATE,
        GEBRUIKSDOEL VARCHAR2(255),
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HOOGSTEBOUWLAAG VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        LAAGSTEBOUWLAAG VARCHAR2(255),
        ONTSLUITINGVERDIEPING VARCHAR2(255),
        OPPERVLAKTE NUMBER,
        SOORTWOONOBJECT VARCHAR2(255),
        STATUS VARCHAR2(255),
        TOEGANGBOUWLAAG VARCHAR2(255),
        VERSIE NUMBER
);

ALTER TABLE LIGPLAATS ADD CONSTRAINT FK_LIGPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE STANDPLAATS ADD CONSTRAINT FK_STANDPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE OVERIGBENOEMDTERREIN ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE OVERIGGEBOUWDOBJECT ADD CONSTRAINT FK_OVERIGGEBOUWDOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE OVERIGEADRESSEERBAAROBJECTAANDUIDING ADD CONSTRAINT FK_OVERIGEADRESSEERBAAROBJECTAANDUIDING_GEN_NUMMERAANDUIDING FOREIGN KEY (NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- Generalization to NUMMERAANDUIDING

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 350)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 347)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY (LIGT_AAN_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- LIGT_AAN (0..* to 1, Connector_ID: 354)

ALTER TABLE OVERIGBENOEMDTERREIN ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_HEEFT_ALS_OFFICIEEL_ADRES FOREIGN KEY (HEEFT_ALS_OFFICIEEL_ADRES_OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_OFFICIEEL_ADRES (0..1 to 1, Connector_ID: 154)

ALTER TABLE OVERIGGEBOUWDOBJECT ADD CONSTRAINT FK_OVERIGGEBOUWDOBJECT_HEEFT_ALS_OFFICIEEL_ADRES FOREIGN KEY (HEEFT_ALS_OFFICIEEL_ADRES_OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_OFFICIEEL_ADRES (0..1 to 0..1, Connector_ID: 145)

