CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        ADRESSEERBAAROBJECT_SELF_ID VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        TYPEADRESSEERBAAROBJECT VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE APPARTEMENTSRECHT (
    KADASTRALEONROERENDEZAAK_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR2(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR2(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR2(200),
        DOCUMENTIDENTIFICATIE VARCHAR2(255),
        DOCUMENTTITEL VARCHAR2(200),
        VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE KADASTRAALPERCEEL (
    KADASTRALEONROERENDEZAAK_ID VARCHAR2(255) PRIMARY KEY,
        AANDUIDINGSOORTGROOTTE VARCHAR2(255),
        BEGRENZINGPERCEEL VARCHAR2(255),
        GROOTTEPERCEEL VARCHAR2(255),
        INDICATIEDEELPERCEEL VARCHAR2(255),
        OMSCHRIJVINGDEELPERCEEL VARCHAR2(20),
        PLAATSCOORDINATENPERCEEL VARCHAR2(255)
);

CREATE TABLE KADASTRALEMUTATIE (
    KADASTRALEMUTATIE_ID VARCHAR2(255) PRIMARY KEY,
        HEEFT_BETREKKING_OP_ZAKELIJKRECHT_ID VARCHAR2(255)
);

CREATE TABLE KADASTRALEONROERENDEZAAK (
    KADASTRALEONROERENDEZAAK_ID VARCHAR2(255) PRIMARY KEY,
        APPARTEMENTSRECHTVOLGNUMMER VARCHAR2(255),
        ATTRIBUTE VARCHAR2(255),
        BEGRENZING VARCHAR2(255),
        CULTUURCODEONBEBOUWD VARCHAR2(255),
        DATUMBEGINGELDIGHEIDKADASTRALEONROERENDEZAAK DATE,
        DATUMEINDEGELDIGHEIDKADASTRALEONROERENDEZAAK DATE,
        GERELATEERD_KADASTRALEONROERENDEZAAK_ID VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        KADASTRALEGEMEENTE VARCHAR2(20),
        KADASTRALEGEMEENTECODE VARCHAR2(20),
        KOOPJAAR NUMBER,
        KOOPSOM VARCHAR2(255),
        LANDINRICHTINGRENTEBEDRAG NUMBER(10,2),
        LANDINRICHTINGRENTEEINDEJAAR DATE,
        LIGGING VARCHAR2(255),
        LOCATIEOMSCHRIJVING VARCHAR2(255),
        OPPERVLAKTE NUMBER,
        OUD VARCHAR2(255),
        PERCEELNUMMER VARCHAR2(255),
        SECTIE VARCHAR2(255),
        VALUTACODE VARCHAR2(255)
);

CREATE TABLE KADASTRALEONROERENDEZAAKAANTEKENING (
    KADASTRALEONROERENDEZAAKAANTEKENING_ID VARCHAR2(255) PRIMARY KEY,
        AARDAANTEKENINGKADASTRAALOBJECT VARCHAR2(255),
        BESCHRIJVINGAANTEKENINGKADASTRAALOBJECT VARCHAR2(255),
        DATUMBEGINAANTEKENINGKADASTRAALOBJECT DATE,
        DATUMEINDEAANTEKENINGKADASTRAALOBJECT DATE,
        HEEFT_BETREKKING_OP_KADASTRALEONROERENDEZAAK_ID VARCHAR2(255),
        KADASTERIDENTIFICATIEAANTEKENING VARCHAR2(255)
);

CREATE TABLE KP_KDSTRLMTT (
    KP_KDSTRLMTT_ID VARCHAR2(255) PRIMARY KEY,
    KADASTRALEMUTATIE_ID VARCHAR2(255),
    KADASTRALEONROERENDEZAAK_ID VARCHAR2(255)
);

CREATE TABLE KP_KDSTRLNRRNDZK (
    KP_KDSTRLNRRNDZK_ID VARCHAR2(255) PRIMARY KEY,
    IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID VARCHAR2(255),
    IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID VARCHAR2(255)
);

CREATE TABLE KP_RCHTSPRSN (
    KP_RCHTSPRSN_ID VARCHAR2(255) PRIMARY KEY,
    RECHTSPERSOON_ID VARCHAR2(255),
    KADASTRALEMUTATIE_ID VARCHAR2(255)
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        ADRESCORRESPONDENTIE VARCHAR2(100),
        EMAILADRES VARCHAR2(80),
        FAXNUMMER VARCHAR2(20),
        IDENTIFICATIE VARCHAR2(255),
        KVKNUMMER VARCHAR2(20),
        NAAM VARCHAR2(200),
        RECHTSVORM VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE ZAKELIJKRECHT (
    ZAKELIJKRECHT_ID VARCHAR2(255) PRIMARY KEY,
        AARDZAKELIJKRECHT VARCHAR2(255),
        DATUMEINDERECHT DATE,
        DATUMINGANGRECHT DATE,
        IDENTIFICATIEZAKELIJKRECHT VARCHAR2(255),
        IS_BELAST_MET_ZAKELIJKRECHT_ID VARCHAR2(255),
        RUST_OP_KADASTRALEONROERENDEZAAK_ID VARCHAR2(255),
        TOELICHTINGBEWAARDER VARCHAR2(100)
);

ALTER TABLE APPARTEMENTSRECHT ADD CONSTRAINT FK_APPARTEMENTSRECHT_GEN_KADASTRALEONROERENDEZAAK FOREIGN KEY (KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- Generalization to KADASTRALEONROERENDEZAAK

ALTER TABLE KADASTRAALPERCEEL ADD CONSTRAINT FK_KADASTRAALPERCEEL_GEN_KADASTRALEONROERENDEZAAK FOREIGN KEY (KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- Generalization to KADASTRALEONROERENDEZAAK

ALTER TABLE KP_KDSTRLMTT ADD CONSTRAINT FK_KP_KDSTRLMTT_1 FOREIGN KEY (KADASTRALEMUTATIE_ID) REFERENCES KADASTRALEMUTATIE (KADASTRALEMUTATIE_ID);
-- KADASTRALEMUTATIE (many-to-many junction, Connector_ID: 740)

ALTER TABLE KP_KDSTRLMTT ADD CONSTRAINT FK_KP_KDSTRLMTT_2 FOREIGN KEY (KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 740)

ALTER TABLE KP_KDSTRLNRRNDZK ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_1 FOREIGN KEY (IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 178)

ALTER TABLE KP_KDSTRLNRRNDZK ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_2 FOREIGN KEY (IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 178)

ALTER TABLE KP_RCHTSPRSN ADD CONSTRAINT FK_KP_RCHTSPRSN_1 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 739)

ALTER TABLE KP_RCHTSPRSN ADD CONSTRAINT FK_KP_RCHTSPRSN_2 FOREIGN KEY (KADASTRALEMUTATIE_ID) REFERENCES KADASTRALEMUTATIE (KADASTRALEMUTATIE_ID);
-- KADASTRALEMUTATIE (many-to-many junction, Connector_ID: 739)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- unnamed (None to None, Connector_ID: 1540)

ALTER TABLE KADASTRALEMUTATIE ADD CONSTRAINT FK_KADASTRALEMUTATIE_HEEFT_BETREKKING_OP FOREIGN KEY (HEEFT_BETREKKING_OP_ZAKELIJKRECHT_ID) REFERENCES ZAKELIJKRECHT (ZAKELIJKRECHT_ID);
-- HEEFT_BETREKKING_OP (1 to 0..*, Connector_ID: 741)

ALTER TABLE KADASTRALEONROERENDEZAAK ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GERELATEERD FOREIGN KEY (GERELATEERD_KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- GERELATEERD (1 to 0..*, Connector_ID: 181)

ALTER TABLE KADASTRALEONROERENDEZAAKAANTEKENING ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAKAANTEKENING_HEEFT_BETREKKING_OP FOREIGN KEY (HEEFT_BETREKKING_OP_KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- HEEFT_BETREKKING_OP (0..* to 1, Connector_ID: 175)

ALTER TABLE ZAKELIJKRECHT ADD CONSTRAINT FK_ZAKELIJKRECHT_IS_BELAST_MET FOREIGN KEY (IS_BELAST_MET_ZAKELIJKRECHT_ID) REFERENCES ZAKELIJKRECHT (ZAKELIJKRECHT_ID);
-- IS_BELAST_MET (0..1 to 0..*, Connector_ID: 123)

ALTER TABLE ZAKELIJKRECHT ADD CONSTRAINT FK_ZAKELIJKRECHT_RUST_OP FOREIGN KEY (RUST_OP_KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (KADASTRALEONROERENDEZAAK_ID);
-- RUST_OP (1..* to 0..1, Connector_ID: 177)

