CREATE TABLE `CLIENT` (
    `INGESCHREVENPERSOON_ID` INT PRIMARY KEY,
        `CODE` VARCHAR(80),
        `GEZAGSDRAGERGEKEND` BOOLEAN,
        `JURIDISCHESTATUS` VARCHAR(80),
        `WETTELIJKEVERTEGENWOORDIGING` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `GERECHTELIJKE_UITSPRAAK` (
    `GERECHTELIJKE_UITSPRAAK_ID` INT PRIMARY KEY,
        `BASIS_VAN_GEZAGSVERHOUDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `GEZAGSVERHOUDING` (
    `GEZAGSVERHOUDING_ID` INT PRIMARY KEY,
        `BETREFT_INGESCHREVENPERSOON_ID` INT,
        `EINDDATUM` DATE,
        `INDICATIE_CURATELEREGISTER` INT,
        `INDICATIE_GEZAG_MINDERJARIGE` INT,
        `INGANGSDATUM` DATE
) ENGINE=InnoDB;

CREATE TABLE `INGESCHREVENPERSOON` (
    `INGESCHREVENPERSOON_ID` INT PRIMARY KEY,
        `ADRESHERKOMST` VARCHAR(255),
        `ANUMMER` VARCHAR(20),
        `BESCHRIJVINGLOCATIE` VARCHAR(200),
        `BUITENLANDSREISDOCUMENT` VARCHAR(80),
        `BURGERLIJKESTAAT` VARCHAR(255),
        `DATUMBEGINGELDIGHEIDVERBLIJFPLAATS` DATE,
        `DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS` DATE,
        `DATUMINSCHRIJVINGGEMEENTE` DATE,
        `DATUMOPSCHORTINGBIJHOUDING` DATE,
        `DATUMVERTREKUITNEDERLAND` DATE,
        `DATUMVESTIGINGNEDERLAND` DATE,
        `GEMEENTEVANINSCHRIJVING` VARCHAR(80),
        `GEZAGHEBBENDE_GEZAGSVERHOUDING_ID` INT,
        `GEZINSRELATIE` VARCHAR(255),
        `INDICATIEGEHEIM` BOOLEAN,
        `INGEZETENE` BOOLEAN,
        `LANDWAARNAARVERTROKKEN` VARCHAR(255),
        `LANDWAARVANDAANINGESCHREVEN` VARCHAR(255),
        `OUDER1` VARCHAR(255),
        `OUDER2` VARCHAR(255),
        `OUDER_1_INGESCHREVENPERSOON_ID` INT,
        `OUDER_2_INGESCHREVENPERSOON_ID` INT,
        `PARTNERID` VARCHAR(255),
        `REDENEINDEBEWONING` DATE,
        `REDENOPSCHORTINGBIJHOUDING` VARCHAR(200),
        `SIGNALERINGREISDOCUMENT` BOOLEAN,
        `VERBLIJFSTITEL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `NIETNATUURLIJKPERSOON` (
    `NIETNATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `DATUMAANVANG` DATE,
        `DATUMEINDE` DATE,
        `DATUMUITSCHRIJVING` DATE,
        `DATUMVOORTZETTING` DATE,
        `FAXNUMMER` VARCHAR(20),
        `GEZAGHEBBENDE_GEZAGSVERHOUDING_ID` INT,
        `INGESCHREVEN` BOOLEAN,
        `INOPRICHTING` BOOLEAN,
        `KVKNUMMER` VARCHAR(255),
        `NNPID` VARCHAR(255),
        `RECHTSVORM` VARCHAR(255),
        `RSINNUMMER` VARCHAR(255),
        `STATUTAIRENAAM` VARCHAR(255),
        `STATUTAIREZETEL` VARCHAR(255),
        `WEBSITEURL` VARCHAR(200)
) ENGINE=InnoDB;

ALTER TABLE `CLIENT` ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY (`INGESCHREVENPERSOON_ID`) REFERENCES `INGESCHREVENPERSOON` (`INGESCHREVENPERSOON_ID`);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE `GERECHTELIJKE_UITSPRAAK` ADD CONSTRAINT FK_GERECHTELIJKE_UITSPRAAK_BASIS_VAN FOREIGN KEY (`BASIS_VAN_GEZAGSVERHOUDING_ID`) REFERENCES `GEZAGSVERHOUDING` (`GEZAGSVERHOUDING_ID`);
-- BASIS_VAN (0..1 to 0..*, Connector_ID: 935)

ALTER TABLE `GEZAGSVERHOUDING` ADD CONSTRAINT FK_GEZAGSVERHOUDING_BETREFT FOREIGN KEY (`BETREFT_INGESCHREVENPERSOON_ID`) REFERENCES `INGESCHREVENPERSOON` (`INGESCHREVENPERSOON_ID`);
-- BETREFT (0..2 to 1, Connector_ID: 934)

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEZAGHEBBENDE FOREIGN KEY (`GEZAGHEBBENDE_GEZAGSVERHOUDING_ID`) REFERENCES `GEZAGSVERHOUDING` (`GEZAGSVERHOUDING_ID`);
-- GEZAGHEBBENDE (0..1 to 0..*, Connector_ID: 933)

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (`OUDER_1_INGESCHREVENPERSOON_ID`) REFERENCES `INGESCHREVENPERSOON` (`INGESCHREVENPERSOON_ID`);
-- OUDER_1 (None to None, Connector_ID: 170)

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (`OUDER_2_INGESCHREVENPERSOON_ID`) REFERENCES `INGESCHREVENPERSOON` (`INGESCHREVENPERSOON_ID`);
-- OUDER_2 (None to None, Connector_ID: 171)

ALTER TABLE `NIETNATUURLIJKPERSOON` ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_GEZAGHEBBENDE FOREIGN KEY (`GEZAGHEBBENDE_GEZAGSVERHOUDING_ID`) REFERENCES `GEZAGSVERHOUDING` (`GEZAGSVERHOUDING_ID`);
-- GEZAGHEBBENDE (0..1 to 0..*, Connector_ID: 932)

