CREATE TABLE `SOCIALE_GROEP` (
    `SOCIALE_GROEP_ID` INT PRIMARY KEY,
        `EINDDATUM` DATE,
        `NAAM` VARCHAR(80),
        `OMSCHRIJVING` TEXT,
        `STARTDATUM` DATE,
        `TYPERING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `NATUURLIJKPERSOON` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON` VARCHAR(50),
        `AANDUIDINGNAAMGEBRUIK` VARCHAR(50),
        `AANHEFAANSCHRIJVING` VARCHAR(50),
        `ACADEMISCHETITEL` VARCHAR(80),
        `ACHTERNAAM` VARCHAR(100),
        `ADELLIJKETITELOFPREDIKAAT` VARCHAR(255),
        `ANUMMER` VARCHAR(20),
        `ATTRIBUTE` VARCHAR(255),
        `BURGERSERVICENUMMER` VARCHAR(255),
        `DATUMGEBOORTE` DATE,
        `DATUMOVERLIJDEN` DATE,
        `GEBOORTELAND` VARCHAR(255),
        `GEBOORTEPLAATS` VARCHAR(200),
        `GESLACHTSAANDUIDING` VARCHAR(255),
        `GESLACHTSNAAM` VARCHAR(200),
        `GESLACHTSNAAMAANSCHRIJVING` VARCHAR(200),
        `HANDLICHTING` VARCHAR(50),
        `INDICATIEAFSCHERMINGPERSOONSGEGEVENS` BOOLEAN,
        `INDICATIEOVERLEDEN` BOOLEAN,
        `LANDOVERLIJDEN` VARCHAR(255),
        `MAAKT_DEEL_UIT_VAN_SOCIALE_GROEP_ID` INT,
        `NATIONALITEIT` VARCHAR(100),
        `OVERLIJDENSPLAATS` VARCHAR(200),
        `VOORLETTERSAANSCHRIJVING` VARCHAR(20),
        `VOORNAMEN` VARCHAR(200),
        `VOORNAMENAANSCHRIJVING` VARCHAR(200),
        `VOORVOEGSELGESLACHTSNAAM` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `CLIENT` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `CODE` VARCHAR(80),
        `GEZAGSDRAGERGEKEND` BOOLEAN,
        `JURIDISCHESTATUS` VARCHAR(80),
        `WETTELIJKEVERTEGENWOORDIGING` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `INGESCHREVENPERSOON` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `ADRESHERKOMST` VARCHAR(255),
        `ANUMMER` VARCHAR(20),
        `BESCHRIJVINGLOCATIE` VARCHAR(200),
        `BUITENLANDSREISDOCUMENT` VARCHAR(80),
        `BURGERLIJKESTAAT` VARCHAR(255),
        `DATUMBEGINGELDIGHEIDVERBLIJFPLAATS` DATE,
        `DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS` DATE,
        `DATUMINSCHRIJVINGGEMEENTE` DATE,
        `DATUMOPSCHORTINGBIJHOUDING` DATE,
        `DATUMVERTREKUITNEDERLAND` DATE,
        `DATUMVESTIGINGNEDERLAND` DATE,
        `GEMEENTEVANINSCHRIJVING` VARCHAR(80),
        `GEZINSRELATIE` VARCHAR(255),
        `INDICATIEGEHEIM` BOOLEAN,
        `INGEZETENE` BOOLEAN,
        `LANDWAARNAARVERTROKKEN` VARCHAR(255),
        `LANDWAARVANDAANINGESCHREVEN` VARCHAR(255),
        `OUDER1` VARCHAR(255),
        `OUDER2` VARCHAR(255),
        `OUDER_1_INGESCHREVENPERSOON_ID` INT,
        `OUDER_2_INGESCHREVENPERSOON_ID` INT,
        `PARTNERID` VARCHAR(255),
        `REDENEINDEBEWONING` DATE,
        `REDENOPSCHORTINGBIJHOUDING` VARCHAR(200),
        `SIGNALERINGREISDOCUMENT` BOOLEAN,
        `VERBLIJFSTITEL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `SOCIALE_RELATIE` (
    `SOCIALE_RELATIE_ID` INT PRIMARY KEY,
        `EINDDATUM` DATE,
        `HEEFT_NATUURLIJKPERSOON_ID` INT,
        `STARTDATUM` DATE,
        `TYPERING` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `CLIENT` ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY (`NATUURLIJKPERSOON_ID`) REFERENCES `INGESCHREVENPERSOON` (`NATUURLIJKPERSOON_ID`);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY (`NATUURLIJKPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (`OUDER_1_INGESCHREVENPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- OUDER_1 (None to None, Connector_ID: 170)

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (`OUDER_2_INGESCHREVENPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- OUDER_2 (None to None, Connector_ID: 171)

ALTER TABLE `NATUURLIJKPERSOON` ADD CONSTRAINT FK_NATUURLIJKPERSOON_MAAKT_DEEL_UIT_VAN FOREIGN KEY (`MAAKT_DEEL_UIT_VAN_SOCIALE_GROEP_ID`) REFERENCES `SOCIALE_GROEP` (`SOCIALE_GROEP_ID`);
-- MAAKT_DEEL_UIT_VAN (2..* to 0..*, Connector_ID: 920)

ALTER TABLE `SOCIALE_RELATIE` ADD CONSTRAINT FK_SOCIALE_RELATIE_HEEFT FOREIGN KEY (`HEEFT_NATUURLIJKPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- HEEFT (0..* to 2..*, Connector_ID: 919)

