CREATE TABLE HUISHOUDEN (
    HUISHOUDEN_ID VARCHAR2(255) PRIMARY KEY,
        SOORT VARCHAR2(255)
);

CREATE TABLE CLIENT (
    CLIENT_ID VARCHAR2(255) PRIMARY KEY,
        CODE VARCHAR2(80),
        GEZAGSDRAGERGEKEND NUMBER(1),
        JURIDISCHESTATUS VARCHAR2(80),
        MAAKT_ONDERDEEL_UIT_VAN_HUISHOUDEN_ID VARCHAR2(255),
        WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE RELATIESOORT (
    RELATIESOORT_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE RELATIE (
    RELATIE_ID VARCHAR2(255) PRIMARY KEY,
        IS_SOORT_RELATIESOORT_ID VARCHAR2(255),
        RELATIESOORT NUMBER
);

CREATE TABLE KP_CLNT_RLT (
    KP_CLNT_RLT_ID VARCHAR2(255) PRIMARY KEY,
    CLIENT_ID VARCHAR2(255),
    RELATIE_ID VARCHAR2(255)
);

CREATE TABLE KP_RLT_HSHDN (
    KP_RLT_HSHDN_ID VARCHAR2(255) PRIMARY KEY,
    RELATIE_ID VARCHAR2(255),
    HUISHOUDEN_ID VARCHAR2(255)
);

ALTER TABLE KP_CLNT_RLT ADD CONSTRAINT FK_KP_CLNT_RLT_1 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- CLIENT (many-to-many junction, Connector_ID: 954)

ALTER TABLE KP_CLNT_RLT ADD CONSTRAINT FK_KP_CLNT_RLT_2 FOREIGN KEY (RELATIE_ID) REFERENCES RELATIE (RELATIE_ID);
-- RELATIE (many-to-many junction, Connector_ID: 954)

ALTER TABLE KP_RLT_HSHDN ADD CONSTRAINT FK_KP_RLT_HSHDN_1 FOREIGN KEY (RELATIE_ID) REFERENCES RELATIE (RELATIE_ID);
-- RELATIE (many-to-many junction, Connector_ID: 929)

ALTER TABLE KP_RLT_HSHDN ADD CONSTRAINT FK_KP_RLT_HSHDN_2 FOREIGN KEY (HUISHOUDEN_ID) REFERENCES HUISHOUDEN (HUISHOUDEN_ID);
-- HUISHOUDEN (many-to-many junction, Connector_ID: 929)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_MAAKT_ONDERDEEL_UIT_VAN FOREIGN KEY (MAAKT_ONDERDEEL_UIT_VAN_HUISHOUDEN_ID) REFERENCES HUISHOUDEN (HUISHOUDEN_ID);
-- MAAKT_ONDERDEEL_UIT_VAN (0..* to 1, Connector_ID: 949)

ALTER TABLE RELATIE ADD CONSTRAINT FK_RELATIE_IS_SOORT FOREIGN KEY (IS_SOORT_RELATIESOORT_ID) REFERENCES RELATIESOORT (RELATIESOORT_ID);
-- IS_SOORT (0..* to 1, Connector_ID: 922)

