CREATE TABLE APPLICATIE (
    APPLICATIE_ID VARCHAR(255) PRIMARY KEY,
        APPLICATIEURL VARCHAR(255),
        BEHEERSTATUS INTEGER,
        BELEIDSDOMEIN VARCHAR(255),
        BEVAT_GEGEVEN_ID VARCHAR(255),
        CATEGORIE VARCHAR(255),
        GUID VARCHAR(255),
        NAAM VARCHAR(255),
        OMSCHRIJVING TEXT,
        PACKAGINGSTATUS INTEGER
);

CREATE TABLE ATTRIBUUTSOORT (
    ATTRIBUUTSOORT_ID VARCHAR(255) PRIMARY KEY,
        AUTHENTIEK BOOLEAN,
        DATUMOPNAME DATE,
        DEFINITIE TEXT,
        DOMEIN VARCHAR(80),
        EA_GUID VARCHAR(255),
        HEEFT_DATATYPE_ID VARCHAR(255),
        HERKOMST VARCHAR(80),
        HERKOMSTDEFINITIE VARCHAR(80),
        ID INTEGER,
        IDENTIFICEREND BOOLEAN,
        INDICATIEAFLEIDBAAR BOOLEAN,
        INDICATIEMATERIELEHISTORIE BOOLEAN,
        KARDINALITEIT VARCHAR(255),
        LENGTE VARCHAR(255),
        MOGELIJKGEENWAARDE BOOLEAN,
        NAAM VARCHAR(80),
        PATROON VARCHAR(255),
        PRECISIE INTEGER,
        STEREOTYPE VARCHAR(255),
        TOELICHTING TEXT
);

CREATE TABLE CLASSIFICATIE (
    CLASSIFICATIE_ID VARCHAR(255) PRIMARY KEY,
        BEVATPERSOONSGEGEVENS VARCHAR(255),
        GERELATEERDPERSOONSGEGEVENS VARCHAR(255),
        ID VARCHAR(255)
);

CREATE TABLE DATATYPE (
    DATATYPE_ID VARCHAR(255) PRIMARY KEY,
        DATUMOPNAME DATE,
        DEFINITIE TEXT,
        DOMEIN VARCHAR(255),
        EA_GUID VARCHAR(255),
        HERKOMST VARCHAR(255),
        ID INTEGER,
        KARDINALITEIT VARCHAR(255),
        LENGTE VARCHAR(255),
        NAAM VARCHAR(255),
        PATROON VARCHAR(255),
        TOELICHTING TEXT
);

CREATE TABLE EXTERNE_BRON (
    EXTERNE_BRON_ID VARCHAR(255) PRIMARY KEY,
        GUID VARCHAR(255),
        LEVERT_GEGEVEN_ID VARCHAR(255),
        NAAM VARCHAR(255)
);

CREATE TABLE GEGEVEN (
    GEGEVEN_ID VARCHAR(255) PRIMARY KEY,
        ALIAS VARCHAR(255),
        EA_GUID VARCHAR(255),
        GEDEFINIEERD_DOOR_OBJECTTYPE_ID VARCHAR(255),
        ID INTEGER,
        NAAM VARCHAR(255),
        STEREOTYPE VARCHAR(255),
        TOELICHTING TEXT
);

CREATE TABLE GENERALISATIE (
    GENERALISATIE_ID VARCHAR(255) PRIMARY KEY,
        DATUMOPNAME DATE,
        DEFINITIE TEXT,
        EA_GUID VARCHAR(255),
        HERKOMST VARCHAR(255),
        HERKOMSTDEFINITIE VARCHAR(255),
        ID INTEGER,
        INDICATIEMATERIELEHISTORIE BOOLEAN,
        NAAM VARCHAR(255),
        TOELICHTING TEXT
);

CREATE TABLE KP_GGVN_CLSSFCT (
    KP_GGVN_CLSSFCT_ID VARCHAR(255) PRIMARY KEY,
    GEGEVEN_ID VARCHAR(255),
    CLASSIFICATIE_ID VARCHAR(255)
);

CREATE TABLE OBJECTTYPE (
    OBJECTTYPE_ID VARCHAR(255) PRIMARY KEY,
        BEZIT_ATTRIBUUTSOORT_ID VARCHAR(255),
        BEZIT_RELATIESOORT_ID VARCHAR(255),
        DATUMOPNAME DATE,
        DEFINITIE TEXT,
        EA_GUID VARCHAR(255),
        GENERALISATIE_ID VARCHAR(255),
        HERKOMST VARCHAR(255),
        HERKOMSTDEFINITIE VARCHAR(255),
        ID INTEGER,
        INDICATIEABSTRACT BOOLEAN,
        KWALITEIT VARCHAR(255),
        NAAM VARCHAR(255),
        POPULATIE TEXT,
        STEREOTYPE VARCHAR(255),
        TOELICHTING TEXT,
        UNIEKEAANDUIDING VARCHAR(255)
);

CREATE TABLE RELATIESOORT (
    RELATIESOORT_ID VARCHAR(255) PRIMARY KEY,
        AUTHENTIEK BOOLEAN,
        DATUMOPNAME DATE,
        DEFINITIE TEXT,
        EA_GUID VARCHAR(255),
        GERELATEERDOBJECTTYPE_OBJECTTYPE_ID VARCHAR(255),
        HERKOMST VARCHAR(80),
        HERKOMSTDEFINITIE VARCHAR(80),
        ID INTEGER,
        INDICATIEAFLEIDBAAR BOOLEAN,
        INDICATIEMATERIELEHISTORIE BOOLEAN,
        KARDINALITEIT VARCHAR(255),
        MOGELIJKGEENWAARDE BOOLEAN,
        NAAM VARCHAR(80),
        TOELICHTING TEXT,
        UNIDIRECTIONEEL VARCHAR(255)
);

ALTER TABLE KP_GGVN_CLSSFCT ADD CONSTRAINT FK_KP_GGVN_CLSSFCT_1 FOREIGN KEY (GEGEVEN_ID) REFERENCES GEGEVEN (GEGEVEN_ID);
-- GEGEVEN (many-to-many junction, Connector_ID: 639)

ALTER TABLE KP_GGVN_CLSSFCT ADD CONSTRAINT FK_KP_GGVN_CLSSFCT_2 FOREIGN KEY (CLASSIFICATIE_ID) REFERENCES CLASSIFICATIE (CLASSIFICATIE_ID);
-- CLASSIFICATIE (many-to-many junction, Connector_ID: 639)

ALTER TABLE APPLICATIE ADD CONSTRAINT FK_APPLICATIE_BEVAT FOREIGN KEY (BEVAT_GEGEVEN_ID) REFERENCES GEGEVEN (GEGEVEN_ID);
-- BEVAT (0..1 to 0..*, Connector_ID: 645)

ALTER TABLE ATTRIBUUTSOORT ADD CONSTRAINT FK_ATTRIBUUTSOORT_HEEFT FOREIGN KEY (HEEFT_DATATYPE_ID) REFERENCES DATATYPE (DATATYPE_ID);
-- HEEFT (0..* to 0..1, Connector_ID: 641)

ALTER TABLE EXTERNE_BRON ADD CONSTRAINT FK_EXTERNE_BRON_LEVERT FOREIGN KEY (LEVERT_GEGEVEN_ID) REFERENCES GEGEVEN (GEGEVEN_ID);
-- LEVERT (0..1 to 0..*, Connector_ID: 629)

ALTER TABLE GEGEVEN ADD CONSTRAINT FK_GEGEVEN_GEDEFINIEERD_DOOR FOREIGN KEY (GEDEFINIEERD_DOOR_OBJECTTYPE_ID) REFERENCES OBJECTTYPE (OBJECTTYPE_ID);
-- GEDEFINIEERD_DOOR (0..* to 0..1, Connector_ID: 627)

ALTER TABLE OBJECTTYPE ADD CONSTRAINT FK_OBJECTTYPE_BEZIT FOREIGN KEY (BEZIT_RELATIESOORT_ID) REFERENCES RELATIESOORT (RELATIESOORT_ID);
-- BEZIT (1 to 0..*, Connector_ID: 617)

ALTER TABLE OBJECTTYPE ADD CONSTRAINT FK_OBJECTTYPE_BEZIT_2 FOREIGN KEY (BEZIT_ATTRIBUUTSOORT_ID) REFERENCES ATTRIBUUTSOORT (ATTRIBUUTSOORT_ID);
-- BEZIT (0..1 to 0..*, Connector_ID: 640)

ALTER TABLE OBJECTTYPE ADD CONSTRAINT FK_OBJECTTYPE_GENERALISATIE FOREIGN KEY (GENERALISATIE_ID) REFERENCES GENERALISATIE (GENERALISATIE_ID);
-- unnamed (1 to 0..1, Connector_ID: 626)

ALTER TABLE RELATIESOORT ADD CONSTRAINT FK_RELATIESOORT_GERELATEERDOBJECTTYPE FOREIGN KEY (GERELATEERDOBJECTTYPE_OBJECTTYPE_ID) REFERENCES OBJECTTYPE (OBJECTTYPE_ID);
-- GERELATEERDOBJECTTYPE (0..* to 1, Connector_ID: 616)

