CREATE TABLE [DIENSTEN_AANVRAAG] (
    [DIENSTEN_AANVRAAG_ID] INT PRIMARY KEY
);

CREATE TABLE [REDEN_AFWIJKENDE_STARTDATUM] (
    [REDEN_AFWIJKENDE_STARTDATUM_ID] INT PRIMARY KEY,
    [REDENAFWIJKENDESTARTDATUMTYPE] DATE,
    [REDEN_AFWIJKING_AANWEZIG] VARCHAR(255),
    [REDEN_NIET_EERDER_AANVRAGEN] VARCHAR(255)
);

CREATE TABLE [REDEN_AANVRAAG] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [DIENSTTYPE] VARCHAR(255),
    [GEWENSTE_INGANGSDATUM] DATE
);

CREATE TABLE [DIENSTEN_AANVRAAG_LEVENSONDERHOUD] (
    [DIENSTEN_AANVRAAG_ID] INT PRIMARY KEY
);

CREATE TABLE [ANDERE_REDEN_AFWIJKENDE_STARTDATUM] (
    [REDEN_AFWIJKENDE_STARTDATUM_ID] INT PRIMARY KEY,
    [OMSCHRIJVINGBIJZONDEREREDEN] VARCHAR(255)
);

CREATE TABLE [WACHTEN_DIGID] (
    [REDEN_AFWIJKENDE_STARTDATUM_ID] INT PRIMARY KEY,
    [AANVRAAGDATUM_DIGID] DATE
);

CREATE TABLE [WACHTEN_BESLISSING_INSTANTIE] (
    [REDEN_AFWIJKENDE_STARTDATUM_ID] INT PRIMARY KEY,
    [ONTVANGSTDATUM_BESLISSING_INSTANTIE] DATE
);

CREATE TABLE [OPNAME_INSTELLING] (
    [REDEN_AFWIJKENDE_STARTDATUM_ID] INT PRIMARY KEY,
    [EINDDATUM_OPNAME] DATE,
    [STARTDATUM_OPNAME] DATE
);

CREATE TABLE [GESTOPT_BETAALD_WERK] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [AFWIJSREDEN_WW_AANVRAAG] VARCHAR(255),
    [BEDRIJFSADRES] VARCHAR(255),
    [BEDRIJFSTELEFOONNUMMER] VARCHAR(255),
    [CONTRACTPERIODE] VARCHAR(255),
    [LAATSTE_SALARISDATUM] DATE,
    [MINIMAAL_26_WEKEN_VAN_36_GEWERKT] VARCHAR(255),
    [NAAM_BEDRIJF] VARCHAR(255),
    [ONTSLAGBRIEF_ONTVANGEN] VARCHAR(255),
    [ONTSLAGVERGOEDING_ONTVANGEN] VARCHAR(255),
    [REDEN_EINDE_WERK] DATE,
    [SPECIFICATIE_REDEN_EINDE_WERK] DATE,
    [WETTELIJKE_STAPPEN_GEZET] VARCHAR(255),
    [WW_UITKERING_AANGEVRAAGD] VARCHAR(255),
    [ZIEKTEWET_UITKERING_AANGEVRAAGD] VARCHAR(255)
);

CREATE TABLE [GESTOPTE_UITKERING] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [EINDDATUM_UITKERING] DATE,
    [EINDE_UITKERING_IN_BEZWAAR] DATE,
    [GEDEELTELIJK_ARBEIDSONGESCHIKT_NA_50E] VARCHAR(255),
    [INGANGSDATUM_WGA_BINNEN_PERIODE] DATE,
    [IOAW_UITKERING_ONTVANGEN] VARCHAR(255),
    [MINDERDAN35_AO] VARCHAR(255),
    [REDEN_EINDE_UITKERING] DATE,
    [SPECIFICATIE_ANDERE_UITKERING] DATE,
    [SPECIFICATIE_REDEN_EINDE_UITKERING] DATE,
    [STARTDATUM_WW_OF_WGA_UITKERING] DATE,
    [UITKERING] VARCHAR(255),
    [WERKLOOSPERIODE] VARCHAR(255)
);

CREATE TABLE [GESTOPTE_DETENTIE] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [DUUR_DETENTIE] VARCHAR(255),
    [EINDDATUM_DETENTIE] DATE,
    [SOORT_UITKERING_VOOR_DETENTIE] VARCHAR(255),
    [SPECIFICATIE_UITKERING_VOOR_DETENTIE] VARCHAR(255),
    [UITKERING_VOOR_DETENTIE] VARCHAR(255)
);

CREATE TABLE [REDEN_AANVRAAG_LEVENSONDERHOUD] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [ONVOLDOENDE_INKOMEN] VARCHAR(255),
    [REDEN] VARCHAR(255),
    [VERBLIJFSTATUS] VARCHAR(255),
    [WIJZIGING_GEZIN] VARCHAR(255),
    [ZELFSTANDIGE] VARCHAR(255)
);

CREATE TABLE [GESTOPTE_BIJSTANDUITKERING] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [REDEN_EINDE_BIJSTANDSUITKERING] DATE,
    [SITUATIE_GEWIJZIGD] VARCHAR(255),
    [SPECIFICATIE_REDEN_EINDE_BIJSTAND] DATE,
    [SPECIFICATIE_WIJZIGING_SITUATIE] VARCHAR(255)
);

CREATE TABLE [GESTOPTE_STUDIEFINANCIERING] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [EINDDATUM_STUDIEFINANCIERING] DATE,
    [SPECIFICATIE_STUDIEFINANCIERING] DATE
);

CREATE TABLE [KP_DNSTN_ANVRG_RDN_ANVRG] (
    [KP_DNSTN_ANVRG_RDN_ANVRG_ID] INT PRIMARY KEY,
    [DIENSTEN_AANVRAAG_ID] INT,
    [REDEN_AANVRAAG_ID] INT
);

CREATE TABLE [VERTREK_UIT_ASIELZOEKERSCENTRUM] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [BEDRAG_WEEKGELD_COA] DECIMAL(10,2),
    [EINDDATUM_WEEKGELD_COA] DATE,
    [INGANGSDATUM_HUURCONTRACT] DATE,
    [WEEKGELD_COA] VARCHAR(255),
    [WEEKGELD_COA_STOPT] VARCHAR(255)
);

CREATE TABLE [LEVENSSITUATIE_LEVENSSITUATIE] (
    [LEVENSSITUATIE_LEVENSSITUATIE_ID] INT PRIMARY KEY,
    [IS_REDEN_TOT_REDEN_AANVRAAG_ID] INT
);

CREATE TABLE [ANDERE_REDEN_VERZOEK] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [OPGAVE_FINANCIËLE_ONDERSTEUNING] VARCHAR(255),
    [SPECIFICATIE_GELDTEKORT] VARCHAR(255)
);

CREATE TABLE [GESTOPT_OF_VERKOCHT_EIGEN_BEDRIJF] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [DATUM_GESTOPT_MET_EIGEN_BEDRIJF] DATE,
    [KVK_INSCHRIJFNUMMER] DATE,
    [REDEN_EIGEN_BEDRIJFS_GESTOPT] VARCHAR(255),
    [UITGESCHREVEN_BIJ_KAMER_VAN_KOOPHANDEL] VARCHAR(255),
    [VERKOOPBEDRAG] DECIMAL(10,2)
);

CREATE TABLE [OVERLEDEN_PARTNER] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [MEER_DAN_45_ARBEIDSONGESCHIKT] VARCHAR(255),
    [NABESTAANDEUITKERING_AANGEVRAAGD] VARCHAR(255),
    [REDEN_ANW_AFGEWEZEN] VARCHAR(255)
);

CREATE TABLE [GESTOPTE_OF_VERLAAGDE_ALIMENTATIE] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [EINDDATUM_ALIMENTATIE] DATE,
    [LBIO_INGESCHAKELD] VARCHAR(255),
    [NABESTAANDEUITKERING_AANGEVRAAGD] VARCHAR(255),
    [OPGAVE_FINANCIËLE_ONDERSTEUNING] DATE,
    [REDEN_EINDE_OF_VERLAAGDE_ALIMENTATIE] DATE
);

CREATE TABLE [VERBROKEN_RELATIE] (
    [REDEN_AANVRAAG_ID] INT PRIMARY KEY,
    [AFSPRAAK_ONDERHOUDSBIJDRAGE_GEMAAKT] VARCHAR(255),
    [DATUM_RELATIE_VERBROKEN] DATE,
    [GEREGISTREERDE_PARTNER] VARCHAR(255),
    [OPGAVE_FINANCIËLE_ONDERSTEUNING] VARCHAR(255)
);

CREATE TABLE [INGANG_BIJSTANDSUITKERING] (
    [INGANG_BIJSTANDSUITKERING_ID] INT PRIMARY KEY,
    [AFWIJKENDE_INGANGSDATUM] DATE,
    [BEVAT_DIENSTEN_AANVRAAG_LEVENSONDERHOUD_ID] INT,
    [BEVAT_REDEN_AFWIJKENDE_STARTDATUM_ID] INT,
    [DATUM_MELDING_BIJ_GEMEENTE] DATE,
    [GEWENSTE_STARTDATUM_UITKERING] DATE,
    [NA_MELDING_GEMEENTE_DIGITAAL_VERWEZEN] VARCHAR(255)
);

ALTER TABLE [ANDERE_REDEN_AFWIJKENDE_STARTDATUM] ADD CONSTRAINT FK_ANDERE_REDEN_AFWIJKENDE_STARTDATUM_GEN_REDEN_AFWIJKENDE_STARTDATUM FOREIGN KEY ([REDEN_AFWIJKENDE_STARTDATUM_ID]) REFERENCES [REDEN_AFWIJKENDE_STARTDATUM] ([REDEN_AFWIJKENDE_STARTDATUM_ID]);
-- Generalization to REDEN_AFWIJKENDE_STARTDATUM

ALTER TABLE [ANDERE_REDEN_VERZOEK] ADD CONSTRAINT FK_ANDERE_REDEN_VERZOEK_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [DIENSTEN_AANVRAAG_LEVENSONDERHOUD] ADD CONSTRAINT FK_DIENSTEN_AANVRAAG_LEVENSONDERHOUD_GEN_DIENSTEN_AANVRAAG FOREIGN KEY ([DIENSTEN_AANVRAAG_ID]) REFERENCES [DIENSTEN_AANVRAAG] ([DIENSTEN_AANVRAAG_ID]);
-- Generalization to DIENSTEN_AANVRAAG

ALTER TABLE [GESTOPT_BETAALD_WERK] ADD CONSTRAINT FK_GESTOPT_BETAALD_WERK_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [GESTOPT_OF_VERKOCHT_EIGEN_BEDRIJF] ADD CONSTRAINT FK_GESTOPT_OF_VERKOCHT_EIGEN_BEDRIJF_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [GESTOPTE_BIJSTANDUITKERING] ADD CONSTRAINT FK_GESTOPTE_BIJSTANDUITKERING_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [GESTOPTE_DETENTIE] ADD CONSTRAINT FK_GESTOPTE_DETENTIE_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [GESTOPTE_OF_VERLAAGDE_ALIMENTATIE] ADD CONSTRAINT FK_GESTOPTE_OF_VERLAAGDE_ALIMENTATIE_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [GESTOPTE_STUDIEFINANCIERING] ADD CONSTRAINT FK_GESTOPTE_STUDIEFINANCIERING_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [GESTOPTE_UITKERING] ADD CONSTRAINT FK_GESTOPTE_UITKERING_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [OPNAME_INSTELLING] ADD CONSTRAINT FK_OPNAME_INSTELLING_GEN_REDEN_AFWIJKENDE_STARTDATUM FOREIGN KEY ([REDEN_AFWIJKENDE_STARTDATUM_ID]) REFERENCES [REDEN_AFWIJKENDE_STARTDATUM] ([REDEN_AFWIJKENDE_STARTDATUM_ID]);
-- Generalization to REDEN_AFWIJKENDE_STARTDATUM

ALTER TABLE [OVERLEDEN_PARTNER] ADD CONSTRAINT FK_OVERLEDEN_PARTNER_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [REDEN_AANVRAAG_LEVENSONDERHOUD] ADD CONSTRAINT FK_REDEN_AANVRAAG_LEVENSONDERHOUD_GEN_REDEN_AANVRAAG FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG

ALTER TABLE [VERBROKEN_RELATIE] ADD CONSTRAINT FK_VERBROKEN_RELATIE_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [VERTREK_UIT_ASIELZOEKERSCENTRUM] ADD CONSTRAINT FK_VERTREK_UIT_ASIELZOEKERSCENTRUM_GEN_REDEN_AANVRAAG_LEVENSONDERHOUD FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG_LEVENSONDERHOUD] ([REDEN_AANVRAAG_ID]);
-- Generalization to REDEN_AANVRAAG_LEVENSONDERHOUD

ALTER TABLE [WACHTEN_BESLISSING_INSTANTIE] ADD CONSTRAINT FK_WACHTEN_BESLISSING_INSTANTIE_GEN_REDEN_AFWIJKENDE_STARTDATUM FOREIGN KEY ([REDEN_AFWIJKENDE_STARTDATUM_ID]) REFERENCES [REDEN_AFWIJKENDE_STARTDATUM] ([REDEN_AFWIJKENDE_STARTDATUM_ID]);
-- Generalization to REDEN_AFWIJKENDE_STARTDATUM

ALTER TABLE [WACHTEN_DIGID] ADD CONSTRAINT FK_WACHTEN_DIGID_GEN_REDEN_AFWIJKENDE_STARTDATUM FOREIGN KEY ([REDEN_AFWIJKENDE_STARTDATUM_ID]) REFERENCES [REDEN_AFWIJKENDE_STARTDATUM] ([REDEN_AFWIJKENDE_STARTDATUM_ID]);
-- Generalization to REDEN_AFWIJKENDE_STARTDATUM

ALTER TABLE [KP_DNSTN_ANVRG_RDN_ANVRG] ADD CONSTRAINT FK_KP_DNSTN_ANVRG_RDN_ANVRG_1 FOREIGN KEY ([DIENSTEN_AANVRAAG_ID]) REFERENCES [DIENSTEN_AANVRAAG] ([DIENSTEN_AANVRAAG_ID]);
-- DIENSTEN_AANVRAAG (many-to-many junction, Connector_ID: 1692)

ALTER TABLE [KP_DNSTN_ANVRG_RDN_ANVRG] ADD CONSTRAINT FK_KP_DNSTN_ANVRG_RDN_ANVRG_2 FOREIGN KEY ([REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG] ([REDEN_AANVRAAG_ID]);
-- REDEN_AANVRAAG (many-to-many junction, Connector_ID: 1692)

ALTER TABLE [LEVENSSITUATIE_LEVENSSITUATIE] ADD CONSTRAINT FK_LEVENSSITUATIE_LEVENSSITUATIE_IS_REDEN_TOT FOREIGN KEY ([IS_REDEN_TOT_REDEN_AANVRAAG_ID]) REFERENCES [REDEN_AANVRAAG] ([REDEN_AANVRAAG_ID]);
-- IS_REDEN_TOT (0..1 to 0..*, Connector_ID: 1681)

ALTER TABLE [INGANG_BIJSTANDSUITKERING] ADD CONSTRAINT FK_INGANG_BIJSTANDSUITKERING_BEVAT FOREIGN KEY ([BEVAT_REDEN_AFWIJKENDE_STARTDATUM_ID]) REFERENCES [REDEN_AFWIJKENDE_STARTDATUM] ([REDEN_AFWIJKENDE_STARTDATUM_ID]);
-- BEVAT (0..1 to 0..1, Connector_ID: 1682)

ALTER TABLE [INGANG_BIJSTANDSUITKERING] ADD CONSTRAINT FK_INGANG_BIJSTANDSUITKERING_BEVAT_2 FOREIGN KEY ([BEVAT_DIENSTEN_AANVRAAG_LEVENSONDERHOUD_ID]) REFERENCES [DIENSTEN_AANVRAAG] ([DIENSTEN_AANVRAAG_ID]);
-- BEVAT (0..* to 1, Connector_ID: 1690)

