CREATE TABLE ASIELSTATUSHOUDER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DIGID_AANGEVRAAGD_ENUM_ID VARCHAR2(255),
        EMAILADRES_VERBLIJF_AZC VARCHAR2(255),
        IS_GEKOPPELD_AAN VARCHAR2(255),
        LAND_RIJBEWIJS VARCHAR2(50),
        RIJBEWIJS_ENUM_ID VARCHAR2(255),
        TELEFOONNUMMER_VERBLIJF_AZC VARCHAR2(255)
);

CREATE TABLE BOOLEAN_ENUM (
    BOOLEAN_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE CLIENT (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        CODE VARCHAR2(80),
        GEZAGSDRAGERGEKEND_ENUM_ID VARCHAR2(255),
        JURIDISCHESTATUS VARCHAR2(80),
        WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE CLIENTBEGELEIDER (
    MEDEWERKER_ID VARCHAR2(255) PRIMARY KEY,
        BEGELEIDERSCODE VARCHAR2(20),
        MAAKT_ONDERDEEL_UIT_VAN_TEAM_ID VARCHAR2(255)
);

CREATE TABLE DOELGROEP_ENUM (
    DOELGROEP_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO DOELGROEP_ENUM (DOELGROEP_ENUM_ID, VALUE) VALUES
    (1, 'ASIELSTATUSHOUDER'),
    (2, 'GEESTELIJK_BEDIENAAR'),
    (3, 'GEZINSHERENIGER'),
    (4, 'GEZINSHERENIGER_MET_ASIELSTATUSHOUDER'),
    (5, 'GEZINSVORMER'),
    (6, 'GEZINSVORMER_MET_ASIELSTATUSHOUDER'),
    (7, 'OVERIG');

CREATE TABLE GEZINSMIGRANT_EN_OVERIGE_MIGRANT_ (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE INBURGERAAR (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DOELGROEP NUMBER,
        GEDETAILLEERDE_DOELGROEP_ENUM_ID VARCHAR2(255)
);

CREATE TABLE INGESCHREVENPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESHERKOMST VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        BESCHRIJVINGLOCATIE VARCHAR2(200),
        BUITENLANDSREISDOCUMENT VARCHAR2(80),
        BURGERLIJKESTAAT VARCHAR2(255),
        DATUMBEGINGELDIGHEIDVERBLIJFPLAATS DATE,
        DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS DATE,
        DATUMINSCHRIJVINGGEMEENTE DATE,
        DATUMOPSCHORTINGBIJHOUDING DATE,
        DATUMVERTREKUITNEDERLAND DATE,
        DATUMVESTIGINGNEDERLAND DATE,
        GEMEENTEVANINSCHRIJVING VARCHAR2(80),
        GEZINSRELATIE VARCHAR2(255),
        INDICATIEGEHEIM_ENUM_ID VARCHAR2(255),
        INGEZETENE_ENUM_ID VARCHAR2(255),
        LANDWAARNAARVERTROKKEN VARCHAR2(255),
        LANDWAARVANDAANINGESCHREVEN VARCHAR2(255),
        OUDER1 VARCHAR2(255),
        OUDER2 VARCHAR2(255),
        OUDER_1_INGESCHREVENPERSOON_ID VARCHAR2(255),
        OUDER_2_INGESCHREVENPERSOON_ID VARCHAR2(255),
        PARTNERID VARCHAR2(255),
        REDENEINDEBEWONING DATE,
        REDENOPSCHORTINGBIJHOUDING VARCHAR2(200),
        SIGNALERINGREISDOCUMENT_ENUM_ID VARCHAR2(255),
        VERBLIJFSTITEL VARCHAR2(255)
);

CREATE TABLE KP_CLNT (
    KP_CLNT_ID VARCHAR2(255) PRIMARY KEY,
    CLIENT_ID VARCHAR2(255),
    RELATIE_ID VARCHAR2(255)
);

CREATE TABLE KP_CLNTBGLDR (
    KP_CLNTBGLDR_ID VARCHAR2(255) PRIMARY KEY,
    CLIENTBEGELEIDER_ID VARCHAR2(255),
    CLIENT_ID VARCHAR2(255)
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        AGBCODE VARCHAR2(255),
        LEVERANCIERSCODE VARCHAR2(255),
        NAAM VARCHAR2(200),
        SOORTLEVERANCIER VARCHAR2(80),
        SOORTLEVERANCIERCODE VARCHAR2(255)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID VARCHAR2(255) PRIMARY KEY,
        ACHTERNAAM VARCHAR2(200),
        DATUMINDIENST DATE,
        DATUMUITDIENST DATE,
        EMAILADRES VARCHAR2(255),
        EXTERN VARCHAR2(255),
        FUNCTIE VARCHAR2(50),
        GESLACHTSAANDUIDING VARCHAR2(255),
        MEDEWERKERIDENTIFICATIE VARCHAR2(255),
        MEDEWERKERTOELICHTING VARCHAR2(255),
        ROEPNAAM VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20),
        VOORLETTERS VARCHAR2(20),
        VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE NATUURLIJKPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON VARCHAR2(50),
        AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
        AANHEFAANSCHRIJVING VARCHAR2(50),
        ACADEMISCHETITEL VARCHAR2(80),
        ACHTERNAAM VARCHAR2(100),
        ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        ATTRIBUTE VARCHAR2(255),
        BURGERSERVICENUMMER VARCHAR2(255),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        GEBOORTELAND VARCHAR2(255),
        GEBOORTEPLAATS VARCHAR2(200),
        GESLACHTSAANDUIDING VARCHAR2(255),
        GESLACHTSNAAM VARCHAR2(200),
        GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
        HANDLICHTING VARCHAR2(50),
        INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID VARCHAR2(255),
        INDICATIEOVERLEDEN_ENUM_ID VARCHAR2(255),
        LANDOVERLIJDEN VARCHAR2(255),
        NATIONALITEIT VARCHAR2(100),
        OVERLIJDENSPLAATS VARCHAR2(200),
        VOORLETTERSAANSCHRIJVING VARCHAR2(20),
        VOORNAMEN VARCHAR2(200),
        VOORNAMENAANSCHRIJVING VARCHAR2(200),
        VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        ADRESCORRESPONDENTIE VARCHAR2(100),
        EMAILADRES VARCHAR2(80),
        FAXNUMMER VARCHAR2(20),
        IDENTIFICATIE VARCHAR2(255),
        KVKNUMMER VARCHAR2(20),
        NAAM VARCHAR2(200),
        RECHTSVORM VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE RELATIE (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        RELATIESOORT NUMBER
);

CREATE TABLE TEAM (
    TEAM_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE VREEMDELING (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        SOCIAAL_REFERENT VARCHAR2(255),
        V_NUMMER VARCHAR2(255)
);

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_GEN_INBURGERAAR FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES INBURGERAAR (RECHTSPERSOON_ID);
-- Generalization to INBURGERAAR

ALTER TABLE GEZINSMIGRANT_EN_OVERIGE_MIGRANT_ ADD CONSTRAINT FK_GEZINSMIGRANT_EN_OVERIGE_MIGRANT__GEN_INBURGERAAR FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES INBURGERAAR (RECHTSPERSOON_ID);
-- Generalization to INBURGERAAR

ALTER TABLE INBURGERAAR ADD CONSTRAINT FK_INBURGERAAR_GEN_VREEMDELING FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES VREEMDELING (RECHTSPERSOON_ID);
-- Generalization to VREEMDELING

ALTER TABLE VREEMDELING ADD CONSTRAINT FK_VREEMDELING_GEN_NATUURLIJKPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES INGESCHREVENPERSOON (RECHTSPERSOON_ID);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE CLIENTBEGELEIDER ADD CONSTRAINT FK_CLIENTBEGELEIDER_GEN_MEDEWERKER FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- Generalization to MEDEWERKER

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE RELATIE ADD CONSTRAINT FK_RELATIE_GEN_NATUURLIJKPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_CLNT ADD CONSTRAINT FK_KP_CLNT_1 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (RECHTSPERSOON_ID);
-- CLIENT (many-to-many junction, Connector_ID: 954)

ALTER TABLE KP_CLNT ADD CONSTRAINT FK_KP_CLNT_2 FOREIGN KEY (RELATIE_ID) REFERENCES RELATIE (RECHTSPERSOON_ID);
-- RELATIE (many-to-many junction, Connector_ID: 954)

ALTER TABLE KP_CLNTBGLDR ADD CONSTRAINT FK_KP_CLNTBGLDR_1 FOREIGN KEY (CLIENTBEGELEIDER_ID) REFERENCES CLIENTBEGELEIDER (MEDEWERKER_ID);
-- CLIENTBEGELEIDER (many-to-many junction, Connector_ID: 941)

ALTER TABLE KP_CLNTBGLDR ADD CONSTRAINT FK_KP_CLNTBGLDR_2 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (RECHTSPERSOON_ID);
-- CLIENT (many-to-many junction, Connector_ID: 941)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_DIGID_AANGEVRAAGD_ENUM_ID FOREIGN KEY (DIGID_AANGEVRAAGD_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- DIGID_AANGEVRAAGD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_RIJBEWIJS_ENUM_ID FOREIGN KEY (RIJBEWIJS_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- RIJBEWIJS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_GEZAGSDRAGERGEKEND_ENUM_ID FOREIGN KEY (GEZAGSDRAGERGEKEND_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GEZAGSDRAGERGEKEND_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE CLIENTBEGELEIDER ADD CONSTRAINT FK_CLIENTBEGELEIDER_MAAKT_ONDERDEEL_UIT_VAN FOREIGN KEY (MAAKT_ONDERDEEL_UIT_VAN_TEAM_ID) REFERENCES TEAM (TEAM_ID);
-- MAAKT_ONDERDEEL_UIT_VAN (0..* to 1, Connector_ID: 1039)

ALTER TABLE INBURGERAAR ADD CONSTRAINT FK_INBURGERAAR_GEDETAILLEERDE_DOELGROEP_ENUM_ID FOREIGN KEY (GEDETAILLEERDE_DOELGROEP_ENUM_ID) REFERENCES DOELGROEP_ENUM (DOELGROEP_ENUM_ID);
-- GEDETAILLEERDE_DOELGROEP_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_INDICATIEGEHEIM_ENUM_ID FOREIGN KEY (INDICATIEGEHEIM_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEGEHEIM_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_INGEZETENE_ENUM_ID FOREIGN KEY (INGEZETENE_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INGEZETENE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (OUDER_1_INGESCHREVENPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- OUDER_1 (None to None, Connector_ID: 170)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (OUDER_2_INGESCHREVENPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- OUDER_2 (None to None, Connector_ID: 171)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_SIGNALERINGREISDOCUMENT_ENUM_ID FOREIGN KEY (SIGNALERINGREISDOCUMENT_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- SIGNALERINGREISDOCUMENT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID FOREIGN KEY (INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEOVERLEDEN_ENUM_ID FOREIGN KEY (INDICATIEOVERLEDEN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEOVERLEDEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

