CREATE TABLE FUNCTIEHUIS (
    FUNCTIEHUIS_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(80),
    OMSCHRIJVING CLOB
);

CREATE TABLE ORGANISATORISCHEEENHEID (
    ORGANISATORISCHEEENHEID_ID NUMBER PRIMARY KEY,
    DATUMONTSTAAN DATE,
    DATUMOPHEFFING DATE,
    EMAILADRES VARCHAR2(255),
    FAXNUMMER VARCHAR2(20),
    FORMATIE VARCHAR2(255),
    IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID NUMBER,
    NAAM VARCHAR2(50),
    NAAMVERKORT VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(80),
    ORGANISATIEIDENTIFICATIE VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    TOELICHTING VARCHAR2(255)
);

CREATE TABLE NORMPROFIEL (
    NORMPROFIEL_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(100),
    ONDERDEEL_VAN_FUNCTIEHUIS_ID NUMBER,
    SCHAAL VARCHAR2(255)
);

CREATE TABLE ORGANISATORISCHEEENHEIDHR (
    ORGANISATORISCHEEENHEID_ID NUMBER PRIMARY KEY,
    NAAM NUMBER,
    TYPE NUMBER
);

CREATE TABLE FUNCTIE (
    FUNCTIE_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(50),
    GEBASEERD_OP_NORMPROFIEL_ID NUMBER,
    NAAM VARCHAR2(80),
    OMSCHRIJVING CLOB,
    SCHAAL VARCHAR2(20),
    TAKEN CLOB
);

CREATE TABLE FORMATIEPLAATS (
    FORMATIEPLAATS_ID NUMBER PRIMARY KEY,
    ONDERDEEL_VAN_ORGANISATORISCHEEENHEIDHR_ID NUMBER,
    UREN_PER_WEEK VARCHAR2(100)
);

CREATE TABLE ROL (
    ROL_ID NUMBER PRIMARY KEY,
    DATUMBEGIN DATE,
    DATUMEINDE DATE,
    HOORT_BIJ_ORGANISATORISCHEEENHEIDHR_ID NUMBER,
    OMSCHRIJVING VARCHAR2(50)
);

CREATE TABLE DIENSTVERBAND (
    DIENSTVERBAND_ID NUMBER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DIENSTVERBAND_CONFORM_FUNCTIE_FUNCTIE_ID NUMBER,
    PERIODIEK NUMBER,
    SALARIS VARCHAR2(255),
    SCHAAL NUMBER,
    URENPERWEEK NUMBER
);

CREATE TABLE KP_FRMTPLTS_FNCT (
    KP_FRMTPLTS_FNCT_ID NUMBER PRIMARY KEY,
    FORMATIEPLAATS_ID NUMBER,
    FUNCTIE_ID NUMBER
);

CREATE TABLE KP_DNSTVRBND_ORGNSTRSCHNHDHR (
    KP_DNSTVRBND_ORGNSTRSCHNHDHR_ID NUMBER PRIMARY KEY,
    DIENSTVERBAND_ID NUMBER,
    ORGANISATORISCHEEENHEIDHR_ID NUMBER
);

CREATE TABLE WERKNEMER (
    WERKNEMER_ID NUMBER PRIMARY KEY,
    GEBOORTEDATUM DATE,
    MEDEWERKER_HEEFT_DIENSTVERBAND_DIENSTVERBAND_ID NUMBER,
    NAAM VARCHAR2(80),
    VOORNAAM VARCHAR2(255),
    WOONPLAATS VARCHAR2(50)
);

CREATE TABLE INZET (
    INZET_ID NUMBER PRIMARY KEY,
    AANTAL_VOLGENS_INZET_DIENSTVERBAND_ID NUMBER,
    DATUMBEGIN DATE,
    DATUMEINDE DATE,
    INZET_BIJ_ORGANISATORISCHEEENHEIDHR_ID NUMBER,
    INZET_VOOR_FUNCTIE_FUNCTIE_ID NUMBER,
    PERCENTAGE VARCHAR2(20),
    UREN VARCHAR2(20)
);

CREATE TABLE KP_FRMTPLTS_DNSTVRBND (
    KP_FRMTPLTS_DNSTVRBND_ID NUMBER PRIMARY KEY,
    FORMATIEPLAATS_ID NUMBER,
    DIENSTVERBAND_ID NUMBER
);

CREATE TABLE KP_WRKNMR_ROL (
    KP_WRKNMR_ROL_ID NUMBER PRIMARY KEY,
    WERKNEMER_ID NUMBER,
    ROL_ID NUMBER
);

ALTER TABLE ORGANISATORISCHEEENHEIDHR ADD CONSTRAINT FK_ORGANISATORISCHEEENHEIDHR_GEN_ORGANISATORISCHEEENHEID FOREIGN KEY (ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- Generalization to ORGANISATORISCHEEENHEID

ALTER TABLE KP_WRKNMR_ROL ADD CONSTRAINT FK_KP_WRKNMR_ROL_1 FOREIGN KEY (WERKNEMER_ID) REFERENCES WERKNEMER (WERKNEMER_ID);
-- WERKNEMER (many-to-many junction, Connector_ID: 443)

ALTER TABLE KP_WRKNMR_ROL ADD CONSTRAINT FK_KP_WRKNMR_ROL_2 FOREIGN KEY (ROL_ID) REFERENCES ROL (ROL_ID);
-- ROL (many-to-many junction, Connector_ID: 443)

ALTER TABLE KP_FRMTPLTS_FNCT ADD CONSTRAINT FK_KP_FRMTPLTS_FNCT_1 FOREIGN KEY (FORMATIEPLAATS_ID) REFERENCES FORMATIEPLAATS (FORMATIEPLAATS_ID);
-- FORMATIEPLAATS (many-to-many junction, Connector_ID: 462)

ALTER TABLE KP_FRMTPLTS_FNCT ADD CONSTRAINT FK_KP_FRMTPLTS_FNCT_2 FOREIGN KEY (FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- FUNCTIE (many-to-many junction, Connector_ID: 462)

ALTER TABLE KP_FRMTPLTS_DNSTVRBND ADD CONSTRAINT FK_KP_FRMTPLTS_DNSTVRBND_1 FOREIGN KEY (FORMATIEPLAATS_ID) REFERENCES FORMATIEPLAATS (FORMATIEPLAATS_ID);
-- FORMATIEPLAATS (many-to-many junction, Connector_ID: 466)

ALTER TABLE KP_FRMTPLTS_DNSTVRBND ADD CONSTRAINT FK_KP_FRMTPLTS_DNSTVRBND_2 FOREIGN KEY (DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- DIENSTVERBAND (many-to-many junction, Connector_ID: 466)

ALTER TABLE KP_DNSTVRBND_ORGNSTRSCHNHDHR ADD CONSTRAINT FK_KP_DNSTVRBND_ORGNSTRSCHNHDHR_1 FOREIGN KEY (DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- DIENSTVERBAND (many-to-many junction, Connector_ID: 472)

ALTER TABLE KP_DNSTVRBND_ORGNSTRSCHNHDHR ADD CONSTRAINT FK_KP_DNSTVRBND_ORGNSTRSCHNHDHR_2 FOREIGN KEY (ORGANISATORISCHEEENHEIDHR_ID) REFERENCES ORGANISATORISCHEEENHEIDHR (ORGANISATORISCHEEENHEID_ID);
-- ORGANISATORISCHEEENHEIDHR (many-to-many junction, Connector_ID: 472)

ALTER TABLE ROL ADD CONSTRAINT FK_ROL_HOORT_BIJ FOREIGN KEY (HOORT_BIJ_ORGANISATORISCHEEENHEIDHR_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- HOORT_BIJ (0..* to 0..1, Connector_ID: 447)

ALTER TABLE INZET ADD CONSTRAINT FK_INZET_INZET_BIJ FOREIGN KEY (INZET_BIJ_ORGANISATORISCHEEENHEIDHR_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- INZET_BIJ (0..* to 1, Connector_ID: 452)

ALTER TABLE NORMPROFIEL ADD CONSTRAINT FK_NORMPROFIEL_ONDERDEEL_VAN FOREIGN KEY (ONDERDEEL_VAN_FUNCTIEHUIS_ID) REFERENCES FUNCTIEHUIS (FUNCTIEHUIS_ID);
-- ONDERDEEL_VAN (1..* to 1, Connector_ID: 458)

ALTER TABLE INZET ADD CONSTRAINT FK_INZET_INZET_VOOR_FUNCTIE FOREIGN KEY (INZET_VOOR_FUNCTIE_FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- INZET_VOOR_FUNCTIE (1 to 1, Connector_ID: 459)

ALTER TABLE FUNCTIE ADD CONSTRAINT FK_FUNCTIE_GEBASEERD_OP FOREIGN KEY (GEBASEERD_OP_NORMPROFIEL_ID) REFERENCES NORMPROFIEL (NORMPROFIEL_ID);
-- GEBASEERD_OP (1 to 1, Connector_ID: 461)

ALTER TABLE FORMATIEPLAATS ADD CONSTRAINT FK_FORMATIEPLAATS_ONDERDEEL_VAN FOREIGN KEY (ONDERDEEL_VAN_ORGANISATORISCHEEENHEIDHR_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- ONDERDEEL_VAN (1 to 0..1, Connector_ID: 463)

ALTER TABLE INZET ADD CONSTRAINT FK_INZET_AANTAL_VOLGENS_INZET FOREIGN KEY (AANTAL_VOLGENS_INZET_DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- AANTAL_VOLGENS_INZET (1 to 0..*, Connector_ID: 467)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_MEDEWERKER_HEEFT_DIENSTVERBAND FOREIGN KEY (MEDEWERKER_HEEFT_DIENSTVERBAND_DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- MEDEWERKER_HEEFT_DIENSTVERBAND (1 to 1..*, Connector_ID: 468)

ALTER TABLE DIENSTVERBAND ADD CONSTRAINT FK_DIENSTVERBAND_DIENSTVERBAND_CONFORM_FUNCTIE FOREIGN KEY (DIENSTVERBAND_CONFORM_FUNCTIE_FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- DIENSTVERBAND_CONFORM_FUNCTIE (0..* to 1, Connector_ID: 471)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_DEEL_VAN FOREIGN KEY (IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_DEEL_VAN (1 to 0..1, Connector_ID: 2059)

