CREATE TABLE FUNCTIEHUIS (
    FUNCTIEHUIS_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE KEUZEBUDGETBESTEDING (
    KEUZEBUDGETBESTEDING_ID INTEGER PRIMARY KEY,
    BEDRAG DECIMAL(10,2),
    DATUM DATE,
    SOORT_BESTEDING_KEUZEBUDGETBESTEDINGSOORT_ID INTEGER
);

CREATE TABLE VERZUIM (
    VERZUIM_ID INTEGER PRIMARY KEY,
    DATUMTIJDEINDE TIMESTAMP,
    DATUMTIJDSTART TIMESTAMP,
    SOORT_VERZUIM_VERZUIMSOORT_ID INTEGER
);

CREATE TABLE KP_OPLDNG_ONDRWJSNSTTT (
    KP_OPLDNG_ONDRWJSNSTTT_ID INTEGER PRIMARY KEY,
    OPLEIDING_ID INTEGER,
    ONDERWIJSINSTITUUT_ID INTEGER
);

CREATE TABLE ORGANISATORISCHEEENHEIDHR (
    ORGANISATORISCHEEENHEID_ID INTEGER PRIMARY KEY,
    NAAM INTEGER,
    TYPE INTEGER
);

CREATE TABLE DISCIPLINAIRE_MAATREGEL (
    DISCIPLINAIRE_MAATREGEL_ID INTEGER PRIMARY KEY,
    DATUMGECONSTATEERD DATE,
    DATUMOPGELEGD DATE,
    OMSCHRIJVING TEXT,
    REDEN TEXT,
    SOORT_MAATREGEL_SOORTDISCIPLINAIREMAATREGEL_ID INTEGER
);

CREATE TABLE VERLOFSOORT (
    VERLOFSOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE OPLEIDING (
    OPLEIDING_ID INTEGER PRIMARY KEY,
    INSTITUUT VARCHAR(80),
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT,
    PRIJS DECIMAL(10,2)
);

CREATE TABLE WERKNEMER (
    WERKNEMER_ID INTEGER PRIMARY KEY,
    BEOORDEELD_DOOR_BEOORDELING_ID INTEGER,
    BEOORDELING_VAN_BEOORDELING_ID INTEGER,
    DIENT_IN_DECLARATIE_ID INTEGER,
    GEBOORTEDATUM DATE,
    HEEFT_GENOTEN_GENOTENOPLEIDING_ID INTEGER,
    HEEFT_MAATREGEL_DISCIPLINAIRE_MAATREGEL_ID INTEGER,
    HEEFT_ONDERGAAN_GEWELDSINCIDENT_ID INTEGER,
    HEEFT_VERLOF_VERLOF_ID INTEGER,
    HEEFT_VERZUIM_VERZUIM_ID INTEGER,
    IS_PARTNER_VAN_RELATIE_ID INTEGER,
    MEDEWERKER_HEEFT_DIENSTVERBAND_DIENSTVERBAND_ID INTEGER,
    NAAM VARCHAR(80),
    VOORNAAM VARCHAR(255),
    WOONPLAATS VARCHAR(50)
);

CREATE TABLE DECLARATIE (
    DECLARATIE_ID INTEGER PRIMARY KEY,
    BEDRAG DECIMAL(10,2),
    BETREFT VARCHAR(80),
    DATUMDECLARATIE DATE,
    DATUMINDIENING DATE,
    OMSCHRIJVING TEXT,
    SOORT_DECLARATIE_DECLARATIESOORT_ID INTEGER
);

CREATE TABLE FORMATIEPLAATS (
    FORMATIEPLAATS_ID INTEGER PRIMARY KEY,
    ONDERDEEL_VAN_ORGANISATORISCHEEENHEIDHR_ID INTEGER,
    UREN_PER_WEEK VARCHAR(100)
);

CREATE TABLE KP_DNSTVRBND_ORGNSTRSCHNHDHR (
    KP_DNSTVRBND_ORGNSTRSCHNHDHR_ID INTEGER PRIMARY KEY,
    DIENSTVERBAND_ID INTEGER,
    ORGANISATORISCHEEENHEIDHR_ID INTEGER
);

CREATE TABLE VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (
    VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID INTEGER PRIMARY KEY
);

CREATE TABLE KEUZEBUDGETBESTEDINGSOORT (
    KEUZEBUDGETBESTEDINGSOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE VERLOF (
    VERLOF_ID INTEGER PRIMARY KEY,
    DATUMAANVRAAG DATE,
    DATUMTIJDEINDE TIMESTAMP,
    DATUMTIJDSTART TIMESTAMP,
    DATUMTOEKENNING DATE,
    GOEDGEKEURD BOOLEAN,
    SOORT_VERLOF_VERLOFSOORT_ID INTEGER
);

CREATE TABLE KP_DNSTVRBND_VSTGNGVNZKBHNDLNDRGNST (
    KP_DNSTVRBND_VSTGNGVNZKBHNDLNDRGNST_ID INTEGER PRIMARY KEY,
    DIENSTVERBAND_ID INTEGER,
    VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID INTEGER
);

CREATE TABLE KP_FRMTPLTS_FNCT (
    KP_FRMTPLTS_FNCT_ID INTEGER PRIMARY KEY,
    FORMATIEPLAATS_ID INTEGER,
    FUNCTIE_ID INTEGER
);

CREATE TABLE VERZUIMSOORT (
    VERZUIMSOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE BEOORDELING (
    BEOORDELING_ID INTEGER PRIMARY KEY,
    DATUM DATE,
    OMSCHRIJVING TEXT,
    OORDEEL VARCHAR(80)
);

CREATE TABLE GENOTENOPLEIDING (
    GENOTENOPLEIDING_ID INTEGER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DATUMTOEWIJZING DATE,
    PRIJS DECIMAL(10,2),
    SOORT_OPLEIDING_OPLEIDING_ID INTEGER,
    VERREKENEN BOOLEAN
);

CREATE TABLE INZET (
    INZET_ID INTEGER PRIMARY KEY,
    AANTAL_VOLGENS_INZET_DIENSTVERBAND_ID INTEGER,
    DATUMBEGIN DATE,
    DATUMEINDE DATE,
    INZET_BIJ_ORGANISATORISCHEEENHEIDHR_ID INTEGER,
    INZET_VOOR_FUNCTIE_FUNCTIE_ID INTEGER,
    PERCENTAGE VARCHAR(20),
    UREN VARCHAR(20)
);

CREATE TABLE KP_FRMTPLTS_DNSTVRBND (
    KP_FRMTPLTS_DNSTVRBND_ID INTEGER PRIMARY KEY,
    FORMATIEPLAATS_ID INTEGER,
    DIENSTVERBAND_ID INTEGER
);

CREATE TABLE DIENSTVERBAND (
    DIENSTVERBAND_ID INTEGER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DIENSTVERBAND_CONFORM_FUNCTIE_FUNCTIE_ID INTEGER,
    PERIODIEK INTEGER,
    SALARIS VARCHAR(255),
    SCHAAL INTEGER,
    URENPERWEEK INTEGER
);

CREATE TABLE ROL (
    ROL_ID INTEGER PRIMARY KEY,
    DATUMBEGIN DATE,
    DATUMEINDE DATE,
    HOORT_BIJ_ORGANISATORISCHEEENHEIDHR_ID INTEGER,
    OMSCHRIJVING VARCHAR(50)
);

CREATE TABLE ONDERWIJSINSTITUUT (
    ONDERWIJSINSTITUUT_ID INTEGER PRIMARY KEY
);

CREATE TABLE INDIVIDUEEL_KEUZEBUDGET (
    INDIVIDUEEL_KEUZEBUDGET_ID INTEGER PRIMARY KEY,
    BEDRAG DECIMAL(10,2),
    BESTEDING_KEUZEBUDGETBESTEDING_ID INTEGER,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DATUMTOEKENNING DATE,
    HEEFT_INDIVIDUEEL_KEUZEBUDGET_WERKNEMER_ID INTEGER
);

CREATE TABLE SOORTDISCIPLINAIREMAATREGEL (
    SOORTDISCIPLINAIREMAATREGEL_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE RELATIE (
    RELATIE_ID INTEGER PRIMARY KEY,
    IS_KIND_VAN_WERKNEMER_ID INTEGER
);

CREATE TABLE GEWELDSINCIDENT (
    GEWELDSINCIDENT_ID INTEGER PRIMARY KEY,
    DATUM DATE,
    OMSCHRIJVING TEXT,
    TYPE VARCHAR(80)
);

CREATE TABLE ORGANISATORISCHEEENHEID (
    ORGANISATORISCHEEENHEID_ID INTEGER PRIMARY KEY,
    DATUMONTSTAAN DATE,
    DATUMOPHEFFING DATE,
    EMAILADRES VARCHAR(255),
    FAXNUMMER VARCHAR(20),
    FORMATIE VARCHAR(255),
    IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID INTEGER,
    IS_GEHUISVEST_IN_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID INTEGER,
    NAAM VARCHAR(50),
    NAAMVERKORT VARCHAR(255),
    OMSCHRIJVING VARCHAR(80),
    ORGANISATIEIDENTIFICATIE VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20),
    TOELICHTING VARCHAR(255)
);

CREATE TABLE FUNCTIE (
    FUNCTIE_ID INTEGER PRIMARY KEY,
    CODE VARCHAR(50),
    GEBASEERD_OP_NORMPROFIEL_ID INTEGER,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT,
    SCHAAL VARCHAR(20),
    TAKEN TEXT
);

CREATE TABLE KP_WRKNMR_ROL (
    KP_WRKNMR_ROL_ID INTEGER PRIMARY KEY,
    WERKNEMER_ID INTEGER,
    ROL_ID INTEGER
);

CREATE TABLE DECLARATIESOORT (
    DECLARATIESOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE NORMPROFIEL (
    NORMPROFIEL_ID INTEGER PRIMARY KEY,
    CODE VARCHAR(255),
    OMSCHRIJVING VARCHAR(100),
    ONDERDEEL_VAN_FUNCTIEHUIS_ID INTEGER,
    SCHAAL VARCHAR(255)
);

ALTER TABLE ORGANISATORISCHEEENHEIDHR ADD CONSTRAINT FK_ORGANISATORISCHEEENHEIDHR_GEN_ORGANISATORISCHEEENHEID FOREIGN KEY (ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- Generalization to ORGANISATORISCHEEENHEID

ALTER TABLE KP_WRKNMR_ROL ADD CONSTRAINT FK_KP_WRKNMR_ROL_1 FOREIGN KEY (WERKNEMER_ID) REFERENCES WERKNEMER (WERKNEMER_ID);
-- WERKNEMER (many-to-many junction, Connector_ID: 443)

ALTER TABLE KP_WRKNMR_ROL ADD CONSTRAINT FK_KP_WRKNMR_ROL_2 FOREIGN KEY (ROL_ID) REFERENCES ROL (ROL_ID);
-- ROL (many-to-many junction, Connector_ID: 443)

ALTER TABLE KP_OPLDNG_ONDRWJSNSTTT ADD CONSTRAINT FK_KP_OPLDNG_ONDRWJSNSTTT_1 FOREIGN KEY (OPLEIDING_ID) REFERENCES OPLEIDING (OPLEIDING_ID);
-- OPLEIDING (many-to-many junction, Connector_ID: 449)

ALTER TABLE KP_OPLDNG_ONDRWJSNSTTT ADD CONSTRAINT FK_KP_OPLDNG_ONDRWJSNSTTT_2 FOREIGN KEY (ONDERWIJSINSTITUUT_ID) REFERENCES ONDERWIJSINSTITUUT (ONDERWIJSINSTITUUT_ID);
-- ONDERWIJSINSTITUUT (many-to-many junction, Connector_ID: 449)

ALTER TABLE KP_FRMTPLTS_FNCT ADD CONSTRAINT FK_KP_FRMTPLTS_FNCT_1 FOREIGN KEY (FORMATIEPLAATS_ID) REFERENCES FORMATIEPLAATS (FORMATIEPLAATS_ID);
-- FORMATIEPLAATS (many-to-many junction, Connector_ID: 462)

ALTER TABLE KP_FRMTPLTS_FNCT ADD CONSTRAINT FK_KP_FRMTPLTS_FNCT_2 FOREIGN KEY (FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- FUNCTIE (many-to-many junction, Connector_ID: 462)

ALTER TABLE KP_FRMTPLTS_DNSTVRBND ADD CONSTRAINT FK_KP_FRMTPLTS_DNSTVRBND_1 FOREIGN KEY (FORMATIEPLAATS_ID) REFERENCES FORMATIEPLAATS (FORMATIEPLAATS_ID);
-- FORMATIEPLAATS (many-to-many junction, Connector_ID: 466)

ALTER TABLE KP_FRMTPLTS_DNSTVRBND ADD CONSTRAINT FK_KP_FRMTPLTS_DNSTVRBND_2 FOREIGN KEY (DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- DIENSTVERBAND (many-to-many junction, Connector_ID: 466)

ALTER TABLE KP_DNSTVRBND_VSTGNGVNZKBHNDLNDRGNST ADD CONSTRAINT FK_KP_DNSTVRBND_VSTGNGVNZKBHNDLNDRGNST_1 FOREIGN KEY (DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- DIENSTVERBAND (many-to-many junction, Connector_ID: 470)

ALTER TABLE KP_DNSTVRBND_VSTGNGVNZKBHNDLNDRGNST ADD CONSTRAINT FK_KP_DNSTVRBND_VSTGNGVNZKBHNDLNDRGNST_2 FOREIGN KEY (VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID) REFERENCES VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID);
-- VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (many-to-many junction, Connector_ID: 470)

ALTER TABLE KP_DNSTVRBND_ORGNSTRSCHNHDHR ADD CONSTRAINT FK_KP_DNSTVRBND_ORGNSTRSCHNHDHR_1 FOREIGN KEY (DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- DIENSTVERBAND (many-to-many junction, Connector_ID: 472)

ALTER TABLE KP_DNSTVRBND_ORGNSTRSCHNHDHR ADD CONSTRAINT FK_KP_DNSTVRBND_ORGNSTRSCHNHDHR_2 FOREIGN KEY (ORGANISATORISCHEEENHEIDHR_ID) REFERENCES ORGANISATORISCHEEENHEIDHR (ORGANISATORISCHEEENHEID_ID);
-- ORGANISATORISCHEEENHEIDHR (many-to-many junction, Connector_ID: 472)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_HEEFT_VERZUIM FOREIGN KEY (HEEFT_VERZUIM_VERZUIM_ID) REFERENCES VERZUIM (VERZUIM_ID);
-- HEEFT_VERZUIM (1 to 0..*, Connector_ID: 432)

ALTER TABLE VERZUIM ADD CONSTRAINT FK_VERZUIM_SOORT_VERZUIM FOREIGN KEY (SOORT_VERZUIM_VERZUIMSOORT_ID) REFERENCES VERZUIMSOORT (VERZUIMSOORT_ID);
-- SOORT_VERZUIM (0..* to 1, Connector_ID: 433)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_HEEFT_VERLOF FOREIGN KEY (HEEFT_VERLOF_VERLOF_ID) REFERENCES VERLOF (VERLOF_ID);
-- HEEFT_VERLOF (1 to 0..*, Connector_ID: 434)

ALTER TABLE VERLOF ADD CONSTRAINT FK_VERLOF_SOORT_VERLOF FOREIGN KEY (SOORT_VERLOF_VERLOFSOORT_ID) REFERENCES VERLOFSOORT (VERLOFSOORT_ID);
-- SOORT_VERLOF (0..* to 1, Connector_ID: 435)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_IS_PARTNER_VAN FOREIGN KEY (IS_PARTNER_VAN_RELATIE_ID) REFERENCES RELATIE (RELATIE_ID);
-- IS_PARTNER_VAN (1 to 0..1, Connector_ID: 444)

ALTER TABLE RELATIE ADD CONSTRAINT FK_RELATIE_IS_KIND_VAN FOREIGN KEY (IS_KIND_VAN_WERKNEMER_ID) REFERENCES WERKNEMER (WERKNEMER_ID);
-- IS_KIND_VAN (0..* to 1, Connector_ID: 445)

ALTER TABLE ROL ADD CONSTRAINT FK_ROL_HOORT_BIJ FOREIGN KEY (HOORT_BIJ_ORGANISATORISCHEEENHEIDHR_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- HOORT_BIJ (0..* to 0..1, Connector_ID: 447)

ALTER TABLE KEUZEBUDGETBESTEDING ADD CONSTRAINT FK_KEUZEBUDGETBESTEDING_SOORT_BESTEDING FOREIGN KEY (SOORT_BESTEDING_KEUZEBUDGETBESTEDINGSOORT_ID) REFERENCES KEUZEBUDGETBESTEDINGSOORT (KEUZEBUDGETBESTEDINGSOORT_ID);
-- SOORT_BESTEDING (0..* to 1, Connector_ID: 451)

ALTER TABLE INZET ADD CONSTRAINT FK_INZET_INZET_BIJ FOREIGN KEY (INZET_BIJ_ORGANISATORISCHEEENHEIDHR_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- INZET_BIJ (0..* to 1, Connector_ID: 452)

ALTER TABLE INDIVIDUEEL_KEUZEBUDGET ADD CONSTRAINT FK_INDIVIDUEEL_KEUZEBUDGET_BESTEDING FOREIGN KEY (BESTEDING_KEUZEBUDGETBESTEDING_ID) REFERENCES KEUZEBUDGETBESTEDING (KEUZEBUDGETBESTEDING_ID);
-- BESTEDING (1 to 0..*, Connector_ID: 453)

ALTER TABLE INDIVIDUEEL_KEUZEBUDGET ADD CONSTRAINT FK_INDIVIDUEEL_KEUZEBUDGET_HEEFT_INDIVIDUEEL_KEUZEBUDGET FOREIGN KEY (HEEFT_INDIVIDUEEL_KEUZEBUDGET_WERKNEMER_ID) REFERENCES WERKNEMER (WERKNEMER_ID);
-- HEEFT_INDIVIDUEEL_KEUZEBUDGET (0..* to 1, Connector_ID: 454)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_HEEFT_ONDERGAAN FOREIGN KEY (HEEFT_ONDERGAAN_GEWELDSINCIDENT_ID) REFERENCES GEWELDSINCIDENT (GEWELDSINCIDENT_ID);
-- HEEFT_ONDERGAAN (0..* to 1, Connector_ID: 455)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_HEEFT_GENOTEN FOREIGN KEY (HEEFT_GENOTEN_GENOTENOPLEIDING_ID) REFERENCES GENOTENOPLEIDING (GENOTENOPLEIDING_ID);
-- HEEFT_GENOTEN (1 to 0..*, Connector_ID: 456)

ALTER TABLE GENOTENOPLEIDING ADD CONSTRAINT FK_GENOTENOPLEIDING_SOORT_OPLEIDING FOREIGN KEY (SOORT_OPLEIDING_OPLEIDING_ID) REFERENCES OPLEIDING (OPLEIDING_ID);
-- SOORT_OPLEIDING (0..* to 1, Connector_ID: 457)

ALTER TABLE NORMPROFIEL ADD CONSTRAINT FK_NORMPROFIEL_ONDERDEEL_VAN FOREIGN KEY (ONDERDEEL_VAN_FUNCTIEHUIS_ID) REFERENCES FUNCTIEHUIS (FUNCTIEHUIS_ID);
-- ONDERDEEL_VAN (1..* to 1, Connector_ID: 458)

ALTER TABLE INZET ADD CONSTRAINT FK_INZET_INZET_VOOR_FUNCTIE FOREIGN KEY (INZET_VOOR_FUNCTIE_FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- INZET_VOOR_FUNCTIE (1 to 1, Connector_ID: 459)

ALTER TABLE FUNCTIE ADD CONSTRAINT FK_FUNCTIE_GEBASEERD_OP FOREIGN KEY (GEBASEERD_OP_NORMPROFIEL_ID) REFERENCES NORMPROFIEL (NORMPROFIEL_ID);
-- GEBASEERD_OP (1 to 1, Connector_ID: 461)

ALTER TABLE FORMATIEPLAATS ADD CONSTRAINT FK_FORMATIEPLAATS_ONDERDEEL_VAN FOREIGN KEY (ONDERDEEL_VAN_ORGANISATORISCHEEENHEIDHR_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- ONDERDEEL_VAN (1 to 0..1, Connector_ID: 463)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_HEEFT_MAATREGEL FOREIGN KEY (HEEFT_MAATREGEL_DISCIPLINAIRE_MAATREGEL_ID) REFERENCES DISCIPLINAIRE_MAATREGEL (DISCIPLINAIRE_MAATREGEL_ID);
-- HEEFT_MAATREGEL (1 to 0..*, Connector_ID: 464)

ALTER TABLE DISCIPLINAIRE_MAATREGEL ADD CONSTRAINT FK_DISCIPLINAIRE_MAATREGEL_SOORT_MAATREGEL FOREIGN KEY (SOORT_MAATREGEL_SOORTDISCIPLINAIREMAATREGEL_ID) REFERENCES SOORTDISCIPLINAIREMAATREGEL (SOORTDISCIPLINAIREMAATREGEL_ID);
-- SOORT_MAATREGEL (0..* to 1, Connector_ID: 465)

ALTER TABLE INZET ADD CONSTRAINT FK_INZET_AANTAL_VOLGENS_INZET FOREIGN KEY (AANTAL_VOLGENS_INZET_DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- AANTAL_VOLGENS_INZET (1 to 0..*, Connector_ID: 467)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_MEDEWERKER_HEEFT_DIENSTVERBAND FOREIGN KEY (MEDEWERKER_HEEFT_DIENSTVERBAND_DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- MEDEWERKER_HEEFT_DIENSTVERBAND (1 to 1..*, Connector_ID: 468)

ALTER TABLE DIENSTVERBAND ADD CONSTRAINT FK_DIENSTVERBAND_DIENSTVERBAND_CONFORM_FUNCTIE FOREIGN KEY (DIENSTVERBAND_CONFORM_FUNCTIE_FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- DIENSTVERBAND_CONFORM_FUNCTIE (0..* to 1, Connector_ID: 471)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_DIENT_IN FOREIGN KEY (DIENT_IN_DECLARATIE_ID) REFERENCES DECLARATIE (DECLARATIE_ID);
-- DIENT_IN (1 to 0..*, Connector_ID: 473)

ALTER TABLE DECLARATIE ADD CONSTRAINT FK_DECLARATIE_SOORT_DECLARATIE FOREIGN KEY (SOORT_DECLARATIE_DECLARATIESOORT_ID) REFERENCES DECLARATIESOORT (DECLARATIESOORT_ID);
-- SOORT_DECLARATIE (0..* to 1, Connector_ID: 474)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_BEOORDELING_VAN FOREIGN KEY (BEOORDELING_VAN_BEOORDELING_ID) REFERENCES BEOORDELING (BEOORDELING_ID);
-- BEOORDELING_VAN (1 to 0..*, Connector_ID: 475)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_BEOORDEELD_DOOR FOREIGN KEY (BEOORDEELD_DOOR_BEOORDELING_ID) REFERENCES BEOORDELING (BEOORDELING_ID);
-- BEOORDEELD_DOOR (1 to 0..*, Connector_ID: 476)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_DEEL_VAN FOREIGN KEY (IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_DEEL_VAN (1 to 0..1, Connector_ID: 2059)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_GEHUISVEST_IN FOREIGN KEY (IS_GEHUISVEST_IN_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID) REFERENCES VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID);
-- IS_GEHUISVEST_IN (1..* to 1, Connector_ID: 2062)

