CREATE TABLE GUNNING (
    GUNNING_ID NUMBER PRIMARY KEY,
    BERICHT VARCHAR2(255),
    BETREFT_INSCHRIJVING_ID NUMBER,
    BETREFT_OFFERTE_ID NUMBER,
    DATUMGUNNING DATE,
    DATUMPUBLICATIE DATE,
    DATUMVOORLOPIGEGUNNING DATE,
    GEGUNDEPRIJS NUMBER(10,2),
    INHUUR_MEDEWERKER_ID NUMBER
);

CREATE TABLE AANBESTEDINGSOORT_ENUM (
    AANBESTEDINGSOORT_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO AANBESTEDINGSOORT_ENUM (AANBESTEDINGSOORT_ENUM_ID, VALUE) VALUES
    (1, 'ENKELVOUDIG_ONDERHANDS'),
    (2, 'EUROPESE_AANBESTEDING'),
    (3, 'MEERVOUDIG_ONDERHANDS'),
    (4, 'NATIONALE_AANBESTEDING');

CREATE TABLE OFFERTE (
    OFFERTE_ID NUMBER PRIMARY KEY,
    BETREFT_AANBESTEDING_ID NUMBER,
    DATUMOFFERTE DATE,
    INGEDIEND_DOOR_LEVERANCIER_ID NUMBER,
    NAAM VARCHAR2(200),
    OMSCHRIJVING CLOB,
    PRIJS NUMBER(10,2)
);

CREATE TABLE KP_ZK_DCMNT (
    KP_ZK_DCMNT_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    DOCUMENT_ID NUMBER
);

CREATE TABLE INKOOPPAKKET (
    INKOOPPAKKET_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(80),
    NAAM VARCHAR2(200),
    TYPE_ENUM_ID NUMBER
);

CREATE TABLE KWALIFICATIE (
    KWALIFICATIE_ID NUMBER PRIMARY KEY,
    BETREFT_AANBESTEDING_ID NUMBER,
    EINDEGELDIGHEID DATE,
    STARTGELDIGHEID DATE
);

CREATE TABLE KP_ZK_MDWRKR (
    KP_ZK_MDWRKR_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    MEDEWERKER_ID NUMBER
);

CREATE TABLE INKOOPROL_ENUM (
    INKOOPROL_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO INKOOPROL_ENUM (INKOOPROL_ENUM_ID, VALUE) VALUES
    (1, 'BEHEERDER'),
    (2, 'EIGENAAR'),
    (3, 'INKOOPADVISEUR');

CREATE TABLE KP_KSTNPLTS_INKPRDR (
    KP_KSTNPLTS_INKPRDR_ID NUMBER PRIMARY KEY,
    KOSTENPLAATS_ID NUMBER,
    INKOOPORDER_ID NUMBER
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID NUMBER PRIMARY KEY,
    BTWCODE VARCHAR2(255),
    BTWOMSCHRIJVING VARCHAR2(80),
    KOSTENPLAATSSOORTCODE NUMBER(10,2),
    KOSTENPLAATSSOORTOMSCHRIJVING NUMBER(10,2),
    KOSTENPLAATSTYPECODE NUMBER(10,2),
    KOSTENPLAATSTYPEOMSCHRIJVING NUMBER(10,2),
    NAAM VARCHAR2(80),
    OMSCHRIJVING VARCHAR2(200)
);

CREATE TABLE KP_INKPPKKT_CPV_CD (
    KP_INKPPKKT_CPV_CD_ID NUMBER PRIMARY KEY,
    INKOOPPAKKET_ID NUMBER,
    CPV_CODE_ID NUMBER
);

CREATE TABLE OFFERTEAANVRAAG (
    OFFERTEAANVRAAG_ID NUMBER PRIMARY KEY,
    BETREFT_AANBESTEDING_ID NUMBER,
    DATUMAANVRAAG DATE,
    DATUMSLUITING DATE,
    GERICHT_AAN_LEVERANCIER_ID NUMBER,
    NAAM VARCHAR2(80),
    OMSCHRIJVING CLOB
);

CREATE TABLE AANKONDIGING (
    AANKONDIGING_ID NUMBER PRIMARY KEY,
    BESCHRIJVING CLOB,
    CATEGORIE_ENUM_ID NUMBER,
    DATUM DATE,
    MONDT_UIT_AANBESTEDING_ID NUMBER,
    NAAM VARCHAR2(200),
    TYPE_ENUM_ID NUMBER
);

CREATE TABLE STARTFORMULIERAANBESTEDEN (
    STARTFORMULIERAANBESTEDEN_ID NUMBER PRIMARY KEY,
    BEOOGDELOOPTIJD TIMESTAMP,
    BEOOGDETOTALEOPDRACHTWAARDE VARCHAR2(255),
    BETREFT_ZAAK_ID NUMBER,
    INDICATIEAANVULLENDEOPDRACHTLEVERANCIER NUMBER(1),
    INDICATIEBEOOGDEAANBESTEDINGONDERHANDS NUMBER(1),
    INDICATIEBEOOGDEPROCKOMTOVEREEN NUMBER(1),
    INDICATIEEENMALIGELOS NUMBER(1),
    INDICATIEMEERJARIGERAAMOVEREENKOMST NUMBER(1),
    INDICATIEMEERJARIGREPETEREND NUMBER(1),
    INDICATOROVERKOEPELENDPROJECT NUMBER(1),
    MONDT_UIT_AANBESTEDING_ID NUMBER,
    MONDT_UIT_AANKONDIGING_ID NUMBER,
    OMSCHRIJVING CLOB,
    OPDRACHTCATEGORIE_ENUM_ID NUMBER,
    OPDRACHTSOORT_ENUM_ID NUMBER,
    TOELICHTINGAANVULLENDEOPDRACHT CLOB,
    TOELICHTINGEENMALIGOFREPETEREND CLOB
);

CREATE TABLE OPDRACHTSOORT_ENUM (
    OPDRACHTSOORT_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO OPDRACHTSOORT_ENUM (OPDRACHTSOORT_ENUM_ID, VALUE) VALUES
    (1, 'INHUUR_EXTERN_PERSONEEL'),
    (2, 'OPDRACHT_VOOR_LEVERING_DIENSTEN_OF_WERKEN'),
    (3, 'SUBSIDIES');

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    ACHTERNAAM VARCHAR2(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    DIENT_IN_STARTFORMULIERAANBESTEDEN_ID NUMBER,
    EMAILADRES VARCHAR2(255),
    EXTERN NUMBER(1),
    FUNCTIE VARCHAR2(50),
    GELEVERD_VIA_LEVERANCIER_ID NUMBER,
    GESLACHTSAANDUIDING VARCHAR2(255),
    IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID NUMBER,
    IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID NUMBER,
    MEDEWERKERIDENTIFICATIE VARCHAR2(255),
    MEDEWERKERTOELICHTING VARCHAR2(255),
    ROEPNAAM VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    VOORLETTERS VARCHAR2(20),
    VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE ZAAK (
    ZAAK_ID NUMBER PRIMARY KEY,
    ARCHIEFNOMINATIE VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMEINDEGEPLAND DATE,
    DATUMEINDEUITERLIJKEAFDOENING DATE,
    DATUMLAATSTEBETALING DATE,
    DATUMPUBLICATIE DATE,
    DATUMREGISTRATIE DATE,
    DATUMSTART DATE,
    DATUMVERNIETIGINGDOSSIER DATE,
    DUURVERLENGING VARCHAR2(255),
    HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID NUMBER,
    INDICATIEBETALING VARCHAR2(255),
    INDICATIEDEELZAKEN NUMBER(1),
    INDICATIEOPSCHORTING VARCHAR2(255),
    IS_DEELZAAK_VAN_ZAAK_ID NUMBER,
    LEGES VARCHAR2(100),
    OMSCHRIJVING VARCHAR2(80),
    OMSCHRIJVINGRESULTAAT VARCHAR2(80),
    REDENOPSCHORTING VARCHAR2(200),
    REDENVERLENGING VARCHAR2(200),
    TOELICHTING VARCHAR2(255),
    TOELICHTINGRESULTAAT VARCHAR2(255),
    VERTROUWELIJKHEID VARCHAR2(255),
    ZAAKIDENTIFICATIE VARCHAR2(255),
    ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE CPV_CODE (
    CPV_CODE_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(80),
    OMSCHRIJVING VARCHAR2(255),
    VALT_ONDER_AANBESTEDING_ID NUMBER
);

CREATE TABLE INKOOPORDER (
    INKOOPORDER_ID NUMBER PRIMARY KEY,
    ARTIKELCODE VARCHAR2(80),
    BETALINGMEERDEREJAREN NUMBER(1),
    BETREFT VARCHAR2(255),
    BETREFT_CONTRACT_ID NUMBER,
    DATUMEINDE DATE,
    DATUMINGEDIEND DATE,
    DATUMSTART DATE,
    GERELATEERD_INKOOPORDER_ID NUMBER,
    GOEDERENCODE VARCHAR2(80),
    HEEFT_INKOOPPAKKET_ID NUMBER,
    OMSCHRIJVING VARCHAR2(255),
    OORSPRONKELIJK_INKOOPORDER_ID NUMBER,
    ORDERNUMMER VARCHAR2(255),
    SALDO VARCHAR2(255),
    TOTAALNETTOBEDRAG NUMBER(10,2),
    VERPLICHTING_AAN_LEVERANCIER_ID NUMBER,
    WIJZEVANAANBESTEDEN VARCHAR2(255)
);

CREATE TABLE INSCHRIJVING (
    INSCHRIJVING_ID NUMBER PRIMARY KEY,
    BETREFT_AANBESTEDING_ID NUMBER,
    DATUM DATE,
    PRIJS NUMBER(10,2),
    SCORE NUMBER
);

CREATE TABLE CONTRACT (
    CONTRACT_ID NUMBER PRIMARY KEY,
    AUTORISATIEGROEP VARCHAR2(200),
    BESCHRIJVING CLOB,
    BOVENLIGGEND_CONTRACT_ID NUMBER,
    CATEGORIE VARCHAR2(80),
    CLASSIFICATIE VARCHAR2(80),
    CONTRACTREVISIE NUMBER,
    DATUMCREATIE DATE,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    GROEP VARCHAR2(80),
    INTERNCONTRACTID VARCHAR2(255),
    INTERNCONTRACTREVISIE NUMBER,
    OPMERKINGEN CLOB,
    STATUS VARCHAR2(80),
    TYPE VARCHAR2(80),
    VASTLEGGING_ALS_CONTRACT_DOCUMENT_ID NUMBER,
    VOORWAARDE VARCHAR2(80),
    ZOEKWOORDEN VARCHAR2(255)
);

CREATE TABLE LEVERANCIER (
    LEVERANCIER_ID NUMBER PRIMARY KEY,
    CONTRACTANT_CONTRACT_ID NUMBER,
    HEEFT_INSCHRIJVING_ID NUMBER,
    HEEFT_KWALIFICATIE_ID NUMBER,
    NAAM VARCHAR2(200),
    NUMMER VARCHAR2(255)
);

CREATE TABLE KP_MDWRKR_ORGNSTRSCHNHD (
    KP_MDWRKR_ORGNSTRSCHNHD_ID NUMBER PRIMARY KEY,
    MEDEWERKER_ID NUMBER,
    ORGANISATORISCHEEENHEID_ID NUMBER
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR2(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR2(200),
    DOCUMENTIDENTIFICATIE VARCHAR2(255),
    DOCUMENTTITEL VARCHAR2(200),
    VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE AANBESTEDING (
    AANBESTEDING_ID NUMBER PRIMARY KEY,
    BETREFT_ZAAK_ID NUMBER,
    DATUMPUBLICATIE DATE,
    DATUMSTART DATE,
    DIGITAAL NUMBER(1),
    DOCUMENT_ID NUMBER,
    MONDT_UIT_GUNNING_ID NUMBER,
    NAAM VARCHAR2(200),
    PROCEDURE_ENUM_ID NUMBER,
    PROCESLEIDER_MEDEWERKER_ID NUMBER,
    REFERENTIENUMMER VARCHAR2(80),
    SCOREMAXIMAAL NUMBER,
    STATUS VARCHAR2(80),
    TENDERNEDKENMERK VARCHAR2(80),
    TYPE_ENUM_ID NUMBER,
    VOLGENDESLUITING VARCHAR2(255)
);

CREATE TABLE SELECTIETABELAANBESTEDING (
    SELECTIETABELAANBESTEDING_ID NUMBER PRIMARY KEY,
    AANBESTEDINGSOORT_ENUM_ID NUMBER,
    DREMPELBEDRAGTOT NUMBER(10,2),
    DREMPELBEDRAGVANAF NUMBER(10,2),
    OPDRACHTCATEGORIE_ENUM_ID NUMBER,
    OPENBAAR NUMBER(1)
);

CREATE TABLE ORGANISATORISCHEEENHEID (
    ORGANISATORISCHEEENHEID_ID NUMBER PRIMARY KEY,
    DATUMONTSTAAN DATE,
    DATUMOPHEFFING DATE,
    EMAILADRES VARCHAR2(255),
    FAXNUMMER VARCHAR2(20),
    FORMATIE VARCHAR2(255),
    HEEFT_KOSTENPLAATS_ID NUMBER,
    IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID NUMBER,
    NAAM VARCHAR2(50),
    NAAMVERKORT VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(80),
    ORGANISATIEIDENTIFICATIE VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    TOELICHTING VARCHAR2(255)
);

CREATE TABLE OPDRACHTCATEGORIE_ENUM (
    OPDRACHTCATEGORIE_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO OPDRACHTCATEGORIE_ENUM (OPDRACHTCATEGORIE_ENUM_ID, VALUE) VALUES
    (1, 'DIENSTEN_REGULIER'),
    (2, 'DIENSTEN_SOCIALE_OF_SPECIFIEKE_DIENSTEN'),
    (3, 'LEVERINGEN'),
    (4, 'WERKEN');

ALTER TABLE KP_INKPPKKT_CPV_CD ADD CONSTRAINT FK_KP_INKPPKKT_CPV_CD_1 FOREIGN KEY (INKOOPPAKKET_ID) REFERENCES INKOOPPAKKET (INKOOPPAKKET_ID);
-- INKOOPPAKKET (many-to-many junction, Connector_ID: 403)

ALTER TABLE KP_INKPPKKT_CPV_CD ADD CONSTRAINT FK_KP_INKPPKKT_CPV_CD_2 FOREIGN KEY (CPV_CODE_ID) REFERENCES CPV_CODE (CPV_CODE_ID);
-- CPV_CODE (many-to-many junction, Connector_ID: 403)

ALTER TABLE KP_KSTNPLTS_INKPRDR ADD CONSTRAINT FK_KP_KSTNPLTS_INKPRDR_1 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 492)

ALTER TABLE KP_KSTNPLTS_INKPRDR ADD CONSTRAINT FK_KP_KSTNPLTS_INKPRDR_2 FOREIGN KEY (INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- INKOOPORDER (many-to-many junction, Connector_ID: 492)

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_MDWRKR_ORGNSTRSCHNHD ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_1 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2175)

ALTER TABLE KP_MDWRKR_ORGNSTRSCHNHD ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_2 FOREIGN KEY (ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- ORGANISATORISCHEEENHEID (many-to-many junction, Connector_ID: 2175)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_VASTLEGGING_ALS_CONTRACT FOREIGN KEY (VASTLEGGING_ALS_CONTRACT_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- VASTLEGGING_ALS_CONTRACT (None to None, Connector_ID: 103)

ALTER TABLE AANBESTEDING ADD CONSTRAINT FK_AANBESTEDING_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- unnamed (None to None, Connector_ID: 106)

ALTER TABLE STARTFORMULIERAANBESTEDEN ADD CONSTRAINT FK_STARTFORMULIERAANBESTEDEN_BETREFT FOREIGN KEY (BETREFT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 385)

ALTER TABLE OFFERTE ADD CONSTRAINT FK_OFFERTE_INGEDIEND_DOOR FOREIGN KEY (INGEDIEND_DOOR_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- INGEDIEND_DOOR (0..* to 1, Connector_ID: 386)

ALTER TABLE OFFERTEAANVRAAG ADD CONSTRAINT FK_OFFERTEAANVRAAG_GERICHT_AAN FOREIGN KEY (GERICHT_AAN_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- GERICHT_AAN (0..* to 1, Connector_ID: 387)

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_HEEFT FOREIGN KEY (HEEFT_KWALIFICATIE_ID) REFERENCES KWALIFICATIE (KWALIFICATIE_ID);
-- HEEFT (1 to 0..*, Connector_ID: 391)

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_HEEFT_2 FOREIGN KEY (HEEFT_INSCHRIJVING_ID) REFERENCES INSCHRIJVING (INSCHRIJVING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 394)

ALTER TABLE GUNNING ADD CONSTRAINT FK_GUNNING_INHUUR FOREIGN KEY (INHUUR_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- INHUUR (0..* to 0..1, Connector_ID: 395)

ALTER TABLE GUNNING ADD CONSTRAINT FK_GUNNING_BETREFT FOREIGN KEY (BETREFT_OFFERTE_ID) REFERENCES OFFERTE (OFFERTE_ID);
-- BETREFT (0..1 to 0..1, Connector_ID: 396)

ALTER TABLE GUNNING ADD CONSTRAINT FK_GUNNING_BETREFT_2 FOREIGN KEY (BETREFT_INSCHRIJVING_ID) REFERENCES INSCHRIJVING (INSCHRIJVING_ID);
-- BETREFT (0..1 to 0..1, Connector_ID: 398)

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_CONTRACTANT FOREIGN KEY (CONTRACTANT_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- CONTRACTANT (1 to 0..*, Connector_ID: 404)

ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_BOVENLIGGEND FOREIGN KEY (BOVENLIGGEND_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- BOVENLIGGEND (0..* to 0..1, Connector_ID: 405)

ALTER TABLE STARTFORMULIERAANBESTEDEN ADD CONSTRAINT FK_STARTFORMULIERAANBESTEDEN_MONDT_UIT FOREIGN KEY (MONDT_UIT_AANKONDIGING_ID) REFERENCES AANKONDIGING (AANKONDIGING_ID);
-- MONDT_UIT (0..1 to 0..*, Connector_ID: 413)

ALTER TABLE CPV_CODE ADD CONSTRAINT FK_CPV_CODE_VALT_ONDER FOREIGN KEY (VALT_ONDER_AANBESTEDING_ID) REFERENCES AANBESTEDING (AANBESTEDING_ID);
-- VALT_ONDER (1 to 0..*, Connector_ID: 421)

ALTER TABLE INSCHRIJVING ADD CONSTRAINT FK_INSCHRIJVING_BETREFT FOREIGN KEY (BETREFT_AANBESTEDING_ID) REFERENCES AANBESTEDING (AANBESTEDING_ID);
-- BETREFT (0..* to 1, Connector_ID: 422)

ALTER TABLE OFFERTE ADD CONSTRAINT FK_OFFERTE_BETREFT FOREIGN KEY (BETREFT_AANBESTEDING_ID) REFERENCES AANBESTEDING (AANBESTEDING_ID);
-- BETREFT (0..* to 1, Connector_ID: 423)

ALTER TABLE STARTFORMULIERAANBESTEDEN ADD CONSTRAINT FK_STARTFORMULIERAANBESTEDEN_MONDT_UIT_2 FOREIGN KEY (MONDT_UIT_AANBESTEDING_ID) REFERENCES AANBESTEDING (AANBESTEDING_ID);
-- MONDT_UIT (0..1 to 0..1, Connector_ID: 424)

ALTER TABLE AANKONDIGING ADD CONSTRAINT FK_AANKONDIGING_MONDT_UIT FOREIGN KEY (MONDT_UIT_AANBESTEDING_ID) REFERENCES AANBESTEDING (AANBESTEDING_ID);
-- MONDT_UIT (0..* to 0..1, Connector_ID: 425)

ALTER TABLE OFFERTEAANVRAAG ADD CONSTRAINT FK_OFFERTEAANVRAAG_BETREFT FOREIGN KEY (BETREFT_AANBESTEDING_ID) REFERENCES AANBESTEDING (AANBESTEDING_ID);
-- BETREFT (0..* to 1, Connector_ID: 426)

ALTER TABLE KWALIFICATIE ADD CONSTRAINT FK_KWALIFICATIE_BETREFT FOREIGN KEY (BETREFT_AANBESTEDING_ID) REFERENCES AANBESTEDING (AANBESTEDING_ID);
-- BETREFT (0..* to 1, Connector_ID: 427)

ALTER TABLE AANBESTEDING ADD CONSTRAINT FK_AANBESTEDING_MONDT_UIT FOREIGN KEY (MONDT_UIT_GUNNING_ID) REFERENCES GUNNING (GUNNING_ID);
-- MONDT_UIT (0..1 to 0..1, Connector_ID: 428)

ALTER TABLE AANBESTEDING ADD CONSTRAINT FK_AANBESTEDING_BETREFT FOREIGN KEY (BETREFT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- BETREFT (0..1 to 0..1, Connector_ID: 429)

ALTER TABLE AANBESTEDING ADD CONSTRAINT FK_AANBESTEDING_PROCESLEIDER FOREIGN KEY (PROCESLEIDER_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- PROCESLEIDER (0..* to 0..1, Connector_ID: 430)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_OORSPRONKELIJK FOREIGN KEY (OORSPRONKELIJK_INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- OORSPRONKELIJK (0..1 to 0..1, Connector_ID: 493)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_GERELATEERD FOREIGN KEY (GERELATEERD_INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- GERELATEERD (0..1 to 0..*, Connector_ID: 494)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_BETREFT FOREIGN KEY (BETREFT_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- BETREFT (0..1 to 1, Connector_ID: 495)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_VERPLICHTING_AAN FOREIGN KEY (VERPLICHTING_AAN_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- VERPLICHTING_AAN (0..* to 1, Connector_ID: 496)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_HEEFT FOREIGN KEY (HEEFT_INKOOPPAKKET_ID) REFERENCES INKOOPPAKKET (INKOOPPAKKET_ID);
-- HEEFT (0..* to 1, Connector_ID: 497)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_DEEL_VAN FOREIGN KEY (IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_DEEL_VAN (1 to 0..1, Connector_ID: 2059)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..1 to 1, Connector_ID: 2063)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJK_VOOR FOREIGN KEY (IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_VERANTWOORDELIJK_VOOR (0..1 to 0..1, Connector_ID: 2166)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_CONTACTPERSOON_VOOR FOREIGN KEY (IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_CONTACTPERSOON_VOOR (0..1 to 0..1, Connector_ID: 2185)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_DIENT_IN FOREIGN KEY (DIENT_IN_STARTFORMULIERAANBESTEDEN_ID) REFERENCES STARTFORMULIERAANBESTEDEN (STARTFORMULIERAANBESTEDEN_ID);
-- DIENT_IN (1 to 0..*, Connector_ID: 2192)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_GELEVERD_VIA FOREIGN KEY (GELEVERD_VIA_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- GELEVERD_VIA (0..* to 0..1, Connector_ID: 2194)

ALTER TABLE AANBESTEDING ADD CONSTRAINT FK_AANBESTEDING_TYPE_ENUM_ID FOREIGN KEY (TYPE_ENUM_ID) REFERENCES OPDRACHTCATEGORIE_ENUM (OPDRACHTCATEGORIE_ENUM_ID);
-- TYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE AANBESTEDING ADD CONSTRAINT FK_AANBESTEDING_PROCEDURE_ENUM_ID FOREIGN KEY (PROCEDURE_ENUM_ID) REFERENCES AANBESTEDINGSOORT_ENUM (AANBESTEDINGSOORT_ENUM_ID);
-- PROCEDURE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE AANKONDIGING ADD CONSTRAINT FK_AANKONDIGING_TYPE_ENUM_ID FOREIGN KEY (TYPE_ENUM_ID) REFERENCES AANBESTEDINGSOORT_ENUM (AANBESTEDINGSOORT_ENUM_ID);
-- TYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE AANKONDIGING ADD CONSTRAINT FK_AANKONDIGING_CATEGORIE_ENUM_ID FOREIGN KEY (CATEGORIE_ENUM_ID) REFERENCES OPDRACHTCATEGORIE_ENUM (OPDRACHTCATEGORIE_ENUM_ID);
-- CATEGORIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INKOOPPAKKET ADD CONSTRAINT FK_INKOOPPAKKET_TYPE_ENUM_ID FOREIGN KEY (TYPE_ENUM_ID) REFERENCES OPDRACHTCATEGORIE_ENUM (OPDRACHTCATEGORIE_ENUM_ID);
-- TYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE SELECTIETABELAANBESTEDING ADD CONSTRAINT FK_SELECTIETABELAANBESTEDING_AANBESTEDINGSOORT_ENUM_ID FOREIGN KEY (AANBESTEDINGSOORT_ENUM_ID) REFERENCES AANBESTEDINGSOORT_ENUM (AANBESTEDINGSOORT_ENUM_ID);
-- AANBESTEDINGSOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE SELECTIETABELAANBESTEDING ADD CONSTRAINT FK_SELECTIETABELAANBESTEDING_OPDRACHTCATEGORIE_ENUM_ID FOREIGN KEY (OPDRACHTCATEGORIE_ENUM_ID) REFERENCES OPDRACHTCATEGORIE_ENUM (OPDRACHTCATEGORIE_ENUM_ID);
-- OPDRACHTCATEGORIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE STARTFORMULIERAANBESTEDEN ADD CONSTRAINT FK_STARTFORMULIERAANBESTEDEN_OPDRACHTSOORT_ENUM_ID FOREIGN KEY (OPDRACHTSOORT_ENUM_ID) REFERENCES OPDRACHTSOORT_ENUM (OPDRACHTSOORT_ENUM_ID);
-- OPDRACHTSOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE STARTFORMULIERAANBESTEDEN ADD CONSTRAINT FK_STARTFORMULIERAANBESTEDEN_OPDRACHTCATEGORIE_ENUM_ID FOREIGN KEY (OPDRACHTCATEGORIE_ENUM_ID) REFERENCES OPDRACHTCATEGORIE_ENUM (OPDRACHTCATEGORIE_ENUM_ID);
-- OPDRACHTCATEGORIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

