CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR2(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR2(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR2(200),
        DOCUMENTIDENTIFICATIE VARCHAR2(255),
        DOCUMENTTITEL VARCHAR2(200),
        VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE VERKEERSBESLUIT (
    VERKEERSBESLUIT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBESLUIT DATE,
        DATUMEINDE DATE,
        DATUMSTART DATE,
        HUISNUMMER VARCHAR2(255),
        IS_VASTGELEGD_IN_DOCUMENT_ID VARCHAR2(255),
        POSTCODE VARCHAR2(255),
        REFERENTIENUMMER VARCHAR2(80),
        STRAAT VARCHAR2(200),
        TITEL VARCHAR2(255)
);

ALTER TABLE VERKEERSBESLUIT ADD CONSTRAINT FK_VERKEERSBESLUIT_IS_VASTGELEGD_IN FOREIGN KEY (IS_VASTGELEGD_IN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- IS_VASTGELEGD_IN (1 to 1, Connector_ID: 1263)

