CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR(200),
        DOCUMENTIDENTIFICATIE VARCHAR(255),
        DOCUMENTTITEL VARCHAR(200),
        VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE VERKEERSBESLUIT (
    VERKEERSBESLUIT_ID VARCHAR(255) PRIMARY KEY,
        DATUMBESLUIT DATE,
        DATUMEINDE DATE,
        DATUMSTART DATE,
        HUISNUMMER VARCHAR(255),
        IS_VASTGELEGD_IN_DOCUMENT_ID VARCHAR(255),
        POSTCODE VARCHAR(255),
        REFERENTIENUMMER VARCHAR(80),
        STRAAT VARCHAR(200),
        TITEL VARCHAR(255)
);

ALTER TABLE VERKEERSBESLUIT ADD CONSTRAINT FK_VERKEERSBESLUIT_IS_VASTGELEGD_IN FOREIGN KEY (IS_VASTGELEGD_IN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- IS_VASTGELEGD_IN (1 to 1, Connector_ID: 1263)

