CREATE TABLE [VERBLIJFSOBJECT] (
    [VERBLIJFSOBJECT_ID] INT PRIMARY KEY,
    [AANTALKAMERS] VARCHAR(255),
    [BEGINGELDIGHEID] DATE,
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDGELDIGHEID] DATE,
    [GEBRUIKSDOEL] VARCHAR(255),
    [GECONSTATEERD] BIT,
    [GEOMETRIE] GEOMETRY,
    [HOOGSTEBOUWLAAG] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [LAAGSTEBOUWLAAG] VARCHAR(255),
    [ONTSLUITINGVERDIEPING] VARCHAR(255),
    [OPPERVLAKTE] INT,
    [SOORTWOONOBJECT] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [TOEGANGBOUWLAAG] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [WIJK] (
    [WIJK_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] DATE,
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD] BIT,
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [VERSIE] INT,
    [WIJKCODE] VARCHAR(255),
    [WIJKNAAM] VARCHAR(255)
);

CREATE TABLE [OVERIGBENOEMDTERREIN] (
    [OVERIGBENOEMDTERREIN_ID] INT PRIMARY KEY,
    [GEBRUIKSDOELOVERIGBENOEMDTERREIN] VARCHAR(255),
    [OVERIGBENOEMDTERREINIDENTIFICATIE] VARCHAR(255)
);

CREATE TABLE [SPORTLOCATIE] (
    [SPORTLOCATIE_ID] INT PRIMARY KEY,
    [NAAM] VARCHAR(200)
);

CREATE TABLE [BINNENLOCATIE] (
    [SPORTLOCATIE_ID] INT PRIMARY KEY,
    [ADRES] VARCHAR(255),
    [BEDIENT_WIJK_ID] INT,
    [BOUWJAAR] VARCHAR(255),
    [GEMEENTELIJK] BIT,
    [GESCHATTEKOSTENPERJAAR] DECIMAL(10,2),
    [GYMZAAL] BIT,
    [IS_GEVESTIGD_IN_VERBLIJFSOBJECT_ID] INT,
    [KLOKURENONDERWIJS] VARCHAR(255),
    [KLOKURENVERENIGINGEN] VARCHAR(255),
    [LOCATIE] VARCHAR(255),
    [ONDERHOUDSNIVEAU] VARCHAR(80),
    [ONDERHOUDSSTATUS] INT,
    [SPORTHAL] BIT,
    [VLOEROPPERVLAKTE] INT
);

CREATE TABLE [DOCUMENT] (
    [DOCUMENT_ID] INT PRIMARY KEY,
    [COCUMENTBESCHRIJVING] VARCHAR(255),
    [DATUMCREATIEDOCUMENT] DATE,
    [DATUMONTVANGSTDOCUMENT] DATE,
    [DATUMVERZENDINGDOCUMENT] DATE,
    [DOCUMENTAUTEUR] VARCHAR(200),
    [DOCUMENTIDENTIFICATIE] VARCHAR(255),
    [DOCUMENTTITEL] VARCHAR(200),
    [INSPECTIERAPPORT_SPORTLOCATIE_ID] INT,
    [VERTROUWELIJKAANDUIDING] VARCHAR(20)
);

CREATE TABLE [SPORTPARK] (
    [SPORTLOCATIE_ID] INT PRIMARY KEY,
    [LIGT_OP_OVERIGBENOEMDTERREIN_ID] INT
);

CREATE TABLE [VELD] (
    [VELD_ID] INT PRIMARY KEY,
    [HEEFT_SPORTLOCATIE_ID] INT,
    [LIGT_OP_OVERIGBENOEMDTERREIN_ID] INT
);

CREATE TABLE [KP_BNNNLCT_SPRTLCT] (
    [KP_BNNNLCT_SPRTLCT_ID] INT PRIMARY KEY,
    [BINNENLOCATIE_ID] INT,
    [SPORTLOCATIE_ID] INT
);

CREATE TABLE [KP_SPRTPRK_SPRTLCT] (
    [KP_SPRTPRK_SPRTLCT_ID] INT PRIMARY KEY,
    [SPORTPARK_ID] INT,
    [SPORTLOCATIE_ID] INT
);

ALTER TABLE [BINNENLOCATIE] ADD CONSTRAINT FK_BINNENLOCATIE_GEN_SPORTLOCATIE FOREIGN KEY ([SPORTLOCATIE_ID]) REFERENCES [SPORTLOCATIE] ([SPORTLOCATIE_ID]);
-- Generalization to SPORTLOCATIE

ALTER TABLE [SPORTPARK] ADD CONSTRAINT FK_SPORTPARK_GEN_SPORTLOCATIE FOREIGN KEY ([SPORTLOCATIE_ID]) REFERENCES [SPORTLOCATIE] ([SPORTLOCATIE_ID]);
-- Generalization to SPORTLOCATIE

ALTER TABLE [KP_SPRTPRK_SPRTLCT] ADD CONSTRAINT FK_KP_SPRTPRK_SPRTLCT_1 FOREIGN KEY ([SPORTPARK_ID]) REFERENCES [SPORTPARK] ([SPORTLOCATIE_ID]);
-- SPORTPARK (many-to-many junction, Connector_ID: 1086)

ALTER TABLE [KP_SPRTPRK_SPRTLCT] ADD CONSTRAINT FK_KP_SPRTPRK_SPRTLCT_2 FOREIGN KEY ([SPORTLOCATIE_ID]) REFERENCES [SPORTLOCATIE] ([SPORTLOCATIE_ID]);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1086)

ALTER TABLE [KP_BNNNLCT_SPRTLCT] ADD CONSTRAINT FK_KP_BNNNLCT_SPRTLCT_1 FOREIGN KEY ([BINNENLOCATIE_ID]) REFERENCES [BINNENLOCATIE] ([SPORTLOCATIE_ID]);
-- BINNENLOCATIE (many-to-many junction, Connector_ID: 1095)

ALTER TABLE [KP_BNNNLCT_SPRTLCT] ADD CONSTRAINT FK_KP_BNNNLCT_SPRTLCT_2 FOREIGN KEY ([SPORTLOCATIE_ID]) REFERENCES [SPORTLOCATIE] ([SPORTLOCATIE_ID]);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1095)

ALTER TABLE [DOCUMENT] ADD CONSTRAINT FK_DOCUMENT_INSPECTIERAPPORT FOREIGN KEY ([INSPECTIERAPPORT_SPORTLOCATIE_ID]) REFERENCES [SPORTLOCATIE] ([SPORTLOCATIE_ID]);
-- INSPECTIERAPPORT (0..1 to 0..*, Connector_ID: 115)

ALTER TABLE [VELD] ADD CONSTRAINT FK_VELD_LIGT_OP FOREIGN KEY ([LIGT_OP_OVERIGBENOEMDTERREIN_ID]) REFERENCES [OVERIGBENOEMDTERREIN] ([OVERIGBENOEMDTERREIN_ID]);
-- LIGT_OP (0..1 to 1, Connector_ID: 1082)

ALTER TABLE [SPORTPARK] ADD CONSTRAINT FK_SPORTPARK_LIGT_OP FOREIGN KEY ([LIGT_OP_OVERIGBENOEMDTERREIN_ID]) REFERENCES [OVERIGBENOEMDTERREIN] ([OVERIGBENOEMDTERREIN_ID]);
-- LIGT_OP (0..1 to 1, Connector_ID: 1084)

ALTER TABLE [VELD] ADD CONSTRAINT FK_VELD_HEEFT FOREIGN KEY ([HEEFT_SPORTLOCATIE_ID]) REFERENCES [SPORTLOCATIE] ([SPORTLOCATIE_ID]);
-- HEEFT (0..1 to 0..*, Connector_ID: 1085)

ALTER TABLE [BINNENLOCATIE] ADD CONSTRAINT FK_BINNENLOCATIE_BEDIENT FOREIGN KEY ([BEDIENT_WIJK_ID]) REFERENCES [WIJK] ([WIJK_ID]);
-- BEDIENT (0..* to 1, Connector_ID: 1093)

ALTER TABLE [BINNENLOCATIE] ADD CONSTRAINT FK_BINNENLOCATIE_IS_GEVESTIGD_IN FOREIGN KEY ([IS_GEVESTIGD_IN_VERBLIJFSOBJECT_ID]) REFERENCES [VERBLIJFSOBJECT] ([VERBLIJFSOBJECT_ID]);
-- IS_GEVESTIGD_IN (0..* to 0..1, Connector_ID: 1094)

