CREATE TABLE VELD (
    VELD_ID INTEGER PRIMARY KEY
);

CREATE TABLE SPORTMATERIAAL (
    SPORTMATERIAAL_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200)
);

CREATE TABLE SPORTLOCATIE (
    SPORTLOCATIE_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200)
);

CREATE TABLE SPORT (
    SPORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    NIETNATUURLIJKPERSOON_ID INTEGER PRIMARY KEY,
    DATUMAANVANG DATE,
    DATUMEINDE DATE,
    DATUMUITSCHRIJVING DATE,
    DATUMVOORTZETTING DATE,
    FAXNUMMER VARCHAR(20),
    INGESCHREVEN BOOLEAN,
    INOPRICHTING BOOLEAN,
    KVKNUMMER VARCHAR(255),
    NNPID VARCHAR(255),
    RECHTSVORM VARCHAR(255),
    RSINNUMMER VARCHAR(255),
    STATUTAIRENAAM VARCHAR(255),
    STATUTAIREZETEL VARCHAR(255),
    WEBSITEURL VARCHAR(200)
);

CREATE TABLE AANTAL (
    AANTAL_ID INTEGER PRIMARY KEY,
    AANTALMATERIAAL INTEGER
);

CREATE TABLE BELIJNING (
    BELIJNING_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200)
);

CREATE TABLE SPORTPARK (
    SPORTLOCATIE_ID INTEGER PRIMARY KEY,
    HEEFT_VELD_ID INTEGER
);

CREATE TABLE BINNENLOCATIE (
    SPORTLOCATIE_ID INTEGER PRIMARY KEY,
    ADRES VARCHAR(255),
    BOUWJAAR VARCHAR(255),
    GEMEENTELIJK BOOLEAN,
    GESCHATTEKOSTENPERJAAR DECIMAL(10,2),
    GYMZAAL BOOLEAN,
    KLOKURENONDERWIJS VARCHAR(255),
    KLOKURENVERENIGINGEN VARCHAR(255),
    LOCATIE VARCHAR(255),
    ONDERHOUDSNIVEAU VARCHAR(80),
    ONDERHOUDSSTATUS INTEGER,
    SPORTHAL BOOLEAN,
    VLOEROPPERVLAKTE INTEGER
);

CREATE TABLE SPORTVERENIGING (
    NIETNATUURLIJKPERSOON_ID INTEGER PRIMARY KEY,
    AANTALNORMTEAMS VARCHAR(255),
    ADRES VARCHAR(255),
    BINNENSPORT BOOLEAN,
    BUITENSPORT BOOLEAN,
    EMAIL VARCHAR(80),
    LEDENAANTAL INTEGER,
    NAAM VARCHAR(200),
    TYPESPORT VARCHAR(200)
);

CREATE TABLE SCHOOL (
    NIETNATUURLIJKPERSOON_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200)
);

CREATE TABLE KP_VLD_BLJNNG (
    KP_VLD_BLJNNG_ID INTEGER PRIMARY KEY,
    VELD_ID INTEGER,
    BELIJNING_ID INTEGER
);

CREATE TABLE KP_BNNNLCT_BLJNNG (
    KP_BNNNLCT_BLJNNG_ID INTEGER PRIMARY KEY,
    BINNENLOCATIE_ID INTEGER,
    BELIJNING_ID INTEGER
);

CREATE TABLE KP_BNNNLCT_SPRTMTRL (
    KP_BNNNLCT_SPRTMTRL_ID INTEGER PRIMARY KEY,
    BINNENLOCATIE_ID INTEGER,
    SPORTMATERIAAL_ID INTEGER
);

CREATE TABLE KP_SPRTVRNGNG_SPRTLCT (
    KP_SPRTVRNGNG_SPRTLCT_ID INTEGER PRIMARY KEY,
    SPORTVERENIGING_ID INTEGER,
    SPORTLOCATIE_ID INTEGER
);

CREATE TABLE KP_SPRTVRNGNG_SPRT (
    KP_SPRTVRNGNG_SPRT_ID INTEGER PRIMARY KEY,
    SPORTVERENIGING_ID INTEGER,
    SPORT_ID INTEGER
);

CREATE TABLE KP_SCHL_SPRTLCT (
    KP_SCHL_SPRTLCT_ID INTEGER PRIMARY KEY,
    SCHOOL_ID INTEGER,
    SPORTLOCATIE_ID INTEGER
);

ALTER TABLE SCHOOL ADD CONSTRAINT FK_SCHOOL_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_GEN_SPORTLOCATIE FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- Generalization to SPORTLOCATIE

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_GEN_SPORTLOCATIE FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- Generalization to SPORTLOCATIE

ALTER TABLE SPORTVERENIGING ADD CONSTRAINT FK_SPORTVERENIGING_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE KP_SPRTVRNGNG_SPRTLCT ADD CONSTRAINT FK_KP_SPRTVRNGNG_SPRTLCT_1 FOREIGN KEY (SPORTVERENIGING_ID) REFERENCES SPORTVERENIGING (NIETNATUURLIJKPERSOON_ID);
-- SPORTVERENIGING (many-to-many junction, Connector_ID: 1087)

ALTER TABLE KP_SPRTVRNGNG_SPRTLCT ADD CONSTRAINT FK_KP_SPRTVRNGNG_SPRTLCT_2 FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1087)

ALTER TABLE KP_SPRTVRNGNG_SPRT ADD CONSTRAINT FK_KP_SPRTVRNGNG_SPRT_1 FOREIGN KEY (SPORTVERENIGING_ID) REFERENCES SPORTVERENIGING (NIETNATUURLIJKPERSOON_ID);
-- SPORTVERENIGING (many-to-many junction, Connector_ID: 1088)

ALTER TABLE KP_SPRTVRNGNG_SPRT ADD CONSTRAINT FK_KP_SPRTVRNGNG_SPRT_2 FOREIGN KEY (SPORT_ID) REFERENCES SPORT (SPORT_ID);
-- SPORT (many-to-many junction, Connector_ID: 1088)

ALTER TABLE KP_BNNNLCT_SPRTMTRL ADD CONSTRAINT FK_KP_BNNNLCT_SPRTMTRL_1 FOREIGN KEY (BINNENLOCATIE_ID) REFERENCES BINNENLOCATIE (SPORTLOCATIE_ID);
-- BINNENLOCATIE (many-to-many junction, Connector_ID: 1092)

ALTER TABLE KP_BNNNLCT_SPRTMTRL ADD CONSTRAINT FK_KP_BNNNLCT_SPRTMTRL_2 FOREIGN KEY (SPORTMATERIAAL_ID) REFERENCES SPORTMATERIAAL (SPORTMATERIAAL_ID);
-- SPORTMATERIAAL (many-to-many junction, Connector_ID: 1092)

ALTER TABLE KP_VLD_BLJNNG ADD CONSTRAINT FK_KP_VLD_BLJNNG_1 FOREIGN KEY (VELD_ID) REFERENCES VELD (VELD_ID);
-- VELD (many-to-many junction, Connector_ID: 1096)

ALTER TABLE KP_VLD_BLJNNG ADD CONSTRAINT FK_KP_VLD_BLJNNG_2 FOREIGN KEY (BELIJNING_ID) REFERENCES BELIJNING (BELIJNING_ID);
-- BELIJNING (many-to-many junction, Connector_ID: 1096)

ALTER TABLE KP_BNNNLCT_BLJNNG ADD CONSTRAINT FK_KP_BNNNLCT_BLJNNG_1 FOREIGN KEY (BINNENLOCATIE_ID) REFERENCES BINNENLOCATIE (SPORTLOCATIE_ID);
-- BINNENLOCATIE (many-to-many junction, Connector_ID: 1097)

ALTER TABLE KP_BNNNLCT_BLJNNG ADD CONSTRAINT FK_KP_BNNNLCT_BLJNNG_2 FOREIGN KEY (BELIJNING_ID) REFERENCES BELIJNING (BELIJNING_ID);
-- BELIJNING (many-to-many junction, Connector_ID: 1097)

ALTER TABLE KP_SCHL_SPRTLCT ADD CONSTRAINT FK_KP_SCHL_SPRTLCT_1 FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL (NIETNATUURLIJKPERSOON_ID);
-- SCHOOL (many-to-many junction, Connector_ID: 1205)

ALTER TABLE KP_SCHL_SPRTLCT ADD CONSTRAINT FK_KP_SCHL_SPRTLCT_2 FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1205)

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_HEEFT FOREIGN KEY (HEEFT_VELD_ID) REFERENCES VELD (VELD_ID);
-- HEEFT (0..1 to 0..*, Connector_ID: 1085)

