CREATE TABLE VERBLIJFSOBJECT (
    VERBLIJFSOBJECT_ID NUMBER PRIMARY KEY,
    AANTALKAMERS VARCHAR2(255),
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GEBRUIKSDOEL VARCHAR2(255),
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    HOOGSTEBOUWLAAG VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LAAGSTEBOUWLAAG VARCHAR2(255),
    ONTSLUITINGVERDIEPING VARCHAR2(255),
    OPPERVLAKTE NUMBER,
    SOORTWOONOBJECT VARCHAR2(255),
    STATUS VARCHAR2(255),
    TOEGANGBOUWLAAG VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE WIJK (
    WIJK_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    STATUS VARCHAR2(255),
    VERSIE NUMBER,
    WIJKCODE VARCHAR2(255),
    WIJKNAAM VARCHAR2(255)
);

CREATE TABLE OVERIGBENOEMDTERREIN (
    OVERIGBENOEMDTERREIN_ID NUMBER PRIMARY KEY,
    GEBRUIKSDOELOVERIGBENOEMDTERREIN VARCHAR2(255),
    OVERIGBENOEMDTERREINIDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE SPORTLOCATIE (
    SPORTLOCATIE_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(200)
);

CREATE TABLE BINNENLOCATIE (
    SPORTLOCATIE_ID NUMBER PRIMARY KEY,
    ADRES VARCHAR2(255),
    BEDIENT_WIJK_ID NUMBER,
    BOUWJAAR VARCHAR2(255),
    GEMEENTELIJK NUMBER(1),
    GESCHATTEKOSTENPERJAAR NUMBER(10,2),
    GYMZAAL NUMBER(1),
    IS_GEVESTIGD_IN_VERBLIJFSOBJECT_ID NUMBER,
    KLOKURENONDERWIJS VARCHAR2(255),
    KLOKURENVERENIGINGEN VARCHAR2(255),
    LOCATIE VARCHAR2(255),
    ONDERHOUDSNIVEAU VARCHAR2(80),
    ONDERHOUDSSTATUS NUMBER,
    SPORTHAL NUMBER(1),
    VLOEROPPERVLAKTE NUMBER
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR2(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR2(200),
    DOCUMENTIDENTIFICATIE VARCHAR2(255),
    DOCUMENTTITEL VARCHAR2(200),
    INSPECTIERAPPORT_SPORTLOCATIE_ID NUMBER,
    VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE SPORTPARK (
    SPORTLOCATIE_ID NUMBER PRIMARY KEY,
    LIGT_OP_OVERIGBENOEMDTERREIN_ID NUMBER
);

CREATE TABLE VELD (
    VELD_ID NUMBER PRIMARY KEY,
    HEEFT_SPORTLOCATIE_ID NUMBER,
    LIGT_OP_OVERIGBENOEMDTERREIN_ID NUMBER
);

CREATE TABLE KP_BNNNLCT_SPRTLCT (
    KP_BNNNLCT_SPRTLCT_ID NUMBER PRIMARY KEY,
    BINNENLOCATIE_ID NUMBER,
    SPORTLOCATIE_ID NUMBER
);

CREATE TABLE KP_SPRTPRK_SPRTLCT (
    KP_SPRTPRK_SPRTLCT_ID NUMBER PRIMARY KEY,
    SPORTPARK_ID NUMBER,
    SPORTLOCATIE_ID NUMBER
);

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_GEN_SPORTLOCATIE FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- Generalization to SPORTLOCATIE

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_GEN_SPORTLOCATIE FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- Generalization to SPORTLOCATIE

ALTER TABLE KP_SPRTPRK_SPRTLCT ADD CONSTRAINT FK_KP_SPRTPRK_SPRTLCT_1 FOREIGN KEY (SPORTPARK_ID) REFERENCES SPORTPARK (SPORTLOCATIE_ID);
-- SPORTPARK (many-to-many junction, Connector_ID: 1086)

ALTER TABLE KP_SPRTPRK_SPRTLCT ADD CONSTRAINT FK_KP_SPRTPRK_SPRTLCT_2 FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1086)

ALTER TABLE KP_BNNNLCT_SPRTLCT ADD CONSTRAINT FK_KP_BNNNLCT_SPRTLCT_1 FOREIGN KEY (BINNENLOCATIE_ID) REFERENCES BINNENLOCATIE (SPORTLOCATIE_ID);
-- BINNENLOCATIE (many-to-many junction, Connector_ID: 1095)

ALTER TABLE KP_BNNNLCT_SPRTLCT ADD CONSTRAINT FK_KP_BNNNLCT_SPRTLCT_2 FOREIGN KEY (SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- SPORTLOCATIE (many-to-many junction, Connector_ID: 1095)

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_INSPECTIERAPPORT FOREIGN KEY (INSPECTIERAPPORT_SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- INSPECTIERAPPORT (0..1 to 0..*, Connector_ID: 115)

ALTER TABLE VELD ADD CONSTRAINT FK_VELD_LIGT_OP FOREIGN KEY (LIGT_OP_OVERIGBENOEMDTERREIN_ID) REFERENCES OVERIGBENOEMDTERREIN (OVERIGBENOEMDTERREIN_ID);
-- LIGT_OP (0..1 to 1, Connector_ID: 1082)

ALTER TABLE SPORTPARK ADD CONSTRAINT FK_SPORTPARK_LIGT_OP FOREIGN KEY (LIGT_OP_OVERIGBENOEMDTERREIN_ID) REFERENCES OVERIGBENOEMDTERREIN (OVERIGBENOEMDTERREIN_ID);
-- LIGT_OP (0..1 to 1, Connector_ID: 1084)

ALTER TABLE VELD ADD CONSTRAINT FK_VELD_HEEFT FOREIGN KEY (HEEFT_SPORTLOCATIE_ID) REFERENCES SPORTLOCATIE (SPORTLOCATIE_ID);
-- HEEFT (0..1 to 0..*, Connector_ID: 1085)

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_BEDIENT FOREIGN KEY (BEDIENT_WIJK_ID) REFERENCES WIJK (WIJK_ID);
-- BEDIENT (0..* to 1, Connector_ID: 1093)

ALTER TABLE BINNENLOCATIE ADD CONSTRAINT FK_BINNENLOCATIE_IS_GEVESTIGD_IN FOREIGN KEY (IS_GEVESTIGD_IN_VERBLIJFSOBJECT_ID) REFERENCES VERBLIJFSOBJECT (VERBLIJFSOBJECT_ID);
-- IS_GEVESTIGD_IN (0..* to 0..1, Connector_ID: 1094)

