CREATE TABLE AANTAL_GEHINDERDEN_ENUM (
    AANTAL_GEHINDERDEN_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO AANTAL_GEHINDERDEN_ENUM (AANTAL_GEHINDERDEN_ENUM_ID, VALUE) VALUES
    (1, '100_000_TOT_1_000_000'),
    (2, '10_000_TOT_100_000'),
    (3, '1_000_TOT_10_000'),
    (4, 'MEER_DAN_1_000_000'),
    (5, 'MINDER_DAN_1000');

CREATE TABLE KP_STRMMNG_WGDL (
    KP_STRMMNG_WGDL_ID NUMBER PRIMARY KEY,
    STREMMING_ID NUMBER,
    WEGDEEL_ID NUMBER
);

CREATE TABLE STREMMINGSTATUS_ENUM (
    STREMMINGSTATUS_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO STREMMINGSTATUS_ENUM (STREMMINGSTATUS_ENUM_ID, VALUE) VALUES
    (1, 'AANGEMELD'),
    (2, 'AFGEROND'),
    (3, 'GEPULBLICEERD'),
    (4, 'IN_UITVOERING'),
    (5, 'PLAN_AFHANDELEN');

CREATE TABLE STREMMING (
    STREMMING_ID NUMBER PRIMARY KEY,
    AANTALGEHINDERDEN NUMBER,
    DATUMAANMELDING DATE,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DATUMWIJZIGING DATE,
    DELENTOEGESTAAN NUMBER(1),
    GESCHIKTVOORPUBLICATIE NUMBER(1),
    HINDERKLASSE_ENUM_ID NUMBER,
    LOCATIE VARCHAR2(255),
    NAAM VARCHAR2(255),
    STATUS_ENUM_ID NUMBER
);

CREATE TABLE HINDERKLASSE_ENUM (
    HINDERKLASSE_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO HINDERKLASSE_ENUM (HINDERKLASSE_ENUM_ID, VALUE) VALUES
    (1, 'KLASSE_0_GEEN_HINDER'),
    (2, 'KLASSE_1_KLEINE_HINDER'),
    (3, 'KLASSE_2_MATIGE_HINDER'),
    (4, 'KLASSE_3_GROTE_HINDER'),
    (5, 'KLASSE_4_ZEER_GROTE_HINDER');

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    ACHTERNAAM VARCHAR2(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR2(255),
    EXTERN NUMBER(1),
    FUNCTIE VARCHAR2(50),
    GESLACHTSAANDUIDING VARCHAR2(255),
    GEWIJZIGD_DOOR_STREMMING_ID NUMBER,
    INGEVOERD_DOOR_STREMMING_ID NUMBER,
    MEDEWERKERIDENTIFICATIE VARCHAR2(255),
    MEDEWERKERTOELICHTING VARCHAR2(255),
    ROEPNAAM VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    VOORLETTERS VARCHAR2(20),
    VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE HINDERCATEGORIE_ENUM (
    HINDERCATEGORIE_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO HINDERCATEGORIE_ENUM (HINDERCATEGORIE_ENUM_ID, VALUE) VALUES
    (1, 'A'),
    (2, 'B'),
    (3, 'C'),
    (4, 'D'),
    (5, 'E');

CREATE TABLE WEGDEEL (
    WEGDEEL_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDWEGDEEL DATE,
    DATUMEINDEGELDIGHEIDWEGDEEL DATE,
    FUNCTIEWEGDEEL VARCHAR2(255),
    FYSIEKVOORKOMENWEGDEEL VARCHAR2(255),
    GEOMETRIEWEGDEEL SDO_GEOMETRY,
    IDENTIFICATIEWEGDEEL VARCHAR2(255),
    KRUINLIJNGEOMETRIEWEGDEEL SDO_GEOMETRY,
    LOD0GEOMETRIEWEGDEEL SDO_GEOMETRY,
    PLUSFUNCTIEWEGDEEL VARCHAR2(255),
    PLUSFYSIEKVOORKOMENWEGDEEL VARCHAR2(255),
    RELATIEVEHOOGTELIGGINGWEGDEEL VARCHAR2(255),
    STATUSWEGDEEL VARCHAR2(255),
    WEGDEELOPTALUD NUMBER(1)
);

ALTER TABLE KP_STRMMNG_WGDL ADD CONSTRAINT FK_KP_STRMMNG_WGDL_1 FOREIGN KEY (STREMMING_ID) REFERENCES STREMMING (STREMMING_ID);
-- STREMMING (many-to-many junction, Connector_ID: 1268)

ALTER TABLE KP_STRMMNG_WGDL ADD CONSTRAINT FK_KP_STRMMNG_WGDL_2 FOREIGN KEY (WEGDEEL_ID) REFERENCES WEGDEEL (WEGDEEL_ID);
-- WEGDEEL (many-to-many junction, Connector_ID: 1268)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_GEWIJZIGD_DOOR FOREIGN KEY (GEWIJZIGD_DOOR_STREMMING_ID) REFERENCES STREMMING (STREMMING_ID);
-- GEWIJZIGD_DOOR (0..1 to 0..*, Connector_ID: 2177)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_INGEVOERD_DOOR FOREIGN KEY (INGEVOERD_DOOR_STREMMING_ID) REFERENCES STREMMING (STREMMING_ID);
-- INGEVOERD_DOOR (1 to 0..*, Connector_ID: 2180)

ALTER TABLE STREMMING ADD CONSTRAINT FK_STREMMING_HINDERKLASSE_ENUM_ID FOREIGN KEY (HINDERKLASSE_ENUM_ID) REFERENCES HINDERKLASSE_ENUM (HINDERKLASSE_ENUM_ID);
-- HINDERKLASSE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE STREMMING ADD CONSTRAINT FK_STREMMING_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID) REFERENCES STREMMINGSTATUS_ENUM (STREMMINGSTATUS_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

