CREATE TABLE AANTAL_GEHINDERDEN_ENUM (
    AANTAL_GEHINDERDEN_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO AANTAL_GEHINDERDEN_ENUM (AANTAL_GEHINDERDEN_ENUM_ID, VALUE) VALUES
    (1, '100_000_TOT_1_000_000'),
    (2, '10_000_TOT_100_000'),
    (3, '1_000_TOT_10_000'),
    (4, 'MEER_DAN_1_000_000'),
    (5, 'MINDER_DAN_1000');

CREATE TABLE KP_STRMMNG_WGDL (
    KP_STRMMNG_WGDL_ID INTEGER PRIMARY KEY,
    STREMMING_ID INTEGER,
    WEGDEEL_ID INTEGER
);

CREATE TABLE STREMMINGSTATUS_ENUM (
    STREMMINGSTATUS_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO STREMMINGSTATUS_ENUM (STREMMINGSTATUS_ENUM_ID, VALUE) VALUES
    (1, 'AANGEMELD'),
    (2, 'AFGEROND'),
    (3, 'GEPULBLICEERD'),
    (4, 'IN_UITVOERING'),
    (5, 'PLAN_AFHANDELEN');

CREATE TABLE STREMMING (
    STREMMING_ID INTEGER PRIMARY KEY,
    AANTALGEHINDERDEN INTEGER,
    DATUMAANMELDING DATE,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DATUMWIJZIGING DATE,
    DELENTOEGESTAAN BOOLEAN,
    GESCHIKTVOORPUBLICATIE BOOLEAN,
    HINDERKLASSE_ENUM_ID INTEGER,
    LOCATIE VARCHAR(255),
    NAAM VARCHAR(255),
    STATUS_ENUM_ID INTEGER
);

CREATE TABLE HINDERKLASSE_ENUM (
    HINDERKLASSE_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO HINDERKLASSE_ENUM (HINDERKLASSE_ENUM_ID, VALUE) VALUES
    (1, 'KLASSE_0_GEEN_HINDER'),
    (2, 'KLASSE_1_KLEINE_HINDER'),
    (3, 'KLASSE_2_MATIGE_HINDER'),
    (4, 'KLASSE_3_GROTE_HINDER'),
    (5, 'KLASSE_4_ZEER_GROTE_HINDER');

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID INTEGER PRIMARY KEY,
    ACHTERNAAM VARCHAR(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR(255),
    EXTERN BOOLEAN,
    FUNCTIE VARCHAR(50),
    GESLACHTSAANDUIDING VARCHAR(255),
    GEWIJZIGD_DOOR_STREMMING_ID INTEGER,
    INGEVOERD_DOOR_STREMMING_ID INTEGER,
    MEDEWERKERIDENTIFICATIE VARCHAR(255),
    MEDEWERKERTOELICHTING VARCHAR(255),
    ROEPNAAM VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20),
    VOORLETTERS VARCHAR(20),
    VOORVOEGSELACHTERNAAM VARCHAR(255)
);

CREATE TABLE HINDERCATEGORIE_ENUM (
    HINDERCATEGORIE_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO HINDERCATEGORIE_ENUM (HINDERCATEGORIE_ENUM_ID, VALUE) VALUES
    (1, 'A'),
    (2, 'B'),
    (3, 'C'),
    (4, 'D'),
    (5, 'E');

CREATE TABLE WEGDEEL (
    WEGDEEL_ID INTEGER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDWEGDEEL DATE,
    DATUMEINDEGELDIGHEIDWEGDEEL DATE,
    FUNCTIEWEGDEEL VARCHAR(255),
    FYSIEKVOORKOMENWEGDEEL VARCHAR(255),
    GEOMETRIEWEGDEEL GEOMETRY,
    IDENTIFICATIEWEGDEEL VARCHAR(255),
    KRUINLIJNGEOMETRIEWEGDEEL GEOMETRY,
    LOD0GEOMETRIEWEGDEEL GEOMETRY,
    PLUSFUNCTIEWEGDEEL VARCHAR(255),
    PLUSFYSIEKVOORKOMENWEGDEEL VARCHAR(255),
    RELATIEVEHOOGTELIGGINGWEGDEEL VARCHAR(255),
    STATUSWEGDEEL VARCHAR(255),
    WEGDEELOPTALUD BOOLEAN
);

ALTER TABLE KP_STRMMNG_WGDL ADD CONSTRAINT FK_KP_STRMMNG_WGDL_1 FOREIGN KEY (STREMMING_ID) REFERENCES STREMMING (STREMMING_ID);
-- STREMMING (many-to-many junction, Connector_ID: 1268)

ALTER TABLE KP_STRMMNG_WGDL ADD CONSTRAINT FK_KP_STRMMNG_WGDL_2 FOREIGN KEY (WEGDEEL_ID) REFERENCES WEGDEEL (WEGDEEL_ID);
-- WEGDEEL (many-to-many junction, Connector_ID: 1268)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_GEWIJZIGD_DOOR FOREIGN KEY (GEWIJZIGD_DOOR_STREMMING_ID) REFERENCES STREMMING (STREMMING_ID);
-- GEWIJZIGD_DOOR (0..1 to 0..*, Connector_ID: 2177)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_INGEVOERD_DOOR FOREIGN KEY (INGEVOERD_DOOR_STREMMING_ID) REFERENCES STREMMING (STREMMING_ID);
-- INGEVOERD_DOOR (1 to 0..*, Connector_ID: 2180)

ALTER TABLE STREMMING ADD CONSTRAINT FK_STREMMING_STATUS_ENUM_ID FOREIGN KEY (STATUS_ENUM_ID) REFERENCES STREMMINGSTATUS_ENUM (STREMMINGSTATUS_ENUM_ID);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE STREMMING ADD CONSTRAINT FK_STREMMING_HINDERKLASSE_ENUM_ID FOREIGN KEY (HINDERKLASSE_ENUM_ID) REFERENCES HINDERKLASSE_ENUM (HINDERKLASSE_ENUM_ID);
-- HINDERKLASSE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

