CREATE TABLE AANVRAAG (
    AANVRAAG_ID VARCHAR2(255) PRIMARY KEY,
        AANVRAAGDATUM DATE,
        AANVRAAGID DATE,
        CODE_ONTVANGENDE_GEMEENTE DATE
);

CREATE TABLE DIENST (
    DIENST_ID VARCHAR2(255) PRIMARY KEY,
        AANTAL_KOSTENDELERS NUMBER(10,2),
        BEGINDATUM DATE,
        DIENSTID VARCHAR2(255),
        EINDDATUM DATE,
        PERIODICITEIT_STATUSFORMULIER VARCHAR2(255),
        STARTDATUM_STATUSFORMULIER DATE
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID VARCHAR2(255) PRIMARY KEY,
        BTWCODE VARCHAR2(255),
        BTWOMSCHRIJVING VARCHAR2(80),
        KOSTENPLAATSSOORTCODE NUMBER(10,2),
        KOSTENPLAATSSOORTOMSCHRIJVING NUMBER(10,2),
        KOSTENPLAATSTYPECODE NUMBER(10,2),
        KOSTENPLAATSTYPEOMSCHRIJVING NUMBER(10,2),
        NAAM VARCHAR2(80),
        OMSCHRIJVING VARCHAR2(200)
);

CREATE TABLE LEVERINGSCOMPONENT (
    LEVERINGSCOMPONENT_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG NUMBER(10,2),
        EINDDATUM DATE,
        GEVALSRUBRIEK VARCHAR2(255),
        HEEFT_KOSTENPLAATS_ID VARCHAR2(255),
        LEVERINGSCOMPONENT_ID VARCHAR2(255),
        OMSCHRIJVING_AFWIJKING VARCHAR2(255),
        PERCENTAGE VARCHAR2(255),
        PERIODE_STARTDATUM DATE,
        SOORT VARCHAR2(255)
);

CREATE TABLE LEVERINGSSPECIFICATIE (
    LEVERINGSSPECIFICATIE_ID VARCHAR2(255) PRIMARY KEY,
        LEVERINGSSPECIFICATIE_BESTAAT_UIT_LEVERINGSCOMPONENT_LEVERINGSCOMPONENT_ID VARCHAR2(255),
        LEVERINGSSPECIFICATIE_ID VARCHAR2(255),
        PERIODE_EINDDATUM DATE,
        PERIODE_STARTDATUM DATE,
        PERIODICITEIT VARCHAR2(255)
);

CREATE TABLE LEVERINGSOPDRACHT (
    LEVERINGSOPDRACHT_ID VARCHAR2(255) PRIMARY KEY,
        LEVERINGSKANAAL VARCHAR2(255),
        LEVERINGSOPDRACHT_BESTAAT_UIT_LEVERINGSSPECIFICATIE_LEVERINGSSPECIFICATIE_ID VARCHAR2(255),
        LEVERINGSOPDRACHT_ID VARCHAR2(255),
        LEVERINGSOPDRACHT_IN_KADER_VAN_DIENST_DIENST_ID VARCHAR2(255)
);

CREATE TABLE NORMAFWIJKING (
    NORMAFWIJKING_ID VARCHAR2(255) PRIMARY KEY,
        DATUM_VASTSTELLING_NORMAFWIJKING DATE,
        DATUM_VASTSTELLING_VERWIJTBAARHEID DATE,
        MOTIVATIE_VERWIJTBAARHEID DATE,
        NORMAFWIJKING_ID DATE,
        RECIDIVE VARCHAR2(255),
        TYPE_NORMAFWIJKING VARCHAR2(255),
        VERWIJTBAARHEID VARCHAR2(255)
);

CREATE TABLE PROFIEL (
    PROFIEL_ID VARCHAR2(255) PRIMARY KEY,
        BEVAT_REDEN_AANVRAAG_ID VARCHAR2(255),
        DATUMAANVANGPROFIEL DATE,
        DATUMEINDEPROFIEL DATE,
        PROFIELID NUMBER,
        PROFIELTYPE VARCHAR2(200)
);

CREATE TABLE CLIENT (
    CLIENT_ID VARCHAR2(255) PRIMARY KEY,
        CODE VARCHAR2(80),
        DOET_AANVRAAG_AANVRAAG_ID VARCHAR2(255),
        GEZAGSDRAGERGEKEND NUMBER(1),
        HEEFT_PROFIEL_ID VARCHAR2(255),
        JURIDISCHESTATUS VARCHAR2(80),
        NEEMT_DIENST_AF_DIENST_ID VARCHAR2(255),
        VEROORZAAKT_NORMAFWIJKING_ID VARCHAR2(255),
        WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE DEBITEUR (
    DEBITEUR_ID VARCHAR2(255) PRIMARY KEY,
        DEBITEUR_ID VARCHAR2(255),
        EIGEN_KENMERK VARCHAR2(255),
        OPVOERDATUM DATE,
        SOORT_DEBITEUR VARCHAR2(255),
        VERWIJST_CLIENT_ID VARCHAR2(255)
);

CREATE TABLE REDEN_AANVRAAG (
    REDEN_AANVRAAG_ID VARCHAR2(255) PRIMARY KEY,
        DIENSTTYPE VARCHAR2(255),
        GEWENSTE_INGANGSDATUM DATE
);

CREATE TABLE TERUGVORDERINGSVERZOEK (
    TERUGVORDERINGSVERZOEK_ID VARCHAR2(255) PRIMARY KEY,
        AANMAAKDATUM DATE,
        BEHANDELSTATUS_VERZOEK VARCHAR2(255),
        BETREFT_CLIENT_ID VARCHAR2(255),
        CATEGORIE VARCHAR2(255),
        FISCAAL VARCHAR2(255),
        PERIODE_EINDDATUM DATE,
        PERIODE_STARTDATUM DATE,
        PRIOTYPE DATE,
        REGELING VARCHAR2(255),
        SUBCATEGORIE VARCHAR2(255),
        TERUGVORDERINGSVERZOEK_BETREFT_DIENST_DIENST_ID VARCHAR2(255),
        TERUGVORDERINGSVERZOEK_ID DATE
);

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_DOET_AANVRAAG FOREIGN KEY (DOET_AANVRAAG_AANVRAAG_ID) REFERENCES AANVRAAG (AANVRAAG_ID);
-- DOET_AANVRAAG (1 to 0..*, Connector_ID: 1477)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT FOREIGN KEY (HEEFT_PROFIEL_ID) REFERENCES PROFIEL (PROFIEL_ID);
-- HEEFT (1 to 1..*, Connector_ID: 947)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_NEEMT_DIENST_AF FOREIGN KEY (NEEMT_DIENST_AF_DIENST_ID) REFERENCES DIENST (DIENST_ID);
-- NEEMT_DIENST_AF (1..2 to 0..*, Connector_ID: 1465)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_VEROORZAAKT FOREIGN KEY (VEROORZAAKT_NORMAFWIJKING_ID) REFERENCES NORMAFWIJKING (NORMAFWIJKING_ID);
-- VEROORZAAKT (1 to 0..*, Connector_ID: 1443)

ALTER TABLE DEBITEUR ADD CONSTRAINT FK_DEBITEUR_VERWIJST FOREIGN KEY (VERWIJST_CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- VERWIJST (0..1 to 1, Connector_ID: 1406)

ALTER TABLE LEVERINGSCOMPONENT ADD CONSTRAINT FK_LEVERINGSCOMPONENT_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..* to 0..1, Connector_ID: 1458)

ALTER TABLE LEVERINGSOPDRACHT ADD CONSTRAINT FK_LEVERINGSOPDRACHT_LEVERINGSOPDRACHT_BESTAAT_UIT_LEVERINGSSPECIFICATIE FOREIGN KEY (LEVERINGSOPDRACHT_BESTAAT_UIT_LEVERINGSSPECIFICATIE_LEVERINGSSPECIFICATIE_ID) REFERENCES LEVERINGSSPECIFICATIE (LEVERINGSSPECIFICATIE_ID);
-- LEVERINGSOPDRACHT_BESTAAT_UIT_LEVERINGSSPECIFICATIE (1..* to 1..1, Connector_ID: 1454)

ALTER TABLE LEVERINGSOPDRACHT ADD CONSTRAINT FK_LEVERINGSOPDRACHT_LEVERINGSOPDRACHT_IN_KADER_VAN_DIENST FOREIGN KEY (LEVERINGSOPDRACHT_IN_KADER_VAN_DIENST_DIENST_ID) REFERENCES DIENST (DIENST_ID);
-- LEVERINGSOPDRACHT_IN_KADER_VAN_DIENST (1..1 to 1..*, Connector_ID: 1467)

ALTER TABLE LEVERINGSSPECIFICATIE ADD CONSTRAINT FK_LEVERINGSSPECIFICATIE_LEVERINGSSPECIFICATIE_BESTAAT_UIT_LEVERINGSCOMPONENT FOREIGN KEY (LEVERINGSSPECIFICATIE_BESTAAT_UIT_LEVERINGSCOMPONENT_LEVERINGSCOMPONENT_ID) REFERENCES LEVERINGSCOMPONENT (LEVERINGSCOMPONENT_ID);
-- LEVERINGSSPECIFICATIE_BESTAAT_UIT_LEVERINGSCOMPONENT (1..* to 1..1, Connector_ID: 1456)

ALTER TABLE PROFIEL ADD CONSTRAINT FK_PROFIEL_BEVAT FOREIGN KEY (BEVAT_REDEN_AANVRAAG_ID) REFERENCES REDEN_AANVRAAG (REDEN_AANVRAAG_ID);
-- BEVAT (1 to 0..1, Connector_ID: 1429)

ALTER TABLE TERUGVORDERINGSVERZOEK ADD CONSTRAINT FK_TERUGVORDERINGSVERZOEK_BETREFT FOREIGN KEY (BETREFT_CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- BETREFT (0..* to 1..2, Connector_ID: 1387)

ALTER TABLE TERUGVORDERINGSVERZOEK ADD CONSTRAINT FK_TERUGVORDERINGSVERZOEK_TERUGVORDERINGSVERZOEK_BETREFT_DIENST FOREIGN KEY (TERUGVORDERINGSVERZOEK_BETREFT_DIENST_DIENST_ID) REFERENCES DIENST (DIENST_ID);
-- TERUGVORDERINGSVERZOEK_BETREFT_DIENST (1..1 to 0..*, Connector_ID: 1468)

