CREATE TABLE [AANVRAAG] (
    [AANVRAAG_ID] INT PRIMARY KEY,
        [AANVRAAGDATUM] DATE,
        [AANVRAAGID] DATE,
        [AANVRAAG_LEIDT_TOT_BESLUIT_BESLUIT_ID] INT,
        [CODE_ONTVANGENDE_GEMEENTE] DATE
);

CREATE TABLE [AANVRAAGTYPE] (
    [AANVRAAGTYPE_ID] INT PRIMARY KEY,
        [AANVRAAGTYPEID] VARCHAR(255),
        [AANVRAAGTYPE_BESCHRIJFT_AANVRAAG_AANVRAAG_ID] INT,
        [AANVRAAGTYPE_BETREFT_DIENSTTYPE_DIENSTTYPE_ID] INT,
        [EINDDATUM] DATE,
        [NAAM] VARCHAR(255),
        [SOORT_AANVRAAG] VARCHAR(255),
        [STARTDATUM] DATE
);

CREATE TABLE [BESCHIKKING] (
    [BESCHIKKING_ID] INT PRIMARY KEY,
        [BESCHIKKING_BEVAT_ONDERDEEL_BESCHIKKING_ONDERDEEL_BESCHIKKING_ID] INT,
        [DATUM_BESSCHIKKING] DATE
);

CREATE TABLE [BESLUIT] (
    [BESLUIT_ID] INT PRIMARY KEY,
        [BESLUIT_INITIEERT_DIENST_DIENST_ID] INT,
        [BESLUIT_LEIDT_TOT_BESCHIKKING_BESCHIKKING_ID] INT,
        [DATUM_BESLISSING] DATE
);

CREATE TABLE [BETALINGSBLOKKADE] (
    [BETALINGSBLOKKADE_ID] INT PRIMARY KEY,
        [AANDUIDING] VARCHAR(255),
        [BETALINGSBLOKKADE_ID] VARCHAR(255),
        [DIRECT_BLOKKEREN] VARCHAR(255),
        [INITIËLE_AANMAAKDATUM] DATE,
        [REDEN] VARCHAR(255)
);

CREATE TABLE [DIENST] (
    [DIENST_ID] INT PRIMARY KEY,
        [AANTAL_KOSTENDELERS] DECIMAL(10,2),
        [BEGINDATUM] DATE,
        [DIENSTID] VARCHAR(255),
        [DIENST_HEEFT_REFERTEPERIODE_REFERTEPERIODE_ID] INT,
        [DIENST_ONDERGAAT_BETALINGSBLOKKADE_BETALINGSBLOKKADE_ID] INT,
        [DIENST_VEREIST_INDIVIDUELE_PLICHT_INDIVIDUELE_PLICHT_ID] INT,
        [EINDDATUM] DATE,
        [PERIODICITEIT_STATUSFORMULIER] VARCHAR(255),
        [STARTDATUM_STATUSFORMULIER] DATE
);

CREATE TABLE [DIENSTTYPE] (
    [DIENSTTYPE_ID] INT PRIMARY KEY,
        [DIENSTTYPE_BESCHRIJFT_DIENST_DIENST_ID] INT,
        [DIENSTTYPE_BEVAT_ONDERDEEL_BESCHIKKING_ONDERDEEL_BESCHIKKING_ID] INT,
        [DIENSTTYPE_HEEFT_LEVERINGSCOMPONENTTYPE_LEVERINGSCOMPONENTTYPE_ID] INT,
        [DIENSTTYPE_HEEFT_VERSTREKKINGSVORM_VERSTREKKINGSVORM_ID] INT,
        [DIENSTTYPE_ID] VARCHAR(255),
        [DUUR_REFERTEPERIODE] VARCHAR(255),
        [EINDDATUM] DATE,
        [MINIMAAL_VEREIST_BETROUWBAARHEIDSNIVEAU_EDIENSTVERLENING] VARCHAR(255),
        [NAAM] VARCHAR(255),
        [PERIODICITEIT] VARCHAR(255),
        [PERIODICITEIT_INKOMSTENFORMULIER] VARCHAR(255),
        [STARTDATUM] DATE,
        [TYPE_REFERTEPERIODEBEPALING] VARCHAR(255)
);

CREATE TABLE [INDIVIDUELE_PLICHT] (
    [INDIVIDUELE_PLICHT_ID] INT PRIMARY KEY
);

CREATE TABLE [KP_DNSTTYP] (
    [KP_DNSTTYP_ID] INT PRIMARY KEY,
    [DIENSTTYPE_ID] INT,
    [VOORWAARDETYPE_ID] INT
);

CREATE TABLE [KP_RCHT] (
    [KP_RCHT_ID] INT PRIMARY KEY,
    [RECHT_ID] INT,
    [VOORWAARDE_ID] INT
);

CREATE TABLE [KP_VRWRD] (
    [KP_VRWRD_ID] INT PRIMARY KEY,
    [VOORWAARDE_IS_OPGEBOUWD_UIT_VOORWAARDE_1_ID] INT,
    [VOORWAARDE_IS_OPGEBOUWD_UIT_VOORWAARDE_2_ID] INT
);

CREATE TABLE [LEVERINGSCOMPONENT] (
    [LEVERINGSCOMPONENT_ID] INT PRIMARY KEY,
        [BEDRAG] DECIMAL(10,2),
        [EINDDATUM] DATE,
        [GEVALSRUBRIEK] VARCHAR(255),
        [LEVERINGSCOMPONENT_ID] VARCHAR(255),
        [OMSCHRIJVING_AFWIJKING] VARCHAR(255),
        [PERCENTAGE] VARCHAR(255),
        [PERIODE_STARTDATUM] DATE,
        [SOORT] VARCHAR(255)
);

CREATE TABLE [LEVERINGSCOMPONENTTYPE] (
    [LEVERINGSCOMPONENTTYPE_ID] INT PRIMARY KEY,
        [AFWIJKENDE_NORM] VARCHAR(255),
        [EINDDATUM] DATE,
        [FISCAAL] VARCHAR(255),
        [KOSTENSOORT] DECIMAL(10,2),
        [LEVERINGSCOMPONENTTYPE_BESCHRIJFT_LEVERINGSCOMPONENT_LEVERINGSCOMPONENT_ID] INT,
        [LEVERINGSCOMPONENTTYPE_ID] VARCHAR(255),
        [NORMBEDRAG] DECIMAL(10,2),
        [NORMPERCENTAGE] VARCHAR(255),
        [RUBRIEK] VARCHAR(255),
        [SOORT_WETTELIJKE_NORM] VARCHAR(255),
        [STARTDATUM] DATE
);

CREATE TABLE [LEVERINGSOPDRACHT] (
    [LEVERINGSOPDRACHT_ID] INT PRIMARY KEY,
        [LEVERINGSKANAAL] VARCHAR(255),
        [LEVERINGSOPDRACHT_BESTAAT_UIT_LEVERINGSSPECIFICATIE_LEVERINGSSPECIFICATIE_ID] INT,
        [LEVERINGSOPDRACHT_HEEFT_VERSTREKKINGSVORM_VERSTREKKINGSVORM_ID] INT,
        [LEVERINGSOPDRACHT_ID] VARCHAR(255),
        [LEVERINGSOPDRACHT_IN_KADER_VAN_DIENST_DIENST_ID] INT
);

CREATE TABLE [LEVERINGSSPECIFICATIE] (
    [LEVERINGSSPECIFICATIE_ID] INT PRIMARY KEY,
        [LEVERINGSSPECIFICATIE_BESTAAT_UIT_LEVERINGSCOMPONENT_LEVERINGSCOMPONENT_ID] INT,
        [LEVERINGSSPECIFICATIE_ID] VARCHAR(255),
        [PERIODE_EINDDATUM] DATE,
        [PERIODE_STARTDATUM] DATE,
        [PERIODICITEIT] VARCHAR(255)
);

CREATE TABLE [ONDERDEEL_BESCHIKKING] (
    [ONDERDEEL_BESCHIKKING_ID] INT PRIMARY KEY,
        [BESCHIKKINGDIENSTTYPEID] VARCHAR(255),
        [DATUM_BESSCHIKKING_DIENSTTYPE] DATE,
        [REDEN_BESCHIKKING_DIENSTTYPE] VARCHAR(255)
);

CREATE TABLE [PERIODIEK_DIENST_BIJZ_BIJSTAND_] (
    [PERIODIEK_DIENST_BIJZ_BIJSTAND__ID] INT PRIMARY KEY,
        [BEDRAG] DECIMAL(10,2),
        [EINDDATUM] DATE,
        [FISCAAL] VARCHAR(255),
        [KOSTENSOORT] DECIMAL(10,2),
        [PERIODICITEIT] VARCHAR(255),
        [PERIODIEKDIENSTBIJZBIJSTAND_ID] VARCHAR(255),
        [STARTDATUM] DATE
);

CREATE TABLE [RECHT] (
    [RECHT_ID] INT PRIMARY KEY,
        [BEGINDATUM_VAN_HET_RECHT] DATE,
        [BESCHRIJVING] DATE,
        [EINDDATUM_VAN_HET_RECHT] DATE,
        [RECHTID] DATE,
        [RECHT_IS_GRONDSLAG_VOOR_BESLUIT_BESLUIT_ID] INT,
        [VASTSTELDATUM_VAN_HET_RECHT] DATE
);

CREATE TABLE [REFERTEPERIODE] (
    [REFERTEPERIODE_ID] INT PRIMARY KEY,
        [EINDDATUM] DATE,
        [REFERTEPERIODE_ID] VARCHAR(255),
        [STARTDATUM] DATE
);

CREATE TABLE [REGELING] (
    [REGELING_ID] INT PRIMARY KEY,
        [BESCHRIJVING] VARCHAR(255),
        [EINDDATUM] DATE,
        [NAAM] VARCHAR(255),
        [REGELING_BEVAT_DIENSTTYPE_DIENSTTYPE_ID] INT,
        [REGELING_ID] VARCHAR(255),
        [STARTDATUM] DATE
);

CREATE TABLE [UITSLUITINGSGROND] (
    [VOORWAARDE_ID] INT PRIMARY KEY,
        [TYPE] VARCHAR(255),
        [UITSLUITINGSGROND_ID] VARCHAR(255)
);

CREATE TABLE [VERSTREKKINGSVORM] (
    [VERSTREKKINGSVORM_ID] INT PRIMARY KEY,
        [NAAM] VARCHAR(255),
        [TYPE] VARCHAR(255),
        [VERSTREKKINGSVORM_ID] VARCHAR(255)
);

CREATE TABLE [VOORLIGGENDE_VOORZIENING] (
    [VOORWAARDE_ID] INT PRIMARY KEY,
        [TYPE] VARCHAR(255),
        [VOORLIGGENDE_VOORZIENING_ID] VARCHAR(255)
);

CREATE TABLE [VOORWAARDE] (
    [VOORWAARDE_ID] INT PRIMARY KEY,
        [BRONTYPE] VARCHAR(255),
        [CONCLUSIE] VARCHAR(255),
        [VASTLEGGINGSDATUM] DATE,
        [VERANTWOORDING_VASTSTELLING] VARCHAR(255),
        [VOORWAARDEID] VARCHAR(255)
);

CREATE TABLE [VOORWAARDETYPE] (
    [VOORWAARDETYPE_ID] INT PRIMARY KEY,
        [BESCHRIJVING] VARCHAR(255),
        [VOORWAARDETYPEID] VARCHAR(255),
        [VOORWAARDETYPE_BESCHRIJFT_VOORWAARDE_VOORWAARDE_ID] INT
);

ALTER TABLE [UITSLUITINGSGROND] ADD CONSTRAINT FK_UITSLUITINGSGROND_GEN_VOORWAARDE FOREIGN KEY ([VOORWAARDE_ID]) REFERENCES [VOORWAARDE] ([VOORWAARDE_ID]);
-- Generalization to VOORWAARDE

ALTER TABLE [VOORLIGGENDE_VOORZIENING] ADD CONSTRAINT FK_VOORLIGGENDE_VOORZIENING_GEN_VOORWAARDE FOREIGN KEY ([VOORWAARDE_ID]) REFERENCES [VOORWAARDE] ([VOORWAARDE_ID]);
-- Generalization to VOORWAARDE

ALTER TABLE [KP_DNSTTYP] ADD CONSTRAINT FK_KP_DNSTTYP_1 FOREIGN KEY ([DIENSTTYPE_ID]) REFERENCES [DIENSTTYPE] ([DIENSTTYPE_ID]);
-- DIENSTTYPE (many-to-many junction, Connector_ID: 1464)

ALTER TABLE [KP_DNSTTYP] ADD CONSTRAINT FK_KP_DNSTTYP_2 FOREIGN KEY ([VOORWAARDETYPE_ID]) REFERENCES [VOORWAARDETYPE] ([VOORWAARDETYPE_ID]);
-- VOORWAARDETYPE (many-to-many junction, Connector_ID: 1464)

ALTER TABLE [KP_RCHT] ADD CONSTRAINT FK_KP_RCHT_1 FOREIGN KEY ([RECHT_ID]) REFERENCES [RECHT] ([RECHT_ID]);
-- RECHT (many-to-many junction, Connector_ID: 1453)

ALTER TABLE [KP_RCHT] ADD CONSTRAINT FK_KP_RCHT_2 FOREIGN KEY ([VOORWAARDE_ID]) REFERENCES [VOORWAARDE] ([VOORWAARDE_ID]);
-- VOORWAARDE (many-to-many junction, Connector_ID: 1453)

ALTER TABLE [KP_VRWRD] ADD CONSTRAINT FK_KP_VRWRD_1 FOREIGN KEY ([VOORWAARDE_IS_OPGEBOUWD_UIT_VOORWAARDE_1_ID]) REFERENCES [VOORWAARDE] ([VOORWAARDE_ID]);
-- VOORWAARDE (many-to-many junction, Connector_ID: 1450)

ALTER TABLE [KP_VRWRD] ADD CONSTRAINT FK_KP_VRWRD_2 FOREIGN KEY ([VOORWAARDE_IS_OPGEBOUWD_UIT_VOORWAARDE_2_ID]) REFERENCES [VOORWAARDE] ([VOORWAARDE_ID]);
-- VOORWAARDE (many-to-many junction, Connector_ID: 1450)

ALTER TABLE [AANVRAAG] ADD CONSTRAINT FK_AANVRAAG_AANVRAAG_LEIDT_TOT_BESLUIT FOREIGN KEY ([AANVRAAG_LEIDT_TOT_BESLUIT_BESLUIT_ID]) REFERENCES [BESLUIT] ([BESLUIT_ID]);
-- AANVRAAG_LEIDT_TOT_BESLUIT (0..1 to 1..1, Connector_ID: 1479)

ALTER TABLE [AANVRAAGTYPE] ADD CONSTRAINT FK_AANVRAAGTYPE_AANVRAAGTYPE_BESCHRIJFT_AANVRAAG FOREIGN KEY ([AANVRAAGTYPE_BESCHRIJFT_AANVRAAG_AANVRAAG_ID]) REFERENCES [AANVRAAG] ([AANVRAAG_ID]);
-- AANVRAAGTYPE_BESCHRIJFT_AANVRAAG (0..* to 1..1, Connector_ID: 1478)

ALTER TABLE [AANVRAAGTYPE] ADD CONSTRAINT FK_AANVRAAGTYPE_AANVRAAGTYPE_BETREFT_DIENSTTYPE FOREIGN KEY ([AANVRAAGTYPE_BETREFT_DIENSTTYPE_DIENSTTYPE_ID]) REFERENCES [DIENSTTYPE] ([DIENSTTYPE_ID]);
-- AANVRAAGTYPE_BETREFT_DIENSTTYPE (1..* to 1..1, Connector_ID: 1476)

ALTER TABLE [BESCHIKKING] ADD CONSTRAINT FK_BESCHIKKING_BESCHIKKING_BEVAT_ONDERDEEL_BESCHIKKING FOREIGN KEY ([BESCHIKKING_BEVAT_ONDERDEEL_BESCHIKKING_ONDERDEEL_BESCHIKKING_ID]) REFERENCES [ONDERDEEL_BESCHIKKING] ([ONDERDEEL_BESCHIKKING_ID]);
-- BESCHIKKING_BEVAT_ONDERDEEL_BESCHIKKING (1..* to 1..1, Connector_ID: 1475)

ALTER TABLE [BESLUIT] ADD CONSTRAINT FK_BESLUIT_BESLUIT_INITIEERT_DIENST FOREIGN KEY ([BESLUIT_INITIEERT_DIENST_DIENST_ID]) REFERENCES [DIENST] ([DIENST_ID]);
-- BESLUIT_INITIEERT_DIENST (0..* to 1..1, Connector_ID: 1473)

ALTER TABLE [BESLUIT] ADD CONSTRAINT FK_BESLUIT_BESLUIT_LEIDT_TOT_BESCHIKKING FOREIGN KEY ([BESLUIT_LEIDT_TOT_BESCHIKKING_BESCHIKKING_ID]) REFERENCES [BESCHIKKING] ([BESCHIKKING_ID]);
-- BESLUIT_LEIDT_TOT_BESCHIKKING (1..1 to 1..1, Connector_ID: 1474)

ALTER TABLE [DIENST] ADD CONSTRAINT FK_DIENST_DIENST_HEEFT_REFERTEPERIODE FOREIGN KEY ([DIENST_HEEFT_REFERTEPERIODE_REFERTEPERIODE_ID]) REFERENCES [REFERTEPERIODE] ([REFERTEPERIODE_ID]);
-- DIENST_HEEFT_REFERTEPERIODE (0..1 to 1..1, Connector_ID: 1469)

ALTER TABLE [DIENST] ADD CONSTRAINT FK_DIENST_DIENST_ONDERGAAT_BETALINGSBLOKKADE FOREIGN KEY ([DIENST_ONDERGAAT_BETALINGSBLOKKADE_BETALINGSBLOKKADE_ID]) REFERENCES [BETALINGSBLOKKADE] ([BETALINGSBLOKKADE_ID]);
-- DIENST_ONDERGAAT_BETALINGSBLOKKADE (0..1 to 1..1, Connector_ID: 1471)

ALTER TABLE [DIENST] ADD CONSTRAINT FK_DIENST_DIENST_VEREIST_INDIVIDUELE_PLICHT FOREIGN KEY ([DIENST_VEREIST_INDIVIDUELE_PLICHT_INDIVIDUELE_PLICHT_ID]) REFERENCES [INDIVIDUELE_PLICHT] ([INDIVIDUELE_PLICHT_ID]);
-- DIENST_VEREIST_INDIVIDUELE_PLICHT (0..* to 1..1, Connector_ID: 1470)

ALTER TABLE [DIENSTTYPE] ADD CONSTRAINT FK_DIENSTTYPE_DIENSTTYPE_BESCHRIJFT_DIENST FOREIGN KEY ([DIENSTTYPE_BESCHRIJFT_DIENST_DIENST_ID]) REFERENCES [DIENST] ([DIENST_ID]);
-- DIENSTTYPE_BESCHRIJFT_DIENST (0..* to 1..1, Connector_ID: 1466)

ALTER TABLE [DIENSTTYPE] ADD CONSTRAINT FK_DIENSTTYPE_DIENSTTYPE_BEVAT_ONDERDEEL_BESCHIKKING FOREIGN KEY ([DIENSTTYPE_BEVAT_ONDERDEEL_BESCHIKKING_ONDERDEEL_BESCHIKKING_ID]) REFERENCES [ONDERDEEL_BESCHIKKING] ([ONDERDEEL_BESCHIKKING_ID]);
-- DIENSTTYPE_BEVAT_ONDERDEEL_BESCHIKKING (0..* to 1..1, Connector_ID: 1462)

ALTER TABLE [DIENSTTYPE] ADD CONSTRAINT FK_DIENSTTYPE_DIENSTTYPE_HEEFT_LEVERINGSCOMPONENTTYPE FOREIGN KEY ([DIENSTTYPE_HEEFT_LEVERINGSCOMPONENTTYPE_LEVERINGSCOMPONENTTYPE_ID]) REFERENCES [LEVERINGSCOMPONENTTYPE] ([LEVERINGSCOMPONENTTYPE_ID]);
-- DIENSTTYPE_HEEFT_LEVERINGSCOMPONENTTYPE (1..* to 1..1, Connector_ID: 1463)

ALTER TABLE [DIENSTTYPE] ADD CONSTRAINT FK_DIENSTTYPE_DIENSTTYPE_HEEFT_VERSTREKKINGSVORM FOREIGN KEY ([DIENSTTYPE_HEEFT_VERSTREKKINGSVORM_VERSTREKKINGSVORM_ID]) REFERENCES [VERSTREKKINGSVORM] ([VERSTREKKINGSVORM_ID]);
-- DIENSTTYPE_HEEFT_VERSTREKKINGSVORM (1..* to 1..1, Connector_ID: 1461)

ALTER TABLE [LEVERINGSCOMPONENTTYPE] ADD CONSTRAINT FK_LEVERINGSCOMPONENTTYPE_LEVERINGSCOMPONENTTYPE_BESCHRIJFT_LEVERINGSCOMPONENT FOREIGN KEY ([LEVERINGSCOMPONENTTYPE_BESCHRIJFT_LEVERINGSCOMPONENT_LEVERINGSCOMPONENT_ID]) REFERENCES [LEVERINGSCOMPONENT] ([LEVERINGSCOMPONENT_ID]);
-- LEVERINGSCOMPONENTTYPE_BESCHRIJFT_LEVERINGSCOMPONENT (0..* to 1..1, Connector_ID: 1457)

ALTER TABLE [LEVERINGSOPDRACHT] ADD CONSTRAINT FK_LEVERINGSOPDRACHT_LEVERINGSOPDRACHT_BESTAAT_UIT_LEVERINGSSPECIFICATIE FOREIGN KEY ([LEVERINGSOPDRACHT_BESTAAT_UIT_LEVERINGSSPECIFICATIE_LEVERINGSSPECIFICATIE_ID]) REFERENCES [LEVERINGSSPECIFICATIE] ([LEVERINGSSPECIFICATIE_ID]);
-- LEVERINGSOPDRACHT_BESTAAT_UIT_LEVERINGSSPECIFICATIE (1..* to 1..1, Connector_ID: 1454)

ALTER TABLE [LEVERINGSOPDRACHT] ADD CONSTRAINT FK_LEVERINGSOPDRACHT_LEVERINGSOPDRACHT_HEEFT_VERSTREKKINGSVORM FOREIGN KEY ([LEVERINGSOPDRACHT_HEEFT_VERSTREKKINGSVORM_VERSTREKKINGSVORM_ID]) REFERENCES [VERSTREKKINGSVORM] ([VERSTREKKINGSVORM_ID]);
-- LEVERINGSOPDRACHT_HEEFT_VERSTREKKINGSVORM (1..1 to 0..*, Connector_ID: 1455)

ALTER TABLE [LEVERINGSOPDRACHT] ADD CONSTRAINT FK_LEVERINGSOPDRACHT_LEVERINGSOPDRACHT_IN_KADER_VAN_DIENST FOREIGN KEY ([LEVERINGSOPDRACHT_IN_KADER_VAN_DIENST_DIENST_ID]) REFERENCES [DIENST] ([DIENST_ID]);
-- LEVERINGSOPDRACHT_IN_KADER_VAN_DIENST (1..1 to 1..*, Connector_ID: 1467)

ALTER TABLE [LEVERINGSSPECIFICATIE] ADD CONSTRAINT FK_LEVERINGSSPECIFICATIE_LEVERINGSSPECIFICATIE_BESTAAT_UIT_LEVERINGSCOMPONENT FOREIGN KEY ([LEVERINGSSPECIFICATIE_BESTAAT_UIT_LEVERINGSCOMPONENT_LEVERINGSCOMPONENT_ID]) REFERENCES [LEVERINGSCOMPONENT] ([LEVERINGSCOMPONENT_ID]);
-- LEVERINGSSPECIFICATIE_BESTAAT_UIT_LEVERINGSCOMPONENT (1..* to 1..1, Connector_ID: 1456)

ALTER TABLE [RECHT] ADD CONSTRAINT FK_RECHT_RECHT_IS_GRONDSLAG_VOOR_BESLUIT FOREIGN KEY ([RECHT_IS_GRONDSLAG_VOOR_BESLUIT_BESLUIT_ID]) REFERENCES [BESLUIT] ([BESLUIT_ID]);
-- RECHT_IS_GRONDSLAG_VOOR_BESLUIT (1..1 to 1..1, Connector_ID: 1472)

ALTER TABLE [REGELING] ADD CONSTRAINT FK_REGELING_REGELING_BEVAT_DIENSTTYPE FOREIGN KEY ([REGELING_BEVAT_DIENSTTYPE_DIENSTTYPE_ID]) REFERENCES [DIENSTTYPE] ([DIENSTTYPE_ID]);
-- REGELING_BEVAT_DIENSTTYPE (1..* to 1..1, Connector_ID: 1460)

ALTER TABLE [VOORWAARDETYPE] ADD CONSTRAINT FK_VOORWAARDETYPE_VOORWAARDETYPE_BESCHRIJFT_VOORWAARDE FOREIGN KEY ([VOORWAARDETYPE_BESCHRIJFT_VOORWAARDE_VOORWAARDE_ID]) REFERENCES [VOORWAARDE] ([VOORWAARDE_ID]);
-- VOORWAARDETYPE_BESCHRIJFT_VOORWAARDE (0..* to 1..1, Connector_ID: 1449)

