CREATE TABLE KP_WRKZMHDN_ALS_MNTLZRGR_WRKZMHDN_ANDRS_DAN_IN_ARBDSVRHDNG (
    KP_WRKZMHDN_ALS_MNTLZRGR_WRKZMHDN_ANDRS_DAN_IN_ARBDSVRHDNG_ID NUMBER PRIMARY KEY,
    WERKZAAMHEDEN_ALS_MANTELZORGER_ID NUMBER,
    WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_ID NUMBER
);

CREATE TABLE OPLEIDINGSNAAM (
    OPLEIDINGSNAAM_ID NUMBER PRIMARY KEY,
    NAAMOPLEIDING VARCHAR2(255)
);

CREATE TABLE OPLEIDINGSNAAMGECODEERD (
    OPLEIDINGSNAAM_ID NUMBER PRIMARY KEY,
    CODEOPLEIDINGSNAAM_ENUM_ID NUMBER,
    CODESOORTOPLEIDINGSNAAM VARCHAR2(255),
    HEEFT_SYNONIEM_OPLEIDINGSNAAM_ID NUMBER,
    INDICATIEOPLEIDINGSNAAMACTIEF VARCHAR2(255),
    OMSCHRIJVINGOPLEIDINGSNAAM VARCHAR2(255)
);

CREATE TABLE CODEOPLEIDINGSNAAM_ENUM (
    CODEOPLEIDINGSNAAM_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO CODEOPLEIDINGSNAAM_ENUM (CODEOPLEIDINGSNAAM_ENUM_ID, VALUE) VALUES (1, 'REFERENTIEOPLEIDING');
INSERT INTO CODEOPLEIDINGSNAAM_ENUM (CODEOPLEIDINGSNAAM_ENUM_ID, VALUE) VALUES (2, 'SYNONIEM');

CREATE TABLE CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (
    CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID, VALUE) VALUES (1, 'BASISNIVEAU');
INSERT INTO CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID, VALUE) VALUES (2, 'GEEN_BASISOPLEIDING');
INSERT INTO CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID, VALUE) VALUES (3, 'HBO_NIVEAU');
INSERT INTO CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID, VALUE) VALUES (4, 'LBO_MAVO_NIVEAU');
INSERT INTO CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID, VALUE) VALUES (5, 'MBO_HAVO_VWO_NIVEAU');
INSERT INTO CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID, VALUE) VALUES (6, 'NIET_VAN_TOEPASSING');
INSERT INTO CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID, VALUE) VALUES (7, 'WETENSCHAPPELIJK_ONDERWIJS');
INSERT INTO CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM (CODE_OPLEIDINGSNIVEAU_CLIËNT__ENUM_ID, VALUE) VALUES (8, '_NOG_NIET_BEKEND');

CREATE TABLE OPLEIDINGSRICHTING_ENUM (
    OPLEIDINGSRICHTING_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID, VALUE) VALUES (1, 'HOGER_ONDERWIJS_DERDE_FASE');
INSERT INTO OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID, VALUE) VALUES (2, 'HOGER_ONDERWIJS_EERSTE_FASE');
INSERT INTO OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID, VALUE) VALUES (3, 'HOGER_ONDERWIJS_TWEEDE_FASE');
INSERT INTO OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID, VALUE) VALUES (4, 'ONDERWIJS_AAN_KLEUTERS');
INSERT INTO OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID, VALUE) VALUES (5, 'PRIMAIR_ONDERWIJS');
INSERT INTO OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID, VALUE) VALUES (6, 'SECUNDAIR_ONDERWIJS_EERSTE_FASE');
INSERT INTO OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID, VALUE) VALUES (7, 'SECUNDAIR_ONDERWIJS_TWEEDE_FASE');

CREATE TABLE SOORT_ONTHEFFING__ENUM (
    SOORT_ONTHEFFING__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO SOORT_ONTHEFFING__ENUM (SOORT_ONTHEFFING__ENUM_ID, VALUE) VALUES (1, 'OUDER_MET_KIND_5');
INSERT INTO SOORT_ONTHEFFING__ENUM (SOORT_ONTHEFFING__ENUM_ID, VALUE) VALUES (2, 'SOCIAAL_MEDISCH_PERMANENT_');
INSERT INTO SOORT_ONTHEFFING__ENUM (SOORT_ONTHEFFING__ENUM_ID, VALUE) VALUES (3, 'SOCIAAL_MEDISCH_TIJDELIJK_');

CREATE TABLE KANAAL_CONTACTMOMENT__ENUM (
    KANAAL_CONTACTMOMENT__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO KANAAL_CONTACTMOMENT__ENUM (KANAAL_CONTACTMOMENT__ENUM_ID, VALUE) VALUES (1, 'BERICHTEN_VIA_THOMAS');
INSERT INTO KANAAL_CONTACTMOMENT__ENUM (KANAAL_CONTACTMOMENT__ENUM_ID, VALUE) VALUES (2, 'FYSIEK_GESPREK');
INSERT INTO KANAAL_CONTACTMOMENT__ENUM (KANAAL_CONTACTMOMENT__ENUM_ID, VALUE) VALUES (3, 'MAIL');
INSERT INTO KANAAL_CONTACTMOMENT__ENUM (KANAAL_CONTACTMOMENT__ENUM_ID, VALUE) VALUES (4, 'ONTVANGEN_CORRESPONDENTIE');
INSERT INTO KANAAL_CONTACTMOMENT__ENUM (KANAAL_CONTACTMOMENT__ENUM_ID, VALUE) VALUES (5, 'TELEFONISCH_GESPREK');

CREATE TABLE WERKZAAMHEDEN_ALS_MANTELZORGER (
    WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_ID NUMBER PRIMARY KEY,
    ANDERE_MANTELZORGTAKEN VARCHAR2(255),
    HULP_BIJ_MEDICATIE VARCHAR2(255),
    MANTELZORGOVEREENKOMST_AFGESLOTEN VARCHAR2(255),
    MANTELZORGVERKALRING_VERSTREKT VARCHAR2(255),
    OMSCHRIJVING_ANDERE_MANTELZORGTAKEN VARCHAR2(255),
    TE_BESPREKEN_MANTELZORGTAKEN VARCHAR2(255),
    TOEZICHT_HOUDEN VARCHAR2(255),
    VERVOER_EN_BEGELEIDING VARCHAR2(255),
    VERZORGDE_ACTVITEITEN VARCHAR2(255)
);

CREATE TABLE CODENIVEAUOPLEIDING_ENUM (
    CODENIVEAUOPLEIDING_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO CODENIVEAUOPLEIDING_ENUM (CODENIVEAUOPLEIDING_ENUM_ID, VALUE) VALUES (1, 'BASISONDERWIJS');
INSERT INTO CODENIVEAUOPLEIDING_ENUM (CODENIVEAUOPLEIDING_ENUM_ID, VALUE) VALUES (2, 'HAVO_VWO');
INSERT INTO CODENIVEAUOPLEIDING_ENUM (CODENIVEAUOPLEIDING_ENUM_ID, VALUE) VALUES (3, 'HBO_BACHELOR');
INSERT INTO CODENIVEAUOPLEIDING_ENUM (CODENIVEAUOPLEIDING_ENUM_ID, VALUE) VALUES (4, 'MBO');
INSERT INTO CODENIVEAUOPLEIDING_ENUM (CODENIVEAUOPLEIDING_ENUM_ID, VALUE) VALUES (5, 'VMBO_MBO_1');
INSERT INTO CODENIVEAUOPLEIDING_ENUM (CODENIVEAUOPLEIDING_ENUM_ID, VALUE) VALUES (6, 'WO_MASTER');

CREATE TABLE INDICATIE_MATE_VAN_VAARDIGHEID__ENUM (
    INDICATIE_MATE_VAN_VAARDIGHEID__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO INDICATIE_MATE_VAN_VAARDIGHEID__ENUM (INDICATIE_MATE_VAN_VAARDIGHEID__ENUM_ID, VALUE) VALUES (1, 'GOED');
INSERT INTO INDICATIE_MATE_VAN_VAARDIGHEID__ENUM (INDICATIE_MATE_VAN_VAARDIGHEID__ENUM_ID, VALUE) VALUES (2, 'NIET');
INSERT INTO INDICATIE_MATE_VAN_VAARDIGHEID__ENUM (INDICATIE_MATE_VAN_VAARDIGHEID__ENUM_ID, VALUE) VALUES (3, 'NIET_VAN_TOEPASSING');
INSERT INTO INDICATIE_MATE_VAN_VAARDIGHEID__ENUM (INDICATIE_MATE_VAN_VAARDIGHEID__ENUM_ID, VALUE) VALUES (4, 'ONDERZOEK_NOODZAKELIJK');
INSERT INTO INDICATIE_MATE_VAN_VAARDIGHEID__ENUM (INDICATIE_MATE_VAN_VAARDIGHEID__ENUM_ID, VALUE) VALUES (5, 'ONVOLDOENDE');
INSERT INTO INDICATIE_MATE_VAN_VAARDIGHEID__ENUM (INDICATIE_MATE_VAN_VAARDIGHEID__ENUM_ID, VALUE) VALUES (6, 'VOLDOENDE');

CREATE TABLE BESCHIKBAARVOORARBEID (
    BESCHIKBAARVOORARBEID_ID NUMBER PRIMARY KEY,
    AANTALURENPWBESCHIKBAAR NUMBER,
    DAGBESCHIKBAARHEID_ENUM_ID NUMBER,
    EINDDATUMBESCHIKBAARHEID DATE,
    EINDTIJDDAGBESCHIKBAARHEID TIMESTAMP,
    INDICATIE_NOG_WERKZAAM VARCHAR2(255),
    INTERVAL_OPZEGTERMIJN VARCHAR2(255),
    STARTDAGBESCHIKBAARHEID DATE,
    STARTDATUMBESCHIKBAARHEID DATE,
    TOELICHTINGBESCHIKBAARHEID VARCHAR2(255),
    WAARDEOPZEGTERMIJN NUMBER
);

CREATE TABLE OPLEIDINGSNIVEAU (
    OPLEIDINGSNIVEAU_ID NUMBER PRIMARY KEY,
    CODEOPLEIDINGSNIVEAUCLIENT VARCHAR2(255)
);

CREATE TABLE INDICATIE_DOELGROEPENREGISTER__ENUM (
    INDICATIE_DOELGROEPENREGISTER__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO INDICATIE_DOELGROEPENREGISTER__ENUM (INDICATIE_DOELGROEPENREGISTER__ENUM_ID, VALUE) VALUES (1, 'JA');
INSERT INTO INDICATIE_DOELGROEPENREGISTER__ENUM (INDICATIE_DOELGROEPENREGISTER__ENUM_ID, VALUE) VALUES (2, 'NEE');
INSERT INTO INDICATIE_DOELGROEPENREGISTER__ENUM (INDICATIE_DOELGROEPENREGISTER__ENUM_ID, VALUE) VALUES (3, 'VERMOEDELIJK');

CREATE TABLE TAALVAARDIGHEID__ENUM (
    TAALVAARDIGHEID__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO TAALVAARDIGHEID__ENUM (TAALVAARDIGHEID__ENUM_ID, VALUE) VALUES (1, 'ARM');
INSERT INTO TAALVAARDIGHEID__ENUM (TAALVAARDIGHEID__ENUM_ID, VALUE) VALUES (2, 'GOED');
INSERT INTO TAALVAARDIGHEID__ENUM (TAALVAARDIGHEID__ENUM_ID, VALUE) VALUES (3, 'MIDDELMATIG');
INSERT INTO TAALVAARDIGHEID__ENUM (TAALVAARDIGHEID__ENUM_ID, VALUE) VALUES (4, 'UITSTEKEND');
INSERT INTO TAALVAARDIGHEID__ENUM (TAALVAARDIGHEID__ENUM_ID, VALUE) VALUES (5, 'VOLDOENDE');

CREATE TABLE BEMIDDELINGSBEROEP (
    BEMIDDELINGSBEROEP_ID NUMBER PRIMARY KEY,
    TOELICHTINGBEROEP VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE DOELGROEPENREGISTER (
    DOELGROEPENREGISTER_ID NUMBER PRIMARY KEY,
    ADVIESUWV VARCHAR2(255),
    BAANAFSPRAAK_ENUM_ID NUMBER,
    INDICATIEDOELGROEPENREGISTER VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE ZRM_SCORE__ENUM (
    ZRM_SCORE__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO ZRM_SCORE__ENUM (ZRM_SCORE__ENUM_ID, VALUE) VALUES (1, 'ACUTE_PROBLEMATIEK');
INSERT INTO ZRM_SCORE__ENUM (ZRM_SCORE__ENUM_ID, VALUE) VALUES (2, 'BEPERKT_ZELFREDZAAM');
INSERT INTO ZRM_SCORE__ENUM (ZRM_SCORE__ENUM_ID, VALUE) VALUES (3, 'NIET_ZELFREDZAAM');
INSERT INTO ZRM_SCORE__ENUM (ZRM_SCORE__ENUM_ID, VALUE) VALUES (4, 'VOLDOENDE_ZELFREDZAAM');
INSERT INTO ZRM_SCORE__ENUM (ZRM_SCORE__ENUM_ID, VALUE) VALUES (5, 'VOLLEDIG_ZELFREDZAAM');

CREATE TABLE FLEXIBLITEIT (
    FLEXIBLITEIT_ID NUMBER PRIMARY KEY,
    INDICATIEBEREIDBUITENBEROEPSWENS VARCHAR2(255),
    INDICATIEBEREIDHEIDONREGELMATIGWERK VARCHAR2(255),
    INDICATIEBEREIDHEIDZOEKENONDERNIVEAU VARCHAR2(255),
    INDICATIEBEREIDHEIDZWAARWERK VARCHAR2(255),
    INGESCHREVENBIJUITZENDBUREAU VARCHAR2(255)
);

CREATE TABLE OPLEIDING (
    OPLEIDING_ID NUMBER PRIMARY KEY,
    AANTALJARENOPLEIDING NUMBER,
    CODELEERWEGMBO_ENUM_ID NUMBER,
    CODENIVEAUOPLEIDING_ENUM_ID NUMBER,
    CODESTATUSOPLEIDING_ENUM_ID NUMBER,
    CODETIJDSBESLAGOPLEIDING TIMESTAMP,
    DATUMAANVANG DATE,
    DATUMDIPLOMA DATE,
    DATUMEINDE DATE,
    INDICATIEBUITENLANDSEOPLEIDING VARCHAR2(255),
    INDICATIEDEELTIJDOPLEIDING TIMESTAMP,
    INDICATIEDIPLOMA VARCHAR2(255),
    INSTITUUTNAAM CLOB,
    OPLEIDINGSNAAM_ID NUMBER,
    OPLEIDINGSNIVEAU_ID NUMBER,
    OPLEIDINGSRICHTING_ENUM_ID NUMBER,
    OPLEIDINGSTYPE_ENUM_ID NUMBER,
    TOELICHTINGBEEINDIGENOPLEIDING DATE,
    TOELICHTINGOPLEIDING VARCHAR2(255)
);

CREATE TABLE VRIJSTELLINGARBEIDSPLICHT (
    VRIJSTELLINGARBEIDSPLICHT_ID NUMBER PRIMARY KEY,
    CODEREDENVRIJHEIDSTELLING NUMBER,
    CODEVRIJSTELLING NUMBER,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    INDICATIEVRIJSTELLING VARCHAR2(255)
);

CREATE TABLE WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING (
    WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_ID NUMBER PRIMARY KEY,
    AANTALURENGEMIDDELDWEEK NUMBER,
    BEDRAG_NETTO_INKOMSTEN_UIT_WADIA NUMBER(10,2),
    CODE_MAATSCHAPPELIJKE_CONTEXT VARCHAR2(255),
    DATUM_AANVANG_WERKZAAMHEDEN DATE,
    DATUM_EINDE_WERKZAAMHEDEN DATE,
    FUNCTIENAAM VARCHAR2(255),
    OMSCHRIJVING_REDEN_EINDE_WERKZAAMHEDEN DATE,
    OMSCHRIJVING_WERKZAAMHEDEN VARCHAR2(255),
    PERSOONORGANISATIEWAARBIJ VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE BEMIDDELINGSTRAJECT (
    BEMIDDELINGSTRAJECT_ID NUMBER PRIMARY KEY,
    DATUMBEMIDDELING DATE,
    DATUMVACATURE DATE,
    INDICATIEPLAATSING VARCHAR2(255),
    OMSCHRIJVINGCONTACTBEMIDDELING CLOB,
    OMSCHRIJVINGRESULTAATBEMIDDELING CLOB,
    OMSCHRIJVINGSTATUSBEMIDDELING CLOB,
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE VERVOERMIDDEL_ENUM (
    VERVOERMIDDEL_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (1, 'ANDERS');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (2, 'AUTO');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (3, 'BROMFIETS_SCOOTER');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (4, 'FIETS');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (5, 'GEEN');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (6, 'LOPEN');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (7, 'MOTORFIETS');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (8, 'OPENBAAR_VERVOER');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (9, 'OPENBAAR_VERVOER_WEEKEND_OV_');
INSERT INTO VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID, VALUE) VALUES (10, 'OPENBAAR_VERVOER_WEEK_OV_');

CREATE TABLE TAALBEHEERSINGNEDERLANDS (
    TAALBEHEERSINGNEDERLANDS_ID NUMBER PRIMARY KEY,
    GESPREKSVAARDIGHEIDNEDERLANDS VARCHAR2(255),
    LEESVAARDIGHEIDNEDERLANDS VARCHAR2(255),
    LUISTERVAARDIGHEIDNEDERLANDS VARCHAR2(255),
    ONTHEFFINGTAALEIS VARCHAR2(255),
    SCHRIJFVAARDIGHEIDNEDERLANDS VARCHAR2(255),
    SPREEKSVAARDIGHEIDNEDERLANDS VARCHAR2(255)
);

CREATE TABLE ARBEIDSPERIODE (
    ARBEIDSPERIODE_ID NUMBER PRIMARY KEY,
    ARBEIDSVERHOUDING_ID NUMBER,
    CONTACT_EMAIL VARCHAR2(255),
    CONTACT_PERSOON VARCHAR2(255),
    CONTACT_TELEFOON VARCHAR2(255),
    DATUM_AANVANG_ARBEIDSPERIODE DATE,
    DATUM_EINDE_ARBEIDSPERIODE DATE,
    FUNCTIENAAM VARCHAR2(255),
    FUNCTIEOMSCHRIJVING VARCHAR2(255),
    GEMIDDELD_AANTAL_UUR_PER_WEEK NUMBER
);

CREATE TABLE VAARDIGHEIDSVASTSTELLING (
    VAARDIGHEIDSVASTSTELLING_ID NUMBER PRIMARY KEY,
    DATUMLAATSTEVASTSTELLING DATE,
    INDICATIE_MATE_VAN_VAARDIGHEID VARCHAR2(255)
);

CREATE TABLE INTERVAL_OPZEGTERMIJN__ENUM (
    INTERVAL_OPZEGTERMIJN__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO INTERVAL_OPZEGTERMIJN__ENUM (INTERVAL_OPZEGTERMIJN__ENUM_ID, VALUE) VALUES (1, 'DAG');
INSERT INTO INTERVAL_OPZEGTERMIJN__ENUM (INTERVAL_OPZEGTERMIJN__ENUM_ID, VALUE) VALUES (2, 'MAAND');
INSERT INTO INTERVAL_OPZEGTERMIJN__ENUM (INTERVAL_OPZEGTERMIJN__ENUM_ID, VALUE) VALUES (3, 'UUR');
INSERT INTO INTERVAL_OPZEGTERMIJN__ENUM (INTERVAL_OPZEGTERMIJN__ENUM_ID, VALUE) VALUES (4, 'WEEK');

CREATE TABLE DAG_BESCHIKBAARHEID_ENUM (
    DAG_BESCHIKBAARHEID_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO DAG_BESCHIKBAARHEID_ENUM (DAG_BESCHIKBAARHEID_ENUM_ID, VALUE) VALUES (1, 'DINSDAG');
INSERT INTO DAG_BESCHIKBAARHEID_ENUM (DAG_BESCHIKBAARHEID_ENUM_ID, VALUE) VALUES (2, 'DONDERDAG');
INSERT INTO DAG_BESCHIKBAARHEID_ENUM (DAG_BESCHIKBAARHEID_ENUM_ID, VALUE) VALUES (3, 'MAANDAG');
INSERT INTO DAG_BESCHIKBAARHEID_ENUM (DAG_BESCHIKBAARHEID_ENUM_ID, VALUE) VALUES (4, 'VRIJDAG');
INSERT INTO DAG_BESCHIKBAARHEID_ENUM (DAG_BESCHIKBAARHEID_ENUM_ID, VALUE) VALUES (5, 'WOENSDAG');
INSERT INTO DAG_BESCHIKBAARHEID_ENUM (DAG_BESCHIKBAARHEID_ENUM_ID, VALUE) VALUES (6, 'ZATERDAG');
INSERT INTO DAG_BESCHIKBAARHEID_ENUM (DAG_BESCHIKBAARHEID_ENUM_ID, VALUE) VALUES (7, 'ZONDAG');

CREATE TABLE CODE_TIJDSBESLAG_OPLEIDING__ENUM (
    CODE_TIJDSBESLAG_OPLEIDING__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO CODE_TIJDSBESLAG_OPLEIDING__ENUM (CODE_TIJDSBESLAG_OPLEIDING__ENUM_ID, VALUE) VALUES (1, 'ANDERS');
INSERT INTO CODE_TIJDSBESLAG_OPLEIDING__ENUM (CODE_TIJDSBESLAG_OPLEIDING__ENUM_ID, VALUE) VALUES (2, 'AVONDOPLEIDING');
INSERT INTO CODE_TIJDSBESLAG_OPLEIDING__ENUM (CODE_TIJDSBESLAG_OPLEIDING__ENUM_ID, VALUE) VALUES (3, 'DAGOPLEIDING');
INSERT INTO CODE_TIJDSBESLAG_OPLEIDING__ENUM (CODE_TIJDSBESLAG_OPLEIDING__ENUM_ID, VALUE) VALUES (4, 'DAG_AVONDOPLEIDING');
INSERT INTO CODE_TIJDSBESLAG_OPLEIDING__ENUM (CODE_TIJDSBESLAG_OPLEIDING__ENUM_ID, VALUE) VALUES (5, 'ONBEKEND');
INSERT INTO CODE_TIJDSBESLAG_OPLEIDING__ENUM (CODE_TIJDSBESLAG_OPLEIDING__ENUM_ID, VALUE) VALUES (6, 'SCHRIFTELIJK');

CREATE TABLE ONTHEFFING (
    ONTHEFFING_ID NUMBER PRIMARY KEY,
    AANVRAAGDATUMONTHEFFING DATE,
    BIJLAGENBIJAANVRAAG VARCHAR2(255),
    BIJLAGENBIJHERZIENINGSBESLUIT VARCHAR2(255),
    BIJLAGENBIJONTHEFFINGSBESLUIT VARCHAR2(255),
    EINDDATUMONTHEFFING DATE,
    HERZIENINGSDATUMONTHEFFING DATE,
    INGANGSDATUMONTHEFFING DATE,
    MOTIVATIEHERZIENINGSBESLUIT VARCHAR2(255),
    MOTIVATIEONTHEFFINGSBESLUIT VARCHAR2(255),
    ONTHEFFENVERPLICHTINGEN VARCHAR2(255),
    ONTHEFFINGSBESLUIT VARCHAR2(255),
    REDENAANVRAAG VARCHAR2(255),
    RESULTAATINSTRUMENTBEOORDELING VARCHAR2(255),
    SOORTONTHEFFING VARCHAR2(255),
    VERSIENUMMERAANVRAAG NUMBER
);

CREATE TABLE VOORKEUR (
    VOORKEUR_ID NUMBER PRIMARY KEY,
    BEZITPERSOONLIJKEOVKAART VARCHAR2(255),
    BRANCHECODE NUMBER,
    BRANCHENAAM VARCHAR2(255),
    GEGEVENSWERKLOCATIE VARCHAR2(255),
    NUMMEROVK NUMBER,
    SOORTBAAN_ENUM_ID NUMBER,
    SOORTWERK VARCHAR2(255),
    TOELICHTINGVERVOERSMIDDEL VARCHAR2(255),
    VERLOOPDATUMOVK DATE,
    VERVOERMIDDEL_ENUM_ID NUMBER,
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM (
    CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM (CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM_ID, VALUE) VALUES (1, 'WERKZAAMHEDEN_ALS_FREELANCER');
INSERT INTO CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM (CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM_ID, VALUE) VALUES (2, 'WERKZAAMHEDEN_ALS_MANTELZORGER');
INSERT INTO CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM (CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM_ID, VALUE) VALUES (3, 'WERKZAAMHEDEN_ALS_VRIJWILLIGER');
INSERT INTO CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM (CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM_ID, VALUE) VALUES (4, 'WERKZAAMHEDEN_ALS_ZELFSTANDIGE');
INSERT INTO CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM (CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM_ID, VALUE) VALUES (5, 'WERKZAAMHEDEN_IN_EEN_NIET_NADER_GESPECIFICEERDE_CONTEXT_NIET_ZIJNDE_EEN_ARBEIDSVERHOUDING');
INSERT INTO CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM (CODE_MAATSCHAPPELIJKE_CONTEXT_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING__ENUM_ID, VALUE) VALUES (6, 'WERKZAAMHEDEN_IN_EEN_POLITIEKE_FUNCTIE');

CREATE TABLE SETU_JOB_CATEGORY_ENUM (
    SETU_JOB_CATEGORY_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (1, 'ADMINISTRATIEVE_SECRETARIAT');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (2, 'AGRICULTURAL_CATTLE_BREEDING_ANIMAL_CARE_NATURE_CONSERVATION');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (3, 'BUILDING_INDUSTRY');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (4, 'BUSINESS_SERVICES_RETAIL_TRADE');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (5, 'CATERING_TOURISM');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (6, 'CLEANING_HOUSEKEEING_CLEAN_UP');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (7, 'CONSULTING_STAFF_POLICY');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (8, 'CULTURE_ARTS_CREATIVE');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (9, 'CUSTOMER_SERVICE_CALL_CENTRE_RECEPTION');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (10, 'DESIGN_ARCHITECTURE_GRAPHICAL');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (11, 'EDITIOR_JOURNALISM');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (12, 'EDUCATION_TRAINING');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (13, 'FINANCIAL_ADMINISTRATIEVE_ACCOUNTING');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (14, 'GOVERNMENT_SERVICE_GOVERNMENT');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (15, 'HEALTH_CARE_MEDICAL_NURSING_PARAMEDICAL');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (16, 'IT_ICT_SOFTWARE_DEVELOPMENT_INTERNET');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (17, 'LEGAL');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (18, 'MARKETING_ADVERTISEMENT_PUBLIC_RELATIONS_COMMUNICATION');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (19, 'PERSONAL_HEALTH_CAR');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (20, 'PERSONNEL_MATTERS_HUMAN_RESOURCES_EMPLOYMENT_FINDING');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (21, 'PRODUCTION_CRAFTS');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (22, 'RESEARCH_SCIENCE_LABORATORY');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (23, 'SALES_COMMERCIAL');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (24, 'SECURITY_DEFENCE_AUXILIARY_SERVICE');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (25, 'SPORT_RELAXATION');
INSERT INTO SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID, VALUE) VALUES (26, 'TECHNOLOGY_ENGINEERING');

CREATE TABLE KP_OPLDNGSNMGCDRD_OPLDNGSNM (
    KP_OPLDNGSNMGCDRD_OPLDNGSNM_ID NUMBER PRIMARY KEY,
    OPLEIDINGSNAAMGECODEERD_ID NUMBER,
    OPLEIDINGSNAAM_ID NUMBER
);

CREATE TABLE ARBEIDSVERMOGEN (
    ARBEIDSVERMOGEN_ID NUMBER PRIMARY KEY,
    CODEARBEIDSVERMOGEN VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE RIJBEWIJS_CERTIFICAAT (
    RIJBEWIJS_CERTIFICAAT_ID NUMBER PRIMARY KEY,
    BESCHRIJVING VARCHAR2(255),
    CODESOORTRIJBEWIJS VARCHAR2(255),
    GELDIGTOT DATE,
    GELDIGVANAF DATE,
    INDICATIEGELDIGHEIDRIJBEWIJS VARCHAR2(255),
    NAAMCERTIFICAAT VARCHAR2(255),
    NUMMERCERTIFICAAT VARCHAR2(255),
    VERSTREKKENDEPARTIJ VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE HULP_AANWEZIG_ENUM (
    HULP_AANWEZIG_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO HULP_AANWEZIG_ENUM (HULP_AANWEZIG_ENUM_ID, VALUE) VALUES (1, 'JA_FORMEEL');
INSERT INTO HULP_AANWEZIG_ENUM (HULP_AANWEZIG_ENUM_ID, VALUE) VALUES (2, 'JA_INFORMEEL');
INSERT INTO HULP_AANWEZIG_ENUM (HULP_AANWEZIG_ENUM_ID, VALUE) VALUES (3, 'NEE');

CREATE TABLE KP_OPLDNGSNMNGCDRD_OPLDNGSNM (
    KP_OPLDNGSNMNGCDRD_OPLDNGSNM_ID NUMBER PRIMARY KEY,
    OPLEIDINGSNAAMONGECODEERD_ID NUMBER,
    OPLEIDINGSNAAM_ID NUMBER
);

CREATE TABLE MOBILITEIT (
    MOBILITEIT_ID NUMBER PRIMARY KEY,
    CODEVERVOERMIDDEL_ENUM_ID NUMBER,
    INDICATIEBEREIDHEIDVERHUIZEN VARCHAR2(255),
    MAXIMALEREISTIJD TIMESTAMP,
    TOELICHTINGMAXIMALEREISTIJD TIMESTAMP,
    TOELICHTINGVERVOERMIDDEL VARCHAR2(255)
);

CREATE TABLE ONTHEFFINGSVERPLICHTING__ENUM (
    ONTHEFFINGSVERPLICHTING__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO ONTHEFFINGSVERPLICHTING__ENUM (ONTHEFFINGSVERPLICHTING__ENUM_ID, VALUE) VALUES (1, 'A_');
INSERT INTO ONTHEFFINGSVERPLICHTING__ENUM (ONTHEFFINGSVERPLICHTING__ENUM_ID, VALUE) VALUES (2, 'A_B_C');
INSERT INTO ONTHEFFINGSVERPLICHTING__ENUM (ONTHEFFINGSVERPLICHTING__ENUM_ID, VALUE) VALUES (3, 'A_C_');

CREATE TABLE ARBEIDSMARKTKWALIFICATIES (
    ARBEIDSMARKTKWALIFICATIES_ID NUMBER PRIMARY KEY,
    CODE_TAALBEHEERSING_MONDELING VARCHAR2(255),
    CODE_TAALBEHEERSING_SCHRIFTELIJK VARCHAR2(255),
    CODE_WERK_EN_DENKNIVEAU VARCHAR2(255),
    KLANTTYPERING VARCHAR2(255),
    TOELICHTINGARBEIDSMARKTKWALIFICATIES VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE CODE_ARBEIDSVERMOGEN__ENUM (
    CODE_ARBEIDSVERMOGEN__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO CODE_ARBEIDSVERMOGEN__ENUM (CODE_ARBEIDSVERMOGEN__ENUM_ID, VALUE) VALUES (1, 'MET_HULP_WML_OF_HOGER');
INSERT INTO CODE_ARBEIDSVERMOGEN__ENUM (CODE_ARBEIDSVERMOGEN__ENUM_ID, VALUE) VALUES (2, 'NOG_NIET_BEKEND');
INSERT INTO CODE_ARBEIDSVERMOGEN__ENUM (CODE_ARBEIDSVERMOGEN__ENUM_ID, VALUE) VALUES (3, 'ONDER_WML');
INSERT INTO CODE_ARBEIDSVERMOGEN__ENUM (CODE_ARBEIDSVERMOGEN__ENUM_ID, VALUE) VALUES (4, 'TIJDELIJK_GEEN_ARBEIDSVERMOGEN');
INSERT INTO CODE_ARBEIDSVERMOGEN__ENUM (CODE_ARBEIDSVERMOGEN__ENUM_ID, VALUE) VALUES (5, 'ZELFSTANDIG_WML_OF_HOGER');

CREATE TABLE LOONKOSTENSUBSIDIE (
    LOONKOSTENSUBSIDIE_ID NUMBER PRIMARY KEY,
    PERCENTAGELOONWAARDEWML VARCHAR2(255)
);

CREATE TABLE DOELREINTEGRATIEVOORZIENING (
    DOELREINTEGRATIEVOORZIENING_ID NUMBER PRIMARY KEY,
    CODEDOELREINTEGRATIEVOORZIENING NUMBER
);

CREATE TABLE VERVOERSMOGELIJKHEDEN__ENUM (
    VERVOERSMOGELIJKHEDEN__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (1, 'ANDERS');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (2, 'AUTO');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (3, 'BROMFIETS_SCOOTER');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (4, 'FIETS');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (5, 'GEEN');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (6, 'LOPEN');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (7, 'MOTORFIETS');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (8, 'OPENBAAR_VERVOER');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (9, 'OPENBAAR_VERVOER_WEEKEND_OV_');
INSERT INTO VERVOERSMOGELIJKHEDEN__ENUM (VERVOERSMOGELIJKHEDEN__ENUM_ID, VALUE) VALUES (10, 'OPENBAAR_VERVOER_WEEK_OV_');

CREATE TABLE CODESTATUSOPLEIDING_ENUM (
    CODESTATUSOPLEIDING_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO CODESTATUSOPLEIDING_ENUM (CODESTATUSOPLEIDING_ENUM_ID, VALUE) VALUES (1, 'AFGEBROKEN');
INSERT INTO CODESTATUSOPLEIDING_ENUM (CODESTATUSOPLEIDING_ENUM_ID, VALUE) VALUES (2, 'LOPEND');
INSERT INTO CODESTATUSOPLEIDING_ENUM (CODESTATUSOPLEIDING_ENUM_ID, VALUE) VALUES (3, 'ONBEKEND');
INSERT INTO CODESTATUSOPLEIDING_ENUM (CODESTATUSOPLEIDING_ENUM_ID, VALUE) VALUES (4, 'SUCCESVOL_AFGEROND');

CREATE TABLE WERKZOEKENDE (
    WERKZOEKENDE_ID NUMBER PRIMARY KEY,
    BESCHIKBAARVOORARBEID_ID NUMBER,
    DATUMAANVANGWERKZOEKENDE DATE,
    DATUMEINDEWERKZOEKENDE DATE,
    DOELREINTEGRATIEVOORZIENING_ID NUMBER,
    FLEXIBLITEIT_ID NUMBER,
    MOBILITEIT_ID NUMBER,
    ONTHEFFING_ID NUMBER,
    OPLEIDINGSNIVEAU_ID NUMBER,
    TAALBEHEERSINGNEDERLANDS_ID NUMBER,
    VRIJSTELLINGARBEIDSPLICHT_ID NUMBER
);

CREATE TABLE WERKERVARING (
    WERKERVARING_ID NUMBER PRIMARY KEY,
    AANTAL_JAREN_WERKZAAM_IN_BEROEP DATE,
    TOELICHTING_BEROEP VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE ZELFREDZAAMHEIDSCORE (
    ZELFREDZAAMHEIDSCORE_ID NUMBER PRIMARY KEY,
    DATUMBEOORDELING DATE,
    DOMEIN_VAN_ZELFREDZAAMHEID VARCHAR2(255),
    INDICATIEHULPAANWEZIG NUMBER(1),
    KENMERKBEOORDELAAR VARCHAR2(200),
    WERKZOEKENDE_ID NUMBER,
    WOONGEMEENTE VARCHAR2(255),
    ZRM_SCORE VARCHAR2(255)
);

CREATE TABLE CODELEERWEGMBO_ENUM (
    CODELEERWEGMBO_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO CODELEERWEGMBO_ENUM (CODELEERWEGMBO_ENUM_ID, VALUE) VALUES (1, 'BBL_BEROEPSBEGELEIDENDE_LEERWEG');
INSERT INTO CODELEERWEGMBO_ENUM (CODELEERWEGMBO_ENUM_ID, VALUE) VALUES (2, 'BOL_BEROEPSOPLEIDENDE_LEERWEG');
INSERT INTO CODELEERWEGMBO_ENUM (CODELEERWEGMBO_ENUM_ID, VALUE) VALUES (3, 'CBL_COMBINATIE_BEROEPSBEGELEIDENDE_LEERWEG');
INSERT INTO CODELEERWEGMBO_ENUM (CODELEERWEGMBO_ENUM_ID, VALUE) VALUES (4, 'COL_COMBINATIE_BEROEPSOPLEIDENDE_LEERWEG');
INSERT INTO CODELEERWEGMBO_ENUM (CODELEERWEGMBO_ENUM_ID, VALUE) VALUES (5, 'OVO_OVERIG_ONDERWIJS_NIET_BEKOSTIGD_');

CREATE TABLE REINTEGRATIEVOORZIENING (
    REINTEGRATIEVOORZIENING_ID NUMBER PRIMARY KEY,
    CODETYPE NUMBER,
    DATUMEINDE DATE,
    DATUMEINDEVERLENGDEBESLISTERMIJN DATE,
    DATUMINGEBRUIKNAME DATE,
    DATUMINNAME DATE,
    DATUMSTART DATE,
    DATUMSTARTVOORLOPIGETOEKENNING DATE,
    DATUMVERWACHTEINDE DATE,
    LOONKOSTENSUBSIDIE_ID NUMBER,
    OMSCHRIJVING VARCHAR2(255),
    OMSCHRIJVINGTYPE VARCHAR2(255),
    REGISTRATIENUMMERREINTEGRATIEVOORZIENING NUMBER,
    TOELICHTINGOMSCHRIJVING VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE BESCHIKBAARVOORBEMIDDELING (
    BESCHIKBAARVOORBEMIDDELING_ID NUMBER PRIMARY KEY,
    DATUMEINDE DATE,
    INDICATIEDIRECTBEMIDDELBAAR VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE SOORTWERK_ENUM (
    SOORTWERK_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO SOORTWERK_ENUM (SOORTWERK_ENUM_ID, VALUE) VALUES (1, 'AANPAKKEN');
INSERT INTO SOORTWERK_ENUM (SOORTWERK_ENUM_ID, VALUE) VALUES (2, 'HELPEN');
INSERT INTO SOORTWERK_ENUM (SOORTWERK_ENUM_ID, VALUE) VALUES (3, 'MAKEN');
INSERT INTO SOORTWERK_ENUM (SOORTWERK_ENUM_ID, VALUE) VALUES (4, 'VERKOPEN');
INSERT INTO SOORTWERK_ENUM (SOORTWERK_ENUM_ID, VALUE) VALUES (5, 'VERVOEREN');

CREATE TABLE OPLEIDINGSNAAMONGECODEERD (
    OPLEIDINGSNAAM_ID NUMBER PRIMARY KEY,
    NAAMOPLEIDINGONGECODEERD VARCHAR2(255)
);

CREATE TABLE DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (
    DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (1, 'BASALE_ADL_ACTIVITEITEN_DAGELIJKS_LEVEN_');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (2, 'FINANCIËN');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (3, 'GEESTELIJKE_GEZONDHEID');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (4, 'HUISELIJKE_RELATIES');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (5, 'HUISVESTING');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (6, 'INSTRUMENTELE_ADL');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (7, 'JUSTITIE');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (8, 'LICHAMELIJKE_GEZONDHEID');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (9, 'MAATSCHAPPELIJKE_PARTICIPATIE');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (10, 'MIDDELENGEBRUIK');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (11, 'SOCIAAL_NETWERK');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (12, 'TIJDSBESTEDING');
INSERT INTO DOMEIN_VAN_ZELFREDZAAMHEID__ENUM (DOMEIN_VAN_ZELFREDZAAMHEID__ENUM_ID, VALUE) VALUES (13, 'WERK_OPLEIDING');

CREATE TABLE ARBEIDSVERHOUDING (
    ARBEIDSVERHOUDING_ID NUMBER PRIMARY KEY,
    DATUM_AANVRAAG_ARBEIDSVERHOUDING DATE,
    DATUM_EINDE_ARBEIDSVERHOUDING DATE,
    WERKZOEKENDE_ID NUMBER
);

CREATE TABLE TAALBEHEERSING (
    TAALBEHEERSING_ID NUMBER PRIMARY KEY,
    LEESVAARDIGHEID VARCHAR2(255),
    MOEDERTAAL VARCHAR2(255),
    SCHRIJFVAARDIGHEID VARCHAR2(255),
    SPREEKVAARDIGHEID VARCHAR2(255),
    TAALCODE VARCHAR2(255),
    TAALNAAM VARCHAR2(255),
    WERKZOEKENDE_ID NUMBER
);

ALTER TABLE OPLEIDINGSNAAMGECODEERD ADD CONSTRAINT FK_OPLEIDINGSNAAMGECODEERD_GEN_OPLEIDINGSNAAM FOREIGN KEY (OPLEIDINGSNAAM_ID) REFERENCES OPLEIDINGSNAAM (OPLEIDINGSNAAM_ID);
-- Generalization to OPLEIDINGSNAAM

ALTER TABLE OPLEIDINGSNAAMONGECODEERD ADD CONSTRAINT FK_OPLEIDINGSNAAMONGECODEERD_GEN_OPLEIDINGSNAAM FOREIGN KEY (OPLEIDINGSNAAM_ID) REFERENCES OPLEIDINGSNAAM (OPLEIDINGSNAAM_ID);
-- Generalization to OPLEIDINGSNAAM

ALTER TABLE WERKZAAMHEDEN_ALS_MANTELZORGER ADD CONSTRAINT FK_WERKZAAMHEDEN_ALS_MANTELZORGER_GEN_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING FOREIGN KEY (WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_ID) REFERENCES WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING (WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_ID);
-- Generalization to WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING

ALTER TABLE KP_WRKZMHDN_ALS_MNTLZRGR_WRKZMHDN_ANDRS_DAN_IN_ARBDSVRHDNG ADD CONSTRAINT FK_KP_WRKZMHDN_ALS_MNTLZRGR_WRKZMHDN_ANDRS_DAN_IN_ARBDSVRHDNG_1 FOREIGN KEY (WERKZAAMHEDEN_ALS_MANTELZORGER_ID) REFERENCES WERKZAAMHEDEN_ALS_MANTELZORGER (WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_ID);
-- WERKZAAMHEDEN_ALS_MANTELZORGER (many-to-many junction, Connector_ID: 1566)

ALTER TABLE KP_WRKZMHDN_ALS_MNTLZRGR_WRKZMHDN_ANDRS_DAN_IN_ARBDSVRHDNG ADD CONSTRAINT FK_KP_WRKZMHDN_ALS_MNTLZRGR_WRKZMHDN_ANDRS_DAN_IN_ARBDSVRHDNG_2 FOREIGN KEY (WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_ID) REFERENCES WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING (WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_ID);
-- WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING (many-to-many junction, Connector_ID: 1566)

ALTER TABLE KP_OPLDNGSNMNGCDRD_OPLDNGSNM ADD CONSTRAINT FK_KP_OPLDNGSNMNGCDRD_OPLDNGSNM_1 FOREIGN KEY (OPLEIDINGSNAAMONGECODEERD_ID) REFERENCES OPLEIDINGSNAAMONGECODEERD (OPLEIDINGSNAAM_ID);
-- OPLEIDINGSNAAMONGECODEERD (many-to-many junction, Connector_ID: 1575)

ALTER TABLE KP_OPLDNGSNMNGCDRD_OPLDNGSNM ADD CONSTRAINT FK_KP_OPLDNGSNMNGCDRD_OPLDNGSNM_2 FOREIGN KEY (OPLEIDINGSNAAM_ID) REFERENCES OPLEIDINGSNAAM (OPLEIDINGSNAAM_ID);
-- OPLEIDINGSNAAM (many-to-many junction, Connector_ID: 1575)

ALTER TABLE KP_OPLDNGSNMGCDRD_OPLDNGSNM ADD CONSTRAINT FK_KP_OPLDNGSNMGCDRD_OPLDNGSNM_1 FOREIGN KEY (OPLEIDINGSNAAMGECODEERD_ID) REFERENCES OPLEIDINGSNAAMGECODEERD (OPLEIDINGSNAAM_ID);
-- OPLEIDINGSNAAMGECODEERD (many-to-many junction, Connector_ID: 1577)

ALTER TABLE KP_OPLDNGSNMGCDRD_OPLDNGSNM ADD CONSTRAINT FK_KP_OPLDNGSNMGCDRD_OPLDNGSNM_2 FOREIGN KEY (OPLEIDINGSNAAM_ID) REFERENCES OPLEIDINGSNAAM (OPLEIDINGSNAAM_ID);
-- OPLEIDINGSNAAM (many-to-many junction, Connector_ID: 1577)

ALTER TABLE ZELFREDZAAMHEIDSCORE ADD CONSTRAINT FK_ZELFREDZAAMHEIDSCORE_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (`1 to 1..*, Connector_ID: 1563)

ALTER TABLE WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING ADD CONSTRAINT FK_WERKZAAMHEDEN_ANDERS_DAN_IN_ARBEIDSVERHOUDING_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 0..*, Connector_ID: 1565)

ALTER TABLE WERKERVARING ADD CONSTRAINT FK_WERKERVARING_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 0..*, Connector_ID: 1567)

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_VRIJSTELLINGARBEIDSPLICHT FOREIGN KEY (VRIJSTELLINGARBEIDSPLICHT_ID) REFERENCES VRIJSTELLINGARBEIDSPLICHT (VRIJSTELLINGARBEIDSPLICHT_ID);
-- unnamed (`1 to 0..1, Connector_ID: 1568)

ALTER TABLE VOORKEUR ADD CONSTRAINT FK_VOORKEUR_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 0..*, Connector_ID: 1569)

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_TAALBEHEERSINGNEDERLANDS FOREIGN KEY (TAALBEHEERSINGNEDERLANDS_ID) REFERENCES TAALBEHEERSINGNEDERLANDS (TAALBEHEERSINGNEDERLANDS_ID);
-- unnamed (1 to 1, Connector_ID: 1570)

ALTER TABLE TAALBEHEERSING ADD CONSTRAINT FK_TAALBEHEERSING_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 1..*, Connector_ID: 1571)

ALTER TABLE RIJBEWIJS_CERTIFICAAT ADD CONSTRAINT FK_RIJBEWIJS_CERTIFICAAT_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 0..*, Connector_ID: 1572)

ALTER TABLE REINTEGRATIEVOORZIENING ADD CONSTRAINT FK_REINTEGRATIEVOORZIENING_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 0..*, Connector_ID: 1573)

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_OPLEIDINGSNIVEAU FOREIGN KEY (OPLEIDINGSNIVEAU_ID) REFERENCES OPLEIDINGSNIVEAU (OPLEIDINGSNIVEAU_ID);
-- unnamed (1 to 0..1, Connector_ID: 1574)

ALTER TABLE OPLEIDINGSNAAMGECODEERD ADD CONSTRAINT FK_OPLEIDINGSNAAMGECODEERD_HEEFT_SYNONIEM FOREIGN KEY (HEEFT_SYNONIEM_OPLEIDINGSNAAM_ID) REFERENCES OPLEIDINGSNAAM (OPLEIDINGSNAAM_ID);
-- HEEFT_SYNONIEM (0..* to 1, Connector_ID: 1576)

ALTER TABLE OPLEIDING ADD CONSTRAINT FK_OPLEIDING_OPLEIDINGSNIVEAU FOREIGN KEY (OPLEIDINGSNIVEAU_ID) REFERENCES OPLEIDINGSNIVEAU (OPLEIDINGSNIVEAU_ID);
-- unnamed (1 to 0..*, Connector_ID: 1578)

ALTER TABLE OPLEIDING ADD CONSTRAINT FK_OPLEIDING_OPLEIDINGSNAAM FOREIGN KEY (OPLEIDINGSNAAM_ID) REFERENCES OPLEIDINGSNAAM (OPLEIDINGSNAAM_ID);
-- unnamed (1 to 1, Connector_ID: 1579)

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_ONTHEFFING FOREIGN KEY (ONTHEFFING_ID) REFERENCES ONTHEFFING (ONTHEFFING_ID);
-- unnamed (1 to 0..1, Connector_ID: 1580)

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_MOBILITEIT FOREIGN KEY (MOBILITEIT_ID) REFERENCES MOBILITEIT (MOBILITEIT_ID);
-- unnamed (1 to 0..1, Connector_ID: 1581)

ALTER TABLE REINTEGRATIEVOORZIENING ADD CONSTRAINT FK_REINTEGRATIEVOORZIENING_LOONKOSTENSUBSIDIE FOREIGN KEY (LOONKOSTENSUBSIDIE_ID) REFERENCES LOONKOSTENSUBSIDIE (LOONKOSTENSUBSIDIE_ID);
-- unnamed (0..1 to 0..1, Connector_ID: 1582)

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_FLEXIBLITEIT FOREIGN KEY (FLEXIBLITEIT_ID) REFERENCES FLEXIBLITEIT (FLEXIBLITEIT_ID);
-- unnamed (1 to 0..1, Connector_ID: 1583)

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_DOELREINTEGRATIEVOORZIENING FOREIGN KEY (DOELREINTEGRATIEVOORZIENING_ID) REFERENCES DOELREINTEGRATIEVOORZIENING (DOELREINTEGRATIEVOORZIENING_ID);
-- unnamed (1 to 0..1, Connector_ID: 1584)

ALTER TABLE DOELGROEPENREGISTER ADD CONSTRAINT FK_DOELGROEPENREGISTER_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 1..*, Connector_ID: 1585)

ALTER TABLE BESCHIKBAARVOORBEMIDDELING ADD CONSTRAINT FK_BESCHIKBAARVOORBEMIDDELING_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 0..*, Connector_ID: 1587)

ALTER TABLE WERKZOEKENDE ADD CONSTRAINT FK_WERKZOEKENDE_BESCHIKBAARVOORARBEID FOREIGN KEY (BESCHIKBAARVOORARBEID_ID) REFERENCES BESCHIKBAARVOORARBEID (BESCHIKBAARVOORARBEID_ID);
-- unnamed (1 to 0..1, Connector_ID: 1588)

ALTER TABLE BEMIDDELINGSTRAJECT ADD CONSTRAINT FK_BEMIDDELINGSTRAJECT_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 0..*, Connector_ID: 1589)

ALTER TABLE BEMIDDELINGSBEROEP ADD CONSTRAINT FK_BEMIDDELINGSBEROEP_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (0..* to 1, Connector_ID: 1590)

ALTER TABLE ARBEIDSVERMOGEN ADD CONSTRAINT FK_ARBEIDSVERMOGEN_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 1..*, Connector_ID: 1591)

ALTER TABLE ARBEIDSVERHOUDING ADD CONSTRAINT FK_ARBEIDSVERHOUDING_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (0..* to 1, Connector_ID: 1592)

ALTER TABLE ARBEIDSPERIODE ADD CONSTRAINT FK_ARBEIDSPERIODE_ARBEIDSVERHOUDING FOREIGN KEY (ARBEIDSVERHOUDING_ID) REFERENCES ARBEIDSVERHOUDING (ARBEIDSVERHOUDING_ID);
-- unnamed (1 to 1..*, Connector_ID: 1593)

ALTER TABLE ARBEIDSMARKTKWALIFICATIES ADD CONSTRAINT FK_ARBEIDSMARKTKWALIFICATIES_WERKZOEKENDE FOREIGN KEY (WERKZOEKENDE_ID) REFERENCES WERKZOEKENDE (WERKZOEKENDE_ID);
-- unnamed (1 to 1..*, Connector_ID: 1594)

ALTER TABLE BESCHIKBAARVOORARBEID ADD CONSTRAINT FK_BESCHIKBAARVOORARBEID_DAGBESCHIKBAARHEID_ENUM_ID FOREIGN KEY (DAGBESCHIKBAARHEID_ENUM_ID_DAG_BESCHIKBAARHEID_ENUM_ID) REFERENCES DAG_BESCHIKBAARHEID_ENUM (DAG_BESCHIKBAARHEID_ENUM_ID);
-- DAGBESCHIKBAARHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE DOELGROEPENREGISTER ADD CONSTRAINT FK_DOELGROEPENREGISTER_BAANAFSPRAAK_ENUM_ID FOREIGN KEY (BAANAFSPRAAK_ENUM_ID_SOORTWERK_ENUM_ID) REFERENCES SOORTWERK_ENUM (SOORTWERK_ENUM_ID);
-- BAANAFSPRAAK_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE MOBILITEIT ADD CONSTRAINT FK_MOBILITEIT_CODEVERVOERMIDDEL_ENUM_ID FOREIGN KEY (CODEVERVOERMIDDEL_ENUM_ID_VERVOERMIDDEL_ENUM_ID) REFERENCES VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID);
-- CODEVERVOERMIDDEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPLEIDING ADD CONSTRAINT FK_OPLEIDING_OPLEIDINGSRICHTING_ENUM_ID FOREIGN KEY (OPLEIDINGSRICHTING_ENUM_ID_OPLEIDINGSRICHTING_ENUM_ID) REFERENCES OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID);
-- OPLEIDINGSRICHTING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPLEIDING ADD CONSTRAINT FK_OPLEIDING_CODENIVEAUOPLEIDING_ENUM_ID FOREIGN KEY (CODENIVEAUOPLEIDING_ENUM_ID_CODENIVEAUOPLEIDING_ENUM_ID) REFERENCES CODENIVEAUOPLEIDING_ENUM (CODENIVEAUOPLEIDING_ENUM_ID);
-- CODENIVEAUOPLEIDING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPLEIDING ADD CONSTRAINT FK_OPLEIDING_OPLEIDINGSTYPE_ENUM_ID FOREIGN KEY (OPLEIDINGSTYPE_ENUM_ID_OPLEIDINGSRICHTING_ENUM_ID) REFERENCES OPLEIDINGSRICHTING_ENUM (OPLEIDINGSRICHTING_ENUM_ID);
-- OPLEIDINGSTYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPLEIDING ADD CONSTRAINT FK_OPLEIDING_CODESTATUSOPLEIDING_ENUM_ID FOREIGN KEY (CODESTATUSOPLEIDING_ENUM_ID_CODESTATUSOPLEIDING_ENUM_ID) REFERENCES CODESTATUSOPLEIDING_ENUM (CODESTATUSOPLEIDING_ENUM_ID);
-- CODESTATUSOPLEIDING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPLEIDING ADD CONSTRAINT FK_OPLEIDING_CODELEERWEGMBO_ENUM_ID FOREIGN KEY (CODELEERWEGMBO_ENUM_ID_CODELEERWEGMBO_ENUM_ID) REFERENCES CODELEERWEGMBO_ENUM (CODELEERWEGMBO_ENUM_ID);
-- CODELEERWEGMBO_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPLEIDINGSNAAMGECODEERD ADD CONSTRAINT FK_OPLEIDINGSNAAMGECODEERD_CODEOPLEIDINGSNAAM_ENUM_ID FOREIGN KEY (CODEOPLEIDINGSNAAM_ENUM_ID_CODEOPLEIDINGSNAAM_ENUM_ID) REFERENCES CODEOPLEIDINGSNAAM_ENUM (CODEOPLEIDINGSNAAM_ENUM_ID);
-- CODEOPLEIDINGSNAAM_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VOORKEUR ADD CONSTRAINT FK_VOORKEUR_VERVOERMIDDEL_ENUM_ID FOREIGN KEY (VERVOERMIDDEL_ENUM_ID_VERVOERMIDDEL_ENUM_ID) REFERENCES VERVOERMIDDEL_ENUM (VERVOERMIDDEL_ENUM_ID);
-- VERVOERMIDDEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VOORKEUR ADD CONSTRAINT FK_VOORKEUR_SOORTBAAN_ENUM_ID FOREIGN KEY (SOORTBAAN_ENUM_ID_SETU_JOB_CATEGORY_ENUM_ID) REFERENCES SETU_JOB_CATEGORY_ENUM (SETU_JOB_CATEGORY_ENUM_ID);
-- SOORTBAAN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

