CREATE TABLE NATUURLIJKPERSOON (
    NATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON VARCHAR2(50),
        AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
        AANHEFAANSCHRIJVING VARCHAR2(50),
        ACADEMISCHETITEL VARCHAR2(80),
        ACHTERNAAM VARCHAR2(100),
        ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        ATTRIBUTE VARCHAR2(255),
        BURGERSERVICENUMMER VARCHAR2(255),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        GEBOORTELAND VARCHAR2(255),
        GEBOORTEPLAATS VARCHAR2(200),
        GESLACHTSAANDUIDING VARCHAR2(255),
        GESLACHTSNAAM VARCHAR2(200),
        GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
        HANDLICHTING VARCHAR2(50),
        INDICATIEAFSCHERMINGPERSOONSGEGEVENS NUMBER(1),
        INDICATIEOVERLEDEN NUMBER(1),
        LANDOVERLIJDEN VARCHAR2(255),
        NATIONALITEIT VARCHAR2(100),
        OVERLIJDENSPLAATS VARCHAR2(200),
        VOORLETTERSAANSCHRIJVING VARCHAR2(20),
        VOORNAMEN VARCHAR2(200),
        VOORNAMENAANSCHRIJVING VARCHAR2(200),
        VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMUITSCHRIJVING DATE,
        DATUMVOORTZETTING DATE,
        FAXNUMMER VARCHAR2(20),
        INGESCHREVEN NUMBER(1),
        INOPRICHTING NUMBER(1),
        KVKNUMMER VARCHAR2(255),
        NNPID VARCHAR2(255),
        RECHTSVORM VARCHAR2(255),
        RSINNUMMER VARCHAR2(255),
        STATUTAIRENAAM VARCHAR2(255),
        STATUTAIREZETEL VARCHAR2(255),
        WEBSITEURL VARCHAR2(200)
);

CREATE TABLE BETROKKENE (
    BETROKKENE_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(50),
        IS_NATUURLIJKPERSOON_ID VARCHAR2(255),
        IS_NIETNATUURLIJKPERSOON_ID VARCHAR2(255),
        NAAM VARCHAR2(200),
        ROL VARCHAR2(255)
);

CREATE TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN (
    KP_NTNTRLJKPRSN_NTRLJKPRSN_ID VARCHAR2(255) PRIMARY KEY,
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255),
    NATUURLIJKPERSOON_ID VARCHAR2(255)
);

CREATE TABLE ZAAK (
    ZAAK_ID VARCHAR2(255) PRIMARY KEY,
        ARCHIEFNOMINATIE VARCHAR2(255),
        ATTRIBUTE VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMEINDEGEPLAND DATE,
        DATUMEINDEUITERLIJKEAFDOENING DATE,
        DATUMLAATSTEBETALING DATE,
        DATUMPUBLICATIE DATE,
        DATUMREGISTRATIE DATE,
        DATUMSTART DATE,
        DATUMVERNIETIGINGDOSSIER DATE,
        DOCUMENT VARCHAR2(255),
        DUURVERLENGING VARCHAR2(255),
        HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID VARCHAR2(255),
        INDICATIEBETALING VARCHAR2(255),
        INDICATIEDEELZAKEN VARCHAR2(255),
        INDICATIEOPSCHORTING VARCHAR2(255),
        IS_DEELZAAK_VAN_ZAAK_ID VARCHAR2(255),
        LEGES VARCHAR2(100),
        OMSCHRIJVING VARCHAR2(80),
        OMSCHRIJVINGRESULTAAT VARCHAR2(80),
        REDENOPSCHORTING VARCHAR2(200),
        REDENVERLENGING VARCHAR2(200),
        TOELICHTING VARCHAR2(255),
        TOELICHTINGRESULTAAT VARCHAR2(255),
        VERTROUWELIJKHEID VARCHAR2(255),
        ZAAKIDENTIFICATIE VARCHAR2(255),
        ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE AANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        AFGEHANDELD NUMBER(1),
        CATEGORIE VARCHAR2(200),
        CATEGORIECODE VARCHAR2(80),
        DATUMAANMAAK DATE,
        DATUMAFHANDELING DATE,
        DATUMBEGINSTATUS DATE,
        DATUMEINDESTATUS DATE,
        HOOFDCATEGORIE VARCHAR2(80),
        HOOFDCATEGORIECODE VARCHAR2(80),
        IDENTIFICATIE VARCHAR2(255),
        KANAAL VARCHAR2(80),
        KAN_LEIDEN_TOT_ZAAK_ID VARCHAR2(255),
        ONDERWERP VARCHAR2(200),
        ONDERWERPCODE VARCHAR2(80),
        SOORT VARCHAR2(80),
        STATUS VARCHAR2(80),
        STATUSCODE VARCHAR2(80),
        STATUSVOLGORDE VARCHAR2(80),
        SUBCATEGORIE VARCHAR2(200),
        SUBCATEGORIECODE VARCHAR2(80)
);

CREATE TABLE KLANTCONTACT (
    KLANTCONTACT_ID VARCHAR2(255) PRIMARY KEY,
        EINDTIJD TIMESTAMP,
        HEEFT_BETREKKING_OP_ZAAK_ID VARCHAR2(255),
        HEEFT_KLANTCONTACTEN_BETROKKENE_ID VARCHAR2(255),
        KANAAL VARCHAR2(20),
        KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID VARCHAR2(255),
        NOTITIE CLOB,
        STARTTIJD TIMESTAMP,
        TIJDSDUUR TIMESTAMP,
        TOELICHTING CLOB,
        WACHTTIJDTOTAAL TIMESTAMP
);

CREATE TABLE KP_BTRKKN_ZK (
    KP_BTRKKN_ZK_ID VARCHAR2(255) PRIMARY KEY,
    BETROKKENE_ID VARCHAR2(255),
    ZAAK_ID VARCHAR2(255)
);

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_1 FOREIGN KEY (BETROKKENE_ID) REFERENCES BETROKKENE (BETROKKENE_ID);
-- BETROKKENE (many-to-many junction, Connector_ID: 290)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_2 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 290)

ALTER TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_1 FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- NIETNATUURLIJKPERSOON (many-to-many junction, Connector_ID: 152)

ALTER TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_2 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (NATUURLIJKPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 152)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_KAN_LEIDEN_TOT FOREIGN KEY (KAN_LEIDEN_TOT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 380)

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_IS FOREIGN KEY (IS_NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- IS (0..1 to 1, Connector_ID: 287)

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_IS_2 FOREIGN KEY (IS_NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (NATUURLIJKPERSOON_ID);
-- IS (0..1 to 1, Connector_ID: 289)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_HEEFT_BETREKKING_OP FOREIGN KEY (HEEFT_BETREKKING_OP_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP (0..* to 0..1, Connector_ID: 277)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_HEEFT_KLANTCONTACTEN FOREIGN KEY (HEEFT_KLANTCONTACTEN_BETROKKENE_ID) REFERENCES BETROKKENE (BETROKKENE_ID);
-- HEEFT_KLANTCONTACTEN (0..* to 0..1, Connector_ID: 285)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_KAN_LEIDEN_TOT FOREIGN KEY (KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 376)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (None to 0..*, Connector_ID: 243)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (None to 0..1, Connector_ID: 245)

