CREATE TABLE AANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        AFGEHANDELD NUMBER(1),
        CATEGORIE VARCHAR2(200),
        CATEGORIECODE VARCHAR2(80),
        DATUMAANMAAK DATE,
        DATUMAFHANDELING DATE,
        DATUMBEGINSTATUS DATE,
        DATUMEINDESTATUS DATE,
        HEEFT_DOCUMENTEN_DOCUMENT_ID VARCHAR2(255),
        HOOFDCATEGORIE VARCHAR2(80),
        HOOFDCATEGORIECODE VARCHAR2(80),
        IDENTIFICATIE VARCHAR2(255),
        KANAAL VARCHAR2(80),
        KAN_LEIDEN_TOT_ZAAK_ID VARCHAR2(255),
        MELDER_RECHTSPERSOON_ID VARCHAR2(255),
        ONDERWERP VARCHAR2(200),
        ONDERWERPCODE VARCHAR2(80),
        SOORT VARCHAR2(80),
        STATUS VARCHAR2(80),
        STATUSCODE VARCHAR2(80),
        STATUSVOLGORDE VARCHAR2(80),
        SUBCATEGORIE VARCHAR2(200),
        SUBCATEGORIECODE VARCHAR2(80)
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR2(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR2(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR2(200),
        DOCUMENTIDENTIFICATIE VARCHAR2(255),
        DOCUMENTTITEL VARCHAR2(200),
        VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE ENUM_INCIDENTTYPE_ENUM (
    ENUM_INCIDENTTYPE_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

CREATE TABLE ENUM_LEEFGEBIED_ENUM (
    ENUM_LEEFGEBIED_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

CREATE TABLE ENUM_VERZOEKSOORT_ENUM (
    ENUM_VERZOEKSOORT_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

CREATE TABLE INCIDENT (
    INCIDENT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMTIJDTOT TIMESTAMP,
        DATUMTIJDVANAF TIMESTAMP,
        INFORMERING_INFORMERING_ID VARCHAR2(255),
        LOCATIE VARCHAR2(255),
        OMSCHRIJVING CLOB,
        SOORT VARCHAR2(255),
        TOELICHTING CLOB
);

CREATE TABLE INFORMERING (
    INFORMERING_ID VARCHAR2(255) PRIMARY KEY,
        DATUM DATE,
        INDICATIEGEINFORMEERD NUMBER(1),
        INFORMERING_NATUURLIJKPERSOON_ID VARCHAR2(255),
        REACTIE CLOB,
        REDENNIETGEINFORMEERD CLOB
);

CREATE TABLE KLANTCONTACT (
    KLANTCONTACT_ID VARCHAR2(255) PRIMARY KEY,
        EINDTIJD TIMESTAMP,
        HEEFT_BETREKKING_OP_ZAAK_ID VARCHAR2(255),
        IS_GEVOERD_DOOR_MEDEWERKER_ID VARCHAR2(255),
        KANAAL VARCHAR2(20),
        KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID VARCHAR2(255),
        NOTITIE CLOB,
        STARTTIJD TIMESTAMP,
        TIJDSDUUR TIMESTAMP,
        TOELICHTING CLOB,
        WACHTTIJDTOTAAL TIMESTAMP
);

CREATE TABLE KP_ANVRGFMLDNG (
    KP_ANVRGFMLDNG_ID VARCHAR2(255) PRIMARY KEY,
    AANVRAAGOFMELDING_ID VARCHAR2(255),
    ONDERWERP_ID VARCHAR2(255)
);

CREATE TABLE KP_NTNTRLJKPRSN (
    KP_NTNTRLJKPRSN_ID VARCHAR2(255) PRIMARY KEY,
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255),
    NATUURLIJKPERSOON_ID VARCHAR2(255)
);

CREATE TABLE KP_ZK (
    KP_ZK_ID VARCHAR2(255) PRIMARY KEY,
    ZAAK_ID VARCHAR2(255),
    DOCUMENT_ID VARCHAR2(255)
);

CREATE TABLE KP_ZRGMLDNG (
    KP_ZRGMLDNG_ID VARCHAR2(255) PRIMARY KEY,
    ZORGMELDING_ID VARCHAR2(255),
    NATUURLIJKPERSOON_ID VARCHAR2(255)
);

CREATE TABLE LEEFGEBIED (
    LEEFGEBIED_ID VARCHAR2(255) PRIMARY KEY,
        LEEFGEBIED_ENUM_ID VARCHAR2(255),
        TOELICHTING CLOB
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID VARCHAR2(255) PRIMARY KEY,
        ACHTERNAAM VARCHAR2(200),
        DATUMINDIENST DATE,
        DATUMUITDIENST DATE,
        EMAILADRES VARCHAR2(255),
        EXTERN VARCHAR2(255),
        FUNCTIE VARCHAR2(50),
        GESLACHTSAANDUIDING VARCHAR2(255),
        MEDEWERKERIDENTIFICATIE VARCHAR2(255),
        MEDEWERKERTOELICHTING VARCHAR2(255),
        ROEPNAAM VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20),
        VOORLETTERS VARCHAR2(20),
        VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE NATUURLIJKPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON VARCHAR2(50),
        AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
        AANHEFAANSCHRIJVING VARCHAR2(50),
        ACADEMISCHETITEL VARCHAR2(80),
        ACHTERNAAM VARCHAR2(100),
        ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        ATTRIBUTE VARCHAR2(255),
        BURGERSERVICENUMMER VARCHAR2(255),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        GEBOORTELAND VARCHAR2(255),
        GEBOORTEPLAATS VARCHAR2(200),
        GESLACHTSAANDUIDING VARCHAR2(255),
        GESLACHTSNAAM VARCHAR2(200),
        GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
        HANDLICHTING VARCHAR2(50),
        INDICATIEAFSCHERMINGPERSOONSGEGEVENS NUMBER(1),
        INDICATIEOVERLEDEN NUMBER(1),
        LANDOVERLIJDEN VARCHAR2(255),
        NATIONALITEIT VARCHAR2(100),
        OVERLIJDENSPLAATS VARCHAR2(200),
        VOORLETTERSAANSCHRIJVING VARCHAR2(20),
        VOORNAMEN VARCHAR2(200),
        VOORNAMENAANSCHRIJVING VARCHAR2(200),
        VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMUITSCHRIJVING DATE,
        DATUMVOORTZETTING DATE,
        FAXNUMMER VARCHAR2(20),
        INGESCHREVEN NUMBER(1),
        INOPRICHTING NUMBER(1),
        KVKNUMMER VARCHAR2(255),
        NNPID VARCHAR2(255),
        RECHTSVORM VARCHAR2(255),
        RSINNUMMER VARCHAR2(255),
        STATUTAIRENAAM VARCHAR2(255),
        STATUTAIREZETEL VARCHAR2(255),
        WEBSITEURL VARCHAR2(200)
);

CREATE TABLE ONDERWERP (
    ONDERWERP_ID VARCHAR2(255) PRIMARY KEY,
        HOOFDONDERWERP_ONDERWERP_ID VARCHAR2(255),
        ISACTIEF NUMBER(1),
        NAAM VARCHAR2(80),
        TOELICHTING CLOB
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        ADRESCORRESPONDENTIE VARCHAR2(100),
        EMAILADRES VARCHAR2(80),
        FAXNUMMER VARCHAR2(20),
        IDENTIFICATIE VARCHAR2(255),
        KVKNUMMER VARCHAR2(20),
        NAAM VARCHAR2(200),
        RECHTSVORM VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE ZAAK (
    ZAAK_ID VARCHAR2(255) PRIMARY KEY,
        ARCHIEFNOMINATIE VARCHAR2(255),
        ATTRIBUTE VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMEINDEGEPLAND DATE,
        DATUMEINDEUITERLIJKEAFDOENING DATE,
        DATUMLAATSTEBETALING DATE,
        DATUMPUBLICATIE DATE,
        DATUMREGISTRATIE DATE,
        DATUMSTART DATE,
        DATUMVERNIETIGINGDOSSIER DATE,
        DOCUMENT VARCHAR2(255),
        DUURVERLENGING VARCHAR2(255),
        HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID VARCHAR2(255),
        INDICATIEBETALING VARCHAR2(255),
        INDICATIEDEELZAKEN VARCHAR2(255),
        INDICATIEOPSCHORTING VARCHAR2(255),
        IS_DEELZAAK_VAN_ZAAK_ID VARCHAR2(255),
        LEGES VARCHAR2(100),
        OMSCHRIJVING VARCHAR2(80),
        OMSCHRIJVINGRESULTAAT VARCHAR2(80),
        REDENOPSCHORTING VARCHAR2(200),
        REDENVERLENGING VARCHAR2(200),
        TOELICHTING VARCHAR2(255),
        TOELICHTINGRESULTAAT VARCHAR2(255),
        VERTROUWELIJKHEID VARCHAR2(255),
        ZAAKIDENTIFICATIE VARCHAR2(255),
        ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE ZORGELIJKE_SITUATIE (
    ZORGELIJKE_SITUATIE_ID VARCHAR2(255) PRIMARY KEY,
        BERUST_OP_INCIDENT_ID VARCHAR2(255),
        NADEREOMSCHRIJVING CLOB,
        SITIUATIESCHETS CLOB,
        TOELICHTING_LEEFGEBIED_ID VARCHAR2(255)
);

CREATE TABLE ZORGMELDING (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        BETREFT_NATUURLIJKPERSOON_ID VARCHAR2(255),
        NAAR_AANLEIDING_VAN_ZORGELIJKE_SITUATIE_ID VARCHAR2(255),
        NADEREOMSCHRIJVING CLOB,
        OMSCHRIJVING CLOB,
        TERUGKOPPELINGGEWENST NUMBER(1),
        VERZOEK_ENUM_ID VARCHAR2(255),
        ZORGMELDINGSOORT NUMBER
);

ALTER TABLE ZORGMELDING ADD CONSTRAINT FK_ZORGMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE NIETNATUURLIJKPERSOON ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_ANVRGFMLDNG ADD CONSTRAINT FK_KP_ANVRGFMLDNG_1 FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- AANVRAAGOFMELDING (many-to-many junction, Connector_ID: 381)

ALTER TABLE KP_ANVRGFMLDNG ADD CONSTRAINT FK_KP_ANVRGFMLDNG_2 FOREIGN KEY (ONDERWERP_ID) REFERENCES ONDERWERP (ONDERWERP_ID);
-- ONDERWERP (many-to-many junction, Connector_ID: 381)

ALTER TABLE KP_NTNTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_1 FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NIETNATUURLIJKPERSOON (many-to-many junction, Connector_ID: 152)

ALTER TABLE KP_NTNTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_2 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 152)

ALTER TABLE KP_ZK ADD CONSTRAINT FK_KP_ZK_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 269)

ALTER TABLE KP_ZK ADD CONSTRAINT FK_KP_ZK_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 269)

ALTER TABLE KP_ZK ADD CONSTRAINT FK_KP_ZK_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 281)

ALTER TABLE KP_ZK ADD CONSTRAINT FK_KP_ZK_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 281)

ALTER TABLE KP_ZRGMLDNG ADD CONSTRAINT FK_KP_ZRGMLDNG_1 FOREIGN KEY (ZORGMELDING_ID) REFERENCES ZORGMELDING (AANVRAAGOFMELDING_ID);
-- ZORGMELDING (many-to-many junction, Connector_ID: 1002)

ALTER TABLE KP_ZRGMLDNG ADD CONSTRAINT FK_KP_ZRGMLDNG_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 1002)

ALTER TABLE KP_ZRGMLDNG ADD CONSTRAINT FK_KP_ZRGMLDNG_1 FOREIGN KEY (ZORGMELDING_ID) REFERENCES ZORGMELDING (AANVRAAGOFMELDING_ID);
-- ZORGMELDING (many-to-many junction, Connector_ID: 1004)

ALTER TABLE KP_ZRGMLDNG ADD CONSTRAINT FK_KP_ZRGMLDNG_2 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1004)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_HEEFT_DOCUMENTEN FOREIGN KEY (HEEFT_DOCUMENTEN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- HEEFT_DOCUMENTEN (0..1 to 0..*, Connector_ID: 378)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_KAN_LEIDEN_TOT FOREIGN KEY (KAN_LEIDEN_TOT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 380)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_MELDER FOREIGN KEY (MELDER_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- MELDER (1..* to 0..1, Connector_ID: 377)

ALTER TABLE INCIDENT ADD CONSTRAINT FK_INCIDENT_INFORMERING FOREIGN KEY (INFORMERING_INFORMERING_ID) REFERENCES INFORMERING (INFORMERING_ID);
-- INFORMERING (1 to 0..*, Connector_ID: 1009)

ALTER TABLE INFORMERING ADD CONSTRAINT FK_INFORMERING_INFORMERING FOREIGN KEY (INFORMERING_NATUURLIJKPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- INFORMERING (0..* to 1, Connector_ID: 1010)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_HEEFT_BETREKKING_OP FOREIGN KEY (HEEFT_BETREKKING_OP_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP (0..* to 0..1, Connector_ID: 277)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_IS_GEVOERD_DOOR FOREIGN KEY (IS_GEVOERD_DOOR_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- IS_GEVOERD_DOOR (0..* to 0..1, Connector_ID: 275)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_KAN_LEIDEN_TOT FOREIGN KEY (KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 376)

ALTER TABLE LEEFGEBIED ADD CONSTRAINT FK_LEEFGEBIED_LEEFGEBIED_ENUM_ID FOREIGN KEY (LEEFGEBIED_ENUM_ID) REFERENCES ENUM_LEEFGEBIED_ENUM (ENUM_LEEFGEBIED_ENUM_ID);
-- LEEFGEBIED_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ONDERWERP ADD CONSTRAINT FK_ONDERWERP_HOOFDONDERWERP FOREIGN KEY (HOOFDONDERWERP_ONDERWERP_ID) REFERENCES ONDERWERP (ONDERWERP_ID);
-- HOOFDONDERWERP (0..* to 1, Connector_ID: 361)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (None to 0..*, Connector_ID: 243)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (None to 0..1, Connector_ID: 245)

ALTER TABLE ZORGELIJKE_SITUATIE ADD CONSTRAINT FK_ZORGELIJKE_SITUATIE_BERUST_OP FOREIGN KEY (BERUST_OP_INCIDENT_ID) REFERENCES INCIDENT (INCIDENT_ID);
-- BERUST_OP (1 to 0..*, Connector_ID: 1007)

ALTER TABLE ZORGELIJKE_SITUATIE ADD CONSTRAINT FK_ZORGELIJKE_SITUATIE_TOELICHTING FOREIGN KEY (TOELICHTING_LEEFGEBIED_ID) REFERENCES LEEFGEBIED (LEEFGEBIED_ID);
-- TOELICHTING (1 to 0..*, Connector_ID: 1008)

ALTER TABLE ZORGMELDING ADD CONSTRAINT FK_ZORGMELDING_BETREFT FOREIGN KEY (BETREFT_NATUURLIJKPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- BETREFT (0..* to 1, Connector_ID: 1003)

ALTER TABLE ZORGMELDING ADD CONSTRAINT FK_ZORGMELDING_NAAR_AANLEIDING_VAN FOREIGN KEY (NAAR_AANLEIDING_VAN_ZORGELIJKE_SITUATIE_ID) REFERENCES ZORGELIJKE_SITUATIE (ZORGELIJKE_SITUATIE_ID);
-- NAAR_AANLEIDING_VAN (1 to 1..*, Connector_ID: 1006)

ALTER TABLE ZORGMELDING ADD CONSTRAINT FK_ZORGMELDING_VERZOEK_ENUM_ID FOREIGN KEY (VERZOEK_ENUM_ID) REFERENCES ENUM_VERZOEKSOORT_ENUM (ENUM_VERZOEKSOORT_ENUM_ID);
-- VERZOEK_ENUM_ID (1 to 1, Connector_ID: enum_ref)

