CREATE TABLE PIP (
    PIP_ID NUMBER PRIMARY KEY,
    DAGTEKENINGINITIELEPIP DATE,
    DAGTEKENINGPIP DATE,
    EMAILCONTACTPERSOON VARCHAR2(255),
    INDICATORMAGOPLEIDINGAFMAKEN NUMBER(1),
    NAAMCONTACTPERSOON VARCHAR2(255)
);

CREATE TABLE LEERROUTE (
    LEERROUTE_ID NUMBER PRIMARY KEY,
    AFGESPROKEN_IN_PIP_ID NUMBER,
    EXAMENA2 VARCHAR2(255),
    GEENLEERBAARHEIDSTOETSZB VARCHAR2(255),
    GESCHATTEINTENSITEITB1ROUTE VARCHAR2(255),
    INDICATORALFABETISERING VARCHAR2(255),
    INDICATORMAGOPLEIDINGAFMAKEN VARCHAR2(255),
    INDICATORTOESTEMMINGEXAMENA2 VARCHAR2(255),
    LEERROUTETYPE VARCHAR2(255),
    NIVEAU VARCHAR2(255)
);

CREATE TABLE B1_ROUTE (
    B1_ROUTE_ID NUMBER PRIMARY KEY,
    AANTALGRATISEXAMENPOGINGENTEGOED NUMBER,
    EXAMENDATUM DATE,
    GEVOLGDEURENPARTICIPATIETAALLES NUMBER,
    ONDERDEEL_VAN__LEERROUTE_ID NUMBER,
    REDENGEENRESULTAAT VARCHAR2(255),
    RESULTAAT NUMBER
);

ALTER TABLE LEERROUTE ADD CONSTRAINT FK_LEERROUTE_AFGESPROKEN_IN FOREIGN KEY (AFGESPROKEN_IN_PIP_ID) REFERENCES PIP (PIP_ID);
-- AFGESPROKEN_IN (0..1 to 1, Connector_ID: 1620)

ALTER TABLE B1_ROUTE ADD CONSTRAINT FK_B1_ROUTE_ONDERDEEL_VAN_ FOREIGN KEY (ONDERDEEL_VAN__LEERROUTE_ID) REFERENCES LEERROUTE (LEERROUTE_ID);
-- ONDERDEEL_VAN_ (0..1 to 1, Connector_ID: 1630)

