CREATE TABLE `KADASTRALEONROERENDEZAAK` (
    `KADASTRALEONROERENDEZAAK_ID` INT PRIMARY KEY,
    `APPARTEMENTSRECHTVOLGNUMMER` VARCHAR(255),
    `BEGRENZING` VARCHAR(255),
    `CULTUURCODEONBEBOUWD` VARCHAR(255),
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `GERELATEERD_KADASTRALEONROERENDEZAAK_ID` INT,
    `IDENTIFICATIE` VARCHAR(255),
    `KADASTRALEGEMEENTE` VARCHAR(20),
    `KADASTRALEGEMEENTECODE` VARCHAR(20),
    `KOOPJAAR` INT,
    `KOOPSOM` VARCHAR(255),
    `LANDINRICHTINGRENTEBEDRAG` DECIMAL(10,2),
    `LANDINRICHTINGRENTEEINDEJAAR` DATE,
    `LIGGING` VARCHAR(255),
    `LOCATIEOMSCHRIJVING` VARCHAR(255),
    `OPPERVLAKTE` INT,
    `PERCEELNUMMER` VARCHAR(255),
    `SECTIE` VARCHAR(255),
    `VALUTACODE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `ADRESSEERBAAROBJECT` (
    `ADRESSEERBAAROBJECT_ID` INT PRIMARY KEY,
    `IDENTIFICATIE` VARCHAR(255),
    `TYPEADRESSEERBAAROBJECT` VARCHAR(255),
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `RECHTSPERSOON` (
    `RECHTSPERSOON_ID` INT PRIMARY KEY,
    `ADRESBINNENLAND` VARCHAR(255),
    `ADRESBUITENLAND` VARCHAR(255),
    `ADRESCORRESPONDENTIE` VARCHAR(100),
    `EMAILADRES` VARCHAR(80),
    `FAXNUMMER` VARCHAR(20),
    `IDENTIFICATIE` VARCHAR(255),
    `KVKNUMMER` VARCHAR(20),
    `NAAM` VARCHAR(200),
    `RECHTSVORM` VARCHAR(100),
    `REKENINGNUMMER` VARCHAR(255),
    `TELEFOONNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `KP_KDSTRLMTT_KDSTRLNRRNDZK` (
    `KP_KDSTRLMTT_KDSTRLNRRNDZK_ID` INT PRIMARY KEY,
    `KADASTRALEMUTATIE_ID` INT,
    `KADASTRALEONROERENDEZAAK_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_RCHTSPRSN_KDSTRLMTT` (
    `KP_RCHTSPRSN_KDSTRLMTT_ID` INT PRIMARY KEY,
    `RECHTSPERSOON_ID` INT,
    `KADASTRALEMUTATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `ZAKELIJKRECHT` (
    `ZAKELIJKRECHT_ID` INT PRIMARY KEY,
    `AARDZAKELIJKRECHT` VARCHAR(255),
    `DATUMEINDERECHT` DATE,
    `DATUMINGANGRECHT` DATE,
    `IDENTIFICATIEZAKELIJKRECHT` VARCHAR(255),
    `IS_BELAST_MET_ZAKELIJKRECHT_ID` INT,
    `RUST_OP_KADASTRALEONROERENDEZAAK_ID` INT,
    `TOELICHTINGBEWAARDER` VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE `DOCUMENT` (
    `DOCUMENT_ID` INT PRIMARY KEY,
    `COCUMENTBESCHRIJVING` VARCHAR(255),
    `DATUMCREATIEDOCUMENT` DATE,
    `DATUMONTVANGSTDOCUMENT` DATE,
    `DATUMVERZENDINGDOCUMENT` DATE,
    `DOCUMENTAUTEUR` VARCHAR(200),
    `DOCUMENTIDENTIFICATIE` VARCHAR(255),
    `DOCUMENTTITEL` VARCHAR(200),
    `VERTROUWELIJKAANDUIDING` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `KADASTRALEMUTATIE` (
    `KADASTRALEMUTATIE_ID` INT PRIMARY KEY,
    `HEEFT_BETREKKING_OP_ZAKELIJKRECHT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KADASTRAALPERCEEL` (
    `KADASTRALEONROERENDEZAAK_ID` INT PRIMARY KEY,
    `AANDUIDINGSOORTGROOTTE` VARCHAR(255),
    `BEGRENZINGPERCEEL` VARCHAR(255),
    `GROOTTEPERCEEL` VARCHAR(255),
    `INDICATIEDEELPERCEEL` BOOLEAN,
    `OMSCHRIJVINGDEELPERCEEL` VARCHAR(20),
    `PLAATSCOORDINATENPERCEEL` GEOMETRY
) ENGINE=InnoDB;

CREATE TABLE `APPARTEMENTSRECHT` (
    `KADASTRALEONROERENDEZAAK_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` (
    `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_ID` INT PRIMARY KEY,
    `IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID` INT,
    `IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KADASTRALEONROERENDEZAAKAANTEKENING` (
    `KADASTRALEONROERENDEZAAKAANTEKENING_ID` INT PRIMARY KEY,
    `AARDAANTEKENINGKADASTRAALOBJECT` VARCHAR(255),
    `BESCHRIJVINGAANTEKENINGKADASTRAALOBJECT` VARCHAR(255),
    `DATUMBEGINAANTEKENINGKADASTRAALOBJECT` DATE,
    `DATUMEINDEAANTEKENINGKADASTRAALOBJECT` DATE,
    `HEEFT_BETREKKING_OP_KADASTRALEONROERENDEZAAK_ID` INT,
    `KADASTERIDENTIFICATIEAANTEKENING` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `KADASTRAALPERCEEL` ADD CONSTRAINT FK_KADASTRAALPERCEEL_GEN_KADASTRALEONROERENDEZAAK FOREIGN KEY (`KADASTRALEONROERENDEZAAK_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`KADASTRALEONROERENDEZAAK_ID`);
-- Generalization to KADASTRALEONROERENDEZAAK

ALTER TABLE `APPARTEMENTSRECHT` ADD CONSTRAINT FK_APPARTEMENTSRECHT_GEN_KADASTRALEONROERENDEZAAK FOREIGN KEY (`KADASTRALEONROERENDEZAAK_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`KADASTRALEONROERENDEZAAK_ID`);
-- Generalization to KADASTRALEONROERENDEZAAK

ALTER TABLE `KP_KDSTRLMTT_KDSTRLNRRNDZK` ADD CONSTRAINT FK_KP_KDSTRLMTT_KDSTRLNRRNDZK_1 FOREIGN KEY (`KADASTRALEMUTATIE_ID`) REFERENCES `KADASTRALEMUTATIE` (`KADASTRALEMUTATIE_ID`);
-- KADASTRALEMUTATIE (many-to-many junction, Connector_ID: 740)

ALTER TABLE `KP_KDSTRLMTT_KDSTRLNRRNDZK` ADD CONSTRAINT FK_KP_KDSTRLMTT_KDSTRLNRRNDZK_2 FOREIGN KEY (`KADASTRALEONROERENDEZAAK_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`KADASTRALEONROERENDEZAAK_ID`);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 740)

ALTER TABLE `KP_RCHTSPRSN_KDSTRLMTT` ADD CONSTRAINT FK_KP_RCHTSPRSN_KDSTRLMTT_1 FOREIGN KEY (`RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 1909)

ALTER TABLE `KP_RCHTSPRSN_KDSTRLMTT` ADD CONSTRAINT FK_KP_RCHTSPRSN_KDSTRLMTT_2 FOREIGN KEY (`KADASTRALEMUTATIE_ID`) REFERENCES `KADASTRALEMUTATIE` (`KADASTRALEMUTATIE_ID`);
-- KADASTRALEMUTATIE (many-to-many junction, Connector_ID: 1909)

ALTER TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_1 FOREIGN KEY (`IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`KADASTRALEONROERENDEZAAK_ID`);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_2 FOREIGN KEY (`IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`KADASTRALEONROERENDEZAAK_ID`);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE `KADASTRALEMUTATIE` ADD CONSTRAINT FK_KADASTRALEMUTATIE_HEEFT_BETREKKING_OP FOREIGN KEY (`HEEFT_BETREKKING_OP_ZAKELIJKRECHT_ID`) REFERENCES `ZAKELIJKRECHT` (`ZAKELIJKRECHT_ID`);
-- HEEFT_BETREKKING_OP (1 to 0..*, Connector_ID: 741)

ALTER TABLE `KADASTRALEONROERENDEZAAK` ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GERELATEERD FOREIGN KEY (`GERELATEERD_KADASTRALEONROERENDEZAAK_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`KADASTRALEONROERENDEZAAK_ID`);
-- GERELATEERD (1 to 0..*, Connector_ID: 1938)

ALTER TABLE `ZAKELIJKRECHT` ADD CONSTRAINT FK_ZAKELIJKRECHT_IS_BELAST_MET FOREIGN KEY (`IS_BELAST_MET_ZAKELIJKRECHT_ID`) REFERENCES `ZAKELIJKRECHT` (`ZAKELIJKRECHT_ID`);
-- IS_BELAST_MET (0..1 to 0..*, Connector_ID: 1944)

ALTER TABLE `ZAKELIJKRECHT` ADD CONSTRAINT FK_ZAKELIJKRECHT_RUST_OP FOREIGN KEY (`RUST_OP_KADASTRALEONROERENDEZAAK_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`KADASTRALEONROERENDEZAAK_ID`);
-- RUST_OP (1..* to 0..1, Connector_ID: 1947)

ALTER TABLE `KADASTRALEONROERENDEZAAKAANTEKENING` ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAKAANTEKENING_HEEFT_BETREKKING_OP FOREIGN KEY (`HEEFT_BETREKKING_OP_KADASTRALEONROERENDEZAAK_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`KADASTRALEONROERENDEZAAK_ID`);
-- HEEFT_BETREKKING_OP (0..* to 1, Connector_ID: 1989)

