CREATE TABLE [ADRESSEERBAAROBJECT] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID] INT,
    [HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID] INT,
    [IDENTIFICATIE] VARCHAR(255),
    [TYPEADRESSEERBAAROBJECT] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [LIGPLAATS] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] DATE,
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD] BIT,
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [VERSIE] VARCHAR(255)
);

CREATE TABLE [OPENBARERUIMTE] (
    [OPENBARERUIMTE_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD] BIT,
    [GEOMETRIE] GEOMETRY,
    [HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS] VARCHAR(255),
    [HUISNUMMERRANGE_EVEN_NUMMERS] VARCHAR(255),
    [HUISNUMMERRANGE_ONEVEN_NUMMERS] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [LABELNAAM] VARCHAR(80),
    [NAAMOPENBARERUIMTE] VARCHAR(80),
    [STATUS] VARCHAR(255),
    [STRAATCODE] VARCHAR(80),
    [STRAATNAAM] VARCHAR(255),
    [TYPEOPENBARERUIMTE] VARCHAR(255),
    [VERSIE] INT,
    [WEGSEGMENT] VARCHAR(255)
);

CREATE TABLE [OVERIGEADRESSEERBAAROBJECTAANDUIDING] (
    [NUMMERAANDUIDING_ID] INT PRIMARY KEY,
    [IDENTIFICATIECODE] VARCHAR(255)
);

CREATE TABLE [OVERIGBENOEMDTERREIN] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [GEBRUIKSDOELOVERIGBENOEMDTERREIN] VARCHAR(255),
    [HEEFT_ALS_OFFICIEEL_ADRES_OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID] INT,
    [OVERIGBENOEMDTERREINIDENTIFICATIE] VARCHAR(255)
);

CREATE TABLE [VERBLIJFSOBJECT] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [AANTALKAMERS] VARCHAR(255),
    [BEGINGELDIGHEID] DATE,
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDGELDIGHEID] DATE,
    [GEBRUIKSDOEL] VARCHAR(255),
    [GECONSTATEERD] BIT,
    [GEOMETRIE] GEOMETRY,
    [HOOGSTEBOUWLAAG] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [LAAGSTEBOUWLAAG] VARCHAR(255),
    [ONTSLUITINGVERDIEPING] VARCHAR(255),
    [OPPERVLAKTE] INT,
    [SOORTWOONOBJECT] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [TOEGANGBOUWLAAG] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [NUMMERAANDUIDING] (
    [NUMMERAANDUIDING_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDEGELDIGHEID] DATE,
    [GECONSTATEERD] BIT,
    [GEOMETRIE] GEOMETRY,
    [HUISLETTER] VARCHAR(255),
    [HUISNUMMER] VARCHAR(255),
    [HUISNUMMERTOEVOEGING] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [LIGT_AAN_OPENBARERUIMTE_ID] INT,
    [POSTCODE] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [TYPEADRESSEERBAAROBJECT] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [OVERIGGEBOUWDOBJECT] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [BOUWJAAR] VARCHAR(255),
    [HEEFT_ALS_OFFICIEEL_ADRES_OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID] INT,
    [INDICATIEPLANOBJECT] BIT,
    [OVERIGGEBOUWDOBJECTIDENTIFICATIE] VARCHAR(255)
);

CREATE TABLE [STANDPLAATS] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [DATUM_BEGIN_GELDIGHEID] DATE,
    [DATUM_EINDE] DATE,
    [DATUM_EINDE_GELDIGHEID] DATE,
    [DATUM_INGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [GECONSTATEERD] BIT,
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [VERSIE] INT
);

ALTER TABLE [VERBLIJFSOBJECT] ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [LIGPLAATS] ADD CONSTRAINT FK_LIGPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [STANDPLAATS] ADD CONSTRAINT FK_STANDPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [OVERIGEADRESSEERBAAROBJECTAANDUIDING] ADD CONSTRAINT FK_OVERIGEADRESSEERBAAROBJECTAANDUIDING_GEN_NUMMERAANDUIDING FOREIGN KEY ([NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- Generalization to NUMMERAANDUIDING

ALTER TABLE [OVERIGGEBOUWDOBJECT] ADD CONSTRAINT FK_OVERIGGEBOUWDOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [OVERIGBENOEMDTERREIN] ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [OVERIGBENOEMDTERREIN] ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_HEEFT_ALS_OFFICIEEL_ADRES FOREIGN KEY ([HEEFT_ALS_OFFICIEEL_ADRES_OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_OFFICIEEL_ADRES (0..1 to 1, Connector_ID: 1952)

ALTER TABLE [OVERIGGEBOUWDOBJECT] ADD CONSTRAINT FK_OVERIGGEBOUWDOBJECT_HEEFT_ALS_OFFICIEEL_ADRES FOREIGN KEY ([HEEFT_ALS_OFFICIEEL_ADRES_OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_OFFICIEEL_ADRES (0..1 to 0..1, Connector_ID: 1953)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY ([HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY ([HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE [NUMMERAANDUIDING] ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY ([LIGT_AAN_OPENBARERUIMTE_ID]) REFERENCES [OPENBARERUIMTE] ([OPENBARERUIMTE_ID]);
-- LIGT_AAN (0..* to 1, Connector_ID: 2281)

