CREATE TABLE `VERVOERDER` (
    `LEVERANCIER_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `ZIEKMELDING_LEERLINGENVERVOER` (
    `ZIEKMELDING_LEERLINGENVERVOER_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `KLACHT_LEERLINGENVERVOER` (
    `KLACHT_LEERLINGENVERVOER_ID` INT PRIMARY KEY,
    `BETREFT_LEERLING_ID` INT,
    `BETREFT_VERVOERDER_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_PRCSVRBL_ONDRWJS_ODR_OF_VRZRGR` (
    `KP_PRCSVRBL_ONDRWJS_ODR_OF_VRZRGR_ID` INT PRIMARY KEY,
    `PROCESVERBAAL_ONDERWIJS_ID` INT,
    `OUDER_OF_VERZORGER_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VERZUIMSOORT_ENUM` (
    `VERZUIMSOORT_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `VERZUIMSOORT_ENUM` (`VERZUIMSOORT_ENUM_ID`, VALUE) VALUES
    (1, 'ABSOLUUT'),
    (2, 'RELATIEF');

CREATE TABLE `VERZUIMMELDING` (
    `AANVRAAGOFMELDING_1020_ID` INT PRIMARY KEY,
    `DATUMEINDE` DATE,
    `DATUMSTART` DATE,
    `HEEFT_SCHOOL_ID` INT,
    `VOORSTELSCHOOL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `PROCESVERBAAL_ONDERWIJS` (
    `BESLISSING_ID` INT PRIMARY KEY,
    `DATUMAFGEHANDELD` DATE,
    `DATUMEINDEPROEFTIJD` DATETIME,
    `DATUMINGELICHT` DATE,
    `DATUMUITSPRAAK` DATE,
    `DATUMZITTING` DATE,
    `GELDBOETE` VARCHAR(255),
    `GELDBOETEVOORWAARDELIJK_ENUM_ID` INT,
    `OPMERKINGEN` VARCHAR(255),
    `PROEFTIJD` DATETIME,
    `REDEN` VARCHAR(255),
    `SANCTIESOORT` VARCHAR(100),
    `UITSPRAAK` VARCHAR(255),
    `VERZUIMSOORT_ENUM_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BSCHKKNG_LRLNGNVRVR_VRVRDR` (
    `KP_BSCHKKNG_LRLNGNVRVR_VRVRDR_ID` INT PRIMARY KEY,
    `BESCHIKKING_LEERLINGENVERVOER_ID` INT,
    `VERVOERDER_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `AANVRAAGOFMELDING_116` (
    `AANVRAAGOFMELDING_1020_ID` INT PRIMARY KEY,
    `BETREFT_LEERLING_ID` INT,
    `BETREFT_SCHOOL_ID` INT,
    `DATUM` DATE,
    `LEIDT_TOT_BESLISSING_ID` INT,
    `OPMERKINGEN` VARCHAR(255),
    `REDEN` VARCHAR(255),
    `SOORTVERZUIMOFAANVRAAG_ENUM_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `LEERPLICHTAMBTENAAR` (
    `LEERPLICHTAMBTENAAR_ID` INT PRIMARY KEY,
    `OPGELEGD_DOOR_PROCESVERBAAL_ONDERWIJS_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VRIJSTELLING` (
    `BESLISSING_ID` INT PRIMARY KEY,
    `AANVRAAGTOEGEKEND_ENUM_ID` INT,
    `BUITENLANDSESCHOOLLOCATIE` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMSTART` DATE,
    `HEEFT_SCHOOL_ID` INT,
    `VERZUIMSOORT_ENUM_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_DRGLDNG_OM_ODR_OF_VRZRGR` (
    `KP_DRGLDNG_OM_ODR_OF_VRZRGR_ID` INT PRIMARY KEY,
    `DOORGELEIDING_OM_ID` INT,
    `OUDER_OF_VERZORGER_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `BOOLEAN_ENUM` (
    `BOOLEAN_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`, VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE `DOORGELEIDING_OM` (
    `BESLISSING_ID` INT PRIMARY KEY,
    `AFDOENING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `LEERLING` (
    `LEERLING_ID` INT PRIMARY KEY,
    `BETREFT_LEERLING_PROCESVERBAAL_ONDERWIJS_ID` INT,
    `BETREFT_ZIEKMELDING_LEERLINGENVERVOER_ID` INT,
    `HEEFT_VERZUIMMELDING_ID` INT,
    `HEEFT_VRIJSTELLING_ID` INT,
    `KWETSBAREJONGERE_ENUM_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `BESCHIKKING_LEERLINGENVERVOER` (
    `BESLISSING_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `BESLISSING` (
    `BESLISSING_ID` INT PRIMARY KEY,
    `BEHANDELAAR_LEERPLICHTAMBTENAAR_ID` INT,
    `BETREFT_LEERLING_ID` INT,
    `BETREFT_SCHOOL_ID` INT,
    `DATUM` DATE,
    `OPMERKINGEN` TEXT,
    `REDEN` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `AANVRAAGOFMELDING_1020` (
    `AANVRAAGOFMELDING_1020_ID` INT PRIMARY KEY,
    `AFGEHANDELD_ENUM_ID` INT,
    `CATEGORIE` VARCHAR(200),
    `CATEGORIECODE` VARCHAR(80),
    `DATUMAANMAAK` DATE,
    `DATUMAFHANDELING` DATE,
    `DATUMBEGINSTATUS` DATE,
    `DATUMEINDESTATUS` DATE,
    `HOOFDCATEGORIE` VARCHAR(80),
    `HOOFDCATEGORIECODE` VARCHAR(80),
    `IDENTIFICATIE` VARCHAR(255),
    `KANAAL` VARCHAR(80),
    `ONDERWERP` VARCHAR(200),
    `ONDERWERPCODE` VARCHAR(80),
    `SOORT` VARCHAR(80),
    `STATUS` VARCHAR(80),
    `STATUSCODE` VARCHAR(80),
    `STATUSVOLGORDE` VARCHAR(80),
    `SUBCATEGORIE` VARCHAR(200),
    `SUBCATEGORIECODE` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `OUDER_OF_VERZORGER` (
    `OUDER_OF_VERZORGER_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `VERLOFAANVRAAG` (
    `AANVRAAGOFMELDING_1020_ID` INT PRIMARY KEY,
    `DATUMSTART` DATE,
    `DATUMTOT` DATE,
    `SOORTVERLOF` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `LEVERANCIER` (
    `LEVERANCIER_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(200),
    `NUMMER` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `AANVRAAGVRIJSTELLING` (
    `AANVRAAGOFMELDING_1020_ID` INT PRIMARY KEY,
    `BUITENLANDSESCHOOLLOCATIE` VARCHAR(255),
    `DATUMAANVRAAG` DATE
) ENGINE=InnoDB;

CREATE TABLE `HALT_VERWIJZING` (
    `BESLISSING_ID` INT PRIMARY KEY,
    `AFDOENING` VARCHAR(255),
    `DATUMMUTATIE` DATE,
    `DATUMRETOUR` DATE,
    `MEMO` TEXT
) ENGINE=InnoDB;

CREATE TABLE `SCHOOL` (
    `SCHOOL_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

ALTER TABLE `AANVRAAGOFMELDING_116` ADD CONSTRAINT FK_AANVRAAGOFMELDING_116_GEN_AANVRAAGOFMELDING_1020 FOREIGN KEY (`AANVRAAGOFMELDING_1020_ID`) REFERENCES `AANVRAAGOFMELDING_1020` (`AANVRAAGOFMELDING_1020_ID`);
-- Generalization to AANVRAAGOFMELDING_1020

ALTER TABLE `AANVRAAGVRIJSTELLING` ADD CONSTRAINT FK_AANVRAAGVRIJSTELLING_GEN_AANVRAAGOFMELDING_116 FOREIGN KEY (`AANVRAAGOFMELDING_1020_ID`) REFERENCES `AANVRAAGOFMELDING_116` (`AANVRAAGOFMELDING_1020_ID`);
-- Generalization to AANVRAAGOFMELDING_116

ALTER TABLE `BESCHIKKING_LEERLINGENVERVOER` ADD CONSTRAINT FK_BESCHIKKING_LEERLINGENVERVOER_GEN_BESLISSING FOREIGN KEY (`BESLISSING_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- Generalization to BESLISSING

ALTER TABLE `DOORGELEIDING_OM` ADD CONSTRAINT FK_DOORGELEIDING_OM_GEN_BESLISSING FOREIGN KEY (`BESLISSING_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- Generalization to BESLISSING

ALTER TABLE `HALT_VERWIJZING` ADD CONSTRAINT FK_HALT_VERWIJZING_GEN_BESLISSING FOREIGN KEY (`BESLISSING_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- Generalization to BESLISSING

ALTER TABLE `PROCESVERBAAL_ONDERWIJS` ADD CONSTRAINT FK_PROCESVERBAAL_ONDERWIJS_GEN_BESLISSING FOREIGN KEY (`BESLISSING_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- Generalization to BESLISSING

ALTER TABLE `VERLOFAANVRAAG` ADD CONSTRAINT FK_VERLOFAANVRAAG_GEN_AANVRAAGOFMELDING_116 FOREIGN KEY (`AANVRAAGOFMELDING_1020_ID`) REFERENCES `AANVRAAGOFMELDING_116` (`AANVRAAGOFMELDING_1020_ID`);
-- Generalization to AANVRAAGOFMELDING_116

ALTER TABLE `VERVOERDER` ADD CONSTRAINT FK_VERVOERDER_GEN_LEVERANCIER FOREIGN KEY (`LEVERANCIER_ID`) REFERENCES `LEVERANCIER` (`LEVERANCIER_ID`);
-- Generalization to LEVERANCIER

ALTER TABLE `VERZUIMMELDING` ADD CONSTRAINT FK_VERZUIMMELDING_GEN_AANVRAAGOFMELDING_116 FOREIGN KEY (`AANVRAAGOFMELDING_1020_ID`) REFERENCES `AANVRAAGOFMELDING_116` (`AANVRAAGOFMELDING_1020_ID`);
-- Generalization to AANVRAAGOFMELDING_116

ALTER TABLE `VRIJSTELLING` ADD CONSTRAINT FK_VRIJSTELLING_GEN_BESLISSING FOREIGN KEY (`BESLISSING_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- Generalization to BESLISSING

ALTER TABLE `KP_PRCSVRBL_ONDRWJS_ODR_OF_VRZRGR` ADD CONSTRAINT FK_KP_PRCSVRBL_ONDRWJS_ODR_OF_VRZRGR_1 FOREIGN KEY (`PROCESVERBAAL_ONDERWIJS_ID`) REFERENCES `PROCESVERBAAL_ONDERWIJS` (`BESLISSING_ID`);
-- PROCESVERBAAL_ONDERWIJS (many-to-many junction, Connector_ID: 1231)

ALTER TABLE `KP_PRCSVRBL_ONDRWJS_ODR_OF_VRZRGR` ADD CONSTRAINT FK_KP_PRCSVRBL_ONDRWJS_ODR_OF_VRZRGR_2 FOREIGN KEY (`OUDER_OF_VERZORGER_ID`) REFERENCES `OUDER_OF_VERZORGER` (`OUDER_OF_VERZORGER_ID`);
-- OUDER_OF_VERZORGER (many-to-many junction, Connector_ID: 1231)

ALTER TABLE `KP_DRGLDNG_OM_ODR_OF_VRZRGR` ADD CONSTRAINT FK_KP_DRGLDNG_OM_ODR_OF_VRZRGR_1 FOREIGN KEY (`DOORGELEIDING_OM_ID`) REFERENCES `DOORGELEIDING_OM` (`BESLISSING_ID`);
-- DOORGELEIDING_OM (many-to-many junction, Connector_ID: 1238)

ALTER TABLE `KP_DRGLDNG_OM_ODR_OF_VRZRGR` ADD CONSTRAINT FK_KP_DRGLDNG_OM_ODR_OF_VRZRGR_2 FOREIGN KEY (`OUDER_OF_VERZORGER_ID`) REFERENCES `OUDER_OF_VERZORGER` (`OUDER_OF_VERZORGER_ID`);
-- OUDER_OF_VERZORGER (many-to-many junction, Connector_ID: 1238)

ALTER TABLE `KP_BSCHKKNG_LRLNGNVRVR_VRVRDR` ADD CONSTRAINT FK_KP_BSCHKKNG_LRLNGNVRVR_VRVRDR_1 FOREIGN KEY (`BESCHIKKING_LEERLINGENVERVOER_ID`) REFERENCES `BESCHIKKING_LEERLINGENVERVOER` (`BESLISSING_ID`);
-- BESCHIKKING_LEERLINGENVERVOER (many-to-many junction, Connector_ID: 1243)

ALTER TABLE `KP_BSCHKKNG_LRLNGNVRVR_VRVRDR` ADD CONSTRAINT FK_KP_BSCHKKNG_LRLNGNVRVR_VRVRDR_2 FOREIGN KEY (`VERVOERDER_ID`) REFERENCES `VERVOERDER` (`LEVERANCIER_ID`);
-- VERVOERDER (many-to-many junction, Connector_ID: 1243)

ALTER TABLE `LEERLING` ADD CONSTRAINT FK_LEERLING_BETREFT FOREIGN KEY (`BETREFT_ZIEKMELDING_LEERLINGENVERVOER_ID`) REFERENCES `ZIEKMELDING_LEERLINGENVERVOER` (`ZIEKMELDING_LEERLINGENVERVOER_ID`);
-- BETREFT (1 to 0..*, Connector_ID: 1221)

ALTER TABLE `LEERLING` ADD CONSTRAINT FK_LEERLING_HEEFT FOREIGN KEY (`HEEFT_VRIJSTELLING_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 1222)

ALTER TABLE `VRIJSTELLING` ADD CONSTRAINT FK_VRIJSTELLING_HEEFT FOREIGN KEY (`HEEFT_SCHOOL_ID`) REFERENCES `SCHOOL` (`SCHOOL_ID`);
-- HEEFT (0..* to 1, Connector_ID: 1223)

ALTER TABLE `LEERLING` ADD CONSTRAINT FK_LEERLING_HEEFT_2 FOREIGN KEY (`HEEFT_VERZUIMMELDING_ID`) REFERENCES `AANVRAAGOFMELDING_1020` (`AANVRAAGOFMELDING_1020_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 1225)

ALTER TABLE `VERZUIMMELDING` ADD CONSTRAINT FK_VERZUIMMELDING_HEEFT FOREIGN KEY (`HEEFT_SCHOOL_ID`) REFERENCES `SCHOOL` (`SCHOOL_ID`);
-- HEEFT (0..* to 1, Connector_ID: 1226)

ALTER TABLE `LEERLING` ADD CONSTRAINT FK_LEERLING_BETREFT_LEERLING FOREIGN KEY (`BETREFT_LEERLING_PROCESVERBAAL_ONDERWIJS_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- BETREFT_LEERLING (1 to 0..*, Connector_ID: 1230)

ALTER TABLE `LEERPLICHTAMBTENAAR` ADD CONSTRAINT FK_LEERPLICHTAMBTENAAR_OPGELEGD_DOOR FOREIGN KEY (`OPGELEGD_DOOR_PROCESVERBAAL_ONDERWIJS_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- OPGELEGD_DOOR (1 to 0..*, Connector_ID: 1233)

ALTER TABLE `KLACHT_LEERLINGENVERVOER` ADD CONSTRAINT FK_KLACHT_LEERLINGENVERVOER_BETREFT FOREIGN KEY (`BETREFT_VERVOERDER_ID`) REFERENCES `LEVERANCIER` (`LEVERANCIER_ID`);
-- BETREFT (0..* to 1, Connector_ID: 1235)

ALTER TABLE `KLACHT_LEERLINGENVERVOER` ADD CONSTRAINT FK_KLACHT_LEERLINGENVERVOER_BETREFT_2 FOREIGN KEY (`BETREFT_LEERLING_ID`) REFERENCES `LEERLING` (`LEERLING_ID`);
-- BETREFT (0..* to 1, Connector_ID: 1236)

ALTER TABLE `BESLISSING` ADD CONSTRAINT FK_BESLISSING_BETREFT FOREIGN KEY (`BETREFT_SCHOOL_ID`) REFERENCES `SCHOOL` (`SCHOOL_ID`);
-- BETREFT (0..* to 0..1, Connector_ID: 1240)

ALTER TABLE `BESLISSING` ADD CONSTRAINT FK_BESLISSING_BEHANDELAAR FOREIGN KEY (`BEHANDELAAR_LEERPLICHTAMBTENAAR_ID`) REFERENCES `LEERPLICHTAMBTENAAR` (`LEERPLICHTAMBTENAAR_ID`);
-- BEHANDELAAR (0..* to 1, Connector_ID: 1241)

ALTER TABLE `BESLISSING` ADD CONSTRAINT FK_BESLISSING_BETREFT_2 FOREIGN KEY (`BETREFT_LEERLING_ID`) REFERENCES `LEERLING` (`LEERLING_ID`);
-- BETREFT (0..* to 1, Connector_ID: 1242)

ALTER TABLE `AANVRAAGOFMELDING_116` ADD CONSTRAINT FK_AANVRAAGOFMELDING_116_BETREFT FOREIGN KEY (`BETREFT_SCHOOL_ID`) REFERENCES `SCHOOL` (`SCHOOL_ID`);
-- BETREFT (0..* to 0..1, Connector_ID: 1246)

ALTER TABLE `AANVRAAGOFMELDING_116` ADD CONSTRAINT FK_AANVRAAGOFMELDING_116_LEIDT_TOT FOREIGN KEY (`LEIDT_TOT_BESLISSING_ID`) REFERENCES `BESLISSING` (`BESLISSING_ID`);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 1247)

ALTER TABLE `AANVRAAGOFMELDING_116` ADD CONSTRAINT FK_AANVRAAGOFMELDING_116_BETREFT_2 FOREIGN KEY (`BETREFT_LEERLING_ID`) REFERENCES `LEERLING` (`LEERLING_ID`);
-- BETREFT (0..* to 1, Connector_ID: 1248)

ALTER TABLE `AANVRAAGOFMELDING_116` ADD CONSTRAINT FK_AANVRAAGOFMELDING_116_SOORTVERZUIMOFAANVRAAG_ENUM_ID FOREIGN KEY (`SOORTVERZUIMOFAANVRAAG_ENUM_ID`) REFERENCES `VERZUIMSOORT_ENUM` (`VERZUIMSOORT_ENUM_ID`);
-- SOORTVERZUIMOFAANVRAAG_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `PROCESVERBAAL_ONDERWIJS` ADD CONSTRAINT FK_PROCESVERBAAL_ONDERWIJS_VERZUIMSOORT_ENUM_ID FOREIGN KEY (`VERZUIMSOORT_ENUM_ID`) REFERENCES `VERZUIMSOORT_ENUM` (`VERZUIMSOORT_ENUM_ID`);
-- VERZUIMSOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `PROCESVERBAAL_ONDERWIJS` ADD CONSTRAINT FK_PROCESVERBAAL_ONDERWIJS_GELDBOETEVOORWAARDELIJK_ENUM_ID FOREIGN KEY (`GELDBOETEVOORWAARDELIJK_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GELDBOETEVOORWAARDELIJK_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VRIJSTELLING` ADD CONSTRAINT FK_VRIJSTELLING_AANVRAAGTOEGEKEND_ENUM_ID FOREIGN KEY (`AANVRAAGTOEGEKEND_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- AANVRAAGTOEGEKEND_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VRIJSTELLING` ADD CONSTRAINT FK_VRIJSTELLING_VERZUIMSOORT_ENUM_ID FOREIGN KEY (`VERZUIMSOORT_ENUM_ID`) REFERENCES `VERZUIMSOORT_ENUM` (`VERZUIMSOORT_ENUM_ID`);
-- VERZUIMSOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `LEERLING` ADD CONSTRAINT FK_LEERLING_KWETSBAREJONGERE_ENUM_ID FOREIGN KEY (`KWETSBAREJONGERE_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- KWETSBAREJONGERE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `AANVRAAGOFMELDING_1020` ADD CONSTRAINT FK_AANVRAAGOFMELDING_1020_AFGEHANDELD_ENUM_ID FOREIGN KEY (`AFGEHANDELD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- AFGEHANDELD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

