CREATE TABLE APPLICATIE (
    APPLICATIE_ID VARCHAR2(255) PRIMARY KEY,
        APPLICATIEURL VARCHAR2(255),
        BEHEERSTATUS NUMBER,
        BELEIDSDOMEIN VARCHAR2(255),
        CATEGORIE VARCHAR2(255),
        GUID VARCHAR2(255),
        HEEFT_HERKOMST_BATCH_ID VARCHAR2(255),
        NAAM VARCHAR2(255),
        OMSCHRIJVING CLOB,
        PACKAGINGSTATUS NUMBER
);

CREATE TABLE BANKAFSCHRIFT (
    BANKAFSCHRIFT_ID VARCHAR2(255) PRIMARY KEY,
        DATUM DATE,
        HEEFT_BANKAFSCHRIFTREGEL_ID VARCHAR2(255),
        NUMMER VARCHAR2(255)
);

CREATE TABLE BANKAFSCHRIFTREGEL (
    BANKAFSCHRIFTREGEL_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG NUMBER(10,2),
        BIJ NUMBER(1),
        DATUM DATE,
        LEIDT_TOT_MUTATIE_ID VARCHAR2(255),
        REKENINGVAN VARCHAR2(255)
);

CREATE TABLE BANKREKENING (
    BANKREKENING_ID VARCHAR2(255) PRIMARY KEY,
        BANK VARCHAR2(80),
        HEEFT_BANKAFSCHRIFT_ID VARCHAR2(255),
        NAAR_BETALING_ID VARCHAR2(255),
        NUMMER VARCHAR2(255),
        TENNAAMSTELLING VARCHAR2(80),
        VAN_BETALING_ID VARCHAR2(255)
);

CREATE TABLE BATCH (
    BATCH_ID VARCHAR2(255) PRIMARY KEY,
        DATUM DATE,
        HEEFT_BATCHREGEL_ID VARCHAR2(255),
        HEEFT_HERKOMST_EXTERNEBRON_ID VARCHAR2(255),
        NUMMER VARCHAR2(255),
        TIJD TIMESTAMP
);

CREATE TABLE BATCHREGEL (
    BATCHREGEL_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG NUMBER(10,2),
        DATUMBETALING DATE,
        LEIDT_TOT_MUTATIE_ID VARCHAR2(255),
        OMSCHRIJVING VARCHAR2(200),
        REKENINGNAAR VARCHAR2(255),
        REKENINGVAN VARCHAR2(255)
);

CREATE TABLE BETALING (
    BETALING_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG NUMBER(10,2),
        DATUMTIJD TIMESTAMP,
        KOMT_VOOR_OP_BANKAFSCHRIFTREGEL_ID VARCHAR2(255),
        OMSCHRIJVING VARCHAR2(200),
        VALUTA VARCHAR2(255)
);

CREATE TABLE EXTERNEBRON (
    EXTERNEBRON_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE FACTUUR (
    FACTUUR_ID VARCHAR2(255) PRIMARY KEY,
        BETAALBAARPER DATE,
        BETAALTERMIJN VARCHAR2(255),
        CODE VARCHAR2(255),
        DATUMFACTUUR DATE,
        FACTUURBEDRAGBTW NUMBER(10,2),
        FACTUURBEDRAGEXCLUSIEFBTW NUMBER(10,2),
        HEEFT_FACTUURREGEL_ID VARCHAR2(255),
        OMSCHRIJVING VARCHAR2(200),
        SCHRIJFT_OP_KOSTENPLAATS_ID VARCHAR2(255)
);

CREATE TABLE FACTUURREGEL (
    FACTUURREGEL_ID VARCHAR2(255) PRIMARY KEY,
        AANTAL VARCHAR2(255),
        BEDRAGBTW NUMBER(10,2),
        BEDRAGEXBTW NUMBER(10,2),
        BTWPERCENTAGE VARCHAR2(255),
        LEIDT_TOT_MUTATIE_ID VARCHAR2(255),
        NUMMER VARCHAR2(255),
        OMSCHRIJVING VARCHAR2(80)
);

CREATE TABLE HOOFDREKENING (
    HOOFDREKENING_ID VARCHAR2(255) PRIMARY KEY,
        HEEFT_SUBREKENING_ID VARCHAR2(255),
        HEEFT_WERKORDER_ID VARCHAR2(255),
        NAAM VARCHAR2(80),
        NUMMER VARCHAR2(255),
        OMSCHRIJVING VARCHAR2(200),
        PIAHOOFCATEGORIEOMSCHRIJVING VARCHAR2(80),
        PIAHOOFDCATEGORIECODE VARCHAR2(20),
        SUBCODE VARCHAR2(20),
        SUBCODEOMSCHRIJVING VARCHAR2(80),
        VALT_BINNEN_HOOFDREKENING_ID VARCHAR2(255)
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID VARCHAR2(255) PRIMARY KEY,
        BTWCODE VARCHAR2(255),
        BTWOMSCHRIJVING VARCHAR2(80),
        HEEFT_SUBREKENING_ID VARCHAR2(255),
        HEEFT_WERKORDER_ID VARCHAR2(255),
        KOSTENPLAATSSOORTCODE NUMBER(10,2),
        KOSTENPLAATSSOORTOMSCHRIJVING NUMBER(10,2),
        KOSTENPLAATSTYPECODE NUMBER(10,2),
        KOSTENPLAATSTYPEOMSCHRIJVING NUMBER(10,2),
        NAAM VARCHAR2(80),
        OMSCHRIJVING VARCHAR2(200)
);

CREATE TABLE KP_HFDRKNNG_KSTNPLTS (
    KP_HFDRKNNG_KSTNPLTS_ID VARCHAR2(255) PRIMARY KEY,
    HOOFDREKENING_ID VARCHAR2(255),
    KOSTENPLAATS_ID VARCHAR2(255)
);

CREATE TABLE MUTATIE (
    MUTATIE_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG NUMBER(10,2),
        DATUM DATE,
        HEEFT_BETREKKING_OP_KOSTENPLAATS_ID VARCHAR2(255),
        NAAR_HOOFDREKENING_ID VARCHAR2(255),
        VAN_HOOFDREKENING_ID VARCHAR2(255)
);

CREATE TABLE SUBREKENING (
    SUBREKENING_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        NUMMER VARCHAR2(20),
        OMSCHRIJVING CLOB
);

CREATE TABLE WERKORDER (
    WERKORDER_ID VARCHAR2(255) PRIMARY KEY,
        CODE VARCHAR2(20),
        DOCUMENTNUMMER NUMBER,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB,
        WERKORDERTYPE VARCHAR2(80)
);

ALTER TABLE KP_HFDRKNNG_KSTNPLTS ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_1 FOREIGN KEY (HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- HOOFDREKENING (many-to-many junction, Connector_ID: 505)

ALTER TABLE KP_HFDRKNNG_KSTNPLTS ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_2 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 505)

ALTER TABLE APPLICATIE ADD CONSTRAINT FK_APPLICATIE_HEEFT_HERKOMST FOREIGN KEY (HEEFT_HERKOMST_BATCH_ID) REFERENCES BATCH (BATCH_ID);
-- HEEFT_HERKOMST (1 to 0..*, Connector_ID: 644)

ALTER TABLE BANKAFSCHRIFT ADD CONSTRAINT FK_BANKAFSCHRIFT_HEEFT FOREIGN KEY (HEEFT_BANKAFSCHRIFTREGEL_ID) REFERENCES BANKAFSCHRIFTREGEL (BANKAFSCHRIFTREGEL_ID);
-- HEEFT (1 to 0..*, Connector_ID: 531)

ALTER TABLE BANKAFSCHRIFTREGEL ADD CONSTRAINT FK_BANKAFSCHRIFTREGEL_LEIDT_TOT FOREIGN KEY (LEIDT_TOT_MUTATIE_ID) REFERENCES MUTATIE (MUTATIE_ID);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 529)

ALTER TABLE BANKREKENING ADD CONSTRAINT FK_BANKREKENING_HEEFT FOREIGN KEY (HEEFT_BANKAFSCHRIFT_ID) REFERENCES BANKAFSCHRIFT (BANKAFSCHRIFT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 530)

ALTER TABLE BANKREKENING ADD CONSTRAINT FK_BANKREKENING_NAAR FOREIGN KEY (NAAR_BETALING_ID) REFERENCES BETALING (BETALING_ID);
-- NAAR (1 to 0..*, Connector_ID: 526)

ALTER TABLE BANKREKENING ADD CONSTRAINT FK_BANKREKENING_VAN FOREIGN KEY (VAN_BETALING_ID) REFERENCES BETALING (BETALING_ID);
-- VAN (1 to 0..*, Connector_ID: 527)

ALTER TABLE BATCH ADD CONSTRAINT FK_BATCH_HEEFT FOREIGN KEY (HEEFT_BATCHREGEL_ID) REFERENCES BATCHREGEL (BATCHREGEL_ID);
-- HEEFT (1 to 0..*, Connector_ID: 524)

ALTER TABLE BATCH ADD CONSTRAINT FK_BATCH_HEEFT_HERKOMST FOREIGN KEY (HEEFT_HERKOMST_EXTERNEBRON_ID) REFERENCES EXTERNEBRON (EXTERNEBRON_ID);
-- HEEFT_HERKOMST (0..* to 1, Connector_ID: 525)

ALTER TABLE BATCHREGEL ADD CONSTRAINT FK_BATCHREGEL_LEIDT_TOT FOREIGN KEY (LEIDT_TOT_MUTATIE_ID) REFERENCES MUTATIE (MUTATIE_ID);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 523)

ALTER TABLE BETALING ADD CONSTRAINT FK_BETALING_KOMT_VOOR_OP FOREIGN KEY (KOMT_VOOR_OP_BANKAFSCHRIFTREGEL_ID) REFERENCES BANKAFSCHRIFTREGEL (BANKAFSCHRIFTREGEL_ID);
-- KOMT_VOOR_OP (0..* to 0..1, Connector_ID: 528)

ALTER TABLE FACTUUR ADD CONSTRAINT FK_FACTUUR_HEEFT FOREIGN KEY (HEEFT_FACTUURREGEL_ID) REFERENCES FACTUURREGEL (FACTUURREGEL_ID);
-- HEEFT (1 to 1..*, Connector_ID: 508)

ALTER TABLE FACTUUR ADD CONSTRAINT FK_FACTUUR_SCHRIJFT_OP FOREIGN KEY (SCHRIJFT_OP_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- SCHRIJFT_OP (0..* to 0..1, Connector_ID: 510)

ALTER TABLE FACTUURREGEL ADD CONSTRAINT FK_FACTUURREGEL_LEIDT_TOT FOREIGN KEY (LEIDT_TOT_MUTATIE_ID) REFERENCES MUTATIE (MUTATIE_ID);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 506)

ALTER TABLE HOOFDREKENING ADD CONSTRAINT FK_HOOFDREKENING_HEEFT FOREIGN KEY (HEEFT_WERKORDER_ID) REFERENCES WERKORDER (WERKORDER_ID);
-- HEEFT (1 to 0..*, Connector_ID: 502)

ALTER TABLE HOOFDREKENING ADD CONSTRAINT FK_HOOFDREKENING_HEEFT_2 FOREIGN KEY (HEEFT_SUBREKENING_ID) REFERENCES SUBREKENING (SUBREKENING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 503)

ALTER TABLE HOOFDREKENING ADD CONSTRAINT FK_HOOFDREKENING_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 504)

ALTER TABLE KOSTENPLAATS ADD CONSTRAINT FK_KOSTENPLAATS_HEEFT FOREIGN KEY (HEEFT_SUBREKENING_ID) REFERENCES SUBREKENING (SUBREKENING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 488)

ALTER TABLE KOSTENPLAATS ADD CONSTRAINT FK_KOSTENPLAATS_HEEFT_2 FOREIGN KEY (HEEFT_WERKORDER_ID) REFERENCES WERKORDER (WERKORDER_ID);
-- HEEFT (1 to 0..*, Connector_ID: 489)

ALTER TABLE MUTATIE ADD CONSTRAINT FK_MUTATIE_HEEFT_BETREKKING_OP FOREIGN KEY (HEEFT_BETREKKING_OP_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT_BETREKKING_OP (0..* to 1, Connector_ID: 483)

ALTER TABLE MUTATIE ADD CONSTRAINT FK_MUTATIE_NAAR FOREIGN KEY (NAAR_HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- NAAR (0..* to 1, Connector_ID: 500)

ALTER TABLE MUTATIE ADD CONSTRAINT FK_MUTATIE_VAN FOREIGN KEY (VAN_HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- VAN (0..* to 1, Connector_ID: 501)

