CREATE TABLE OVERIGEADRESSEERBAAROBJECTAANDUIDING (
    NUMMERAANDUIDING_ID INTEGER PRIMARY KEY,
    IDENTIFICATIECODE VARCHAR(255)
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID INTEGER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER INTEGER,
    EINDEGELDIGHEID DATE,
    GECONSTATEERD BOOLEAN,
    GEOMETRIE GEOMETRY,
    HUISLETTER VARCHAR(255),
    HUISNUMMER VARCHAR(255),
    HUISNUMMERTOEVOEGING VARCHAR(255),
    IDENTIFICATIE VARCHAR(255),
    POSTCODE VARCHAR(255),
    STATUS VARCHAR(255),
    TYPEADRESSEERBAAROBJECT VARCHAR(255),
    VERSIE INTEGER
);

CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID INTEGER PRIMARY KEY,
    HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID INTEGER,
    HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID INTEGER,
    IDENTIFICATIE VARCHAR(255),
    TYPEADRESSEERBAAROBJECT VARCHAR(255),
    VERSIE INTEGER
);

ALTER TABLE OVERIGEADRESSEERBAAROBJECTAANDUIDING ADD CONSTRAINT FK_OVERIGEADRESSEERBAAROBJECTAANDUIDING_GEN_NUMMERAANDUIDING FOREIGN KEY (NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- Generalization to NUMMERAANDUIDING

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

