CREATE TABLE `BEHEEROBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANGEMAAKTDOOR` VARCHAR(200),
    `BEGINGARANTIEPERIODE` VARCHAR(255),
    `BEHEERGEBIED` VARCHAR(255),
    `BEHEEROBJECTBEHEERVAK` VARCHAR(255),
    `BEHEEROBJECTGEBRUIKSFUNCTIE` VARCHAR(255),
    `BEHEEROBJECTMEMO` VARCHAR(255),
    `BESCHERMDEFLORAENFAUNA` BOOLEAN,
    `BUURT` VARCHAR(80),
    `CONVERSIEID` VARCHAR(50),
    `DATUMMUTATIE` DATE,
    `DATUMOPLEVERING` DATE,
    `DATUMPUBLICATIELV` DATE,
    `DATUMVERWIJDERING` DATE,
    `EINDEGARANTIEPERIODE` DATE,
    `GEBIEDSTYPE` VARCHAR(255),
    `GEMEENTE` VARCHAR(80),
    `GEOMETRIE` GEOMETRY,
    `GEWIJZIGDDOOR` VARCHAR(200),
    `GRONDSOORT` VARCHAR(255),
    `GRONDSOORTPLUS` VARCHAR(255),
    `IDENTIFICATIEIMBOR` VARCHAR(255),
    `IDENTIFICATIEIMGEO` VARCHAR(255),
    `JAARVANAANLEG` VARCHAR(255),
    `OBJECTBEGINTIJD` DATETIME,
    `OBJECTEINDTIJD` DATETIME,
    `ONDERHOUDSPLICHTIGE` VARCHAR(255),
    `OPENBARERUIMTE` VARCHAR(80),
    `POSTCODE` VARCHAR(255),
    `RELATIEVEHOOGTELIGGING` VARCHAR(255),
    `STADSDEEL` VARCHAR(80),
    `STATUS` VARCHAR(255),
    `THEORETISCHEINDEJAAR` DATE,
    `TIJDSTIPREGISTRATIE` DATETIME,
    `TYPEBEHEERDER` VARCHAR(255),
    `TYPEBEHEERDERPLUS` VARCHAR(255),
    `TYPEEIGENAAR` VARCHAR(255),
    `TYPEEIGENAARPLUS` VARCHAR(255),
    `TYPELIGGING` VARCHAR(255),
    `WATERSCHAP` VARCHAR(80),
    `WIJK` VARCHAR(80),
    `WOONPLAATS` VARCHAR(80),
    `ZETTINGSGEVOELIGHEID` VARCHAR(255),
    `ZETTINGSGEVOELIGHEIDPLUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `PUT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `BOVENGRONDSZICHTBAAR` BOOLEAN,
    `BREEDTE` VARCHAR(255),
    `DIAMETER` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `MAAIVELDHOOGTE` VARCHAR(255),
    `MATERIAAL` VARCHAR(255),
    `TOEGANKELIJK` BOOLEAN,
    `TYPEAFDEKKING` VARCHAR(255),
    `VORM` VARCHAR(255),
    `WANDDIKTE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `TERREINDEEL` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `BREEDTE` VARCHAR(255),
    `CULTUURHISTORISCHWAARDEVOL` VARCHAR(255),
    `HERPLANTPLICHT` BOOLEAN,
    `OPPERVLAKTE` VARCHAR(255),
    `OPTALUD` BOOLEAN,
    `PERCENTAGELOOFBOS` VARCHAR(255),
    `TERREINDEELSOORTNAAM` DATE,
    `TYPE` VARCHAR(255),
    `TYPEBEWERKING` VARCHAR(255),
    `TYPEPLUS` VARCHAR(255),
    `TYPEPLUS2` VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE `TUNNELOBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `AANTALTUNNELBUIZEN` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `DOORRIJBREEDTE` VARCHAR(255),
    `DOORRIJHOOGTE` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `JAARCONSERVEREN` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `OBJECTNAAM` VARCHAR(255),
    `OBJECTNUMMER` VARCHAR(20),
    `OPPERVLAKTE` VARCHAR(255),
    `TUNNELOBJECTMATERIAAL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KUNSTWERK` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `ANTIGRAFFITIVOORZIENING` BOOLEAN,
    `BEREIKBAARHEID` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `CONSTRUCTIETYPE` VARCHAR(255),
    `GEWICHT` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `INSTALLATEUR` VARCHAR(255),
    `JAARCONSERVEREN` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `JAARRENOVATIE` VARCHAR(255),
    `JAARVERVANGING` VARCHAR(255),
    `KILOMETRERINGBEGIN` VARCHAR(255),
    `KILOMETRERINGEINDE` DATE,
    `KLEUR` VARCHAR(255),
    `KUNSTWERKBEREIKBAARHEIDPLUS` VARCHAR(255),
    `KUNSTWERKMATERIAAL` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `LOOPRICHEL` BOOLEAN,
    `MINIMUMCONDITIESCORE` VARCHAR(255),
    `MONUMENT` BOOLEAN,
    `MONUMENTNUMMER` VARCHAR(20),
    `OBJECTNAAM` VARCHAR(255),
    `OBJECTNUMMER` VARCHAR(20),
    `ONDERHOUDSREGIME` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `ORIENTATIE` VARCHAR(255),
    `TECHNISCHELEVENSDUUR` VARCHAR(255),
    `TYPEFUNDERING` VARCHAR(255),
    `TYPEMONUMENT` VARCHAR(255),
    `VERVANGINGSWAARDE` VARCHAR(255),
    `WEGNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `LEIDING` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AFWIJKENDEDIEPTELEGGING` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `DIAMETER` VARCHAR(255),
    `DIEPTE` VARCHAR(255),
    `EISVOORZORGSMAATREGEL` VARCHAR(200),
    `GEONAUWKEURIGHEIDXY` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `MATERIAAL` VARCHAR(255),
    `THEMAIMKL` VARCHAR(255),
    `VERHOOGDRISICO` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `KAST` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANTALDEUREN` VARCHAR(255),
    `ADRESTELECOM` VARCHAR(255),
    `BAGCODE` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `EANCODE` VARCHAR(50),
    `FABRIKANT` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `INBELGEGEVENS` VARCHAR(50),
    `INSTALLATEUR` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `KLEUR` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `TYPECOMMUNICATIE` VARCHAR(255),
    `TYPEFUNDERING` VARCHAR(255),
    `TYPESLOT` VARCHAR(255),
    `VERMOGEN` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `VERHARDINGSOBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `AANOFVRIJLIGGEND` VARCHAR(255),
    `AANTALDEKLAGEN` VARCHAR(255),
    `AANTALONDERLAGEN` VARCHAR(255),
    `AANTALTUSSENLAGEN` VARCHAR(255),
    `AFMETING` VARCHAR(255),
    `BELASTING` VARCHAR(255),
    `BERGENDVERMOGEN` VARCHAR(255),
    `BGTFYSIEKVOORKOMEN` VARCHAR(80),
    `BREEDTE` VARCHAR(255),
    `DIKTECONSTRUCTIE` VARCHAR(255),
    `DRAAGKRACHTIG` BOOLEAN,
    `FORMAAT` VARCHAR(255),
    `FYSIEKVOORKOMENIMGEO` VARCHAR(80),
    `GELUIDSREDUCEREND` BOOLEAN,
    `JAARCONSERVEREN` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `JAARPRAKTISCHEINDE` DATE,
    `KLEUR` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LENGTEKUNSTGRAS` VARCHAR(255),
    `LENGTEVOEGEN` VARCHAR(255),
    `LEVENSDUUR` VARCHAR(255),
    `MATERIAAL` VARCHAR(255),
    `MAXIMALEVALHOOGTE` VARCHAR(255),
    `OMTREK` VARCHAR(255),
    `ONDERGRONDCODE` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `OPTALUD` BOOLEAN,
    `PLAATSORIENTATIE` VARCHAR(255),
    `PRIJSAANSCHAF` DECIMAL(10,2),
    `RIJSTROOK` VARCHAR(255),
    `SOORTVOEG` VARCHAR(255),
    `TOELICHTINGGEMENGDEBESTRATING` VARCHAR(255),
    `TYPE` VARCHAR(255),
    `TYPECONSTRUCTIE` VARCHAR(255),
    `TYPEFUNDERING` VARCHAR(255),
    `TYPEPLUS` VARCHAR(255),
    `TYPEPLUS2` VARCHAR(100),
    `TYPERIJSTROOK` VARCHAR(255),
    `TYPEVOEG` VARCHAR(255),
    `TYPEVOEGVULLING` VARCHAR(255),
    `VEGEN` VARCHAR(255),
    `VERHARDINGSOBJECTCONSTRUCTIELAAG` VARCHAR(200),
    `VERHARDINGSOBJECTMODALITEIT` VARCHAR(255),
    `VERHARDINGSOBJECTRAND` VARCHAR(255),
    `VERHARDINGSOBJECTWEGFUNCTIE` VARCHAR(255),
    `VERHOOGDELIGGING` BOOLEAN,
    `VULMATERIAALKUNSTGRAS` VARCHAR(255),
    `WATERDOORLATENDHEID` VARCHAR(255),
    `WEGAS` VARCHAR(255),
    `WEGCATEGORIEDV` VARCHAR(255),
    `WEGCATEGORIEDVPLUS` VARCHAR(255),
    `WEGNUMMER` VARCHAR(20),
    `WEGTYPEBESTAAND` VARCHAR(255),
    `WEGVAK` VARCHAR(255),
    `WEGVAKNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `GROENOBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANTALOBSTAKELS` VARCHAR(255),
    `AANTALZIJDEN` VARCHAR(255),
    `AFVOEREN` BOOLEAN,
    `BEREIKBAARHEID` VARCHAR(255),
    `BERGENDVERMOGEN` VARCHAR(255),
    `BEWERKINGSPERCENTAGE` VARCHAR(255),
    `BGTFYSIEKVOORKOMEN` VARCHAR(80),
    `BOLLEN` BOOLEAN,
    `BREEDTE` VARCHAR(255),
    `BREEDTEKLASSEHAAG` VARCHAR(255),
    `BVC` BOOLEAN,
    `CULTUURHISTORISCHWAARDEVOL` VARCHAR(255),
    `DRAAGKRACHTIG` BOOLEAN,
    `ECOLOGISCHBEHEER` BOOLEAN,
    `FYSIEKVOORKOMENIMGEO` VARCHAR(80),
    `GEWENSTSLUITINGSPERCENTAGE` VARCHAR(255),
    `GROENOBJECTBEREIKBAARHEIDPLUS` VARCHAR(255),
    `GROENOBJECTCONSTRUCTIELAAG` VARCHAR(200),
    `GROENOBJECTRAND` VARCHAR(255),
    `GROENOBJECTSOORTNAAM` VARCHAR(255),
    `HAAGVOETLENGTE` VARCHAR(255),
    `HAAGVOETOPPERVLAKTE` VARCHAR(255),
    `HERPLANTPLICHT` BOOLEAN,
    `HOOGTE` VARCHAR(255),
    `HOOGTEKLASSEHAAG` VARCHAR(255),
    `KNIPFREQUENTIE` VARCHAR(255),
    `KNIPOPPERVLAKTE` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `MAAIFREQUENTIE` VARCHAR(255),
    `MAXIMALEVALHOOGTE` VARCHAR(255),
    `OBJECTNUMMER` VARCHAR(20),
    `OBSTAKELS` BOOLEAN,
    `OMTREK` VARCHAR(255),
    `ONDERGROEI` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `OPTALUD` BOOLEAN,
    `TALUDSTEILTE` VARCHAR(255),
    `TYPE` VARCHAR(255),
    `TYPEBEWERKING` VARCHAR(255),
    `TYPEOMGEVINGSRISICOKLASSE` VARCHAR(255),
    `TYPEPLUS` VARCHAR(255),
    `TYPEPLUS2` VARCHAR(100),
    `VEILIGHEIDSKLASSEBOOM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BAK` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `BREEDTE` VARCHAR(255),
    `DIAMETER` VARCHAR(255),
    `GEWICHTLEEG` VARCHAR(255),
    `GEWICHTVOL` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `INHOUD` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `MATERIAAL` VARCHAR(255),
    `VERPLAATSBAAR` BOOLEAN,
    `VORM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `OVERBRUGGINGSOBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `ANTIGRAFFITIVOORZIENING` BOOLEAN,
    `BEREIKBAARHEID` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `INSTALLATEUR` VARCHAR(255),
    `JAARCONSERVEREN` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `JAARRENOVATIE` VARCHAR(255),
    `JAARVERVANGING` VARCHAR(255),
    `KLEUR` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LOOPRICHEL` BOOLEAN,
    `MINIMUMCONDITIESCORE` VARCHAR(255),
    `ONDERHOUDSREGIME` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `OVERBRUGGINGSOBJECTMATERIAAL` VARCHAR(255),
    `OVERBRUGGINGSOBJECTMODALITEIT` VARCHAR(255),
    `TECHNISCHELEVENSDUUR` VARCHAR(255),
    `TYPEFUNDERING` VARCHAR(255),
    `VERVANGINGSWAARDE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BORD` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `BREEDTE` VARCHAR(255),
    `DIAMETER` VARCHAR(255),
    `DRAGER` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `MATERIAAL` VARCHAR(255),
    `VORM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BOUWWERK` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `BOUWWERKMATERIAAL` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `FABRIKANT` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `TYPEFUNDERING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `VERLICHTINGSOBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `VEGETATIEOBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AFVOEREN` BOOLEAN,
    `BEREIKBAARHEID` VARCHAR(255),
    `ECOLOGISCHBEHEER` BOOLEAN,
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `KWEKER` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `OBJECTNUMMER` VARCHAR(20),
    `SOORTNAAM` VARCHAR(255),
    `TYPESTANDPLAATS` VARCHAR(255),
    `TYPESTANDPLAATSPLUS` VARCHAR(255),
    `VEGETATIEOBJECTBEREIKBAARHEIDPLUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `WATERINRICHTINGSOBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `JAARCONSERVEREN` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `MATERIAAL` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `GEO_OBJECT` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `GEOMETRIESOORT` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `VERWIJST_NAAR_BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `FUNCTIONEELGEBIED` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `FUNCTIONEELGEBIEDCODE` VARCHAR(20),
    `FUNCTIONEELGEBIEDNAAM` VARCHAR(80),
    `OMTREK` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `LEIDINGELEMENT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AFWIJKENDEDIEPTELEGGING` VARCHAR(255),
    `DIEPTE` VARCHAR(255),
    `GEONAUWKEURIGHEIDXY` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `THEMAIMKL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `MEUBILAIR` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `BOUWJAAR` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `DATUMAANSCHAF` DATE,
    `DIAMETER` VARCHAR(255),
    `FABRIKANT` VARCHAR(255),
    `GEWICHT` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `INSTALLATEUR` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `JAARPRAKTISCHEINDE` DATE,
    `KLEUR` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `MEUBILAIRMATERIAAL` VARCHAR(255),
    `MODEL` VARCHAR(50),
    `ONDERGROND` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `PRIJSAANSCHAF` DECIMAL(10,2),
    `SERIENUMMER` VARCHAR(50),
    `TRANSPONDER` VARCHAR(50),
    `TRANSPONDERLOCATIE` VARCHAR(50),
    `TYPEFUNDERING` VARCHAR(255),
    `TYPEPLAAT` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `WATEROBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `BREEDTE` VARCHAR(255),
    `FOLIE` BOOLEAN,
    `HOOGTE` VARCHAR(255),
    `INFILTRERENDOPPERVLAK` VARCHAR(255),
    `INFILTRERENDVERMOGEN` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LOZINGSPUNT` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `POROSITEIT` VARCHAR(255),
    `STREEFDIEPTE` VARCHAR(255),
    `TYPE` VARCHAR(255),
    `TYPEPLUS` VARCHAR(255),
    `TYPEPLUS2` VARCHAR(100),
    `TYPEVAARWATER` VARCHAR(255),
    `TYPEWATERPLANT` VARCHAR(255),
    `UITSTROOMNIVEAU` VARCHAR(255),
    `VAARWEGTRAJECT` VARCHAR(50),
    `VORM` VARCHAR(255),
    `WATERNAAM` VARCHAR(100),
    `WATERPEIL` VARCHAR(255),
    `WATERPEILWINTER` VARCHAR(255),
    `WATERPEILZOMER` VARCHAR(255),
    `WATERPLANTEN` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `MAST` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `PAAL` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `BREEDTE` VARCHAR(255),
    `DIAMETER` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `MATERIAAL` VARCHAR(255),
    `VORM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `INSTALLATIE` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `BREEDTE` VARCHAR(255),
    `EANCODE` VARCHAR(50),
    `FABRIKANT` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `INBELGEGEVENS` VARCHAR(50),
    `INSTALLATEUR` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `TYPECOMMUNICATIE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `WEGINRICHTINGSOBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `JAARCONSERVEREN` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `KWALITEITSNIVEAUACTUEEL` VARCHAR(255),
    `KWALITEITSNIVEAUGEWENST` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `MATERIAAL` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `WEGINRICHTINGSOBJECTWEGFUNCTIE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `SCHEIDING` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANLEGHOOGTE` VARCHAR(255),
    `BREEDTE` VARCHAR(255),
    `HOOGTE` VARCHAR(255),
    `JAARONDERHOUDUITGEVOERD` VARCHAR(255),
    `LENGTE` VARCHAR(255),
    `LEVERANCIER` VARCHAR(255),
    `OBJECTNAAM` VARCHAR(255),
    `OBJECTNUMMER` VARCHAR(20),
    `OPPERVLAKTE` VARCHAR(255),
    `SCHEIDINGMATERIAAL` VARCHAR(255),
    `VERPLAATSBAAR` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `KP_PUT_BHRBJCT` (
    `KP_PUT_BHRBJCT_ID` INT PRIMARY KEY,
    `PUT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_TRRNDL_BHRBJCT` (
    `KP_TRRNDL_BHRBJCT_ID` INT PRIMARY KEY,
    `TERREINDEEL_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_TNNLBJCT_BHRBJCT` (
    `KP_TNNLBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `TUNNELOBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_KNSTWRK_BHRBJCT` (
    `KP_KNSTWRK_BHRBJCT_ID` INT PRIMARY KEY,
    `KUNSTWERK_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_LDNG_BHRBJCT` (
    `KP_LDNG_BHRBJCT_ID` INT PRIMARY KEY,
    `LEIDING_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_KST_BHRBJCT` (
    `KP_KST_BHRBJCT_ID` INT PRIMARY KEY,
    `KAST_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRHRDNGSBJCT_BHRBJCT` (
    `KP_VRHRDNGSBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `VERHARDINGSOBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_GRNBJCT_BHRBJCT` (
    `KP_GRNBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `GROENOBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BAK_BHRBJCT` (
    `KP_BAK_BHRBJCT_ID` INT PRIMARY KEY,
    `BAK_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_OVRBRGGNGSBJCT_BHRBJCT` (
    `KP_OVRBRGGNGSBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `OVERBRUGGINGSOBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BRD_BHRBJCT` (
    `KP_BRD_BHRBJCT_ID` INT PRIMARY KEY,
    `BORD_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BWWRK_BHRBJCT` (
    `KP_BWWRK_BHRBJCT_ID` INT PRIMARY KEY,
    `BOUWWERK_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRLCHTNGSBJCT_BHRBJCT` (
    `KP_VRLCHTNGSBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `VERLICHTINGSOBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VGTTBJCT_BHRBJCT` (
    `KP_VGTTBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `VEGETATIEOBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_WTRNRCHTNGSBJCT_BHRBJCT` (
    `KP_WTRNRCHTNGSBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `WATERINRICHTINGSOBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_FNCTNLGBD_BHRBJCT` (
    `KP_FNCTNLGBD_BHRBJCT_ID` INT PRIMARY KEY,
    `FUNCTIONEELGEBIED_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_LDNGLMNT_BHRBJCT` (
    `KP_LDNGLMNT_BHRBJCT_ID` INT PRIMARY KEY,
    `LEIDINGELEMENT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_MBLR_BHRBJCT` (
    `KP_MBLR_BHRBJCT_ID` INT PRIMARY KEY,
    `MEUBILAIR_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_WTRBJCT_BHRBJCT` (
    `KP_WTRBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `WATEROBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_MST_BHRBJCT` (
    `KP_MST_BHRBJCT_ID` INT PRIMARY KEY,
    `MAST_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_PL_BHRBJCT` (
    `KP_PL_BHRBJCT_ID` INT PRIMARY KEY,
    `PAAL_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_INSTLLT_BHRBJCT` (
    `KP_INSTLLT_BHRBJCT_ID` INT PRIMARY KEY,
    `INSTALLATIE_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_WGNRCHTNGSBJCT_BHRBJCT` (
    `KP_WGNRCHTNGSBJCT_BHRBJCT_ID` INT PRIMARY KEY,
    `WEGINRICHTINGSOBJECT_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_SCHDNG_BHRBJCT` (
    `KP_SCHDNG_BHRBJCT_ID` INT PRIMARY KEY,
    `SCHEIDING_ID` INT,
    `BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `BAK` ADD CONSTRAINT FK_BAK_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `BORD` ADD CONSTRAINT FK_BORD_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `BOUWWERK` ADD CONSTRAINT FK_BOUWWERK_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `FUNCTIONEELGEBIED` ADD CONSTRAINT FK_FUNCTIONEELGEBIED_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `GROENOBJECT` ADD CONSTRAINT FK_GROENOBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `INSTALLATIE` ADD CONSTRAINT FK_INSTALLATIE_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `KAST` ADD CONSTRAINT FK_KAST_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `KUNSTWERK` ADD CONSTRAINT FK_KUNSTWERK_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `LEIDING` ADD CONSTRAINT FK_LEIDING_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `LEIDINGELEMENT` ADD CONSTRAINT FK_LEIDINGELEMENT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `MAST` ADD CONSTRAINT FK_MAST_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `MEUBILAIR` ADD CONSTRAINT FK_MEUBILAIR_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `OVERBRUGGINGSOBJECT` ADD CONSTRAINT FK_OVERBRUGGINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `PAAL` ADD CONSTRAINT FK_PAAL_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `PUT` ADD CONSTRAINT FK_PUT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `SCHEIDING` ADD CONSTRAINT FK_SCHEIDING_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `TERREINDEEL` ADD CONSTRAINT FK_TERREINDEEL_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `TUNNELOBJECT` ADD CONSTRAINT FK_TUNNELOBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `VEGETATIEOBJECT` ADD CONSTRAINT FK_VEGETATIEOBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `VERHARDINGSOBJECT` ADD CONSTRAINT FK_VERHARDINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `VERLICHTINGSOBJECT` ADD CONSTRAINT FK_VERLICHTINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `WATERINRICHTINGSOBJECT` ADD CONSTRAINT FK_WATERINRICHTINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `WATEROBJECT` ADD CONSTRAINT FK_WATEROBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `WEGINRICHTINGSOBJECT` ADD CONSTRAINT FK_WEGINRICHTINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- Generalization to BEHEEROBJECT

ALTER TABLE `KP_WGNRCHTNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_WGNRCHTNGSBJCT_BHRBJCT_1 FOREIGN KEY (`WEGINRICHTINGSOBJECT_ID`) REFERENCES `WEGINRICHTINGSOBJECT` (`BEHEEROBJECT_ID`);
-- WEGINRICHTINGSOBJECT (many-to-many junction, Connector_ID: 752)

ALTER TABLE `KP_WGNRCHTNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_WGNRCHTNGSBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 752)

ALTER TABLE `KP_WTRBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_WTRBJCT_BHRBJCT_1 FOREIGN KEY (`WATEROBJECT_ID`) REFERENCES `WATEROBJECT` (`BEHEEROBJECT_ID`);
-- WATEROBJECT (many-to-many junction, Connector_ID: 753)

ALTER TABLE `KP_WTRBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_WTRBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 753)

ALTER TABLE `KP_WTRNRCHTNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_WTRNRCHTNGSBJCT_BHRBJCT_1 FOREIGN KEY (`WATERINRICHTINGSOBJECT_ID`) REFERENCES `WATERINRICHTINGSOBJECT` (`BEHEEROBJECT_ID`);
-- WATERINRICHTINGSOBJECT (many-to-many junction, Connector_ID: 754)

ALTER TABLE `KP_WTRNRCHTNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_WTRNRCHTNGSBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 754)

ALTER TABLE `KP_VRLCHTNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_VRLCHTNGSBJCT_BHRBJCT_1 FOREIGN KEY (`VERLICHTINGSOBJECT_ID`) REFERENCES `VERLICHTINGSOBJECT` (`BEHEEROBJECT_ID`);
-- VERLICHTINGSOBJECT (many-to-many junction, Connector_ID: 756)

ALTER TABLE `KP_VRLCHTNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_VRLCHTNGSBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 756)

ALTER TABLE `KP_VRHRDNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_VRHRDNGSBJCT_BHRBJCT_1 FOREIGN KEY (`VERHARDINGSOBJECT_ID`) REFERENCES `VERHARDINGSOBJECT` (`BEHEEROBJECT_ID`);
-- VERHARDINGSOBJECT (many-to-many junction, Connector_ID: 758)

ALTER TABLE `KP_VRHRDNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_VRHRDNGSBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 758)

ALTER TABLE `KP_VGTTBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_VGTTBJCT_BHRBJCT_1 FOREIGN KEY (`VEGETATIEOBJECT_ID`) REFERENCES `VEGETATIEOBJECT` (`BEHEEROBJECT_ID`);
-- VEGETATIEOBJECT (many-to-many junction, Connector_ID: 759)

ALTER TABLE `KP_VGTTBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_VGTTBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 759)

ALTER TABLE `KP_TNNLBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_TNNLBJCT_BHRBJCT_1 FOREIGN KEY (`TUNNELOBJECT_ID`) REFERENCES `TUNNELOBJECT` (`BEHEEROBJECT_ID`);
-- TUNNELOBJECT (many-to-many junction, Connector_ID: 761)

ALTER TABLE `KP_TNNLBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_TNNLBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 761)

ALTER TABLE `KP_TRRNDL_BHRBJCT` ADD CONSTRAINT FK_KP_TRRNDL_BHRBJCT_1 FOREIGN KEY (`TERREINDEEL_ID`) REFERENCES `TERREINDEEL` (`BEHEEROBJECT_ID`);
-- TERREINDEEL (many-to-many junction, Connector_ID: 762)

ALTER TABLE `KP_TRRNDL_BHRBJCT` ADD CONSTRAINT FK_KP_TRRNDL_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 762)

ALTER TABLE `KP_SCHDNG_BHRBJCT` ADD CONSTRAINT FK_KP_SCHDNG_BHRBJCT_1 FOREIGN KEY (`SCHEIDING_ID`) REFERENCES `SCHEIDING` (`BEHEEROBJECT_ID`);
-- SCHEIDING (many-to-many junction, Connector_ID: 769)

ALTER TABLE `KP_SCHDNG_BHRBJCT` ADD CONSTRAINT FK_KP_SCHDNG_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 769)

ALTER TABLE `KP_PUT_BHRBJCT` ADD CONSTRAINT FK_KP_PUT_BHRBJCT_1 FOREIGN KEY (`PUT_ID`) REFERENCES `PUT` (`BEHEEROBJECT_ID`);
-- PUT (many-to-many junction, Connector_ID: 773)

ALTER TABLE `KP_PUT_BHRBJCT` ADD CONSTRAINT FK_KP_PUT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 773)

ALTER TABLE `KP_PL_BHRBJCT` ADD CONSTRAINT FK_KP_PL_BHRBJCT_1 FOREIGN KEY (`PAAL_ID`) REFERENCES `PAAL` (`BEHEEROBJECT_ID`);
-- PAAL (many-to-many junction, Connector_ID: 775)

ALTER TABLE `KP_PL_BHRBJCT` ADD CONSTRAINT FK_KP_PL_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 775)

ALTER TABLE `KP_OVRBRGGNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_OVRBRGGNGSBJCT_BHRBJCT_1 FOREIGN KEY (`OVERBRUGGINGSOBJECT_ID`) REFERENCES `OVERBRUGGINGSOBJECT` (`BEHEEROBJECT_ID`);
-- OVERBRUGGINGSOBJECT (many-to-many junction, Connector_ID: 777)

ALTER TABLE `KP_OVRBRGGNGSBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_OVRBRGGNGSBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 777)

ALTER TABLE `KP_MBLR_BHRBJCT` ADD CONSTRAINT FK_KP_MBLR_BHRBJCT_1 FOREIGN KEY (`MEUBILAIR_ID`) REFERENCES `MEUBILAIR` (`BEHEEROBJECT_ID`);
-- MEUBILAIR (many-to-many junction, Connector_ID: 778)

ALTER TABLE `KP_MBLR_BHRBJCT` ADD CONSTRAINT FK_KP_MBLR_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 778)

ALTER TABLE `KP_MST_BHRBJCT` ADD CONSTRAINT FK_KP_MST_BHRBJCT_1 FOREIGN KEY (`MAST_ID`) REFERENCES `MAST` (`BEHEEROBJECT_ID`);
-- MAST (many-to-many junction, Connector_ID: 779)

ALTER TABLE `KP_MST_BHRBJCT` ADD CONSTRAINT FK_KP_MST_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 779)

ALTER TABLE `KP_LDNGLMNT_BHRBJCT` ADD CONSTRAINT FK_KP_LDNGLMNT_BHRBJCT_1 FOREIGN KEY (`LEIDINGELEMENT_ID`) REFERENCES `LEIDINGELEMENT` (`BEHEEROBJECT_ID`);
-- LEIDINGELEMENT (many-to-many junction, Connector_ID: 780)

ALTER TABLE `KP_LDNGLMNT_BHRBJCT` ADD CONSTRAINT FK_KP_LDNGLMNT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 780)

ALTER TABLE `KP_LDNG_BHRBJCT` ADD CONSTRAINT FK_KP_LDNG_BHRBJCT_1 FOREIGN KEY (`LEIDING_ID`) REFERENCES `LEIDING` (`BEHEEROBJECT_ID`);
-- LEIDING (many-to-many junction, Connector_ID: 781)

ALTER TABLE `KP_LDNG_BHRBJCT` ADD CONSTRAINT FK_KP_LDNG_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 781)

ALTER TABLE `KP_KNSTWRK_BHRBJCT` ADD CONSTRAINT FK_KP_KNSTWRK_BHRBJCT_1 FOREIGN KEY (`KUNSTWERK_ID`) REFERENCES `KUNSTWERK` (`BEHEEROBJECT_ID`);
-- KUNSTWERK (many-to-many junction, Connector_ID: 782)

ALTER TABLE `KP_KNSTWRK_BHRBJCT` ADD CONSTRAINT FK_KP_KNSTWRK_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 782)

ALTER TABLE `KP_KST_BHRBJCT` ADD CONSTRAINT FK_KP_KST_BHRBJCT_1 FOREIGN KEY (`KAST_ID`) REFERENCES `KAST` (`BEHEEROBJECT_ID`);
-- KAST (many-to-many junction, Connector_ID: 786)

ALTER TABLE `KP_KST_BHRBJCT` ADD CONSTRAINT FK_KP_KST_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 786)

ALTER TABLE `KP_INSTLLT_BHRBJCT` ADD CONSTRAINT FK_KP_INSTLLT_BHRBJCT_1 FOREIGN KEY (`INSTALLATIE_ID`) REFERENCES `INSTALLATIE` (`BEHEEROBJECT_ID`);
-- INSTALLATIE (many-to-many junction, Connector_ID: 788)

ALTER TABLE `KP_INSTLLT_BHRBJCT` ADD CONSTRAINT FK_KP_INSTLLT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 788)

ALTER TABLE `KP_GRNBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_GRNBJCT_BHRBJCT_1 FOREIGN KEY (`GROENOBJECT_ID`) REFERENCES `GROENOBJECT` (`BEHEEROBJECT_ID`);
-- GROENOBJECT (many-to-many junction, Connector_ID: 790)

ALTER TABLE `KP_GRNBJCT_BHRBJCT` ADD CONSTRAINT FK_KP_GRNBJCT_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 790)

ALTER TABLE `KP_FNCTNLGBD_BHRBJCT` ADD CONSTRAINT FK_KP_FNCTNLGBD_BHRBJCT_1 FOREIGN KEY (`FUNCTIONEELGEBIED_ID`) REFERENCES `FUNCTIONEELGEBIED` (`BEHEEROBJECT_ID`);
-- FUNCTIONEELGEBIED (many-to-many junction, Connector_ID: 793)

ALTER TABLE `KP_FNCTNLGBD_BHRBJCT` ADD CONSTRAINT FK_KP_FNCTNLGBD_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 793)

ALTER TABLE `KP_BWWRK_BHRBJCT` ADD CONSTRAINT FK_KP_BWWRK_BHRBJCT_1 FOREIGN KEY (`BOUWWERK_ID`) REFERENCES `BOUWWERK` (`BEHEEROBJECT_ID`);
-- BOUWWERK (many-to-many junction, Connector_ID: 800)

ALTER TABLE `KP_BWWRK_BHRBJCT` ADD CONSTRAINT FK_KP_BWWRK_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 800)

ALTER TABLE `KP_BRD_BHRBJCT` ADD CONSTRAINT FK_KP_BRD_BHRBJCT_1 FOREIGN KEY (`BORD_ID`) REFERENCES `BORD` (`BEHEEROBJECT_ID`);
-- BORD (many-to-many junction, Connector_ID: 801)

ALTER TABLE `KP_BRD_BHRBJCT` ADD CONSTRAINT FK_KP_BRD_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 801)

ALTER TABLE `KP_BAK_BHRBJCT` ADD CONSTRAINT FK_KP_BAK_BHRBJCT_1 FOREIGN KEY (`BAK_ID`) REFERENCES `BAK` (`BEHEEROBJECT_ID`);
-- BAK (many-to-many junction, Connector_ID: 809)

ALTER TABLE `KP_BAK_BHRBJCT` ADD CONSTRAINT FK_KP_BAK_BHRBJCT_2 FOREIGN KEY (`BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- BEHEEROBJECT (many-to-many junction, Connector_ID: 809)

ALTER TABLE `GEO_OBJECT` ADD CONSTRAINT FK_GEO_OBJECT_VERWIJST_NAAR FOREIGN KEY (`VERWIJST_NAAR_BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- VERWIJST_NAAR (1 to 0..1, Connector_ID: 805)

