CREATE TABLE `BEHEEROBJECT` (
    `BEHEEROBJECT_ID` INT PRIMARY KEY,
    `AANGEMAAKTDOOR` VARCHAR(200),
    `BEGINGARANTIEPERIODE` VARCHAR(255),
    `BEHEERGEBIED` VARCHAR(255),
    `BEHEEROBJECTBEHEERVAK` VARCHAR(255),
    `BEHEEROBJECTGEBRUIKSFUNCTIE` VARCHAR(255),
    `BEHEEROBJECTMEMO` VARCHAR(255),
    `BESCHERMDEFLORAENFAUNA` BOOLEAN,
    `BUURT` VARCHAR(80),
    `CONVERSIEID` VARCHAR(50),
    `DATUMMUTATIE` DATE,
    `DATUMOPLEVERING` DATE,
    `DATUMPUBLICATIELV` DATE,
    `DATUMVERWIJDERING` DATE,
    `EINDEGARANTIEPERIODE` DATE,
    `GEBIEDSTYPE` VARCHAR(255),
    `GEMEENTE` VARCHAR(80),
    `GEOMETRIE` GEOMETRY,
    `GEWIJZIGDDOOR` VARCHAR(200),
    `GRONDSOORT` VARCHAR(255),
    `GRONDSOORTPLUS` VARCHAR(255),
    `IDENTIFICATIEIMBOR` VARCHAR(255),
    `IDENTIFICATIEIMGEO` VARCHAR(255),
    `JAARVANAANLEG` VARCHAR(255),
    `OBJECTBEGINTIJD` DATETIME,
    `OBJECTEINDTIJD` DATETIME,
    `ONDERHOUDSPLICHTIGE` VARCHAR(255),
    `OPENBARERUIMTE` VARCHAR(80),
    `POSTCODE` VARCHAR(255),
    `RELATIEVEHOOGTELIGGING` VARCHAR(255),
    `STADSDEEL` VARCHAR(80),
    `STATUS` VARCHAR(255),
    `THEORETISCHEINDEJAAR` DATE,
    `TIJDSTIPREGISTRATIE` DATETIME,
    `TYPEBEHEERDER` VARCHAR(255),
    `TYPEBEHEERDERPLUS` VARCHAR(255),
    `TYPEEIGENAAR` VARCHAR(255),
    `TYPEEIGENAARPLUS` VARCHAR(255),
    `TYPELIGGING` VARCHAR(255),
    `WATERSCHAP` VARCHAR(80),
    `WIJK` VARCHAR(80),
    `WOONPLAATS` VARCHAR(80),
    `ZETTINGSGEVOELIGHEID` VARCHAR(255),
    `ZETTINGSGEVOELIGHEIDPLUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `GEO_OBJECT` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `GEOMETRIESOORT` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `VERWIJST_NAAR_BEHEEROBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `OVERIGBOUWWERK` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDOVERIGBOUWWERK` DATE,
    `DATUMEINDEGELDIGHEIDOVERIGBOUWWERK` DATE,
    `GEOMETRIEOVERIGBOUWWERK` GEOMETRY,
    `IDENTIFICATIEOVERIGBOUWWERK` VARCHAR(255),
    `LOD0GEOMETRIEOVERIGBOUWWERK` GEOMETRY,
    `LOD1GEOMETRIEOVERIGBOUWWERK` GEOMETRY,
    `LOD2GEOMETRIEOVERIGBOUWWERK` GEOMETRY,
    `LOD3GEOMETRIEOVERIGBOUWWERK` GEOMETRY,
    `RELATIEVEHOOGTELIGGINGOVERIGBOUWWERK` VARCHAR(255),
    `STATUSOVERIGBOUWWERK` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `OVERBRUGGINGSDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDOVERBRUGGINGSDEEL` DATE,
    `DATUMEINDEGELDIGHEIDOVERBRUGGINGSDEEL` DATE,
    `GEOMETRIEOVERBRUGGINGSDEEL` GEOMETRY,
    `HOORTBIJTYPEOVERBRUGGING` VARCHAR(255),
    `IDENTIFICATIEOVERBRUGGINGSDEEL` VARCHAR(255),
    `LOD0GEOMETRIEOVERBRUGGINGSDEEL` GEOMETRY,
    `OVERBRUGGINGISBEWEEGBAAR` BOOLEAN,
    `RELATIEVEHOOGTELIGGINGOVERBRUGGINGSDEEL` VARCHAR(255),
    `STATUSOVERBRUGGINGSDEEL` VARCHAR(255),
    `TYPEOVERBRUGGINGSDEEL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `PAND` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` DATE,
    `BRUTOINHOUDPAND` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` VARCHAR(255),
    `EINDGELDIGHEID` DATE,
    `GECONSTATEERD` BOOLEAN,
    `GEOMETRIEBOVENAANZICHT` GEOMETRY,
    `GEOMETRIEMAAIVELD` GEOMETRY,
    `GEOMETRIEPUNT` GEOMETRY,
    `HOOGSTEBOUWLAAG` VARCHAR(255),
    `IDENTIFICATIE` VARCHAR(255),
    `LAAGSTEBOUWLAAG` VARCHAR(255),
    `OORSPRONKELIJKBOUWJAAR` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `RELATIEVEHOOGTELIGGING` VARCHAR(255),
    `STATUS` VARCHAR(255),
    `STATUSVOORTGANGBOUW` VARCHAR(255),
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `FUNCTIONEELGEBIED` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDFUNCTIONEELGEBIED` DATE,
    `DATUMEINDEGELDIGHEIDFUNCTIONEELGEBIED` DATE,
    `GEOMETRIEFUNCTIONEELGEBIED` GEOMETRY,
    `IDENTIFICATIEFUNCTIONEELGEBIED` VARCHAR(255),
    `NAAMFUNCTIONEELGEBIED` VARCHAR(255),
    `STATUSFUNCTIONEELGEBIED` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KUNSTWERKDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDKUNSTWERKDEEL` DATE,
    `DATUMEINDEGELDIGHEIDKUNSTWERKDEEL` DATE,
    `GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
    `IDENTIFICATIEKUNSTWERKDEEL` VARCHAR(255),
    `LOD0GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
    `LOD1GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
    `LOD2GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
    `LOD3GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
    `RELATIEVEHOOGTELIGGINGKUNSTWERKDEEL` VARCHAR(255),
    `STATUSKUNSTWERKDEEL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `GEBOUWINSTALLATIE` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDGEBOUWINSTALLATIE` DATE,
    `DATUMEINDEGELDIGHEIDGEBOUWINSTALLATIE` DATE,
    `GEOMETRIEGEBOUWINSTALLATIE` GEOMETRY,
    `IDENTIFICATIEGEBOUWINSTALLATIE` VARCHAR(255),
    `LOD0GEOMETRIEGEBOUWINSTALLATIE` GEOMETRY,
    `RELATIEVEHOOGTELIGGINGGEBOUWINSTALLATIE` VARCHAR(255),
    `STATUSGEBOUWINSTALLATIE` VARCHAR(255),
    `TYPEGEBOUWINSTALLATIE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `ONDERSTEUNENDWATERDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `PLUSTYPE` VARCHAR(255),
    `RELATIEVEHOOGTELIGGING` VARCHAR(255),
    `STATUS` VARCHAR(255),
    `TYPE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `ONDERSTEUNENDWEGDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `FUNCTIE` VARCHAR(255),
    `FYSIEKVOORKOMEN` VARCHAR(255),
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `KRUINLIJNGEOMETRIE` GEOMETRY,
    `LOD0GEOMETRIE` GEOMETRY,
    `OPTALUD` BOOLEAN,
    `PLUSFUNCTIE` VARCHAR(255),
    `PLUSFYSIEKVOORKOMEN` VARCHAR(255),
    `RELATIEVEHOOGTELIGGING` VARCHAR(255),
    `STATUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `OVERIGBENOEMDTERREIN` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `GEBRUIKSDOELOVERIGBENOEMDTERREIN` VARCHAR(255),
    `OVERIGBENOEMDTERREINIDENTIFICATIE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `WATERDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDWATERDEEL` DATE,
    `DATUMEINDEGELDIGHEIDWATERDEEL` DATE,
    `GEOMETRIEWATERDEEL` GEOMETRY,
    `IDENTIFICATIEWATERDEEL` VARCHAR(255),
    `PLUSTYPEWATERDEEL` VARCHAR(255),
    `RELATIEVEHOOGTELIGGINGWATERDEEL` VARCHAR(255),
    `STATUSWATERDEEL` VARCHAR(255),
    `TYPEWATERDEEL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BEGROEIDTERREINDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `FYSIEKVOORKOMEN` VARCHAR(255),
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `KRUINLIJNGEOMETRIE` GEOMETRY,
    `LOD0GEOMETRIE` GEOMETRY,
    `OPTALUD` BOOLEAN,
    `PLUSFYSIEKVOORKOMEN` VARCHAR(255),
    `RELATIEVEHOOGTELIGGING` VARCHAR(255),
    `STATUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `OVERIGESCHEIDING` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDOVERIGESCHEIDING` DATE,
    `DATUMEINDEGELDIGHEIDOVERIGESCHEIDING` DATE,
    `GEOMETRIEOVERIGESCHEIDING` GEOMETRY,
    `IDENTIFICATIEOVERIGESCHEIDING` VARCHAR(255),
    `LOD0GEOMETRIEOVERIGESCHEIDING` GEOMETRY,
    `LOD1GEOMETRIEOVERIGESCHEIDING` GEOMETRY,
    `LOD2GEOMETRIEOVERIGESCHEIDING` GEOMETRY,
    `LOD3GEOMETRIEOVERIGESCHEIDING` GEOMETRY,
    `RELATIEVEHOOGTELIGGINGOVERIGESCHEIDING` VARCHAR(255),
    `STATUSOVERIGESCHEIDING` VARCHAR(255),
    `TYPEOVERIGESCHEIDING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `VEGETATIEOBJECT` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDVEGETATIEOBJECT` DATE,
    `DATUMEINDEGELDIGHEIDVEGETATIEOBJECT` DATE,
    `GEOMETRIEVEGETATIEOBJECT` GEOMETRY,
    `IDENTIFICATIEVEGETATIEOBJECT` VARCHAR(255),
    `LOD0GEOMETRIEVEGETATIEOBJECT` GEOMETRY,
    `RELATIEVEHOOGTELIGGINGVEGETATIEOBJECT` VARCHAR(255),
    `STATUSVEGETATIEOBJECT` VARCHAR(255),
    `TYPEVEGETATIEOBJECT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `SPOOR` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDSPOOR` DATE,
    `DATUMEINDEGELDIGHEIDSPOOR` DATE,
    `GEOMETRIESPOOR` GEOMETRY,
    `IDENTIFICATIESPOOR` VARCHAR(255),
    `LOD0GEOMETRIESPOOR` GEOMETRY,
    `RELATIEVEHOOGTELIGGINGSPOOR` VARCHAR(255),
    `STATUSSPOOR` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `SCHEIDING` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDSCHEIDING` DATE,
    `DATUMEINDEGELDIGHEIDSCHEIDING` DATE,
    `GEOMETRIESCHEIDING` GEOMETRY,
    `IDENTIFICATIESCHEIDING` VARCHAR(255),
    `LOD0GEOMETRIESCHEIDING` GEOMETRY,
    `LOD1GEOMETRIESCHEIDING` GEOMETRY,
    `LOD2GEOMETRIESCHEIDING` GEOMETRY,
    `LOD3GEOMETRIESCHEIDING` GEOMETRY,
    `RELATIEVEHOOGTELIGGINGSCHEIDING` VARCHAR(255),
    `STATUSSCHEIDING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `INRICHTINGSELEMENT` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDINRICHTINGSELEMENT` DATE,
    `DATUMEINDEGELDIGHEIDINRICHTINGSELEMENT` DATE,
    `GEOMETRIEINRICHTINGSELEMENT` GEOMETRY,
    `IDENTIFICATIEINRICHTINGSELEMENT` VARCHAR(255),
    `LOD0GEOMETRIEINRICHTINGSELEMENT` GEOMETRY,
    `PLUSTYPEINRICHTINGSELEMENT` VARCHAR(255),
    `RELATIEVEHOOGTELIGGINGINRICHTINGSELEMENT` VARCHAR(255),
    `STATUSINRICHTINGSELEMENT` VARCHAR(255),
    `TYPEINRICHTINGSELEMENT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `WEGDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDWEGDEEL` DATE,
    `DATUMEINDEGELDIGHEIDWEGDEEL` DATE,
    `FUNCTIEWEGDEEL` VARCHAR(255),
    `FYSIEKVOORKOMENWEGDEEL` VARCHAR(255),
    `GEOMETRIEWEGDEEL` GEOMETRY,
    `IDENTIFICATIEWEGDEEL` VARCHAR(255),
    `KRUINLIJNGEOMETRIEWEGDEEL` GEOMETRY,
    `LOD0GEOMETRIEWEGDEEL` GEOMETRY,
    `PLUSFUNCTIEWEGDEEL` VARCHAR(255),
    `PLUSFYSIEKVOORKOMENWEGDEEL` VARCHAR(255),
    `RELATIEVEHOOGTELIGGINGWEGDEEL` VARCHAR(255),
    `STATUSWEGDEEL` VARCHAR(255),
    `WEGDEELOPTALUD` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `ONBEGROEIDTERREINDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `FYSIEKVOORKOMEN` VARCHAR(255),
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `KRUINLIJNGEOMETRIE` GEOMETRY,
    `ONBEGROEIDTERREINDEELOPTALUD` DATE,
    `PLUSFYSIEKVOORKOMEN` VARCHAR(255),
    `RELATIEVEHOOGTELIGGING` VARCHAR(255),
    `STATUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `TUNNELDEEL` (
    `GEO_OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDTUNNELDEEL` DATE,
    `DATUMEINDEGELDIGHEIDTUNNELDEEL` DATE,
    `GEOMETRIETUNNELDEEL` GEOMETRY,
    `IDENTIFICATIETUNNELDEEL` VARCHAR(255),
    `LOD0GEOMETRIETUNNELDEEL` GEOMETRY,
    `RELATIEVEHOOGTELIGGINGTUNNELDEEL` VARCHAR(255),
    `STATUSTUNNELDEEL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_OVRGBWWRK_GEO_OBJCT` (
    `KP_OVRGBWWRK_GEO_OBJCT_ID` INT PRIMARY KEY,
    `OVERIGBOUWWERK_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_OVRBRGGNGSDL_GEO_OBJCT` (
    `KP_OVRBRGGNGSDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `OVERBRUGGINGSDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_PND_GEO_OBJCT` (
    `KP_PND_GEO_OBJCT_ID` INT PRIMARY KEY,
    `PAND_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_FNCTNLGBD_GEO_OBJCT` (
    `KP_FNCTNLGBD_GEO_OBJCT_ID` INT PRIMARY KEY,
    `FUNCTIONEELGEBIED_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_KNSTWRKDL_GEO_OBJCT` (
    `KP_KNSTWRKDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `KUNSTWERKDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_GBWNSTLLT_GEO_OBJCT` (
    `KP_GBWNSTLLT_GEO_OBJCT_ID` INT PRIMARY KEY,
    `GEBOUWINSTALLATIE_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_ONDRSTNNDWTRDL_GEO_OBJCT` (
    `KP_ONDRSTNNDWTRDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `ONDERSTEUNENDWATERDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_ONDRSTNNDWGDL_GEO_OBJCT` (
    `KP_ONDRSTNNDWGDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `ONDERSTEUNENDWEGDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_OVRGBNMDTRRN_GEO_OBJCT` (
    `KP_OVRGBNMDTRRN_GEO_OBJCT_ID` INT PRIMARY KEY,
    `OVERIGBENOEMDTERREIN_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_WTRDL_GEO_OBJCT` (
    `KP_WTRDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `WATERDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BGRDTRRNDL_GEO_OBJCT` (
    `KP_BGRDTRRNDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `BEGROEIDTERREINDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_OVRGSCHDNG_GEO_OBJCT` (
    `KP_OVRGSCHDNG_GEO_OBJCT_ID` INT PRIMARY KEY,
    `OVERIGESCHEIDING_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VGTTBJCT_GEO_OBJCT` (
    `KP_VGTTBJCT_GEO_OBJCT_ID` INT PRIMARY KEY,
    `VEGETATIEOBJECT_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_SPR_GEO_OBJCT` (
    `KP_SPR_GEO_OBJCT_ID` INT PRIMARY KEY,
    `SPOOR_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_SCHDNG_GEO_OBJCT` (
    `KP_SCHDNG_GEO_OBJCT_ID` INT PRIMARY KEY,
    `SCHEIDING_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_INRCHTNGSLMNT_GEO_OBJCT` (
    `KP_INRCHTNGSLMNT_GEO_OBJCT_ID` INT PRIMARY KEY,
    `INRICHTINGSELEMENT_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_WGDL_GEO_OBJCT` (
    `KP_WGDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `WEGDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_ONBGRDTRRNDL_GEO_OBJCT` (
    `KP_ONBGRDTRRNDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `ONBEGROEIDTERREINDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_TNNLDL_GEO_OBJCT` (
    `KP_TNNLDL_GEO_OBJCT_ID` INT PRIMARY KEY,
    `TUNNELDEEL_ID` INT,
    `GEO_OBJECT_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `PAND` ADD CONSTRAINT FK_PAND_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `OVERIGBOUWWERK` ADD CONSTRAINT FK_OVERIGBOUWWERK_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `OVERBRUGGINGSDEEL` ADD CONSTRAINT FK_OVERBRUGGINGSDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `KUNSTWERKDEEL` ADD CONSTRAINT FK_KUNSTWERKDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `INRICHTINGSELEMENT` ADD CONSTRAINT FK_INRICHTINGSELEMENT_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `GEBOUWINSTALLATIE` ADD CONSTRAINT FK_GEBOUWINSTALLATIE_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `ONDERSTEUNENDWATERDEEL` ADD CONSTRAINT FK_ONDERSTEUNENDWATERDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `VEGETATIEOBJECT` ADD CONSTRAINT FK_VEGETATIEOBJECT_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `WEGDEEL` ADD CONSTRAINT FK_WEGDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `SCHEIDING` ADD CONSTRAINT FK_SCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `SPOOR` ADD CONSTRAINT FK_SPOOR_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `FUNCTIONEELGEBIED` ADD CONSTRAINT FK_FUNCTIONEELGEBIED_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `ONBEGROEIDTERREINDEEL` ADD CONSTRAINT FK_ONBEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `OVERIGBENOEMDTERREIN` ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `BEGROEIDTERREINDEEL` ADD CONSTRAINT FK_BEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `OVERIGESCHEIDING` ADD CONSTRAINT FK_OVERIGESCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `TUNNELDEEL` ADD CONSTRAINT FK_TUNNELDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `ONDERSTEUNENDWEGDEEL` ADD CONSTRAINT FK_ONDERSTEUNENDWEGDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `WATERDEEL` ADD CONSTRAINT FK_WATERDEEL_GEN_GEO_OBJECT FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- Generalization to GEO_OBJECT

ALTER TABLE `KP_WTRDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_WTRDL_GEO_OBJCT_1 FOREIGN KEY (`WATERDEEL_ID`) REFERENCES `WATERDEEL` (`GEO_OBJECT_ID`);
-- WATERDEEL (many-to-many junction, Connector_ID: 1837)

ALTER TABLE `KP_WTRDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_WTRDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1837)

ALTER TABLE `KP_ONDRSTNNDWGDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_ONDRSTNNDWGDL_GEO_OBJCT_1 FOREIGN KEY (`ONDERSTEUNENDWEGDEEL_ID`) REFERENCES `ONDERSTEUNENDWEGDEEL` (`GEO_OBJECT_ID`);
-- ONDERSTEUNENDWEGDEEL (many-to-many junction, Connector_ID: 1838)

ALTER TABLE `KP_ONDRSTNNDWGDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_ONDRSTNNDWGDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1838)

ALTER TABLE `KP_TNNLDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_TNNLDL_GEO_OBJCT_1 FOREIGN KEY (`TUNNELDEEL_ID`) REFERENCES `TUNNELDEEL` (`GEO_OBJECT_ID`);
-- TUNNELDEEL (many-to-many junction, Connector_ID: 1839)

ALTER TABLE `KP_TNNLDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_TNNLDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1839)

ALTER TABLE `KP_OVRGSCHDNG_GEO_OBJCT` ADD CONSTRAINT FK_KP_OVRGSCHDNG_GEO_OBJCT_1 FOREIGN KEY (`OVERIGESCHEIDING_ID`) REFERENCES `OVERIGESCHEIDING` (`GEO_OBJECT_ID`);
-- OVERIGESCHEIDING (many-to-many junction, Connector_ID: 1840)

ALTER TABLE `KP_OVRGSCHDNG_GEO_OBJCT` ADD CONSTRAINT FK_KP_OVRGSCHDNG_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1840)

ALTER TABLE `KP_BGRDTRRNDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_BGRDTRRNDL_GEO_OBJCT_1 FOREIGN KEY (`BEGROEIDTERREINDEEL_ID`) REFERENCES `BEGROEIDTERREINDEEL` (`GEO_OBJECT_ID`);
-- BEGROEIDTERREINDEEL (many-to-many junction, Connector_ID: 1841)

ALTER TABLE `KP_BGRDTRRNDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_BGRDTRRNDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1841)

ALTER TABLE `KP_OVRGBNMDTRRN_GEO_OBJCT` ADD CONSTRAINT FK_KP_OVRGBNMDTRRN_GEO_OBJCT_1 FOREIGN KEY (`OVERIGBENOEMDTERREIN_ID`) REFERENCES `OVERIGBENOEMDTERREIN` (`GEO_OBJECT_ID`);
-- OVERIGBENOEMDTERREIN (many-to-many junction, Connector_ID: 1844)

ALTER TABLE `KP_OVRGBNMDTRRN_GEO_OBJCT` ADD CONSTRAINT FK_KP_OVRGBNMDTRRN_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1844)

ALTER TABLE `KP_ONBGRDTRRNDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_ONBGRDTRRNDL_GEO_OBJCT_1 FOREIGN KEY (`ONBEGROEIDTERREINDEEL_ID`) REFERENCES `ONBEGROEIDTERREINDEEL` (`GEO_OBJECT_ID`);
-- ONBEGROEIDTERREINDEEL (many-to-many junction, Connector_ID: 1851)

ALTER TABLE `KP_ONBGRDTRRNDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_ONBGRDTRRNDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1851)

ALTER TABLE `KP_FNCTNLGBD_GEO_OBJCT` ADD CONSTRAINT FK_KP_FNCTNLGBD_GEO_OBJCT_1 FOREIGN KEY (`FUNCTIONEELGEBIED_ID`) REFERENCES `FUNCTIONEELGEBIED` (`GEO_OBJECT_ID`);
-- FUNCTIONEELGEBIED (many-to-many junction, Connector_ID: 1855)

ALTER TABLE `KP_FNCTNLGBD_GEO_OBJCT` ADD CONSTRAINT FK_KP_FNCTNLGBD_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1855)

ALTER TABLE `KP_SPR_GEO_OBJCT` ADD CONSTRAINT FK_KP_SPR_GEO_OBJCT_1 FOREIGN KEY (`SPOOR_ID`) REFERENCES `SPOOR` (`GEO_OBJECT_ID`);
-- SPOOR (many-to-many junction, Connector_ID: 1862)

ALTER TABLE `KP_SPR_GEO_OBJCT` ADD CONSTRAINT FK_KP_SPR_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1862)

ALTER TABLE `KP_SCHDNG_GEO_OBJCT` ADD CONSTRAINT FK_KP_SCHDNG_GEO_OBJCT_1 FOREIGN KEY (`SCHEIDING_ID`) REFERENCES `SCHEIDING` (`GEO_OBJECT_ID`);
-- SCHEIDING (many-to-many junction, Connector_ID: 1877)

ALTER TABLE `KP_SCHDNG_GEO_OBJCT` ADD CONSTRAINT FK_KP_SCHDNG_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1877)

ALTER TABLE `KP_WGDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_WGDL_GEO_OBJCT_1 FOREIGN KEY (`WEGDEEL_ID`) REFERENCES `WEGDEEL` (`GEO_OBJECT_ID`);
-- WEGDEEL (many-to-many junction, Connector_ID: 1929)

ALTER TABLE `KP_WGDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_WGDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1929)

ALTER TABLE `KP_VGTTBJCT_GEO_OBJCT` ADD CONSTRAINT FK_KP_VGTTBJCT_GEO_OBJCT_1 FOREIGN KEY (`VEGETATIEOBJECT_ID`) REFERENCES `VEGETATIEOBJECT` (`GEO_OBJECT_ID`);
-- VEGETATIEOBJECT (many-to-many junction, Connector_ID: 1930)

ALTER TABLE `KP_VGTTBJCT_GEO_OBJCT` ADD CONSTRAINT FK_KP_VGTTBJCT_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1930)

ALTER TABLE `KP_ONDRSTNNDWTRDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_ONDRSTNNDWTRDL_GEO_OBJCT_1 FOREIGN KEY (`ONDERSTEUNENDWATERDEEL_ID`) REFERENCES `ONDERSTEUNENDWATERDEEL` (`GEO_OBJECT_ID`);
-- ONDERSTEUNENDWATERDEEL (many-to-many junction, Connector_ID: 1951)

ALTER TABLE `KP_ONDRSTNNDWTRDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_ONDRSTNNDWTRDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1951)

ALTER TABLE `KP_GBWNSTLLT_GEO_OBJCT` ADD CONSTRAINT FK_KP_GBWNSTLLT_GEO_OBJCT_1 FOREIGN KEY (`GEBOUWINSTALLATIE_ID`) REFERENCES `GEBOUWINSTALLATIE` (`GEO_OBJECT_ID`);
-- GEBOUWINSTALLATIE (many-to-many junction, Connector_ID: 1954)

ALTER TABLE `KP_GBWNSTLLT_GEO_OBJCT` ADD CONSTRAINT FK_KP_GBWNSTLLT_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1954)

ALTER TABLE `KP_INRCHTNGSLMNT_GEO_OBJCT` ADD CONSTRAINT FK_KP_INRCHTNGSLMNT_GEO_OBJCT_1 FOREIGN KEY (`INRICHTINGSELEMENT_ID`) REFERENCES `INRICHTINGSELEMENT` (`GEO_OBJECT_ID`);
-- INRICHTINGSELEMENT (many-to-many junction, Connector_ID: 1957)

ALTER TABLE `KP_INRCHTNGSLMNT_GEO_OBJCT` ADD CONSTRAINT FK_KP_INRCHTNGSLMNT_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1957)

ALTER TABLE `KP_KNSTWRKDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_KNSTWRKDL_GEO_OBJCT_1 FOREIGN KEY (`KUNSTWERKDEEL_ID`) REFERENCES `KUNSTWERKDEEL` (`GEO_OBJECT_ID`);
-- KUNSTWERKDEEL (many-to-many junction, Connector_ID: 1977)

ALTER TABLE `KP_KNSTWRKDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_KNSTWRKDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1977)

ALTER TABLE `KP_OVRBRGGNGSDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_OVRBRGGNGSDL_GEO_OBJCT_1 FOREIGN KEY (`OVERBRUGGINGSDEEL_ID`) REFERENCES `OVERBRUGGINGSDEEL` (`GEO_OBJECT_ID`);
-- OVERBRUGGINGSDEEL (many-to-many junction, Connector_ID: 1978)

ALTER TABLE `KP_OVRBRGGNGSDL_GEO_OBJCT` ADD CONSTRAINT FK_KP_OVRBRGGNGSDL_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1978)

ALTER TABLE `KP_OVRGBWWRK_GEO_OBJCT` ADD CONSTRAINT FK_KP_OVRGBWWRK_GEO_OBJCT_1 FOREIGN KEY (`OVERIGBOUWWERK_ID`) REFERENCES `OVERIGBOUWWERK` (`GEO_OBJECT_ID`);
-- OVERIGBOUWWERK (many-to-many junction, Connector_ID: 1986)

ALTER TABLE `KP_OVRGBWWRK_GEO_OBJCT` ADD CONSTRAINT FK_KP_OVRGBWWRK_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1986)

ALTER TABLE `KP_PND_GEO_OBJCT` ADD CONSTRAINT FK_KP_PND_GEO_OBJCT_1 FOREIGN KEY (`PAND_ID`) REFERENCES `PAND` (`GEO_OBJECT_ID`);
-- PAND (many-to-many junction, Connector_ID: 2298)

ALTER TABLE `KP_PND_GEO_OBJCT` ADD CONSTRAINT FK_KP_PND_GEO_OBJCT_2 FOREIGN KEY (`GEO_OBJECT_ID`) REFERENCES `GEO_OBJECT` (`GEO_OBJECT_ID`);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 2298)

ALTER TABLE `GEO_OBJECT` ADD CONSTRAINT FK_GEO_OBJECT_VERWIJST_NAAR FOREIGN KEY (`VERWIJST_NAAR_BEHEEROBJECT_ID`) REFERENCES `BEHEEROBJECT` (`BEHEEROBJECT_ID`);
-- VERWIJST_NAAR (1 to 0..1, Connector_ID: 805)

