CREATE TABLE BEHEEROBJECT (
    BEHEEROBJECT_ID NUMBER PRIMARY KEY,
    AANGEMAAKTDOOR VARCHAR2(200),
    BEGINGARANTIEPERIODE VARCHAR2(255),
    BEHEERGEBIED VARCHAR2(255),
    BEHEEROBJECTBEHEERVAK VARCHAR2(255),
    BEHEEROBJECTGEBRUIKSFUNCTIE VARCHAR2(255),
    BEHEEROBJECTMEMO VARCHAR2(255),
    BESCHERMDEFLORAENFAUNA NUMBER(1),
    BUURT VARCHAR2(80),
    CONVERSIEID VARCHAR2(50),
    DATUMMUTATIE DATE,
    DATUMOPLEVERING DATE,
    DATUMPUBLICATIELV DATE,
    DATUMVERWIJDERING DATE,
    EINDEGARANTIEPERIODE DATE,
    GEBIEDSTYPE VARCHAR2(255),
    GEMEENTE VARCHAR2(80),
    GEOMETRIE SDO_GEOMETRY,
    GEWIJZIGDDOOR VARCHAR2(200),
    GRONDSOORT VARCHAR2(255),
    GRONDSOORTPLUS VARCHAR2(255),
    IDENTIFICATIEIMBOR VARCHAR2(255),
    IDENTIFICATIEIMGEO VARCHAR2(255),
    JAARVANAANLEG VARCHAR2(255),
    OBJECTBEGINTIJD TIMESTAMP,
    OBJECTEINDTIJD TIMESTAMP,
    ONDERHOUDSPLICHTIGE VARCHAR2(255),
    OPENBARERUIMTE VARCHAR2(80),
    POSTCODE VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STADSDEEL VARCHAR2(80),
    STATUS VARCHAR2(255),
    THEORETISCHEINDEJAAR DATE,
    TIJDSTIPREGISTRATIE TIMESTAMP,
    TYPEBEHEERDER VARCHAR2(255),
    TYPEBEHEERDERPLUS VARCHAR2(255),
    TYPEEIGENAAR VARCHAR2(255),
    TYPEEIGENAARPLUS VARCHAR2(255),
    TYPELIGGING VARCHAR2(255),
    WATERSCHAP VARCHAR2(80),
    WIJK VARCHAR2(80),
    WOONPLAATS VARCHAR2(80),
    ZETTINGSGEVOELIGHEID VARCHAR2(255),
    ZETTINGSGEVOELIGHEIDPLUS VARCHAR2(255)
);

CREATE TABLE GEO_OBJECT (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    GEOMETRIESOORT SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    VERWIJST_NAAR_BEHEEROBJECT_ID NUMBER
);

CREATE TABLE OVERIGBOUWWERK (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDOVERIGBOUWWERK DATE,
    DATUMEINDEGELDIGHEIDOVERIGBOUWWERK DATE,
    GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    IDENTIFICATIEOVERIGBOUWWERK VARCHAR2(255),
    LOD0GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    LOD1GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    LOD2GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    LOD3GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGOVERIGBOUWWERK VARCHAR2(255),
    STATUSOVERIGBOUWWERK VARCHAR2(255)
);

CREATE TABLE OVERBRUGGINGSDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDOVERBRUGGINGSDEEL DATE,
    DATUMEINDEGELDIGHEIDOVERBRUGGINGSDEEL DATE,
    GEOMETRIEOVERBRUGGINGSDEEL SDO_GEOMETRY,
    HOORTBIJTYPEOVERBRUGGING VARCHAR2(255),
    IDENTIFICATIEOVERBRUGGINGSDEEL VARCHAR2(255),
    LOD0GEOMETRIEOVERBRUGGINGSDEEL SDO_GEOMETRY,
    OVERBRUGGINGISBEWEEGBAAR NUMBER(1),
    RELATIEVEHOOGTELIGGINGOVERBRUGGINGSDEEL VARCHAR2(255),
    STATUSOVERBRUGGINGSDEEL VARCHAR2(255),
    TYPEOVERBRUGGINGSDEEL VARCHAR2(255)
);

CREATE TABLE PAND (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    BRUTOINHOUDPAND VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER VARCHAR2(255),
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIEBOVENAANZICHT SDO_GEOMETRY,
    GEOMETRIEMAAIVELD SDO_GEOMETRY,
    GEOMETRIEPUNT SDO_GEOMETRY,
    HOOGSTEBOUWLAAG VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LAAGSTEBOUWLAAG VARCHAR2(255),
    OORSPRONKELIJKBOUWJAAR VARCHAR2(255),
    OPPERVLAKTE VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUS VARCHAR2(255),
    STATUSVOORTGANGBOUW VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE FUNCTIONEELGEBIED (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDFUNCTIONEELGEBIED DATE,
    DATUMEINDEGELDIGHEIDFUNCTIONEELGEBIED DATE,
    GEOMETRIEFUNCTIONEELGEBIED SDO_GEOMETRY,
    IDENTIFICATIEFUNCTIONEELGEBIED VARCHAR2(255),
    NAAMFUNCTIONEELGEBIED VARCHAR2(255),
    STATUSFUNCTIONEELGEBIED VARCHAR2(255)
);

CREATE TABLE KUNSTWERKDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDKUNSTWERKDEEL DATE,
    DATUMEINDEGELDIGHEIDKUNSTWERKDEEL DATE,
    GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    IDENTIFICATIEKUNSTWERKDEEL VARCHAR2(255),
    LOD0GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    LOD1GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    LOD2GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    LOD3GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGKUNSTWERKDEEL VARCHAR2(255),
    STATUSKUNSTWERKDEEL VARCHAR2(255)
);

CREATE TABLE GEBOUWINSTALLATIE (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDGEBOUWINSTALLATIE DATE,
    DATUMEINDEGELDIGHEIDGEBOUWINSTALLATIE DATE,
    GEOMETRIEGEBOUWINSTALLATIE SDO_GEOMETRY,
    IDENTIFICATIEGEBOUWINSTALLATIE VARCHAR2(255),
    LOD0GEOMETRIEGEBOUWINSTALLATIE SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGGEBOUWINSTALLATIE VARCHAR2(255),
    STATUSGEBOUWINSTALLATIE VARCHAR2(255),
    TYPEGEBOUWINSTALLATIE VARCHAR2(255)
);

CREATE TABLE ONDERSTEUNENDWATERDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    PLUSTYPE VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUS VARCHAR2(255),
    TYPE VARCHAR2(255)
);

CREATE TABLE ONDERSTEUNENDWEGDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    FUNCTIE VARCHAR2(255),
    FYSIEKVOORKOMEN VARCHAR2(255),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    KRUINLIJNGEOMETRIE SDO_GEOMETRY,
    LOD0GEOMETRIE SDO_GEOMETRY,
    OPTALUD NUMBER(1),
    PLUSFUNCTIE VARCHAR2(255),
    PLUSFYSIEKVOORKOMEN VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUS VARCHAR2(255)
);

CREATE TABLE OVERIGBENOEMDTERREIN (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    GEBRUIKSDOELOVERIGBENOEMDTERREIN VARCHAR2(255),
    OVERIGBENOEMDTERREINIDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE WATERDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDWATERDEEL DATE,
    DATUMEINDEGELDIGHEIDWATERDEEL DATE,
    GEOMETRIEWATERDEEL SDO_GEOMETRY,
    IDENTIFICATIEWATERDEEL VARCHAR2(255),
    PLUSTYPEWATERDEEL VARCHAR2(255),
    RELATIEVEHOOGTELIGGINGWATERDEEL VARCHAR2(255),
    STATUSWATERDEEL VARCHAR2(255),
    TYPEWATERDEEL VARCHAR2(255)
);

CREATE TABLE BEGROEIDTERREINDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    FYSIEKVOORKOMEN VARCHAR2(255),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    KRUINLIJNGEOMETRIE SDO_GEOMETRY,
    LOD0GEOMETRIE SDO_GEOMETRY,
    OPTALUD NUMBER(1),
    PLUSFYSIEKVOORKOMEN VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUS VARCHAR2(255)
);

CREATE TABLE OVERIGESCHEIDING (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDOVERIGESCHEIDING DATE,
    DATUMEINDEGELDIGHEIDOVERIGESCHEIDING DATE,
    GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    IDENTIFICATIEOVERIGESCHEIDING VARCHAR2(255),
    LOD0GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    LOD1GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    LOD2GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    LOD3GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGOVERIGESCHEIDING VARCHAR2(255),
    STATUSOVERIGESCHEIDING VARCHAR2(255),
    TYPEOVERIGESCHEIDING VARCHAR2(255)
);

CREATE TABLE VEGETATIEOBJECT (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDVEGETATIEOBJECT DATE,
    DATUMEINDEGELDIGHEIDVEGETATIEOBJECT DATE,
    GEOMETRIEVEGETATIEOBJECT SDO_GEOMETRY,
    IDENTIFICATIEVEGETATIEOBJECT VARCHAR2(255),
    LOD0GEOMETRIEVEGETATIEOBJECT SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGVEGETATIEOBJECT VARCHAR2(255),
    STATUSVEGETATIEOBJECT VARCHAR2(255),
    TYPEVEGETATIEOBJECT VARCHAR2(255)
);

CREATE TABLE SPOOR (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDSPOOR DATE,
    DATUMEINDEGELDIGHEIDSPOOR DATE,
    GEOMETRIESPOOR SDO_GEOMETRY,
    IDENTIFICATIESPOOR VARCHAR2(255),
    LOD0GEOMETRIESPOOR SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGSPOOR VARCHAR2(255),
    STATUSSPOOR VARCHAR2(255)
);

CREATE TABLE SCHEIDING (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDSCHEIDING DATE,
    DATUMEINDEGELDIGHEIDSCHEIDING DATE,
    GEOMETRIESCHEIDING SDO_GEOMETRY,
    IDENTIFICATIESCHEIDING VARCHAR2(255),
    LOD0GEOMETRIESCHEIDING SDO_GEOMETRY,
    LOD1GEOMETRIESCHEIDING SDO_GEOMETRY,
    LOD2GEOMETRIESCHEIDING SDO_GEOMETRY,
    LOD3GEOMETRIESCHEIDING SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGSCHEIDING VARCHAR2(255),
    STATUSSCHEIDING VARCHAR2(255)
);

CREATE TABLE INRICHTINGSELEMENT (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDINRICHTINGSELEMENT DATE,
    DATUMEINDEGELDIGHEIDINRICHTINGSELEMENT DATE,
    GEOMETRIEINRICHTINGSELEMENT SDO_GEOMETRY,
    IDENTIFICATIEINRICHTINGSELEMENT VARCHAR2(255),
    LOD0GEOMETRIEINRICHTINGSELEMENT SDO_GEOMETRY,
    PLUSTYPEINRICHTINGSELEMENT VARCHAR2(255),
    RELATIEVEHOOGTELIGGINGINRICHTINGSELEMENT VARCHAR2(255),
    STATUSINRICHTINGSELEMENT VARCHAR2(255),
    TYPEINRICHTINGSELEMENT VARCHAR2(255)
);

CREATE TABLE WEGDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDWEGDEEL DATE,
    DATUMEINDEGELDIGHEIDWEGDEEL DATE,
    FUNCTIEWEGDEEL VARCHAR2(255),
    FYSIEKVOORKOMENWEGDEEL VARCHAR2(255),
    GEOMETRIEWEGDEEL SDO_GEOMETRY,
    IDENTIFICATIEWEGDEEL VARCHAR2(255),
    KRUINLIJNGEOMETRIEWEGDEEL SDO_GEOMETRY,
    LOD0GEOMETRIEWEGDEEL SDO_GEOMETRY,
    PLUSFUNCTIEWEGDEEL VARCHAR2(255),
    PLUSFYSIEKVOORKOMENWEGDEEL VARCHAR2(255),
    RELATIEVEHOOGTELIGGINGWEGDEEL VARCHAR2(255),
    STATUSWEGDEEL VARCHAR2(255),
    WEGDEELOPTALUD NUMBER(1)
);

CREATE TABLE ONBEGROEIDTERREINDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    FYSIEKVOORKOMEN VARCHAR2(255),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    KRUINLIJNGEOMETRIE SDO_GEOMETRY,
    ONBEGROEIDTERREINDEELOPTALUD DATE,
    PLUSFYSIEKVOORKOMEN VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUS VARCHAR2(255)
);

CREATE TABLE TUNNELDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDTUNNELDEEL DATE,
    DATUMEINDEGELDIGHEIDTUNNELDEEL DATE,
    GEOMETRIETUNNELDEEL SDO_GEOMETRY,
    IDENTIFICATIETUNNELDEEL VARCHAR2(255),
    LOD0GEOMETRIETUNNELDEEL SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGTUNNELDEEL VARCHAR2(255),
    STATUSTUNNELDEEL VARCHAR2(255)
);

CREATE TABLE KP_OVRGBWWRK_GEO_OBJCT (
    KP_OVRGBWWRK_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    OVERIGBOUWWERK_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_OVRBRGGNGSDL_GEO_OBJCT (
    KP_OVRBRGGNGSDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    OVERBRUGGINGSDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_PND_GEO_OBJCT (
    KP_PND_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    PAND_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_FNCTNLGBD_GEO_OBJCT (
    KP_FNCTNLGBD_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    FUNCTIONEELGEBIED_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_KNSTWRKDL_GEO_OBJCT (
    KP_KNSTWRKDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    KUNSTWERKDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_GBWNSTLLT_GEO_OBJCT (
    KP_GBWNSTLLT_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    GEBOUWINSTALLATIE_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_ONDRSTNNDWTRDL_GEO_OBJCT (
    KP_ONDRSTNNDWTRDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    ONDERSTEUNENDWATERDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_ONDRSTNNDWGDL_GEO_OBJCT (
    KP_ONDRSTNNDWGDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    ONDERSTEUNENDWEGDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_OVRGBNMDTRRN_GEO_OBJCT (
    KP_OVRGBNMDTRRN_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    OVERIGBENOEMDTERREIN_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_WTRDL_GEO_OBJCT (
    KP_WTRDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    WATERDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_BGRDTRRNDL_GEO_OBJCT (
    KP_BGRDTRRNDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    BEGROEIDTERREINDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_OVRGSCHDNG_GEO_OBJCT (
    KP_OVRGSCHDNG_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    OVERIGESCHEIDING_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_VGTTBJCT_GEO_OBJCT (
    KP_VGTTBJCT_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    VEGETATIEOBJECT_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_SPR_GEO_OBJCT (
    KP_SPR_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    SPOOR_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_SCHDNG_GEO_OBJCT (
    KP_SCHDNG_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    SCHEIDING_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_INRCHTNGSLMNT_GEO_OBJCT (
    KP_INRCHTNGSLMNT_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    INRICHTINGSELEMENT_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_WGDL_GEO_OBJCT (
    KP_WGDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    WEGDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_ONBGRDTRRNDL_GEO_OBJCT (
    KP_ONBGRDTRRNDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    ONBEGROEIDTERREINDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

CREATE TABLE KP_TNNLDL_GEO_OBJCT (
    KP_TNNLDL_GEO_OBJCT_ID NUMBER PRIMARY KEY,
    TUNNELDEEL_ID NUMBER,
    GEO_OBJECT_ID NUMBER
);

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGBOUWWERK ADD CONSTRAINT FK_OVERIGBOUWWERK_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERBRUGGINGSDEEL ADD CONSTRAINT FK_OVERBRUGGINGSDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE KUNSTWERKDEEL ADD CONSTRAINT FK_KUNSTWERKDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE INRICHTINGSELEMENT ADD CONSTRAINT FK_INRICHTINGSELEMENT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE GEBOUWINSTALLATIE ADD CONSTRAINT FK_GEBOUWINSTALLATIE_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONDERSTEUNENDWATERDEEL ADD CONSTRAINT FK_ONDERSTEUNENDWATERDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE VEGETATIEOBJECT ADD CONSTRAINT FK_VEGETATIEOBJECT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE WEGDEEL ADD CONSTRAINT FK_WEGDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE SCHEIDING ADD CONSTRAINT FK_SCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE SPOOR ADD CONSTRAINT FK_SPOOR_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE FUNCTIONEELGEBIED ADD CONSTRAINT FK_FUNCTIONEELGEBIED_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONBEGROEIDTERREINDEEL ADD CONSTRAINT FK_ONBEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGBENOEMDTERREIN ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE BEGROEIDTERREINDEEL ADD CONSTRAINT FK_BEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGESCHEIDING ADD CONSTRAINT FK_OVERIGESCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE TUNNELDEEL ADD CONSTRAINT FK_TUNNELDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONDERSTEUNENDWEGDEEL ADD CONSTRAINT FK_ONDERSTEUNENDWEGDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE WATERDEEL ADD CONSTRAINT FK_WATERDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE KP_WTRDL_GEO_OBJCT ADD CONSTRAINT FK_KP_WTRDL_GEO_OBJCT_1 FOREIGN KEY (WATERDEEL_ID) REFERENCES WATERDEEL (GEO_OBJECT_ID);
-- WATERDEEL (many-to-many junction, Connector_ID: 1837)

ALTER TABLE KP_WTRDL_GEO_OBJCT ADD CONSTRAINT FK_KP_WTRDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1837)

ALTER TABLE KP_ONDRSTNNDWGDL_GEO_OBJCT ADD CONSTRAINT FK_KP_ONDRSTNNDWGDL_GEO_OBJCT_1 FOREIGN KEY (ONDERSTEUNENDWEGDEEL_ID) REFERENCES ONDERSTEUNENDWEGDEEL (GEO_OBJECT_ID);
-- ONDERSTEUNENDWEGDEEL (many-to-many junction, Connector_ID: 1838)

ALTER TABLE KP_ONDRSTNNDWGDL_GEO_OBJCT ADD CONSTRAINT FK_KP_ONDRSTNNDWGDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1838)

ALTER TABLE KP_TNNLDL_GEO_OBJCT ADD CONSTRAINT FK_KP_TNNLDL_GEO_OBJCT_1 FOREIGN KEY (TUNNELDEEL_ID) REFERENCES TUNNELDEEL (GEO_OBJECT_ID);
-- TUNNELDEEL (many-to-many junction, Connector_ID: 1839)

ALTER TABLE KP_TNNLDL_GEO_OBJCT ADD CONSTRAINT FK_KP_TNNLDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1839)

ALTER TABLE KP_OVRGSCHDNG_GEO_OBJCT ADD CONSTRAINT FK_KP_OVRGSCHDNG_GEO_OBJCT_1 FOREIGN KEY (OVERIGESCHEIDING_ID) REFERENCES OVERIGESCHEIDING (GEO_OBJECT_ID);
-- OVERIGESCHEIDING (many-to-many junction, Connector_ID: 1840)

ALTER TABLE KP_OVRGSCHDNG_GEO_OBJCT ADD CONSTRAINT FK_KP_OVRGSCHDNG_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1840)

ALTER TABLE KP_BGRDTRRNDL_GEO_OBJCT ADD CONSTRAINT FK_KP_BGRDTRRNDL_GEO_OBJCT_1 FOREIGN KEY (BEGROEIDTERREINDEEL_ID) REFERENCES BEGROEIDTERREINDEEL (GEO_OBJECT_ID);
-- BEGROEIDTERREINDEEL (many-to-many junction, Connector_ID: 1841)

ALTER TABLE KP_BGRDTRRNDL_GEO_OBJCT ADD CONSTRAINT FK_KP_BGRDTRRNDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1841)

ALTER TABLE KP_OVRGBNMDTRRN_GEO_OBJCT ADD CONSTRAINT FK_KP_OVRGBNMDTRRN_GEO_OBJCT_1 FOREIGN KEY (OVERIGBENOEMDTERREIN_ID) REFERENCES OVERIGBENOEMDTERREIN (GEO_OBJECT_ID);
-- OVERIGBENOEMDTERREIN (many-to-many junction, Connector_ID: 1844)

ALTER TABLE KP_OVRGBNMDTRRN_GEO_OBJCT ADD CONSTRAINT FK_KP_OVRGBNMDTRRN_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1844)

ALTER TABLE KP_ONBGRDTRRNDL_GEO_OBJCT ADD CONSTRAINT FK_KP_ONBGRDTRRNDL_GEO_OBJCT_1 FOREIGN KEY (ONBEGROEIDTERREINDEEL_ID) REFERENCES ONBEGROEIDTERREINDEEL (GEO_OBJECT_ID);
-- ONBEGROEIDTERREINDEEL (many-to-many junction, Connector_ID: 1851)

ALTER TABLE KP_ONBGRDTRRNDL_GEO_OBJCT ADD CONSTRAINT FK_KP_ONBGRDTRRNDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1851)

ALTER TABLE KP_FNCTNLGBD_GEO_OBJCT ADD CONSTRAINT FK_KP_FNCTNLGBD_GEO_OBJCT_1 FOREIGN KEY (FUNCTIONEELGEBIED_ID) REFERENCES FUNCTIONEELGEBIED (GEO_OBJECT_ID);
-- FUNCTIONEELGEBIED (many-to-many junction, Connector_ID: 1855)

ALTER TABLE KP_FNCTNLGBD_GEO_OBJCT ADD CONSTRAINT FK_KP_FNCTNLGBD_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1855)

ALTER TABLE KP_SPR_GEO_OBJCT ADD CONSTRAINT FK_KP_SPR_GEO_OBJCT_1 FOREIGN KEY (SPOOR_ID) REFERENCES SPOOR (GEO_OBJECT_ID);
-- SPOOR (many-to-many junction, Connector_ID: 1862)

ALTER TABLE KP_SPR_GEO_OBJCT ADD CONSTRAINT FK_KP_SPR_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1862)

ALTER TABLE KP_SCHDNG_GEO_OBJCT ADD CONSTRAINT FK_KP_SCHDNG_GEO_OBJCT_1 FOREIGN KEY (SCHEIDING_ID) REFERENCES SCHEIDING (GEO_OBJECT_ID);
-- SCHEIDING (many-to-many junction, Connector_ID: 1877)

ALTER TABLE KP_SCHDNG_GEO_OBJCT ADD CONSTRAINT FK_KP_SCHDNG_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1877)

ALTER TABLE KP_WGDL_GEO_OBJCT ADD CONSTRAINT FK_KP_WGDL_GEO_OBJCT_1 FOREIGN KEY (WEGDEEL_ID) REFERENCES WEGDEEL (GEO_OBJECT_ID);
-- WEGDEEL (many-to-many junction, Connector_ID: 1929)

ALTER TABLE KP_WGDL_GEO_OBJCT ADD CONSTRAINT FK_KP_WGDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1929)

ALTER TABLE KP_VGTTBJCT_GEO_OBJCT ADD CONSTRAINT FK_KP_VGTTBJCT_GEO_OBJCT_1 FOREIGN KEY (VEGETATIEOBJECT_ID) REFERENCES VEGETATIEOBJECT (GEO_OBJECT_ID);
-- VEGETATIEOBJECT (many-to-many junction, Connector_ID: 1930)

ALTER TABLE KP_VGTTBJCT_GEO_OBJCT ADD CONSTRAINT FK_KP_VGTTBJCT_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1930)

ALTER TABLE KP_ONDRSTNNDWTRDL_GEO_OBJCT ADD CONSTRAINT FK_KP_ONDRSTNNDWTRDL_GEO_OBJCT_1 FOREIGN KEY (ONDERSTEUNENDWATERDEEL_ID) REFERENCES ONDERSTEUNENDWATERDEEL (GEO_OBJECT_ID);
-- ONDERSTEUNENDWATERDEEL (many-to-many junction, Connector_ID: 1951)

ALTER TABLE KP_ONDRSTNNDWTRDL_GEO_OBJCT ADD CONSTRAINT FK_KP_ONDRSTNNDWTRDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1951)

ALTER TABLE KP_GBWNSTLLT_GEO_OBJCT ADD CONSTRAINT FK_KP_GBWNSTLLT_GEO_OBJCT_1 FOREIGN KEY (GEBOUWINSTALLATIE_ID) REFERENCES GEBOUWINSTALLATIE (GEO_OBJECT_ID);
-- GEBOUWINSTALLATIE (many-to-many junction, Connector_ID: 1954)

ALTER TABLE KP_GBWNSTLLT_GEO_OBJCT ADD CONSTRAINT FK_KP_GBWNSTLLT_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1954)

ALTER TABLE KP_INRCHTNGSLMNT_GEO_OBJCT ADD CONSTRAINT FK_KP_INRCHTNGSLMNT_GEO_OBJCT_1 FOREIGN KEY (INRICHTINGSELEMENT_ID) REFERENCES INRICHTINGSELEMENT (GEO_OBJECT_ID);
-- INRICHTINGSELEMENT (many-to-many junction, Connector_ID: 1957)

ALTER TABLE KP_INRCHTNGSLMNT_GEO_OBJCT ADD CONSTRAINT FK_KP_INRCHTNGSLMNT_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1957)

ALTER TABLE KP_KNSTWRKDL_GEO_OBJCT ADD CONSTRAINT FK_KP_KNSTWRKDL_GEO_OBJCT_1 FOREIGN KEY (KUNSTWERKDEEL_ID) REFERENCES KUNSTWERKDEEL (GEO_OBJECT_ID);
-- KUNSTWERKDEEL (many-to-many junction, Connector_ID: 1977)

ALTER TABLE KP_KNSTWRKDL_GEO_OBJCT ADD CONSTRAINT FK_KP_KNSTWRKDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1977)

ALTER TABLE KP_OVRBRGGNGSDL_GEO_OBJCT ADD CONSTRAINT FK_KP_OVRBRGGNGSDL_GEO_OBJCT_1 FOREIGN KEY (OVERBRUGGINGSDEEL_ID) REFERENCES OVERBRUGGINGSDEEL (GEO_OBJECT_ID);
-- OVERBRUGGINGSDEEL (many-to-many junction, Connector_ID: 1978)

ALTER TABLE KP_OVRBRGGNGSDL_GEO_OBJCT ADD CONSTRAINT FK_KP_OVRBRGGNGSDL_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1978)

ALTER TABLE KP_OVRGBWWRK_GEO_OBJCT ADD CONSTRAINT FK_KP_OVRGBWWRK_GEO_OBJCT_1 FOREIGN KEY (OVERIGBOUWWERK_ID) REFERENCES OVERIGBOUWWERK (GEO_OBJECT_ID);
-- OVERIGBOUWWERK (many-to-many junction, Connector_ID: 1986)

ALTER TABLE KP_OVRGBWWRK_GEO_OBJCT ADD CONSTRAINT FK_KP_OVRGBWWRK_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 1986)

ALTER TABLE KP_PND_GEO_OBJCT ADD CONSTRAINT FK_KP_PND_GEO_OBJCT_1 FOREIGN KEY (PAND_ID) REFERENCES PAND (GEO_OBJECT_ID);
-- PAND (many-to-many junction, Connector_ID: 2298)

ALTER TABLE KP_PND_GEO_OBJCT ADD CONSTRAINT FK_KP_PND_GEO_OBJCT_2 FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- GEO_OBJECT (many-to-many junction, Connector_ID: 2298)

ALTER TABLE GEO_OBJECT ADD CONSTRAINT FK_GEO_OBJECT_VERWIJST_NAAR FOREIGN KEY (VERWIJST_NAAR_BEHEEROBJECT_ID) REFERENCES BEHEEROBJECT (BEHEEROBJECT_ID);
-- VERWIJST_NAAR (1 to 0..1, Connector_ID: 805)

