CREATE TABLE OVERIGEADRESSEERBAAROBJECTAANDUIDING (
    NUMMERAANDUIDING_ID NUMBER PRIMARY KEY,
    IDENTIFICATIECODE VARCHAR2(255)
);

CREATE TABLE KP_LGPLTS_ADRSSRBRBJCT (
    KP_LGPLTS_ADRSSRBRBJCT_ID NUMBER PRIMARY KEY,
    LIGPLAATS_ID NUMBER,
    ADRESSEERBAAROBJECT_ID NUMBER
);

CREATE TABLE OVERIGGEBOUWDOBJECT (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    BOUWJAAR VARCHAR2(255),
    HEEFT_ALS_OFFICIEEL_ADRES_NUMMERAANDUIDING_ID NUMBER,
    INDICATIEPLANOBJECT NUMBER(1),
    OVERIGGEBOUWDOBJECTIDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE KP_OVRGBNMDTRRN_ADRSSRBRBJCT (
    KP_OVRGBNMDTRRN_ADRSSRBRBJCT_ID NUMBER PRIMARY KEY,
    OVERIGBENOEMDTERREIN_ID NUMBER,
    ADRESSEERBAAROBJECT_ID NUMBER
);

CREATE TABLE OPENBARERUIMTE (
    OPENBARERUIMTE_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS VARCHAR2(255),
    HUISNUMMERRANGE_EVEN_NUMMERS VARCHAR2(255),
    HUISNUMMERRANGE_ONEVEN_NUMMERS VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LABELNAAM VARCHAR2(80),
    NAAMOPENBARERUIMTE VARCHAR2(80),
    STATUS VARCHAR2(255),
    STRAATCODE VARCHAR2(80),
    STRAATNAAM VARCHAR2(255),
    TYPEOPENBARERUIMTE VARCHAR2(255),
    VERSIE NUMBER,
    WEGSEGMENT VARCHAR2(255)
);

CREATE TABLE KP_VRBLJFSBJCT_ADRSSRBRBJCT (
    KP_VRBLJFSBJCT_ADRSSRBRBJCT_ID NUMBER PRIMARY KEY,
    VERBLIJFSOBJECT_ID NUMBER,
    ADRESSEERBAAROBJECT_ID NUMBER
);

CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID NUMBER,
    IDENTIFICATIE VARCHAR2(255),
    TYPEADRESSEERBAAROBJECT VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDEGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    HEEFT_ALS_NEVENADRES_ADRESSEERBAAROBJECT_ID NUMBER,
    HUISLETTER VARCHAR2(255),
    HUISNUMMER VARCHAR2(255),
    HUISNUMMERTOEVOEGING VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LIGT_AAN_OPENBARERUIMTE_ID NUMBER,
    POSTCODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    TYPEADRESSEERBAAROBJECT VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE VERBLIJFSOBJECT (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    AANTALKAMERS VARCHAR2(255),
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GEBRUIKSDOEL VARCHAR2(255),
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    HOOGSTEBOUWLAAG VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    LAAGSTEBOUWLAAG VARCHAR2(255),
    ONTSLUITINGVERDIEPING VARCHAR2(255),
    OPPERVLAKTE NUMBER,
    SOORTWOONOBJECT VARCHAR2(255),
    STATUS VARCHAR2(255),
    TOEGANGBOUWLAAG VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE OVERIGBENOEMDTERREIN (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    GEBRUIKSDOELOVERIGBENOEMDTERREIN VARCHAR2(255),
    HEEFT_ALS_OFFICIEEL_ADRES_NUMMERAANDUIDING_ID NUMBER,
    OVERIGBENOEMDTERREINIDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE KP_OVRGGBWDBJCT_ADRSSRBRBJCT (
    KP_OVRGGBWDBJCT_ADRSSRBRBJCT_ID NUMBER PRIMARY KEY,
    OVERIGGEBOUWDOBJECT_ID NUMBER,
    ADRESSEERBAAROBJECT_ID NUMBER
);

CREATE TABLE KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG (
    KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG_ID NUMBER PRIMARY KEY,
    OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID NUMBER,
    NUMMERAANDUIDING_ID NUMBER
);

CREATE TABLE LIGPLAATS (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    STATUS VARCHAR2(255),
    VERSIE VARCHAR2(255)
);

CREATE TABLE KP_STNDPLTS_ADRSSRBRBJCT (
    KP_STNDPLTS_ADRSSRBRBJCT_ID NUMBER PRIMARY KEY,
    STANDPLAATS_ID NUMBER,
    ADRESSEERBAAROBJECT_ID NUMBER
);

CREATE TABLE STANDPLAATS (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    STATUS VARCHAR2(255),
    VERSIE NUMBER
);

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE LIGPLAATS ADD CONSTRAINT FK_LIGPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE STANDPLAATS ADD CONSTRAINT FK_STANDPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE OVERIGEADRESSEERBAAROBJECTAANDUIDING ADD CONSTRAINT FK_OVERIGEADRESSEERBAAROBJECTAANDUIDING_GEN_NUMMERAANDUIDING FOREIGN KEY (NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- Generalization to NUMMERAANDUIDING

ALTER TABLE OVERIGGEBOUWDOBJECT ADD CONSTRAINT FK_OVERIGGEBOUWDOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE OVERIGBENOEMDTERREIN ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE KP_OVRGGBWDBJCT_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_OVRGGBWDBJCT_ADRSSRBRBJCT_1 FOREIGN KEY (OVERIGGEBOUWDOBJECT_ID) REFERENCES OVERIGGEBOUWDOBJECT (ADRESSEERBAAROBJECT_ID);
-- OVERIGGEBOUWDOBJECT (many-to-many junction, Connector_ID: 2243)

ALTER TABLE KP_OVRGGBWDBJCT_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_OVRGGBWDBJCT_ADRSSRBRBJCT_2 FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2243)

ALTER TABLE KP_OVRGBNMDTRRN_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_OVRGBNMDTRRN_ADRSSRBRBJCT_1 FOREIGN KEY (OVERIGBENOEMDTERREIN_ID) REFERENCES OVERIGBENOEMDTERREIN (ADRESSEERBAAROBJECT_ID);
-- OVERIGBENOEMDTERREIN (many-to-many junction, Connector_ID: 2245)

ALTER TABLE KP_OVRGBNMDTRRN_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_OVRGBNMDTRRN_ADRSSRBRBJCT_2 FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2245)

ALTER TABLE KP_STNDPLTS_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_STNDPLTS_ADRSSRBRBJCT_1 FOREIGN KEY (STANDPLAATS_ID) REFERENCES STANDPLAATS (ADRESSEERBAAROBJECT_ID);
-- STANDPLAATS (many-to-many junction, Connector_ID: 2252)

ALTER TABLE KP_STNDPLTS_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_STNDPLTS_ADRSSRBRBJCT_2 FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2252)

ALTER TABLE KP_LGPLTS_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_LGPLTS_ADRSSRBRBJCT_1 FOREIGN KEY (LIGPLAATS_ID) REFERENCES LIGPLAATS (ADRESSEERBAAROBJECT_ID);
-- LIGPLAATS (many-to-many junction, Connector_ID: 2253)

ALTER TABLE KP_LGPLTS_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_LGPLTS_ADRSSRBRBJCT_2 FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2253)

ALTER TABLE KP_VRBLJFSBJCT_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_VRBLJFSBJCT_ADRSSRBRBJCT_1 FOREIGN KEY (VERBLIJFSOBJECT_ID) REFERENCES VERBLIJFSOBJECT (ADRESSEERBAAROBJECT_ID);
-- VERBLIJFSOBJECT (many-to-many junction, Connector_ID: 2262)

ALTER TABLE KP_VRBLJFSBJCT_ADRSSRBRBJCT ADD CONSTRAINT FK_KP_VRBLJFSBJCT_ADRSSRBRBJCT_2 FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2262)

ALTER TABLE KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG ADD CONSTRAINT FK_KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG_1 FOREIGN KEY (OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID) REFERENCES OVERIGEADRESSEERBAAROBJECTAANDUIDING (NUMMERAANDUIDING_ID);
-- OVERIGEADRESSEERBAAROBJECTAANDUIDING (many-to-many junction, Connector_ID: 2277)

ALTER TABLE KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG ADD CONSTRAINT FK_KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG_2 FOREIGN KEY (NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- NUMMERAANDUIDING (many-to-many junction, Connector_ID: 2277)

ALTER TABLE KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG ADD CONSTRAINT FK_KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG_1 FOREIGN KEY (OVERIGEADRESSEERBAAROBJECTAANDUIDING_ID) REFERENCES OVERIGEADRESSEERBAAROBJECTAANDUIDING (NUMMERAANDUIDING_ID);
-- OVERIGEADRESSEERBAAROBJECTAANDUIDING (many-to-many junction, Connector_ID: 2280)

ALTER TABLE KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG ADD CONSTRAINT FK_KP_OVRGDRSSRBRBJCTNDDNG_NMMRNDDNG_2 FOREIGN KEY (NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- NUMMERAANDUIDING (many-to-many junction, Connector_ID: 2280)

ALTER TABLE OVERIGBENOEMDTERREIN ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_HEEFT_ALS_OFFICIEEL_ADRES FOREIGN KEY (HEEFT_ALS_OFFICIEEL_ADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_OFFICIEEL_ADRES (0..1 to 1, Connector_ID: 1952)

ALTER TABLE OVERIGGEBOUWDOBJECT ADD CONSTRAINT FK_OVERIGGEBOUWDOBJECT_HEEFT_ALS_OFFICIEEL_ADRES FOREIGN KEY (HEEFT_ALS_OFFICIEEL_ADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_OFFICIEEL_ADRES (0..1 to 0..1, Connector_ID: 1953)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY (LIGT_AAN_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- LIGT_AAN (0..* to 1, Connector_ID: 2281)

