CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        ADRESSEERBAAROBJECT_SELF_ID VARCHAR2(255),
        HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID VARCHAR2(255),
        HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID VARCHAR2(255),
        HEEFT_WINKELVLOEROPPERVLAK_ID VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        TYPEADRESSEERBAAROBJECT VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE BUURT (
    BUURT_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        CODE VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(255),
        LIGT_IN_WIJK_ID VARCHAR2(255),
        NAAM VARCHAR2(255),
        STATUS VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE GEBIED (
    GEBIED_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDBUURT DATE,
        DATUMEINDEGELDIGHEIDGEBIED DATE,
        GEBIEDCODE VARCHAR2(255),
        GEBIEDSOORT VARCHAR2(80),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIEIMGEOBRT VARCHAR2(255),
        KOMT_OVEREEN_BUURT_ID VARCHAR2(255),
        NAAM VARCHAR2(255)
);

CREATE TABLE KP_NMMRNDDNG (
    KP_NMMRNDDNG_ID VARCHAR2(255) PRIMARY KEY,
    NUMMERAANDUIDING_ID VARCHAR2(255),
    GEBIED_ID VARCHAR2(255)
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDEGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HEEFT_ALS_LOCATIE_ADRES_VESTIGING_ID VARCHAR2(255),
        HUISLETTER VARCHAR2(255),
        HUISNUMMER VARCHAR2(255),
        HUISNUMMERTOEVOEGING VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        LIGT_AAN_OPENBARERUIMTE_ID VARCHAR2(255),
        LIGT_IN_BUURT_ID VARCHAR2(255),
        POSTCODE VARCHAR2(255),
        STATUS VARCHAR2(255),
        TYPEADRESSEERBAAROBJECT VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE OPENBARERUIMTE (
    OPENBARERUIMTE_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS VARCHAR2(255),
        HUISNUMMERRANGE_EVEN_NUMMERS VARCHAR2(255),
        HUISNUMMERRANGE_ONEVEN_NUMMERS VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        LABELNAAM VARCHAR2(80),
        LIGT_IN_BUURT_ID VARCHAR2(255),
        NAAMOPENBARERUIMTE VARCHAR2(80),
        STATUS VARCHAR2(255),
        STRAATCODE VARCHAR2(80),
        STRAATNAAM VARCHAR2(255),
        TYPEOPENBARERUIMTE VARCHAR2(255),
        VERSIE NUMBER,
        WEGSEGMENT VARCHAR2(255)
);

CREATE TABLE VERBLIJFSOBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        AANTALKAMERS VARCHAR2(255),
        BEGINGELDIGHEID DATE,
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDGELDIGHEID DATE,
        GEBRUIKSDOEL VARCHAR2(255),
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HOOGSTEBOUWLAAG VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        LAAGSTEBOUWLAAG VARCHAR2(255),
        ONTSLUITINGVERDIEPING VARCHAR2(255),
        OPPERVLAKTE NUMBER,
        SOORTWOONOBJECT VARCHAR2(255),
        STATUS VARCHAR2(255),
        TOEGANGBOUWLAAG VARCHAR2(255),
        VERBLIJFSOBJECT_SELF_ID VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE VESTIGING (
    VESTIGING_ID VARCHAR2(255) PRIMARY KEY,
        COMMERCIELEVESTIGING NUMBER(1),
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMVOORTZETTING DATE,
        FULLTIMEWERKZAMEMANNEN VARCHAR2(255),
        FULLTIMEWERKZAMEVROUWEN VARCHAR2(255),
        HANDELSNAAM VARCHAR2(255),
        HEEFT_HOOFDLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID VARCHAR2(255),
        HEEFT_NEVENLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID VARCHAR2(255),
        PARTTIMEWERKZAMEMANNEN VARCHAR2(255),
        PARTTIMEWERKZAMEVROUWEN VARCHAR2(255),
        TOEVOEGINGADRES VARCHAR2(100),
        TOTAALWERKZAMEPERSONEN VARCHAR2(255),
        VERKORTENAAM VARCHAR2(255),
        VESTIGINGSNUMMER VARCHAR2(255)
);

CREATE TABLE WIJK (
    WIJK_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(255),
        STATUS VARCHAR2(255),
        VERSIE NUMBER,
        WIJKCODE VARCHAR2(255),
        WIJKNAAM VARCHAR2(255)
);

CREATE TABLE WINKELVLOEROPPERVLAK (
    WINKELVLOEROPPERVLAK_ID VARCHAR2(255) PRIMARY KEY,
        AANTALKASSA NUMBER,
        BRONWVO VARCHAR2(255),
        LEEGSTAND NUMBER(1),
        WINKELVLOEROPPERVLAKTE NUMBER,
        WVOKLASSE VARCHAR2(255)
);

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE KP_NMMRNDDNG ADD CONSTRAINT FK_KP_NMMRNDDNG_1 FOREIGN KEY (NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- NUMMERAANDUIDING (many-to-many junction, Connector_ID: 353)

ALTER TABLE KP_NMMRNDDNG ADD CONSTRAINT FK_KP_NMMRNDDNG_2 FOREIGN KEY (GEBIED_ID) REFERENCES GEBIED (GEBIED_ID);
-- GEBIED (many-to-many junction, Connector_ID: 353)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- unnamed (None to None, Connector_ID: 1540)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT FOREIGN KEY (HEEFT_WINKELVLOEROPPERVLAK_ID) REFERENCES WINKELVLOEROPPERVLAK (WINKELVLOEROPPERVLAK_ID);
-- HEEFT (1 to 0..1, Connector_ID: 1250)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 350)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 347)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_LIGT_IN FOREIGN KEY (LIGT_IN_WIJK_ID) REFERENCES WIJK (WIJK_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 346)

ALTER TABLE GEBIED ADD CONSTRAINT FK_GEBIED_KOMT_OVEREEN FOREIGN KEY (KOMT_OVEREEN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- KOMT_OVEREEN (0..1 to 0..1, Connector_ID: 345)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_HEEFT_ALS_LOCATIE_ADRES FOREIGN KEY (HEEFT_ALS_LOCATIE_ADRES_VESTIGING_ID) REFERENCES VESTIGING (VESTIGING_ID);
-- HEEFT_ALS_LOCATIE_ADRES (1 to 0..*, Connector_ID: 355)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY (LIGT_AAN_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- LIGT_AAN (0..* to 1, Connector_ID: 354)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_IN FOREIGN KEY (LIGT_IN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- LIGT_IN (1 to 1, Connector_ID: 1538)

ALTER TABLE OPENBARERUIMTE ADD CONSTRAINT FK_OPENBARERUIMTE_LIGT_IN FOREIGN KEY (LIGT_IN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- LIGT_IN (1 to 1..*, Connector_ID: 343)

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_VERBLIJFSOBJECT FOREIGN KEY (VERBLIJFSOBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- unnamed (None to None, Connector_ID: 1546)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_HEEFT_HOOFDLOCATIE_IN_OF_OP FOREIGN KEY (HEEFT_HOOFDLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_HOOFDLOCATIE_IN_OF_OP (0..* to 0..1, Connector_ID: 332)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_HEEFT_NEVENLOCATIE_IN_OF_OP FOREIGN KEY (HEEFT_NEVENLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_NEVENLOCATIE_IN_OF_OP (0..* to 0..1, Connector_ID: 333)

