CREATE TABLE INKOMENSVOORZIENING (
    INKOMENSVOORZIENING_ID NUMBER PRIMARY KEY,
    ADMINISTRATIEVEEINDDATUM DATE,
    ADMINISTRATIEVESTARTDATUM DATE,
    BEDRAG NUMBER(10,2),
    BETALINGSMOMENTCODE VARCHAR2(255),
    CODE VARCHAR2(255),
    DATUMTOEKENNING DATE,
    EENMALIG NUMBER(1),
    EINDDATUM DATE,
    GROEP VARCHAR2(255),
    INDICATIEBLOKKERING NUMBER(1),
    INDICATIESTUDIETOESLAG NUMBER(1),
    INDICATIEUITKERINGSPLITSEN NUMBER(1),
    INDICATIEUITKERINGSSPECIFICATIE NUMBER(1),
    INGANGSDATUM DATE,
    IS_OPGEBOUWD_UIT_COMPONENT_ID NUMBER,
    TOEKENNINGSDATUM DATE,
    VERSTERKKINGSVORM VARCHAR2(255),
    VERWERKTTOTENMETDATUM DATE
);

CREATE TABLE COMPONENT (
    COMPONENT_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2),
    BEGINDATUMBETREKKINGOP DATE,
    DEBETCREDIT VARCHAR2(255),
    EINDATUMBETREKKINGOP DATE,
    GROEP VARCHAR2(255),
    GROEPCODE VARCHAR2(255),
    GROOTBOEKCODE VARCHAR2(255),
    GROOTBOEKOMSCHRIJVING VARCHAR2(255),
    HEEFT_UITKERINGSRUN_ID NUMBER,
    IS_VAN_SOORT_COMPONENTSOORT_ID NUMBER,
    KOSTENPLAATS NUMBER(10,2),
    OMSCHRIJVING VARCHAR2(255),
    REKENINGNUMMER VARCHAR2(255),
    TOELICHTING VARCHAR2(255)
);

CREATE TABLE INKOMENSVOORZIENINGSOORT (
    INKOMENSVOORZIENINGSOORT_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(255),
    IS_SOORT_VOORZIENING_INKOMENSVOORZIENING_ID NUMBER,
    NAAM VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(255),
    REGELING VARCHAR2(255),
    REGELINGSCODE VARCHAR2(255),
    VERGOEDING VARCHAR2(255),
    VERGOEDINGSCODE VARCHAR2(255),
    WET VARCHAR2(255)
);

CREATE TABLE CLIENT (
    CLIENT_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(80),
    GEZAGSDRAGERGEKEND NUMBER(1),
    HEEFT_REGELING_REGELING_ID NUMBER,
    HEEFT_VOORZIENING_INKOMENSVOORZIENING_ID NUMBER,
    IS_PARTNER_VAN_INKOMENSVOORZIENING_ID NUMBER,
    JURIDISCHESTATUS VARCHAR2(80),
    WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE COMPONENTSOORT (
    COMPONENTSOORT_ID NUMBER PRIMARY KEY,
    COMPONENTCODE VARCHAR2(255),
    KOLOM VARCHAR2(255),
    KOLOMCODE VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(255),
    REGELING VARCHAR2(255),
    REGELINGCODE VARCHAR2(255)
);

CREATE TABLE REGELING (
    REGELING_ID NUMBER PRIMARY KEY,
    EINDDATUM DATE,
    IS_REGELINGSOORT_REGELINGSOORT_ID NUMBER,
    OMSCHRIJVING VARCHAR2(255),
    STARTDATUM DATE,
    TOEKENNINGSDATUM DATE
);

CREATE TABLE UITKERINGSRUN (
    UITKERINGSRUN_ID NUMBER PRIMARY KEY,
    DATUMRUN DATE,
    FREQUENTIE VARCHAR2(255),
    PERIODERUN VARCHAR2(255),
    SOORTRUN VARCHAR2(255)
);

CREATE TABLE REGELINGSOORT (
    REGELINGSOORT_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(255)
);

CREATE TABLE KP_CLNT_INKMNSVRZNNG (
    KP_CLNT_INKMNSVRZNNG_ID NUMBER PRIMARY KEY,
    CLIENT_ID NUMBER,
    INKOMENSVOORZIENING_ID NUMBER
);

ALTER TABLE KP_CLNT_INKMNSVRZNNG ADD CONSTRAINT FK_KP_CLNT_INKMNSVRZNNG_1 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- CLIENT (many-to-many junction, Connector_ID: 1707)

ALTER TABLE KP_CLNT_INKMNSVRZNNG ADD CONSTRAINT FK_KP_CLNT_INKMNSVRZNNG_2 FOREIGN KEY (INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- INKOMENSVOORZIENING (many-to-many junction, Connector_ID: 1707)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT_REGELING FOREIGN KEY (HEEFT_REGELING_REGELING_ID) REFERENCES REGELING (REGELING_ID);
-- HEEFT_REGELING (1 to 0..*, Connector_ID: 1701)

ALTER TABLE REGELING ADD CONSTRAINT FK_REGELING_IS_REGELINGSOORT FOREIGN KEY (IS_REGELINGSOORT_REGELINGSOORT_ID) REFERENCES REGELINGSOORT (REGELINGSOORT_ID);
-- IS_REGELINGSOORT (0..* to 1, Connector_ID: 1703)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT_VOORZIENING FOREIGN KEY (HEEFT_VOORZIENING_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- HEEFT_VOORZIENING (1 to 1, Connector_ID: 1704)

ALTER TABLE INKOMENSVOORZIENINGSOORT ADD CONSTRAINT FK_INKOMENSVOORZIENINGSOORT_IS_SOORT_VOORZIENING FOREIGN KEY (IS_SOORT_VOORZIENING_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- IS_SOORT_VOORZIENING (1 to 0..*, Connector_ID: 1705)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_IS_PARTNER_VAN FOREIGN KEY (IS_PARTNER_VAN_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- IS_PARTNER_VAN (0 to 1, Connector_ID: 1709)

ALTER TABLE INKOMENSVOORZIENING ADD CONSTRAINT FK_INKOMENSVOORZIENING_IS_OPGEBOUWD_UIT FOREIGN KEY (IS_OPGEBOUWD_UIT_COMPONENT_ID) REFERENCES COMPONENT (COMPONENT_ID);
-- IS_OPGEBOUWD_UIT (1 to 1..*, Connector_ID: 1714)

ALTER TABLE COMPONENT ADD CONSTRAINT FK_COMPONENT_HEEFT FOREIGN KEY (HEEFT_UITKERINGSRUN_ID) REFERENCES UITKERINGSRUN (UITKERINGSRUN_ID);
-- HEEFT (1..* to 1, Connector_ID: 1715)

ALTER TABLE COMPONENT ADD CONSTRAINT FK_COMPONENT_IS_VAN_SOORT FOREIGN KEY (IS_VAN_SOORT_COMPONENTSOORT_ID) REFERENCES COMPONENTSOORT (COMPONENTSOORT_ID);
-- IS_VAN_SOORT (1..* to 1, Connector_ID: 1716)

