CREATE TABLE `REDEN_AANVRAAG` (
    `REDEN_AANVRAAG_ID` INT PRIMARY KEY,
    `DIENSTTYPE` VARCHAR(255),
    `GEWENSTE_INGANGSDATUM` DATE
) ENGINE=InnoDB;

CREATE TABLE `KOSTENPLAATS` (
    `KOSTENPLAATS_ID` INT PRIMARY KEY,
    `BTWCODE` VARCHAR(255),
    `BTWOMSCHRIJVING` VARCHAR(80),
    `KOSTENPLAATSSOORTCODE` DECIMAL(10,2),
    `KOSTENPLAATSSOORTOMSCHRIJVING` DECIMAL(10,2),
    `KOSTENPLAATSTYPECODE` DECIMAL(10,2),
    `KOSTENPLAATSTYPEOMSCHRIJVING` DECIMAL(10,2),
    `NAAM` VARCHAR(80),
    `OMSCHRIJVING` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `DIENST` (
    `DIENST_ID` INT PRIMARY KEY,
    `AANTAL_KOSTENDELERS` DECIMAL(10,2),
    `BEGINDATUM` DATE,
    `EINDDATUM` DATE,
    `PERIODICITEIT_STATUSFORMULIER` VARCHAR(255),
    `STARTDATUM_STATUSFORMULIER` DATE
) ENGINE=InnoDB;

CREATE TABLE `NORMAFWIJKING` (
    `NORMAFWIJKING_ID` INT PRIMARY KEY,
    `DATUM_VASTSTELLING_NORMAFWIJKING` DATE,
    `DATUM_VASTSTELLING_VERWIJTBAARHEID` DATE,
    `IDENTIFICATIE` DATE,
    `MOTIVATIE_VERWIJTBAARHEID` DATE,
    `RECIDIVE` VARCHAR(255),
    `TYPE_NORMAFWIJKING` VARCHAR(255),
    `VERWIJTBAARHEID` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `AANVRAAG` (
    `AANVRAAG_ID` INT PRIMARY KEY,
    `AANVRAAGDATUM` DATE,
    `CODE_ONTVANGENDE_GEMEENTE` DATE
) ENGINE=InnoDB;

CREATE TABLE `LEVERINGSCOMPONENT` (
    `LEVERINGSCOMPONENT_ID` INT PRIMARY KEY,
    `BEDRAG` DECIMAL(10,2),
    `EINDDATUM` DATE,
    `GEVALSRUBRIEK` VARCHAR(255),
    `HEEFT_KOSTENPLAATS_ID` INT,
    `OMSCHRIJVING_AFWIJKING` VARCHAR(255),
    `PERCENTAGE` VARCHAR(255),
    `PERIODE_STARTDATUM` DATE,
    `SOORT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `PROFIEL` (
    `PROFIEL_ID` INT PRIMARY KEY,
    `BEVAT_REDEN_AANVRAAG_ID` INT,
    `DATUMAANVANGPROFIEL` DATE,
    `DATUMEINDEPROFIEL` DATE,
    `PROFIELTYPE` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `LEVERINGSSPECIFICATIE` (
    `LEVERINGSSPECIFICATIE_ID` INT PRIMARY KEY,
    `BESTAAT_UIT_LEVERINGSCOMPONENT_ID` INT,
    `PERIODE_EINDDATUM` DATE,
    `PERIODE_STARTDATUM` DATE,
    `PERIODICITEIT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `CLIENT` (
    `CLIENT_ID` INT PRIMARY KEY,
    `CODE` VARCHAR(80),
    `DOET_AANVRAAG_AANVRAAG_ID` INT,
    `GEZAGSDRAGERGEKEND` BOOLEAN,
    `HEEFT_PROFIEL_ID` INT,
    `JURIDISCHESTATUS` VARCHAR(80),
    `NEEMT_DIENST_AF_DIENST_ID` INT,
    `VEROORZAAKT_NORMAFWIJKING_ID` INT,
    `WETTELIJKEVERTEGENWOORDIGING` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `LEVERINGSOPDRACHT` (
    `LEVERINGSOPDRACHT_ID` INT PRIMARY KEY,
    `BESTAAT_UIT_LEVERINGSSPECIFICATIE_ID` INT,
    `IN_KADER_VAN_DIENST_ID` INT,
    `LEVERINGSKANAAL` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `DEBITEUR` (
    `DEBITEUR_ID` INT PRIMARY KEY,
    `EIGEN_KENMERK` VARCHAR(255),
    `OPVOERDATUM` DATE,
    `SOORT_DEBITEUR` VARCHAR(255),
    `VERWIJST_CLIENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `TERUGVORDERINGSVERZOEK` (
    `TERUGVORDERINGSVERZOEK_ID` INT PRIMARY KEY,
    `AANMAAKDATUM` DATE,
    `BEHANDELSTATUS_VERZOEK` VARCHAR(255),
    `BETREFT_CLIENT_ID` INT,
    `CATEGORIE` VARCHAR(255),
    `FISCAAL` VARCHAR(255),
    `PERIODE_EINDDATUM` DATE,
    `PERIODE_STARTDATUM` DATE,
    `PRIOTYPE` DATE,
    `REGELING` VARCHAR(255),
    `SUBCATEGORIE` VARCHAR(255),
    `TERUGVORDERINGSVERZOEK_BETREFT_DIENST_DIENST_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `CLIENT` ADD CONSTRAINT FK_CLIENT_HEEFT FOREIGN KEY (`HEEFT_PROFIEL_ID`) REFERENCES `PROFIEL` (`PROFIEL_ID`);
-- HEEFT (1 to 1..*, Connector_ID: 947)

ALTER TABLE `TERUGVORDERINGSVERZOEK` ADD CONSTRAINT FK_TERUGVORDERINGSVERZOEK_BETREFT FOREIGN KEY (`BETREFT_CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`);
-- BETREFT (0..* to 1..2, Connector_ID: 1636)

ALTER TABLE `DEBITEUR` ADD CONSTRAINT FK_DEBITEUR_VERWIJST FOREIGN KEY (`VERWIJST_CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`);
-- VERWIJST (0..1 to 1, Connector_ID: 1655)

ALTER TABLE `PROFIEL` ADD CONSTRAINT FK_PROFIEL_BEVAT FOREIGN KEY (`BEVAT_REDEN_AANVRAAG_ID`) REFERENCES `REDEN_AANVRAAG` (`REDEN_AANVRAAG_ID`);
-- BEVAT (1 to 0..1, Connector_ID: 1678)

ALTER TABLE `CLIENT` ADD CONSTRAINT FK_CLIENT_VEROORZAAKT FOREIGN KEY (`VEROORZAAKT_NORMAFWIJKING_ID`) REFERENCES `NORMAFWIJKING` (`NORMAFWIJKING_ID`);
-- VEROORZAAKT (1 to 0..*, Connector_ID: 1695)

ALTER TABLE `LEVERINGSOPDRACHT` ADD CONSTRAINT FK_LEVERINGSOPDRACHT_BESTAAT_UIT FOREIGN KEY (`BESTAAT_UIT_LEVERINGSSPECIFICATIE_ID`) REFERENCES `LEVERINGSSPECIFICATIE` (`LEVERINGSSPECIFICATIE_ID`);
-- BESTAAT_UIT (1..* to 1..1, Connector_ID: 1722)

ALTER TABLE `LEVERINGSSPECIFICATIE` ADD CONSTRAINT FK_LEVERINGSSPECIFICATIE_BESTAAT_UIT FOREIGN KEY (`BESTAAT_UIT_LEVERINGSCOMPONENT_ID`) REFERENCES `LEVERINGSCOMPONENT` (`LEVERINGSCOMPONENT_ID`);
-- BESTAAT_UIT (1..* to 1..1, Connector_ID: 1724)

ALTER TABLE `LEVERINGSCOMPONENT` ADD CONSTRAINT FK_LEVERINGSCOMPONENT_HEEFT FOREIGN KEY (`HEEFT_KOSTENPLAATS_ID`) REFERENCES `KOSTENPLAATS` (`KOSTENPLAATS_ID`);
-- HEEFT (0..* to 0..1, Connector_ID: 1726)

ALTER TABLE `CLIENT` ADD CONSTRAINT FK_CLIENT_NEEMT_DIENST_AF FOREIGN KEY (`NEEMT_DIENST_AF_DIENST_ID`) REFERENCES `DIENST` (`DIENST_ID`);
-- NEEMT_DIENST_AF (1..2 to 0..*, Connector_ID: 1733)

ALTER TABLE `LEVERINGSOPDRACHT` ADD CONSTRAINT FK_LEVERINGSOPDRACHT_IN_KADER_VAN FOREIGN KEY (`IN_KADER_VAN_DIENST_ID`) REFERENCES `DIENST` (`DIENST_ID`);
-- IN_KADER_VAN (1..1 to 1..*, Connector_ID: 1735)

ALTER TABLE `TERUGVORDERINGSVERZOEK` ADD CONSTRAINT FK_TERUGVORDERINGSVERZOEK_TERUGVORDERINGSVERZOEK_BETREFT_DIENST FOREIGN KEY (`TERUGVORDERINGSVERZOEK_BETREFT_DIENST_DIENST_ID`) REFERENCES `DIENST` (`DIENST_ID`);
-- TERUGVORDERINGSVERZOEK_BETREFT_DIENST (1..1 to 0..*, Connector_ID: 1736)

ALTER TABLE `CLIENT` ADD CONSTRAINT FK_CLIENT_DOET_AANVRAAG FOREIGN KEY (`DOET_AANVRAAG_AANVRAAG_ID`) REFERENCES `AANVRAAG` (`AANVRAAG_ID`);
-- DOET_AANVRAAG (1 to 0..*, Connector_ID: 1745)

