CREATE TABLE INKOMENSVOORZIENING (
    INKOMENSVOORZIENING_ID NUMBER PRIMARY KEY,
    ADMINISTRATIEVEEINDDATUM DATE,
    ADMINISTRATIEVESTARTDATUM DATE,
    BEDRAG NUMBER(10,2),
    BETALINGSMOMENTCODE VARCHAR2(255),
    CODE VARCHAR2(255),
    DATUMTOEKENNING DATE,
    EENMALIG NUMBER(1),
    EINDDATUM DATE,
    GROEP VARCHAR2(255),
    INDICATIEBLOKKERING NUMBER(1),
    INDICATIESTUDIETOESLAG NUMBER(1),
    INDICATIEUITKERINGSPLITSEN NUMBER(1),
    INDICATIEUITKERINGSSPECIFICATIE NUMBER(1),
    INGANGSDATUM DATE,
    TOEKENNINGSDATUM DATE,
    VERSTERKKINGSVORM VARCHAR2(255),
    VERWERKTTOTENMETDATUM DATE
);

CREATE TABLE REDENINSTROOM (
    REDENINSTROOM_ID NUMBER PRIMARY KEY,
    BEGINDATUMGELDIGHEID DATE,
    CBS_CODE VARCHAR2(255),
    CBS_OMSCHRIJVING VARCHAR2(255),
    EINDDATUMGELDIGHEID DATE,
    OMSCHRIJVING VARCHAR2(255),
    REDENINSTROOMCODE VARCHAR2(255),
    REDENINSTROOM_INKOMENSVOORZIENING_ID NUMBER
);

CREATE TABLE HUISVESTINGSOORT (
    HUISVESTINGSOORT_ID NUMBER PRIMARY KEY,
    BEGINDATUMGELDIGHEID DATE,
    EINDDATUMGELDIGHEID DATE,
    OMSCHRIJVING VARCHAR2(255),
    SOORTHUISVESTINGCODE VARCHAR2(255),
    SOORTHUISVESTING_INKOMENSVOORZIENING_ID NUMBER
);

CREATE TABLE REDENBLOKKERING (
    REDENBLOKKERING_ID NUMBER PRIMARY KEY,
    BEGINDATUMGELDIGHEID DATE,
    EINDDATUMGELDIGHEID DATE,
    OMSCHRIJVING VARCHAR2(255),
    REDENBLOKKERINGCODE VARCHAR2(255),
    REDENBLOKKERING_INKOMENSVOORZIENING_ID NUMBER
);

CREATE TABLE REDENUITSTROOM (
    REDENUITSTROOM_ID NUMBER PRIMARY KEY,
    BEGINDATUMGELDIGHEID DATE,
    CBS_CODE VARCHAR2(255),
    CBS_OMSCHRIJVING VARCHAR2(255),
    EINDDATUMGELDIGHEID DATE,
    OMSCHRIJVING VARCHAR2(255),
    REDENUITSTROOMCODE VARCHAR2(255),
    REDENUITSTROOM_INKOMENSVOORZIENING_ID NUMBER
);

ALTER TABLE REDENBLOKKERING ADD CONSTRAINT FK_REDENBLOKKERING_REDENBLOKKERING FOREIGN KEY (REDENBLOKKERING_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- REDENBLOKKERING (1 to 0..*, Connector_ID: 1710)

ALTER TABLE REDENINSTROOM ADD CONSTRAINT FK_REDENINSTROOM_REDENINSTROOM FOREIGN KEY (REDENINSTROOM_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- REDENINSTROOM (1 to 1..*, Connector_ID: 1711)

ALTER TABLE REDENUITSTROOM ADD CONSTRAINT FK_REDENUITSTROOM_REDENUITSTROOM FOREIGN KEY (REDENUITSTROOM_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- REDENUITSTROOM (1 to 0..*, Connector_ID: 1712)

ALTER TABLE HUISVESTINGSOORT ADD CONSTRAINT FK_HUISVESTINGSOORT_SOORTHUISVESTING FOREIGN KEY (SOORTHUISVESTING_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- SOORTHUISVESTING (1 to 0..*, Connector_ID: 1713)

