CREATE TABLE [INKOMENSVOORZIENING] (
    [INKOMENSVOORZIENING_ID] INT PRIMARY KEY,
    [ADMINISTRATIEVEEINDDATUM] DATE,
    [ADMINISTRATIEVESTARTDATUM] DATE,
    [BEDRAG] DECIMAL(10,2),
    [BETALINGSMOMENTCODE] VARCHAR(255),
    [CODE] VARCHAR(255),
    [DATUMTOEKENNING] DATE,
    [EENMALIG] BIT,
    [EINDDATUM] DATE,
    [GROEP] VARCHAR(255),
    [INDICATIEBLOKKERING] BIT,
    [INDICATIESTUDIETOESLAG] BIT,
    [INDICATIEUITKERINGSPLITSEN] BIT,
    [INDICATIEUITKERINGSSPECIFICATIE] BIT,
    [INGANGSDATUM] DATE,
    [TOEKENNINGSDATUM] DATE,
    [VERSTERKKINGSVORM] VARCHAR(255),
    [VERWERKTTOTENMETDATUM] DATE
);

CREATE TABLE [REDENINSTROOM] (
    [REDENINSTROOM_ID] INT PRIMARY KEY,
    [BEGINDATUMGELDIGHEID] DATE,
    [CBS_CODE] VARCHAR(255),
    [CBS_OMSCHRIJVING] VARCHAR(255),
    [EINDDATUMGELDIGHEID] DATE,
    [OMSCHRIJVING] VARCHAR(255),
    [REDENINSTROOMCODE] VARCHAR(255),
    [REDENINSTROOM_INKOMENSVOORZIENING_ID] INT
);

CREATE TABLE [HUISVESTINGSOORT] (
    [HUISVESTINGSOORT_ID] INT PRIMARY KEY,
    [BEGINDATUMGELDIGHEID] DATE,
    [EINDDATUMGELDIGHEID] DATE,
    [OMSCHRIJVING] VARCHAR(255),
    [SOORTHUISVESTINGCODE] VARCHAR(255),
    [SOORTHUISVESTING_INKOMENSVOORZIENING_ID] INT
);

CREATE TABLE [REDENBLOKKERING] (
    [REDENBLOKKERING_ID] INT PRIMARY KEY,
    [BEGINDATUMGELDIGHEID] DATE,
    [EINDDATUMGELDIGHEID] DATE,
    [OMSCHRIJVING] VARCHAR(255),
    [REDENBLOKKERINGCODE] VARCHAR(255),
    [REDENBLOKKERING_INKOMENSVOORZIENING_ID] INT
);

CREATE TABLE [REDENUITSTROOM] (
    [REDENUITSTROOM_ID] INT PRIMARY KEY,
    [BEGINDATUMGELDIGHEID] DATE,
    [CBS_CODE] VARCHAR(255),
    [CBS_OMSCHRIJVING] VARCHAR(255),
    [EINDDATUMGELDIGHEID] DATE,
    [OMSCHRIJVING] VARCHAR(255),
    [REDENUITSTROOMCODE] VARCHAR(255),
    [REDENUITSTROOM_INKOMENSVOORZIENING_ID] INT
);

ALTER TABLE [REDENBLOKKERING] ADD CONSTRAINT FK_REDENBLOKKERING_REDENBLOKKERING FOREIGN KEY ([REDENBLOKKERING_INKOMENSVOORZIENING_ID]) REFERENCES [INKOMENSVOORZIENING] ([INKOMENSVOORZIENING_ID]);
-- REDENBLOKKERING (1 to 0..*, Connector_ID: 1710)

ALTER TABLE [REDENINSTROOM] ADD CONSTRAINT FK_REDENINSTROOM_REDENINSTROOM FOREIGN KEY ([REDENINSTROOM_INKOMENSVOORZIENING_ID]) REFERENCES [INKOMENSVOORZIENING] ([INKOMENSVOORZIENING_ID]);
-- REDENINSTROOM (1 to 1..*, Connector_ID: 1711)

ALTER TABLE [REDENUITSTROOM] ADD CONSTRAINT FK_REDENUITSTROOM_REDENUITSTROOM FOREIGN KEY ([REDENUITSTROOM_INKOMENSVOORZIENING_ID]) REFERENCES [INKOMENSVOORZIENING] ([INKOMENSVOORZIENING_ID]);
-- REDENUITSTROOM (1 to 0..*, Connector_ID: 1712)

ALTER TABLE [HUISVESTINGSOORT] ADD CONSTRAINT FK_HUISVESTINGSOORT_SOORTHUISVESTING FOREIGN KEY ([SOORTHUISVESTING_INKOMENSVOORZIENING_ID]) REFERENCES [INKOMENSVOORZIENING] ([INKOMENSVOORZIENING_ID]);
-- SOORTHUISVESTING (1 to 0..*, Connector_ID: 1713)

