CREATE TABLE REDENINSTROOM (
    REDENINSTROOM_ID NUMBER PRIMARY KEY,
    BEGINDATUMGELDIGHEID DATE,
    CBS_CODE VARCHAR2(255),
    CBS_OMSCHRIJVING VARCHAR2(255),
    EINDDATUMGELDIGHEID DATE,
    OMSCHRIJVING VARCHAR2(255),
    REDENINSTROOMCODE VARCHAR2(255)
);

CREATE TABLE REDENUITSTROOM (
    REDENUITSTROOM_ID NUMBER PRIMARY KEY,
    BEGINDATUMGELDIGHEID DATE,
    CBS_CODE VARCHAR2(255),
    CBS_OMSCHRIJVING VARCHAR2(255),
    EINDDATUMGELDIGHEID DATE,
    OMSCHRIJVING VARCHAR2(255),
    REDENUITSTROOMCODE VARCHAR2(255)
);

CREATE TABLE HUISVESTINGSOORT (
    HUISVESTINGSOORT_ID NUMBER PRIMARY KEY,
    BEGINDATUMGELDIGHEID DATE,
    EINDDATUMGELDIGHEID DATE,
    OMSCHRIJVING VARCHAR2(255),
    SOORTHUISVESTINGCODE VARCHAR2(255)
);

CREATE TABLE REDENBLOKKERING (
    REDENBLOKKERING_ID NUMBER PRIMARY KEY,
    BEGINDATUMGELDIGHEID DATE,
    EINDDATUMGELDIGHEID DATE,
    OMSCHRIJVING VARCHAR2(255),
    REDENBLOKKERINGCODE VARCHAR2(255)
);

CREATE TABLE INKOMENSVOORZIENING (
    INKOMENSVOORZIENING_ID NUMBER PRIMARY KEY,
    ADMINISTRATIEVEEINDDATUM DATE,
    ADMINISTRATIEVESTARTDATUM DATE,
    BEDRAG NUMBER(10,2),
    BETALINGSMOMENTCODE VARCHAR2(255),
    CODE VARCHAR2(255),
    DATUMTOEKENNING DATE,
    EENMALIG NUMBER(1),
    EINDDATUM DATE,
    GROEP VARCHAR2(255),
    INDICATIEBLOKKERING NUMBER(1),
    INDICATIESTUDIETOESLAG NUMBER(1),
    INDICATIEUITKERINGSPLITSEN NUMBER(1),
    INDICATIEUITKERINGSSPECIFICATIE NUMBER(1),
    INGANGSDATUM DATE,
    REDENBLOKKERING_REDENBLOKKERING_ID NUMBER,
    REDENINSTROOM_REDENINSTROOM_ID NUMBER,
    REDENUITSTROOM_REDENUITSTROOM_ID NUMBER,
    SOORTHUISVESTING_HUISVESTINGSOORT_ID NUMBER,
    TOEKENNINGSDATUM DATE,
    VERSTERKKINGSVORM VARCHAR2(255),
    VERWERKTTOTENMETDATUM DATE
);

ALTER TABLE INKOMENSVOORZIENING ADD CONSTRAINT FK_INKOMENSVOORZIENING_REDENBLOKKERING FOREIGN KEY (REDENBLOKKERING_REDENBLOKKERING_ID) REFERENCES REDENBLOKKERING (REDENBLOKKERING_ID);
-- REDENBLOKKERING (1 to 0..*, Connector_ID: 1710)

ALTER TABLE INKOMENSVOORZIENING ADD CONSTRAINT FK_INKOMENSVOORZIENING_REDENINSTROOM FOREIGN KEY (REDENINSTROOM_REDENINSTROOM_ID) REFERENCES REDENINSTROOM (REDENINSTROOM_ID);
-- REDENINSTROOM (1 to 1..*, Connector_ID: 1711)

ALTER TABLE INKOMENSVOORZIENING ADD CONSTRAINT FK_INKOMENSVOORZIENING_REDENUITSTROOM FOREIGN KEY (REDENUITSTROOM_REDENUITSTROOM_ID) REFERENCES REDENUITSTROOM (REDENUITSTROOM_ID);
-- REDENUITSTROOM (1 to 0..*, Connector_ID: 1712)

ALTER TABLE INKOMENSVOORZIENING ADD CONSTRAINT FK_INKOMENSVOORZIENING_SOORTHUISVESTING FOREIGN KEY (SOORTHUISVESTING_HUISVESTINGSOORT_ID) REFERENCES HUISVESTINGSOORT (HUISVESTINGSOORT_ID);
-- SOORTHUISVESTING (1 to 0..*, Connector_ID: 1713)

