CREATE TABLE `REDENINSTROOM` (
    `REDENINSTROOM_ID` INT PRIMARY KEY,
    `BEGINDATUMGELDIGHEID` DATE,
    `CBS_CODE` VARCHAR(255),
    `CBS_OMSCHRIJVING` VARCHAR(255),
    `EINDDATUMGELDIGHEID` DATE,
    `OMSCHRIJVING` VARCHAR(255),
    `REDENINSTROOMCODE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `REDENUITSTROOM` (
    `REDENUITSTROOM_ID` INT PRIMARY KEY,
    `BEGINDATUMGELDIGHEID` DATE,
    `CBS_CODE` VARCHAR(255),
    `CBS_OMSCHRIJVING` VARCHAR(255),
    `EINDDATUMGELDIGHEID` DATE,
    `OMSCHRIJVING` VARCHAR(255),
    `REDENUITSTROOMCODE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `HUISVESTINGSOORT` (
    `HUISVESTINGSOORT_ID` INT PRIMARY KEY,
    `BEGINDATUMGELDIGHEID` DATE,
    `EINDDATUMGELDIGHEID` DATE,
    `OMSCHRIJVING` VARCHAR(255),
    `SOORTHUISVESTINGCODE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `REDENBLOKKERING` (
    `REDENBLOKKERING_ID` INT PRIMARY KEY,
    `BEGINDATUMGELDIGHEID` DATE,
    `EINDDATUMGELDIGHEID` DATE,
    `OMSCHRIJVING` VARCHAR(255),
    `REDENBLOKKERINGCODE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `INKOMENSVOORZIENING` (
    `INKOMENSVOORZIENING_ID` INT PRIMARY KEY,
    `ADMINISTRATIEVEEINDDATUM` DATE,
    `ADMINISTRATIEVESTARTDATUM` DATE,
    `BEDRAG` DECIMAL(10,2),
    `BETALINGSMOMENTCODE` VARCHAR(255),
    `CODE` VARCHAR(255),
    `DATUMTOEKENNING` DATE,
    `EENMALIG` BOOLEAN,
    `EINDDATUM` DATE,
    `GROEP` VARCHAR(255),
    `INDICATIEBLOKKERING` BOOLEAN,
    `INDICATIESTUDIETOESLAG` BOOLEAN,
    `INDICATIEUITKERINGSPLITSEN` BOOLEAN,
    `INDICATIEUITKERINGSSPECIFICATIE` BOOLEAN,
    `INGANGSDATUM` DATE,
    `REDENBLOKKERING_REDENBLOKKERING_ID` INT,
    `REDENINSTROOM_REDENINSTROOM_ID` INT,
    `REDENUITSTROOM_REDENUITSTROOM_ID` INT,
    `SOORTHUISVESTING_HUISVESTINGSOORT_ID` INT,
    `TOEKENNINGSDATUM` DATE,
    `VERSTERKKINGSVORM` VARCHAR(255),
    `VERWERKTTOTENMETDATUM` DATE
) ENGINE=InnoDB;

ALTER TABLE `INKOMENSVOORZIENING` ADD CONSTRAINT FK_INKOMENSVOORZIENING_REDENBLOKKERING FOREIGN KEY (`REDENBLOKKERING_REDENBLOKKERING_ID`) REFERENCES `REDENBLOKKERING` (`REDENBLOKKERING_ID`);
-- REDENBLOKKERING (1 to 0..*, Connector_ID: 1710)

ALTER TABLE `INKOMENSVOORZIENING` ADD CONSTRAINT FK_INKOMENSVOORZIENING_REDENINSTROOM FOREIGN KEY (`REDENINSTROOM_REDENINSTROOM_ID`) REFERENCES `REDENINSTROOM` (`REDENINSTROOM_ID`);
-- REDENINSTROOM (1 to 1..*, Connector_ID: 1711)

ALTER TABLE `INKOMENSVOORZIENING` ADD CONSTRAINT FK_INKOMENSVOORZIENING_REDENUITSTROOM FOREIGN KEY (`REDENUITSTROOM_REDENUITSTROOM_ID`) REFERENCES `REDENUITSTROOM` (`REDENUITSTROOM_ID`);
-- REDENUITSTROOM (1 to 0..*, Connector_ID: 1712)

ALTER TABLE `INKOMENSVOORZIENING` ADD CONSTRAINT FK_INKOMENSVOORZIENING_SOORTHUISVESTING FOREIGN KEY (`SOORTHUISVESTING_HUISVESTINGSOORT_ID`) REFERENCES `HUISVESTINGSOORT` (`HUISVESTINGSOORT_ID`);
-- SOORTHUISVESTING (1 to 0..*, Connector_ID: 1713)

