CREATE TABLE AANDACHTSPUNT_ (
    AANDACHTSPUNT__ID VARCHAR(255) PRIMARY KEY,
        AANDACHTSPUNT_ENUM_ID VARCHAR(255),
        EINDDATUM DATE,
        STARTDATUM DATE,
        SUBDOEL_AANDACHTSPUNT_ID VARCHAR(255)
);

CREATE TABLE AANDACHTSPUNT_ENUM (
    AANDACHTSPUNT_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO AANDACHTSPUNT_ENUM (AANDACHTSPUNT_ENUM_ID, VALUE) VALUES
    (1, 'DIGITALE_VAARDIGHEDEN'),
    (2, 'FINANCIEN'),
    (3, 'JUSTITIE'),
    (4, 'LICHAAMELIJKE_GEZONDHEID'),
    (5, 'PSYCHISCHE_GEZONDHEID'),
    (6, 'TAAL'),
    (7, 'VERSLAVING'),
    (8, 'WOONSITUATIE'),
    (9, 'ZORGTAKEN');

CREATE TABLE AANVRAAG_VERLENGING_INBURGERINGSTERMIJN (
    AANVRAAG_VERLENGING_INBURGERINGSTERMIJN_ID VARCHAR(255) PRIMARY KEY,
        BEOORDELINGAANVRAAGVERLENGING_ENUM_ID VARCHAR(255),
        BEOORDELING_AANVRAAG_INBURGERINGSTERMIJN_ID VARCHAR(255),
        VERLENGINGSGROND VARCHAR(255),
        VERLENGINGSGROND_ID VARCHAR(255)
);

CREATE TABLE ASIELSTATUSHOUDER (
    NATUURLIJKPERSOON_ID VARCHAR(255) PRIMARY KEY,
        BEZIT_ICT_VAARDIGHEID_ID VARCHAR(255),
        DIGID_AANGEVRAAGD BOOLEAN,
        EMAILADRES_VERBLIJF_AZC VARCHAR(255),
        HEEFT_AANGEVRAAGD_DIPLOMAWAARDERING_ID VARCHAR(255),
        HEEFT_GEVOLGD_EDUCATIE_ID VARCHAR(255),
        HEEFT_GEVOLGD_TRAINING_ID VARCHAR(255),
        HEEFT_TAALVAARDIGHEID_ID VARCHAR(255),
        IS_GEKOPPELD_AAN VARCHAR(255),
        IS_GEKOPPELD_AAN__GEMEENTE_ID VARCHAR(255),
        LAND_RIJBEWIJS VARCHAR(50),
        NEEMT_DEEL_VOORBEREIDING_OP_INBURGERING_ID VARCHAR(255),
        RIJBEWIJS BOOLEAN,
        TELEFOONNUMMER_VERBLIJF_AZC VARCHAR(255),
        VERBLIJFT_VERBLIJFPLAATS_AZC_ID VARCHAR(255),
        WERK_ID VARCHAR(255)
);

CREATE TABLE B1_ROUTE (
    B1_ROUTE_ID VARCHAR(255) PRIMARY KEY,
        AANTALGRATISEXAMENPOGINGENTEGOED INTEGER,
        EXAMENDATUM DATE,
        GEVOLGDEURENPARTICIPATIETAALLES INTEGER,
        ONDERDEEL_VAN__LEERROUTE_ID VARCHAR(255),
        REDENGEENRESULTAAT VARCHAR(255),
        RESULTAAT INTEGER
);

CREATE TABLE BEOORDELINGAANVRAAGVERLENGING_ENUM (
    BEOORDELINGAANVRAAGVERLENGING_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO BEOORDELINGAANVRAAGVERLENGING_ENUM (BEOORDELINGAANVRAAGVERLENGING_ENUM_ID, VALUE) VALUES
    (1, 'NIETTOEGESTAAN'),
    (2, 'TOEGESTAAN');

CREATE TABLE BREDE_INTAKE (
    BREDE_INTAKE_ID VARCHAR(255) PRIMARY KEY,
        HEEFT_LEERROUTE_ID VARCHAR(255),
        ONDERDEEL_VAN_INBURGERINGSTRAJECT_ID VARCHAR(255)
);

CREATE TABLE CLASSIFICATIEARMTOTUITSTEKEND_ENUM (
    CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID, VALUE) VALUES
    (1, 'ARM'),
    (2, 'GOED'),
    (3, 'MIDDELMATIG'),
    (4, 'UITSTEKEND'),
    (5, 'VOLDOENDE');

CREATE TABLE CLASSIFICATIEVOLDOENDEONVOLDOENDE__ENUM (
    CLASSIFICATIEVOLDOENDEONVOLDOENDE__ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO CLASSIFICATIEVOLDOENDEONVOLDOENDE__ENUM (CLASSIFICATIEVOLDOENDEONVOLDOENDE__ENUM_ID, VALUE) VALUES
    (1, 'ONVOLDOENDE'),
    (2, 'VOLDOENDE');

CREATE TABLE DIPLOMAWAARDERING (
    DIPLOMAWAARDERING_ID VARCHAR(255) PRIMARY KEY,
        DIPLOMAWAARDERINGNEDERLANDSNIVEAU BOOLEAN,
        DIPLOMAWAARDERINGRICHTING_ENUM_ID VARCHAR(255),
        DIPLOMAWAARDERINGVOOR_ENUM_ID VARCHAR(255),
        NIVEAUCOMPETENTIE_ENUM_ID VARCHAR(255),
        WAARDERINGAANGEVRAAGD VARCHAR(255)
);

CREATE TABLE DOEL_ENUM (
    DOEL_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO DOEL_ENUM (DOEL_ENUM_ID, VALUE) VALUES
    (1, 'BETAALD_WERKEN'),
    (2, 'BETAAL_WERKEN_NAAR_VERMOGEN'),
    (3, 'MAATSCHAPPELIJK_FIT_WORDEN'),
    (4, 'ONDERNEMEN'),
    (5, 'OPLEIDING_MET_STUDIEFINANCIERING'),
    (6, 'WERKFIT_WORDEN');

CREATE TABLE EDUCATIE (
    EDUCATIE_ID VARCHAR(255) PRIMARY KEY,
        EDUCATIEDIPLOMA_ENUM_ID VARCHAR(255),
        EDUCATIEINBEZIT BOOLEAN,
        EDUCATIELAND VARCHAR(255),
        EDUCATIETOT DATE,
        EDUCATIEVAN DATE,
        OPLEIDING VARCHAR(255)
);

CREATE TABLE EXAMEN (
    EXAMEN_ID VARCHAR(255) PRIMARY KEY,
        AFGEROND_MET_INBURGERINGSTRAJECT_ID VARCHAR(255)
);

CREATE TABLE EXAMENONDERDEEL (
    EXAMENONDERDEEL_ID VARCHAR(255) PRIMARY KEY,
        EXAMEN_ID VARCHAR(255)
);

CREATE TABLE GEMEENTE (
    GEMEENTE_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDGEMEENTE DATE,
        DATUMEINDEGELDIGHEIDGEMEENTE DATE,
        GEMEENTECODE VARCHAR(255),
        GEMEENTEGEOMETRIE GEOMETRY,
        GEMEENTENAAM VARCHAR(80),
        GEMEENTENAAMNEN VARCHAR(255),
        IDENTIFICATIE VARCHAR(100),
        IS_OVERGEGAAN_IN_GEMEENTE_ID VARCHAR(255)
);

CREATE TABLE GEZINSMIGRANT_EN_OVERIGE_MIGRANT_ (
    NATUURLIJKPERSOON_ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE HOOFDDOEL (
    HOOFDDOEL_ID VARCHAR(255) PRIMARY KEY,
        DOEL_ENUM_ID VARCHAR(255),
        EINDDATUM DATE,
        STARTDATUM DATE
);

CREATE TABLE ICT_VAARDIGHEID (
    ICT_VAARDIGHEID_ID VARCHAR(255) PRIMARY KEY,
        ICTVAARDIGHEID BOOLEAN,
        NIVEAUICTVAARDIGHEID_ENUM_ID VARCHAR(255)
);

CREATE TABLE INBURGERAAR (
    NATUURLIJKPERSOON_ID VARCHAR(255) PRIMARY KEY,
        DOELGROEP INTEGER,
        GEDETAILLEERDE_DOELGROEP VARCHAR(255),
        HEEFT_AANDACHTSPUNT__ID VARCHAR(255),
        HEEFT_AANVRAAG_VERLENGING_INBURGERINGSTERMIJN_ID VARCHAR(255),
        HEEFT_EEN_INBURGERINGSPLICHT_ID VARCHAR(255),
        HEEFT_HOOFDDOEL_ID VARCHAR(255),
        HEEFT_ONTWIKKELWENS__ID VARCHAR(255)
);

CREATE TABLE INBURGERINGSAANBOD (
    INBURGERINGSAANBOD_ID VARCHAR(255) PRIMARY KEY,
        CONTRACTID INTEGER,
        CURSUSINSTELLING VARCHAR(255),
        DATUMAANVANGTAALSCHAKELTRAJECT DATE,
        DATUMEINDECURSUS DATE,
        DATUMINBURGERINGSAANBOD DATE,
        DATUMTAALSCHAKELDIPLOMA DATE,
        INDICATORALFABETISERING VARCHAR(255),
        PARTICIPATIEDEELNAME VARCHAR(255),
        TAALSCHAKELTRAJECT BOOLEAN,
        VOOR_INBURGERAAR_ID VARCHAR(255)
);

CREATE TABLE INBURGERINGSPLICHT (
    INBURGERINGSPLICHT_ID VARCHAR(255) PRIMARY KEY,
        BESCHIKKINGVOLDAANINBURGERINGSPLICHT VARCHAR(255),
        DATUMEIND DATE,
        DATUMGEWIJZIGDINBURGERINGSPLICHT DATE,
        DATUMGEWIJZIGDWORDTBEHANDELDALS DATE,
        DATUMSTART DATE,
        INBURGERAARSPECIALISATIE VARCHAR(255),
        INBURGERINGSTERMIJN_ID VARCHAR(255),
        INDICATORINBURGERINGSPLICHT BOOLEAN,
        ONTHEFFING_ONTHEFFING_ID VARCHAR(255),
        REDENGEENINBURGERINGSPLICHT VARCHAR(255),
        UITKOMSTLEERBAARHEIDSTOETS_ENUM_ID VARCHAR(255),
        VRIJSTELLING_VRIJSTELLING_ID VARCHAR(255),
        V_NUMMER INTEGER,
        WORDTBEHANDELSALS VARCHAR(255)
);

CREATE TABLE INBURGERINGSTERMIJN (
    INBURGERINGSTERMIJN_ID VARCHAR(255) PRIMARY KEY,
        BOETEBEDRAG DECIMAL(10,2),
        DATUMAANVANGINBURGERINGSTERMIJN DATE,
        DATUMBOETE DATE,
        DATUMEINDEINBURGERINGSTERMIJN DATE,
        VOORAANKONDIGINGBOETE BOOLEAN
);

CREATE TABLE INBURGERINGSTRAJECT (
    INBURGERINGSTRAJECT_ID VARCHAR(255) PRIMARY KEY,
        HEEFT_INBURGERINGSPLICHT_ID VARCHAR(255)
);

CREATE TABLE INTRODUCTIEMODULE (
    INTRODUCTIEMODULE_ID VARCHAR(255) PRIMARY KEY,
        DEELNAMEINTRODUCTIEMODULE VARCHAR(255),
        MODULENAAM VARCHAR(255)
);

CREATE TABLE LEERROUTE (
    LEERROUTE_ID VARCHAR(255) PRIMARY KEY,
        AFGESPROKEN_IN_PIP_ID VARCHAR(255),
        EXAMENA2 VARCHAR(255),
        GESCHATTEINTENSITEITB1ROUTE VARCHAR(255),
        INDICATORALFABETISERING_ENUM_ID VARCHAR(255),
        INDICATORLEERBAARHEIDSTOETSOVERGESLAGENVANWEGEZINTUIGELIJKEBEPERKING VARCHAR(255),
        INDICATORMAGOPLEIDINGAFMAKEN VARCHAR(255),
        INDICATORTOESTEMMINGEXAMENA2 VARCHAR(255),
        LEERROUTETYPE VARCHAR(255),
        NIVEAU VARCHAR(255)
);

CREATE TABLE MAP (
    MAP_ID VARCHAR(255) PRIMARY KEY,
        ONDERDEEL_VAN_LEERROUTE_ID VARCHAR(255)
);

CREATE TABLE NATUURLIJKPERSOON (
    NATUURLIJKPERSOON_ID VARCHAR(255) PRIMARY KEY,
        AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON VARCHAR(50),
        AANDUIDINGNAAMGEBRUIK VARCHAR(50),
        AANHEFAANSCHRIJVING VARCHAR(50),
        ACADEMISCHETITEL VARCHAR(80),
        ACHTERNAAM VARCHAR(100),
        ADELLIJKETITELOFPREDIKAAT VARCHAR(255),
        ANUMMER VARCHAR(20),
        ATTRIBUTE VARCHAR(255),
        BURGERSERVICENUMMER VARCHAR(255),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        GEBOORTELAND VARCHAR(255),
        GEBOORTEPLAATS VARCHAR(200),
        GESLACHTSAANDUIDING VARCHAR(255),
        GESLACHTSNAAM VARCHAR(200),
        GESLACHTSNAAMAANSCHRIJVING VARCHAR(200),
        HANDLICHTING VARCHAR(50),
        INDICATIEAFSCHERMINGPERSOONSGEGEVENS BOOLEAN,
        INDICATIEOVERLEDEN BOOLEAN,
        LANDOVERLIJDEN VARCHAR(255),
        NATIONALITEIT VARCHAR(100),
        OVERLIJDENSPLAATS VARCHAR(200),
        VOORLETTERSAANSCHRIJVING VARCHAR(20),
        VOORNAMEN VARCHAR(200),
        VOORNAMENAANSCHRIJVING VARCHAR(200),
        VOORVOEGSELGESLACHTSNAAM VARCHAR(80)
);

CREATE TABLE ONTHEFFING (
    ONTHEFFING_ID VARCHAR(255) PRIMARY KEY,
        BESLISSINGONTHEFFING BOOLEAN,
        DATUMONTHEFFING DATE,
        ONTHEFFING_VOOR_EXAMENONDERDEEL_ID VARCHAR(255)
);

CREATE TABLE ONTWIKKELWENS_ (
    ONTWIKKELWENS__ID VARCHAR(255) PRIMARY KEY,
        EINDDATUM DATE,
        ONTWIKKELWENS_ENUM_ID VARCHAR(255),
        STARTDATUM DATE,
        SUBDOEL_ONTWIKKELWENS_ID VARCHAR(255)
);

CREATE TABLE ONTWIKKELWENS_ENUM (
    ONTWIKKELWENS_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ONTWIKKELWENS_ENUM (ONTWIKKELWENS_ENUM_ID, VALUE) VALUES
    (1, 'BETAALD_WERKEN'),
    (2, 'BETAALD_WERKEN_MET_EEN_OPLEIDING'),
    (3, 'BETAALD_WERKEN_NAAR_VERMOGEN'),
    (4, 'ONDERNEMEN'),
    (5, 'OPLEIDING_VOLGEN'),
    (6, 'PASSENDE_DAGBESTEDING_HEBBEN'),
    (7, 'TAALVAARDIGHEDEN_OPDOEN'),
    (8, 'VRIJWILLIGERSWERK'),
    (9, 'WERKERVARING_OPDOEN'),
    (10, 'WERKNEMERSVAARDIGHEDEN_ONTWIKKELEN');

CREATE TABLE OPLEIDINGSNIVEAU_ENUM (
    OPLEIDINGSNIVEAU_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO OPLEIDINGSNIVEAU_ENUM (OPLEIDINGSNIVEAU_ENUM_ID, VALUE) VALUES
    (1, 'BASISNIVEAU'),
    (2, 'GEEN_BASISOPLEIDING'),
    (3, 'HBO_NIVEAU'),
    (4, 'LBO_MAVO_NIVEAU'),
    (5, 'MBO_HAVO_VWO_NIVEAU'),
    (6, 'NIET_VAN_TOEPASSING'),
    (7, 'WETENSCHAPPELIJK_ONDERWIJS');

CREATE TABLE PARTICIPATIEDEELNAME_ENUM (
    PARTICIPATIEDEELNAME_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO PARTICIPATIEDEELNAME_ENUM (PARTICIPATIEDEELNAME_ENUM_ID, VALUE) VALUES
    (1, 'ONVOLDOENDE'),
    (2, 'VOLDOENDE');

CREATE TABLE PIP (
    PIP_ID VARCHAR(255) PRIMARY KEY,
        BEVAT_INBURGERINGSAANBOD_ID VARCHAR(255)
);

CREATE TABLE PRESENTIETAALLES_ENUM (
    PRESENTIETAALLES_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO PRESENTIETAALLES_ENUM (PRESENTIETAALLES_ENUM_ID, VALUE) VALUES
    (1, 'ALTIJD_AANWEZIG'),
    (2, 'NOOIT_AANWEZIG'),
    (3, 'WEL_NIET_AANWEZIG');

CREATE TABLE PVT (
    PVT_ID VARCHAR(255) PRIMARY KEY,
        ONDERDEEL_VAN_LEERROUTE_ID VARCHAR(255)
);

CREATE TABLE SUBDOEL_AANDACHTSPUNT (
    SUBDOEL_AANDACHTSPUNT_ID VARCHAR(255) PRIMARY KEY,
        EINDDATUM DATE,
        STARTDATUM DATE,
        SUBDOEL VARCHAR(255)
);

CREATE TABLE SUBDOEL_BETAALD_WERKEN_ENUM (
    SUBDOEL_BETAALD_WERKEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_BETAALD_WERKEN_ENUM (SUBDOEL_BETAALD_WERKEN_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_GESTART_MET_WERKEN_EN_BEHOUD_MIJN_WERK_SUCCESVOL'),
    (2, 'IK_HEB_MIJN_SOLLICITATIEVAARDIGHEDEN_ONTWIKKELD'),
    (3, 'IK_HEB_URENUITBREIDING_GEKREGEN'),
    (4, 'IK_HEB_WERK_GEVONDEN_WAARMEE_IK_UIT_DE_BIJSTAND_GA'),
    (5, 'IK_WEET_WAT_MIJN_KWALITEITEN_ZIJN'),
    (6, 'IK_WEET_WELK_WERK_BIJ_MIJ_PAST');

CREATE TABLE SUBDOEL_BETAALD_WERKEN_MET_EEN_OPLEIDING_ENUM (
    SUBDOEL_BETAALD_WERKEN_MET_EEN_OPLEIDING_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_BETAALD_WERKEN_MET_EEN_OPLEIDING_ENUM (SUBDOEL_BETAALD_WERKEN_MET_EEN_OPLEIDING_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_GESTART_MET_EEN_BBL_OPLEIDING_WERKEN_EN_LEREN_'),
    (2, 'IK_VOLG_EEN_OPLEIDING_NAAST_MIJN_PARTTIME_BETAALDE_BAAN'),
    (3, 'IK_WEET_WELKE_OPLEIDING_PAST_BIJ_MIJN_MOGELIJKHEDEN');

CREATE TABLE SUBDOEL_BETAALD_WERKEN_NAAR_VERMOGEN_ENUM (
    SUBDOEL_BETAALD_WERKEN_NAAR_VERMOGEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_BETAALD_WERKEN_NAAR_VERMOGEN_ENUM (SUBDOEL_BETAALD_WERKEN_NAAR_VERMOGEN_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_GESTART_MET_WERKEN_EN_BEHOUD_MIJN_WERK_SUCCESVOL'),
    (2, 'IK_HEB_URENUITBREIDING_GEKREGEN'),
    (3, 'IK_HEB_WERK_GEVONDEN_WAARMEE_IK_UIT_DE_BIJSTAND_GA'),
    (4, 'IK_WEET_HOEVEEL_UUR_IK_KAN_WERKEN'),
    (5, 'IK_WEET_WAT_MIJN_KWALITEITEN_ZIJN'),
    (6, 'IK_WEET_WELK_WERK_BIJ_MIJN_PAST');

CREATE TABLE SUBDOEL_DIGITALE_VAARDIGHEDEN_ENUM (
    SUBDOEL_DIGITALE_VAARDIGHEDEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_DIGITALE_VAARDIGHEDEN_ENUM (SUBDOEL_DIGITALE_VAARDIGHEDEN_ENUM_ID, VALUE) VALUES
    (1, 'IK_HEB_VOLDOENDE_DIGITALE_VAARDIGHEDEN_OM_EEN_STAP_TE_ZETTEN_RICHTING_DE_ARBEIDSMARKT'),
    (2, 'IK_KAN_OMGAAN_MET_COMPUTER_SMARTPHONE_EN_TABLET_EN_KAN_ZELFSTANDIG_MAILEN_EN_ZOEKEN_OP_INTERNET');

CREATE TABLE SUBDOEL_EENZAAMHEID_ENUM (
    SUBDOEL_EENZAAMHEID_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_EENZAAMHEID_ENUM (SUBDOEL_EENZAAMHEID_ENUM_ID, VALUE) VALUES
    (1, 'IK_HEB_EEN_NETWERK_WAARMEE_IK_SOCIALE_CONTACTEN_HEB'),
    (2, 'IK_HEB_VERTROUWEN_IN_MIJZELF');

CREATE TABLE SUBDOEL_FINANCIEN_ENUM (
    SUBDOEL_FINANCIEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_FINANCIEN_ENUM (SUBDOEL_FINANCIEN_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_GESTART_MET_DE_HULP_VOOR_MIJN_SCHULDEN'),
    (2, 'IK_HEB_GEEN_FINANCIELE_BELEMMERINGEN_OM_AAN_HET_WERK_TE_GAAN'),
    (3, 'IK_HEB_HULP_BIJ_HET_REGELEN_VAN_MIJN_FINANCIEN'),
    (4, 'IK_HEB_OVERZICHT_OVER_MIJN_FINANCIELE_SITUATIE_EN_HET_LUKT_MIJ_OM_ROND_TE_KOMEN');

CREATE TABLE SUBDOEL_JUSTITIE_ENUM (
    SUBDOEL_JUSTITIE_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_JUSTITIE_ENUM (SUBDOEL_JUSTITIE_ENUM_ID, VALUE) VALUES
    (1, 'IK_HEB_MIJN_PENITENTAIR_PROGRAMMA_SUCCESVOL_AFGEROND'),
    (2, 'IK_WEET_WAT_MIJN_MOGELIJKHEDEN_ZIJN_MET_MIJN_JUSTITIELE_VERLEDEN');

CREATE TABLE SUBDOEL_LICHAMELIJKE_GEZONDHEID_ENUM (
    SUBDOEL_LICHAMELIJKE_GEZONDHEID_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_LICHAMELIJKE_GEZONDHEID_ENUM (SUBDOEL_LICHAMELIJKE_GEZONDHEID_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_ONDER_BEHANDELING_VOOR_MIJN_LICHAMELIJKE_KLACHTEN'),
    (2, 'IK_HEB_EEN_BEOORDELING_ARBEIDSVERMOGEN_AANGEVRAAGD_BIJ_HET_UWV'),
    (3, 'IK_HEB_HULP_GEVRAAGD_VOOR_MIJN_LICHAMELIJKE_KLACHTEN'),
    (4, 'IK_HEB_VERTROUWEN_IN_MIJZELF'),
    (5, 'IK_WEET_WAT_MIJN_MOGELIJKHEDEN_ZIJN_ONDANKS_MIJN_LICHAMELIJKE_KLACHTEN');

CREATE TABLE SUBDOEL_ONDERNEMEN_ENUM (
    SUBDOEL_ONDERNEMEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_ONDERNEMEN_ENUM (SUBDOEL_ONDERNEMEN_ENUM_ID, VALUE) VALUES
    (1, 'IK_HEB_EEN_ONDERNEMINGSPLAN_GESCHREVEN'),
    (2, 'IK_HEB_MIJN_BBZ_AANVRAAG_INGEDIEND'),
    (3, 'IK_WEET_OF_IK_IN_AANMERKING_KOM_OM_TE_ONDERNEMEN_VANUIT_BIJSTAND'),
    (4, 'MIJN_BBZ_AANVRAAG_IS_TOEGEKEND');

CREATE TABLE SUBDOEL_ONTWIKKELWENS (
    SUBDOEL_ONTWIKKELWENS_ID VARCHAR(255) PRIMARY KEY,
        EINDDATUM DATE,
        STARTDATUM DATE,
        SUBDOEL VARCHAR(255)
);

CREATE TABLE SUBDOEL_OPLEIDING_VOLGEN_ENUM (
    SUBDOEL_OPLEIDING_VOLGEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_OPLEIDING_VOLGEN_ENUM (SUBDOEL_OPLEIDING_VOLGEN_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_GESTART_MET_EEN_OPLEIDING'),
    (2, 'IK_WEET_WELKE_OPLEIDING_PAST_BIJ_MIJN_MOGELIJKHEDEN');

CREATE TABLE SUBDOEL_PASSENDE_DAGBESTEDING_HEBBEN_MAATSCHAPPELIJK_FIT_WORDEN__ENUM (
    SUBDOEL_PASSENDE_DAGBESTEDING_HEBBEN_MAATSCHAPPELIJK_FIT_WORDEN__ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_PASSENDE_DAGBESTEDING_HEBBEN_MAATSCHAPPELIJK_FIT_WORDEN__ENUM (SUBDOEL_PASSENDE_DAGBESTEDING_HEBBEN_MAATSCHAPPELIJK_FIT_WORDEN__ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_GESTART_MET_EEN_PASSENDE_DAGBESTEDING');

CREATE TABLE SUBDOEL_PSYCHISCHE_GEZONDHEID_ENUM (
    SUBDOEL_PSYCHISCHE_GEZONDHEID_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_PSYCHISCHE_GEZONDHEID_ENUM (SUBDOEL_PSYCHISCHE_GEZONDHEID_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_ONDER_BEHANDELING_VOOR_MIJN_PSYCHISCHE_KLACHTEN'),
    (2, 'IK_HEB_EEN_BEOORDELING_ARBEIDSVERMOGEN_AANGEVRAAGD_BIJ_HET_UWV'),
    (3, 'IK_HEB_HULP_GEVRAAGD_VOOR_MIJN_PSYCHISCHE_KLACHTEN'),
    (4, 'IK_HEB_VERTROUWEN_IN_MIJZELF'),
    (5, 'IK_WEET_WAT_MIJN_MOGELIJKKHEDEN_ZIJN_ONDANKS_DE_PSYCHISCHE_KLACHTEN');

CREATE TABLE SUBDOEL_TAALVAARDIGHEDEN_OPDOEN_ENUM (
    SUBDOEL_TAALVAARDIGHEDEN_OPDOEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_TAALVAARDIGHEDEN_OPDOEN_ENUM (SUBDOEL_TAALVAARDIGHEDEN_OPDOEN_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEHEERS_DE_NEDERLANDSE_TAAL_VOLDOENDE_OM_AAN_HET_WERK_TE_GAAN_OF_TE_ONDERNEMEN');

CREATE TABLE SUBDOEL_TAAL_ENUM (
    SUBDOEL_TAAL_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_TAAL_ENUM (SUBDOEL_TAAL_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEHEERS_DE_NEDERLANDSE_TAAL_OP_HET_VOOR_MIJ_HOOGST_HAALBARE_NIVEAU'),
    (2, 'IK_BEHEERS_DE_NEDERLANDSE_TAAL_VOLDOENDE_OM_EEN_VOLGENDE_STAP_TE_KUNNEN_ZETTEN'),
    (3, 'IK_WEET_WAT_MIJN_NEDERLANDS_TAALNIVEAU_IS');

CREATE TABLE SUBDOEL_VERSLAVING_ENUM (
    SUBDOEL_VERSLAVING_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_VERSLAVING_ENUM (SUBDOEL_VERSLAVING_ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_ONDER_BEHANDELING_VOOR_MIJN_VERSLAVINGSPROBLEMATIEK'),
    (2, 'IK_HEB_HULP_GEVRAAGD_VOOR_MIJN_VERSLAVINGSPROBLEMATIEK'),
    (3, 'IK_HEB_VERTROUWEN_IN_MIJZELF'),
    (4, 'IK_WEET_WAT_MIJN_MOGELIJKHEDEN_ZIJN_ONDANKS_DE_VERSLAVINGSPROBLEMATIEK');

CREATE TABLE SUBDOEL_VRIJWILLIGERSWERK_DOEN_MAATSCHAPPELIJK_FIT_WORDEN__ENUM (
    SUBDOEL_VRIJWILLIGERSWERK_DOEN_MAATSCHAPPELIJK_FIT_WORDEN__ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_VRIJWILLIGERSWERK_DOEN_MAATSCHAPPELIJK_FIT_WORDEN__ENUM (SUBDOEL_VRIJWILLIGERSWERK_DOEN_MAATSCHAPPELIJK_FIT_WORDEN__ENUM_ID, VALUE) VALUES
    (1, 'IK_BEN_GESTART_MET_VRIJWILLIGERSWERK');

CREATE TABLE SUBDOEL_WERKERVARING_OPDOEN_WERKFIT_WORDEN__ENUM (
    SUBDOEL_WERKERVARING_OPDOEN_WERKFIT_WORDEN__ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_WERKERVARING_OPDOEN_WERKFIT_WORDEN__ENUM (SUBDOEL_WERKERVARING_OPDOEN_WERKFIT_WORDEN__ENUM_ID, VALUE) VALUES
    (1, 'IK_HEB_OPGEBOUWD_IN_HET_AANTAL_UREN_WAT_IK_KAN_WERKEN'),
    (2, 'IK_HEB_WERKERVARING_OPGEDAAN_IN_EEN_FUNCTIE'),
    (3, 'IK_WEET_HOEVEEL_UREN_IK_KAN_WERKEN'),
    (4, 'IK_WEET_WAT_MIJN_KWALTITEITEN_ZIJN');

CREATE TABLE SUBDOEL_WERKNEMERSVAARDIGHEDEN_ONTWIKKELEN_WERKFIT_WORDEN__ENUM (
    SUBDOEL_WERKNEMERSVAARDIGHEDEN_ONTWIKKELEN_WERKFIT_WORDEN__ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_WERKNEMERSVAARDIGHEDEN_ONTWIKKELEN_WERKFIT_WORDEN__ENUM (SUBDOEL_WERKNEMERSVAARDIGHEDEN_ONTWIKKELEN_WERKFIT_WORDEN__ENUM_ID, VALUE) VALUES
    (1, 'IK_HEB_EEN_WERKRITME'),
    (2, 'IK_HEB_OPGEBOUWD_IN_HET_AANTAL_UREN_WAT_IK_KAN_WERKEN'),
    (3, 'IK_WEET_HOEVEEL_UREN_IK_KAN_WERKEN'),
    (4, 'IK_WEET_WAT_ER_VAN_MIJN_VERWACHT_WORDT_ALS_WERKNEMER'),
    (5, 'IK_WEET_WAT_MIJN_KWALITEITEN_ZIJN');

CREATE TABLE SUBDOEL_WOONSITUATIE_ENUM (
    SUBDOEL_WOONSITUATIE_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_WOONSITUATIE_ENUM (SUBDOEL_WOONSITUATIE_ENUM_ID, VALUE) VALUES
    (1, 'IK_HEB_ERVOOR_GEZORGD_DAT_MIJN_WOONSITUATIE_VERBETERD'),
    (2, 'IK_HEB_HULP_GEVRAAGD_OM_MIJN_WOONSITUATIE_TE_VERBETEREN');

CREATE TABLE SUBDOEL_ZORGTAKEN_ENUM (
    SUBDOEL_ZORGTAKEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SUBDOEL_ZORGTAKEN_ENUM (SUBDOEL_ZORGTAKEN_ENUM_ID, VALUE) VALUES
    (1, 'IK_HEB_KINDEROPVANG_VOOR_MIJN_KINDEREN'),
    (2, 'IK_KAN_MIJN_ZORGTAKEN_MANTELZORG_OVERDRAGEN_AAN_ANDEREN'),
    (3, 'IK_KRIJG_BETAALD_VOOR_MIJN_WERKZAAMHEDEN_ALS_MANTELZORGER_VANUIT_PGB_'),
    (4, 'IK_WEET_HOE_IK_MIJN_ZORGTAKEN_KAN_COMBINEREN_MET_EEN_BAAN_OPLEIDING_OF_ANDERE_ACTIVITEIT'),
    (5, 'IK_WEET_OF_IK_VANUIT_PGB_BETAALD_KAN_KRIJGEN_VOOR_MIJN_WERKZAAMHEDEN_ALS_MANTELZORGER');

CREATE TABLE TAALVAARDIGHEID (
    TAALVAARDIGHEID_ID VARCHAR(255) PRIMARY KEY,
        EINDEVANTAALLESACTVITEIT DATE,
        OPLEIDINGSNIVEAUGESCHAT VARCHAR(255),
        PRESENTIETAALLES VARCHAR(255),
        RESULTAATTAALLES_ENUM_ID VARCHAR(255),
        RESULTAATTOETSSPREEKVAARDIGHEID INTEGER,
        RESULTAATTOETSTAALLEERBAARHEID INTEGER,
        SCORE INTEGER,
        STARTVANTAALLESACTVITEIT DATE,
        TAALLESACTIVITEIT VARCHAR(255),
        TAALVAARDIGHEIDMONDELING_ENUM_ID VARCHAR(255),
        TAALVAARDIGHEIDSCHRIFTELIJK_ENUM_ID VARCHAR(255),
        TAALVAARDIGHEID_ENUM_ID VARCHAR(255),
        TOETSSPREEKVAARDIGHEID_ENUM_ID VARCHAR(255),
        TOETSTAALLEERBAARHEID_ENUM_ID VARCHAR(255)
);

CREATE TABLE TRAINING (
    TRAINING_ID VARCHAR(255) PRIMARY KEY,
        PERIODETRAINING VARCHAR(255),
        RESULTAATTRAINING_ENUM_ID VARCHAR(255),
        TRAINING BOOLEAN
);

CREATE TABLE UITKOMSTLEERBAARHEIDSTOETS_ENUM (
    UITKOMSTLEERBAARHEIDSTOETS_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO UITKOMSTLEERBAARHEIDSTOETS_ENUM (UITKOMSTLEERBAARHEIDSTOETS_ENUM_ID, VALUE) VALUES
    (1, 'B1_ROUTE'),
    (2, 'ONDERWIJSROUTE'),
    (3, 'Z_ROUTE');

CREATE TABLE VERBLIJFPLAATS_AZC (
    VERBLIJFPLAATS_AZC_ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE VERLENGINGSGROND (
    VERLENGINGSGROND_ID VARCHAR(255) PRIMARY KEY,
        AANWEZIGHEIDAANVRAAGVERLENING BOOLEAN,
        DATUMAANVANGVERLENGINGSGROND DATE,
        DATUMBEOORDELINGVERLENGINGSGROND DATE,
        DATUMEINDEVERLENGINGSGROND DATE,
        VERLENGINGINWEKEN INTEGER,
        VERLENGINGSGROND VARCHAR(255)
);

CREATE TABLE VOORBEREIDING_OP_INBURGERING (
    VOORBEREIDING_OP_INBURGERING_ID VARCHAR(255) PRIMARY KEY,
        BESTAAT_UIT_INTRODUCTIEMODULE_ID VARCHAR(255),
        DATUMINSTEMMING DATE,
        INSTEMMINGDEELNAMEVOORINBURGERING BOOLEAN,
        REDEN VARCHAR(255)
);

CREATE TABLE VREEMDELING (
    NATUURLIJKPERSOON_ID VARCHAR(255) PRIMARY KEY,
        SOCIAAL_REFERENT VARCHAR(255),
        V_NUMMER VARCHAR(255)
);

CREATE TABLE VRIJSTELLING (
    VRIJSTELLING_ID VARCHAR(255) PRIMARY KEY,
        DATUMVRIJSTELLING DATE,
        EINDOORDEELVRIJSTELLING DATE,
        VRIJSTELLING_VOOR_EXAMENONDERDEEL_ID VARCHAR(255)
);

CREATE TABLE WERK (
    WERK_ID VARCHAR(255) PRIMARY KEY,
        AMBITIE VARCHAR(255),
        BEROEP VARCHAR(255),
        BEROEPTOT DATE,
        BEROEPVAN DATE,
        CONTACTUAF VARCHAR(255),
        CVGEMAAKT BOOLEAN,
        SOORTAANSTELLING VARCHAR(255),
        TAAK VARCHAR(255),
        TAAKTOT DATE,
        TAAKVAN DATE,
        VRIJETEKSTBESTEDING VARCHAR(255)
);

CREATE TABLE WORDTBEHANDELDALS_ENUM (
    WORDTBEHANDELDALS_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO WORDTBEHANDELDALS_ENUM (WORDTBEHANDELDALS_ENUM_ID, VALUE) VALUES
    (1, 'ASIELSTATUSHOUDER'),
    (2, 'GEZINSMIGRANT'),
    (3, 'OVERIGEMIGRANT');

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_GEN_INBURGERAAR FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES INBURGERAAR (NATUURLIJKPERSOON_ID);
-- Generalization to INBURGERAAR

ALTER TABLE GEZINSMIGRANT_EN_OVERIGE_MIGRANT_ ADD CONSTRAINT FK_GEZINSMIGRANT_EN_OVERIGE_MIGRANT__GEN_INBURGERAAR FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES INBURGERAAR (NATUURLIJKPERSOON_ID);
-- Generalization to INBURGERAAR

ALTER TABLE INBURGERAAR ADD CONSTRAINT FK_INBURGERAAR_GEN_VREEMDELING FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES VREEMDELING (NATUURLIJKPERSOON_ID);
-- Generalization to VREEMDELING

ALTER TABLE VREEMDELING ADD CONSTRAINT FK_VREEMDELING_GEN_NATUURLIJKPERSOON FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (NATUURLIJKPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE AANDACHTSPUNT_ ADD CONSTRAINT FK_AANDACHTSPUNT__AANDACHTSPUNT_ENUM_ID FOREIGN KEY (AANDACHTSPUNT_ENUM_ID) REFERENCES AANDACHTSPUNT_ENUM (AANDACHTSPUNT_ENUM_ID);
-- AANDACHTSPUNT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE AANDACHTSPUNT_ ADD CONSTRAINT FK_AANDACHTSPUNT__SUBDOEL_AANDACHTSPUNT FOREIGN KEY (SUBDOEL_AANDACHTSPUNT_ID) REFERENCES SUBDOEL_AANDACHTSPUNT (SUBDOEL_AANDACHTSPUNT_ID);
-- unnamed (0 to 0..*, Connector_ID: 1631)

ALTER TABLE AANVRAAG_VERLENGING_INBURGERINGSTERMIJN ADD CONSTRAINT FK_AANVRAAG_VERLENGING_INBURGERINGSTERMIJN_BEOORDELINGAANVRAAGVERLENGING_ENUM_ID FOREIGN KEY (BEOORDELINGAANVRAAGVERLENGING_ENUM_ID) REFERENCES BEOORDELINGAANVRAAGVERLENGING_ENUM (BEOORDELINGAANVRAAGVERLENGING_ENUM_ID);
-- BEOORDELINGAANVRAAGVERLENGING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE AANVRAAG_VERLENGING_INBURGERINGSTERMIJN ADD CONSTRAINT FK_AANVRAAG_VERLENGING_INBURGERINGSTERMIJN_BEOORDELING_AANVRAAG FOREIGN KEY (BEOORDELING_AANVRAAG_INBURGERINGSTERMIJN_ID) REFERENCES INBURGERINGSTERMIJN (INBURGERINGSTERMIJN_ID);
-- BEOORDELING_AANVRAAG (1 to 1..*, Connector_ID: 1615)

ALTER TABLE AANVRAAG_VERLENGING_INBURGERINGSTERMIJN ADD CONSTRAINT FK_AANVRAAG_VERLENGING_INBURGERINGSTERMIJN_VERLENGINGSGROND FOREIGN KEY (VERLENGINGSGROND_ID) REFERENCES VERLENGINGSGROND (VERLENGINGSGROND_ID);
-- unnamed (None to None, Connector_ID: 1613)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_BEZIT FOREIGN KEY (BEZIT_ICT_VAARDIGHEID_ID) REFERENCES ICT_VAARDIGHEID (ICT_VAARDIGHEID_ID);
-- BEZIT (1 to 0..*, Connector_ID: 1628)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_HEEFT FOREIGN KEY (HEEFT_TAALVAARDIGHEID_ID) REFERENCES TAALVAARDIGHEID (TAALVAARDIGHEID_ID);
-- HEEFT (1 to 1, Connector_ID: 1629)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_HEEFT_AANGEVRAAGD FOREIGN KEY (HEEFT_AANGEVRAAGD_DIPLOMAWAARDERING_ID) REFERENCES DIPLOMAWAARDERING (DIPLOMAWAARDERING_ID);
-- HEEFT_AANGEVRAAGD (1 to 0..*, Connector_ID: 1608)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_HEEFT_GEVOLGD FOREIGN KEY (HEEFT_GEVOLGD_EDUCATIE_ID) REFERENCES EDUCATIE (EDUCATIE_ID);
-- HEEFT_GEVOLGD (1 to 0..*, Connector_ID: 1609)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_HEEFT_GEVOLGD_2 FOREIGN KEY (HEEFT_GEVOLGD_TRAINING_ID) REFERENCES TRAINING (TRAINING_ID);
-- HEEFT_GEVOLGD (1 to 0..*, Connector_ID: 1610)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_IS_GEKOPPELD_AAN_ FOREIGN KEY (IS_GEKOPPELD_AAN__GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- IS_GEKOPPELD_AAN_ (0..* to 0..1, Connector_ID: 1029)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_NEEMT_DEEL FOREIGN KEY (NEEMT_DEEL_VOORBEREIDING_OP_INBURGERING_ID) REFERENCES VOORBEREIDING_OP_INBURGERING (VOORBEREIDING_OP_INBURGERING_ID);
-- NEEMT_DEEL (1 to 1, Connector_ID: 1612)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_VERBLIJFT FOREIGN KEY (VERBLIJFT_VERBLIJFPLAATS_AZC_ID) REFERENCES VERBLIJFPLAATS_AZC (VERBLIJFPLAATS_AZC_ID);
-- VERBLIJFT (0..* to 0..1, Connector_ID: 1028)

ALTER TABLE ASIELSTATUSHOUDER ADD CONSTRAINT FK_ASIELSTATUSHOUDER_WERK FOREIGN KEY (WERK_ID) REFERENCES WERK (WERK_ID);
-- unnamed (1 to 0..*, Connector_ID: 1625)

ALTER TABLE B1_ROUTE ADD CONSTRAINT FK_B1_ROUTE_ONDERDEEL_VAN_ FOREIGN KEY (ONDERDEEL_VAN__LEERROUTE_ID) REFERENCES LEERROUTE (LEERROUTE_ID);
-- ONDERDEEL_VAN_ (0..1 to 1, Connector_ID: 1630)

ALTER TABLE BREDE_INTAKE ADD CONSTRAINT FK_BREDE_INTAKE_HEEFT FOREIGN KEY (HEEFT_LEERROUTE_ID) REFERENCES LEERROUTE (LEERROUTE_ID);
-- HEEFT (0..1 to 1, Connector_ID: 1622)

ALTER TABLE BREDE_INTAKE ADD CONSTRAINT FK_BREDE_INTAKE_ONDERDEEL_VAN FOREIGN KEY (ONDERDEEL_VAN_INBURGERINGSTRAJECT_ID) REFERENCES INBURGERINGSTRAJECT (INBURGERINGSTRAJECT_ID);
-- ONDERDEEL_VAN (0..1 to 1, Connector_ID: 1025)

ALTER TABLE DIPLOMAWAARDERING ADD CONSTRAINT FK_DIPLOMAWAARDERING_DIPLOMAWAARDERINGRICHTING_ENUM_ID FOREIGN KEY (DIPLOMAWAARDERINGRICHTING_ENUM_ID) REFERENCES OPLEIDINGSNIVEAU_ENUM (OPLEIDINGSNIVEAU_ENUM_ID);
-- DIPLOMAWAARDERINGRICHTING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE DIPLOMAWAARDERING ADD CONSTRAINT FK_DIPLOMAWAARDERING_DIPLOMAWAARDERINGVOOR_ENUM_ID FOREIGN KEY (DIPLOMAWAARDERINGVOOR_ENUM_ID) REFERENCES OPLEIDINGSNIVEAU_ENUM (OPLEIDINGSNIVEAU_ENUM_ID);
-- DIPLOMAWAARDERINGVOOR_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE DIPLOMAWAARDERING ADD CONSTRAINT FK_DIPLOMAWAARDERING_NIVEAUCOMPETENTIE_ENUM_ID FOREIGN KEY (NIVEAUCOMPETENTIE_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- NIVEAUCOMPETENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE EDUCATIE ADD CONSTRAINT FK_EDUCATIE_EDUCATIEDIPLOMA_ENUM_ID FOREIGN KEY (EDUCATIEDIPLOMA_ENUM_ID) REFERENCES OPLEIDINGSNIVEAU_ENUM (OPLEIDINGSNIVEAU_ENUM_ID);
-- EDUCATIEDIPLOMA_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE EXAMEN ADD CONSTRAINT FK_EXAMEN_AFGEROND_MET FOREIGN KEY (AFGEROND_MET_INBURGERINGSTRAJECT_ID) REFERENCES INBURGERINGSTRAJECT (INBURGERINGSTRAJECT_ID);
-- AFGEROND_MET (0..1 to 1, Connector_ID: 1023)

ALTER TABLE EXAMENONDERDEEL ADD CONSTRAINT FK_EXAMENONDERDEEL_EXAMEN FOREIGN KEY (EXAMEN_ID) REFERENCES EXAMEN (EXAMEN_ID);
-- unnamed (0..* to 1, Connector_ID: 1022)

ALTER TABLE GEMEENTE ADD CONSTRAINT FK_GEMEENTE_IS_OVERGEGAAN_IN FOREIGN KEY (IS_OVERGEGAAN_IN_GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- IS_OVERGEGAAN_IN (None to 0..*, Connector_ID: 219)

ALTER TABLE HOOFDDOEL ADD CONSTRAINT FK_HOOFDDOEL_DOEL_ENUM_ID FOREIGN KEY (DOEL_ENUM_ID) REFERENCES DOEL_ENUM (DOEL_ENUM_ID);
-- DOEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ICT_VAARDIGHEID ADD CONSTRAINT FK_ICT_VAARDIGHEID_NIVEAUICTVAARDIGHEID_ENUM_ID FOREIGN KEY (NIVEAUICTVAARDIGHEID_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- NIVEAUICTVAARDIGHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INBURGERAAR ADD CONSTRAINT FK_INBURGERAAR_HEEFT FOREIGN KEY (HEEFT_AANDACHTSPUNT__ID) REFERENCES AANDACHTSPUNT_ (AANDACHTSPUNT__ID);
-- HEEFT (None to 0..*, Connector_ID: 1597)

ALTER TABLE INBURGERAAR ADD CONSTRAINT FK_INBURGERAAR_HEEFT_2 FOREIGN KEY (HEEFT_HOOFDDOEL_ID) REFERENCES HOOFDDOEL (HOOFDDOEL_ID);
-- HEEFT (None to 0..*, Connector_ID: 1603)

ALTER TABLE INBURGERAAR ADD CONSTRAINT FK_INBURGERAAR_HEEFT_3 FOREIGN KEY (HEEFT_ONTWIKKELWENS__ID) REFERENCES ONTWIKKELWENS_ (ONTWIKKELWENS__ID);
-- HEEFT (None to 0..*, Connector_ID: 1607)

ALTER TABLE INBURGERAAR ADD CONSTRAINT FK_INBURGERAAR_HEEFT_4 FOREIGN KEY (HEEFT_AANVRAAG_VERLENGING_INBURGERINGSTERMIJN_ID) REFERENCES AANVRAAG_VERLENGING_INBURGERINGSTERMIJN (AANVRAAG_VERLENGING_INBURGERINGSTERMIJN_ID);
-- HEEFT (None to None, Connector_ID: 1614)

ALTER TABLE INBURGERAAR ADD CONSTRAINT FK_INBURGERAAR_HEEFT_EEN FOREIGN KEY (HEEFT_EEN_INBURGERINGSPLICHT_ID) REFERENCES INBURGERINGSPLICHT (INBURGERINGSPLICHT_ID);
-- HEEFT_EEN (1 to 1, Connector_ID: 1599)

ALTER TABLE INBURGERINGSAANBOD ADD CONSTRAINT FK_INBURGERINGSAANBOD_VOOR FOREIGN KEY (VOOR_INBURGERAAR_ID) REFERENCES NATUURLIJKPERSOON (NATUURLIJKPERSOON_ID);
-- VOOR (1 to 1..*, Connector_ID: 1601)

ALTER TABLE INBURGERINGSPLICHT ADD CONSTRAINT FK_INBURGERINGSPLICHT_INBURGERINGSTERMIJN FOREIGN KEY (INBURGERINGSTERMIJN_ID) REFERENCES INBURGERINGSTERMIJN (INBURGERINGSTERMIJN_ID);
-- unnamed (1 to 1..*, Connector_ID: 1600)

ALTER TABLE INBURGERINGSPLICHT ADD CONSTRAINT FK_INBURGERINGSPLICHT_ONTHEFFING FOREIGN KEY (ONTHEFFING_ONTHEFFING_ID) REFERENCES ONTHEFFING (ONTHEFFING_ID);
-- ONTHEFFING (1 to 0..*, Connector_ID: 1627)

ALTER TABLE INBURGERINGSPLICHT ADD CONSTRAINT FK_INBURGERINGSPLICHT_UITKOMSTLEERBAARHEIDSTOETS_ENUM_ID FOREIGN KEY (UITKOMSTLEERBAARHEIDSTOETS_ENUM_ID) REFERENCES UITKOMSTLEERBAARHEIDSTOETS_ENUM (UITKOMSTLEERBAARHEIDSTOETS_ENUM_ID);
-- UITKOMSTLEERBAARHEIDSTOETS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INBURGERINGSPLICHT ADD CONSTRAINT FK_INBURGERINGSPLICHT_VRIJSTELLING FOREIGN KEY (VRIJSTELLING_VRIJSTELLING_ID) REFERENCES VRIJSTELLING (VRIJSTELLING_ID);
-- VRIJSTELLING (1 to 0..*, Connector_ID: 1604)

ALTER TABLE INBURGERINGSTRAJECT ADD CONSTRAINT FK_INBURGERINGSTRAJECT_HEEFT FOREIGN KEY (HEEFT_INBURGERINGSPLICHT_ID) REFERENCES INBURGERINGSPLICHT (INBURGERINGSPLICHT_ID);
-- HEEFT (1 to 1, Connector_ID: 1598)

ALTER TABLE LEERROUTE ADD CONSTRAINT FK_LEERROUTE_AFGESPROKEN_IN FOREIGN KEY (AFGESPROKEN_IN_PIP_ID) REFERENCES PIP (PIP_ID);
-- AFGESPROKEN_IN (0..1 to 1, Connector_ID: 1620)

ALTER TABLE LEERROUTE ADD CONSTRAINT FK_LEERROUTE_INDICATORALFABETISERING_ENUM_ID FOREIGN KEY (INDICATORALFABETISERING_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- INDICATORALFABETISERING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE MAP ADD CONSTRAINT FK_MAP_ONDERDEEL_VAN FOREIGN KEY (ONDERDEEL_VAN_LEERROUTE_ID) REFERENCES LEERROUTE (LEERROUTE_ID);
-- ONDERDEEL_VAN (0..1 to 1, Connector_ID: 1619)

ALTER TABLE ONTHEFFING ADD CONSTRAINT FK_ONTHEFFING_ONTHEFFING_VOOR FOREIGN KEY (ONTHEFFING_VOOR_EXAMENONDERDEEL_ID) REFERENCES EXAMENONDERDEEL (EXAMENONDERDEEL_ID);
-- ONTHEFFING_VOOR (1 to None, Connector_ID: 1626)

ALTER TABLE ONTWIKKELWENS_ ADD CONSTRAINT FK_ONTWIKKELWENS__ONTWIKKELWENS_ENUM_ID FOREIGN KEY (ONTWIKKELWENS_ENUM_ID) REFERENCES ONTWIKKELWENS_ENUM (ONTWIKKELWENS_ENUM_ID);
-- ONTWIKKELWENS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ONTWIKKELWENS_ ADD CONSTRAINT FK_ONTWIKKELWENS__SUBDOEL_ONTWIKKELWENS FOREIGN KEY (SUBDOEL_ONTWIKKELWENS_ID) REFERENCES SUBDOEL_ONTWIKKELWENS (SUBDOEL_ONTWIKKELWENS_ID);
-- unnamed (0 to 0..*, Connector_ID: 1616)

ALTER TABLE PIP ADD CONSTRAINT FK_PIP_BEVAT FOREIGN KEY (BEVAT_INBURGERINGSAANBOD_ID) REFERENCES INBURGERINGSAANBOD (INBURGERINGSAANBOD_ID);
-- BEVAT (1 to 1, Connector_ID: 1602)

ALTER TABLE PVT ADD CONSTRAINT FK_PVT_ONDERDEEL_VAN FOREIGN KEY (ONDERDEEL_VAN_LEERROUTE_ID) REFERENCES LEERROUTE (LEERROUTE_ID);
-- ONDERDEEL_VAN (0..1 to 1, Connector_ID: 1624)

ALTER TABLE TAALVAARDIGHEID ADD CONSTRAINT FK_TAALVAARDIGHEID_RESULTAATTAALLES_ENUM_ID FOREIGN KEY (RESULTAATTAALLES_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- RESULTAATTAALLES_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TAALVAARDIGHEID ADD CONSTRAINT FK_TAALVAARDIGHEID_TAALVAARDIGHEIDMONDELING_ENUM_ID FOREIGN KEY (TAALVAARDIGHEIDMONDELING_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- TAALVAARDIGHEIDMONDELING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TAALVAARDIGHEID ADD CONSTRAINT FK_TAALVAARDIGHEID_TAALVAARDIGHEIDSCHRIFTELIJK_ENUM_ID FOREIGN KEY (TAALVAARDIGHEIDSCHRIFTELIJK_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- TAALVAARDIGHEIDSCHRIFTELIJK_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TAALVAARDIGHEID ADD CONSTRAINT FK_TAALVAARDIGHEID_TAALVAARDIGHEID_ENUM_ID FOREIGN KEY (TAALVAARDIGHEID_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- TAALVAARDIGHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TAALVAARDIGHEID ADD CONSTRAINT FK_TAALVAARDIGHEID_TOETSSPREEKVAARDIGHEID_ENUM_ID FOREIGN KEY (TOETSSPREEKVAARDIGHEID_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- TOETSSPREEKVAARDIGHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TAALVAARDIGHEID ADD CONSTRAINT FK_TAALVAARDIGHEID_TOETSTAALLEERBAARHEID_ENUM_ID FOREIGN KEY (TOETSTAALLEERBAARHEID_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- TOETSTAALLEERBAARHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TRAINING ADD CONSTRAINT FK_TRAINING_RESULTAATTRAINING_ENUM_ID FOREIGN KEY (RESULTAATTRAINING_ENUM_ID) REFERENCES CLASSIFICATIEARMTOTUITSTEKEND_ENUM (CLASSIFICATIEARMTOTUITSTEKEND_ENUM_ID);
-- RESULTAATTRAINING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VOORBEREIDING_OP_INBURGERING ADD CONSTRAINT FK_VOORBEREIDING_OP_INBURGERING_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_INTRODUCTIEMODULE_ID) REFERENCES INTRODUCTIEMODULE (INTRODUCTIEMODULE_ID);
-- BESTAAT_UIT (None to None, Connector_ID: 1611)

ALTER TABLE VRIJSTELLING ADD CONSTRAINT FK_VRIJSTELLING_VRIJSTELLING_VOOR FOREIGN KEY (VRIJSTELLING_VOOR_EXAMENONDERDEEL_ID) REFERENCES EXAMENONDERDEEL (EXAMENONDERDEEL_ID);
-- VRIJSTELLING_VOOR (1 to 1, Connector_ID: 1605)

