CREATE TABLE [KP_ANVRGFMLDNG_ONDRWRP] (
    [KP_ANVRGFMLDNG_ONDRWRP_ID] INT PRIMARY KEY,
    [AANVRAAGOFMELDING_ID] INT,
    [ONDERWERP_ID] INT
);

CREATE TABLE [VESTIGINGVANZAAKBEHANDELENDEORGANISATIE] (
    [VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID] INT PRIMARY KEY
);

CREATE TABLE [KP_FRMLRSRT_ZKTYP] (
    [KP_FRMLRSRT_ZKTYP_ID] INT PRIMARY KEY,
    [FORMULIERSOORT_ID] INT,
    [ZAAKTYPE_ID] INT
);

CREATE TABLE [HEFFING] (
    [HEFFING_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [CODE] VARCHAR(80),
    [DATUMINDIENING] DATE,
    [GEFACTUREERD] BIT,
    [INREKENING] VARCHAR(255),
    [NUMMER] INT,
    [RUNNUMMER] INT
);

CREATE TABLE [ONDERWERP] (
    [ONDERWERP_ID] INT PRIMARY KEY,
    [HOOFDONDERWERP_ONDERWERP_ID] INT,
    [ISACTIEF] BIT,
    [NAAM] VARCHAR(80),
    [TOELICHTING] NVARCHAR(MAX)
);

CREATE TABLE [FORMULIERSOORT] (
    [FORMULIERSOORT_ID] INT PRIMARY KEY,
    [INGEBRUIK] BIT,
    [NAAM] VARCHAR(80),
    [ONDERWERP] VARCHAR(80)
);

CREATE TABLE [MEDEWERKER] (
    [MEDEWERKER_ID] INT PRIMARY KEY,
    [ACHTERNAAM] VARCHAR(200),
    [DATUMINDIENST] DATE,
    [DATUMUITDIENST] DATE,
    [EMAILADRES] VARCHAR(255),
    [EXTERN] BIT,
    [FUNCTIE] VARCHAR(50),
    [GESLACHTSAANDUIDING] VARCHAR(255),
    [MEDEWERKERIDENTIFICATIE] VARCHAR(255),
    [MEDEWERKERTOELICHTING] VARCHAR(255),
    [ROEPNAAM] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20),
    [VOORLETTERS] VARCHAR(20),
    [VOORVOEGSELACHTERNAAM] VARCHAR(255)
);

CREATE TABLE [KLANTCONTACT] (
    [KLANTCONTACT_ID] INT PRIMARY KEY,
    [EINDTIJD] DATETIME2,
    [HEEFT_BETREKKING_OP_ZAAK_ID] INT,
    [IS_GEVOERD_DOOR_MEDEWERKER_ID] INT,
    [KANAAL] VARCHAR(20),
    [LOCATIE_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID] INT,
    [NOTITIE] NVARCHAR(MAX),
    [STARTTIJD] DATETIME2,
    [TIJDSDUUR] DATETIME2,
    [TOELICHTING] NVARCHAR(MAX),
    [WACHTTIJDTOTAAL] DATETIME2
);

CREATE TABLE [DOCUMENT] (
    [DOCUMENT_ID] INT PRIMARY KEY,
    [COCUMENTBESCHRIJVING] VARCHAR(255),
    [DATUMCREATIEDOCUMENT] DATE,
    [DATUMONTVANGSTDOCUMENT] DATE,
    [DATUMVERZENDINGDOCUMENT] DATE,
    [DOCUMENTAUTEUR] VARCHAR(200),
    [DOCUMENTIDENTIFICATIE] VARCHAR(255),
    [DOCUMENTTITEL] VARCHAR(200),
    [HEEFT_DOCUMENTEN_AANVRAAGOFMELDING_ID] INT,
    [VERTROUWELIJKAANDUIDING] VARCHAR(20)
);

CREATE TABLE [KP_ZK_MDWRKR] (
    [KP_ZK_MDWRKR_ID] INT PRIMARY KEY,
    [ZAAK_ID] INT,
    [MEDEWERKER_ID] INT
);

CREATE TABLE [ZAAK] (
    [ZAAK_ID] INT PRIMARY KEY,
    [ARCHIEFNOMINATIE] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMEINDEGEPLAND] DATE,
    [DATUMEINDEUITERLIJKEAFDOENING] DATE,
    [DATUMLAATSTEBETALING] DATE,
    [DATUMPUBLICATIE] DATE,
    [DATUMREGISTRATIE] DATE,
    [DATUMSTART] DATE,
    [DATUMVERNIETIGINGDOSSIER] DATE,
    [DUURVERLENGING] VARCHAR(255),
    [HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID] INT,
    [HEEFT_HEFFING_ID] INT,
    [INDICATIEBETALING] VARCHAR(255),
    [INDICATIEDEELZAKEN] BIT,
    [INDICATIEOPSCHORTING] VARCHAR(255),
    [IS_DEELZAAK_VAN_ZAAK_ID] INT,
    [IS_VAN_ZAAKTYPE_ID] INT,
    [KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID] INT,
    [LEGES] VARCHAR(100),
    [OMSCHRIJVING] VARCHAR(80),
    [OMSCHRIJVINGRESULTAAT] VARCHAR(80),
    [REDENOPSCHORTING] VARCHAR(200),
    [REDENVERLENGING] VARCHAR(200),
    [TOELICHTING] VARCHAR(255),
    [TOELICHTINGRESULTAAT] VARCHAR(255),
    [VERTROUWELIJKHEID] VARCHAR(255),
    [ZAAKIDENTIFICATIE] VARCHAR(255),
    [ZAAKNIVEAU] VARCHAR(255)
);

CREATE TABLE [PRODUCTOFDIENST] (
    [PRODUCTOFDIENST_ID] INT PRIMARY KEY,
    [AFHANDELTIJD] DATETIME2,
    [INGEBRUIK] BIT,
    [NAAM] VARCHAR(80)
);

CREATE TABLE [FORMULIERSOORTVELD] (
    [FORMULIERSOORTVELD_ID] INT PRIMARY KEY,
    [HEEFT_VELDEN_FORMULIERSOORT_ID] INT,
    [HELPTEKST] NVARCHAR(MAX),
    [ISVERPLICHT] BIT,
    [LABEL] VARCHAR(80),
    [MAXLENGTE] INT,
    [VELDNAAM] VARCHAR(255),
    [VELDTYPE] VARCHAR(255)
);

CREATE TABLE [AANVRAAGOFMELDING] (
    [AANVRAAGOFMELDING_ID] INT PRIMARY KEY,
    [AANVRAAG_MET__FORMULIERSOORT_ID] INT,
    [AFGEHANDELD] BIT,
    [CATEGORIE] VARCHAR(200),
    [CATEGORIECODE] VARCHAR(80),
    [DATUMAANMAAK] DATE,
    [DATUMAFHANDELING] DATE,
    [DATUMBEGINSTATUS] DATE,
    [DATUMEINDESTATUS] DATE,
    [HOOFDCATEGORIE] VARCHAR(80),
    [HOOFDCATEGORIECODE] VARCHAR(80),
    [IDENTIFICATIE] VARCHAR(255),
    [KANAAL] VARCHAR(80),
    [KAN_LEIDEN_TOT_KLANTCONTACT_ID] INT,
    [ONDERWERP] VARCHAR(200),
    [ONDERWERPCODE] VARCHAR(80),
    [SOORT] VARCHAR(80),
    [STATUS] VARCHAR(80),
    [STATUSCODE] VARCHAR(80),
    [STATUSVOLGORDE] VARCHAR(80),
    [SUBCATEGORIE] VARCHAR(200),
    [SUBCATEGORIECODE] VARCHAR(80)
);

CREATE TABLE [ZAAKTYPE] (
    [ZAAKTYPE_ID] INT PRIMARY KEY,
    [ARCHIEFCODE] VARCHAR(20),
    [DATUMBEGINGELDIGHEIDZAAKTYPE] DATE,
    [DATUMEINDEGELDIGHEIDZAAKTYPE] DATE,
    [DOORLOOPTIJDBEHANDELING] DATETIME2,
    [INDICATIEPUBLICATIE] VARCHAR(255),
    [IS_VERANTWOORDELIJKE_VOOR_MEDEWERKER_ID] INT,
    [PUBLICATIETEKST] VARCHAR(255),
    [SERVICENORMBEHANDELING] VARCHAR(255),
    [TREFWOORD] VARCHAR(255),
    [VERTROUWELIJKAANDUIDING] VARCHAR(20),
    [ZAAKCATEGORIE] VARCHAR(255),
    [ZAAKTYPEOMSCHRIJVING] VARCHAR(80),
    [ZAAKTYPEOMSCHRIJVINGGENERIEK] VARCHAR(80)
);

CREATE TABLE [KP_KLNTCNTCT_PRDCTFDNST] (
    [KP_KLNTCNTCT_PRDCTFDNST_ID] INT PRIMARY KEY,
    [KLANTCONTACT_ID] INT,
    [PRODUCTOFDIENST_ID] INT
);

CREATE TABLE [AANVRAAGDATA] (
    [AANVRAAGDATA_ID] INT PRIMARY KEY,
    [DATA] VARCHAR(255),
    [HEEFT_DATA_AANVRAAGOFMELDING_ID] INT,
    [IS_CONFORM_FORMULIERSOORTVELD_ID] INT,
    [VELD] VARCHAR(255)
);

CREATE TABLE [BETALING] (
    [BETALING_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [DATUMTIJD] DATETIME2,
    [HEEFT_BETALING_ZAAK_ID] INT,
    [OMSCHRIJVING] VARCHAR(200),
    [VALUTA] VARCHAR(255)
);

CREATE TABLE [KP_ZK_DCMNT] (
    [KP_ZK_DCMNT_ID] INT PRIMARY KEY,
    [ZAAK_ID] INT,
    [DOCUMENT_ID] INT
);

ALTER TABLE [KP_FRMLRSRT_ZKTYP] ADD CONSTRAINT FK_KP_FRMLRSRT_ZKTYP_1 FOREIGN KEY ([FORMULIERSOORT_ID]) REFERENCES [FORMULIERSOORT] ([FORMULIERSOORT_ID]);
-- FORMULIERSOORT (many-to-many junction, Connector_ID: 369)

ALTER TABLE [KP_FRMLRSRT_ZKTYP] ADD CONSTRAINT FK_KP_FRMLRSRT_ZKTYP_2 FOREIGN KEY ([ZAAKTYPE_ID]) REFERENCES [ZAAKTYPE] ([ZAAKTYPE_ID]);
-- ZAAKTYPE (many-to-many junction, Connector_ID: 369)

ALTER TABLE [KP_ANVRGFMLDNG_ONDRWRP] ADD CONSTRAINT FK_KP_ANVRGFMLDNG_ONDRWRP_1 FOREIGN KEY ([AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- AANVRAAGOFMELDING (many-to-many junction, Connector_ID: 381)

ALTER TABLE [KP_ANVRGFMLDNG_ONDRWRP] ADD CONSTRAINT FK_KP_ANVRGFMLDNG_ONDRWRP_2 FOREIGN KEY ([ONDERWERP_ID]) REFERENCES [ONDERWERP] ([ONDERWERP_ID]);
-- ONDERWERP (many-to-many junction, Connector_ID: 381)

ALTER TABLE [KP_KLNTCNTCT_PRDCTFDNST] ADD CONSTRAINT FK_KP_KLNTCNTCT_PRDCTFDNST_1 FOREIGN KEY ([KLANTCONTACT_ID]) REFERENCES [KLANTCONTACT] ([KLANTCONTACT_ID]);
-- KLANTCONTACT (many-to-many junction, Connector_ID: 2055)

ALTER TABLE [KP_KLNTCNTCT_PRDCTFDNST] ADD CONSTRAINT FK_KP_KLNTCNTCT_PRDCTFDNST_2 FOREIGN KEY ([PRODUCTOFDIENST_ID]) REFERENCES [PRODUCTOFDIENST] ([PRODUCTOFDIENST_ID]);
-- PRODUCTOFDIENST (many-to-many junction, Connector_ID: 2055)

ALTER TABLE [KP_ZK_DCMNT] ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY ([ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE [KP_ZK_DCMNT] ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY ([DOCUMENT_ID]) REFERENCES [DOCUMENT] ([DOCUMENT_ID]);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE [KP_ZK_MDWRKR] ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY ([ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE [KP_ZK_MDWRKR] ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY ([MEDEWERKER_ID]) REFERENCES [MEDEWERKER] ([MEDEWERKER_ID]);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE [ONDERWERP] ADD CONSTRAINT FK_ONDERWERP_HOOFDONDERWERP FOREIGN KEY ([HOOFDONDERWERP_ONDERWERP_ID]) REFERENCES [ONDERWERP] ([ONDERWERP_ID]);
-- HOOFDONDERWERP (0..* to 1, Connector_ID: 361)

ALTER TABLE [FORMULIERSOORTVELD] ADD CONSTRAINT FK_FORMULIERSOORTVELD_HEEFT_VELDEN FOREIGN KEY ([HEEFT_VELDEN_FORMULIERSOORT_ID]) REFERENCES [FORMULIERSOORT] ([FORMULIERSOORT_ID]);
-- HEEFT_VELDEN (1 to 0..*, Connector_ID: 368)

ALTER TABLE [DOCUMENT] ADD CONSTRAINT FK_DOCUMENT_HEEFT_DOCUMENTEN FOREIGN KEY ([HEEFT_DOCUMENTEN_AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- HEEFT_DOCUMENTEN (0..1 to 0..*, Connector_ID: 378)

ALTER TABLE [AANVRAAGOFMELDING] ADD CONSTRAINT FK_AANVRAAGOFMELDING_AANVRAAG_MET_ FOREIGN KEY ([AANVRAAG_MET__FORMULIERSOORT_ID]) REFERENCES [FORMULIERSOORT] ([FORMULIERSOORT_ID]);
-- AANVRAAG_MET_ (0..* to 0..1, Connector_ID: 379)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_KAN_LEIDEN_TOT FOREIGN KEY ([KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 380)

ALTER TABLE [AANVRAAGDATA] ADD CONSTRAINT FK_AANVRAAGDATA_HEEFT_DATA FOREIGN KEY ([HEEFT_DATA_AANVRAAGOFMELDING_ID]) REFERENCES [AANVRAAGOFMELDING] ([AANVRAAGOFMELDING_ID]);
-- HEEFT_DATA (1 to 0..*, Connector_ID: 382)

ALTER TABLE [AANVRAAGDATA] ADD CONSTRAINT FK_AANVRAAGDATA_IS_CONFORM FOREIGN KEY ([IS_CONFORM_FORMULIERSOORTVELD_ID]) REFERENCES [FORMULIERSOORTVELD] ([FORMULIERSOORTVELD_ID]);
-- IS_CONFORM (0..* to 1, Connector_ID: 383)

ALTER TABLE [KLANTCONTACT] ADD CONSTRAINT FK_KLANTCONTACT_LOCATIE FOREIGN KEY ([LOCATIE_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID]) REFERENCES [VESTIGINGVANZAAKBEHANDELENDEORGANISATIE] ([VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID]);
-- LOCATIE (0..* to 0..1, Connector_ID: 2052)

ALTER TABLE [AANVRAAGOFMELDING] ADD CONSTRAINT FK_AANVRAAGOFMELDING_KAN_LEIDEN_TOT FOREIGN KEY ([KAN_LEIDEN_TOT_KLANTCONTACT_ID]) REFERENCES [KLANTCONTACT] ([KLANTCONTACT_ID]);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 2057)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_HEEFT FOREIGN KEY ([HEEFT_HEFFING_ID]) REFERENCES [HEFFING] ([HEFFING_ID]);
-- HEEFT (1 to 0..1, Connector_ID: 2103)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY ([HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE [BETALING] ADD CONSTRAINT FK_BETALING_HEEFT_BETALING FOREIGN KEY ([HEEFT_BETALING_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT_BETALING (0..1 to 0..*, Connector_ID: 2114)

ALTER TABLE [KLANTCONTACT] ADD CONSTRAINT FK_KLANTCONTACT_HEEFT_BETREKKING_OP FOREIGN KEY ([HEEFT_BETREKKING_OP_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT_BETREKKING_OP (0..* to 0..1, Connector_ID: 2115)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY ([IS_VAN_ZAAKTYPE_ID]) REFERENCES [ZAAKTYPE] ([ZAAKTYPE_ID]);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY ([IS_DEELZAAK_VAN_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE [ZAAKTYPE] ADD CONSTRAINT FK_ZAAKTYPE_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY ([IS_VERANTWOORDELIJKE_VOOR_MEDEWERKER_ID]) REFERENCES [MEDEWERKER] ([MEDEWERKER_ID]);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2170)

ALTER TABLE [KLANTCONTACT] ADD CONSTRAINT FK_KLANTCONTACT_IS_GEVOERD_DOOR FOREIGN KEY ([IS_GEVOERD_DOOR_MEDEWERKER_ID]) REFERENCES [MEDEWERKER] ([MEDEWERKER_ID]);
-- IS_GEVOERD_DOOR (0..* to 0..1, Connector_ID: 2186)

