CREATE TABLE SOORTEN_KLANTCONTACT_ENUM (
    SOORTEN_KLANTCONTACT_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO SOORTEN_KLANTCONTACT_ENUM (SOORTEN_KLANTCONTACT_ENUM_ID, VALUE) VALUES
    (1, 'BALIE'),
    (2, 'BRIEF'),
    (3, 'INTERNET'),
    (4, 'SELFSERVICELOKET'),
    (5, 'TELEFONISCH');

CREATE TABLE ZAAK (
    ZAAK_ID NUMBER PRIMARY KEY,
    ARCHIEFNOMINATIE VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMEINDEGEPLAND DATE,
    DATUMEINDEUITERLIJKEAFDOENING DATE,
    DATUMLAATSTEBETALING DATE,
    DATUMPUBLICATIE DATE,
    DATUMREGISTRATIE DATE,
    DATUMSTART DATE,
    DATUMVERNIETIGINGDOSSIER DATE,
    DUURVERLENGING VARCHAR2(255),
    HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID NUMBER,
    INDICATIEBETALING VARCHAR2(255),
    INDICATIEDEELZAKEN NUMBER(1),
    INDICATIEOPSCHORTING VARCHAR2(255),
    IS_DEELZAAK_VAN_ZAAK_ID NUMBER,
    LEGES VARCHAR2(100),
    OMSCHRIJVING VARCHAR2(80),
    OMSCHRIJVINGRESULTAAT VARCHAR2(80),
    REDENOPSCHORTING VARCHAR2(200),
    REDENVERLENGING VARCHAR2(200),
    TOELICHTING VARCHAR2(255),
    TOELICHTINGRESULTAAT VARCHAR2(255),
    VERTROUWELIJKHEID VARCHAR2(255),
    ZAAKIDENTIFICATIE VARCHAR2(255),
    ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (
    VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID NUMBER PRIMARY KEY
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    ACHTERNAAM VARCHAR2(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR2(255),
    EXTERN NUMBER(1),
    FUNCTIE VARCHAR2(50),
    GESLACHTSAANDUIDING VARCHAR2(255),
    MEDEWERKERIDENTIFICATIE VARCHAR2(255),
    MEDEWERKERTOELICHTING VARCHAR2(255),
    ROEPNAAM VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    VOORLETTERS VARCHAR2(20),
    VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE KLANTCONTACT (
    KLANTCONTACT_ID NUMBER PRIMARY KEY,
    EINDTIJD TIMESTAMP,
    HEEFT_BETREKKING_OP_ZAAK_ID NUMBER,
    IS_GEVOERD_DOOR_MEDEWERKER_ID NUMBER,
    IS_VAN_SOORT_SOORTEN_KLANTCONTACT_ENUM_ID NUMBER,
    KANAAL VARCHAR2(20),
    LOCATIE_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID NUMBER,
    NOTITIE CLOB,
    STARTTIJD TIMESTAMP,
    TIJDSDUUR TIMESTAMP,
    TOELICHTING CLOB,
    WACHTTIJDTOTAAL TIMESTAMP
);

CREATE TABLE KP_ZK_MDWRKR (
    KP_ZK_MDWRKR_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    MEDEWERKER_ID NUMBER
);

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_LOCATIE FOREIGN KEY (LOCATIE_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID) REFERENCES VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID);
-- LOCATIE (0..* to 0..1, Connector_ID: 2052)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_IS_VAN_SOORT FOREIGN KEY (IS_VAN_SOORT_ENUM_ID) REFERENCES SOORTEN_KLANTCONTACT_ENUM (SOORTEN_KLANTCONTACT_ENUM_ID);
-- IS_VAN_SOORT (1 to 0..*, Connector_ID: 2056)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_HEEFT_BETREKKING_OP FOREIGN KEY (HEEFT_BETREKKING_OP_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP (0..* to 0..1, Connector_ID: 2115)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE KLANTCONTACT ADD CONSTRAINT FK_KLANTCONTACT_IS_GEVOERD_DOOR FOREIGN KEY (IS_GEVOERD_DOOR_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- IS_GEVOERD_DOOR (0..* to 0..1, Connector_ID: 2186)

