CREATE TABLE ARCHIEF (
    ARCHIEF_ID VARCHAR(255) PRIMARY KEY,
        ARCHIEFNUMMER VARCHAR(20),
        HEEFT_RECHTHEBBENDE_ID VARCHAR(255),
        NAAM VARCHAR(80),
        OMSCHRIJVING TEXT,
        OPENBAARHEIDSBEPERKING INTEGER
);

CREATE TABLE ARCHIEFCATEGORIE (
    ARCHIEFCATEGORIE_ID VARCHAR(255) PRIMARY KEY,
        NAAM VARCHAR(80),
        NUMMER VARCHAR(20),
        OMSCHRIJVING TEXT
);

CREATE TABLE ARCHIEFSTUK (
    ARCHIEFSTUK_ID VARCHAR(255) PRIMARY KEY,
        BESCHRIJVING TEXT,
        HEEFT_NADERE_TOEGANG_ID VARCHAR(255),
        INVENTARISNUMMER VARCHAR(20),
        IS_ONDERDEEL_VAN_ARCHIEF_ID VARCHAR(255),
        OMVANG VARCHAR(255),
        OPENBAARHEIDSBEPERKING BOOLEAN,
        TREFWOORDEN VARCHAR(200),
        UITERLIJKEVORM VARCHAR(255)
);

CREATE TABLE INDELING (
    INDELING_ID VARCHAR(255) PRIMARY KEY,
        HOORT_BIJ_ARCHIEF_ID VARCHAR(255),
        INDELINGSOORT VARCHAR(20),
        NAAM VARCHAR(80),
        NUMMER VARCHAR(20),
        OMSCHRIJVING TEXT,
        VALT_BINNEN_ARCHIEFSTUK_ID VARCHAR(255),
        VALT_BINNEN_INDELING_ID VARCHAR(255)
);

CREATE TABLE INDEX (
    INDEX_ID VARCHAR(255) PRIMARY KEY,
        INDEXNAAM VARCHAR(80),
        INDEXWAARDE VARCHAR(80)
);

CREATE TABLE KP_ARCHF (
    KP_ARCHF_ID VARCHAR(255) PRIMARY KEY,
    ARCHIEF_ID VARCHAR(255),
    ARCHIEFCATEGORIE_ID VARCHAR(255)
);

CREATE TABLE KP_ARCHFSTK (
    KP_ARCHFSTK_ID VARCHAR(255) PRIMARY KEY,
    ARCHIEFSTUK_ID VARCHAR(255),
    ORDENINGSSCHEMA_ID VARCHAR(255)
);

CREATE TABLE NADERE_TOEGANG (
    NADERE_TOEGANG_ID VARCHAR(255) PRIMARY KEY,
        WORDT_BESCHREVEN_INDEX_ID VARCHAR(255)
);

CREATE TABLE ORDENINGSSCHEMA (
    ORDENINGSSCHEMA_ID VARCHAR(255) PRIMARY KEY,
        NAAM VARCHAR(80),
        TEXT TEXT
);

CREATE TABLE PERIODE (
    PERIODE_ID VARCHAR(255) PRIMARY KEY,
        DATUMEINDE DATE,
        DATUMSTART DATE,
        OMSCHRIJVING VARCHAR(255)
);

CREATE TABLE RECHTHEBBENDE (
    RECHTHEBBENDE_ID VARCHAR(255) PRIMARY KEY
);

ALTER TABLE KP_ARCHF ADD CONSTRAINT FK_KP_ARCHF_1 FOREIGN KEY (ARCHIEF_ID) REFERENCES ARCHIEF (ARCHIEF_ID);
-- ARCHIEF (many-to-many junction, Connector_ID: 1181)

ALTER TABLE KP_ARCHF ADD CONSTRAINT FK_KP_ARCHF_2 FOREIGN KEY (PERIODE_ID) REFERENCES PERIODE (PERIODE_ID);
-- PERIODE (many-to-many junction, Connector_ID: 1181)

ALTER TABLE KP_ARCHF ADD CONSTRAINT FK_KP_ARCHF_1 FOREIGN KEY (ARCHIEF_ID) REFERENCES ARCHIEF (ARCHIEF_ID);
-- ARCHIEF (many-to-many junction, Connector_ID: 1183)

ALTER TABLE KP_ARCHF ADD CONSTRAINT FK_KP_ARCHF_2 FOREIGN KEY (ARCHIEFCATEGORIE_ID) REFERENCES ARCHIEFCATEGORIE (ARCHIEFCATEGORIE_ID);
-- ARCHIEFCATEGORIE (many-to-many junction, Connector_ID: 1183)

ALTER TABLE KP_ARCHFSTK ADD CONSTRAINT FK_KP_ARCHFSTK_1 FOREIGN KEY (ARCHIEFSTUK_ID) REFERENCES ARCHIEFSTUK (ARCHIEFSTUK_ID);
-- ARCHIEFSTUK (many-to-many junction, Connector_ID: 1171)

ALTER TABLE KP_ARCHFSTK ADD CONSTRAINT FK_KP_ARCHFSTK_2 FOREIGN KEY (PERIODE_ID) REFERENCES PERIODE (PERIODE_ID);
-- PERIODE (many-to-many junction, Connector_ID: 1171)

ALTER TABLE KP_ARCHFSTK ADD CONSTRAINT FK_KP_ARCHFSTK_1 FOREIGN KEY (ARCHIEFSTUK_ID) REFERENCES ARCHIEFSTUK (ARCHIEFSTUK_ID);
-- ARCHIEFSTUK (many-to-many junction, Connector_ID: 1173)

ALTER TABLE KP_ARCHFSTK ADD CONSTRAINT FK_KP_ARCHFSTK_2 FOREIGN KEY (ORDENINGSSCHEMA_ID) REFERENCES ORDENINGSSCHEMA (ORDENINGSSCHEMA_ID);
-- ORDENINGSSCHEMA (many-to-many junction, Connector_ID: 1173)

ALTER TABLE ARCHIEF ADD CONSTRAINT FK_ARCHIEF_HEEFT FOREIGN KEY (HEEFT_RECHTHEBBENDE_ID) REFERENCES RECHTHEBBENDE (RECHTHEBBENDE_ID);
-- HEEFT (0..* to 0..1, Connector_ID: 1182)

ALTER TABLE ARCHIEFSTUK ADD CONSTRAINT FK_ARCHIEFSTUK_HEEFT FOREIGN KEY (HEEFT_NADERE_TOEGANG_ID) REFERENCES NADERE_TOEGANG (NADERE_TOEGANG_ID);
-- HEEFT (1 to 0..1, Connector_ID: 1172)

ALTER TABLE ARCHIEFSTUK ADD CONSTRAINT FK_ARCHIEFSTUK_IS_ONDERDEEL_VAN FOREIGN KEY (IS_ONDERDEEL_VAN_ARCHIEF_ID) REFERENCES ARCHIEF (ARCHIEF_ID);
-- IS_ONDERDEEL_VAN (0..* to 1, Connector_ID: 1180)

ALTER TABLE INDELING ADD CONSTRAINT FK_INDELING_HOORT_BIJ FOREIGN KEY (HOORT_BIJ_ARCHIEF_ID) REFERENCES ARCHIEF (ARCHIEF_ID);
-- HOORT_BIJ (0..* to 1, Connector_ID: 1179)

ALTER TABLE INDELING ADD CONSTRAINT FK_INDELING_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_INDELING_ID) REFERENCES INDELING (INDELING_ID);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 1165)

ALTER TABLE INDELING ADD CONSTRAINT FK_INDELING_VALT_BINNEN_2 FOREIGN KEY (VALT_BINNEN_ARCHIEFSTUK_ID) REFERENCES ARCHIEFSTUK (ARCHIEFSTUK_ID);
-- VALT_BINNEN (0..1 to 0..*, Connector_ID: 1170)

ALTER TABLE NADERE_TOEGANG ADD CONSTRAINT FK_NADERE_TOEGANG_WORDT_BESCHREVEN FOREIGN KEY (WORDT_BESCHREVEN_INDEX_ID) REFERENCES INDEX (INDEX_ID);
-- WORDT_BESCHREVEN (1 to 1..*, Connector_ID: 1164)

