CREATE TABLE `FOTO` (
    `FOTO_ID` INT PRIMARY KEY,
    `BESTANDSGROOTTE` INT,
    `BESTANDSNAAM` VARCHAR(200),
    `BESTANDSTYPE` VARCHAR(80),
    `DATUMTIJD` DATETIME,
    `LOCATIE` VARCHAR(255),
    `PIXELSX` INT,
    `PIXELSY` INT
) ENGINE=InnoDB;

CREATE TABLE `OBJECT` (
    `OBJECT_ID` INT PRIMARY KEY,
    `ADRESBINNENLAND` VARCHAR(255),
    `ADRESBUITENLAND` VARCHAR(200),
    `DOMEIN` VARCHAR(200),
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(50),
    `INDICATIERISICO` BOOLEAN,
    `KADASTRALEAANDUIDING` VARCHAR(255),
    `NAAM` VARCHAR(200),
    `OBJECTTYPE` VARCHAR(255),
    `TOELICHTING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BEOORDELINGSOORT_ENUM` (
    `BEOORDELINGSOORT_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `BEOORDELINGSOORT_ENUM` (`BEOORDELINGSOORT_ENUM_ID`, VALUE) VALUES
    (1, 'NIET_OKE'),
    (2, 'NIET_RELEVANT'),
    (3, 'OKE');

CREATE TABLE `AANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `AFGEHANDELD` BOOLEAN,
    `CATEGORIE` VARCHAR(200),
    `CATEGORIECODE` VARCHAR(80),
    `DATUMAANMAAK` DATE,
    `DATUMAFHANDELING` DATE,
    `DATUMBEGINSTATUS` DATE,
    `DATUMEINDESTATUS` DATE,
    `HOOFDCATEGORIE` VARCHAR(80),
    `HOOFDCATEGORIECODE` VARCHAR(80),
    `IDENTIFICATIE` VARCHAR(255),
    `KANAAL` VARCHAR(80),
    `ONDERWERP` VARCHAR(200),
    `ONDERWERPCODE` VARCHAR(80),
    `SOORT` VARCHAR(80),
    `STATUS` VARCHAR(80),
    `STATUSCODE` VARCHAR(80),
    `STATUSVOLGORDE` VARCHAR(80),
    `SUBCATEGORIE` VARCHAR(200),
    `SUBCATEGORIECODE` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `VTH_MELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `ACTIVITEIT` VARCHAR(80),
    `BEOORDELING_ENUM_ID` INT,
    `DATUMSEPONERING` DATE,
    `DATUMTIJDTOT` DATETIME,
    `GESEPONEERD` BOOLEAN,
    `HEEFT_FOTO_ID` INT,
    `LOCATIE` VARCHAR(255),
    `ORGANISATIEONDERDEEL` VARCHAR(80),
    `OVERTREDINGSCODE` VARCHAR(20),
    `OVERTREDINGSGROEP` VARCHAR(200),
    `REFERENTIENUMMER` VARCHAR(80),
    `RESULTAAT` VARCHAR(80),
    `SOORTVTHMELDING` VARCHAR(80),
    `STATUS` VARCHAR(255),
    `STRAATNAAM` VARCHAR(255),
    `TAAKTYPE` VARCHAR(80),
    `ZAAKNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `FIETSREGISTRATIE` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `GELABELD` BOOLEAN,
    `VERWIJDERD` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `COMBIBON` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `SANCTIE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `WAARNEMING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `KP_VTH_MLDNG_OBJCT` (
    `KP_VTH_MLDNG_OBJCT_ID` INT PRIMARY KEY,
    `VTH_MELDING_ID` INT,
    `OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `BOA` (
    `BOA_ID` INT PRIMARY KEY,
    `VERBALISANT_VTH_MELDING_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `COMBIBON` ADD CONSTRAINT FK_COMBIBON_GEN_VTH_MELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `VTH_MELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to VTH_MELDING

ALTER TABLE `FIETSREGISTRATIE` ADD CONSTRAINT FK_FIETSREGISTRATIE_GEN_VTH_MELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `VTH_MELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to VTH_MELDING

ALTER TABLE `VTH_MELDING` ADD CONSTRAINT FK_VTH_MELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE `WAARNEMING` ADD CONSTRAINT FK_WAARNEMING_GEN_VTH_MELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `VTH_MELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to VTH_MELDING

ALTER TABLE `KP_VTH_MLDNG_OBJCT` ADD CONSTRAINT FK_KP_VTH_MLDNG_OBJCT_1 FOREIGN KEY (`VTH_MELDING_ID`) REFERENCES `VTH_MELDING` (`AANVRAAGOFMELDING_ID`);
-- VTH_MELDING (many-to-many junction, Connector_ID: 1297)

ALTER TABLE `KP_VTH_MLDNG_OBJCT` ADD CONSTRAINT FK_KP_VTH_MLDNG_OBJCT_2 FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- OBJECT (many-to-many junction, Connector_ID: 1297)

ALTER TABLE `VTH_MELDING` ADD CONSTRAINT FK_VTH_MELDING_HEEFT FOREIGN KEY (`HEEFT_FOTO_ID`) REFERENCES `FOTO` (`FOTO_ID`);
-- HEEFT (0..1 to 0..*, Connector_ID: 1298)

ALTER TABLE `BOA` ADD CONSTRAINT FK_BOA_VERBALISANT FOREIGN KEY (`VERBALISANT_VTH_MELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- VERBALISANT (1 to 0..*, Connector_ID: 1326)

ALTER TABLE `VTH_MELDING` ADD CONSTRAINT FK_VTH_MELDING_BEOORDELING_ENUM_ID FOREIGN KEY (`BEOORDELING_ENUM_ID`) REFERENCES `BEOORDELINGSOORT_ENUM` (`BEOORDELINGSOORT_ENUM_ID`);
-- BEOORDELING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

