CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    EMAILADRES VARCHAR2(80),
    FAXNUMMER VARCHAR2(20),
    IDENTIFICATIE VARCHAR2(255),
    KVKNUMMER VARCHAR2(20),
    NAAM VARCHAR2(200),
    RECHTSVORM VARCHAR2(100),
    REKENINGNUMMER VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE HEFFINGSOORT_ENUM (
    HEFFINGSOORT_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO HEFFINGSOORT_ENUM (HEFFINGSOORT_ENUM_ID, VALUE) VALUES
    (1, 'LEGES'),
    (2, 'PRECARIO');

CREATE TABLE VORDERINGREGEL (
    VORDERINGREGEL_ID NUMBER PRIMARY KEY,
    AANGEMAAKT_DOOR VARCHAR2(50),
    AANMAAKDATUM DATE,
    BEDRAG_EXCL_BTW NUMBER(10,2),
    BEDRAG_INCL_BTW NUMBER(10,2),
    BTWCATEGORIE VARCHAR2(50),
    GEMUTEERD_DOOR VARCHAR2(50),
    MUTATIEDATUM DATE,
    OMSCHRIJVING VARCHAR2(50),
    PERIODIEK VARCHAR2(50),
    TYPE VARCHAR2(50)
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR2(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR2(200),
    DOCUMENTIDENTIFICATIE VARCHAR2(255),
    DOCUMENTTITEL VARCHAR2(200),
    VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE HEFFINGGRONDSLAG (
    HEFFINGGRONDSLAG_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2),
    DOMEIN VARCHAR2(80),
    HOOFDSTUK NUMBER,
    OMSCHRIJVING VARCHAR2(255),
    PARAGRAAF VARCHAR2(255)
);

CREATE TABLE STATUSTYPE (
    STATUSTYPE_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDSTATUSTYPE DATE,
    DATUMEINDEGELDIGHEIDSTATUSTYPE DATE,
    DOORLOOPTIJDSTATUS TIMESTAMP,
    STATUSTYPEOMSCHRIJVING VARCHAR2(80),
    STATUSTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80),
    STATUSTYPEVOLGNUMMER VARCHAR2(255)
);

CREATE TABLE INDIENER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY
);

CREATE TABLE HEFFING (
    HEFFING_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2),
    BETREFT_VORDERINGREGEL_ID NUMBER,
    CODE VARCHAR2(80),
    DATUMINDIENING DATE,
    GEFACTUREERD NUMBER(1),
    HEEFT_GRONDSLAG_HEFFINGGRONDSLAG_ID NUMBER,
    INREKENING VARCHAR2(255),
    NUMMER NUMBER,
    RUNNUMMER NUMBER,
    SOORT_HEFFINGSOORT_ENUM_ID NUMBER
);

CREATE TABLE HEFFINGSVERORDENING (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    VERMELD_IN_HEFFINGGRONDSLAG_ID NUMBER
);

CREATE TABLE ZAAKTYPE (
    ZAAKTYPE_ID NUMBER PRIMARY KEY,
    ARCHIEFCODE VARCHAR2(20),
    DATUMBEGINGELDIGHEIDZAAKTYPE DATE,
    DATUMEINDEGELDIGHEIDZAAKTYPE DATE,
    DOORLOOPTIJDBEHANDELING TIMESTAMP,
    HEEFT_HEFFINGGRONDSLAG_ID NUMBER,
    HEEFT_STATUSTYPE_ID NUMBER,
    INDICATIEPUBLICATIE VARCHAR2(255),
    PUBLICATIETEKST VARCHAR2(255),
    SERVICENORMBEHANDELING VARCHAR2(255),
    TREFWOORD VARCHAR2(255),
    VERTROUWELIJKAANDUIDING VARCHAR2(20),
    ZAAKCATEGORIE VARCHAR2(255),
    ZAAKTYPEOMSCHRIJVING VARCHAR2(80),
    ZAAKTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80)
);

CREATE TABLE STATUS (
    STATUS_ID NUMBER PRIMARY KEY,
    DATUMSTATUSGEZET DATE,
    INDICATIEIAATSTGEZETTESTATUS VARCHAR2(255),
    IS_VAN_STATUSTYPE_ID NUMBER,
    STATUSTOELICHTING VARCHAR2(255)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    ACHTERNAAM VARCHAR2(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR2(255),
    EXTERN NUMBER(1),
    FUNCTIE VARCHAR2(50),
    GESLACHTSAANDUIDING VARCHAR2(255),
    IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID NUMBER,
    MEDEWERKERIDENTIFICATIE VARCHAR2(255),
    MEDEWERKERTOELICHTING VARCHAR2(255),
    ROEPNAAM VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    VOORLETTERS VARCHAR2(20),
    VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE ZAAK (
    ZAAK_ID NUMBER PRIMARY KEY,
    ARCHIEFNOMINATIE VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMEINDEGEPLAND DATE,
    DATUMEINDEUITERLIJKEAFDOENING DATE,
    DATUMLAATSTEBETALING DATE,
    DATUMPUBLICATIE DATE,
    DATUMREGISTRATIE DATE,
    DATUMSTART DATE,
    DATUMVERNIETIGINGDOSSIER DATE,
    DUURVERLENGING VARCHAR2(255),
    HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID NUMBER,
    HEEFT_HEFFING_ID NUMBER,
    HEEFT_STATUS_ID NUMBER,
    INDICATIEBETALING VARCHAR2(255),
    INDICATIEDEELZAKEN NUMBER(1),
    INDICATIEOPSCHORTING VARCHAR2(255),
    IS_DEELZAAK_VAN_ZAAK_ID NUMBER,
    IS_VAN_ZAAKTYPE_ID NUMBER,
    LEGES VARCHAR2(100),
    OMSCHRIJVING VARCHAR2(80),
    OMSCHRIJVINGRESULTAAT VARCHAR2(80),
    REDENOPSCHORTING VARCHAR2(200),
    REDENVERLENGING VARCHAR2(200),
    TOELICHTING VARCHAR2(255),
    TOELICHTINGRESULTAAT VARCHAR2(255),
    VERTROUWELIJKHEID VARCHAR2(255),
    ZAAKIDENTIFICATIE VARCHAR2(255),
    ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE BETROKKENE (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(200),
    IDENTIFICATIE VARCHAR2(50),
    IS_MEDEWERKER_ID NUMBER,
    NAAM VARCHAR2(200)
);

CREATE TABLE VTHZAAK (
    ZAAK_ID NUMBER PRIMARY KEY,
    BEHANDELAAR VARCHAR2(20),
    BEVOEGDGEZAG VARCHAR2(50),
    PRIORITERING NUMBER,
    TEAMBEHANDELAAR VARCHAR2(20),
    UITVOERENDEINSTANTIE VARCHAR2(50),
    VERKAMERING NUMBER(1)
);

CREATE TABLE KP_ZK_DCMNT (
    KP_ZK_DCMNT_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    DOCUMENT_ID NUMBER
);

CREATE TABLE AANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID NUMBER PRIMARY KEY,
    AFGEHANDELD NUMBER(1),
    CATEGORIE VARCHAR2(200),
    CATEGORIECODE VARCHAR2(80),
    DATUMAANMAAK DATE,
    DATUMAFHANDELING DATE,
    DATUMBEGINSTATUS DATE,
    DATUMEINDESTATUS DATE,
    HEEFT_DOCUMENTEN_DOCUMENT_ID NUMBER,
    HOOFDCATEGORIE VARCHAR2(80),
    HOOFDCATEGORIECODE VARCHAR2(80),
    IDENTIFICATIE VARCHAR2(255),
    INGEDIEND_DOOR_INDIENER_ID NUMBER,
    KANAAL VARCHAR2(80),
    KAN_LEIDEN_TOT_ZAAK_ID NUMBER,
    MELDER_RECHTSPERSOON_ID NUMBER,
    ONDERWERP VARCHAR2(200),
    ONDERWERPCODE VARCHAR2(80),
    SOORT VARCHAR2(80),
    STATUS VARCHAR2(80),
    STATUSCODE VARCHAR2(80),
    STATUSVOLGORDE VARCHAR2(80),
    SUBCATEGORIE VARCHAR2(200),
    SUBCATEGORIECODE VARCHAR2(80)
);

CREATE TABLE BESLUIT (
    BESLUIT_ID NUMBER PRIMARY KEY,
    BESLUITIDENTIFICATIE VARCHAR2(50),
    BESLUITTOELICHTING VARCHAR2(255),
    DATUMBESLUIT DATE,
    DATUMPUBLICATIE DATE,
    DATUMSTART DATE,
    DATUMUITERLIJKEREACTIE DATE,
    DATUMVERVAL DATE,
    DATUMVERZENDING DATE,
    IS_UITKOMST_VAN_ZAAK_ID NUMBER,
    IS_VASTGELEGD_IN_DOCUMENT_ID NUMBER,
    OMSCHRIJVING VARCHAR2(200),
    REDENVERVAL VARCHAR2(255)
);

CREATE TABLE KP_ZK_MDWRKR (
    KP_ZK_MDWRKR_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    MEDEWERKER_ID NUMBER
);

CREATE TABLE KP_BTRKKN_ZK (
    KP_BTRKKN_ZK_ID NUMBER PRIMARY KEY,
    BETROKKENE_ID NUMBER,
    ZAAK_ID NUMBER
);

CREATE TABLE VORDERING (
    VORDERING_ID NUMBER PRIMARY KEY,
    AANGEMAAKTDOOR VARCHAR2(50),
    BEDRAGBTW NUMBER(10,2),
    DATUMAANMAAK DATE,
    DATUMMUTATIE DATE,
    GEACCORDEERD VARCHAR2(50),
    GEACCORDEERDDOOR VARCHAR2(50),
    GEACCORDEERDOP VARCHAR2(255),
    GEEXPORTEERD VARCHAR2(50),
    GEMUTEERDDOOR VARCHAR2(50),
    HEEFT_VORDERINGREGEL_ID NUMBER,
    HEEFT_VTHZAAK_ID NUMBER,
    OMSCHRIJVING CLOB,
    TOTAALBEDRAG NUMBER(10,2),
    TOTAALBEDRAGINCLUSIEF NUMBER(10,2),
    VORDERINGNUMMER VARCHAR2(50)
);

CREATE TABLE INSPECTIE (
    INSPECTIE_ID NUMBER PRIMARY KEY,
    AANGEMAAKTDOOR VARCHAR2(50),
    DATUMAANMAAK DATE,
    DATUMGEPLAND DATE,
    DATUMINSPECTIE DATE,
    DATUMMUTATIE DATE,
    GEMUTEERDDOOR VARCHAR2(50),
    HEEFT_VTHZAAK_ID NUMBER,
    INSPECTIETYPE VARCHAR2(50),
    KENMERK VARCHAR2(20),
    OMSCHRIJVING VARCHAR2(80),
    OPMERKINGEN VARCHAR2(80),
    STATUS VARCHAR2(20)
);

CREATE TABLE VOMAANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID NUMBER PRIMARY KEY,
    ACTIVITEITEN VARCHAR2(255),
    ADRES VARCHAR2(255),
    BAGID VARCHAR2(255),
    DOSSIERNUMMER VARCHAR2(200),
    INTAKETYPE VARCHAR2(80),
    INTERNNUMMER VARCHAR2(80),
    KADASTRALEAANDUIDING VARCHAR2(255),
    KENMERK VARCHAR2(80),
    LOCATIE VARCHAR2(255),
    LOCATIEOMSCHRIJVING VARCHAR2(255),
    TOELICHTING CLOB
);

CREATE TABLE WABOAANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID NUMBER PRIMARY KEY,
    BOUWKOSTEN NUMBER(10,2),
    OLONUMMER VARCHAR2(80),
    OMSCHRIJVING VARCHAR2(255),
    PROJECTKOSTEN NUMBER(10,2),
    REGISTRATIENUMMER VARCHAR2(100)
);

CREATE TABLE VTHAANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID NUMBER PRIMARY KEY,
    OMSCHRIJVING VARCHAR2(255)
);

CREATE TABLE KP_BSLT_DCMNT (
    KP_BSLT_DCMNT_ID NUMBER PRIMARY KEY,
    BESLUIT_ID NUMBER,
    DOCUMENT_ID NUMBER
);

CREATE TABLE BEVINDING (
    BEVINDING_ID NUMBER PRIMARY KEY,
    AANGEMAAKTDOOR VARCHAR2(255),
    ACTIVITEIT VARCHAR2(50),
    BEVINDING_SELF_ID NUMBER,
    CONTROLEELEMENT VARCHAR2(50),
    CONTROLENIVEAU VARCHAR2(50),
    DATUMAANMAAK DATE,
    DATUMMUTATIE DATE,
    DIEPTE VARCHAR2(20),
    FASE VARCHAR2(20),
    GEMUTEERDDOOR VARCHAR2(255),
    HEEFT_INSPECTIE_ID NUMBER,
    RESULTAAT VARCHAR2(50),
    RISICO VARCHAR2(50)
);

ALTER TABLE HEFFINGSVERORDENING ADD CONSTRAINT FK_HEFFINGSVERORDENING_GEN_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- Generalization to DOCUMENT

ALTER TABLE INDIENER ADD CONSTRAINT FK_INDIENER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE VOMAANVRAAGOFMELDING ADD CONSTRAINT FK_VOMAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE VTHAANVRAAGOFMELDING ADD CONSTRAINT FK_VTHAANVRAAGOFMELDING_GEN_VOMAANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VOMAANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VOMAANVRAAGOFMELDING

ALTER TABLE VTHZAAK ADD CONSTRAINT FK_VTHZAAK_GEN_ZAAK FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- Generalization to ZAAK

ALTER TABLE WABOAANVRAAGOFMELDING ADD CONSTRAINT FK_WABOAANVRAAGOFMELDING_GEN_VOMAANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VOMAANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VOMAANVRAAGOFMELDING

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_BSLT_DCMNT ADD CONSTRAINT FK_KP_BSLT_DCMNT_1 FOREIGN KEY (BESLUIT_ID) REFERENCES BESLUIT (BESLUIT_ID);
-- BESLUIT (many-to-many junction, Connector_ID: 2150)

ALTER TABLE KP_BSLT_DCMNT ADD CONSTRAINT FK_KP_BSLT_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2150)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_1 FOREIGN KEY (BETROKKENE_ID) REFERENCES BETROKKENE (RECHTSPERSOON_ID);
-- BETROKKENE (many-to-many junction, Connector_ID: 2164)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_2 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2164)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_MELDER FOREIGN KEY (MELDER_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- MELDER (1..* to 0..1, Connector_ID: 377)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_HEEFT_DOCUMENTEN FOREIGN KEY (HEEFT_DOCUMENTEN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- HEEFT_DOCUMENTEN (0..1 to 0..*, Connector_ID: 378)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_KAN_LEIDEN_TOT FOREIGN KEY (KAN_LEIDEN_TOT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 380)

ALTER TABLE VORDERING ADD CONSTRAINT FK_VORDERING_HEEFT FOREIGN KEY (HEEFT_VTHZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT (1..* to 1.., Connector_ID: 1301)

ALTER TABLE VORDERING ADD CONSTRAINT FK_VORDERING_HEEFT_2 FOREIGN KEY (HEEFT_VORDERINGREGEL_ID) REFERENCES VORDERINGREGEL (VORDERINGREGEL_ID);
-- HEEFT (1.. to 1..*, Connector_ID: 1302)

ALTER TABLE INSPECTIE ADD CONSTRAINT FK_INSPECTIE_HEEFT FOREIGN KEY (HEEFT_VTHZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT (1..* to 1.., Connector_ID: 1315)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_INGEDIEND_DOOR FOREIGN KEY (INGEDIEND_DOOR_INDIENER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- INGEDIEND_DOOR (0..* to 1, Connector_ID: 1316)

ALTER TABLE HEFFINGSVERORDENING ADD CONSTRAINT FK_HEFFINGSVERORDENING_VERMELD_IN FOREIGN KEY (VERMELD_IN_HEFFINGGRONDSLAG_ID) REFERENCES HEFFINGGRONDSLAG (HEFFINGGRONDSLAG_ID);
-- VERMELD_IN (1 to 0..*, Connector_ID: 1321)

ALTER TABLE BEVINDING ADD CONSTRAINT FK_BEVINDING_BEVINDING FOREIGN KEY (BEVINDING_ID) REFERENCES BEVINDING (BEVINDING_ID);
-- unnamed (1 to 0..*, Connector_ID: 1327)

ALTER TABLE BEVINDING ADD CONSTRAINT FK_BEVINDING_HEEFT FOREIGN KEY (HEEFT_INSPECTIE_ID) REFERENCES INSPECTIE (INSPECTIE_ID);
-- HEEFT (0..* to 1.., Connector_ID: 1328)

ALTER TABLE HEFFING ADD CONSTRAINT FK_HEFFING_BETREFT FOREIGN KEY (BETREFT_VORDERINGREGEL_ID) REFERENCES VORDERINGREGEL (VORDERINGREGEL_ID);
-- BETREFT (0..1 to 1.., Connector_ID: 2049)

ALTER TABLE HEFFING ADD CONSTRAINT FK_HEFFING_HEEFT_GRONDSLAG FOREIGN KEY (HEEFT_GRONDSLAG_HEFFINGGRONDSLAG_ID) REFERENCES HEFFINGGRONDSLAG (HEFFINGGRONDSLAG_ID);
-- HEEFT_GRONDSLAG (0..* to 1, Connector_ID: 2050)

ALTER TABLE HEFFING ADD CONSTRAINT FK_HEFFING_SOORT FOREIGN KEY (SOORT_ENUM_ID) REFERENCES HEFFINGSOORT_ENUM (HEFFINGSOORT_ENUM_ID);
-- SOORT (0..* to 1, Connector_ID: 2051)

ALTER TABLE STATUS ADD CONSTRAINT FK_STATUS_IS_VAN FOREIGN KEY (IS_VAN_STATUSTYPE_ID) REFERENCES STATUSTYPE (STATUSTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2090)

ALTER TABLE ZAAKTYPE ADD CONSTRAINT FK_ZAAKTYPE_HEEFT FOREIGN KEY (HEEFT_STATUSTYPE_ID) REFERENCES STATUSTYPE (STATUSTYPE_ID);
-- HEEFT (1 to 1..*, Connector_ID: 2093)

ALTER TABLE ZAAKTYPE ADD CONSTRAINT FK_ZAAKTYPE_HEEFT_2 FOREIGN KEY (HEEFT_HEFFINGGRONDSLAG_ID) REFERENCES HEFFINGGRONDSLAG (HEFFINGGRONDSLAG_ID);
-- HEEFT (1 to 0..*, Connector_ID: 2097)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT FOREIGN KEY (HEEFT_STATUS_ID) REFERENCES STATUS (STATUS_ID);
-- HEEFT (1 to 0..*, Connector_ID: 2101)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_2 FOREIGN KEY (HEEFT_HEFFING_ID) REFERENCES HEFFING (HEFFING_ID);
-- HEEFT (1 to 0..1, Connector_ID: 2103)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_UITKOMST_VAN FOREIGN KEY (IS_UITKOMST_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_UITKOMST_VAN (0..* to 1, Connector_ID: 2112)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY (IS_VAN_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_VASTGELEGD_IN FOREIGN KEY (IS_VASTGELEGD_IN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- IS_VASTGELEGD_IN (0..1 to 0..1, Connector_ID: 2149)

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_IS FOREIGN KEY (IS_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- IS (0..1 to 1, Connector_ID: 2167)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY (IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2170)

