CREATE TABLE NATUURLIJKPERSOON (
    NATUURLIJKPERSOON_ID NUMBER PRIMARY KEY,
    AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
    AANHEFAANSCHRIJVING VARCHAR2(50),
    ACADEMISCHETITEL VARCHAR2(80),
    ACHTERNAAM VARCHAR2(100),
    ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
    ANUMMER VARCHAR2(20),
    BIJZONDERNEDERLANDERSCHAP VARCHAR2(50),
    BURGERSERVICENUMMER VARCHAR2(255),
    DATUMGEBOORTE DATE,
    DATUMOVERLIJDEN DATE,
    GEBOORTELAND VARCHAR2(255),
    GEBOORTEPLAATS VARCHAR2(200),
    GESLACHTSAANDUIDING VARCHAR2(255),
    GESLACHTSNAAM VARCHAR2(200),
    GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
    HANDLICHTING VARCHAR2(50),
    INDICATIEAFSCHERMINGPERSOONSGEGEVENS NUMBER(1),
    INDICATIEOVERLEDEN NUMBER(1),
    IS_OBJECT_ID NUMBER,
    LANDOVERLIJDEN VARCHAR2(255),
    NATIONALITEIT VARCHAR2(100),
    OVERLIJDENSPLAATS VARCHAR2(200),
    VOORLETTERSAANSCHRIJVING VARCHAR2(20),
    VOORNAMEN VARCHAR2(200),
    VOORNAMENAANSCHRIJVING VARCHAR2(200),
    VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN (
    KP_NTNTRLJKPRSN_NTRLJKPRSN_ID NUMBER PRIMARY KEY,
    NIETNATUURLIJKPERSOON_ID NUMBER,
    NATUURLIJKPERSOON_ID NUMBER
);

CREATE TABLE MAATSCHAPPELIJKEACTIVITEIT (
    MAATSCHAPPELIJKEACTIVITEIT_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    DATUMAANVANG DATE,
    DATUMEINDEGELDIG DATE,
    DATUMFAILLISEMENT DATE,
    INDICATIEECONOMISCHACTIEF NUMBER(1),
    IS_FUNCTIONARIS_VAN_NATUURLIJKPERSOON_ID NUMBER,
    IS_OBJECT_ID NUMBER,
    KVKNUMMER VARCHAR2(255),
    RECHTSVORM VARCHAR2(100),
    RSIN VARCHAR2(255),
    STATUTAIRENAAM VARCHAR2(100),
    TELEFOONNUMMER VARCHAR2(20),
    URL VARCHAR2(100)
);

CREATE TABLE KADASTRAALPERCEEL (
    OBJECT_ID NUMBER PRIMARY KEY,
    AANDUIDINGSOORTGROOTTE VARCHAR2(255),
    BEGRENZINGPERCEEL VARCHAR2(255),
    GROOTTEPERCEEL VARCHAR2(255),
    INDICATIEDEELPERCEEL NUMBER(1),
    IS_OBJECT_ID NUMBER,
    OMSCHRIJVINGDEELPERCEEL VARCHAR2(20),
    PLAATSCOORDINATENPERCEEL SDO_GEOMETRY
);

CREATE TABLE BUURT (
    BUURT_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    CODE VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    LIGT_IN_OPENBARERUIMTE_ID NUMBER,
    NAAM VARCHAR2(255),
    STATUS VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE INRICHTINGSELEMENT (
    INRICHTINGSELEMENT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDINRICHTINGSELEMENT DATE,
    DATUMEINDEGELDIGHEIDINRICHTINGSELEMENT DATE,
    GEOMETRIEINRICHTINGSELEMENT SDO_GEOMETRY,
    IDENTIFICATIEINRICHTINGSELEMENT VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    LOD0GEOMETRIEINRICHTINGSELEMENT SDO_GEOMETRY,
    PLUSTYPEINRICHTINGSELEMENT VARCHAR2(255),
    RELATIEVEHOOGTELIGGINGINRICHTINGSELEMENT VARCHAR2(255),
    STATUSINRICHTINGSELEMENT VARCHAR2(255),
    TYPEINRICHTINGSELEMENT VARCHAR2(255)
);

CREATE TABLE PAND (
    PAND_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    BRUTOINHOUDPAND VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER VARCHAR2(255),
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIEBOVENAANZICHT SDO_GEOMETRY,
    GEOMETRIEMAAIVELD SDO_GEOMETRY,
    GEOMETRIEPUNT SDO_GEOMETRY,
    HOOGSTEBOUWLAAG VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    LAAGSTEBOUWLAAG VARCHAR2(255),
    OORSPRONKELIJKBOUWJAAR VARCHAR2(255),
    OPPERVLAKTE VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUS VARCHAR2(255),
    STATUSVOORTGANGBOUW VARCHAR2(255),
    VERSIE NUMBER,
    ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_ID NUMBER
);

CREATE TABLE KUNSTWERKDEEL (
    KUNSTWERKDEEL_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDKUNSTWERKDEEL DATE,
    DATUMEINDEGELDIGHEIDKUNSTWERKDEEL DATE,
    GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    IDENTIFICATIEKUNSTWERKDEEL VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    LOD0GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    LOD1GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    LOD2GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    LOD3GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGKUNSTWERKDEEL VARCHAR2(255),
    STATUSKUNSTWERKDEEL VARCHAR2(255)
);

CREATE TABLE OBJECT (
    OBJECT_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(200),
    DOMEIN VARCHAR2(200),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(50),
    INDICATIERISICO NUMBER(1),
    IS_VAARTUIG_ID NUMBER,
    IS_VOERTUIG_ID NUMBER,
    KADASTRALEAANDUIDING VARCHAR2(255),
    NAAM VARCHAR2(200),
    OBJECTTYPE VARCHAR2(255),
    TOELICHTING VARCHAR2(255)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    NIETNATUURLIJKPERSOON_ID NUMBER PRIMARY KEY,
    DATUMAANVANG DATE,
    DATUMEINDE DATE,
    DATUMUITSCHRIJVING DATE,
    DATUMVOORTZETTING DATE,
    FAXNUMMER VARCHAR2(20),
    INGESCHREVEN NUMBER(1),
    INOPRICHTING NUMBER(1),
    IS_OBJECT_ID NUMBER,
    KVKNUMMER VARCHAR2(255),
    NNPID VARCHAR2(255),
    RECHTSVORM VARCHAR2(255),
    RSINNUMMER VARCHAR2(255),
    STATUTAIRENAAM VARCHAR2(255),
    STATUTAIREZETEL VARCHAR2(255),
    WEBSITEURL VARCHAR2(200)
);

CREATE TABLE KP_KDSTRLPRCL_KDSTRLNRRNDZK (
    KP_KDSTRLPRCL_KDSTRLNRRNDZK_ID NUMBER PRIMARY KEY,
    KADASTRAALPERCEEL_ID NUMBER,
    KADASTRALEONROERENDEZAAK_ID NUMBER
);

CREATE TABLE STANDPLAATS (
    STANDPLAATS_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    STATUS VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE KADASTRALEONROERENDEZAAK (
    OBJECT_ID NUMBER PRIMARY KEY,
    APPARTEMENTSRECHTVOLGNUMMER VARCHAR2(255),
    BEGRENZING VARCHAR2(255),
    CULTUURCODEONBEBOUWD VARCHAR2(255),
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    GERELATEERD_OBJECT_ID NUMBER,
    IDENTIFICATIE VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    KADASTRALEGEMEENTE VARCHAR2(20),
    KADASTRALEGEMEENTECODE VARCHAR2(20),
    KOOPJAAR NUMBER,
    KOOPSOM VARCHAR2(255),
    LANDINRICHTINGRENTEBEDRAG NUMBER(10,2),
    LANDINRICHTINGRENTEEINDEJAAR DATE,
    LIGGING VARCHAR2(255),
    LOCATIEOMSCHRIJVING VARCHAR2(255),
    OPPERVLAKTE NUMBER,
    PERCEELNUMMER VARCHAR2(255),
    SECTIE VARCHAR2(255),
    VALUTACODE VARCHAR2(255)
);

CREATE TABLE VOERTUIG (
    VOERTUIG_ID NUMBER PRIMARY KEY,
    KENTEKEN VARCHAR2(255),
    KLEUR VARCHAR2(200),
    LAND VARCHAR2(200),
    MERK VARCHAR2(200),
    TYPE VARCHAR2(200)
);

CREATE TABLE OPENBARERUIMTE (
    OPENBARERUIMTE_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS VARCHAR2(255),
    HUISNUMMERRANGE_EVEN_NUMMERS VARCHAR2(255),
    HUISNUMMERRANGE_ONEVEN_NUMMERS VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    LABELNAAM VARCHAR2(80),
    NAAMOPENBARERUIMTE VARCHAR2(80),
    STATUS VARCHAR2(255),
    STRAATCODE VARCHAR2(80),
    STRAATNAAM VARCHAR2(255),
    TYPEOPENBARERUIMTE VARCHAR2(255),
    VERSIE NUMBER,
    WEGSEGMENT VARCHAR2(255)
);

CREATE TABLE WATERDEEL (
    WATERDEEL_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDWATERDEEL DATE,
    DATUMEINDEGELDIGHEIDWATERDEEL DATE,
    GEOMETRIEWATERDEEL SDO_GEOMETRY,
    IDENTIFICATIEWATERDEEL VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    PLUSTYPEWATERDEEL VARCHAR2(255),
    RELATIEVEHOOGTELIGGINGWATERDEEL VARCHAR2(255),
    STATUSWATERDEEL VARCHAR2(255),
    TYPEWATERDEEL VARCHAR2(255)
);

CREATE TABLE KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ (
    KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_ID NUMBER PRIMARY KEY,
    IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID NUMBER,
    IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID NUMBER
);

CREATE TABLE LIGPLAATS (
    LIGPLAATS_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    IS_OBJECT_ID NUMBER,
    STATUS VARCHAR2(255),
    VERSIE VARCHAR2(255)
);

CREATE TABLE VAARTUIG (
    VAARTUIG_ID NUMBER PRIMARY KEY,
    BREEDTE NUMBER,
    HOOGTE NUMBER,
    KLEUR VARCHAR2(20),
    LENGTE NUMBER,
    NAAMVAARTUIG VARCHAR2(255),
    REGISTRATIENUMMER VARCHAR2(80)
);

CREATE TABLE KP_KDSTRLNRRNDZK_OBJCT (
    KP_KDSTRLNRRNDZK_OBJCT_ID NUMBER PRIMARY KEY,
    KADASTRALEONROERENDEZAAK_ID NUMBER,
    OBJECT_ID NUMBER
);

ALTER TABLE KADASTRAALPERCEEL ADD CONSTRAINT FK_KADASTRAALPERCEEL_GEN_KADASTRALEONROERENDEZAAK FOREIGN KEY (OBJECT_ID) REFERENCES KADASTRALEONROERENDEZAAK (OBJECT_ID);
-- Generalization to KADASTRALEONROERENDEZAAK

ALTER TABLE KADASTRALEONROERENDEZAAK ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GEN_OBJECT FOREIGN KEY (OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- Generalization to OBJECT

ALTER TABLE KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_1 FOREIGN KEY (IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID) REFERENCES KADASTRALEONROERENDEZAAK (OBJECT_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_2 FOREIGN KEY (IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID) REFERENCES KADASTRALEONROERENDEZAAK (OBJECT_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_1 FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- NIETNATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1970)

ALTER TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_2 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (NATUURLIJKPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1970)

ALTER TABLE KP_KDSTRLPRCL_KDSTRLNRRNDZK ADD CONSTRAINT FK_KP_KDSTRLPRCL_KDSTRLNRRNDZK_1 FOREIGN KEY (KADASTRAALPERCEEL_ID) REFERENCES KADASTRAALPERCEEL (OBJECT_ID);
-- KADASTRAALPERCEEL (many-to-many junction, Connector_ID: 1988)

ALTER TABLE KP_KDSTRLPRCL_KDSTRLNRRNDZK ADD CONSTRAINT FK_KP_KDSTRLPRCL_KDSTRLNRRNDZK_2 FOREIGN KEY (KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (OBJECT_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1988)

ALTER TABLE KP_KDSTRLNRRNDZK_OBJCT ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_OBJCT_1 FOREIGN KEY (KADASTRALEONROERENDEZAAK_ID) REFERENCES KADASTRALEONROERENDEZAAK (OBJECT_ID);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 2067)

ALTER TABLE KP_KDSTRLNRRNDZK_OBJCT ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_OBJCT_2 FOREIGN KEY (OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- OBJECT (many-to-many junction, Connector_ID: 2067)

ALTER TABLE KADASTRALEONROERENDEZAAK ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GERELATEERD FOREIGN KEY (GERELATEERD_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- GERELATEERD (1 to 0..*, Connector_ID: 1938)

ALTER TABLE MAATSCHAPPELIJKEACTIVITEIT ADD CONSTRAINT FK_MAATSCHAPPELIJKEACTIVITEIT_IS_FUNCTIONARIS_VAN FOREIGN KEY (IS_FUNCTIONARIS_VAN_NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (NATUURLIJKPERSOON_ID);
-- IS_FUNCTIONARIS_VAN (0..* to 1.., Connector_ID: 1962)

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2069)

ALTER TABLE KUNSTWERKDEEL ADD CONSTRAINT FK_KUNSTWERKDEEL_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2074)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_IS FOREIGN KEY (IS_VOERTUIG_ID) REFERENCES VOERTUIG (VOERTUIG_ID);
-- IS (0..1 to 0..1, Connector_ID: 2075)

ALTER TABLE KADASTRALEONROERENDEZAAK ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2077)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_IS_2 FOREIGN KEY (IS_VAARTUIG_ID) REFERENCES VAARTUIG (VAARTUIG_ID);
-- IS (0..1 to 0..1, Connector_ID: 2081)

ALTER TABLE KADASTRAALPERCEEL ADD CONSTRAINT FK_KADASTRAALPERCEEL_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2082)

ALTER TABLE WATERDEEL ADD CONSTRAINT FK_WATERDEEL_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2084)

ALTER TABLE INRICHTINGSELEMENT ADD CONSTRAINT FK_INRICHTINGSELEMENT_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2087)

ALTER TABLE NIETNATUURLIJKPERSOON ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2088)

ALTER TABLE MAATSCHAPPELIJKEACTIVITEIT ADD CONSTRAINT FK_MAATSCHAPPELIJKEACTIVITEIT_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2089)

ALTER TABLE OPENBARERUIMTE ADD CONSTRAINT FK_OPENBARERUIMTE_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2236)

ALTER TABLE STANDPLAATS ADD CONSTRAINT FK_STANDPLAATS_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2250)

ALTER TABLE LIGPLAATS ADD CONSTRAINT FK_LIGPLAATS_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2254)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_LIGT_IN FOREIGN KEY (LIGT_IN_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- LIGT_IN (1 to 1..*, Connector_ID: 2264)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2266)

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_IS FOREIGN KEY (IS_OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- IS (0..1 to 0..*, Connector_ID: 2299)

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_ZONDER_VERBLIJFSOBJECT_LIGT_IN FOREIGN KEY (ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- ZONDER_VERBLIJFSOBJECT_LIGT_IN (0..* to 0..1, Connector_ID: 2300)

