CREATE TABLE `KP_BTRKKN_ZK` (
    `KP_BTRKKN_ZK_ID` INT PRIMARY KEY,
    `BETROKKENE_ID` INT,
    `ZAAK_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `SUBPRODUCTTYPE` (
    `SUBPRODUCTTYPE_ID` INT PRIMARY KEY,
    `HEEFT_PRODUCTTYPE_ID` INT,
    `OMSCHRIJVING` VARCHAR(200),
    `PRIORITEIT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `ACTIVITEIT_OMGEVINGSWET` (
    `ACTIVITEIT_OMGEVINGSWET_ID` INT PRIMARY KEY,
    `OMSCHRIJVING` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `KP_SBPRDCTTYP_VTHZK` (
    `KP_SBPRDCTTYP_VTHZK_ID` INT PRIMARY KEY,
    `SUBPRODUCTTYPE_ID` INT,
    `VTHZAAK_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VTHAANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `OMSCHRIJVING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_ACTVTT_OMGVNGSWT_VTHZK` (
    `KP_ACTVTT_OMGVNGSWT_VTHZK_ID` INT PRIMARY KEY,
    `ACTIVITEIT_OMGEVINGSWET_ID` INT,
    `VTHZAAK_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KADASTRALEONROERENDEZAAK` (
    `OBJECT_ID` INT PRIMARY KEY,
    `APPARTEMENTSRECHTVOLGNUMMER` VARCHAR(255),
    `BEGRENZING` VARCHAR(255),
    `CULTUURCODEONBEBOUWD` VARCHAR(255),
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `GERELATEERD_OBJECT_ID` INT,
    `IDENTIFICATIE` VARCHAR(255),
    `IS_OBJECT_ID` INT,
    `KADASTRALEGEMEENTE` VARCHAR(20),
    `KADASTRALEGEMEENTECODE` VARCHAR(20),
    `KOOPJAAR` INT,
    `KOOPSOM` VARCHAR(255),
    `LANDINRICHTINGRENTEBEDRAG` DECIMAL(10,2),
    `LANDINRICHTINGRENTEEINDEJAAR` DATE,
    `LIGGING` VARCHAR(255),
    `LOCATIEOMSCHRIJVING` VARCHAR(255),
    `OPPERVLAKTE` INT,
    `PERCEELNUMMER` VARCHAR(255),
    `SECTIE` VARCHAR(255),
    `VALUTACODE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN` (
    `KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN_ID` INT PRIMARY KEY,
    `IS_ONTSTAAN_UIT_OVERGEGAAN_IN_1_ID` INT,
    `IS_ONTSTAAN_UIT_OVERGEGAAN_IN_2_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_INDNR_RCHTSPRSN` (
    `KP_INDNR_RCHTSPRSN_ID` INT PRIMARY KEY,
    `INDIENER_ID` INT,
    `RECHTSPERSOON_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_WNFRDNVRGFMLDNG_ANVRGFMLDNG` (
    `KP_WNFRDNVRGFMLDNG_ANVRGFMLDNG_ID` INT PRIMARY KEY,
    `WOONFRAUDEAANVRAAGOFMELDING_ID` INT,
    `AANVRAAGOFMELDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VTHZAAK` (
    `ZAAK_ID` INT PRIMARY KEY,
    `BEHANDELAAR` VARCHAR(20),
    `BEVOEGDGEZAG` VARCHAR(50),
    `PRIORITERING` INT,
    `TEAMBEHANDELAAR` VARCHAR(20),
    `UITVOERENDEINSTANTIE` VARCHAR(50),
    `VERKAMERING_ENUM_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VOMAANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `ACTIVITEITEN` VARCHAR(255),
    `ADRES` VARCHAR(255),
    `BAGID` VARCHAR(255),
    `DOSSIERNUMMER` VARCHAR(200),
    `INTAKETYPE` VARCHAR(80),
    `INTERNNUMMER` VARCHAR(80),
    `KADASTRALEAANDUIDING` VARCHAR(255),
    `KENMERK` VARCHAR(80),
    `LOCATIE` VARCHAR(255),
    `LOCATIEOMSCHRIJVING` VARCHAR(255),
    `TOELICHTING` TEXT
) ENGINE=InnoDB;

CREATE TABLE `RECHTSPERSOON` (
    `RECHTSPERSOON_ID` INT PRIMARY KEY,
    `ADRESBINNENLAND` VARCHAR(255),
    `ADRESBUITENLAND` VARCHAR(255),
    `ADRESCORRESPONDENTIE` VARCHAR(100),
    `EMAILADRES` VARCHAR(80),
    `FAXNUMMER` VARCHAR(20),
    `IDENTIFICATIE` VARCHAR(255),
    `KVKNUMMER` VARCHAR(20),
    `NAAM` VARCHAR(200),
    `RECHTSVORM` VARCHAR(100),
    `REKENINGNUMMER` VARCHAR(255),
    `TELEFOONNUMMER` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `NUMMERAANDUIDING` (
    `NUMMERAANDUIDING_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` DATE,
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` INT,
    `EINDEGELDIGHEID` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `HEEFT_ALS_NEVENADRES_OBJECT_ID` INT,
    `HUISLETTER` VARCHAR(255),
    `HUISNUMMER` VARCHAR(255),
    `HUISNUMMERTOEVOEGING` VARCHAR(255),
    `IDENTIFICATIE` VARCHAR(255),
    `POSTCODE` VARCHAR(255),
    `STATUS` VARCHAR(255),
    `TYPEADRESSEERBAAROBJECT` VARCHAR(255),
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `STATUS` (
    `STATUS_ID` INT PRIMARY KEY,
    `DATUMSTATUSGEZET` DATE,
    `HEEFT_ZAAK_ID` INT,
    `INDICATIEIAATSTGEZETTESTATUS` VARCHAR(255),
    `IS_VAN_STATUSTYPE_ID` INT,
    `STATUSTOELICHTING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `HEFFINGGRONDSLAG` (
    `HEFFINGGRONDSLAG_ID` INT PRIMARY KEY,
    `BEDRAG` DECIMAL(10,2),
    `DOMEIN` VARCHAR(80),
    `HEEFT_ACTIVITEIT_OMGEVINGSWET_ID` INT,
    `HEEFT_ZAAKTYPE_ID` INT,
    `HOOFDSTUK` INT,
    `OMSCHRIJVING` VARCHAR(255),
    `PARAGRAAF` VARCHAR(255),
    `VERMELD_IN_HEFFINGSVERORDENING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_KDSTRLNRRNDZK_OBJCT` (
    `KP_KDSTRLNRRNDZK_OBJCT_ID` INT PRIMARY KEY,
    `KADASTRALEONROERENDEZAAK_ID` INT,
    `OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `INDIENER` (
    `RECHTSPERSOON_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `ZAAK` (
    `ZAAK_ID` INT PRIMARY KEY,
    `ARCHIEFNOMINATIE` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMEINDEGEPLAND` DATE,
    `DATUMEINDEUITERLIJKEAFDOENING` DATE,
    `DATUMLAATSTEBETALING` DATE,
    `DATUMPUBLICATIE` DATE,
    `DATUMREGISTRATIE` DATE,
    `DATUMSTART` DATE,
    `DATUMVERNIETIGINGDOSSIER` DATE,
    `DUURVERLENGING` VARCHAR(255),
    `HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID` INT,
    `HEEFT_HEFFING_ID` INT,
    `HEEFT_PRODUCT_PRODUCTTYPE_ID` INT,
    `INDICATIEBETALING` VARCHAR(255),
    `INDICATIEDEELZAKEN_ENUM_ID` INT,
    `INDICATIEOPSCHORTING` VARCHAR(255),
    `IS_DEELZAAK_VAN_ZAAK_ID` INT,
    `IS_VAN_ZAAKTYPE_ID` INT,
    `KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID` INT,
    `LEGES` VARCHAR(100),
    `OMSCHRIJVING` VARCHAR(80),
    `OMSCHRIJVINGRESULTAAT` VARCHAR(80),
    `REDENOPSCHORTING` VARCHAR(200),
    `REDENVERLENGING` VARCHAR(200),
    `TOELICHTING` VARCHAR(255),
    `TOELICHTINGRESULTAAT` VARCHAR(255),
    `VERTROUWELIJKHEID` VARCHAR(255),
    `ZAAKIDENTIFICATIE` VARCHAR(255),
    `ZAAKNIVEAU` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_MRNVRGFMLDNG_ANVRGFMLDNG` (
    `KP_MRNVRGFMLDNG_ANVRGFMLDNG_ID` INT PRIMARY KEY,
    `MORAANVRAAGOFMELDING_ID` INT,
    `AANVRAAGOFMELDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BTRKKN_RCHTSPRSN` (
    `KP_BTRKKN_RCHTSPRSN_ID` INT PRIMARY KEY,
    `BETROKKENE_ID` INT,
    `RECHTSPERSOON_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_ADRSSRBRBJCT_OBJCT` (
    `KP_ADRSSRBRBJCT_OBJCT_ID` INT PRIMARY KEY,
    `ADRESSEERBAAROBJECT_ID` INT,
    `OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `INSPECTIE` (
    `INSPECTIE_ID` INT PRIMARY KEY,
    `AANGEMAAKTDOOR` VARCHAR(50),
    `DATUMAANMAAK` DATE,
    `DATUMGEPLAND` DATE,
    `DATUMINSPECTIE` DATE,
    `DATUMMUTATIE` DATE,
    `GEMUTEERDDOOR` VARCHAR(50),
    `HEEFT_ZAAK_ID` INT,
    `INSPECTIETYPE` VARCHAR(50),
    `KENMERK` VARCHAR(20),
    `OMSCHRIJVING` VARCHAR(80),
    `OPMERKINGEN` VARCHAR(80),
    `STATUS` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `AANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `AFGEHANDELD_ENUM_ID` INT,
    `CATEGORIE` VARCHAR(200),
    `CATEGORIECODE` VARCHAR(80),
    `DATUMAANMAAK` DATE,
    `DATUMAFHANDELING` DATE,
    `DATUMBEGINSTATUS` DATE,
    `DATUMEINDESTATUS` DATE,
    `HOOFDCATEGORIE` VARCHAR(80),
    `HOOFDCATEGORIECODE` VARCHAR(80),
    `IDENTIFICATIE` VARCHAR(255),
    `INGEDIEND_DOOR_RECHTSPERSOON_ID` INT,
    `KANAAL` VARCHAR(80),
    `MELDER_RECHTSPERSOON_ID` INT,
    `ONDERWERP` VARCHAR(200),
    `ONDERWERPCODE` VARCHAR(80),
    `SOORT` VARCHAR(80),
    `STATUS` VARCHAR(80),
    `STATUSCODE` VARCHAR(80),
    `STATUSVOLGORDE` VARCHAR(80),
    `SUBCATEGORIE` VARCHAR(200),
    `SUBCATEGORIECODE` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `HEFFING` (
    `HEFFING_ID` INT PRIMARY KEY,
    `BEDRAG` DECIMAL(10,2),
    `BETREFT_VORDERINGREGEL_ID` INT,
    `CODE` VARCHAR(80),
    `DATUMINDIENING` DATE,
    `GEFACTUREERD_ENUM_ID` INT,
    `HEEFT_GRONDSLAG_HEFFINGGRONDSLAG_ID` INT,
    `INREKENING` VARCHAR(255),
    `NUMMER` INT,
    `RUNNUMMER` INT,
    `SOORT_HEFFINGSOORT_ENUM_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_ONBSTMD_ADRS_OBJCT` (
    `KP_ONBSTMD_ADRS_OBJCT_ID` INT PRIMARY KEY,
    `ONBESTEMD_ADRES_ID` INT,
    `OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `BESLUITTYPE` (
    `BESLUITTYPE_ID` INT PRIMARY KEY,
    `BESLUITCATEGORIE` VARCHAR(255),
    `BESLUITTYPEOMSCHRIJVING` VARCHAR(80),
    `BESLUITTYPEOMSCHRIJVINGGENERIEK` VARCHAR(80),
    `DATUMBEGINGELDIGHEIDBESLUITTYPE` DATE,
    `DATUMEINDEGELDIGHEIDBESLUITTYPE` DATE,
    `INDICATIEPUBLICATIE` VARCHAR(255),
    `PUBLICATIETEKST` VARCHAR(255),
    `PUBLICATIETERMIJN` VARCHAR(255),
    `REACTIETERMIJN` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BENOEMDOBJECT` (
    `OBJECT_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEID` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `GEOMETRIEPUNT` GEOMETRY,
    `GEOMETRIEVLAK` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE `BETROKKENE` (
    `RECHTSPERSOON_ID` INT PRIMARY KEY,
    `ADRESBINNENLAND` VARCHAR(255),
    `ADRESBUITENLAND` VARCHAR(200),
    `IDENTIFICATIE` VARCHAR(50),
    `NAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `OBJECT` (
    `OBJECT_ID` INT PRIMARY KEY,
    `ADRESBINNENLAND` VARCHAR(255),
    `ADRESBUITENLAND` VARCHAR(200),
    `BETREFT_ZAAK_ID` INT,
    `DOMEIN` VARCHAR(200),
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(50),
    `INDICATIERISICO_ENUM_ID` INT,
    `IS_BESLUIT_ID` INT,
    `KADASTRALEAANDUIDING` VARCHAR(255),
    `NAAM` VARCHAR(200),
    `OBJECTTYPE` VARCHAR(255),
    `TOELICHTING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `STATUSTYPE` (
    `STATUSTYPE_ID` INT PRIMARY KEY,
    `DATUMBEGINGELDIGHEIDSTATUSTYPE` DATE,
    `DATUMEINDEGELDIGHEIDSTATUSTYPE` DATE,
    `DOORLOOPTIJDSTATUS` DATETIME,
    `HEEFT_ZAAKTYPE_ID` INT,
    `STATUSTYPEOMSCHRIJVING` VARCHAR(80),
    `STATUSTYPEOMSCHRIJVINGGENERIEK` VARCHAR(80),
    `STATUSTYPEVOLGNUMMER` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `WABOAANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `BOUWKOSTEN` DECIMAL(10,2),
    `OLONUMMER` VARCHAR(80),
    `OMSCHRIJVING` VARCHAR(255),
    `PROJECTKOSTEN` DECIMAL(10,2),
    `REGISTRATIENUMMER` VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE `WOONFRAUDEAANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `ADRES` VARCHAR(255),
    `CATEGORIE` VARCHAR(80),
    `LOCATIEOMSCHRIJVING` VARCHAR(255),
    `MELDINGOMSCHRIJVING` VARCHAR(255),
    `MELDINGTEKST` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `ADRESSEERBAAROBJECT` (
    `OBJECT_ID` INT PRIMARY KEY,
    `HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID` INT,
    `IDENTIFICATIE` VARCHAR(255),
    `TYPEADRESSEERBAAROBJECT` VARCHAR(255),
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `HEFFINGSVERORDENING` (
    `HEFFINGSVERORDENING_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `KP_BNMDBJCT_OBJCT` (
    `KP_BNMDBJCT_OBJCT_ID` INT PRIMARY KEY,
    `BENOEMDOBJECT_ID` INT,
    `OBJECT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_WBNVRGFMLDNG_VMNVRGFMLDNG` (
    `KP_WBNVRGFMLDNG_VMNVRGFMLDNG_ID` INT PRIMARY KEY,
    `WABOAANVRAAGOFMELDING_ID` INT,
    `VOMAANVRAAGOFMELDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_WNVRLSTNVRGFMLDNG_ANVRGFMLDNG` (
    `KP_WNVRLSTNVRGFMLDNG_ANVRGFMLDNG_ID` INT PRIMARY KEY,
    `WOONOVERLASTAANVRAAGOFMELDING_ID` INT,
    `AANVRAAGOFMELDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `HEFFINGSOORT_ENUM` (
    `HEFFINGSOORT_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `HEFFINGSOORT_ENUM` (`HEFFINGSOORT_ENUM_ID`, VALUE) VALUES
    (1, 'LEGES'),
    (2, 'PRECARIO');

CREATE TABLE `KP_VMNVRGFMLDNG_ANVRGFMLDNG` (
    `KP_VMNVRGFMLDNG_ANVRGFMLDNG_ID` INT PRIMARY KEY,
    `VOMAANVRAAGOFMELDING_ID` INT,
    `AANVRAAGOFMELDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `PRODUCTTYPE` (
    `PRODUCTTYPE_ID` INT PRIMARY KEY,
    `HEEFT_ZAAK_ID` INT,
    `OMSCHRIJVING` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `VORDERINGREGEL` (
    `VORDERINGREGEL_ID` INT PRIMARY KEY,
    `AANGEMAAKT_DOOR` VARCHAR(50),
    `AANMAAKDATUM` DATE,
    `BEDRAG_EXCL_BTW` DECIMAL(10,2),
    `BEDRAG_INCL_BTW` DECIMAL(10,2),
    `BTWCATEGORIE` VARCHAR(50),
    `GEMUTEERD_DOOR` VARCHAR(50),
    `HEEFT_VORDERING_ID` INT,
    `MUTATIEDATUM` DATE,
    `OMSCHRIJVING` VARCHAR(50),
    `PERIODIEK` VARCHAR(50),
    `TYPE` VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE `WOONOVERLASTAANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `LOCATIE` VARCHAR(255),
    `LOCATIEOMSCHRIJVING` VARCHAR(255),
    `MELDINGOMSCHRIJVING` VARCHAR(255),
    `MELDINGTEKST` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `VORDERING` (
    `VORDERING_ID` INT PRIMARY KEY,
    `AANGEMAAKTDOOR` VARCHAR(50),
    `BEDRAGBTW` DECIMAL(10,2),
    `DATUMAANMAAK` DATE,
    `DATUMMUTATIE` DATE,
    `GEACCORDEERD` VARCHAR(50),
    `GEACCORDEERDDOOR` VARCHAR(50),
    `GEACCORDEERDOP` DATE,
    `GEEXPORTEERD` VARCHAR(50),
    `GEMUTEERDDOOR` VARCHAR(50),
    `HEEFT_ZAAK_ID` INT,
    `OMSCHRIJVING` TEXT,
    `TOTAALBEDRAG` DECIMAL(10,2),
    `TOTAALBEDRAGINCLUSIEF` DECIMAL(10,2),
    `VORDERINGNUMMER` VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE `BOOLEAN_ENUM` (
    `BOOLEAN_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`, VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE `ZAAKTYPE` (
    `ZAAKTYPE_ID` INT PRIMARY KEY,
    `ARCHIEFCODE` VARCHAR(20),
    `DATUMBEGINGELDIGHEIDZAAKTYPE` DATE,
    `DATUMEINDEGELDIGHEIDZAAKTYPE` DATE,
    `DOORLOOPTIJDBEHANDELING` DATETIME,
    `HEEFT_PRODUCTTYPE_ID` INT,
    `INDICATIEPUBLICATIE` VARCHAR(255),
    `PUBLICATIETEKST` VARCHAR(255),
    `SERVICENORMBEHANDELING` VARCHAR(255),
    `TREFWOORD` VARCHAR(255),
    `VERTROUWELIJKAANDUIDING` VARCHAR(20),
    `ZAAKCATEGORIE` VARCHAR(255),
    `ZAAKTYPEOMSCHRIJVING` VARCHAR(80),
    `ZAAKTYPEOMSCHRIJVINGGENERIEK` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `MORAANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `CROW_ENUM_ID` INT,
    `LOCATIE` VARCHAR(255),
    `LOCATIEOMSCHRIJVING` VARCHAR(255),
    `MELDINGOMSCHRIJVING` VARCHAR(255),
    `MELDINGTEKST` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BESLUIT` (
    `BESLUIT_ID` INT PRIMARY KEY,
    `BESLUITIDENTIFICATIE` VARCHAR(50),
    `BESLUITTOELICHTING` VARCHAR(255),
    `DATUMBESLUIT` DATE,
    `DATUMPUBLICATIE` DATE,
    `DATUMSTART` DATE,
    `DATUMUITERLIJKEREACTIE` DATE,
    `DATUMVERVAL` DATE,
    `DATUMVERZENDING` DATE,
    `IS_UITKOMST_VAN_ZAAK_ID` INT,
    `IS_VAN_BESLUITTYPE_ID` INT,
    `OMSCHRIJVING` VARCHAR(200),
    `REDENVERVAL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `ONBESTEMD_ADRES` (
    `OBJECT_ID` INT PRIMARY KEY,
    `HUISLETTER` VARCHAR(255),
    `HUISNUMMER` VARCHAR(255),
    `HUISNUMMERTOEVOEGING` VARCHAR(255),
    `POSTCODE` VARCHAR(255),
    `STRAATNAAM` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `KP_VTHZK_ZK` (
    `KP_VTHZK_ZK_ID` INT PRIMARY KEY,
    `VTHZAAK_ID` INT,
    `ZAAK_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `BEVINDING` (
    `BEVINDING_ID` INT PRIMARY KEY,
    `AANGEMAAKTDOOR` VARCHAR(255),
    `ACTIVITEIT` VARCHAR(50),
    `BEVINDING_SELF_ID` INT,
    `CONTROLEELEMENT` VARCHAR(50),
    `CONTROLENIVEAU` VARCHAR(50),
    `DATUMAANMAAK` DATE,
    `DATUMMUTATIE` DATE,
    `DIEPTE` VARCHAR(20),
    `FASE` VARCHAR(20),
    `GEMUTEERDDOOR` VARCHAR(255),
    `HEEFT_INSPECTIE_ID` INT,
    `RESULTAAT` VARCHAR(50),
    `RISICO` VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE `KP_VTHNVRGFMLDNG_VMNVRGFMLDNG` (
    `KP_VTHNVRGFMLDNG_VMNVRGFMLDNG_ID` INT PRIMARY KEY,
    `VTHAANVRAAGOFMELDING_ID` INT,
    `VOMAANVRAAGOFMELDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` (
    `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_ID` INT PRIMARY KEY,
    `IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID` INT,
    `IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `INDIENER` ADD CONSTRAINT FK_INDIENER_GEN_RECHTSPERSOON FOREIGN KEY (`RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- Generalization to RECHTSPERSOON

ALTER TABLE `MORAANVRAAGOFMELDING` ADD CONSTRAINT FK_MORAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE `VOMAANVRAAGOFMELDING` ADD CONSTRAINT FK_VOMAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE `VTHAANVRAAGOFMELDING` ADD CONSTRAINT FK_VTHAANVRAAGOFMELDING_GEN_VOMAANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `VOMAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to VOMAANVRAAGOFMELDING

ALTER TABLE `VTHZAAK` ADD CONSTRAINT FK_VTHZAAK_GEN_ZAAK FOREIGN KEY (`ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- Generalization to ZAAK

ALTER TABLE `WABOAANVRAAGOFMELDING` ADD CONSTRAINT FK_WABOAANVRAAGOFMELDING_GEN_VOMAANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `VOMAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to VOMAANVRAAGOFMELDING

ALTER TABLE `WOONFRAUDEAANVRAAGOFMELDING` ADD CONSTRAINT FK_WOONFRAUDEAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE `WOONOVERLASTAANVRAAGOFMELDING` ADD CONSTRAINT FK_WOONOVERLASTAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE `ADRESSEERBAAROBJECT` ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_GEN_OBJECT FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- Generalization to OBJECT

ALTER TABLE `BETROKKENE` ADD CONSTRAINT FK_BETROKKENE_GEN_RECHTSPERSOON FOREIGN KEY (`RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- Generalization to RECHTSPERSOON

ALTER TABLE `BENOEMDOBJECT` ADD CONSTRAINT FK_BENOEMDOBJECT_GEN_OBJECT FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- Generalization to OBJECT

ALTER TABLE `ONBESTEMD_ADRES` ADD CONSTRAINT FK_ONBESTEMD_ADRES_GEN_OBJECT FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- Generalization to OBJECT

ALTER TABLE `KADASTRALEONROERENDEZAAK` ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GEN_OBJECT FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- Generalization to OBJECT

ALTER TABLE `KP_WNVRLSTNVRGFMLDNG_ANVRGFMLDNG` ADD CONSTRAINT FK_KP_WNVRLSTNVRGFMLDNG_ANVRGFMLDNG_1 FOREIGN KEY (`WOONOVERLASTAANVRAAGOFMELDING_ID`) REFERENCES `WOONOVERLASTAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- WOONOVERLASTAANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1292)

ALTER TABLE `KP_WNVRLSTNVRGFMLDNG_ANVRGFMLDNG` ADD CONSTRAINT FK_KP_WNVRLSTNVRGFMLDNG_ANVRGFMLDNG_2 FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- AANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1292)

ALTER TABLE `KP_WNFRDNVRGFMLDNG_ANVRGFMLDNG` ADD CONSTRAINT FK_KP_WNFRDNVRGFMLDNG_ANVRGFMLDNG_1 FOREIGN KEY (`WOONFRAUDEAANVRAAGOFMELDING_ID`) REFERENCES `WOONFRAUDEAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- WOONFRAUDEAANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1293)

ALTER TABLE `KP_WNFRDNVRGFMLDNG_ANVRGFMLDNG` ADD CONSTRAINT FK_KP_WNFRDNVRGFMLDNG_ANVRGFMLDNG_2 FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- AANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1293)

ALTER TABLE `KP_WBNVRGFMLDNG_VMNVRGFMLDNG` ADD CONSTRAINT FK_KP_WBNVRGFMLDNG_VMNVRGFMLDNG_1 FOREIGN KEY (`WABOAANVRAAGOFMELDING_ID`) REFERENCES `WABOAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- WABOAANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1294)

ALTER TABLE `KP_WBNVRGFMLDNG_VMNVRGFMLDNG` ADD CONSTRAINT FK_KP_WBNVRGFMLDNG_VMNVRGFMLDNG_2 FOREIGN KEY (`VOMAANVRAAGOFMELDING_ID`) REFERENCES `VOMAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- VOMAANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1294)

ALTER TABLE `KP_VTHZK_ZK` ADD CONSTRAINT FK_KP_VTHZK_ZK_1 FOREIGN KEY (`VTHZAAK_ID`) REFERENCES `VTHZAAK` (`ZAAK_ID`);
-- VTHZAAK (many-to-many junction, Connector_ID: 1296)

ALTER TABLE `KP_VTHZK_ZK` ADD CONSTRAINT FK_KP_VTHZK_ZK_2 FOREIGN KEY (`ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- ZAAK (many-to-many junction, Connector_ID: 1296)

ALTER TABLE `KP_VTHNVRGFMLDNG_VMNVRGFMLDNG` ADD CONSTRAINT FK_KP_VTHNVRGFMLDNG_VMNVRGFMLDNG_1 FOREIGN KEY (`VTHAANVRAAGOFMELDING_ID`) REFERENCES `VTHAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- VTHAANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1300)

ALTER TABLE `KP_VTHNVRGFMLDNG_VMNVRGFMLDNG` ADD CONSTRAINT FK_KP_VTHNVRGFMLDNG_VMNVRGFMLDNG_2 FOREIGN KEY (`VOMAANVRAAGOFMELDING_ID`) REFERENCES `VOMAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- VOMAANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1300)

ALTER TABLE `KP_VMNVRGFMLDNG_ANVRGFMLDNG` ADD CONSTRAINT FK_KP_VMNVRGFMLDNG_ANVRGFMLDNG_1 FOREIGN KEY (`VOMAANVRAAGOFMELDING_ID`) REFERENCES `VOMAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- VOMAANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1303)

ALTER TABLE `KP_VMNVRGFMLDNG_ANVRGFMLDNG` ADD CONSTRAINT FK_KP_VMNVRGFMLDNG_ANVRGFMLDNG_2 FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- AANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1303)

ALTER TABLE `KP_SBPRDCTTYP_VTHZK` ADD CONSTRAINT FK_KP_SBPRDCTTYP_VTHZK_1 FOREIGN KEY (`SUBPRODUCTTYPE_ID`) REFERENCES `SUBPRODUCTTYPE` (`SUBPRODUCTTYPE_ID`);
-- SUBPRODUCTTYPE (many-to-many junction, Connector_ID: 1305)

ALTER TABLE `KP_SBPRDCTTYP_VTHZK` ADD CONSTRAINT FK_KP_SBPRDCTTYP_VTHZK_2 FOREIGN KEY (`VTHZAAK_ID`) REFERENCES `VTHZAAK` (`ZAAK_ID`);
-- VTHZAAK (many-to-many junction, Connector_ID: 1305)

ALTER TABLE `KP_MRNVRGFMLDNG_ANVRGFMLDNG` ADD CONSTRAINT FK_KP_MRNVRGFMLDNG_ANVRGFMLDNG_1 FOREIGN KEY (`MORAANVRAAGOFMELDING_ID`) REFERENCES `MORAANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- MORAANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1311)

ALTER TABLE `KP_MRNVRGFMLDNG_ANVRGFMLDNG` ADD CONSTRAINT FK_KP_MRNVRGFMLDNG_ANVRGFMLDNG_2 FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- AANVRAAGOFMELDING (many-to-many junction, Connector_ID: 1311)

ALTER TABLE `KP_INDNR_RCHTSPRSN` ADD CONSTRAINT FK_KP_INDNR_RCHTSPRSN_1 FOREIGN KEY (`INDIENER_ID`) REFERENCES `INDIENER` (`RECHTSPERSOON_ID`);
-- INDIENER (many-to-many junction, Connector_ID: 1317)

ALTER TABLE `KP_INDNR_RCHTSPRSN` ADD CONSTRAINT FK_KP_INDNR_RCHTSPRSN_2 FOREIGN KEY (`RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 1317)

ALTER TABLE `KP_ACTVTT_OMGVNGSWT_VTHZK` ADD CONSTRAINT FK_KP_ACTVTT_OMGVNGSWT_VTHZK_1 FOREIGN KEY (`ACTIVITEIT_OMGEVINGSWET_ID`) REFERENCES `ACTIVITEIT_OMGEVINGSWET` (`ACTIVITEIT_OMGEVINGSWET_ID`);
-- ACTIVITEIT_OMGEVINGSWET (many-to-many junction, Connector_ID: 1330)

ALTER TABLE `KP_ACTVTT_OMGVNGSWT_VTHZK` ADD CONSTRAINT FK_KP_ACTVTT_OMGVNGSWT_VTHZK_2 FOREIGN KEY (`VTHZAAK_ID`) REFERENCES `VTHZAAK` (`ZAAK_ID`);
-- VTHZAAK (many-to-many junction, Connector_ID: 1330)

ALTER TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_1 FOREIGN KEY (`IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`OBJECT_ID`);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_2 FOREIGN KEY (`IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`OBJECT_ID`);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE `KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN` ADD CONSTRAINT FK_KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN_1 FOREIGN KEY (`IS_ONTSTAAN_UIT_OVERGEGAAN_IN_1_ID`) REFERENCES `BENOEMDOBJECT` (`OBJECT_ID`);
-- BENOEMDOBJECT (many-to-many junction, Connector_ID: 2013)

ALTER TABLE `KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN` ADD CONSTRAINT FK_KP_BNMDBJCT_IS_ONTSTN_UIT_OVRGGN_IN_2 FOREIGN KEY (`IS_ONTSTAAN_UIT_OVERGEGAAN_IN_2_ID`) REFERENCES `BENOEMDOBJECT` (`OBJECT_ID`);
-- BENOEMDOBJECT (many-to-many junction, Connector_ID: 2013)

ALTER TABLE `KP_KDSTRLNRRNDZK_OBJCT` ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_OBJCT_1 FOREIGN KEY (`KADASTRALEONROERENDEZAAK_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`OBJECT_ID`);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 2067)

ALTER TABLE `KP_KDSTRLNRRNDZK_OBJCT` ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_OBJCT_2 FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- OBJECT (many-to-many junction, Connector_ID: 2067)

ALTER TABLE `KP_BNMDBJCT_OBJCT` ADD CONSTRAINT FK_KP_BNMDBJCT_OBJCT_1 FOREIGN KEY (`BENOEMDOBJECT_ID`) REFERENCES `BENOEMDOBJECT` (`OBJECT_ID`);
-- BENOEMDOBJECT (many-to-many junction, Connector_ID: 2072)

ALTER TABLE `KP_BNMDBJCT_OBJCT` ADD CONSTRAINT FK_KP_BNMDBJCT_OBJCT_2 FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- OBJECT (many-to-many junction, Connector_ID: 2072)

ALTER TABLE `KP_ONBSTMD_ADRS_OBJCT` ADD CONSTRAINT FK_KP_ONBSTMD_ADRS_OBJCT_1 FOREIGN KEY (`ONBESTEMD_ADRES_ID`) REFERENCES `ONBESTEMD_ADRES` (`OBJECT_ID`);
-- ONBESTEMD_ADRES (many-to-many junction, Connector_ID: 2083)

ALTER TABLE `KP_ONBSTMD_ADRS_OBJCT` ADD CONSTRAINT FK_KP_ONBSTMD_ADRS_OBJCT_2 FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- OBJECT (many-to-many junction, Connector_ID: 2083)

ALTER TABLE `KP_BTRKKN_RCHTSPRSN` ADD CONSTRAINT FK_KP_BTRKKN_RCHTSPRSN_1 FOREIGN KEY (`BETROKKENE_ID`) REFERENCES `BETROKKENE` (`RECHTSPERSOON_ID`);
-- BETROKKENE (many-to-many junction, Connector_ID: 2158)

ALTER TABLE `KP_BTRKKN_RCHTSPRSN` ADD CONSTRAINT FK_KP_BTRKKN_RCHTSPRSN_2 FOREIGN KEY (`RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 2158)

ALTER TABLE `KP_BTRKKN_ZK` ADD CONSTRAINT FK_KP_BTRKKN_ZK_1 FOREIGN KEY (`BETROKKENE_ID`) REFERENCES `BETROKKENE` (`RECHTSPERSOON_ID`);
-- BETROKKENE (many-to-many junction, Connector_ID: 2164)

ALTER TABLE `KP_BTRKKN_ZK` ADD CONSTRAINT FK_KP_BTRKKN_ZK_2 FOREIGN KEY (`ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- ZAAK (many-to-many junction, Connector_ID: 2164)

ALTER TABLE `KP_ADRSSRBRBJCT_OBJCT` ADD CONSTRAINT FK_KP_ADRSSRBRBJCT_OBJCT_1 FOREIGN KEY (`ADRESSEERBAAROBJECT_ID`) REFERENCES `ADRESSEERBAAROBJECT` (`OBJECT_ID`);
-- ADRESSEERBAAROBJECT (many-to-many junction, Connector_ID: 2241)

ALTER TABLE `KP_ADRSSRBRBJCT_OBJCT` ADD CONSTRAINT FK_KP_ADRSSRBRBJCT_OBJCT_2 FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- OBJECT (many-to-many junction, Connector_ID: 2241)

ALTER TABLE `AANVRAAGOFMELDING` ADD CONSTRAINT FK_AANVRAAGOFMELDING_MELDER FOREIGN KEY (`MELDER_RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- MELDER (1..* to 0..1, Connector_ID: 377)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_KAN_LEIDEN_TOT FOREIGN KEY (`KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 380)

ALTER TABLE `VORDERING` ADD CONSTRAINT FK_VORDERING_HEEFT FOREIGN KEY (`HEEFT_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- HEEFT (1..* to 1.., Connector_ID: 1301)

ALTER TABLE `VORDERINGREGEL` ADD CONSTRAINT FK_VORDERINGREGEL_HEEFT FOREIGN KEY (`HEEFT_VORDERING_ID`) REFERENCES `VORDERING` (`VORDERING_ID`);
-- HEEFT (1.. to 1..*, Connector_ID: 1302)

ALTER TABLE `SUBPRODUCTTYPE` ADD CONSTRAINT FK_SUBPRODUCTTYPE_HEEFT FOREIGN KEY (`HEEFT_PRODUCTTYPE_ID`) REFERENCES `PRODUCTTYPE` (`PRODUCTTYPE_ID`);
-- HEEFT (* to 1, Connector_ID: 1306)

ALTER TABLE `PRODUCTTYPE` ADD CONSTRAINT FK_PRODUCTTYPE_HEEFT FOREIGN KEY (`HEEFT_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- HEEFT (1 to 1, Connector_ID: 1310)

ALTER TABLE `INSPECTIE` ADD CONSTRAINT FK_INSPECTIE_HEEFT FOREIGN KEY (`HEEFT_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- HEEFT (1..* to 1.., Connector_ID: 1315)

ALTER TABLE `AANVRAAGOFMELDING` ADD CONSTRAINT FK_AANVRAAGOFMELDING_INGEDIEND_DOOR FOREIGN KEY (`INGEDIEND_DOOR_RECHTSPERSOON_ID`) REFERENCES `RECHTSPERSOON` (`RECHTSPERSOON_ID`);
-- INGEDIEND_DOOR (0..* to 1, Connector_ID: 1316)

ALTER TABLE `HEFFINGGRONDSLAG` ADD CONSTRAINT FK_HEFFINGGRONDSLAG_VERMELD_IN FOREIGN KEY (`VERMELD_IN_HEFFINGSVERORDENING_ID`) REFERENCES `HEFFINGSVERORDENING` (`HEFFINGSVERORDENING_ID`);
-- VERMELD_IN (1 to 0..*, Connector_ID: 1321)

ALTER TABLE `BEVINDING` ADD CONSTRAINT FK_BEVINDING_BEVINDING FOREIGN KEY (`BEVINDING_ID`) REFERENCES `BEVINDING` (`BEVINDING_ID`);
-- unnamed (1 to 0..*, Connector_ID: 1327)

ALTER TABLE `BEVINDING` ADD CONSTRAINT FK_BEVINDING_HEEFT FOREIGN KEY (`HEEFT_INSPECTIE_ID`) REFERENCES `INSPECTIE` (`INSPECTIE_ID`);
-- HEEFT (0..* to 1.., Connector_ID: 1328)

ALTER TABLE `HEFFINGGRONDSLAG` ADD CONSTRAINT FK_HEFFINGGRONDSLAG_HEEFT FOREIGN KEY (`HEEFT_ACTIVITEIT_OMGEVINGSWET_ID`) REFERENCES `ACTIVITEIT_OMGEVINGSWET` (`ACTIVITEIT_OMGEVINGSWET_ID`);
-- HEEFT (1..* to 1.., Connector_ID: 1596)

ALTER TABLE `KADASTRALEONROERENDEZAAK` ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GERELATEERD FOREIGN KEY (`GERELATEERD_OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- GERELATEERD (1 to 0..*, Connector_ID: 1938)

ALTER TABLE `HEFFING` ADD CONSTRAINT FK_HEFFING_BETREFT FOREIGN KEY (`BETREFT_VORDERINGREGEL_ID`) REFERENCES `VORDERINGREGEL` (`VORDERINGREGEL_ID`);
-- BETREFT (0..1 to 1.., Connector_ID: 2049)

ALTER TABLE `HEFFING` ADD CONSTRAINT FK_HEFFING_HEEFT_GRONDSLAG FOREIGN KEY (`HEEFT_GRONDSLAG_HEFFINGGRONDSLAG_ID`) REFERENCES `HEFFINGGRONDSLAG` (`HEFFINGGRONDSLAG_ID`);
-- HEEFT_GRONDSLAG (0..* to 1, Connector_ID: 2050)

ALTER TABLE `HEFFING` ADD CONSTRAINT FK_HEFFING_SOORT FOREIGN KEY (`SOORT_HEFFINGSOORT_ENUM_ID`) REFERENCES `HEFFINGSOORT_ENUM` (`HEFFINGSOORT_ENUM_ID`);
-- SOORT (0..* to 1, Connector_ID: 2051)

ALTER TABLE `BESLUIT` ADD CONSTRAINT FK_BESLUIT_IS_VAN FOREIGN KEY (`IS_VAN_BESLUITTYPE_ID`) REFERENCES `BESLUITTYPE` (`BESLUITTYPE_ID`);
-- IS_VAN (0..* to 1, Connector_ID: 2066)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS FOREIGN KEY (`IS_BESLUIT_ID`) REFERENCES `BESLUIT` (`BESLUIT_ID`);
-- IS (0..1 to 1.., Connector_ID: 2071)

ALTER TABLE `KADASTRALEONROERENDEZAAK` ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_IS FOREIGN KEY (`IS_OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- IS (0..1 to 0..*, Connector_ID: 2077)

ALTER TABLE `STATUS` ADD CONSTRAINT FK_STATUS_IS_VAN FOREIGN KEY (`IS_VAN_STATUSTYPE_ID`) REFERENCES `STATUSTYPE` (`STATUSTYPE_ID`);
-- IS_VAN (0..* to 1, Connector_ID: 2090)

ALTER TABLE `STATUSTYPE` ADD CONSTRAINT FK_STATUSTYPE_HEEFT FOREIGN KEY (`HEEFT_ZAAKTYPE_ID`) REFERENCES `ZAAKTYPE` (`ZAAKTYPE_ID`);
-- HEEFT (1 to 1..*, Connector_ID: 2093)

ALTER TABLE `ZAAKTYPE` ADD CONSTRAINT FK_ZAAKTYPE_HEEFT FOREIGN KEY (`HEEFT_PRODUCTTYPE_ID`) REFERENCES `PRODUCTTYPE` (`PRODUCTTYPE_ID`);
-- HEEFT (1 to 1, Connector_ID: 2096)

ALTER TABLE `HEFFINGGRONDSLAG` ADD CONSTRAINT FK_HEFFINGGRONDSLAG_HEEFT_2 FOREIGN KEY (`HEEFT_ZAAKTYPE_ID`) REFERENCES `ZAAKTYPE` (`ZAAKTYPE_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 2097)

ALTER TABLE `STATUS` ADD CONSTRAINT FK_STATUS_HEEFT FOREIGN KEY (`HEEFT_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 2101)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_HEEFT FOREIGN KEY (`HEEFT_HEFFING_ID`) REFERENCES `HEFFING` (`HEFFING_ID`);
-- HEEFT (1 to 0..1, Connector_ID: 2103)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (`HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_HEEFT_PRODUCT FOREIGN KEY (`HEEFT_PRODUCT_PRODUCTTYPE_ID`) REFERENCES `PRODUCTTYPE` (`PRODUCTTYPE_ID`);
-- HEEFT_PRODUCT (1 to 1, Connector_ID: 2110)

ALTER TABLE `BESLUIT` ADD CONSTRAINT FK_BESLUIT_IS_UITKOMST_VAN FOREIGN KEY (`IS_UITKOMST_VAN_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- IS_UITKOMST_VAN (0..* to 1, Connector_ID: 2112)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_BETREFT FOREIGN KEY (`BETREFT_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- BETREFT (0..1 to 1, Connector_ID: 2117)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY (`IS_VAN_ZAAKTYPE_ID`) REFERENCES `ZAAKTYPE` (`ZAAKTYPE_ID`);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (`IS_DEELZAAK_VAN_ZAAK_ID`) REFERENCES `ZAAK` (`ZAAK_ID`);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE `NUMMERAANDUIDING` ADD CONSTRAINT FK_NUMMERAANDUIDING_HEEFT_ALS_NEVENADRES FOREIGN KEY (`HEEFT_ALS_NEVENADRES_OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE `ADRESSEERBAAROBJECT` ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (`HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID`) REFERENCES `NUMMERAANDUIDING` (`NUMMERAANDUIDING_ID`);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE `MORAANVRAAGOFMELDING` ADD CONSTRAINT FK_MORAANVRAAGOFMELDING_CROW_ENUM_ID FOREIGN KEY (`CROW_ENUM_ID_BOOLEAN_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- CROW_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VTHZAAK` ADD CONSTRAINT FK_VTHZAAK_VERKAMERING_ENUM_ID FOREIGN KEY (`VERKAMERING_ENUM_ID_BOOLEAN_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- VERKAMERING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `AANVRAAGOFMELDING` ADD CONSTRAINT FK_AANVRAAGOFMELDING_AFGEHANDELD_ENUM_ID FOREIGN KEY (`AFGEHANDELD_ENUM_ID_BOOLEAN_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- AFGEHANDELD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `NUMMERAANDUIDING` ADD CONSTRAINT FK_NUMMERAANDUIDING_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `ZAAK` ADD CONSTRAINT FK_ZAAK_INDICATIEDEELZAKEN_ENUM_ID FOREIGN KEY (`INDICATIEDEELZAKEN_ENUM_ID_BOOLEAN_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- INDICATIEDEELZAKEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_INDICATIERISICO_ENUM_ID FOREIGN KEY (`INDICATIERISICO_ENUM_ID_BOOLEAN_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- INDICATIERISICO_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `HEFFING` ADD CONSTRAINT FK_HEFFING_GEFACTUREERD_ENUM_ID FOREIGN KEY (`GEFACTUREERD_ENUM_ID_BOOLEAN_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GEFACTUREERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

