CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID INTEGER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR(255),
    ADRESBUITENLAND VARCHAR(255),
    ADRESCORRESPONDENTIE VARCHAR(100),
    EMAILADRES VARCHAR(80),
    FAXNUMMER VARCHAR(20),
    IDENTIFICATIE VARCHAR(255),
    KVKNUMMER VARCHAR(20),
    NAAM VARCHAR(200),
    RECHTSVORM VARCHAR(100),
    REKENINGNUMMER VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20)
);

CREATE TABLE HEFFINGSOORT_ENUM (
    HEFFINGSOORT_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO HEFFINGSOORT_ENUM (HEFFINGSOORT_ENUM_ID, VALUE) VALUES
    (1, 'LEGES'),
    (2, 'PRECARIO');

CREATE TABLE VORDERINGREGEL (
    VORDERINGREGEL_ID INTEGER PRIMARY KEY,
    AANGEMAAKT_DOOR VARCHAR(50),
    AANMAAKDATUM DATE,
    BEDRAG_EXCL_BTW DECIMAL(10,2),
    BEDRAG_INCL_BTW DECIMAL(10,2),
    BTWCATEGORIE VARCHAR(50),
    GEMUTEERD_DOOR VARCHAR(50),
    MUTATIEDATUM DATE,
    OMSCHRIJVING VARCHAR(50),
    PERIODIEK VARCHAR(50),
    TYPE VARCHAR(50)
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR(200),
    DOCUMENTIDENTIFICATIE VARCHAR(255),
    DOCUMENTTITEL VARCHAR(200),
    VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE HEFFINGGRONDSLAG (
    HEFFINGGRONDSLAG_ID INTEGER PRIMARY KEY,
    BEDRAG DECIMAL(10,2),
    DOMEIN VARCHAR(80),
    HOOFDSTUK INTEGER,
    OMSCHRIJVING VARCHAR(255),
    PARAGRAAF VARCHAR(255)
);

CREATE TABLE STATUSTYPE (
    STATUSTYPE_ID INTEGER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDSTATUSTYPE DATE,
    DATUMEINDEGELDIGHEIDSTATUSTYPE DATE,
    DOORLOOPTIJDSTATUS TIMESTAMP,
    STATUSTYPEOMSCHRIJVING VARCHAR(80),
    STATUSTYPEOMSCHRIJVINGGENERIEK VARCHAR(80),
    STATUSTYPEVOLGNUMMER VARCHAR(255)
);

CREATE TABLE INDIENER (
    RECHTSPERSOON_ID INTEGER PRIMARY KEY
);

CREATE TABLE HEFFING (
    HEFFING_ID INTEGER PRIMARY KEY,
    BEDRAG DECIMAL(10,2),
    BETREFT_VORDERINGREGEL_ID INTEGER,
    CODE VARCHAR(80),
    DATUMINDIENING DATE,
    GEFACTUREERD BOOLEAN,
    HEEFT_GRONDSLAG_HEFFINGGRONDSLAG_ID INTEGER,
    INREKENING VARCHAR(255),
    NUMMER INTEGER,
    RUNNUMMER INTEGER,
    SOORT_HEFFINGSOORT_ENUM_ID INTEGER
);

CREATE TABLE HEFFINGSVERORDENING (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    VERMELD_IN_HEFFINGGRONDSLAG_ID INTEGER
);

CREATE TABLE ZAAKTYPE (
    ZAAKTYPE_ID INTEGER PRIMARY KEY,
    ARCHIEFCODE VARCHAR(20),
    DATUMBEGINGELDIGHEIDZAAKTYPE DATE,
    DATUMEINDEGELDIGHEIDZAAKTYPE DATE,
    DOORLOOPTIJDBEHANDELING TIMESTAMP,
    HEEFT_HEFFINGGRONDSLAG_ID INTEGER,
    HEEFT_STATUSTYPE_ID INTEGER,
    INDICATIEPUBLICATIE VARCHAR(255),
    PUBLICATIETEKST VARCHAR(255),
    SERVICENORMBEHANDELING VARCHAR(255),
    TREFWOORD VARCHAR(255),
    VERTROUWELIJKAANDUIDING VARCHAR(20),
    ZAAKCATEGORIE VARCHAR(255),
    ZAAKTYPEOMSCHRIJVING VARCHAR(80),
    ZAAKTYPEOMSCHRIJVINGGENERIEK VARCHAR(80)
);

CREATE TABLE STATUS (
    STATUS_ID INTEGER PRIMARY KEY,
    DATUMSTATUSGEZET DATE,
    INDICATIEIAATSTGEZETTESTATUS VARCHAR(255),
    IS_VAN_STATUSTYPE_ID INTEGER,
    STATUSTOELICHTING VARCHAR(255)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID INTEGER PRIMARY KEY,
    ACHTERNAAM VARCHAR(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR(255),
    EXTERN BOOLEAN,
    FUNCTIE VARCHAR(50),
    GESLACHTSAANDUIDING VARCHAR(255),
    IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID INTEGER,
    MEDEWERKERIDENTIFICATIE VARCHAR(255),
    MEDEWERKERTOELICHTING VARCHAR(255),
    ROEPNAAM VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20),
    VOORLETTERS VARCHAR(20),
    VOORVOEGSELACHTERNAAM VARCHAR(255)
);

CREATE TABLE ZAAK (
    ZAAK_ID INTEGER PRIMARY KEY,
    ARCHIEFNOMINATIE VARCHAR(255),
    DATUMEINDE DATE,
    DATUMEINDEGEPLAND DATE,
    DATUMEINDEUITERLIJKEAFDOENING DATE,
    DATUMLAATSTEBETALING DATE,
    DATUMPUBLICATIE DATE,
    DATUMREGISTRATIE DATE,
    DATUMSTART DATE,
    DATUMVERNIETIGINGDOSSIER DATE,
    DUURVERLENGING VARCHAR(255),
    HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID INTEGER,
    HEEFT_HEFFING_ID INTEGER,
    HEEFT_STATUS_ID INTEGER,
    INDICATIEBETALING VARCHAR(255),
    INDICATIEDEELZAKEN BOOLEAN,
    INDICATIEOPSCHORTING VARCHAR(255),
    IS_DEELZAAK_VAN_ZAAK_ID INTEGER,
    IS_VAN_ZAAKTYPE_ID INTEGER,
    LEGES VARCHAR(100),
    OMSCHRIJVING VARCHAR(80),
    OMSCHRIJVINGRESULTAAT VARCHAR(80),
    REDENOPSCHORTING VARCHAR(200),
    REDENVERLENGING VARCHAR(200),
    TOELICHTING VARCHAR(255),
    TOELICHTINGRESULTAAT VARCHAR(255),
    VERTROUWELIJKHEID VARCHAR(255),
    ZAAKIDENTIFICATIE VARCHAR(255),
    ZAAKNIVEAU VARCHAR(255)
);

CREATE TABLE BETROKKENE (
    RECHTSPERSOON_ID INTEGER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR(255),
    ADRESBUITENLAND VARCHAR(200),
    IDENTIFICATIE VARCHAR(50),
    IS_MEDEWERKER_ID INTEGER,
    NAAM VARCHAR(200)
);

CREATE TABLE VTHZAAK (
    ZAAK_ID INTEGER PRIMARY KEY,
    BEHANDELAAR VARCHAR(20),
    BEVOEGDGEZAG VARCHAR(50),
    PRIORITERING INTEGER,
    TEAMBEHANDELAAR VARCHAR(20),
    UITVOERENDEINSTANTIE VARCHAR(50),
    VERKAMERING BOOLEAN
);

CREATE TABLE KP_ZK_DCMNT (
    KP_ZK_DCMNT_ID INTEGER PRIMARY KEY,
    ZAAK_ID INTEGER,
    DOCUMENT_ID INTEGER
);

CREATE TABLE AANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID INTEGER PRIMARY KEY,
    AFGEHANDELD BOOLEAN,
    CATEGORIE VARCHAR(200),
    CATEGORIECODE VARCHAR(80),
    DATUMAANMAAK DATE,
    DATUMAFHANDELING DATE,
    DATUMBEGINSTATUS DATE,
    DATUMEINDESTATUS DATE,
    HEEFT_DOCUMENTEN_DOCUMENT_ID INTEGER,
    HOOFDCATEGORIE VARCHAR(80),
    HOOFDCATEGORIECODE VARCHAR(80),
    IDENTIFICATIE VARCHAR(255),
    INGEDIEND_DOOR_INDIENER_ID INTEGER,
    KANAAL VARCHAR(80),
    KAN_LEIDEN_TOT_ZAAK_ID INTEGER,
    MELDER_RECHTSPERSOON_ID INTEGER,
    ONDERWERP VARCHAR(200),
    ONDERWERPCODE VARCHAR(80),
    SOORT VARCHAR(80),
    STATUS VARCHAR(80),
    STATUSCODE VARCHAR(80),
    STATUSVOLGORDE VARCHAR(80),
    SUBCATEGORIE VARCHAR(200),
    SUBCATEGORIECODE VARCHAR(80)
);

CREATE TABLE BESLUIT (
    BESLUIT_ID INTEGER PRIMARY KEY,
    BESLUITIDENTIFICATIE VARCHAR(50),
    BESLUITTOELICHTING VARCHAR(255),
    DATUMBESLUIT DATE,
    DATUMPUBLICATIE DATE,
    DATUMSTART DATE,
    DATUMUITERLIJKEREACTIE DATE,
    DATUMVERVAL DATE,
    DATUMVERZENDING DATE,
    IS_UITKOMST_VAN_ZAAK_ID INTEGER,
    IS_VASTGELEGD_IN_DOCUMENT_ID INTEGER,
    OMSCHRIJVING VARCHAR(200),
    REDENVERVAL VARCHAR(255)
);

CREATE TABLE KP_ZK_MDWRKR (
    KP_ZK_MDWRKR_ID INTEGER PRIMARY KEY,
    ZAAK_ID INTEGER,
    MEDEWERKER_ID INTEGER
);

CREATE TABLE KP_BTRKKN_ZK (
    KP_BTRKKN_ZK_ID INTEGER PRIMARY KEY,
    BETROKKENE_ID INTEGER,
    ZAAK_ID INTEGER
);

CREATE TABLE VORDERING (
    VORDERING_ID INTEGER PRIMARY KEY,
    AANGEMAAKTDOOR VARCHAR(50),
    BEDRAGBTW DECIMAL(10,2),
    DATUMAANMAAK DATE,
    DATUMMUTATIE DATE,
    GEACCORDEERD VARCHAR(50),
    GEACCORDEERDDOOR VARCHAR(50),
    GEACCORDEERDOP VARCHAR(255),
    GEEXPORTEERD VARCHAR(50),
    GEMUTEERDDOOR VARCHAR(50),
    HEEFT_VORDERINGREGEL_ID INTEGER,
    HEEFT_VTHZAAK_ID INTEGER,
    OMSCHRIJVING TEXT,
    TOTAALBEDRAG DECIMAL(10,2),
    TOTAALBEDRAGINCLUSIEF DECIMAL(10,2),
    VORDERINGNUMMER VARCHAR(50)
);

CREATE TABLE INSPECTIE (
    INSPECTIE_ID INTEGER PRIMARY KEY,
    AANGEMAAKTDOOR VARCHAR(50),
    DATUMAANMAAK DATE,
    DATUMGEPLAND DATE,
    DATUMINSPECTIE DATE,
    DATUMMUTATIE DATE,
    GEMUTEERDDOOR VARCHAR(50),
    HEEFT_VTHZAAK_ID INTEGER,
    INSPECTIETYPE VARCHAR(50),
    KENMERK VARCHAR(20),
    OMSCHRIJVING VARCHAR(80),
    OPMERKINGEN VARCHAR(80),
    STATUS VARCHAR(20)
);

CREATE TABLE VOMAANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID INTEGER PRIMARY KEY,
    ACTIVITEITEN VARCHAR(255),
    ADRES VARCHAR(255),
    BAGID VARCHAR(255),
    DOSSIERNUMMER VARCHAR(200),
    INTAKETYPE VARCHAR(80),
    INTERNNUMMER VARCHAR(80),
    KADASTRALEAANDUIDING VARCHAR(255),
    KENMERK VARCHAR(80),
    LOCATIE VARCHAR(255),
    LOCATIEOMSCHRIJVING VARCHAR(255),
    TOELICHTING TEXT
);

CREATE TABLE WABOAANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID INTEGER PRIMARY KEY,
    BOUWKOSTEN DECIMAL(10,2),
    OLONUMMER VARCHAR(80),
    OMSCHRIJVING VARCHAR(255),
    PROJECTKOSTEN DECIMAL(10,2),
    REGISTRATIENUMMER VARCHAR(100)
);

CREATE TABLE VTHAANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID INTEGER PRIMARY KEY,
    OMSCHRIJVING VARCHAR(255)
);

CREATE TABLE KP_BSLT_DCMNT (
    KP_BSLT_DCMNT_ID INTEGER PRIMARY KEY,
    BESLUIT_ID INTEGER,
    DOCUMENT_ID INTEGER
);

CREATE TABLE BEVINDING (
    BEVINDING_ID INTEGER PRIMARY KEY,
    AANGEMAAKTDOOR VARCHAR(255),
    ACTIVITEIT VARCHAR(50),
    BEVINDING_SELF_ID INTEGER,
    CONTROLEELEMENT VARCHAR(50),
    CONTROLENIVEAU VARCHAR(50),
    DATUMAANMAAK DATE,
    DATUMMUTATIE DATE,
    DIEPTE VARCHAR(20),
    FASE VARCHAR(20),
    GEMUTEERDDOOR VARCHAR(255),
    HEEFT_INSPECTIE_ID INTEGER,
    RESULTAAT VARCHAR(50),
    RISICO VARCHAR(50)
);

ALTER TABLE HEFFINGSVERORDENING ADD CONSTRAINT FK_HEFFINGSVERORDENING_GEN_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- Generalization to DOCUMENT

ALTER TABLE INDIENER ADD CONSTRAINT FK_INDIENER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE VOMAANVRAAGOFMELDING ADD CONSTRAINT FK_VOMAANVRAAGOFMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE VTHAANVRAAGOFMELDING ADD CONSTRAINT FK_VTHAANVRAAGOFMELDING_GEN_VOMAANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VOMAANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VOMAANVRAAGOFMELDING

ALTER TABLE VTHZAAK ADD CONSTRAINT FK_VTHZAAK_GEN_ZAAK FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- Generalization to ZAAK

ALTER TABLE WABOAANVRAAGOFMELDING ADD CONSTRAINT FK_WABOAANVRAAGOFMELDING_GEN_VOMAANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VOMAANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VOMAANVRAAGOFMELDING

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_BSLT_DCMNT ADD CONSTRAINT FK_KP_BSLT_DCMNT_1 FOREIGN KEY (BESLUIT_ID) REFERENCES BESLUIT (BESLUIT_ID);
-- BESLUIT (many-to-many junction, Connector_ID: 2150)

ALTER TABLE KP_BSLT_DCMNT ADD CONSTRAINT FK_KP_BSLT_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2150)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_1 FOREIGN KEY (BETROKKENE_ID) REFERENCES BETROKKENE (RECHTSPERSOON_ID);
-- BETROKKENE (many-to-many junction, Connector_ID: 2164)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_2 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2164)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_MELDER FOREIGN KEY (MELDER_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- MELDER (1..* to 0..1, Connector_ID: 377)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_HEEFT_DOCUMENTEN FOREIGN KEY (HEEFT_DOCUMENTEN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- HEEFT_DOCUMENTEN (0..1 to 0..*, Connector_ID: 378)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_KAN_LEIDEN_TOT FOREIGN KEY (KAN_LEIDEN_TOT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 380)

ALTER TABLE VORDERING ADD CONSTRAINT FK_VORDERING_HEEFT FOREIGN KEY (HEEFT_VTHZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT (1..* to 1.., Connector_ID: 1301)

ALTER TABLE VORDERING ADD CONSTRAINT FK_VORDERING_HEEFT_2 FOREIGN KEY (HEEFT_VORDERINGREGEL_ID) REFERENCES VORDERINGREGEL (VORDERINGREGEL_ID);
-- HEEFT (1.. to 1..*, Connector_ID: 1302)

ALTER TABLE INSPECTIE ADD CONSTRAINT FK_INSPECTIE_HEEFT FOREIGN KEY (HEEFT_VTHZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT (1..* to 1.., Connector_ID: 1315)

ALTER TABLE AANVRAAGOFMELDING ADD CONSTRAINT FK_AANVRAAGOFMELDING_INGEDIEND_DOOR FOREIGN KEY (INGEDIEND_DOOR_INDIENER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- INGEDIEND_DOOR (0..* to 1, Connector_ID: 1316)

ALTER TABLE HEFFINGSVERORDENING ADD CONSTRAINT FK_HEFFINGSVERORDENING_VERMELD_IN FOREIGN KEY (VERMELD_IN_HEFFINGGRONDSLAG_ID) REFERENCES HEFFINGGRONDSLAG (HEFFINGGRONDSLAG_ID);
-- VERMELD_IN (1 to 0..*, Connector_ID: 1321)

ALTER TABLE BEVINDING ADD CONSTRAINT FK_BEVINDING_BEVINDING FOREIGN KEY (BEVINDING_ID) REFERENCES BEVINDING (BEVINDING_ID);
-- unnamed (1 to 0..*, Connector_ID: 1327)

ALTER TABLE BEVINDING ADD CONSTRAINT FK_BEVINDING_HEEFT FOREIGN KEY (HEEFT_INSPECTIE_ID) REFERENCES INSPECTIE (INSPECTIE_ID);
-- HEEFT (0..* to 1.., Connector_ID: 1328)

ALTER TABLE HEFFING ADD CONSTRAINT FK_HEFFING_BETREFT FOREIGN KEY (BETREFT_VORDERINGREGEL_ID) REFERENCES VORDERINGREGEL (VORDERINGREGEL_ID);
-- BETREFT (0..1 to 1.., Connector_ID: 2049)

ALTER TABLE HEFFING ADD CONSTRAINT FK_HEFFING_HEEFT_GRONDSLAG FOREIGN KEY (HEEFT_GRONDSLAG_HEFFINGGRONDSLAG_ID) REFERENCES HEFFINGGRONDSLAG (HEFFINGGRONDSLAG_ID);
-- HEEFT_GRONDSLAG (0..* to 1, Connector_ID: 2050)

ALTER TABLE HEFFING ADD CONSTRAINT FK_HEFFING_SOORT FOREIGN KEY (SOORT_ENUM_ID) REFERENCES HEFFINGSOORT_ENUM (HEFFINGSOORT_ENUM_ID);
-- SOORT (0..* to 1, Connector_ID: 2051)

ALTER TABLE STATUS ADD CONSTRAINT FK_STATUS_IS_VAN FOREIGN KEY (IS_VAN_STATUSTYPE_ID) REFERENCES STATUSTYPE (STATUSTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2090)

ALTER TABLE ZAAKTYPE ADD CONSTRAINT FK_ZAAKTYPE_HEEFT FOREIGN KEY (HEEFT_STATUSTYPE_ID) REFERENCES STATUSTYPE (STATUSTYPE_ID);
-- HEEFT (1 to 1..*, Connector_ID: 2093)

ALTER TABLE ZAAKTYPE ADD CONSTRAINT FK_ZAAKTYPE_HEEFT_2 FOREIGN KEY (HEEFT_HEFFINGGRONDSLAG_ID) REFERENCES HEFFINGGRONDSLAG (HEFFINGGRONDSLAG_ID);
-- HEEFT (1 to 0..*, Connector_ID: 2097)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT FOREIGN KEY (HEEFT_STATUS_ID) REFERENCES STATUS (STATUS_ID);
-- HEEFT (1 to 0..*, Connector_ID: 2101)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_2 FOREIGN KEY (HEEFT_HEFFING_ID) REFERENCES HEFFING (HEFFING_ID);
-- HEEFT (1 to 0..1, Connector_ID: 2103)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_UITKOMST_VAN FOREIGN KEY (IS_UITKOMST_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_UITKOMST_VAN (0..* to 1, Connector_ID: 2112)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY (IS_VAN_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_VASTGELEGD_IN FOREIGN KEY (IS_VASTGELEGD_IN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- IS_VASTGELEGD_IN (0..1 to 0..1, Connector_ID: 2149)

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_IS FOREIGN KEY (IS_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- IS (0..1 to 1, Connector_ID: 2167)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY (IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2170)

