CREATE TABLE `WOONPLAATS` (
    `WOONPLAATS_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` INT,
    `EINDGELDIGHEID` DATE,
    `EINDREGISTRATIE` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `LIGT_IN_GEMEENTE_ID` INT,
    `STATUS_ENUM_ID` INT,
    `TIJDSTIPACTIEF` DATETIME,
    `TIJDSTIPREGISTRATIE` DATETIME,
    `VERSIE` INT,
    `VOORKOMEN` DATE,
    `WOONPLAATSNAAM` VARCHAR(80),
    `WOONPLAATSNAAMNEN` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `PAND` (
    `PAND_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` VARCHAR(255),
    `BRUTOINHOUDPAND` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` VARCHAR(255),
    `EINDGELDIGHEID` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIEBOVENAANZICHT` GEOMETRY,
    `GEOMETRIEMAAIVELD` GEOMETRY,
    `GEOMETRIEPUNT` GEOMETRY,
    `HOOGSTEBOUWLAAG` VARCHAR(255),
    `IDENTIFICATIE` VARCHAR(255),
    `LAAGSTEBOUWLAAG` VARCHAR(255),
    `OORSPRONKELIJKBOUWJAAR` VARCHAR(255),
    `OPPERVLAKTE` VARCHAR(255),
    `RELATIEVEHOOGTELIGGING` VARCHAR(255),
    `STATUSVOORTGANGBOUW_ENUM_ID` INT,
    `STATUS_ENUM_ID` INT,
    `VERSIE` INT,
    `ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `NUMMERAANDUIDING` (
    `NUMMERAANDUIDING_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` INT,
    `EINDEGELDIGHEID` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `HUISLETTER` VARCHAR(255),
    `HUISNUMMER` VARCHAR(255),
    `HUISNUMMERTOEVOEGING` VARCHAR(255),
    `IDENTIFICATIE` VARCHAR(255),
    `LIGT_AAN_OPENBARERUIMTE_ID` INT,
    `LIGT_IN_BUURT_ID` INT,
    `LIGT_IN_WOONPLAATS_ID` INT,
    `POSTCODE` VARCHAR(255),
    `STATUS_ENUM_ID` INT,
    `TYPEADRESSEERBAAROBJECT_ENUM_ID` INT,
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `GEMEENTE` (
    `GEMEENTE_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `EINDGELDIGHEID` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEMEENTECODE` VARCHAR(255),
    `GEMEENTENAAM` VARCHAR(80),
    `GEMEENTENAAM_NEN` VARCHAR(255),
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `STATUSWOONPLAATS_ENUM` (
    `STATUSWOONPLAATS_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `STATUSWOONPLAATS_ENUM` (`STATUSWOONPLAATS_ENUM_ID`, VALUE) VALUES
    (1, 'LEEG'),
    (2, 'ONBEKEND'),
    (3, 'WOONPLAATS_AANGEWEZEN'),
    (4, 'WOONPLAATS_INGETROKKEN_');

CREATE TABLE `BUURT` (
    `BUURT_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` VARCHAR(255),
    `CODE` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `EINDGELDIGHEID` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `LIGT_IN_WIJK_ID` INT,
    `NAAM` VARCHAR(255),
    `STATUS_ENUM_ID` INT,
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `STATUSOPENBARERUIMTE_ENUM` (
    `STATUSOPENBARERUIMTE_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `STATUSOPENBARERUIMTE_ENUM` (`STATUSOPENBARERUIMTE_ENUM_ID`, VALUE) VALUES
    (1, 'LEEG'),
    (2, 'NAAMGEVING_INGETROKKEN'),
    (3, 'NAAMGEVING_UITGEGEVEN'),
    (4, 'ONBEKEND');

CREATE TABLE `STANDPLAATS` (
    `ADRESSEERBAAROBJECT_ID` INT PRIMARY KEY,
    `DATUM_BEGIN_GELDIGHEID` DATE,
    `DATUM_EINDE` DATE,
    `DATUM_EINDE_GELDIGHEID` DATE,
    `DATUM_INGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` INT,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `STATUS_ENUM_ID` INT,
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_GMNT_IS_OVRGGN_IN` (
    `KP_GMNT_IS_OVRGGN_IN_ID` INT PRIMARY KEY,
    `IS_OVERGEGAAN_IN_1_ID` INT,
    `IS_OVERGEGAAN_IN_2_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `STATUSLIGPLAATS_ENUM` (
    `STATUSLIGPLAATS_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `STATUSLIGPLAATS_ENUM` (`STATUSLIGPLAATS_ENUM_ID`, VALUE) VALUES
    (1, 'LEEG'),
    (2, 'ONBEKEND'),
    (3, 'PLAATS_AANGEWEZEN'),
    (4, 'PLAATS_INGETROKKEN');

CREATE TABLE `TYPEADRESSEERBAAROBJECT_ENUM` (
    `TYPEADRESSEERBAAROBJECT_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `TYPEADRESSEERBAAROBJECT_ENUM` (`TYPEADRESSEERBAAROBJECT_ENUM_ID`, VALUE) VALUES
    (1, 'LIGPLAATS'),
    (2, 'STANDPLAATS'),
    (3, 'VERBLIJFSOBJECT');

CREATE TABLE `OPENBARERUIMTE` (
    `OPENBARERUIMTE_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` INT,
    `EINDGELDIGHEID` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS` VARCHAR(255),
    `HUISNUMMERRANGE_EVEN_NUMMERS` VARCHAR(255),
    `HUISNUMMERRANGE_ONEVEN_NUMMERS` VARCHAR(255),
    `IDENTIFICATIE` VARCHAR(255),
    `LABELNAAM` VARCHAR(80),
    `LIGT_IN_BUURT_ID` INT,
    `LIGT_IN_WOONPLAATS_ID` INT,
    `NAAMOPENBARERUIMTE` VARCHAR(80),
    `STATUS_ENUM_ID` INT,
    `STRAATCODE` VARCHAR(80),
    `STRAATNAAM` VARCHAR(255),
    `TYPEOPENBARERUIMTE_ENUM_ID` INT,
    `VERSIE` INT,
    `WEGSEGMENT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_VRBLJFSBJCT_PND` (
    `KP_VRBLJFSBJCT_PND_ID` INT PRIMARY KEY,
    `VERBLIJFSOBJECT_ID` INT,
    `PAND_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `STATUSSTANDPLAATS_ENUM` (
    `STATUSSTANDPLAATS_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `STATUSSTANDPLAATS_ENUM` (`STATUSSTANDPLAATS_ENUM_ID`, VALUE) VALUES
    (1, 'LEEG'),
    (2, 'ONBEKEND'),
    (3, 'PLAATS_AANGEWEZEN'),
    (4, 'PLAATS_INGETROKKEN');

CREATE TABLE `LIGPLAATS` (
    `ADRESSEERBAAROBJECT_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` DATE,
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` INT,
    `EINDGELDIGHEID` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `STATUS_ENUM_ID` INT,
    `VERSIE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `STATUSVERBLIJFSOBJECT_ENUM` (
    `STATUSVERBLIJFSOBJECT_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `STATUSVERBLIJFSOBJECT_ENUM` (`STATUSVERBLIJFSOBJECT_ENUM_ID`, VALUE) VALUES
    (1, 'LEEG'),
    (2, 'NIET_GEREALISEERD_VERBLIJFSOBJECT'),
    (3, 'ONBEKEND'),
    (4, 'VERBLIJFSOBJECT_BUITEN_GEBRUIK'),
    (5, 'VERBLIJFSOBJECT_GEVORMD'),
    (6, 'VERBLIJFSOBJECT_INGETROKKEN'),
    (7, 'VERBLIJFSOBJECT_IN_GEBRUIK'),
    (8, 'VERBLIJFSOBJECT_IN_GEBRUIK_NIET_INGEMETEN_');

CREATE TABLE `SOORTWOONOBJECT_ENUM` (
    `SOORTWOONOBJECT_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `SOORTWOONOBJECT_ENUM` (`SOORTWOONOBJECT_ENUM_ID`, VALUE) VALUES
    (1, 'BIJZONDER_WOONGEBOUW'),
    (2, 'LEEG'),
    (3, 'ONBEKEND'),
    (4, 'OVERIG_WOONVERBLIJF'),
    (5, 'RECREATIEWONING'),
    (6, 'WONING'),
    (7, 'WOONEENHEID');

CREATE TABLE `STATUSNUMMERAANDUIDING_ENUM` (
    `STATUSNUMMERAANDUIDING_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `STATUSNUMMERAANDUIDING_ENUM` (`STATUSNUMMERAANDUIDING_ENUM_ID`, VALUE) VALUES
    (1, 'LEEG'),
    (2, 'NAAMGEVING_INGETROKKEN'),
    (3, 'NAAMGEVING_UITGEGEVEN'),
    (4, 'ONBEKEND');

CREATE TABLE `BOOLEAN_ENUM` (
    `BOOLEAN_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`, VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE `ADRESSEERBAAROBJECT` (
    `ADRESSEERBAAROBJECT_ID` INT PRIMARY KEY,
    `HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID` INT,
    `HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID` INT,
    `IDENTIFICATIE` VARCHAR(255),
    `TYPEADRESSEERBAAROBJECT_ENUM_ID` INT,
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `VERBLIJFSOBJECT` (
    `ADRESSEERBAAROBJECT_ID` INT PRIMARY KEY,
    `AANTALKAMERS` VARCHAR(255),
    `BEGINGELDIGHEID` DATE,
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `DOCUMENTDATUM` DATE,
    `DOCUMENTNUMMER` INT,
    `EINDGELDIGHEID` DATE,
    `GEBRUIKSDOEL_ENUM_ID` INT,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `HOOGSTEBOUWLAAG` VARCHAR(255),
    `IDENTIFICATIE` VARCHAR(255),
    `LAAGSTEBOUWLAAG` VARCHAR(255),
    `ONTSLUITINGVERDIEPING_ENUM_ID` INT,
    `OPPERVLAKTE` INT,
    `SOORTWOONOBJECT_ENUM_ID` INT,
    `STATUS_ENUM_ID` INT,
    `TOEGANGBOUWLAAG` VARCHAR(255),
    `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `WIJK` (
    `WIJK_ID` INT PRIMARY KEY,
    `BEGINGELDIGHEID` VARCHAR(255),
    `DATUMEINDE` DATE,
    `DATUMINGANG` DATE,
    `EINDGELDIGHEID` DATE,
    `GECONSTATEERD_ENUM_ID` INT,
    `GEOMETRIE` GEOMETRY,
    `IDENTIFICATIE` VARCHAR(255),
    `LIGT_IN_WOONPLAATS_ID` INT,
    `STATUS_ENUM_ID` INT,
    `VERSIE` INT,
    `WIJKCODE` VARCHAR(255),
    `WIJKNAAM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `GEBRUIKSDOEL_ENUM` (
    `GEBRUIKSDOEL_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `GEBRUIKSDOEL_ENUM` (`GEBRUIKSDOEL_ENUM_ID`, VALUE) VALUES
    (1, 'BIJEENKOMSTFUNCTIE'),
    (2, 'CELFUNCTIE_'),
    (3, 'GEZONDHEIDSZORGFUNCTIE'),
    (4, 'INDUSTRIEFUNCTIE'),
    (5, 'KANTOORFUNCTIE'),
    (6, 'LEEG'),
    (7, 'LOGIESFUNCTIE'),
    (8, 'ONBEKEND'),
    (9, 'ONDERWIJSFUNCTIE_'),
    (10, 'OVERIGE_GEBRUIKSFUNCTIE_'),
    (11, 'SPORTFUNCTIE_'),
    (12, 'WINKELFUNCTIE_'),
    (13, 'WOONFUNCTIE_');

CREATE TABLE `STATUSPAND_ENUM` (
    `STATUSPAND_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `STATUSPAND_ENUM` (`STATUSPAND_ENUM_ID`, VALUE) VALUES
    (1, 'BOUWAANVRAAG_ONTVANGEN'),
    (2, 'BOUWVERGUNNING_VERLEEND'),
    (3, 'BOUW_GESTART'),
    (4, 'LEEG'),
    (5, 'NIET_GEREALISEERD_PAND'),
    (6, 'ONBEKEND'),
    (7, 'PAND_BUITEN_GEBRUIK'),
    (8, 'PAND_GESLOOPT'),
    (9, 'PAND_IN_GEBRUIK'),
    (10, 'PAND_IN_GEBRUIK_NIET_INGEMETEN_'),
    (11, 'PAND_TEN_ONRECHTE_OPGEVOERD'),
    (12, 'SLOOPVERGUNNING_VERLEEND'),
    (13, 'VERBOUWING_PAND');

CREATE TABLE `ONTSLUITINGSWIJZEVERDIEPING_ENUM` (
    `ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `ONTSLUITINGSWIJZEVERDIEPING_ENUM` (`ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID`, VALUE) VALUES
    (1, 'LEEG'),
    (2, 'LIFT'),
    (3, 'ONBEKEND'),
    (4, 'ROLTRAP'),
    (5, 'TRAP');

CREATE TABLE `STATUSVOORTGANGBOUW_ENUM` (
    `STATUSVOORTGANGBOUW_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `STATUSVOORTGANGBOUW_ENUM` (`STATUSVOORTGANGBOUW_ENUM_ID`, VALUE) VALUES
    (1, 'LEEG'),
    (2, 'NIEUWBOUWVERGUNNING_INGETROKKEN'),
    (3, 'NIEUWBOUWVERGUNNING_VERLEEND'),
    (4, 'NIEUWBOUW_GEREED'),
    (5, 'NIEUWBOUW_GESTART'),
    (6, 'ONBEKEND'),
    (7, 'SLOOPVERGUNNING_INGETROKKEN'),
    (8, 'SLOOPVERGUNNING_VERLEEND'),
    (9, 'SLOOP_GEREED'),
    (10, 'SLOOP_GESTART'),
    (11, 'VERBOUWVERGUNNING_INGETROKKEN'),
    (12, 'VERBOUWVERGUNNING_VERLEEND'),
    (13, 'VERBOUW_GEREED'),
    (14, 'VERBOUW_GESTART');

CREATE TABLE `TYPERINGOPENBARERUIMTE_ENUM` (
    `TYPERINGOPENBARERUIMTE_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `TYPERINGOPENBARERUIMTE_ENUM` (`TYPERINGOPENBARERUIMTE_ENUM_ID`, VALUE) VALUES
    (1, 'ADMINISTRATIEF_GEBIED'),
    (2, 'FUNCTIONEEL_GEBIED'),
    (3, 'KUNSTWERK'),
    (4, 'LANDSCHAPPELIJK_GEBIED'),
    (5, 'LEEG'),
    (6, 'ONBEKEND'),
    (7, 'SPOORBAAN'),
    (8, 'TERREIN'),
    (9, 'WATER'),
    (10, 'WEG');

ALTER TABLE `VERBLIJFSOBJECT` ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (`ADRESSEERBAAROBJECT_ID`) REFERENCES `ADRESSEERBAAROBJECT` (`ADRESSEERBAAROBJECT_ID`);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE `LIGPLAATS` ADD CONSTRAINT FK_LIGPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (`ADRESSEERBAAROBJECT_ID`) REFERENCES `ADRESSEERBAAROBJECT` (`ADRESSEERBAAROBJECT_ID`);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE `STANDPLAATS` ADD CONSTRAINT FK_STANDPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (`ADRESSEERBAAROBJECT_ID`) REFERENCES `ADRESSEERBAAROBJECT` (`ADRESSEERBAAROBJECT_ID`);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE `KP_GMNT_IS_OVRGGN_IN` ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_1 FOREIGN KEY (`IS_OVERGEGAAN_IN_1_ID`) REFERENCES `GEMEENTE` (`GEMEENTE_ID`);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE `KP_GMNT_IS_OVRGGN_IN` ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_2 FOREIGN KEY (`IS_OVERGEGAAN_IN_2_ID`) REFERENCES `GEMEENTE` (`GEMEENTE_ID`);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE `KP_VRBLJFSBJCT_PND` ADD CONSTRAINT FK_KP_VRBLJFSBJCT_PND_1 FOREIGN KEY (`VERBLIJFSOBJECT_ID`) REFERENCES `VERBLIJFSOBJECT` (`ADRESSEERBAAROBJECT_ID`);
-- VERBLIJFSOBJECT (many-to-many junction, Connector_ID: 2305)

ALTER TABLE `KP_VRBLJFSBJCT_PND` ADD CONSTRAINT FK_KP_VRBLJFSBJCT_PND_2 FOREIGN KEY (`PAND_ID`) REFERENCES `PAND` (`PAND_ID`);
-- PAND (many-to-many junction, Connector_ID: 2305)

ALTER TABLE `OPENBARERUIMTE` ADD CONSTRAINT FK_OPENBARERUIMTE_LIGT_IN FOREIGN KEY (`LIGT_IN_BUURT_ID`) REFERENCES `BUURT` (`BUURT_ID`);
-- LIGT_IN (1 to 1..*, Connector_ID: 2264)

ALTER TABLE `ADRESSEERBAAROBJECT` ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY (`HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID`) REFERENCES `NUMMERAANDUIDING` (`NUMMERAANDUIDING_ID`);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE `NUMMERAANDUIDING` ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_IN FOREIGN KEY (`LIGT_IN_BUURT_ID`) REFERENCES `BUURT` (`BUURT_ID`);
-- LIGT_IN (1 to 1, Connector_ID: 2272)

ALTER TABLE `ADRESSEERBAAROBJECT` ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (`HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID`) REFERENCES `NUMMERAANDUIDING` (`NUMMERAANDUIDING_ID`);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE `NUMMERAANDUIDING` ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY (`LIGT_AAN_OPENBARERUIMTE_ID`) REFERENCES `OPENBARERUIMTE` (`OPENBARERUIMTE_ID`);
-- LIGT_AAN (0..* to 1, Connector_ID: 2281)

ALTER TABLE `NUMMERAANDUIDING` ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_IN_2 FOREIGN KEY (`LIGT_IN_WOONPLAATS_ID`) REFERENCES `WOONPLAATS` (`WOONPLAATS_ID`);
-- LIGT_IN (0..* to 0..1, Connector_ID: 2283)

ALTER TABLE `OPENBARERUIMTE` ADD CONSTRAINT FK_OPENBARERUIMTE_LIGT_IN_2 FOREIGN KEY (`LIGT_IN_WOONPLAATS_ID`) REFERENCES `WOONPLAATS` (`WOONPLAATS_ID`);
-- LIGT_IN (1..* to 1, Connector_ID: 2288)

ALTER TABLE `WOONPLAATS` ADD CONSTRAINT FK_WOONPLAATS_LIGT_IN FOREIGN KEY (`LIGT_IN_GEMEENTE_ID`) REFERENCES `GEMEENTE` (`GEMEENTE_ID`);
-- LIGT_IN (1..* to 1.., Connector_ID: 2290)

ALTER TABLE `WIJK` ADD CONSTRAINT FK_WIJK_LIGT_IN FOREIGN KEY (`LIGT_IN_WOONPLAATS_ID`) REFERENCES `WOONPLAATS` (`WOONPLAATS_ID`);
-- LIGT_IN (1..* to 1, Connector_ID: 2294)

ALTER TABLE `BUURT` ADD CONSTRAINT FK_BUURT_LIGT_IN FOREIGN KEY (`LIGT_IN_WIJK_ID`) REFERENCES `WIJK` (`WIJK_ID`);
-- LIGT_IN (1..* to 1, Connector_ID: 2297)

ALTER TABLE `PAND` ADD CONSTRAINT FK_PAND_ZONDER_VERBLIJFSOBJECT_LIGT_IN FOREIGN KEY (`ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_ID`) REFERENCES `BUURT` (`BUURT_ID`);
-- ZONDER_VERBLIJFSOBJECT_LIGT_IN (0..* to 0..1, Connector_ID: 2300)

ALTER TABLE `PAND` ADD CONSTRAINT FK_PAND_STATUSVOORTGANGBOUW_ENUM_ID FOREIGN KEY (`STATUSVOORTGANGBOUW_ENUM_ID`) REFERENCES `STATUSVOORTGANGBOUW_ENUM` (`STATUSVOORTGANGBOUW_ENUM_ID`);
-- STATUSVOORTGANGBOUW_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `PAND` ADD CONSTRAINT FK_PAND_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSPAND_ENUM` (`STATUSPAND_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `PAND` ADD CONSTRAINT FK_PAND_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `WIJK` ADD CONSTRAINT FK_WIJK_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSOPENBARERUIMTE_ENUM` (`STATUSOPENBARERUIMTE_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `WIJK` ADD CONSTRAINT FK_WIJK_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `WOONPLAATS` ADD CONSTRAINT FK_WOONPLAATS_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSWOONPLAATS_ENUM` (`STATUSWOONPLAATS_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `WOONPLAATS` ADD CONSTRAINT FK_WOONPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `NUMMERAANDUIDING` ADD CONSTRAINT FK_NUMMERAANDUIDING_TYPEADRESSEERBAAROBJECT_ENUM_ID FOREIGN KEY (`TYPEADRESSEERBAAROBJECT_ENUM_ID`) REFERENCES `TYPEADRESSEERBAAROBJECT_ENUM` (`TYPEADRESSEERBAAROBJECT_ENUM_ID`);
-- TYPEADRESSEERBAAROBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `NUMMERAANDUIDING` ADD CONSTRAINT FK_NUMMERAANDUIDING_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSNUMMERAANDUIDING_ENUM` (`STATUSNUMMERAANDUIDING_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `NUMMERAANDUIDING` ADD CONSTRAINT FK_NUMMERAANDUIDING_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `BUURT` ADD CONSTRAINT FK_BUURT_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSOPENBARERUIMTE_ENUM` (`STATUSOPENBARERUIMTE_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `BUURT` ADD CONSTRAINT FK_BUURT_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VERBLIJFSOBJECT` ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEBRUIKSDOEL_ENUM_ID FOREIGN KEY (`GEBRUIKSDOEL_ENUM_ID`) REFERENCES `GEBRUIKSDOEL_ENUM` (`GEBRUIKSDOEL_ENUM_ID`);
-- GEBRUIKSDOEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VERBLIJFSOBJECT` ADD CONSTRAINT FK_VERBLIJFSOBJECT_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VERBLIJFSOBJECT` ADD CONSTRAINT FK_VERBLIJFSOBJECT_ONTSLUITINGVERDIEPING_ENUM_ID FOREIGN KEY (`ONTSLUITINGVERDIEPING_ENUM_ID`) REFERENCES `ONTSLUITINGSWIJZEVERDIEPING_ENUM` (`ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID`);
-- ONTSLUITINGVERDIEPING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VERBLIJFSOBJECT` ADD CONSTRAINT FK_VERBLIJFSOBJECT_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSVERBLIJFSOBJECT_ENUM` (`STATUSVERBLIJFSOBJECT_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VERBLIJFSOBJECT` ADD CONSTRAINT FK_VERBLIJFSOBJECT_SOORTWOONOBJECT_ENUM_ID FOREIGN KEY (`SOORTWOONOBJECT_ENUM_ID`) REFERENCES `SOORTWOONOBJECT_ENUM` (`SOORTWOONOBJECT_ENUM_ID`);
-- SOORTWOONOBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `LIGPLAATS` ADD CONSTRAINT FK_LIGPLAATS_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSLIGPLAATS_ENUM` (`STATUSLIGPLAATS_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `LIGPLAATS` ADD CONSTRAINT FK_LIGPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `STANDPLAATS` ADD CONSTRAINT FK_STANDPLAATS_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSSTANDPLAATS_ENUM` (`STATUSSTANDPLAATS_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `STANDPLAATS` ADD CONSTRAINT FK_STANDPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `ADRESSEERBAAROBJECT` ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_TYPEADRESSEERBAAROBJECT_ENUM_ID FOREIGN KEY (`TYPEADRESSEERBAAROBJECT_ENUM_ID`) REFERENCES `TYPEADRESSEERBAAROBJECT_ENUM` (`TYPEADRESSEERBAAROBJECT_ENUM_ID`);
-- TYPEADRESSEERBAAROBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `OPENBARERUIMTE` ADD CONSTRAINT FK_OPENBARERUIMTE_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `STATUSOPENBARERUIMTE_ENUM` (`STATUSOPENBARERUIMTE_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `OPENBARERUIMTE` ADD CONSTRAINT FK_OPENBARERUIMTE_TYPEOPENBARERUIMTE_ENUM_ID FOREIGN KEY (`TYPEOPENBARERUIMTE_ENUM_ID`) REFERENCES `TYPERINGOPENBARERUIMTE_ENUM` (`TYPERINGOPENBARERUIMTE_ENUM_ID`);
-- TYPEOPENBARERUIMTE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `OPENBARERUIMTE` ADD CONSTRAINT FK_OPENBARERUIMTE_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `GEMEENTE` ADD CONSTRAINT FK_GEMEENTE_GECONSTATEERD_ENUM_ID FOREIGN KEY (`GECONSTATEERD_ENUM_ID`) REFERENCES `BOOLEAN_ENUM` (`BOOLEAN_ENUM_ID`);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

