CREATE TABLE BEPERKINGSCATEGORIE (
    BEPERKINGSCATEGORIE_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(255),
    WET VARCHAR2(255)
);

CREATE TABLE BEPERKINGSCORESOORT (
    BEPERKINGSCORESOORT_ID NUMBER PRIMARY KEY,
    VRAAG VARCHAR2(200),
    WET VARCHAR2(255)
);

CREATE TABLE BESCHIKKING (
    BESCHIKKING_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(20),
    COMMENTAAR VARCHAR2(200),
    DATUMAFGIFTE DATE,
    GRONDSLAGEN NUMBER,
    WET VARCHAR2(255)
);

CREATE TABLE BEPERKINGSCORE (
    BEPERKINGSCORE_ID NUMBER PRIMARY KEY,
    COMMENTAAR VARCHAR2(200),
    IS_EEN_BEPERKINGSCORESOORT_ID NUMBER,
    SCORE NUMBER,
    WET VARCHAR2(255)
);

CREATE TABLE BEPERKING (
    BEPERKING_ID NUMBER PRIMARY KEY,
    BEPERKINGSCORE_ID NUMBER,
    CATEGORIE NUMBER,
    COMMENTAAR NUMBER,
    DUUR NUMBER,
    IS_EEN_BEPERKINGSCATEGORIE_ID NUMBER,
    IS_GEBASEERD_OP_BESCHIKKING_ID NUMBER,
    WET VARCHAR2(255)
);

ALTER TABLE BEPERKINGSCORE ADD CONSTRAINT FK_BEPERKINGSCORE_IS_EEN FOREIGN KEY (IS_EEN_BEPERKINGSCORESOORT_ID) REFERENCES BEPERKINGSCORESOORT (BEPERKINGSCORESOORT_ID);
-- IS_EEN (0..* to 0..1, Connector_ID: 1070)

ALTER TABLE BEPERKING ADD CONSTRAINT FK_BEPERKING_BEPERKINGSCORE FOREIGN KEY (BEPERKINGSCORE_ID) REFERENCES BEPERKINGSCORE (BEPERKINGSCORE_ID);
-- unnamed (0..1 to 0..*, Connector_ID: 1071)

ALTER TABLE BEPERKING ADD CONSTRAINT FK_BEPERKING_IS_GEBASEERD_OP FOREIGN KEY (IS_GEBASEERD_OP_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- IS_GEBASEERD_OP (0..* to 0..1, Connector_ID: 1072)

ALTER TABLE BEPERKING ADD CONSTRAINT FK_BEPERKING_IS_EEN FOREIGN KEY (IS_EEN_BEPERKINGSCATEGORIE_ID) REFERENCES BEPERKINGSCATEGORIE (BEPERKINGSCATEGORIE_ID);
-- IS_EEN (0..* to 0..1, Connector_ID: 1073)

