CREATE TABLE [NATUURLIJKPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [AANDUIDINGNAAMGEBRUIK] VARCHAR(50),
    [AANHEFAANSCHRIJVING] VARCHAR(50),
    [ACADEMISCHETITEL] VARCHAR(80),
    [ACHTERNAAM] VARCHAR(100),
    [ADELLIJKETITELOFPREDIKAAT] VARCHAR(255),
    [ANUMMER] VARCHAR(20),
    [BIJZONDERNEDERLANDERSCHAP] VARCHAR(50),
    [BURGERSERVICENUMMER] VARCHAR(255),
    [DATUMGEBOORTE] DATE,
    [DATUMOVERLIJDEN] DATE,
    [GEBOORTELAND] VARCHAR(255),
    [GEBOORTEPLAATS] VARCHAR(200),
    [GESLACHTSAANDUIDING] VARCHAR(255),
    [GESLACHTSNAAM] VARCHAR(200),
    [GESLACHTSNAAMAANSCHRIJVING] VARCHAR(200),
    [HANDLICHTING] VARCHAR(50),
    [INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID] INT,
    [INDICATIEOVERLEDEN_ENUM_ID] INT,
    [LANDOVERLIJDEN] VARCHAR(255),
    [NATIONALITEIT] VARCHAR(100),
    [OVERLIJDENSPLAATS] VARCHAR(200),
    [VOORLETTERSAANSCHRIJVING] VARCHAR(20),
    [VOORNAMEN] VARCHAR(200),
    [VOORNAMENAANSCHRIJVING] VARCHAR(200),
    [VOORVOEGSELGESLACHTSNAAM] VARCHAR(80)
);

CREATE TABLE [MEDEWERKER] (
    [MEDEWERKER_ID] INT PRIMARY KEY,
    [ACHTERNAAM] VARCHAR(200),
    [DATUMINDIENST] DATE,
    [DATUMUITDIENST] DATE,
    [EMAILADRES] VARCHAR(255),
    [EXTERN_ENUM_ID] INT,
    [FUNCTIE] VARCHAR(50),
    [GESLACHTSAANDUIDING] VARCHAR(255),
    [MEDEWERKERIDENTIFICATIE] VARCHAR(255),
    [MEDEWERKERTOELICHTING] VARCHAR(255),
    [ROEPNAAM] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20),
    [VOORLETTERS] VARCHAR(20),
    [VOORVOEGSELACHTERNAAM] VARCHAR(255)
);

CREATE TABLE [DECLARATIEREGEL] (
    [DECLARATIEREGEL_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [BETREFT_CLIENT_ID] INT,
    [CODE] VARCHAR(20),
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [IS_VOOR_BESCHIKKING_ID] INT,
    [VALT_BINNEN_DECLARATIE_ID] INT
);

CREATE TABLE [INGESCHREVENPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [ADRESHERKOMST] VARCHAR(255),
    [ANUMMER] VARCHAR(20),
    [BESCHRIJVINGLOCATIE] VARCHAR(200),
    [BUITENLANDSREISDOCUMENT] VARCHAR(80),
    [BURGERLIJKESTAAT] VARCHAR(255),
    [DATUMBEGINGELDIGHEIDVERBLIJFPLAATS] DATE,
    [DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS] DATE,
    [DATUMINSCHRIJVINGGEMEENTE] DATE,
    [DATUMOPSCHORTINGBIJHOUDING] DATE,
    [DATUMVERTREKUITNEDERLAND] DATE,
    [DATUMVESTIGINGNEDERLAND] DATE,
    [GEMEENTEVANINSCHRIJVING] VARCHAR(80),
    [GEZINSRELATIE] VARCHAR(255),
    [INDICATIEGEHEIM_ENUM_ID] INT,
    [INGEZETENE_ENUM_ID] INT,
    [LANDWAARNAARVERTROKKEN] VARCHAR(255),
    [LANDWAARVANDAANINGESCHREVEN] VARCHAR(255),
    [OUDER1] VARCHAR(255),
    [OUDER2] VARCHAR(255),
    [OUDER_1_INGESCHREVENPERSOON_ID] INT,
    [OUDER_2_INGESCHREVENPERSOON_ID] INT,
    [PARTNERID] VARCHAR(255),
    [REDENEINDEBEWONING] DATE,
    [REDENOPSCHORTINGBIJHOUDING] VARCHAR(200),
    [SIGNALERINGREISDOCUMENT_ENUM_ID] INT,
    [VERBLIJFSTITEL] VARCHAR(255)
);

CREATE TABLE [EENHEID_ENUM] (
    [EENHEID_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [EENHEID_ENUM] ([EENHEID_ENUM_ID], VALUE) VALUES
    (1, 'DAGDEEL_4_UUR_'),
    (2, 'ETMAAL'),
    (3, 'EUROS'),
    (4, 'LEEG'),
    (5, 'MINUUT'),
    (6, 'ONBEKEND'),
    (7, 'STUKS'),
    (8, 'UUR');

CREATE TABLE [VOORZIENING] (
    [VOORZIENING_ID] INT PRIMARY KEY,
    [AFHANDELWIJZE] VARCHAR(200),
    [CODE] VARCHAR(20),
    [HEEFT_TARIEF_ID] INT,
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [PRODUCTCODE] VARCHAR(255),
    [VALT_BINNEN_VOORZIENINGSOORT_ID] INT,
    [WET_ENUM_ID] INT
);

CREATE TABLE [PGB_TOEKENNING] (
    [PGB_TOEKENNING_ID] INT PRIMARY KEY,
    [BETREFT_BESCHIKTE_VOORZIENING_ID] INT,
    [BETREFT_BUDGETUITPUTTING_ID] INT,
    [BUDGET] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMTOEKENNING] DATE
);

CREATE TABLE [LEVERINGSVORM_293] (
    [LEVERINGSVORM_293_ID] INT PRIMARY KEY,
    [LEVERINGSVORMCODE] VARCHAR(20),
    [NAAM] VARCHAR(255),
    [WET_ENUM_ID] INT
);

CREATE TABLE [CLIENT] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [CODE] VARCHAR(80),
    [GEZAGSDRAGERGEKEND_ENUM_ID] INT,
    [JURIDISCHESTATUS] VARCHAR(80),
    [WETTELIJKEVERTEGENWOORDIGING] VARCHAR(80)
);

CREATE TABLE [LEVERING] (
    [LEVERING_ID] INT PRIMARY KEY,
    [CODE] VARCHAR(20),
    [DATUMSTART] DATE,
    [DATUMSTOP] DATE,
    [EENHEID_ENUM_ID] INT,
    [FREQUENTIE_ENUM_ID] INT,
    [GELEVERDE_PRESTATIE_BESCHIKKING_ID] INT,
    [GELEVERDE_ZORG_TOEWIJZING_ID] INT,
    [OMVANG] INT,
    [PRESTATIE_VOOR_CLIENT_ID] INT,
    [STOPREDEN] NVARCHAR(MAX),
    [VOORZIENING_VOORZIENING_ID] INT
);

CREATE TABLE [CONTRACT] (
    [CONTRACT_ID] INT PRIMARY KEY,
    [AUTORISATIEGROEP] VARCHAR(200),
    [BESCHRIJVING] NVARCHAR(MAX),
    [BEVAT_TARIEF_ID] INT,
    [BOVENLIGGEND_CONTRACT_ID] INT,
    [CATEGORIE] VARCHAR(80),
    [CLASSIFICATIE] VARCHAR(80),
    [CONTRACTREVISIE] INT,
    [DATUMCREATIE] DATE,
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [GROEP] VARCHAR(80),
    [INTERNCONTRACTID] VARCHAR(255),
    [INTERNCONTRACTREVISIE] INT,
    [OPMERKINGEN] NVARCHAR(MAX),
    [STATUS] VARCHAR(80),
    [TYPE] VARCHAR(80),
    [VOORWAARDE] VARCHAR(80),
    [ZOEKWOORDEN] VARCHAR(255)
);

CREATE TABLE [BOOLEAN_ENUM] (
    [BOOLEAN_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID], VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE [LEVERINGSVORM_309_ENUM] (
    [LEVERINGSVORM_309_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [LEVERINGSVORM_309_ENUM] ([LEVERINGSVORM_309_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'ONBEKEND'),
    (3, 'PGB'),
    (4, 'ZIN');

CREATE TABLE [CLIENTBEGELEIDER] (
    [MEDEWERKER_ID] INT PRIMARY KEY,
    [BEGELEIDERSCODE] VARCHAR(20),
    [GEEFT_AF_BESCHIKKING_ID] INT
);

CREATE TABLE [TARIEF] (
    [TARIEF_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [EENHEID_ENUM_ID] INT,
    [HEEFT_LEVERANCIER_ID] INT,
    [WET_ENUM_ID] INT
);

CREATE TABLE [KP_CLNTBGLDR_CLNT] (
    [KP_CLNTBGLDR_CLNT_ID] INT PRIMARY KEY,
    [CLIENTBEGELEIDER_ID] INT,
    [CLIENT_ID] INT
);

CREATE TABLE [RECHTSPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [ADRESBINNENLAND] VARCHAR(255),
    [ADRESBUITENLAND] VARCHAR(255),
    [ADRESCORRESPONDENTIE] VARCHAR(100),
    [EMAILADRES] VARCHAR(80),
    [FAXNUMMER] VARCHAR(20),
    [IDENTIFICATIE] VARCHAR(255),
    [KVKNUMMER] VARCHAR(20),
    [NAAM] VARCHAR(200),
    [RECHTSVORM] VARCHAR(100),
    [REKENINGNUMMER] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20)
);

CREATE TABLE [TOEWIJZING] (
    [TOEWIJZING_ID] INT PRIMARY KEY,
    [CODE] VARCHAR(20),
    [COMMENTAAR] NVARCHAR(MAX),
    [DATUMAANSCHAF] DATE,
    [DATUMEINDETOEWIJZING] DATE,
    [DATUMSTARTTOEWIJZING] DATE,
    [DATUMTOEWIJZING] DATE,
    [EENHEID_ENUM_ID] INT,
    [FREQUENTIE_ENUM_ID] INT,
    [IS_OP_BASIS_VAN_DECLARATIEREGEL_ID] INT,
    [LEVERT_VOORZIENING_LEVERANCIER_ID] INT,
    [OMVANG] VARCHAR(255),
    [REDENWIJZIGING] INT,
    [TOEWIJZINGNUMMER] VARCHAR(255),
    [WET_ENUM_ID] INT
);

CREATE TABLE [FREQUENTIE_ENUM] (
    [FREQUENTIE_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [FREQUENTIE_ENUM] ([FREQUENTIE_ENUM_ID], VALUE) VALUES
    (1, 'BINNEN_GELDIGHEID_BESCHIKKING'),
    (2, 'LEEG'),
    (3, 'ONBEKEND'),
    (4, 'PER_4_WEKEN'),
    (5, 'PER_DAG'),
    (6, 'PER_JAAR'),
    (7, 'PER_MAAND'),
    (8, 'PER_WEEK');

CREATE TABLE [DECLARATIE] (
    [DECLARATIE_ID] INT PRIMARY KEY,
    [DATUMDECLARATIE] DATE,
    [DECLARATIEBEDRAG] DECIMAL(10,2),
    [DECLARATIESTATUS] INT,
    [INGEDIEND_DOOR_LEVERANCIER_ID] INT
);

CREATE TABLE [WET_ENUM] (
    [WET_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [WET_ENUM] ([WET_ENUM_ID], VALUE) VALUES
    (1, 'ANDERE_WET'),
    (2, 'BIJZONDERE_BIJSTAND'),
    (3, 'I_O_A_W_I_O_A_Z_'),
    (4, 'JEUGDWET'),
    (5, 'LEEG'),
    (6, 'NIET_VAN_TOEPASSING'),
    (7, 'ONBEKEND'),
    (8, 'PARTICIPATIEWET_PW_I'),
    (9, 'WMO');

CREATE TABLE [VERZOEK_OM_TOEWIJZING] (
    [VERZOEK_OM_TOEWIJZING_ID] INT PRIMARY KEY,
    [BESCHIKKINGSNUMMER] VARCHAR(255),
    [BETREFT_CLIENT_ID] INT,
    [BETREFT_VOORZIENING_ID] INT,
    [COMMENTAAR] NVARCHAR(MAX),
    [DATUMEINDETOEWIJZING] DATE,
    [DATUMINGANGBESCHIKKING] DATE,
    [DATUMINGANGTOEWIJZING] DATE,
    [DATUMONTVANGST] DATE,
    [EENHEID_ENUM_ID] INT,
    [FREQUENTIE_ENUM_ID] INT,
    [LEIDT_TOT_BESCHIKKING_ID] INT,
    [LEVERANCIER_LEVERANCIER_ID] INT,
    [RAAMCONTRACT_ENUM_ID] INT,
    [REFERENTIEAANBIEDER] VARCHAR(255),
    [SOORTVERWIJZER_ENUM_ID] INT,
    [VERWIJZER] VARCHAR(200),
    [VOLUME] INT
);

CREATE TABLE [VOORZIENINGSOORT] (
    [VOORZIENINGSOORT_ID] INT PRIMARY KEY,
    [CODE] VARCHAR(20),
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [PRODUCTCATEGORIE] VARCHAR(200),
    [PRODUCTCATEGORIECODE] VARCHAR(20),
    [PRODUCTCODE] VARCHAR(20),
    [WET_ENUM_ID] INT
);

CREATE TABLE [MELDING_EIGEN_BIJDRAGE] (
    [MELDING_EIGEN_BIJDRAGE_ID] INT PRIMARY KEY,
    [BETREFT_BESCHIKKING_ID] INT,
    [DATUMSTART] DATE,
    [DATUMSTOP] DATE
);

CREATE TABLE [BESCHIKKING] (
    [BESCHIKKING_ID] INT PRIMARY KEY,
    [CLIENT_ID] INT,
    [CODE] VARCHAR(20),
    [COMMENTAAR] VARCHAR(200),
    [DATUMAFGIFTE] DATE,
    [GRONDSLAGEN] INT,
    [HEEFT_VOORZIENINGEN_BESCHIKTE_VOORZIENING_ID] INT,
    [TOEWIJZING_TOEWIJZING_ID] INT,
    [WET_ENUM_ID] INT
);

CREATE TABLE [SOORT_VERWIJZER_ENUM] (
    [SOORT_VERWIJZER_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [SOORT_VERWIJZER_ENUM] ([SOORT_VERWIJZER_ENUM_ID], VALUE) VALUES
    (1, 'GECERTIFICEERDE_INSTELLING'),
    (2, 'GEMEENTE'),
    (3, 'HUISARTS'),
    (4, 'JEUGDARTS'),
    (5, 'LEEG'),
    (6, 'MEDISCH_SPECIALIST'),
    (7, 'ONBEKEND'),
    (8, 'RECHTER_OFFICIER_VAN_JUSTITIE_FUNCTIONARIS_JUSTITIËLE_JEUGDINRICHTING'),
    (9, 'ZELFVERWIJZER_GEEN_VERWIJZER');

CREATE TABLE [BESCHIKTE_VOORZIENING] (
    [BESCHIKTE_VOORZIENING_ID] INT PRIMARY KEY,
    [CODE] VARCHAR(20),
    [DATUMEINDE] DATE,
    [DATUMEINDEOORSPRONKELIJK] DATE,
    [DATUMSTART] DATE,
    [EENHEID_ENUM_ID] INT,
    [FREQUENTIE_ENUM_ID] INT,
    [HEEFT_LEVERINGSVORM_293_ID] INT,
    [IS_VOORZIENING_VOORZIENING_ID] INT,
    [LEVERINGSVORM_287_ENUM_ID] INT,
    [OMVANG] INT,
    [REDENEINDE] DATE,
    [STATUS] VARCHAR(50),
    [TOEGEWEZEN_PRODUCT_TOEWIJZING_ID] INT,
    [WET_ENUM_ID] INT
);

CREATE TABLE [LEVERANCIER] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [AGBCODE] VARCHAR(255),
    [HEEFT_CONTRACT_ID] INT,
    [LEVERANCIERSCODE] VARCHAR(255),
    [LEVERDE_PRESTATIE_LEVERING_ID] INT,
    [NAAM] VARCHAR(200),
    [SOORTLEVERANCIER] VARCHAR(80),
    [SOORTLEVERANCIERCODE] VARCHAR(255)
);

CREATE TABLE [BUDGETUITPUTTING] (
    [BUDGETUITPUTTING_ID] INT PRIMARY KEY,
    [DATUM] DATE,
    [UITGENUTBEDRAG] DECIMAL(10,2)
);

ALTER TABLE [CLIENT] ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [INGESCHREVENPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE [CLIENTBEGELEIDER] ADD CONSTRAINT FK_CLIENTBEGELEIDER_GEN_MEDEWERKER FOREIGN KEY ([MEDEWERKER_ID]) REFERENCES [MEDEWERKER] ([MEDEWERKER_ID]);
-- Generalization to MEDEWERKER

ALTER TABLE [LEVERANCIER] ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [NATUURLIJKPERSOON] ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [NATUURLIJKPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE [KP_CLNTBGLDR_CLNT] ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_1 FOREIGN KEY ([CLIENTBEGELEIDER_ID]) REFERENCES [CLIENTBEGELEIDER] ([MEDEWERKER_ID]);
-- CLIENTBEGELEIDER (many-to-many junction, Connector_ID: 941)

ALTER TABLE [KP_CLNTBGLDR_CLNT] ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_2 FOREIGN KEY ([CLIENT_ID]) REFERENCES [CLIENT] ([RECHTSPERSOON_ID]);
-- CLIENT (many-to-many junction, Connector_ID: 941)

ALTER TABLE [CONTRACT] ADD CONSTRAINT FK_CONTRACT_BOVENLIGGEND FOREIGN KEY ([BOVENLIGGEND_CONTRACT_ID]) REFERENCES [CONTRACT] ([CONTRACT_ID]);
-- BOVENLIGGEND (0..* to 0..1, Connector_ID: 405)

ALTER TABLE [LEVERANCIER] ADD CONSTRAINT FK_LEVERANCIER_HEEFT FOREIGN KEY ([HEEFT_CONTRACT_ID]) REFERENCES [CONTRACT] ([CONTRACT_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 926)

ALTER TABLE [VOORZIENING] ADD CONSTRAINT FK_VOORZIENING_VALT_BINNEN FOREIGN KEY ([VALT_BINNEN_VOORZIENINGSOORT_ID]) REFERENCES [VOORZIENINGSOORT] ([VOORZIENINGSOORT_ID]);
-- VALT_BINNEN (0..* to 1, Connector_ID: 1031)

ALTER TABLE [VERZOEK_OM_TOEWIJZING] ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_BETREFT FOREIGN KEY ([BETREFT_CLIENT_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- BETREFT (0..* to 1, Connector_ID: 1032)

ALTER TABLE [VERZOEK_OM_TOEWIJZING] ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_LEVERANCIER FOREIGN KEY ([LEVERANCIER_LEVERANCIER_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- LEVERANCIER (0..* to 1, Connector_ID: 1033)

ALTER TABLE [VERZOEK_OM_TOEWIJZING] ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_BETREFT_2 FOREIGN KEY ([BETREFT_VOORZIENING_ID]) REFERENCES [VOORZIENING] ([VOORZIENING_ID]);
-- BETREFT (0..* to 1, Connector_ID: 1034)

ALTER TABLE [TOEWIJZING] ADD CONSTRAINT FK_TOEWIJZING_LEVERT_VOORZIENING FOREIGN KEY ([LEVERT_VOORZIENING_LEVERANCIER_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- LEVERT_VOORZIENING (0..* to 0..1, Connector_ID: 1038)

ALTER TABLE [VOORZIENING] ADD CONSTRAINT FK_VOORZIENING_HEEFT FOREIGN KEY ([HEEFT_TARIEF_ID]) REFERENCES [TARIEF] ([TARIEF_ID]);
-- HEEFT (1 to 1..*, Connector_ID: 1040)

ALTER TABLE [CONTRACT] ADD CONSTRAINT FK_CONTRACT_BEVAT FOREIGN KEY ([BEVAT_TARIEF_ID]) REFERENCES [TARIEF] ([TARIEF_ID]);
-- BEVAT (1 to 0..*, Connector_ID: 1041)

ALTER TABLE [TARIEF] ADD CONSTRAINT FK_TARIEF_HEEFT FOREIGN KEY ([HEEFT_LEVERANCIER_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- HEEFT (0..* to 1, Connector_ID: 1042)

ALTER TABLE [LEVERANCIER] ADD CONSTRAINT FK_LEVERANCIER_LEVERDE_PRESTATIE FOREIGN KEY ([LEVERDE_PRESTATIE_LEVERING_ID]) REFERENCES [LEVERING] ([LEVERING_ID]);
-- LEVERDE_PRESTATIE (1 to 0..*, Connector_ID: 1046)

ALTER TABLE [LEVERING] ADD CONSTRAINT FK_LEVERING_VOORZIENING FOREIGN KEY ([VOORZIENING_VOORZIENING_ID]) REFERENCES [VOORZIENING] ([VOORZIENING_ID]);
-- VOORZIENING (0..* to 1, Connector_ID: 1047)

ALTER TABLE [LEVERING] ADD CONSTRAINT FK_LEVERING_GELEVERDE_ZORG FOREIGN KEY ([GELEVERDE_ZORG_TOEWIJZING_ID]) REFERENCES [TOEWIJZING] ([TOEWIJZING_ID]);
-- GELEVERDE_ZORG (0..* to 0..1, Connector_ID: 1048)

ALTER TABLE [LEVERING] ADD CONSTRAINT FK_LEVERING_PRESTATIE_VOOR FOREIGN KEY ([PRESTATIE_VOOR_CLIENT_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- PRESTATIE_VOOR (0..* to 0..1, Connector_ID: 1049)

ALTER TABLE [TOEWIJZING] ADD CONSTRAINT FK_TOEWIJZING_IS_OP_BASIS_VAN FOREIGN KEY ([IS_OP_BASIS_VAN_DECLARATIEREGEL_ID]) REFERENCES [DECLARATIEREGEL] ([DECLARATIEREGEL_ID]);
-- IS_OP_BASIS_VAN (1 to 0..*, Connector_ID: 1052)

ALTER TABLE [DECLARATIEREGEL] ADD CONSTRAINT FK_DECLARATIEREGEL_BETREFT FOREIGN KEY ([BETREFT_CLIENT_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- BETREFT (0..* to 1, Connector_ID: 1053)

ALTER TABLE [DECLARATIEREGEL] ADD CONSTRAINT FK_DECLARATIEREGEL_VALT_BINNEN FOREIGN KEY ([VALT_BINNEN_DECLARATIE_ID]) REFERENCES [DECLARATIE] ([DECLARATIE_ID]);
-- VALT_BINNEN (0..* to 1, Connector_ID: 1054)

ALTER TABLE [DECLARATIE] ADD CONSTRAINT FK_DECLARATIE_INGEDIEND_DOOR FOREIGN KEY ([INGEDIEND_DOOR_LEVERANCIER_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- INGEDIEND_DOOR (0..* to 1, Connector_ID: 1055)

ALTER TABLE [PGB_TOEKENNING] ADD CONSTRAINT FK_PGB_TOEKENNING_BETREFT FOREIGN KEY ([BETREFT_BUDGETUITPUTTING_ID]) REFERENCES [BUDGETUITPUTTING] ([BUDGETUITPUTTING_ID]);
-- BETREFT (1 to 0..*, Connector_ID: 1056)

ALTER TABLE [PGB_TOEKENNING] ADD CONSTRAINT FK_PGB_TOEKENNING_BETREFT_2 FOREIGN KEY ([BETREFT_BESCHIKTE_VOORZIENING_ID]) REFERENCES [BESCHIKTE_VOORZIENING] ([BESCHIKTE_VOORZIENING_ID]);
-- BETREFT (0..* to 1, Connector_ID: 1058)

ALTER TABLE [BESCHIKTE_VOORZIENING] ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_HEEFT FOREIGN KEY ([HEEFT_LEVERINGSVORM_293_ID]) REFERENCES [LEVERINGSVORM_293] ([LEVERINGSVORM_293_ID]);
-- HEEFT (0..* to 1, Connector_ID: 1059)

ALTER TABLE [BESCHIKTE_VOORZIENING] ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_TOEGEWEZEN_PRODUCT FOREIGN KEY ([TOEGEWEZEN_PRODUCT_TOEWIJZING_ID]) REFERENCES [TOEWIJZING] ([TOEWIJZING_ID]);
-- TOEGEWEZEN_PRODUCT (1..* to 0..1, Connector_ID: 1060)

ALTER TABLE [BESCHIKTE_VOORZIENING] ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_IS_VOORZIENING FOREIGN KEY ([IS_VOORZIENING_VOORZIENING_ID]) REFERENCES [VOORZIENING] ([VOORZIENING_ID]);
-- IS_VOORZIENING (0..* to 1, Connector_ID: 1061)

ALTER TABLE [VERZOEK_OM_TOEWIJZING] ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_LEIDT_TOT FOREIGN KEY ([LEIDT_TOT_BESCHIKKING_ID]) REFERENCES [BESCHIKKING] ([BESCHIKKING_ID]);
-- LEIDT_TOT (0..* to 0..1, Connector_ID: 1062)

ALTER TABLE [DECLARATIEREGEL] ADD CONSTRAINT FK_DECLARATIEREGEL_IS_VOOR FOREIGN KEY ([IS_VOOR_BESCHIKKING_ID]) REFERENCES [BESCHIKKING] ([BESCHIKKING_ID]);
-- IS_VOOR (0..* to 1, Connector_ID: 1063)

ALTER TABLE [CLIENTBEGELEIDER] ADD CONSTRAINT FK_CLIENTBEGELEIDER_GEEFT_AF FOREIGN KEY ([GEEFT_AF_BESCHIKKING_ID]) REFERENCES [BESCHIKKING] ([BESCHIKKING_ID]);
-- GEEFT_AF (1 to 0..*, Connector_ID: 1064)

ALTER TABLE [LEVERING] ADD CONSTRAINT FK_LEVERING_GELEVERDE_PRESTATIE FOREIGN KEY ([GELEVERDE_PRESTATIE_BESCHIKKING_ID]) REFERENCES [BESCHIKKING] ([BESCHIKKING_ID]);
-- GELEVERDE_PRESTATIE (0..* to 0..1, Connector_ID: 1065)

ALTER TABLE [MELDING_EIGEN_BIJDRAGE] ADD CONSTRAINT FK_MELDING_EIGEN_BIJDRAGE_BETREFT FOREIGN KEY ([BETREFT_BESCHIKKING_ID]) REFERENCES [BESCHIKKING] ([BESCHIKKING_ID]);
-- BETREFT (0..* to 1, Connector_ID: 1066)

ALTER TABLE [BESCHIKKING] ADD CONSTRAINT FK_BESCHIKKING_TOEWIJZING FOREIGN KEY ([TOEWIJZING_TOEWIJZING_ID]) REFERENCES [TOEWIJZING] ([TOEWIJZING_ID]);
-- TOEWIJZING (1 to 0..*, Connector_ID: 1067)

ALTER TABLE [BESCHIKKING] ADD CONSTRAINT FK_BESCHIKKING_HEEFT_VOORZIENINGEN FOREIGN KEY ([HEEFT_VOORZIENINGEN_BESCHIKTE_VOORZIENING_ID]) REFERENCES [BESCHIKTE_VOORZIENING] ([BESCHIKTE_VOORZIENING_ID]);
-- HEEFT_VOORZIENINGEN (1 to 1..*, Connector_ID: 1068)

ALTER TABLE [BESCHIKKING] ADD CONSTRAINT FK_BESCHIKKING_CLIENT FOREIGN KEY ([CLIENT_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- unnamed (0..* to 1, Connector_ID: 1069)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY ([OUDER_1_INGESCHREVENPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- OUDER_1 (1 to 1, Connector_ID: 1871)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY ([OUDER_2_INGESCHREVENPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- OUDER_2 (1 to 1, Connector_ID: 1873)

ALTER TABLE [BESCHIKKING] ADD CONSTRAINT FK_BESCHIKKING_WET_ENUM_ID FOREIGN KEY ([WET_ENUM_ID]) REFERENCES [WET_ENUM] ([WET_ENUM_ID]);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [BESCHIKTE_VOORZIENING] ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_FREQUENTIE_ENUM_ID FOREIGN KEY ([FREQUENTIE_ENUM_ID]) REFERENCES [FREQUENTIE_ENUM] ([FREQUENTIE_ENUM_ID]);
-- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [BESCHIKTE_VOORZIENING] ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_LEVERINGSVORM_287_ENUM_ID FOREIGN KEY ([LEVERINGSVORM_287_ENUM_ID]) REFERENCES [LEVERINGSVORM_309_ENUM] ([LEVERINGSVORM_309_ENUM_ID]);
-- LEVERINGSVORM_287_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [BESCHIKTE_VOORZIENING] ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_WET_ENUM_ID FOREIGN KEY ([WET_ENUM_ID]) REFERENCES [WET_ENUM] ([WET_ENUM_ID]);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [BESCHIKTE_VOORZIENING] ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_EENHEID_ENUM_ID FOREIGN KEY ([EENHEID_ENUM_ID]) REFERENCES [EENHEID_ENUM] ([EENHEID_ENUM_ID]);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [LEVERING] ADD CONSTRAINT FK_LEVERING_FREQUENTIE_ENUM_ID FOREIGN KEY ([FREQUENTIE_ENUM_ID]) REFERENCES [FREQUENTIE_ENUM] ([FREQUENTIE_ENUM_ID]);
-- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [LEVERING] ADD CONSTRAINT FK_LEVERING_EENHEID_ENUM_ID FOREIGN KEY ([EENHEID_ENUM_ID]) REFERENCES [EENHEID_ENUM] ([EENHEID_ENUM_ID]);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [LEVERINGSVORM_293] ADD CONSTRAINT FK_LEVERINGSVORM_293_WET_ENUM_ID FOREIGN KEY ([WET_ENUM_ID]) REFERENCES [WET_ENUM] ([WET_ENUM_ID]);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [TARIEF] ADD CONSTRAINT FK_TARIEF_WET_ENUM_ID FOREIGN KEY ([WET_ENUM_ID]) REFERENCES [WET_ENUM] ([WET_ENUM_ID]);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [TARIEF] ADD CONSTRAINT FK_TARIEF_EENHEID_ENUM_ID FOREIGN KEY ([EENHEID_ENUM_ID]) REFERENCES [EENHEID_ENUM] ([EENHEID_ENUM_ID]);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [TOEWIJZING] ADD CONSTRAINT FK_TOEWIJZING_FREQUENTIE_ENUM_ID FOREIGN KEY ([FREQUENTIE_ENUM_ID]) REFERENCES [FREQUENTIE_ENUM] ([FREQUENTIE_ENUM_ID]);
-- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [TOEWIJZING] ADD CONSTRAINT FK_TOEWIJZING_WET_ENUM_ID FOREIGN KEY ([WET_ENUM_ID]) REFERENCES [WET_ENUM] ([WET_ENUM_ID]);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [TOEWIJZING] ADD CONSTRAINT FK_TOEWIJZING_EENHEID_ENUM_ID FOREIGN KEY ([EENHEID_ENUM_ID]) REFERENCES [EENHEID_ENUM] ([EENHEID_ENUM_ID]);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERZOEK_OM_TOEWIJZING] ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_RAAMCONTRACT_ENUM_ID FOREIGN KEY ([RAAMCONTRACT_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- RAAMCONTRACT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERZOEK_OM_TOEWIJZING] ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_FREQUENTIE_ENUM_ID FOREIGN KEY ([FREQUENTIE_ENUM_ID]) REFERENCES [FREQUENTIE_ENUM] ([FREQUENTIE_ENUM_ID]);
-- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERZOEK_OM_TOEWIJZING] ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_SOORTVERWIJZER_ENUM_ID FOREIGN KEY ([SOORTVERWIJZER_ENUM_ID]) REFERENCES [SOORT_VERWIJZER_ENUM] ([SOORT_VERWIJZER_ENUM_ID]);
-- SOORTVERWIJZER_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERZOEK_OM_TOEWIJZING] ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_EENHEID_ENUM_ID FOREIGN KEY ([EENHEID_ENUM_ID]) REFERENCES [EENHEID_ENUM] ([EENHEID_ENUM_ID]);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VOORZIENING] ADD CONSTRAINT FK_VOORZIENING_WET_ENUM_ID FOREIGN KEY ([WET_ENUM_ID]) REFERENCES [WET_ENUM] ([WET_ENUM_ID]);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VOORZIENINGSOORT] ADD CONSTRAINT FK_VOORZIENINGSOORT_WET_ENUM_ID FOREIGN KEY ([WET_ENUM_ID]) REFERENCES [WET_ENUM] ([WET_ENUM_ID]);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [CLIENT] ADD CONSTRAINT FK_CLIENT_GEZAGSDRAGERGEKEND_ENUM_ID FOREIGN KEY ([GEZAGSDRAGERGEKEND_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GEZAGSDRAGERGEKEND_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [MEDEWERKER] ADD CONSTRAINT FK_MEDEWERKER_EXTERN_ENUM_ID FOREIGN KEY ([EXTERN_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- EXTERN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NATUURLIJKPERSOON] ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID FOREIGN KEY ([INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NATUURLIJKPERSOON] ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEOVERLEDEN_ENUM_ID FOREIGN KEY ([INDICATIEOVERLEDEN_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIEOVERLEDEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_SIGNALERINGREISDOCUMENT_ENUM_ID FOREIGN KEY ([SIGNALERINGREISDOCUMENT_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- SIGNALERINGREISDOCUMENT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_INGEZETENE_ENUM_ID FOREIGN KEY ([INGEZETENE_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INGEZETENE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_INDICATIEGEHEIM_ENUM_ID FOREIGN KEY ([INDICATIEGEHEIM_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIEGEHEIM_ENUM_ID (1 to 1, Connector_ID: enum_ref)

