CREATE TABLE UITVOERENDE_INSTANTIE (
    UITVOERENDE_INSTANTIE_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(200)
);

CREATE TABLE ZAAKTYPE (
    ZAAKTYPE_ID NUMBER PRIMARY KEY,
    ARCHIEFCODE VARCHAR2(20),
    DATUMBEGINGELDIGHEIDZAAKTYPE DATE,
    DATUMEINDEGELDIGHEIDZAAKTYPE DATE,
    DOORLOOPTIJDBEHANDELING TIMESTAMP,
    INDICATIEPUBLICATIE VARCHAR2(255),
    PUBLICATIETEKST VARCHAR2(255),
    SERVICENORMBEHANDELING VARCHAR2(255),
    TREFWOORD VARCHAR2(255),
    VERTROUWELIJKAANDUIDING VARCHAR2(20),
    ZAAKCATEGORIE VARCHAR2(255),
    ZAAKTYPEOMSCHRIJVING VARCHAR2(80),
    ZAAKTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80)
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    EMAILADRES VARCHAR2(80),
    FAXNUMMER VARCHAR2(20),
    IDENTIFICATIE VARCHAR2(255),
    KVKNUMMER VARCHAR2(20),
    NAAM VARCHAR2(200),
    RECHTSVORM VARCHAR2(100),
    REKENINGNUMMER VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE LOCATIE (
    LOCATIE_ID NUMBER PRIMARY KEY,
    HOOGTE NUMBER,
    NAAM VARCHAR2(200),
    NEN3610ID VARCHAR2(80)
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR2(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR2(200),
    DOCUMENTIDENTIFICATIE VARCHAR2(255),
    DOCUMENTTITEL VARCHAR2(200),
    VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE VRAAG_CLASSIFICATIE_ENUM (
    VRAAG_CLASSIFICATIE_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO VRAAG_CLASSIFICATIE_ENUM (VRAAG_CLASSIFICATIE_ENUM_ID, VALUE) VALUES
    (1, 'AANVRAGER'),
    (2, 'ACTIVITEIT'),
    (3, 'GEVRAAGDE_BIJLAGE'),
    (4, 'PROJECT'),
    (5, 'VERZOEK');

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    ACHTERNAAM VARCHAR2(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR2(255),
    EXTERN NUMBER(1),
    FUNCTIE VARCHAR2(50),
    GESLACHTSAANDUIDING VARCHAR2(255),
    IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID NUMBER,
    MEDEWERKERIDENTIFICATIE VARCHAR2(255),
    MEDEWERKERTOELICHTING VARCHAR2(255),
    ROEPNAAM VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    VOORLETTERS VARCHAR2(20),
    VOORVOEGSELACHTERNAAM VARCHAR2(255),
    WERKT_BIJ_UITVOERENDE_INSTANTIE_ID NUMBER
);

CREATE TABLE BEVOEGD_GEZAG (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY
);

CREATE TABLE PROJECTLOCATIE (
    PROJECTLOCATIE_ID NUMBER PRIMARY KEY,
    ADRES NUMBER,
    BETREFT_LOCATIE_ID NUMBER,
    KADASTRAALPERCEEL VARCHAR2(80),
    KADASTRALEGEMEENTE VARCHAR2(80),
    KADASTRALESECTIE VARCHAR2(80)
);

CREATE TABLE SPECIFICATIE (
    SPECIFICATIE_ID NUMBER PRIMARY KEY,
    ANTWOORD VARCHAR2(200),
    GROEPERING VARCHAR2(200),
    PUBLICEERBAAR NUMBER(1),
    VRAAGCLASSIFICATIE_ENUM_ID NUMBER,
    VRAAGID VARCHAR2(80),
    VRAAGREFERENTIE VARCHAR2(200),
    VRAAGTEKST CLOB
);

CREATE TABLE PROJECT (
    PROJECT_ID NUMBER PRIMARY KEY,
    HEEFT_PROJECTLOCATIE_ID NUMBER,
    NAAM VARCHAR2(200),
    OMSCHRIJVING CLOB
);

CREATE TABLE ZAAK (
    ZAAK_ID NUMBER PRIMARY KEY,
    ARCHIEFNOMINATIE VARCHAR2(255),
    BETREFT_PROJECT_ID NUMBER,
    DATUMEINDE DATE,
    DATUMEINDEGEPLAND DATE,
    DATUMEINDEUITERLIJKEAFDOENING DATE,
    DATUMLAATSTEBETALING DATE,
    DATUMPUBLICATIE DATE,
    DATUMREGISTRATIE DATE,
    DATUMSTART DATE,
    DATUMVERNIETIGINGDOSSIER DATE,
    DUURVERLENGING VARCHAR2(255),
    HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID NUMBER,
    INDICATIEBETALING VARCHAR2(255),
    INDICATIEDEELZAKEN NUMBER(1),
    INDICATIEOPSCHORTING VARCHAR2(255),
    IS_DEELZAAK_VAN_ZAAK_ID NUMBER,
    IS_VAN_ZAAKTYPE_ID NUMBER,
    LEGES VARCHAR2(100),
    OMSCHRIJVING VARCHAR2(80),
    OMSCHRIJVINGRESULTAAT VARCHAR2(80),
    REDENOPSCHORTING VARCHAR2(200),
    REDENVERLENGING VARCHAR2(200),
    TOELICHTING VARCHAR2(255),
    TOELICHTINGRESULTAAT VARCHAR2(255),
    VERTROUWELIJKHEID VARCHAR2(255),
    ZAAKIDENTIFICATIE VARCHAR2(255),
    ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE KP_ZK_MDWRKR (
    KP_ZK_MDWRKR_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    MEDEWERKER_ID NUMBER
);

CREATE TABLE VERZOEK (
    VERZOEK_ID NUMBER PRIMARY KEY,
    AKKOORDVERKLARING NUMBER(1),
    AMBTSHALVE NUMBER(1),
    BEHANDELAAR_UITVOERENDE_INSTANTIE_ID NUMBER,
    BETREFT_EERDER_VERZOEK_VERZOEK_ID NUMBER,
    BETREFT_PROJECT_ID NUMBER,
    BEVAT_SPECIFICATIE_ID NUMBER,
    DATUMINDIENING DATE,
    DOEL VARCHAR2(255),
    HEEFT_BIJLAGEN_DOCUMENT_ID NUMBER,
    LEIDT_TOT_ZAAK_ID NUMBER,
    NAAM VARCHAR2(200),
    REFERENTIEAANVRAGER VARCHAR2(200),
    TOELICHTINGLATERAANTELEVERENINFORMATIE CLOB,
    TOELICHTINGNIETAANTELEVERENINFORMATIE CLOB,
    TOELICHTINGVERZOEK CLOB,
    TYPE VARCHAR2(255),
    VERANTWOORDELIJKE_BEVOEGD_GEZAG_ID NUMBER,
    VERZOEKNUMMER VARCHAR2(80),
    VOLGNUMMER VARCHAR2(80)
);

CREATE TABLE KP_ZK_DCMNT (
    KP_ZK_DCMNT_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    DOCUMENT_ID NUMBER
);

CREATE TABLE INITIATIEFNEMER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    HEEFT_ALS_VERANTWOORDELIJKE_VERZOEK_ID NUMBER
);

CREATE TABLE KP_VRZK_PRJCTLCT (
    KP_VRZK_PRJCTLCT_ID NUMBER PRIMARY KEY,
    VERZOEK_ID NUMBER,
    PROJECTLOCATIE_ID NUMBER
);

CREATE TABLE KP_VRZK_LCT (
    KP_VRZK_LCT_ID NUMBER PRIMARY KEY,
    VERZOEK_ID NUMBER,
    LOCATIE_ID NUMBER
);

CREATE TABLE GEMACHTIGDE (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    DIENT_IN__VERZOEK_ID NUMBER,
    IS_GEMACHTIGD_DOOR_INITIATIEFNEMER_ID NUMBER
);

ALTER TABLE BEVOEGD_GEZAG ADD CONSTRAINT FK_BEVOEGD_GEZAG_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE GEMACHTIGDE ADD CONSTRAINT FK_GEMACHTIGDE_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE INITIATIEFNEMER ADD CONSTRAINT FK_INITIATIEFNEMER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_VRZK_PRJCTLCT ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 112)

ALTER TABLE KP_VRZK_PRJCTLCT ADD CONSTRAINT FK_KP_VRZK_PRJCTLCT_2 FOREIGN KEY (PROJECTLOCATIE_ID) REFERENCES PROJECTLOCATIE (PROJECTLOCATIE_ID);
-- PROJECTLOCATIE (many-to-many junction, Connector_ID: 112)

ALTER TABLE KP_VRZK_LCT ADD CONSTRAINT FK_KP_VRZK_LCT_1 FOREIGN KEY (VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- VERZOEK (many-to-many junction, Connector_ID: 692)

ALTER TABLE KP_VRZK_LCT ADD CONSTRAINT FK_KP_VRZK_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 692)

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_HEEFT_BIJLAGEN FOREIGN KEY (HEEFT_BIJLAGEN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- HEEFT_BIJLAGEN (None to None, Connector_ID: 113)

ALTER TABLE GEMACHTIGDE ADD CONSTRAINT FK_GEMACHTIGDE_IS_GEMACHTIGD_DOOR FOREIGN KEY (IS_GEMACHTIGD_DOOR_INITIATIEFNEMER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- IS_GEMACHTIGD_DOOR (0..1 to 1..*, Connector_ID: 114)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BETREFT_EERDER_VERZOEK FOREIGN KEY (BETREFT_EERDER_VERZOEK_VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- BETREFT_EERDER_VERZOEK (0..1 to 0..*, Connector_ID: 690)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_LEIDT_TOT FOREIGN KEY (LEIDT_TOT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 691)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BEHANDELAAR FOREIGN KEY (BEHANDELAAR_UITVOERENDE_INSTANTIE_ID) REFERENCES UITVOERENDE_INSTANTIE (UITVOERENDE_INSTANTIE_ID);
-- BEHANDELAAR (0..* to 0..1, Connector_ID: 695)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BEVAT FOREIGN KEY (BEVAT_SPECIFICATIE_ID) REFERENCES SPECIFICATIE (SPECIFICATIE_ID);
-- BEVAT (1 to 0..*, Connector_ID: 696)

ALTER TABLE PROJECTLOCATIE ADD CONSTRAINT FK_PROJECTLOCATIE_BETREFT FOREIGN KEY (BETREFT_LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 697)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_BETREFT FOREIGN KEY (BETREFT_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- BETREFT (1..* to 1.., Connector_ID: 701)

ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_HEEFT FOREIGN KEY (HEEFT_PROJECTLOCATIE_ID) REFERENCES PROJECTLOCATIE (PROJECTLOCATIE_ID);
-- HEEFT (1 to 0..*, Connector_ID: 704)

ALTER TABLE INITIATIEFNEMER ADD CONSTRAINT FK_INITIATIEFNEMER_HEEFT_ALS_VERANTWOORDELIJKE FOREIGN KEY (HEEFT_ALS_VERANTWOORDELIJKE_VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- HEEFT_ALS_VERANTWOORDELIJKE (1 to 1..*, Connector_ID: 705)

ALTER TABLE GEMACHTIGDE ADD CONSTRAINT FK_GEMACHTIGDE_DIENT_IN_ FOREIGN KEY (DIENT_IN__VERZOEK_ID) REFERENCES VERZOEK (VERZOEK_ID);
-- DIENT_IN_ (0..1 to 1..*, Connector_ID: 707)

ALTER TABLE VERZOEK ADD CONSTRAINT FK_VERZOEK_VERANTWOORDELIJKE FOREIGN KEY (VERANTWOORDELIJKE_BEVOEGD_GEZAG_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- VERANTWOORDELIJKE (0..* to 1, Connector_ID: 709)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_BETREFT FOREIGN KEY (BETREFT_PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 2106)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY (IS_VAN_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY (IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2170)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_WERKT_BIJ FOREIGN KEY (WERKT_BIJ_UITVOERENDE_INSTANTIE_ID) REFERENCES UITVOERENDE_INSTANTIE (UITVOERENDE_INSTANTIE_ID);
-- WERKT_BIJ (0..* to 1, Connector_ID: 2172)

ALTER TABLE SPECIFICATIE ADD CONSTRAINT FK_SPECIFICATIE_VRAAGCLASSIFICATIE_ENUM_ID FOREIGN KEY (VRAAGCLASSIFICATIE_ENUM_ID) REFERENCES VRAAG_CLASSIFICATIE_ENUM (VRAAG_CLASSIFICATIE_ENUM_ID);
-- VRAAGCLASSIFICATIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

