CREATE TABLE `REGELTEKST` (
    `REGELTEKST_ID` INT PRIMARY KEY,
    `IDENTIFICATIE` VARCHAR(200),
    `IS_GERELATEERD_REGELTEKST_ID` INT,
    `OMSCHRIJVING` TEXT,
    `TEKST` TEXT,
    `WERKINGSGEBIED_REGELTEKST_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `THEMA` (
    `THEMA_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(200),
    `OMSCHRIJVING` TEXT,
    `SUBTHEMA_THEMA_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `IDEALISATIE` (
    `IDEALISATIE_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(200),
    `OMSCHRIJVING` TEXT
) ENGINE=InnoDB;

CREATE TABLE `JURIDISCHE_REGEL` (
    `JURIDISCHE_REGEL_ID` INT PRIMARY KEY,
    `DATUMBEKEND` DATE,
    `DATUMEINDEGELDIGHEID` DATE,
    `DATUMINWERKING` DATE,
    `DATUMSTART` DATE,
    `IS_OPGENOMEN_IN_REGELTEKST_ID` INT,
    `OMSCHRIJVING` TEXT,
    `REGELTEKST` VARCHAR(200),
    `THEMA` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `KP_RGLTKST_THM` (
    `KP_RGLTKST_THM_ID` INT PRIMARY KEY,
    `REGELTEKST_ID` INT,
    `THEMA_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_RGLTKST_IDLST` (
    `KP_RGLTKST_IDLST_ID` INT PRIMARY KEY,
    `REGELTEKST_ID` INT,
    `IDEALISATIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_JRDSCH_RGL_THM` (
    `KP_JRDSCH_RGL_THM_ID` INT PRIMARY KEY,
    `JURIDISCHE_REGEL_ID` INT,
    `THEMA_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_JRDSCH_RGL_IDLST` (
    `KP_JRDSCH_RGL_IDLST_ID` INT PRIMARY KEY,
    `JURIDISCHE_REGEL_ID` INT,
    `IDEALISATIE_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `KP_JRDSCH_RGL_THM` ADD CONSTRAINT FK_KP_JRDSCH_RGL_THM_1 FOREIGN KEY (`JURIDISCHE_REGEL_ID`) REFERENCES `JURIDISCHE_REGEL` (`JURIDISCHE_REGEL_ID`);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 669)

ALTER TABLE `KP_JRDSCH_RGL_THM` ADD CONSTRAINT FK_KP_JRDSCH_RGL_THM_2 FOREIGN KEY (`THEMA_ID`) REFERENCES `THEMA` (`THEMA_ID`);
-- THEMA (many-to-many junction, Connector_ID: 669)

ALTER TABLE `KP_JRDSCH_RGL_IDLST` ADD CONSTRAINT FK_KP_JRDSCH_RGL_IDLST_1 FOREIGN KEY (`JURIDISCHE_REGEL_ID`) REFERENCES `JURIDISCHE_REGEL` (`JURIDISCHE_REGEL_ID`);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 671)

ALTER TABLE `KP_JRDSCH_RGL_IDLST` ADD CONSTRAINT FK_KP_JRDSCH_RGL_IDLST_2 FOREIGN KEY (`IDEALISATIE_ID`) REFERENCES `IDEALISATIE` (`IDEALISATIE_ID`);
-- IDEALISATIE (many-to-many junction, Connector_ID: 671)

ALTER TABLE `KP_RGLTKST_IDLST` ADD CONSTRAINT FK_KP_RGLTKST_IDLST_1 FOREIGN KEY (`REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- REGELTEKST (many-to-many junction, Connector_ID: 686)

ALTER TABLE `KP_RGLTKST_IDLST` ADD CONSTRAINT FK_KP_RGLTKST_IDLST_2 FOREIGN KEY (`IDEALISATIE_ID`) REFERENCES `IDEALISATIE` (`IDEALISATIE_ID`);
-- IDEALISATIE (many-to-many junction, Connector_ID: 686)

ALTER TABLE `KP_RGLTKST_THM` ADD CONSTRAINT FK_KP_RGLTKST_THM_1 FOREIGN KEY (`REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- REGELTEKST (many-to-many junction, Connector_ID: 688)

ALTER TABLE `KP_RGLTKST_THM` ADD CONSTRAINT FK_KP_RGLTKST_THM_2 FOREIGN KEY (`THEMA_ID`) REFERENCES `THEMA` (`THEMA_ID`);
-- THEMA (many-to-many junction, Connector_ID: 688)

ALTER TABLE `THEMA` ADD CONSTRAINT FK_THEMA_SUBTHEMA FOREIGN KEY (`SUBTHEMA_THEMA_ID`) REFERENCES `THEMA` (`THEMA_ID`);
-- SUBTHEMA (0..1 to 0..*, Connector_ID: 657)

ALTER TABLE `JURIDISCHE_REGEL` ADD CONSTRAINT FK_JURIDISCHE_REGEL_IS_OPGENOMEN_IN FOREIGN KEY (`IS_OPGENOMEN_IN_REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- IS_OPGENOMEN_IN (1..* to 1, Connector_ID: 683)

ALTER TABLE `REGELTEKST` ADD CONSTRAINT FK_REGELTEKST_IS_GERELATEERD FOREIGN KEY (`IS_GERELATEERD_REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- IS_GERELATEERD (0..1 to 0..*, Connector_ID: 685)

ALTER TABLE `REGELTEKST` ADD CONSTRAINT FK_REGELTEKST_WERKINGSGEBIED FOREIGN KEY (`WERKINGSGEBIED_REGELTEKST_ID`) REFERENCES `REGELTEKST` (`REGELTEKST_ID`);
-- WERKINGSGEBIED (0..1 to 0..*, Connector_ID: 687)

