CREATE TABLE GEBIEDSAANWIJZING (
    GEBIEDSAANWIJZING_ID INTEGER PRIMARY KEY,
    GROEP VARCHAR(200),
    NAAM VARCHAR(200),
    NEN3610ID VARCHAR(80)
);

CREATE TABLE ACTIVITEIT (
    ACTIVITEIT_ID INTEGER PRIMARY KEY,
    BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID INTEGER,
    GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID INTEGER,
    GROEP VARCHAR(200),
    NAAM VARCHAR(200),
    NEN3610ID VARCHAR(80)
);

CREATE TABLE NORMWAARDE (
    NORMWAARDE_ID INTEGER PRIMARY KEY,
    KWALITATIEVEWAARDE VARCHAR(80),
    KWANTITATIEVEWAARDEEENHEID VARCHAR(80),
    KWANTITATIEVEWAARDEOMVANG VARCHAR(255)
);

CREATE TABLE LOCATIE (
    LOCATIE_ID INTEGER PRIMARY KEY,
    HOOGTE INTEGER,
    NAAM VARCHAR(200),
    NEN3610ID VARCHAR(80)
);

CREATE TABLE REGELTEKST (
    REGELTEKST_ID INTEGER PRIMARY KEY,
    IDENTIFICATIE VARCHAR(200),
    IS_GERELATEERD_REGELTEKST_ID INTEGER,
    OMSCHRIJVING TEXT,
    TEKST TEXT,
    WERKINGSGEBIED_REGELTEKST_ID INTEGER
);

CREATE TABLE FUNCTIE (
    GEBIEDSAANWIJZING_ID INTEGER PRIMARY KEY,
    GROEP VARCHAR(200),
    NAAM VARCHAR(200)
);

CREATE TABLE BEPERKINGSGEBIED (
    GEBIEDSAANWIJZING_ID INTEGER PRIMARY KEY,
    GROEP VARCHAR(200),
    NAAM VARCHAR(200)
);

CREATE TABLE NORM (
    NORM_ID INTEGER PRIMARY KEY,
    BEVAT_NORMWAARDE_ID INTEGER,
    NEN3610ID VARCHAR(80)
);

CREATE TABLE KP_ACTVTT_LCT (
    KP_ACTVTT_LCT_ID INTEGER PRIMARY KEY,
    ACTIVITEIT_ID INTEGER,
    LOCATIE_ID INTEGER
);

CREATE TABLE KP_GBDSNWJZNG_LCT (
    KP_GBDSNWJZNG_LCT_ID INTEGER PRIMARY KEY,
    GEBIEDSAANWIJZING_ID INTEGER,
    LOCATIE_ID INTEGER
);

CREATE TABLE KP_NRMWRD_LCT (
    KP_NRMWRD_LCT_ID INTEGER PRIMARY KEY,
    NORMWAARDE_ID INTEGER,
    LOCATIE_ID INTEGER
);

CREATE TABLE JURIDISCHE_REGEL (
    JURIDISCHE_REGEL_ID INTEGER PRIMARY KEY,
    DATUMBEKEND DATE,
    DATUMEINDEGELDIGHEID DATE,
    DATUMINWERKING DATE,
    DATUMSTART DATE,
    IS_OPGENOMEN_IN_REGELTEKST_ID INTEGER,
    OMSCHRIJVING TEXT,
    REGELTEKST VARCHAR(200),
    THEMA VARCHAR(200)
);

CREATE TABLE KP_RGLTKST_LCT (
    KP_RGLTKST_LCT_ID INTEGER PRIMARY KEY,
    REGELTEKST_ID INTEGER,
    LOCATIE_ID INTEGER
);

CREATE TABLE OMGEVINGSNORM (
    NORM_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200),
    OMGEVINGSNORMGROEP VARCHAR(200)
);

CREATE TABLE OMGEVINGSWAARDE (
    NORM_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(200),
    OMGEVINGSWAARDEGROEP VARCHAR(200)
);

CREATE TABLE KP_JRDSCH_RGL_ACTVTT (
    KP_JRDSCH_RGL_ACTVTT_ID INTEGER PRIMARY KEY,
    JURIDISCHE_REGEL_ID INTEGER,
    ACTIVITEIT_ID INTEGER
);

CREATE TABLE OMGEVINGSWAARDEREGEL (
    JURIDISCHE_REGEL_ID INTEGER PRIMARY KEY,
    GROEP VARCHAR(200),
    NAAM VARCHAR(200)
);

CREATE TABLE INSTRUCTIEREGEL (
    JURIDISCHE_REGEL_ID INTEGER PRIMARY KEY,
    INSTRUCTIEREGELINSTRUMENT VARCHAR(200),
    INSTRUCTIEREGELTAAKUITOEFENING VARCHAR(200)
);

CREATE TABLE KP_JRDSCH_RGL_LCT (
    KP_JRDSCH_RGL_LCT_ID INTEGER PRIMARY KEY,
    JURIDISCHE_REGEL_ID INTEGER,
    LOCATIE_ID INTEGER
);

CREATE TABLE REGEL_VOOR_IEDEREEN (
    JURIDISCHE_REGEL_ID INTEGER PRIMARY KEY,
    ACTIVITEITREGELKWALIFICATIE VARCHAR(200)
);

CREATE TABLE KP_OMGVNGSWRDRGL_OMGVNGSNRM (
    KP_OMGVNGSWRDRGL_OMGVNGSNRM_ID INTEGER PRIMARY KEY,
    OMGEVINGSWAARDEREGEL_ID INTEGER,
    OMGEVINGSNORM_ID INTEGER
);

CREATE TABLE KP_OMGVNGSWRDRGL_OMGVNGSWRD (
    KP_OMGVNGSWRDRGL_OMGVNGSWRD_ID INTEGER PRIMARY KEY,
    OMGEVINGSWAARDEREGEL_ID INTEGER,
    OMGEVINGSWAARDE_ID INTEGER
);

CREATE TABLE KP_INSTRCTRGL_GBDSNWJZNG (
    KP_INSTRCTRGL_GBDSNWJZNG_ID INTEGER PRIMARY KEY,
    INSTRUCTIEREGEL_ID INTEGER,
    GEBIEDSAANWIJZING_ID INTEGER
);

CREATE TABLE KP_RGL_VR_IDRN_OMGVNGSNRM (
    KP_RGL_VR_IDRN_OMGVNGSNRM_ID INTEGER PRIMARY KEY,
    REGEL_VOOR_IEDEREEN_ID INTEGER,
    OMGEVINGSNORM_ID INTEGER
);

CREATE TABLE KP_RGL_VR_IDRN_GBDSNWJZNG (
    KP_RGL_VR_IDRN_GBDSNWJZNG_ID INTEGER PRIMARY KEY,
    REGEL_VOOR_IEDEREEN_ID INTEGER,
    GEBIEDSAANWIJZING_ID INTEGER
);

CREATE TABLE KP_RGL_VR_IDRN_ACTVTT (
    KP_RGL_VR_IDRN_ACTVTT_ID INTEGER PRIMARY KEY,
    REGEL_VOOR_IEDEREEN_ID INTEGER,
    ACTIVITEIT_ID INTEGER
);

ALTER TABLE BEPERKINGSGEBIED ADD CONSTRAINT FK_BEPERKINGSGEBIED_GEN_GEBIEDSAANWIJZING FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- Generalization to GEBIEDSAANWIJZING

ALTER TABLE FUNCTIE ADD CONSTRAINT FK_FUNCTIE_GEN_GEBIEDSAANWIJZING FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- Generalization to GEBIEDSAANWIJZING

ALTER TABLE INSTRUCTIEREGEL ADD CONSTRAINT FK_INSTRUCTIEREGEL_GEN_JURIDISCHE_REGEL FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- Generalization to JURIDISCHE_REGEL

ALTER TABLE OMGEVINGSNORM ADD CONSTRAINT FK_OMGEVINGSNORM_GEN_NORM FOREIGN KEY (NORM_ID) REFERENCES NORM (NORM_ID);
-- Generalization to NORM

ALTER TABLE OMGEVINGSWAARDE ADD CONSTRAINT FK_OMGEVINGSWAARDE_GEN_NORM FOREIGN KEY (NORM_ID) REFERENCES NORM (NORM_ID);
-- Generalization to NORM

ALTER TABLE OMGEVINGSWAARDEREGEL ADD CONSTRAINT FK_OMGEVINGSWAARDEREGEL_GEN_JURIDISCHE_REGEL FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- Generalization to JURIDISCHE_REGEL

ALTER TABLE REGEL_VOOR_IEDEREEN ADD CONSTRAINT FK_REGEL_VOOR_IEDEREEN_GEN_JURIDISCHE_REGEL FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- Generalization to JURIDISCHE_REGEL

ALTER TABLE KP_OMGVNGSWRDRGL_OMGVNGSWRD ADD CONSTRAINT FK_KP_OMGVNGSWRDRGL_OMGVNGSWRD_1 FOREIGN KEY (OMGEVINGSWAARDEREGEL_ID) REFERENCES OMGEVINGSWAARDEREGEL (JURIDISCHE_REGEL_ID);
-- OMGEVINGSWAARDEREGEL (many-to-many junction, Connector_ID: 660)

ALTER TABLE KP_OMGVNGSWRDRGL_OMGVNGSWRD ADD CONSTRAINT FK_KP_OMGVNGSWRDRGL_OMGVNGSWRD_2 FOREIGN KEY (OMGEVINGSWAARDE_ID) REFERENCES OMGEVINGSWAARDE (NORM_ID);
-- OMGEVINGSWAARDE (many-to-many junction, Connector_ID: 660)

ALTER TABLE KP_OMGVNGSWRDRGL_OMGVNGSNRM ADD CONSTRAINT FK_KP_OMGVNGSWRDRGL_OMGVNGSNRM_1 FOREIGN KEY (OMGEVINGSWAARDEREGEL_ID) REFERENCES OMGEVINGSWAARDEREGEL (JURIDISCHE_REGEL_ID);
-- OMGEVINGSWAARDEREGEL (many-to-many junction, Connector_ID: 662)

ALTER TABLE KP_OMGVNGSWRDRGL_OMGVNGSNRM ADD CONSTRAINT FK_KP_OMGVNGSWRDRGL_OMGVNGSNRM_2 FOREIGN KEY (OMGEVINGSNORM_ID) REFERENCES OMGEVINGSNORM (NORM_ID);
-- OMGEVINGSNORM (many-to-many junction, Connector_ID: 662)

ALTER TABLE KP_RGL_VR_IDRN_OMGVNGSNRM ADD CONSTRAINT FK_KP_RGL_VR_IDRN_OMGVNGSNRM_1 FOREIGN KEY (REGEL_VOOR_IEDEREEN_ID) REFERENCES REGEL_VOOR_IEDEREEN (JURIDISCHE_REGEL_ID);
-- REGEL_VOOR_IEDEREEN (many-to-many junction, Connector_ID: 663)

ALTER TABLE KP_RGL_VR_IDRN_OMGVNGSNRM ADD CONSTRAINT FK_KP_RGL_VR_IDRN_OMGVNGSNRM_2 FOREIGN KEY (OMGEVINGSNORM_ID) REFERENCES OMGEVINGSNORM (NORM_ID);
-- OMGEVINGSNORM (many-to-many junction, Connector_ID: 663)

ALTER TABLE KP_NRMWRD_LCT ADD CONSTRAINT FK_KP_NRMWRD_LCT_1 FOREIGN KEY (NORMWAARDE_ID) REFERENCES NORMWAARDE (NORMWAARDE_ID);
-- NORMWAARDE (many-to-many junction, Connector_ID: 665)

ALTER TABLE KP_NRMWRD_LCT ADD CONSTRAINT FK_KP_NRMWRD_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 665)

ALTER TABLE KP_JRDSCH_RGL_LCT ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_JRDSCH_RGL_LCT ADD CONSTRAINT FK_KP_JRDSCH_RGL_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_RGL_VR_IDRN_GBDSNWJZNG ADD CONSTRAINT FK_KP_RGL_VR_IDRN_GBDSNWJZNG_1 FOREIGN KEY (REGEL_VOOR_IEDEREEN_ID) REFERENCES REGEL_VOOR_IEDEREEN (JURIDISCHE_REGEL_ID);
-- REGEL_VOOR_IEDEREEN (many-to-many junction, Connector_ID: 672)

ALTER TABLE KP_RGL_VR_IDRN_GBDSNWJZNG ADD CONSTRAINT FK_KP_RGL_VR_IDRN_GBDSNWJZNG_2 FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- GEBIEDSAANWIJZING (many-to-many junction, Connector_ID: 672)

ALTER TABLE KP_INSTRCTRGL_GBDSNWJZNG ADD CONSTRAINT FK_KP_INSTRCTRGL_GBDSNWJZNG_1 FOREIGN KEY (INSTRUCTIEREGEL_ID) REFERENCES INSTRUCTIEREGEL (JURIDISCHE_REGEL_ID);
-- INSTRUCTIEREGEL (many-to-many junction, Connector_ID: 673)

ALTER TABLE KP_INSTRCTRGL_GBDSNWJZNG ADD CONSTRAINT FK_KP_INSTRCTRGL_GBDSNWJZNG_2 FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- GEBIEDSAANWIJZING (many-to-many junction, Connector_ID: 673)

ALTER TABLE KP_GBDSNWJZNG_LCT ADD CONSTRAINT FK_KP_GBDSNWJZNG_LCT_1 FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- GEBIEDSAANWIJZING (many-to-many junction, Connector_ID: 674)

ALTER TABLE KP_GBDSNWJZNG_LCT ADD CONSTRAINT FK_KP_GBDSNWJZNG_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 674)

ALTER TABLE KP_JRDSCH_RGL_ACTVTT ADD CONSTRAINT FK_KP_JRDSCH_RGL_ACTVTT_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 677)

ALTER TABLE KP_JRDSCH_RGL_ACTVTT ADD CONSTRAINT FK_KP_JRDSCH_RGL_ACTVTT_2 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 677)

ALTER TABLE KP_RGL_VR_IDRN_ACTVTT ADD CONSTRAINT FK_KP_RGL_VR_IDRN_ACTVTT_1 FOREIGN KEY (REGEL_VOOR_IEDEREEN_ID) REFERENCES REGEL_VOOR_IEDEREEN (JURIDISCHE_REGEL_ID);
-- REGEL_VOOR_IEDEREEN (many-to-many junction, Connector_ID: 678)

ALTER TABLE KP_RGL_VR_IDRN_ACTVTT ADD CONSTRAINT FK_KP_RGL_VR_IDRN_ACTVTT_2 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 678)

ALTER TABLE KP_ACTVTT_LCT ADD CONSTRAINT FK_KP_ACTVTT_LCT_1 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 680)

ALTER TABLE KP_ACTVTT_LCT ADD CONSTRAINT FK_KP_ACTVTT_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 680)

ALTER TABLE KP_RGLTKST_LCT ADD CONSTRAINT FK_KP_RGLTKST_LCT_1 FOREIGN KEY (REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- REGELTEKST (many-to-many junction, Connector_ID: 684)

ALTER TABLE KP_RGLTKST_LCT ADD CONSTRAINT FK_KP_RGLTKST_LCT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 684)

ALTER TABLE NORM ADD CONSTRAINT FK_NORM_BEVAT FOREIGN KEY (BEVAT_NORMWAARDE_ID) REFERENCES NORMWAARDE (NORMWAARDE_ID);
-- BEVAT (1 to 1..*, Connector_ID: 666)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_BOVENLIGGENDE_ACTIVITEIT FOREIGN KEY (BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BOVENLIGGENDE_ACTIVITEIT (1 to 0..1, Connector_ID: 681)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_GERELATEERDE_ACTIVITEIT FOREIGN KEY (GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- GERELATEERDE_ACTIVITEIT (1 to 0..1, Connector_ID: 682)

ALTER TABLE JURIDISCHE_REGEL ADD CONSTRAINT FK_JURIDISCHE_REGEL_IS_OPGENOMEN_IN FOREIGN KEY (IS_OPGENOMEN_IN_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- IS_OPGENOMEN_IN (1..* to 1, Connector_ID: 683)

ALTER TABLE REGELTEKST ADD CONSTRAINT FK_REGELTEKST_IS_GERELATEERD FOREIGN KEY (IS_GERELATEERD_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- IS_GERELATEERD (0..1 to 0..*, Connector_ID: 685)

ALTER TABLE REGELTEKST ADD CONSTRAINT FK_REGELTEKST_WERKINGSGEBIED FOREIGN KEY (WERKINGSGEBIED_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- WERKINGSGEBIED (0..1 to 0..*, Connector_ID: 687)

