CREATE TABLE SOCIAALTEAMDOSSIERSOORT (
    SOCIAALTEAMDOSSIERSOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE SCORESOORT (
    SCORESOORT_ID INTEGER PRIMARY KEY,
    NIVEAU VARCHAR(255)
);

CREATE TABLE ZELFREDZAAMHEIDMATRIX (
    ZELFREDZAAMHEIDMATRIX_ID INTEGER PRIMARY KEY,
    DATUMEINDEGELDIGHEID DATE,
    DATUMSTARTGELDIGHEID DATE,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE CLIENTBEGELEIDER (
    CLIENTBEGELEIDER_ID INTEGER PRIMARY KEY,
    BEGELEIDERSCODE VARCHAR(20)
);

CREATE TABLE LEEFGEBIED (
    LEEFGEBIED_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80)
);

CREATE TABLE RELATIE (
    RELATIE_ID INTEGER PRIMARY KEY,
    RELATIESOORT INTEGER
);

CREATE TABLE CASEAANMELDING (
    CASEAANMELDING_ID INTEGER PRIMARY KEY,
    DATUM DATE
);

CREATE TABLE BIJZONDERHEIDSOORT (
    BIJZONDERHEIDSOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE CLIENT (
    CLIENT_ID INTEGER PRIMARY KEY,
    CODE VARCHAR(80),
    GEZAGSDRAGERGEKEND BOOLEAN,
    JURIDISCHESTATUS VARCHAR(80),
    WETTELIJKEVERTEGENWOORDIGING VARCHAR(80)
);

CREATE TABLE DOELSTELLINGSOORT (
    DOELSTELLINGSOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE BEHANDELSOORT (
    BEHANDELSOORT_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    OMSCHRIJVING TEXT
);

CREATE TABLE KP_ZLFRDZMHDMTRX_SCRSRT (
    KP_ZLFRDZMHDMTRX_SCRSRT_ID INTEGER PRIMARY KEY,
    ZELFREDZAAMHEIDMATRIX_ID INTEGER,
    SCORESOORT_ID INTEGER
);

CREATE TABLE KP_ZLFRDZMHDMTRX_LFGBD (
    KP_ZLFRDZMHDMTRX_LFGBD_ID INTEGER PRIMARY KEY,
    ZELFREDZAAMHEIDMATRIX_ID INTEGER,
    LEEFGEBIED_ID INTEGER
);

CREATE TABLE KP_CLNTBGLDR_CLNT (
    KP_CLNTBGLDR_CLNT_ID INTEGER PRIMARY KEY,
    CLIENTBEGELEIDER_ID INTEGER,
    CLIENT_ID INTEGER
);

CREATE TABLE SOCIAALTEAMDOSSIER (
    SOCIAALTEAMDOSSIER_ID INTEGER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DATUMVASTSTELLING DATE,
    HEEFT_AANMELDING_CASEAANMELDING_ID INTEGER,
    HEEFT_CLIENTBEGELEIDER_ID INTEGER,
    HEEFT_CLIENT_ID INTEGER,
    HEEFT_SOORT_SOCIAALTEAMDOSSIERSOORT_ID INTEGER,
    OMSCHRIJVING TEXT,
    STATUS VARCHAR(20)
);

CREATE TABLE KP_CLNT_RLT (
    KP_CLNT_RLT_ID INTEGER PRIMARY KEY,
    CLIENT_ID INTEGER,
    RELATIE_ID INTEGER
);

CREATE TABLE SCORE (
    SCORE_ID INTEGER PRIMARY KEY,
    DATUM DATE,
    HEEFT_CLIENT_ID INTEGER,
    HOOGTE_SCORE_SCORESOORT_ID INTEGER,
    SCORE_BIJ_LEEGGEBIED_LEEFGEBIED_ID INTEGER
);

CREATE TABLE BIJZONDERHEID (
    BIJZONDERHEID_ID INTEGER PRIMARY KEY,
    HEEFT_BIJZONDERHEID_SOCIAALTEAMDOSSIER_ID INTEGER,
    IS_VAN_SOORT_BIJZONDERHEIDSOORT_ID INTEGER,
    OMSCHRIJVING TEXT
);

CREATE TABLE BEHANDELING (
    BEHANDELING_ID INTEGER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    HEEFT_BEHANDELING_SOCIAALTEAMDOSSIER_ID INTEGER,
    IS_VAN_SOORT_BEHANDELSOORT_ID INTEGER,
    TOELICHTING TEXT
);

CREATE TABLE KP_SCLTMDSSR_RLT (
    KP_SCLTMDSSR_RLT_ID INTEGER PRIMARY KEY,
    SOCIAALTEAMDOSSIER_ID INTEGER,
    RELATIE_ID INTEGER
);

CREATE TABLE DOELSTELLING (
    DOELSTELLING_ID INTEGER PRIMARY KEY,
    HEEFT_DOELSTELLING_SOCIAALTEAMDOSSIER_ID INTEGER,
    IS_VAN_SOORT_DOELSTELLINGSOORT_ID INTEGER,
    OMSCHRIJVING TEXT
);

ALTER TABLE KP_SCLTMDSSR_RLT ADD CONSTRAINT FK_KP_SCLTMDSSR_RLT_1 FOREIGN KEY (SOCIAALTEAMDOSSIER_ID) REFERENCES SOCIAALTEAMDOSSIER (SOCIAALTEAMDOSSIER_ID);
-- SOCIAALTEAMDOSSIER (many-to-many junction, Connector_ID: 921)

ALTER TABLE KP_SCLTMDSSR_RLT ADD CONSTRAINT FK_KP_SCLTMDSSR_RLT_2 FOREIGN KEY (RELATIE_ID) REFERENCES RELATIE (RELATIE_ID);
-- RELATIE (many-to-many junction, Connector_ID: 921)

ALTER TABLE KP_CLNTBGLDR_CLNT ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_1 FOREIGN KEY (CLIENTBEGELEIDER_ID) REFERENCES CLIENTBEGELEIDER (CLIENTBEGELEIDER_ID);
-- CLIENTBEGELEIDER (many-to-many junction, Connector_ID: 941)

ALTER TABLE KP_CLNTBGLDR_CLNT ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_2 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- CLIENT (many-to-many junction, Connector_ID: 941)

ALTER TABLE KP_CLNT_RLT ADD CONSTRAINT FK_KP_CLNT_RLT_1 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- CLIENT (many-to-many junction, Connector_ID: 954)

ALTER TABLE KP_CLNT_RLT ADD CONSTRAINT FK_KP_CLNT_RLT_2 FOREIGN KEY (RELATIE_ID) REFERENCES RELATIE (RELATIE_ID);
-- RELATIE (many-to-many junction, Connector_ID: 954)

ALTER TABLE KP_ZLFRDZMHDMTRX_SCRSRT ADD CONSTRAINT FK_KP_ZLFRDZMHDMTRX_SCRSRT_1 FOREIGN KEY (ZELFREDZAAMHEIDMATRIX_ID) REFERENCES ZELFREDZAAMHEIDMATRIX (ZELFREDZAAMHEIDMATRIX_ID);
-- ZELFREDZAAMHEIDMATRIX (many-to-many junction, Connector_ID: 1043)

ALTER TABLE KP_ZLFRDZMHDMTRX_SCRSRT ADD CONSTRAINT FK_KP_ZLFRDZMHDMTRX_SCRSRT_2 FOREIGN KEY (SCORESOORT_ID) REFERENCES SCORESOORT (SCORESOORT_ID);
-- SCORESOORT (many-to-many junction, Connector_ID: 1043)

ALTER TABLE KP_ZLFRDZMHDMTRX_LFGBD ADD CONSTRAINT FK_KP_ZLFRDZMHDMTRX_LFGBD_1 FOREIGN KEY (ZELFREDZAAMHEIDMATRIX_ID) REFERENCES ZELFREDZAAMHEIDMATRIX (ZELFREDZAAMHEIDMATRIX_ID);
-- ZELFREDZAAMHEIDMATRIX (many-to-many junction, Connector_ID: 1050)

ALTER TABLE KP_ZLFRDZMHDMTRX_LFGBD ADD CONSTRAINT FK_KP_ZLFRDZMHDMTRX_LFGBD_2 FOREIGN KEY (LEEFGEBIED_ID) REFERENCES LEEFGEBIED (LEEFGEBIED_ID);
-- LEEFGEBIED (many-to-many junction, Connector_ID: 1050)

ALTER TABLE SOCIAALTEAMDOSSIER ADD CONSTRAINT FK_SOCIAALTEAMDOSSIER_HEEFT_SOORT FOREIGN KEY (HEEFT_SOORT_SOCIAALTEAMDOSSIERSOORT_ID) REFERENCES SOCIAALTEAMDOSSIERSOORT (SOCIAALTEAMDOSSIERSOORT_ID);
-- HEEFT_SOORT (0..* to 1, Connector_ID: 858)

ALTER TABLE DOELSTELLING ADD CONSTRAINT FK_DOELSTELLING_HEEFT_DOELSTELLING FOREIGN KEY (HEEFT_DOELSTELLING_SOCIAALTEAMDOSSIER_ID) REFERENCES SOCIAALTEAMDOSSIER (SOCIAALTEAMDOSSIER_ID);
-- HEEFT_DOELSTELLING (1 to 0..*, Connector_ID: 859)

ALTER TABLE DOELSTELLING ADD CONSTRAINT FK_DOELSTELLING_IS_VAN_SOORT FOREIGN KEY (IS_VAN_SOORT_DOELSTELLINGSOORT_ID) REFERENCES DOELSTELLINGSOORT (DOELSTELLINGSOORT_ID);
-- IS_VAN_SOORT (0..* to 1, Connector_ID: 860)

ALTER TABLE SOCIAALTEAMDOSSIER ADD CONSTRAINT FK_SOCIAALTEAMDOSSIER_HEEFT_AANMELDING FOREIGN KEY (HEEFT_AANMELDING_CASEAANMELDING_ID) REFERENCES CASEAANMELDING (CASEAANMELDING_ID);
-- HEEFT_AANMELDING (0..1 to 0..1, Connector_ID: 861)

ALTER TABLE BIJZONDERHEID ADD CONSTRAINT FK_BIJZONDERHEID_HEEFT_BIJZONDERHEID FOREIGN KEY (HEEFT_BIJZONDERHEID_SOCIAALTEAMDOSSIER_ID) REFERENCES SOCIAALTEAMDOSSIER (SOCIAALTEAMDOSSIER_ID);
-- HEEFT_BIJZONDERHEID (1 to 0..*, Connector_ID: 862)

ALTER TABLE BIJZONDERHEID ADD CONSTRAINT FK_BIJZONDERHEID_IS_VAN_SOORT FOREIGN KEY (IS_VAN_SOORT_BIJZONDERHEIDSOORT_ID) REFERENCES BIJZONDERHEIDSOORT (BIJZONDERHEIDSOORT_ID);
-- IS_VAN_SOORT (0..* to 1, Connector_ID: 863)

ALTER TABLE BEHANDELING ADD CONSTRAINT FK_BEHANDELING_HEEFT_BEHANDELING FOREIGN KEY (HEEFT_BEHANDELING_SOCIAALTEAMDOSSIER_ID) REFERENCES SOCIAALTEAMDOSSIER (SOCIAALTEAMDOSSIER_ID);
-- HEEFT_BEHANDELING (1 to 0..*, Connector_ID: 864)

ALTER TABLE BEHANDELING ADD CONSTRAINT FK_BEHANDELING_IS_VAN_SOORT FOREIGN KEY (IS_VAN_SOORT_BEHANDELSOORT_ID) REFERENCES BEHANDELSOORT (BEHANDELSOORT_ID);
-- IS_VAN_SOORT (0..* to 1, Connector_ID: 865)

ALTER TABLE SOCIAALTEAMDOSSIER ADD CONSTRAINT FK_SOCIAALTEAMDOSSIER_HEEFT FOREIGN KEY (HEEFT_CLIENTBEGELEIDER_ID) REFERENCES CLIENTBEGELEIDER (CLIENTBEGELEIDER_ID);
-- HEEFT (1 to 0..*, Connector_ID: 938)

ALTER TABLE SOCIAALTEAMDOSSIER ADD CONSTRAINT FK_SOCIAALTEAMDOSSIER_HEEFT_2 FOREIGN KEY (HEEFT_CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 943)

ALTER TABLE SCORE ADD CONSTRAINT FK_SCORE_HEEFT FOREIGN KEY (HEEFT_CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1044)

ALTER TABLE SCORE ADD CONSTRAINT FK_SCORE_HOOGTE_SCORE FOREIGN KEY (HOOGTE_SCORE_SCORESOORT_ID) REFERENCES SCORESOORT (SCORESOORT_ID);
-- HOOGTE_SCORE (0..* to 1, Connector_ID: 1045)

ALTER TABLE SCORE ADD CONSTRAINT FK_SCORE_SCORE_BIJ_LEEGGEBIED FOREIGN KEY (SCORE_BIJ_LEEGGEBIED_LEEFGEBIED_ID) REFERENCES LEEFGEBIED (LEEFGEBIED_ID);
-- SCORE_BIJ_LEEGGEBIED (0..* to 1, Connector_ID: 1051)

