CREATE TABLE `NATUURLIJKPERSOON` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON` VARCHAR(50),
        `AANDUIDINGNAAMGEBRUIK` VARCHAR(50),
        `AANHEFAANSCHRIJVING` VARCHAR(50),
        `ACADEMISCHETITEL` VARCHAR(80),
        `ACHTERNAAM` VARCHAR(100),
        `ADELLIJKETITELOFPREDIKAAT` VARCHAR(255),
        `ANUMMER` VARCHAR(20),
        `ATTRIBUTE` VARCHAR(255),
        `BURGERSERVICENUMMER` VARCHAR(255),
        `DATUMGEBOORTE` DATE,
        `DATUMOVERLIJDEN` DATE,
        `GEBOORTELAND` VARCHAR(255),
        `GEBOORTEPLAATS` VARCHAR(200),
        `GESLACHTSAANDUIDING` VARCHAR(255),
        `GESLACHTSNAAM` VARCHAR(200),
        `GESLACHTSNAAMAANSCHRIJVING` VARCHAR(200),
        `HANDLICHTING` VARCHAR(50),
        `INDICATIEAFSCHERMINGPERSOONSGEGEVENS` BOOLEAN,
        `INDICATIEOVERLEDEN` BOOLEAN,
        `LANDOVERLIJDEN` VARCHAR(255),
        `NATIONALITEIT` VARCHAR(100),
        `OVERLIJDENSPLAATS` VARCHAR(200),
        `VOORLETTERSAANSCHRIJVING` VARCHAR(20),
        `VOORNAMEN` VARCHAR(200),
        `VOORNAMENAANSCHRIJVING` VARCHAR(200),
        `VOORVOEGSELGESLACHTSNAAM` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `CLIENT` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `CODE` VARCHAR(80),
        `GEZAGSDRAGERGEKEND` BOOLEAN,
        `JURIDISCHESTATUS` VARCHAR(80),
        `WETTELIJKEVERTEGENWOORDIGING` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `GEMEENTEBEGRAFENIS` (
    `GEMEENTEBEGRAFENIS_ID` INT PRIMARY KEY,
        `ACHTERGRONDMELDING` VARCHAR(200),
        `BEGRAFENISKOSTEN` DECIMAL(10,2),
        `DATUMAFGEDAAN` DATE,
        `DATUMBEGRAFENIS` DATE,
        `DATUMGEMELD` DATE,
        `DATUMRUIMINGGRAF` DATE,
        `DOODSOORZAAK` VARCHAR(80),
        `GEMEENTELIJKEKOSTEN` DECIMAL(10,2),
        `HEEFT_NATUURLIJKPERSOON_ID` INT,
        `INKOOPORDERNUMMER` VARCHAR(255),
        `MELDER` VARCHAR(80),
        `URENGEMEENTE` INT,
        `VERHAALDBEDRAG` DECIMAL(10,2)
) ENGINE=InnoDB;

CREATE TABLE `INGESCHREVENPERSOON` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `ADRESHERKOMST` VARCHAR(255),
        `ANUMMER` VARCHAR(20),
        `BESCHRIJVINGLOCATIE` VARCHAR(200),
        `BUITENLANDSREISDOCUMENT` VARCHAR(80),
        `BURGERLIJKESTAAT` VARCHAR(255),
        `DATUMBEGINGELDIGHEIDVERBLIJFPLAATS` DATE,
        `DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS` DATE,
        `DATUMINSCHRIJVINGGEMEENTE` DATE,
        `DATUMOPSCHORTINGBIJHOUDING` DATE,
        `DATUMVERTREKUITNEDERLAND` DATE,
        `DATUMVESTIGINGNEDERLAND` DATE,
        `GEMEENTEVANINSCHRIJVING` VARCHAR(80),
        `GEZINSRELATIE` VARCHAR(255),
        `INDICATIEGEHEIM` BOOLEAN,
        `INGEZETENE` BOOLEAN,
        `LANDWAARNAARVERTROKKEN` VARCHAR(255),
        `LANDWAARVANDAANINGESCHREVEN` VARCHAR(255),
        `OUDER1` VARCHAR(255),
        `OUDER2` VARCHAR(255),
        `OUDER_1_INGESCHREVENPERSOON_ID` INT,
        `OUDER_2_INGESCHREVENPERSOON_ID` INT,
        `PARTNERID` VARCHAR(255),
        `REDENEINDEBEWONING` DATE,
        `REDENOPSCHORTINGBIJHOUDING` VARCHAR(200),
        `SIGNALERINGREISDOCUMENT` BOOLEAN,
        `VERBLIJFSTITEL` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `CLIENT` ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY (`NATUURLIJKPERSOON_ID`) REFERENCES `INGESCHREVENPERSOON` (`NATUURLIJKPERSOON_ID`);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY (`NATUURLIJKPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE `GEMEENTEBEGRAFENIS` ADD CONSTRAINT FK_GEMEENTEBEGRAFENIS_HEEFT FOREIGN KEY (`HEEFT_NATUURLIJKPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- HEEFT (0..1 to 1, Connector_ID: 1081)

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (`OUDER_1_INGESCHREVENPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- OUDER_1 (None to None, Connector_ID: 170)

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (`OUDER_2_INGESCHREVENPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- OUDER_2 (None to None, Connector_ID: 171)

