CREATE TABLE `AANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
        `AFGEHANDELD` BOOLEAN,
        `CATEGORIE` VARCHAR(200),
        `CATEGORIECODE` VARCHAR(80),
        `DATUMAANMAAK` DATE,
        `DATUMAFHANDELING` DATE,
        `DATUMBEGINSTATUS` DATE,
        `DATUMEINDESTATUS` DATE,
        `HOOFDCATEGORIE` VARCHAR(80),
        `HOOFDCATEGORIECODE` VARCHAR(80),
        `IDENTIFICATIE` VARCHAR(255),
        `KANAAL` VARCHAR(80),
        `ONDERWERP` VARCHAR(200),
        `ONDERWERPCODE` VARCHAR(80),
        `SOORT` VARCHAR(80),
        `STATUS` VARCHAR(80),
        `STATUSCODE` VARCHAR(80),
        `STATUSVOLGORDE` VARCHAR(80),
        `SUBCATEGORIE` VARCHAR(200),
        `SUBCATEGORIECODE` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `CLIENT` (
    `CLIENT_ID` INT PRIMARY KEY,
        `CODE` VARCHAR(80),
        `GEZAGSDRAGERGEKEND` BOOLEAN,
        `JURIDISCHESTATUS` VARCHAR(80),
        `WETTELIJKEVERTEGENWOORDIGING` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `AOMMELDINGWMOJEUGD` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
        `AANMELDER` VARCHAR(100),
        `AANMELDINGDOOR` VARCHAR(100),
        `AANMELDINGDOORLANDELIJK` VARCHAR(100),
        `AANMELDWIJZE` VARCHAR(80),
        `DESKUNDIGHEID` VARCHAR(80),
        `HEEFT_CLIENT_ID` INT,
        `ISCLIENTOPDEHOOGTE` VARCHAR(50),
        `ONDERZOEKSWIJZE` VARCHAR(50),
        `REDENAFSLUITING` VARCHAR(80),
        `VERVOLG` VARCHAR(50),
        `VERWEZEN` VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE `BESCHIKKING` (
    `BESCHIKKING_ID` INT PRIMARY KEY,
        `BETREFT_AOMMELDINGWMOJEUGD_ID` INT,
        `CLIENT_ID` INT,
        `CODE` VARCHAR(20),
        `COMMENTAAR` VARCHAR(200),
        `DATUMAFGIFTE` DATE,
        `GRONDSLAGEN` INT,
        `WET` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `AOM_AANVRAAGWMOJEUGD` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
        `CLIENTREACTIE` VARCHAR(100),
        `DATUMBESCHIKKING` DATE,
        `DATUMEERSTEAFSPRAAK` DATE,
        `DATUMEINDE` DATE,
        `DATUMPLANVASTGESTELD` DATE,
        `DATUMSTARTAANVRAAG` DATE,
        `DESKUNDIGHEID` VARCHAR(50),
        `DOORLOOPMETHODIEK` VARCHAR(50),
        `HEEFT_CLIENT_ID` INT,
        `LEIDT_TOT_BESCHIKKING_ID` INT,
        `MAXIMALEDOORLOOPTIJD` DATETIME,
        `REDENAFSLUITING` VARCHAR(50)
) ENGINE=InnoDB;

ALTER TABLE `AOM_AANVRAAGWMOJEUGD` ADD CONSTRAINT FK_AOM_AANVRAAGWMOJEUGD_GEN_AANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE `AOMMELDINGWMOJEUGD` ADD CONSTRAINT FK_AOMMELDINGWMOJEUGD_GEN_AANVRAAGOFMELDING FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE `AOMMELDINGWMOJEUGD` ADD CONSTRAINT FK_AOMMELDINGWMOJEUGD_HEEFT FOREIGN KEY (`HEEFT_CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`);
-- HEEFT (None to None, Connector_ID: 1075)

ALTER TABLE `AOM_AANVRAAGWMOJEUGD` ADD CONSTRAINT FK_AOM_AANVRAAGWMOJEUGD_HEEFT FOREIGN KEY (`HEEFT_CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`);
-- HEEFT (None to None, Connector_ID: 1079)

ALTER TABLE `AOM_AANVRAAGWMOJEUGD` ADD CONSTRAINT FK_AOM_AANVRAAGWMOJEUGD_LEIDT_TOT FOREIGN KEY (`LEIDT_TOT_BESCHIKKING_ID`) REFERENCES `BESCHIKKING` (`BESCHIKKING_ID`);
-- LEIDT_TOT (0..1 to 0..*, Connector_ID: 1078)

ALTER TABLE `BESCHIKKING` ADD CONSTRAINT FK_BESCHIKKING_BETREFT FOREIGN KEY (`BETREFT_AOMMELDINGWMOJEUGD_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- BETREFT (None to None, Connector_ID: 1074)

ALTER TABLE `BESCHIKKING` ADD CONSTRAINT FK_BESCHIKKING_CLIENT FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`);
-- unnamed (0..* to 1, Connector_ID: 1069)

