CREATE TABLE LEVERANCIER (
    LEVERANCIER_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200),
        NUMMER VARCHAR2(255)
);

CREATE TABLE OMZETGROEP (
    OMZETGROEP_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR2(255) PRIMARY KEY,
        CODEMUSEUMJAARKAART VARCHAR2(255),
        DATUMEINDEGELDIGHEID DATE,
        DATUMSTART DATE,
        ENTREEKAART NUMBER,
        LEVERANCIER_LEVERANCIER_ID VARCHAR2(255),
        OMSCHRIJVING VARCHAR2(80),
        PRIJS NUMBER(10,2)
);

CREATE TABLE BALIEVERKOOP (
    BALIEVERKOOP_ID VARCHAR2(255) PRIMARY KEY,
        AANTAL NUMBER,
        BETREFT_PRODUCT_ID VARCHAR2(255),
        KANAAL VARCHAR2(80),
        VERKOOPTIJD TIMESTAMP
);

CREATE TABLE BALIEVERKOOP_ENTREEKAART (
    BALIEVERKOOP_ID VARCHAR2(255) PRIMARY KEY,
        DATUMEINDEGELDIGHEID DATE,
        DATUMSTART DATE,
        GEBRUIKTOP VARCHAR2(255),
        RONDLEIDING NUMBER(1)
);

CREATE TABLE ENTREEKAART (
    PRODUCT_ID VARCHAR2(255) PRIMARY KEY,
        RONDLEIDING NUMBER(1)
);

CREATE TABLE KP_PRDCT_OMZTGRP (
    KP_PRDCT_OMZTGRP_ID VARCHAR2(255) PRIMARY KEY,
    PRODUCT_ID VARCHAR2(255),
    OMZETGROEP_ID VARCHAR2(255)
);

CREATE TABLE PRODUCTGROEP (
    PRODUCTGROEP_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE KP_PRDCT_PRDCTGRP (
    KP_PRDCT_PRDCTGRP_ID VARCHAR2(255) PRIMARY KEY,
    PRODUCT_ID VARCHAR2(255),
    PRODUCTGROEP_ID VARCHAR2(255)
);

CREATE TABLE WINKELVOORRAADITEM (
    WINKELVOORRAADITEM_ID VARCHAR2(255) PRIMARY KEY,
        AANTAL NUMBER,
        AANTALINBESTELLING NUMBER,
        BETREFT_PRODUCT_ID VARCHAR2(255),
        DATUMLEVERINGBESTELLING DATE,
        LOCATIE VARCHAR2(80)
);

ALTER TABLE BALIEVERKOOP_ENTREEKAART ADD CONSTRAINT FK_BALIEVERKOOP_ENTREEKAART_GEN_BALIEVERKOOP FOREIGN KEY (BALIEVERKOOP_ID) REFERENCES BALIEVERKOOP (BALIEVERKOOP_ID);
-- Generalization to BALIEVERKOOP

ALTER TABLE ENTREEKAART ADD CONSTRAINT FK_ENTREEKAART_GEN_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- Generalization to PRODUCT

ALTER TABLE KP_PRDCT_OMZTGRP ADD CONSTRAINT FK_KP_PRDCT_OMZTGRP_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- PRODUCT (many-to-many junction, Connector_ID: 1114)

ALTER TABLE KP_PRDCT_OMZTGRP ADD CONSTRAINT FK_KP_PRDCT_OMZTGRP_2 FOREIGN KEY (OMZETGROEP_ID) REFERENCES OMZETGROEP (OMZETGROEP_ID);
-- OMZETGROEP (many-to-many junction, Connector_ID: 1114)

ALTER TABLE KP_PRDCT_PRDCTGRP ADD CONSTRAINT FK_KP_PRDCT_PRDCTGRP_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- PRODUCT (many-to-many junction, Connector_ID: 1112)

ALTER TABLE KP_PRDCT_PRDCTGRP ADD CONSTRAINT FK_KP_PRDCT_PRDCTGRP_2 FOREIGN KEY (PRODUCTGROEP_ID) REFERENCES PRODUCTGROEP (PRODUCTGROEP_ID);
-- PRODUCTGROEP (many-to-many junction, Connector_ID: 1112)

ALTER TABLE BALIEVERKOOP ADD CONSTRAINT FK_BALIEVERKOOP_BETREFT FOREIGN KEY (BETREFT_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- BETREFT (0..* to 1, Connector_ID: 1133)

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_LEVERANCIER FOREIGN KEY (LEVERANCIER_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- LEVERANCIER (0..* to 0..1, Connector_ID: 1111)

ALTER TABLE WINKELVOORRAADITEM ADD CONSTRAINT FK_WINKELVOORRAADITEM_BETREFT FOREIGN KEY (BETREFT_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- BETREFT (0..1 to 1, Connector_ID: 1110)

