CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR(255) PRIMARY KEY,
        HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID VARCHAR(255),
        HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID VARCHAR(255),
        HEEFT_WINKELVLOEROPPERVLAK_ID VARCHAR(255),
        IDENTIFICATIE VARCHAR(255),
        TYPEADRESSEERBAAROBJECT VARCHAR(255),
        VERSIE INTEGER
);

CREATE TABLE BUURT (
    BUURT_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        CODE VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD BOOLEAN,
        GEOMETRIE GEOMETRY,
        IDENTIFICATIE VARCHAR(255),
        LIGT_IN_WIJK_ID VARCHAR(255),
        NAAM VARCHAR(255),
        STATUS VARCHAR(255),
        VERSIE INTEGER
);

CREATE TABLE GEBIED (
    GEBIED_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDBUURT DATE,
        DATUMEINDEGELDIGHEIDGEBIED DATE,
        GEBIEDCODE VARCHAR(255),
        GEBIEDSOORT VARCHAR(80),
        GEOMETRIE GEOMETRY,
        IDENTIFICATIEIMGEOBRT VARCHAR(255),
        KOMT_OVEREEN_BUURT_ID VARCHAR(255),
        NAAM VARCHAR(255)
);

CREATE TABLE KP_NMMRNDDNG_GBD (
    KP_NMMRNDDNG_GBD_ID VARCHAR(255) PRIMARY KEY,
    NUMMERAANDUIDING_ID VARCHAR(255),
    GEBIED_ID VARCHAR(255)
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER INTEGER,
        EINDEGELDIGHEID DATE,
        GECONSTATEERD BOOLEAN,
        GEOMETRIE GEOMETRY,
        HEEFT_ALS_LOCATIE_ADRES_VESTIGING_ID VARCHAR(255),
        HUISLETTER VARCHAR(255),
        HUISNUMMER VARCHAR(255),
        HUISNUMMERTOEVOEGING VARCHAR(255),
        IDENTIFICATIE VARCHAR(255),
        LIGT_AAN_OPENBARERUIMTE_ID VARCHAR(255),
        LIGT_IN_BUURT_ID VARCHAR(255),
        POSTCODE VARCHAR(255),
        STATUS VARCHAR(255),
        TYPEADRESSEERBAAROBJECT VARCHAR(255),
        VERSIE INTEGER
);

CREATE TABLE OPENBARERUIMTE (
    OPENBARERUIMTE_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER INTEGER,
        EINDGELDIGHEID DATE,
        GECONSTATEERD BOOLEAN,
        GEOMETRIE GEOMETRY,
        HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS VARCHAR(255),
        HUISNUMMERRANGE_EVEN_NUMMERS VARCHAR(255),
        HUISNUMMERRANGE_ONEVEN_NUMMERS VARCHAR(255),
        IDENTIFICATIE VARCHAR(255),
        LABELNAAM VARCHAR(80),
        LIGT_IN_BUURT_ID VARCHAR(255),
        NAAMOPENBARERUIMTE VARCHAR(80),
        STATUS VARCHAR(255),
        STRAATCODE VARCHAR(80),
        STRAATNAAM VARCHAR(255),
        TYPEOPENBARERUIMTE VARCHAR(255),
        VERSIE INTEGER,
        WEGSEGMENT VARCHAR(255)
);

CREATE TABLE VERBLIJFSOBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR(255) PRIMARY KEY,
        AANTALKAMERS VARCHAR(255),
        BEGINGELDIGHEID DATE,
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER INTEGER,
        EINDGELDIGHEID DATE,
        GEBRUIKSDOEL VARCHAR(255),
        GECONSTATEERD BOOLEAN,
        GEOMETRIE GEOMETRY,
        HOOGSTEBOUWLAAG VARCHAR(255),
        IDENTIFICATIE VARCHAR(255),
        LAAGSTEBOUWLAAG VARCHAR(255),
        ONTSLUITINGVERDIEPING VARCHAR(255),
        OPPERVLAKTE INTEGER,
        SOORTWOONOBJECT VARCHAR(255),
        STATUS VARCHAR(255),
        TOEGANGBOUWLAAG VARCHAR(255),
        VERSIE INTEGER
);

CREATE TABLE VESTIGING (
    VESTIGING_ID VARCHAR(255) PRIMARY KEY,
        COMMERCIELEVESTIGING BOOLEAN,
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMVOORTZETTING DATE,
        FULLTIMEWERKZAMEMANNEN VARCHAR(255),
        FULLTIMEWERKZAMEVROUWEN VARCHAR(255),
        HANDELSNAAM VARCHAR(255),
        HEEFT_HOOFDLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID VARCHAR(255),
        HEEFT_NEVENLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID VARCHAR(255),
        PARTTIMEWERKZAMEMANNEN VARCHAR(255),
        PARTTIMEWERKZAMEVROUWEN VARCHAR(255),
        TOEVOEGINGADRES VARCHAR(100),
        TOTAALWERKZAMEPERSONEN VARCHAR(255),
        VERKORTENAAM VARCHAR(255),
        VESTIGINGSNUMMER VARCHAR(255)
);

CREATE TABLE WIJK (
    WIJK_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD BOOLEAN,
        GEOMETRIE GEOMETRY,
        IDENTIFICATIE VARCHAR(255),
        STATUS VARCHAR(255),
        VERSIE INTEGER,
        WIJKCODE VARCHAR(255),
        WIJKNAAM VARCHAR(255)
);

CREATE TABLE WINKELVLOEROPPERVLAK (
    WINKELVLOEROPPERVLAK_ID VARCHAR(255) PRIMARY KEY,
        AANTALKASSA INTEGER,
        BRONWVO VARCHAR(255),
        LEEGSTAND BOOLEAN,
        WINKELVLOEROPPERVLAKTE INTEGER,
        WVOKLASSE VARCHAR(255)
);

ALTER TABLE VERBLIJFSOBJECT ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY (ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE KP_NMMRNDDNG_GBD ADD CONSTRAINT FK_KP_NMMRNDDNG_GBD_1 FOREIGN KEY (NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- NUMMERAANDUIDING (many-to-many junction, Connector_ID: 353)

ALTER TABLE KP_NMMRNDDNG_GBD ADD CONSTRAINT FK_KP_NMMRNDDNG_GBD_2 FOREIGN KEY (GEBIED_ID) REFERENCES GEBIED (GEBIED_ID);
-- GEBIED (many-to-many junction, Connector_ID: 353)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT FOREIGN KEY (HEEFT_WINKELVLOEROPPERVLAK_ID) REFERENCES WINKELVLOEROPPERVLAK (WINKELVLOEROPPERVLAK_ID);
-- HEEFT (1 to 0..1, Connector_ID: 1250)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 350)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 347)

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_LIGT_IN FOREIGN KEY (LIGT_IN_WIJK_ID) REFERENCES WIJK (WIJK_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 346)

ALTER TABLE GEBIED ADD CONSTRAINT FK_GEBIED_KOMT_OVEREEN FOREIGN KEY (KOMT_OVEREEN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- KOMT_OVEREEN (0..1 to 0..1, Connector_ID: 345)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_HEEFT_ALS_LOCATIE_ADRES FOREIGN KEY (HEEFT_ALS_LOCATIE_ADRES_VESTIGING_ID) REFERENCES VESTIGING (VESTIGING_ID);
-- HEEFT_ALS_LOCATIE_ADRES (1 to 0..*, Connector_ID: 355)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY (LIGT_AAN_OPENBARERUIMTE_ID) REFERENCES OPENBARERUIMTE (OPENBARERUIMTE_ID);
-- LIGT_AAN (0..* to 1, Connector_ID: 354)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_IN FOREIGN KEY (LIGT_IN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- LIGT_IN (1 to 1, Connector_ID: 1538)

ALTER TABLE OPENBARERUIMTE ADD CONSTRAINT FK_OPENBARERUIMTE_LIGT_IN FOREIGN KEY (LIGT_IN_BUURT_ID) REFERENCES BUURT (BUURT_ID);
-- LIGT_IN (1 to 1..*, Connector_ID: 343)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_HEEFT_HOOFDLOCATIE_IN_OF_OP FOREIGN KEY (HEEFT_HOOFDLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_HOOFDLOCATIE_IN_OF_OP (0..* to 0..1, Connector_ID: 332)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_HEEFT_NEVENLOCATIE_IN_OF_OP FOREIGN KEY (HEEFT_NEVENLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_NEVENLOCATIE_IN_OF_OP (0..* to 0..1, Connector_ID: 333)

