CREATE TABLE KP_MDWRKR_ORGNSTRSCHNHD (
    KP_MDWRKR_ORGNSTRSCHNHD_ID INTEGER PRIMARY KEY,
    MEDEWERKER_ID INTEGER,
    ORGANISATORISCHEEENHEID_ID INTEGER
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID INTEGER PRIMARY KEY,
    BTWCODE VARCHAR(255),
    BTWOMSCHRIJVING VARCHAR(80),
    KOSTENPLAATSSOORTCODE DECIMAL(10,2),
    KOSTENPLAATSSOORTOMSCHRIJVING DECIMAL(10,2),
    KOSTENPLAATSTYPECODE DECIMAL(10,2),
    KOSTENPLAATSTYPEOMSCHRIJVING DECIMAL(10,2),
    NAAM VARCHAR(80),
    OMSCHRIJVING VARCHAR(200)
);

CREATE TABLE LEVERANCIER (
    LEVERANCIER_ID INTEGER PRIMARY KEY,
    BIEDT_AAN_KANDIDAAT_ID INTEGER,
    CONTRACTANT_CONTRACT_ID INTEGER,
    NAAM VARCHAR(200),
    NUMMER VARCHAR(255)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID INTEGER PRIMARY KEY,
    ACHTERNAAM VARCHAR(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR(255),
    EXTERN BOOLEAN,
    FUNCTIE VARCHAR(50),
    GELEVERD_VIA_LEVERANCIER_ID INTEGER,
    GESLACHTSAANDUIDING VARCHAR(255),
    IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID INTEGER,
    IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID INTEGER,
    MEDEWERKERIDENTIFICATIE VARCHAR(255),
    MEDEWERKERTOELICHTING VARCHAR(255),
    ROEPNAAM VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20),
    VOORLETTERS VARCHAR(20),
    VOORVOEGSELACHTERNAAM VARCHAR(255)
);

CREATE TABLE AANBESTEDING_INHUUR (
    AANBESTEDING_INHUUR_ID INTEGER PRIMARY KEY,
    AANVRAAGGESLOTEN VARCHAR(255),
    AANVRAAGNUMMER VARCHAR(80),
    DATUMCREATIE DATE,
    DATUMOPENINGKLUIS DATE,
    DATUMSLUITING DATE,
    DATUMVERZENDING DATE,
    DOCUMENT_ID INTEGER,
    EIGENAAR_MEDEWERKER_ID INTEGER,
    FASE VARCHAR(80),
    HOOGSTETARIEF DECIMAL(10,2),
    LAAGSTETARIEF DECIMAL(10,2),
    MONDT_UIT_GUNNING_ID INTEGER,
    OMSCHRIJVING TEXT,
    PERCEEL VARCHAR(80),
    PROCEDURE VARCHAR(80),
    PROJECTNAAM VARCHAR(200),
    PROJECTREFERENTIE VARCHAR(255),
    PUBLICATIE VARCHAR(80),
    REFERENTIE VARCHAR(80),
    STATUS VARCHAR(80),
    TITEL VARCHAR(200),
    TYPE VARCHAR(255),
    VALT_BINNEN_CATEGORIE_ID INTEGER
);

CREATE TABLE FORMULIERINHUUR (
    FORMULIERINHUUR_ID INTEGER PRIMARY KEY,
    AANVRAGER_MEDEWERKER_ID INTEGER,
    AKKOORDFINANCIEELADVISEUR BOOLEAN,
    AKKOORDHRADVISEUR BOOLEAN,
    DATUMINGANGINHUUR DATE,
    DOCUMENT_ID INTEGER,
    FUNCTIENAAMINHUUR VARCHAR(200),
    HEEFT_KOSTENPLAATS_ID INTEGER,
    MONDT_UIT_IN_AANBESTEDING_INHUUR_ID INTEGER
);

CREATE TABLE ORGANISATORISCHEEENHEID (
    ORGANISATORISCHEEENHEID_ID INTEGER PRIMARY KEY,
    DATUMONTSTAAN DATE,
    DATUMOPHEFFING DATE,
    EMAILADRES VARCHAR(255),
    FAXNUMMER VARCHAR(20),
    FORMATIE VARCHAR(255),
    HEEFT_KOSTENPLAATS_ID INTEGER,
    IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID INTEGER,
    NAAM VARCHAR(50),
    NAAMVERKORT VARCHAR(255),
    OMSCHRIJVING VARCHAR(80),
    ORGANISATIEIDENTIFICATIE VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20),
    TOELICHTING VARCHAR(255)
);

CREATE TABLE CATEGORIE (
    CATEGORIE_ID INTEGER PRIMARY KEY,
    CODE VARCHAR(80),
    OMSCHRIJVING VARCHAR(255)
);

CREATE TABLE KP_KSTNPLTS_INKPRDR (
    KP_KSTNPLTS_INKPRDR_ID INTEGER PRIMARY KEY,
    KOSTENPLAATS_ID INTEGER,
    INKOOPORDER_ID INTEGER
);

CREATE TABLE UITNODIGING (
    UITNODIGING_ID INTEGER PRIMARY KEY,
    AFGEWEZEN BOOLEAN,
    BETREFT_AANBESTEDING_INHUUR_ID INTEGER,
    DATUM DATE,
    GEACCEPTEERD BOOLEAN,
    GERICHT_AAN_LEVERANCIER_ID INTEGER
);

CREATE TABLE NATUURLIJKPERSOON (
    NATUURLIJKPERSOON_ID INTEGER PRIMARY KEY,
    AANDUIDINGNAAMGEBRUIK VARCHAR(50),
    AANHEFAANSCHRIJVING VARCHAR(50),
    ACADEMISCHETITEL VARCHAR(80),
    ACHTERNAAM VARCHAR(100),
    ADELLIJKETITELOFPREDIKAAT VARCHAR(255),
    ANUMMER VARCHAR(20),
    BIJZONDERNEDERLANDERSCHAP VARCHAR(50),
    BURGERSERVICENUMMER VARCHAR(255),
    DATUMGEBOORTE DATE,
    DATUMOVERLIJDEN DATE,
    GEBOORTELAND VARCHAR(255),
    GEBOORTEPLAATS VARCHAR(200),
    GESLACHTSAANDUIDING VARCHAR(255),
    GESLACHTSNAAM VARCHAR(200),
    GESLACHTSNAAMAANSCHRIJVING VARCHAR(200),
    HANDLICHTING VARCHAR(50),
    INDICATIEAFSCHERMINGPERSOONSGEGEVENS BOOLEAN,
    INDICATIEOVERLEDEN BOOLEAN,
    LANDOVERLIJDEN VARCHAR(255),
    NATIONALITEIT VARCHAR(100),
    OVERLIJDENSPLAATS VARCHAR(200),
    VOORLETTERSAANSCHRIJVING VARCHAR(20),
    VOORNAMEN VARCHAR(200),
    VOORNAMENAANSCHRIJVING VARCHAR(200),
    VOORVOEGSELGESLACHTSNAAM VARCHAR(80)
);

CREATE TABLE CONTRACT (
    CONTRACT_ID INTEGER PRIMARY KEY,
    AUTORISATIEGROEP VARCHAR(200),
    BESCHRIJVING TEXT,
    BOVENLIGGEND_CONTRACT_ID INTEGER,
    CATEGORIE VARCHAR(80),
    CLASSIFICATIE VARCHAR(80),
    CONTRACTREVISIE INTEGER,
    DATUMCREATIE DATE,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    GROEP VARCHAR(80),
    INTERNCONTRACTID VARCHAR(255),
    INTERNCONTRACTREVISIE INTEGER,
    OPMERKINGEN TEXT,
    STATUS VARCHAR(80),
    TYPE VARCHAR(80),
    VASTLEGGING_ALS_CONTRACT_DOCUMENT_ID INTEGER,
    VOORWAARDE VARCHAR(80),
    ZOEKWOORDEN VARCHAR(255)
);

CREATE TABLE KP_LVRNCR_CTGR (
    KP_LVRNCR_CTGR_ID INTEGER PRIMARY KEY,
    LEVERANCIER_ID INTEGER,
    CATEGORIE_ID INTEGER
);

CREATE TABLE INKOOPORDER (
    INKOOPORDER_ID INTEGER PRIMARY KEY,
    ARTIKELCODE VARCHAR(80),
    BETALINGMEERDEREJAREN BOOLEAN,
    BETREFT VARCHAR(255),
    BETREFT_CONTRACT_ID INTEGER,
    DATUMEINDE DATE,
    DATUMINGEDIEND DATE,
    DATUMSTART DATE,
    GERELATEERD_INKOOPORDER_ID INTEGER,
    GOEDERENCODE VARCHAR(80),
    OMSCHRIJVING VARCHAR(255),
    OORSPRONKELIJK_INKOOPORDER_ID INTEGER,
    ORDERNUMMER VARCHAR(255),
    SALDO VARCHAR(255),
    TOTAALNETTOBEDRAG DECIMAL(10,2),
    VERPLICHTING_AAN_LEVERANCIER_ID INTEGER,
    WIJZEVANAANBESTEDEN VARCHAR(255)
);

CREATE TABLE GUNNING (
    GUNNING_ID INTEGER PRIMARY KEY,
    BERICHT VARCHAR(255),
    BETREFT_KANDIDAAT_ID INTEGER,
    DATUMGUNNING DATE,
    DATUMPUBLICATIE DATE,
    DATUMVOORLOPIGEGUNNING DATE,
    GEGUNDEPRIJS DECIMAL(10,2),
    INHUUR_MEDEWERKER_ID INTEGER
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID INTEGER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR(200),
    DOCUMENTIDENTIFICATIE VARCHAR(255),
    DOCUMENTTITEL VARCHAR(200),
    VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE KANDIDAAT (
    KANDIDAAT_ID INTEGER PRIMARY KEY,
    BETREFT_NATUURLIJKPERSOON_ID INTEGER,
    DATUMINGESTUURD DATE,
    INGEDIEND_VOOR_AANBESTEDING_INHUUR_ID INTEGER
);

ALTER TABLE KP_LVRNCR_CTGR ADD CONSTRAINT FK_KP_LVRNCR_CTGR_1 FOREIGN KEY (LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- LEVERANCIER (many-to-many junction, Connector_ID: 406)

ALTER TABLE KP_LVRNCR_CTGR ADD CONSTRAINT FK_KP_LVRNCR_CTGR_2 FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORIE (CATEGORIE_ID);
-- CATEGORIE (many-to-many junction, Connector_ID: 406)

ALTER TABLE KP_KSTNPLTS_INKPRDR ADD CONSTRAINT FK_KP_KSTNPLTS_INKPRDR_1 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 492)

ALTER TABLE KP_KSTNPLTS_INKPRDR ADD CONSTRAINT FK_KP_KSTNPLTS_INKPRDR_2 FOREIGN KEY (INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- INKOOPORDER (many-to-many junction, Connector_ID: 492)

ALTER TABLE KP_MDWRKR_ORGNSTRSCHNHD ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_1 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2175)

ALTER TABLE KP_MDWRKR_ORGNSTRSCHNHD ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_2 FOREIGN KEY (ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- ORGANISATORISCHEEENHEID (many-to-many junction, Connector_ID: 2175)

ALTER TABLE FORMULIERINHUUR ADD CONSTRAINT FK_FORMULIERINHUUR_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- unnamed (None to None, Connector_ID: 102)

ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_VASTLEGGING_ALS_CONTRACT FOREIGN KEY (VASTLEGGING_ALS_CONTRACT_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- VASTLEGGING_ALS_CONTRACT (None to None, Connector_ID: 103)

ALTER TABLE AANBESTEDING_INHUUR ADD CONSTRAINT FK_AANBESTEDING_INHUUR_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- unnamed (None to None, Connector_ID: 105)

ALTER TABLE UITNODIGING ADD CONSTRAINT FK_UITNODIGING_GERICHT_AAN FOREIGN KEY (GERICHT_AAN_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- GERICHT_AAN (0..* to 1, Connector_ID: 389)

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_BIEDT_AAN FOREIGN KEY (BIEDT_AAN_KANDIDAAT_ID) REFERENCES KANDIDAAT (KANDIDAAT_ID);
-- BIEDT_AAN (1 to 0..*, Connector_ID: 392)

ALTER TABLE KANDIDAAT ADD CONSTRAINT FK_KANDIDAAT_BETREFT FOREIGN KEY (BETREFT_NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (NATUURLIJKPERSOON_ID);
-- BETREFT (0..* to 1, Connector_ID: 393)

ALTER TABLE GUNNING ADD CONSTRAINT FK_GUNNING_INHUUR FOREIGN KEY (INHUUR_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- INHUUR (0..* to 0..1, Connector_ID: 395)

ALTER TABLE GUNNING ADD CONSTRAINT FK_GUNNING_BETREFT FOREIGN KEY (BETREFT_KANDIDAAT_ID) REFERENCES KANDIDAAT (KANDIDAAT_ID);
-- BETREFT (0..1 to 1, Connector_ID: 397)

ALTER TABLE FORMULIERINHUUR ADD CONSTRAINT FK_FORMULIERINHUUR_AANVRAGER FOREIGN KEY (AANVRAGER_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- AANVRAGER (0..* to 1, Connector_ID: 402)

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_CONTRACTANT FOREIGN KEY (CONTRACTANT_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- CONTRACTANT (1 to 0..*, Connector_ID: 404)

ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_BOVENLIGGEND FOREIGN KEY (BOVENLIGGEND_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- BOVENLIGGEND (0..* to 0..1, Connector_ID: 405)

ALTER TABLE KANDIDAAT ADD CONSTRAINT FK_KANDIDAAT_INGEDIEND_VOOR FOREIGN KEY (INGEDIEND_VOOR_AANBESTEDING_INHUUR_ID) REFERENCES AANBESTEDING_INHUUR (AANBESTEDING_INHUUR_ID);
-- INGEDIEND_VOOR (0..* to 1, Connector_ID: 414)

ALTER TABLE FORMULIERINHUUR ADD CONSTRAINT FK_FORMULIERINHUUR_MONDT_UIT_IN FOREIGN KEY (MONDT_UIT_IN_AANBESTEDING_INHUUR_ID) REFERENCES AANBESTEDING_INHUUR (AANBESTEDING_INHUUR_ID);
-- MONDT_UIT_IN (0..1 to 0..1, Connector_ID: 415)

ALTER TABLE UITNODIGING ADD CONSTRAINT FK_UITNODIGING_BETREFT FOREIGN KEY (BETREFT_AANBESTEDING_INHUUR_ID) REFERENCES AANBESTEDING_INHUUR (AANBESTEDING_INHUUR_ID);
-- BETREFT (0..* to 1, Connector_ID: 416)

ALTER TABLE AANBESTEDING_INHUUR ADD CONSTRAINT FK_AANBESTEDING_INHUUR_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_CATEGORIE_ID) REFERENCES CATEGORIE (CATEGORIE_ID);
-- VALT_BINNEN (0..* to 1, Connector_ID: 417)

ALTER TABLE AANBESTEDING_INHUUR ADD CONSTRAINT FK_AANBESTEDING_INHUUR_EIGENAAR FOREIGN KEY (EIGENAAR_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- EIGENAAR (0..* to 0..1, Connector_ID: 418)

ALTER TABLE AANBESTEDING_INHUUR ADD CONSTRAINT FK_AANBESTEDING_INHUUR_MONDT_UIT FOREIGN KEY (MONDT_UIT_GUNNING_ID) REFERENCES GUNNING (GUNNING_ID);
-- MONDT_UIT (1 to 0..1, Connector_ID: 420)

ALTER TABLE FORMULIERINHUUR ADD CONSTRAINT FK_FORMULIERINHUUR_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..* to 1, Connector_ID: 485)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_OORSPRONKELIJK FOREIGN KEY (OORSPRONKELIJK_INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- OORSPRONKELIJK (0..1 to 0..1, Connector_ID: 493)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_GERELATEERD FOREIGN KEY (GERELATEERD_INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- GERELATEERD (0..1 to 0..*, Connector_ID: 494)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_BETREFT FOREIGN KEY (BETREFT_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- BETREFT (0..1 to 1, Connector_ID: 495)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_VERPLICHTING_AAN FOREIGN KEY (VERPLICHTING_AAN_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- VERPLICHTING_AAN (0..* to 1, Connector_ID: 496)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_DEEL_VAN FOREIGN KEY (IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_DEEL_VAN (1 to 0..1, Connector_ID: 2059)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..1 to 1, Connector_ID: 2063)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJK_VOOR FOREIGN KEY (IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_VERANTWOORDELIJK_VOOR (0..1 to 0..1, Connector_ID: 2166)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_CONTACTPERSOON_VOOR FOREIGN KEY (IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_CONTACTPERSOON_VOOR (0..1 to 0..1, Connector_ID: 2185)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_GELEVERD_VIA FOREIGN KEY (GELEVERD_VIA_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- GELEVERD_VIA (0..* to 0..1, Connector_ID: 2194)

