CREATE TABLE `FUNCTIE` (
    `FUNCTIE_ID` INT PRIMARY KEY,
        `CODE` VARCHAR(50),
        `NAAM` VARCHAR(80),
        `OMSCHRIJVING` TEXT,
        `SCHAAL` VARCHAR(20),
        `TAKEN` TEXT
) ENGINE=InnoDB;

CREATE TABLE `OPDRACHTGEVER` (
    `OPDRACHTGEVER_ID` INT PRIMARY KEY,
        `CLUSTERCODE` VARCHAR(20),
        `CLUSTEROMSCHRIJVING` VARCHAR(80),
        `NAAM` VARCHAR(80),
        `NUMMER` VARCHAR(20),
        `OMSCHRIJVING` TEXT,
        `UITGEVOERD_DOOR_FUNCTIE_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `OPDRACHTNEMER` (
    `OPDRACHTNEMER_ID` INT PRIMARY KEY,
        `CLUSTERCODE` VARCHAR(20),
        `CLUSTERCODEOMSCHRIJVING` VARCHAR(80),
        `NAAM` VARCHAR(80),
        `NUMMER` VARCHAR(20),
        `OMSCHRIJVING` VARCHAR(80),
        `UITGEVOERD_DOOR_FUNCTIE_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `OPDRACHTGEVER` ADD CONSTRAINT FK_OPDRACHTGEVER_UITGEVOERD_DOOR FOREIGN KEY (`UITGEVOERD_DOOR_FUNCTIE_ID`) REFERENCES `FUNCTIE` (`FUNCTIE_ID`);
-- UITGEVOERD_DOOR (0..* to 1, Connector_ID: 479)

ALTER TABLE `OPDRACHTNEMER` ADD CONSTRAINT FK_OPDRACHTNEMER_UITGEVOERD_DOOR FOREIGN KEY (`UITGEVOERD_DOOR_FUNCTIE_ID`) REFERENCES `FUNCTIE` (`FUNCTIE_ID`);
-- UITGEVOERD_DOOR (0..* to 1, Connector_ID: 477)

