CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDEGELDIGHEID DATE,
    GECONSTATEERD NUMBER(1),
    GEOMETRIE SDO_GEOMETRY,
    HUISLETTER VARCHAR2(255),
    HUISNUMMER VARCHAR2(255),
    HUISNUMMERTOEVOEGING VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    POSTCODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    TYPEADRESSEERBAAROBJECT VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE ADRESAANDUIDING (
    ADRESAANDUIDING_ID NUMBER PRIMARY KEY,
    BAGID VARCHAR2(255),
    GEMEENTENAAM VARCHAR2(80),
    HUISLETTER VARCHAR2(255),
    HUISNUMMER VARCHAR2(255),
    HUISNUMMERTOEVOEGING VARCHAR2(255),
    POSTCODE VARCHAR2(255),
    STRAATNAAM VARCHAR2(200),
    VERWIJST_NAAR_NUMMERAANDUIDING_ID NUMBER
);

ALTER TABLE ADRESAANDUIDING ADD CONSTRAINT FK_ADRESAANDUIDING_VERWIJST_NAAR FOREIGN KEY (VERWIJST_NAAR_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- VERWIJST_NAAR (0..1 to 0..1, Connector_ID: 2271)

