CREATE TABLE `NATUURLIJKPERSOON` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
    `AANDUIDINGNAAMGEBRUIK` VARCHAR(50),
    `AANHEFAANSCHRIJVING` VARCHAR(50),
    `ACADEMISCHETITEL` VARCHAR(80),
    `ACHTERNAAM` VARCHAR(100),
    `ADELLIJKETITELOFPREDIKAAT` VARCHAR(255),
    `ANUMMER` VARCHAR(20),
    `BIJZONDERNEDERLANDERSCHAP` VARCHAR(50),
    `BURGERSERVICENUMMER` VARCHAR(255),
    `DATUMGEBOORTE` DATE,
    `DATUMOVERLIJDEN` DATE,
    `GEBOORTELAND` VARCHAR(255),
    `GEBOORTEPLAATS` VARCHAR(200),
    `GESLACHTSAANDUIDING` VARCHAR(255),
    `GESLACHTSNAAM` VARCHAR(200),
    `GESLACHTSNAAMAANSCHRIJVING` VARCHAR(200),
    `HANDLICHTING` VARCHAR(50),
    `INDICATIEAFSCHERMINGPERSOONSGEGEVENS` BOOLEAN,
    `INDICATIEOVERLEDEN` BOOLEAN,
    `LANDOVERLIJDEN` VARCHAR(255),
    `NATIONALITEIT` VARCHAR(100),
    `OVERLIJDENSPLAATS` VARCHAR(200),
    `VOORLETTERSAANSCHRIJVING` VARCHAR(20),
    `VOORNAMEN` VARCHAR(200),
    `VOORNAMENAANSCHRIJVING` VARCHAR(200),
    `VOORVOEGSELGESLACHTSNAAM` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `INGESCHREVENPERSOON` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
    `ADRESHERKOMST` VARCHAR(255),
    `ANUMMER` VARCHAR(20),
    `BESCHRIJVINGLOCATIE` VARCHAR(200),
    `BUITENLANDSREISDOCUMENT` VARCHAR(80),
    `BURGERLIJKESTAAT` VARCHAR(255),
    `DATUMBEGINGELDIGHEIDVERBLIJFPLAATS` DATE,
    `DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS` DATE,
    `DATUMINSCHRIJVINGGEMEENTE` DATE,
    `DATUMOPSCHORTINGBIJHOUDING` DATE,
    `DATUMVERTREKUITNEDERLAND` DATE,
    `DATUMVESTIGINGNEDERLAND` DATE,
    `GEMEENTEVANINSCHRIJVING` VARCHAR(80),
    `GEZINSRELATIE` VARCHAR(255),
    `INDICATIEGEHEIM` BOOLEAN,
    `INGEZETENE` BOOLEAN,
    `LANDWAARNAARVERTROKKEN` VARCHAR(255),
    `LANDWAARVANDAANINGESCHREVEN` VARCHAR(255),
    `OUDER1` VARCHAR(255),
    `OUDER2` VARCHAR(255),
    `OUDER_1_INGESCHREVENPERSOON_ID` INT,
    `OUDER_2_INGESCHREVENPERSOON_ID` INT,
    `PARTNERID` VARCHAR(255),
    `REDENEINDEBEWONING` DATE,
    `REDENOPSCHORTINGBIJHOUDING` VARCHAR(200),
    `SIGNALERINGREISDOCUMENT` BOOLEAN,
    `VERBLIJFSTITEL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `INGEZETENE` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
    `AANDUIDINGEUROPEESKIESRECHT` BOOLEAN,
    `AANDUIDINGUITGESLOTENKIESRECHT` BOOLEAN,
    `DATUMVERKRIJGINGVERBLIJFSTITEL` DATE,
    `DATUMVERLIESVERBLIJFSTITEL` DATE,
    `INDICATIEBLOKKERING` VARCHAR(255),
    `INDICATIECURATELEREGISTER` VARCHAR(255),
    `INDICATIEGEZAGMINDERJARIGE` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY (`NATUURLIJKPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE `INGEZETENE` ADD CONSTRAINT FK_INGEZETENE_GEN_INGESCHREVENPERSOON FOREIGN KEY (`NATUURLIJKPERSOON_ID`) REFERENCES `INGESCHREVENPERSOON` (`NATUURLIJKPERSOON_ID`);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (`OUDER_1_INGESCHREVENPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- OUDER_1 (1 to 1, Connector_ID: 1871)

ALTER TABLE `INGESCHREVENPERSOON` ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (`OUDER_2_INGESCHREVENPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- OUDER_2 (1 to 1, Connector_ID: 1873)

