CREATE TABLE [INGESCHREVENPERSOON] (
    [NATUURLIJKPERSOON_ID] INT PRIMARY KEY,
    [ADRESHERKOMST] VARCHAR(255),
    [ANUMMER] VARCHAR(20),
    [BESCHRIJVINGLOCATIE] VARCHAR(200),
    [BUITENLANDSREISDOCUMENT] VARCHAR(80),
    [BURGERLIJKESTAAT] VARCHAR(255),
    [DATUMBEGINGELDIGHEIDVERBLIJFPLAATS] DATE,
    [DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS] DATE,
    [DATUMINSCHRIJVINGGEMEENTE] DATE,
    [DATUMOPSCHORTINGBIJHOUDING] DATE,
    [DATUMVERTREKUITNEDERLAND] DATE,
    [DATUMVESTIGINGNEDERLAND] DATE,
    [GEMEENTEVANINSCHRIJVING] VARCHAR(80),
    [GEZINSRELATIE] VARCHAR(255),
    [INDICATIEGEHEIM] BIT,
    [INGEZETENE] BIT,
    [LANDWAARNAARVERTROKKEN] VARCHAR(255),
    [LANDWAARVANDAANINGESCHREVEN] VARCHAR(255),
    [OUDER1] VARCHAR(255),
    [OUDER2] VARCHAR(255),
    [OUDER_1_NATUURLIJKPERSOON_ID] INT,
    [OUDER_2_NATUURLIJKPERSOON_ID] INT,
    [PARTNERID] VARCHAR(255),
    [REDENEINDEBEWONING] DATE,
    [REDENOPSCHORTINGBIJHOUDING] VARCHAR(200),
    [SIGNALERINGREISDOCUMENT] BIT,
    [VERBLIJFSTITEL] VARCHAR(255)
);

CREATE TABLE [NATUURLIJKPERSOON] (
    [NATUURLIJKPERSOON_ID] INT PRIMARY KEY,
    [AANDUIDINGNAAMGEBRUIK] VARCHAR(50),
    [AANHEFAANSCHRIJVING] VARCHAR(50),
    [ACADEMISCHETITEL] VARCHAR(80),
    [ACHTERNAAM] VARCHAR(100),
    [ADELLIJKETITELOFPREDIKAAT] VARCHAR(255),
    [ANUMMER] VARCHAR(20),
    [BIJZONDERNEDERLANDERSCHAP] VARCHAR(50),
    [BURGERSERVICENUMMER] VARCHAR(255),
    [DATUMGEBOORTE] DATE,
    [DATUMOVERLIJDEN] DATE,
    [GEBOORTELAND] VARCHAR(255),
    [GEBOORTEPLAATS] VARCHAR(200),
    [GESLACHTSAANDUIDING] VARCHAR(255),
    [GESLACHTSNAAM] VARCHAR(200),
    [GESLACHTSNAAMAANSCHRIJVING] VARCHAR(200),
    [HANDLICHTING] VARCHAR(50),
    [INDICATIEAFSCHERMINGPERSOONSGEGEVENS] BIT,
    [INDICATIEOVERLEDEN] BIT,
    [LANDOVERLIJDEN] VARCHAR(255),
    [NATIONALITEIT] VARCHAR(100),
    [OVERLIJDENSPLAATS] VARCHAR(200),
    [VOORLETTERSAANSCHRIJVING] VARCHAR(20),
    [VOORNAMEN] VARCHAR(200),
    [VOORNAMENAANSCHRIJVING] VARCHAR(200),
    [VOORVOEGSELGESLACHTSNAAM] VARCHAR(80)
);

CREATE TABLE [KP_INGSCHRVNPRSN_NTRLJKPRSN] (
    [KP_INGSCHRVNPRSN_NTRLJKPRSN_ID] INT PRIMARY KEY,
    [INGESCHREVENPERSOON_ID] INT,
    [NATUURLIJKPERSOON_ID] INT
);

CREATE TABLE [INGEZETENE] (
    [NATUURLIJKPERSOON_ID] INT PRIMARY KEY,
    [AANDUIDINGEUROPEESKIESRECHT] BIT,
    [AANDUIDINGUITGESLOTENKIESRECHT] BIT,
    [DATUMVERKRIJGINGVERBLIJFSTITEL] DATE,
    [DATUMVERLIESVERBLIJFSTITEL] DATE,
    [INDICATIEBLOKKERING] VARCHAR(255),
    [INDICATIECURATELEREGISTER] VARCHAR(255),
    [INDICATIEGEZAGMINDERJARIGE] VARCHAR(255)
);

CREATE TABLE [KP_INGZTN_INGSCHRVNPRSN] (
    [KP_INGZTN_INGSCHRVNPRSN_ID] INT PRIMARY KEY,
    [INGEZETENE_ID] INT,
    [INGESCHREVENPERSOON_ID] INT
);

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY ([NATUURLIJKPERSOON_ID]) REFERENCES [NATUURLIJKPERSOON] ([NATUURLIJKPERSOON_ID]);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE [INGEZETENE] ADD CONSTRAINT FK_INGEZETENE_GEN_INGESCHREVENPERSOON FOREIGN KEY ([NATUURLIJKPERSOON_ID]) REFERENCES [INGESCHREVENPERSOON] ([NATUURLIJKPERSOON_ID]);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE [KP_INGZTN_INGSCHRVNPRSN] ADD CONSTRAINT FK_KP_INGZTN_INGSCHRVNPRSN_1 FOREIGN KEY ([INGEZETENE_ID]) REFERENCES [INGEZETENE] ([NATUURLIJKPERSOON_ID]);
-- INGEZETENE (many-to-many junction, Connector_ID: 1867)

ALTER TABLE [KP_INGZTN_INGSCHRVNPRSN] ADD CONSTRAINT FK_KP_INGZTN_INGSCHRVNPRSN_2 FOREIGN KEY ([INGESCHREVENPERSOON_ID]) REFERENCES [INGESCHREVENPERSOON] ([NATUURLIJKPERSOON_ID]);
-- INGESCHREVENPERSOON (many-to-many junction, Connector_ID: 1867)

ALTER TABLE [KP_INGSCHRVNPRSN_NTRLJKPRSN] ADD CONSTRAINT FK_KP_INGSCHRVNPRSN_NTRLJKPRSN_1 FOREIGN KEY ([INGESCHREVENPERSOON_ID]) REFERENCES [INGESCHREVENPERSOON] ([NATUURLIJKPERSOON_ID]);
-- INGESCHREVENPERSOON (many-to-many junction, Connector_ID: 1878)

ALTER TABLE [KP_INGSCHRVNPRSN_NTRLJKPRSN] ADD CONSTRAINT FK_KP_INGSCHRVNPRSN_NTRLJKPRSN_2 FOREIGN KEY ([NATUURLIJKPERSOON_ID]) REFERENCES [NATUURLIJKPERSOON] ([NATUURLIJKPERSOON_ID]);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1878)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY ([OUDER_1_NATUURLIJKPERSOON_ID]) REFERENCES [NATUURLIJKPERSOON] ([NATUURLIJKPERSOON_ID]);
-- OUDER_1 (1 to 1, Connector_ID: 1871)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY ([OUDER_2_NATUURLIJKPERSOON_ID]) REFERENCES [NATUURLIJKPERSOON] ([NATUURLIJKPERSOON_ID]);
-- OUDER_2 (1 to 1, Connector_ID: 1873)

