CREATE TABLE GEO_OBJECT (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    GEOMETRIESOORT SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE OVERIGBOUWWERK (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDOVERIGBOUWWERK DATE,
    DATUMEINDEGELDIGHEIDOVERIGBOUWWERK DATE,
    GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    IDENTIFICATIEOVERIGBOUWWERK VARCHAR2(255),
    LOD0GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    LOD1GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    LOD2GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    LOD3GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGOVERIGBOUWWERK VARCHAR2(255),
    STATUSOVERIGBOUWWERK VARCHAR2(255)
);

CREATE TABLE BEGROEIDTERREINDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    FYSIEKVOORKOMEN VARCHAR2(255),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    KRUINLIJNGEOMETRIE SDO_GEOMETRY,
    LOD0GEOMETRIE SDO_GEOMETRY,
    OPTALUD NUMBER(1),
    PLUSFYSIEKVOORKOMEN VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUS VARCHAR2(255)
);

CREATE TABLE SCHEIDING (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDSCHEIDING DATE,
    DATUMEINDEGELDIGHEIDSCHEIDING DATE,
    GEOMETRIESCHEIDING SDO_GEOMETRY,
    IDENTIFICATIESCHEIDING VARCHAR2(255),
    LOD0GEOMETRIESCHEIDING SDO_GEOMETRY,
    LOD1GEOMETRIESCHEIDING SDO_GEOMETRY,
    LOD2GEOMETRIESCHEIDING SDO_GEOMETRY,
    LOD3GEOMETRIESCHEIDING SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGSCHEIDING VARCHAR2(255),
    STATUSSCHEIDING VARCHAR2(255)
);

CREATE TABLE ONBEGROEIDTERREINDEEL (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEID DATE,
    DATUMEINDEGELDIGHEID DATE,
    FYSIEKVOORKOMEN VARCHAR2(255),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(255),
    KRUINLIJNGEOMETRIE SDO_GEOMETRY,
    ONBEGROEIDTERREINDEELOPTALUD DATE,
    PLUSFYSIEKVOORKOMEN VARCHAR2(255),
    RELATIEVEHOOGTELIGGING VARCHAR2(255),
    STATUS VARCHAR2(255)
);

CREATE TABLE OVERIGESCHEIDING (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDOVERIGESCHEIDING DATE,
    DATUMEINDEGELDIGHEIDOVERIGESCHEIDING DATE,
    GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    IDENTIFICATIEOVERIGESCHEIDING VARCHAR2(255),
    LOD0GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    LOD1GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    LOD2GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    LOD3GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGOVERIGESCHEIDING VARCHAR2(255),
    STATUSOVERIGESCHEIDING VARCHAR2(255),
    TYPEOVERIGESCHEIDING VARCHAR2(255)
);

CREATE TABLE VEGETATIEOBJECT (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDVEGETATIEOBJECT DATE,
    DATUMEINDEGELDIGHEIDVEGETATIEOBJECT DATE,
    GEOMETRIEVEGETATIEOBJECT SDO_GEOMETRY,
    IDENTIFICATIEVEGETATIEOBJECT VARCHAR2(255),
    LOD0GEOMETRIEVEGETATIEOBJECT SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGVEGETATIEOBJECT VARCHAR2(255),
    STATUSVEGETATIEOBJECT VARCHAR2(255),
    TYPEVEGETATIEOBJECT VARCHAR2(255)
);

CREATE TABLE INRICHTINGSELEMENT (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDINRICHTINGSELEMENT DATE,
    DATUMEINDEGELDIGHEIDINRICHTINGSELEMENT DATE,
    GEOMETRIEINRICHTINGSELEMENT SDO_GEOMETRY,
    IDENTIFICATIEINRICHTINGSELEMENT VARCHAR2(255),
    LOD0GEOMETRIEINRICHTINGSELEMENT SDO_GEOMETRY,
    PLUSTYPEINRICHTINGSELEMENT VARCHAR2(255),
    RELATIEVEHOOGTELIGGINGINRICHTINGSELEMENT VARCHAR2(255),
    STATUSINRICHTINGSELEMENT VARCHAR2(255),
    TYPEINRICHTINGSELEMENT VARCHAR2(255)
);

CREATE TABLE FUNCTIONEELGEBIED (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDFUNCTIONEELGEBIED DATE,
    DATUMEINDEGELDIGHEIDFUNCTIONEELGEBIED DATE,
    GEOMETRIEFUNCTIONEELGEBIED SDO_GEOMETRY,
    IDENTIFICATIEFUNCTIONEELGEBIED VARCHAR2(255),
    NAAMFUNCTIONEELGEBIED VARCHAR2(255),
    STATUSFUNCTIONEELGEBIED VARCHAR2(255)
);

CREATE TABLE GEBOUWINSTALLATIE (
    GEO_OBJECT_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDGEBOUWINSTALLATIE DATE,
    DATUMEINDEGELDIGHEIDGEBOUWINSTALLATIE DATE,
    GEOMETRIEGEBOUWINSTALLATIE SDO_GEOMETRY,
    IDENTIFICATIEGEBOUWINSTALLATIE VARCHAR2(255),
    LOD0GEOMETRIEGEBOUWINSTALLATIE SDO_GEOMETRY,
    RELATIEVEHOOGTELIGGINGGEBOUWINSTALLATIE VARCHAR2(255),
    STATUSGEBOUWINSTALLATIE VARCHAR2(255),
    TYPEGEBOUWINSTALLATIE VARCHAR2(255)
);

ALTER TABLE OVERIGBOUWWERK ADD CONSTRAINT FK_OVERIGBOUWWERK_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE INRICHTINGSELEMENT ADD CONSTRAINT FK_INRICHTINGSELEMENT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE GEBOUWINSTALLATIE ADD CONSTRAINT FK_GEBOUWINSTALLATIE_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE VEGETATIEOBJECT ADD CONSTRAINT FK_VEGETATIEOBJECT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE SCHEIDING ADD CONSTRAINT FK_SCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE FUNCTIONEELGEBIED ADD CONSTRAINT FK_FUNCTIONEELGEBIED_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONBEGROEIDTERREINDEEL ADD CONSTRAINT FK_ONBEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE BEGROEIDTERREINDEEL ADD CONSTRAINT FK_BEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGESCHEIDING ADD CONSTRAINT FK_OVERIGESCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

