CREATE TABLE [TENAAMSTELLING] (
    [TENAAMSTELLING_ID] INT PRIMARY KEY,
    [AANDEELINRECHT] VARCHAR(255),
    [BURGERLIJKESTAATTENTIJDEVANVERKRIJGING] DATETIME2,
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [EXPLOITANTCODE] VARCHAR(255),
    [IDENTIFICATIETENAAMSTELLING] VARCHAR(255),
    [VERKLARINGINZAKEDERDENBESCHERMING] VARCHAR(100),
    [VERKREGENNAMENSSAMENWERKINGSVERBAND] VARCHAR(255)
);

CREATE TABLE [AANTEKENING] (
    [AANTEKENING_ID] INT PRIMARY KEY,
    [AARD] VARCHAR(100),
    [BEGRENZING] VARCHAR(255),
    [BETREFTGEDEELTEVANPERCEEL] BIT,
    [DATUMEINDE] DATE,
    [DATUMEINDERECHT] DATE,
    [IDENTIFICATIE] VARCHAR(100),
    [OMSCHRIJVING] VARCHAR(200),
    [TENAAMSTELLING_ID] INT
);

ALTER TABLE [AANTEKENING] ADD CONSTRAINT FK_AANTEKENING_TENAAMSTELLING FOREIGN KEY ([TENAAMSTELLING_ID]) REFERENCES [TENAAMSTELLING] ([TENAAMSTELLING_ID]);
-- unnamed (1 to 0..*, Connector_ID: 1981)

