CREATE TABLE STATUSTYPE (
    STATUSTYPE_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDSTATUSTYPE DATE,
    DATUMEINDEGELDIGHEIDSTATUSTYPE DATE,
    DOORLOOPTIJDSTATUS TIMESTAMP,
    STATUSTYPEOMSCHRIJVING VARCHAR2(80),
    STATUSTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80),
    STATUSTYPEVOLGNUMMER VARCHAR2(255)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    ACHTERNAAM VARCHAR2(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR2(255),
    EXTERN NUMBER(1),
    FUNCTIE VARCHAR2(50),
    GESLACHTSAANDUIDING VARCHAR2(255),
    IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID NUMBER,
    IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID NUMBER,
    IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID NUMBER,
    MEDEWERKERIDENTIFICATIE VARCHAR2(255),
    MEDEWERKERTOELICHTING VARCHAR2(255),
    ROEPNAAM VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    VOORLETTERS VARCHAR2(20),
    VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE KP_BTRKKN_ZK (
    KP_BTRKKN_ZK_ID NUMBER PRIMARY KEY,
    BETROKKENE_ID NUMBER,
    ZAAK_ID NUMBER
);

CREATE TABLE ZAAK (
    ZAAK_ID NUMBER PRIMARY KEY,
    ARCHIEFNOMINATIE VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMEINDEGEPLAND DATE,
    DATUMEINDEUITERLIJKEAFDOENING DATE,
    DATUMLAATSTEBETALING DATE,
    DATUMPUBLICATIE DATE,
    DATUMREGISTRATIE DATE,
    DATUMSTART DATE,
    DATUMVERNIETIGINGDOSSIER DATE,
    DUURVERLENGING VARCHAR2(255),
    HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID NUMBER,
    HEEFT_STATUS_ID NUMBER,
    INDICATIEBETALING VARCHAR2(255),
    INDICATIEDEELZAKEN NUMBER(1),
    INDICATIEOPSCHORTING VARCHAR2(255),
    IS_DEELZAAK_VAN_ZAAK_ID NUMBER,
    IS_VAN_ZAAKTYPE_ID NUMBER,
    LEGES VARCHAR2(100),
    OMSCHRIJVING VARCHAR2(80),
    OMSCHRIJVINGRESULTAAT VARCHAR2(80),
    REDENOPSCHORTING VARCHAR2(200),
    REDENVERLENGING VARCHAR2(200),
    TOELICHTING VARCHAR2(255),
    TOELICHTINGRESULTAAT VARCHAR2(255),
    VERTROUWELIJKHEID VARCHAR2(255),
    ZAAKIDENTIFICATIE VARCHAR2(255),
    ZAAKNIVEAU VARCHAR2(255)
);

CREATE TABLE BESLUITTYPE (
    BESLUITTYPE_ID NUMBER PRIMARY KEY,
    BESLUITCATEGORIE VARCHAR2(255),
    BESLUITTYPEOMSCHRIJVING VARCHAR2(80),
    BESLUITTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80),
    DATUMBEGINGELDIGHEIDBESLUITTYPE DATE,
    DATUMEINDEGELDIGHEIDBESLUITTYPE DATE,
    INDICATIEPUBLICATIE VARCHAR2(255),
    PUBLICATIETEKST VARCHAR2(255),
    PUBLICATIETERMIJN VARCHAR2(255),
    REACTIETERMIJN VARCHAR2(255)
);

CREATE TABLE DOCUMENTTYPE (
    DOCUMENTTYPE_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDDOCUMENTTYPE DATE,
    DATUMEINDEGELDIGHEIDDOCUMENTTYPE DATE,
    DOCUMENTCATEGORIE VARCHAR2(80),
    DOCUMENTTYPEOMSCHRIJVING VARCHAR2(80),
    DOCUMENTTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80),
    DOCUMENTTYPETREFWOORD VARCHAR2(255)
);

CREATE TABLE KP_MDWRKR_ORGNSTRSCHNHD (
    KP_MDWRKR_ORGNSTRSCHNHD_ID NUMBER PRIMARY KEY,
    MEDEWERKER_ID NUMBER,
    ORGANISATORISCHEEENHEID_ID NUMBER
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR2(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR2(200),
    DOCUMENTIDENTIFICATIE VARCHAR2(255),
    DOCUMENTTITEL VARCHAR2(200),
    IS_VAN_DOCUMENTTYPE_ID NUMBER,
    VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

CREATE TABLE BETROKKENE (
    BETROKKENE_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(200),
    IDENTIFICATIE VARCHAR2(50),
    IS_MEDEWERKER_ID NUMBER,
    IS_ORGANISATORISCHEEENHEID_ID NUMBER,
    NAAM VARCHAR2(200)
);

CREATE TABLE KP_ZK_DCMNT (
    KP_ZK_DCMNT_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    DOCUMENT_ID NUMBER
);

CREATE TABLE ENKELVOUDIGDOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    BESTANDSNAAM VARCHAR2(255),
    DOCUMENTFORMAAT VARCHAR2(255),
    DOCUMENTINHOUD VARCHAR2(255),
    DOCUMENTLINK VARCHAR2(200),
    DOCUMENTSTATUS VARCHAR2(20),
    DOCUMENTTAAL VARCHAR2(20),
    DOCUMENTVERSIE VARCHAR2(255)
);

CREATE TABLE OBJECT (
    OBJECT_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(200),
    BETREFT_ZAAK_ID NUMBER,
    DOMEIN VARCHAR2(200),
    GEOMETRIE SDO_GEOMETRY,
    IDENTIFICATIE VARCHAR2(50),
    INDICATIERISICO NUMBER(1),
    IS_BESLUIT_ID NUMBER,
    KADASTRALEAANDUIDING VARCHAR2(255),
    NAAM VARCHAR2(200),
    OBJECTTYPE VARCHAR2(255),
    TOELICHTING VARCHAR2(255)
);

CREATE TABLE SAMENGESTELDDOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    OMVAT_ENKELVOUDIGDOCUMENT_ID NUMBER
);

CREATE TABLE ZAAKTYPE (
    ZAAKTYPE_ID NUMBER PRIMARY KEY,
    ARCHIEFCODE VARCHAR2(20),
    DATUMBEGINGELDIGHEIDZAAKTYPE DATE,
    DATUMEINDEGELDIGHEIDZAAKTYPE DATE,
    DOORLOOPTIJDBEHANDELING TIMESTAMP,
    HEEFT_STATUSTYPE_ID NUMBER,
    INDICATIEPUBLICATIE VARCHAR2(255),
    PUBLICATIETEKST VARCHAR2(255),
    SERVICENORMBEHANDELING VARCHAR2(255),
    TREFWOORD VARCHAR2(255),
    VERTROUWELIJKAANDUIDING VARCHAR2(20),
    ZAAKCATEGORIE VARCHAR2(255),
    ZAAKTYPEOMSCHRIJVING VARCHAR2(80),
    ZAAKTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80)
);

CREATE TABLE KP_BSLT_DCMNT (
    KP_BSLT_DCMNT_ID NUMBER PRIMARY KEY,
    BESLUIT_ID NUMBER,
    DOCUMENT_ID NUMBER
);

CREATE TABLE ORGANISATORISCHEEENHEID (
    ORGANISATORISCHEEENHEID_ID NUMBER PRIMARY KEY,
    DATUMONTSTAAN DATE,
    DATUMOPHEFFING DATE,
    EMAILADRES VARCHAR2(255),
    FAXNUMMER VARCHAR2(20),
    FORMATIE VARCHAR2(255),
    IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID NUMBER,
    IS_GEHUISVEST_IN_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID NUMBER,
    IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID NUMBER,
    NAAM VARCHAR2(50),
    NAAMVERKORT VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(80),
    ORGANISATIEIDENTIFICATIE VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    TOELICHTING VARCHAR2(255)
);

CREATE TABLE BESLUIT (
    BESLUIT_ID NUMBER PRIMARY KEY,
    BESLUITIDENTIFICATIE VARCHAR2(50),
    BESLUITTOELICHTING VARCHAR2(255),
    DATUMBESLUIT DATE,
    DATUMPUBLICATIE DATE,
    DATUMSTART DATE,
    DATUMUITERLIJKEREACTIE DATE,
    DATUMVERVAL DATE,
    DATUMVERZENDING DATE,
    IS_UITKOMST_VAN_ZAAK_ID NUMBER,
    IS_VAN_BESLUITTYPE_ID NUMBER,
    IS_VASTGELEGD_IN_DOCUMENT_ID NUMBER,
    OMSCHRIJVING VARCHAR2(200),
    REDENVERVAL VARCHAR2(255)
);

CREATE TABLE KP_ZK_MDWRKR (
    KP_ZK_MDWRKR_ID NUMBER PRIMARY KEY,
    ZAAK_ID NUMBER,
    MEDEWERKER_ID NUMBER
);

CREATE TABLE STATUS (
    STATUS_ID NUMBER PRIMARY KEY,
    DATUMSTATUSGEZET DATE,
    INDICATIEIAATSTGEZETTESTATUS VARCHAR2(255),
    IS_VAN_STATUSTYPE_ID NUMBER,
    STATUSTOELICHTING VARCHAR2(255)
);

CREATE TABLE VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (
    VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID NUMBER PRIMARY KEY
);

ALTER TABLE SAMENGESTELDDOCUMENT ADD CONSTRAINT FK_SAMENGESTELDDOCUMENT_GEN_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- Generalization to DOCUMENT

ALTER TABLE ENKELVOUDIGDOCUMENT ADD CONSTRAINT FK_ENKELVOUDIGDOCUMENT_GEN_DOCUMENT FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- Generalization to DOCUMENT

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_ZK_DCMNT ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE KP_BSLT_DCMNT ADD CONSTRAINT FK_KP_BSLT_DCMNT_1 FOREIGN KEY (BESLUIT_ID) REFERENCES BESLUIT (BESLUIT_ID);
-- BESLUIT (many-to-many junction, Connector_ID: 2150)

ALTER TABLE KP_BSLT_DCMNT ADD CONSTRAINT FK_KP_BSLT_DCMNT_2 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- DOCUMENT (many-to-many junction, Connector_ID: 2150)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_1 FOREIGN KEY (BETROKKENE_ID) REFERENCES BETROKKENE (BETROKKENE_ID);
-- BETROKKENE (many-to-many junction, Connector_ID: 2164)

ALTER TABLE KP_BTRKKN_ZK ADD CONSTRAINT FK_KP_BTRKKN_ZK_2 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2164)

ALTER TABLE KP_MDWRKR_ORGNSTRSCHNHD ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_1 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2175)

ALTER TABLE KP_MDWRKR_ORGNSTRSCHNHD ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_2 FOREIGN KEY (ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- ORGANISATORISCHEEENHEID (many-to-many junction, Connector_ID: 2175)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY (ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE KP_ZK_MDWRKR ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_DEEL_VAN FOREIGN KEY (IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_DEEL_VAN (1 to 0..1, Connector_ID: 2059)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_GEHUISVEST_IN FOREIGN KEY (IS_GEHUISVEST_IN_VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID) REFERENCES VESTIGINGVANZAAKBEHANDELENDEORGANISATIE (VESTIGINGVANZAAKBEHANDELENDEORGANISATIE_ID);
-- IS_GEHUISVEST_IN (1..* to 1, Connector_ID: 2062)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_VAN FOREIGN KEY (IS_VAN_BESLUITTYPE_ID) REFERENCES BESLUITTYPE (BESLUITTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2066)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_IS FOREIGN KEY (IS_BESLUIT_ID) REFERENCES BESLUIT (BESLUIT_ID);
-- IS (0..1 to 1.., Connector_ID: 2071)

ALTER TABLE STATUS ADD CONSTRAINT FK_STATUS_IS_VAN FOREIGN KEY (IS_VAN_STATUSTYPE_ID) REFERENCES STATUSTYPE (STATUSTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2090)

ALTER TABLE ZAAKTYPE ADD CONSTRAINT FK_ZAAKTYPE_HEEFT FOREIGN KEY (HEEFT_STATUSTYPE_ID) REFERENCES STATUSTYPE (STATUSTYPE_ID);
-- HEEFT (1 to 1..*, Connector_ID: 2093)

ALTER TABLE ORGANISATORISCHEEENHEID ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY (IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2095)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT FOREIGN KEY (HEEFT_STATUS_ID) REFERENCES STATUS (STATUS_ID);
-- HEEFT (1 to 0..*, Connector_ID: 2101)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY (HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_UITKOMST_VAN FOREIGN KEY (IS_UITKOMST_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_UITKOMST_VAN (0..* to 1, Connector_ID: 2112)

ALTER TABLE OBJECT ADD CONSTRAINT FK_OBJECT_BETREFT FOREIGN KEY (BETREFT_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- BETREFT (0..1 to 1, Connector_ID: 2117)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_VAN FOREIGN KEY (IS_VAN_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2119)

ALTER TABLE ZAAK ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY (IS_DEELZAAK_VAN_ZAAK_ID) REFERENCES ZAAK (ZAAK_ID);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_IS_VAN FOREIGN KEY (IS_VAN_DOCUMENTTYPE_ID) REFERENCES DOCUMENTTYPE (DOCUMENTTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2127)

ALTER TABLE BESLUIT ADD CONSTRAINT FK_BESLUIT_IS_VASTGELEGD_IN FOREIGN KEY (IS_VASTGELEGD_IN_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- IS_VASTGELEGD_IN (0..1 to 0..1, Connector_ID: 2149)

ALTER TABLE SAMENGESTELDDOCUMENT ADD CONSTRAINT FK_SAMENGESTELDDOCUMENT_OMVAT FOREIGN KEY (OMVAT_ENKELVOUDIGDOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- OMVAT (0..1 to 2..*, Connector_ID: 2155)

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_IS FOREIGN KEY (IS_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS (0..1 to 1, Connector_ID: 2161)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJK_VOOR FOREIGN KEY (IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_VERANTWOORDELIJK_VOOR (0..1 to 0..1, Connector_ID: 2166)

ALTER TABLE BETROKKENE ADD CONSTRAINT FK_BETROKKENE_IS_2 FOREIGN KEY (IS_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- IS (0..1 to 1, Connector_ID: 2167)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJKE_VOOR FOREIGN KEY (IS_VERANTWOORDELIJKE_VOOR_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- IS_VERANTWOORDELIJKE_VOOR (0..1 to 0..*, Connector_ID: 2170)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_IS_CONTACTPERSOON_VOOR FOREIGN KEY (IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID) REFERENCES ORGANISATORISCHEEENHEID (ORGANISATORISCHEEENHEID_ID);
-- IS_CONTACTPERSOON_VOOR (0..1 to 0..1, Connector_ID: 2185)

