CREATE TABLE BEGROTINGREGEL (
    BEGROTINGREGEL_ID INTEGER PRIMARY KEY,
    BATENLASTEN VARCHAR(20),
    BEDRAG DECIMAL(10,2),
    BETREFT_DOELSTELLING_ID INTEGER,
    BETREFT_HOOFDREKENING_ID INTEGER,
    BETREFT_HOOFDSTUK_ID INTEGER,
    BETREFT_KOSTENPLAATS_ID INTEGER,
    BETREFT_PRODUCT_ID INTEGER,
    SOORTREGEL VARCHAR(50)
);

CREATE TABLE OPDRACHTGEVER (
    OPDRACHTGEVER_ID INTEGER PRIMARY KEY,
    CLUSTERCODE VARCHAR(20),
    CLUSTEROMSCHRIJVING VARCHAR(80),
    IS_OPDRACHTGEVER_PRODUCT_ID INTEGER,
    NAAM VARCHAR(80),
    NUMMER VARCHAR(20),
    OMSCHRIJVING TEXT
);

CREATE TABLE KP_KSTNPLTS_TKVLD (
    KP_KSTNPLTS_TKVLD_ID INTEGER PRIMARY KEY,
    KOSTENPLAATS_ID INTEGER,
    TAAKVELD_ID INTEGER
);

CREATE TABLE PERIODE (
    PERIODE_ID INTEGER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    OMSCHRIJVING VARCHAR(255)
);

CREATE TABLE KP_HFDSTK_PRD (
    KP_HFDSTK_PRD_ID INTEGER PRIMARY KEY,
    HOOFDSTUK_ID INTEGER,
    PERIODE_ID INTEGER
);

CREATE TABLE DOELSTELLING (
    DOELSTELLING_ID INTEGER PRIMARY KEY,
    HEEFT_PRODUCT_ID INTEGER,
    IS_OPDRACHTGEVER_OPDRACHTGEVER_ID INTEGER,
    NAAM VARCHAR(80),
    NUMMER VARCHAR(20),
    OMSCHRIJVING TEXT
);

CREATE TABLE HOOFDREKENING (
    HOOFDREKENING_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    NUMMER VARCHAR(255),
    OMSCHRIJVING VARCHAR(200),
    PIAHOOFCATEGORIEOMSCHRIJVING VARCHAR(80),
    PIAHOOFDCATEGORIECODE VARCHAR(20),
    SUBCODE VARCHAR(20),
    SUBCODEOMSCHRIJVING VARCHAR(80),
    VALT_BINNEN_HOOFDREKENING_ID INTEGER
);

CREATE TABLE KP_BGRTNG_PRD (
    KP_BGRTNG_PRD_ID INTEGER PRIMARY KEY,
    BEGROTING_ID INTEGER,
    PERIODE_ID INTEGER
);

CREATE TABLE HOOFDSTUK (
    HOOFDSTUK_ID INTEGER PRIMARY KEY,
    HEEFT_DOELSTELLING_ID INTEGER,
    NAAM VARCHAR(80),
    NUMMER VARCHAR(20),
    OMSCHRIJVING TEXT
);

CREATE TABLE KP_HFDRKNNG_KSTNPLTS (
    KP_HFDRKNNG_KSTNPLTS_ID INTEGER PRIMARY KEY,
    HOOFDREKENING_ID INTEGER,
    KOSTENPLAATS_ID INTEGER
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID INTEGER PRIMARY KEY,
    BTWCODE VARCHAR(255),
    BTWOMSCHRIJVING VARCHAR(80),
    IS_BUDGETVERANTWOORDELIJK_OPDRACHTNEMER_ID INTEGER,
    KOSTENPLAATSSOORTCODE DECIMAL(10,2),
    KOSTENPLAATSSOORTOMSCHRIJVING DECIMAL(10,2),
    KOSTENPLAATSTYPECODE DECIMAL(10,2),
    KOSTENPLAATSTYPEOMSCHRIJVING DECIMAL(10,2),
    NAAM VARCHAR(80),
    OMSCHRIJVING VARCHAR(200)
);

CREATE TABLE OPDRACHTNEMER (
    OPDRACHTNEMER_ID INTEGER PRIMARY KEY,
    CLUSTERCODE VARCHAR(20),
    CLUSTERCODEOMSCHRIJVING VARCHAR(80),
    IS_OPDRACHTNEMER_PRODUCT_ID INTEGER,
    NAAM VARCHAR(80),
    NUMMER VARCHAR(20),
    OMSCHRIJVING VARCHAR(80)
);

CREATE TABLE TAAKVELD (
    TAAKVELD_ID INTEGER PRIMARY KEY,
    FUNCTIECODEIV3 VARCHAR(20),
    FUNCTIEOMSCHRIJVINGIV3 VARCHAR(80),
    HOOFDFUNCTIE VARCHAR(50),
    HOOFDFUNCTIEOMSCHRIJVING VARCHAR(100),
    SUBTAAKVELDCODE VARCHAR(20),
    SUBTAAKVELDOMSCHRIJVING VARCHAR(80),
    TAAKVELDCODE VARCHAR(20),
    TAAKVELDOMSCHRIJVING VARCHAR(100)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INTEGER PRIMARY KEY,
    HEEFT_KOSTENPLAATS_ID INTEGER,
    NAAM VARCHAR(80),
    NUMMER VARCHAR(20),
    OMSCHRIJVING TEXT
);

CREATE TABLE BEGROTING (
    BEGROTING_ID INTEGER PRIMARY KEY,
    HEEFT_BEGROTINGREGEL_ID INTEGER,
    NAAM VARCHAR(80),
    NUMMER VARCHAR(20),
    OMSCHRIJVING TEXT
);

ALTER TABLE KP_KSTNPLTS_TKVLD ADD CONSTRAINT FK_KP_KSTNPLTS_TKVLD_1 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 486)

ALTER TABLE KP_KSTNPLTS_TKVLD ADD CONSTRAINT FK_KP_KSTNPLTS_TKVLD_2 FOREIGN KEY (TAAKVELD_ID) REFERENCES TAAKVELD (TAAKVELD_ID);
-- TAAKVELD (many-to-many junction, Connector_ID: 486)

ALTER TABLE KP_HFDSTK_PRD ADD CONSTRAINT FK_KP_HFDSTK_PRD_1 FOREIGN KEY (HOOFDSTUK_ID) REFERENCES HOOFDSTUK (HOOFDSTUK_ID);
-- HOOFDSTUK (many-to-many junction, Connector_ID: 498)

ALTER TABLE KP_HFDSTK_PRD ADD CONSTRAINT FK_KP_HFDSTK_PRD_2 FOREIGN KEY (PERIODE_ID) REFERENCES PERIODE (PERIODE_ID);
-- PERIODE (many-to-many junction, Connector_ID: 498)

ALTER TABLE KP_HFDRKNNG_KSTNPLTS ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_1 FOREIGN KEY (HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- HOOFDREKENING (many-to-many junction, Connector_ID: 505)

ALTER TABLE KP_HFDRKNNG_KSTNPLTS ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_2 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 505)

ALTER TABLE KP_BGRTNG_PRD ADD CONSTRAINT FK_KP_BGRTNG_PRD_1 FOREIGN KEY (BEGROTING_ID) REFERENCES BEGROTING (BEGROTING_ID);
-- BEGROTING (many-to-many junction, Connector_ID: 521)

ALTER TABLE KP_BGRTNG_PRD ADD CONSTRAINT FK_KP_BGRTNG_PRD_2 FOREIGN KEY (PERIODE_ID) REFERENCES PERIODE (PERIODE_ID);
-- PERIODE (many-to-many junction, Connector_ID: 521)

ALTER TABLE OPDRACHTNEMER ADD CONSTRAINT FK_OPDRACHTNEMER_IS_OPDRACHTNEMER FOREIGN KEY (IS_OPDRACHTNEMER_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- IS_OPDRACHTNEMER (0..1 to 0..*, Connector_ID: 478)

ALTER TABLE OPDRACHTGEVER ADD CONSTRAINT FK_OPDRACHTGEVER_IS_OPDRACHTGEVER FOREIGN KEY (IS_OPDRACHTGEVER_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- IS_OPDRACHTGEVER (0..1 to 0..*, Connector_ID: 480)

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..* to 1, Connector_ID: 482)

ALTER TABLE KOSTENPLAATS ADD CONSTRAINT FK_KOSTENPLAATS_IS_BUDGETVERANTWOORDELIJK FOREIGN KEY (IS_BUDGETVERANTWOORDELIJK_OPDRACHTNEMER_ID) REFERENCES OPDRACHTNEMER (OPDRACHTNEMER_ID);
-- IS_BUDGETVERANTWOORDELIJK (1..* to 1, Connector_ID: 487)

ALTER TABLE HOOFDREKENING ADD CONSTRAINT FK_HOOFDREKENING_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 504)

ALTER TABLE HOOFDSTUK ADD CONSTRAINT FK_HOOFDSTUK_HEEFT FOREIGN KEY (HEEFT_DOELSTELLING_ID) REFERENCES DOELSTELLING (DOELSTELLING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 511)

ALTER TABLE DOELSTELLING ADD CONSTRAINT FK_DOELSTELLING_IS_OPDRACHTGEVER FOREIGN KEY (IS_OPDRACHTGEVER_OPDRACHTGEVER_ID) REFERENCES OPDRACHTGEVER (OPDRACHTGEVER_ID);
-- IS_OPDRACHTGEVER (1..* to 1, Connector_ID: 512)

ALTER TABLE DOELSTELLING ADD CONSTRAINT FK_DOELSTELLING_HEEFT FOREIGN KEY (HEEFT_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 513)

ALTER TABLE BEGROTINGREGEL ADD CONSTRAINT FK_BEGROTINGREGEL_BETREFT FOREIGN KEY (BETREFT_HOOFDSTUK_ID) REFERENCES HOOFDSTUK (HOOFDSTUK_ID);
-- BETREFT (0..* to 1, Connector_ID: 516)

ALTER TABLE BEGROTINGREGEL ADD CONSTRAINT FK_BEGROTINGREGEL_BETREFT_2 FOREIGN KEY (BETREFT_HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 517)

ALTER TABLE BEGROTINGREGEL ADD CONSTRAINT FK_BEGROTINGREGEL_BETREFT_3 FOREIGN KEY (BETREFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 518)

ALTER TABLE BEGROTINGREGEL ADD CONSTRAINT FK_BEGROTINGREGEL_BETREFT_4 FOREIGN KEY (BETREFT_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 519)

ALTER TABLE BEGROTINGREGEL ADD CONSTRAINT FK_BEGROTINGREGEL_BETREFT_5 FOREIGN KEY (BETREFT_DOELSTELLING_ID) REFERENCES DOELSTELLING (DOELSTELLING_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 520)

ALTER TABLE BEGROTING ADD CONSTRAINT FK_BEGROTING_HEEFT FOREIGN KEY (HEEFT_BEGROTINGREGEL_ID) REFERENCES BEGROTINGREGEL (BEGROTINGREGEL_ID);
-- HEEFT (1 to 0..*, Connector_ID: 522)

