CREATE TABLE FUNCTIE (
    FUNCTIE_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(50),
    NAAM VARCHAR2(80),
    OMSCHRIJVING CLOB,
    SCHAAL VARCHAR2(20),
    TAKEN CLOB
);

CREATE TABLE OPDRACHTNEMER (
    OPDRACHTNEMER_ID NUMBER PRIMARY KEY,
    CLUSTERCODE VARCHAR2(20),
    CLUSTERCODEOMSCHRIJVING VARCHAR2(80),
    NAAM VARCHAR2(80),
    NUMMER VARCHAR2(20),
    OMSCHRIJVING VARCHAR2(80),
    UITGEVOERD_DOOR_FUNCTIE_ID NUMBER
);

CREATE TABLE OPDRACHTGEVER (
    OPDRACHTGEVER_ID NUMBER PRIMARY KEY,
    CLUSTERCODE VARCHAR2(20),
    CLUSTEROMSCHRIJVING VARCHAR2(80),
    NAAM VARCHAR2(80),
    NUMMER VARCHAR2(20),
    OMSCHRIJVING CLOB,
    UITGEVOERD_DOOR_FUNCTIE_ID NUMBER
);

ALTER TABLE OPDRACHTNEMER ADD CONSTRAINT FK_OPDRACHTNEMER_UITGEVOERD_DOOR FOREIGN KEY (UITGEVOERD_DOOR_FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- UITGEVOERD_DOOR (0..* to 1, Connector_ID: 477)

ALTER TABLE OPDRACHTGEVER ADD CONSTRAINT FK_OPDRACHTGEVER_UITGEVOERD_DOOR FOREIGN KEY (UITGEVOERD_DOOR_FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- UITGEVOERD_DOOR (0..* to 1, Connector_ID: 479)

