CREATE TABLE [APPLICATIE] (
    [APPLICATIE_ID] INT PRIMARY KEY,
    [APPLICATIEURL] VARCHAR(255),
    [BEHEERSTATUS] INT,
    [BELEIDSDOMEIN] VARCHAR(255),
    [CATEGORIE] VARCHAR(255),
    [GUID] VARCHAR(255),
    [HEEFT_HERKOMST_BATCH_ID] INT,
    [NAAM] VARCHAR(255),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [PACKAGINGSTATUS] INT
);

CREATE TABLE [WERKORDER] (
    [WERKORDER_ID] INT PRIMARY KEY,
    [CODE] VARCHAR(20),
    [DOCUMENTNUMMER] INT,
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [WERKORDERTYPE] VARCHAR(80)
);

CREATE TABLE [HOOFDREKENING] (
    [HOOFDREKENING_ID] INT PRIMARY KEY,
    [HEEFT_SUBREKENING_ID] INT,
    [HEEFT_WERKORDER_ID] INT,
    [NAAM] VARCHAR(80),
    [NUMMER] VARCHAR(255),
    [OMSCHRIJVING] VARCHAR(200),
    [PIAHOOFCATEGORIEOMSCHRIJVING] VARCHAR(80),
    [PIAHOOFDCATEGORIECODE] VARCHAR(20),
    [SUBCODE] VARCHAR(20),
    [SUBCODEOMSCHRIJVING] VARCHAR(80),
    [VALT_BINNEN_HOOFDREKENING_ID] INT
);

CREATE TABLE [KOSTENPLAATS] (
    [KOSTENPLAATS_ID] INT PRIMARY KEY,
    [BTWCODE] VARCHAR(255),
    [BTWOMSCHRIJVING] VARCHAR(80),
    [HEEFT_SUBREKENING_ID] INT,
    [HEEFT_WERKORDER_ID] INT,
    [KOSTENPLAATSSOORTCODE] DECIMAL(10,2),
    [KOSTENPLAATSSOORTOMSCHRIJVING] DECIMAL(10,2),
    [KOSTENPLAATSTYPECODE] DECIMAL(10,2),
    [KOSTENPLAATSTYPEOMSCHRIJVING] DECIMAL(10,2),
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] VARCHAR(200)
);

CREATE TABLE [KP_HFDRKNNG_KSTNPLTS] (
    [KP_HFDRKNNG_KSTNPLTS_ID] INT PRIMARY KEY,
    [HOOFDREKENING_ID] INT,
    [KOSTENPLAATS_ID] INT
);

CREATE TABLE [BANKAFSCHRIFT] (
    [BANKAFSCHRIFT_ID] INT PRIMARY KEY,
    [DATUM] DATE,
    [HEEFT_BANKAFSCHRIFTREGEL_ID] INT,
    [NUMMER] VARCHAR(255)
);

CREATE TABLE [MUTATIE] (
    [MUTATIE_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [DATUM] DATE,
    [HEEFT_BETREKKING_OP_KOSTENPLAATS_ID] INT,
    [NAAR_HOOFDREKENING_ID] INT,
    [VAN_HOOFDREKENING_ID] INT
);

CREATE TABLE [BETALING] (
    [BETALING_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [DATUMTIJD] DATETIME2,
    [KOMT_VOOR_OP_BANKAFSCHRIFTREGEL_ID] INT,
    [OMSCHRIJVING] VARCHAR(200),
    [VALUTA] VARCHAR(255)
);

CREATE TABLE [EXTERNEBRON] (
    [EXTERNEBRON_ID] INT PRIMARY KEY
);

CREATE TABLE [FACTUURREGEL] (
    [FACTUURREGEL_ID] INT PRIMARY KEY,
    [AANTAL] VARCHAR(255),
    [BEDRAGBTW] DECIMAL(10,2),
    [BEDRAGEXBTW] DECIMAL(10,2),
    [BTWPERCENTAGE] VARCHAR(255),
    [LEIDT_TOT_MUTATIE_ID] INT,
    [NUMMER] VARCHAR(255),
    [OMSCHRIJVING] VARCHAR(80)
);

CREATE TABLE [FACTUUR] (
    [FACTUUR_ID] INT PRIMARY KEY,
    [BETAALBAARPER] DATE,
    [BETAALTERMIJN] VARCHAR(255),
    [CODE] VARCHAR(255),
    [DATUMFACTUUR] DATE,
    [FACTUURBEDRAGBTW] DECIMAL(10,2),
    [FACTUURBEDRAGEXCLUSIEFBTW] DECIMAL(10,2),
    [HEEFT_FACTUURREGEL_ID] INT,
    [OMSCHRIJVING] VARCHAR(200),
    [SCHRIJFT_OP_KOSTENPLAATS_ID] INT
);

CREATE TABLE [BATCH] (
    [BATCH_ID] INT PRIMARY KEY,
    [DATUM] DATE,
    [HEEFT_BATCHREGEL_ID] INT,
    [HEEFT_HERKOMST_EXTERNEBRON_ID] INT,
    [NUMMER] VARCHAR(255),
    [TIJD] DATETIME2
);

CREATE TABLE [BATCHREGEL] (
    [BATCHREGEL_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [DATUMBETALING] DATE,
    [LEIDT_TOT_MUTATIE_ID] INT,
    [OMSCHRIJVING] VARCHAR(200),
    [REKENINGNAAR] VARCHAR(255),
    [REKENINGVAN] VARCHAR(255)
);

CREATE TABLE [SUBREKENING] (
    [SUBREKENING_ID] INT PRIMARY KEY,
    [NAAM] VARCHAR(80),
    [NUMMER] VARCHAR(20),
    [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [BANKAFSCHRIFTREGEL] (
    [BANKAFSCHRIFTREGEL_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [BIJ] BIT,
    [DATUM] DATE,
    [LEIDT_TOT_MUTATIE_ID] INT,
    [REKENINGVAN] VARCHAR(255)
);

CREATE TABLE [BANKREKENING] (
    [BANKREKENING_ID] INT PRIMARY KEY,
    [BANK] VARCHAR(80),
    [HEEFT_BANKAFSCHRIFT_ID] INT,
    [NAAR_BETALING_ID] INT,
    [NUMMER] VARCHAR(255),
    [TENNAAMSTELLING] VARCHAR(80),
    [VAN_BETALING_ID] INT
);

ALTER TABLE [KP_HFDRKNNG_KSTNPLTS] ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_1 FOREIGN KEY ([HOOFDREKENING_ID]) REFERENCES [HOOFDREKENING] ([HOOFDREKENING_ID]);
-- HOOFDREKENING (many-to-many junction, Connector_ID: 505)

ALTER TABLE [KP_HFDRKNNG_KSTNPLTS] ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_2 FOREIGN KEY ([KOSTENPLAATS_ID]) REFERENCES [KOSTENPLAATS] ([KOSTENPLAATS_ID]);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 505)

ALTER TABLE [MUTATIE] ADD CONSTRAINT FK_MUTATIE_HEEFT_BETREKKING_OP FOREIGN KEY ([HEEFT_BETREKKING_OP_KOSTENPLAATS_ID]) REFERENCES [KOSTENPLAATS] ([KOSTENPLAATS_ID]);
-- HEEFT_BETREKKING_OP (0..* to 1, Connector_ID: 483)

ALTER TABLE [KOSTENPLAATS] ADD CONSTRAINT FK_KOSTENPLAATS_HEEFT FOREIGN KEY ([HEEFT_SUBREKENING_ID]) REFERENCES [SUBREKENING] ([SUBREKENING_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 488)

ALTER TABLE [KOSTENPLAATS] ADD CONSTRAINT FK_KOSTENPLAATS_HEEFT_2 FOREIGN KEY ([HEEFT_WERKORDER_ID]) REFERENCES [WERKORDER] ([WERKORDER_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 489)

ALTER TABLE [MUTATIE] ADD CONSTRAINT FK_MUTATIE_NAAR FOREIGN KEY ([NAAR_HOOFDREKENING_ID]) REFERENCES [HOOFDREKENING] ([HOOFDREKENING_ID]);
-- NAAR (0..* to 1, Connector_ID: 500)

ALTER TABLE [MUTATIE] ADD CONSTRAINT FK_MUTATIE_VAN FOREIGN KEY ([VAN_HOOFDREKENING_ID]) REFERENCES [HOOFDREKENING] ([HOOFDREKENING_ID]);
-- VAN (0..* to 1, Connector_ID: 501)

ALTER TABLE [HOOFDREKENING] ADD CONSTRAINT FK_HOOFDREKENING_HEEFT FOREIGN KEY ([HEEFT_WERKORDER_ID]) REFERENCES [WERKORDER] ([WERKORDER_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 502)

ALTER TABLE [HOOFDREKENING] ADD CONSTRAINT FK_HOOFDREKENING_HEEFT_2 FOREIGN KEY ([HEEFT_SUBREKENING_ID]) REFERENCES [SUBREKENING] ([SUBREKENING_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 503)

ALTER TABLE [HOOFDREKENING] ADD CONSTRAINT FK_HOOFDREKENING_VALT_BINNEN FOREIGN KEY ([VALT_BINNEN_HOOFDREKENING_ID]) REFERENCES [HOOFDREKENING] ([HOOFDREKENING_ID]);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 504)

ALTER TABLE [FACTUURREGEL] ADD CONSTRAINT FK_FACTUURREGEL_LEIDT_TOT FOREIGN KEY ([LEIDT_TOT_MUTATIE_ID]) REFERENCES [MUTATIE] ([MUTATIE_ID]);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 506)

ALTER TABLE [FACTUUR] ADD CONSTRAINT FK_FACTUUR_HEEFT FOREIGN KEY ([HEEFT_FACTUURREGEL_ID]) REFERENCES [FACTUURREGEL] ([FACTUURREGEL_ID]);
-- HEEFT (1 to 1..*, Connector_ID: 508)

ALTER TABLE [FACTUUR] ADD CONSTRAINT FK_FACTUUR_SCHRIJFT_OP FOREIGN KEY ([SCHRIJFT_OP_KOSTENPLAATS_ID]) REFERENCES [KOSTENPLAATS] ([KOSTENPLAATS_ID]);
-- SCHRIJFT_OP (0..* to 0..1, Connector_ID: 510)

ALTER TABLE [BATCHREGEL] ADD CONSTRAINT FK_BATCHREGEL_LEIDT_TOT FOREIGN KEY ([LEIDT_TOT_MUTATIE_ID]) REFERENCES [MUTATIE] ([MUTATIE_ID]);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 523)

ALTER TABLE [BATCH] ADD CONSTRAINT FK_BATCH_HEEFT FOREIGN KEY ([HEEFT_BATCHREGEL_ID]) REFERENCES [BATCHREGEL] ([BATCHREGEL_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 524)

ALTER TABLE [BATCH] ADD CONSTRAINT FK_BATCH_HEEFT_HERKOMST FOREIGN KEY ([HEEFT_HERKOMST_EXTERNEBRON_ID]) REFERENCES [EXTERNEBRON] ([EXTERNEBRON_ID]);
-- HEEFT_HERKOMST (0..* to 1, Connector_ID: 525)

ALTER TABLE [BANKREKENING] ADD CONSTRAINT FK_BANKREKENING_NAAR FOREIGN KEY ([NAAR_BETALING_ID]) REFERENCES [BETALING] ([BETALING_ID]);
-- NAAR (1 to 0..*, Connector_ID: 526)

ALTER TABLE [BANKREKENING] ADD CONSTRAINT FK_BANKREKENING_VAN FOREIGN KEY ([VAN_BETALING_ID]) REFERENCES [BETALING] ([BETALING_ID]);
-- VAN (1 to 0..*, Connector_ID: 527)

ALTER TABLE [BANKAFSCHRIFTREGEL] ADD CONSTRAINT FK_BANKAFSCHRIFTREGEL_LEIDT_TOT FOREIGN KEY ([LEIDT_TOT_MUTATIE_ID]) REFERENCES [MUTATIE] ([MUTATIE_ID]);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 529)

ALTER TABLE [BANKREKENING] ADD CONSTRAINT FK_BANKREKENING_HEEFT FOREIGN KEY ([HEEFT_BANKAFSCHRIFT_ID]) REFERENCES [BANKAFSCHRIFT] ([BANKAFSCHRIFT_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 530)

ALTER TABLE [BANKAFSCHRIFT] ADD CONSTRAINT FK_BANKAFSCHRIFT_HEEFT FOREIGN KEY ([HEEFT_BANKAFSCHRIFTREGEL_ID]) REFERENCES [BANKAFSCHRIFTREGEL] ([BANKAFSCHRIFTREGEL_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 531)

ALTER TABLE [APPLICATIE] ADD CONSTRAINT FK_APPLICATIE_HEEFT_HERKOMST FOREIGN KEY ([HEEFT_HERKOMST_BATCH_ID]) REFERENCES [BATCH] ([BATCH_ID]);
-- HEEFT_HERKOMST (1 to 0..*, Connector_ID: 644)

ALTER TABLE [BETALING] ADD CONSTRAINT FK_BETALING_KOMT_VOOR_OP FOREIGN KEY ([KOMT_VOOR_OP_BANKAFSCHRIFTREGEL_ID]) REFERENCES [BANKAFSCHRIFTREGEL] ([BANKAFSCHRIFTREGEL_ID]);
-- KOMT_VOOR_OP (0..* to 0..1, Connector_ID: 2045)

