CREATE TABLE GEMEENTE (
    GEMEENTE_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD BOOLEAN,
        GEMEENTECODE VARCHAR(255),
        GEMEENTENAAM VARCHAR(80),
        GEMEENTENAAM_NEN VARCHAR(255),
        GEOMETRIE GEOMETRY,
        IDENTIFICATIE VARCHAR(255),
        IS_OVERGEGAAN_IN_GEMEENTE_ID VARCHAR(255),
        VERSIE INTEGER
);

CREATE TABLE WOONPLAATS (
    WOONPLAATS_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER INTEGER,
        EINDGELDIGHEID DATE,
        EINDREGISTRATIE DATE,
        GECONSTATEERD BOOLEAN,
        GEOMETRIE GEOMETRY,
        IDENTIFICATIE VARCHAR(255),
        LIGT_IN_GEMEENTE_ID VARCHAR(255),
        STATUS VARCHAR(255),
        TIJDSTIPACTIEF TIMESTAMP,
        TIJDSTIPREGISTRATIE TIMESTAMP,
        VERSIE INTEGER,
        VOORKOMEN DATE,
        WOONPLAATSNAAM VARCHAR(80),
        WOONPLAATSNAAMNEN VARCHAR(255)
);

CREATE TABLE WIJK (
    WIJK_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD BOOLEAN,
        GEOMETRIE GEOMETRY,
        IDENTIFICATIE VARCHAR(255),
        LIGT_IN_WOONPLAATS_ID VARCHAR(255),
        STATUS VARCHAR(255),
        VERSIE INTEGER,
        WIJKCODE VARCHAR(255),
        WIJKNAAM VARCHAR(255)
);

CREATE TABLE BUURT (
    BUURT_ID VARCHAR(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR(255),
        CODE VARCHAR(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        EINDGELDIGHEID DATE,
        GECONSTATEERD BOOLEAN,
        GEOMETRIE GEOMETRY,
        IDENTIFICATIE VARCHAR(255),
        LIGT_IN_WIJK_ID VARCHAR(255),
        NAAM VARCHAR(255),
        STATUS VARCHAR(255),
        VERSIE INTEGER
);

ALTER TABLE BUURT ADD CONSTRAINT FK_BUURT_LIGT_IN FOREIGN KEY (LIGT_IN_WIJK_ID) REFERENCES WIJK (WIJK_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 346)

ALTER TABLE GEMEENTE ADD CONSTRAINT FK_GEMEENTE_IS_OVERGEGAAN_IN FOREIGN KEY (IS_OVERGEGAAN_IN_GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- IS_OVERGEGAAN_IN (None to 0..*, Connector_ID: 341)

ALTER TABLE WIJK ADD CONSTRAINT FK_WIJK_LIGT_IN FOREIGN KEY (LIGT_IN_WOONPLAATS_ID) REFERENCES WOONPLAATS (WOONPLAATS_ID);
-- LIGT_IN (1..* to 1, Connector_ID: 319)

ALTER TABLE WOONPLAATS ADD CONSTRAINT FK_WOONPLAATS_LIGT_IN FOREIGN KEY (LIGT_IN_GEMEENTE_ID) REFERENCES GEMEENTE (GEMEENTE_ID);
-- LIGT_IN (1..* to 1.., Connector_ID: 340)

