CREATE TABLE `ENUMCONTACTSOORT_ENUM` (
    `ENUMCONTACTSOORT_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `ENUMCONTACTSOORT_ENUM` (`ENUMCONTACTSOORT_ENUM_ID`, VALUE) VALUES
    (1, 'BRIEF'),
    (2, 'HUISBEZOEK'),
    (3, 'KAARTJE'),
    (4, 'MAIL'),
    (5, 'OVERIGE'),
    (6, 'SMS_WHATSAPP'),
    (7, 'TELEFOON');

CREATE TABLE `ENUMDAGDEEL_ENUM` (
    `ENUMDAGDEEL_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `ENUMDAGDEEL_ENUM` (`ENUMDAGDEEL_ENUM_ID`, VALUE) VALUES
    (1, 'AVOND'),
    (2, 'MIDDAG'),
    (3, 'OCHTEND');

CREATE TABLE `ENUMEINDRESULTAAT_ENUM` (
    `ENUMEINDRESULTAAT_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `ENUMEINDRESULTAAT_ENUM` (`ENUMEINDRESULTAAT_ENUM_ID`, VALUE) VALUES
    (1, 'GEEN_CONTACT_MEER_KUNNEN_KRIJGEN'),
    (2, 'INWONER_AL_BEKEND_BIJ_SCHULDHULPVERLENING'),
    (3, 'INWONER_HEEFT_AL_EEN_ANDER_LOPEND_TRAJECT'),
    (4, 'INWONER_HEEFT_BETAALD_BETALINGSREGELING_GETROFFEN_VOOR_OPPAKKEN_MELDING'),
    (5, 'INWONER_HEEFT_ZELF_BETAALD_BETALINGSREGELING_GETROFFEN_NA_OPPAKKEN_MELDING'),
    (6, 'INWONER_PROBEERT_HET_ZELF_OP_TE_LOSSEN'),
    (7, 'INWONER_WIL_GEEN_HULP'),
    (8, 'NIET_OPGEPAKT'),
    (9, 'NIET_OPGEPAKT_BRP_UITSLUITING'),
    (10, 'NIET_OPGEPAKT_GEEN_CAPACITEIT'),
    (11, 'NIET_OPGEPAKT_INWONER_WIL_GEEN_CONTACT'),
    (12, 'VERWIJZING_FINANCIEEL'),
    (13, 'VERWIJZING_NIET_FINANCIEEL'),
    (14, 'VOORZIEN_VAN_INFORMATIE'),
    (15, '_BUDGET_ADVIES_EN_OF_QUICK_FIX');

CREATE TABLE `ENUMSIGNAALPARTNER_ENUM` (
    `ENUMSIGNAALPARTNER_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `ENUMSIGNAALPARTNER_ENUM` (`ENUMSIGNAALPARTNER_ENUM_ID`, VALUE) VALUES
    (1, 'BELASTINGDIENST'),
    (2, 'CAK_EIGEN_BIJDRAGE'),
    (3, 'CAK_ZORGVERZEKERINGEN'),
    (4, 'DIENST_TOESLAGEN'),
    (5, 'DUO'),
    (6, 'ENERGIE'),
    (7, 'HUUR'),
    (8, 'HYPOTHEEK'),
    (9, 'OVERIGE'),
    (10, 'WATER'),
    (11, 'ZORG');

CREATE TABLE `ENUMSIGNAALSTATUS_ENUM` (
    `ENUMSIGNAALSTATUS_ENUM_ID` INT PRIMARY KEY,
    VALUE VARCHAR(255)
) ENGINE=InnoDB;

INSERT INTO `ENUMSIGNAALSTATUS_ENUM` (`ENUMSIGNAALSTATUS_ENUM_ID`, VALUE) VALUES
    (1, 'HERHAALDE_MELDING'),
    (2, 'NIET_OPGEPAKT'),
    (3, 'NOG_NIET_OPGEPAKT'),
    (4, 'ONTERECHT_SIGNAAL'),
    (5, 'OPGEPAKT'),
    (6, 'OVERLEDEN'),
    (7, 'WOONT_NIET_IN_GEMEENTE'),
    (8, 'WOONT_OP_EEN_ANDER_ADRES_BINNEN_GEMEENTE');

CREATE TABLE `CLIENT` (
    `CLIENT_ID` INT PRIMARY KEY,
        `CODE` VARCHAR(80),
        `GEZAGSDRAGERGEKEND` BOOLEAN,
        `JURIDISCHESTATUS` VARCHAR(80),
        `WETTELIJKEVERTEGENWOORDIGING` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `CONTACTPOGING` (
    `CONTACTPOGING_ID` INT PRIMARY KEY,
        `BEREIKT` BOOLEAN,
        `DAGDEEL_ENUM_ID` INT,
        `DATUM` DATE,
        `SOORT_ENUM_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `GEMEENTE` (
    `GEMEENTE_ID` INT PRIMARY KEY,
        `BEGINGELDIGHEID` VARCHAR(255),
        `DATUMEINDE` DATE,
        `DATUMINGANG` DATE,
        `EINDGELDIGHEID` DATE,
        `GECONSTATEERD` BOOLEAN,
        `GEMEENTECODE` VARCHAR(255),
        `GEMEENTENAAM` VARCHAR(80),
        `GEMEENTENAAM_NEN` VARCHAR(255),
        `GEOMETRIE` GEOMETRY,
        `IDENTIFICATIE` VARCHAR(255),
        `IS_OVERGEGAAN_IN_GEMEENTE_ID` INT,
        `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `NIETNATUURLIJKPERSOON` (
    `NIETNATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `DATUMAANVANG` DATE,
        `DATUMEINDE` DATE,
        `DATUMUITSCHRIJVING` DATE,
        `DATUMVOORTZETTING` DATE,
        `FAXNUMMER` VARCHAR(20),
        `INGESCHREVEN` BOOLEAN,
        `INOPRICHTING` BOOLEAN,
        `KVKNUMMER` VARCHAR(255),
        `NNPID` VARCHAR(255),
        `RECHTSVORM` VARCHAR(255),
        `RSINNUMMER` VARCHAR(255),
        `STATUTAIRENAAM` VARCHAR(255),
        `STATUTAIREZETEL` VARCHAR(255),
        `WEBSITEURL` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `SIGNAALPARTNER` (
    `SIGNAALPARTNER_ID` INT PRIMARY KEY,
        `TYPE_ENUM_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VROEGSIGNAALZAAK` (
    `VROEGSIGNAALZAAK_ID` INT PRIMARY KEY,
        `DATUM_OPGEPAKT` DATE,
        `EINDDATUM_MATCHINGPERIODE` DATE,
        `HEEFT_CONTACTPOGING_ID` INT,
        `MATCHINGSDATUM` DATE,
        `OPGEPAKTDOOR_NIETNATUURLIJKPERSOON_ID` INT,
        `OPGEPAKTNAMENS_GEMEENTE_ID` INT,
        `RESULTAAT_ENUM_ID` INT,
        `STARTDATUM_MATCHTINGPERIODE` DATE
) ENGINE=InnoDB;

CREATE TABLE `VROEGSIGNAAL` (
    `VROEGSIGNAAL_ID` INT PRIMARY KEY,
        `BEDRAG` DECIMAL(10,2),
        `BETREFT_CLIENT_ID` INT,
        `CRISISSIGNAAL` BOOLEAN,
        `ONTSTAANSDATUM` DATE,
        `OPGEPAKTIN_VROEGSIGNAALZAAK_ID` INT,
        `SIGNAALDATUM` DATE,
        `STATUS_ENUM_ID` INT,
        `VERZONDENDOOR_SIGNAALPARTNER_ID` INT,
        `WARMEOVERDRACHT` BOOLEAN
) ENGINE=InnoDB;

ALTER TABLE `CONTACTPOGING` ADD CONSTRAINT FK_CONTACTPOGING_DAGDEEL_ENUM_ID FOREIGN KEY (`DAGDEEL_ENUM_ID`) REFERENCES `ENUMDAGDEEL_ENUM` (`ENUMDAGDEEL_ENUM_ID`);
-- DAGDEEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `CONTACTPOGING` ADD CONSTRAINT FK_CONTACTPOGING_SOORT_ENUM_ID FOREIGN KEY (`SOORT_ENUM_ID`) REFERENCES `ENUMCONTACTSOORT_ENUM` (`ENUMCONTACTSOORT_ENUM_ID`);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `GEMEENTE` ADD CONSTRAINT FK_GEMEENTE_IS_OVERGEGAAN_IN FOREIGN KEY (`IS_OVERGEGAAN_IN_GEMEENTE_ID`) REFERENCES `GEMEENTE` (`GEMEENTE_ID`);
-- IS_OVERGEGAAN_IN (None to 0..*, Connector_ID: 341)

ALTER TABLE `SIGNAALPARTNER` ADD CONSTRAINT FK_SIGNAALPARTNER_TYPE_ENUM_ID FOREIGN KEY (`TYPE_ENUM_ID`) REFERENCES `ENUMSIGNAALPARTNER_ENUM` (`ENUMSIGNAALPARTNER_ENUM_ID`);
-- TYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VROEGSIGNAAL` ADD CONSTRAINT FK_VROEGSIGNAAL_BETREFT FOREIGN KEY (`BETREFT_CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`);
-- BETREFT (0..* to 1, Connector_ID: 1504)

ALTER TABLE `VROEGSIGNAAL` ADD CONSTRAINT FK_VROEGSIGNAAL_OPGEPAKTIN FOREIGN KEY (`OPGEPAKTIN_VROEGSIGNAALZAAK_ID`) REFERENCES `VROEGSIGNAALZAAK` (`VROEGSIGNAALZAAK_ID`);
-- OPGEPAKTIN (1..* to 0..1, Connector_ID: 1505)

ALTER TABLE `VROEGSIGNAAL` ADD CONSTRAINT FK_VROEGSIGNAAL_STATUS_ENUM_ID FOREIGN KEY (`STATUS_ENUM_ID`) REFERENCES `ENUMSIGNAALSTATUS_ENUM` (`ENUMSIGNAALSTATUS_ENUM_ID`);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE `VROEGSIGNAAL` ADD CONSTRAINT FK_VROEGSIGNAAL_VERZONDENDOOR FOREIGN KEY (`VERZONDENDOOR_SIGNAALPARTNER_ID`) REFERENCES `SIGNAALPARTNER` (`SIGNAALPARTNER_ID`);
-- VERZONDENDOOR (0..* to 1, Connector_ID: 1507)

ALTER TABLE `VROEGSIGNAALZAAK` ADD CONSTRAINT FK_VROEGSIGNAALZAAK_HEEFT FOREIGN KEY (`HEEFT_CONTACTPOGING_ID`) REFERENCES `CONTACTPOGING` (`CONTACTPOGING_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 1506)

ALTER TABLE `VROEGSIGNAALZAAK` ADD CONSTRAINT FK_VROEGSIGNAALZAAK_OPGEPAKTDOOR FOREIGN KEY (`OPGEPAKTDOOR_NIETNATUURLIJKPERSOON_ID`) REFERENCES `NIETNATUURLIJKPERSOON` (`NIETNATUURLIJKPERSOON_ID`);
-- OPGEPAKTDOOR (0..* to 1, Connector_ID: 1532)

ALTER TABLE `VROEGSIGNAALZAAK` ADD CONSTRAINT FK_VROEGSIGNAALZAAK_OPGEPAKTNAMENS FOREIGN KEY (`OPGEPAKTNAMENS_GEMEENTE_ID`) REFERENCES `GEMEENTE` (`GEMEENTE_ID`);
-- OPGEPAKTNAMENS (0..* to 1, Connector_ID: 1509)

ALTER TABLE `VROEGSIGNAALZAAK` ADD CONSTRAINT FK_VROEGSIGNAALZAAK_RESULTAAT_ENUM_ID FOREIGN KEY (`RESULTAAT_ENUM_ID`) REFERENCES `ENUMEINDRESULTAAT_ENUM` (`ENUMEINDRESULTAAT_ENUM_ID`);
-- RESULTAAT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

