CREATE TABLE CLIENT (
    INGESCHREVENPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        CODE VARCHAR2(80),
        GEZAGSDRAGERGEKEND NUMBER(1),
        JURIDISCHESTATUS VARCHAR2(80),
        WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE GERECHTELIJKE_UITSPRAAK (
    GERECHTELIJKE_UITSPRAAK_ID VARCHAR2(255) PRIMARY KEY,
        BASIS_VAN_GEZAGSVERHOUDING_ID VARCHAR2(255)
);

CREATE TABLE GEZAGSVERHOUDING (
    GEZAGSVERHOUDING_ID VARCHAR2(255) PRIMARY KEY,
        BETREFT_INGESCHREVENPERSOON_ID VARCHAR2(255),
        EINDDATUM DATE,
        INDICATIE_CURATELEREGISTER NUMBER,
        INDICATIE_GEZAG_MINDERJARIGE NUMBER,
        INGANGSDATUM DATE
);

CREATE TABLE INGESCHREVENPERSOON (
    INGESCHREVENPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESHERKOMST VARCHAR2(255),
        ANUMMER VARCHAR2(20),
        BESCHRIJVINGLOCATIE VARCHAR2(200),
        BUITENLANDSREISDOCUMENT VARCHAR2(80),
        BURGERLIJKESTAAT VARCHAR2(255),
        DATUMBEGINGELDIGHEIDVERBLIJFPLAATS DATE,
        DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS DATE,
        DATUMINSCHRIJVINGGEMEENTE DATE,
        DATUMOPSCHORTINGBIJHOUDING DATE,
        DATUMVERTREKUITNEDERLAND DATE,
        DATUMVESTIGINGNEDERLAND DATE,
        GEMEENTEVANINSCHRIJVING VARCHAR2(80),
        GEZAGHEBBENDE_GEZAGSVERHOUDING_ID VARCHAR2(255),
        GEZINSRELATIE VARCHAR2(255),
        INDICATIEGEHEIM NUMBER(1),
        INGEZETENE NUMBER(1),
        LANDWAARNAARVERTROKKEN VARCHAR2(255),
        LANDWAARVANDAANINGESCHREVEN VARCHAR2(255),
        OUDER1 VARCHAR2(255),
        OUDER2 VARCHAR2(255),
        OUDER_1_INGESCHREVENPERSOON_ID VARCHAR2(255),
        OUDER_2_INGESCHREVENPERSOON_ID VARCHAR2(255),
        PARTNERID VARCHAR2(255),
        REDENEINDEBEWONING DATE,
        REDENOPSCHORTINGBIJHOUDING VARCHAR2(200),
        SIGNALERINGREISDOCUMENT NUMBER(1),
        VERBLIJFSTITEL VARCHAR2(255)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMUITSCHRIJVING DATE,
        DATUMVOORTZETTING DATE,
        FAXNUMMER VARCHAR2(20),
        GEZAGHEBBENDE_GEZAGSVERHOUDING_ID VARCHAR2(255),
        INGESCHREVEN NUMBER(1),
        INOPRICHTING NUMBER(1),
        KVKNUMMER VARCHAR2(255),
        NNPID VARCHAR2(255),
        RECHTSVORM VARCHAR2(255),
        RSINNUMMER VARCHAR2(255),
        STATUTAIRENAAM VARCHAR2(255),
        STATUTAIREZETEL VARCHAR2(255),
        WEBSITEURL VARCHAR2(200)
);

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY (INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE GERECHTELIJKE_UITSPRAAK ADD CONSTRAINT FK_GERECHTELIJKE_UITSPRAAK_BASIS_VAN FOREIGN KEY (BASIS_VAN_GEZAGSVERHOUDING_ID) REFERENCES GEZAGSVERHOUDING (GEZAGSVERHOUDING_ID);
-- BASIS_VAN (0..1 to 0..*, Connector_ID: 935)

ALTER TABLE GEZAGSVERHOUDING ADD CONSTRAINT FK_GEZAGSVERHOUDING_BETREFT FOREIGN KEY (BETREFT_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- BETREFT (0..2 to 1, Connector_ID: 934)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEZAGHEBBENDE FOREIGN KEY (GEZAGHEBBENDE_GEZAGSVERHOUDING_ID) REFERENCES GEZAGSVERHOUDING (GEZAGSVERHOUDING_ID);
-- GEZAGHEBBENDE (0..1 to 0..*, Connector_ID: 933)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (OUDER_1_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- OUDER_1 (None to None, Connector_ID: 170)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (OUDER_2_INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (INGESCHREVENPERSOON_ID);
-- OUDER_2 (None to None, Connector_ID: 171)

ALTER TABLE NIETNATUURLIJKPERSOON ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_GEZAGHEBBENDE FOREIGN KEY (GEZAGHEBBENDE_GEZAGSVERHOUDING_ID) REFERENCES GEZAGSVERHOUDING (GEZAGSVERHOUDING_ID);
-- GEZAGHEBBENDE (0..1 to 0..*, Connector_ID: 932)

