CREATE TABLE ENUMBEGELEIDINGSSOORT_ENUM (
    ENUMBEGELEIDINGSSOORT_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMBEGELEIDINGSSOORT_ENUM (ENUMBEGELEIDINGSSOORT_ENUM_ID, VALUE) VALUES
    (1, 'BESCHERMINGSBEWIND'),
    (2, 'BUDGETBEGELEIDING'),
    (3, 'BUDGETBEHEER'),
    (4, 'BUDGETCOACHING'),
    (5, 'LANGE_TERMIJN_BEGELEIDING_DFD_');

CREATE TABLE ENUMOPLOSSINGSSOORT_ENUM (
    ENUMOPLOSSINGSSOORT_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENUMOPLOSSINGSSOORT_ENUM (ENUMOPLOSSINGSSOORT_ENUM_ID, VALUE) VALUES
    (1, '0_AANBOD'),
    (2, 'BETALINGSREGELING'),
    (3, 'HERFINANCIERING'),
    (4, 'SANERINGSKREDIET'),
    (5, 'SCHULDBEMIDDELING');

CREATE TABLE BEGELEIDINGSSOORT (
    BEGELEIDINGSSOORT_ID VARCHAR2(255) PRIMARY KEY,
        SOORT VARCHAR2(255)
);

CREATE TABLE BEGELEIDING (
    BEGELEIDING_ID VARCHAR2(255) PRIMARY KEY,
        EINDDATUM DATE,
        SOORT_BEGELEIDINGSSOORT_ID VARCHAR2(255),
        SOORT_ENUM_ID VARCHAR2(255),
        STARTDATUM DATE
);

CREATE TABLE CONTACTPERSOON (
    CONTACTPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        EMAIL VARCHAR2(255),
        FUNCTIETITEL VARCHAR2(200),
        NAAM VARCHAR2(200),
        TELEFOONNUMMER VARCHAR2(200)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMAANVANG DATE,
        DATUMEINDE DATE,
        DATUMUITSCHRIJVING DATE,
        DATUMVOORTZETTING DATE,
        FAXNUMMER VARCHAR2(20),
        INGESCHREVEN NUMBER(1),
        INOPRICHTING NUMBER(1),
        KVKNUMMER VARCHAR2(255),
        NNPID VARCHAR2(255),
        RECHTSVORM VARCHAR2(255),
        RSINNUMMER VARCHAR2(255),
        STATUTAIRENAAM VARCHAR2(255),
        STATUTAIREZETEL VARCHAR2(255),
        WEBSITEURL VARCHAR2(200)
);

CREATE TABLE OPLOSSINGSSOORT (
    OPLOSSINGSSOORT_ID VARCHAR2(255) PRIMARY KEY,
        SOORT VARCHAR2(255)
);

CREATE TABLE OPLOSSING (
    OPLOSSING_ID VARCHAR2(255) PRIMARY KEY,
        EINDDATUM DATE,
        SOORT_ENUM_ID VARCHAR2(255),
        SOORT_OPLOSSINGSSOORT_ID VARCHAR2(255),
        STARTDATUM DATE,
        VTLB VARCHAR2(255)
);

CREATE TABLE SCHULDHULPORGANISATIE (
    NIETNATUURLIJKPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200)
);

CREATE TABLE KP_SCHLDHLPRGNST_BGLDNGSSRT (
    KP_SCHLDHLPRGNST_BGLDNGSSRT_ID VARCHAR2(255) PRIMARY KEY,
    SCHULDHULPORGANISATIE_ID VARCHAR2(255),
    BEGELEIDINGSSOORT_ID VARCHAR2(255)
);

CREATE TABLE KP_SCHLDHLPRGNST_CNTCTPRSN (
    KP_SCHLDHLPRGNST_CNTCTPRSN_ID VARCHAR2(255) PRIMARY KEY,
    SCHULDHULPORGANISATIE_ID VARCHAR2(255),
    CONTACTPERSOON_ID VARCHAR2(255)
);

CREATE TABLE KP_SCHLDHLPRGNST_OPLSSNGSSRT (
    KP_SCHLDHLPRGNST_OPLSSNGSSRT_ID VARCHAR2(255) PRIMARY KEY,
    SCHULDHULPORGANISATIE_ID VARCHAR2(255),
    OPLOSSINGSSOORT_ID VARCHAR2(255)
);

CREATE TABLE SCHULDHULPTRAJECT (
    SCHULDHULPTRAJECT_ID VARCHAR2(255) PRIMARY KEY,
        BEVAT_BEGELEIDING_ID VARCHAR2(255),
        BEVAT_OPLOSSING_ID VARCHAR2(255),
        EINDDATUM DATE,
        OMSCHRIJVING CLOB,
        STARTDATUM DATE,
        TOEKENNINGSDATUM DATE,
        TOTAALSCHULDBEDRAGBIJAANVANGSCHULD NUMBER(10,2)
);

CREATE TABLE KP_SCHLDHLPRGNST_SCHLDHLPTRJCT (
    KP_SCHLDHLPRGNST_SCHLDHLPTRJCT_ID VARCHAR2(255) PRIMARY KEY,
    SCHULDHULPORGANISATIE_ID VARCHAR2(255),
    SCHULDHULPTRAJECT_ID VARCHAR2(255)
);

ALTER TABLE SCHULDHULPORGANISATIE ADD CONSTRAINT FK_SCHULDHULPORGANISATIE_GEN_NIETNATUURLIJKPERSOON FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (NIETNATUURLIJKPERSOON_ID);
-- Generalization to NIETNATUURLIJKPERSOON

ALTER TABLE KP_SCHLDHLPRGNST_BGLDNGSSRT ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_BGLDNGSSRT_1 FOREIGN KEY (SCHULDHULPORGANISATIE_ID) REFERENCES SCHULDHULPORGANISATIE (NIETNATUURLIJKPERSOON_ID);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 993)

ALTER TABLE KP_SCHLDHLPRGNST_BGLDNGSSRT ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_BGLDNGSSRT_2 FOREIGN KEY (BEGELEIDINGSSOORT_ID) REFERENCES BEGELEIDINGSSOORT (BEGELEIDINGSSOORT_ID);
-- BEGELEIDINGSSOORT (many-to-many junction, Connector_ID: 993)

ALTER TABLE KP_SCHLDHLPRGNST_CNTCTPRSN ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_CNTCTPRSN_1 FOREIGN KEY (SCHULDHULPORGANISATIE_ID) REFERENCES SCHULDHULPORGANISATIE (NIETNATUURLIJKPERSOON_ID);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 992)

ALTER TABLE KP_SCHLDHLPRGNST_CNTCTPRSN ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_CNTCTPRSN_2 FOREIGN KEY (CONTACTPERSOON_ID) REFERENCES CONTACTPERSOON (CONTACTPERSOON_ID);
-- CONTACTPERSOON (many-to-many junction, Connector_ID: 992)

ALTER TABLE KP_SCHLDHLPRGNST_OPLSSNGSSRT ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_OPLSSNGSSRT_1 FOREIGN KEY (SCHULDHULPORGANISATIE_ID) REFERENCES SCHULDHULPORGANISATIE (NIETNATUURLIJKPERSOON_ID);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 974)

ALTER TABLE KP_SCHLDHLPRGNST_OPLSSNGSSRT ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_OPLSSNGSSRT_2 FOREIGN KEY (OPLOSSINGSSOORT_ID) REFERENCES OPLOSSINGSSOORT (OPLOSSINGSSOORT_ID);
-- OPLOSSINGSSOORT (many-to-many junction, Connector_ID: 974)

ALTER TABLE KP_SCHLDHLPRGNST_SCHLDHLPTRJCT ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_SCHLDHLPTRJCT_1 FOREIGN KEY (SCHULDHULPORGANISATIE_ID) REFERENCES SCHULDHULPORGANISATIE (NIETNATUURLIJKPERSOON_ID);
-- SCHULDHULPORGANISATIE (many-to-many junction, Connector_ID: 967)

ALTER TABLE KP_SCHLDHLPRGNST_SCHLDHLPTRJCT ADD CONSTRAINT FK_KP_SCHLDHLPRGNST_SCHLDHLPTRJCT_2 FOREIGN KEY (SCHULDHULPTRAJECT_ID) REFERENCES SCHULDHULPTRAJECT (SCHULDHULPTRAJECT_ID);
-- SCHULDHULPTRAJECT (many-to-many junction, Connector_ID: 967)

ALTER TABLE BEGELEIDING ADD CONSTRAINT FK_BEGELEIDING_SOORT FOREIGN KEY (SOORT_BEGELEIDINGSSOORT_ID) REFERENCES BEGELEIDINGSSOORT (BEGELEIDINGSSOORT_ID);
-- SOORT (0..* to 1, Connector_ID: 999)

ALTER TABLE BEGELEIDING ADD CONSTRAINT FK_BEGELEIDING_SOORT_ENUM_ID FOREIGN KEY (SOORT_ENUM_ID) REFERENCES ENUMBEGELEIDINGSSOORT_ENUM (ENUMBEGELEIDINGSSOORT_ENUM_ID);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE OPLOSSING ADD CONSTRAINT FK_OPLOSSING_SOORT FOREIGN KEY (SOORT_OPLOSSINGSSOORT_ID) REFERENCES OPLOSSINGSSOORT (OPLOSSINGSSOORT_ID);
-- SOORT (0..* to 1, Connector_ID: 977)

ALTER TABLE OPLOSSING ADD CONSTRAINT FK_OPLOSSING_SOORT_ENUM_ID FOREIGN KEY (SOORT_ENUM_ID) REFERENCES ENUMOPLOSSINGSSOORT_ENUM (ENUMOPLOSSINGSSOORT_ENUM_ID);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT FOREIGN KEY (BEVAT_OPLOSSING_ID) REFERENCES OPLOSSING (OPLOSSING_ID);
-- BEVAT (1 to 0..1, Connector_ID: 976)

ALTER TABLE SCHULDHULPTRAJECT ADD CONSTRAINT FK_SCHULDHULPTRAJECT_BEVAT_2 FOREIGN KEY (BEVAT_BEGELEIDING_ID) REFERENCES BEGELEIDING (BEGELEIDING_ID);
-- BEVAT (1 to 0..*, Connector_ID: 996)

