CREATE TABLE [RECHTSPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
        [ADRESBINNENLAND] VARCHAR(255),
        [ADRESBUITENLAND] VARCHAR(255),
        [ADRESCORRESPONDENTIE] VARCHAR(100),
        [EMAILADRES] VARCHAR(80),
        [FAXNUMMER] VARCHAR(20),
        [IDENTIFICATIE] VARCHAR(255),
        [KVKNUMMER] VARCHAR(20),
        [NAAM] VARCHAR(200),
        [RECHTSVORM] VARCHAR(100),
        [REKENINGNUMMER] VARCHAR(255),
        [TELEFOONNUMMER] VARCHAR(20)
);

CREATE TABLE [EIGENAAR] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY
);

CREATE TABLE [HUURDER] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY
);

CREATE TABLE [LEVERANCIER] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
        [NAAM] VARCHAR(200),
        [NUMMER] VARCHAR(255)
);

CREATE TABLE [PACHTER] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY
);

ALTER TABLE [EIGENAAR] ADD CONSTRAINT FK_EIGENAAR_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [HUURDER] ADD CONSTRAINT FK_HUURDER_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [PACHTER] ADD CONSTRAINT FK_PACHTER_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [LEVERANCIER] ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

