CREATE TABLE NATUURLIJKPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
    AANHEFAANSCHRIJVING VARCHAR2(50),
    ACADEMISCHETITEL VARCHAR2(80),
    ACHTERNAAM VARCHAR2(100),
    ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
    ANUMMER VARCHAR2(20),
    BIJZONDERNEDERLANDERSCHAP VARCHAR2(50),
    BURGERSERVICENUMMER VARCHAR2(255),
    DATUMGEBOORTE DATE,
    DATUMOVERLIJDEN DATE,
    GEBOORTELAND VARCHAR2(255),
    GEBOORTEPLAATS VARCHAR2(200),
    GESLACHTSAANDUIDING VARCHAR2(255),
    GESLACHTSNAAM VARCHAR2(200),
    GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
    HANDLICHTING VARCHAR2(50),
    INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID NUMBER,
    INDICATIEOVERLEDEN_ENUM_ID NUMBER,
    LANDOVERLIJDEN VARCHAR2(255),
    NATIONALITEIT VARCHAR2(100),
    OVERLIJDENSPLAATS VARCHAR2(200),
    VOORLETTERSAANSCHRIJVING VARCHAR2(20),
    VOORNAMEN VARCHAR2(200),
    VOORNAMENAANSCHRIJVING VARCHAR2(200),
    VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE KP_NTRLJKPRSN_RCHTSPRSN (
    KP_NTRLJKPRSN_RCHTSPRSN_ID NUMBER PRIMARY KEY,
    NATUURLIJKPERSOON_ID NUMBER,
    RECHTSPERSOON_ID NUMBER
);

CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID NUMBER PRIMARY KEY,
    HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID NUMBER,
    IDENTIFICATIE VARCHAR2(255),
    TYPEADRESSEERBAAROBJECT VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE KP_NTNTRLJKPRSN_RCHTSPRSN (
    KP_NTNTRLJKPRSN_RCHTSPRSN_ID NUMBER PRIMARY KEY,
    NIETNATUURLIJKPERSOON_ID NUMBER,
    RECHTSPERSOON_ID NUMBER
);

CREATE TABLE SBIACTIVITEIT (
    SBIACTIVITEIT_ID NUMBER PRIMARY KEY,
    DATUMEINDESBIACTIVITEIT DATE,
    DATUMINGANGSBIACTIVITEIT DATE,
    HOOFDNIVEAU VARCHAR2(255),
    HOOFDNIVEAUOMSCHRIJVING VARCHAR2(100),
    NAAMACTIVITEIT VARCHAR2(255),
    SBICODE VARCHAR2(255),
    SBIGROEP VARCHAR2(255),
    SBIGROEPOMSCHRIJVING VARCHAR2(100)
);

CREATE TABLE MAATSCHAPPELIJKEACTIVITEIT (
    MAATSCHAPPELIJKEACTIVITEIT_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    DATUMAANVANG DATE,
    DATUMEINDEGELDIG DATE,
    DATUMFAILLISEMENT DATE,
    HEEFT_ALS_EIGENAAR_RECHTSPERSOON_ID NUMBER,
    INDICATIEECONOMISCHACTIEF_ENUM_ID NUMBER,
    IS_FUNCTIONARIS_VAN_RECHTSPERSOON_ID NUMBER,
    KVKNUMMER VARCHAR2(255),
    RECHTSVORM VARCHAR2(100),
    RSIN VARCHAR2(255),
    STATUTAIRENAAM VARCHAR2(100),
    TELEFOONNUMMER VARCHAR2(20),
    URL VARCHAR2(100)
);

CREATE TABLE NIETNATUURLIJKPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    DATUMAANVANG DATE,
    DATUMEINDE DATE,
    DATUMUITSCHRIJVING DATE,
    DATUMVOORTZETTING DATE,
    FAXNUMMER VARCHAR2(20),
    INGESCHREVEN_ENUM_ID NUMBER,
    INOPRICHTING_ENUM_ID NUMBER,
    KVKNUMMER VARCHAR2(255),
    NNPID VARCHAR2(255),
    RECHTSVORM_ENUM_ID NUMBER,
    RSINNUMMER VARCHAR2(255),
    STATUTAIRENAAM VARCHAR2(255),
    STATUTAIREZETEL VARCHAR2(255),
    WEBSITEURL VARCHAR2(200)
);

CREATE TABLE VESTIGING (
    VESTIGING_ID NUMBER PRIMARY KEY,
    COMMERCIELEVESTIGING_ENUM_ID NUMBER,
    DATUMAANVANG DATE,
    DATUMEINDE DATE,
    DATUMVOORTZETTING DATE,
    FULLTIMEWERKZAMEMANNEN VARCHAR2(255),
    FULLTIMEWERKZAMEVROUWEN VARCHAR2(255),
    HANDELSNAAM VARCHAR2(255),
    HEEFT_ALS_LOCATIE_ADRES_NUMMERAANDUIDING_ID NUMBER,
    HEEFT_HOOFDLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID NUMBER,
    HEEFT_NEVENLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID NUMBER,
    HEEFT_RECHTSPERSOON_ID NUMBER,
    IS_HOOFDVESTIGING_VAN_MAATSCHAPPELIJKEACTIVITEIT_ID NUMBER,
    PARTTIMEWERKZAMEMANNEN VARCHAR2(255),
    PARTTIMEWERKZAMEVROUWEN VARCHAR2(255),
    TOEVOEGINGADRES VARCHAR2(100),
    TOTAALWERKZAMEPERSONEN VARCHAR2(255),
    UITOEFENING_VAN_ACTIVITEITEN_MAATSCHAPPELIJKEACTIVITEIT_ID NUMBER,
    VERKORTENAAM VARCHAR2(255),
    VESTIGINGSNUMMER VARCHAR2(255)
);

CREATE TABLE SBIACTIVITEITVESTIGING (
    SBIACTIVITEITVESTIGING_ID NUMBER PRIMARY KEY,
    INDICATIEHOOFDACTIVITEIT VARCHAR2(100),
    SBICODE VARCHAR2(50),
    VESTIGING_ID NUMBER
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID NUMBER PRIMARY KEY,
    BEGINGELDIGHEID DATE,
    DATUMEINDE DATE,
    DATUMINGANG DATE,
    DOCUMENTDATUM DATE,
    DOCUMENTNUMMER NUMBER,
    EINDEGELDIGHEID DATE,
    GECONSTATEERD_ENUM_ID NUMBER,
    GEOMETRIE SDO_GEOMETRY,
    HEEFT_ALS_NEVENADRES_ADRESSEERBAAROBJECT_ID NUMBER,
    HUISLETTER VARCHAR2(255),
    HUISNUMMER VARCHAR2(255),
    HUISNUMMERTOEVOEGING VARCHAR2(255),
    IDENTIFICATIE VARCHAR2(255),
    POSTCODE VARCHAR2(255),
    STATUS VARCHAR2(255),
    TYPEADRESSEERBAAROBJECT VARCHAR2(255),
    VERSIE NUMBER
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    EMAILADRES VARCHAR2(80),
    FAXNUMMER VARCHAR2(20),
    IDENTIFICATIE VARCHAR2(255),
    KVKNUMMER VARCHAR2(20),
    NAAM VARCHAR2(200),
    RECHTSVORM VARCHAR2(100),
    REKENINGNUMMER VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE SOORTRECHTSVORM_ENUM (
    SOORTRECHTSVORM_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (1, 'BESLOTEN_VENNOOTSCHAP');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (2, 'COMMANDITAIRE_VENNOOTSCHAP');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (3, 'COOPERATIE_EUROPEES_ECONOMISCHE_SAMENWERKING');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (4, 'EUROPESE_COOPERATIEVE_VENNOOTSCHAP');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (5, 'EUROPESE_NAAMLOZE_VENNOOTSCHAP');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (6, 'KAPITAALVENNOOTSCHAP_BINNEN_EER');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (7, 'KAPITAALVENNOOTSCHAP_BUITEN_EER');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (8, 'KERKELIJKE_ORGANISATIE');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (9, 'LEEG');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (10, 'MAATSCHAP');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (11, 'NAAMLOZE_VENNOOTSCHAP');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (12, 'ONBEKEND');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (13, 'ONDERLINGE_WAARBORG_MAATSCHAPPIJ');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (14, 'OVERIGE_BUITENLANDSE_RECHTSPERSOON_VENNOOTSCHAP');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (15, 'OVERIG_PRIVAATRECHTELIJKE_RECHTSPERSOON');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (16, 'PUBLIEKRECHTELIJKE_RECHTSPERSOON');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (17, 'REDERIJ');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (18, 'STICHTING');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (19, 'VENNOOTSCHAP_ONDER_FIRMA');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (20, 'VERENIGING');
INSERT INTO SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID, VALUE) VALUES (21, 'VERENIGING_VAN_EIGENAARS');

CREATE TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN (
    KP_NTNTRLJKPRSN_NTRLJKPRSN_ID NUMBER PRIMARY KEY,
    NIETNATUURLIJKPERSOON_ID NUMBER,
    NATUURLIJKPERSOON_ID NUMBER
);

CREATE TABLE BOOLEAN_ENUM (
    BOOLEAN_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (1, 'JA');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (2, 'LEEG');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (3, 'NEE');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (4, 'ONBEKEND');

ALTER TABLE NIETNATUURLIJKPERSOON ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_NTRLJKPRSN_RCHTSPRSN ADD CONSTRAINT FK_KP_NTRLJKPRSN_RCHTSPRSN_1 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1898)

ALTER TABLE KP_NTRLJKPRSN_RCHTSPRSN ADD CONSTRAINT FK_KP_NTRLJKPRSN_RCHTSPRSN_2 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 1898)

ALTER TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_1 FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NIETNATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1970)

ALTER TABLE KP_NTNTRLJKPRSN_NTRLJKPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_2 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1970)

ALTER TABLE KP_NTNTRLJKPRSN_RCHTSPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_RCHTSPRSN_1 FOREIGN KEY (NIETNATUURLIJKPERSOON_ID) REFERENCES NIETNATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NIETNATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1971)

ALTER TABLE KP_NTNTRLJKPRSN_RCHTSPRSN ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_RCHTSPRSN_2 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 1971)

ALTER TABLE SBIACTIVITEITVESTIGING ADD CONSTRAINT FK_SBIACTIVITEITVESTIGING_VESTIGING FOREIGN KEY (VESTIGING_ID) REFERENCES VESTIGING (VESTIGING_ID);
-- unnamed (1 to 1..*, Connector_ID: 1861)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_IS_HOOFDVESTIGING_VAN FOREIGN KEY (IS_HOOFDVESTIGING_VAN_MAATSCHAPPELIJKEACTIVITEIT_ID) REFERENCES MAATSCHAPPELIJKEACTIVITEIT (MAATSCHAPPELIJKEACTIVITEIT_ID);
-- IS_HOOFDVESTIGING_VAN (0..1 to 0..1, Connector_ID: 1959)

ALTER TABLE MAATSCHAPPELIJKEACTIVITEIT ADD CONSTRAINT FK_MAATSCHAPPELIJKEACTIVITEIT_HEEFT_ALS_EIGENAAR FOREIGN KEY (HEEFT_ALS_EIGENAAR_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- HEEFT_ALS_EIGENAAR (0..1 to 1, Connector_ID: 1960)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_UITOEFENING_VAN_ACTIVITEITEN FOREIGN KEY (UITOEFENING_VAN_ACTIVITEITEN_MAATSCHAPPELIJKEACTIVITEIT_ID) REFERENCES MAATSCHAPPELIJKEACTIVITEIT (MAATSCHAPPELIJKEACTIVITEIT_ID);
-- UITOEFENING_VAN_ACTIVITEITEN (0..* to 1, Connector_ID: 1961)

ALTER TABLE MAATSCHAPPELIJKEACTIVITEIT ADD CONSTRAINT FK_MAATSCHAPPELIJKEACTIVITEIT_IS_FUNCTIONARIS_VAN FOREIGN KEY (IS_FUNCTIONARIS_VAN_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- IS_FUNCTIONARIS_VAN (0..* to 1.., Connector_ID: 1962)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_HEEFT FOREIGN KEY (HEEFT_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1968)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_HEEFT_HOOFDLOCATIE_IN_OF_OP FOREIGN KEY (HEEFT_HOOFDLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_HOOFDLOCATIE_IN_OF_OP (0..* to 0..1, Connector_ID: 2240)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_HEEFT_NEVENLOCATIE_IN_OF_OP FOREIGN KEY (HEEFT_NEVENLOCATIE_IN_OF_OP_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_NEVENLOCATIE_IN_OF_OP (0..* to 0..1, Connector_ID: 2244)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_ADRESSEERBAAROBJECT_ID) REFERENCES ADRESSEERBAAROBJECT (ADRESSEERBAAROBJECT_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_HEEFT_ALS_LOCATIE_ADRES FOREIGN KEY (HEEFT_ALS_LOCATIE_ADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_LOCATIE_ADRES (1 to 0..*, Connector_ID: 2282)

ALTER TABLE NUMMERAANDUIDING ADD CONSTRAINT FK_NUMMERAANDUIDING_GECONSTATEERD_ENUM_ID FOREIGN KEY (GECONSTATEERD_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NIETNATUURLIJKPERSOON ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_RECHTSVORM_ENUM_ID FOREIGN KEY (RECHTSVORM_ENUM_ID_SOORTRECHTSVORM_ENUM_ID) REFERENCES SOORTRECHTSVORM_ENUM (SOORTRECHTSVORM_ENUM_ID);
-- RECHTSVORM_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NIETNATUURLIJKPERSOON ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_INOPRICHTING_ENUM_ID FOREIGN KEY (INOPRICHTING_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INOPRICHTING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NIETNATUURLIJKPERSOON ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_INGESCHREVEN_ENUM_ID FOREIGN KEY (INGESCHREVEN_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INGESCHREVEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE MAATSCHAPPELIJKEACTIVITEIT ADD CONSTRAINT FK_MAATSCHAPPELIJKEACTIVITEIT_INDICATIEECONOMISCHACTIEF_ENUM_ID FOREIGN KEY (INDICATIEECONOMISCHACTIEF_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEECONOMISCHACTIEF_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEOVERLEDEN_ENUM_ID FOREIGN KEY (INDICATIEOVERLEDEN_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEOVERLEDEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID FOREIGN KEY (INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VESTIGING ADD CONSTRAINT FK_VESTIGING_COMMERCIELEVESTIGING_ENUM_ID FOREIGN KEY (COMMERCIELEVESTIGING_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- COMMERCIELEVESTIGING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

