CREATE TABLE [MEDEWERKER] (
    [MEDEWERKER_ID] INT PRIMARY KEY,
    [AANVRAGER_SUBSIDIE_ID] INT,
    [ACHTERNAAM] VARCHAR(200),
    [DATUMINDIENST] DATE,
    [DATUMUITDIENST] DATE,
    [EMAILADRES] VARCHAR(255),
    [EXTERN] BIT,
    [FUNCTIE] VARCHAR(50),
    [GESLACHTSAANDUIDING] VARCHAR(255),
    [IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID] INT,
    [IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID] INT,
    [MEDEWERKERIDENTIFICATIE] VARCHAR(255),
    [MEDEWERKERTOELICHTING] VARCHAR(255),
    [ROEPNAAM] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20),
    [VOORLETTERS] VARCHAR(20),
    [VOORVOEGSELACHTERNAAM] VARCHAR(255)
);

CREATE TABLE [ORGANISATORISCHEEENHEID] (
    [ORGANISATORISCHEEENHEID_ID] INT PRIMARY KEY,
    [DATUMONTSTAAN] DATE,
    [DATUMOPHEFFING] DATE,
    [EMAILADRES] VARCHAR(255),
    [FAXNUMMER] VARCHAR(20),
    [FORMATIE] VARCHAR(255),
    [HEEFT_KOSTENPLAATS_ID] INT,
    [IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID] INT,
    [NAAM] VARCHAR(50),
    [NAAMVERKORT] VARCHAR(255),
    [OMSCHRIJVING] VARCHAR(80),
    [ORGANISATIEIDENTIFICATIE] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20),
    [TOELICHTING] VARCHAR(255)
);

CREATE TABLE [SUBSIDIECOMPONENT] (
    [SUBSIDIECOMPONENT_ID] INT PRIMARY KEY,
    [GERESERVEERDBEDRAG] DECIMAL(10,2),
    [HEEFT_KOSTENPLAATS_ID] INT,
    [TOEGEKENDBEDRAG] DECIMAL(10,2)
);

CREATE TABLE [SUBSIDIEAANVRAAG] (
    [SUBSIDIEAANVRAAG_ID] INT PRIMARY KEY,
    [AANGEVRAAGDBEDRAG] DECIMAL(10,2),
    [BETREFT_SUBSIDIE_ID] INT,
    [DATUMINDIENING] DATE,
    [KENMERK] VARCHAR(80),
    [MONDT_UIT_SUBSIDIEBESCHIKKING_ID] INT,
    [ONTVANGSTBEVESTIGING] DATE,
    [VERWACHTEBESCHIKKING] DATE
);

CREATE TABLE [DOCUMENT] (
    [DOCUMENT_ID] INT PRIMARY KEY,
    [COCUMENTBESCHRIJVING] VARCHAR(255),
    [DATUMCREATIEDOCUMENT] DATE,
    [DATUMONTVANGSTDOCUMENT] DATE,
    [DATUMVERZENDINGDOCUMENT] DATE,
    [DOCUMENTAUTEUR] VARCHAR(200),
    [DOCUMENTIDENTIFICATIE] VARCHAR(255),
    [DOCUMENTTITEL] VARCHAR(200),
    [VERTROUWELIJKAANDUIDING] VARCHAR(20)
);

CREATE TABLE [KP_MDWRKR_ORGNSTRSCHNHD] (
    [KP_MDWRKR_ORGNSTRSCHNHD_ID] INT PRIMARY KEY,
    [MEDEWERKER_ID] INT,
    [ORGANISATORISCHEEENHEID_ID] INT
);

CREATE TABLE [KP_ZK_MDWRKR] (
    [KP_ZK_MDWRKR_ID] INT PRIMARY KEY,
    [ZAAK_ID] INT,
    [MEDEWERKER_ID] INT
);

CREATE TABLE [KOSTENPLAATS] (
    [KOSTENPLAATS_ID] INT PRIMARY KEY,
    [BTWCODE] VARCHAR(255),
    [BTWOMSCHRIJVING] VARCHAR(80),
    [KOSTENPLAATSSOORTCODE] DECIMAL(10,2),
    [KOSTENPLAATSSOORTOMSCHRIJVING] DECIMAL(10,2),
    [KOSTENPLAATSTYPECODE] DECIMAL(10,2),
    [KOSTENPLAATSTYPEOMSCHRIJVING] DECIMAL(10,2),
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] VARCHAR(200)
);

CREATE TABLE [TAAK] (
    [TAAK_ID] INT PRIMARY KEY,
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [PROJECTLEIDER_RECHTSPERSOON_ID] INT,
    [TAAKOMSCHRIJVING] NVARCHAR(MAX),
    [TERMIJN] INT
);

CREATE TABLE [RAPPORTAGEMOMENT] (
    [RAPPORTAGEMOMENT_ID] INT PRIMARY KEY,
    [DATUM] DATE,
    [HEEFT_DOCUMENT_ID] INT,
    [NAAM] VARCHAR(200),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [TERMIJN] INT
);

CREATE TABLE [ZAAK] (
    [ZAAK_ID] INT PRIMARY KEY,
    [ARCHIEFNOMINATIE] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMEINDEGEPLAND] DATE,
    [DATUMEINDEUITERLIJKEAFDOENING] DATE,
    [DATUMLAATSTEBETALING] DATE,
    [DATUMPUBLICATIE] DATE,
    [DATUMREGISTRATIE] DATE,
    [DATUMSTART] DATE,
    [DATUMVERNIETIGINGDOSSIER] DATE,
    [DUURVERLENGING] VARCHAR(255),
    [HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID] INT,
    [INDICATIEBETALING] VARCHAR(255),
    [INDICATIEDEELZAKEN] BIT,
    [INDICATIEOPSCHORTING] VARCHAR(255),
    [IS_DEELZAAK_VAN_ZAAK_ID] INT,
    [LEGES] VARCHAR(100),
    [OMSCHRIJVING] VARCHAR(80),
    [OMSCHRIJVINGRESULTAAT] VARCHAR(80),
    [REDENOPSCHORTING] VARCHAR(200),
    [REDENVERLENGING] VARCHAR(200),
    [TOELICHTING] VARCHAR(255),
    [TOELICHTINGRESULTAAT] VARCHAR(255),
    [VERTROUWELIJKHEID] VARCHAR(255),
    [ZAAKIDENTIFICATIE] VARCHAR(255),
    [ZAAKNIVEAU] VARCHAR(255)
);

CREATE TABLE [RECHTSPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [AANVRAGER_SUBSIDIE_ID] INT,
    [ADRESBINNENLAND] VARCHAR(255),
    [ADRESBUITENLAND] VARCHAR(255),
    [ADRESCORRESPONDENTIE] VARCHAR(100),
    [EMAILADRES] VARCHAR(80),
    [FAXNUMMER] VARCHAR(20),
    [IDENTIFICATIE] VARCHAR(255),
    [KVKNUMMER] VARCHAR(20),
    [NAAM] VARCHAR(200),
    [PROJECTLEIDER_RAPPORTAGEMOMENT_ID] INT,
    [RECHTSVORM] VARCHAR(100),
    [REKENINGNUMMER] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20)
);

CREATE TABLE [KP_ZK_DCMNT] (
    [KP_ZK_DCMNT_ID] INT PRIMARY KEY,
    [ZAAK_ID] INT,
    [DOCUMENT_ID] INT
);

CREATE TABLE [SECTOR] (
    [SECTOR_ID] INT PRIMARY KEY,
    [NAAM] VARCHAR(200),
    [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [SUBSIDIEBESCHIKKING] (
    [SUBSIDIEBESCHIKKING_ID] INT PRIMARY KEY,
    [BESCHIKKINGSNUMMER] VARCHAR(80),
    [BESCHIKTBEDRAG] DECIMAL(10,2),
    [BESLUIT] VARCHAR(80),
    [BETREFT_SUBSIDIE_ID] INT,
    [INTERNKENMERK] VARCHAR(80),
    [KENMERK] VARCHAR(80),
    [ONTVANGEN] DATE,
    [OPMERKINGEN] NVARCHAR(MAX)
);

CREATE TABLE [SUBSIDIENIVEAU_ENUM] (
    [SUBSIDIENIVEAU_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [SUBSIDIENIVEAU_ENUM] ([SUBSIDIENIVEAU_ENUM_ID], VALUE) VALUES
    (1, 'EUROPEES'),
    (2, 'GEMEENTE'),
    (3, 'NATIONAAL'),
    (4, 'PROVINCIE'),
    (5, 'REGIONAAL');

CREATE TABLE [SUBSIDIEPROGRAMMA] (
    [SUBSIDIEPROGRAMMA_ID] INT PRIMARY KEY,
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [GAAT_OVER_SUBSIDIE_ID] INT,
    [NAAM] VARCHAR(200),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [PROGRAMMABEGROTING] VARCHAR(255),
    [VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID] INT
);

CREATE TABLE [SUBSIDIE] (
    [SUBSIDIE_ID] INT PRIMARY KEY,
    [ACCOUNTANTSCONTROLE] BIT,
    [BEHANDELAAR_MEDEWERKER_ID] INT,
    [COFINANCIERING] VARCHAR(255),
    [DATUMBEHANDELTERMIJN] DATE,
    [DATUMBEWAARTERMIJN] DATE,
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [DATUMSUBSIDIEVASTSTELLING] DATE,
    [DATUMVERZENDINGEINDEAFREKENING] DATE,
    [DEADLINEINDIENING] DATE,
    [DOELSTELLING] VARCHAR(200),
    [GEREALISEERDEPROJECTKOSTEN] DECIMAL(10,2),
    [HEEFT_DOCUMENT_ID] INT,
    [HEEFT_KOSTENPLAATS_ID] INT,
    [HEEFT_RAPPORTAGEMOMENT_ID] INT,
    [HEEFT_TAAK_ID] INT,
    [HEEFT_ZAAK_ID] INT,
    [HOOGTESUBSIDIE] VARCHAR(255),
    [NIVEAU_ENUM_ID] INT,
    [ONDERWERP] VARCHAR(200),
    [ONTVANGENBEDRAG] DECIMAL(10,2),
    [OPMERKINGEN] NVARCHAR(MAX),
    [OPMERKINGENVOORSCHOTTEN] NVARCHAR(MAX),
    [PRESTATIESUBSIDIE] BIT,
    [SOCIALRETURNBEDRAG] DECIMAL(10,2),
    [SOCIALRETURNNAGEKOMEN] BIT,
    [SOCIALRETURNVERPLICHTING] BIT,
    [STATUS] VARCHAR(80),
    [SUBSIDIEBEDRAG] DECIMAL(10,2),
    [SUBSIDIESOORT] VARCHAR(80),
    [SUBSIDIEVASTSTELLINGBEDRAG] DECIMAL(10,2),
    [UITGAANDESUBSIDIE] BIT,
    [VALT_BINNEN_SECTOR_ID] INT,
    [VERANTWOORDENOP] DATE,
    [VERSTREKKER_RECHTSPERSOON_ID] INT
);

ALTER TABLE [KP_ZK_DCMNT] ADD CONSTRAINT FK_KP_ZK_DCMNT_1 FOREIGN KEY ([ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- ZAAK (many-to-many junction, Connector_ID: 2132)

ALTER TABLE [KP_ZK_DCMNT] ADD CONSTRAINT FK_KP_ZK_DCMNT_2 FOREIGN KEY ([DOCUMENT_ID]) REFERENCES [DOCUMENT] ([DOCUMENT_ID]);
-- DOCUMENT (many-to-many junction, Connector_ID: 2132)

ALTER TABLE [KP_MDWRKR_ORGNSTRSCHNHD] ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_1 FOREIGN KEY ([MEDEWERKER_ID]) REFERENCES [MEDEWERKER] ([MEDEWERKER_ID]);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2175)

ALTER TABLE [KP_MDWRKR_ORGNSTRSCHNHD] ADD CONSTRAINT FK_KP_MDWRKR_ORGNSTRSCHNHD_2 FOREIGN KEY ([ORGANISATORISCHEEENHEID_ID]) REFERENCES [ORGANISATORISCHEEENHEID] ([ORGANISATORISCHEEENHEID_ID]);
-- ORGANISATORISCHEEENHEID (many-to-many junction, Connector_ID: 2175)

ALTER TABLE [KP_ZK_MDWRKR] ADD CONSTRAINT FK_KP_ZK_MDWRKR_1 FOREIGN KEY ([ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- ZAAK (many-to-many junction, Connector_ID: 2190)

ALTER TABLE [KP_ZK_MDWRKR] ADD CONSTRAINT FK_KP_ZK_MDWRKR_2 FOREIGN KEY ([MEDEWERKER_ID]) REFERENCES [MEDEWERKER] ([MEDEWERKER_ID]);
-- MEDEWERKER (many-to-many junction, Connector_ID: 2190)

ALTER TABLE [TAAK] ADD CONSTRAINT FK_TAAK_PROJECTLEIDER FOREIGN KEY ([PROJECTLEIDER_RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- PROJECTLEIDER (0..* to 0..1, Connector_ID: 589)

ALTER TABLE [SUBSIDIEPROGRAMMA] ADD CONSTRAINT FK_SUBSIDIEPROGRAMMA_VERANTWOORDELIJK_VOOR FOREIGN KEY ([VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID]) REFERENCES [ORGANISATORISCHEEENHEID] ([ORGANISATORISCHEEENHEID_ID]);
-- VERANTWOORDELIJK_VOOR (0..* to 1, Connector_ID: 590)

ALTER TABLE [SUBSIDIECOMPONENT] ADD CONSTRAINT FK_SUBSIDIECOMPONENT_HEEFT FOREIGN KEY ([HEEFT_KOSTENPLAATS_ID]) REFERENCES [KOSTENPLAATS] ([KOSTENPLAATS_ID]);
-- HEEFT (0..* to 1, Connector_ID: 591)

ALTER TABLE [SUBSIDIEAANVRAAG] ADD CONSTRAINT FK_SUBSIDIEAANVRAAG_MONDT_UIT FOREIGN KEY ([MONDT_UIT_SUBSIDIEBESCHIKKING_ID]) REFERENCES [SUBSIDIEBESCHIKKING] ([SUBSIDIEBESCHIKKING_ID]);
-- MONDT_UIT (1 to 0..1, Connector_ID: 592)

ALTER TABLE [SUBSIDIEPROGRAMMA] ADD CONSTRAINT FK_SUBSIDIEPROGRAMMA_GAAT_OVER FOREIGN KEY ([GAAT_OVER_SUBSIDIE_ID]) REFERENCES [SUBSIDIE] ([SUBSIDIE_ID]);
-- GAAT_OVER (0..1 to 1..*, Connector_ID: 593)

ALTER TABLE [SUBSIDIEBESCHIKKING] ADD CONSTRAINT FK_SUBSIDIEBESCHIKKING_BETREFT FOREIGN KEY ([BETREFT_SUBSIDIE_ID]) REFERENCES [SUBSIDIE] ([SUBSIDIE_ID]);
-- BETREFT (0..1 to 1, Connector_ID: 595)

ALTER TABLE [SUBSIDIEAANVRAAG] ADD CONSTRAINT FK_SUBSIDIEAANVRAAG_BETREFT FOREIGN KEY ([BETREFT_SUBSIDIE_ID]) REFERENCES [SUBSIDIE] ([SUBSIDIE_ID]);
-- BETREFT (1 to 1, Connector_ID: 597)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_HEEFT FOREIGN KEY ([HEEFT_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT (0..1 to 0..1, Connector_ID: 598)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_HEEFT_2 FOREIGN KEY ([HEEFT_DOCUMENT_ID]) REFERENCES [DOCUMENT] ([DOCUMENT_ID]);
-- HEEFT (0..* to 0..1, Connector_ID: 599)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_HEEFT_3 FOREIGN KEY ([HEEFT_KOSTENPLAATS_ID]) REFERENCES [KOSTENPLAATS] ([KOSTENPLAATS_ID]);
-- HEEFT (0..* to 0..1, Connector_ID: 600)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_HEEFT_4 FOREIGN KEY ([HEEFT_TAAK_ID]) REFERENCES [TAAK] ([TAAK_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 601)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_VERSTREKKER FOREIGN KEY ([VERSTREKKER_RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- VERSTREKKER (0..* to 0..1, Connector_ID: 602)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_BEHANDELAAR FOREIGN KEY ([BEHANDELAAR_MEDEWERKER_ID]) REFERENCES [MEDEWERKER] ([MEDEWERKER_ID]);
-- BEHANDELAAR (0..* to 0..1, Connector_ID: 603)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_VALT_BINNEN FOREIGN KEY ([VALT_BINNEN_SECTOR_ID]) REFERENCES [SECTOR] ([SECTOR_ID]);
-- VALT_BINNEN (0..* to 0..1, Connector_ID: 604)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_HEEFT_5 FOREIGN KEY ([HEEFT_RAPPORTAGEMOMENT_ID]) REFERENCES [RAPPORTAGEMOMENT] ([RAPPORTAGEMOMENT_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 606)

ALTER TABLE [RAPPORTAGEMOMENT] ADD CONSTRAINT FK_RAPPORTAGEMOMENT_HEEFT FOREIGN KEY ([HEEFT_DOCUMENT_ID]) REFERENCES [DOCUMENT] ([DOCUMENT_ID]);
-- HEEFT (0..1 to 0..*, Connector_ID: 607)

ALTER TABLE [RECHTSPERSOON] ADD CONSTRAINT FK_RECHTSPERSOON_PROJECTLEIDER FOREIGN KEY ([PROJECTLEIDER_RAPPORTAGEMOMENT_ID]) REFERENCES [RAPPORTAGEMOMENT] ([RAPPORTAGEMOMENT_ID]);
-- PROJECTLEIDER (0..1 to 0..*, Connector_ID: 1907)

ALTER TABLE [RECHTSPERSOON] ADD CONSTRAINT FK_RECHTSPERSOON_AANVRAGER FOREIGN KEY ([AANVRAGER_SUBSIDIE_ID]) REFERENCES [SUBSIDIE] ([SUBSIDIE_ID]);
-- AANVRAGER (0..1 to 0..*, Connector_ID: 1924)

ALTER TABLE [ORGANISATORISCHEEENHEID] ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_IS_DEEL_VAN FOREIGN KEY ([IS_DEEL_VAN_ORGANISATORISCHEEENHEID_ID]) REFERENCES [ORGANISATORISCHEEENHEID] ([ORGANISATORISCHEEENHEID_ID]);
-- IS_DEEL_VAN (1 to 0..1, Connector_ID: 2059)

ALTER TABLE [ORGANISATORISCHEEENHEID] ADD CONSTRAINT FK_ORGANISATORISCHEEENHEID_HEEFT FOREIGN KEY ([HEEFT_KOSTENPLAATS_ID]) REFERENCES [KOSTENPLAATS] ([KOSTENPLAATS_ID]);
-- HEEFT (0..1 to 1, Connector_ID: 2063)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_HEEFT_BETREKKING_OP_ANDERE FOREIGN KEY ([HEEFT_BETREKKING_OP_ANDERE_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- HEEFT_BETREKKING_OP_ANDERE (1 to 0..*, Connector_ID: 2108)

ALTER TABLE [ZAAK] ADD CONSTRAINT FK_ZAAK_IS_DEELZAAK_VAN FOREIGN KEY ([IS_DEELZAAK_VAN_ZAAK_ID]) REFERENCES [ZAAK] ([ZAAK_ID]);
-- IS_DEELZAAK_VAN (1 to 0..1, Connector_ID: 2121)

ALTER TABLE [MEDEWERKER] ADD CONSTRAINT FK_MEDEWERKER_IS_VERANTWOORDELIJK_VOOR FOREIGN KEY ([IS_VERANTWOORDELIJK_VOOR_ORGANISATORISCHEEENHEID_ID]) REFERENCES [ORGANISATORISCHEEENHEID] ([ORGANISATORISCHEEENHEID_ID]);
-- IS_VERANTWOORDELIJK_VOOR (0..1 to 0..1, Connector_ID: 2166)

ALTER TABLE [MEDEWERKER] ADD CONSTRAINT FK_MEDEWERKER_AANVRAGER FOREIGN KEY ([AANVRAGER_SUBSIDIE_ID]) REFERENCES [SUBSIDIE] ([SUBSIDIE_ID]);
-- AANVRAGER (0..1 to 0..*, Connector_ID: 2181)

ALTER TABLE [MEDEWERKER] ADD CONSTRAINT FK_MEDEWERKER_IS_CONTACTPERSOON_VOOR FOREIGN KEY ([IS_CONTACTPERSOON_VOOR_ORGANISATORISCHEEENHEID_ID]) REFERENCES [ORGANISATORISCHEEENHEID] ([ORGANISATORISCHEEENHEID_ID]);
-- IS_CONTACTPERSOON_VOOR (0..1 to 0..1, Connector_ID: 2185)

ALTER TABLE [SUBSIDIE] ADD CONSTRAINT FK_SUBSIDIE_NIVEAU_ENUM_ID FOREIGN KEY ([NIVEAU_ENUM_ID]) REFERENCES [SUBSIDIENIVEAU_ENUM] ([SUBSIDIENIVEAU_ENUM_ID]);
-- NIVEAU_ENUM_ID (1 to 1, Connector_ID: enum_ref)

