CREATE TABLE MAATREGEL (
    MAATREGEL_ID VARCHAR2(255) PRIMARY KEY,
        DATUM_AANVANG_MAATREGEL DATE,
        DATUM_EINDE_MAATREGEL DATE,
        DATUM_VASTSTELLING_MAATREGEL DATE,
        TYPE_MAATREGEL VARCHAR2(255)
);

CREATE TABLE BOETE (
    MAATREGEL_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG_BOETE NUMBER(10,2),
        BOETEVORM VARCHAR2(255),
        REDEN_BOETE VARCHAR2(255),
        VOORWAARDE_BOETE VARCHAR2(255)
);

CREATE TABLE MAATREGEL_OP_UITKERING (
    MAATREGEL_ID VARCHAR2(255) PRIMARY KEY,
        CODE_REDEN_MAATREGEL VARCHAR2(255),
        MOTIVATIE_VERMINDERING_MAATREGEL VARCHAR2(255),
        PERCENTAGE_MAATREGEL VARCHAR2(255)
);

CREATE TABLE AFWIJKENDE_MAATREGEL (
    MAATREGEL_ID VARCHAR2(255) PRIMARY KEY,
        AFWIJKENDE_MAATREGEL_REFEREERT_NAAR_MAATREGEL_OP_UITKERING_MAATREGEL_OP_UITKERING_ID VARCHAR2(255),
        BEDRAG NUMBER(10,2),
        CODE_REDEN_AFWIJKING_MAATREGEL VARCHAR2(255),
        MOTIVATIE_AFWIJKING_MAATREGEL VARCHAR2(255),
        PERCENTAGE VARCHAR2(255)
);

CREATE TABLE NORMAFWIJKING (
    NORMAFWIJKING_ID VARCHAR2(255) PRIMARY KEY,
        DATUM_VASTSTELLING_NORMAFWIJKING DATE,
        DATUM_VASTSTELLING_VERWIJTBAARHEID DATE,
        MOTIVATIE_VERWIJTBAARHEID DATE,
        NORMAFWIJKING_LEIDT_TOT_MAATREGEL_MAATREGEL_ID VARCHAR2(255),
        RECIDIVE VARCHAR2(255),
        TYPE_NORMAFWIJKING VARCHAR2(255),
        VERWIJTBAARHEID VARCHAR2(255)
);

ALTER TABLE AFWIJKENDE_MAATREGEL ADD CONSTRAINT FK_AFWIJKENDE_MAATREGEL_GEN_MAATREGEL FOREIGN KEY (MAATREGEL_ID) REFERENCES MAATREGEL (MAATREGEL_ID);
-- Generalization to MAATREGEL

ALTER TABLE BOETE ADD CONSTRAINT FK_BOETE_GEN_MAATREGEL FOREIGN KEY (MAATREGEL_ID) REFERENCES MAATREGEL (MAATREGEL_ID);
-- Generalization to MAATREGEL

ALTER TABLE MAATREGEL_OP_UITKERING ADD CONSTRAINT FK_MAATREGEL_OP_UITKERING_GEN_MAATREGEL FOREIGN KEY (MAATREGEL_ID) REFERENCES MAATREGEL (MAATREGEL_ID);
-- Generalization to MAATREGEL

ALTER TABLE AFWIJKENDE_MAATREGEL ADD CONSTRAINT FK_AFWIJKENDE_MAATREGEL_AFWIJKENDE_MAATREGEL_REFEREERT_NAAR_MAATREGEL_OP_UITKERING FOREIGN KEY (AFWIJKENDE_MAATREGEL_REFEREERT_NAAR_MAATREGEL_OP_UITKERING_MAATREGEL_OP_UITKERING_ID) REFERENCES MAATREGEL (MAATREGEL_ID);
-- AFWIJKENDE_MAATREGEL_REFEREERT_NAAR_MAATREGEL_OP_UITKERING (1..1 to 1..1, Connector_ID: 1699)

ALTER TABLE NORMAFWIJKING ADD CONSTRAINT FK_NORMAFWIJKING_NORMAFWIJKING_LEIDT_TOT_MAATREGEL FOREIGN KEY (NORMAFWIJKING_LEIDT_TOT_MAATREGEL_MAATREGEL_ID) REFERENCES MAATREGEL (MAATREGEL_ID);
-- NORMAFWIJKING_LEIDT_TOT_MAATREGEL (0..1 to 1..1, Connector_ID: 1697)

