CREATE TABLE ONDERWERP (
    ONDERWERP_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE ZAAKTYPE (
    ZAAKTYPE_ID VARCHAR2(255) PRIMARY KEY,
        ARCHIEFCODE VARCHAR2(20),
        DATUMBEGINGELDIGHEIDZAAKTYPE DATE,
        DATUMEINDEGELDIGHEIDZAAKTYPE DATE,
        DOORLOOPTIJDBEHANDELING TIMESTAMP,
        INDICATIEPUBLICATIE VARCHAR2(255),
        PUBLICATIETEKST VARCHAR2(255),
        SERVICENORMBEHANDELING VARCHAR2(255),
        TREFWOORD VARCHAR2(255),
        VERTROUWELIJKAANDUIDING VARCHAR2(20),
        ZAAKCATEGORIE VARCHAR2(255),
        ZAAKTYPEOMSCHRIJVING VARCHAR2(80),
        ZAAKTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR2(255) PRIMARY KEY,
        BETREFT_ZAAKTYPE_ID VARCHAR2(255)
);

CREATE TABLE DOMEIN_TAAKVELD (
    DOMEIN_TAAKVELD_ID VARCHAR2(255) PRIMARY KEY,
        VALT_BINNEN_ONDERWERP_ID VARCHAR2(255),
        VALT_BINNEN_PRODUCT_ID VARCHAR2(255)
);

CREATE TABLE DIENST (
    DIENST_ID VARCHAR2(255) PRIMARY KEY,
        BETREFT_PRODUCT_ID VARCHAR2(255),
        HEEFT_ONDERWERP_ID VARCHAR2(255),
        START_ZAAKTYPE_ID VARCHAR2(255),
        VALT_BINNEN_DOMEIN_TAAKVELD_ID VARCHAR2(255)
);

CREATE TABLE PRIJZENBOEK (
    PRIJZENBOEK_ID VARCHAR2(255) PRIMARY KEY,
        HEEFT_PRIJS_PRODUCT_ID VARCHAR2(255)
);

ALTER TABLE DIENST ADD CONSTRAINT FK_DIENST_BETREFT FOREIGN KEY (BETREFT_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 632)

ALTER TABLE DIENST ADD CONSTRAINT FK_DIENST_HEEFT FOREIGN KEY (HEEFT_ONDERWERP_ID) REFERENCES ONDERWERP (ONDERWERP_ID);
-- HEEFT (0..* to 1, Connector_ID: 633)

ALTER TABLE DIENST ADD CONSTRAINT FK_DIENST_START FOREIGN KEY (START_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- START (0..* to 0..1, Connector_ID: 634)

ALTER TABLE DIENST ADD CONSTRAINT FK_DIENST_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_DOMEIN_TAAKVELD_ID) REFERENCES DOMEIN_TAAKVELD (DOMEIN_TAAKVELD_ID);
-- VALT_BINNEN (0..* to 1, Connector_ID: 635)

ALTER TABLE DOMEIN_TAAKVELD ADD CONSTRAINT FK_DOMEIN_TAAKVELD_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 630)

ALTER TABLE DOMEIN_TAAKVELD ADD CONSTRAINT FK_DOMEIN_TAAKVELD_VALT_BINNEN_2 FOREIGN KEY (VALT_BINNEN_ONDERWERP_ID) REFERENCES ONDERWERP (ONDERWERP_ID);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 631)

ALTER TABLE PRIJZENBOEK ADD CONSTRAINT FK_PRIJZENBOEK_HEEFT_PRIJS FOREIGN KEY (HEEFT_PRIJS_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- HEEFT_PRIJS (None to 0..*, Connector_ID: 615)

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_BETREFT FOREIGN KEY (BETREFT_ZAAKTYPE_ID) REFERENCES ZAAKTYPE (ZAAKTYPE_ID);
-- BETREFT (0..1 to 0..*, Connector_ID: 614)

