CREATE TABLE WAARDEPEILING (
    WAARDEPEILING_ID NUMBER PRIMARY KEY,
    BIJGEVOEGD_BEWIJS NUMBER(1),
    BRONTYPE VARCHAR2(255),
    DATUM_AANSPRAAK_VERMOGENSCOMPONENT DATE,
    LINK_NAAR_BEWIJS VARCHAR2(255),
    PEILMOMENT DATE,
    WAARDESOORT_VERMOGENSCOMPONENT VARCHAR2(255),
    WAARDE_VERMOGENSCOMPONENT VARCHAR2(255)
);

CREATE TABLE VERMOGENSCOMPONENT (
    VERMOGENSCOMPONENT_ID NUMBER PRIMARY KEY,
    CODE_SOORT_VERMOGENSCOMPONENT VARCHAR2(255),
    DATUM_VASTSTELLING_VERMOGENCOMPONENT DATE,
    IDENTIFICATIE VARCHAR2(255),
    NOG_AAN_TE_SPREKEN_VERMOGEN VARCHAR2(255),
    VERMOGENSCOMPONENT_IS_GEWAARDEERD_MET_WAARDEPEILING_WAARDEPEILING_ID NUMBER,
    VRIJ_TE_LATEN_VERMOGEN VARCHAR2(255)
);

CREATE TABLE BANKREKENING (
    VERMOGENSCOMPONENT_ID NUMBER PRIMARY KEY,
    BANKREKENINGNUMMER VARCHAR2(255),
    BRONTYPE VARCHAR2(255),
    DATUM_AANVANG_BANKREKENING DATE,
    DATUM_EINDE_BANKREKENING DATE,
    IBAN VARCHAR2(255),
    REKENINGTYPE VARCHAR2(255),
    TENAAMSTELLING VARCHAR2(255),
    VOORKEUR_BANKREKENING NUMBER(1)
);

CREATE TABLE ONROEREND_GOED (
    VERMOGENSCOMPONENT_ID NUMBER PRIMARY KEY,
    OVERWAARDE VARCHAR2(255)
);

CREATE TABLE MOTORVOERTUIG (
    VERMOGENSCOMPONENT_ID NUMBER PRIMARY KEY,
    KENTEKEN VARCHAR2(255),
    SOORT_MOTORVOERTUIG VARCHAR2(255)
);

CREATE TABLE HYPOTHEEK (
    VERMOGENSCOMPONENT_ID NUMBER PRIMARY KEY,
    HYPOTHEEK_RUST_OP_ONROEREND_GOED_ONROEREND_GOED_ID NUMBER,
    OVERWAARDE VARCHAR2(255)
);

ALTER TABLE BANKREKENING ADD CONSTRAINT FK_BANKREKENING_GEN_VERMOGENSCOMPONENT FOREIGN KEY (VERMOGENSCOMPONENT_ID) REFERENCES VERMOGENSCOMPONENT (VERMOGENSCOMPONENT_ID);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE HYPOTHEEK ADD CONSTRAINT FK_HYPOTHEEK_GEN_VERMOGENSCOMPONENT FOREIGN KEY (VERMOGENSCOMPONENT_ID) REFERENCES VERMOGENSCOMPONENT (VERMOGENSCOMPONENT_ID);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE MOTORVOERTUIG ADD CONSTRAINT FK_MOTORVOERTUIG_GEN_VERMOGENSCOMPONENT FOREIGN KEY (VERMOGENSCOMPONENT_ID) REFERENCES VERMOGENSCOMPONENT (VERMOGENSCOMPONENT_ID);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE ONROEREND_GOED ADD CONSTRAINT FK_ONROEREND_GOED_GEN_VERMOGENSCOMPONENT FOREIGN KEY (VERMOGENSCOMPONENT_ID) REFERENCES VERMOGENSCOMPONENT (VERMOGENSCOMPONENT_ID);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE VERMOGENSCOMPONENT ADD CONSTRAINT FK_VERMOGENSCOMPONENT_VERMOGENSCOMPONENT_IS_GEWAARDEERD_MET_WAARDEPEILING FOREIGN KEY (VERMOGENSCOMPONENT_IS_GEWAARDEERD_MET_WAARDEPEILING_WAARDEPEILING_ID) REFERENCES WAARDEPEILING (WAARDEPEILING_ID);
-- VERMOGENSCOMPONENT_IS_GEWAARDEERD_MET_WAARDEPEILING (0..* to 1..1, Connector_ID: 866)

ALTER TABLE HYPOTHEEK ADD CONSTRAINT FK_HYPOTHEEK_HYPOTHEEK_RUST_OP_ONROEREND_GOED FOREIGN KEY (HYPOTHEEK_RUST_OP_ONROEREND_GOED_ONROEREND_GOED_ID) REFERENCES VERMOGENSCOMPONENT (VERMOGENSCOMPONENT_ID);
-- HYPOTHEEK_RUST_OP_ONROEREND_GOED (1..1 to 0..*, Connector_ID: 869)

