CREATE TABLE `KP_ALMNTT_PRMR_INKMSTNCMPNNT` (
    `KP_ALMNTT_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `ALIMENTATIE_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `INKOMSTENVERHOUDING` (
    `INKOMSTENVERHOUDING_ID` INT PRIMARY KEY,
    `CATEGORIE_INKOMSTEN` VARCHAR(255),
    `INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT_INKOMSTENCOMPONENT_ID` INT,
    `PERIODE_EINDDATUM` DATE,
    `PERIODE_STARTDATUM` DATE
) ENGINE=InnoDB;

CREATE TABLE `KP_VRLGNG_DR_BT_INKMSTNVRMNDRNG` (
    `KP_VRLGNG_DR_BT_INKMSTNVRMNDRNG_ID` INT PRIMARY KEY,
    `VERLAGING_DOOR_BOETE_ID` INT,
    `INKOMSTENVERMINDERING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `DERTIENDE_MAAND_EINDEJAARSUITKERING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `PENSIOEN` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `BESLAG_OP_PENSIOEN` BOOLEAN,
    `INKOMSTENSOORT_PENSIOEN` VARCHAR(255),
    `LOONHEFFINGSKORTING` BOOLEAN,
    `PENSIOEN_HEEFT_LOONBESLAG_INKOMSTENCOMPONENT_ID` INT,
    `PENSIOEN_HEEFT_VAKANTIEGELD_INKOMSTENCOMPONENT_ID` INT,
    `PERIODICITEIT_UITBETALING_PENSIOEN` VARCHAR(255),
    `UITBETALING_VAKANTIEGELD_PENSIOEN` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_VRLGNG_DR_MTRGL_INKMSTNVRMNDRNG` (
    `KP_VRLGNG_DR_MTRGL_INKMSTNVRMNDRNG_ID` INT PRIMARY KEY,
    `VERLAGING_DOOR_MAATREGEL_ID` INT,
    `INKOMSTENVERMINDERING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_TE_BTLN_ALMNTT_KSTNCMPNNT` (
    `KP_TE_BTLN_ALMNTT_KSTNCMPNNT_ID` INT PRIMARY KEY,
    `TE_BETALEN_ALIMENTATIE_ID` INT,
    `KOSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `VERGOEDING_IN_NATURA` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `VERLAGING_DOOR_MAATREGEL` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `KP_SCNDR_INKMSTNCMPNNT_INKMSTNCMPNNT` (
    `KP_SCNDR_INKMSTNCMPNNT_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `SECUNDAIR_INKOMSTENCOMPONENT_ID` INT,
    `INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_RSKSTN_NR_HET_WRK__KSTNCMPNNT` (
    `KP_RSKSTN_NR_HET_WRK__KSTNCMPNNT_ID` INT PRIMARY KEY,
    `REISKOSTEN_NAAR_HET_WERK__ID` INT,
    `KOSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `STUDIEFINANCIERING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `DAADWERKELIJK_GENOTEN` BOOLEAN,
    `INKOMSTENSOORT_STUDIEFINANCIERING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_UTKRNG_PRMR_INKMSTNCMPNNT` (
    `KP_UTKRNG_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `UITKERING_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `INKOMSTENCOMPONENT` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `BIJGEVOEGD_BEWIJS` BOOLEAN,
    `BOEKINGSDATUM` DATE,
    `BRUTO_NETTO` VARCHAR(255),
    `INKOMSTEN` VARCHAR(255),
    `INKOMSTENCOMPONENTTYPE` VARCHAR(255),
    `LINK_NAAR_BEWIJS` VARCHAR(255),
    `PEILMOMENT` DATE,
    `PERIODE_EINDDATUM` DATE,
    `PERIODE_STARTDATUM` DATE
) ENGINE=InnoDB;

CREATE TABLE `INKOMSTENVERMINDERING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `SECUNDAIR_INKOMSTENCOMPONENT` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `EIGEN_BEDRIJF` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `AANTAL_UREN_PER_WEEK_BESTEED_AAN_WERK` VARCHAR(255),
    `INGESCHREVEN_BIJ_KVK` BOOLEAN,
    `RECHT_OP_ZELFSTANDIGENAFTREK` BOOLEAN,
    `SOORT_BEDRIJF` VARCHAR(255),
    `TOESTEMMING_GEMEENTE_PARTTIME_ONDERNEMEN` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `ONDERHOUDSVERHOUDING` (
    `ONDERHOUDSVERHOUDING_ID` INT PRIMARY KEY,
    `ONDERHOUDSVERHOUDINGTYPE` VARCHAR(255),
    `ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT_ONDERHOUDSPLICHT_ID` INT,
    `PERIODE_EINDDATUM` DATE,
    `PERIODE_STARTDATUM` DATE
) ENGINE=InnoDB;

CREATE TABLE `UITKERING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `BESLAG_OP_UITKERING` BOOLEAN,
    `INKOMSTENSOORT_UITKERING` VARCHAR(255),
    `LOONHEFFINGSKORTING` BOOLEAN,
    `PERIODICITEIT_UITBETALING_UITKERING` VARCHAR(255),
    `TOESLAG_OP_UITKERING` BOOLEAN,
    `UITKERING_HEEFT_LOONBESLAG_INKOMSTENCOMPONENT_ID` INT,
    `UITKERING_HEEFT_VAKANTIEGELD_INKOMSTENCOMPONENT_ID` INT,
    `UITKERING_HEEFT_VERLAGING_DOOR_BOETE_INKOMSTENCOMPONENT_ID` INT,
    `UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL_INKOMSTENCOMPONENT_ID` INT,
    `UITKERING_VERLAAGD_DOOR_BOETE` BOOLEAN,
    `UITKERING_VERLAAGD_DOOR_MAATREGEL` BOOLEAN,
    `VAKANTIEGELD_JAARLIJKS_ONTVANGEN` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `STAGE` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `MAALTIJDVERGOEDING` DATETIME,
    `ONKOSTENVERGOEDING` DECIMAL(10,2),
    `PERIODICITEIT_UITBETALING_LOON` VARCHAR(255),
    `REISKOSTENVERGOEDING` DECIMAL(10,2),
    `STAGE_HEEFT_MAALTIJDVERGOEDING_INKOMSTENCOMPONENT_ID` INT,
    `STAGE_HEEFT_ONKOSTENVERGOEDING_INKOMSTENCOMPONENT_ID` INT,
    `STAGE_HEEFT_REISKOSTENVERGOEDING_INKOMSTENCOMPONENT_ID` INT,
    `STAGE_HEEFT_VERGOEDING_IN_NATURA_INKOMSTENCOMPONENT_ID` INT,
    `VERGOEDING_IN_NATURA` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `EIGEN_BIJDRAGE` (
    `KOSTENCOMPONENT_ID` INT PRIMARY KEY,
    `SOORT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BESLAG_OP_INKOMEN` (
    `KOSTENCOMPONENT_ID` INT PRIMARY KEY,
    `SOORT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `DRAAGKRACHT` (
    `DRAAGKRACHT_ID` INT PRIMARY KEY,
    `DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME_DRAAGKRACHTREGIME_ID` INT,
    `EINDDATUM` DATE,
    `STARTDATUM` DATE
) ENGINE=InnoDB;

CREATE TABLE `VERLAGING_DOOR_BOETE` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `KP_STG_PRMR_INKMSTNCMPNNT` (
    `KP_STG_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `STAGE_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_PNSN_PRMR_INKMSTNCMPNNT` (
    `KP_PNSN_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `PENSIOEN_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRGDNG_IN_NTR_VRGDNG` (
    `KP_VRGDNG_IN_NTR_VRGDNG_ID` INT PRIMARY KEY,
    `VERGOEDING_IN_NATURA_ID` INT,
    `VERGOEDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `HOBBY` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `AANTAL_UREN_PER_WEEK_BESTEED_AAN_HOBBY` VARCHAR(255),
    `BESCHRIJVING_HOBBY` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `REISKOSTENVERGOEDING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `KP_STDFNNCRNG_PRMR_INKMSTNCMPNNT` (
    `KP_STDFNNCRNG_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `STUDIEFINANCIERING_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_LNBSLG_INKMSTNVRMNDRNG` (
    `KP_LNBSLG_INKMSTNVRMNDRNG_ID` INT PRIMARY KEY,
    `LOONBESLAG_ID` INT,
    `INKOMSTENVERMINDERING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_EGN_BJDRG_KSTNCMPNNT` (
    `KP_EGN_BJDRG_KSTNCMPNNT_ID` INT PRIMARY KEY,
    `EIGEN_BIJDRAGE_ID` INT,
    `KOSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `PRIMAIR_INKOMSTENCOMPONENT` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `ONDERHOUDSPLICHT` (
    `ONDERHOUDSPLICHT_ID` INT PRIMARY KEY,
    `BIJDRAGE` VARCHAR(255),
    `BOEKINGSDATUM` DATE,
    `ONDERHOUDSPLICHTTYPE` VARCHAR(255),
    `PEILMOMENT` DATE,
    `PERIODE_EINDDATUM` DATE,
    `PERIODE_STARTDATUM` DATE
) ENGINE=InnoDB;

CREATE TABLE `KP_HBBY_PRMR_INKMSTNCMPNNT` (
    `KP_HBBY_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `HOBBY_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BTLD_WRK_PRMR_INKMSTNCMPNNT` (
    `KP_BTLD_WRK_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `BETAALD_WERK_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `TE_BETALEN_ALIMENTATIE` (
    `KOSTENCOMPONENT_ID` INT PRIMARY KEY,
    `SOORT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_VKNTGLD_SCNDR_INKMSTNCMPNNT` (
    `KP_VKNTGLD_SCNDR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `VAKANTIEGELD_ID` INT,
    `SECUNDAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_HFFNGSKRTNG_SCNDR_INKMSTNCMPNNT` (
    `KP_HFFNGSKRTNG_SCNDR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `HEFFINGSKORTING_ID` INT,
    `SECUNDAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `MAALTIJDVERGOEDING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `VERGOEDING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `KP_ANDR_INKMN_PRMR_INKMSTNCMPNNT` (
    `KP_ANDR_INKMN_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `ANDER_INKOMEN_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_BSLG_OP_INKMN_KSTNCMPNNT` (
    `KP_BSLG_OP_INKMN_KSTNCMPNNT_ID` INT PRIMARY KEY,
    `BESLAG_OP_INKOMEN_ID` INT,
    `KOSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KOSTENCOMPONENT` (
    `KOSTENCOMPONENT_ID` INT PRIMARY KEY,
    `BEDRAG` DECIMAL(10,2)
) ENGINE=InnoDB;

CREATE TABLE `ANDER_INKOMEN` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `BESCHRIJVING_ANDER_INKOMEN` VARCHAR(255),
    `CATEGORIE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `BETAALD_WERK` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `ARBEIDSCONTRACT` BOOLEAN,
    `BEGINDATUM_CONTRACT` DATE,
    `BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING_INKOMSTENCOMPONENT_ID` INT,
    `BETAALD_WERK_HEEFT_HEFFINGSKORTING_INKOMSTENCOMPONENT_ID` INT,
    `BETAALD_WERK_HEEFT_LOONBESLAG_INKOMSTENCOMPONENT_ID` INT,
    `BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING_INKOMSTENCOMPONENT_ID` INT,
    `BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING_INKOMSTENCOMPONENT_ID` INT,
    `BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING_INKOMSTENCOMPONENT_ID` INT,
    `BETAALD_WERK_HEEFT_VAKANTIEGELD_INKOMSTENCOMPONENT_ID` INT,
    `EINDDATUM_CONTRACT` DATE,
    `INKOMSTENSOORT_BETAALD_WERK` VARCHAR(255),
    `INKOMSTEN_UIT_IKB_REGELING` BOOLEAN,
    `LOONDIENST` BOOLEAN,
    `LOONHEFFINGSNUMMER` VARCHAR(255),
    `PERIODICITEIT_UITBETALING_LOON` VARCHAR(255),
    `SOORT_CONTRACT` VARCHAR(255),
    `URENVERMINDERING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_INKMSTNVRMNDRNG_SCNDR_INKMSTNCMPNNT` (
    `KP_INKMSTNVRMNDRNG_SCNDR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `INKOMSTENVERMINDERING_ID` INT,
    `SECUNDAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_MLTJDVRGDNG_VRGDNG` (
    `KP_MLTJDVRGDNG_VRGDNG_ID` INT PRIMARY KEY,
    `MAALTIJDVERGOEDING_ID` INT,
    `VERGOEDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_VRGDNG_SCNDR_INKMSTNCMPNNT` (
    `KP_VRGDNG_SCNDR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `VERGOEDING_ID` INT,
    `SECUNDAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `ALIMENTATIE` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `BEDRAG_AAN_ANDERE_REKENINGEN` DECIMAL(10,2),
    `BEDRAG_IN_CONVENANT` DECIMAL(10,2),
    `BIJDRAGEEXPARTNERANDEREREKENINGEN` BOOLEAN,
    `INKOMSTENSOORT_ALIMENTATIE` VARCHAR(255),
    `JUISTE_BEDRAG_BETAALD_DOOR_EX_PARTNER` DECIMAL(10,2),
    `LBIO_INGESCHAKELD` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `KP_DRTND_MND_ENDJRSTKRNG_SCNDR_INKMSTNCMPNNT` (
    `KP_DRTND_MND_ENDJRSTKRNG_SCNDR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `DERTIENDE_MAAND_EINDEJAARSUITKERING_ID` INT,
    `SECUNDAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_EGN_BDRJF_PRMR_INKMSTNCMPNNT` (
    `KP_EGN_BDRJF_PRMR_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `EIGEN_BEDRIJF_ID` INT,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `ONKOSTENVERGOEDING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `HEFFINGSKORTING` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY,
    `ALGEMENE_HEFFINGSKORTING` BOOLEAN,
    `INKOMENSAFHANKELIJKE_COMBINATIEKORTING` BOOLEAN
) ENGINE=InnoDB;

CREATE TABLE `LOONBESLAG` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `REISKOSTEN_NAAR_HET_WERK_` (
    `KOSTENCOMPONENT_ID` INT PRIMARY KEY,
    `SOORT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `VAKANTIEGELD` (
    `INKOMSTENCOMPONENT_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `VRIJLATING_INKOMSTEN` (
    `VRIJLATING_INKOMSTEN_ID` INT PRIMARY KEY,
    `DOELGROEP` VARCHAR(255),
    `MEDISCH` BOOLEAN,
    `PERIODE_EINDDATUM` DATE,
    `PERIODE_STARTDATUM` DATE,
    `SOORT_VRIJLATING` VARCHAR(255),
    `VRIJGELATEN_BEDRAG` DECIMAL(10,2)
) ENGINE=InnoDB;

CREATE TABLE `KP_PRMR_INKMSTNCMPNNT_INKMSTNCMPNNT` (
    `KP_PRMR_INKMSTNCMPNNT_INKMSTNCMPNNT_ID` INT PRIMARY KEY,
    `PRIMAIR_INKOMSTENCOMPONENT_ID` INT,
    `INKOMSTENCOMPONENT_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_ONKSTNVRGDNG_VRGDNG` (
    `KP_ONKSTNVRGDNG_VRGDNG_ID` INT PRIMARY KEY,
    `ONKOSTENVERGOEDING_ID` INT,
    `VERGOEDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_RSKSTNVRGDNG_VRGDNG` (
    `KP_RSKSTNVRGDNG_VRGDNG_ID` INT PRIMARY KEY,
    `REISKOSTENVERGOEDING_ID` INT,
    `VERGOEDING_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `DRAAGKRACHTREGIME` (
    `DRAAGKRACHTREGIME_ID` INT PRIMARY KEY,
    `INITIELE_DRAAGKRACHT` VARCHAR(255),
    `NAAM` VARCHAR(255),
    `PEILDATUM` DATE,
    `RESTERENDE_DRAAGKRACHT` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `ALIMENTATIE` ADD CONSTRAINT FK_ALIMENTATIE_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `ANDER_INKOMEN` ADD CONSTRAINT FK_ANDER_INKOMEN_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `BESLAG_OP_INKOMEN` ADD CONSTRAINT FK_BESLAG_OP_INKOMEN_GEN_KOSTENCOMPONENT FOREIGN KEY (`KOSTENCOMPONENT_ID`) REFERENCES `KOSTENCOMPONENT` (`KOSTENCOMPONENT_ID`);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE `BETAALD_WERK` ADD CONSTRAINT FK_BETAALD_WERK_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `DERTIENDE_MAAND_EINDEJAARSUITKERING` ADD CONSTRAINT FK_DERTIENDE_MAAND_EINDEJAARSUITKERING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE `EIGEN_BEDRIJF` ADD CONSTRAINT FK_EIGEN_BEDRIJF_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `EIGEN_BIJDRAGE` ADD CONSTRAINT FK_EIGEN_BIJDRAGE_GEN_KOSTENCOMPONENT FOREIGN KEY (`KOSTENCOMPONENT_ID`) REFERENCES `KOSTENCOMPONENT` (`KOSTENCOMPONENT_ID`);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE `HEFFINGSKORTING` ADD CONSTRAINT FK_HEFFINGSKORTING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE `HOBBY` ADD CONSTRAINT FK_HOBBY_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `INKOMSTENVERMINDERING` ADD CONSTRAINT FK_INKOMSTENVERMINDERING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE `LOONBESLAG` ADD CONSTRAINT FK_LOONBESLAG_GEN_INKOMSTENVERMINDERING FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENVERMINDERING` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE `MAALTIJDVERGOEDING` ADD CONSTRAINT FK_MAALTIJDVERGOEDING_GEN_VERGOEDING FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to VERGOEDING

ALTER TABLE `ONKOSTENVERGOEDING` ADD CONSTRAINT FK_ONKOSTENVERGOEDING_GEN_VERGOEDING FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to VERGOEDING

ALTER TABLE `PENSIOEN` ADD CONSTRAINT FK_PENSIOEN_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `PRIMAIR_INKOMSTENCOMPONENT` ADD CONSTRAINT FK_PRIMAIR_INKOMSTENCOMPONENT_GEN_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to INKOMSTENCOMPONENT

ALTER TABLE `REISKOSTEN_NAAR_HET_WERK_` ADD CONSTRAINT FK_REISKOSTEN_NAAR_HET_WERK__GEN_KOSTENCOMPONENT FOREIGN KEY (`KOSTENCOMPONENT_ID`) REFERENCES `KOSTENCOMPONENT` (`KOSTENCOMPONENT_ID`);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE `REISKOSTENVERGOEDING` ADD CONSTRAINT FK_REISKOSTENVERGOEDING_GEN_VERGOEDING FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to VERGOEDING

ALTER TABLE `SECUNDAIR_INKOMSTENCOMPONENT` ADD CONSTRAINT FK_SECUNDAIR_INKOMSTENCOMPONENT_GEN_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to INKOMSTENCOMPONENT

ALTER TABLE `STAGE` ADD CONSTRAINT FK_STAGE_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `STUDIEFINANCIERING` ADD CONSTRAINT FK_STUDIEFINANCIERING_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `TE_BETALEN_ALIMENTATIE` ADD CONSTRAINT FK_TE_BETALEN_ALIMENTATIE_GEN_KOSTENCOMPONENT FOREIGN KEY (`KOSTENCOMPONENT_ID`) REFERENCES `KOSTENCOMPONENT` (`KOSTENCOMPONENT_ID`);
-- Generalization to KOSTENCOMPONENT

ALTER TABLE `UITKERING` ADD CONSTRAINT FK_UITKERING_GEN_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to PRIMAIR_INKOMSTENCOMPONENT

ALTER TABLE `VAKANTIEGELD` ADD CONSTRAINT FK_VAKANTIEGELD_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE `VERGOEDING` ADD CONSTRAINT FK_VERGOEDING_GEN_SECUNDAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to SECUNDAIR_INKOMSTENCOMPONENT

ALTER TABLE `VERGOEDING_IN_NATURA` ADD CONSTRAINT FK_VERGOEDING_IN_NATURA_GEN_VERGOEDING FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to VERGOEDING

ALTER TABLE `VERLAGING_DOOR_BOETE` ADD CONSTRAINT FK_VERLAGING_DOOR_BOETE_GEN_INKOMSTENVERMINDERING FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENVERMINDERING` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE `VERLAGING_DOOR_MAATREGEL` ADD CONSTRAINT FK_VERLAGING_DOOR_MAATREGEL_GEN_INKOMSTENVERMINDERING FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENVERMINDERING` (`INKOMSTENCOMPONENT_ID`);
-- Generalization to INKOMSTENVERMINDERING

ALTER TABLE `KP_VRLGNG_DR_MTRGL_INKMSTNVRMNDRNG` ADD CONSTRAINT FK_KP_VRLGNG_DR_MTRGL_INKMSTNVRMNDRNG_1 FOREIGN KEY (`VERLAGING_DOOR_MAATREGEL_ID`) REFERENCES `VERLAGING_DOOR_MAATREGEL` (`INKOMSTENCOMPONENT_ID`);
-- VERLAGING_DOOR_MAATREGEL (many-to-many junction, Connector_ID: 872)

ALTER TABLE `KP_VRLGNG_DR_MTRGL_INKMSTNVRMNDRNG` ADD CONSTRAINT FK_KP_VRLGNG_DR_MTRGL_INKMSTNVRMNDRNG_2 FOREIGN KEY (`INKOMSTENVERMINDERING_ID`) REFERENCES `INKOMSTENVERMINDERING` (`INKOMSTENCOMPONENT_ID`);
-- INKOMSTENVERMINDERING (many-to-many junction, Connector_ID: 872)

ALTER TABLE `KP_VRLGNG_DR_BT_INKMSTNVRMNDRNG` ADD CONSTRAINT FK_KP_VRLGNG_DR_BT_INKMSTNVRMNDRNG_1 FOREIGN KEY (`VERLAGING_DOOR_BOETE_ID`) REFERENCES `VERLAGING_DOOR_BOETE` (`INKOMSTENCOMPONENT_ID`);
-- VERLAGING_DOOR_BOETE (many-to-many junction, Connector_ID: 873)

ALTER TABLE `KP_VRLGNG_DR_BT_INKMSTNVRMNDRNG` ADD CONSTRAINT FK_KP_VRLGNG_DR_BT_INKMSTNVRMNDRNG_2 FOREIGN KEY (`INKOMSTENVERMINDERING_ID`) REFERENCES `INKOMSTENVERMINDERING` (`INKOMSTENCOMPONENT_ID`);
-- INKOMSTENVERMINDERING (many-to-many junction, Connector_ID: 873)

ALTER TABLE `KP_VRGDNG_IN_NTR_VRGDNG` ADD CONSTRAINT FK_KP_VRGDNG_IN_NTR_VRGDNG_1 FOREIGN KEY (`VERGOEDING_IN_NATURA_ID`) REFERENCES `VERGOEDING_IN_NATURA` (`INKOMSTENCOMPONENT_ID`);
-- VERGOEDING_IN_NATURA (many-to-many junction, Connector_ID: 874)

ALTER TABLE `KP_VRGDNG_IN_NTR_VRGDNG` ADD CONSTRAINT FK_KP_VRGDNG_IN_NTR_VRGDNG_2 FOREIGN KEY (`VERGOEDING_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- VERGOEDING (many-to-many junction, Connector_ID: 874)

ALTER TABLE `KP_VRGDNG_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_VRGDNG_SCNDR_INKMSTNCMPNNT_1 FOREIGN KEY (`VERGOEDING_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- VERGOEDING (many-to-many junction, Connector_ID: 875)

ALTER TABLE `KP_VRGDNG_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_VRGDNG_SCNDR_INKMSTNCMPNNT_2 FOREIGN KEY (`SECUNDAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- SECUNDAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 875)

ALTER TABLE `KP_VKNTGLD_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_VKNTGLD_SCNDR_INKMSTNCMPNNT_1 FOREIGN KEY (`VAKANTIEGELD_ID`) REFERENCES `VAKANTIEGELD` (`INKOMSTENCOMPONENT_ID`);
-- VAKANTIEGELD (many-to-many junction, Connector_ID: 876)

ALTER TABLE `KP_VKNTGLD_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_VKNTGLD_SCNDR_INKMSTNCMPNNT_2 FOREIGN KEY (`SECUNDAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- SECUNDAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 876)

ALTER TABLE `KP_UTKRNG_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_UTKRNG_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`UITKERING_ID`) REFERENCES `UITKERING` (`INKOMSTENCOMPONENT_ID`);
-- UITKERING (many-to-many junction, Connector_ID: 880)

ALTER TABLE `KP_UTKRNG_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_UTKRNG_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 880)

ALTER TABLE `KP_TE_BTLN_ALMNTT_KSTNCMPNNT` ADD CONSTRAINT FK_KP_TE_BTLN_ALMNTT_KSTNCMPNNT_1 FOREIGN KEY (`TE_BETALEN_ALIMENTATIE_ID`) REFERENCES `TE_BETALEN_ALIMENTATIE` (`KOSTENCOMPONENT_ID`);
-- TE_BETALEN_ALIMENTATIE (many-to-many junction, Connector_ID: 881)

ALTER TABLE `KP_TE_BTLN_ALMNTT_KSTNCMPNNT` ADD CONSTRAINT FK_KP_TE_BTLN_ALMNTT_KSTNCMPNNT_2 FOREIGN KEY (`KOSTENCOMPONENT_ID`) REFERENCES `KOSTENCOMPONENT` (`KOSTENCOMPONENT_ID`);
-- KOSTENCOMPONENT (many-to-many junction, Connector_ID: 881)

ALTER TABLE `KP_STDFNNCRNG_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_STDFNNCRNG_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`STUDIEFINANCIERING_ID`) REFERENCES `STUDIEFINANCIERING` (`INKOMSTENCOMPONENT_ID`);
-- STUDIEFINANCIERING (many-to-many junction, Connector_ID: 882)

ALTER TABLE `KP_STDFNNCRNG_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_STDFNNCRNG_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 882)

ALTER TABLE `KP_STG_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_STG_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`STAGE_ID`) REFERENCES `STAGE` (`INKOMSTENCOMPONENT_ID`);
-- STAGE (many-to-many junction, Connector_ID: 884)

ALTER TABLE `KP_STG_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_STG_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 884)

ALTER TABLE `KP_SCNDR_INKMSTNCMPNNT_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_SCNDR_INKMSTNCMPNNT_INKMSTNCMPNNT_1 FOREIGN KEY (`SECUNDAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- SECUNDAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 885)

ALTER TABLE `KP_SCNDR_INKMSTNCMPNNT_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_SCNDR_INKMSTNCMPNNT_INKMSTNCMPNNT_2 FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 885)

ALTER TABLE `KP_RSKSTNVRGDNG_VRGDNG` ADD CONSTRAINT FK_KP_RSKSTNVRGDNG_VRGDNG_1 FOREIGN KEY (`REISKOSTENVERGOEDING_ID`) REFERENCES `REISKOSTENVERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- REISKOSTENVERGOEDING (many-to-many junction, Connector_ID: 887)

ALTER TABLE `KP_RSKSTNVRGDNG_VRGDNG` ADD CONSTRAINT FK_KP_RSKSTNVRGDNG_VRGDNG_2 FOREIGN KEY (`VERGOEDING_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- VERGOEDING (many-to-many junction, Connector_ID: 887)

ALTER TABLE `KP_RSKSTN_NR_HET_WRK__KSTNCMPNNT` ADD CONSTRAINT FK_KP_RSKSTN_NR_HET_WRK__KSTNCMPNNT_1 FOREIGN KEY (`REISKOSTEN_NAAR_HET_WERK__ID`) REFERENCES `REISKOSTEN_NAAR_HET_WERK_` (`KOSTENCOMPONENT_ID`);
-- REISKOSTEN_NAAR_HET_WERK_ (many-to-many junction, Connector_ID: 888)

ALTER TABLE `KP_RSKSTN_NR_HET_WRK__KSTNCMPNNT` ADD CONSTRAINT FK_KP_RSKSTN_NR_HET_WRK__KSTNCMPNNT_2 FOREIGN KEY (`KOSTENCOMPONENT_ID`) REFERENCES `KOSTENCOMPONENT` (`KOSTENCOMPONENT_ID`);
-- KOSTENCOMPONENT (many-to-many junction, Connector_ID: 888)

ALTER TABLE `KP_PRMR_INKMSTNCMPNNT_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_PRMR_INKMSTNCMPNNT_INKMSTNCMPNNT_1 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 889)

ALTER TABLE `KP_PRMR_INKMSTNCMPNNT_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_PRMR_INKMSTNCMPNNT_INKMSTNCMPNNT_2 FOREIGN KEY (`INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 889)

ALTER TABLE `KP_PNSN_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_PNSN_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`PENSIOEN_ID`) REFERENCES `PENSIOEN` (`INKOMSTENCOMPONENT_ID`);
-- PENSIOEN (many-to-many junction, Connector_ID: 891)

ALTER TABLE `KP_PNSN_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_PNSN_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 891)

ALTER TABLE `KP_ONKSTNVRGDNG_VRGDNG` ADD CONSTRAINT FK_KP_ONKSTNVRGDNG_VRGDNG_1 FOREIGN KEY (`ONKOSTENVERGOEDING_ID`) REFERENCES `ONKOSTENVERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- ONKOSTENVERGOEDING (many-to-many junction, Connector_ID: 893)

ALTER TABLE `KP_ONKSTNVRGDNG_VRGDNG` ADD CONSTRAINT FK_KP_ONKSTNVRGDNG_VRGDNG_2 FOREIGN KEY (`VERGOEDING_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- VERGOEDING (many-to-many junction, Connector_ID: 893)

ALTER TABLE `KP_MLTJDVRGDNG_VRGDNG` ADD CONSTRAINT FK_KP_MLTJDVRGDNG_VRGDNG_1 FOREIGN KEY (`MAALTIJDVERGOEDING_ID`) REFERENCES `MAALTIJDVERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- MAALTIJDVERGOEDING (many-to-many junction, Connector_ID: 896)

ALTER TABLE `KP_MLTJDVRGDNG_VRGDNG` ADD CONSTRAINT FK_KP_MLTJDVRGDNG_VRGDNG_2 FOREIGN KEY (`VERGOEDING_ID`) REFERENCES `VERGOEDING` (`INKOMSTENCOMPONENT_ID`);
-- VERGOEDING (many-to-many junction, Connector_ID: 896)

ALTER TABLE `KP_LNBSLG_INKMSTNVRMNDRNG` ADD CONSTRAINT FK_KP_LNBSLG_INKMSTNVRMNDRNG_1 FOREIGN KEY (`LOONBESLAG_ID`) REFERENCES `LOONBESLAG` (`INKOMSTENCOMPONENT_ID`);
-- LOONBESLAG (many-to-many junction, Connector_ID: 899)

ALTER TABLE `KP_LNBSLG_INKMSTNVRMNDRNG` ADD CONSTRAINT FK_KP_LNBSLG_INKMSTNVRMNDRNG_2 FOREIGN KEY (`INKOMSTENVERMINDERING_ID`) REFERENCES `INKOMSTENVERMINDERING` (`INKOMSTENCOMPONENT_ID`);
-- INKOMSTENVERMINDERING (many-to-many junction, Connector_ID: 899)

ALTER TABLE `KP_INKMSTNVRMNDRNG_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_INKMSTNVRMNDRNG_SCNDR_INKMSTNCMPNNT_1 FOREIGN KEY (`INKOMSTENVERMINDERING_ID`) REFERENCES `INKOMSTENVERMINDERING` (`INKOMSTENCOMPONENT_ID`);
-- INKOMSTENVERMINDERING (many-to-many junction, Connector_ID: 900)

ALTER TABLE `KP_INKMSTNVRMNDRNG_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_INKMSTNVRMNDRNG_SCNDR_INKMSTNCMPNNT_2 FOREIGN KEY (`SECUNDAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- SECUNDAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 900)

ALTER TABLE `KP_HBBY_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_HBBY_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`HOBBY_ID`) REFERENCES `HOBBY` (`INKOMSTENCOMPONENT_ID`);
-- HOBBY (many-to-many junction, Connector_ID: 902)

ALTER TABLE `KP_HBBY_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_HBBY_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 902)

ALTER TABLE `KP_HFFNGSKRTNG_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_HFFNGSKRTNG_SCNDR_INKMSTNCMPNNT_1 FOREIGN KEY (`HEFFINGSKORTING_ID`) REFERENCES `HEFFINGSKORTING` (`INKOMSTENCOMPONENT_ID`);
-- HEFFINGSKORTING (many-to-many junction, Connector_ID: 903)

ALTER TABLE `KP_HFFNGSKRTNG_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_HFFNGSKRTNG_SCNDR_INKMSTNCMPNNT_2 FOREIGN KEY (`SECUNDAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- SECUNDAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 903)

ALTER TABLE `KP_EGN_BJDRG_KSTNCMPNNT` ADD CONSTRAINT FK_KP_EGN_BJDRG_KSTNCMPNNT_1 FOREIGN KEY (`EIGEN_BIJDRAGE_ID`) REFERENCES `EIGEN_BIJDRAGE` (`KOSTENCOMPONENT_ID`);
-- EIGEN_BIJDRAGE (many-to-many junction, Connector_ID: 904)

ALTER TABLE `KP_EGN_BJDRG_KSTNCMPNNT` ADD CONSTRAINT FK_KP_EGN_BJDRG_KSTNCMPNNT_2 FOREIGN KEY (`KOSTENCOMPONENT_ID`) REFERENCES `KOSTENCOMPONENT` (`KOSTENCOMPONENT_ID`);
-- KOSTENCOMPONENT (many-to-many junction, Connector_ID: 904)

ALTER TABLE `KP_EGN_BDRJF_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_EGN_BDRJF_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`EIGEN_BEDRIJF_ID`) REFERENCES `EIGEN_BEDRIJF` (`INKOMSTENCOMPONENT_ID`);
-- EIGEN_BEDRIJF (many-to-many junction, Connector_ID: 905)

ALTER TABLE `KP_EGN_BDRJF_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_EGN_BDRJF_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 905)

ALTER TABLE `KP_DRTND_MND_ENDJRSTKRNG_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_DRTND_MND_ENDJRSTKRNG_SCNDR_INKMSTNCMPNNT_1 FOREIGN KEY (`DERTIENDE_MAAND_EINDEJAARSUITKERING_ID`) REFERENCES `DERTIENDE_MAAND_EINDEJAARSUITKERING` (`INKOMSTENCOMPONENT_ID`);
-- DERTIENDE_MAAND_EINDEJAARSUITKERING (many-to-many junction, Connector_ID: 907)

ALTER TABLE `KP_DRTND_MND_ENDJRSTKRNG_SCNDR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_DRTND_MND_ENDJRSTKRNG_SCNDR_INKMSTNCMPNNT_2 FOREIGN KEY (`SECUNDAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `SECUNDAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- SECUNDAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 907)

ALTER TABLE `KP_BTLD_WRK_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_BTLD_WRK_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`BETAALD_WERK_ID`) REFERENCES `BETAALD_WERK` (`INKOMSTENCOMPONENT_ID`);
-- BETAALD_WERK (many-to-many junction, Connector_ID: 915)

ALTER TABLE `KP_BTLD_WRK_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_BTLD_WRK_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 915)

ALTER TABLE `KP_BSLG_OP_INKMN_KSTNCMPNNT` ADD CONSTRAINT FK_KP_BSLG_OP_INKMN_KSTNCMPNNT_1 FOREIGN KEY (`BESLAG_OP_INKOMEN_ID`) REFERENCES `BESLAG_OP_INKOMEN` (`KOSTENCOMPONENT_ID`);
-- BESLAG_OP_INKOMEN (many-to-many junction, Connector_ID: 916)

ALTER TABLE `KP_BSLG_OP_INKMN_KSTNCMPNNT` ADD CONSTRAINT FK_KP_BSLG_OP_INKMN_KSTNCMPNNT_2 FOREIGN KEY (`KOSTENCOMPONENT_ID`) REFERENCES `KOSTENCOMPONENT` (`KOSTENCOMPONENT_ID`);
-- KOSTENCOMPONENT (many-to-many junction, Connector_ID: 916)

ALTER TABLE `KP_ANDR_INKMN_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_ANDR_INKMN_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`ANDER_INKOMEN_ID`) REFERENCES `ANDER_INKOMEN` (`INKOMSTENCOMPONENT_ID`);
-- ANDER_INKOMEN (many-to-many junction, Connector_ID: 917)

ALTER TABLE `KP_ANDR_INKMN_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_ANDR_INKMN_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 917)

ALTER TABLE `KP_ALMNTT_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_ALMNTT_PRMR_INKMSTNCMPNNT_1 FOREIGN KEY (`ALIMENTATIE_ID`) REFERENCES `ALIMENTATIE` (`INKOMSTENCOMPONENT_ID`);
-- ALIMENTATIE (many-to-many junction, Connector_ID: 918)

ALTER TABLE `KP_ALMNTT_PRMR_INKMSTNCMPNNT` ADD CONSTRAINT FK_KP_ALMNTT_PRMR_INKMSTNCMPNNT_2 FOREIGN KEY (`PRIMAIR_INKOMSTENCOMPONENT_ID`) REFERENCES `PRIMAIR_INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PRIMAIR_INKOMSTENCOMPONENT (many-to-many junction, Connector_ID: 918)

ALTER TABLE `UITKERING` ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VERLAGING_DOOR_BOETE FOREIGN KEY (`UITKERING_HEEFT_VERLAGING_DOOR_BOETE_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- UITKERING_HEEFT_VERLAGING_DOOR_BOETE (0..* to 1..1, Connector_ID: 877)

ALTER TABLE `UITKERING` ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VAKANTIEGELD FOREIGN KEY (`UITKERING_HEEFT_VAKANTIEGELD_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- UITKERING_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 878)

ALTER TABLE `UITKERING` ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL FOREIGN KEY (`UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- UITKERING_HEEFT_VERLAGING_DOOR_MAATREGEL (0..* to 1..1, Connector_ID: 879)

ALTER TABLE `STAGE` ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_VERGOEDING_IN_NATURA FOREIGN KEY (`STAGE_HEEFT_VERGOEDING_IN_NATURA_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- STAGE_HEEFT_VERGOEDING_IN_NATURA (0..* to 1..1, Connector_ID: 883)

ALTER TABLE `STAGE` ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_REISKOSTENVERGOEDING FOREIGN KEY (`STAGE_HEEFT_REISKOSTENVERGOEDING_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- STAGE_HEEFT_REISKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 886)

ALTER TABLE `PENSIOEN` ADD CONSTRAINT FK_PENSIOEN_PENSIOEN_HEEFT_VAKANTIEGELD FOREIGN KEY (`PENSIOEN_HEEFT_VAKANTIEGELD_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PENSIOEN_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 890)

ALTER TABLE `STAGE` ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_ONKOSTENVERGOEDING FOREIGN KEY (`STAGE_HEEFT_ONKOSTENVERGOEDING_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- STAGE_HEEFT_ONKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 892)

ALTER TABLE `ONDERHOUDSVERHOUDING` ADD CONSTRAINT FK_ONDERHOUDSVERHOUDING_ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT FOREIGN KEY (`ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT_ONDERHOUDSPLICHT_ID`) REFERENCES `ONDERHOUDSPLICHT` (`ONDERHOUDSPLICHT_ID`);
-- ONDERHOUDSVERHOUDING_BEVAT_ONDERHOUDSPLICHT (0..* to 1..1, Connector_ID: 894)

ALTER TABLE `STAGE` ADD CONSTRAINT FK_STAGE_STAGE_HEEFT_MAALTIJDVERGOEDING FOREIGN KEY (`STAGE_HEEFT_MAALTIJDVERGOEDING_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- STAGE_HEEFT_MAALTIJDVERGOEDING (0..* to 1..1, Connector_ID: 895)

ALTER TABLE `UITKERING` ADD CONSTRAINT FK_UITKERING_UITKERING_HEEFT_LOONBESLAG FOREIGN KEY (`UITKERING_HEEFT_LOONBESLAG_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- UITKERING_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 897)

ALTER TABLE `PENSIOEN` ADD CONSTRAINT FK_PENSIOEN_PENSIOEN_HEEFT_LOONBESLAG FOREIGN KEY (`PENSIOEN_HEEFT_LOONBESLAG_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- PENSIOEN_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 898)

ALTER TABLE `INKOMSTENVERHOUDING` ADD CONSTRAINT FK_INKOMSTENVERHOUDING_INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (`INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT (1..* to 0..1, Connector_ID: 901)

ALTER TABLE `DRAAGKRACHT` ADD CONSTRAINT FK_DRAAGKRACHT_DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME FOREIGN KEY (`DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME_DRAAGKRACHTREGIME_ID`) REFERENCES `DRAAGKRACHTREGIME` (`DRAAGKRACHTREGIME_ID`);
-- DRAAGKRACHT_HEEFT_DRAAGKRACHTREGIME (1..* to 1..1, Connector_ID: 906)

ALTER TABLE `BETAALD_WERK` ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING FOREIGN KEY (`BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- BETAALD_WERK_HEEFT_MAALTIJDVERGOEDING (0..* to 1..1, Connector_ID: 908)

ALTER TABLE `BETAALD_WERK` ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING FOREIGN KEY (`BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- BETAALD_WERK_HEEFT_DERTIENDE_MAAND_EINDEJAARSUITKERING (0..* to 1..1, Connector_ID: 909)

ALTER TABLE `BETAALD_WERK` ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING FOREIGN KEY (`BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- BETAALD_WERK_HEEFT_REISKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 910)

ALTER TABLE `BETAALD_WERK` ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING FOREIGN KEY (`BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- BETAALD_WERK_HEEFT_ONKOSTENVERGOEDING (0..* to 1..1, Connector_ID: 911)

ALTER TABLE `BETAALD_WERK` ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_LOONBESLAG FOREIGN KEY (`BETAALD_WERK_HEEFT_LOONBESLAG_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- BETAALD_WERK_HEEFT_LOONBESLAG (0..* to 1..1, Connector_ID: 912)

ALTER TABLE `BETAALD_WERK` ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_HEFFINGSKORTING FOREIGN KEY (`BETAALD_WERK_HEEFT_HEFFINGSKORTING_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- BETAALD_WERK_HEEFT_HEFFINGSKORTING (0..* to 1..1, Connector_ID: 913)

ALTER TABLE `BETAALD_WERK` ADD CONSTRAINT FK_BETAALD_WERK_BETAALD_WERK_HEEFT_VAKANTIEGELD FOREIGN KEY (`BETAALD_WERK_HEEFT_VAKANTIEGELD_INKOMSTENCOMPONENT_ID`) REFERENCES `INKOMSTENCOMPONENT` (`INKOMSTENCOMPONENT_ID`);
-- BETAALD_WERK_HEEFT_VAKANTIEGELD (0..* to 1..1, Connector_ID: 914)

