CREATE TABLE VERMOGENSCOMPONENT (
    VERMOGENSCOMPONENT_ID NUMBER PRIMARY KEY,
    CODE_SOORT_VERMOGENSCOMPONENT VARCHAR2(255),
    DATUM_VASTSTELLING_VERMOGENCOMPONENT DATE,
    IDENTIFICATIE VARCHAR2(255),
    NOG_AAN_TE_SPREKEN_VERMOGEN VARCHAR2(255),
    VRIJ_TE_LATEN_VERMOGEN VARCHAR2(255)
);

CREATE TABLE PRIMAIR_INKOMSTENCOMPONENT (
    PRIMAIR_INKOMSTENCOMPONENT_ID NUMBER PRIMARY KEY
);

CREATE TABLE BANKREKENING (
    VERMOGENSCOMPONENT_ID NUMBER PRIMARY KEY,
    BANKREKENINGNUMMER VARCHAR2(255),
    BRONTYPE VARCHAR2(255),
    DATUM_AANVANG_BANKREKENING DATE,
    DATUM_EINDE_BANKREKENING DATE,
    IBAN VARCHAR2(255),
    REKENINGTYPE VARCHAR2(255),
    TENAAMSTELLING VARCHAR2(255),
    VOORKEUR_BANKREKENING NUMBER(1)
);

CREATE TABLE INKOMSTENVERHOUDING (
    INKOMSTENVERHOUDING_ID NUMBER PRIMARY KEY,
    CATEGORIE_INKOMSTEN VARCHAR2(255),
    INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT_PRIMAIR_INKOMSTENCOMPONENT_ID NUMBER,
    PERIODE_EINDDATUM DATE,
    PERIODE_STARTDATUM DATE
);

CREATE TABLE PROFIEL (
    PROFIEL_ID NUMBER PRIMARY KEY,
    BEVAT_INKOMSTENVERHOUDING_ID NUMBER,
    BEVAT_VERMOGENSCOMPONENT_ID NUMBER,
    DATUMAANVANGPROFIEL DATE,
    DATUMEINDEPROFIEL DATE,
    PROFIELTYPE VARCHAR2(200)
);

CREATE TABLE CLIENT (
    CLIENT_ID NUMBER PRIMARY KEY,
    BEZIT_BANKREKENING_ID NUMBER,
    CODE VARCHAR2(80),
    GEZAGSDRAGERGEKEND NUMBER(1),
    HEEFT_PROFIEL_ID NUMBER,
    JURIDISCHESTATUS VARCHAR2(80),
    WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

ALTER TABLE BANKREKENING ADD CONSTRAINT FK_BANKREKENING_GEN_VERMOGENSCOMPONENT FOREIGN KEY (VERMOGENSCOMPONENT_ID) REFERENCES VERMOGENSCOMPONENT (VERMOGENSCOMPONENT_ID);
-- Generalization to VERMOGENSCOMPONENT

ALTER TABLE INKOMSTENVERHOUDING ADD CONSTRAINT FK_INKOMSTENVERHOUDING_INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT FOREIGN KEY (INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT_PRIMAIR_INKOMSTENCOMPONENT_ID) REFERENCES PRIMAIR_INKOMSTENCOMPONENT (PRIMAIR_INKOMSTENCOMPONENT_ID);
-- INKOMSTENVERHOUDING_BEVAT_PRIMAIR_INKOMSTENCOMPONENT (1..* to 0..1, Connector_ID: 901)

ALTER TABLE PROFIEL ADD CONSTRAINT FK_PROFIEL_BEVAT FOREIGN KEY (BEVAT_VERMOGENSCOMPONENT_ID) REFERENCES VERMOGENSCOMPONENT (VERMOGENSCOMPONENT_ID);
-- BEVAT (1..2 to 0..*, Connector_ID: 924)

ALTER TABLE PROFIEL ADD CONSTRAINT FK_PROFIEL_BEVAT_2 FOREIGN KEY (BEVAT_INKOMSTENVERHOUDING_ID) REFERENCES INKOMSTENVERHOUDING (INKOMSTENVERHOUDING_ID);
-- BEVAT (1 to 0..*, Connector_ID: 925)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_BEZIT FOREIGN KEY (BEZIT_BANKREKENING_ID) REFERENCES VERMOGENSCOMPONENT (VERMOGENSCOMPONENT_ID);
-- BEZIT (1..2 to 0..*, Connector_ID: 945)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT FOREIGN KEY (HEEFT_PROFIEL_ID) REFERENCES PROFIEL (PROFIEL_ID);
-- HEEFT (1 to 1..*, Connector_ID: 947)

