CREATE TABLE INKOOPORDER (
    INKOOPORDER_ID INTEGER PRIMARY KEY,
    ARTIKELCODE VARCHAR(80),
    BETALINGMEERDEREJAREN BOOLEAN,
    BETREFT VARCHAR(255),
    DATUMEINDE DATE,
    DATUMINGEDIEND DATE,
    DATUMSTART DATE,
    GERELATEERD_INKOOPORDER_ID INTEGER,
    GOEDERENCODE VARCHAR(80),
    HOORT_BIJ_WERKBON_ID INTEGER,
    OMSCHRIJVING VARCHAR(255),
    OORSPRONKELIJK_INKOOPORDER_ID INTEGER,
    ORDERNUMMER VARCHAR(255),
    SALDO VARCHAR(255),
    TOTAALNETTOBEDRAG DECIMAL(10,2),
    WIJZEVANAANBESTEDEN VARCHAR(255)
);

CREATE TABLE BOUWDEEL (
    BOUWDEEL_ID INTEGER PRIMARY KEY,
    BESTAAT_UIT_BOUWDEELELEMENT_ID INTEGER,
    CODE VARCHAR(255),
    OMSCHRIJVING VARCHAR(80)
);

CREATE TABLE ZAKELIJKRECHT_2335 (
    ZAKELIJKRECHT_2335_ID INTEGER PRIMARY KEY,
    AARDZAKELIJKRECHT VARCHAR(255),
    DATUMEINDERECHT DATE,
    DATUMINGANGRECHT DATE,
    IDENTIFICATIEZAKELIJKRECHT VARCHAR(255),
    IS_BELAST_MET_ZAKELIJKRECHT_2335_ID INTEGER,
    TOELICHTINGBEWAARDER VARCHAR(100)
);

CREATE TABLE BOUWDEELELEMENT (
    BOUWDEELELEMENT_ID INTEGER PRIMARY KEY,
    CODE VARCHAR(255),
    OMSCHRIJVING VARCHAR(80)
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID INTEGER PRIMARY KEY,
    BTWCODE VARCHAR(255),
    BTWOMSCHRIJVING VARCHAR(80),
    HEEFT_VASTGOEDOBJECT_ID INTEGER,
    KOSTENPLAATSSOORTCODE DECIMAL(10,2),
    KOSTENPLAATSSOORTOMSCHRIJVING DECIMAL(10,2),
    KOSTENPLAATSTYPECODE DECIMAL(10,2),
    KOSTENPLAATSTYPEOMSCHRIJVING DECIMAL(10,2),
    NAAM VARCHAR(80),
    OMSCHRIJVING VARCHAR(200)
);

CREATE TABLE HOOFDREKENING (
    HOOFDREKENING_ID INTEGER PRIMARY KEY,
    NAAM VARCHAR(80),
    NUMMER VARCHAR(255),
    OMSCHRIJVING VARCHAR(200),
    PIAHOOFCATEGORIEOMSCHRIJVING VARCHAR(80),
    PIAHOOFDCATEGORIECODE VARCHAR(20),
    SUBCODE VARCHAR(20),
    SUBCODEOMSCHRIJVING VARCHAR(80),
    VALT_BINNEN_HOOFDREKENING_ID INTEGER
);

CREATE TABLE ZAKELIJKRECHT_917_ENUM (
    ZAKELIJKRECHT_917_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ZAKELIJKRECHT_917_ENUM (ZAKELIJKRECHT_917_ENUM_ID, VALUE) VALUES
    (1, 'EIGENDOM'),
    (2, 'HUUR'),
    (3, 'LEEG'),
    (4, 'ONBEKEND'),
    (5, 'PACHT'),
    (6, 'RECHT_VAN_OPSTAL');

CREATE TABLE VASTGOEDOBJECT (
    VASTGOEDOBJECT_ID INTEGER PRIMARY KEY,
    AANTALETAGES INTEGER,
    AANTALPARKEERPLAATSEN INTEGER,
    AANTALRIOLERINGEN INTEGER,
    ADRESAANDUIDING VARCHAR(255),
    AFGEKOCHTEERFPACHT BOOLEAN,
    AFGESPROKENCONDITIESCORE_ENUM_ID INTEGER,
    AFKOOPWAARDE VARCHAR(255),
    ASBESTRAPPORTAGEAANWEZIG BOOLEAN,
    BEDRAGAANKOOP DECIMAL(10,2),
    BESTAAT_UIT_BOUWDEEL_ID INTEGER,
    BESTEMMINGSPLAN VARCHAR(200),
    BETREFT_INSPECTIE_ID INTEGER,
    BOEKWAARDE VARCHAR(255),
    BOUWJAAR INTEGER,
    BOUWWERK VARCHAR(80),
    BOVENLIGGENDNIVEAU VARCHAR(80),
    BOVENLIGGENDNIVEAUCODE VARCHAR(20),
    BRUTOVLOEROPPERVLAKTE INTEGER,
    CO2UITSTOOT INTEGER,
    CONDITIESCORE_ENUM_ID INTEGER,
    DATUMAFSTOTEN DATE,
    DATUMBEREKENINGOPPERVLAK DATE,
    DATUMEIGENDOM DATE,
    DATUMVERKOOP DATE,
    DEELPORTEFEUILLE VARCHAR(80),
    ENERGIEKOSTEN DECIMAL(10,2),
    ENERGIELABEL_ENUM_ID INTEGER,
    ENERGIEVERBRUIK INTEGER,
    FISCALEWAARDE VARCHAR(255),
    FOTO VARCHAR(255),
    GEARCHIVEERD BOOLEAN,
    HEEFT_VERHUURBAAR_EENHEID_ID INTEGER,
    HERBOUWWAARDE VARCHAR(255),
    HOOFDSTUK VARCHAR(80),
    IDENTIFICATIE VARCHAR(80),
    JAARLAATSTERENOVATIE VARCHAR(255),
    KOSTENPLAATS DECIMAL(10,2),
    LOCATIE VARCHAR(255),
    MARKTWAARDE VARCHAR(255),
    MONUMENT VARCHAR(255),
    NAAM VARCHAR(80),
    OBJECTSTATUS VARCHAR(255),
    OBJECTSTATUSCODE VARCHAR(255),
    OBJECTTYPE VARCHAR(80),
    OBJECTTYPECODE VARCHAR(255),
    OMSCHRIJVING VARCHAR(80),
    ONDERHOUDSCATEGORIE VARCHAR(80),
    OPPERVLAKTEKANTOOR INTEGER,
    PORTEFEUILLE VARCHAR(80),
    PORTEFEUILLECODE VARCHAR(255),
    PROVINCIE VARCHAR(255),
    TOELICHTING TEXT,
    VERHUURBAARVLOEROPPERVLAK INTEGER,
    VERKOOPBAARHEID VARCHAR(80),
    VERKOOPBEDRAG DECIMAL(10,2),
    VERZEKERDEWAARDE VARCHAR(255),
    WAARDEGROND VARCHAR(255),
    WAARDEOPSTAL VARCHAR(255),
    WIJK VARCHAR(255),
    WOZWAARDE VARCHAR(255)
);

CREATE TABLE KP_INKPRDR_HFDRKNNG (
    KP_INKPRDR_HFDRKNNG_ID INTEGER PRIMARY KEY,
    INKOOPORDER_ID INTEGER,
    HOOFDREKENING_ID INTEGER
);

CREATE TABLE MJOP_ITEM (
    MJOP_ITEM_ID INTEGER PRIMARY KEY,
    BETREFT_BOUWDEELELEMENT_ID INTEGER,
    BETREFT_BOUWDEEL_ID INTEGER,
    BETREFT_VASTGOEDOBJECT_ID INTEGER,
    CODE VARCHAR(255),
    DATUMEINDE DATE,
    DATUMOPZEGGINGAANBIEDER DATE,
    DATUMOPZEGGINGONTVANGER DATE,
    DATUMSTART DATE,
    KOSTEN DECIMAL(10,2),
    OMSCHRIJVING VARCHAR(80),
    OPZEGTERMIJNAANBIEDER INTEGER,
    OPZEGTERMIJNONTVANGER INTEGER,
    OP_BASIS_VAN_PRIJZENBOEKITEM_ID INTEGER
);

CREATE TABLE INSPECTIE (
    INSPECTIE_ID INTEGER PRIMARY KEY,
    BEVINDINGEN TEXT,
    DATUM DATE,
    LEIDT_TOT_MJOP_ID INTEGER
);

CREATE TABLE KP_VSTGDBJCT_ZKLJK_RCHT (
    KP_VSTGDBJCT_ZKLJK_RCHT_ID INTEGER PRIMARY KEY,
    VASTGOEDOBJECT_ID INTEGER,
    ZAKELIJK_RECHT_ID INTEGER
);

CREATE TABLE PRIJZENBOEKITEM (
    PRIJZENBOEKITEM_ID INTEGER PRIMARY KEY,
    DATUMEINDEGELDIGHEID DATE,
    DATUMSTART DATE,
    PRIJS DECIMAL(10,2),
    VERRICHTING VARCHAR(80)
);

CREATE TABLE KP_WRKBN_BWDL (
    KP_WRKBN_BWDL_ID INTEGER PRIMARY KEY,
    WERKBON_ID INTEGER,
    BOUWDEEL_ID INTEGER
);

CREATE TABLE VASTGOED_CONTRACT (
    VASTGOED_CONTRACT_ID INTEGER PRIMARY KEY,
    BESCHRIJVING VARCHAR(200),
    DATUMEINDE DATE,
    DATUMSTART DATE,
    HEEFT_RECHTSPERSOON_ID INTEGER,
    IDENTIFICATIE VARCHAR(80),
    MAANDBEDRAG DECIMAL(10,2),
    OPZEGTERMIJN VARCHAR(80),
    STATUS VARCHAR(80),
    TYPE VARCHAR(80)
);

CREATE TABLE MJOP (
    MJOP_ID INTEGER PRIMARY KEY,
    BESTAAT_UIT_MJOP_ITEM_ID INTEGER,
    BETREFT_VASTGOEDOBJECT_ID INTEGER,
    DATUM DATE,
    GEREALISEERD_DOOR_WERKBON_ID INTEGER,
    OMSCHRIJVING TEXT
);

CREATE TABLE KP_WRKBN_BWDLLMNT (
    KP_WRKBN_BWDLLMNT_ID INTEGER PRIMARY KEY,
    WERKBON_ID INTEGER,
    BOUWDEELELEMENT_ID INTEGER
);

CREATE TABLE ENERGIELABEL_GEBOUWEN_ENUM (
    ENERGIELABEL_GEBOUWEN_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENERGIELABEL_GEBOUWEN_ENUM (ENERGIELABEL_GEBOUWEN_ENUM_ID, VALUE) VALUES
    (1, 'A'),
    (2, 'A_'),
    (3, 'A_'),
    (4, 'B'),
    (5, 'C'),
    (6, 'D'),
    (7, 'E'),
    (8, 'F'),
    (9, 'G'),
    (10, 'LEEG'),
    (11, 'ONBEKEND');

CREATE TABLE ZAKELIJK_RECHT (
    ZAKELIJKRECHT_2335_ID INTEGER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    HEEFT_KOSTENPLAATS_ID INTEGER,
    KOSTEN DECIMAL(10,2),
    SOORT_ENUM_ID INTEGER
);

CREATE TABLE WERKBON (
    WERKBON_ID INTEGER PRIMARY KEY,
    BETREFT_VASTGOEDOBJECT_ID INTEGER
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID INTEGER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR(255),
    ADRESBUITENLAND VARCHAR(255),
    ADRESCORRESPONDENTIE VARCHAR(100),
    EMAILADRES VARCHAR(80),
    FAXNUMMER VARCHAR(20),
    IDENTIFICATIE VARCHAR(255),
    KVKNUMMER VARCHAR(20),
    NAAM VARCHAR(200),
    RECHTSVORM VARCHAR(100),
    REKENINGNUMMER VARCHAR(255),
    TELEFOONNUMMER VARCHAR(20)
);

CREATE TABLE VERHUURBAAR_EENHEID (
    VERHUURBAAR_EENHEID_ID INTEGER PRIMARY KEY,
    ADRES VARCHAR(255),
    AFMETING INTEGER,
    BEZETTING INTEGER,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DATUMWERKELIJKBEGIN DATE,
    DATUMWERKELIJKEINDE DATE,
    HUURPRIJS DECIMAL(10,2),
    IDENTIFICATIE VARCHAR(80),
    NAAM VARCHAR(80),
    NETTOOMTREK INTEGER,
    NETTOOPPERVLAK INTEGER,
    OPMERKINGEN TEXT,
    TYPE VARCHAR(80)
);

CREATE TABLE NEN2767_CONDITIESCORE_ENUM (
    NEN2767_CONDITIESCORE_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO NEN2767_CONDITIESCORE_ENUM (NEN2767_CONDITIESCORE_ENUM_ID, VALUE) VALUES
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, 'LEEG'),
    (8, 'ONBEKEND');

CREATE TABLE KP_HFDRKNNG_KSTNPLTS (
    KP_HFDRKNNG_KSTNPLTS_ID INTEGER PRIMARY KEY,
    HOOFDREKENING_ID INTEGER,
    KOSTENPLAATS_ID INTEGER
);

CREATE TABLE KP_KSTNPLTS_INKPRDR (
    KP_KSTNPLTS_INKPRDR_ID INTEGER PRIMARY KEY,
    KOSTENPLAATS_ID INTEGER,
    INKOOPORDER_ID INTEGER
);

ALTER TABLE ZAKELIJK_RECHT ADD CONSTRAINT FK_ZAKELIJK_RECHT_GEN_ZAKELIJKRECHT_2335 FOREIGN KEY (ZAKELIJKRECHT_2335_ID) REFERENCES ZAKELIJKRECHT_2335 (ZAKELIJKRECHT_2335_ID);
-- Generalization to ZAKELIJKRECHT_2335

ALTER TABLE KP_KSTNPLTS_INKPRDR ADD CONSTRAINT FK_KP_KSTNPLTS_INKPRDR_1 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 492)

ALTER TABLE KP_KSTNPLTS_INKPRDR ADD CONSTRAINT FK_KP_KSTNPLTS_INKPRDR_2 FOREIGN KEY (INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- INKOOPORDER (many-to-many junction, Connector_ID: 492)

ALTER TABLE KP_INKPRDR_HFDRKNNG ADD CONSTRAINT FK_KP_INKPRDR_HFDRKNNG_1 FOREIGN KEY (INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- INKOOPORDER (many-to-many junction, Connector_ID: 499)

ALTER TABLE KP_INKPRDR_HFDRKNNG ADD CONSTRAINT FK_KP_INKPRDR_HFDRKNNG_2 FOREIGN KEY (HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- HOOFDREKENING (many-to-many junction, Connector_ID: 499)

ALTER TABLE KP_HFDRKNNG_KSTNPLTS ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_1 FOREIGN KEY (HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- HOOFDREKENING (many-to-many junction, Connector_ID: 505)

ALTER TABLE KP_HFDRKNNG_KSTNPLTS ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_2 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 505)

ALTER TABLE KP_VSTGDBJCT_ZKLJK_RCHT ADD CONSTRAINT FK_KP_VSTGDBJCT_ZKLJK_RCHT_1 FOREIGN KEY (VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- VASTGOEDOBJECT (many-to-many junction, Connector_ID: 544)

ALTER TABLE KP_VSTGDBJCT_ZKLJK_RCHT ADD CONSTRAINT FK_KP_VSTGDBJCT_ZKLJK_RCHT_2 FOREIGN KEY (ZAKELIJK_RECHT_ID) REFERENCES ZAKELIJK_RECHT (ZAKELIJKRECHT_2335_ID);
-- ZAKELIJK_RECHT (many-to-many junction, Connector_ID: 544)

ALTER TABLE KP_WRKBN_BWDLLMNT ADD CONSTRAINT FK_KP_WRKBN_BWDLLMNT_1 FOREIGN KEY (WERKBON_ID) REFERENCES WERKBON (WERKBON_ID);
-- WERKBON (many-to-many junction, Connector_ID: 580)

ALTER TABLE KP_WRKBN_BWDLLMNT ADD CONSTRAINT FK_KP_WRKBN_BWDLLMNT_2 FOREIGN KEY (BOUWDEELELEMENT_ID) REFERENCES BOUWDEELELEMENT (BOUWDEELELEMENT_ID);
-- BOUWDEELELEMENT (many-to-many junction, Connector_ID: 580)

ALTER TABLE KP_WRKBN_BWDL ADD CONSTRAINT FK_KP_WRKBN_BWDL_1 FOREIGN KEY (WERKBON_ID) REFERENCES WERKBON (WERKBON_ID);
-- WERKBON (many-to-many junction, Connector_ID: 582)

ALTER TABLE KP_WRKBN_BWDL ADD CONSTRAINT FK_KP_WRKBN_BWDL_2 FOREIGN KEY (BOUWDEEL_ID) REFERENCES BOUWDEEL (BOUWDEEL_ID);
-- BOUWDEEL (many-to-many junction, Connector_ID: 582)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_OORSPRONKELIJK FOREIGN KEY (OORSPRONKELIJK_INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- OORSPRONKELIJK (0..1 to 0..1, Connector_ID: 493)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_GERELATEERD FOREIGN KEY (GERELATEERD_INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- GERELATEERD (0..1 to 0..*, Connector_ID: 494)

ALTER TABLE HOOFDREKENING ADD CONSTRAINT FK_HOOFDREKENING_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 504)

ALTER TABLE ZAKELIJK_RECHT ADD CONSTRAINT FK_ZAKELIJK_RECHT_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..* to 1, Connector_ID: 534)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_HOORT_BIJ FOREIGN KEY (HOORT_BIJ_WERKBON_ID) REFERENCES WERKBON (WERKBON_ID);
-- HOORT_BIJ (1 to 0..*, Connector_ID: 539)

ALTER TABLE KOSTENPLAATS ADD CONSTRAINT FK_KOSTENPLAATS_HEEFT FOREIGN KEY (HEEFT_VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 540)

ALTER TABLE WERKBON ADD CONSTRAINT FK_WERKBON_BETREFT FOREIGN KEY (BETREFT_VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- BETREFT (0..* to 1, Connector_ID: 542)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_HEEFT FOREIGN KEY (HEEFT_VERHUURBAAR_EENHEID_ID) REFERENCES VERHUURBAAR_EENHEID (VERHUURBAAR_EENHEID_ID);
-- HEEFT (1 to 0..*, Connector_ID: 547)

ALTER TABLE VASTGOED_CONTRACT ADD CONSTRAINT FK_VASTGOED_CONTRACT_HEEFT FOREIGN KEY (HEEFT_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- HEEFT (0..* to 1, Connector_ID: 552)

ALTER TABLE MJOP_ITEM ADD CONSTRAINT FK_MJOP_ITEM_BETREFT FOREIGN KEY (BETREFT_VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- BETREFT (0..* to 1, Connector_ID: 558)

ALTER TABLE MJOP_ITEM ADD CONSTRAINT FK_MJOP_ITEM_OP_BASIS_VAN FOREIGN KEY (OP_BASIS_VAN_PRIJZENBOEKITEM_ID) REFERENCES PRIJZENBOEKITEM (PRIJZENBOEKITEM_ID);
-- OP_BASIS_VAN (0..* to 1, Connector_ID: 559)

ALTER TABLE MJOP ADD CONSTRAINT FK_MJOP_GEREALISEERD_DOOR FOREIGN KEY (GEREALISEERD_DOOR_WERKBON_ID) REFERENCES WERKBON (WERKBON_ID);
-- GEREALISEERD_DOOR (1 to 0..*, Connector_ID: 560)

ALTER TABLE MJOP ADD CONSTRAINT FK_MJOP_BETREFT FOREIGN KEY (BETREFT_VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- BETREFT (0..* to 1, Connector_ID: 561)

ALTER TABLE MJOP ADD CONSTRAINT FK_MJOP_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_MJOP_ITEM_ID) REFERENCES MJOP_ITEM (MJOP_ITEM_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 562)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_BETREFT FOREIGN KEY (BETREFT_INSPECTIE_ID) REFERENCES INSPECTIE (INSPECTIE_ID);
-- BETREFT (1 to 0..*, Connector_ID: 571)

ALTER TABLE INSPECTIE ADD CONSTRAINT FK_INSPECTIE_LEIDT_TOT FOREIGN KEY (LEIDT_TOT_MJOP_ID) REFERENCES MJOP (MJOP_ID);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 572)

ALTER TABLE MJOP_ITEM ADD CONSTRAINT FK_MJOP_ITEM_BETREFT_2 FOREIGN KEY (BETREFT_BOUWDEELELEMENT_ID) REFERENCES BOUWDEELELEMENT (BOUWDEELELEMENT_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 579)

ALTER TABLE MJOP_ITEM ADD CONSTRAINT FK_MJOP_ITEM_BETREFT_3 FOREIGN KEY (BETREFT_BOUWDEEL_ID) REFERENCES BOUWDEEL (BOUWDEEL_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 581)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_BOUWDEEL_ID) REFERENCES BOUWDEEL (BOUWDEEL_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 583)

ALTER TABLE BOUWDEEL ADD CONSTRAINT FK_BOUWDEEL_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_BOUWDEELELEMENT_ID) REFERENCES BOUWDEELELEMENT (BOUWDEELELEMENT_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 584)

ALTER TABLE ZAKELIJKRECHT_2335 ADD CONSTRAINT FK_ZAKELIJKRECHT_2335_IS_BELAST_MET FOREIGN KEY (IS_BELAST_MET_ZAKELIJKRECHT_2335_ID) REFERENCES ZAKELIJKRECHT_2335 (ZAKELIJKRECHT_2335_ID);
-- IS_BELAST_MET (0..1 to 0..*, Connector_ID: 1944)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_AFGESPROKENCONDITIESCORE_ENUM_ID FOREIGN KEY (AFGESPROKENCONDITIESCORE_ENUM_ID) REFERENCES NEN2767_CONDITIESCORE_ENUM (NEN2767_CONDITIESCORE_ENUM_ID);
-- AFGESPROKENCONDITIESCORE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_CONDITIESCORE_ENUM_ID FOREIGN KEY (CONDITIESCORE_ENUM_ID) REFERENCES NEN2767_CONDITIESCORE_ENUM (NEN2767_CONDITIESCORE_ENUM_ID);
-- CONDITIESCORE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_ENERGIELABEL_ENUM_ID FOREIGN KEY (ENERGIELABEL_ENUM_ID) REFERENCES ENERGIELABEL_GEBOUWEN_ENUM (ENERGIELABEL_GEBOUWEN_ENUM_ID);
-- ENERGIELABEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ZAKELIJK_RECHT ADD CONSTRAINT FK_ZAKELIJK_RECHT_SOORT_ENUM_ID FOREIGN KEY (SOORT_ENUM_ID) REFERENCES ZAKELIJKRECHT_917_ENUM (ZAKELIJKRECHT_917_ENUM_ID);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

