CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    EMAILADRES VARCHAR2(80),
    FAXNUMMER VARCHAR2(20),
    IDENTIFICATIE VARCHAR2(255),
    KVKNUMMER VARCHAR2(20),
    NAAM VARCHAR2(200),
    RECHTSVORM VARCHAR2(100),
    REKENINGNUMMER VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE PACHTER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY
);

CREATE TABLE HUURDER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY
);

CREATE TABLE EIGENAAR (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(200),
    NUMMER VARCHAR2(255)
);

CREATE TABLE KP_PCHTR_RCHTSPRSN (
    KP_PCHTR_RCHTSPRSN_ID NUMBER PRIMARY KEY,
    PACHTER_ID NUMBER,
    RECHTSPERSOON_ID NUMBER
);

CREATE TABLE KP_HRDR_RCHTSPRSN (
    KP_HRDR_RCHTSPRSN_ID NUMBER PRIMARY KEY,
    HUURDER_ID NUMBER,
    RECHTSPERSOON_ID NUMBER
);

CREATE TABLE KP_EGNR_RCHTSPRSN (
    KP_EGNR_RCHTSPRSN_ID NUMBER PRIMARY KEY,
    EIGENAAR_ID NUMBER,
    RECHTSPERSOON_ID NUMBER
);

CREATE TABLE KP_LVRNCR_RCHTSPRSN (
    KP_LVRNCR_RCHTSPRSN_ID NUMBER PRIMARY KEY,
    LEVERANCIER_ID NUMBER,
    RECHTSPERSOON_ID NUMBER
);

ALTER TABLE EIGENAAR ADD CONSTRAINT FK_EIGENAAR_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE HUURDER ADD CONSTRAINT FK_HUURDER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE PACHTER ADD CONSTRAINT FK_PACHTER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_LVRNCR_RCHTSPRSN ADD CONSTRAINT FK_KP_LVRNCR_RCHTSPRSN_1 FOREIGN KEY (LEVERANCIER_ID) REFERENCES LEVERANCIER (RECHTSPERSOON_ID);
-- LEVERANCIER (many-to-many junction, Connector_ID: 390)

ALTER TABLE KP_LVRNCR_RCHTSPRSN ADD CONSTRAINT FK_KP_LVRNCR_RCHTSPRSN_2 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 390)

ALTER TABLE KP_PCHTR_RCHTSPRSN ADD CONSTRAINT FK_KP_PCHTR_RCHTSPRSN_1 FOREIGN KEY (PACHTER_ID) REFERENCES PACHTER (RECHTSPERSOON_ID);
-- PACHTER (many-to-many junction, Connector_ID: 554)

ALTER TABLE KP_PCHTR_RCHTSPRSN ADD CONSTRAINT FK_KP_PCHTR_RCHTSPRSN_2 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 554)

ALTER TABLE KP_HRDR_RCHTSPRSN ADD CONSTRAINT FK_KP_HRDR_RCHTSPRSN_1 FOREIGN KEY (HUURDER_ID) REFERENCES HUURDER (RECHTSPERSOON_ID);
-- HUURDER (many-to-many junction, Connector_ID: 574)

ALTER TABLE KP_HRDR_RCHTSPRSN ADD CONSTRAINT FK_KP_HRDR_RCHTSPRSN_2 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 574)

ALTER TABLE KP_EGNR_RCHTSPRSN ADD CONSTRAINT FK_KP_EGNR_RCHTSPRSN_1 FOREIGN KEY (EIGENAAR_ID) REFERENCES EIGENAAR (RECHTSPERSOON_ID);
-- EIGENAAR (many-to-many junction, Connector_ID: 577)

ALTER TABLE KP_EGNR_RCHTSPRSN ADD CONSTRAINT FK_KP_EGNR_RCHTSPRSN_2 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 577)

