CREATE TABLE INKOOPORDER (
    INKOOPORDER_ID NUMBER PRIMARY KEY,
    ARTIKELCODE VARCHAR2(80),
    BETALINGMEERDEREJAREN NUMBER(1),
    BETREFT VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMINGEDIEND DATE,
    DATUMSTART DATE,
    GERELATEERD_INKOOPORDER_ID NUMBER,
    GOEDERENCODE VARCHAR2(80),
    HOORT_BIJ_WERKBON_ID NUMBER,
    OMSCHRIJVING VARCHAR2(255),
    OORSPRONKELIJK_INKOOPORDER_ID NUMBER,
    ORDERNUMMER VARCHAR2(255),
    SALDO VARCHAR2(255),
    TOTAALNETTOBEDRAG NUMBER(10,2),
    WIJZEVANAANBESTEDEN VARCHAR2(255)
);

CREATE TABLE BOUWDEEL (
    BOUWDEEL_ID NUMBER PRIMARY KEY,
    BESTAAT_UIT_BOUWDEELELEMENT_ID NUMBER,
    CODE VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(80)
);

CREATE TABLE ZAKELIJKRECHT_2335 (
    ZAKELIJKRECHT_2335_ID NUMBER PRIMARY KEY,
    AARDZAKELIJKRECHT VARCHAR2(255),
    DATUMEINDERECHT DATE,
    DATUMINGANGRECHT DATE,
    IDENTIFICATIEZAKELIJKRECHT VARCHAR2(255),
    IS_BELAST_MET_ZAKELIJKRECHT_2335_ID NUMBER,
    TOELICHTINGBEWAARDER VARCHAR2(100)
);

CREATE TABLE BOUWDEELELEMENT (
    BOUWDEELELEMENT_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(80)
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID NUMBER PRIMARY KEY,
    BTWCODE VARCHAR2(255),
    BTWOMSCHRIJVING VARCHAR2(80),
    HEEFT_VASTGOEDOBJECT_ID NUMBER,
    KOSTENPLAATSSOORTCODE NUMBER(10,2),
    KOSTENPLAATSSOORTOMSCHRIJVING NUMBER(10,2),
    KOSTENPLAATSTYPECODE NUMBER(10,2),
    KOSTENPLAATSTYPEOMSCHRIJVING NUMBER(10,2),
    NAAM VARCHAR2(80),
    OMSCHRIJVING VARCHAR2(200)
);

CREATE TABLE HOOFDREKENING (
    HOOFDREKENING_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(80),
    NUMMER VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(200),
    PIAHOOFCATEGORIEOMSCHRIJVING VARCHAR2(80),
    PIAHOOFDCATEGORIECODE VARCHAR2(20),
    SUBCODE VARCHAR2(20),
    SUBCODEOMSCHRIJVING VARCHAR2(80),
    VALT_BINNEN_HOOFDREKENING_ID NUMBER
);

CREATE TABLE ZAKELIJKRECHT_917_ENUM (
    ZAKELIJKRECHT_917_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ZAKELIJKRECHT_917_ENUM (ZAKELIJKRECHT_917_ENUM_ID, VALUE) VALUES
    (1, 'EIGENDOM'),
    (2, 'HUUR'),
    (3, 'LEEG'),
    (4, 'ONBEKEND'),
    (5, 'PACHT'),
    (6, 'RECHT_VAN_OPSTAL');

CREATE TABLE VASTGOEDOBJECT (
    VASTGOEDOBJECT_ID NUMBER PRIMARY KEY,
    AANTALETAGES NUMBER,
    AANTALPARKEERPLAATSEN NUMBER,
    AANTALRIOLERINGEN NUMBER,
    ADRESAANDUIDING VARCHAR2(255),
    AFGEKOCHTEERFPACHT NUMBER(1),
    AFGESPROKENCONDITIESCORE_ENUM_ID NUMBER,
    AFKOOPWAARDE VARCHAR2(255),
    ASBESTRAPPORTAGEAANWEZIG NUMBER(1),
    BEDRAGAANKOOP NUMBER(10,2),
    BESTAAT_UIT_BOUWDEEL_ID NUMBER,
    BESTEMMINGSPLAN VARCHAR2(200),
    BETREFT_INSPECTIE_ID NUMBER,
    BOEKWAARDE VARCHAR2(255),
    BOUWJAAR NUMBER,
    BOUWWERK VARCHAR2(80),
    BOVENLIGGENDNIVEAU VARCHAR2(80),
    BOVENLIGGENDNIVEAUCODE VARCHAR2(20),
    BRUTOVLOEROPPERVLAKTE NUMBER,
    CO2UITSTOOT NUMBER,
    CONDITIESCORE_ENUM_ID NUMBER,
    DATUMAFSTOTEN DATE,
    DATUMBEREKENINGOPPERVLAK DATE,
    DATUMEIGENDOM DATE,
    DATUMVERKOOP DATE,
    DEELPORTEFEUILLE VARCHAR2(80),
    ENERGIEKOSTEN NUMBER(10,2),
    ENERGIELABEL_ENUM_ID NUMBER,
    ENERGIEVERBRUIK NUMBER,
    FISCALEWAARDE VARCHAR2(255),
    FOTO VARCHAR2(255),
    GEARCHIVEERD NUMBER(1),
    HEEFT_VERHUURBAAR_EENHEID_ID NUMBER,
    HERBOUWWAARDE VARCHAR2(255),
    HOOFDSTUK VARCHAR2(80),
    IDENTIFICATIE VARCHAR2(80),
    JAARLAATSTERENOVATIE VARCHAR2(255),
    KOSTENPLAATS NUMBER(10,2),
    LOCATIE VARCHAR2(255),
    MARKTWAARDE VARCHAR2(255),
    MONUMENT VARCHAR2(255),
    NAAM VARCHAR2(80),
    OBJECTSTATUS VARCHAR2(255),
    OBJECTSTATUSCODE VARCHAR2(255),
    OBJECTTYPE VARCHAR2(80),
    OBJECTTYPECODE VARCHAR2(255),
    OMSCHRIJVING VARCHAR2(80),
    ONDERHOUDSCATEGORIE VARCHAR2(80),
    OPPERVLAKTEKANTOOR NUMBER,
    PORTEFEUILLE VARCHAR2(80),
    PORTEFEUILLECODE VARCHAR2(255),
    PROVINCIE VARCHAR2(255),
    TOELICHTING CLOB,
    VERHUURBAARVLOEROPPERVLAK NUMBER,
    VERKOOPBAARHEID VARCHAR2(80),
    VERKOOPBEDRAG NUMBER(10,2),
    VERZEKERDEWAARDE VARCHAR2(255),
    WAARDEGROND VARCHAR2(255),
    WAARDEOPSTAL VARCHAR2(255),
    WIJK VARCHAR2(255),
    WOZWAARDE VARCHAR2(255)
);

CREATE TABLE KP_INKPRDR_HFDRKNNG (
    KP_INKPRDR_HFDRKNNG_ID NUMBER PRIMARY KEY,
    INKOOPORDER_ID NUMBER,
    HOOFDREKENING_ID NUMBER
);

CREATE TABLE MJOP_ITEM (
    MJOP_ITEM_ID NUMBER PRIMARY KEY,
    BETREFT_BOUWDEELELEMENT_ID NUMBER,
    BETREFT_BOUWDEEL_ID NUMBER,
    BETREFT_VASTGOEDOBJECT_ID NUMBER,
    CODE VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMOPZEGGINGAANBIEDER DATE,
    DATUMOPZEGGINGONTVANGER DATE,
    DATUMSTART DATE,
    KOSTEN NUMBER(10,2),
    OMSCHRIJVING VARCHAR2(80),
    OPZEGTERMIJNAANBIEDER NUMBER,
    OPZEGTERMIJNONTVANGER NUMBER,
    OP_BASIS_VAN_PRIJZENBOEKITEM_ID NUMBER
);

CREATE TABLE INSPECTIE (
    INSPECTIE_ID NUMBER PRIMARY KEY,
    BEVINDINGEN CLOB,
    DATUM DATE,
    LEIDT_TOT_MJOP_ID NUMBER
);

CREATE TABLE KP_VSTGDBJCT_ZKLJK_RCHT (
    KP_VSTGDBJCT_ZKLJK_RCHT_ID NUMBER PRIMARY KEY,
    VASTGOEDOBJECT_ID NUMBER,
    ZAKELIJK_RECHT_ID NUMBER
);

CREATE TABLE PRIJZENBOEKITEM (
    PRIJZENBOEKITEM_ID NUMBER PRIMARY KEY,
    DATUMEINDEGELDIGHEID DATE,
    DATUMSTART DATE,
    PRIJS NUMBER(10,2),
    VERRICHTING VARCHAR2(80)
);

CREATE TABLE KP_WRKBN_BWDL (
    KP_WRKBN_BWDL_ID NUMBER PRIMARY KEY,
    WERKBON_ID NUMBER,
    BOUWDEEL_ID NUMBER
);

CREATE TABLE VASTGOED_CONTRACT (
    VASTGOED_CONTRACT_ID NUMBER PRIMARY KEY,
    BESCHRIJVING VARCHAR2(200),
    DATUMEINDE DATE,
    DATUMSTART DATE,
    HEEFT_RECHTSPERSOON_ID NUMBER,
    IDENTIFICATIE VARCHAR2(80),
    MAANDBEDRAG NUMBER(10,2),
    OPZEGTERMIJN VARCHAR2(80),
    STATUS VARCHAR2(80),
    TYPE VARCHAR2(80)
);

CREATE TABLE MJOP (
    MJOP_ID NUMBER PRIMARY KEY,
    BESTAAT_UIT_MJOP_ITEM_ID NUMBER,
    BETREFT_VASTGOEDOBJECT_ID NUMBER,
    DATUM DATE,
    GEREALISEERD_DOOR_WERKBON_ID NUMBER,
    OMSCHRIJVING CLOB
);

CREATE TABLE KP_WRKBN_BWDLLMNT (
    KP_WRKBN_BWDLLMNT_ID NUMBER PRIMARY KEY,
    WERKBON_ID NUMBER,
    BOUWDEELELEMENT_ID NUMBER
);

CREATE TABLE ENERGIELABEL_GEBOUWEN_ENUM (
    ENERGIELABEL_GEBOUWEN_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ENERGIELABEL_GEBOUWEN_ENUM (ENERGIELABEL_GEBOUWEN_ENUM_ID, VALUE) VALUES
    (1, 'A'),
    (2, 'A_'),
    (3, 'A_'),
    (4, 'B'),
    (5, 'C'),
    (6, 'D'),
    (7, 'E'),
    (8, 'F'),
    (9, 'G'),
    (10, 'LEEG'),
    (11, 'ONBEKEND');

CREATE TABLE ZAKELIJK_RECHT (
    ZAKELIJKRECHT_2335_ID NUMBER PRIMARY KEY,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    HEEFT_KOSTENPLAATS_ID NUMBER,
    KOSTEN NUMBER(10,2),
    SOORT_ENUM_ID NUMBER
);

CREATE TABLE WERKBON (
    WERKBON_ID NUMBER PRIMARY KEY,
    BETREFT_VASTGOEDOBJECT_ID NUMBER
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    EMAILADRES VARCHAR2(80),
    FAXNUMMER VARCHAR2(20),
    IDENTIFICATIE VARCHAR2(255),
    KVKNUMMER VARCHAR2(20),
    NAAM VARCHAR2(200),
    RECHTSVORM VARCHAR2(100),
    REKENINGNUMMER VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE VERHUURBAAR_EENHEID (
    VERHUURBAAR_EENHEID_ID NUMBER PRIMARY KEY,
    ADRES VARCHAR2(255),
    AFMETING NUMBER,
    BEZETTING NUMBER,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    DATUMWERKELIJKBEGIN DATE,
    DATUMWERKELIJKEINDE DATE,
    HUURPRIJS NUMBER(10,2),
    IDENTIFICATIE VARCHAR2(80),
    NAAM VARCHAR2(80),
    NETTOOMTREK NUMBER,
    NETTOOPPERVLAK NUMBER,
    OPMERKINGEN CLOB,
    TYPE VARCHAR2(80)
);

CREATE TABLE NEN2767_CONDITIESCORE_ENUM (
    NEN2767_CONDITIESCORE_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO NEN2767_CONDITIESCORE_ENUM (NEN2767_CONDITIESCORE_ENUM_ID, VALUE) VALUES
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, 'LEEG'),
    (8, 'ONBEKEND');

CREATE TABLE KP_HFDRKNNG_KSTNPLTS (
    KP_HFDRKNNG_KSTNPLTS_ID NUMBER PRIMARY KEY,
    HOOFDREKENING_ID NUMBER,
    KOSTENPLAATS_ID NUMBER
);

CREATE TABLE KP_KSTNPLTS_INKPRDR (
    KP_KSTNPLTS_INKPRDR_ID NUMBER PRIMARY KEY,
    KOSTENPLAATS_ID NUMBER,
    INKOOPORDER_ID NUMBER
);

ALTER TABLE ZAKELIJK_RECHT ADD CONSTRAINT FK_ZAKELIJK_RECHT_GEN_ZAKELIJKRECHT_2335 FOREIGN KEY (ZAKELIJKRECHT_2335_ID) REFERENCES ZAKELIJKRECHT_2335 (ZAKELIJKRECHT_2335_ID);
-- Generalization to ZAKELIJKRECHT_2335

ALTER TABLE KP_KSTNPLTS_INKPRDR ADD CONSTRAINT FK_KP_KSTNPLTS_INKPRDR_1 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 492)

ALTER TABLE KP_KSTNPLTS_INKPRDR ADD CONSTRAINT FK_KP_KSTNPLTS_INKPRDR_2 FOREIGN KEY (INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- INKOOPORDER (many-to-many junction, Connector_ID: 492)

ALTER TABLE KP_INKPRDR_HFDRKNNG ADD CONSTRAINT FK_KP_INKPRDR_HFDRKNNG_1 FOREIGN KEY (INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- INKOOPORDER (many-to-many junction, Connector_ID: 499)

ALTER TABLE KP_INKPRDR_HFDRKNNG ADD CONSTRAINT FK_KP_INKPRDR_HFDRKNNG_2 FOREIGN KEY (HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- HOOFDREKENING (many-to-many junction, Connector_ID: 499)

ALTER TABLE KP_HFDRKNNG_KSTNPLTS ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_1 FOREIGN KEY (HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- HOOFDREKENING (many-to-many junction, Connector_ID: 505)

ALTER TABLE KP_HFDRKNNG_KSTNPLTS ADD CONSTRAINT FK_KP_HFDRKNNG_KSTNPLTS_2 FOREIGN KEY (KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- KOSTENPLAATS (many-to-many junction, Connector_ID: 505)

ALTER TABLE KP_VSTGDBJCT_ZKLJK_RCHT ADD CONSTRAINT FK_KP_VSTGDBJCT_ZKLJK_RCHT_1 FOREIGN KEY (VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- VASTGOEDOBJECT (many-to-many junction, Connector_ID: 544)

ALTER TABLE KP_VSTGDBJCT_ZKLJK_RCHT ADD CONSTRAINT FK_KP_VSTGDBJCT_ZKLJK_RCHT_2 FOREIGN KEY (ZAKELIJK_RECHT_ID) REFERENCES ZAKELIJK_RECHT (ZAKELIJKRECHT_2335_ID);
-- ZAKELIJK_RECHT (many-to-many junction, Connector_ID: 544)

ALTER TABLE KP_WRKBN_BWDLLMNT ADD CONSTRAINT FK_KP_WRKBN_BWDLLMNT_1 FOREIGN KEY (WERKBON_ID) REFERENCES WERKBON (WERKBON_ID);
-- WERKBON (many-to-many junction, Connector_ID: 580)

ALTER TABLE KP_WRKBN_BWDLLMNT ADD CONSTRAINT FK_KP_WRKBN_BWDLLMNT_2 FOREIGN KEY (BOUWDEELELEMENT_ID) REFERENCES BOUWDEELELEMENT (BOUWDEELELEMENT_ID);
-- BOUWDEELELEMENT (many-to-many junction, Connector_ID: 580)

ALTER TABLE KP_WRKBN_BWDL ADD CONSTRAINT FK_KP_WRKBN_BWDL_1 FOREIGN KEY (WERKBON_ID) REFERENCES WERKBON (WERKBON_ID);
-- WERKBON (many-to-many junction, Connector_ID: 582)

ALTER TABLE KP_WRKBN_BWDL ADD CONSTRAINT FK_KP_WRKBN_BWDL_2 FOREIGN KEY (BOUWDEEL_ID) REFERENCES BOUWDEEL (BOUWDEEL_ID);
-- BOUWDEEL (many-to-many junction, Connector_ID: 582)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_OORSPRONKELIJK FOREIGN KEY (OORSPRONKELIJK_INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- OORSPRONKELIJK (0..1 to 0..1, Connector_ID: 493)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_GERELATEERD FOREIGN KEY (GERELATEERD_INKOOPORDER_ID) REFERENCES INKOOPORDER (INKOOPORDER_ID);
-- GERELATEERD (0..1 to 0..*, Connector_ID: 494)

ALTER TABLE HOOFDREKENING ADD CONSTRAINT FK_HOOFDREKENING_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_HOOFDREKENING_ID) REFERENCES HOOFDREKENING (HOOFDREKENING_ID);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 504)

ALTER TABLE ZAKELIJK_RECHT ADD CONSTRAINT FK_ZAKELIJK_RECHT_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..* to 1, Connector_ID: 534)

ALTER TABLE INKOOPORDER ADD CONSTRAINT FK_INKOOPORDER_HOORT_BIJ FOREIGN KEY (HOORT_BIJ_WERKBON_ID) REFERENCES WERKBON (WERKBON_ID);
-- HOORT_BIJ (1 to 0..*, Connector_ID: 539)

ALTER TABLE KOSTENPLAATS ADD CONSTRAINT FK_KOSTENPLAATS_HEEFT FOREIGN KEY (HEEFT_VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- HEEFT (1 to 0..*, Connector_ID: 540)

ALTER TABLE WERKBON ADD CONSTRAINT FK_WERKBON_BETREFT FOREIGN KEY (BETREFT_VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- BETREFT (0..* to 1, Connector_ID: 542)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_HEEFT FOREIGN KEY (HEEFT_VERHUURBAAR_EENHEID_ID) REFERENCES VERHUURBAAR_EENHEID (VERHUURBAAR_EENHEID_ID);
-- HEEFT (1 to 0..*, Connector_ID: 547)

ALTER TABLE VASTGOED_CONTRACT ADD CONSTRAINT FK_VASTGOED_CONTRACT_HEEFT FOREIGN KEY (HEEFT_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- HEEFT (0..* to 1, Connector_ID: 552)

ALTER TABLE MJOP_ITEM ADD CONSTRAINT FK_MJOP_ITEM_BETREFT FOREIGN KEY (BETREFT_VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- BETREFT (0..* to 1, Connector_ID: 558)

ALTER TABLE MJOP_ITEM ADD CONSTRAINT FK_MJOP_ITEM_OP_BASIS_VAN FOREIGN KEY (OP_BASIS_VAN_PRIJZENBOEKITEM_ID) REFERENCES PRIJZENBOEKITEM (PRIJZENBOEKITEM_ID);
-- OP_BASIS_VAN (0..* to 1, Connector_ID: 559)

ALTER TABLE MJOP ADD CONSTRAINT FK_MJOP_GEREALISEERD_DOOR FOREIGN KEY (GEREALISEERD_DOOR_WERKBON_ID) REFERENCES WERKBON (WERKBON_ID);
-- GEREALISEERD_DOOR (1 to 0..*, Connector_ID: 560)

ALTER TABLE MJOP ADD CONSTRAINT FK_MJOP_BETREFT FOREIGN KEY (BETREFT_VASTGOEDOBJECT_ID) REFERENCES VASTGOEDOBJECT (VASTGOEDOBJECT_ID);
-- BETREFT (0..* to 1, Connector_ID: 561)

ALTER TABLE MJOP ADD CONSTRAINT FK_MJOP_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_MJOP_ITEM_ID) REFERENCES MJOP_ITEM (MJOP_ITEM_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 562)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_BETREFT FOREIGN KEY (BETREFT_INSPECTIE_ID) REFERENCES INSPECTIE (INSPECTIE_ID);
-- BETREFT (1 to 0..*, Connector_ID: 571)

ALTER TABLE INSPECTIE ADD CONSTRAINT FK_INSPECTIE_LEIDT_TOT FOREIGN KEY (LEIDT_TOT_MJOP_ID) REFERENCES MJOP (MJOP_ID);
-- LEIDT_TOT (0..1 to 0..1, Connector_ID: 572)

ALTER TABLE MJOP_ITEM ADD CONSTRAINT FK_MJOP_ITEM_BETREFT_2 FOREIGN KEY (BETREFT_BOUWDEELELEMENT_ID) REFERENCES BOUWDEELELEMENT (BOUWDEELELEMENT_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 579)

ALTER TABLE MJOP_ITEM ADD CONSTRAINT FK_MJOP_ITEM_BETREFT_3 FOREIGN KEY (BETREFT_BOUWDEEL_ID) REFERENCES BOUWDEEL (BOUWDEEL_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 581)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_BOUWDEEL_ID) REFERENCES BOUWDEEL (BOUWDEEL_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 583)

ALTER TABLE BOUWDEEL ADD CONSTRAINT FK_BOUWDEEL_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_BOUWDEELELEMENT_ID) REFERENCES BOUWDEELELEMENT (BOUWDEELELEMENT_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 584)

ALTER TABLE ZAKELIJKRECHT_2335 ADD CONSTRAINT FK_ZAKELIJKRECHT_2335_IS_BELAST_MET FOREIGN KEY (IS_BELAST_MET_ZAKELIJKRECHT_2335_ID) REFERENCES ZAKELIJKRECHT_2335 (ZAKELIJKRECHT_2335_ID);
-- IS_BELAST_MET (0..1 to 0..*, Connector_ID: 1944)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_ENERGIELABEL_ENUM_ID FOREIGN KEY (ENERGIELABEL_ENUM_ID) REFERENCES ENERGIELABEL_GEBOUWEN_ENUM (ENERGIELABEL_GEBOUWEN_ENUM_ID);
-- ENERGIELABEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_CONDITIESCORE_ENUM_ID FOREIGN KEY (CONDITIESCORE_ENUM_ID) REFERENCES NEN2767_CONDITIESCORE_ENUM (NEN2767_CONDITIESCORE_ENUM_ID);
-- CONDITIESCORE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VASTGOEDOBJECT ADD CONSTRAINT FK_VASTGOEDOBJECT_AFGESPROKENCONDITIESCORE_ENUM_ID FOREIGN KEY (AFGESPROKENCONDITIESCORE_ENUM_ID) REFERENCES NEN2767_CONDITIESCORE_ENUM (NEN2767_CONDITIESCORE_ENUM_ID);
-- AFGESPROKENCONDITIESCORE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE ZAKELIJK_RECHT ADD CONSTRAINT FK_ZAKELIJK_RECHT_SOORT_ENUM_ID FOREIGN KEY (SOORT_ENUM_ID) REFERENCES ZAKELIJKRECHT_917_ENUM (ZAKELIJKRECHT_917_ENUM_ID);
-- SOORT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

