CREATE TABLE [KP_GMNT_IS_OVRGGN_IN] (
    [KP_GMNT_IS_OVRGGN_IN_ID] INT PRIMARY KEY,
    [IS_OVERGEGAAN_IN_1_ID] INT,
    [IS_OVERGEGAAN_IN_2_ID] INT
);

CREATE TABLE [VERBLIJFSOBJECT] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [AANTALKAMERS] VARCHAR(255),
    [BEGINGELDIGHEID] DATE,
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDGELDIGHEID] DATE,
    [GEBRUIKSDOEL_ENUM_ID] INT,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [HEEFT_VASTGOEDOBJECT_ID] INT,
    [HOOGSTEBOUWLAAG] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [LAAGSTEBOUWLAAG] VARCHAR(255),
    [ONTSLUITINGVERDIEPING_ENUM_ID] INT,
    [OPPERVLAKTE] INT,
    [SOORTWOONOBJECT_ENUM_ID] INT,
    [STATUS_ENUM_ID] INT,
    [TOEGANGBOUWLAAG] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [NUMMERAANDUIDING] (
    [NUMMERAANDUIDING_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDEGELDIGHEID] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [HUISLETTER] VARCHAR(255),
    [HUISNUMMER] VARCHAR(255),
    [HUISNUMMERTOEVOEGING] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [LIGT_AAN_OPENBARERUIMTE_ID] INT,
    [LIGT_IN_BUURT_ID] INT,
    [LIGT_IN_WOONPLAATS_ID] INT,
    [POSTCODE] VARCHAR(255),
    [STATUS_ENUM_ID] INT,
    [TYPEADRESSEERBAAROBJECT_ENUM_ID] INT,
    [VERSIE] INT
);

CREATE TABLE [VERHUURBAAR_EENHEID] (
    [VERHUURBAAR_EENHEID_ID] INT PRIMARY KEY,
    [ADRES] VARCHAR(255),
    [AFMETING] INT,
    [BETREFT_VASTGOEDCONTRACTREGEL_ID] INT,
    [BEZETTING] INT,
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [DATUMWERKELIJKBEGIN] DATE,
    [DATUMWERKELIJKEINDE] DATE,
    [HUURPRIJS] DECIMAL(10,2),
    [IDENTIFICATIE] VARCHAR(80),
    [NAAM] VARCHAR(80),
    [NETTOOMTREK] INT,
    [NETTOOPPERVLAK] INT,
    [OPMERKINGEN] NVARCHAR(MAX),
    [TYPE] VARCHAR(80)
);

CREATE TABLE [STATUSNUMMERAANDUIDING_ENUM] (
    [STATUSNUMMERAANDUIDING_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [STATUSNUMMERAANDUIDING_ENUM] ([STATUSNUMMERAANDUIDING_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'NAAMGEVING_INGETROKKEN'),
    (3, 'NAAMGEVING_UITGEGEVEN'),
    (4, 'ONBEKEND');

CREATE TABLE [KP_VSTGDBJCT_KDSTRLNRRNDZK] (
    [KP_VSTGDBJCT_KDSTRLNRRNDZK_ID] INT PRIMARY KEY,
    [VASTGOEDOBJECT_ID] INT,
    [KADASTRALEONROERENDEZAAK_ID] INT
);

CREATE TABLE [KP_NTNTRLJKPRSN_NTRLJKPRSN] (
    [KP_NTNTRLJKPRSN_NTRLJKPRSN_ID] INT PRIMARY KEY,
    [NIETNATUURLIJKPERSOON_ID] INT,
    [NATUURLIJKPERSOON_ID] INT
);

CREATE TABLE [KP_VRBLJFSBJCT_PND] (
    [KP_VRBLJFSBJCT_PND_ID] INT PRIMARY KEY,
    [VERBLIJFSOBJECT_ID] INT,
    [PAND_ID] INT
);

CREATE TABLE [LOCATIEONROERENDEZAAK] (
    [LOCATIEONROERENDEZAAK_ID] INT PRIMARY KEY,
    [ADRESTYPE_ENUM_ID] INT,
    [CULTUURCODEBEBOUWD] VARCHAR(255),
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [GEOMETRIE] GEOMETRY,
    [HEEFT_ADRESSEERBAAR_OBJECT_ADRESSEERBAAROBJECT_ID] INT,
    [HEEFT_ADRES_KADASTRALEONROERENDEZAAK_ID] INT,
    [LOCATIEOMSCHRIJVING] VARCHAR(255)
);

CREATE TABLE [KPONSTAANUIT] (
    [KPONSTAANUIT_ID] INT PRIMARY KEY,
    [APPARTEMENTSRECHTSPLITSING_ID] INT,
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [IS_ONTSTAAN_UIT_ZAKELIJKRECHT_ID] INT
);

CREATE TABLE [STATLIGPLAATSSTANDPLAATS_ENUM] (
    [STATLIGPLAATSSTANDPLAATS_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [STATLIGPLAATSSTANDPLAATS_ENUM] ([STATLIGPLAATSSTANDPLAATS_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'ONBEKEND'),
    (3, 'PLAATS_AANGEWEZEN'),
    (4, 'PLAATS_INGETROKKEN');

CREATE TABLE [RECHTSPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [ADRESBINNENLAND] VARCHAR(255),
    [ADRESBUITENLAND] VARCHAR(255),
    [ADRESCORRESPONDENTIE] VARCHAR(100),
    [EMAILADRES] VARCHAR(80),
    [FAXNUMMER] VARCHAR(20),
    [HEEFT_TENAAMSTELLING_ID] INT,
    [IDENTIFICATIE] VARCHAR(255),
    [KVKNUMMER] VARCHAR(20),
    [NAAM] VARCHAR(200),
    [RECHTSVORM] VARCHAR(100),
    [REKENINGNUMMER] VARCHAR(255),
    [TELEFOONNUMMER] VARCHAR(20)
);

CREATE TABLE [NADAANVULLINGBRP] (
    [NUMMERAANDUIDING_ID] INT PRIMARY KEY,
    [OPMERKINGEN] VARCHAR(100)
);

CREATE TABLE [NATUURLIJKPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [AANDUIDINGNAAMGEBRUIK] VARCHAR(50),
    [AANHEFAANSCHRIJVING] VARCHAR(50),
    [ACADEMISCHETITEL] VARCHAR(80),
    [ACHTERNAAM] VARCHAR(100),
    [ADELLIJKETITELOFPREDIKAAT_ENUM_ID] INT,
    [ANUMMER] VARCHAR(20),
    [BIJZONDERNEDERLANDERSCHAP] VARCHAR(50),
    [BURGERSERVICENUMMER] VARCHAR(255),
    [DATUMGEBOORTE] DATE,
    [DATUMOVERLIJDEN] DATE,
    [GEBOORTELAND] VARCHAR(255),
    [GEBOORTEPLAATS] VARCHAR(200),
    [GESLACHTSAANDUIDING] VARCHAR(255),
    [GESLACHTSNAAM] VARCHAR(200),
    [GESLACHTSNAAMAANSCHRIJVING] VARCHAR(200),
    [HANDLICHTING] VARCHAR(50),
    [INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID] INT,
    [INDICATIEOVERLEDEN_ENUM_ID] INT,
    [LANDOVERLIJDEN] VARCHAR(255),
    [NATIONALITEIT] VARCHAR(100),
    [OVERLIJDENSPLAATS] VARCHAR(200),
    [VOORLETTERSAANSCHRIJVING] VARCHAR(20),
    [VOORNAMEN] VARCHAR(200),
    [VOORNAMENAANSCHRIJVING] VARCHAR(200),
    [VOORVOEGSELGESLACHTSNAAM] VARCHAR(80)
);

CREATE TABLE [ZAKELIJKRECHT] (
    [ZAKELIJKRECHT_ID] INT PRIMARY KEY,
    [AARDZAKELIJKRECHT] VARCHAR(255),
    [DATUMEINDERECHT] DATE,
    [DATUMINGANGRECHT] DATE,
    [IDENTIFICATIEZAKELIJKRECHT] VARCHAR(255),
    [IS_BELAST_MET_ZAKELIJKRECHT_ID] INT,
    [RUST_OP_KADASTRALEONROERENDEZAAK_ID] INT,
    [TOELICHTINGBEWAARDER] VARCHAR(100)
);

CREATE TABLE [CULTUURCODEBEBOUWD] (
    [CULTUURCODEBEBOUWD_ID] INT PRIMARY KEY,
    [CODE] VARCHAR(255),
    [DATUMBEGINGELDIGHEIDCULTUURCODEBEBOUWD] DATE,
    [DATUMEINDEGELDIGHEIDCULTUURCODEBEBOUWD] DATE,
    [NAAMCULTUURCODEBEBOUWD] VARCHAR(255)
);

CREATE TABLE [VASTGOED_CONTRACT] (
    [VASTGOED_CONTRACT_ID] INT PRIMARY KEY,
    [BESCHRIJVING] VARCHAR(200),
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [HEEFT_RECHTSPERSOON_ID] INT,
    [IDENTIFICATIE] VARCHAR(80),
    [MAANDBEDRAG] DECIMAL(10,2),
    [OPZEGTERMIJN] VARCHAR(80),
    [STATUS] VARCHAR(80),
    [TYPE] VARCHAR(80)
);

CREATE TABLE [ONTSLUITINGSWIJZEVERDIEPING_ENUM] (
    [ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [ONTSLUITINGSWIJZEVERDIEPING_ENUM] ([ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'LIFT'),
    (3, 'ONBEKEND'),
    (4, 'ROLTRAP'),
    (5, 'TRAP');

CREATE TABLE [AARDZAKELIJKRECHT] (
    [AARDZAKELIJKRECHT_ID] INT PRIMARY KEY,
    [CODEAARDZAKELIJKRECHT] VARCHAR(255),
    [DATUMBEGINGELDIGHEIDAARDZAKELIJKRECHT] DATE,
    [DATUMEINDEGELDIGHEIDAARDZAKELIJKRECHT] DATE,
    [NAAMAARDZAKELIJKRECHT] VARCHAR(255)
);

CREATE TABLE [NIETNATUURLIJKPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [DATUMAANVANG] DATE,
    [DATUMEINDE] DATE,
    [DATUMUITSCHRIJVING] DATE,
    [DATUMVOORTZETTING] DATE,
    [FAXNUMMER] VARCHAR(20),
    [INGESCHREVEN_ENUM_ID] INT,
    [INOPRICHTING_ENUM_ID] INT,
    [KVKNUMMER] VARCHAR(255),
    [NNPID] VARCHAR(255),
    [RECHTSVORM_ENUM_ID] INT,
    [RSINNUMMER] VARCHAR(255),
    [STATUTAIRENAAM] VARCHAR(255),
    [STATUTAIREZETEL] VARCHAR(255),
    [WEBSITEURL] VARCHAR(200)
);

CREATE TABLE [KPBETROKKENBIJ] (
    [KPBETROKKENBIJ_ID] INT PRIMARY KEY,
    [APPARTEMENTSRECHTSPLITSING_ID] INT,
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [IS_BETROKKEN_BIJ_ZAKELIJKRECHT_ID] INT
);

CREATE TABLE [STATUSVERBLIJFSOBJECT_ENUM] (
    [STATUSVERBLIJFSOBJECT_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [STATUSVERBLIJFSOBJECT_ENUM] ([STATUSVERBLIJFSOBJECT_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'NIET_GEREALISEERD_VERBLIJFSOBJECT'),
    (3, 'ONBEKEND'),
    (4, 'VERBLIJFSOBJECT_BUITEN_GEBRUIK'),
    (5, 'VERBLIJFSOBJECT_GEVORMD'),
    (6, 'VERBLIJFSOBJECT_INGETROKKEN'),
    (7, 'VERBLIJFSOBJECT_IN_GEBRUIK'),
    (8, 'VERBLIJFSOBJECT_IN_GEBRUIK_NIET_INGEMETEN_');

CREATE TABLE [ADRESSEERBAAROBJECT] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID] INT,
    [HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID] INT,
    [IDENTIFICATIE] VARCHAR(255),
    [TYPEADRESSEERBAAROBJECT_ENUM_ID] INT,
    [VERSIE] INT
);

CREATE TABLE [WOONPLAATS] (
    [WOONPLAATS_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDGELDIGHEID] DATE,
    [EINDREGISTRATIE] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [LIGT_IN_GEMEENTE_ID] INT,
    [STATUS_ENUM_ID] INT,
    [TIJDSTIPACTIEF] DATETIME2,
    [TIJDSTIPREGISTRATIE] DATETIME2,
    [VERSIE] INT,
    [VOORKOMEN] DATE,
    [WOONPLAATSNAAM] VARCHAR(80),
    [WOONPLAATSNAAMNEN] VARCHAR(255)
);

CREATE TABLE [STATUSPAND_ENUM] (
    [STATUSPAND_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [STATUSPAND_ENUM] ([STATUSPAND_ENUM_ID], VALUE) VALUES
    (1, 'BOUWAANVRAAG_ONTVANGEN'),
    (2, 'BOUWVERGUNNING_VERLEEND'),
    (3, 'BOUW_GESTART'),
    (4, 'LEEG'),
    (5, 'NIET_GEREALISEERD_PAND'),
    (6, 'ONBEKEND'),
    (7, 'PAND_BUITEN_GEBRUIK'),
    (8, 'PAND_GESLOOPT'),
    (9, 'PAND_IN_GEBRUIK'),
    (10, 'PAND_IN_GEBRUIK_NIET_INGEMETEN_'),
    (11, 'PAND_TEN_ONRECHTE_OPGEVOERD'),
    (12, 'SLOOPVERGUNNING_VERLEEND'),
    (13, 'VERBOUWING_PAND');

CREATE TABLE [TENAAMSTELLING] (
    [TENAAMSTELLING_ID] INT PRIMARY KEY,
    [AANDEELINRECHT] VARCHAR(255),
    [BURGERLIJKESTAATTENTIJDEVANVERKRIJGING] DATETIME2,
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [EXPLOITANTCODE] VARCHAR(255),
    [HEEFT_BETREKKING_OP_ZAKELIJKRECHT_ID] INT,
    [IDENTIFICATIETENAAMSTELLING] VARCHAR(255),
    [VERKLARINGINZAKEDERDENBESCHERMING] VARCHAR(100),
    [VERKREGENNAMENSSAMENWERKINGSVERBAND_ENUM_ID] INT
);

CREATE TABLE [INGESCHREVENPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [ADRESHERKOMST] VARCHAR(255),
    [ANUMMER] VARCHAR(20),
    [BESCHRIJVINGLOCATIE] VARCHAR(200),
    [BUITENLANDSREISDOCUMENT] VARCHAR(80),
    [BURGERLIJKESTAAT] VARCHAR(255),
    [DATUMBEGINGELDIGHEIDVERBLIJFPLAATS] DATE,
    [DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS] DATE,
    [DATUMINSCHRIJVINGGEMEENTE] DATE,
    [DATUMOPSCHORTINGBIJHOUDING] DATE,
    [DATUMVERTREKUITNEDERLAND] DATE,
    [DATUMVESTIGINGNEDERLAND] DATE,
    [GEMEENTEVANINSCHRIJVING] VARCHAR(80),
    [GEZINSRELATIE_ENUM_ID] INT,
    [HEEFT_ALS_ADRES_NUMMERAANDUIDING_ID] INT,
    [INDICATIEGEHEIM_ENUM_ID] INT,
    [INGEZETENE_ENUM_ID] INT,
    [LANDWAARNAARVERTROKKEN] VARCHAR(255),
    [LANDWAARVANDAANINGESCHREVEN] VARCHAR(255),
    [OUDER1] VARCHAR(255),
    [OUDER2] VARCHAR(255),
    [OUDER_1_INGESCHREVENPERSOON_ID] INT,
    [OUDER_2_INGESCHREVENPERSOON_ID] INT,
    [PARTNERID] VARCHAR(255),
    [REDENEINDEBEWONING] DATE,
    [REDENOPSCHORTINGBIJHOUDING] VARCHAR(200),
    [SIGNALERINGREISDOCUMENT_ENUM_ID] INT,
    [VERBLIJFSTITEL] VARCHAR(255)
);

CREATE TABLE [OVERIGBENOEMDTERREIN] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [GEBRUIKSDOELOVERIGBENOEMDTERREIN_ENUM_ID] INT,
    [OVERIGBENOEMDTERREINIDENTIFICATIE] VARCHAR(255)
);

CREATE TABLE [GESLACHT_ENUM] (
    [GESLACHT_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [GESLACHT_ENUM] ([GESLACHT_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'MAN'),
    (3, 'ONBEKEND'),
    (4, 'VROUW');

CREATE TABLE [ADELIJKETITEL_ENUM] (
    [ADELIJKETITEL_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [ADELIJKETITEL_ENUM] ([ADELIJKETITEL_ENUM_ID], VALUE) VALUES
    (1, 'BARON'),
    (2, 'BARONES'),
    (3, 'GRAAF'),
    (4, 'GRAVIN'),
    (5, 'HERTOG'),
    (6, 'HERTOGIN'),
    (7, 'LEEG'),
    (8, 'MARKIES'),
    (9, 'MARKIEZIN'),
    (10, 'ONBEKEND'),
    (11, 'PRINS'),
    (12, 'PRINSES'),
    (13, 'RIDDER');

CREATE TABLE [KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ] (
    [KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_ID] INT PRIMARY KEY,
    [IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID] INT,
    [IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID] INT
);

CREATE TABLE [KP_ZKLJKRCHT_TNMSTLLNG] (
    [KP_ZKLJKRCHT_TNMSTLLNG_ID] INT PRIMARY KEY,
    [ZAKELIJKRECHT_ID] INT,
    [TENAAMSTELLING_ID] INT
);

CREATE TABLE [OPENBARERUIMTE] (
    [OPENBARERUIMTE_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS] VARCHAR(255),
    [HUISNUMMERRANGE_EVEN_NUMMERS] VARCHAR(255),
    [HUISNUMMERRANGE_ONEVEN_NUMMERS] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [LABELNAAM] VARCHAR(80),
    [LIGT_IN_BUURT_ID] INT,
    [LIGT_IN_WOONPLAATS_ID] INT,
    [NAAMOPENBARERUIMTE] VARCHAR(80),
    [STATUS_ENUM_ID] INT,
    [STRAATCODE] VARCHAR(80),
    [STRAATNAAM] VARCHAR(255),
    [TYPEOPENBARERUIMTE_ENUM_ID] INT,
    [VERSIE] INT,
    [WEGSEGMENT] VARCHAR(255)
);

CREATE TABLE [KADASTRALEONROERENDEZAAK] (
    [KADASTRALEONROERENDEZAAK_ID] INT PRIMARY KEY,
    [APPARTEMENTSRECHTVOLGNUMMER] VARCHAR(255),
    [BEGRENZING] VARCHAR(255),
    [CULTUURCODEONBEBOUWD] VARCHAR(255),
    [DATUMBEGINGELDIGHEID] DATE,
    [DATUMEINDEGELDIGHEID] DATE,
    [GERELATEERD_KADASTRALEONROERENDEZAAK_ID] INT,
    [IDENTIFICATIE] VARCHAR(255),
    [KADASTRALEGEMEENTE] VARCHAR(20),
    [KADASTRALEGEMEENTECODE] VARCHAR(20),
    [KOOPJAAR] INT,
    [KOOPSOM] VARCHAR(255),
    [LANDINRICHTINGRENTEBEDRAG] DECIMAL(10,2),
    [LANDINRICHTINGRENTEEINDEJAAR] DATE,
    [LIGGING] VARCHAR(255),
    [LOCATIEOMSCHRIJVING] VARCHAR(255),
    [OPPERVLAKTE] INT,
    [PERCEELNUMMER] VARCHAR(255),
    [SECTIE] VARCHAR(255),
    [VALUTACODE] VARCHAR(255)
);

CREATE TABLE [CULTUURCODEONBEBOUWD] (
    [CULTUURCODEONBEBOUWD_ID] INT PRIMARY KEY,
    [CODE] VARCHAR(255),
    [DATUMBEGINGELDIGHEIDCULTUURCODEONBEBOUWD] DATE,
    [DATUMEINDEGELDIGHEIDCULTUURCODEONBEBOUWD] DATE,
    [NAAMCULTUURCODEONBEBOUWD] VARCHAR(255)
);

CREATE TABLE [STATUSOPENBARERUIMTE_ENUM] (
    [STATUSOPENBARERUIMTE_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [STATUSOPENBARERUIMTE_ENUM] ([STATUSOPENBARERUIMTE_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'NAAMGEVING_INGETROKKEN'),
    (3, 'NAAMGEVING_UITGEGEVEN'),
    (4, 'ONBEKEND');

CREATE TABLE [GEZINSRELATIE_ENUM] (
    [GEZINSRELATIE_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [GEZINSRELATIE_ENUM] ([GEZINSRELATIE_ENUM_ID], VALUE) VALUES
    (1, 'ALLEENSTAAND_SAMENWONEND'),
    (2, 'ECHTGENOTE_BINNEN_GEZIN'),
    (3, 'HOOFD_GEZIN_MET_KIND_EREN_'),
    (4, 'HOOFD_GEZIN_ZONDER_KIND_EREN_'),
    (5, 'HOOFD_HUWELIJK_GELIJK_GESLACHT'),
    (6, 'HOOFD_PARTNERRELATIE'),
    (7, 'KIND'),
    (8, 'LEEG'),
    (9, 'ONBEKEND'),
    (10, 'OUDER_MET_KIND_EREN_');

CREATE TABLE [BUURT] (
    [BUURT_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [CODE] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [LIGT_IN_WIJK_ID] INT,
    [NAAM] VARCHAR(255),
    [STATUS_ENUM_ID] INT,
    [VERSIE] INT
);

CREATE TABLE [STANDPLAATS] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [DATUM_BEGIN_GELDIGHEID] DATE,
    [DATUM_EINDE] DATE,
    [DATUM_EINDE_GELDIGHEID] DATE,
    [DATUM_INGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [VASTGOEDCONTRACTREGEL] (
    [VASTGOEDCONTRACTREGEL_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [FREQUENTIE] VARCHAR(80),
    [HEEFT_VASTGOED_CONTRACT_ID] INT,
    [IDENTIFICATIE] VARCHAR(80),
    [OMSCHRIJVING] VARCHAR(200),
    [STATUS] VARCHAR(80),
    [TYPE] VARCHAR(80)
);

CREATE TABLE [TYPERINGAPPARTEMENTSRECHTSPLITSING_ENUM] (
    [TYPERINGAPPARTEMENTSRECHTSPLITSING_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [TYPERINGAPPARTEMENTSRECHTSPLITSING_ENUM] ([TYPERINGAPPARTEMENTSRECHTSPLITSING_ENUM_ID], VALUE) VALUES
    (1, 'HOOFDSPLITSING'),
    (2, 'LEEG'),
    (3, 'ONBEKEND'),
    (4, 'ONDERSPLITSING'),
    (5, 'SPLITSINGAFKOOPERFPACHT');

CREATE TABLE [LIGPLAATS] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] DATE,
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [VERSIE] VARCHAR(255)
);

CREATE TABLE [VASTGOEDOBJECT] (
    [VASTGOEDOBJECT_ID] INT PRIMARY KEY,
    [AANTALETAGES] INT,
    [AANTALPARKEERPLAATSEN] INT,
    [AANTALRIOLERINGEN] INT,
    [ADRESAANDUIDING] VARCHAR(255),
    [AFGEKOCHTEERFPACHT_ENUM_ID] INT,
    [AFGESPROKENCONDITIESCORE_ENUM_ID] INT,
    [AFKOOPWAARDE] VARCHAR(255),
    [ASBESTRAPPORTAGEAANWEZIG_ENUM_ID] INT,
    [BEDRAGAANKOOP] DECIMAL(10,2),
    [BESTEMMINGSPLAN] VARCHAR(200),
    [BOEKWAARDE] VARCHAR(255),
    [BOUWJAAR] INT,
    [BOUWWERK] VARCHAR(80),
    [BOVENLIGGENDNIVEAU] VARCHAR(80),
    [BOVENLIGGENDNIVEAUCODE] VARCHAR(20),
    [BRUTOVLOEROPPERVLAKTE] INT,
    [CO2UITSTOOT] INT,
    [CONDITIESCORE_ENUM_ID] INT,
    [DATUMAFSTOTEN] DATE,
    [DATUMBEREKENINGOPPERVLAK] DATE,
    [DATUMEIGENDOM] DATE,
    [DATUMVERKOOP] DATE,
    [DEELPORTEFEUILLE] VARCHAR(80),
    [ENERGIEKOSTEN] DECIMAL(10,2),
    [ENERGIELABEL_ENUM_ID] INT,
    [ENERGIEVERBRUIK] INT,
    [FISCALEWAARDE] VARCHAR(255),
    [FOTO] VARCHAR(255),
    [GEARCHIVEERD_ENUM_ID] INT,
    [HEEFT_VASTGOEDCONTRACTREGEL_ID] INT,
    [HEEFT_VERHUURBAAR_EENHEID_ID] INT,
    [HERBOUWWAARDE] VARCHAR(255),
    [HOOFDSTUK] VARCHAR(80),
    [IDENTIFICATIE] VARCHAR(80),
    [JAARLAATSTERENOVATIE] VARCHAR(255),
    [KOSTENPLAATS] DECIMAL(10,2),
    [LOCATIE] VARCHAR(255),
    [MARKTWAARDE] VARCHAR(255),
    [MONUMENT_ENUM_ID] INT,
    [NAAM] VARCHAR(80),
    [OBJECTSTATUS] VARCHAR(255),
    [OBJECTSTATUSCODE] VARCHAR(255),
    [OBJECTTYPE] VARCHAR(80),
    [OBJECTTYPECODE] VARCHAR(255),
    [OMSCHRIJVING] VARCHAR(80),
    [ONDERHOUDSCATEGORIE] VARCHAR(80),
    [OPPERVLAKTEKANTOOR] INT,
    [PORTEFEUILLE] VARCHAR(80),
    [PORTEFEUILLECODE] VARCHAR(255),
    [PROVINCIE] VARCHAR(255),
    [TOELICHTING] NVARCHAR(MAX),
    [VERHUURBAARVLOEROPPERVLAK] INT,
    [VERKOOPBAARHEID] VARCHAR(80),
    [VERKOOPBEDRAG] DECIMAL(10,2),
    [VERZEKERDEWAARDE] VARCHAR(255),
    [WAARDEGROND] VARCHAR(255),
    [WAARDEOPSTAL] VARCHAR(255),
    [WIJK] VARCHAR(255),
    [WOZWAARDE] VARCHAR(255)
);

CREATE TABLE [GEBRUIKSDOEL_ENUM] (
    [GEBRUIKSDOEL_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [GEBRUIKSDOEL_ENUM] ([GEBRUIKSDOEL_ENUM_ID], VALUE) VALUES
    (1, 'BIJEENKOMSTFUNCTIE'),
    (2, 'CELFUNCTIE_'),
    (3, 'GEZONDHEIDSZORGFUNCTIE'),
    (4, 'INDUSTRIEFUNCTIE'),
    (5, 'KANTOORFUNCTIE'),
    (6, 'LEEG'),
    (7, 'LOGIESFUNCTIE'),
    (8, 'ONBEKEND'),
    (9, 'ONDERWIJSFUNCTIE_'),
    (10, 'OVERIGE_GEBRUIKSFUNCTIE_'),
    (11, 'SPORTFUNCTIE_'),
    (12, 'WINKELFUNCTIE_'),
    (13, 'WOONFUNCTIE_');

CREATE TABLE [STATUSWOONPLAATS_ENUM] (
    [STATUSWOONPLAATS_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [STATUSWOONPLAATS_ENUM] ([STATUSWOONPLAATS_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'ONBEKEND'),
    (3, 'WOONPLAATS_AANGEWEZEN'),
    (4, 'WOONPLAATS_INGETROKKEN_');

CREATE TABLE [SOORTRECHTSVORM_ENUM] (
    [SOORTRECHTSVORM_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [SOORTRECHTSVORM_ENUM] ([SOORTRECHTSVORM_ENUM_ID], VALUE) VALUES
    (1, 'BESLOTEN_VENNOOTSCHAP'),
    (2, 'COMMANDITAIRE_VENNOOTSCHAP'),
    (3, 'COOPERATIE_EUROPEES_ECONOMISCHE_SAMENWERKING'),
    (4, 'EUROPESE_COOPERATIEVE_VENNOOTSCHAP'),
    (5, 'EUROPESE_NAAMLOZE_VENNOOTSCHAP'),
    (6, 'KAPITAALVENNOOTSCHAP_BINNEN_EER'),
    (7, 'KAPITAALVENNOOTSCHAP_BUITEN_EER'),
    (8, 'KERKELIJKE_ORGANISATIE'),
    (9, 'LEEG'),
    (10, 'MAATSCHAP'),
    (11, 'NAAMLOZE_VENNOOTSCHAP'),
    (12, 'ONBEKEND'),
    (13, 'ONDERLINGE_WAARBORG_MAATSCHAPPIJ'),
    (14, 'OVERIGE_BUITENLANDSE_RECHTSPERSOON_VENNOOTSCHAP'),
    (15, 'OVERIG_PRIVAATRECHTELIJKE_RECHTSPERSOON'),
    (16, 'PUBLIEKRECHTELIJKE_RECHTSPERSOON'),
    (17, 'REDERIJ'),
    (18, 'STICHTING'),
    (19, 'VENNOOTSCHAP_ONDER_FIRMA'),
    (20, 'VERENIGING'),
    (21, 'VERENIGING_VAN_EIGENAARS');

CREATE TABLE [GEMEENTE] (
    [GEMEENTE_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEMEENTECODE] VARCHAR(255),
    [GEMEENTENAAM] VARCHAR(80),
    [GEMEENTENAAM_NEN] VARCHAR(255),
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [APPARTEMENTSRECHTSPLITSING] (
    [APPARTEMENTSRECHTSPLITSING_ID] INT PRIMARY KEY,
    [DDENTIFICATIEAPPARTEMENTSRECHTSPLITSING] VARCHAR(255),
    [TYPESPLITSING_ENUM_ID] INT
);

CREATE TABLE [WIJK] (
    [WIJK_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIE] GEOMETRY,
    [IDENTIFICATIE] VARCHAR(255),
    [LIGT_IN_WOONPLAATS_ID] INT,
    [STATUS_ENUM_ID] INT,
    [VERSIE] INT,
    [WIJKCODE] VARCHAR(255),
    [WIJKNAAM] VARCHAR(255)
);

CREATE TABLE [OVERIGGEBOUWDOBJECT] (
    [ADRESSEERBAAROBJECT_ID] INT PRIMARY KEY,
    [BOUWJAAR] VARCHAR(255),
    [INDICATIEPLANOBJECT_ENUM_ID] INT,
    [OVERIGGEBOUWDOBJECTIDENTIFICATIE] VARCHAR(255)
);

CREATE TABLE [STATUSVOORTGANGBOUW_ENUM] (
    [STATUSVOORTGANGBOUW_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [STATUSVOORTGANGBOUW_ENUM] ([STATUSVOORTGANGBOUW_ENUM_ID], VALUE) VALUES
    (1, 'LEEG'),
    (2, 'NIEUWBOUWVERGUNNING_INGETROKKEN'),
    (3, 'NIEUWBOUWVERGUNNING_VERLEEND'),
    (4, 'NIEUWBOUW_GEREED'),
    (5, 'NIEUWBOUW_GESTART'),
    (6, 'ONBEKEND'),
    (7, 'SLOOPVERGUNNING_INGETROKKEN'),
    (8, 'SLOOPVERGUNNING_VERLEEND'),
    (9, 'SLOOP_GEREED'),
    (10, 'SLOOP_GESTART'),
    (11, 'VERBOUWVERGUNNING_INGETROKKEN'),
    (12, 'VERBOUWVERGUNNING_VERLEEND'),
    (13, 'VERBOUW_GEREED'),
    (14, 'VERBOUW_GESTART');

CREATE TABLE [TYPERINGOPENBARERUIMTE_ENUM] (
    [TYPERINGOPENBARERUIMTE_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [TYPERINGOPENBARERUIMTE_ENUM] ([TYPERINGOPENBARERUIMTE_ENUM_ID], VALUE) VALUES
    (1, 'ADMINISTRATIEF_GEBIED'),
    (2, 'FUNCTIONEEL_GEBIED'),
    (3, 'KUNSTWERK'),
    (4, 'LANDSCHAPPELIJK_GEBIED'),
    (5, 'LEEG'),
    (6, 'ONBEKEND'),
    (7, 'SPOORBAAN'),
    (8, 'TERREIN'),
    (9, 'WATER'),
    (10, 'WEG');

CREATE TABLE [TYPEADRESSEERBAAROBJECT_ENUM] (
    [TYPEADRESSEERBAAROBJECT_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [TYPEADRESSEERBAAROBJECT_ENUM] ([TYPEADRESSEERBAAROBJECT_ENUM_ID], VALUE) VALUES
    (1, 'KADBINNENLANDSADRES'),
    (2, 'LEEG'),
    (3, 'LIGPLAATS'),
    (4, 'ONBEKEND'),
    (5, 'STANDPLAATS'),
    (6, 'VERBLIJFSOBJECT');

CREATE TABLE [ENERGIELABEL_GEBOUWEN_ENUM] (
    [ENERGIELABEL_GEBOUWEN_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [ENERGIELABEL_GEBOUWEN_ENUM] ([ENERGIELABEL_GEBOUWEN_ENUM_ID], VALUE) VALUES
    (1, 'A'),
    (2, 'A_'),
    (3, 'A_'),
    (4, 'B'),
    (5, 'C'),
    (6, 'D'),
    (7, 'E'),
    (8, 'F'),
    (9, 'G'),
    (10, 'LEEG'),
    (11, 'ONBEKEND');

CREATE TABLE [NEN2767_CONDITIESCORE_ENUM] (
    [NEN2767_CONDITIESCORE_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [NEN2767_CONDITIESCORE_ENUM] ([NEN2767_CONDITIESCORE_ENUM_ID], VALUE) VALUES
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, 'LEEG'),
    (8, 'ONBEKEND');

CREATE TABLE [PAND] (
    [PAND_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [BRUTOINHOUDPAND] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] VARCHAR(255),
    [EINDGELDIGHEID] DATE,
    [GECONSTATEERD_ENUM_ID] INT,
    [GEOMETRIEBOVENAANZICHT] GEOMETRY,
    [GEOMETRIEMAAIVELD] GEOMETRY,
    [GEOMETRIEPUNT] GEOMETRY,
    [HEEFT_VASTGOEDOBJECT_ID] INT,
    [HOOGSTEBOUWLAAG] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [LAAGSTEBOUWLAAG] VARCHAR(255),
    [OORSPRONKELIJKBOUWJAAR] VARCHAR(255),
    [OPPERVLAKTE] VARCHAR(255),
    [RELATIEVEHOOGTELIGGING] VARCHAR(255),
    [STATUSVOORTGANGBOUW_ENUM_ID] INT,
    [STATUS_ENUM_ID] INT,
    [VERSIE] INT,
    [ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_ID] INT
);

CREATE TABLE [BOOLEAN_ENUM] (
    [BOOLEAN_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID], VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE [SOORTWOONOBJECT_ENUM] (
    [SOORTWOONOBJECT_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [SOORTWOONOBJECT_ENUM] ([SOORTWOONOBJECT_ENUM_ID], VALUE) VALUES
    (1, 'BIJZONDER_WOONGEBOUW'),
    (2, 'LEEG'),
    (3, 'ONBEKEND'),
    (4, 'OVERIG_WOONVERBLIJF'),
    (5, 'RECREATIEWONING'),
    (6, 'WONING'),
    (7, 'WOONEENHEID');

CREATE TABLE [MONUMENTTYPERING_ENUM] (
    [MONUMENTTYPERING_ENUM_ID] INT PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO [MONUMENTTYPERING_ENUM] ([MONUMENTTYPERING_ENUM_ID], VALUE) VALUES
    (1, 'BESCHERMD_STADSGEZICHT'),
    (2, 'DEELS_RIJKSMONUMENT'),
    (3, 'GEEN_MONUMENT'),
    (4, 'GEMEENTELIJK_MONUMENT'),
    (5, 'JA'),
    (6, 'LEEG'),
    (7, 'NEE'),
    (8, 'ONBEKEND'),
    (9, 'RIJKSMONUMENT');

ALTER TABLE [NADAANVULLINGBRP] ADD CONSTRAINT FK_NADAANVULLINGBRP_GEN_NUMMERAANDUIDING FOREIGN KEY ([NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- Generalization to NUMMERAANDUIDING

ALTER TABLE [VERBLIJFSOBJECT] ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [LIGPLAATS] ADD CONSTRAINT FK_LIGPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [STANDPLAATS] ADD CONSTRAINT FK_STANDPLAATS_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [NIETNATUURLIJKPERSOON] ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [OVERIGGEBOUWDOBJECT] ADD CONSTRAINT FK_OVERIGGEBOUWDOBJECT_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [NATUURLIJKPERSOON] ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to RECHTSPERSOON

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY ([RECHTSPERSOON_ID]) REFERENCES [NATUURLIJKPERSOON] ([RECHTSPERSOON_ID]);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE [OVERIGBENOEMDTERREIN] ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEN_ADRESSEERBAAROBJECT FOREIGN KEY ([ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- Generalization to ADRESSEERBAAROBJECT

ALTER TABLE [KP_VSTGDBJCT_KDSTRLNRRNDZK] ADD CONSTRAINT FK_KP_VSTGDBJCT_KDSTRLNRRNDZK_1 FOREIGN KEY ([VASTGOEDOBJECT_ID]) REFERENCES [VASTGOEDOBJECT] ([VASTGOEDOBJECT_ID]);
-- VASTGOEDOBJECT (many-to-many junction, Connector_ID: 548)

ALTER TABLE [KP_VSTGDBJCT_KDSTRLNRRNDZK] ADD CONSTRAINT FK_KP_VSTGDBJCT_KDSTRLNRRNDZK_2 FOREIGN KEY ([KADASTRALEONROERENDEZAAK_ID]) REFERENCES [KADASTRALEONROERENDEZAAK] ([KADASTRALEONROERENDEZAAK_ID]);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 548)

ALTER TABLE [KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ] ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_1 FOREIGN KEY ([IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID]) REFERENCES [KADASTRALEONROERENDEZAAK] ([KADASTRALEONROERENDEZAAK_ID]);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE [KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ] ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_2 FOREIGN KEY ([IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID]) REFERENCES [KADASTRALEONROERENDEZAAK] ([KADASTRALEONROERENDEZAAK_ID]);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 1933)

ALTER TABLE [KP_NTNTRLJKPRSN_NTRLJKPRSN] ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_1 FOREIGN KEY ([NIETNATUURLIJKPERSOON_ID]) REFERENCES [NIETNATUURLIJKPERSOON] ([RECHTSPERSOON_ID]);
-- NIETNATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1970)

ALTER TABLE [KP_NTNTRLJKPRSN_NTRLJKPRSN] ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_2 FOREIGN KEY ([NATUURLIJKPERSOON_ID]) REFERENCES [NATUURLIJKPERSOON] ([RECHTSPERSOON_ID]);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1970)

ALTER TABLE [KP_ZKLJKRCHT_TNMSTLLNG] ADD CONSTRAINT FK_KP_ZKLJKRCHT_TNMSTLLNG_1 FOREIGN KEY ([ZAKELIJKRECHT_ID]) REFERENCES [ZAKELIJKRECHT] ([ZAKELIJKRECHT_ID]);
-- ZAKELIJKRECHT (many-to-many junction, Connector_ID: 1979)

ALTER TABLE [KP_ZKLJKRCHT_TNMSTLLNG] ADD CONSTRAINT FK_KP_ZKLJKRCHT_TNMSTLLNG_2 FOREIGN KEY ([TENAAMSTELLING_ID]) REFERENCES [TENAAMSTELLING] ([TENAAMSTELLING_ID]);
-- TENAAMSTELLING (many-to-many junction, Connector_ID: 1979)

ALTER TABLE [KP_GMNT_IS_OVRGGN_IN] ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_1 FOREIGN KEY ([IS_OVERGEGAAN_IN_1_ID]) REFERENCES [GEMEENTE] ([GEMEENTE_ID]);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE [KP_GMNT_IS_OVRGGN_IN] ADD CONSTRAINT FK_KP_GMNT_IS_OVRGGN_IN_2 FOREIGN KEY ([IS_OVERGEGAAN_IN_2_ID]) REFERENCES [GEMEENTE] ([GEMEENTE_ID]);
-- GEMEENTE (many-to-many junction, Connector_ID: 2233)

ALTER TABLE [KP_VRBLJFSBJCT_PND] ADD CONSTRAINT FK_KP_VRBLJFSBJCT_PND_1 FOREIGN KEY ([VERBLIJFSOBJECT_ID]) REFERENCES [VERBLIJFSOBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- VERBLIJFSOBJECT (many-to-many junction, Connector_ID: 2305)

ALTER TABLE [KP_VRBLJFSBJCT_PND] ADD CONSTRAINT FK_KP_VRBLJFSBJCT_PND_2 FOREIGN KEY ([PAND_ID]) REFERENCES [PAND] ([PAND_ID]);
-- PAND (many-to-many junction, Connector_ID: 2305)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_HEEFT FOREIGN KEY ([HEEFT_VERHUURBAAR_EENHEID_ID]) REFERENCES [VERHUURBAAR_EENHEID] ([VERHUURBAAR_EENHEID_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 547)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_HEEFT_2 FOREIGN KEY ([HEEFT_VASTGOEDCONTRACTREGEL_ID]) REFERENCES [VASTGOEDCONTRACTREGEL] ([VASTGOEDCONTRACTREGEL_ID]);
-- HEEFT (1.. to 0..1, Connector_ID: 549)

ALTER TABLE [VERHUURBAAR_EENHEID] ADD CONSTRAINT FK_VERHUURBAAR_EENHEID_BETREFT FOREIGN KEY ([BETREFT_VASTGOEDCONTRACTREGEL_ID]) REFERENCES [VASTGOEDCONTRACTREGEL] ([VASTGOEDCONTRACTREGEL_ID]);
-- BETREFT (0..1 to 1, Connector_ID: 550)

ALTER TABLE [VASTGOEDCONTRACTREGEL] ADD CONSTRAINT FK_VASTGOEDCONTRACTREGEL_HEEFT FOREIGN KEY ([HEEFT_VASTGOED_CONTRACT_ID]) REFERENCES [VASTGOED_CONTRACT] ([VASTGOED_CONTRACT_ID]);
-- HEEFT (1..* to 1, Connector_ID: 551)

ALTER TABLE [VASTGOED_CONTRACT] ADD CONSTRAINT FK_VASTGOED_CONTRACT_HEEFT FOREIGN KEY ([HEEFT_RECHTSPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- HEEFT (0..* to 1, Connector_ID: 552)

ALTER TABLE [LOCATIEONROERENDEZAAK] ADD CONSTRAINT FK_LOCATIEONROERENDEZAAK_HEEFT_ADRES FOREIGN KEY ([HEEFT_ADRES_KADASTRALEONROERENDEZAAK_ID]) REFERENCES [KADASTRALEONROERENDEZAAK] ([KADASTRALEONROERENDEZAAK_ID]);
-- HEEFT_ADRES (0..* to 1, Connector_ID: 563)

ALTER TABLE [LOCATIEONROERENDEZAAK] ADD CONSTRAINT FK_LOCATIEONROERENDEZAAK_HEEFT_ADRESSEERBAAR_OBJECT FOREIGN KEY ([HEEFT_ADRESSEERBAAR_OBJECT_ADRESSEERBAAROBJECT_ID]) REFERENCES [ADRESSEERBAAROBJECT] ([ADRESSEERBAAROBJECT_ID]);
-- HEEFT_ADRESSEERBAAR_OBJECT (0..* to 1, Connector_ID: 564)

ALTER TABLE [KPONSTAANUIT] ADD CONSTRAINT FK_KPONSTAANUIT_IS_ONTSTAAN_UIT FOREIGN KEY ([IS_ONTSTAAN_UIT_ZAKELIJKRECHT_ID]) REFERENCES [ZAKELIJKRECHT] ([ZAKELIJKRECHT_ID]);
-- IS_ONTSTAAN_UIT (0..* to 1, Connector_ID: 567)

ALTER TABLE [KPONSTAANUIT] ADD CONSTRAINT FK_KPONSTAANUIT_APPARTEMENTSRECHTSPLITSING FOREIGN KEY ([APPARTEMENTSRECHTSPLITSING_ID]) REFERENCES [APPARTEMENTSRECHTSPLITSING] ([APPARTEMENTSRECHTSPLITSING_ID]);
-- unnamed (0..* to 1, Connector_ID: 568)

ALTER TABLE [KPBETROKKENBIJ] ADD CONSTRAINT FK_KPBETROKKENBIJ_IS_BETROKKEN_BIJ FOREIGN KEY ([IS_BETROKKEN_BIJ_ZAKELIJKRECHT_ID]) REFERENCES [ZAKELIJKRECHT] ([ZAKELIJKRECHT_ID]);
-- IS_BETROKKEN_BIJ (0..* to 1, Connector_ID: 569)

ALTER TABLE [KPBETROKKENBIJ] ADD CONSTRAINT FK_KPBETROKKENBIJ_APPARTEMENTSRECHTSPLITSING FOREIGN KEY ([APPARTEMENTSRECHTSPLITSING_ID]) REFERENCES [APPARTEMENTSRECHTSPLITSING] ([APPARTEMENTSRECHTSPLITSING_ID]);
-- unnamed (0..* to 1, Connector_ID: 570)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY ([OUDER_1_INGESCHREVENPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- OUDER_1 (1 to 1, Connector_ID: 1871)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY ([OUDER_2_INGESCHREVENPERSOON_ID]) REFERENCES [RECHTSPERSOON] ([RECHTSPERSOON_ID]);
-- OUDER_2 (1 to 1, Connector_ID: 1873)

ALTER TABLE [KADASTRALEONROERENDEZAAK] ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GERELATEERD FOREIGN KEY ([GERELATEERD_KADASTRALEONROERENDEZAAK_ID]) REFERENCES [KADASTRALEONROERENDEZAAK] ([KADASTRALEONROERENDEZAAK_ID]);
-- GERELATEERD (1 to 0..*, Connector_ID: 1938)

ALTER TABLE [ZAKELIJKRECHT] ADD CONSTRAINT FK_ZAKELIJKRECHT_IS_BELAST_MET FOREIGN KEY ([IS_BELAST_MET_ZAKELIJKRECHT_ID]) REFERENCES [ZAKELIJKRECHT] ([ZAKELIJKRECHT_ID]);
-- IS_BELAST_MET (0..1 to 0..*, Connector_ID: 1944)

ALTER TABLE [ZAKELIJKRECHT] ADD CONSTRAINT FK_ZAKELIJKRECHT_RUST_OP FOREIGN KEY ([RUST_OP_KADASTRALEONROERENDEZAAK_ID]) REFERENCES [KADASTRALEONROERENDEZAAK] ([KADASTRALEONROERENDEZAAK_ID]);
-- RUST_OP (1..* to 0..1, Connector_ID: 1947)

ALTER TABLE [RECHTSPERSOON] ADD CONSTRAINT FK_RECHTSPERSOON_HEEFT FOREIGN KEY ([HEEFT_TENAAMSTELLING_ID]) REFERENCES [TENAAMSTELLING] ([TENAAMSTELLING_ID]);
-- HEEFT (1 to 0..*, Connector_ID: 1980)

ALTER TABLE [TENAAMSTELLING] ADD CONSTRAINT FK_TENAAMSTELLING_HEEFT_BETREKKING_OP FOREIGN KEY ([HEEFT_BETREKKING_OP_ZAKELIJKRECHT_ID]) REFERENCES [ZAKELIJKRECHT] ([ZAKELIJKRECHT_ID]);
-- HEEFT_BETREKKING_OP (0..* to 1, Connector_ID: 1982)

ALTER TABLE [VERBLIJFSOBJECT] ADD CONSTRAINT FK_VERBLIJFSOBJECT_HEEFT FOREIGN KEY ([HEEFT_VASTGOEDOBJECT_ID]) REFERENCES [VASTGOEDOBJECT] ([VASTGOEDOBJECT_ID]);
-- HEEFT (1 to 1, Connector_ID: 2261)

ALTER TABLE [OPENBARERUIMTE] ADD CONSTRAINT FK_OPENBARERUIMTE_LIGT_IN FOREIGN KEY ([LIGT_IN_BUURT_ID]) REFERENCES [BUURT] ([BUURT_ID]);
-- LIGT_IN (1 to 1..*, Connector_ID: 2264)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY ([HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 2268)

ALTER TABLE [NUMMERAANDUIDING] ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_IN FOREIGN KEY ([LIGT_IN_BUURT_ID]) REFERENCES [BUURT] ([BUURT_ID]);
-- LIGT_IN (1 to 1, Connector_ID: 2272)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_HEEFT_ALS_ADRES FOREIGN KEY ([HEEFT_ALS_ADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_ADRES (0..* to 0..1, Connector_ID: 2273)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY ([HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 2274)

ALTER TABLE [NUMMERAANDUIDING] ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_AAN FOREIGN KEY ([LIGT_AAN_OPENBARERUIMTE_ID]) REFERENCES [OPENBARERUIMTE] ([OPENBARERUIMTE_ID]);
-- LIGT_AAN (0..* to 1, Connector_ID: 2281)

ALTER TABLE [NUMMERAANDUIDING] ADD CONSTRAINT FK_NUMMERAANDUIDING_LIGT_IN_2 FOREIGN KEY ([LIGT_IN_WOONPLAATS_ID]) REFERENCES [WOONPLAATS] ([WOONPLAATS_ID]);
-- LIGT_IN (0..* to 0..1, Connector_ID: 2283)

ALTER TABLE [OPENBARERUIMTE] ADD CONSTRAINT FK_OPENBARERUIMTE_LIGT_IN_2 FOREIGN KEY ([LIGT_IN_WOONPLAATS_ID]) REFERENCES [WOONPLAATS] ([WOONPLAATS_ID]);
-- LIGT_IN (1..* to 1, Connector_ID: 2288)

ALTER TABLE [WOONPLAATS] ADD CONSTRAINT FK_WOONPLAATS_LIGT_IN FOREIGN KEY ([LIGT_IN_GEMEENTE_ID]) REFERENCES [GEMEENTE] ([GEMEENTE_ID]);
-- LIGT_IN (1..* to 1.., Connector_ID: 2290)

ALTER TABLE [WIJK] ADD CONSTRAINT FK_WIJK_LIGT_IN FOREIGN KEY ([LIGT_IN_WOONPLAATS_ID]) REFERENCES [WOONPLAATS] ([WOONPLAATS_ID]);
-- LIGT_IN (1..* to 1, Connector_ID: 2294)

ALTER TABLE [BUURT] ADD CONSTRAINT FK_BUURT_LIGT_IN FOREIGN KEY ([LIGT_IN_WIJK_ID]) REFERENCES [WIJK] ([WIJK_ID]);
-- LIGT_IN (1..* to 1, Connector_ID: 2297)

ALTER TABLE [PAND] ADD CONSTRAINT FK_PAND_ZONDER_VERBLIJFSOBJECT_LIGT_IN FOREIGN KEY ([ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_ID]) REFERENCES [BUURT] ([BUURT_ID]);
-- ZONDER_VERBLIJFSOBJECT_LIGT_IN (0..* to 0..1, Connector_ID: 2300)

ALTER TABLE [PAND] ADD CONSTRAINT FK_PAND_HEEFT FOREIGN KEY ([HEEFT_VASTGOEDOBJECT_ID]) REFERENCES [VASTGOEDOBJECT] ([VASTGOEDOBJECT_ID]);
-- HEEFT (1 to 1, Connector_ID: 2301)

ALTER TABLE [LOCATIEONROERENDEZAAK] ADD CONSTRAINT FK_LOCATIEONROERENDEZAAK_ADRESTYPE_ENUM_ID FOREIGN KEY ([ADRESTYPE_ENUM_ID]) REFERENCES [TYPEADRESSEERBAAROBJECT_ENUM] ([TYPEADRESSEERBAAROBJECT_ENUM_ID]);
-- ADRESTYPE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_AFGESPROKENCONDITIESCORE_ENUM_ID FOREIGN KEY ([AFGESPROKENCONDITIESCORE_ENUM_ID]) REFERENCES [NEN2767_CONDITIESCORE_ENUM] ([NEN2767_CONDITIESCORE_ENUM_ID]);
-- AFGESPROKENCONDITIESCORE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_MONUMENT_ENUM_ID FOREIGN KEY ([MONUMENT_ENUM_ID]) REFERENCES [MONUMENTTYPERING_ENUM] ([MONUMENTTYPERING_ENUM_ID]);
-- MONUMENT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_AFGEKOCHTEERFPACHT_ENUM_ID FOREIGN KEY ([AFGEKOCHTEERFPACHT_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- AFGEKOCHTEERFPACHT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_GEARCHIVEERD_ENUM_ID FOREIGN KEY ([GEARCHIVEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GEARCHIVEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_ASBESTRAPPORTAGEAANWEZIG_ENUM_ID FOREIGN KEY ([ASBESTRAPPORTAGEAANWEZIG_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- ASBESTRAPPORTAGEAANWEZIG_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_CONDITIESCORE_ENUM_ID FOREIGN KEY ([CONDITIESCORE_ENUM_ID]) REFERENCES [NEN2767_CONDITIESCORE_ENUM] ([NEN2767_CONDITIESCORE_ENUM_ID]);
-- CONDITIESCORE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VASTGOEDOBJECT] ADD CONSTRAINT FK_VASTGOEDOBJECT_ENERGIELABEL_ENUM_ID FOREIGN KEY ([ENERGIELABEL_ENUM_ID]) REFERENCES [ENERGIELABEL_GEBOUWEN_ENUM] ([ENERGIELABEL_GEBOUWEN_ENUM_ID]);
-- ENERGIELABEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [PAND] ADD CONSTRAINT FK_PAND_STATUS_ENUM_ID FOREIGN KEY ([STATUS_ENUM_ID]) REFERENCES [STATUSPAND_ENUM] ([STATUSPAND_ENUM_ID]);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [PAND] ADD CONSTRAINT FK_PAND_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [PAND] ADD CONSTRAINT FK_PAND_STATUSVOORTGANGBOUW_ENUM_ID FOREIGN KEY ([STATUSVOORTGANGBOUW_ENUM_ID]) REFERENCES [STATUSVOORTGANGBOUW_ENUM] ([STATUSVOORTGANGBOUW_ENUM_ID]);
-- STATUSVOORTGANGBOUW_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [WIJK] ADD CONSTRAINT FK_WIJK_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [WIJK] ADD CONSTRAINT FK_WIJK_STATUS_ENUM_ID FOREIGN KEY ([STATUS_ENUM_ID]) REFERENCES [STATUSOPENBARERUIMTE_ENUM] ([STATUSOPENBARERUIMTE_ENUM_ID]);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [WOONPLAATS] ADD CONSTRAINT FK_WOONPLAATS_STATUS_ENUM_ID FOREIGN KEY ([STATUS_ENUM_ID]) REFERENCES [STATUSWOONPLAATS_ENUM] ([STATUSWOONPLAATS_ENUM_ID]);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [WOONPLAATS] ADD CONSTRAINT FK_WOONPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NUMMERAANDUIDING] ADD CONSTRAINT FK_NUMMERAANDUIDING_TYPEADRESSEERBAAROBJECT_ENUM_ID FOREIGN KEY ([TYPEADRESSEERBAAROBJECT_ENUM_ID]) REFERENCES [TYPEADRESSEERBAAROBJECT_ENUM] ([TYPEADRESSEERBAAROBJECT_ENUM_ID]);
-- TYPEADRESSEERBAAROBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NUMMERAANDUIDING] ADD CONSTRAINT FK_NUMMERAANDUIDING_STATUS_ENUM_ID FOREIGN KEY ([STATUS_ENUM_ID]) REFERENCES [STATUSNUMMERAANDUIDING_ENUM] ([STATUSNUMMERAANDUIDING_ENUM_ID]);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NUMMERAANDUIDING] ADD CONSTRAINT FK_NUMMERAANDUIDING_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [BUURT] ADD CONSTRAINT FK_BUURT_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [BUURT] ADD CONSTRAINT FK_BUURT_STATUS_ENUM_ID FOREIGN KEY ([STATUS_ENUM_ID]) REFERENCES [STATUSOPENBARERUIMTE_ENUM] ([STATUSOPENBARERUIMTE_ENUM_ID]);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERBLIJFSOBJECT] ADD CONSTRAINT FK_VERBLIJFSOBJECT_ONTSLUITINGVERDIEPING_ENUM_ID FOREIGN KEY ([ONTSLUITINGVERDIEPING_ENUM_ID]) REFERENCES [ONTSLUITINGSWIJZEVERDIEPING_ENUM] ([ONTSLUITINGSWIJZEVERDIEPING_ENUM_ID]);
-- ONTSLUITINGVERDIEPING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERBLIJFSOBJECT] ADD CONSTRAINT FK_VERBLIJFSOBJECT_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERBLIJFSOBJECT] ADD CONSTRAINT FK_VERBLIJFSOBJECT_STATUS_ENUM_ID FOREIGN KEY ([STATUS_ENUM_ID]) REFERENCES [STATUSVERBLIJFSOBJECT_ENUM] ([STATUSVERBLIJFSOBJECT_ENUM_ID]);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERBLIJFSOBJECT] ADD CONSTRAINT FK_VERBLIJFSOBJECT_GEBRUIKSDOEL_ENUM_ID FOREIGN KEY ([GEBRUIKSDOEL_ENUM_ID]) REFERENCES [GEBRUIKSDOEL_ENUM] ([GEBRUIKSDOEL_ENUM_ID]);
-- GEBRUIKSDOEL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [VERBLIJFSOBJECT] ADD CONSTRAINT FK_VERBLIJFSOBJECT_SOORTWOONOBJECT_ENUM_ID FOREIGN KEY ([SOORTWOONOBJECT_ENUM_ID]) REFERENCES [SOORTWOONOBJECT_ENUM] ([SOORTWOONOBJECT_ENUM_ID]);
-- SOORTWOONOBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [LIGPLAATS] ADD CONSTRAINT FK_LIGPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [STANDPLAATS] ADD CONSTRAINT FK_STANDPLAATS_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [ADRESSEERBAAROBJECT] ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_TYPEADRESSEERBAAROBJECT_ENUM_ID FOREIGN KEY ([TYPEADRESSEERBAAROBJECT_ENUM_ID]) REFERENCES [TYPEADRESSEERBAAROBJECT_ENUM] ([TYPEADRESSEERBAAROBJECT_ENUM_ID]);
-- TYPEADRESSEERBAAROBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [OPENBARERUIMTE] ADD CONSTRAINT FK_OPENBARERUIMTE_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [OPENBARERUIMTE] ADD CONSTRAINT FK_OPENBARERUIMTE_TYPEOPENBARERUIMTE_ENUM_ID FOREIGN KEY ([TYPEOPENBARERUIMTE_ENUM_ID]) REFERENCES [TYPERINGOPENBARERUIMTE_ENUM] ([TYPERINGOPENBARERUIMTE_ENUM_ID]);
-- TYPEOPENBARERUIMTE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [OPENBARERUIMTE] ADD CONSTRAINT FK_OPENBARERUIMTE_STATUS_ENUM_ID FOREIGN KEY ([STATUS_ENUM_ID]) REFERENCES [STATUSOPENBARERUIMTE_ENUM] ([STATUSOPENBARERUIMTE_ENUM_ID]);
-- STATUS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [GEMEENTE] ADD CONSTRAINT FK_GEMEENTE_GECONSTATEERD_ENUM_ID FOREIGN KEY ([GECONSTATEERD_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- GECONSTATEERD_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [TENAAMSTELLING] ADD CONSTRAINT FK_TENAAMSTELLING_VERKREGENNAMENSSAMENWERKINGSVERBAND_ENUM_ID FOREIGN KEY ([VERKREGENNAMENSSAMENWERKINGSVERBAND_ENUM_ID]) REFERENCES [SOORTRECHTSVORM_ENUM] ([SOORTRECHTSVORM_ENUM_ID]);
-- VERKREGENNAMENSSAMENWERKINGSVERBAND_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NIETNATUURLIJKPERSOON] ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_INOPRICHTING_ENUM_ID FOREIGN KEY ([INOPRICHTING_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INOPRICHTING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NIETNATUURLIJKPERSOON] ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_INGESCHREVEN_ENUM_ID FOREIGN KEY ([INGESCHREVEN_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INGESCHREVEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NIETNATUURLIJKPERSOON] ADD CONSTRAINT FK_NIETNATUURLIJKPERSOON_RECHTSVORM_ENUM_ID FOREIGN KEY ([RECHTSVORM_ENUM_ID]) REFERENCES [SOORTRECHTSVORM_ENUM] ([SOORTRECHTSVORM_ENUM_ID]);
-- RECHTSVORM_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [OVERIGGEBOUWDOBJECT] ADD CONSTRAINT FK_OVERIGGEBOUWDOBJECT_INDICATIEPLANOBJECT_ENUM_ID FOREIGN KEY ([INDICATIEPLANOBJECT_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIEPLANOBJECT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NATUURLIJKPERSOON] ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEOVERLEDEN_ENUM_ID FOREIGN KEY ([INDICATIEOVERLEDEN_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIEOVERLEDEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NATUURLIJKPERSOON] ADD CONSTRAINT FK_NATUURLIJKPERSOON_ADELLIJKETITELOFPREDIKAAT_ENUM_ID FOREIGN KEY ([ADELLIJKETITELOFPREDIKAAT_ENUM_ID]) REFERENCES [ADELIJKETITEL_ENUM] ([ADELIJKETITEL_ENUM_ID]);
-- ADELLIJKETITELOFPREDIKAAT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [NATUURLIJKPERSOON] ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID FOREIGN KEY ([INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_INDICATIEGEHEIM_ENUM_ID FOREIGN KEY ([INDICATIEGEHEIM_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INDICATIEGEHEIM_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEZINSRELATIE_ENUM_ID FOREIGN KEY ([GEZINSRELATIE_ENUM_ID]) REFERENCES [GEZINSRELATIE_ENUM] ([GEZINSRELATIE_ENUM_ID]);
-- GEZINSRELATIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_SIGNALERINGREISDOCUMENT_ENUM_ID FOREIGN KEY ([SIGNALERINGREISDOCUMENT_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- SIGNALERINGREISDOCUMENT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [INGESCHREVENPERSOON] ADD CONSTRAINT FK_INGESCHREVENPERSOON_INGEZETENE_ENUM_ID FOREIGN KEY ([INGEZETENE_ENUM_ID]) REFERENCES [BOOLEAN_ENUM] ([BOOLEAN_ENUM_ID]);
-- INGEZETENE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [APPARTEMENTSRECHTSPLITSING] ADD CONSTRAINT FK_APPARTEMENTSRECHTSPLITSING_TYPESPLITSING_ENUM_ID FOREIGN KEY ([TYPESPLITSING_ENUM_ID]) REFERENCES [TYPERINGAPPARTEMENTSRECHTSPLITSING_ENUM] ([TYPERINGAPPARTEMENTSRECHTSPLITSING_ENUM_ID]);
-- TYPESPLITSING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE [OVERIGBENOEMDTERREIN] ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEBRUIKSDOELOVERIGBENOEMDTERREIN_ENUM_ID FOREIGN KEY ([GEBRUIKSDOELOVERIGBENOEMDTERREIN_ENUM_ID]) REFERENCES [GEBRUIKSDOEL_ENUM] ([GEBRUIKSDOEL_ENUM_ID]);
-- GEBRUIKSDOELOVERIGBENOEMDTERREIN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

