CREATE TABLE [RENTEVORDERING] (
    [VORDERING_ID] INT PRIMARY KEY,
    [RENTEVORDERING_IS_GERELATEERD_AAN_VORDERING_VORDERING_ID] INT
);

CREATE TABLE [VERREKENING] (
    [VORDERING_ID] INT PRIMARY KEY
);

CREATE TABLE [KREDIETHYPOTHEEKVORDERING] (
    [VORDERING_ID] INT PRIMARY KEY
);

CREATE TABLE [AFLOSSINGSAFSPRAAK] (
    [AFLOSSINGSAFSPRAAK_ID] INT PRIMARY KEY,
    [AFLOSSINGSAFSPRAAK_BETREFT_VORDERING_VORDERING_ID] INT,
    [AFLOSSINGSAFSPRAAK_BEVAT_AFLOSSING_AFLOSSING_ID] INT,
    [BEDRAG] DECIMAL(10,2),
    [EINDDATUM] DATE,
    [INDICATIE_INCLUSIEF_VAKANTIEGELD] VARCHAR(255),
    [PERIODIEK] VARCHAR(255),
    [STARTDATUM] DATE
);

CREATE TABLE [LEENBIJSTANDVORDERING] (
    [VORDERING_ID] INT PRIMARY KEY
);

CREATE TABLE [LOONBESLAGAFSPRAAK] (
    [AFLOSSINGSAFSPRAAK_ID] INT PRIMARY KEY
);

CREATE TABLE [INVORDERINGSBASIS] (
    [INVORDERINGSBASIS_ID] INT PRIMARY KEY,
    [AFLOSSINGSCAPACITEIT] VARCHAR(255),
    [BESLAGVRIJE_VOET] VARCHAR(255),
    [INVORDERINGSMOGELIJKHEID] VARCHAR(255),
    [TYPE_INVORDERINGSMOGELIJKHEID] VARCHAR(255),
    [VASTSTELDATUM_AFLOSSINGSCAPACITEIT] DATE,
    [VASTSTELDATUM_BESLAGVRIJE_VOET] DATE,
    [VASTSTELDATUM_INVORDERINGSMOGELIJKHEID] DATE
);

CREATE TABLE [CONSERVATOIR_BESLAG] (
    [CONSERVATOIR_BESLAG_ID] INT PRIMARY KEY,
    [AANVRAAGDATUM] DATE,
    [TOESTEMMINGSDATUM] DATE
);

CREATE TABLE [DEBITEUR] (
    [DEBITEUR_ID] INT PRIMARY KEY,
    [DEBITEUR_HEEFT_AANGEGAAN_LEENBIJSTAND_LEENBIJSTAND_ID] INT,
    [DEBITEUR_HEEFT_AFGESLOTEN_KREDIETHYPOTHEEK_KREDIETHYPOTHEEK_ID] INT,
    [DEBITEUR_HEEFT_INVORDERINGSBASIS_INVORDERINGSBASIS_ID] INT,
    [DEBITEUR_HEEFT_VORDERING_VORDERING_ID] INT,
    [EIGEN_KENMERK] VARCHAR(255),
    [HEEFT_AFLOSSINGSPLAN_ID] INT,
    [OPVOERDATUM] DATE,
    [SOORT_DEBITEUR] VARCHAR(255)
);

CREATE TABLE [VERMINDERING_TERUGVORDERING] (
    [VERMINDERING_TERUGVORDERING_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [BOEKINGSDATUM] DATE,
    [MOTIVATIE_VERMINDERING] VARCHAR(255),
    [VASTSTELDATUM] DATE,
    [VERMINDERINGTYPE] VARCHAR(255)
);

CREATE TABLE [AFLOSSINGSPLAN] (
    [AFLOSSINGSPLAN_ID] INT PRIMARY KEY,
    [AFLOSSINGSKENMERK] VARCHAR(255),
    [AFLOSSINGSPLAN_ONDERGAAT_UITSTEL_AFLOSSING_UITSTEL_AFLOSSING_ID] INT,
    [BEVAT_AFLOSSINGSAFSPRAAK_ID] INT,
    [EINDDATUM] DATE,
    [IS_GEBASEERD_OP_INVORDERINGSBASIS_ID] INT,
    [STARTDATUM] DATE
);

CREATE TABLE [KREDIETHYPOTHEEK] (
    [KREDIETHYPOTHEEK_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [IS_ORIGINE_VAN_KREDIETHYPOTHEEKVORDERING_ID] INT,
    [VESTIGINGSDATUM] DATE
);

CREATE TABLE [BETAALCOMPONENT] (
    [BETAALCOMPONENT_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [BOEKINGSDATUM] DATE
);

CREATE TABLE [LEENBIJSTAND] (
    [LEENBIJSTAND_ID] INT PRIMARY KEY,
    [AFLOSSINGSKENMERK] VARCHAR(255),
    [BEDRAG] DECIMAL(10,2),
    [BOEKINGSDATUM] DATE,
    [IS_ORIGINE_VAN_LEENBIJSTANDVORDERING_ID] INT,
    [ONTVANGSTDATUM] DATE
);

CREATE TABLE [UITSTEL_AFLOSSING] (
    [UITSTEL_AFLOSSING_ID] INT PRIMARY KEY,
    [AANMAAKDATUM] DATE,
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE,
    [REDEN_UITSTEL] VARCHAR(255)
);

CREATE TABLE [INCASSOKOSTENVORDERING] (
    [VORDERING_ID] INT PRIMARY KEY,
    [INCASSOKOSTENVORDERING_IS_GERELATEERD_AAN_VORDERING_VORDERING_ID] INT
);

CREATE TABLE [RESTITUTIE] (
    [RESTITUTIE_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [BETAALDATUM] DATE,
    [BOEKINGSDATUM] DATE
);

CREATE TABLE [INTERVENTIEVERZOEK] (
    [INTERVENTIEVERZOEK_ID] INT PRIMARY KEY,
    [INITIEERT_INTERVENTIE_ID] INT,
    [VERZOEKDATUM] DATE
);

CREATE TABLE [INTERVENTIE] (
    [INTERVENTIE_ID] INT PRIMARY KEY,
    [BESLISDATUM] DATE,
    [INGANGSDATUM] DATE,
    [INTERVENTIETYPE] VARCHAR(255)
);

CREATE TABLE [VERWIJTBARE_VORDERING] (
    [VORDERING_ID] INT PRIMARY KEY
);

CREATE TABLE [RECHTMAAND] (
    [RECHTMAAND_ID] INT PRIMARY KEY,
    [BOEKJAAR] VARCHAR(255),
    [JAAR] VARCHAR(255),
    [MAAND] VARCHAR(255),
    [RECHTMAAND_BEVAT_BETAALCOMPONENT_BETAALCOMPONENT_ID] INT
);

CREATE TABLE [BOETEVORDERING] (
    [VORDERING_ID] INT PRIMARY KEY,
    [IS_GERELATEERD_AAN_VERWIJTBARE_VORDERING_ID] INT
);

CREATE TABLE [CORRECTIE] (
    [CORRECTIE_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [BOEKINGSDATUM] DATE,
    [REDEN] VARCHAR(255)
);

CREATE TABLE [VORDERING] (
    [VORDERING_ID] INT PRIMARY KEY,
    [CATEGORIE] VARCHAR(255),
    [FISCAAL] VARCHAR(255),
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE,
    [PRIOTYPE] VARCHAR(255),
    [REGELING] VARCHAR(255),
    [STUITINGSVOORTGANGSINDICATOR] VARCHAR(255),
    [SUBCATEGORIE] VARCHAR(255),
    [TITEL] VARCHAR(255),
    [VASTSTELDATUM_TERUGVORDERING] DATE,
    [VERJARINGSDATUM] DATE,
    [VERWERKINGSSTATUS] VARCHAR(255),
    [VORDERING_BEVAT_AFLOSSING_AFLOSSING_ID] INT,
    [VORDERING_BEVAT_AFSCHRIJVING_AFSCHRIJVING_ID] INT,
    [VORDERING_BEVAT_CORRECTIE_CORRECTIE_ID] INT,
    [VORDERING_BEVAT_KWIJTSCHELDING_KWIJTSCHELDING_ID] INT,
    [VORDERING_BEVAT_RESTITUTIE_RESTITUTIE_ID] INT,
    [VORDERING_BEVAT_VERMINDERING_TERUGVORDERING_VERMINDERING_TERUGVORDERING_ID] INT,
    [VORDERING_BEVAT_VORDERINGSCOMPONENT_VORDERINGSCOMPONENT_ID] INT,
    [VORDERING_IS_GERELATEERD_AAN_CONSERVATOIR_BESLAG_CONSERVATOIR_BESLAG_ID] INT
);

CREATE TABLE [AFLOSSING] (
    [AFLOSSING_ID] INT PRIMARY KEY,
    [AFLOSSINGSKENMERK] VARCHAR(255),
    [BEDRAG] DECIMAL(10,2),
    [BOEKINGSDATUM] DATE,
    [ONTVANGSTDATUM] DATE
);

CREATE TABLE [VORDERINGSCOMPONENT] (
    [VORDERINGSCOMPONENT_ID] INT PRIMARY KEY,
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE,
    [PRIOTYPE] DATE,
    [VORDERINGSCOMPONENT_BEVAT_RECHTMAAND_RECHTMAAND_ID] INT
);

CREATE TABLE [KP_INTRVNTVRZK_AFLSSNGSFSPRK] (
    [KP_INTRVNTVRZK_AFLSSNGSFSPRK_ID] INT PRIMARY KEY,
    [INTERVENTIEVERZOEK_ID] INT,
    [AFLOSSINGSAFSPRAAK_ID] INT
);

CREATE TABLE [TERUGVORDERINGSVERZOEK] (
    [TERUGVORDERINGSVERZOEK_ID] INT PRIMARY KEY,
    [AANMAAKDATUM] DATE,
    [BEHANDELSTATUS_VERZOEK] VARCHAR(255),
    [CATEGORIE] VARCHAR(255),
    [FISCAAL] VARCHAR(255),
    [LEIDT_TOT_VORDERING_ID] INT,
    [PERIODE_EINDDATUM] DATE,
    [PERIODE_STARTDATUM] DATE,
    [PRIOTYPE] DATE,
    [REGELING] VARCHAR(255),
    [SUBCATEGORIE] VARCHAR(255),
    [TERUGVORDERINGSVERZOEK_BEVAT_RECHTMAAND_RECHTMAAND_ID] INT
);

CREATE TABLE [KWIJTSCHELDING] (
    [KWIJTSCHELDING_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [BOEKINGSDATUM] DATE,
    [REDEN] VARCHAR(255)
);

CREATE TABLE [AFSCHRIJVING] (
    [AFSCHRIJVING_ID] INT PRIMARY KEY,
    [AANMAAKDATUM] DATE,
    [REDEN_AFSCHRIJVING] VARCHAR(255)
);

ALTER TABLE [BOETEVORDERING] ADD CONSTRAINT FK_BOETEVORDERING_GEN_VORDERING FOREIGN KEY ([VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- Generalization to VORDERING

ALTER TABLE [INCASSOKOSTENVORDERING] ADD CONSTRAINT FK_INCASSOKOSTENVORDERING_GEN_VORDERING FOREIGN KEY ([VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- Generalization to VORDERING

ALTER TABLE [KREDIETHYPOTHEEKVORDERING] ADD CONSTRAINT FK_KREDIETHYPOTHEEKVORDERING_GEN_VORDERING FOREIGN KEY ([VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- Generalization to VORDERING

ALTER TABLE [LEENBIJSTANDVORDERING] ADD CONSTRAINT FK_LEENBIJSTANDVORDERING_GEN_VORDERING FOREIGN KEY ([VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- Generalization to VORDERING

ALTER TABLE [LOONBESLAGAFSPRAAK] ADD CONSTRAINT FK_LOONBESLAGAFSPRAAK_GEN_AFLOSSINGSAFSPRAAK FOREIGN KEY ([AFLOSSINGSAFSPRAAK_ID]) REFERENCES [AFLOSSINGSAFSPRAAK] ([AFLOSSINGSAFSPRAAK_ID]);
-- Generalization to AFLOSSINGSAFSPRAAK

ALTER TABLE [RENTEVORDERING] ADD CONSTRAINT FK_RENTEVORDERING_GEN_VORDERING FOREIGN KEY ([VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- Generalization to VORDERING

ALTER TABLE [VERREKENING] ADD CONSTRAINT FK_VERREKENING_GEN_VORDERING FOREIGN KEY ([VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- Generalization to VORDERING

ALTER TABLE [VERWIJTBARE_VORDERING] ADD CONSTRAINT FK_VERWIJTBARE_VORDERING_GEN_VORDERING FOREIGN KEY ([VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- Generalization to VORDERING

ALTER TABLE [KP_INTRVNTVRZK_AFLSSNGSFSPRK] ADD CONSTRAINT FK_KP_INTRVNTVRZK_AFLSSNGSFSPRK_1 FOREIGN KEY ([INTERVENTIEVERZOEK_ID]) REFERENCES [INTERVENTIEVERZOEK] ([INTERVENTIEVERZOEK_ID]);
-- INTERVENTIEVERZOEK (many-to-many junction, Connector_ID: 1667)

ALTER TABLE [KP_INTRVNTVRZK_AFLSSNGSFSPRK] ADD CONSTRAINT FK_KP_INTRVNTVRZK_AFLSSNGSFSPRK_2 FOREIGN KEY ([AFLOSSINGSAFSPRAAK_ID]) REFERENCES [AFLOSSINGSAFSPRAAK] ([AFLOSSINGSAFSPRAAK_ID]);
-- AFLOSSINGSAFSPRAAK (many-to-many junction, Connector_ID: 1667)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_VORDERING_BEVAT_VORDERINGSCOMPONENT FOREIGN KEY ([VORDERING_BEVAT_VORDERINGSCOMPONENT_VORDERINGSCOMPONENT_ID]) REFERENCES [VORDERINGSCOMPONENT] ([VORDERINGSCOMPONENT_ID]);
-- VORDERING_BEVAT_VORDERINGSCOMPONENT (0..* to 0..1, Connector_ID: 1632)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_VORDERING_BEVAT_VERMINDERING_TERUGVORDERING FOREIGN KEY ([VORDERING_BEVAT_VERMINDERING_TERUGVORDERING_VERMINDERING_TERUGVORDERING_ID]) REFERENCES [VERMINDERING_TERUGVORDERING] ([VERMINDERING_TERUGVORDERING_ID]);
-- VORDERING_BEVAT_VERMINDERING_TERUGVORDERING (0..* to 1..1, Connector_ID: 1635)

ALTER TABLE [TERUGVORDERINGSVERZOEK] ADD CONSTRAINT FK_TERUGVORDERINGSVERZOEK_LEIDT_TOT FOREIGN KEY ([LEIDT_TOT_VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- LEIDT_TOT (0..1 to 1..1, Connector_ID: 1637)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_VORDERING_BEVAT_RESTITUTIE FOREIGN KEY ([VORDERING_BEVAT_RESTITUTIE_RESTITUTIE_ID]) REFERENCES [RESTITUTIE] ([RESTITUTIE_ID]);
-- VORDERING_BEVAT_RESTITUTIE (0..* to 1..1, Connector_ID: 1638)

ALTER TABLE [RENTEVORDERING] ADD CONSTRAINT FK_RENTEVORDERING_RENTEVORDERING_IS_GERELATEERD_AAN_VORDERING FOREIGN KEY ([RENTEVORDERING_IS_GERELATEERD_AAN_VORDERING_VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- RENTEVORDERING_IS_GERELATEERD_AAN_VORDERING (1..1 to 0..*, Connector_ID: 1639)

ALTER TABLE [VORDERINGSCOMPONENT] ADD CONSTRAINT FK_VORDERINGSCOMPONENT_VORDERINGSCOMPONENT_BEVAT_RECHTMAAND FOREIGN KEY ([VORDERINGSCOMPONENT_BEVAT_RECHTMAAND_RECHTMAAND_ID]) REFERENCES [RECHTMAAND] ([RECHTMAAND_ID]);
-- VORDERINGSCOMPONENT_BEVAT_RECHTMAAND (0..* to 1..1, Connector_ID: 1641)

ALTER TABLE [TERUGVORDERINGSVERZOEK] ADD CONSTRAINT FK_TERUGVORDERINGSVERZOEK_TERUGVORDERINGSVERZOEK_BEVAT_RECHTMAAND FOREIGN KEY ([TERUGVORDERINGSVERZOEK_BEVAT_RECHTMAAND_RECHTMAAND_ID]) REFERENCES [RECHTMAAND] ([RECHTMAAND_ID]);
-- TERUGVORDERINGSVERZOEK_BEVAT_RECHTMAAND (0..* to 1..1, Connector_ID: 1642)

ALTER TABLE [LEENBIJSTAND] ADD CONSTRAINT FK_LEENBIJSTAND_IS_ORIGINE_VAN FOREIGN KEY ([IS_ORIGINE_VAN_LEENBIJSTANDVORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- IS_ORIGINE_VAN (0..* to 1..1, Connector_ID: 1645)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_VORDERING_BEVAT_KWIJTSCHELDING FOREIGN KEY ([VORDERING_BEVAT_KWIJTSCHELDING_KWIJTSCHELDING_ID]) REFERENCES [KWIJTSCHELDING] ([KWIJTSCHELDING_ID]);
-- VORDERING_BEVAT_KWIJTSCHELDING (0..1 to 1..1, Connector_ID: 1646)

ALTER TABLE [KREDIETHYPOTHEEK] ADD CONSTRAINT FK_KREDIETHYPOTHEEK_IS_ORIGINE_VAN FOREIGN KEY ([IS_ORIGINE_VAN_KREDIETHYPOTHEEKVORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- IS_ORIGINE_VAN (0..* to 1..1, Connector_ID: 1648)

ALTER TABLE [INTERVENTIEVERZOEK] ADD CONSTRAINT FK_INTERVENTIEVERZOEK_INITIEERT FOREIGN KEY ([INITIEERT_INTERVENTIE_ID]) REFERENCES [INTERVENTIE] ([INTERVENTIE_ID]);
-- INITIEERT (0..1 to 1..*, Connector_ID: 1650)

ALTER TABLE [INCASSOKOSTENVORDERING] ADD CONSTRAINT FK_INCASSOKOSTENVORDERING_INCASSOKOSTENVORDERING_IS_GERELATEERD_AAN_VORDERING FOREIGN KEY ([INCASSOKOSTENVORDERING_IS_GERELATEERD_AAN_VORDERING_VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- INCASSOKOSTENVORDERING_IS_GERELATEERD_AAN_VORDERING (1..1 to 0..*, Connector_ID: 1651)

ALTER TABLE [DEBITEUR] ADD CONSTRAINT FK_DEBITEUR_DEBITEUR_HEEFT_AANGEGAAN_LEENBIJSTAND FOREIGN KEY ([DEBITEUR_HEEFT_AANGEGAAN_LEENBIJSTAND_LEENBIJSTAND_ID]) REFERENCES [LEENBIJSTAND] ([LEENBIJSTAND_ID]);
-- DEBITEUR_HEEFT_AANGEGAAN_LEENBIJSTAND (0..* to 1..2, Connector_ID: 1653)

ALTER TABLE [DEBITEUR] ADD CONSTRAINT FK_DEBITEUR_DEBITEUR_HEEFT_AFGESLOTEN_KREDIETHYPOTHEEK FOREIGN KEY ([DEBITEUR_HEEFT_AFGESLOTEN_KREDIETHYPOTHEEK_KREDIETHYPOTHEEK_ID]) REFERENCES [KREDIETHYPOTHEEK] ([KREDIETHYPOTHEEK_ID]);
-- DEBITEUR_HEEFT_AFGESLOTEN_KREDIETHYPOTHEEK (0..1 to 1..2, Connector_ID: 1654)

ALTER TABLE [DEBITEUR] ADD CONSTRAINT FK_DEBITEUR_DEBITEUR_HEEFT_VORDERING FOREIGN KEY ([DEBITEUR_HEEFT_VORDERING_VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- DEBITEUR_HEEFT_VORDERING (1..* to 1..2, Connector_ID: 1656)

ALTER TABLE [DEBITEUR] ADD CONSTRAINT FK_DEBITEUR_DEBITEUR_HEEFT_INVORDERINGSBASIS FOREIGN KEY ([DEBITEUR_HEEFT_INVORDERINGSBASIS_INVORDERINGSBASIS_ID]) REFERENCES [INVORDERINGSBASIS] ([INVORDERINGSBASIS_ID]);
-- DEBITEUR_HEEFT_INVORDERINGSBASIS (1..1 to 1..1, Connector_ID: 1657)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_VORDERING_BEVAT_CORRECTIE FOREIGN KEY ([VORDERING_BEVAT_CORRECTIE_CORRECTIE_ID]) REFERENCES [CORRECTIE] ([CORRECTIE_ID]);
-- VORDERING_BEVAT_CORRECTIE (0..* to 1..1, Connector_ID: 1658)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_VORDERING_IS_GERELATEERD_AAN_CONSERVATOIR_BESLAG FOREIGN KEY ([VORDERING_IS_GERELATEERD_AAN_CONSERVATOIR_BESLAG_CONSERVATOIR_BESLAG_ID]) REFERENCES [CONSERVATOIR_BESLAG] ([CONSERVATOIR_BESLAG_ID]);
-- VORDERING_IS_GERELATEERD_AAN_CONSERVATOIR_BESLAG (0..1 to 1..1, Connector_ID: 1659)

ALTER TABLE [BOETEVORDERING] ADD CONSTRAINT FK_BOETEVORDERING_IS_GERELATEERD_AAN FOREIGN KEY ([IS_GERELATEERD_AAN_VERWIJTBARE_VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- IS_GERELATEERD_AAN (0..1 to 0..1, Connector_ID: 1660)

ALTER TABLE [RECHTMAAND] ADD CONSTRAINT FK_RECHTMAAND_RECHTMAAND_BEVAT_BETAALCOMPONENT FOREIGN KEY ([RECHTMAAND_BEVAT_BETAALCOMPONENT_BETAALCOMPONENT_ID]) REFERENCES [BETAALCOMPONENT] ([BETAALCOMPONENT_ID]);
-- RECHTMAAND_BEVAT_BETAALCOMPONENT (1..* to 1..1, Connector_ID: 1662)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_VORDERING_BEVAT_AFSCHRIJVING FOREIGN KEY ([VORDERING_BEVAT_AFSCHRIJVING_AFSCHRIJVING_ID]) REFERENCES [AFSCHRIJVING] ([AFSCHRIJVING_ID]);
-- VORDERING_BEVAT_AFSCHRIJVING (0..1 to 1..1, Connector_ID: 1663)

ALTER TABLE [DEBITEUR] ADD CONSTRAINT FK_DEBITEUR_HEEFT FOREIGN KEY ([HEEFT_AFLOSSINGSPLAN_ID]) REFERENCES [AFLOSSINGSPLAN] ([AFLOSSINGSPLAN_ID]);
-- HEEFT (0..1 to 1..1, Connector_ID: 1664)

ALTER TABLE [AFLOSSINGSPLAN] ADD CONSTRAINT FK_AFLOSSINGSPLAN_IS_GEBASEERD_OP FOREIGN KEY ([IS_GEBASEERD_OP_INVORDERINGSBASIS_ID]) REFERENCES [INVORDERINGSBASIS] ([INVORDERINGSBASIS_ID]);
-- IS_GEBASEERD_OP (1..1 to 1..1, Connector_ID: 1665)

ALTER TABLE [AFLOSSINGSPLAN] ADD CONSTRAINT FK_AFLOSSINGSPLAN_AFLOSSINGSPLAN_ONDERGAAT_UITSTEL_AFLOSSING FOREIGN KEY ([AFLOSSINGSPLAN_ONDERGAAT_UITSTEL_AFLOSSING_UITSTEL_AFLOSSING_ID]) REFERENCES [UITSTEL_AFLOSSING] ([UITSTEL_AFLOSSING_ID]);
-- AFLOSSINGSPLAN_ONDERGAAT_UITSTEL_AFLOSSING (0..1 to 1..1, Connector_ID: 1666)

ALTER TABLE [AFLOSSINGSPLAN] ADD CONSTRAINT FK_AFLOSSINGSPLAN_BEVAT FOREIGN KEY ([BEVAT_AFLOSSINGSAFSPRAAK_ID]) REFERENCES [AFLOSSINGSAFSPRAAK] ([AFLOSSINGSAFSPRAAK_ID]);
-- BEVAT (1..* to 1..1, Connector_ID: 1668)

ALTER TABLE [AFLOSSINGSAFSPRAAK] ADD CONSTRAINT FK_AFLOSSINGSAFSPRAAK_AFLOSSINGSAFSPRAAK_BETREFT_VORDERING FOREIGN KEY ([AFLOSSINGSAFSPRAAK_BETREFT_VORDERING_VORDERING_ID]) REFERENCES [VORDERING] ([VORDERING_ID]);
-- AFLOSSINGSAFSPRAAK_BETREFT_VORDERING (1..1 to 0..*, Connector_ID: 1669)

ALTER TABLE [VORDERING] ADD CONSTRAINT FK_VORDERING_VORDERING_BEVAT_AFLOSSING FOREIGN KEY ([VORDERING_BEVAT_AFLOSSING_AFLOSSING_ID]) REFERENCES [AFLOSSING] ([AFLOSSING_ID]);
-- VORDERING_BEVAT_AFLOSSING (0..* to 1..1, Connector_ID: 1670)

ALTER TABLE [AFLOSSINGSAFSPRAAK] ADD CONSTRAINT FK_AFLOSSINGSAFSPRAAK_AFLOSSINGSAFSPRAAK_BEVAT_AFLOSSING FOREIGN KEY ([AFLOSSINGSAFSPRAAK_BEVAT_AFLOSSING_AFLOSSING_ID]) REFERENCES [AFLOSSING] ([AFLOSSING_ID]);
-- AFLOSSINGSAFSPRAAK_BEVAT_AFLOSSING (0..* to 1..1, Connector_ID: 1671)

