CREATE TABLE BELPROVIDER (
    RECHTSPERSOON_ID VARCHAR(255) PRIMARY KEY,
        CODE VARCHAR(255)
);

CREATE TABLE BOOLEAN_ENUM (
    BOOLEAN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES
    (1, 'JA'),
    (2, 'LEEG'),
    (3, 'NEE'),
    (4, 'ONBEKEND');

CREATE TABLE DOELGROEPENPLAATSEN_ENUM (
    DOELGROEPENPLAATSEN_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO DOELGROEPENPLAATSEN_ENUM (DOELGROEPENPLAATSEN_ENUM_ID, VALUE) VALUES
    (1, 'DP01'),
    (2, 'DP02'),
    (3, 'DP03'),
    (4, 'DP04'),
    (5, 'DP05'),
    (6, 'LEEG');

CREATE TABLE KP_PRKRRCHT_PRKRZN (
    KP_PRKRRCHT_PRKRZN_ID VARCHAR(255) PRIMARY KEY,
    PARKEERRECHT_ID VARCHAR(255),
    PARKEERZONE_ID VARCHAR(255)
);

CREATE TABLE KP_PRKRVRGNNNG_PRKRZN (
    KP_PRKRVRGNNNG_PRKRZN_ID VARCHAR(255) PRIMARY KEY,
    PARKEERVERGUNNING_ID VARCHAR(255),
    PARKEERZONE_ID VARCHAR(255)
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID VARCHAR(255) PRIMARY KEY,
        NAAM VARCHAR(200),
        NUMMER VARCHAR(255)
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID VARCHAR(255) PRIMARY KEY,
        ACHTERNAAM VARCHAR(200),
        DATUMINDIENST DATE,
        DATUMUITDIENST DATE,
        EMAILADRES VARCHAR(255),
        EXTERN VARCHAR(255),
        FUNCTIE VARCHAR(50),
        GELEVERD_VIA_LEVERANCIER_ID VARCHAR(255),
        GESLACHTSAANDUIDING VARCHAR(255),
        MEDEWERKERIDENTIFICATIE VARCHAR(255),
        MEDEWERKERTOELICHTING VARCHAR(255),
        ROEPNAAM VARCHAR(255),
        TELEFOONNUMMER VARCHAR(20),
        VOORLETTERS VARCHAR(20),
        VOORVOEGSELACHTERNAAM VARCHAR(255)
);

CREATE TABLE MULDERFEIT (
    MULDERFEIT_ID VARCHAR(255) PRIMARY KEY,
        BEDRAG DECIMAL(10,2),
        BETREFT_VOERTUIG_VOERTUIG_ID VARCHAR(255),
        BEZWAARAFGEHANDELD DATE,
        BEZWAARINGETROKKEN DATE,
        BEZWAARTOEGEWEZEN DATE,
        BONNUMMER INTEGER,
        DATUMBETALING DATE,
        DATUMBEZWAAR DATE,
        DATUMGESEPONEERD DATE,
        DATUMINDIENING DATE,
        DIENSTCD VARCHAR(255),
        ORGANISATIE VARCHAR(200),
        OVERTREDING VARCHAR(80),
        PARKEERTARIEF DECIMAL(10,2),
        REDENSEPONEREN VARCHAR(255),
        VORDERINGNUMMER INTEGER
);

CREATE TABLE NAHEFFING (
    NAHEFFING_ID VARCHAR(255) PRIMARY KEY,
        BEDRAG DECIMAL(10,2),
        BEZWAARAFGEHANDELD DATE,
        BEZWAARINGETROKKEN DATE,
        BEZWAARTOEGEWEZEN DATE,
        BONNUMMER INTEGER,
        DATUMBETALING DATE,
        DATUMBEZWAAR DATE,
        DATUMGESEPONEERD DATE,
        DATUMINDIENING DATE,
        DIENSTCD VARCHAR(255),
        FISCAAL_ENUM_ID VARCHAR(255),
        ORGANISATIE VARCHAR(200),
        OVERTREDING VARCHAR(80),
        PARKEERTARIEF DECIMAL(10,2),
        REDENSEPONEREN VARCHAR(255),
        VORDERINGNUMMER INTEGER
);

CREATE TABLE PARKEERGARAGE (
    PARKEERZONE_ID VARCHAR(255) PRIMARY KEY
);

CREATE TABLE PARKEERRECHT (
    PARKEERRECHT_ID VARCHAR(255) PRIMARY KEY,
        AANMAAKTIJD TIMESTAMP,
        BEDRAGAANKOOP DECIMAL(10,2),
        BEDRAGBTW DECIMAL(10,2),
        BETREFT_VOERTUIG_ID VARCHAR(255),
        DATUMTIJDEINDE TIMESTAMP,
        DATUMTIJDSTART TIMESTAMP,
        LEVERANCIER_BELPROVIDER_ID VARCHAR(255),
        PRODUCTNAAM VARCHAR(80),
        PRODUCTOMSCHRIJVING TEXT
);

CREATE TABLE PARKEERSCAN (
    PARKEERSCAN_ID VARCHAR(255) PRIMARY KEY,
        BETREFT_PARKEERVLAK_ID VARCHAR(255),
        BETREFT_VOERTUIG_ID VARCHAR(255),
        CODEGEBRUIKER VARCHAR(255),
        CODESCANVOERTUIG VARCHAR(255),
        COORDINATEN GEOMETRY,
        FOTO VARCHAR(255),
        KENTEKEN VARCHAR(255),
        KOMT_VOORT_UIT_NAHEFFING_ID VARCHAR(255),
        PARKEERRECHT_ENUM_ID VARCHAR(255),
        TIJDSTIP TIMESTAMP,
        TRANSACTIEID VARCHAR(255),
        UITGEVOERD_DOOR_MEDEWERKER_ID VARCHAR(255),
        VERIFICATIE_PARKEERRECHT_ID VARCHAR(255)
);

CREATE TABLE PARKEERVERGUNNING (
    PARKEERVERGUNNING_ID VARCHAR(255) PRIMARY KEY,
        DATUMEINDEGELDIGHEID DATE,
        DATUMRESERVERING DATE,
        DATUMSTART DATE,
        HOUDER_RECHTSPERSOON_ID VARCHAR(255),
        KENTEKEN VARCHAR(255),
        MINUTENAFGESCHREVEN INTEGER,
        MINUTENGELDIG INTEGER,
        MINUTENRESTEREND INTEGER,
        NUMMER INTEGER,
        RESULTEERT_PARKEERRECHT_ID VARCHAR(255),
        TYPE VARCHAR(255)
);

CREATE TABLE PARKEERVLAK (
    PARKEERVLAK_ID VARCHAR(255) PRIMARY KEY,
        AANTAL INTEGER,
        COORDINATEN GEOMETRY,
        DOELGROEP_ENUM_ID VARCHAR(255),
        FISCAAL_ENUM_ID VARCHAR(255),
        PLAATS VARCHAR(200),
        VLAKID VARCHAR(255)
);

CREATE TABLE PARKEERZONE (
    PARKEERZONE_ID VARCHAR(255) PRIMARY KEY,
        AANTALPARKEERVLAKKEN INTEGER,
        ALLEENDAGTARIEF_ENUM_ID VARCHAR(255),
        BEVAT_PARKEERVLAK_ID VARCHAR(255),
        BEVAT_STRAATSECTIE_ID VARCHAR(255),
        DAGTARIEF DECIMAL(10,2),
        EINDEDAG DATE,
        EINDTIJD TIMESTAMP,
        GEBRUIK VARCHAR(255),
        GEOMETRIE GEOMETRY,
        IPMCODE VARCHAR(255),
        IPMNAAM VARCHAR(255),
        ISPARKEERGARAGE_ENUM_ID VARCHAR(255),
        NAAM VARCHAR(255),
        SECTORCODE VARCHAR(255),
        SOORTCODE VARCHAR(255),
        STARTDAG DATE,
        STARTTARIEF DECIMAL(10,2),
        STARTTIJD TIMESTAMP,
        TYPECODE VARCHAR(255),
        TYPENAAM VARCHAR(255),
        UURTARIEF DECIMAL(10,2)
);

CREATE TABLE PRODUCTGROEP (
    PRODUCTGROEP_ID VARCHAR(255) PRIMARY KEY,
        BESLISBOOM VARCHAR(255),
        CODE VARCHAR(255),
        OMSCHRIJVING VARCHAR(255),
        SOORT_PARKEERVERGUNNING_ID VARCHAR(255)
);

CREATE TABLE PRODUCTSOORT (
    PRODUCTSOORT_ID VARCHAR(255) PRIMARY KEY,
        CODE VARCHAR(255),
        OMSCHRIJVING VARCHAR(255),
        SOORT_PARKEERVERGUNNING_ID VARCHAR(255),
        TARIEF DECIMAL(10,2),
        TARIEFPERIODE VARCHAR(255),
        VALT_BINNEN_PRODUCTGROEP_ID VARCHAR(255)
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR(255),
        ADRESBUITENLAND VARCHAR(255),
        ADRESCORRESPONDENTIE VARCHAR(100),
        EMAILADRES VARCHAR(80),
        FAXNUMMER VARCHAR(20),
        IDENTIFICATIE VARCHAR(255),
        KVKNUMMER VARCHAR(20),
        NAAM VARCHAR(200),
        RECHTSVORM VARCHAR(100),
        REKENINGNUMMER VARCHAR(255),
        TELEFOONNUMMER VARCHAR(20)
);

CREATE TABLE STRAATSECTIE (
    STRAATSECTIE_ID VARCHAR(255) PRIMARY KEY,
        BEVAT_PARKEERVLAK_ID VARCHAR(255),
        CODE VARCHAR(255),
        OMSCHRIJVING VARCHAR(255),
        ZONECODE_ENUM_ID VARCHAR(255)
);

CREATE TABLE VOERTUIG (
    VOERTUIG_ID VARCHAR(255) PRIMARY KEY,
        KENTEKEN VARCHAR(255),
        KLEUR VARCHAR(200),
        LAND VARCHAR(200),
        MERK VARCHAR(200),
        TYPE VARCHAR(200)
);

CREATE TABLE ZONESOORT_ENUM (
    ZONESOORT_ENUM_ID VARCHAR(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO ZONESOORT_ENUM (ZONESOORT_ENUM_ID, VALUE) VALUES
    (1, 'GSM_ZONE'),
    (2, 'VERGUNNINGHOUDERZONE');

ALTER TABLE BELPROVIDER ADD CONSTRAINT FK_BELPROVIDER_GEN_LEVERANCIER FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES LEVERANCIER (RECHTSPERSOON_ID);
-- Generalization to LEVERANCIER

ALTER TABLE PARKEERGARAGE ADD CONSTRAINT FK_PARKEERGARAGE_GEN_PARKEERZONE FOREIGN KEY (PARKEERZONE_ID) REFERENCES PARKEERZONE (PARKEERZONE_ID);
-- Generalization to PARKEERZONE

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_PRKRRCHT_PRKRZN ADD CONSTRAINT FK_KP_PRKRRCHT_PRKRZN_1 FOREIGN KEY (PARKEERRECHT_ID) REFERENCES PARKEERRECHT (PARKEERRECHT_ID);
-- PARKEERRECHT (many-to-many junction, Connector_ID: 1284)

ALTER TABLE KP_PRKRRCHT_PRKRZN ADD CONSTRAINT FK_KP_PRKRRCHT_PRKRZN_2 FOREIGN KEY (PARKEERZONE_ID) REFERENCES PARKEERZONE (PARKEERZONE_ID);
-- PARKEERZONE (many-to-many junction, Connector_ID: 1284)

ALTER TABLE KP_PRKRVRGNNNG_PRKRZN ADD CONSTRAINT FK_KP_PRKRVRGNNNG_PRKRZN_1 FOREIGN KEY (PARKEERVERGUNNING_ID) REFERENCES PARKEERVERGUNNING (PARKEERVERGUNNING_ID);
-- PARKEERVERGUNNING (many-to-many junction, Connector_ID: 1277)

ALTER TABLE KP_PRKRVRGNNNG_PRKRZN ADD CONSTRAINT FK_KP_PRKRVRGNNNG_PRKRZN_2 FOREIGN KEY (PARKEERZONE_ID) REFERENCES PARKEERZONE (PARKEERZONE_ID);
-- PARKEERZONE (many-to-many junction, Connector_ID: 1277)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_GELEVERD_VIA FOREIGN KEY (GELEVERD_VIA_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- GELEVERD_VIA (0..* to 0..1, Connector_ID: 388)

ALTER TABLE MULDERFEIT ADD CONSTRAINT FK_MULDERFEIT_BETREFT_VOERTUIG FOREIGN KEY (BETREFT_VOERTUIG_VOERTUIG_ID) REFERENCES VOERTUIG (VOERTUIG_ID);
-- BETREFT_VOERTUIG (0..* to 0..1, Connector_ID: 1288)

ALTER TABLE NAHEFFING ADD CONSTRAINT FK_NAHEFFING_FISCAAL_ENUM_ID FOREIGN KEY (FISCAAL_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- FISCAAL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERRECHT ADD CONSTRAINT FK_PARKEERRECHT_BETREFT FOREIGN KEY (BETREFT_VOERTUIG_ID) REFERENCES VOERTUIG (VOERTUIG_ID);
-- BETREFT (0..* to 1, Connector_ID: 1285)

ALTER TABLE PARKEERRECHT ADD CONSTRAINT FK_PARKEERRECHT_LEVERANCIER FOREIGN KEY (LEVERANCIER_BELPROVIDER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- LEVERANCIER (0..* to 0..1, Connector_ID: 1289)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_BETREFT FOREIGN KEY (BETREFT_PARKEERVLAK_ID) REFERENCES PARKEERVLAK (PARKEERVLAK_ID);
-- BETREFT (0..* to 1, Connector_ID: 1279)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_BETREFT_2 FOREIGN KEY (BETREFT_VOERTUIG_ID) REFERENCES VOERTUIG (VOERTUIG_ID);
-- BETREFT (0..* to 1, Connector_ID: 1280)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_KOMT_VOORT_UIT FOREIGN KEY (KOMT_VOORT_UIT_NAHEFFING_ID) REFERENCES NAHEFFING (NAHEFFING_ID);
-- KOMT_VOORT_UIT (0..1 to 0..1, Connector_ID: 1287)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_PARKEERRECHT_ENUM_ID FOREIGN KEY (PARKEERRECHT_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- PARKEERRECHT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_UITGEVOERD_DOOR FOREIGN KEY (UITGEVOERD_DOOR_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- UITGEVOERD_DOOR (0..* to 1, Connector_ID: 1281)

ALTER TABLE PARKEERSCAN ADD CONSTRAINT FK_PARKEERSCAN_VERIFICATIE FOREIGN KEY (VERIFICATIE_PARKEERRECHT_ID) REFERENCES PARKEERRECHT (PARKEERRECHT_ID);
-- VERIFICATIE (0..1 to None, Connector_ID: 1282)

ALTER TABLE PARKEERVERGUNNING ADD CONSTRAINT FK_PARKEERVERGUNNING_HOUDER FOREIGN KEY (HOUDER_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- HOUDER (0..* to 1, Connector_ID: 1276)

ALTER TABLE PARKEERVERGUNNING ADD CONSTRAINT FK_PARKEERVERGUNNING_RESULTEERT FOREIGN KEY (RESULTEERT_PARKEERRECHT_ID) REFERENCES PARKEERRECHT (PARKEERRECHT_ID);
-- RESULTEERT (0..1 to 0..1, Connector_ID: 1283)

ALTER TABLE PARKEERVLAK ADD CONSTRAINT FK_PARKEERVLAK_DOELGROEP_ENUM_ID FOREIGN KEY (DOELGROEP_ENUM_ID) REFERENCES DOELGROEPENPLAATSEN_ENUM (DOELGROEPENPLAATSEN_ENUM_ID);
-- DOELGROEP_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERVLAK ADD CONSTRAINT FK_PARKEERVLAK_FISCAAL_ENUM_ID FOREIGN KEY (FISCAAL_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- FISCAAL_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERZONE ADD CONSTRAINT FK_PARKEERZONE_ALLEENDAGTARIEF_ENUM_ID FOREIGN KEY (ALLEENDAGTARIEF_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- ALLEENDAGTARIEF_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PARKEERZONE ADD CONSTRAINT FK_PARKEERZONE_BEVAT FOREIGN KEY (BEVAT_STRAATSECTIE_ID) REFERENCES STRAATSECTIE (STRAATSECTIE_ID);
-- BEVAT (1 to 0..*, Connector_ID: 1271)

ALTER TABLE PARKEERZONE ADD CONSTRAINT FK_PARKEERZONE_BEVAT_2 FOREIGN KEY (BEVAT_PARKEERVLAK_ID) REFERENCES PARKEERVLAK (PARKEERVLAK_ID);
-- BEVAT (1 to 0..*, Connector_ID: 1273)

ALTER TABLE PARKEERZONE ADD CONSTRAINT FK_PARKEERZONE_ISPARKEERGARAGE_ENUM_ID FOREIGN KEY (ISPARKEERGARAGE_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- ISPARKEERGARAGE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE PRODUCTGROEP ADD CONSTRAINT FK_PRODUCTGROEP_SOORT FOREIGN KEY (SOORT_PARKEERVERGUNNING_ID) REFERENCES PARKEERVERGUNNING (PARKEERVERGUNNING_ID);
-- SOORT (1 to 0..*, Connector_ID: 1275)

ALTER TABLE PRODUCTSOORT ADD CONSTRAINT FK_PRODUCTSOORT_SOORT FOREIGN KEY (SOORT_PARKEERVERGUNNING_ID) REFERENCES PARKEERVERGUNNING (PARKEERVERGUNNING_ID);
-- SOORT (1 to 0..*, Connector_ID: 1274)

ALTER TABLE PRODUCTSOORT ADD CONSTRAINT FK_PRODUCTSOORT_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_PRODUCTGROEP_ID) REFERENCES PRODUCTGROEP (PRODUCTGROEP_ID);
-- VALT_BINNEN (0..* to 1, Connector_ID: 1270)

ALTER TABLE STRAATSECTIE ADD CONSTRAINT FK_STRAATSECTIE_BEVAT FOREIGN KEY (BEVAT_PARKEERVLAK_ID) REFERENCES PARKEERVLAK (PARKEERVLAK_ID);
-- BEVAT (1 to 0..*, Connector_ID: 1272)

ALTER TABLE STRAATSECTIE ADD CONSTRAINT FK_STRAATSECTIE_ZONECODE_ENUM_ID FOREIGN KEY (ZONECODE_ENUM_ID) REFERENCES ZONESOORT_ENUM (ZONESOORT_ENUM_ID);
-- ZONECODE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

