CREATE TABLE [MAATREGEL] (
    [MAATREGEL_ID] INT PRIMARY KEY,
    [DATUM_AANVANG_MAATREGEL] DATE,
    [DATUM_EINDE_MAATREGEL] DATE,
    [DATUM_VASTSTELLING_MAATREGEL] DATE,
    [IDENTIFICATIE] DATE,
    [TYPE_MAATREGEL] VARCHAR(255)
);

CREATE TABLE [NORMAFWIJKING] (
    [NORMAFWIJKING_ID] INT PRIMARY KEY,
    [DATUM_VASTSTELLING_NORMAFWIJKING] DATE,
    [DATUM_VASTSTELLING_VERWIJTBAARHEID] DATE,
    [IDENTIFICATIE] DATE,
    [MOTIVATIE_VERWIJTBAARHEID] DATE,
    [NORMAFWIJKING_LEIDT_TOT_MAATREGEL_MAATREGEL_ID] INT,
    [RECIDIVE] VARCHAR(255),
    [TYPE_NORMAFWIJKING] VARCHAR(255),
    [VERWIJTBAARHEID] VARCHAR(255)
);

CREATE TABLE [MAATREGEL_OP_UITKERING] (
    [MAATREGEL_ID] INT PRIMARY KEY,
    [CODE_REDEN_MAATREGEL] VARCHAR(255),
    [MOTIVATIE_VERMINDERING_MAATREGEL] VARCHAR(255),
    [PERCENTAGE_MAATREGEL] VARCHAR(255)
);

CREATE TABLE [BOETE] (
    [MAATREGEL_ID] INT PRIMARY KEY,
    [BEDRAG_BOETE] DECIMAL(10,2),
    [BOETEVORM] VARCHAR(255),
    [REDEN_BOETE] VARCHAR(255),
    [VOORWAARDE_BOETE] VARCHAR(255)
);

CREATE TABLE [AFWIJKENDE_MAATREGEL] (
    [MAATREGEL_ID] INT PRIMARY KEY,
    [BEDRAG] DECIMAL(10,2),
    [CODE_REDEN_AFWIJKING_MAATREGEL] VARCHAR(255),
    [MOTIVATIE_AFWIJKING_MAATREGEL] VARCHAR(255),
    [PERCENTAGE] VARCHAR(255),
    [REFEREERT_MAATREGEL_OP_UITKERING_ID] INT
);

ALTER TABLE [AFWIJKENDE_MAATREGEL] ADD CONSTRAINT FK_AFWIJKENDE_MAATREGEL_GEN_MAATREGEL FOREIGN KEY ([MAATREGEL_ID]) REFERENCES [MAATREGEL] ([MAATREGEL_ID]);
-- Generalization to MAATREGEL

ALTER TABLE [BOETE] ADD CONSTRAINT FK_BOETE_GEN_MAATREGEL FOREIGN KEY ([MAATREGEL_ID]) REFERENCES [MAATREGEL] ([MAATREGEL_ID]);
-- Generalization to MAATREGEL

ALTER TABLE [MAATREGEL_OP_UITKERING] ADD CONSTRAINT FK_MAATREGEL_OP_UITKERING_GEN_MAATREGEL FOREIGN KEY ([MAATREGEL_ID]) REFERENCES [MAATREGEL] ([MAATREGEL_ID]);
-- Generalization to MAATREGEL

ALTER TABLE [NORMAFWIJKING] ADD CONSTRAINT FK_NORMAFWIJKING_NORMAFWIJKING_LEIDT_TOT_MAATREGEL FOREIGN KEY ([NORMAFWIJKING_LEIDT_TOT_MAATREGEL_MAATREGEL_ID]) REFERENCES [MAATREGEL] ([MAATREGEL_ID]);
-- NORMAFWIJKING_LEIDT_TOT_MAATREGEL (0..1 to 1..1, Connector_ID: 1697)

ALTER TABLE [AFWIJKENDE_MAATREGEL] ADD CONSTRAINT FK_AFWIJKENDE_MAATREGEL_REFEREERT FOREIGN KEY ([REFEREERT_MAATREGEL_OP_UITKERING_ID]) REFERENCES [MAATREGEL] ([MAATREGEL_ID]);
-- REFEREERT (1..1 to 1..1, Connector_ID: 1699)

