CREATE TABLE ACTIVITEIT (
    ACTIVITEIT_ID VARCHAR(255) PRIMARY KEY,
        BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID VARCHAR(255),
        GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID VARCHAR(255),
        GROEP VARCHAR(200),
        NAAM VARCHAR(200),
        NEN3610ID VARCHAR(80)
);

CREATE TABLE BEPERKINGSGEBIED (
    GEBIEDSAANWIJZING_ID VARCHAR(255) PRIMARY KEY,
        GROEP VARCHAR(200),
        NAAM VARCHAR(200)
);

CREATE TABLE FUNCTIE (
    GEBIEDSAANWIJZING_ID VARCHAR(255) PRIMARY KEY,
        GROEP VARCHAR(200),
        NAAM VARCHAR(200)
);

CREATE TABLE GEBIEDSAANWIJZING (
    GEBIEDSAANWIJZING_ID VARCHAR(255) PRIMARY KEY,
        GROEP VARCHAR(200),
        NAAM VARCHAR(200),
        NEN3610ID VARCHAR(80)
);

CREATE TABLE INSTRUCTIEREGEL (
    JURIDISCHE_REGEL_ID VARCHAR(255) PRIMARY KEY,
        INSTRUCTIEREGELINSTRUMENT VARCHAR(200),
        INSTRUCTIEREGELTAAKUITOEFENING VARCHAR(200)
);

CREATE TABLE JURIDISCHE_REGEL (
    JURIDISCHE_REGEL_ID VARCHAR(255) PRIMARY KEY,
        DATUMBEKEND DATE,
        DATUMEINDEGELDIGHEID DATE,
        DATUMINWERKING DATE,
        DATUMSTART DATE,
        IS_OPGENOMEN_IN_REGELTEKST_ID VARCHAR(255),
        OMSCHRIJVING TEXT,
        REGELTEKST VARCHAR(200),
        THEMA VARCHAR(200)
);

CREATE TABLE KP_ACTVTT (
    KP_ACTVTT_ID VARCHAR(255) PRIMARY KEY,
    ACTIVITEIT_ID VARCHAR(255),
    LOCATIE_ID VARCHAR(255)
);

CREATE TABLE KP_GBDSNWJZNG (
    KP_GBDSNWJZNG_ID VARCHAR(255) PRIMARY KEY,
    GEBIEDSAANWIJZING_ID VARCHAR(255),
    LOCATIE_ID VARCHAR(255)
);

CREATE TABLE KP_INSTRCTRGL (
    KP_INSTRCTRGL_ID VARCHAR(255) PRIMARY KEY,
    INSTRUCTIEREGEL_ID VARCHAR(255),
    GEBIEDSAANWIJZING_ID VARCHAR(255)
);

CREATE TABLE KP_JRDSCH (
    KP_JRDSCH_ID VARCHAR(255) PRIMARY KEY,
    JURIDISCHE_REGEL_ID VARCHAR(255),
    ACTIVITEIT_ID VARCHAR(255)
);

CREATE TABLE KP_NRMWRD (
    KP_NRMWRD_ID VARCHAR(255) PRIMARY KEY,
    NORMWAARDE_ID VARCHAR(255),
    LOCATIE_ID VARCHAR(255)
);

CREATE TABLE KP_OMGVNGSWRDRGL (
    KP_OMGVNGSWRDRGL_ID VARCHAR(255) PRIMARY KEY,
    OMGEVINGSWAARDEREGEL_ID VARCHAR(255),
    OMGEVINGSNORM_ID VARCHAR(255)
);

CREATE TABLE KP_RGL (
    KP_RGL_ID VARCHAR(255) PRIMARY KEY,
    REGEL_VOOR_IEDEREEN_ID VARCHAR(255),
    ACTIVITEIT_ID VARCHAR(255)
);

CREATE TABLE KP_RGLTKST (
    KP_RGLTKST_ID VARCHAR(255) PRIMARY KEY,
    REGELTEKST_ID VARCHAR(255),
    LOCATIE_ID VARCHAR(255)
);

CREATE TABLE LOCATIE (
    LOCATIE_ID VARCHAR(255) PRIMARY KEY,
        HOOGTE INTEGER,
        NAAM VARCHAR(200),
        NEN3610ID VARCHAR(80)
);

CREATE TABLE NORM (
    NORM_ID VARCHAR(255) PRIMARY KEY,
        BEVAT_NORMWAARDE_ID VARCHAR(255),
        NEN3610ID VARCHAR(80)
);

CREATE TABLE NORMWAARDE (
    NORMWAARDE_ID VARCHAR(255) PRIMARY KEY,
        KWALITATIEVEWAARDE VARCHAR(80),
        KWANTITATIEVEWAARDEEENHEID VARCHAR(80),
        KWANTITATIEVEWAARDEOMVANG VARCHAR(255)
);

CREATE TABLE OMGEVINGSNORM (
    NORM_ID VARCHAR(255) PRIMARY KEY,
        NAAM VARCHAR(200),
        OMGEVINGSNORMGROEP VARCHAR(200)
);

CREATE TABLE OMGEVINGSWAARDE (
    NORM_ID VARCHAR(255) PRIMARY KEY,
        NAAM VARCHAR(200),
        OMGEVINGSWAARDEGROEP VARCHAR(200)
);

CREATE TABLE OMGEVINGSWAARDEREGEL (
    JURIDISCHE_REGEL_ID VARCHAR(255) PRIMARY KEY,
        GROEP VARCHAR(200),
        NAAM VARCHAR(200)
);

CREATE TABLE REGELTEKST (
    REGELTEKST_ID VARCHAR(255) PRIMARY KEY,
        IDENTIFICATIE VARCHAR(200),
        IS_GERELATEERD_REGELTEKST_ID VARCHAR(255),
        OMSCHRIJVING TEXT,
        TEKST TEXT,
        WERKINGSGEBIED_REGELTEKST_ID VARCHAR(255)
);

CREATE TABLE REGEL_VOOR_IEDEREEN (
    JURIDISCHE_REGEL_ID VARCHAR(255) PRIMARY KEY,
        ACTIVITEITREGELKWALIFICATIE VARCHAR(200)
);

ALTER TABLE BEPERKINGSGEBIED ADD CONSTRAINT FK_BEPERKINGSGEBIED_GEN_GEBIEDSAANWIJZING FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- Generalization to GEBIEDSAANWIJZING

ALTER TABLE FUNCTIE ADD CONSTRAINT FK_FUNCTIE_GEN_GEBIEDSAANWIJZING FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- Generalization to GEBIEDSAANWIJZING

ALTER TABLE INSTRUCTIEREGEL ADD CONSTRAINT FK_INSTRUCTIEREGEL_GEN_JURIDISCHE_REGEL FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- Generalization to JURIDISCHE_REGEL

ALTER TABLE OMGEVINGSNORM ADD CONSTRAINT FK_OMGEVINGSNORM_GEN_NORM FOREIGN KEY (NORM_ID) REFERENCES NORM (NORM_ID);
-- Generalization to NORM

ALTER TABLE OMGEVINGSWAARDE ADD CONSTRAINT FK_OMGEVINGSWAARDE_GEN_NORM FOREIGN KEY (NORM_ID) REFERENCES NORM (NORM_ID);
-- Generalization to NORM

ALTER TABLE OMGEVINGSWAARDEREGEL ADD CONSTRAINT FK_OMGEVINGSWAARDEREGEL_GEN_JURIDISCHE_REGEL FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- Generalization to JURIDISCHE_REGEL

ALTER TABLE REGEL_VOOR_IEDEREEN ADD CONSTRAINT FK_REGEL_VOOR_IEDEREEN_GEN_JURIDISCHE_REGEL FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- Generalization to JURIDISCHE_REGEL

ALTER TABLE KP_ACTVTT ADD CONSTRAINT FK_KP_ACTVTT_1 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 680)

ALTER TABLE KP_ACTVTT ADD CONSTRAINT FK_KP_ACTVTT_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 680)

ALTER TABLE KP_GBDSNWJZNG ADD CONSTRAINT FK_KP_GBDSNWJZNG_1 FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- GEBIEDSAANWIJZING (many-to-many junction, Connector_ID: 674)

ALTER TABLE KP_GBDSNWJZNG ADD CONSTRAINT FK_KP_GBDSNWJZNG_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 674)

ALTER TABLE KP_INSTRCTRGL ADD CONSTRAINT FK_KP_INSTRCTRGL_1 FOREIGN KEY (INSTRUCTIEREGEL_ID) REFERENCES INSTRUCTIEREGEL (JURIDISCHE_REGEL_ID);
-- INSTRUCTIEREGEL (many-to-many junction, Connector_ID: 673)

ALTER TABLE KP_INSTRCTRGL ADD CONSTRAINT FK_KP_INSTRCTRGL_2 FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- GEBIEDSAANWIJZING (many-to-many junction, Connector_ID: 673)

ALTER TABLE KP_JRDSCH ADD CONSTRAINT FK_KP_JRDSCH_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_JRDSCH ADD CONSTRAINT FK_KP_JRDSCH_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 668)

ALTER TABLE KP_JRDSCH ADD CONSTRAINT FK_KP_JRDSCH_1 FOREIGN KEY (JURIDISCHE_REGEL_ID) REFERENCES JURIDISCHE_REGEL (JURIDISCHE_REGEL_ID);
-- JURIDISCHE_REGEL (many-to-many junction, Connector_ID: 677)

ALTER TABLE KP_JRDSCH ADD CONSTRAINT FK_KP_JRDSCH_2 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 677)

ALTER TABLE KP_NRMWRD ADD CONSTRAINT FK_KP_NRMWRD_1 FOREIGN KEY (NORMWAARDE_ID) REFERENCES NORMWAARDE (NORMWAARDE_ID);
-- NORMWAARDE (many-to-many junction, Connector_ID: 665)

ALTER TABLE KP_NRMWRD ADD CONSTRAINT FK_KP_NRMWRD_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 665)

ALTER TABLE KP_OMGVNGSWRDRGL ADD CONSTRAINT FK_KP_OMGVNGSWRDRGL_1 FOREIGN KEY (OMGEVINGSWAARDEREGEL_ID) REFERENCES OMGEVINGSWAARDEREGEL (JURIDISCHE_REGEL_ID);
-- OMGEVINGSWAARDEREGEL (many-to-many junction, Connector_ID: 660)

ALTER TABLE KP_OMGVNGSWRDRGL ADD CONSTRAINT FK_KP_OMGVNGSWRDRGL_2 FOREIGN KEY (OMGEVINGSWAARDE_ID) REFERENCES OMGEVINGSWAARDE (NORM_ID);
-- OMGEVINGSWAARDE (many-to-many junction, Connector_ID: 660)

ALTER TABLE KP_OMGVNGSWRDRGL ADD CONSTRAINT FK_KP_OMGVNGSWRDRGL_1 FOREIGN KEY (OMGEVINGSWAARDEREGEL_ID) REFERENCES OMGEVINGSWAARDEREGEL (JURIDISCHE_REGEL_ID);
-- OMGEVINGSWAARDEREGEL (many-to-many junction, Connector_ID: 662)

ALTER TABLE KP_OMGVNGSWRDRGL ADD CONSTRAINT FK_KP_OMGVNGSWRDRGL_2 FOREIGN KEY (OMGEVINGSNORM_ID) REFERENCES OMGEVINGSNORM (NORM_ID);
-- OMGEVINGSNORM (many-to-many junction, Connector_ID: 662)

ALTER TABLE KP_RGL ADD CONSTRAINT FK_KP_RGL_1 FOREIGN KEY (REGEL_VOOR_IEDEREEN_ID) REFERENCES REGEL_VOOR_IEDEREEN (JURIDISCHE_REGEL_ID);
-- REGEL_VOOR_IEDEREEN (many-to-many junction, Connector_ID: 663)

ALTER TABLE KP_RGL ADD CONSTRAINT FK_KP_RGL_2 FOREIGN KEY (OMGEVINGSNORM_ID) REFERENCES OMGEVINGSNORM (NORM_ID);
-- OMGEVINGSNORM (many-to-many junction, Connector_ID: 663)

ALTER TABLE KP_RGL ADD CONSTRAINT FK_KP_RGL_1 FOREIGN KEY (REGEL_VOOR_IEDEREEN_ID) REFERENCES REGEL_VOOR_IEDEREEN (JURIDISCHE_REGEL_ID);
-- REGEL_VOOR_IEDEREEN (many-to-many junction, Connector_ID: 672)

ALTER TABLE KP_RGL ADD CONSTRAINT FK_KP_RGL_2 FOREIGN KEY (GEBIEDSAANWIJZING_ID) REFERENCES GEBIEDSAANWIJZING (GEBIEDSAANWIJZING_ID);
-- GEBIEDSAANWIJZING (many-to-many junction, Connector_ID: 672)

ALTER TABLE KP_RGL ADD CONSTRAINT FK_KP_RGL_1 FOREIGN KEY (REGEL_VOOR_IEDEREEN_ID) REFERENCES REGEL_VOOR_IEDEREEN (JURIDISCHE_REGEL_ID);
-- REGEL_VOOR_IEDEREEN (many-to-many junction, Connector_ID: 678)

ALTER TABLE KP_RGL ADD CONSTRAINT FK_KP_RGL_2 FOREIGN KEY (ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- ACTIVITEIT (many-to-many junction, Connector_ID: 678)

ALTER TABLE KP_RGLTKST ADD CONSTRAINT FK_KP_RGLTKST_1 FOREIGN KEY (REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- REGELTEKST (many-to-many junction, Connector_ID: 684)

ALTER TABLE KP_RGLTKST ADD CONSTRAINT FK_KP_RGLTKST_2 FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- LOCATIE (many-to-many junction, Connector_ID: 684)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_BOVENLIGGENDE_ACTIVITEIT FOREIGN KEY (BOVENLIGGENDE_ACTIVITEIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BOVENLIGGENDE_ACTIVITEIT (1 to 0..1, Connector_ID: 681)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_GERELATEERDE_ACTIVITEIT FOREIGN KEY (GERELATEERDE_ACTIVITEIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- GERELATEERDE_ACTIVITEIT (1 to 0..1, Connector_ID: 682)

ALTER TABLE JURIDISCHE_REGEL ADD CONSTRAINT FK_JURIDISCHE_REGEL_IS_OPGENOMEN_IN FOREIGN KEY (IS_OPGENOMEN_IN_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- IS_OPGENOMEN_IN (1..* to 1, Connector_ID: 683)

ALTER TABLE NORM ADD CONSTRAINT FK_NORM_BEVAT FOREIGN KEY (BEVAT_NORMWAARDE_ID) REFERENCES NORMWAARDE (NORMWAARDE_ID);
-- BEVAT (1 to 1..*, Connector_ID: 666)

ALTER TABLE REGELTEKST ADD CONSTRAINT FK_REGELTEKST_IS_GERELATEERD FOREIGN KEY (IS_GERELATEERD_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- IS_GERELATEERD (0..1 to 0..*, Connector_ID: 685)

ALTER TABLE REGELTEKST ADD CONSTRAINT FK_REGELTEKST_WERKINGSGEBIED FOREIGN KEY (WERKINGSGEBIED_REGELTEKST_ID) REFERENCES REGELTEKST (REGELTEKST_ID);
-- WERKINGSGEBIED (0..1 to 0..*, Connector_ID: 687)

