CREATE TABLE BEOORDELINGSOORT_ENUM (
    BEOORDELINGSOORT_ENUM_ID VARCHAR2(255) PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO BEOORDELINGSOORT_ENUM (BEOORDELINGSOORT_ENUM_ID, VALUE) VALUES
    (1, 'NIET_OKE'),
    (2, 'NIET_RELEVANT'),
    (3, 'OKE');

CREATE TABLE AANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        AFGEHANDELD NUMBER(1),
        CATEGORIE VARCHAR2(200),
        CATEGORIECODE VARCHAR2(80),
        DATUMAANMAAK DATE,
        DATUMAFHANDELING DATE,
        DATUMBEGINSTATUS DATE,
        DATUMEINDESTATUS DATE,
        HOOFDCATEGORIE VARCHAR2(80),
        HOOFDCATEGORIECODE VARCHAR2(80),
        IDENTIFICATIE VARCHAR2(255),
        KANAAL VARCHAR2(80),
        ONDERWERP VARCHAR2(200),
        ONDERWERPCODE VARCHAR2(80),
        SOORT VARCHAR2(80),
        STATUS VARCHAR2(80),
        STATUSCODE VARCHAR2(80),
        STATUSVOLGORDE VARCHAR2(80),
        SUBCATEGORIE VARCHAR2(200),
        SUBCATEGORIECODE VARCHAR2(80)
);

CREATE TABLE COMBIBON (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        SANCTIE VARCHAR2(255)
);

CREATE TABLE FIETSREGISTRATIE (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        GELABELD NUMBER(1),
        VERWIJDERD NUMBER(1)
);

CREATE TABLE FOTO (
    FOTO_ID VARCHAR2(255) PRIMARY KEY,
        BESTANDSGROOTTE NUMBER,
        BESTANDSNAAM VARCHAR2(200),
        BESTANDSTYPE VARCHAR2(80),
        DATUMTIJD TIMESTAMP,
        LOCATIE VARCHAR2(255),
        PIXELSX NUMBER,
        PIXELSY NUMBER
);

CREATE TABLE OBJECT (
    OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        DOMEIN VARCHAR2(200),
        GEOMETRIE SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(50),
        INDICATIERISICO VARCHAR2(255),
        KADASTRALEAANDUIDING VARCHAR2(255),
        NAAM VARCHAR2(200),
        OBJECTTYPE VARCHAR2(255),
        TOELICHTING VARCHAR2(255)
);

CREATE TABLE VTHMELDING (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY,
        ACTIVITEIT VARCHAR2(80),
        BEOORDELING_ENUM_ID VARCHAR2(255),
        DATUMSEPONERING DATE,
        DATUMTIJDTOT TIMESTAMP,
        GESEPONEERD NUMBER(1),
        HEEFT_FOTO_ID VARCHAR2(255),
        LOCATIE VARCHAR2(255),
        ORGANISATIEONDERDEEL VARCHAR2(80),
        OVERTREDINGSCODE VARCHAR2(20),
        OVERTREDINGSGROEP VARCHAR2(200),
        REFERENTIENUMMER VARCHAR2(80),
        RESULTAAT VARCHAR2(80),
        SOORTVTHMELDING VARCHAR2(80),
        STATUS VARCHAR2(255),
        STRAATNAAM VARCHAR2(255),
        TAAKTYPE VARCHAR2(80),
        ZAAKNUMMER VARCHAR2(20)
);

CREATE TABLE BOA (
    BOA_ID VARCHAR2(255) PRIMARY KEY,
        VERBALISANT_VTHMELDING_ID VARCHAR2(255)
);

CREATE TABLE KP_VTHMLDNG (
    KP_VTHMLDNG_ID VARCHAR2(255) PRIMARY KEY,
    VTHMELDING_ID VARCHAR2(255),
    OBJECT_ID VARCHAR2(255)
);

CREATE TABLE WAARNEMING (
    AANVRAAGOFMELDING_ID VARCHAR2(255) PRIMARY KEY
);

ALTER TABLE COMBIBON ADD CONSTRAINT FK_COMBIBON_GEN_VTHMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VTHMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VTHMELDING

ALTER TABLE FIETSREGISTRATIE ADD CONSTRAINT FK_FIETSREGISTRATIE_GEN_VTHMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VTHMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VTHMELDING

ALTER TABLE VTHMELDING ADD CONSTRAINT FK_VTHMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE WAARNEMING ADD CONSTRAINT FK_WAARNEMING_GEN_VTHMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES VTHMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to VTHMELDING

ALTER TABLE KP_VTHMLDNG ADD CONSTRAINT FK_KP_VTHMLDNG_1 FOREIGN KEY (VTHMELDING_ID) REFERENCES VTHMELDING (AANVRAAGOFMELDING_ID);
-- VTHMELDING (many-to-many junction, Connector_ID: 1297)

ALTER TABLE KP_VTHMLDNG ADD CONSTRAINT FK_KP_VTHMLDNG_2 FOREIGN KEY (OBJECT_ID) REFERENCES OBJECT (OBJECT_ID);
-- OBJECT (many-to-many junction, Connector_ID: 1297)

ALTER TABLE BOA ADD CONSTRAINT FK_BOA_VERBALISANT FOREIGN KEY (VERBALISANT_VTHMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- VERBALISANT (1 to 0..*, Connector_ID: 1326)

ALTER TABLE VTHMELDING ADD CONSTRAINT FK_VTHMELDING_BEOORDELING_ENUM_ID FOREIGN KEY (BEOORDELING_ENUM_ID) REFERENCES BEOORDELINGSOORT_ENUM (BEOORDELINGSOORT_ENUM_ID);
-- BEOORDELING_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VTHMELDING ADD CONSTRAINT FK_VTHMELDING_HEEFT FOREIGN KEY (HEEFT_FOTO_ID) REFERENCES FOTO (FOTO_ID);
-- HEEFT (0..1 to 0..*, Connector_ID: 1298)

