CREATE TABLE `BUURT_1043` (
    `BUURT_1043_ID` INT PRIMARY KEY,
        `BEGINGELDIGHEID` VARCHAR(255),
        `CODE` VARCHAR(255),
        `DATUMEINDE` DATE,
        `DATUMINGANG` DATE,
        `EINDGELDIGHEID` DATE,
        `GECONSTATEERD` BOOLEAN,
        `GEOMETRIE` GEOMETRY,
        `IDENTIFICATIE` VARCHAR(255),
        `NAAM` VARCHAR(255),
        `STATUS` VARCHAR(255),
        `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `BUURT_1186` (
    `BUURT_1186_ID` INT PRIMARY KEY,
        `BUURTCODE` VARCHAR(255),
        `BUURTGEOMETRIE` GEOMETRY,
        `BUURTNAAM` VARCHAR(255),
        `DATUMBEGINGELDIGHEIDBUURT` DATE,
        `DATUMEINDEGELDIGHEIDBUURT` DATE,
        `IDENTIFICATIE` VARCHAR(100),
        `IDENTIFICATIEIMGEOBRT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `INRICHTINGSELEMENT` (
    `INRICHTINGSELEMENT_ID` INT PRIMARY KEY,
        `DATUMBEGINGELDIGHEIDINRICHTINGSELEMENT` DATE,
        `DATUMEINDEGELDIGHEIDINRICHTINGSELEMENT` DATE,
        `GEOMETRIEINRICHTINGSELEMENT` GEOMETRY,
        `IDENTIFICATIEINRICHTINGSELEMENT` VARCHAR(255),
        `LOD0GEOMETRIEINRICHTINGSELEMENT` GEOMETRY,
        `PLUSTYPEINRICHTINGSELEMENT` VARCHAR(255),
        `RELATIEVEHOOGTELIGGINGINRICHTINGSELEMENT` VARCHAR(255),
        `STATUSINRICHTINGSELEMENT` VARCHAR(255),
        `TYPEINRICHTINGSELEMENT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KADASTRAALPERCEEL` (
    `OBJECT_ID` INT PRIMARY KEY,
        `AANDUIDINGSOORTGROOTTE` VARCHAR(255),
        `BEGRENZINGPERCEEL` VARCHAR(255),
        `GROOTTEPERCEEL` VARCHAR(255),
        `INDICATIEDEELPERCEEL` VARCHAR(255),
        `OMSCHRIJVINGDEELPERCEEL` VARCHAR(20),
        `PLAATSCOORDINATENPERCEEL` GEOMETRY
) ENGINE=InnoDB;

CREATE TABLE `KADASTRALEONROERENDEZAAK` (
    `OBJECT_ID` INT PRIMARY KEY,
        `APPARTEMENTSRECHTVOLGNUMMER` VARCHAR(255),
        `ATTRIBUTE` VARCHAR(255),
        `BEGRENZING` VARCHAR(255),
        `CULTUURCODEONBEBOUWD` VARCHAR(255),
        `DATUMBEGINGELDIGHEIDKADASTRALEONROERENDEZAAK` DATE,
        `DATUMEINDEGELDIGHEIDKADASTRALEONROERENDEZAAK` DATE,
        `GERELATEERD_KADASTRALEONROERENDEZAAK_ID` INT,
        `IDENTIFICATIE` VARCHAR(255),
        `KADASTRALEGEMEENTE` VARCHAR(20),
        `KADASTRALEGEMEENTECODE` VARCHAR(20),
        `KOOPJAAR` INT,
        `KOOPSOM` VARCHAR(255),
        `LANDINRICHTINGRENTEBEDRAG` DECIMAL(10,2),
        `LANDINRICHTINGRENTEEINDEJAAR` DATE,
        `LIGGING` VARCHAR(255),
        `LOCATIEOMSCHRIJVING` VARCHAR(255),
        `OPPERVLAKTE` INT,
        `OUD` VARCHAR(255),
        `PERCEELNUMMER` VARCHAR(255),
        `SECTIE` VARCHAR(255),
        `VALUTACODE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` (
    `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_ID` INT PRIMARY KEY,
    `IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID` INT,
    `IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_NTNTRLJKPRSN_NTRLJKPRSN` (
    `KP_NTNTRLJKPRSN_NTRLJKPRSN_ID` INT PRIMARY KEY,
    `NIETNATUURLIJKPERSOON_ID` INT,
    `NATUURLIJKPERSOON_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KUNSTWERKDEEL` (
    `KUNSTWERKDEEL_ID` INT PRIMARY KEY,
        `DATUMBEGINGELDIGHEIDKUNSTWERKDEEL` DATE,
        `DATUMEINDEGELDIGHEIDKUNSTWERKDEEL` DATE,
        `GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
        `IDENTIFICATIEKUNSTWERKDEEL` VARCHAR(255),
        `LOD0GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
        `LOD1GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
        `LOD2GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
        `LOD3GEOMETRIEKUNSTWERKDEEL` GEOMETRY,
        `RELATIEVEHOOGTELIGGINGKUNSTWERKDEEL` VARCHAR(255),
        `STATUSKUNSTWERKDEEL` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `LIGPLAATS_1045` (
    `LIGPLAATS_1045_ID` INT PRIMARY KEY,
        `BEGINGELDIGHEID` DATE,
        `DATUMEINDE` DATE,
        `DATUMINGANG` DATE,
        `DOCUMENTDATUM` DATE,
        `DOCUMENTNUMMER` INT,
        `EINDGELDIGHEID` DATE,
        `GECONSTATEERD` BOOLEAN,
        `GEOMETRIE` GEOMETRY,
        `IDENTIFICATIE` VARCHAR(255),
        `STATUS` VARCHAR(255),
        `VERSIE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `LIGPLAATS_1189` (
    `LIGPLAATS_1189_ID` INT PRIMARY KEY,
        `DATUMDOCUMENT` DATE,
        `DOCUMENTNUMMER` INT,
        `INDICATIEGECONSTATEERDELIGPLAATS` VARCHAR(255),
        `INONDERZOEK` BOOLEAN,
        `LIGPLAATSIDENTIFICATIE` VARCHAR(255),
        `LIGPLAATSSTATUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `MAATSCHAPPELIJKEACTIVITEIT` (
    `MAATSCHAPPELIJKEACTIVITEIT_ID` INT PRIMARY KEY,
        `ADRESBINNENLAND` VARCHAR(255),
        `ADRESCORRESPONDENTIE` VARCHAR(100),
        `DATUMAANVANG` DATE,
        `DATUMEINDEGELDIG` DATE,
        `DATUMFAILLISEMENT` DATE,
        `INDICATIEECONOMISCHACTIEF` VARCHAR(255),
        `IS_FUNCTIONARIS_VAN_NATUURLIJKPERSOON_ID` INT,
        `KVKNUMMER` VARCHAR(255),
        `RECHTSVORM` VARCHAR(100),
        `RSIN` VARCHAR(255),
        `STATUTAIRENAAM` VARCHAR(100),
        `TELEFOONNUMMER` VARCHAR(20),
        `URL` VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE `NATUURLIJKPERSOON` (
    `NATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON` VARCHAR(50),
        `AANDUIDINGNAAMGEBRUIK` VARCHAR(50),
        `AANHEFAANSCHRIJVING` VARCHAR(50),
        `ACADEMISCHETITEL` VARCHAR(80),
        `ACHTERNAAM` VARCHAR(100),
        `ADELLIJKETITELOFPREDIKAAT` VARCHAR(255),
        `ANUMMER` VARCHAR(20),
        `ATTRIBUTE` VARCHAR(255),
        `BURGERSERVICENUMMER` VARCHAR(255),
        `DATUMGEBOORTE` DATE,
        `DATUMOVERLIJDEN` DATE,
        `GEBOORTELAND` VARCHAR(255),
        `GEBOORTEPLAATS` VARCHAR(200),
        `GESLACHTSAANDUIDING` VARCHAR(255),
        `GESLACHTSNAAM` VARCHAR(200),
        `GESLACHTSNAAMAANSCHRIJVING` VARCHAR(200),
        `HANDLICHTING` VARCHAR(50),
        `INDICATIEAFSCHERMINGPERSOONSGEGEVENS` BOOLEAN,
        `INDICATIEOVERLEDEN` BOOLEAN,
        `LANDOVERLIJDEN` VARCHAR(255),
        `NATIONALITEIT` VARCHAR(100),
        `OVERLIJDENSPLAATS` VARCHAR(200),
        `VOORLETTERSAANSCHRIJVING` VARCHAR(20),
        `VOORNAMEN` VARCHAR(200),
        `VOORNAMENAANSCHRIJVING` VARCHAR(200),
        `VOORVOEGSELGESLACHTSNAAM` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `NIETNATUURLIJKPERSOON` (
    `NIETNATUURLIJKPERSOON_ID` INT PRIMARY KEY,
        `DATUMAANVANG` DATE,
        `DATUMEINDE` DATE,
        `DATUMUITSCHRIJVING` DATE,
        `DATUMVOORTZETTING` DATE,
        `FAXNUMMER` VARCHAR(20),
        `INGESCHREVEN` BOOLEAN,
        `INOPRICHTING` BOOLEAN,
        `KVKNUMMER` VARCHAR(255),
        `NNPID` VARCHAR(255),
        `RECHTSVORM` VARCHAR(255),
        `RSINNUMMER` VARCHAR(255),
        `STATUTAIRENAAM` VARCHAR(255),
        `STATUTAIREZETEL` VARCHAR(255),
        `WEBSITEURL` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `OBJECT` (
    `OBJECT_ID` INT PRIMARY KEY,
        `ADRESBINNENLAND` VARCHAR(255),
        `ADRESBUITENLAND` VARCHAR(255),
        `DOMEIN` VARCHAR(200),
        `GEOMETRIE` GEOMETRY,
        `IDENTIFICATIE` VARCHAR(50),
        `INDICATIERISICO` VARCHAR(255),
        `IS_BUURT_1043_ID` INT,
        `IS_BUURT_1186_ID` INT,
        `IS_INRICHTINGSELEMENT_ID` INT,
        `IS_KADASTRAALPERCEEL_ID` INT,
        `IS_KADASTRALEONROERENDEZAAK_ID` INT,
        `IS_KUNSTWERKDEEL_ID` INT,
        `IS_LIGPLAATS_1045_ID` INT,
        `IS_LIGPLAATS_1189_ID` INT,
        `IS_MAATSCHAPPELIJKEACTIVITEIT_ID` INT,
        `IS_NATUURLIJKPERSOON_ID` INT,
        `IS_NIETNATUURLIJKPERSOON_ID` INT,
        `IS_OPENBARERUIMTE_1047_ID` INT,
        `IS_OPENBARERUIMTE_1191_ID` INT,
        `IS_PAND_1048_ID` INT,
        `IS_PAND_1192_ID` INT,
        `IS_STANDPLAATS_1049_ID` INT,
        `IS_STANDPLAATS_1193_ID` INT,
        `IS_VAARTUIG_ID` INT,
        `IS_VOERTUIG_ID` INT,
        `IS_WATERDEEL_ID` INT,
        `KADASTRALEAANDUIDING` VARCHAR(255),
        `NAAM` VARCHAR(200),
        `OBJECTTYPE` VARCHAR(255),
        `TOELICHTING` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `OPENBARERUIMTE_1047` (
    `OPENBARERUIMTE_1047_ID` INT PRIMARY KEY,
        `BEGINGELDIGHEID` VARCHAR(255),
        `DATUMEINDE` DATE,
        `DATUMINGANG` DATE,
        `DOCUMENTDATUM` DATE,
        `DOCUMENTNUMMER` INT,
        `EINDGELDIGHEID` DATE,
        `GECONSTATEERD` BOOLEAN,
        `GEOMETRIE` GEOMETRY,
        `HUISNUMMERRANGE_EVEN_EN_ONEVEN_NUMMERS` VARCHAR(255),
        `HUISNUMMERRANGE_EVEN_NUMMERS` VARCHAR(255),
        `HUISNUMMERRANGE_ONEVEN_NUMMERS` VARCHAR(255),
        `IDENTIFICATIE` VARCHAR(255),
        `LABELNAAM` VARCHAR(80),
        `LIGT_IN_BUURT_1043_ID` INT,
        `LIGT_IN_BUURT_1186_ID` INT,
        `NAAMOPENBARERUIMTE` VARCHAR(80),
        `STATUS` VARCHAR(255),
        `STRAATCODE` VARCHAR(80),
        `STRAATNAAM` VARCHAR(255),
        `TYPEOPENBARERUIMTE` VARCHAR(255),
        `VERSIE` INT,
        `WEGSEGMENT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `OPENBARERUIMTE_1191` (
    `OPENBARERUIMTE_1191_ID` INT PRIMARY KEY,
        `DATUMBEGINGELDIGHEIDOPENBARERUIMTE` DATE,
        `DATUMEINDEGELDIGHEIDOPENBARERUIMTE` DATE,
        `HUISNUMMERRANGEEVENENONEVENNUMMERS` VARCHAR(255),
        `HUISNUMMERRANGEEVENNUMMERS` VARCHAR(255),
        `HUISNUMMERRANGEONEVENNUMMERS` VARCHAR(255),
        `IDENTIFICATIECODEOPENBARERUIMTE` VARCHAR(255),
        `IDENTIFICATIEIMGEOOPR` VARCHAR(255),
        `INDICATIEGECONSTATEERDEOPENBARERUIMTE` VARCHAR(255),
        `INONDERZOEK` BOOLEAN,
        `LABELNAAMOPENBARERUIMTE` VARCHAR(255),
        `NAAMOPENBARERUIMTE` VARCHAR(80),
        `OPENBARERUIMTEGEOMETRIE` GEOMETRY,
        `STATUSOPENBARERUIMTE` VARCHAR(255),
        `STRAATNAAM` VARCHAR(255),
        `TYPEOPENBARERUIMTE` VARCHAR(255),
        `WEGSEGMENT` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `PAND_1048` (
    `PAND_1048_ID` INT PRIMARY KEY,
        `BEGINGELDIGHEID` VARCHAR(255),
        `BRUTOINHOUDPAND` VARCHAR(255),
        `DATUMEINDE` DATE,
        `DATUMINGANG` DATE,
        `DOCUMENTDATUM` DATE,
        `DOCUMENTNUMMER` VARCHAR(255),
        `EINDGELDIGHEID` DATE,
        `GECONSTATEERD` BOOLEAN,
        `GEOMETRIEBOVENAANZICHT` GEOMETRY,
        `GEOMETRIEMAAIVELD` GEOMETRY,
        `GEOMETRIEPUNT` GEOMETRY,
        `HOOGSTEBOUWLAAG` VARCHAR(255),
        `IDENTIFICATIE` VARCHAR(255),
        `LAAGSTEBOUWLAAG` VARCHAR(255),
        `OORSPRONKELIJKBOUWJAAR` VARCHAR(255),
        `OPPERVLAKTE` VARCHAR(255),
        `RELATIEVEHOOGTELIGGING` VARCHAR(255),
        `STATUS` VARCHAR(255),
        `STATUSVOORTGANGBOUW` VARCHAR(255),
        `VERSIE` INT,
        `ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_1043_ID` INT,
        `ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_1186_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `PAND_1192` (
    `PAND_1192_ID` INT PRIMARY KEY,
        `BRUTOINHOUDPAND` VARCHAR(255),
        `DATUMBEGINGELDIGHEIDPAND` DATE,
        `DATUMEINDEGELDIGHEIDPAND` DATE,
        `GEOMETRIEPUNT` GEOMETRY,
        `HOOGSTEBOUWLAAGPAND` VARCHAR(255),
        `IDENTIFICATIEBGTPND` VARCHAR(255),
        `INDICATIEGECONSTATEERDPAND` VARCHAR(255),
        `INDICATIEPLANOBJECT` VARCHAR(255),
        `INWINNINGGEOMETRIEBOVENAANZICHT` GEOMETRY,
        `INWINNINGGEOMETRIEMAAIVELD` GEOMETRY,
        `LAAGSTEBOUWLAAGPAND` VARCHAR(255),
        `LABELNUMMERAANDUIDINGREEKS` VARCHAR(255),
        `LOD1GEOMETRIEPAND` GEOMETRY,
        `LOD2GEOMETRIEPAND` GEOMETRY,
        `LOD3GEOMETRIEPAND` GEOMETRY,
        `OORSPRONKELIJKBOUWJAARPAND` VARCHAR(255),
        `OPPERVLAKTEPAND` VARCHAR(255),
        `PANDGEOMETRIEBOVENAANZICHT` GEOMETRY,
        `PANDGEOMETRIEMAAIVELD` GEOMETRY,
        `PANDIDENTIFICATIE` VARCHAR(255),
        `PANDSTATUS` VARCHAR(255),
        `RELATIEVEHOOGTELIGGINGPAND` VARCHAR(255),
        `STATUSVOORTGANGBOUW` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `STANDPLAATS_1049` (
    `STANDPLAATS_1049_ID` INT PRIMARY KEY,
        `DATUM_BEGIN_GELDIGHEID` DATE,
        `DATUM_EINDE` DATE,
        `DATUM_EINDE_GELDIGHEID` DATE,
        `DATUM_INGANG` DATE,
        `DOCUMENTDATUM` DATE,
        `DOCUMENTNUMMER` INT,
        `GECONSTATEERD` BOOLEAN,
        `GEOMETRIE` GEOMETRY,
        `IDENTIFICATIE` VARCHAR(255),
        `STATUS` VARCHAR(255),
        `VERSIE` INT
) ENGINE=InnoDB;

CREATE TABLE `STANDPLAATS_1193` (
    `STANDPLAATS_1193_ID` INT PRIMARY KEY,
        `INDICATIEGECONSTATEERDESTANDPLAATS` VARCHAR(255),
        `STANDPLAATSIDENTIFICATIE` VARCHAR(255),
        `STANDPLAATSSTATUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `VAARTUIG` (
    `VAARTUIG_ID` INT PRIMARY KEY,
        `BREEDTE` INT,
        `HOOGTE` INT,
        `KLEUR` VARCHAR(20),
        `LENGTE` INT,
        `NAAMVAARTUIG` VARCHAR(255),
        `REGISTRATIENUMMER` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `VOERTUIG` (
    `VOERTUIG_ID` INT PRIMARY KEY,
        `KENTEKEN` VARCHAR(255),
        `KLEUR` VARCHAR(200),
        `LAND` VARCHAR(200),
        `MERK` VARCHAR(200),
        `TYPE` VARCHAR(200)
) ENGINE=InnoDB;

CREATE TABLE `WATERDEEL` (
    `WATERDEEL_ID` INT PRIMARY KEY,
        `DATUMBEGINGELDIGHEIDWATERDEEL` DATE,
        `DATUMEINDEGELDIGHEIDWATERDEEL` DATE,
        `GEOMETRIEWATERDEEL` GEOMETRY,
        `IDENTIFICATIEWATERDEEL` VARCHAR(255),
        `PLUSTYPEWATERDEEL` VARCHAR(255),
        `RELATIEVEHOOGTELIGGINGWATERDEEL` VARCHAR(255),
        `STATUSWATERDEEL` VARCHAR(255),
        `TYPEWATERDEEL` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `KADASTRAALPERCEEL` ADD CONSTRAINT FK_KADASTRAALPERCEEL_GEN_KADASTRALEONROERENDEZAAK FOREIGN KEY (`OBJECT_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`OBJECT_ID`);
-- Generalization to KADASTRALEONROERENDEZAAK

ALTER TABLE `KADASTRALEONROERENDEZAAK` ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GEN_OBJECT FOREIGN KEY (`OBJECT_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- Generalization to OBJECT

ALTER TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_1 FOREIGN KEY (`IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_1_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`OBJECT_ID`);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 178)

ALTER TABLE `KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ` ADD CONSTRAINT FK_KP_KDSTRLNRRNDZK_IS_ONTSTN_UIT_ANDR_KDSTRL_ONRZ_ZK_BIJ_2 FOREIGN KEY (`IS_ONTSTAAN_UIT_ANDERE_KADASTRALE_ONROERENDE_ZAAK_BIJ_2_ID`) REFERENCES `KADASTRALEONROERENDEZAAK` (`OBJECT_ID`);
-- KADASTRALEONROERENDEZAAK (many-to-many junction, Connector_ID: 178)

ALTER TABLE `KP_NTNTRLJKPRSN_NTRLJKPRSN` ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_1 FOREIGN KEY (`NIETNATUURLIJKPERSOON_ID`) REFERENCES `NIETNATUURLIJKPERSOON` (`NIETNATUURLIJKPERSOON_ID`);
-- NIETNATUURLIJKPERSOON (many-to-many junction, Connector_ID: 152)

ALTER TABLE `KP_NTNTRLJKPRSN_NTRLJKPRSN` ADD CONSTRAINT FK_KP_NTNTRLJKPRSN_NTRLJKPRSN_2 FOREIGN KEY (`NATUURLIJKPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 152)

ALTER TABLE `KADASTRALEONROERENDEZAAK` ADD CONSTRAINT FK_KADASTRALEONROERENDEZAAK_GERELATEERD FOREIGN KEY (`GERELATEERD_KADASTRALEONROERENDEZAAK_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- GERELATEERD (1 to 0..*, Connector_ID: 181)

ALTER TABLE `MAATSCHAPPELIJKEACTIVITEIT` ADD CONSTRAINT FK_MAATSCHAPPELIJKEACTIVITEIT_IS_FUNCTIONARIS_VAN FOREIGN KEY (`IS_FUNCTIONARIS_VAN_NATUURLIJKPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- IS_FUNCTIONARIS_VAN (0..* to 1.., Connector_ID: 164)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS FOREIGN KEY (`IS_NATUURLIJKPERSOON_ID`) REFERENCES `NATUURLIJKPERSOON` (`NATUURLIJKPERSOON_ID`);
-- IS (0..1 to 0..*, Connector_ID: 253)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_10 FOREIGN KEY (`IS_PAND_1192_ID`) REFERENCES `PAND_1192` (`PAND_1192_ID`);
-- IS (0..1 to 0..*, Connector_ID: 263)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_11 FOREIGN KEY (`IS_INRICHTINGSELEMENT_ID`) REFERENCES `INRICHTINGSELEMENT` (`INRICHTINGSELEMENT_ID`);
-- IS (0..1 to 0..*, Connector_ID: 266)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_12 FOREIGN KEY (`IS_NIETNATUURLIJKPERSOON_ID`) REFERENCES `NIETNATUURLIJKPERSOON` (`NIETNATUURLIJKPERSOON_ID`);
-- IS (0..1 to 0..*, Connector_ID: 267)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_13 FOREIGN KEY (`IS_MAATSCHAPPELIJKEACTIVITEIT_ID`) REFERENCES `MAATSCHAPPELIJKEACTIVITEIT` (`MAATSCHAPPELIJKEACTIVITEIT_ID`);
-- IS (0..1 to 0..*, Connector_ID: 268)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_14 FOREIGN KEY (`IS_STANDPLAATS_1049_ID`) REFERENCES `STANDPLAATS_1049` (`STANDPLAATS_1049_ID`);
-- IS (0..1 to 0..*, Connector_ID: 323)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_15 FOREIGN KEY (`IS_PAND_1048_ID`) REFERENCES `PAND_1048` (`PAND_1048_ID`);
-- IS (0..1 to 0..*, Connector_ID: 326)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_16 FOREIGN KEY (`IS_OPENBARERUIMTE_1047_ID`) REFERENCES `OPENBARERUIMTE_1047` (`OPENBARERUIMTE_1047_ID`);
-- IS (0..1 to 0..*, Connector_ID: 330)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_17 FOREIGN KEY (`IS_LIGPLAATS_1045_ID`) REFERENCES `LIGPLAATS_1045` (`LIGPLAATS_1045_ID`);
-- IS (0..1 to 0..*, Connector_ID: 337)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_18 FOREIGN KEY (`IS_BUURT_1043_ID`) REFERENCES `BUURT_1043` (`BUURT_1043_ID`);
-- IS (0..1 to 0..*, Connector_ID: 344)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_19 FOREIGN KEY (`IS_VOERTUIG_ID`) REFERENCES `VOERTUIG` (`VOERTUIG_ID`);
-- IS (0..1 to 0..1, Connector_ID: 1269)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_2 FOREIGN KEY (`IS_BUURT_1186_ID`) REFERENCES `BUURT_1186` (`BUURT_1186_ID`);
-- IS (0..1 to 0..*, Connector_ID: 254)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_20 FOREIGN KEY (`IS_VAARTUIG_ID`) REFERENCES `VAARTUIG` (`VAARTUIG_ID`);
-- IS (0..1 to 0..1, Connector_ID: 1304)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_3 FOREIGN KEY (`IS_OPENBARERUIMTE_1191_ID`) REFERENCES `OPENBARERUIMTE_1191` (`OPENBARERUIMTE_1191_ID`);
-- IS (0..1 to 0..*, Connector_ID: 255)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_4 FOREIGN KEY (`IS_KUNSTWERKDEEL_ID`) REFERENCES `KUNSTWERKDEEL` (`KUNSTWERKDEEL_ID`);
-- IS (0..1 to 0..*, Connector_ID: 256)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_5 FOREIGN KEY (`IS_LIGPLAATS_1189_ID`) REFERENCES `LIGPLAATS_1189` (`LIGPLAATS_1189_ID`);
-- IS (0..1 to 0..*, Connector_ID: 257)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_6 FOREIGN KEY (`IS_KADASTRALEONROERENDEZAAK_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- IS (0..1 to 0..*, Connector_ID: 258)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_7 FOREIGN KEY (`IS_STANDPLAATS_1193_ID`) REFERENCES `STANDPLAATS_1193` (`STANDPLAATS_1193_ID`);
-- IS (0..1 to 0..*, Connector_ID: 259)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_8 FOREIGN KEY (`IS_KADASTRALEONROERENDEZAAK_ID`) REFERENCES `OBJECT` (`OBJECT_ID`);
-- IS (0..1 to 0..*, Connector_ID: 261)

ALTER TABLE `OBJECT` ADD CONSTRAINT FK_OBJECT_IS_9 FOREIGN KEY (`IS_WATERDEEL_ID`) REFERENCES `WATERDEEL` (`WATERDEEL_ID`);
-- IS (0..1 to 0..*, Connector_ID: 262)

ALTER TABLE `OPENBARERUIMTE_1047` ADD CONSTRAINT FK_OPENBARERUIMTE_1047_LIGT_IN FOREIGN KEY (`LIGT_IN_BUURT_1043_ID`) REFERENCES `BUURT_1043` (`BUURT_1043_ID`);
-- LIGT_IN (1 to 1..*, Connector_ID: 343)

ALTER TABLE `OPENBARERUIMTE_1047` ADD CONSTRAINT FK_OPENBARERUIMTE_1047_LIGT_IN_2 FOREIGN KEY (`LIGT_IN_BUURT_1186_ID`) REFERENCES `BUURT_1186` (`BUURT_1186_ID`);
-- LIGT_IN (1 to 1, Connector_ID: 1501)

ALTER TABLE `PAND_1048` ADD CONSTRAINT FK_PAND_1048_ZONDER_VERBLIJFSOBJECT_LIGT_IN FOREIGN KEY (`ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_1043_ID`) REFERENCES `BUURT_1043` (`BUURT_1043_ID`);
-- ZONDER_VERBLIJFSOBJECT_LIGT_IN (0..* to 0..1, Connector_ID: 342)

ALTER TABLE `PAND_1048` ADD CONSTRAINT FK_PAND_1048_ZONDER_VERBLIJFSOBJECT_LIGT_IN_2 FOREIGN KEY (`ZONDER_VERBLIJFSOBJECT_LIGT_IN_BUURT_1186_ID`) REFERENCES `BUURT_1186` (`BUURT_1186_ID`);
-- ZONDER_VERBLIJFSOBJECT_LIGT_IN (0..* to 0..1, Connector_ID: 1499)

