CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        ADRESCORRESPONDENTIE VARCHAR2(100),
        EMAILADRES VARCHAR2(80),
        FAXNUMMER VARCHAR2(20),
        IDENTIFICATIE VARCHAR2(255),
        KVKNUMMER VARCHAR2(20),
        NAAM VARCHAR2(200),
        RECHTSVORM VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE EIGENAAR (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE HUURDER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200),
        NUMMER VARCHAR2(255)
);

CREATE TABLE PACHTER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY
);

ALTER TABLE EIGENAAR ADD CONSTRAINT FK_EIGENAAR_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE HUURDER ADD CONSTRAINT FK_HUURDER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE PACHTER ADD CONSTRAINT FK_PACHTER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

