CREATE TABLE PRODUCTGROEP (
    PRODUCTGROEP_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(80),
    OMSCHRIJVING CLOB
);

CREATE TABLE LEVERANCIER (
    LEVERANCIER_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(200),
    NUMMER VARCHAR2(255)
);

CREATE TABLE OMZETGROEP (
    OMZETGROEP_ID NUMBER PRIMARY KEY,
    NAAM VARCHAR2(80),
    OMSCHRIJVING CLOB
);

CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    CODEMUSEUMJAARKAART VARCHAR2(255),
    DATUMEINDEGELDIGHEID DATE,
    DATUMSTART DATE,
    ENTREEKAART NUMBER,
    LEVERANCIER_LEVERANCIER_ID NUMBER,
    OMSCHRIJVING VARCHAR2(80),
    PRIJS NUMBER(10,2)
);

CREATE TABLE WINKELVOORRAADITEM (
    WINKELVOORRAADITEM_ID NUMBER PRIMARY KEY,
    AANTAL NUMBER,
    AANTALINBESTELLING NUMBER,
    BETREFT_PRODUCT_ID NUMBER,
    DATUMLEVERINGBESTELLING DATE,
    LOCATIE VARCHAR2(80)
);

CREATE TABLE KP_PRDCT_OMZTGRP (
    KP_PRDCT_OMZTGRP_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    OMZETGROEP_ID NUMBER
);

CREATE TABLE ENTREEKAART (
    PRODUCT_ID NUMBER PRIMARY KEY,
    RONDLEIDING NUMBER(1)
);

CREATE TABLE BALIEVERKOOP (
    BALIEVERKOOP_ID NUMBER PRIMARY KEY,
    AANTAL NUMBER,
    BETREFT_PRODUCT_ID NUMBER,
    KANAAL VARCHAR2(80),
    VERKOOPTIJD TIMESTAMP
);

CREATE TABLE KP_PRDCT_PRDCTGRP (
    KP_PRDCT_PRDCTGRP_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCTGROEP_ID NUMBER
);

CREATE TABLE BALIEVERKOOP_ENTREEKAART (
    BALIEVERKOOP_ID NUMBER PRIMARY KEY,
    DATUMEINDEGELDIGHEID DATE,
    DATUMSTART DATE,
    GEBRUIKTOP VARCHAR2(255),
    RONDLEIDING NUMBER(1)
);

ALTER TABLE BALIEVERKOOP_ENTREEKAART ADD CONSTRAINT FK_BALIEVERKOOP_ENTREEKAART_GEN_BALIEVERKOOP FOREIGN KEY (BALIEVERKOOP_ID) REFERENCES BALIEVERKOOP (BALIEVERKOOP_ID);
-- Generalization to BALIEVERKOOP

ALTER TABLE ENTREEKAART ADD CONSTRAINT FK_ENTREEKAART_GEN_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- Generalization to PRODUCT

ALTER TABLE KP_PRDCT_PRDCTGRP ADD CONSTRAINT FK_KP_PRDCT_PRDCTGRP_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- PRODUCT (many-to-many junction, Connector_ID: 1112)

ALTER TABLE KP_PRDCT_PRDCTGRP ADD CONSTRAINT FK_KP_PRDCT_PRDCTGRP_2 FOREIGN KEY (PRODUCTGROEP_ID) REFERENCES PRODUCTGROEP (PRODUCTGROEP_ID);
-- PRODUCTGROEP (many-to-many junction, Connector_ID: 1112)

ALTER TABLE KP_PRDCT_OMZTGRP ADD CONSTRAINT FK_KP_PRDCT_OMZTGRP_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- PRODUCT (many-to-many junction, Connector_ID: 1114)

ALTER TABLE KP_PRDCT_OMZTGRP ADD CONSTRAINT FK_KP_PRDCT_OMZTGRP_2 FOREIGN KEY (OMZETGROEP_ID) REFERENCES OMZETGROEP (OMZETGROEP_ID);
-- OMZETGROEP (many-to-many junction, Connector_ID: 1114)

ALTER TABLE WINKELVOORRAADITEM ADD CONSTRAINT FK_WINKELVOORRAADITEM_BETREFT FOREIGN KEY (BETREFT_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- BETREFT (0..1 to 1, Connector_ID: 1110)

ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_LEVERANCIER FOREIGN KEY (LEVERANCIER_LEVERANCIER_ID) REFERENCES LEVERANCIER (LEVERANCIER_ID);
-- LEVERANCIER (0..* to 0..1, Connector_ID: 1111)

ALTER TABLE BALIEVERKOOP ADD CONSTRAINT FK_BALIEVERKOOP_BETREFT FOREIGN KEY (BETREFT_PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);
-- BETREFT (0..* to 1, Connector_ID: 1133)

