CREATE TABLE [PERIODE] (
    [PERIODE_ID] INT PRIMARY KEY,
    [DATUMEINDE] DATE,
    [DATUMSTART] DATE,
    [OMSCHRIJVING] VARCHAR(255)
);

CREATE TABLE [INDEX] (
    [INDEX_ID] INT PRIMARY KEY,
    [INDEXNAAM] VARCHAR(80),
    [INDEXWAARDE] VARCHAR(80)
);

CREATE TABLE [RECHTHEBBENDE] (
    [RECHTHEBBENDE_ID] INT PRIMARY KEY
);

CREATE TABLE [ORDENINGSSCHEMA] (
    [ORDENINGSSCHEMA_ID] INT PRIMARY KEY,
    [NAAM] VARCHAR(80),
    [TEXT] NVARCHAR(MAX)
);

CREATE TABLE [ARCHIEFCATEGORIE] (
    [ARCHIEFCATEGORIE_ID] INT PRIMARY KEY,
    [NAAM] VARCHAR(80),
    [NUMMER] VARCHAR(20),
    [OMSCHRIJVING] NVARCHAR(MAX)
);

CREATE TABLE [NADERE_TOEGANG] (
    [NADERE_TOEGANG_ID] INT PRIMARY KEY,
    [WORDT_BESCHREVEN_INDEX_ID] INT
);

CREATE TABLE [ARCHIEF] (
    [ARCHIEF_ID] INT PRIMARY KEY,
    [ARCHIEFNUMMER] VARCHAR(20),
    [HEEFT_RECHTHEBBENDE_ID] INT,
    [NAAM] VARCHAR(80),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [OPENBAARHEIDSBEPERKING] INT
);

CREATE TABLE [KP_ARCHF_ARCHFCTGR] (
    [KP_ARCHF_ARCHFCTGR_ID] INT PRIMARY KEY,
    [ARCHIEF_ID] INT,
    [ARCHIEFCATEGORIE_ID] INT
);

CREATE TABLE [ARCHIEFSTUK] (
    [ARCHIEFSTUK_ID] INT PRIMARY KEY,
    [BESCHRIJVING] NVARCHAR(MAX),
    [HEEFT_NADERE_TOEGANG_ID] INT,
    [INVENTARISNUMMER] VARCHAR(20),
    [IS_ONDERDEEL_VAN_ARCHIEF_ID] INT,
    [OMVANG] VARCHAR(255),
    [OPENBAARHEIDSBEPERKING] BIT,
    [TREFWOORDEN] VARCHAR(200),
    [UITERLIJKEVORM] VARCHAR(255)
);

CREATE TABLE [KP_ARCHF_PRD] (
    [KP_ARCHF_PRD_ID] INT PRIMARY KEY,
    [ARCHIEF_ID] INT,
    [PERIODE_ID] INT
);

CREATE TABLE [INDELING] (
    [INDELING_ID] INT PRIMARY KEY,
    [HOORT_BIJ_ARCHIEF_ID] INT,
    [INDELINGSOORT] VARCHAR(20),
    [NAAM] VARCHAR(80),
    [NUMMER] VARCHAR(20),
    [OMSCHRIJVING] NVARCHAR(MAX),
    [VALT_BINNEN_ARCHIEFSTUK_ID] INT,
    [VALT_BINNEN_INDELING_ID] INT
);

CREATE TABLE [KP_ARCHFSTK_ORDNNGSSCHM] (
    [KP_ARCHFSTK_ORDNNGSSCHM_ID] INT PRIMARY KEY,
    [ARCHIEFSTUK_ID] INT,
    [ORDENINGSSCHEMA_ID] INT
);

CREATE TABLE [KP_ARCHFSTK_PRD] (
    [KP_ARCHFSTK_PRD_ID] INT PRIMARY KEY,
    [ARCHIEFSTUK_ID] INT,
    [PERIODE_ID] INT
);

ALTER TABLE [KP_ARCHFSTK_PRD] ADD CONSTRAINT FK_KP_ARCHFSTK_PRD_1 FOREIGN KEY ([ARCHIEFSTUK_ID]) REFERENCES [ARCHIEFSTUK] ([ARCHIEFSTUK_ID]);
-- ARCHIEFSTUK (many-to-many junction, Connector_ID: 1171)

ALTER TABLE [KP_ARCHFSTK_PRD] ADD CONSTRAINT FK_KP_ARCHFSTK_PRD_2 FOREIGN KEY ([PERIODE_ID]) REFERENCES [PERIODE] ([PERIODE_ID]);
-- PERIODE (many-to-many junction, Connector_ID: 1171)

ALTER TABLE [KP_ARCHFSTK_ORDNNGSSCHM] ADD CONSTRAINT FK_KP_ARCHFSTK_ORDNNGSSCHM_1 FOREIGN KEY ([ARCHIEFSTUK_ID]) REFERENCES [ARCHIEFSTUK] ([ARCHIEFSTUK_ID]);
-- ARCHIEFSTUK (many-to-many junction, Connector_ID: 1173)

ALTER TABLE [KP_ARCHFSTK_ORDNNGSSCHM] ADD CONSTRAINT FK_KP_ARCHFSTK_ORDNNGSSCHM_2 FOREIGN KEY ([ORDENINGSSCHEMA_ID]) REFERENCES [ORDENINGSSCHEMA] ([ORDENINGSSCHEMA_ID]);
-- ORDENINGSSCHEMA (many-to-many junction, Connector_ID: 1173)

ALTER TABLE [KP_ARCHF_PRD] ADD CONSTRAINT FK_KP_ARCHF_PRD_1 FOREIGN KEY ([ARCHIEF_ID]) REFERENCES [ARCHIEF] ([ARCHIEF_ID]);
-- ARCHIEF (many-to-many junction, Connector_ID: 1181)

ALTER TABLE [KP_ARCHF_PRD] ADD CONSTRAINT FK_KP_ARCHF_PRD_2 FOREIGN KEY ([PERIODE_ID]) REFERENCES [PERIODE] ([PERIODE_ID]);
-- PERIODE (many-to-many junction, Connector_ID: 1181)

ALTER TABLE [KP_ARCHF_ARCHFCTGR] ADD CONSTRAINT FK_KP_ARCHF_ARCHFCTGR_1 FOREIGN KEY ([ARCHIEF_ID]) REFERENCES [ARCHIEF] ([ARCHIEF_ID]);
-- ARCHIEF (many-to-many junction, Connector_ID: 1183)

ALTER TABLE [KP_ARCHF_ARCHFCTGR] ADD CONSTRAINT FK_KP_ARCHF_ARCHFCTGR_2 FOREIGN KEY ([ARCHIEFCATEGORIE_ID]) REFERENCES [ARCHIEFCATEGORIE] ([ARCHIEFCATEGORIE_ID]);
-- ARCHIEFCATEGORIE (many-to-many junction, Connector_ID: 1183)

ALTER TABLE [NADERE_TOEGANG] ADD CONSTRAINT FK_NADERE_TOEGANG_WORDT_BESCHREVEN FOREIGN KEY ([WORDT_BESCHREVEN_INDEX_ID]) REFERENCES [INDEX] ([INDEX_ID]);
-- WORDT_BESCHREVEN (1 to 1..*, Connector_ID: 1164)

ALTER TABLE [INDELING] ADD CONSTRAINT FK_INDELING_VALT_BINNEN FOREIGN KEY ([VALT_BINNEN_INDELING_ID]) REFERENCES [INDELING] ([INDELING_ID]);
-- VALT_BINNEN (1 to 0..*, Connector_ID: 1165)

ALTER TABLE [INDELING] ADD CONSTRAINT FK_INDELING_VALT_BINNEN_2 FOREIGN KEY ([VALT_BINNEN_ARCHIEFSTUK_ID]) REFERENCES [ARCHIEFSTUK] ([ARCHIEFSTUK_ID]);
-- VALT_BINNEN (0..1 to 0..*, Connector_ID: 1170)

ALTER TABLE [ARCHIEFSTUK] ADD CONSTRAINT FK_ARCHIEFSTUK_HEEFT FOREIGN KEY ([HEEFT_NADERE_TOEGANG_ID]) REFERENCES [NADERE_TOEGANG] ([NADERE_TOEGANG_ID]);
-- HEEFT (1 to 0..1, Connector_ID: 1172)

ALTER TABLE [INDELING] ADD CONSTRAINT FK_INDELING_HOORT_BIJ FOREIGN KEY ([HOORT_BIJ_ARCHIEF_ID]) REFERENCES [ARCHIEF] ([ARCHIEF_ID]);
-- HOORT_BIJ (0..* to 1, Connector_ID: 1179)

ALTER TABLE [ARCHIEFSTUK] ADD CONSTRAINT FK_ARCHIEFSTUK_IS_ONDERDEEL_VAN FOREIGN KEY ([IS_ONDERDEEL_VAN_ARCHIEF_ID]) REFERENCES [ARCHIEF] ([ARCHIEF_ID]);
-- IS_ONDERDEEL_VAN (0..* to 1, Connector_ID: 1180)

ALTER TABLE [ARCHIEF] ADD CONSTRAINT FK_ARCHIEF_HEEFT FOREIGN KEY ([HEEFT_RECHTHEBBENDE_ID]) REFERENCES [RECHTHEBBENDE] ([RECHTHEBBENDE_ID]);
-- HEEFT (0..* to 0..1, Connector_ID: 1182)

