CREATE TABLE DOCUMENTTYPE (
    DOCUMENTTYPE_ID NUMBER PRIMARY KEY,
    DATUMBEGINGELDIGHEIDDOCUMENTTYPE DATE,
    DATUMEINDEGELDIGHEIDDOCUMENTTYPE DATE,
    DOCUMENTCATEGORIE VARCHAR2(80),
    DOCUMENTTYPEOMSCHRIJVING VARCHAR2(80),
    DOCUMENTTYPEOMSCHRIJVINGGENERIEK VARCHAR2(80),
    DOCUMENTTYPETREFWOORD VARCHAR2(255)
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    EMAILADRES VARCHAR2(80),
    FAXNUMMER VARCHAR2(20),
    IDENTIFICATIE VARCHAR2(255),
    KVKNUMMER VARCHAR2(20),
    NAAM VARCHAR2(200),
    RECHTSVORM VARCHAR2(100),
    REKENINGNUMMER VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE IDENTIFICATIEKENMERK (
    IDENTIFICATIEKENMERK_ID NUMBER PRIMARY KEY,
    KENMERK VARCHAR2(20)
);

CREATE TABLE UITGEVER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY
);

CREATE TABLE RECHTHEBBENDE (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY
);

CREATE TABLE NATUURLIJKPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
    AANHEFAANSCHRIJVING VARCHAR2(50),
    ACADEMISCHETITEL VARCHAR2(80),
    ACHTERNAAM VARCHAR2(100),
    ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
    ANUMMER VARCHAR2(20),
    BIJZONDERNEDERLANDERSCHAP VARCHAR2(50),
    BURGERSERVICENUMMER VARCHAR2(255),
    DATUMGEBOORTE DATE,
    DATUMOVERLIJDEN DATE,
    GEBOORTELAND VARCHAR2(255),
    GEBOORTEPLAATS VARCHAR2(200),
    GESLACHTSAANDUIDING VARCHAR2(255),
    GESLACHTSNAAM VARCHAR2(200),
    GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
    HANDLICHTING VARCHAR2(50),
    INDICATIEAFSCHERMINGPERSOONSGEGEVENS NUMBER(1),
    INDICATIEOVERLEDEN NUMBER(1),
    LANDOVERLIJDEN VARCHAR2(255),
    NATIONALITEIT VARCHAR2(100),
    OVERLIJDENSPLAATS VARCHAR2(200),
    VOORLETTERSAANSCHRIJVING VARCHAR2(20),
    VOORNAMEN VARCHAR2(200),
    VOORNAMENAANSCHRIJVING VARCHAR2(200),
    VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE BEZOEKER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    COCUMENTBESCHRIJVING VARCHAR2(255),
    DATUMCREATIEDOCUMENT DATE,
    DATUMONTVANGSTDOCUMENT DATE,
    DATUMVERZENDINGDOCUMENT DATE,
    DOCUMENTAUTEUR VARCHAR2(200),
    DOCUMENTIDENTIFICATIE VARCHAR2(255),
    DOCUMENTTITEL VARCHAR2(200),
    HEEFT_KENMERK_IDENTIFICATIEKENMERK_ID NUMBER,
    IS_VAN_DOCUMENTTYPE_ID NUMBER,
    VERTROUWELIJKAANDUIDING VARCHAR2(20)
);

ALTER TABLE BEZOEKER ADD CONSTRAINT FK_BEZOEKER_GEN_NATUURLIJKPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE RECHTHEBBENDE ADD CONSTRAINT FK_RECHTHEBBENDE_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE UITGEVER ADD CONSTRAINT FK_UITGEVER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_IS_VAN FOREIGN KEY (IS_VAN_DOCUMENTTYPE_ID) REFERENCES DOCUMENTTYPE (DOCUMENTTYPE_ID);
-- IS_VAN (0..* to 1, Connector_ID: 2127)

ALTER TABLE DOCUMENT ADD CONSTRAINT FK_DOCUMENT_HEEFT_KENMERK FOREIGN KEY (HEEFT_KENMERK_IDENTIFICATIEKENMERK_ID) REFERENCES IDENTIFICATIEKENMERK (IDENTIFICATIEKENMERK_ID);
-- HEEFT_KENMERK (0..* to 1, Connector_ID: 2134)

