CREATE TABLE [ARCHIEFSTUK] (
    [ARCHIEFSTUK_ID] INT PRIMARY KEY,
    [BESCHRIJVING] NVARCHAR(MAX),
    [INVENTARISNUMMER] VARCHAR(20),
    [OMVANG] VARCHAR(255),
    [OPENBAARHEIDSBEPERKING] BIT,
    [TREFWOORDEN] VARCHAR(200),
    [UITERLIJKEVORM] VARCHAR(255)
);

CREATE TABLE [AANVRAAG] (
    [AANVRAAG_ID] INT PRIMARY KEY,
    [DATUMTIJD] DATETIME2
);

CREATE TABLE [BEZOEKER] (
    [BEZOEKER_ID] INT PRIMARY KEY,
    [DOET_AANVRAAG_ID] INT
);

CREATE TABLE [KP_ANVRG_ARCHFSTK] (
    [KP_ANVRG_ARCHFSTK_ID] INT PRIMARY KEY,
    [AANVRAAG_ID] INT,
    [ARCHIEFSTUK_ID] INT
);

ALTER TABLE [KP_ANVRG_ARCHFSTK] ADD CONSTRAINT FK_KP_ANVRG_ARCHFSTK_1 FOREIGN KEY ([AANVRAAG_ID]) REFERENCES [AANVRAAG] ([AANVRAAG_ID]);
-- AANVRAAG (many-to-many junction, Connector_ID: 1185)

ALTER TABLE [KP_ANVRG_ARCHFSTK] ADD CONSTRAINT FK_KP_ANVRG_ARCHFSTK_2 FOREIGN KEY ([ARCHIEFSTUK_ID]) REFERENCES [ARCHIEFSTUK] ([ARCHIEFSTUK_ID]);
-- ARCHIEFSTUK (many-to-many junction, Connector_ID: 1185)

ALTER TABLE [BEZOEKER] ADD CONSTRAINT FK_BEZOEKER_DOET FOREIGN KEY ([DOET_AANVRAAG_ID]) REFERENCES [AANVRAAG] ([AANVRAAG_ID]);
-- DOET (1 to 0..*, Connector_ID: 1184)

