CREATE TABLE `BEZOEKER` (
    `BEZOEKER_ID` INT PRIMARY KEY
) ENGINE=InnoDB;

CREATE TABLE `ARCHIEFSTUK` (
    `ARCHIEFSTUK_ID` INT PRIMARY KEY,
    `BESCHRIJVING` TEXT,
    `INVENTARISNUMMER` VARCHAR(20),
    `OMVANG` VARCHAR(255),
    `OPENBAARHEIDSBEPERKING` BOOLEAN,
    `TREFWOORDEN` VARCHAR(200),
    `UITERLIJKEVORM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `AANVRAAG` (
    `AANVRAAG_ID` INT PRIMARY KEY,
    `DATUMTIJD` DATETIME,
    `DOET_BEZOEKER_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_ANVRG_ARCHFSTK` (
    `KP_ANVRG_ARCHFSTK_ID` INT PRIMARY KEY,
    `AANVRAAG_ID` INT,
    `ARCHIEFSTUK_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `KP_ANVRG_ARCHFSTK` ADD CONSTRAINT FK_KP_ANVRG_ARCHFSTK_1 FOREIGN KEY (`AANVRAAG_ID`) REFERENCES `AANVRAAG` (`AANVRAAG_ID`);
-- AANVRAAG (many-to-many junction, Connector_ID: 1185)

ALTER TABLE `KP_ANVRG_ARCHFSTK` ADD CONSTRAINT FK_KP_ANVRG_ARCHFSTK_2 FOREIGN KEY (`ARCHIEFSTUK_ID`) REFERENCES `ARCHIEFSTUK` (`ARCHIEFSTUK_ID`);
-- ARCHIEFSTUK (many-to-many junction, Connector_ID: 1185)

ALTER TABLE `AANVRAAG` ADD CONSTRAINT FK_AANVRAAG_DOET FOREIGN KEY (`DOET_BEZOEKER_ID`) REFERENCES `BEZOEKER` (`BEZOEKER_ID`);
-- DOET (1 to 0..*, Connector_ID: 1184)

