CREATE TABLE ADRESSEERBAAROBJECT (
    ADRESSEERBAAROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID VARCHAR2(255),
        HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        TYPEADRESSEERBAAROBJECT VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE NUMMERAANDUIDING (
    NUMMERAANDUIDING_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER NUMBER,
        EINDEGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIE SDO_GEOMETRY,
        HUISLETTER VARCHAR2(255),
        HUISNUMMER VARCHAR2(255),
        HUISNUMMERTOEVOEGING VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        POSTCODE VARCHAR2(255),
        STATUS VARCHAR2(255),
        TYPEADRESSEERBAAROBJECT VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE OVERIGEADRESSEERBAAROBJECTAANDUIDING (
    NUMMERAANDUIDING_ID VARCHAR2(255) PRIMARY KEY,
        IDENTIFICATIECODEOVERIGADRESSEERBAAROBJECTAANDUIDING VARCHAR2(255)
);

ALTER TABLE OVERIGEADRESSEERBAAROBJECTAANDUIDING ADD CONSTRAINT FK_OVERIGEADRESSEERBAAROBJECTAANDUIDING_GEN_NUMMERAANDUIDING FOREIGN KEY (NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- Generalization to NUMMERAANDUIDING

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_HOOFDADRES FOREIGN KEY (HEEFT_ALS_HOOFDADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_HOOFDADRES (1 to 1, Connector_ID: 350)

ALTER TABLE ADRESSEERBAAROBJECT ADD CONSTRAINT FK_ADRESSEERBAAROBJECT_HEEFT_ALS_NEVENADRES FOREIGN KEY (HEEFT_ALS_NEVENADRES_NUMMERAANDUIDING_ID) REFERENCES NUMMERAANDUIDING (NUMMERAANDUIDING_ID);
-- HEEFT_ALS_NEVENADRES (1 to 0..*, Connector_ID: 347)

