CREATE TABLE [BEHEEROBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANGEMAAKTDOOR] VARCHAR(200),
        [BEGINGARANTIEPERIODE] VARCHAR(255),
        [BEHEERGEBIED] VARCHAR(255),
        [BEHEEROBJECTBEHEERVAK] VARCHAR(255),
        [BEHEEROBJECTGEBRUIKSFUNCTIE] VARCHAR(255),
        [BEHEEROBJECTMEMO] VARCHAR(255),
        [BESCHERMDEFLORAENFAUNA] BIT,
        [BUURT] VARCHAR(80),
        [CONVERSIEID] VARCHAR(50),
        [DATUMMUTATIE] DATE,
        [DATUMOPLEVERING] DATE,
        [DATUMPUBLICATIELV] DATE,
        [DATUMVERWIJDERING] DATE,
        [EINDEGARANTIEPERIODE] DATE,
        [GEBIEDSTYPE] VARCHAR(255),
        [GEMEENTE] VARCHAR(80),
        [GEOMETRIE] GEOMETRY,
        [GEWIJZIGDDOOR] VARCHAR(200),
        [GRONDSOORT] VARCHAR(255),
        [GRONDSOORTPLUS] VARCHAR(255),
        [IDENTIFICATIEIMBOR] VARCHAR(255),
        [IDENTIFICATIEIMGEO] VARCHAR(255),
        [JAARVANAANLEG] VARCHAR(255),
        [OBJECTBEGINTIJD] DATETIME2,
        [OBJECTEINDTIJD] DATETIME2,
        [ONDERHOUDSPLICHTIGE] VARCHAR(255),
        [OPENBARERUIMTE] VARCHAR(80),
        [POSTCODE] VARCHAR(255),
        [RELATIEVEHOOGTELIGGING] VARCHAR(255),
        [STADSDEEL] VARCHAR(80),
        [STATUS] VARCHAR(255),
        [THEORETISCHEINDEJAAR] DATE,
        [TIJDSTIPREGISTRATIE] DATETIME2,
        [TYPEBEHEERDER] VARCHAR(255),
        [TYPEBEHEERDERPLUS] VARCHAR(255),
        [TYPEEIGENAAR] VARCHAR(255),
        [TYPEEIGENAARPLUS] VARCHAR(255),
        [TYPELIGGING] VARCHAR(255),
        [WATERSCHAP] VARCHAR(80),
        [WIJK] VARCHAR(80),
        [WOONPLAATS] VARCHAR(80),
        [ZETTINGSGEVOELIGHEID] VARCHAR(255),
        [ZETTINGSGEVOELIGHEIDPLUS] VARCHAR(255)
);

CREATE TABLE [BAK] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [BREEDTE] VARCHAR(255),
        [DIAMETER] VARCHAR(255),
        [GEWICHTLEEG] VARCHAR(255),
        [GEWICHTVOL] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [INHOUD] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [MATERIAAL] VARCHAR(255),
        [VERPLAATSBAAR] BIT,
        [VORM] VARCHAR(255)
);

CREATE TABLE [BORD] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [BREEDTE] VARCHAR(255),
        [DIAMETER] VARCHAR(255),
        [DRAGER] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [MATERIAAL] VARCHAR(255),
        [VORM] VARCHAR(255)
);

CREATE TABLE [BOUWWERK] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [BOUWWERKMATERIAAL] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [FABRIKANT] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255),
        [TYPEFUNDERING] VARCHAR(255)
);

CREATE TABLE [FUNCTIONEELGEBIED] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [FUNCTIONEELGEBIEDCODE] VARCHAR(20),
        [FUNCTIONEELGEBIEDNAAM] VARCHAR(80),
        [OMTREK] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255)
);

CREATE TABLE [GEO_OBJECT] (
    [GEO_OBJECT_ID] INT PRIMARY KEY,
        [DATUMBEGINGELDIGHEID] DATE,
        [DATUMEINDEGELDIGHEID] DATE,
        [GEOMETRIESOORT] GEOMETRY,
        [IDENTIFICATIE] VARCHAR(255),
        [VERWIJST_NAAR_BEHEEROBJECT_ID] INT
);

CREATE TABLE [GROENOBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANTALOBSTAKELS] VARCHAR(255),
        [AANTALZIJDEN] VARCHAR(255),
        [AFVOEREN] BIT,
        [BEREIKBAARHEID] VARCHAR(255),
        [BERGENDVERMOGEN] VARCHAR(255),
        [BEWERKINGSPERCENTAGE] VARCHAR(255),
        [BGTFYSIEKVOORKOMEN] VARCHAR(80),
        [BOLLEN] BIT,
        [BREEDTE] VARCHAR(255),
        [BREEDTEKLASSEHAAG] VARCHAR(255),
        [BVC] BIT,
        [CULTUURHISTORISCHWAARDEVOL] VARCHAR(255),
        [DRAAGKRACHTIG] BIT,
        [ECOLOGISCHBEHEER] BIT,
        [FYSIEKVOORKOMENIMGEO] VARCHAR(80),
        [GEWENSTSLUITINGSPERCENTAGE] VARCHAR(255),
        [GROENOBJECTBEREIKBAARHEIDPLUS] VARCHAR(255),
        [GROENOBJECTCONSTRUCTIELAAG] VARCHAR(200),
        [GROENOBJECTRAND] VARCHAR(255),
        [GROENOBJECTSOORTNAAM] VARCHAR(255),
        [HAAGVOETLENGTE] VARCHAR(255),
        [HAAGVOETOPPERVLAKTE] VARCHAR(255),
        [HERPLANTPLICHT] BIT,
        [HOOGTE] VARCHAR(255),
        [HOOGTEKLASSEHAAG] VARCHAR(255),
        [KNIPFREQUENTIE] VARCHAR(255),
        [KNIPOPPERVLAKTE] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [MAAIFREQUENTIE] VARCHAR(255),
        [MAXIMALEVALHOOGTE] VARCHAR(255),
        [OBJECTNUMMER] VARCHAR(20),
        [OBSTAKELS] BIT,
        [OMTREK] VARCHAR(255),
        [ONDERGROEI] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255),
        [OPTALUD] VARCHAR(255),
        [TALUDSTEILTE] VARCHAR(255),
        [TYPE] VARCHAR(255),
        [TYPEBEWERKING] VARCHAR(255),
        [TYPEOMGEVINGSRISICOKLASSE] VARCHAR(255),
        [TYPEPLUS] VARCHAR(255),
        [TYPEPLUS2] VARCHAR(100),
        [VEILIGHEIDSKLASSEBOOM] VARCHAR(255)
);

CREATE TABLE [INSTALLATIE] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [BREEDTE] VARCHAR(255),
        [EANCODE] VARCHAR(50),
        [FABRIKANT] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [INBELGEGEVENS] VARCHAR(50),
        [INSTALLATEUR] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [TYPECOMMUNICATIE] VARCHAR(255)
);

CREATE TABLE [KAST] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANTALDEUREN] VARCHAR(255),
        [ADRESTELECOM] VARCHAR(255),
        [BAGCODE] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [EANCODE] VARCHAR(50),
        [FABRIKANT] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [INBELGEGEVENS] VARCHAR(50),
        [INSTALLATEUR] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [KLEUR] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [TYPECOMMUNICATIE] VARCHAR(255),
        [TYPEFUNDERING] VARCHAR(255),
        [TYPESLOT] VARCHAR(255),
        [VERMOGEN] VARCHAR(255)
);

CREATE TABLE [KUNSTWERK] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [ANTIGRAFFITIVOORZIENING] BIT,
        [BEREIKBAARHEID] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [CONSTRUCTIETYPE] VARCHAR(255),
        [GEWICHT] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [INSTALLATEUR] VARCHAR(255),
        [JAARCONSERVEREN] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [JAARRENOVATIE] VARCHAR(255),
        [JAARVERVANGING] VARCHAR(255),
        [KILOMETRERINGBEGIN] VARCHAR(255),
        [KILOMETRERINGEINDE] DATE,
        [KLEUR] VARCHAR(255),
        [KUNSTWERKBEREIKBAARHEIDPLUS] VARCHAR(255),
        [KUNSTWERKMATERIAAL] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [LOOPRICHEL] BIT,
        [MINIMUMCONDITIESCORE] VARCHAR(255),
        [MONUMENT] BIT,
        [MONUMENTNUMMER] VARCHAR(20),
        [OBJECTNAAM] VARCHAR(255),
        [OBJECTNUMMER] VARCHAR(20),
        [ONDERHOUDSREGIME] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255),
        [ORIENTATIE] VARCHAR(255),
        [TECHNISCHELEVENSDUUR] VARCHAR(255),
        [TYPEFUNDERING] VARCHAR(255),
        [TYPEMONUMENT] VARCHAR(255),
        [VERVANGINGSWAARDE] VARCHAR(255),
        [WEGNUMMER] VARCHAR(20)
);

CREATE TABLE [LEIDING] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AFWIJKENDEDIEPTELEGGING] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [DIAMETER] VARCHAR(255),
        [DIEPTE] VARCHAR(255),
        [EISVOORZORGSMAATREGEL] VARCHAR(200),
        [GEONAUWKEURIGHEIDXY] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [MATERIAAL] VARCHAR(255),
        [THEMAIMKL] VARCHAR(255),
        [VERHOOGDRISICO] VARCHAR(255)
);

CREATE TABLE [LEIDINGELEMENT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AFWIJKENDEDIEPTELEGGING] VARCHAR(255),
        [DIEPTE] VARCHAR(255),
        [GEONAUWKEURIGHEIDXY] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [THEMAIMKL] VARCHAR(255)
);

CREATE TABLE [MAST] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY
);

CREATE TABLE [MEUBILAIR] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [BOUWJAAR] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [DATUMAANSCHAF] DATE,
        [DIAMETER] VARCHAR(255),
        [FABRIKANT] VARCHAR(255),
        [GEWICHT] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [INSTALLATEUR] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [JAARPRAKTISCHEINDE] DATE,
        [KLEUR] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [MEUBILAIRMATERIAAL] VARCHAR(255),
        [MODEL] VARCHAR(50),
        [ONDERGROND] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255),
        [PRIJSAANSCHAF] DECIMAL(10,2),
        [SERIENUMMER] VARCHAR(50),
        [TRANSPONDER] VARCHAR(50),
        [TRANSPONDERLOCATIE] VARCHAR(50),
        [TYPEFUNDERING] VARCHAR(255),
        [TYPEPLAAT] BIT
);

CREATE TABLE [OVERBRUGGINGSOBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [ANTIGRAFFITIVOORZIENING] BIT,
        [BEREIKBAARHEID] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [INSTALLATEUR] VARCHAR(255),
        [JAARCONSERVEREN] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [JAARRENOVATIE] VARCHAR(255),
        [JAARVERVANGING] VARCHAR(255),
        [KLEUR] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LOOPRICHEL] BIT,
        [MINIMUMCONDITIESCORE] VARCHAR(255),
        [ONDERHOUDSREGIME] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255),
        [OVERBRUGGINGSOBJECTMATERIAAL] VARCHAR(255),
        [OVERBRUGGINGSOBJECTMODALITEIT] VARCHAR(255),
        [TECHNISCHELEVENSDUUR] VARCHAR(255),
        [TYPEFUNDERING] VARCHAR(255),
        [VERVANGINGSWAARDE] VARCHAR(255)
);

CREATE TABLE [PAAL] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [BREEDTE] VARCHAR(255),
        [DIAMETER] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [MATERIAAL] VARCHAR(255),
        [VORM] VARCHAR(255)
);

CREATE TABLE [PUT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [BOVENGRONDSZICHTBAAR] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [DIAMETER] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [MAAIVELDHOOGTE] VARCHAR(255),
        [MATERIAAL] VARCHAR(255),
        [TOEGANKELIJK] BIT,
        [TYPEAFDEKKING] VARCHAR(255),
        [VORM] VARCHAR(255),
        [WANDDIKTE] VARCHAR(255)
);

CREATE TABLE [SCHEIDING] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [OBJECTNAAM] VARCHAR(255),
        [OBJECTNUMMER] VARCHAR(20),
        [OPPERVLAKTE] VARCHAR(255),
        [SCHEIDINGMATERIAAL] VARCHAR(255),
        [VERPLAATSBAAR] BIT
);

CREATE TABLE [TERREINDEEL] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [BREEDTE] VARCHAR(255),
        [CULTUURHISTORISCHWAARDEVOL] VARCHAR(255),
        [HERPLANTPLICHT] BIT,
        [OPPERVLAKTE] VARCHAR(255),
        [OPTALUD] VARCHAR(255),
        [PERCENTAGELOOFBOS] VARCHAR(255),
        [TERREINDEELSOORTNAAM] DATE,
        [TYPE] VARCHAR(255),
        [TYPEBEWERKING] VARCHAR(255),
        [TYPEPLUS] VARCHAR(255),
        [TYPEPLUS2] VARCHAR(100)
);

CREATE TABLE [TUNNELOBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [AANTALTUNNELBUIZEN] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [DOORRIJBREEDTE] VARCHAR(255),
        [DOORRIJHOOGTE] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [JAARCONSERVEREN] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [OBJECTNAAM] VARCHAR(255),
        [OBJECTNUMMER] VARCHAR(20),
        [OPPERVLAKTE] VARCHAR(255),
        [TUNNELOBJECTMATERIAAL] VARCHAR(255)
);

CREATE TABLE [VEGETATIEOBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AFVOEREN] BIT,
        [BEREIKBAARHEID] VARCHAR(255),
        [ECOLOGISCHBEHEER] BIT,
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [KWEKER] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [OBJECTNUMMER] VARCHAR(20),
        [SOORTNAAM] VARCHAR(255),
        [TYPESTANDPLAATS] VARCHAR(255),
        [TYPESTANDPLAATSPLUS] VARCHAR(255),
        [VEGETATIEOBJECTBEREIKBAARHEIDPLUS] VARCHAR(255)
);

CREATE TABLE [VERHARDINGSOBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [AANOFVRIJLIGGEND] VARCHAR(255),
        [AANTALDEKLAGEN] VARCHAR(255),
        [AANTALONDERLAGEN] VARCHAR(255),
        [AANTALTUSSENLAGEN] VARCHAR(255),
        [AFMETING] VARCHAR(255),
        [BELASTING] VARCHAR(255),
        [BERGENDVERMOGEN] VARCHAR(255),
        [BGTFYSIEKVOORKOMEN] VARCHAR(80),
        [BREEDTE] VARCHAR(255),
        [DIKTECONSTRUCTIE] VARCHAR(255),
        [DRAAGKRACHTIG] BIT,
        [FORMAAT] VARCHAR(255),
        [FYSIEKVOORKOMENIMGEO] VARCHAR(80),
        [GELUIDSREDUCEREND] BIT,
        [JAARCONSERVEREN] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [JAARPRAKTISCHEINDE] DATE,
        [KLEUR] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LENGTEKUNSTGRAS] VARCHAR(255),
        [LENGTEVOEGEN] VARCHAR(255),
        [LEVENSDUUR] VARCHAR(255),
        [MATERIAAL] VARCHAR(255),
        [MAXIMALEVALHOOGTE] VARCHAR(255),
        [OMTREK] VARCHAR(255),
        [ONDERGRONDCODE] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255),
        [OPTALUD] VARCHAR(255),
        [PLAATSORIENTATIE] VARCHAR(255),
        [PRIJSAANSCHAF] DECIMAL(10,2),
        [RIJSTROOK] VARCHAR(255),
        [SOORTVOEG] VARCHAR(255),
        [TOELICHTINGGEMENGDEBESTRATING] VARCHAR(255),
        [TYPE] VARCHAR(255),
        [TYPECONSTRUCTIE] VARCHAR(255),
        [TYPEFUNDERING] VARCHAR(255),
        [TYPEPLUS] VARCHAR(255),
        [TYPEPLUS2] VARCHAR(100),
        [TYPERIJSTROOK] VARCHAR(255),
        [TYPEVOEG] VARCHAR(255),
        [TYPEVOEGVULLING] VARCHAR(255),
        [VEGEN] VARCHAR(255),
        [VERHARDINGSOBJECTCONSTRUCTIELAAG] VARCHAR(200),
        [VERHARDINGSOBJECTMODALITEIT] VARCHAR(255),
        [VERHARDINGSOBJECTRAND] VARCHAR(255),
        [VERHARDINGSOBJECTWEGFUNCTIE] VARCHAR(255),
        [VERHOOGDELIGGING] BIT,
        [VULMATERIAALKUNSTGRAS] VARCHAR(255),
        [WATERDOORLATENDHEID] VARCHAR(255),
        [WEGAS] VARCHAR(255),
        [WEGCATEGORIEDV] VARCHAR(255),
        [WEGCATEGORIEDVPLUS] VARCHAR(255),
        [WEGNUMMER] VARCHAR(20),
        [WEGTYPEBESTAAND] VARCHAR(255),
        [WEGVAK] VARCHAR(255),
        [WEGVAKNUMMER] VARCHAR(20)
);

CREATE TABLE [VERLICHTINGSOBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY
);

CREATE TABLE [WATERINRICHTINGSOBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [JAARCONSERVEREN] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [MATERIAAL] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255)
);

CREATE TABLE [WATEROBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [BREEDTE] VARCHAR(255),
        [FOLIE] BIT,
        [HOOGTE] VARCHAR(255),
        [INFILTRERENDOPPERVLAK] VARCHAR(255),
        [INFILTRERENDVERMOGEN] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LOZINGSPUNT] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255),
        [POROSITEIT] VARCHAR(255),
        [STREEFDIEPTE] VARCHAR(255),
        [TYPE] VARCHAR(255),
        [TYPEPLUS] VARCHAR(255),
        [TYPEPLUS2] VARCHAR(100),
        [TYPEVAARWATER] VARCHAR(255),
        [TYPEWATERPLANT] VARCHAR(255),
        [UITSTROOMNIVEAU] VARCHAR(255),
        [VAARWEGTRAJECT] VARCHAR(50),
        [VORM] VARCHAR(255),
        [WATERNAAM] VARCHAR(100),
        [WATERPEIL] VARCHAR(255),
        [WATERPEILWINTER] VARCHAR(255),
        [WATERPEILZOMER] VARCHAR(255),
        [WATERPLANTEN] BIT
);

CREATE TABLE [WEGINRICHTINGSOBJECT] (
    [BEHEEROBJECT_ID] INT PRIMARY KEY,
        [AANLEGHOOGTE] VARCHAR(255),
        [BREEDTE] VARCHAR(255),
        [HOOGTE] VARCHAR(255),
        [JAARCONSERVEREN] VARCHAR(255),
        [JAARONDERHOUDUITGEVOERD] VARCHAR(255),
        [KWALITEITSNIVEAUACTUEEL] VARCHAR(255),
        [KWALITEITSNIVEAUGEWENST] VARCHAR(255),
        [LENGTE] VARCHAR(255),
        [LEVERANCIER] VARCHAR(255),
        [MATERIAAL] VARCHAR(255),
        [OPPERVLAKTE] VARCHAR(255),
        [WEGINRICHTINGSOBJECTWEGFUNCTIE] VARCHAR(255)
);

ALTER TABLE [BAK] ADD CONSTRAINT FK_BAK_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [BORD] ADD CONSTRAINT FK_BORD_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [BOUWWERK] ADD CONSTRAINT FK_BOUWWERK_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [FUNCTIONEELGEBIED] ADD CONSTRAINT FK_FUNCTIONEELGEBIED_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [GROENOBJECT] ADD CONSTRAINT FK_GROENOBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [INSTALLATIE] ADD CONSTRAINT FK_INSTALLATIE_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [KAST] ADD CONSTRAINT FK_KAST_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [KUNSTWERK] ADD CONSTRAINT FK_KUNSTWERK_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [LEIDING] ADD CONSTRAINT FK_LEIDING_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [LEIDINGELEMENT] ADD CONSTRAINT FK_LEIDINGELEMENT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [MAST] ADD CONSTRAINT FK_MAST_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [MEUBILAIR] ADD CONSTRAINT FK_MEUBILAIR_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [OVERBRUGGINGSOBJECT] ADD CONSTRAINT FK_OVERBRUGGINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [PAAL] ADD CONSTRAINT FK_PAAL_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [PUT] ADD CONSTRAINT FK_PUT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [SCHEIDING] ADD CONSTRAINT FK_SCHEIDING_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [TERREINDEEL] ADD CONSTRAINT FK_TERREINDEEL_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [TUNNELOBJECT] ADD CONSTRAINT FK_TUNNELOBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [VEGETATIEOBJECT] ADD CONSTRAINT FK_VEGETATIEOBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [VERHARDINGSOBJECT] ADD CONSTRAINT FK_VERHARDINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [VERLICHTINGSOBJECT] ADD CONSTRAINT FK_VERLICHTINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [WATERINRICHTINGSOBJECT] ADD CONSTRAINT FK_WATERINRICHTINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [WATEROBJECT] ADD CONSTRAINT FK_WATEROBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [WEGINRICHTINGSOBJECT] ADD CONSTRAINT FK_WEGINRICHTINGSOBJECT_GEN_BEHEEROBJECT FOREIGN KEY ([BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- Generalization to BEHEEROBJECT

ALTER TABLE [GEO_OBJECT] ADD CONSTRAINT FK_GEO_OBJECT_VERWIJST_NAAR FOREIGN KEY ([VERWIJST_NAAR_BEHEEROBJECT_ID]) REFERENCES [BEHEEROBJECT] ([BEHEEROBJECT_ID]);
-- VERWIJST_NAAR (1 to 0..1, Connector_ID: 805)

