CREATE TABLE BEHEEROBJECT (
    BEHEEROBJECT_ID VARCHAR2(255) PRIMARY KEY,
        AANGEMAAKTDOOR VARCHAR2(200),
        BEGINGARANTIEPERIODE VARCHAR2(255),
        BEHEERGEBIED VARCHAR2(255),
        BEHEEROBJECTBEHEERVAK VARCHAR2(255),
        BEHEEROBJECTGEBRUIKSFUNCTIE VARCHAR2(255),
        BEHEEROBJECTMEMO VARCHAR2(255),
        BESCHERMDEFLORAENFAUNA NUMBER(1),
        BUURT VARCHAR2(80),
        CONVERSIEID VARCHAR2(50),
        DATUMMUTATIE DATE,
        DATUMOPLEVERING DATE,
        DATUMPUBLICATIELV DATE,
        DATUMVERWIJDERING DATE,
        EINDEGARANTIEPERIODE DATE,
        GEBIEDSTYPE VARCHAR2(255),
        GEMEENTE VARCHAR2(80),
        GEOMETRIE SDO_GEOMETRY,
        GEWIJZIGDDOOR VARCHAR2(200),
        GRONDSOORT VARCHAR2(255),
        GRONDSOORTPLUS VARCHAR2(255),
        IDENTIFICATIEIMBOR VARCHAR2(255),
        IDENTIFICATIEIMGEO VARCHAR2(255),
        JAARVANAANLEG VARCHAR2(255),
        OBJECTBEGINTIJD TIMESTAMP,
        OBJECTEINDTIJD TIMESTAMP,
        ONDERHOUDSPLICHTIGE VARCHAR2(255),
        OPENBARERUIMTE VARCHAR2(80),
        POSTCODE VARCHAR2(255),
        RELATIEVEHOOGTELIGGING VARCHAR2(255),
        STADSDEEL VARCHAR2(80),
        STATUS VARCHAR2(255),
        THEORETISCHEINDEJAAR DATE,
        TIJDSTIPREGISTRATIE TIMESTAMP,
        TYPEBEHEERDER VARCHAR2(255),
        TYPEBEHEERDERPLUS VARCHAR2(255),
        TYPEEIGENAAR VARCHAR2(255),
        TYPEEIGENAARPLUS VARCHAR2(255),
        TYPELIGGING VARCHAR2(255),
        WATERSCHAP VARCHAR2(80),
        WIJK VARCHAR2(80),
        WOONPLAATS VARCHAR2(80),
        ZETTINGSGEVOELIGHEID VARCHAR2(255),
        ZETTINGSGEVOELIGHEIDPLUS VARCHAR2(255)
);

CREATE TABLE GEO_OBJECT (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEID DATE,
        DATUMEINDEGELDIGHEID DATE,
        GEOMETRIESOORT SDO_GEOMETRY,
        IDENTIFICATIE VARCHAR2(255),
        VERWIJST_NAAR_BEHEEROBJECT_ID VARCHAR2(255)
);

CREATE TABLE BEGROEIDTERREINDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        BEGROEIDTERREINDEELOPTALUD DATE,
        DATUMBEGINGELDIGHEIDBEGROEIDTERREINDEEL DATE,
        DATUMEINDEGELDIGHEIDBEGROEIDTERREINDEEL DATE,
        FYSIEKVOORKOMENBEGROEIDTERREINDEEL DATE,
        GEOMETRIEBEGROEIDTERREINDEEL SDO_GEOMETRY,
        IDENTIFICATIEBEGROEIDTERREINDEEL DATE,
        KRUINLIJNGEOMETRIEBEGROEIDTERREINDEEL SDO_GEOMETRY,
        LOD0GEOMETRIEBEGROEIDTERREINDEEL SDO_GEOMETRY,
        PLUSFYSIEKVOORKOMENBEGROEIDTERREINDEEL DATE,
        RELATIEVEHOOGTELIGGINGBEGROEIDTERREINDEEL DATE,
        STATUSBEGROEIDTERREINDEEL DATE
);

CREATE TABLE FUNCTIONEELGEBIED (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDFUNCTIONEELGEBIED DATE,
        DATUMEINDEGELDIGHEIDFUNCTIONEELGEBIED DATE,
        GEOMETRIEFUNCTIONEELGEBIED SDO_GEOMETRY,
        IDENTIFICATIEFUNCTIONEELGEBIED VARCHAR2(255),
        NAAMFUNCTIONEELGEBIED VARCHAR2(255),
        STATUSFUNCTIONEELGEBIED VARCHAR2(255)
);

CREATE TABLE GEBOUWINSTALLATIE (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDGEBOUWINSTALLATIE DATE,
        DATUMEINDEGELDIGHEIDGEBOUWINSTALLATIE DATE,
        GEOMETRIEGEBOUWINSTALLATIE SDO_GEOMETRY,
        IDENTIFICATIEGEBOUWINSTALLATIE VARCHAR2(255),
        LOD0GEOMETRIEGEBOUWINSTALLATIE SDO_GEOMETRY,
        RELATIEVEHOOGTELIGGINGGEBOUWINSTALLATIE VARCHAR2(255),
        STATUSGEBOUWINSTALLATIE VARCHAR2(255),
        TYPEGEBOUWINSTALLATIE VARCHAR2(255)
);

CREATE TABLE INRICHTINGSELEMENT (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDINRICHTINGSELEMENT DATE,
        DATUMEINDEGELDIGHEIDINRICHTINGSELEMENT DATE,
        GEOMETRIEINRICHTINGSELEMENT SDO_GEOMETRY,
        IDENTIFICATIEINRICHTINGSELEMENT VARCHAR2(255),
        LOD0GEOMETRIEINRICHTINGSELEMENT SDO_GEOMETRY,
        PLUSTYPEINRICHTINGSELEMENT VARCHAR2(255),
        RELATIEVEHOOGTELIGGINGINRICHTINGSELEMENT VARCHAR2(255),
        STATUSINRICHTINGSELEMENT VARCHAR2(255),
        TYPEINRICHTINGSELEMENT VARCHAR2(255)
);

CREATE TABLE KUNSTWERKDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDKUNSTWERKDEEL DATE,
        DATUMEINDEGELDIGHEIDKUNSTWERKDEEL DATE,
        GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
        IDENTIFICATIEKUNSTWERKDEEL VARCHAR2(255),
        LOD0GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
        LOD1GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
        LOD2GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
        LOD3GEOMETRIEKUNSTWERKDEEL SDO_GEOMETRY,
        RELATIEVEHOOGTELIGGINGKUNSTWERKDEEL VARCHAR2(255),
        STATUSKUNSTWERKDEEL VARCHAR2(255)
);

CREATE TABLE ONBEGROEIDTERREINDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDONBEGROEIDTERREINDEEL DATE,
        DATUMEINDEGELDIGHEIDONBEGROEIDTERREINDEEL DATE,
        FYSIEKVOORKOMENONBEGROEIDTERREINDEEL DATE,
        GEOMETRIEONBEGROEIDTERREINDEEL SDO_GEOMETRY,
        IDENTIFICATIEONBEGROEIDTERREINDEEL DATE,
        KRUINLIJNGEOMETRIEONBEGROEIDTERREINDEEL SDO_GEOMETRY,
        ONBEGROEIDTERREINDEELOPTALUD DATE,
        PLUSFYSIEKVOORKOMENONBEGROEIDTERREINDEEL DATE,
        RELATIEVEHOOGTELIGGINGONBEGROEIDTERREINDEEL DATE,
        STATUSONBEGROEIDTERREINDEEL DATE
);

CREATE TABLE ONDERSTEUNENDWATERDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDONDERSTEUNENDWATERDEEL DATE,
        DATUMEINDEGELDIGHEIDONDERSTEUNENDWATERDEEL DATE,
        GEOMETRIEONDERSTEUNENDWATERDEEL SDO_GEOMETRY,
        IDENTIFICATIEONDERSTEUNENDWATERDEEL VARCHAR2(255),
        PLUSTYPEONDERSTEUNENDWATERDEEL VARCHAR2(255),
        RELATIEVEHOOGTELIGGINGONDERSTEUNENDWATERDEEL VARCHAR2(255),
        STATUSONDERSTEUNENDWATERDEEL VARCHAR2(255),
        TYPEONDERSTEUNENDWATERDEEL VARCHAR2(255)
);

CREATE TABLE ONDERSTEUNENDWEGDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDONDERSTEUNENDWEGDEEL DATE,
        DATUMEINDEGELDIGHEIDONDERSTEUNENDWEGDEEL DATE,
        FUNCTIEONDERSTEUNENDWEGDEEL VARCHAR2(255),
        FYSIEKVOORKOMENONDERSTEUNENDWEGDEEL_ VARCHAR2(255),
        GEOMETRIEONDERSTEUNENDWEGDEEL SDO_GEOMETRY,
        IDENTIFICATIEONDERSTEUNENDWEGDEEL VARCHAR2(255),
        KRUINLIJNGEOMETRIEONDERSTEUNENDWEGDEEL SDO_GEOMETRY,
        LOD0GEOMETRIEONDERSTEUNENDWEGDEEL SDO_GEOMETRY,
        ONDERSTEUNENDWEGDEELOPTALUD VARCHAR2(255),
        PLUSFUNCTIEONDERSTEUNENDWEGDEEL VARCHAR2(255),
        PLUSFYSIEKVOORKOMENONDERSTEUNENDWEGDEEL VARCHAR2(255),
        RELATIEVEHOOGTELIGGINGONDERSTEUNENDWEGDEEL VARCHAR2(255),
        STATUSONDERSTEUNENDWEGDEEL VARCHAR2(255)
);

CREATE TABLE OVERBRUGGINGSDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDOVERBRUGGINGSDEEL DATE,
        DATUMEINDEGELDIGHEIDOVERBRUGGINGSDEEL DATE,
        GEOMETRIEOVERBRUGGINGSDEEL SDO_GEOMETRY,
        HOORTBIJTYPEOVERBRUGGING VARCHAR2(255),
        IDENTIFICATIEOVERBRUGGINGSDEEL VARCHAR2(255),
        LOD0GEOMETRIEOVERBRUGGINGSDEEL SDO_GEOMETRY,
        OVERBRUGGINGISBEWEEGBAAR VARCHAR2(255),
        RELATIEVEHOOGTELIGGINGOVERBRUGGINGSDEEL VARCHAR2(255),
        STATUSOVERBRUGGINGSDEEL VARCHAR2(255),
        TYPEOVERBRUGGINGSDEEL VARCHAR2(255)
);

CREATE TABLE OVERIGBENOEMDTERREIN (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        GEBRUIKSDOELOVERIGBENOEMDTERREIN VARCHAR2(255),
        OVERIGBENOEMDTERREINIDENTIFICATIE VARCHAR2(255)
);

CREATE TABLE OVERIGBOUWWERK (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDOVERIGBOUWWERK DATE,
        DATUMEINDEGELDIGHEIDOVERIGBOUWWERK DATE,
        GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
        IDENTIFICATIEOVERIGBOUWWERK VARCHAR2(255),
        LOD0GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
        LOD1GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
        LOD2GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
        LOD3GEOMETRIEOVERIGBOUWWERK SDO_GEOMETRY,
        RELATIEVEHOOGTELIGGINGOVERIGBOUWWERK VARCHAR2(255),
        STATUSOVERIGBOUWWERK VARCHAR2(255)
);

CREATE TABLE OVERIGESCHEIDING (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDOVERIGESCHEIDING DATE,
        DATUMEINDEGELDIGHEIDOVERIGESCHEIDING DATE,
        GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
        IDENTIFICATIEOVERIGESCHEIDING VARCHAR2(255),
        LOD0GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
        LOD1GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
        LOD2GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
        LOD3GEOMETRIEOVERIGESCHEIDING SDO_GEOMETRY,
        RELATIEVEHOOGTELIGGINGOVERIGESCHEIDING VARCHAR2(255),
        STATUSOVERIGESCHEIDING VARCHAR2(255),
        TYPEOVERIGESCHEIDING VARCHAR2(255)
);

CREATE TABLE PAND (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        BEGINGELDIGHEID VARCHAR2(255),
        BRUTOINHOUDPAND VARCHAR2(255),
        DATUMEINDE DATE,
        DATUMINGANG DATE,
        DOCUMENTDATUM DATE,
        DOCUMENTNUMMER VARCHAR2(255),
        EINDGELDIGHEID DATE,
        GECONSTATEERD NUMBER(1),
        GEOMETRIEBOVENAANZICHT SDO_GEOMETRY,
        GEOMETRIEMAAIVELD SDO_GEOMETRY,
        GEOMETRIEPUNT SDO_GEOMETRY,
        HOOGSTEBOUWLAAG VARCHAR2(255),
        IDENTIFICATIE VARCHAR2(255),
        LAAGSTEBOUWLAAG VARCHAR2(255),
        OORSPRONKELIJKBOUWJAAR VARCHAR2(255),
        OPPERVLAKTE VARCHAR2(255),
        RELATIEVEHOOGTELIGGING VARCHAR2(255),
        STATUS VARCHAR2(255),
        STATUSVOORTGANGBOUW VARCHAR2(255),
        VERSIE NUMBER
);

CREATE TABLE SCHEIDING (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDSCHEIDING DATE,
        DATUMEINDEGELDIGHEIDSCHEIDING DATE,
        GEOMETRIESCHEIDING SDO_GEOMETRY,
        IDENTIFICATIESCHEIDING VARCHAR2(255),
        LOD0GEOMETRIESCHEIDING SDO_GEOMETRY,
        LOD1GEOMETRIESCHEIDING SDO_GEOMETRY,
        LOD2GEOMETRIESCHEIDING SDO_GEOMETRY,
        LOD3GEOMETRIESCHEIDING SDO_GEOMETRY,
        RELATIEVEHOOGTELIGGINGSCHEIDING VARCHAR2(255),
        STATUSSCHEIDING VARCHAR2(255)
);

CREATE TABLE SPOOR (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDSPOOR DATE,
        DATUMEINDEGELDIGHEIDSPOOR DATE,
        GEOMETRIESPOOR SDO_GEOMETRY,
        IDENTIFICATIESPOOR VARCHAR2(255),
        LOD0GEOMETRIESPOOR SDO_GEOMETRY,
        RELATIEVEHOOGTELIGGINGSPOOR VARCHAR2(255),
        STATUSSPOOR VARCHAR2(255)
);

CREATE TABLE TUNNELDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDTUNNELDEEL DATE,
        DATUMEINDEGELDIGHEIDTUNNELDEEL DATE,
        GEOMETRIETUNNELDEEL SDO_GEOMETRY,
        IDENTIFICATIETUNNELDEEL VARCHAR2(255),
        LOD0GEOMETRIETUNNELDEEL SDO_GEOMETRY,
        RELATIEVEHOOGTELIGGINGTUNNELDEEL VARCHAR2(255),
        STATUSTUNNELDEEL VARCHAR2(255)
);

CREATE TABLE VEGETATIEOBJECT (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDVEGETATIEOBJECT DATE,
        DATUMEINDEGELDIGHEIDVEGETATIEOBJECT DATE,
        GEOMETRIEVEGETATIEOBJECT SDO_GEOMETRY,
        IDENTIFICATIEVEGETATIEOBJECT VARCHAR2(255),
        LOD0GEOMETRIEVEGETATIEOBJECT SDO_GEOMETRY,
        RELATIEVEHOOGTELIGGINGVEGETATIEOBJECT VARCHAR2(255),
        STATUSVEGETATIEOBJECT VARCHAR2(255),
        TYPEVEGETATIEOBJECT VARCHAR2(255)
);

CREATE TABLE WATERDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDWATERDEEL DATE,
        DATUMEINDEGELDIGHEIDWATERDEEL DATE,
        GEOMETRIEWATERDEEL SDO_GEOMETRY,
        IDENTIFICATIEWATERDEEL VARCHAR2(255),
        PLUSTYPEWATERDEEL VARCHAR2(255),
        RELATIEVEHOOGTELIGGINGWATERDEEL VARCHAR2(255),
        STATUSWATERDEEL VARCHAR2(255),
        TYPEWATERDEEL VARCHAR2(255)
);

CREATE TABLE WEGDEEL (
    GEO_OBJECT_ID VARCHAR2(255) PRIMARY KEY,
        DATUMBEGINGELDIGHEIDWEGDEEL DATE,
        DATUMEINDEGELDIGHEIDWEGDEEL DATE,
        FUNCTIEWEGDEEL VARCHAR2(255),
        FYSIEKVOORKOMENWEGDEEL VARCHAR2(255),
        GEOMETRIEWEGDEEL SDO_GEOMETRY,
        IDENTIFICATIEWEGDEEL VARCHAR2(255),
        KRUINLIJNGEOMETRIEWEGDEEL SDO_GEOMETRY,
        LOD0GEOMETRIEWEGDEEL SDO_GEOMETRY,
        PLUSFUNCTIEWEGDEEL VARCHAR2(255),
        PLUSFYSIEKVOORKOMENWEGDEEL VARCHAR2(255),
        RELATIEVEHOOGTELIGGINGWEGDEEL VARCHAR2(255),
        STATUSWEGDEEL VARCHAR2(255),
        WEGDEELOPTALUD VARCHAR2(255)
);

ALTER TABLE PAND ADD CONSTRAINT FK_PAND_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE BEGROEIDTERREINDEEL ADD CONSTRAINT FK_BEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE FUNCTIONEELGEBIED ADD CONSTRAINT FK_FUNCTIONEELGEBIED_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE GEBOUWINSTALLATIE ADD CONSTRAINT FK_GEBOUWINSTALLATIE_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE INRICHTINGSELEMENT ADD CONSTRAINT FK_INRICHTINGSELEMENT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE KUNSTWERKDEEL ADD CONSTRAINT FK_KUNSTWERKDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONBEGROEIDTERREINDEEL ADD CONSTRAINT FK_ONBEGROEIDTERREINDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONDERSTEUNENDWATERDEEL ADD CONSTRAINT FK_ONDERSTEUNENDWATERDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE ONDERSTEUNENDWEGDEEL ADD CONSTRAINT FK_ONDERSTEUNENDWEGDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERBRUGGINGSDEEL ADD CONSTRAINT FK_OVERBRUGGINGSDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGBENOEMDTERREIN ADD CONSTRAINT FK_OVERIGBENOEMDTERREIN_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGBOUWWERK ADD CONSTRAINT FK_OVERIGBOUWWERK_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE OVERIGESCHEIDING ADD CONSTRAINT FK_OVERIGESCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE SCHEIDING ADD CONSTRAINT FK_SCHEIDING_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE SPOOR ADD CONSTRAINT FK_SPOOR_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE TUNNELDEEL ADD CONSTRAINT FK_TUNNELDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE VEGETATIEOBJECT ADD CONSTRAINT FK_VEGETATIEOBJECT_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE WATERDEEL ADD CONSTRAINT FK_WATERDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE WEGDEEL ADD CONSTRAINT FK_WEGDEEL_GEN_GEO_OBJECT FOREIGN KEY (GEO_OBJECT_ID) REFERENCES GEO_OBJECT (GEO_OBJECT_ID);
-- Generalization to GEO_OBJECT

ALTER TABLE GEO_OBJECT ADD CONSTRAINT FK_GEO_OBJECT_VERWIJST_NAAR FOREIGN KEY (VERWIJST_NAAR_BEHEEROBJECT_ID) REFERENCES BEHEEROBJECT (BEHEEROBJECT_ID);
-- VERWIJST_NAAR (1 to 0..1, Connector_ID: 805)

