CREATE TABLE AANVRAAGOFMELDING (
    AANVRAAGOFMELDING_ID VARCHAR(255) PRIMARY KEY,
        AFGEHANDELD BOOLEAN,
        CATEGORIE VARCHAR(200),
        CATEGORIECODE VARCHAR(80),
        DATUMAANMAAK DATE,
        DATUMAFHANDELING DATE,
        DATUMBEGINSTATUS DATE,
        DATUMEINDESTATUS DATE,
        HOOFDCATEGORIE VARCHAR(80),
        HOOFDCATEGORIECODE VARCHAR(80),
        IDENTIFICATIE VARCHAR(255),
        KANAAL VARCHAR(80),
        ONDERWERP VARCHAR(200),
        ONDERWERPCODE VARCHAR(80),
        SOORT VARCHAR(80),
        STATUS VARCHAR(80),
        STATUSCODE VARCHAR(80),
        STATUSVOLGORDE VARCHAR(80),
        SUBCATEGORIE VARCHAR(200),
        SUBCATEGORIECODE VARCHAR(80)
);

CREATE TABLE INCIDENT (
    INCIDENT_ID VARCHAR(255) PRIMARY KEY,
        DATUMTIJDTOT TIMESTAMP,
        DATUMTIJDVANAF TIMESTAMP,
        LOCATIE VARCHAR(255),
        OMSCHRIJVING TEXT,
        SOORT VARCHAR(255),
        TOELICHTING TEXT
);

CREATE TABLE ZORGELIJKE_SITUATIE (
    ZORGELIJKE_SITUATIE_ID VARCHAR(255) PRIMARY KEY,
        BERUST_OP_INCIDENT_ID VARCHAR(255),
        NADEREOMSCHRIJVING TEXT,
        SITIUATIESCHETS TEXT
);

CREATE TABLE ZORGMELDING (
    AANVRAAGOFMELDING_ID VARCHAR(255) PRIMARY KEY,
        NAAR_AANLEIDING_VAN_ZORGELIJKE_SITUATIE_ID VARCHAR(255),
        NADEREOMSCHRIJVING TEXT,
        OMSCHRIJVING TEXT,
        TERUGKOPPELINGGEWENST BOOLEAN,
        VERZOEK VARCHAR(255),
        ZORGMELDINGSOORT INTEGER
);

ALTER TABLE ZORGMELDING ADD CONSTRAINT FK_ZORGMELDING_GEN_AANVRAAGOFMELDING FOREIGN KEY (AANVRAAGOFMELDING_ID) REFERENCES AANVRAAGOFMELDING (AANVRAAGOFMELDING_ID);
-- Generalization to AANVRAAGOFMELDING

ALTER TABLE ZORGELIJKE_SITUATIE ADD CONSTRAINT FK_ZORGELIJKE_SITUATIE_BERUST_OP FOREIGN KEY (BERUST_OP_INCIDENT_ID) REFERENCES INCIDENT (INCIDENT_ID);
-- BERUST_OP (1 to 0..*, Connector_ID: 1007)

ALTER TABLE ZORGMELDING ADD CONSTRAINT FK_ZORGMELDING_NAAR_AANLEIDING_VAN FOREIGN KEY (NAAR_AANLEIDING_VAN_ZORGELIJKE_SITUATIE_ID) REFERENCES ZORGELIJKE_SITUATIE (ZORGELIJKE_SITUATIE_ID);
-- NAAR_AANLEIDING_VAN (1 to 1..*, Connector_ID: 1006)

