CREATE TABLE LOCATIE (
    LOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        HOOGTE NUMBER,
        NAAM VARCHAR2(200),
        NEN3610ID VARCHAR2(80)
);

CREATE TABLE GEBIED (
    LOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        GEBIED VARCHAR2(255)
);

CREATE TABLE GEBIEDENGROEP (
    LOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        OMVAT_GEBIED_ID VARCHAR2(255)
);

CREATE TABLE LIJN (
    LOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        LIJN VARCHAR2(255)
);

CREATE TABLE LIJNENGROEP (
    LOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        OMVAT_LIJN_ID VARCHAR2(255)
);

CREATE TABLE PUNT (
    LOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        PUNT VARCHAR2(255)
);

CREATE TABLE PUNTENGROEP (
    LOCATIE_ID VARCHAR2(255) PRIMARY KEY,
        OMVAT_PUNT_ID VARCHAR2(255)
);

ALTER TABLE GEBIED ADD CONSTRAINT FK_GEBIED_GEN_LOCATIE FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- Generalization to LOCATIE

ALTER TABLE GEBIEDENGROEP ADD CONSTRAINT FK_GEBIEDENGROEP_GEN_LOCATIE FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- Generalization to LOCATIE

ALTER TABLE LIJN ADD CONSTRAINT FK_LIJN_GEN_LOCATIE FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- Generalization to LOCATIE

ALTER TABLE LIJNENGROEP ADD CONSTRAINT FK_LIJNENGROEP_GEN_LOCATIE FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- Generalization to LOCATIE

ALTER TABLE PUNT ADD CONSTRAINT FK_PUNT_GEN_LOCATIE FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- Generalization to LOCATIE

ALTER TABLE PUNTENGROEP ADD CONSTRAINT FK_PUNTENGROEP_GEN_LOCATIE FOREIGN KEY (LOCATIE_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- Generalization to LOCATIE

ALTER TABLE GEBIEDENGROEP ADD CONSTRAINT FK_GEBIEDENGROEP_OMVAT FOREIGN KEY (OMVAT_GEBIED_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- OMVAT (0..1 to 1..*, Connector_ID: 311)

ALTER TABLE LIJNENGROEP ADD CONSTRAINT FK_LIJNENGROEP_OMVAT FOREIGN KEY (OMVAT_LIJN_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- OMVAT (0..1 to 0..*, Connector_ID: 308)

ALTER TABLE PUNTENGROEP ADD CONSTRAINT FK_PUNTENGROEP_OMVAT FOREIGN KEY (OMVAT_PUNT_ID) REFERENCES LOCATIE (LOCATIE_ID);
-- OMVAT (0..1 to 1..*, Connector_ID: 305)

