CREATE TABLE `TAAKVELD` (
    `TAAKVELD_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `DOSSIER` (
    `DOSSIER_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `PROGRAMMA` (
    `PROGRAMMA_ID` INT PRIMARY KEY,
    `NAAM` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `RAADSSTUK` (
    `RAADSSTUK_ID` INT PRIMARY KEY,
    `BESLOTEN` BOOLEAN,
    `DATUMEXPIRATIE` DATE,
    `DATUMPUBLICATIE` DATE,
    `DATUMREGISTRATIE` DATE,
    `HEEFT_TAAKVELD_ID` INT,
    `TYPERAADSSTUK` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `KP_DSSR_RDSSTK` (
    `KP_DSSR_RDSSTK_ID` INT PRIMARY KEY,
    `DOSSIER_ID` INT,
    `RAADSSTUK_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KP_RDSSTK_PRGRMM` (
    `KP_RDSSTK_PRGRMM_ID` INT PRIMARY KEY,
    `RAADSSTUK_ID` INT,
    `PROGRAMMA_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `CATEGORIE` (
    `CATEGORIE_ID` INT PRIMARY KEY,
    `HEEFT_RAADSSTUK_ID` INT,
    `NAAM` VARCHAR(255)
) ENGINE=InnoDB;

ALTER TABLE `KP_RDSSTK_PRGRMM` ADD CONSTRAINT FK_KP_RDSSTK_PRGRMM_1 FOREIGN KEY (`RAADSSTUK_ID`) REFERENCES `RAADSSTUK` (`RAADSSTUK_ID`);
-- RAADSSTUK (many-to-many junction, Connector_ID: 1341)

ALTER TABLE `KP_RDSSTK_PRGRMM` ADD CONSTRAINT FK_KP_RDSSTK_PRGRMM_2 FOREIGN KEY (`PROGRAMMA_ID`) REFERENCES `PROGRAMMA` (`PROGRAMMA_ID`);
-- PROGRAMMA (many-to-many junction, Connector_ID: 1341)

ALTER TABLE `KP_DSSR_RDSSTK` ADD CONSTRAINT FK_KP_DSSR_RDSSTK_1 FOREIGN KEY (`DOSSIER_ID`) REFERENCES `DOSSIER` (`DOSSIER_ID`);
-- DOSSIER (many-to-many junction, Connector_ID: 1345)

ALTER TABLE `KP_DSSR_RDSSTK` ADD CONSTRAINT FK_KP_DSSR_RDSSTK_2 FOREIGN KEY (`RAADSSTUK_ID`) REFERENCES `RAADSSTUK` (`RAADSSTUK_ID`);
-- RAADSSTUK (many-to-many junction, Connector_ID: 1345)

ALTER TABLE `RAADSSTUK` ADD CONSTRAINT FK_RAADSSTUK_HEEFT FOREIGN KEY (`HEEFT_TAAKVELD_ID`) REFERENCES `TAAKVELD` (`TAAKVELD_ID`);
-- HEEFT (0..* to 0..1, Connector_ID: 1335)

ALTER TABLE `CATEGORIE` ADD CONSTRAINT FK_CATEGORIE_HEEFT FOREIGN KEY (`HEEFT_RAADSSTUK_ID`) REFERENCES `RAADSSTUK` (`RAADSSTUK_ID`);
-- HEEFT (0..1 to 0..*, Connector_ID: 1348)

