CREATE TABLE BEOORDELING (
    BEOORDELING_ID VARCHAR(255) PRIMARY KEY,
        DATUM DATE,
        OMSCHRIJVING TEXT,
        OORDEEL VARCHAR(80),
        VASTLEGGING_DOCUMENT_ID VARCHAR(255)
);

CREATE TABLE DIENSTVERBAND (
    DIENSTVERBAND_ID VARCHAR(255) PRIMARY KEY,
        ARBEIDSOVEREENKOMST_DOCUMENT_ID VARCHAR(255),
        DATUMEINDE DATE,
        DATUMSTART DATE,
        PERIODIEK INTEGER,
        SALARIS VARCHAR(255),
        SCHAAL INTEGER,
        URENPERWEEK INTEGER
);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR(200),
        DOCUMENTIDENTIFICATIE VARCHAR(255),
        DOCUMENTTITEL VARCHAR(200),
        VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE WERKNEMER (
    WERKNEMER_ID VARCHAR(255) PRIMARY KEY,
        BEOORDEELT_DOOR_BEOORDELING_ID VARCHAR(255),
        BEOORDELING_VAN_BEOORDELING_ID VARCHAR(255),
        GEBOORTEDATUM DATE,
        MEDEWERKER_HEEFT_DIENSTVERBAND_DIENSTVERBAND_ID VARCHAR(255),
        NAAM VARCHAR(80),
        PERSONEELSDOSSIER_DOCUMENT_ID VARCHAR(255),
        VOORNAAM VARCHAR(255),
        WOONPLAATS VARCHAR(50)
);

ALTER TABLE BEOORDELING ADD CONSTRAINT FK_BEOORDELING_VASTLEGGING FOREIGN KEY (VASTLEGGING_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- VASTLEGGING (None to None, Connector_ID: 110)

ALTER TABLE DIENSTVERBAND ADD CONSTRAINT FK_DIENSTVERBAND_ARBEIDSOVEREENKOMST FOREIGN KEY (ARBEIDSOVEREENKOMST_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- ARBEIDSOVEREENKOMST (None to None, Connector_ID: 109)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_BEOORDEELT_DOOR FOREIGN KEY (BEOORDEELT_DOOR_BEOORDELING_ID) REFERENCES BEOORDELING (BEOORDELING_ID);
-- BEOORDEELT_DOOR (1 to 0..*, Connector_ID: 476)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_BEOORDELING_VAN FOREIGN KEY (BEOORDELING_VAN_BEOORDELING_ID) REFERENCES BEOORDELING (BEOORDELING_ID);
-- BEOORDELING_VAN (1 to 0..*, Connector_ID: 475)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_MEDEWERKER_HEEFT_DIENSTVERBAND FOREIGN KEY (MEDEWERKER_HEEFT_DIENSTVERBAND_DIENSTVERBAND_ID) REFERENCES DIENSTVERBAND (DIENSTVERBAND_ID);
-- MEDEWERKER_HEEFT_DIENSTVERBAND (1 to 1..*, Connector_ID: 468)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_PERSONEELSDOSSIER FOREIGN KEY (PERSONEELSDOSSIER_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- PERSONEELSDOSSIER (None to None, Connector_ID: 107)

