CREATE TABLE DOCUMENT (
    DOCUMENT_ID VARCHAR(255) PRIMARY KEY,
        COCUMENTBESCHRIJVING VARCHAR(255),
        DATUMCREATIEDOCUMENT DATE,
        DATUMONTVANGSTDOCUMENT DATE,
        DATUMVERZENDINGDOCUMENT DATE,
        DOCUMENTAUTEUR VARCHAR(200),
        DOCUMENTIDENTIFICATIE VARCHAR(255),
        DOCUMENTTITEL VARCHAR(200),
        VERTROUWELIJKAANDUIDING VARCHAR(20)
);

CREATE TABLE FUNCTIE (
    FUNCTIE_ID VARCHAR(255) PRIMARY KEY,
        CODE VARCHAR(50),
        NAAM VARCHAR(80),
        OMSCHRIJVING TEXT,
        SCHAAL VARCHAR(20),
        TAKEN TEXT
);

CREATE TABLE KP_SLLCTTGSPRK (
    KP_SLLCTTGSPRK_ID VARCHAR(255) PRIMARY KEY,
    SOLLICITATIEGESPREK_ID VARCHAR(255),
    SOLLICITANT_ID VARCHAR(255)
);

CREATE TABLE SOLLICITANT (
    SOLLICITANT_ID VARCHAR(255) PRIMARY KEY,
        SOLLICITEERT_OP_FUNCTIE_SOLLICITATIE_ID VARCHAR(255)
);

CREATE TABLE SOLLICITATIE (
    SOLLICITATIE_ID VARCHAR(255) PRIMARY KEY,
        DATUM DATE,
        OP_VACATURE_VACATURE_ID VARCHAR(255)
);

CREATE TABLE SOLLICITATIEGESPREK (
    SOLLICITATIEGESPREK_ID VARCHAR(255) PRIMARY KEY,
        AANGENOMEN BOOLEAN,
        DATUM DATE,
        IN_KADER_VAN_SOLLICITATIE_ID VARCHAR(255),
        OPMERKINGEN TEXT,
        VOLGENDGESPREK BOOLEAN
);

CREATE TABLE VACATURE (
    VACATURE_ID VARCHAR(255) PRIMARY KEY,
        DATUMGESLOTEN DATE,
        DATUMOPENGESTELD DATE,
        DEELTIJD TIMESTAMP,
        EXTERN BOOLEAN,
        INTERN BOOLEAN,
        VACATURETEKST_DOCUMENT_ID VARCHAR(255),
        VACATURE_BIJ_FUNCTIE_FUNCTIE_ID VARCHAR(255),
        VASTEDIENST BOOLEAN
);

CREATE TABLE WERKNEMER (
    WERKNEMER_ID VARCHAR(255) PRIMARY KEY,
        GEBOORTEDATUM DATE,
        NAAM VARCHAR(80),
        PERSONEELSDOSSIER_DOCUMENT_ID VARCHAR(255),
        SOLLICITEERT_SOLLICITATIE_ID VARCHAR(255),
        VOORNAAM VARCHAR(255),
        WOONPLAATS VARCHAR(50)
);

ALTER TABLE KP_SLLCTTGSPRK ADD CONSTRAINT FK_KP_SLLCTTGSPRK_1 FOREIGN KEY (SOLLICITATIEGESPREK_ID) REFERENCES SOLLICITATIEGESPREK (SOLLICITATIEGESPREK_ID);
-- SOLLICITATIEGESPREK (many-to-many junction, Connector_ID: 436)

ALTER TABLE KP_SLLCTTGSPRK ADD CONSTRAINT FK_KP_SLLCTTGSPRK_2 FOREIGN KEY (WERKNEMER_ID) REFERENCES WERKNEMER (WERKNEMER_ID);
-- WERKNEMER (many-to-many junction, Connector_ID: 436)

ALTER TABLE KP_SLLCTTGSPRK ADD CONSTRAINT FK_KP_SLLCTTGSPRK_1 FOREIGN KEY (SOLLICITATIEGESPREK_ID) REFERENCES SOLLICITATIEGESPREK (SOLLICITATIEGESPREK_ID);
-- SOLLICITATIEGESPREK (many-to-many junction, Connector_ID: 440)

ALTER TABLE KP_SLLCTTGSPRK ADD CONSTRAINT FK_KP_SLLCTTGSPRK_2 FOREIGN KEY (SOLLICITANT_ID) REFERENCES SOLLICITANT (SOLLICITANT_ID);
-- SOLLICITANT (many-to-many junction, Connector_ID: 440)

ALTER TABLE SOLLICITANT ADD CONSTRAINT FK_SOLLICITANT_SOLLICITEERT_OP_FUNCTIE FOREIGN KEY (SOLLICITEERT_OP_FUNCTIE_SOLLICITATIE_ID) REFERENCES SOLLICITATIE (SOLLICITATIE_ID);
-- SOLLICITEERT_OP_FUNCTIE (1 to 0..*, Connector_ID: 441)

ALTER TABLE SOLLICITATIE ADD CONSTRAINT FK_SOLLICITATIE_OP_VACATURE FOREIGN KEY (OP_VACATURE_VACATURE_ID) REFERENCES VACATURE (VACATURE_ID);
-- OP_VACATURE (0..* to 1, Connector_ID: 439)

ALTER TABLE SOLLICITATIEGESPREK ADD CONSTRAINT FK_SOLLICITATIEGESPREK_IN_KADER_VAN FOREIGN KEY (IN_KADER_VAN_SOLLICITATIE_ID) REFERENCES SOLLICITATIE (SOLLICITATIE_ID);
-- IN_KADER_VAN (0..* to 1, Connector_ID: 438)

ALTER TABLE VACATURE ADD CONSTRAINT FK_VACATURE_VACATURETEKST FOREIGN KEY (VACATURETEKST_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- VACATURETEKST (None to None, Connector_ID: 108)

ALTER TABLE VACATURE ADD CONSTRAINT FK_VACATURE_VACATURE_BIJ_FUNCTIE FOREIGN KEY (VACATURE_BIJ_FUNCTIE_FUNCTIE_ID) REFERENCES FUNCTIE (FUNCTIE_ID);
-- VACATURE_BIJ_FUNCTIE (0..* to 1, Connector_ID: 460)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_PERSONEELSDOSSIER FOREIGN KEY (PERSONEELSDOSSIER_DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
-- PERSONEELSDOSSIER (None to None, Connector_ID: 107)

ALTER TABLE WERKNEMER ADD CONSTRAINT FK_WERKNEMER_SOLLICITEERT FOREIGN KEY (SOLLICITEERT_SOLLICITATIE_ID) REFERENCES SOLLICITATIE (SOLLICITATIE_ID);
-- SOLLICITEERT (1 to 0..*, Connector_ID: 437)

