CREATE TABLE CLIENT (
    CLIENT_ID VARCHAR2(255) PRIMARY KEY,
        CODE VARCHAR2(80),
        GEZAGSDRAGERGEKEND NUMBER(1),
        HEEFT_REGELING_REGELING_ID VARCHAR2(255),
        HEEFT_VOORZIENING_INKOMENSVOORZIENING_ID VARCHAR2(255),
        IS_PARTNER_VAN_INKOMENSVOORZIENING_ID VARCHAR2(255),
        JURIDISCHESTATUS VARCHAR2(80),
        WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE COMPONENT (
    COMPONENT_ID VARCHAR2(255) PRIMARY KEY,
        BEDRAG NUMBER(10,2),
        BEGINDATUMBETREKKINGOP DATE,
        DEBETCREDIT VARCHAR2(50),
        EINDATUMBETREKKINGOP DATE,
        GROEP VARCHAR2(50),
        GROEPCODE VARCHAR2(20),
        GROOTBOEKCODE VARCHAR2(50),
        GROOTBOEKOMSCHRIJVING VARCHAR2(100),
        HEEFT_UITKERINGSRUN_ID VARCHAR2(255),
        IS_VAN_SOORT_COMPONENTSOORT_ID VARCHAR2(255),
        KOSTENPLAATS NUMBER(10,2),
        OMSCHRIJVING VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(50),
        TOELICHTING VARCHAR2(50)
);

CREATE TABLE COMPONENTSOORT (
    COMPONENTSOORT_ID VARCHAR2(255) PRIMARY KEY,
        COMPONENTCODE VARCHAR2(50),
        KOLOM VARCHAR2(50),
        KOLOMCODE VARCHAR2(50),
        OMSCHRIJVING CLOB,
        REGELING VARCHAR2(100),
        REGELINGCODE VARCHAR2(50)
);

CREATE TABLE INKOMENSVOORZIENING (
    INKOMENSVOORZIENING_ID VARCHAR2(255) PRIMARY KEY,
        ADMINISTRATIEVEEINDDATUM DATE,
        ADMINISTRATIEVESTARTDATUM DATE,
        BEDRAG NUMBER(10,2),
        BETALINGSMOMENTCODE VARCHAR2(255),
        CODE VARCHAR2(255),
        DATUMTOEKENNING DATE,
        EENMALIG NUMBER(1),
        EINDDATUM DATE,
        GROEP VARCHAR2(100),
        INDICATIEBLOKKERING NUMBER(1),
        INDICATIESTUDIETOESLAG NUMBER(1),
        INDICATIEUITKERINGSPLITSEN NUMBER(1),
        INDICATIEUITKERINGSSPECIFICATIE NUMBER(1),
        INGANGSDATUM DATE,
        IS_OPGEBOUWD_UIT_COMPONENT_ID VARCHAR2(255),
        TOEKENNINGSDATUM DATE,
        VERSTERKKINGSVORM VARCHAR2(200),
        VERWERKTTOTENMETDATUM DATE
);

CREATE TABLE INKOMENSVOORZIENINGSOORT (
    INKOMENSVOORZIENINGSOORT_ID VARCHAR2(255) PRIMARY KEY,
        CODE VARCHAR2(20),
        IS_SOORT_VOORZIENING_INKOMENSVOORZIENING_ID VARCHAR2(255),
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB,
        REGELING VARCHAR2(200),
        REGELINGSCODE VARCHAR2(20),
        VERGOEDING VARCHAR2(200),
        VERGOEDINGSCODE VARCHAR2(20),
        WET VARCHAR2(255)
);

CREATE TABLE KP_CLNT (
    KP_CLNT_ID VARCHAR2(255) PRIMARY KEY,
    CLIENT_ID VARCHAR2(255),
    INKOMENSVOORZIENING_ID VARCHAR2(255)
);

CREATE TABLE REGELING (
    REGELING_ID VARCHAR2(255) PRIMARY KEY,
        EINDDATUM DATE,
        IS_REGELINGSOORT_REGELINGSOORT_ID VARCHAR2(255),
        OMSCHRIJVING CLOB,
        STARTDATUM DATE,
        TOEKENNINGSDATUM DATE
);

CREATE TABLE REGELINGSOORT (
    REGELINGSOORT_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE UITKERINGSRUN (
    UITKERINGSRUN_ID VARCHAR2(255) PRIMARY KEY,
        DATUMRUN DATE,
        FREQUENTIE VARCHAR2(20),
        PERIODERUN VARCHAR2(255),
        SOORTRUN VARCHAR2(50)
);

ALTER TABLE KP_CLNT ADD CONSTRAINT FK_KP_CLNT_1 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);
-- CLIENT (many-to-many junction, Connector_ID: 952)

ALTER TABLE KP_CLNT ADD CONSTRAINT FK_KP_CLNT_2 FOREIGN KEY (INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- INKOMENSVOORZIENING (many-to-many junction, Connector_ID: 952)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT_REGELING FOREIGN KEY (HEEFT_REGELING_REGELING_ID) REFERENCES REGELING (REGELING_ID);
-- HEEFT_REGELING (1 to 0..*, Connector_ID: 1485)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_HEEFT_VOORZIENING FOREIGN KEY (HEEFT_VOORZIENING_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- HEEFT_VOORZIENING (1 to 1, Connector_ID: 1489)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_IS_PARTNER_VAN FOREIGN KEY (IS_PARTNER_VAN_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- IS_PARTNER_VAN (0 to 1, Connector_ID: 956)

ALTER TABLE COMPONENT ADD CONSTRAINT FK_COMPONENT_HEEFT FOREIGN KEY (HEEFT_UITKERINGSRUN_ID) REFERENCES UITKERINGSRUN (UITKERINGSRUN_ID);
-- HEEFT (1..* to 1, Connector_ID: 1483)

ALTER TABLE COMPONENT ADD CONSTRAINT FK_COMPONENT_IS_VAN_SOORT FOREIGN KEY (IS_VAN_SOORT_COMPONENTSOORT_ID) REFERENCES COMPONENTSOORT (COMPONENTSOORT_ID);
-- IS_VAN_SOORT (1..* to 1, Connector_ID: 1487)

ALTER TABLE INKOMENSVOORZIENING ADD CONSTRAINT FK_INKOMENSVOORZIENING_IS_OPGEBOUWD_UIT FOREIGN KEY (IS_OPGEBOUWD_UIT_COMPONENT_ID) REFERENCES COMPONENT (COMPONENT_ID);
-- IS_OPGEBOUWD_UIT (1 to 1..*, Connector_ID: 1491)

ALTER TABLE INKOMENSVOORZIENINGSOORT ADD CONSTRAINT FK_INKOMENSVOORZIENINGSOORT_IS_SOORT_VOORZIENING FOREIGN KEY (IS_SOORT_VOORZIENING_INKOMENSVOORZIENING_ID) REFERENCES INKOMENSVOORZIENING (INKOMENSVOORZIENING_ID);
-- IS_SOORT_VOORZIENING (1 to 0..*, Connector_ID: 1490)

ALTER TABLE REGELING ADD CONSTRAINT FK_REGELING_IS_REGELINGSOORT FOREIGN KEY (IS_REGELINGSOORT_REGELINGSOORT_ID) REFERENCES REGELINGSOORT (REGELINGSOORT_ID);
-- IS_REGELINGSOORT (0..* to 1, Connector_ID: 1488)

