CREATE TABLE `ONDERWERP` (
    `ONDERWERP_ID` INT PRIMARY KEY,
    `HOOFDONDERWERP_ONDERWERP_ID` INT,
    `ISACTIEF` BOOLEAN,
    `NAAM` VARCHAR(80),
    `TOELICHTING` TEXT
) ENGINE=InnoDB;

CREATE TABLE `PRODUCTOFDIENST` (
    `PRODUCTOFDIENST_ID` INT PRIMARY KEY,
    `AFHANDELTIJD` DATETIME,
    `INGEBRUIK` BOOLEAN,
    `NAAM` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `AFSPRAAKSTATUS` (
    `AFSPRAAKSTATUS_ID` INT PRIMARY KEY,
    `STATUS` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `FORMULIERSOORTVELD` (
    `FORMULIERSOORTVELD_ID` INT PRIMARY KEY,
    `HELPTEKST` TEXT,
    `ISVERPLICHT` BOOLEAN,
    `LABEL` VARCHAR(80),
    `MAXLENGTE` INT,
    `VELDNAAM` VARCHAR(255),
    `VELDTYPE` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `TELEFOONSTATUS` (
    `TELEFOONSTATUS_ID` INT PRIMARY KEY,
    `CONTACTCONNECTIONSTATE` VARCHAR(20),
    `STATUS` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `FORMULIERSOORT` (
    `FORMULIERSOORT_ID` INT PRIMARY KEY,
    `HEEFT_VELDEN_FORMULIERSOORTVELD_ID` INT,
    `INGEBRUIK` BOOLEAN,
    `NAAM` VARCHAR(80),
    `ONDERWERP` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `AANVRAAGDATA` (
    `AANVRAAGDATA_ID` INT PRIMARY KEY,
    `DATA` VARCHAR(255),
    `IS_CONFORM_FORMULIERSOORTVELD_ID` INT,
    `VELD` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `AANVRAAGOFMELDING` (
    `AANVRAAGOFMELDING_ID` INT PRIMARY KEY,
    `AANVRAAG_MET__FORMULIERSOORT_ID` INT,
    `AFGEHANDELD` BOOLEAN,
    `CATEGORIE` VARCHAR(200),
    `CATEGORIECODE` VARCHAR(80),
    `DATUMAANMAAK` DATE,
    `DATUMAFHANDELING` DATE,
    `DATUMBEGINSTATUS` DATE,
    `DATUMEINDESTATUS` DATE,
    `HEEFT_DATA_AANVRAAGDATA_ID` INT,
    `HOOFDCATEGORIE` VARCHAR(80),
    `HOOFDCATEGORIECODE` VARCHAR(80),
    `IDENTIFICATIE` VARCHAR(255),
    `KANAAL` VARCHAR(80),
    `ONDERWERP` VARCHAR(200),
    `ONDERWERPCODE` VARCHAR(80),
    `SOORT` VARCHAR(80),
    `STATUS` VARCHAR(80),
    `STATUSCODE` VARCHAR(80),
    `STATUSVOLGORDE` VARCHAR(80),
    `SUBCATEGORIE` VARCHAR(200),
    `SUBCATEGORIECODE` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `KP_ANVRGFMLDNG_ONDRWRP` (
    `KP_ANVRGFMLDNG_ONDRWRP_ID` INT PRIMARY KEY,
    `AANVRAAGOFMELDING_ID` INT,
    `ONDERWERP_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `KLANTCONTACT` (
    `KLANTCONTACT_ID` INT PRIMARY KEY,
    `EINDTIJD` DATETIME,
    `KANAAL` VARCHAR(20),
    `KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID` INT,
    `NOTITIE` TEXT,
    `STARTTIJD` DATETIME,
    `TIJDSDUUR` DATETIME,
    `TOELICHTING` TEXT,
    `WACHTTIJDTOTAAL` DATETIME
) ENGINE=InnoDB;

CREATE TABLE `TELEFOONTJE` (
    `TELEFOONTJE_ID` INT PRIMARY KEY,
    `AFHANDELTIJDNAGESPREK` DATETIME,
    `DELTAISDNCONNECTIE` INT,
    `EINDTIJD` DATETIME,
    `HEEFT_TELEFOONSTATUS_ID` INT,
    `MONDT_UIT_IN_KLANTCONTACT_ID` INT,
    `STARTTIJD` DATETIME,
    `TOTALEONHOLDTIJD` DATETIME,
    `TOTALESPREEKTIJD` DATETIME,
    `TOTALETIJDSDUUR` DATETIME,
    `TOTALEWACHTTIJD` DATETIME,
    `TRACKID` VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE `KP_KLNTCNTCT_PRDCTFDNST` (
    `KP_KLNTCNTCT_PRDCTFDNST_ID` INT PRIMARY KEY,
    `KLANTCONTACT_ID` INT,
    `PRODUCTOFDIENST_ID` INT
) ENGINE=InnoDB;

CREATE TABLE `BALIEAFSPRAAK` (
    `BALIEAFSPRAAK_ID` INT PRIMARY KEY,
    `EINDTIJDGEPLAND` DATETIME,
    `HEEFT_AFSPRAAKSTATUS_ID` INT,
    `MONDT_UIT_IN_KLANTCONTACT_ID` INT,
    `NOTITIE` TEXT,
    `STARTTIJDGEPLAND` DATETIME,
    `TIJDAANGEMAAKT` DATETIME,
    `TIJDSDUURGEPLAND` DATETIME,
    `TOELICHTING` TEXT,
    `WACHTTIJDNASTARTAFSPRAAK` DATETIME,
    `WACHTTIJDTOTAAL` DATETIME,
    `WACHTTIJDVOORSTARTAFSPRAAK` DATETIME,
    `WERKELIJKETIJDSDUUR` DATETIME
) ENGINE=InnoDB;

CREATE TABLE `TELEFOONONDERWERP` (
    `TELEFOONONDERWERP_ID` INT PRIMARY KEY,
    `HEEFT_KLANTCONTACT_ID` INT,
    `HEEFT_TELEFOONTJE_ID` INT,
    `ONDERWERP` VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE `KP_BLFSPRK_PRDCTFDNST` (
    `KP_BLFSPRK_PRDCTFDNST_ID` INT PRIMARY KEY,
    `BALIEAFSPRAAK_ID` INT,
    `PRODUCTOFDIENST_ID` INT
) ENGINE=InnoDB;

ALTER TABLE `KP_BLFSPRK_PRDCTFDNST` ADD CONSTRAINT FK_KP_BLFSPRK_PRDCTFDNST_1 FOREIGN KEY (`BALIEAFSPRAAK_ID`) REFERENCES `BALIEAFSPRAAK` (`BALIEAFSPRAAK_ID`);
-- BALIEAFSPRAAK (many-to-many junction, Connector_ID: 371)

ALTER TABLE `KP_BLFSPRK_PRDCTFDNST` ADD CONSTRAINT FK_KP_BLFSPRK_PRDCTFDNST_2 FOREIGN KEY (`PRODUCTOFDIENST_ID`) REFERENCES `PRODUCTOFDIENST` (`PRODUCTOFDIENST_ID`);
-- PRODUCTOFDIENST (many-to-many junction, Connector_ID: 371)

ALTER TABLE `KP_ANVRGFMLDNG_ONDRWRP` ADD CONSTRAINT FK_KP_ANVRGFMLDNG_ONDRWRP_1 FOREIGN KEY (`AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- AANVRAAGOFMELDING (many-to-many junction, Connector_ID: 381)

ALTER TABLE `KP_ANVRGFMLDNG_ONDRWRP` ADD CONSTRAINT FK_KP_ANVRGFMLDNG_ONDRWRP_2 FOREIGN KEY (`ONDERWERP_ID`) REFERENCES `ONDERWERP` (`ONDERWERP_ID`);
-- ONDERWERP (many-to-many junction, Connector_ID: 381)

ALTER TABLE `KP_KLNTCNTCT_PRDCTFDNST` ADD CONSTRAINT FK_KP_KLNTCNTCT_PRDCTFDNST_1 FOREIGN KEY (`KLANTCONTACT_ID`) REFERENCES `KLANTCONTACT` (`KLANTCONTACT_ID`);
-- KLANTCONTACT (many-to-many junction, Connector_ID: 2055)

ALTER TABLE `KP_KLNTCNTCT_PRDCTFDNST` ADD CONSTRAINT FK_KP_KLNTCNTCT_PRDCTFDNST_2 FOREIGN KEY (`PRODUCTOFDIENST_ID`) REFERENCES `PRODUCTOFDIENST` (`PRODUCTOFDIENST_ID`);
-- PRODUCTOFDIENST (many-to-many junction, Connector_ID: 2055)

ALTER TABLE `TELEFOONTJE` ADD CONSTRAINT FK_TELEFOONTJE_MONDT_UIT_IN FOREIGN KEY (`MONDT_UIT_IN_KLANTCONTACT_ID`) REFERENCES `KLANTCONTACT` (`KLANTCONTACT_ID`);
-- MONDT_UIT_IN (0..1 to 0..*, Connector_ID: 356)

ALTER TABLE `TELEFOONTJE` ADD CONSTRAINT FK_TELEFOONTJE_HEEFT FOREIGN KEY (`HEEFT_TELEFOONSTATUS_ID`) REFERENCES `TELEFOONSTATUS` (`TELEFOONSTATUS_ID`);
-- HEEFT (0..* to 1, Connector_ID: 357)

ALTER TABLE `TELEFOONONDERWERP` ADD CONSTRAINT FK_TELEFOONONDERWERP_HEEFT FOREIGN KEY (`HEEFT_TELEFOONTJE_ID`) REFERENCES `TELEFOONTJE` (`TELEFOONTJE_ID`);
-- HEEFT (0..1 to 0..*, Connector_ID: 358)

ALTER TABLE `TELEFOONONDERWERP` ADD CONSTRAINT FK_TELEFOONONDERWERP_HEEFT_2 FOREIGN KEY (`HEEFT_KLANTCONTACT_ID`) REFERENCES `KLANTCONTACT` (`KLANTCONTACT_ID`);
-- HEEFT (0..1 to 0..*, Connector_ID: 359)

ALTER TABLE `ONDERWERP` ADD CONSTRAINT FK_ONDERWERP_HOOFDONDERWERP FOREIGN KEY (`HOOFDONDERWERP_ONDERWERP_ID`) REFERENCES `ONDERWERP` (`ONDERWERP_ID`);
-- HOOFDONDERWERP (0..* to 1, Connector_ID: 361)

ALTER TABLE `FORMULIERSOORT` ADD CONSTRAINT FK_FORMULIERSOORT_HEEFT_VELDEN FOREIGN KEY (`HEEFT_VELDEN_FORMULIERSOORTVELD_ID`) REFERENCES `FORMULIERSOORTVELD` (`FORMULIERSOORTVELD_ID`);
-- HEEFT_VELDEN (1 to 0..*, Connector_ID: 368)

ALTER TABLE `BALIEAFSPRAAK` ADD CONSTRAINT FK_BALIEAFSPRAAK_MONDT_UIT_IN FOREIGN KEY (`MONDT_UIT_IN_KLANTCONTACT_ID`) REFERENCES `KLANTCONTACT` (`KLANTCONTACT_ID`);
-- MONDT_UIT_IN (0..1 to 0..1, Connector_ID: 374)

ALTER TABLE `BALIEAFSPRAAK` ADD CONSTRAINT FK_BALIEAFSPRAAK_HEEFT FOREIGN KEY (`HEEFT_AFSPRAAKSTATUS_ID`) REFERENCES `AFSPRAAKSTATUS` (`AFSPRAAKSTATUS_ID`);
-- HEEFT (0..* to 1, Connector_ID: 375)

ALTER TABLE `AANVRAAGOFMELDING` ADD CONSTRAINT FK_AANVRAAGOFMELDING_AANVRAAG_MET_ FOREIGN KEY (`AANVRAAG_MET__FORMULIERSOORT_ID`) REFERENCES `FORMULIERSOORT` (`FORMULIERSOORT_ID`);
-- AANVRAAG_MET_ (0..* to 0..1, Connector_ID: 379)

ALTER TABLE `AANVRAAGOFMELDING` ADD CONSTRAINT FK_AANVRAAGOFMELDING_HEEFT_DATA FOREIGN KEY (`HEEFT_DATA_AANVRAAGDATA_ID`) REFERENCES `AANVRAAGDATA` (`AANVRAAGDATA_ID`);
-- HEEFT_DATA (1 to 0..*, Connector_ID: 382)

ALTER TABLE `AANVRAAGDATA` ADD CONSTRAINT FK_AANVRAAGDATA_IS_CONFORM FOREIGN KEY (`IS_CONFORM_FORMULIERSOORTVELD_ID`) REFERENCES `FORMULIERSOORTVELD` (`FORMULIERSOORTVELD_ID`);
-- IS_CONFORM (0..* to 1, Connector_ID: 383)

ALTER TABLE `KLANTCONTACT` ADD CONSTRAINT FK_KLANTCONTACT_KAN_LEIDEN_TOT FOREIGN KEY (`KAN_LEIDEN_TOT_AANVRAAGOFMELDING_ID`) REFERENCES `AANVRAAGOFMELDING` (`AANVRAAGOFMELDING_ID`);
-- KAN_LEIDEN_TOT (0..1 to 0..*, Connector_ID: 2057)

