CREATE TABLE `CLIENT` (
    `CLIENT_ID` INT PRIMARY KEY,
    `CODE` VARCHAR(80),
    `GEZAGSDRAGERGEKEND` BOOLEAN,
    `JURIDISCHESTATUS` VARCHAR(80),
    `WETTELIJKEVERTEGENWOORDIGING` VARCHAR(80)
) ENGINE=InnoDB;

CREATE TABLE `DAKLOOSHEID` (
    `DAKLOOSHEID_ID` INT PRIMARY KEY,
    `DATUMEIND` DATE,
    `DATUMSTART` DATE,
    `GEMEENTEOORSPRONG` VARCHAR(200),
    `HEEFT_CLIENT_ID` INT,
    `TOESTEMMINGGEMEENTELIJKBRIEFADRES` BOOLEAN,
    `TOESTEMMINGNACHTOPVANG` BOOLEAN
) ENGINE=InnoDB;

ALTER TABLE `DAKLOOSHEID` ADD CONSTRAINT FK_DAKLOOSHEID_HEEFT FOREIGN KEY (`HEEFT_CLIENT_ID`) REFERENCES `CLIENT` (`CLIENT_ID`);
-- HEEFT (1 to 0..*, Connector_ID: 1382)

