CREATE TABLE LEVERING (
    LEVERING_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(20),
    DATUMSTART DATE,
    DATUMSTOP DATE,
    EENHEID_ENUM_ID NUMBER,
    FREQUENTIE_ENUM_ID NUMBER,
    GELEVERDE_PRESTATIE_BESCHIKKING_ID NUMBER,
    GELEVERDE_ZORG_TOEWIJZING_ID NUMBER,
    LEVERDE_PRESTATIE_RECHTSPERSOON_ID NUMBER,
    OMVANG NUMBER,
    PRESTATIE_VOOR_RECHTSPERSOON_ID NUMBER,
    STOPREDEN CLOB,
    VOORZIENING_VOORZIENING_ID NUMBER
);

CREATE TABLE BESCHIKTE_VOORZIENING (
    BESCHIKTE_VOORZIENING_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(20),
    DATUMEINDE DATE,
    DATUMEINDEOORSPRONKELIJK DATE,
    DATUMSTART DATE,
    EENHEID_ENUM_ID NUMBER,
    FREQUENTIE_ENUM_ID NUMBER,
    HEEFT_LEVERINGSVORM_293_ID NUMBER,
    HEEFT_VOORZIENINGEN_BESCHIKKING_ID NUMBER,
    IS_VOORZIENING_VOORZIENING_ID NUMBER,
    LEVERINGSVORM_287_ENUM_ID NUMBER,
    OMVANG NUMBER,
    REDENEINDE DATE,
    STATUS VARCHAR2(50),
    TOEGEWEZEN_PRODUCT_TOEWIJZING_ID NUMBER,
    WET_ENUM_ID NUMBER
);

CREATE TABLE NATUURLIJKPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    AANDUIDINGNAAMGEBRUIK VARCHAR2(50),
    AANHEFAANSCHRIJVING VARCHAR2(50),
    ACADEMISCHETITEL VARCHAR2(80),
    ACHTERNAAM VARCHAR2(100),
    ADELLIJKETITELOFPREDIKAAT VARCHAR2(255),
    ANUMMER VARCHAR2(20),
    BIJZONDERNEDERLANDERSCHAP VARCHAR2(50),
    BURGERSERVICENUMMER VARCHAR2(255),
    DATUMGEBOORTE DATE,
    DATUMOVERLIJDEN DATE,
    GEBOORTELAND VARCHAR2(255),
    GEBOORTEPLAATS VARCHAR2(200),
    GESLACHTSAANDUIDING VARCHAR2(255),
    GESLACHTSNAAM VARCHAR2(200),
    GESLACHTSNAAMAANSCHRIJVING VARCHAR2(200),
    HANDLICHTING VARCHAR2(50),
    INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID NUMBER,
    INDICATIEOVERLEDEN_ENUM_ID NUMBER,
    LANDOVERLIJDEN VARCHAR2(255),
    NATIONALITEIT VARCHAR2(100),
    OVERLIJDENSPLAATS VARCHAR2(200),
    VOORLETTERSAANSCHRIJVING VARCHAR2(20),
    VOORNAMEN VARCHAR2(200),
    VOORNAMENAANSCHRIJVING VARCHAR2(200),
    VOORVOEGSELGESLACHTSNAAM VARCHAR2(80)
);

CREATE TABLE SOORT_VERWIJZER_ENUM (
    SOORT_VERWIJZER_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (1, 'GECERTIFICEERDE_INSTELLING');
INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (2, 'GEMEENTE');
INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (3, 'HUISARTS');
INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (4, 'JEUGDARTS');
INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (5, 'LEEG');
INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (6, 'MEDISCH_SPECIALIST');
INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (7, 'ONBEKEND');
INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (8, 'RECHTER_OFFICIER_VAN_JUSTITIE_FUNCTIONARIS_JUSTITIËLE_JEUGDINRICHTING');
INSERT INTO SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID, VALUE) VALUES (9, 'ZELFVERWIJZER_GEEN_VERWIJZER');

CREATE TABLE DECLARATIE (
    DECLARATIE_ID NUMBER PRIMARY KEY,
    DATUMDECLARATIE DATE,
    DECLARATIEBEDRAG NUMBER(10,2),
    DECLARATIESTATUS NUMBER,
    INGEDIEND_DOOR_RECHTSPERSOON_ID NUMBER
);

CREATE TABLE INGESCHREVENPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESHERKOMST VARCHAR2(255),
    ANUMMER VARCHAR2(20),
    BESCHRIJVINGLOCATIE VARCHAR2(200),
    BUITENLANDSREISDOCUMENT VARCHAR2(80),
    BURGERLIJKESTAAT VARCHAR2(255),
    DATUMBEGINGELDIGHEIDVERBLIJFPLAATS DATE,
    DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS DATE,
    DATUMINSCHRIJVINGGEMEENTE DATE,
    DATUMOPSCHORTINGBIJHOUDING DATE,
    DATUMVERTREKUITNEDERLAND DATE,
    DATUMVESTIGINGNEDERLAND DATE,
    GEMEENTEVANINSCHRIJVING VARCHAR2(80),
    GEZINSRELATIE VARCHAR2(255),
    INDICATIEGEHEIM_ENUM_ID NUMBER,
    INGEZETENE_ENUM_ID NUMBER,
    LANDWAARNAARVERTROKKEN VARCHAR2(255),
    LANDWAARVANDAANINGESCHREVEN VARCHAR2(255),
    OUDER1 VARCHAR2(255),
    OUDER2 VARCHAR2(255),
    OUDER_1_RECHTSPERSOON_ID NUMBER,
    OUDER_2_RECHTSPERSOON_ID NUMBER,
    PARTNERID VARCHAR2(255),
    REDENEINDEBEWONING DATE,
    REDENOPSCHORTINGBIJHOUDING VARCHAR2(200),
    SIGNALERINGREISDOCUMENT_ENUM_ID NUMBER,
    VERBLIJFSTITEL VARCHAR2(255)
);

CREATE TABLE KP_CLNTBGLDR_MDWRKR (
    KP_CLNTBGLDR_MDWRKR_ID NUMBER PRIMARY KEY,
    CLIENTBEGELEIDER_ID NUMBER,
    MEDEWERKER_ID NUMBER
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    AGBCODE VARCHAR2(255),
    LEVERANCIERSCODE VARCHAR2(255),
    NAAM VARCHAR2(200),
    SOORTLEVERANCIER VARCHAR2(80),
    SOORTLEVERANCIERCODE VARCHAR2(255)
);

CREATE TABLE KP_CLNTBGLDR_CLNT (
    KP_CLNTBGLDR_CLNT_ID NUMBER PRIMARY KEY,
    CLIENTBEGELEIDER_ID NUMBER,
    CLIENT_ID NUMBER
);

CREATE TABLE EENHEID_ENUM (
    EENHEID_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO EENHEID_ENUM (EENHEID_ENUM_ID, VALUE) VALUES (1, 'DAGDEEL_4_UUR_');
INSERT INTO EENHEID_ENUM (EENHEID_ENUM_ID, VALUE) VALUES (2, 'ETMAAL');
INSERT INTO EENHEID_ENUM (EENHEID_ENUM_ID, VALUE) VALUES (3, 'EUROS');
INSERT INTO EENHEID_ENUM (EENHEID_ENUM_ID, VALUE) VALUES (4, 'LEEG');
INSERT INTO EENHEID_ENUM (EENHEID_ENUM_ID, VALUE) VALUES (5, 'MINUUT');
INSERT INTO EENHEID_ENUM (EENHEID_ENUM_ID, VALUE) VALUES (6, 'ONBEKEND');
INSERT INTO EENHEID_ENUM (EENHEID_ENUM_ID, VALUE) VALUES (7, 'STUKS');
INSERT INTO EENHEID_ENUM (EENHEID_ENUM_ID, VALUE) VALUES (8, 'UUR');

CREATE TABLE BESCHIKKING (
    BESCHIKKING_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(20),
    COMMENTAAR VARCHAR2(200),
    DATUMAFGIFTE DATE,
    GEEFT_AF_MEDEWERKER_ID NUMBER,
    GRONDSLAGEN NUMBER,
    RECHTSPERSOON_ID NUMBER,
    WET_ENUM_ID NUMBER
);

CREATE TABLE DECLARATIEREGEL (
    DECLARATIEREGEL_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2),
    BETREFT_RECHTSPERSOON_ID NUMBER,
    CODE VARCHAR2(20),
    DATUMEINDE DATE,
    DATUMSTART DATE,
    IS_OP_BASIS_VAN_TOEWIJZING_ID NUMBER,
    IS_VOOR_BESCHIKKING_ID NUMBER,
    VALT_BINNEN_DECLARATIE_ID NUMBER
);

CREATE TABLE CLIENT (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(80),
    GEZAGSDRAGERGEKEND_ENUM_ID NUMBER,
    JURIDISCHESTATUS VARCHAR2(80),
    WETTELIJKEVERTEGENWOORDIGING VARCHAR2(80)
);

CREATE TABLE MELDING_EIGEN_BIJDRAGE (
    MELDING_EIGEN_BIJDRAGE_ID NUMBER PRIMARY KEY,
    BETREFT_BESCHIKKING_ID NUMBER,
    DATUMSTART DATE,
    DATUMSTOP DATE
);

CREATE TABLE LEVERINGSVORM_309_ENUM (
    LEVERINGSVORM_309_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO LEVERINGSVORM_309_ENUM (LEVERINGSVORM_309_ENUM_ID, VALUE) VALUES (1, 'LEEG');
INSERT INTO LEVERINGSVORM_309_ENUM (LEVERINGSVORM_309_ENUM_ID, VALUE) VALUES (2, 'ONBEKEND');
INSERT INTO LEVERINGSVORM_309_ENUM (LEVERINGSVORM_309_ENUM_ID, VALUE) VALUES (3, 'PGB');
INSERT INTO LEVERINGSVORM_309_ENUM (LEVERINGSVORM_309_ENUM_ID, VALUE) VALUES (4, 'ZIN');

CREATE TABLE PGB_TOEKENNING (
    PGB_TOEKENNING_ID NUMBER PRIMARY KEY,
    BETREFT_BESCHIKTE_VOORZIENING_ID NUMBER,
    BUDGET VARCHAR2(255),
    DATUMEINDE DATE,
    DATUMTOEKENNING DATE
);

CREATE TABLE VERZOEK_OM_TOEWIJZING (
    VERZOEK_OM_TOEWIJZING_ID NUMBER PRIMARY KEY,
    BESCHIKKINGSNUMMER VARCHAR2(255),
    BETREFT_RECHTSPERSOON_ID NUMBER,
    BETREFT_VOORZIENING_ID NUMBER,
    COMMENTAAR CLOB,
    DATUMEINDETOEWIJZING DATE,
    DATUMINGANGBESCHIKKING DATE,
    DATUMINGANGTOEWIJZING DATE,
    DATUMONTVANGST DATE,
    EENHEID_ENUM_ID NUMBER,
    FREQUENTIE_ENUM_ID NUMBER,
    LEIDT_TOT_BESCHIKKING_ID NUMBER,
    LEVERANCIER_RECHTSPERSOON_ID NUMBER,
    RAAMCONTRACT_ENUM_ID NUMBER,
    REFERENTIEAANBIEDER VARCHAR2(255),
    SOORTVERWIJZER_ENUM_ID NUMBER,
    VERWIJZER VARCHAR2(200),
    VOLUME NUMBER
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    ACHTERNAAM VARCHAR2(200),
    DATUMINDIENST DATE,
    DATUMUITDIENST DATE,
    EMAILADRES VARCHAR2(255),
    EXTERN_ENUM_ID NUMBER,
    FUNCTIE VARCHAR2(50),
    GESLACHTSAANDUIDING VARCHAR2(255),
    MEDEWERKERIDENTIFICATIE VARCHAR2(255),
    MEDEWERKERTOELICHTING VARCHAR2(255),
    ROEPNAAM VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20),
    VOORLETTERS VARCHAR2(20),
    VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE CONTRACT (
    CONTRACT_ID NUMBER PRIMARY KEY,
    AUTORISATIEGROEP VARCHAR2(200),
    BESCHRIJVING CLOB,
    BOVENLIGGEND_CONTRACT_ID NUMBER,
    CATEGORIE VARCHAR2(80),
    CLASSIFICATIE VARCHAR2(80),
    CONTRACTREVISIE NUMBER,
    DATUMCREATIE DATE,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    GROEP VARCHAR2(80),
    HEEFT_RECHTSPERSOON_ID NUMBER,
    INTERNCONTRACTID VARCHAR2(255),
    INTERNCONTRACTREVISIE NUMBER,
    OPMERKINGEN CLOB,
    STATUS VARCHAR2(80),
    TYPE VARCHAR2(80),
    VOORWAARDE VARCHAR2(80),
    ZOEKWOORDEN VARCHAR2(255)
);

CREATE TABLE FREQUENTIE_ENUM (
    FREQUENTIE_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID, VALUE) VALUES (1, 'BINNEN_GELDIGHEID_BESCHIKKING');
INSERT INTO FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID, VALUE) VALUES (2, 'LEEG');
INSERT INTO FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID, VALUE) VALUES (3, 'ONBEKEND');
INSERT INTO FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID, VALUE) VALUES (4, 'PER_4_WEKEN');
INSERT INTO FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID, VALUE) VALUES (5, 'PER_DAG');
INSERT INTO FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID, VALUE) VALUES (6, 'PER_JAAR');
INSERT INTO FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID, VALUE) VALUES (7, 'PER_MAAND');
INSERT INTO FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID, VALUE) VALUES (8, 'PER_WEEK');

CREATE TABLE BOOLEAN_ENUM (
    BOOLEAN_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (1, 'JA');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (2, 'LEEG');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (3, 'NEE');
INSERT INTO BOOLEAN_ENUM (BOOLEAN_ENUM_ID, VALUE) VALUES (4, 'ONBEKEND');

CREATE TABLE VOORZIENING (
    VOORZIENING_ID NUMBER PRIMARY KEY,
    AFHANDELWIJZE VARCHAR2(200),
    CODE VARCHAR2(20),
    NAAM VARCHAR2(80),
    OMSCHRIJVING CLOB,
    PRODUCTCODE VARCHAR2(255),
    VALT_BINNEN_VOORZIENINGSOORT_ID NUMBER,
    WET_ENUM_ID NUMBER
);

CREATE TABLE KP_CLNT_INGSCHRVNPRSN (
    KP_CLNT_INGSCHRVNPRSN_ID NUMBER PRIMARY KEY,
    CLIENT_ID NUMBER,
    INGESCHREVENPERSOON_ID NUMBER
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID NUMBER PRIMARY KEY,
    ADRESBINNENLAND VARCHAR2(255),
    ADRESBUITENLAND VARCHAR2(255),
    ADRESCORRESPONDENTIE VARCHAR2(100),
    EMAILADRES VARCHAR2(80),
    FAXNUMMER VARCHAR2(20),
    IDENTIFICATIE VARCHAR2(255),
    KVKNUMMER VARCHAR2(20),
    NAAM VARCHAR2(200),
    RECHTSVORM VARCHAR2(100),
    REKENINGNUMMER VARCHAR2(255),
    TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE TOEWIJZING (
    TOEWIJZING_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(20),
    COMMENTAAR CLOB,
    DATUMAANSCHAF DATE,
    DATUMEINDETOEWIJZING DATE,
    DATUMSTARTTOEWIJZING DATE,
    DATUMTOEWIJZING DATE,
    EENHEID_ENUM_ID NUMBER,
    FREQUENTIE_ENUM_ID NUMBER,
    LEVERT_VOORZIENING_RECHTSPERSOON_ID NUMBER,
    OMVANG VARCHAR2(255),
    REDENWIJZIGING NUMBER,
    TOEWIJZINGNUMMER VARCHAR2(255),
    TOEWIJZING_BESCHIKKING_ID NUMBER,
    WET_ENUM_ID NUMBER
);

CREATE TABLE BUDGETUITPUTTING (
    BUDGETUITPUTTING_ID NUMBER PRIMARY KEY,
    BETREFT_PGB_TOEKENNING_ID NUMBER,
    DATUM DATE,
    UITGENUTBEDRAG NUMBER(10,2)
);

CREATE TABLE LEVERINGSVORM_293 (
    LEVERINGSVORM_293_ID NUMBER PRIMARY KEY,
    LEVERINGSVORMCODE VARCHAR2(20),
    NAAM VARCHAR2(255),
    WET_ENUM_ID NUMBER
);

CREATE TABLE VOORZIENINGSOORT (
    VOORZIENINGSOORT_ID NUMBER PRIMARY KEY,
    CODE VARCHAR2(20),
    NAAM VARCHAR2(80),
    OMSCHRIJVING CLOB,
    PRODUCTCATEGORIE VARCHAR2(200),
    PRODUCTCATEGORIECODE VARCHAR2(20),
    PRODUCTCODE VARCHAR2(20),
    WET_ENUM_ID NUMBER
);

CREATE TABLE CLIENTBEGELEIDER (
    MEDEWERKER_ID NUMBER PRIMARY KEY,
    BEGELEIDERSCODE VARCHAR2(20)
);

CREATE TABLE TARIEF (
    TARIEF_ID NUMBER PRIMARY KEY,
    BEDRAG NUMBER(10,2),
    BEVAT_CONTRACT_ID NUMBER,
    DATUMEINDE DATE,
    DATUMSTART DATE,
    EENHEID_ENUM_ID NUMBER,
    HEEFT_RECHTSPERSOON_ID NUMBER,
    HEEFT_VOORZIENING_ID NUMBER,
    WET_ENUM_ID NUMBER
);

CREATE TABLE KP_LVRNCR_RCHTSPRSN (
    KP_LVRNCR_RCHTSPRSN_ID NUMBER PRIMARY KEY,
    LEVERANCIER_ID NUMBER,
    RECHTSPERSOON_ID NUMBER
);

CREATE TABLE KP_NTRLJKPRSN_RCHTSPRSN (
    KP_NTRLJKPRSN_RCHTSPRSN_ID NUMBER PRIMARY KEY,
    NATUURLIJKPERSOON_ID NUMBER,
    RECHTSPERSOON_ID NUMBER
);

CREATE TABLE KP_INGSCHRVNPRSN_NTRLJKPRSN (
    KP_INGSCHRVNPRSN_NTRLJKPRSN_ID NUMBER PRIMARY KEY,
    INGESCHREVENPERSOON_ID NUMBER,
    NATUURLIJKPERSOON_ID NUMBER
);

CREATE TABLE WET_ENUM (
    WET_ENUM_ID NUMBER PRIMARY KEY,
    VALUE VARCHAR2(255)
);

INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (1, 'ANDERE_WET');
INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (2, 'BIJZONDERE_BIJSTAND');
INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (3, 'I_O_A_W_I_O_A_Z_');
INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (4, 'JEUGDWET');
INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (5, 'LEEG');
INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (6, 'NIET_VAN_TOEPASSING');
INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (7, 'ONBEKEND');
INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (8, 'PARTICIPATIEWET_PW_I');
INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES (9, 'WMO');

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES INGESCHREVENPERSOON (RECHTSPERSOON_ID);
-- Generalization to INGESCHREVENPERSOON

ALTER TABLE CLIENTBEGELEIDER ADD CONSTRAINT FK_CLIENTBEGELEIDER_GEN_MEDEWERKER FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- Generalization to MEDEWERKER

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- Generalization to NATUURLIJKPERSOON

ALTER TABLE KP_LVRNCR_RCHTSPRSN ADD CONSTRAINT FK_KP_LVRNCR_RCHTSPRSN_1 FOREIGN KEY (LEVERANCIER_ID) REFERENCES LEVERANCIER (RECHTSPERSOON_ID);
-- LEVERANCIER (many-to-many junction, Connector_ID: 927)

ALTER TABLE KP_LVRNCR_RCHTSPRSN ADD CONSTRAINT FK_KP_LVRNCR_RCHTSPRSN_2 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 927)

ALTER TABLE KP_CLNTBGLDR_MDWRKR ADD CONSTRAINT FK_KP_CLNTBGLDR_MDWRKR_1 FOREIGN KEY (CLIENTBEGELEIDER_ID) REFERENCES CLIENTBEGELEIDER (MEDEWERKER_ID);
-- CLIENTBEGELEIDER (many-to-many junction, Connector_ID: 940)

ALTER TABLE KP_CLNTBGLDR_MDWRKR ADD CONSTRAINT FK_KP_CLNTBGLDR_MDWRKR_2 FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- MEDEWERKER (many-to-many junction, Connector_ID: 940)

ALTER TABLE KP_CLNTBGLDR_CLNT ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_1 FOREIGN KEY (CLIENTBEGELEIDER_ID) REFERENCES CLIENTBEGELEIDER (MEDEWERKER_ID);
-- CLIENTBEGELEIDER (many-to-many junction, Connector_ID: 941)

ALTER TABLE KP_CLNTBGLDR_CLNT ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_2 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (RECHTSPERSOON_ID);
-- CLIENT (many-to-many junction, Connector_ID: 941)

ALTER TABLE KP_CLNT_INGSCHRVNPRSN ADD CONSTRAINT FK_KP_CLNT_INGSCHRVNPRSN_1 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (RECHTSPERSOON_ID);
-- CLIENT (many-to-many junction, Connector_ID: 958)

ALTER TABLE KP_CLNT_INGSCHRVNPRSN ADD CONSTRAINT FK_KP_CLNT_INGSCHRVNPRSN_2 FOREIGN KEY (INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (RECHTSPERSOON_ID);
-- INGESCHREVENPERSOON (many-to-many junction, Connector_ID: 958)

ALTER TABLE KP_INGSCHRVNPRSN_NTRLJKPRSN ADD CONSTRAINT FK_KP_INGSCHRVNPRSN_NTRLJKPRSN_1 FOREIGN KEY (INGESCHREVENPERSOON_ID) REFERENCES INGESCHREVENPERSOON (RECHTSPERSOON_ID);
-- INGESCHREVENPERSOON (many-to-many junction, Connector_ID: 1878)

ALTER TABLE KP_INGSCHRVNPRSN_NTRLJKPRSN ADD CONSTRAINT FK_KP_INGSCHRVNPRSN_NTRLJKPRSN_2 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1878)

ALTER TABLE KP_NTRLJKPRSN_RCHTSPRSN ADD CONSTRAINT FK_KP_NTRLJKPRSN_RCHTSPRSN_1 FOREIGN KEY (NATUURLIJKPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- NATUURLIJKPERSOON (many-to-many junction, Connector_ID: 1898)

ALTER TABLE KP_NTRLJKPRSN_RCHTSPRSN ADD CONSTRAINT FK_KP_NTRLJKPRSN_RCHTSPRSN_2 FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- RECHTSPERSOON (many-to-many junction, Connector_ID: 1898)

ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_BOVENLIGGEND FOREIGN KEY (BOVENLIGGEND_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- BOVENLIGGEND (0..* to 0..1, Connector_ID: 405)

ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_HEEFT FOREIGN KEY (HEEFT_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- HEEFT (1 to 0..*, Connector_ID: 926)

ALTER TABLE VOORZIENING ADD CONSTRAINT FK_VOORZIENING_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_VOORZIENINGSOORT_ID) REFERENCES VOORZIENINGSOORT (VOORZIENINGSOORT_ID);
-- VALT_BINNEN (0..* to 1, Connector_ID: 1031)

ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_BETREFT FOREIGN KEY (BETREFT_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- BETREFT (0..* to 1, Connector_ID: 1032)

ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_LEVERANCIER FOREIGN KEY (LEVERANCIER_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- LEVERANCIER (0..* to 1, Connector_ID: 1033)

ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_BETREFT_2 FOREIGN KEY (BETREFT_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- BETREFT (0..* to 1, Connector_ID: 1034)

ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_LEVERT_VOORZIENING FOREIGN KEY (LEVERT_VOORZIENING_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- LEVERT_VOORZIENING (0..* to 0..1, Connector_ID: 1038)

ALTER TABLE TARIEF ADD CONSTRAINT FK_TARIEF_HEEFT FOREIGN KEY (HEEFT_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- HEEFT (1 to 1..*, Connector_ID: 1040)

ALTER TABLE TARIEF ADD CONSTRAINT FK_TARIEF_BEVAT FOREIGN KEY (BEVAT_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- BEVAT (1 to 0..*, Connector_ID: 1041)

ALTER TABLE TARIEF ADD CONSTRAINT FK_TARIEF_HEEFT_2 FOREIGN KEY (HEEFT_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- HEEFT (0..* to 1, Connector_ID: 1042)

ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_LEVERDE_PRESTATIE FOREIGN KEY (LEVERDE_PRESTATIE_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- LEVERDE_PRESTATIE (1 to 0..*, Connector_ID: 1046)

ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_VOORZIENING FOREIGN KEY (VOORZIENING_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- VOORZIENING (0..* to 1, Connector_ID: 1047)

ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_GELEVERDE_ZORG FOREIGN KEY (GELEVERDE_ZORG_TOEWIJZING_ID) REFERENCES TOEWIJZING (TOEWIJZING_ID);
-- GELEVERDE_ZORG (0..* to 0..1, Connector_ID: 1048)

ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_PRESTATIE_VOOR FOREIGN KEY (PRESTATIE_VOOR_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- PRESTATIE_VOOR (0..* to 0..1, Connector_ID: 1049)

ALTER TABLE DECLARATIEREGEL ADD CONSTRAINT FK_DECLARATIEREGEL_IS_OP_BASIS_VAN FOREIGN KEY (IS_OP_BASIS_VAN_TOEWIJZING_ID) REFERENCES TOEWIJZING (TOEWIJZING_ID);
-- IS_OP_BASIS_VAN (1 to 0..*, Connector_ID: 1052)

ALTER TABLE DECLARATIEREGEL ADD CONSTRAINT FK_DECLARATIEREGEL_BETREFT FOREIGN KEY (BETREFT_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- BETREFT (0..* to 1, Connector_ID: 1053)

ALTER TABLE DECLARATIEREGEL ADD CONSTRAINT FK_DECLARATIEREGEL_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_DECLARATIE_ID) REFERENCES DECLARATIE (DECLARATIE_ID);
-- VALT_BINNEN (0..* to 1, Connector_ID: 1054)

ALTER TABLE DECLARATIE ADD CONSTRAINT FK_DECLARATIE_INGEDIEND_DOOR FOREIGN KEY (INGEDIEND_DOOR_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- INGEDIEND_DOOR (0..* to 1, Connector_ID: 1055)

ALTER TABLE BUDGETUITPUTTING ADD CONSTRAINT FK_BUDGETUITPUTTING_BETREFT FOREIGN KEY (BETREFT_PGB_TOEKENNING_ID) REFERENCES PGB_TOEKENNING (PGB_TOEKENNING_ID);
-- BETREFT (1 to 0..*, Connector_ID: 1056)

ALTER TABLE PGB_TOEKENNING ADD CONSTRAINT FK_PGB_TOEKENNING_BETREFT FOREIGN KEY (BETREFT_BESCHIKTE_VOORZIENING_ID) REFERENCES BESCHIKTE_VOORZIENING (BESCHIKTE_VOORZIENING_ID);
-- BETREFT (0..* to 1, Connector_ID: 1058)

ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_HEEFT FOREIGN KEY (HEEFT_LEVERINGSVORM_293_ID) REFERENCES LEVERINGSVORM_293 (LEVERINGSVORM_293_ID);
-- HEEFT (0..* to 1, Connector_ID: 1059)

ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_TOEGEWEZEN_PRODUCT FOREIGN KEY (TOEGEWEZEN_PRODUCT_TOEWIJZING_ID) REFERENCES TOEWIJZING (TOEWIJZING_ID);
-- TOEGEWEZEN_PRODUCT (1..* to 0..1, Connector_ID: 1060)

ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_IS_VOORZIENING FOREIGN KEY (IS_VOORZIENING_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- IS_VOORZIENING (0..* to 1, Connector_ID: 1061)

ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_LEIDT_TOT FOREIGN KEY (LEIDT_TOT_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- LEIDT_TOT (0..* to 0..1, Connector_ID: 1062)

ALTER TABLE DECLARATIEREGEL ADD CONSTRAINT FK_DECLARATIEREGEL_IS_VOOR FOREIGN KEY (IS_VOOR_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- IS_VOOR (0..* to 1, Connector_ID: 1063)

ALTER TABLE BESCHIKKING ADD CONSTRAINT FK_BESCHIKKING_GEEFT_AF FOREIGN KEY (GEEFT_AF_MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- GEEFT_AF (1 to 0..*, Connector_ID: 1064)

ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_GELEVERDE_PRESTATIE FOREIGN KEY (GELEVERDE_PRESTATIE_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- GELEVERDE_PRESTATIE (0..* to 0..1, Connector_ID: 1065)

ALTER TABLE MELDING_EIGEN_BIJDRAGE ADD CONSTRAINT FK_MELDING_EIGEN_BIJDRAGE_BETREFT FOREIGN KEY (BETREFT_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- BETREFT (0..* to 1, Connector_ID: 1066)

ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_TOEWIJZING FOREIGN KEY (TOEWIJZING_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- TOEWIJZING (1 to 0..*, Connector_ID: 1067)

ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_HEEFT_VOORZIENINGEN FOREIGN KEY (HEEFT_VOORZIENINGEN_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- HEEFT_VOORZIENINGEN (1 to 1..*, Connector_ID: 1068)

ALTER TABLE BESCHIKKING ADD CONSTRAINT FK_BESCHIKKING_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- unnamed (0..* to 1, Connector_ID: 1069)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (OUDER_1_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- OUDER_1 (1 to 1, Connector_ID: 1871)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (OUDER_2_RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- OUDER_2 (1 to 1, Connector_ID: 1873)

ALTER TABLE BESCHIKKING ADD CONSTRAINT FK_BESCHIKKING_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID_WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_LEVERINGSVORM_287_ENUM_ID FOREIGN KEY (LEVERINGSVORM_287_ENUM_ID_LEVERINGSVORM_309_ENUM_ID) REFERENCES LEVERINGSVORM_309_ENUM (LEVERINGSVORM_309_ENUM_ID);
-- LEVERINGSVORM_287_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID_EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID_WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_FREQUENTIE_ENUM_ID FOREIGN KEY (FREQUENTIE_ENUM_ID_FREQUENTIE_ENUM_ID) REFERENCES FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID);
-- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID_EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_FREQUENTIE_ENUM_ID FOREIGN KEY (FREQUENTIE_ENUM_ID_FREQUENTIE_ENUM_ID) REFERENCES FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID);
-- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE LEVERINGSVORM_293 ADD CONSTRAINT FK_LEVERINGSVORM_293_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID_WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TARIEF ADD CONSTRAINT FK_TARIEF_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID_EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TARIEF ADD CONSTRAINT FK_TARIEF_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID_WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID_EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID_WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_FREQUENTIE_ENUM_ID FOREIGN KEY (FREQUENTIE_ENUM_ID_FREQUENTIE_ENUM_ID) REFERENCES FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID);
-- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_SOORTVERWIJZER_ENUM_ID FOREIGN KEY (SOORTVERWIJZER_ENUM_ID_SOORT_VERWIJZER_ENUM_ID) REFERENCES SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID);
-- SOORTVERWIJZER_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID_EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_RAAMCONTRACT_ENUM_ID FOREIGN KEY (RAAMCONTRACT_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- RAAMCONTRACT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_FREQUENTIE_ENUM_ID FOREIGN KEY (FREQUENTIE_ENUM_ID_FREQUENTIE_ENUM_ID) REFERENCES FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID);
-- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VOORZIENING ADD CONSTRAINT FK_VOORZIENING_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID_WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE VOORZIENINGSOORT ADD CONSTRAINT FK_VOORZIENINGSOORT_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID_WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_GEZAGSDRAGERGEKEND_ENUM_ID FOREIGN KEY (GEZAGSDRAGERGEKEND_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- GEZAGSDRAGERGEKEND_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_EXTERN_ENUM_ID FOREIGN KEY (EXTERN_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- EXTERN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEOVERLEDEN_ENUM_ID FOREIGN KEY (INDICATIEOVERLEDEN_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEOVERLEDEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID FOREIGN KEY (INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_INGEZETENE_ENUM_ID FOREIGN KEY (INGEZETENE_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INGEZETENE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_INDICATIEGEHEIM_ENUM_ID FOREIGN KEY (INDICATIEGEHEIM_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- INDICATIEGEHEIM_ENUM_ID (1 to 1, Connector_ID: enum_ref)

ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_SIGNALERINGREISDOCUMENT_ENUM_ID FOREIGN KEY (SIGNALERINGREISDOCUMENT_ENUM_ID_BOOLEAN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- SIGNALERINGREISDOCUMENT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

