CREATE TABLE BELANGHEBBENDE (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        DATUMSTART DATE,
        DATUMTOT DATE
);

CREATE TABLE BELANGTYPE (
    BELANGTYPE_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE BRUIKLEEN (
    BRUIKLEEN_ID VARCHAR2(255) PRIMARY KEY,
        AANVRAAGDOOR VARCHAR2(80),
        DATUMAANVRAAG DATE,
        DATUMEINDE DATE,
        DATUMSTART DATE,
        TOESTEMMINGDOOR VARCHAR2(80)
);

CREATE TABLE COLLECTIE (
    COLLECTIE_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE HISTORISCH_PERSOON_ (
    HISTORISCH_PERSOON__ID VARCHAR2(255) PRIMARY KEY,
        BEROEP VARCHAR2(200),
        DATUMGEBOORTE DATE,
        DATUMOVERLIJDEN DATE,
        NAAM VARCHAR2(200),
        OMSCHRIJVING CLOB,
        PUBLIEKTOEGANKELIJK NUMBER(1),
        WOONDEOP VARCHAR2(50)
);

CREATE TABLE INCIDENT (
    INCIDENT_ID VARCHAR2(255) PRIMARY KEY,
        DATUM DATE,
        LOCATIE VARCHAR2(255),
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE KP_BRKLN (
    KP_BRKLN_ID VARCHAR2(255) PRIMARY KEY,
    BRUIKLEEN_ID VARCHAR2(255),
    TENTOONSTELLING_ID VARCHAR2(255)
);

CREATE TABLE KP_CLLCT (
    KP_CLLCT_ID VARCHAR2(255) PRIMARY KEY,
    COLLECTIE_ID VARCHAR2(255),
    MUSEUMOBJECT_ID VARCHAR2(255)
);

CREATE TABLE KP_INCDNT (
    KP_INCDNT_ID VARCHAR2(255) PRIMARY KEY,
    INCIDENT_ID VARCHAR2(255),
    MUSEUMOBJECT_ID VARCHAR2(255)
);

CREATE TABLE KP_LNR (
    KP_LNR_ID VARCHAR2(255) PRIMARY KEY,
    LENER_ID VARCHAR2(255),
    BRUIKLEEN_ID VARCHAR2(255)
);

CREATE TABLE KP_MSMBJCT (
    KP_MSMBJCT_ID VARCHAR2(255) PRIMARY KEY,
    MUSEUMOBJECT_ID VARCHAR2(255),
    BELANGHEBBENDE_ID VARCHAR2(255)
);

CREATE TABLE KP_SMNSTLLR (
    KP_SMNSTLLR_ID VARCHAR2(255) PRIMARY KEY,
    SAMENSTELLER_ID VARCHAR2(255),
    TENTOONSTELLING_ID VARCHAR2(255)
);

CREATE TABLE KP_TNTNSTLLNG (
    KP_TNTNSTLLNG_ID VARCHAR2(255) PRIMARY KEY,
    TENTOONSTELLING_ID VARCHAR2(255),
    HISTORISCH_PERSOON__ID VARCHAR2(255)
);

CREATE TABLE LENER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        OPMERKINGEN CLOB
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID VARCHAR2(255) PRIMARY KEY,
        ACHTERNAAM VARCHAR2(200),
        DATUMINDIENST DATE,
        DATUMUITDIENST DATE,
        EMAILADRES VARCHAR2(255),
        EXTERN VARCHAR2(255),
        FUNCTIE VARCHAR2(50),
        GESLACHTSAANDUIDING VARCHAR2(255),
        MEDEWERKERIDENTIFICATIE VARCHAR2(255),
        MEDEWERKERTOELICHTING VARCHAR2(255),
        ROEPNAAM VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20),
        VOORLETTERS VARCHAR2(20),
        VOORVOEGSELACHTERNAAM VARCHAR2(255)
);

CREATE TABLE MUSEUMOBJECT (
    MUSEUMOBJECT_ID VARCHAR2(255) PRIMARY KEY,
        AFMETING VARCHAR2(255),
        BETREFT_BRUIKLEEN_ID VARCHAR2(255),
        BEZITTOT DATE,
        BEZITVANAF DATE,
        LOCATIE_STANDPLAATS_ID VARCHAR2(255),
        MEDIUM VARCHAR2(255),
        VERKRIJGING VARCHAR2(255)
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        ADRESCORRESPONDENTIE VARCHAR2(100),
        EMAILADRES VARCHAR2(80),
        FAXNUMMER VARCHAR2(20),
        IDENTIFICATIE VARCHAR2(255),
        KVKNUMMER VARCHAR2(20),
        NAAM VARCHAR2(200),
        RECHTSVORM VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE ROL (
    ROL_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE SAMENSTELLER (
    MEDEWERKER_ID VARCHAR2(255) PRIMARY KEY,
        ROL VARCHAR2(80)
);

CREATE TABLE STANDPLAATS (
    STANDPLAATS_ID VARCHAR2(255) PRIMARY KEY,
        ADRES VARCHAR2(50),
        BESCHRIJVING VARCHAR2(255),
        NAAMINSTELLING VARCHAR2(80)
);

CREATE TABLE TENTOONSTELLING (
    TENTOONSTELLING_ID VARCHAR2(255) PRIMARY KEY,
        DATUMEINDE DATE,
        DATUMSTART DATE,
        OMSCHRIJVING CLOB,
        SUBTITEL VARCHAR2(200),
        TITEL VARCHAR2(80),
        ZAAL_ID VARCHAR2(255)
);

CREATE TABLE ZAAL (
    ZAAL_ID VARCHAR2(255) PRIMARY KEY,
        CAPACITEIT NUMBER,
        NAAM VARCHAR2(80),
        NUMMER NUMBER,
        OMSCHRIJVING CLOB
);

ALTER TABLE BELANGHEBBENDE ADD CONSTRAINT FK_BELANGHEBBENDE_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE LENER ADD CONSTRAINT FK_LENER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE SAMENSTELLER ADD CONSTRAINT FK_SAMENSTELLER_GEN_MEDEWERKER FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- Generalization to MEDEWERKER

ALTER TABLE KP_BRKLN ADD CONSTRAINT FK_KP_BRKLN_1 FOREIGN KEY (BRUIKLEEN_ID) REFERENCES BRUIKLEEN (BRUIKLEEN_ID);
-- BRUIKLEEN (many-to-many junction, Connector_ID: 1129)

ALTER TABLE KP_BRKLN ADD CONSTRAINT FK_KP_BRKLN_2 FOREIGN KEY (TENTOONSTELLING_ID) REFERENCES TENTOONSTELLING (TENTOONSTELLING_ID);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1129)

ALTER TABLE KP_CLLCT ADD CONSTRAINT FK_KP_CLLCT_1 FOREIGN KEY (COLLECTIE_ID) REFERENCES COLLECTIE (COLLECTIE_ID);
-- COLLECTIE (many-to-many junction, Connector_ID: 1126)

ALTER TABLE KP_CLLCT ADD CONSTRAINT FK_KP_CLLCT_2 FOREIGN KEY (MUSEUMOBJECT_ID) REFERENCES MUSEUMOBJECT (MUSEUMOBJECT_ID);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1126)

ALTER TABLE KP_INCDNT ADD CONSTRAINT FK_KP_INCDNT_1 FOREIGN KEY (INCIDENT_ID) REFERENCES INCIDENT (INCIDENT_ID);
-- INCIDENT (many-to-many junction, Connector_ID: 1122)

ALTER TABLE KP_INCDNT ADD CONSTRAINT FK_KP_INCDNT_2 FOREIGN KEY (MUSEUMOBJECT_ID) REFERENCES MUSEUMOBJECT (MUSEUMOBJECT_ID);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1122)

ALTER TABLE KP_LNR ADD CONSTRAINT FK_KP_LNR_1 FOREIGN KEY (LENER_ID) REFERENCES LENER (RECHTSPERSOON_ID);
-- LENER (many-to-many junction, Connector_ID: 1128)

ALTER TABLE KP_LNR ADD CONSTRAINT FK_KP_LNR_2 FOREIGN KEY (BRUIKLEEN_ID) REFERENCES BRUIKLEEN (BRUIKLEEN_ID);
-- BRUIKLEEN (many-to-many junction, Connector_ID: 1128)

ALTER TABLE KP_MSMBJCT ADD CONSTRAINT FK_KP_MSMBJCT_1 FOREIGN KEY (MUSEUMOBJECT_ID) REFERENCES MUSEUMOBJECT (MUSEUMOBJECT_ID);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1103)

ALTER TABLE KP_MSMBJCT ADD CONSTRAINT FK_KP_MSMBJCT_2 FOREIGN KEY (HISTORISCH_PERSOON__ID) REFERENCES HISTORISCH_PERSOON_ (HISTORISCH_PERSOON__ID);
-- HISTORISCH_PERSOON_ (many-to-many junction, Connector_ID: 1103)

ALTER TABLE KP_MSMBJCT ADD CONSTRAINT FK_KP_MSMBJCT_1 FOREIGN KEY (MUSEUMOBJECT_ID) REFERENCES MUSEUMOBJECT (MUSEUMOBJECT_ID);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1118)

ALTER TABLE KP_MSMBJCT ADD CONSTRAINT FK_KP_MSMBJCT_2 FOREIGN KEY (TENTOONSTELLING_ID) REFERENCES TENTOONSTELLING (TENTOONSTELLING_ID);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1118)

ALTER TABLE KP_MSMBJCT ADD CONSTRAINT FK_KP_MSMBJCT_1 FOREIGN KEY (MUSEUMOBJECT_ID) REFERENCES MUSEUMOBJECT (MUSEUMOBJECT_ID);
-- MUSEUMOBJECT (many-to-many junction, Connector_ID: 1130)

ALTER TABLE KP_MSMBJCT ADD CONSTRAINT FK_KP_MSMBJCT_2 FOREIGN KEY (BELANGHEBBENDE_ID) REFERENCES BELANGHEBBENDE (RECHTSPERSOON_ID);
-- BELANGHEBBENDE (many-to-many junction, Connector_ID: 1130)

ALTER TABLE KP_SMNSTLLR ADD CONSTRAINT FK_KP_SMNSTLLR_1 FOREIGN KEY (SAMENSTELLER_ID) REFERENCES SAMENSTELLER (MEDEWERKER_ID);
-- SAMENSTELLER (many-to-many junction, Connector_ID: 1100)

ALTER TABLE KP_SMNSTLLR ADD CONSTRAINT FK_KP_SMNSTLLR_2 FOREIGN KEY (TENTOONSTELLING_ID) REFERENCES TENTOONSTELLING (TENTOONSTELLING_ID);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1100)

ALTER TABLE KP_TNTNSTLLNG ADD CONSTRAINT FK_KP_TNTNSTLLNG_1 FOREIGN KEY (TENTOONSTELLING_ID) REFERENCES TENTOONSTELLING (TENTOONSTELLING_ID);
-- TENTOONSTELLING (many-to-many junction, Connector_ID: 1152)

ALTER TABLE KP_TNTNSTLLNG ADD CONSTRAINT FK_KP_TNTNSTLLNG_2 FOREIGN KEY (HISTORISCH_PERSOON__ID) REFERENCES HISTORISCH_PERSOON_ (HISTORISCH_PERSOON__ID);
-- HISTORISCH_PERSOON_ (many-to-many junction, Connector_ID: 1152)

ALTER TABLE MUSEUMOBJECT ADD CONSTRAINT FK_MUSEUMOBJECT_BETREFT FOREIGN KEY (BETREFT_BRUIKLEEN_ID) REFERENCES BRUIKLEEN (BRUIKLEEN_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1127)

ALTER TABLE MUSEUMOBJECT ADD CONSTRAINT FK_MUSEUMOBJECT_LOCATIE FOREIGN KEY (LOCATIE_STANDPLAATS_ID) REFERENCES STANDPLAATS (STANDPLAATS_ID);
-- LOCATIE (0..* to 0..1, Connector_ID: 1117)

ALTER TABLE TENTOONSTELLING ADD CONSTRAINT FK_TENTOONSTELLING_ZAAL FOREIGN KEY (ZAAL_ID) REFERENCES ZAAL (ZAAL_ID);
-- unnamed (None to None, Connector_ID: 1099)

