CREATE TABLE ACTIVITEITSOORT (
    ACTIVITEITSOORT_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE DOELGROEP (
    DOELGROEP_ID VARCHAR2(255) PRIMARY KEY,
        BESTAAT_UIT_DOELGROEP_ID VARCHAR2(255),
        BRANCH VARCHAR2(80),
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB,
        SEGMENT VARCHAR2(80)
);

CREATE TABLE KOSTENPLAATS (
    KOSTENPLAATS_ID VARCHAR2(255) PRIMARY KEY,
        BTWCODE VARCHAR2(255),
        BTWOMSCHRIJVING VARCHAR2(80),
        KOSTENPLAATSSOORTCODE NUMBER(10,2),
        KOSTENPLAATSSOORTOMSCHRIJVING NUMBER(10,2),
        KOSTENPLAATSTYPECODE NUMBER(10,2),
        KOSTENPLAATSTYPEOMSCHRIJVING NUMBER(10,2),
        NAAM VARCHAR2(80),
        OMSCHRIJVING VARCHAR2(200)
);

CREATE TABLE MAILING (
    MAILING_ID VARCHAR2(255) PRIMARY KEY,
        DATUM DATE,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE PROGRAMMASOORT (
    PROGRAMMASOORT_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE RECHTSPERSOON (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        ADRESBINNENLAND VARCHAR2(255),
        ADRESBUITENLAND VARCHAR2(255),
        ADRESCORRESPONDENTIE VARCHAR2(100),
        EMAILADRES VARCHAR2(80),
        FAXNUMMER VARCHAR2(20),
        IDENTIFICATIE VARCHAR2(255),
        KVKNUMMER VARCHAR2(20),
        NAAM VARCHAR2(200),
        RECHTSVORM VARCHAR2(100),
        REKENINGNUMMER VARCHAR2(255),
        TELEFOONNUMMER VARCHAR2(20)
);

CREATE TABLE LEVERANCIER (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        NAAM VARCHAR2(200),
        NUMMER VARCHAR2(255)
);

CREATE TABLE PRODUCTIE_EENHEID (
    PRODUCTIE_EENHEID_ID VARCHAR2(255) PRIMARY KEY,
        BETREFT_LEVERANCIER_ID VARCHAR2(255)
);

CREATE TABLE TENTOONSTELLING (
    TENTOONSTELLING_ID VARCHAR2(255) PRIMARY KEY,
        DATUMEINDE DATE,
        DATUMSTART DATE,
        OMSCHRIJVING CLOB,
        SUBTITEL VARCHAR2(200),
        TITEL VARCHAR2(80),
        ZAAL_ID VARCHAR2(255)
);

CREATE TABLE RONDLEIDING (
    RONDLEIDING_ID VARCHAR2(255) PRIMARY KEY,
        EINDTIJD TIMESTAMP,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB,
        STARTTIJD TIMESTAMP,
        VOOR_TENTOONSTELLING_ID VARCHAR2(255)
);

CREATE TABLE VOORZIENING (
    VOORZIENING_ID VARCHAR2(255) PRIMARY KEY,
        AANTALBESCHIKBAAR NUMBER,
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB
);

CREATE TABLE ZAAL (
    ZAAL_ID VARCHAR2(255) PRIMARY KEY,
        CAPACITEIT NUMBER,
        NAAM VARCHAR2(80),
        NUMMER NUMBER,
        OMSCHRIJVING CLOB
);

CREATE TABLE RESERVERING (
    RESERVERING_ID VARCHAR2(255) PRIMARY KEY,
        AANTAL NUMBER,
        BETREFT_PRODUCTIE_EENHEID_ID VARCHAR2(255),
        BETREFT_VOORZIENING_ID VARCHAR2(255),
        BETREFT_ZAAL_ID VARCHAR2(255),
        BTW VARCHAR2(255),
        TIJDTOT TIMESTAMP,
        TIJDVANAF TIMESTAMP,
        TOTAALPRIJS NUMBER(10,2)
);

CREATE TABLE ACTIVITEIT (
    ACTIVITEIT_ID VARCHAR2(255) PRIMARY KEY,
        AANTALPERSONEN NUMBER,
        BESTAAT_UIT_ACTIVITEIT_ID VARCHAR2(255),
        HEEFT_RESERVERING_ID VARCHAR2(255),
        HEEFT_RONDLEIDING_ID VARCHAR2(255),
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB,
        VAN_SOORT_ACTIVITEITSOORT_ID VARCHAR2(255)
);

CREATE TABLE PROGRAMMA (
    PROGRAMMA_ID VARCHAR2(255) PRIMARY KEY,
        BESTAAT_UIT_ACTIVITEIT_ID VARCHAR2(255),
        BTW VARCHAR2(255),
        EINDTIJD TIMESTAMP,
        HEEFT_KOSTENPLAATS_ID VARCHAR2(255),
        LOCATIE VARCHAR2(80),
        NAAM VARCHAR2(80),
        OMSCHRIJVING CLOB,
        PRIJSEXCLUSIEFBTW NUMBER(10,2),
        PUBLIEKSTAAK VARCHAR2(80),
        SCHOOLNIVEAU VARCHAR2(80),
        STARTTIJD TIMESTAMP
);

CREATE TABLE KP_PRGRMM (
    KP_PRGRMM_ID VARCHAR2(255) PRIMARY KEY,
    PROGRAMMA_ID VARCHAR2(255),
    PROGRAMMASOORT_ID VARCHAR2(255)
);

CREATE TABLE MUSEUMRELATIE (
    RECHTSPERSOON_ID VARCHAR2(255) PRIMARY KEY,
        RELATIESOORT VARCHAR2(80),
        VOOR_PROGRAMMA_ID VARCHAR2(255)
);

CREATE TABLE KP_MLNG (
    KP_MLNG_ID VARCHAR2(255) PRIMARY KEY,
    MAILING_ID VARCHAR2(255),
    MUSEUMRELATIE_ID VARCHAR2(255)
);

CREATE TABLE KP_MSMRLT (
    KP_MSMRLT_ID VARCHAR2(255) PRIMARY KEY,
    MUSEUMRELATIE_ID VARCHAR2(255),
    DOELGROEP_ID VARCHAR2(255)
);

ALTER TABLE MUSEUMRELATIE ADD CONSTRAINT FK_MUSEUMRELATIE_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- Generalization to RECHTSPERSOON

ALTER TABLE KP_MLNG ADD CONSTRAINT FK_KP_MLNG_1 FOREIGN KEY (MAILING_ID) REFERENCES MAILING (MAILING_ID);
-- MAILING (many-to-many junction, Connector_ID: 1120)

ALTER TABLE KP_MLNG ADD CONSTRAINT FK_KP_MLNG_2 FOREIGN KEY (MUSEUMRELATIE_ID) REFERENCES MUSEUMRELATIE (RECHTSPERSOON_ID);
-- MUSEUMRELATIE (many-to-many junction, Connector_ID: 1120)

ALTER TABLE KP_MSMRLT ADD CONSTRAINT FK_KP_MSMRLT_1 FOREIGN KEY (MUSEUMRELATIE_ID) REFERENCES MUSEUMRELATIE (RECHTSPERSOON_ID);
-- MUSEUMRELATIE (many-to-many junction, Connector_ID: 1124)

ALTER TABLE KP_MSMRLT ADD CONSTRAINT FK_KP_MSMRLT_2 FOREIGN KEY (DOELGROEP_ID) REFERENCES DOELGROEP (DOELGROEP_ID);
-- DOELGROEP (many-to-many junction, Connector_ID: 1124)

ALTER TABLE KP_PRGRMM ADD CONSTRAINT FK_KP_PRGRMM_1 FOREIGN KEY (PROGRAMMA_ID) REFERENCES PROGRAMMA (PROGRAMMA_ID);
-- PROGRAMMA (many-to-many junction, Connector_ID: 1107)

ALTER TABLE KP_PRGRMM ADD CONSTRAINT FK_KP_PRGRMM_2 FOREIGN KEY (PROGRAMMASOORT_ID) REFERENCES PROGRAMMASOORT (PROGRAMMASOORT_ID);
-- PROGRAMMASOORT (many-to-many junction, Connector_ID: 1107)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 1138)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_HEEFT FOREIGN KEY (HEEFT_RESERVERING_ID) REFERENCES RESERVERING (RESERVERING_ID);
-- HEEFT (1 to 0..*, Connector_ID: 1136)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_HEEFT_2 FOREIGN KEY (HEEFT_RONDLEIDING_ID) REFERENCES RONDLEIDING (RONDLEIDING_ID);
-- HEEFT (0..* to 0..1, Connector_ID: 1139)

ALTER TABLE ACTIVITEIT ADD CONSTRAINT FK_ACTIVITEIT_VAN_SOORT FOREIGN KEY (VAN_SOORT_ACTIVITEITSOORT_ID) REFERENCES ACTIVITEITSOORT (ACTIVITEITSOORT_ID);
-- VAN_SOORT (0..* to 1, Connector_ID: 1137)

ALTER TABLE DOELGROEP ADD CONSTRAINT FK_DOELGROEP_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_DOELGROEP_ID) REFERENCES DOELGROEP (DOELGROEP_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 1125)

ALTER TABLE MUSEUMRELATIE ADD CONSTRAINT FK_MUSEUMRELATIE_VOOR FOREIGN KEY (VOOR_PROGRAMMA_ID) REFERENCES PROGRAMMA (PROGRAMMA_ID);
-- VOOR (1 to 0..*, Connector_ID: 1115)

ALTER TABLE PRODUCTIE_EENHEID ADD CONSTRAINT FK_PRODUCTIE_EENHEID_BETREFT FOREIGN KEY (BETREFT_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1109)

ALTER TABLE PROGRAMMA ADD CONSTRAINT FK_PROGRAMMA_BESTAAT_UIT FOREIGN KEY (BESTAAT_UIT_ACTIVITEIT_ID) REFERENCES ACTIVITEIT (ACTIVITEIT_ID);
-- BESTAAT_UIT (1 to 0..*, Connector_ID: 1135)

ALTER TABLE PROGRAMMA ADD CONSTRAINT FK_PROGRAMMA_HEEFT FOREIGN KEY (HEEFT_KOSTENPLAATS_ID) REFERENCES KOSTENPLAATS (KOSTENPLAATS_ID);
-- HEEFT (0..* to 1, Connector_ID: 1106)

ALTER TABLE RESERVERING ADD CONSTRAINT FK_RESERVERING_BETREFT FOREIGN KEY (BETREFT_ZAAL_ID) REFERENCES ZAAL (ZAAL_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1104)

ALTER TABLE RESERVERING ADD CONSTRAINT FK_RESERVERING_BETREFT_2 FOREIGN KEY (BETREFT_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1105)

ALTER TABLE RESERVERING ADD CONSTRAINT FK_RESERVERING_BETREFT_3 FOREIGN KEY (BETREFT_PRODUCTIE_EENHEID_ID) REFERENCES PRODUCTIE_EENHEID (PRODUCTIE_EENHEID_ID);
-- BETREFT (0..* to 0..1, Connector_ID: 1108)

ALTER TABLE RONDLEIDING ADD CONSTRAINT FK_RONDLEIDING_VOOR FOREIGN KEY (VOOR_TENTOONSTELLING_ID) REFERENCES TENTOONSTELLING (TENTOONSTELLING_ID);
-- VOOR (0..* to 0..1, Connector_ID: 1102)

ALTER TABLE TENTOONSTELLING ADD CONSTRAINT FK_TENTOONSTELLING_ZAAL FOREIGN KEY (ZAAL_ID) REFERENCES ZAAL (ZAAL_ID);
-- unnamed (None to None, Connector_ID: 1099)

