CREATE TABLE [NUMMERAANDUIDING] (
    [NUMMERAANDUIDING_ID] INT PRIMARY KEY,
    [BEGINGELDIGHEID] VARCHAR(255),
    [DATUMEINDE] DATE,
    [DATUMINGANG] DATE,
    [DOCUMENTDATUM] DATE,
    [DOCUMENTNUMMER] INT,
    [EINDEGELDIGHEID] DATE,
    [GECONSTATEERD] BIT,
    [GEOMETRIE] GEOMETRY,
    [HUISLETTER] VARCHAR(255),
    [HUISNUMMER] VARCHAR(255),
    [HUISNUMMERTOEVOEGING] VARCHAR(255),
    [IDENTIFICATIE] VARCHAR(255),
    [POSTCODE] VARCHAR(255),
    [STATUS] VARCHAR(255),
    [TYPEADRESSEERBAAROBJECT] VARCHAR(255),
    [VERSIE] INT
);

CREATE TABLE [ADRESAANDUIDING] (
    [ADRESAANDUIDING_ID] INT PRIMARY KEY,
    [BAGID] VARCHAR(255),
    [GEMEENTENAAM] VARCHAR(80),
    [HUISLETTER] VARCHAR(255),
    [HUISNUMMER] VARCHAR(255),
    [HUISNUMMERTOEVOEGING] VARCHAR(255),
    [POSTCODE] VARCHAR(255),
    [STRAATNAAM] VARCHAR(200),
    [VERWIJST_NAAR_NUMMERAANDUIDING_ID] INT
);

ALTER TABLE [ADRESAANDUIDING] ADD CONSTRAINT FK_ADRESAANDUIDING_VERWIJST_NAAR FOREIGN KEY ([VERWIJST_NAAR_NUMMERAANDUIDING_ID]) REFERENCES [NUMMERAANDUIDING] ([NUMMERAANDUIDING_ID]);
-- VERWIJST_NAAR (0..1 to 0..1, Connector_ID: 2271)

