CREATE TABLE KAST (
    KAST_ID VARCHAR(255) PRIMARY KEY,
        AANTALDEUREN VARCHAR(255),
        ADRESTELECOM VARCHAR(255),
        BAGCODE VARCHAR(255),
        BREEDTE VARCHAR(255),
        EANCODE VARCHAR(50),
        FABRIKANT VARCHAR(255),
        HOOGTE VARCHAR(255),
        INBELGEGEVENS VARCHAR(50),
        INSTALLATEUR VARCHAR(255),
        JAARONDERHOUDUITGEVOERD VARCHAR(255),
        KLEUR VARCHAR(255),
        LENGTE VARCHAR(255),
        LEVERANCIER VARCHAR(255),
        TYPECOMMUNICATIE VARCHAR(255),
        TYPEFUNDERING VARCHAR(255),
        TYPESLOT VARCHAR(255),
        VERMOGEN VARCHAR(255)
);

CREATE TABLE PAAL (
    PAAL_ID VARCHAR(255) PRIMARY KEY,
        BREEDTE VARCHAR(255),
        DIAMETER VARCHAR(255),
        HOOGTE VARCHAR(255),
        JAARONDERHOUDUITGEVOERD VARCHAR(255),
        KWALITEITSNIVEAUACTUEEL VARCHAR(255),
        KWALITEITSNIVEAUGEWENST VARCHAR(255),
        LENGTE VARCHAR(255),
        LEVERANCIER VARCHAR(255),
        MATERIAAL VARCHAR(255),
        VORM VARCHAR(255)
);

CREATE TABLE VERKEERSTELLING (
    VERKEERSTELLING_ID VARCHAR(255) PRIMARY KEY,
        AANTAL INTEGER,
        TIJDTOT TIMESTAMP,
        TIJDVANAF TIMESTAMP
);

CREATE TABLE SENSOR (
    SENSOR_ID VARCHAR(255) PRIMARY KEY,
        AANLEGHOOGTE VARCHAR(255),
        ELEKTRAKAST VARCHAR(255),
        FREQUENTIEOMVORMER VARCHAR(255),
        GEGENEREERD_DOOR_VERKEERSTELLING_ID VARCHAR(255),
        HOOGTE VARCHAR(255),
        JAARONDERHOUDUITGEVOERD VARCHAR(255),
        LEVERANCIER VARCHAR(255),
        MEETPUNT VARCHAR(255),
        PLC VARCHAR(255)
);

CREATE TABLE VLOGINFO (
    VLOGINFO_ID VARCHAR(255) PRIMARY KEY,
        DETECTIEVERKEER INTEGER,
        EINDEGROEN DATE,
        GEGENEREERD_DOOR_KAST_ID VARCHAR(255),
        GEGENEREERD_DOOR_PAAL_ID VARCHAR(255),
        GEGENEREERD_DOOR_SENSOR_ID VARCHAR(255),
        SNELHEID INTEGER,
        STARTGROEN DATE,
        TIJDSTIP TIMESTAMP,
        VERKEERWILGROEN BOOLEAN,
        WACHTTIJD TIMESTAMP
);

ALTER TABLE SENSOR ADD CONSTRAINT FK_SENSOR_GEGENEREERD_DOOR FOREIGN KEY (GEGENEREERD_DOOR_VERKEERSTELLING_ID) REFERENCES VERKEERSTELLING (VERKEERSTELLING_ID);
-- GEGENEREERD_DOOR (1 to 0..*, Connector_ID: 1262)

ALTER TABLE VLOGINFO ADD CONSTRAINT FK_VLOGINFO_GEGENEREERD_DOOR FOREIGN KEY (GEGENEREERD_DOOR_KAST_ID) REFERENCES KAST (KAST_ID);
-- GEGENEREERD_DOOR (0..* to 0..1, Connector_ID: 1259)

ALTER TABLE VLOGINFO ADD CONSTRAINT FK_VLOGINFO_GEGENEREERD_DOOR_2 FOREIGN KEY (GEGENEREERD_DOOR_PAAL_ID) REFERENCES PAAL (PAAL_ID);
-- GEGENEREERD_DOOR (0..* to 0..1, Connector_ID: 1260)

ALTER TABLE VLOGINFO ADD CONSTRAINT FK_VLOGINFO_GEGENEREERD_DOOR_3 FOREIGN KEY (GEGENEREERD_DOOR_SENSOR_ID) REFERENCES SENSOR (SENSOR_ID);
-- GEGENEREERD_DOOR (0..* to 0..1, Connector_ID: 1261)

