CREATE TABLE [STROOIDAG] (
    [STROOIDAG_ID] INT PRIMARY KEY,
        [DATUM] DATE,
        [MAXIMUMTEMPERATUUR] VARCHAR(255),
        [MINIMUMTEMPERATUUR] VARCHAR(255),
        [TIJDMAXIMUMTEMPERATUUR] DATETIME2,
        [TIJDMINIMUMTEMPERATUUR] DATETIME2
);

CREATE TABLE [STROOIROUTE] (
    [STROOIROUTE_ID] INT PRIMARY KEY,
        [ROUTE] VARCHAR(255)
);

CREATE TABLE [STROOIROUTEUITVOERING] (
    [STROOIROUTEUITVOERING_ID] INT PRIMARY KEY,
        [GEPLANDEINDE] DATE,
        [GEPLANDSTART] DATE,
        [ROUTE] VARCHAR(255),
        [UITVOERING_OP_STROOIDAG_ID] INT,
        [VOLGENS_STROOIROUTE_ID] INT,
        [WERKELIJKEINDE] DATE,
        [WERKELIJKESTART] DATE
);

ALTER TABLE [STROOIROUTEUITVOERING] ADD CONSTRAINT FK_STROOIROUTEUITVOERING_UITVOERING_OP FOREIGN KEY ([UITVOERING_OP_STROOIDAG_ID]) REFERENCES [STROOIDAG] ([STROOIDAG_ID]);
-- UITVOERING_OP (0..* to 0..1, Connector_ID: 1265)

ALTER TABLE [STROOIROUTEUITVOERING] ADD CONSTRAINT FK_STROOIROUTEUITVOERING_VOLGENS FOREIGN KEY ([VOLGENS_STROOIROUTE_ID]) REFERENCES [STROOIROUTE] ([STROOIROUTE_ID]);
-- VOLGENS (0..* to 1, Connector_ID: 1264)

